### ISSUE TITLE
Get new IP address each time the ESP32 gets started/reboot

### ISSUE THREAD

**Issue by T94T** [espressif/arduino-esp32#1000]
### Hardware:
Board:							Various ESP32 modules
Core Installation/update date:			2.4.0
IDE name:							Arduino IDE 1.8.3
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
Everytime I startup/reboot my ESP32 I get a new IP address from the router (Fritz!Box Fon WLAN 7390).

### Sketch:
For simplicity I use the WiFiClient example.

**Comment by T94T** [comment]
By the way: My ESP8266 devices get the same IP addresses each time they connect.

**Comment by stickbreaker** [comment]
@T94T the DHCP server reuses IP based on MAC address, if the ESP32 is sending a different MAC it will receive a different IP.  Modify your test code to display the MAC address.  Verify that it is sending the same MAC when it asks for an IP.

Chuck.

**Comment by T94T** [comment]
This was my first thought also. But the ESP32 sends the same MAC address each time it connects.

**Comment by lrmoreno007** [comment]
Take a look at this:

https://en.avm.de/service/fritzbox/fritzbox-7390/knowledge-base/publication/show/1469_The-wireless-guest-access-cannot-be-used-to-access-the-internet/

Let's see what he puts in the field: "Valid for"

**Comment by stickbreaker** [comment]
@lrmoreno007 , he, @T94T is getting an IP.  Your weblink is solving an IP pool exhaustion because of extending lease time problem.  His problem is that every time his ESP32 reconnects it is given a different IP. I believe that this wandering IP is a problem because he is using the ESP32 as some type of a server that other devices access.  Whenever the ESP32 reconnects all of his other devices have to 'find it' at a new address.

Chuck.

**Comment by lrmoreno007** [comment]
Thanks for clarifying the problem, but it was already clear. My always assigned the same IP with the cited sketch, so the problem seems to be in the router configuration and I was trying to discard things.

**Comment by T94T** [comment]
I made a git pull on the arduino-esp32 today. Since then, the ESP32 gets the same IP address on each reboot.

**Comment by everslick** [comment]
@T94T  then you should consider closing this issue.
