### ISSUE TITLE
Add default 16MB partition to esp32wroverkit

### ISSUE THREAD

**Issue by tutotio** [espressif/arduino-esp32#10015]
### Related area

Board support

### Hardware specification

ESP32 Wrover Kit (all versions)

### Is your feature request related to a problem?

Default 8MB partition is defined for ESP32 Wrover Kit (all versions), but default 16MB partition is not defined

### Describe the solution you'd like

Add this lines to boards.txt file:

```
esp32wroverkit.menu.FlashSize.16M.build.partitions=default_16MB

esp32wroverkit.menu.PartitionScheme.default_16MB=16M with spiffs (6.25MB APP/3.43MB SPIFFS)
esp32wroverkit.menu.PartitionScheme.default_16MB.build.partitions=default_16MB
esp32wroverkit.menu.PartitionScheme.default_16MB.upload.maximum_size=6553600
```

Thank you :-)

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by P-R-O-C-H-Y** [comment]
Hi @tutotio, can you handle to open a PR with proposed change? :)
