### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by bjy5760163** [espressif/arduino-esp32#10053]
### Board

esp3232e

### Device Description

没连接任何外设

### Hardware Configuration

没连接

### Version

v3.0.3

### IDE Name

Arduino IDE

### Operating System

win10

### Flash frequency

40

### PSRAM enabled

no

### Upload speed

115200

### Description

使用webserver库搭建的网页服务器,从网页客户端发送数据到ESP32,会内存泄漏.我做的是网页遥控应用.40ms发送一次,很快内存就没了.使用2.0.17版本没有问题.

### Sketch

```cpp
void remoteControl() {  //1
  ykfxIn = atoi(esp32_server.arg("fx").c_str());
  ykymIn = atoi(esp32_server.arg("ym").c_str());
}
```

### Debug Message

```plain
没有
```

### Other Steps to Reproduce

使用网页一直发送 参数到esp32

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Hi @bjy5760163 . We accept issue reports only in English. Feel free to open a new issue in English
