### ISSUE TITLE
Cannot build due to "ERROR: Because project depends on idf (>=5.1.0,<5.2.0) which doesn't match"

### ISSUE THREAD

**Issue by plystdr** [espressif/arduino-esp32#10055]
### Board

Custom esp32-s3 board

### Device Description

Custom board.

### Hardware Configuration

Multiple sensors.

### Version

latest master (checkout manually)

### IDE Name

PlatformIO VSCode

### Operating System

Windows 11

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

Cannot make platformio build the project. I even tried skip version checking but nothing works...

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
lib_deps = 
	https://github.com/joltwallet/esp_littlefs.git
	ayushsharma82/ElegantOTA@^3.1.2

[env:test-project]
platform = https://github.com/platformio/platform-espressif32.git
platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#master
framework = espidf, arduino
board = test-board
board_build.mcu = esp32s3
upload_protocol = esptool
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = partition_scheme.csv
board_build.filesystem = littlefs
board_upload.offset_address = 0x670000
lib_deps = 
	${common.lib_deps}
extra_scripts = 
	tasks.py
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DBOARD_HAS_PSRAM
	-DARDUINO_ESP32S3_DEV
	-DCONFIG_SPIRAM_USE
	-mfix-esp32-psram-cache-issue
	-w
	-Wno-unused-variable
	-Wno-unused-function
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-DARDUINO_SKIP_IDF_VERSION_CHECK=1

### Sketch

```cpp
Not even start compiling.
```

### Debug Message

```plain
Processing projecttest (platform: https://github.com/platformio/platform-espressif32.git; framework: espidf, arduino; board: testboard)
--------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION:
PLATFORM: Espressif 32 (6.7.0+sha.68ad40f) > Espressif ESP32-S3-N8-R2 (8 MB QD, 2MB PSRAM)
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.0.3+sha.690bdb5
 - framework-espidf @ 3.40407.240606 (4.4.7)
 - tool-cmake @ 3.16.4
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - tool-idf @ 1.0.1
 - tool-mconf @ 1.4060000.20190628 (406.0.0)
 - tool-ninja @ 1.9.0
 - tool-openocd-esp32 @ 2.1100.20220706 (11.0)
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0)
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Warning! Arduino framework as an ESP-IDF component doesn't handle the `variant` field! The default `esp32` variant will be used.
Reading CMake configuration...
-- Building ESP-IDF components for target esp32s3
Manifest files have changed, solving dependencies.

...........NOTICE: Skipping optional dependency: espressif/cbor

.......NOTICE: Skipping optional dependency: espressif/mdns

....NOTICE: Skipping optional dependency: espressif/jsmn

...........-- Configuring incomplete, errors occurred!
See also "D:/firmware/projecttest/.pio/build/projecttest/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/usertest/.platformio/packages/framework-espidf/tools/cmake/build.cmake:463 (message):
  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  WARNING: Component "idf" not found

  ERROR: Because project depends on idf (>=5.1.0,<5.2.0) which doesn't match
  any versions, version solving failed.

Call Stack (most recent call first):
  C:/Users/usertest/.platformio/packages/framework-espidf/tools/cmake/project.cmake:476 (idf_build_process)
  CMakeLists.txt:7 (project)
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
cc @Jason2866 

Official Platformio does not support Arduino v3. There are other ways to get this going with PlatformIO supported by the community

**Comment by Jason2866** [comment]
@plystdr  You can use the community version which supports https://github.com/pioarduino/platform-espressif32

```
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
board = ...
...
```

**Comment by VojtechBartoska** [comment]
PlatfromIO issue, solution is proposed above. Marking as wontfix at our end.

Can I consider this as answered @plystdr? thanks!

**Comment by WebDust21** [comment]
> @plystdr You can use the community version which supports https://github.com/pioarduino/platform-espressif32 See examples folders to see how Arduino as component setup has to be done
> 
> ```
> platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
> board = ...
> ...
> ```

@Jason2866  You're a hero.
Got myself stuck up a tree with no way down after finding an issue deep in ESP-IDF (using Arduino-ESP32), only to find actually trying to use ESP-IDF a very probable-cause reason that so many programmers are completely bald...

Your repo and suggestions actually WORK, thank you!

Now I just need to figure out how to get a modified repository (based on the proper ESP-IDF version) linked into PlatformIO with my corrections in it to verify that the issue is fixed...

(yes, the corrections DO work...now I'll have to PR the two lines of changed code deeeeeep in the Bluedroid libraries...)

**Comment by Jason2866** [comment]
@WebDust21 To use your own IDF version is easy. Fork https://github.com/pioarduino/esp-idf/tree/release/v5.1
Do your changes there. Create a zip including the git submodules. Easiest to do is via this github actions https://github.com/pioarduino/esp-idf/blob/release/v5.1/.github/workflows/release_zips.yml It will create the zip and does a release in your fork. Fork https://github.com/pioarduino/platform-espressif32 and change this entry pointing to your IDF https://github.com/pioarduino/platform-espressif32/blob/18cb216bea0ffb63390d035d76451af9d8c0435d/platform.json#L48
Use your platform with
```
platform = https://github.com/webdust21/platform-espressif32.git#develop
```

**Comment by CompunixSupport** [comment]
Hello @Jason2866. I was fighting the same issue as at very top and found this article. My project is PlatformIO with ESP-IDF and Arduino as a Component, to be able to encrypt the flash and use secure bootloader.

I have modified my platformio.ini to:
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip  
board = esp32dev
framework = espidf, arduino
monitor_speed = 115200

And the installation commenced, but ended with strange errors:

![Image](https://github.com/user-attachments/assets/b61c5b78-97d2-4707-955d-4df789cf45db)

Also when building after clearing, it is complaining about: ModuleNotFoundError: No module named 'rich'

Please advise.
Thank you,
Dalibor

**Comment by Jason2866** [comment]
@CompunixSupport  kconfig has been updated and needs the python module rich.
It is fixed in development branch already will be in next release.

To solve use branch develop:

```
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32dev
framework = espidf, arduino
monitor_speed = 115200
```

**Comment by CompunixSupport** [comment]
Thank you, Jason,

I got little further but not there yet, now I’m getting:
Error copying tool package file: [Errno 2] No such file or directory: 'C:\\Users\\DaliborSimacek\\.platformio\\tools\\tool-cmake\\package.json'
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\tool-cmake<file:///C:/Users/DaliborSimacek/.platformio/tools/tool-cmake>
FileNotFoundError: Traceback (most recent call last):
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\run\cli.py", line 147, in cli
    process_env(
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\run\cli.py", line 210, in process_env
    ).process()
      ^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\run\processor.py", line 81, in process
    install_project_env_dependencies(
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\package\commands\install.py", line 132, in install_project_env_dependencies
    _install_project_env_platform(project_env, options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\package\commands\install.py", line 149, in _install_project_env_platform
    PlatformPackageManager().install(
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\package\manager\platform.py", line 60, in install
    p.configure_project_packages(project_env, project_targets)
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\platform\base.py", line 185, in configure_project_packages
    self.configure_default_packages(options, targets or [])
  File "C:\Users\DaliborSimacek\.platformio\platforms\espressif32\platform.py", line 184, in configure_default_packages
    install_tool(package)
  File "C:\Users\DaliborSimacek\.platformio\platforms\espressif32\platform.py", line 93, in install_tool
    pm.install(tl_path)
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 47, in install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 97, in _install
    pkg = self.install_from_uri(spec.uri, spec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\package\manager\_install.py", line 187, in install_from_uri
    shutil.copytree(_uri, tmp_dir, symlinks=True)
  File "C:\Users\DaliborSimacek\.platformio\python3\Lib\shutil.py", line 559, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\DaliborSimacek\\.platformio\\tools\\tool-cmake'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

Thank you,

Dalibor Simacek
Compunix, LLC.
23335 N. 18th Dr. Unit 138
Phoenix, AZ 85027
Office:    (623) 434-2121
Website: http://www.compunix.us<http://www.compunix.us/>
***@***.***
***@***.***
________________________________
This message (including any attachments) contains confidential information intended for a specific individual and purpose and is proprietary and protected by law. If you are not the intended recipient, you should inform the sender immediately and delete this message and are hereby notified that any reading, copying, disclosure or distribution of this message, or the taking of any action based on it, is strictly prohibited.

**Comment by CompunixSupport** [comment]
One possible issue is that it is looking for various tools in  .platformio/tool folder (nonexistent), but installing them to .platformio/packages. I have tried to duplicate them in the created .platformio/tool. Not sure how to correct it. Please advise.

set following in platformio.ini:
platform_packages =
    espressif/toolchain-xtensa-esp32
    platformio/tool-ninja@1.9.0
    platformio/tool-mklittlefs@^1.203.210628
    platformio/tool-cmake@^3.30.2

Upon VScode start it checks for the enviroment and get following error:
Resolving esp32dev dependencies...
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\toolchain-xtensa-esp-elf
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\tool-esp-rom-elfs
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20241119.zip
Unpacking 0% 10% 20%
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
Tool Manager: Installing platformio/tool-mklittlefs @ ^1.203.210628
Unpacking 0% 10% 20%
Tool Manager: tool-mklittlefs@1.203.210628 has been installed!
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/esp-rom-elfs-20241011.zip
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Tool Manager: Installing platformio/tool-ninja @ 1.9.0
Unpacking 0% 10% 20%
Tool Manager: tool-ninja@1.9.0 has been installed!
Already up-to-date.
Updating metadata for the vscode IDE...
UserSideException: Processing esp32dev (platform: https://github.com/pioarduino/platform-espressif32.git#develop; board: esp32dev; framework: espidf, arduino)
--------------------------------------------------------------------------------
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\toolchain-xtensa-esp-elf
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
Wrong version for tool-ninja. Installing needed version...
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\tool-esp-rom-elfs
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20241119.zip
Unpacking 0% 10% 20%
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
Tool Manager: Installing platformio/tool-mklittlefs @ ^1.203.210628
Unpacking 0% 10% 20%
Tool Manager: tool-mklittlefs@1.203.210628 has been installed!
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/esp-rom-elfs-20241011.zip
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Tool Manager: Installing platformio/tool-ninja @ 1.9.0
Unpacking 0% 10% 20%
Tool Manager: tool-ninja@1.9.0 has been installed!
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\toolchain-xtensa-esp-elf
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
Wrong version for tool-ninja. Installing needed version...
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\tool-esp-rom-elfs
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\toolchain-xtensa-esp-elf
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\tool-esp-rom-elfs
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (54.3.20+develop.sha.17b022c) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 16MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.2.0 
 - framework-arduinoespressif32-libs @ 5.4.0+sha.aed8bdc8dd 
 - framework-espidf @ 3.50401.0 (5.4.1) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.11 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
WARNING: Ignoring invalid distribution ~ip (C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages)
TypeError: _path_isdir: path should be string, bytes, os.PathLike or integer, not NoneType:
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\builder\main.py", line 173:
    env.SConscript("$BUILD_SCRIPT")
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 620:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\DaliborSimacek\.platformio\platforms\espressif32\builder\main.py", line 399:
    target_elf = env.BuildProgram()
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Util\envs.py", line 252:
    return self.method(*nargs, **kwargs)
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\builder\tools\piobuild.py", line 62:
    env.ProcessProgramDeps()
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Util\envs.py", line 252:
    return self.method(*nargs, **kwargs)
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\builder\tools\piobuild.py", line 142:
    env.BuildFrameworks(env.get("PIOFRAMEWORK"))
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Util\envs.py", line 252:
    return self.method(*nargs, **kwargs)
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\builder\tools\piobuild.py", line 352:
    SConscript(env.GetFrameworkScript(name), exports="env")
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 684:
    return method(*args, **kw)
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 620:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\DaliborSimacek\.platformio\platforms\espressif32\builder\frameworks\espidf.py", line 155:
    assert os.path.isdir(TOOLCHAIN_DIR)
========================= [FAILED] Took 40.75 seconds =========================

**Comment by Jason2866** [comment]
Delete in folder `.platformio/packages` everything just do not delete the folder `pyenv`
Try again. Now all will  be installed correctly.

**Comment by CompunixSupport** [comment]
One note, I do not have pyenv folder (only .cache, packages, penv, platforms, python3), this is how it looks after the re-installation:

![Image](https://github.com/user-attachments/assets/ad8be868-fdde-4a9f-a98a-178d58fc5e96)

The error reported is FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\DaliborSimacek\\.platformio\\tools\\toolchain-xtensa-esp-elf'

**Again, I do not have the .platformio\\tools folder and cannot find where it is referenced**. 

When copied all from packages to a created folder tools, the result shows:
Resolving esp32dev dependencies...
Wrong version for tool-esp-rom-elfs. Installing needed version...
Tool Manager: Installing platformio/tool-mklittlefs @ ^1.203.210628
Unpacking 0% 10% 20%
Tool Manager: tool-mklittlefs@1.203.210628 has been installed!
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/esp-rom-elfs-20241011.zip
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Tool Manager: Installing platformio/tool-ninja @ 1.9.0
Unpacking 0% 10% 20%
Tool Manager: tool-ninja@1.9.0 has been installed!
Already up-to-date.
Updating metadata for the vscode IDE...
UserSideException: Processing esp32dev (platform: https://github.com/pioarduino/platform-espressif32.git#develop; board: esp32dev; framework: espidf, arduino)
--------------------------------------------------------------------------------
Wrong version for tool-ninja. Installing needed version...
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\tool-esp-rom-elfs
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Tool Manager: Installing platformio/tool-mklittlefs @ ^1.203.210628
Unpacking 0% 10% 20%
Tool Manager: tool-mklittlefs@1.203.210628 has been installed!
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/esp-rom-elfs-20241011.zip
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Tool Manager: Installing platformio/tool-ninja @ 1.9.0
Unpacking 0% 10% 20%
Tool Manager: tool-ninja@1.9.0 has been installed!
Wrong version for tool-ninja. Installing needed version...
Tool Manager: Installing file://C:\Users\DaliborSimacek\.platformio\tools\tool-esp-rom-elfs
Tool Manager: tool-esp-rom-elfs@2024.10.11 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (54.3.20+develop.sha.17b022c) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 16MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.2.0 
 - framework-arduinoespressif32-libs @ 5.4.0+sha.aed8bdc8dd 
 - framework-espidf @ 3.50401.0 (5.4.1) 
 - tool-cmake @ 3.30.2 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 4.8.11 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20241119 
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
WARNING: Ignoring invalid distribution ~ip (C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages)
Warning! Arduino framework as an ESP-IDF component doesn't handle the `variant` field! The default `esp32` variant will be used.
Reading CMake configuration...
TypeError: sequence item 1: expected str instance, NoneType found:
  File "C:\Users\DaliborSimacek\.platformio\penv\Lib\site-packages\platformio\builder\main.py", line 173:
    env.SConscript("$BUILD_SCRIPT")
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 620:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\DaliborSimacek\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)

**Comment by Jason2866** [comment]
`penv` is the python environment folder, delete all others folders in folder `.platformio`

**Comment by CompunixSupport** [comment]
As previously mentioned, same result: FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\DaliborSimacek\\.platformio\\tools\\toolchain-xtensa-esp-elf' looking into non-existing "tools" folder and I cannot find anywhere the setting. It happens after the change to platform = https://github.com/pioarduino/platform-espressif32.git#develop, before it looks for .platformio\packages I could see the settings for.
If I create a simple project with arduino component (only WiFi and Wire components) it works. Then adding library NTPClient will cause the issue from the top of the page. After change to platform = https://github.com/pioarduino/platform-espressif32.git#develop, and deleting the folders as you suggested it starts to look for the .platformio/tools folder, which does not get created.

**Comment by Jason2866** [comment]
@CompunixSupport Do you have Internet access, it is mandatory. Can't reproduce the issue. All examples do work in CI for Linux, Mac and Windows. Out of Ideas. Can be a Windows path length limit. Put your project in C:\prj and try again.
