### ISSUE TITLE
WiFiClientSecure?

### ISSUE THREAD

**Issue by forthlightning** [espressif/arduino-esp32#101]
Any timeline on when we can expect TLS-secured wifi client?

A service I am using only accepts secured connections.

Thanks for the hard work and speedy replies!

**Comment by tijnkooijmans** [comment]
I'm also waiting for this feature before I will be able to use the SDK for my product.

**Comment by copercini** [comment]
+1

**Comment by copercini** [comment]
It was merged now!

**Comment by forthlightning** [comment]
I saw all the steps you went through to get it merged! I appreciate the effort and will test it out on monday!
