### ISSUE TITLE
    arduino-esp32/docs/en/api  /adc.rst analogReadMillivolts should be analogReadMilliVolts with capital V

### ISSUE THREAD

**Issue by moeburn** [espressif/arduino-esp32#10124]
### Board

ESP32C3

### Device Description

ESP32C3 Dev Board

### Hardware Configuration

N/A

### Version

v3.0.4

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

80mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

![image](https://github.com/user-attachments/assets/b0df47c9-8869-4c2b-b559-0b27cbd7b2b5)

The second one with the capital V is correct.

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
Thanks @moeburn for reporting!
