### ISSUE TITLE
esptool.py needs updating to v2.2

### ISSUE THREAD

**Issue by kosso** [espressif/arduino-esp32#1013]
Latest release is 2.2 from https://github.com/espressif/esptool 

Current version here is 2.1

Version 2.2 solves some "Timed out waiting for packet header" errors for me on a 'WeMos Lolin32'
Version 2.2 is the current version in `pip`

**Comment by garyocampo** [comment]
is there any way we can update it manually? ive bought a feather huzzah with the hopes that it wouldnt be such a pain.
 when i upload on visual studio  i get this error
`esptool.py v2.1
Connecting....

A fatal error occurred: Timed out waiting for packet header
*** [upload] Error 2`

**Comment by lbernstone** [comment]
Can you close this issue? esptool is now at 2.3.1 in master.

**Comment by copercini** [comment]
Closed as solved
