### ISSUE TITLE
non-BLE bluetooth on arduino?

### ISSUE THREAD

**Issue by jumpjack** [espressif/arduino-esp32#1017]
I installed ESPBluFi on my tablet but it does not see any device, nor my phones, neither my ESP32...
is ESPBlufi supposed to work with standard Bluetooth or BLE?
Does ESP32 support also "old fashioned" bluetooth or just BLE?

**Comment by copercini** [comment]
Take a look here: https://github.com/espressif/arduino-esp32/tree/master/libraries/BluetoothSerial
=)
