### ISSUE TITLE
VS Code Intellisense breaks

### ISSUE THREAD

**Issue by khryssmar** [espressif/arduino-esp32#10189]
### Board

ESP32-WROOM-32D

### Device Description

N/A

### Hardware Configuration

N/A

### Version

v3.0.4

### IDE Name

Arduino

### Operating System

Windows 10

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

921600

### Description

I dont know if the issue is for this repo but the VS  Code intellisense breaks when using the 3.0.4 version. I tried it in 2.0.17 and it is just fine. Seems like the paths the got included in the JSON file is not nearly the same number as that from the 2.0.17.

from 2.0.17:
![image](https://github.com/user-attachments/assets/424df0ba-59b6-418f-922c-954a4d84b171)

from 3.0.4:
![2](https://github.com/user-attachments/assets/e1198ff6-2165-4df4-9156-515b744955df)
![1](https://github.com/user-attachments/assets/958dd1f8-43f9-4b69-bd50-2f220eb973b2)

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment]
Since *.ino files are not c nor c++ intellisense does not work reliable. This is a known limitation of VSC. Can only be solved by switching of Intellisense.

**Comment by khryssmar** [comment]
*.ino is treated as cpp. Also, it Intellisense breaks due to some include files that are not added to the include list.
![image](https://github.com/user-attachments/assets/377bb2d8-57fe-4463-a909-f099e41c7292)

Is there any reason why the previous version has the complete include list and newer version is not?

**Comment by Jason2866** [comment]
This github is for issues regarding Arduino code. For issues and questions around VSC wrong place.
