### ISSUE TITLE
Installing Manually to Arduino IDE

### ISSUE THREAD

**Issue by aliajboy** [espressif/arduino-esp32#10187]
### Board

ESP-32 Dev

### Version

v3.0.4

### IDE Name

Arduino IDE

### Operating System

Windows 11

Hi,
I just need help with installing it on Arduino IDE 2.3.2. It takes hours to install it. now I waited almost 2 hours and it's going really slow. I can download it manually from here where you published it in a ~200MB zip file. How can I install it manually so I don't wait for arduino IDE?

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
Manual installation will need some network connection and has a lot to download (~400MB).
You can follow the [manual install instructions](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html#windows-manual-installation).  This downloads assets into staging directories, so if something seems to be completely stuck, you can cancel it and it will only restart that piece of the download.
