### ISSUE TITLE
Path from PC used to compile code included in compiled firmware WHY?

### ISSUE THREAD

**Issue by JustTryingToGetSomeWorkDone** [espressif/arduino-esp32#10227]
### Board

ESP32-C3-mini-1 on custom prototype board

### Device Description

connected and in use:
128x32 OLED with SSD1306 via i2c on pins 0 and 1
1 momentary switch on pin 4

connected but unused:
DS3231 module is powered and connected to i2c, but currently unused
there is a mosfet circuit on the board that is currently unused on pin 10

### Hardware Configuration

USB CDC is connected and being used for serial communication and programming

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE 2.3.2 with ESP32 core 3.0.4

### Operating System

Windows 10

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

I'm making 2 devices. One is an LED dimmer, the other is a controller for the dimmer. I'm attempting to use ESPNOW to communicate via unencrypted broadcasts. This is very much a work in progress with the aim being get something sending messages, change the message, then upgrade the interface and functionality incrementally. I started with the example code: ESP_NOW Broadcast Master, to which I have added some libraries for a button I use to navigate on this early prototype, and an OLED which I plan to eventually upgrade to something else. I'm currently at the change the message stage on the controller device. Previous tests at sending the example code messages worked fine. Even when I swapped out all the serial prints to display prints, no problem.

I'm attempting to transmit a struct that contains information about whether or not the LEDs are connected, their duty cycles in % of 100, stuff like that. I'm just beginning this step, so after a little hassle with pointers and casting to an unsigned integer, it compiles and looks ok. All I want it to do at this point is when I click a button, the value of the duty cycle should be incremented by 10 and displayed. If it goes over 100, it loops back to 0. Double click and it sends the message. However, from the get go it displays things I do not expect. Other parts of the UI show up in the place of the duty cycle which should be an int. If I click, it shows a frowny face, which I'm quite sure isn't in my code. If I click again and again and again, it starts showing the path to the wire.h library on the PC that I used to compile the firmware: /user/blah/AppData/Local/Arduino15/Package/esp32... something along those lines. It's like it's scrolling when it should be incrementing the initial value of 5 by 10.

So MY main issue and question is: why on earth is it including my PC paths in the firmware? I get that this seems like a buffer issue or memory/stack issue. I'll figure that part out, but having private data included in the compiled and flashed firmware seems like a HUGE privacy issue. Is this the fault of the Arduino IDE or the ESP32 core?

### Sketch

```cpp
#define DEBUGCODE 

#ifdef DEBUGCODE
#include <Arduino.h>
#endif

#include <Wire.h> // regular wire library for esp32
#include <Adafruit_SSD1306.h> // library for the oled I'm using
#include <Adafruit_GFX.h> // library for the oled I'm using
#include <BfButton.h> // https://github.com/mickey9801/ButtonFever 
#include <Preferences.h> // standard esp NVS saving library
#include <DS3231-RTC.h> //  https://github.com/hasenradball/DS3231-RTC
#include "ESP32_NOW.h"
#include "WiFi.h"

#include <esp_mac.h>  // For the MAC2STR and MACSTR macros

/* Definitions */
#define DS3231_I2C_ADDRESS 0x68 // 0x68 is the RTC address
#define SCREEN_WIDTH 128     // OLED display width, in pixels
#define SCREEN_HEIGHT 32     // OLED display height, in pixels
#define OLED_RESET -1        // Reset pin # (or -1 if sharing Arduino reset pin)
#define SCREEN_ADDRESS 0x3C  ///< See datasheet for Address; 0x3D for 128x64, 0x3C for 128x32
#define ESPNOW_WIFI_CHANNEL 6

/* Classes */

// Creating a new class that inherits from the ESP_NOW_Peer class is required.

class ESP_NOW_Broadcast_Peer : public ESP_NOW_Peer {
public:
  // Constructor of the class using the broadcast address
  ESP_NOW_Broadcast_Peer(uint8_t channel, wifi_interface_t iface, const uint8_t *lmk) : ESP_NOW_Peer(ESP_NOW.BROADCAST_ADDR, channel, iface, lmk) {}

  // Destructor of the class
  ~ESP_NOW_Broadcast_Peer() {
    remove();
  }

  // Function to properly initialize the ESP-NOW and register the broadcast peer
  bool begin() {
    if (!ESP_NOW.begin() || !add()) {
      log_e("Failed to initialize ESP-NOW or register the broadcast peer");
      return false;
    }
    return true;
  }

  // Function to send a message to all devices within the network
  bool send_message(const uint8_t *data, size_t len) {
    if (!send(data, len)) {
      log_e("Failed to broadcast message");
      return false;
    }
    return true;
  }
};

/* Global Variables */

uint32_t msg_count = 0;
const unsigned int btnPin = 4;

int mainMenuSelect = 1;

typedef struct struct_message {  
  int ID;                        
  bool LED1;  
  bool LED2;
  bool LED3;
  bool LED4;
  int LED1duty;  
  int LED2duty;
  int LED3duty;
  int LED4duty;
  bool factoryReset;  
} __attribute__((packed)) struct_message;

struct_message myMessage; 


/* Objects */

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);
BfButton btn(BfButton::STANDALONE_DIGITAL, btnPin, true, LOW);  // using internal pullups

// Create a broadcast peer object
ESP_NOW_Broadcast_Peer broadcast_peer(ESPNOW_WIFI_CHANNEL, WIFI_IF_STA, NULL);

/* My Functions */
void doMenuAction(int a){
  if (a==1){ // dim LED 1
    myMessage.LED1duty = myMessage.LED1duty+10;
    if(myMessage.LED1duty > 100){myMessage.LED1duty =0;}
  }
  if (a==2){ // dim LED 2
    myMessage.LED2duty = myMessage.LED2duty+10;
    if(myMessage.LED2duty > 100){myMessage.LED2duty =0;}
  }
  if (a==3){ // dim LED 3
    myMessage.LED3duty = myMessage.LED3duty+10;
    if(myMessage.LED3duty > 100){myMessage.LED3duty =0;}
  }
  if (a==4){ // dim LED 4
    myMessage.LED4duty = myMessage.LED4duty+10;
    if(myMessage.LED4duty > 100){myMessage.LED4duty =0;}
  }
  
}

void pressHandler(BfButton *btn, BfButton::press_pattern_t pattern) {
  switch (pattern) {  
    case BfButton::SINGLE_PRESS: {
      doMenuAction(mainMenuSelect);
      break;}

    case BfButton::DOUBLE_PRESS: {
      // Broadcast a message to all devices within the network
      char data[32];
      snprintf(data, sizeof(data), "Hello, World! #%lu", msg_count++);

      display.printf("Broadcasting message: %s\n", data);
      display.display();

      esp_err_t result = broadcast_peer.send_message((uint8_t *) &myMessage, sizeof(myMessage));
  
      if (result == ESP_OK) {
        Serial.println("Message sent successfully");
      } else {
        Serial.println("Error sending the message");
      }
      break;}

    case BfButton::LONG_PRESS: {
      mainMenuSelect++;
      if(mainMenuSelect > 4){mainMenuSelect=1;}

      break;}
  }
}

void OLED(){
    int boxX = 64;
    int boxY = 10;
    int colAx = 0;
    int colBx = 64;
    int row1y = 1;
    int row2y = 11;
    int row3y = 21;
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  
  if (mainMenuSelect == 1) {
        display.fillRect(colAx, row1y, boxX, boxY, SSD1306_WHITE); 
        display.setTextColor(SSD1306_BLACK);
      } else {
        display.fillRect(colAx, row1y, boxX, boxY, SSD1306_BLACK);
        display.setTextColor(SSD1306_WHITE);
      }
  display.setCursor(colAx, row1y);
  display.print("#1: ");
  display.print(myMessage.LED1duty + "%");
  
  if (mainMenuSelect == 2) {
        display.fillRect(colBx, row1y, boxX, boxY, SSD1306_WHITE);  
        display.setTextColor(SSD1306_BLACK);
      } else {
        display.fillRect(colBx, row1y, boxX, boxY, SSD1306_BLACK);
        display.setTextColor(SSD1306_WHITE);
      }
  display.setCursor(colBx, row1y);
  display.print("#2: ");
  display.print(myMessage.LED2duty + "%");

  if (mainMenuSelect == 3) {
        display.fillRect(colAx, row2y, boxX, boxY, SSD1306_WHITE);  
        display.setTextColor(SSD1306_BLACK);
      } else {
        display.fillRect(colAx, row2y, boxX, boxY, SSD1306_BLACK);
        display.setTextColor(SSD1306_WHITE);
      }
  display.setCursor(colAx, row2y);
  display.print("#3: ");
  display.print(myMessage.LED3duty + "%");

  if (mainMenuSelect == 4) {
        display.fillRect(colBx, row2y, boxX, boxY, SSD1306_WHITE);  
        display.setTextColor(SSD1306_BLACK);
      } else {
        display.fillRect(colBx, row2y, boxX, boxY, SSD1306_BLACK);
        display.setTextColor(SSD1306_WHITE);
      }
  display.setCursor(colBx, row2y);
  display.print("#4: ");
  display.print(myMessage.LED4duty + "%");
  display.display();
  
}
/* Main */

void setup() {
  Serial.begin(115200);
  while (!Serial) {
    delay(10);
  }
  
  // init the display
  Wire.begin(1, 0);  // join i2c bus (address optional for master)
  if (!display.begin(SSD1306_SWITCHCAPVCC, SCREEN_ADDRESS)) {
    for (;;)
      ;  
  }

    display.clearDisplay();
    display.setTextSize(1);
    display.setTextColor(SSD1306_WHITE);
    display.setCursor(0, 0);
    display.display();


  // setup the button
  btn.onPress(pressHandler)
    .onDoublePress(pressHandler)      // default timeout
    .onPressFor(pressHandler, 1250);  // custom timeout for 1.25 second

  // Initialize the Wi-Fi module
  WiFi.mode(WIFI_STA);
  WiFi.setChannel(ESPNOW_WIFI_CHANNEL);
  while (!WiFi.STA.started()) {
    delay(100);
  }
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(0, 0);
  display.println("ESP-NOW Example - Broadcast Master");
  display.println("Wi-Fi parameters:");
  display.println("  Mode: STA");
  delay(1000);
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(0, 0);
  display.println("  MAC Address: " + WiFi.macAddress());
  display.println("  Channel: " + ESPNOW_WIFI_CHANNEL);
  display.display();
  delay(1000);

  // Register the broadcast peer
  if (!broadcast_peer.begin()) {
    display.clearDisplay();
    display.setTextSize(1);
    display.setTextColor(SSD1306_WHITE);
    display.setCursor(0, 0);
    display.println("Failed to initialize broadcast peer");
    display.println("Reebooting in 5 seconds...");
    display.display();
    delay(5000);
    ESP.restart();
  }
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(0, 0);
  display.println("Setup complete. Broadcasting messages every button press.");
  display.display();
  delay(1000);
///////////////////////////////initial values for message struct////////////////////////////
  myMessage.ID = 1;
  myMessage.LED1 = true;
  myMessage.LED2 = false;
  myMessage.LED3 = true;
  myMessage.LED4 = false;
  myMessage.LED1duty = 5;
  myMessage.LED2duty = 5;
  myMessage.LED3duty = 5;
  myMessage.LED4duty = 5;
  myMessage.factoryReset = false;

}

void loop() {
  btn.read();
  OLED();
}
```

### Debug Message

```plain
No error messages
```

### Other Steps to Reproduce

I don't have any other information about reproducing this issue. I suppose you should know if you're including local PC paths in compiled firmware that does not require such information.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by JustTryingToGetSomeWorkDone** [comment]
Well, never look behind the curtain, I guess. I started to wonder if this was due to my error reporting settings or something, so I set the Core Debug Level to None, recompiled, and checked the resulting .elf in Notepad++. The file is riddled with paths from my computer right there in plain text. Why is this necessary? Which settings can I deactivate to make sure this type of information doesn't get sent to the world if I decide to share my work?

The fact that I've never heard about this is what I find the most disturbing. I'm surely not the first to look inside an elf file. Should there not at least be some warning that this can happen.

Disabling the JTAG debugger has no effect either. I'm starting to think there's so way to remove this from the file. Considering the ESP will never need this information, it seems like a huge breach of privacy to me. If it hadn't popped up on my OLED I would have never even checked.

**Comment by JustTryingToGetSomeWorkDone** [comment]
I have determined this is the fault of the Arduino IDE. Compiling the basic blink example sketch on non-ESP boards results in the same behavior. Closing as it does not belong here. I apologize for jumping the gun.

**Comment by me-no-dev** [comment]
This is not dues to the IDE, but due to GCC. When you compile code, such information is included in the result in order to be able to trace code and errors. When we print logs from out Arduino, we strip that part of paths and do not print it, but if you do something like `Serial.println(__FILE__);` you will get the full path of the file you added that line into.
