### ISSUE TITLE
spiclass在同一项目内出现了不同指向，是系统bug吗？

### ISSUE THREAD

**Issue by StarCompute** [espressif/arduino-esp32#10263]
### Board

esp32 dev

### Device Description

一块 32 nodemu,连接了一块自制I2S功放板，一块自制tf 板；

### Hardware Configuration

#define SD_CS          5
#define SPI_MOSI      23
#define SPI_MISO      19
#define SPI_SCK       18
#define I2S_DOUT      21
#define I2S_BCLK      32
#define I2S_LRC       33

### Version

latest development Release Candidate (RC-X)

### IDE Name

platformio

### Operating System

win 10

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

在同一个platformio，同一个项目下，发觉：
`    SPIClass spi = SPIClass(HSPI);
  spi.begin(18 /* SCK */, 19 /* MISO */, 23 /* MOSI */, 5 /* SS */);
  if (!SD.begin(5 /* SS */, spi, 120000000,"/cdcard")) {
    Serial.println("Card Mount Failed");
    return;
  }`
和
`    pinMode(SD_CS, OUTPUT);      digitalWrite(SD_CS, HIGH);
    SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
    SPI.setFrequency(1000000);
    Serial.begin(115200);
    SD.begin(SD_CS);`
中的spiclass一个指向了esp8266内，另外一个指向了esp32中。
如果使用第一段代码，spiclass指向了esp32库；如果使用第二段代码指向了esp8266库
前者在loop中调用esp8266audio或者audioi2s 的loop方法都会导致单片机重启，后者工作正常，能够正常播放mp3;
通过按住ctrl+鼠标，有分别不同的跳转；

如果直接从SD.begin跳转进去；
bool SDFS::begin(uint8_t ssPin, SPIClass &spi, uint32_t frequency, const char * mountpoint, uint8_t max_files, bool format_if_empty)
中的spiclass指向到了8266库上。

详细情况可以参看： 
[https://blog.csdn.net/platform/article/details/141715311](url)

### Sketch

```cpp
#include <Arduino.h>
#include <SD.h>
#include "Audio.h"

// put function declarations here:
Audio ad;

void setup()
{
  // SPIClass spi = SPIClass(HSPI);
  // spi.begin(18 /* SCK */, 19 /* MISO */, 23 /* MOSI */, 5 /* SS */);
  // if (!SD.begin(5 /* SS */, spi, 120000000, "/cdcard"))
  // {
  //   Serial.println("Card Mount Failed");
  //   return;
  // }
  SD.begin();
  ad.setPinout(32, 33, 21);
  ad.setVolume(16); // 0...21
  ad.connecttoFS(SD, "/黑豹乐队 - Don't Break My Heart.mp3");
}

void loop()
{
  ad.loop();
  // put your main code here, to run repeatedly:
}
```

### Debug Message

```plain
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
␛[0;36m[    21][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz␛[0m
␛[0;37m[    51][V][ssl_client.cpp:321] stop_ssl_socket(): Cleaning SSL connection.␛[0m

assert failed: xQueueSemaphoreTake queue.c:1545 (( pxQueue ))


Backtrace: 0x40083741:0x3ffb1e60 0x400892ad:0x3ffb1e80 0x4008e5d5:0x3ffb1ea0 0x4008a201:0x3ffb1fd0 0x400d2ff6:0x3ffb2010 0x400d37c5:0x3ffb2040 0x400f5e62:0x3ffb2070 0x400f68f2:0x3ffb2090 0x400f7946:0x3ffb20b0 0x400f968b:0x3ffb20f0 0x400f2bb6:0x3ffb2120 0x4008710d:0x3ffb2140 0x40087051:0x3ffb2160 0x401318d6:0x3ffb2180 0x40131969:0x3ffb21c0 0x4012b9f9:0x3ffb21e0 0x4012b4fd:0x3ffb2200 0x400d9bea:0x3ffb2220 0x400dd0c6:0x3ffb2250 0x400d2dd6:0x3ffb2270 0x400e8ded:0x3ffb2290




ELF file SHA256: 9f0a5cf9921fc933

Rebooting...
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Please re-submit the issue report in English
