### ISSUE TITLE
wifi_sta_list_t should be zero'ed before use

### ISSUE THREAD

**Issue by TD-er** [espressif/arduino-esp32#10287]
### Board

Any

### Device Description

-

### Hardware Configuration

-

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Windows 11

### Flash frequency

Any

### PSRAM enabled

yes

### Upload speed

115200

### Description

As a follow-up of https://github.com/espressif/arduino-esp32/issues/10281 and as discussed with @me-no-dev

The `wifi_sta_list_t` struct has been extended recently and just to be sure no member is left in an undefined state, we should zero the entire struct before use.
The array of `wifi_sta_info_t` objects internally is filled via some get function from IDF, but I can't see if all are always filled.

`wifi_sta_list_t` is being used multiple times in `AP.cpp`, for example here:
https://github.com/espressif/arduino-esp32/blob/e70f4d3819500151af6a0adda561f09f647b3fc7/libraries/WiFi/src/AP.cpp#L136

### Sketch

```cpp
-
```

### Debug Message

```plain
-
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
this is not necessary here, because we are giving the struct to IDF to fill and not read from it. Zeroing is necessary only when data will be read in IDF. Like configs and such
