### ISSUE TITLE
Debounce question

### ISSUE THREAD

**Issue by usmanshahid001** [espressif/arduino-esp32#1029]
hii we have built counter on esp32 using proximity sensor but i am having pulse on change rather than on high or low ...i am using this command attachInterrupt(digitalPinToInterrupt(interrupt_pin),PULSE_FUNCTION,LOW);it is showing same behaviour either for high or change command...plz help me in this regard 

--
MOD EDIT: move the question from title to body

**Comment by lbernstone** [comment]
You likely need to debounce. http://www.labbookpages.co.uk/electronics/debounce.html
