### ISSUE TITLE
Memory leak in WebServer Authenticate

### ISSUE THREAD

**Issue by TD-er** [espressif/arduino-esp32#10336]
### Board

Any

### Device Description

-

### Hardware Configuration

-

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Windows 11

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

The function `fn` used here does return a `String` object which is allocated on the heap.
https://github.com/espressif/arduino-esp32/blob/4e9eb35752a36bd4e03739dc7e1c3ac246c49d3c/libraries/WebServer/src/WebServer.cpp#L268-L272

The caller is responsible to delete the object, however this is not done here for `ret`.

### Sketch

```cpp
-
```

### Debug Message

```plain
-
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
fixed and by mistake pushed directly to master... https://github.com/espressif/arduino-esp32/commit/8c25325e181b3ec0717187c66bba15e7c2af2494
