### ISSUE TITLE
Downloading firmware in esp32s3_gen4_r8n16 using esp32s3 flash download tool

### ISSUE THREAD

**Issue by muzahid13** [espressif/arduino-esp32#10354]
<img width="945" alt="esp32s3 flash tool" src="https://github.com/user-attachments/assets/18a3c76b-5b5e-47f4-ad15-09c941644f25">
<img width="955" alt="visual stdio ini" src="https://github.com/user-attachments/assets/80840477-75da-4d61-b1af-af1e94bf0f16">
### Related area

esp32

### Hardware specification

esp32s3_gen4_r8n16

### Is your feature request related to a problem?

i built the firmware using platformio in visual studio code. when i upload firmware directly from visual studio code, it is working good. but when i built firmware from vs code but upload using esp32s3 flash tool , it did not work. i put the offset value 0x10000 for firmware.bin, 0x1000 for bootloader.bin and 0x8000 for partition.bin. The bin files uploaded successfully but board didnot work. could you please help  me to solve this issue.

### Describe the solution you'd like

my board must be worked when i will upload the firmware using esp32s3 flash download tool. i cannot use vs code in the production line to upload firmware. so i must use esp32s3 flash download tool.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
bootloader is at address 0x0. And this is really off topic here
