### ISSUE TITLE
LOLIN32 Lite board missing/wrong pin definitions

### ISSUE THREAD

**Issue by njbuch** [espressif/arduino-esp32#1039]
### Hardware:
Board:							LOLIN32 Lite
Core Installation/update date:		25/jan/2018
IDE name:						Platform.io

### Description:
Pinout for LOLIN32 is identical to ESP32, pins_arduino.h seems odd.

Deployment to board works fine, but using for example LED_BUILTIN is not the right one (it should be 22)

### Debug Messages:
```
Some pins not working as intended.
```

**Comment by PEMessage** [comment]
I meet same issue, it seems to be the different between lolin32 and lolin32 lite. Hoping somebody could fix it.
