### ISSUE TITLE
esp32-arduino-libs-3.0.5.zip missing in 3.0.5 release.

### ISSUE THREAD

**Issue by reesesm2000** [espressif/arduino-esp32#10417]
### Board

ESP32

### Device Description

Custom circuit

### Hardware Configuration

All IO ports are being used for various things including I2C (x2) WS2812 and other GPIOs

### Version

latest master (checkout manually)

### IDE Name

VS Code

### Operating System

Windows 11

### Flash frequency

240MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

esp32-arduino-libs-3.0.5.zip missing in 3.0.5 release.

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
libs are no longer stored in the release page. Instead for 3.0.x they are stored here: https://github.com/espressif/esp32-arduino-lib-builder/releases/tag/idf-release_v5.1
