### ISSUE TITLE
Zigbee Implementation: Battery Management, Charger Management, and Power Management 

### ISSUE THREAD

**Issue by Hedda** [espressif/arduino-esp32#10430]
### Related area

Zigbee

### Hardware specification

ESP32-H2

### Is your feature request related to a problem?

Related to https://github.com/espressif/arduino-esp32/issues/10135 (Implement Zigbee in Arduino) and the sleep modes feature request for sleepy Zigbee End Devices ->https://github.com/espressif/arduino-esp32/issues/10405

At the bare minimum Zigbee need to include "Power Source" (i.e. mains power or battery powered) and battery level information.

But also wondering if can include advanced features for Battery Management, Charger Management, and Power Management?

If not as default then as one or more examples?

FYI, related to this I recently also read that Arduino has released an open-source Arduino Power Management library for Arduino Pro that could maybe be ported to arduino-esp32 for ESP32? It includes advanced rea--time battery management and battery monetoring + battery charger manager, as well as "sleep mode" (deep sleep) and "standby mode" (light sleep), with profiles for specific development boards:

* https://github.com/arduino-libraries/Arduino_PowerManagement/
  * https://github.com/arduino-libraries/Arduino_PowerManagement/tree/main/examples
  
For more information on how to use that library see their documentation:

* https://github.com/arduino-libraries/Arduino_PowerManagement/blob/main/docs

More on that new Arduino PowerManagement library here:

* https://www.cnx-software.com/2024/09/26/arduino-power-management-library-arduino-pro-modules/

### Features
* Monitor current and average battery metrics (voltage, current, percentage)
* Monitor battery health metrics (temperature, reported capacity)
* Monitor and control charging
* Save significant amounts of power by sending the boards into Sleep (only available for Portenta C33 for now) and Standby modes
* Toggle and set voltages on different power rails of the board
  * On Nicla Vision
    * Enable and disable the external power rail
    * Enable and disable the camera power rail
    * Change voltage on external power rail
  *   On Portenta C33
    * Enable and disable the external power rail
    * Enable and disable the communication power rail (ESP32, secure element)
    * Change voltage on the external power rail
  * On Portenta H7
    * Enable and disable the external power rail
    * Change voltage on external power rail

### Describe the solution you'd like

Maybe a Power Management library library for ESP32 and Zigbee examples for ESP32-H2, ESP32-H4, ESP32-C5, and ESP32-C6?

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by P-R-O-C-H-Y** [comment]
Hi @Hedda, I have opened a PR which adds power source + battery level feature to the Zigbee library.
When merged it will close this PR. I think all this battery management, power management etc. is not that much related to the Zigbee library. Do you agree?
