### ISSUE TITLE
Comments in BLEAdvertising are wrong/misleading

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [espressif/arduino-esp32#10511]
### Board

not board related

### Device Description

not board related

### Hardware Configuration

not board related

### Version

latest master (checkout manually)

### IDE Name

none

### Operating System

none

### Flash frequency

none

### PSRAM enabled

yes

### Upload speed

none

### Description

I was reading the code of BLEAdvertising() in order to understand the inner details and adapt my project to it.
I noticed that the code has different comments which do not match the implementation.

Several advertising types are different in the comments compared to the implementation. The implementation seems to be correct but the comment was probably copy/pasted and not adapted afterwards.

Example: 

https://github.com/espressif/arduino-esp32/blob/3502b9c7a9c9fcecc51c1f40ea0180a8563f44cd/libraries/BLE/src/BLEAdvertising.cpp#L355
The comment says 0x02, but later it uses 0x03:

https://github.com/espressif/arduino-esp32/blob/3502b9c7a9c9fcecc51c1f40ea0180a8563f44cd/libraries/BLE/src/BLEAdvertising.cpp#L357

### Sketch

```cpp
none
```

### Debug Message

```plain
none
```

### Other Steps to Reproduce

none

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
Thanks @thomasw-mitutoyo-ctl for the PR.
