### ISSUE TITLE
GPIO6 set high inside Bootloader

### ISSUE THREAD

**Issue by microbotsio** [espressif/arduino-esp32#10527]
### Board

ESP32C3 Dev Board

### Device Description

Tested n the ESP32-C3-MINI-1-N4

### Hardware Configuration

GPIO6

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

921600

### Description

Gpio pin 6 is set high inside the bootloader - eg. when re-flashing the device or initially resting the device

Other gpio pins like 1,2,3,5,7 are all keep low during this state. Is there a way to keep gpio 6 set it low? 

### Sketch

```cpp
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

### Debug Message

```plain
Hardware issue
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment]
GPIO 6 is a special GPIO and has restrictions/special behaviour. Short answer no.

**Comment by microbotsio** [comment]
Is there any specifications about the behavior of this pin during boot mode?

**Comment by Jason2866** [comment]
Yes, see [datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-c6_datasheet_en.pdf)

**Comment by VojtechBartoska** [comment]
Closing this as answered.

**Comment by microbotsio** [comment]
Thanks for the information :)
