### ISSUE TITLE
Please add board YB-ESP32-S3-AMP to your boardlist

### ISSUE THREAD

**Issue by yellobyte** [espressif/arduino-esp32#10656]
### Related area

Board support

### Hardware specification

ESP32-S3 dev board with uSD, 2xMAX98357A, USB-C 

### Is your feature request related to a problem?

Board YB-ESP32-S3-AMP is missing in the official board list.
Board spec: https://github.com/yellobyte/ESP32-DevBoards-Getting-Started/tree/main/boards/YB-ESP32-S3-AMP

### Describe the solution you'd like

Pls add board YB-ESP32-S3-AMP to the official board list.
Board definition files under: https://github.com/yellobyte/ESP32-DevBoards-Getting-Started/tree/main/boards/YB-ESP32-S3-AMP/examples/PlatformIO

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by lbernstone** [comment]
We do not create variant files.  If you would like to add your board, you can create files using the default esp32s3 [pins](https://github.com/espressif/arduino-esp32/blob/master/variants/esp32s3/pins_arduino.h) and [menus](https://github.com/espressif/arduino-esp32/blob/master/boards.txt#L538-L788).  The Espressif team will validate the settings and add them to the repo, but the community is in charge of maintaining them.

**Comment by yellobyte** [comment]
Thanks for the info. I will prepare the necessary files and come back to you.
