### ISSUE TITLE
How can I turn off the radio on ESP32?

### ISSUE THREAD

**Issue by JLuisAlcaraz** [espressif/arduino-esp32#1077]
Hi,
I need, in order to save battery, turn off the radio and the BLE. How can I do that on Arduino IDE?

**Comment by CelliesProjects** [comment]
I turn off BLE with `btStop();`
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-bt.c

**Comment by JLuisAlcaraz** [comment]
Thank you very much!

**Comment by CelliesProjects** [comment]
For wifi you can use:

`WiFi.mode( WIFI_MODE_NULL );`

should work in Arduino IDE.

**Comment by JLuisAlcaraz** [comment]
Thank you!

**Comment by JLuisAlcaraz** [comment]
With "WiFi.mode( WIFI_MODE_NULL);" The current compsuntion is the same.
I teste with and without that line and I dont see current variation.
Is there another way to turn off the radio part on the ESP32??

**Comment by CelliesProjects** [comment]
I am not sure, the above info came from issue https://github.com/espressif/arduino-esp32/issues/75.

**Comment by CelliesProjects** [comment]
Maybe turn of both radios?
They may be implemented as a single radio that is multiplexed.

**Comment by copercini** [comment]
There is an example for this: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiBlueToothSwitch/WiFiBlueToothSwitch.ino

to turn wifi and Bluetooth off:
```cpp
WiFi.mode(WIFI_OFF);
btStop();
```

**Comment by JLuisAlcaraz** [comment]
Thank you very much, friends!

**Comment by daton89** [comment]
Stopping bluetooth with `btStop();` will save energy?

**Comment by mrdazhuk** [comment]
`btStop` doesn't work. It freezes the app

**Comment by me-no-dev** [comment]
@mrdazhuk should be fixed in the latest master

**Comment by mrdazhuk** [comment]
@me-no-dev the problem still exists.

**Comment by me-no-dev** [comment]
This works for me in Master and I can no longer reproduce your problem. Did you uninstall the core from the board manager first?
```cpp
  SerialBT.begin("ESP32test");
  delay(1000);
  SerialBT.end();//calls btStop();
```

**Comment by mrdazhuk** [comment]
Let me check. Thank you

**Comment by mrdazhuk** [comment]
@me-no-dev could you please share your configuration from platformio.ini. 
seems to me i'm doing something wrong, because BluetoothSerial.cpp is little different. I've removed everything, but still different

**Comment by me-no-dev** [comment]
@mrdazhuk sorry, I do not use PIO
