### ISSUE TITLE
ESP 32 light sleep 

### ISSUE THREAD

**Issue by jarda195** [espressif/arduino-esp32#1102]
Hi all

How applicat this idea (from ESP8266 on ESP32)

Set sleep and use button func_key (PIN 1 on ESP8266)
-------------------------------
void sleep() {
  gpio_pin_wakeup_enable(GPIO_ID_PIN(PORT_FUNC_KEY), GPIO_PIN_INTR_LOLEVEL); 
  wifi_fpm_open();
  wifi_fpm_set_wakeup_cb(fpm_wakup_cb_fnc);
  wifi_fpm_do_sleep(0xFFFFFFF);
}

Wake up  (press btn func_key)
----------
fpm_wakup_cb_fnc() {
   wifi_fpm_close;
   gpio_pin_wakeup_disable();  //release btn from sleep mode and use in program
}

Thk

Jarek

**Comment by lbernstone** [comment]
Sleep is a very system dependent thing, and is completely different in esp32 from esp8266. Arduino-esp32 does not have a full implementation, but the IDF has some examples: https://github.com/espressif/esp-idf/tree/master/examples/system/deep_sleep
