### ISSUE TITLE
ESP32 SPIFFS Webserver

### ISSUE THREAD

**Issue by shaddow501** [espressif/arduino-esp32#1116]
Hello.

This is not an issue but a question.

I would like to run Webserver from the internal SPIFFS and from the local website to be able to load / access  files from the SD card.

I have the standard Webserver working and that works ok, also the SD card store log files from inputs that the ESP32 gets.

This all works, but how do I open the files from the SD card on the Webpage? what need to be done?

**Comment by rndme** [comment]
there's an SD server example in the esp8266 package, it's going to be 90% the same for esp32. You basically need to alter the SPIFFs example's 404 handler to use SD.exists() instead of SPIFFS.exists, and the load routines as well.

**Comment by shaddow501** [comment]
Dear rndme, thanks for you answer, Yes I did try this lib but my question is how to integrate both SPIFFS and SD in the same webserver and to be able to access them both, My logic is to put the website on the SPIFFS and read from the webserver the logs from the SD-Card, how to do that this is the question...

**Comment by me21** [comment]
Unfortunately, no. Never worked with SD Card myself.

**Comment by shaddow501** [comment]
lol so how can you be sure that your example works?

**Comment by me21** [comment]
I'm not sure, try and we will see :)
