### ISSUE TITLE
ADD: SSDP Example and library

### ISSUE THREAD

**Issue by andrewjaykeller** [espressif/arduino-esp32#1119]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			?11/jul/2017?
IDE name:							VSCode
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:

I want to use SSDP but I do not want to have to implement my own library. Currently I cannot see an SSDP example like I can in the [ESP8266SSDP](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266SSDP) examples.

I would love to see a port of this useful discovery library for use in ESP32!

**Comment by atanisoft** [comment]
Here is an ESP32 port of @me-no-dev uSSDP: https://github.com/marian-craciunescu/uSSDP-ESP32

I haven't looked at it too much but this could be a solution for your needs. One difference in this library vs the ESP8266 one is that you need to call a method from the loop() method, in the ESP8266 library you link to it uses a timer for this task.
