### ISSUE TITLE
reason2str wrong?

### ISSUE THREAD

**Issue by tablatronix** [espressif/arduino-esp32#1128]
Why do the upper reason codes not align with the bottom.

`[W][WiFiGeneric.cpp:298] _eventCallback(): Reason: 202 - ASSOC_FAIL`

    WIFI_REASON_BEACON_TIMEOUT              = 200,
    WIFI_REASON_NO_AP_FOUND                     = 201,
    WIFI_REASON_AUTH_FAIL                            = 202,
    WIFI_REASON_ASSOC_FAIL                          = 203,
    WIFI_REASON_HANDSHAKE_TIMEOUT       = 204,

EDIT: ohhhh
Ok so maybe its just
reason2str that is wrong..

Should this maybe be 0 indexed instead, so (r-176)-1
`#define reason2str(r) ((r>176)?system_event_reasons[r-177]:system_event_reasons[r-1])`

**Comment by copercini** [comment]
Closed due it's fixed here: https://github.com/espressif/arduino-esp32/pull/1132

Nice PR!
