### ISSUE TITLE
Where documentation for "Arduino core for the ESP32" (arduino-esp32) is located?

### ISSUE THREAD

**Issue by N0rbert** [espressif/arduino-esp32#1148]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			2018-01-05
IDE name:						Arduino IDE 1.8.5 & Platform.io 3.5.2rc1
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
I can't find comprehensive documentation for "Arduino core for the ESP32" (arduino-esp32). 
But I can find it for [ESP-IDF at ReadTheDocs](http://esp-idf.readthedocs.io/).

I know about [esp32.net](http://esp32.net) and [esp32.com](http://esp32.com), but their format does not suite my needs, because I need book format.

Where documentation for "Arduino core for the ESP32" (arduino-esp32) is located?  
Is it available in Doxygen / reStructuredText / Markdown / PDF formats anywhere?
Is it similar to ESP-IDF? Or it is completely different API?

**Comment by lbernstone** [comment]
Arduino-esp32 is intended to provide an arduino compatible environment on the esp32 hardware.  https://www.arduino.cc/reference/en/ has the basic arduino functional documentation.

**Comment by N0rbert** [comment]
Let me clarify what I need.
I say about documentation for `esp32_`-prefixed functions, not basic Arduino functions (not `digitalRead()`).
Examples: `esp_deep_sleep_enable_ulp_wakeup`, `esp_deep_sleep_start`, `esp_vfs_spiffs_register`, `esp_wifi_scan_start`, `esp_ble_gap_start_advertising`, `esp_spiffs_mounted` and so on.

Am I understand correctly that right way to use documentation is to read both [Arduino Reference](https://www.arduino.cc/reference/en/) and [ESP-IDF](http://esp-idf.readthedocs.io/) for ESP specific functions?

**Comment by copercini** [comment]
Arduino for ESP32 is a compatibility layer that calls the IDF functions ( [ESP-IDF docs](http://esp-idf.readthedocs.io/en/latest/) )

This is good because you can use both APIs on both platforms, [running Arduino code on IDF](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md) or calling IDF functions directly on your Arduino code

**Comment by N0rbert** [comment]
Thank you for clarification. I thought suddenly I lost something.

**Comment by hansonap** [comment]
> 
> 
> > Examples: esp_deep_sleep_enable_ulp_wakeup, esp_deep_sleep_start, esp_vfs_spiffs_register, esp_wifi_scan_start, esp_ble_gap_start_advertising, esp_spiffs_mounted and so on.
> 
> These functions are from IDF: https://github.com/espressif/esp-idf http://esp-idf.readthedocs.io/en/latest/
> 
> Arduino for ESP32 is a compatibility layer that calls the IDF functions ( [ESP-IDF docs](http://esp-idf.readthedocs.io/en/latest/) )
> 
> This is good because you can use both APIs on both platforms, [running Arduino code on IDF](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md) or calling IDF functions directly on your Arduino code

The above statement is only partially true. From [espressif/arduino-esp32/libraries](https://github.com/espressif/arduino-esp32/tree/master/libraries):
>
>
> arduino-esp32 includes libraries for Arduino compatibility along with *some object wrappers around hardware specific devices.* 

Except for the code itself, there appears to be no documentation for the wrapper objects (example: BluetoothSerial). As I am sure it has for others, the lack of documentation has resulted in additional time trying to fully understand the ecosystem. There are 2 suggested actions here:
1. On the [homepage](https://github.com/espressif/arduino-esp32/) a note stating "arduino-esp32 includes [libraries](https://github.com/espressif/arduino-esp32/tree/master/libraries) for Arduino compatibility along with some object wrappers around hardware specific devices. Examples are included in the examples folder under each library folder. The ESP32 includes additional examples which need no special drivers."
2. Hardware specific libraries should have documentation created.

**Comment by dzhelek** [comment]
What about functions like `touchRead` and `ledcAnalogWrite` which I can neither find in the arduino [reference] (like @lbernstone suggested) nor in the  esp-idf [docs] (as suggested by @copercini )?
Am I understanding correctly that the only two ways I can hear about these functions is from random websites and by digging into the [source] code of arduino-esp32?
Why there is no documentation?

[reference]:  https://www.arduino.cc/reference/en/
[docs]: http://esp-idf.readthedocs.io/en/latest/
[source]: https://github.com/espressif/arduino-esp32/tree/master/cores/esp32

**Comment by szepi1991** [comment]
Just as an additional datapoint: it does look like some libraries have slightly diverged between arduino and arduino-esp32. For example the resolution of [this issue](https://github.com/espressif/arduino-esp32/issues/103) was that the interface for the WiF library i is not fully exchangeable.
