### ISSUE TITLE
btstack integration

### ISSUE THREAD

**Issue by fesch** [espressif/arduino-esp32#1164]
Hi

I wanted to try to integrate btstack (from bluekitchen) into arduino-esp32. I've come so far to compile the libbstack.a library and grep out nearly all h files, but I'm facing now the problem that I do not know where to put the file inside the hardware\espressif\esp32 so that my projet could find them

I've tried different places, but no chance so far.
libbtstack.a >> hardware\espressif\esp32\tools\sdk\lib
btstack\*.h >> hardware\espressif\esp32\tools\sdk\include

Any hints?

**Comment by fesch** [comment]
Adding "-I{compiler.sdk.path}/include/btstack" to the file platforms.txt made it ...

**Comment by copercini** [comment]
Are you planning to use it for RFCOMM/SPP ?

**Comment by fesch** [comment]
Yes, that was the idea.

So far so good, but sub h files seams not to get included included automatically ... :(

**Comment by copercini** [comment]
Take a look here: https://github.com/espressif/arduino-esp32/pull/1144
I can give you a help if you want to test it

**Comment by fesch** [comment]
Cool! I did not find that one yet but will take a look at it!! Thanks :)

**Comment by fesch** [comment]
Thanks, I've got your library up and running!
That is exactly what I was looking for ...

**Comment by beegee-tokyo** [comment]
And if you want to play with Bluetooth and BLE running in parallel, I wrote a small [tutorial](http://desire.giesecke.tk/index.php/2018/02/27/initialize-bluetooth-serial-and-ble-server/)

**Comment by fesch** [comment]
Thanks for the link.

BLE is not needed in my project, at least not yet. But who knows what the future brings ;-)

**Comment by EdanPotter** [comment]
Any news about btstack integration?
