### ISSUE TITLE
Add BluetoothSerial library 

### ISSUE THREAD

**Issue by kww52** [espressif/arduino-esp32#1170]
### Hardware:
Board:							Himalaya ESP32-ST with ESP-WROOM-32
Core Installation/update date:			03.03.2018
IDE name:							Arduino 1.85
Flash Frequency:					80Mhz
Upload Speed:						921600

### Description:
Have **Arduino core for the ESP32** with **BluetoothSerial library**, installed under Arduino 1.85.
If I now want to compile the example "**SerialBT.ino**", I get the following error messages;

libraries\BluetoothSerial\BluetoothSerial.cpp.o:(.literal._ZN15BluetoothSerial5writeEh+0x0): undefined reference to `esp_spp_write'

libraries\BluetoothSerial\BluetoothSerial.cpp.o:(.literal._ZL10esp_spp_cb18esp_spp_cb_event_tP18esp_spp_cb_param_t+0x4): undefined reference to `esp_bt_gap_set_scan_mode'

libraries\BluetoothSerial\BluetoothSerial.cpp.o:(.literal._ZL10esp_spp_cb18esp_spp_cb_event_tP18esp_spp_cb_param_t+0x8): undefined reference to `esp_spp_start_srv'

libraries\BluetoothSerial\BluetoothSerial.cpp.o:(.literal._ZN15BluetoothSerial5beginE6String+0x4): undefined reference to `esp_spp_register_callback'

libraries\BluetoothSerial\BluetoothSerial.cpp.o:(.literal._ZN15BluetoothSerial5beginE6String+0x8): undefined reference to `esp_spp_init'

libraries\BluetoothSerial\BluetoothSerial.cpp.o: In function `BluetoothSerial::write(unsigned char)':
E:\Arduino\libraries\BluetoothSerial\src/BluetoothSerial.cpp:140: undefined reference to `esp_spp_write'

libraries\BluetoothSerial\BluetoothSerial.cpp.o: In function `BluetoothSerial::write(unsigned char const*, unsigned int)':
E:\Arduino\libraries\BluetoothSerial\src/BluetoothSerial.cpp:140: undefined reference to `esp_spp_write'

libraries\BluetoothSerial\BluetoothSerial.cpp.o: In function `esp_spp_cb(esp_spp_cb_event_t, esp_spp_cb_param_t*)':
E:\Arduino\libraries\BluetoothSerial\src/BluetoothSerial.cpp:140: undefined reference to `esp_bt_gap_set_scan_mode'

E:\Arduino\libraries\BluetoothSerial\src/BluetoothSerial.cpp:140: undefined reference to `esp_spp_start_srv'
libraries\BluetoothSerial\BluetoothSerial.cpp.o: In function `BluetoothSerial::flush()':
E:\Arduino\libraries\BluetoothSerial\src/BluetoothSerial.cpp:140: undefined reference to `esp_spp_write'

libraries\BluetoothSerial\BluetoothSerial.cpp.o: In function `BluetoothSerial::begin(String)':
E:\Arduino\libraries\BluetoothSerial\src/BluetoothSerial.cpp:140: undefined reference to `esp_spp_register_callback'

E:\Arduino\libraries\BluetoothSerial\src/BluetoothSerial.cpp:140: undefined reference to `esp_spp_init'
collect2.exe: error: ld returned 1 exit status

Can you help me?

Best regards
Karl-Walter

### Sketch:
SerialBT.ino

**Comment by beegee-tokyo** [comment]
Did you replace as well Bluetooth library.  Which is `tools/sdk/lib/libbt.a`. I took the one from copercinis report.

**Comment by kww52** [comment]
Thanks for the hint, that was the problem!

**Comment by beegee-tokyo** [comment]
If it works, please close the issue.

**Comment by bear24rw** [comment]
For anyone else coming here from google I had the same issue but fixed it with `make menuconfig` and enabling this options: `Component config -> Bluetooth -> Bluedroid Options -> Classic Bluetooth -> SPP`

**Comment by rstrofton** [comment]
> For anyone else coming here from google I had the same issue but fixed it with `make menuconfig` and enabling this options: `Component config -> Bluetooth -> Bluedroid Options -> Classic Bluetooth -> SPP`

Thanks bear24rw that saved me a lot of time
