### ISSUE TITLE
Board is not recognized by Computer

### ISSUE THREAD

**Issue by Goloo** [espressif/arduino-esp32#1172]
### Hardware: 
Board:			                                        ESP WROOM 32
Core Installation/update date:			11/jul/2017
IDE name:							Arduino IDE
Flash Frequency:					        40Mhz
Upload Speed:						115200

### Description:
I made a few projects with my ESP32 since last year and I never used my other boards and everything worked fine. But yesterday I used the Arduino Nano and changed the board in the arduino ide but when I wanted to change back to my ESP32 (I used the WEMOS LOLIN) my computer showed no ports with this board. I tried every single port and some different cables but nothing works. The board itself blinks short with his on board LED like it did before this issue so I don't think it is broken. I reinstalled the whole board library and restarted my Lenovo Thinkpad, but the arduino IDE doesn't recognize my board. 

### Debug Messages:

No Port selected (because I can't even select a port.)

**Comment by AsafFisher** [comment]
I got the same problem
