### ISSUE TITLE
70% of example sketches fail to compile

### ISSUE THREAD

**Issue by krzychb** [espressif/arduino-esp32#12]
Hi,

Current git release provides the following examples sketches:

![new picture](https://cloud.githubusercontent.com/assets/12953787/19212127/5c7964be-8d4b-11e6-8191-3356a6fb8f68.png)

Out of them the following compile out of box:

  1. WiFiClient
  2. WiFiClientBasic
  3. WiFiMilti

All other drop some errors. 
For example, compilation of HTTPSReqest.ino fails as follows:

```
C:\Users\Krzysztof\Desktop\arduino-1.6.12\hardware\espressif\esp32\libraries\WiFi\examples\HTTPSRequest\HTTPSRequest.ino:15:30: fatal error: WiFiClientSecure.h: No such file or directory

 #include <WiFiClientSecure.h>

                              ^

compilation terminated.
```
Test was done using Arduino 1.6.12 portable.

If this is the case, then I would remove all the sketches that do not work. 
This is not to confuse people that are testing this repository.

Krzysztof

**Comment by me-no-dev** [comment]
done! fixed a couple to work ;)

**Comment by krzychb** [comment]
@me-no-dev,
Congratulations on first closure of issue report!
And what an amazing speed :+1:
