### ISSUE TITLE
touchRead

### ISSUE THREAD

**Issue by DiegoMendoza1** [espressif/arduino-esp32#122]
Hi, I am looking for information about the capacitive touch and as they are programmed in the ide of arduino, I have seen that it is necessary to read them with the function touchRead but I do not find which is the librery that needs to recognize this function.

can anybody help me?

Thank you

**Comment by me-no-dev** [comment]
no library is needed ;) just call ```touchRead(pin);``` on any pin that supports touch.

**Comment by DiegoMendoza1** [comment]
I have done so, but when I build with the arduino ide it says touchRead is not declared

**Comment by me-no-dev** [comment]
You must have selected the wrong board or something. touchRead is defined [here](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-touch.h#L43);

**Comment by DiegoMendoza1** [comment]
The board is correct, I have the esp devkit. I have written this code as an example and still does not recognize that touchRead is declared:


`#include <arduino.h>

int Touch = 20;

void setup() {

Serial.begin(115200);

pinMode(Touch, INPUT);


}

void loop() {
  
touchRead(Touch);

 if(Touch == LOW){

  Serial.println("ENABLE");
  
  delay(1000);

  
 else{
  Serial.println ("DISABLE");
  
  delay(1000);
 }
  
  }
}`

**Comment by me-no-dev** [comment]
this sketch compiled just fine here. Also "Arduino" is capitalized. Also touchRead will return unsigned integer value, not LOW/HIGH.

**Comment by me-no-dev** [comment]
btw are you sure you are running the latest esp32-arduino?

**Comment by DiegoMendoza1** [comment]
I´m not sure, where is it?

**Comment by DiegoMendoza1** [comment]
I found it, I didn´t have the latest version, now it compiles correctly.

Thanks
