### ISSUE TITLE
How can i enable and disable ble(uart example) inside the arduino scatch

### ISSUE THREAD

**Issue by kfirmaymon84** [espressif/arduino-esp32#1230]
Hi sorry for the dumb question, 

How can i enable and disable ble(uart example) inside the arduino scatch
 
I am using ble uart example and I'm trying to enable and disable it with push of a button. 
Thanks for helping

**Comment by copercini** [comment]
There is an example for it: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiBlueToothSwitch/WiFiBlueToothSwitch.ino

**Comment by kfirmaymon84** [comment]
Thanks

**Comment by tedder** [comment]
For future googlers, `btStop()` and `btStart()` are the relevant functions.
