### ISSUE TITLE
Best migration path from esp8266

### ISSUE THREAD

**Issue by zafrirron** [espressif/arduino-esp32#1232]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			?11/jul/2017?
IDE name:							Arduino IDE
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
What would be the recommended migration path for arduino esp8266 apps to arduino ESP32?
found myself copying libraries, replacing header files names to make it work, looks like there must be some better way someone already created a better path....

**Comment by tablatronix** [comment]
When converting wifimanager, I used ifdefs and created abstraction wrapper functions for the basic stuff, in case there was any behavior differences between the the 2 also there are some minor differences with some stuff, but most of it is already aligned, sta and ap functions work pretty much the same.
