### ISSUE TITLE
BLE Binary and Heap Size

### ISSUE THREAD

**Issue by PhilColbert** [espressif/arduino-esp32#1235]
I know theres been a few comments regarding the size the addition of BLE however.....

Are there any plans to sort this out ?

My binary goes from 980K to 1832K and free heap from 133k down to 9k..... and then crashes due to heap issues.

Surely this isnt usable?

**Comment by maoiot** [comment]
Support Phil. The collected libraries contain unnecessary debugging information. We need a correct Makefile to rebuild the entire library package for ArduinoIDE
