### ISSUE TITLE
bta_dm_ble_scan start scan failed. status=0x3

### ISSUE THREAD

**Issue by sharkyy** [espressif/arduino-esp32#1241]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:		mar/2018
IDE name:						Arduino IDE
Flash Frequency:					40Mhz
Upload Speed:					115200

### Description:
Hi Guys,

I've created a sketch that scans for BLE Eddystone beacons. This already works very well as long as it doesn't find any beacons. As soon as it finds a beacon it continues scanning but after a few scans I always get this message and the program stops:
[0;31mE (4679213) BT:  bta_dm_ble_scan start scan failed. status=0x3

Does anyone know where this comes from or how this could be either avoided or solved?

Thanks and best regards
Max

**Comment by iotwlionel** [comment]
I'm having the same exact error, googled and found your post, any solutions so far? would it make a difference if we tried to run ble on the 2nd core (not sure how to do that yet)?
