### ISSUE TITLE
OTA programing with arduino ide

### ISSUE THREAD

**Issue by DiegoMendoza1** [espressif/arduino-esp32#125]
Does the OTA work with arduino ide?
If it works can someone put an example?

**Comment by elFallino** [comment]
I guess not (yet?). The Bootloader does not do any WiFi stuff. You would need to write the necessary things on your own either by patching the bootloader or writing user code that receives data OTA and stores them. But it would require you to change the partition layout e.g. to have a second partition where OTA data is stored.

I think that I read somewhere that the current bootloader is able to handle multiple partitions and to start user code from a partition you like. But still the above mentioned things are required.

**Comment by evanmj** [comment]
@DiegoMendoza1 Did you try the ArduinoOTA yet on esp32?  http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html

**Comment by DiegoMendoza1** [comment]
I tried with the esp8266 code but the libraries give me error when compiling the program

**Comment by sfowlr** [comment]
Similar to #78

**Comment by me-no-dev** [comment]
soon. there are fixes inline upstream. When all is good, I will implement it. Partitions are already there.

**Comment by me-no-dev** [comment]
implemented ;)

**Comment by blackketter** [comment]
Excited to try this out.  Can you point me to the documentation?

**Comment by me-no-dev** [comment]
https://github.com/esp8266/Arduino/blob/master/doc/ota_updates/readme.md#application-example
Skip the Python part.

**Comment by blackketter** [comment]
Ok, thanks @me-no-dev!  

Should I open a separate issue suggesting that this repository include its own documentation?

**Comment by me-no-dev** [comment]
please do not open an issue. I am quite aware of the many things missing.

**Comment by DiegoMendoza1** [comment]
Thanks @me-no-dev it is a good new, i have a problem the cpu gets halted, i have open an issue #260. 

Thanks in advance

**Comment by arvindr21** [comment]
Updated 8266 docs URL: https://github.com/esp8266/Arduino/blob/master/doc/ota_updates/readme.rst
