### ISSUE TITLE
.setOutputPower TX on ESP32

### ISSUE THREAD

**Issue by bulentperktas** [espressif/arduino-esp32#1254]
How can i set outputpower on ESP32?

i saw in espressif idf SDK, (line 814)

https://github.com/espressif/esp-idf/blob/master/components/esp32/include/esp_wifi.h

but is there a way set it's value in arduino IDE?

**Comment by lbernstone** [comment]
You can include esp_wifi.h and use that function.  All the esp-idf functions are exposed in headers (although YMMV).
