### ISSUE TITLE
I am using Arduino 1.8.5. I want to change the partition 

### ISSUE THREAD

**Issue by hpwit** [espressif/arduino-esp32#1272]
Please fill the info fields, it helps to get you faster support ;)
I want to change the partitions, I have change default.cvs regenerated default.bin but int still doesn't work, the esp32 is stuck. maybe I need to regenerate the boot_app0.bin
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078a58
user code done

**Comment by beegee-tokyo** [comment]
Should work. Can you post your new default.csv? [Change partition size](https://desire.giesecke.tk/index.php/2018/01/30/change-partition-size/)
