### ISSUE TITLE
'esp_wifi_disconnect' was not declared in this scope

### ISSUE THREAD

**Issue by JLuisAlcaraz** [espressif/arduino-esp32#1278]
Hi all!,
I'm trying to disconnect Wifi and BLE in order to save battery power. I read WiFi.disconnect(true) doesnt work, and esp_wifi_disconnect() must be used.
but the problem is compiler says that this is not declared. What #include I need to add??

**Comment by JLuisAlcaraz** [comment]
#include <esp_wifi.h>

**Comment by dominikandreas** [comment]
this import conflicts with `#inclide <WiFi.h>`, but `#include "esp_deep_sleep.h"` worked for me
