### ISSUE TITLE
ESP32 save power.

### ISSUE THREAD

**Issue by JLuisAlcaraz** [espressif/arduino-esp32#1279]
Hi all!,
I'm trying to disconnect Wifi and BLE in order to save power.
But with "esp_wifi_disconnect()" I dont notice any reduction in power.
I read 78ma with and without that code line. Is there any trick?
The 78ma reading is with the ESP32NodeMCU board without connect anithing, just the board to the 5v power.

**Comment by beegee-tokyo** [comment]
I don't think `esp_wifi_disconnect()` will shut down the WiFi. Try `WiFi.mode( WIFI_OFF );` instead.

**Comment by rin67630** [comment]
I have the same problem.
Running the standard example SimpleTime on a Wemos LoLin32, I still get 76mA on idle...
That example uses WiFi.mode( WIFI_OFF );
