### ISSUE TITLE
get.exe download stuck while installing esp32 library

### ISSUE THREAD

**Issue by salmanabbasi112** [espressif/arduino-esp32#1280]
![image](https://user-images.githubusercontent.com/37957165/38163735-4147d7d2-3512-11e8-8ffa-d2e139934792.png)

The download is not completing. Tried to run as administrator as well. Restarted computer and run get.exe. But still not working. Please help fast.

**Comment by lbernstone** [comment]
If you look down in the comment of this [article](https://desire.giesecke.tk/index.php/2018/02/27/alternative-to-install-arduino-esp32-for-arduino-ide-windows/), @beegee-tokyo lists the urls to download the files.  Put them in the tools/dist folder and see if get.exe completes.

**Comment by Onno-Dirkzwager** [comment]
salmanabbasi112 
in my case I had to disable the virus scanner temporary before clicking get.exe

**Comment by beegee-tokyo** [comment]
Improved the instructions if [get.exe/get.py fails to download required files](https://desire.giesecke.tk/index.php/2018/04/02/get-exe-get-py-fails-to-download-required-files/) in the [Wiki](https://desire.giesecke.tk/index.php/2018/01/30/esp32-wiki-entries/)

**Comment by syndicated-8** [comment]
I'm having the same issue. The get.exe stays stuck downloading. Article link to download files separately doesn't work.
