### ISSUE TITLE
resource concumpition BluetoothSerial.cpp

### ISSUE THREAD

**Issue by AlphaLima** [espressif/arduino-esp32#1282]
BluetoothSerial.cpp
Works fine for me, but it needs 50% of the ESP32 Resources, together with my sketch it is over 100%, so it becomes useless. Is there a way to reduce the library size?

----------------------------- Remove above -----------------------------

### Hardware:
Board:							Node32
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
Describe your problem here

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by lbernstone** [comment]
You can change the partition layout of your device. https://desire.giesecke.tk/index.php/2018/01/30/change-partition-size/
