### ISSUE TITLE
SDFS File::flush() appears to do nothing

### ISSUE THREAD

**Issue by everslick** [espressif/arduino-esp32#1293]
I have a long running process that regularly appends data to a file on SD card and calls flush() on it afterwards. Still when I open the very same file and read its content it has no data appended nor its file size updated. When I close the file between writes, the data is there though. The exact same code works as expected when the file lifes on SPIFFS. So I assume that SD flush() is either not implemented or is buggy.

**Comment by everslick** [comment]
Or do I just see this behaviour mentioned here: https://github.com/espressif/arduino-esp32/pull/514#issuecomment-315703988 ?

**Comment by everslick** [comment]
I see there have been reports about this issue, putting them here for reference: #1173 and #1169

**Comment by psykokwak-com** [comment]
I had the same issue.
I fixed it by adding  `fsync(fileno(_f));`  after `fflush(_f);` in the `void VFSFileImpl::flush()` in file vfs_api.cpp

**Comment by ericlangel** [comment]
Same Problem with Flash (FFAT) File write.

This works...but its to slow
loop(){
File Data = FFat.open("/Data.txt", FILE_APPEND);
Data.write(Buffer,18);
Data.close();
}

And this doesn't work... nothing is written
loop(){
File Data = FFat.open("/Data.txt", FILE_APPEND);
while(1){
Data.write(Buffer,18);
Data.flush
}
}

I have to write 18 Bytes every 1ms.
How can i get it working?
FFat.open() needs 8ms.

**Comment by psykokwak-com** [comment]
Just use the POSIX implementation : fopen, fwrite, fsync, fclose.

**Comment by rrroonn** [comment]
`fsync(fileno(myFileDesc));
` does indeed work around the problem.

**Comment by Bascy** [comment]
I'm getting a `'fileno' was not declared in this scope` when compiling
Where should this method be living?

**Comment by everslick** [comment]
@Bascy : the workaround has already been merged 5 days ago. I think it will land in the stable release sooner or later. fileno() is an internal function, you cannot use it in a sketch.

**Comment by Bascy** [comment]
I'm getting the compile error when compiling FS library through my script, not using `fileno()`  myself

**Comment by Bascy** [comment]
Solved, was caused by a stray compiler option

**Comment by ArosPrince** [comment]
For me. the error is caused by -std=c++17. But I wouldn't call that *a stray compiler option*. There are libraries that require this option.

**Comment by davefiddes** [comment]
@ArosPrince If you are looking to use a newer standard from the one defined in the platform.txt you need to use the GNU extension variant. So the ESP32 Arduino project currently uses -std=gnu++11 if you wanted to use C++17 you change this to -std=gnu++17. Using a newer C++ standard should probably be raised as a separate issue.

**Comment by ArosPrince** [comment]
@davefiddes OK, thanks. Good to know.
