### ISSUE TITLE
esp32 WIFI reconnect

### ISSUE THREAD

**Issue by JacoFourie** [espressif/arduino-esp32#1294]
I have seen that there is talk about the reconnect not working. What is the best way to have the ESP32 reconnect if it looses a wifi connection. Will it be implemented in the core or should I handle it ?

**Comment by copercini** [comment]
Take a look here: https://github.com/espressif/arduino-esp32/issues/653 :wink: 

Will close to concentrate the discussion on https://github.com/espressif/arduino-esp32/issues/653
