### ISSUE TITLE
Connecting NodeMCU 1.0 to 802.1X

### ISSUE THREAD

**Issue by daisthorpe1** [espressif/arduino-esp32#1300]
Hi 

I am new to programming.
I am looking to connect a NodeMCU board to a 802.1X public Wifi BT - X . This requires Username / Password 

Any  help appreciated

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							?ESP32 Dev Module?
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
Describe your problem here

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by martinius96** [comment]
This is ESP32 hub. 
NodeMCU in old SDK cannot join 802.1x network, only with newest sdk to 802.1x - EAP (NOT PEAP)
