### ISSUE TITLE
mkspiffs needs updating

### ISSUE THREAD

**Issue by JamesGKent** [espressif/arduino-esp32#1328]
when i tried to preload files into spiffs using the plugin I get an invalid filesystem error from `spiffs.begin`

I downloaded the latest mkspiffs (0.2.3) and replaced my installed version (0.2.2) and the error disappeared.
package_esp32_index.template.json needs updating with the urls, names and checksums of the newer packages.

**Comment by schweini** [comment]
have you tried calling it as "spiffs.begin(true)" ? This made some examples that didn't work start working for me.

**Comment by JamesGKent** [comment]
i haven't, as stated i updated my local mkspiffs executable and the issue was resolved, i'm not sure why this repo isn't using the latest mkspiffs as it is...
