### ISSUE TITLE
ESP freezes in random moments

### ISSUE THREAD

**Issue by szerwi** [espressif/arduino-esp32#1340]
### Hardware:
Board: ESP32 Dev Module
Core Installation/update date: 20.04.2017
IDE name: Arduino IDE 1.8.5
Flash Frequency: 80Mhz
Upload Speed: 115200

### Description:
After updating libraries to the newest version my ESP freezes in random moments, few seconds after turning on. On libraries from few previous months everything is ok.

**Comment by stickbreaker** [comment]
@szerwi This issue report doesn't do an good.  It is disappointing that you are having problems, with this generic, unspecific report, all we can do is commiserate with you.

Chuck.

**Comment by szerwi** [comment]
https://pastebin.com/3vJ92P8R That's the code that is not working for me on new libraries. ESP32 crashes after 1-2 minutes or when connecting to Telnet.
I updated repository today. My last repository was from January 2018
The same code is working correctly on libraries from January 2018.

**Comment by copercini** [comment]
try put some delay on `loop()` otherwise it will run the functions a lot of times per second

**Comment by szerwi** [comment]
@copercini in my final code I can't use delays.

**Comment by szerwi** [comment]
Problem solved. It was reading to frequently from DS3231. Thank you @copercini for help :)
