### ISSUE TITLE
OTA Updates need a completion message.

### ISSUE THREAD

**Issue by trlafleur** [espressif/arduino-esp32#1354]
When you do an OTA update, there is no information from the IDE that the update was complete...  All you get is the message below.... It would be nice to see a message from the IDE/Loader (espota.py) that the action was completed.

As a very minor note:   espota.py make many references to ESP8266 in its messages and code, and NOT ESP32.

~~~
Sending invitation to 192.94.167.236 
Authenticating...OK
Uploading...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
~~~

### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:		25/Apr/2018
IDE name:						Arduino IDE 1.8.5
Flash Frequency:					80Mhz
Upload Speed:					115200

**Comment by lbernstone** [comment]
Your [need for validation](https://www.psychologytoday.com/us/blog/anger-in-the-age-entitlement/201104/pain-suffering-and-validation) is concerning.  Command line utilities should provide an error code on completion.  If you want to know the result, `echo $?`. espota.py does provide feedback on errors.
