### ISSUE TITLE
Changing partition scheme in menu doesn't change upload max size

### ISSUE THREAD

**Issue by domints** [espressif/arduino-esp32#1378]
### Hardware:
Board:							LOLIN32
Core Installation/update date:			2/may/2018
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						921600

### Description:

So, all above doesn't matter, maybe beside installation date and board type.
In the boards.txt there is section for some boards (i.e. DevKit) that allows change of partition scheme with just few clicks (to min_spiffs, no_ota etc.) which literally changes how big app can be. Unfortunately there is no directive to instruct ArduinoIDE that upload max size changed, so with no_ota partition scheme there is space for 2M program, but ArduinoIDE refuses to flash program bigger than default 1.3M.

I have solved problem on my instance, so I will create pull request with changes to boards.txt, but I wanted to have this issue filed in case anybody looked for it.

**Comment by domints** [comment]
I added PR:

https://github.com/espressif/arduino-esp32/pull/1379

This change was checked on LOLIN32 board, so that's the only board I added partitions to, and also added upload.maximum_size to DevKit.
This would most certainly work with other boards, but I am not sure about their flashes and have no way of testing, so that's why I added only to LOLIN32.

**Comment by reaper7** [comment]
great idea!
this should be added to all boards!

TNX!

**Comment by domints** [comment]
Should I feel ignored? :(

**Comment by reaper7** [comment]
why? I'm sure @me-no-dev look at it.
easy... :)
