### ISSUE TITLE
Udp endPacket() returns -1 on error and 7 on success

### ISSUE THREAD

**Issue by tonu42** [espressif/arduino-esp32#138]
Been using Udp a lot and believe when the packet fails to send successfully it should return 0, and on success a 1.

From cores/esp32/Udp.h

`// Returns 1 if the packet was sent successfully, 0 if there was an error
    virtual int endPacket() =0;`

Below screen shots to support. 

![image](https://cloud.githubusercontent.com/assets/739994/22050500/5dc905a0-dd09-11e6-8479-ee54a7f1291b.png)

![image](https://cloud.githubusercontent.com/assets/739994/22050564/fd3a0fee-dd09-11e6-9d70-69be9ac64d47.png)

**Comment by me-no-dev** [comment]
thanks for noting :) fixed in the latest commit.

**Comment by tonu42** [comment]
Glad to have helped. Glad I was not mistaken. This was my first ever issue I reported on Github! Trying to be involved with the ESP32 development to make it better for everyone. Hope you did not think I was nitpicking.

**Comment by me-no-dev** [comment]
no worries :) things like that are important and easy to miss at the same time
