### ISSUE TITLE
write binary array on SD card failed (it was working fine)

### ISSUE THREAD

**Issue by williamesp2015** [espressif/arduino-esp32#1383]
### Hardware:
Board:							ESP32 Dev Module?
Core Installation/update date:			5/4/2018
IDE name:							PlatformIO 3.5.3b2
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
Previously I had no problem with my SD card writing a binary file but now CPU crashed when trying to write.

/*
 * This sketch is a simple binary write/read benchmark
 * for the standard Arduino SD.h library.
 */
#include <Arduino.h>
#include <SPI.h>
#include <SD.h>
#define SD_CS_PIN 5 //VSPI
#define SD_SO_PIN  19//VSPI 
#define SD_CLK_PIN 18//VSPI 
#define SD_SI_PIN  23//VSPI 
const uint32_t SPI_LS_CLOCK = 4000000;  // 4 MHz
//const uint32_t SPI_HS_CLOCK = 20000000; // 20 MHz
const uint32_t SPI_HS_CLOCK = 8000000; // 8 MHz testing only

#define FILE_SIZE_MB 5
#define FILE_SIZE (1000000UL*FILE_SIZE_MB)
#define BUF_SIZE 100

uint8_t buf[BUF_SIZE];

File file;

//------------------------------------------------------------------------------
// store error strings in flash to save RAM
void error(char* s) {
  Serial.println(s);
  while(1);
}
//------------------------------------------------------------------------------
void setup() {
  Serial.begin(115200);
  auto SPI = SPIClass();
  SPI.begin(SD_CLK_PIN,SD_SO_PIN,SD_SI_PIN,SD_CS_PIN);
  SPISettings(SPI_LS_CLOCK, MSBFIRST, SPI_MODE3);// run on low speed SPI
  delay(1);
  SD.begin(SD_CS_PIN, SPI, 4000000, "/sd");//First Try
  delay(1);
}
//------------------------------------------------------------------------------
void loop() {
  uint32_t maxLatency;
  uint32_t minLatency;
  uint32_t totalLatency;

  // discard any input
  while (Serial.read() >= 0) {}

  // pstr stores strings in flash to save RAM
  Serial.println("Type any character to start");
  while (Serial.read() <= 0) {}
  delay(400);  // catch Due reset problem

  if (!SD.begin(SD_CS_PIN, SPI, 4000000)) error("begin");

  // open or create file - truncate existing file.
  //file = SD.open("BENCH.DAT", FILE_WRITE | O_TRUNC);

//  file = SD.open("BENCH.DAT", O_CREAT | O_TRUNC | O_CREAT);
  file = SD.open("/BENCH.DAT", FILE_APPEND);
  if (!file) {
    error("open failed");
  }

  // fill buf with known data
  for (uint16_t i = 0; i < (BUF_SIZE-2); i++) {
    buf[i] = 'A' + (i % 26);
  }
  buf[BUF_SIZE-2] = '\r';
  buf[BUF_SIZE-1] = '\n';

  Serial.print("File size ");
  Serial.print(FILE_SIZE_MB);
  Serial.println("MB");
  Serial.print("Buffer size ");
  Serial.print(BUF_SIZE);
  Serial.println(" bytes");
  Serial.println("Starting write test.  Please wait up to a minute");

  // do write test
  uint32_t n = FILE_SIZE/sizeof(buf);
  maxLatency = 0;
  minLatency = 999999;
  totalLatency = 0;
  uint32_t t = millis();
  for (uint32_t i = 0; i < n; i++) {
    uint32_t m = micros();
    if (file.write(buf, sizeof(buf)) != sizeof(buf)) {
      error("write failed");
    }
    m = micros() - m;
    if (maxLatency < m) maxLatency = m;
    if (minLatency > m) minLatency = m;
    totalLatency += m;
  }
  file.flush();
  t = millis() - t;
  double s = file.size();
  Serial.print("Write ");
  Serial.print(s/t);
  Serial.print(" KB/sec\n");
  Serial.print("Maximum latency: ");
  Serial.print(maxLatency);
  Serial.print(" usec, Minimum Latency: ");
  Serial.print(minLatency);
  Serial.print(" usec, Avg Latency: ");
  Serial.print(totalLatency/n);
  Serial.print(" usec\n\n");
  Serial.print("Starting read test.  Please wait up to a minute\n");
  // do read test
  file.seek(0);
  maxLatency = 0;
  minLatency = 99999;
  totalLatency = 0;
  t = millis();
  for (uint32_t i = 0; i < n; i++) {
    buf[BUF_SIZE-1] = 0;
    uint32_t m = micros();
    if (file.read(buf, sizeof(buf)) != sizeof(buf)) {
      error("read failed");
    }
    m = micros() - m;
    if (maxLatency < m) maxLatency = m;
    if (minLatency > m) minLatency = m;
    totalLatency += m;
    if (buf[BUF_SIZE-1] != '\n') {
      error("data check");
    }
  }
  t = millis() - t;
  Serial.print("Read ");
  Serial.print(s/t);
  Serial.print(" KB/sec\n");
  Serial.print("Maximum latency: ");
  Serial.print(maxLatency);;
  Serial.print(" usec, Minimum Latency: ");
  Serial.print(minLatency);;
  Serial.print(" usec, Avg Latency: ");
  Serial.print(totalLatency/n);
  Serial.print(" usec\n\n");
  Serial.print("Done\n\n");
  file.close();
}
Type any character to start
File size 5MB
Buffer size 100 bytes
Starting write test.  Please wait up to a minute
/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/./queue.c:1442 (xQueueGene
ricReceive)- assert failed!

abort() was called at PC 0x40084a0d on core 1

Backtrace: 0x40087528:0x3ffca240 0x40087627:0x3ffca260 0x40084a0d:0x3ffca280 0x400d2ec5:0x3ffca
2c0 0x400d1141:0x3ffca2e0 0x400d1395:0x3ffca310 0x400d1a60:0x3ffca340 0x400d453e:0x3ffca370 0x4
00d47e6:0x3ffca390 0x400d4830:0x3ffca3b0 0x400d4e1e:0x3ffca3d0 0x400d4faa:0x3ffca3f0 0x400d61d5
:0x3ffca410 0x400d71ef:0x3ffca450 0x400d7b22:0x3ffca480 0x4000bd83:0x3ffca4a0 0x4000117d:0x3ffc
a4c0 0x400592fe:0x3ffca4e0 0x4005937a:0x3ffca500 0x40058ad3:0x3ffca520 0x400ec214:0x3ffca550 0x
400ec25d:0x3ffca590 0x400e9b0a:0x3ffca5b0 0x400ec329:0x3ffca5d0 0x400d0d96:0x3ffca5f0 0x400ea33
9:0x3ffca640

Rebooting...

**Comment by ArTyGill** [comment]
You create a very large array of variables uint8_t buf [BUF_SIZE], which can not fit in either the RAM or the ROM of your ESP32 module. Use the Stream to write from source to the SD card, or byte write.
