### ISSUE TITLE
Uart RX not working?

### ISSUE THREAD

**Issue by stephmack** [espressif/arduino-esp32#14]
It appears that the uart rx is not working?  
For example if you use:
while (Serial.available()){
}
there are never any bytes found available...  Has anyone else had problems when trying to receive uart data/characters?
The tx works fine as I can see data on the serial monitor.

**Comment by me-no-dev** [comment]
Hmm... it was working fine last I checked... will look into it

**Comment by me-no-dev** [comment]
should be working fine now

**Comment by stephmack** [comment]
Thank You!
