### ISSUE TITLE
Any way to shut the bootloader of esp32?

### ISSUE THREAD

**Issue by vpr1995** [espressif/arduino-esp32#1402]
I am new to esp32. I am trying to make ultra low power BLE beacon and bootloader startup consumes about 190ms costing a heavy burden on battery. Is there any way to turn off bootloader ? Any suggestion is appreciated.

Thank you

**Comment by lbernstone** [comment]
Please post this question on https://bbs.espressif.com/ and close the issue.  It is not a bug report, and has absolutely nothing to do with arduino.
