### ISSUE TITLE
Reset ESP32 with GPIO 12 configured as OUTPUT or INPUT.

### ISSUE THREAD

**Issue by BlackTiger44** [espressif/arduino-esp32#1417]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							ESP32 DEVKIT V1 - DOIT
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
On my ESP32 DEVKIT V1 board from DOIT, when configuring the GPIO12 (D12) as an output or as an input, the following error occurs every time I start the program

rst: 0x10 (RTCWDT_RTC_RESET), boot: 0x37 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
Falling back to built-in command interpreter.
okay

If the cable that reaches the GPIO12 (D12) is physically loosened, both configured as input and output, the ESP32 starts the program normally.

I have tried to configure GPIO12 as shown in the code below, but I can not get it to work, so any help would be welcome.

#include "driver/gpio.h"

#define GPIO_BIT_MASK  (1ULL<<GPIO_NUM_12) 

void setup() 
{
  app_main();
.....
}

void app_main() {
  gpio_config_t io_conf;
  io_conf.intr_type = GPIO_INTR_DISABLE;
  io_conf.mode = GPIO_MODE_OUTPUT;
  io_conf.pin_bit_mask = GPIO_BIT_MASK;
  io_conf.pull_down_en = GPIO_PULLDOWN_DISABLE;
  io_conf.pull_up_en = GPIO_PULLUP_DISABLE;
  gpio_config(&io_conf);
}

Thanks

BlakcTiger

**Comment by lbernstone** [comment]
GPIO12 is also MTDI, which changes the voltage of the internal LDO to 1.8V if pulled high at boot.  This is also a problem for many boards that use gpio12 for the sd card (sd cards have internal pullups).

**Comment by BlackTiger44** [comment]
Thanks Ibernstone for the clarification.

Greetings BlackTiger

**Comment by lbernstone** [comment]
If that "solves" the issue, please close it.

**Comment by BlackTiger44** [comment]
..

**Comment by kraker31** [comment]
It's a clarification, that doesn't solve anything :(

**Comment by kraker31** [comment]
The best way to solve the pb should be to change the efuse configuration to force MTDI to 0 as it should be. No?

**Comment by lbernstone** [comment]
Yes
https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card#note-about-gpio12-esp32-only
