### ISSUE TITLE
AWS_S3_OTA header files problem ?

### ISSUE THREAD

**Issue by SulaimanEfendi** [espressif/arduino-esp32#1431]
**Hardware**
Board: Generic ESP8266 Module
Core Installation/update date:
IDE name: Arduino IDE 1.8.5
Flash Frequency: 40Mhz
Upload Speed: 115200

**Description**
I try to compile the AWS_S3_OTA_Update.ino but I get the (fatal error: Update.h: No such file or directory). How can I add all the needed header files to my scatch? is by adding all headers manually to the Arduino >> libraries or by another way.

After collecting all the need header files manually I get the following problems;

In file included from C:\Users\Suleyman\Documents\Arduino\libraries\Update\src\esp_image_format.h:18:0,
from C:\Users\Suleyman\Documents\Arduino\libraries\Update\src\Updater.cpp:5:
C:\Users\Suleyman\Documents\Arduino\libraries\Update\src\esp_flash_partitions.h:38:50: error: 'esp_partition_info_t' does not name a type esp_err_t esp_partition_table_basic_verify(const esp_partition_info_t *partition_table, bool log_errors, int *num_partitions);

In file included from C:\Users\Suleyman\Documents\Arduino\libraries\Update\src\Updater.cpp:5:0:
C:\Users\Suleyman\Documents\Arduino\libraries\Update\src\esp_image_format.h:133:60: error: 'esp_partition_pos_t' does not name a type esp_err_t esp_image_load(esp_image_load_mode_t mode, const esp_partition_pos_t *part, esp_image_metadata_t *data);
                          
Thanks

**Comment by lbernstone** [comment]
This is the esp32 forum.  esp8266 is [thataway](https://github.com/esp8266/Arduino)

**Comment by SulaimanEfendi** [comment]
thanks, @lbernstone
