### ISSUE TITLE
WiFiMulti does not work again after update

### ISSUE THREAD

**Issue by smacyas** [espressif/arduino-esp32#1432]
Does not work example WiFi Multi with the latest Arduino IDE:

#include <WiFi.h>
#include <WiFiMulti.h>

WiFiMulti wifiMulti;

void setup()
{
Serial.begin(115200);
delay(10);

wifiMulti.addAP("ssid", "pswrd");

Serial.println("Connecting Wifi...");
if(wifiMulti.run() == WL_CONNECTED) {
    Serial.println("");
    Serial.println("WiFi connected");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
}
}

void loop()
{
if(wifiMulti.run() != WL_CONNECTED) {
Serial.println("WiFi not connected!");
delay(1000);
}
}

Connecting Wifi...
E (300) wifi: esp_wifi_scan_start 967 wifi not start
WiFi not connected!
WiFi not connected!
WiFi not connected!
WiFi not connected!

**Comment by smacyas** [comment]
It works with the previuos version of WiFi library, and no with the new one

**Comment by iqbal-hassan** [comment]
Bisected and found the offending commit 69f72eca849a44688e2da38028eb9aa707e91f08.

**Comment by CarloSandoval** [comment]
where can I find the previous version of the WiFi library?

**Comment by timkoers** [comment]
@CarloSandoval by looking at the [commit history](https://github.com/espressif/arduino-esp32/commits/master)you can find all the changes that came with past commits and browse their files.
