### ISSUE TITLE
Compilation failure adding Arduino as a component.

### ISSUE THREAD

**Issue by PhilColbert** [espressif/arduino-esp32#1434]
I just downloaded ESPIDF, copied one of the examples and added Arduino as a component via git as per the website.

Added Bluetooth in the menuconfig .

Unfortunately it now doesnt compile 

CXX build/arduino/libraries/BLE/src//BLEServer.o
C:/msys32/home/Fugazi/esp/hello_world/components/arduino/libraries/BLE/src/BLEServer.cpp:21:22: fatal error: gatt_api.h: No such file or directory
compilation terminated.
make[1]: *** [/home/Fugazi/esp/esp-idf/make/component_wrapper.mk:286: libraries/BLE/src//BLEServer.o] Error 1
make: *** [C:/msys32/home/Fugazi/esp/esp-idf/make/project.mk:467: component-arduino-build] Error 2

After removing //#include <esp_gatts_api.h> in BLEServer.cpp it compiles once more... 

then SimpleBLE.cpp wont compile - remove //#include "bta_api.h", then it compiles.

Have these files just not been updated yet?

Any ideas?

**Comment by lbernstone** [comment]
Since you have the solution (rolling back to the checkout from the latest esp-idf update), what are you calling out as the bug/issue here?  These projects move forward at different rates and there will be inconsistencies between them as individual commits occur.  That commit is about 45 days old.

**Comment by PhilColbert** [comment]
Because, if you follow the instructions how to install espidf and then ardunio as a component, it doesnt work, so anyone new coming along to install it, it fails as per the instructions.

Either the instructions need changing or it fixing so it compiles ?
