### ISSUE TITLE
ping library

### ISSUE THREAD

**Issue by salilsingh20** [espressif/arduino-esp32#1441]
### Hardware:
Board:							DOIT ESP32 DEVKIT V1
Core Installation/update date:			?11/jul/2017?
IDE name:							Platform.io
Flash Frequency:					?160Mhz?
Upload Speed:						?115200?

### Description:
do we have ping library for esp32

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by beegee-tokyo** [comment]
9t's all in thd [Wiki](https://desire.giesecke.tk/index.php/2018/02/18/esp32-ping-library/) ;-)
