### ISSUE TITLE
False tempratures

### ISSUE THREAD

**Issue by Flo082002** [espressif/arduino-esp32#1443]
### Hardware:
Board:							DOIT ESP32 DVKIT V1 Board
Core Installation/update date:			29/1/2018
IDE name:						Arduino IDE 1.8.5 Windows 10/Ubuntu 17.10
Flash Frequency:					80Mhz
Upload Speed:						921600

### Description:
The tempratur is every time 180° or 179°F but I can feel, that it is getting warmer.

### Sketch:

```
#ifdef __cplusplus
extern "C" {
#endif
uint8_t temprature_sens_read();
#ifdef __cplusplus
}
#endif

uint8_t temprature_sens_read();

void setup()
{
Serial.begin(9600);

}


void loop()
{

delay(200);
    Serial.println(temprature_sens_read());

}

```

**Comment by lbernstone** [comment]
This function is from esp-idf, and it is unsupported.  Please close this issue:
```
//Undocumented!!! Get chip temperature in Farenheit
//Source: https://github.com/pcbreflux/espressif/blob/master/esp32/arduino/sketchbook/ESP32_int_temp_sensor/ESP32_int_temp_sensor.ino
uint8_t temprature_sens_read();

```
