### ISSUE TITLE
HardwareSerial.h begin()

### ISSUE THREAD

**Issue by dtboy1995** [espressif/arduino-esp32#1450]
```c
void begin(unsigned long baud, uint32_t config=SERIAL_8N1, int8_t rxPin=-1, int8_t txPin=-1, bool invert=false);
```
Can you explain the meaning of the last parameter `invert` for me.
Thanks.

**Comment by sysizlayan** [comment]
this is for voltage level conversion. 0V means 1, 3.3V means 0 if inverted.

**Comment by dtboy1995** [comment]
@sysizlayan thank you for your reply.
the default value is `false`, when will it be set to `true` ?
I don't quite understand.

**Comment by sysizlayan** [comment]
I have not used that flag also before but I believe it depends on the circuit topology to transmit and receive. For example, if you are using Schmidt Trigger, if you are using open drain/collector transistors or something similar to increase transmission power, this makes circuit simpler.

**Comment by dtboy1995** [comment]
thank you very much.

**Comment by stickbreaker** [comment]
The idle state of the serial is high(3.3v). A byte starts when the signal goes low(0v). Based on the programmed BAUD rate the hardware UART samples the signal level assigning the bit values. If `invert` is true, idle is low, a byte starts when the signal goes high, a high(3.3v) is interpreted as 0, low(0v) as 1. 

Unless you have 'special' hardware connected, leave `inverted` false.

Chuck.

**Comment by lbernstone** [comment]
Please close the issue.
