### ISSUE TITLE
Problem softAp with windows

### ISSUE THREAD

**Issue by vidaxdu40** [espressif/arduino-esp32#1460]
### Hardware:
Board:							sparkfun esp32 thing
Core Installation/update date:			
IDE name:							Arduino IDE
Flash Frequency:					80 MHz
Upload Speed:						115200

Hello everyone, I have a problem. i have a esp32 sparkfun thing board and i have configurated a softAP with arduino. My problem is that i can connect a station on the AP with an iPhone, macbook but with my PC on windows 10 and a windows tab on windows 8 the connection doesn’t work.
Do you have a solution please ?

**Comment by timkoers** [comment]
Could you describe what is going wrong? Is it not connect all, or is there no op.
Windows should connect fine when there is no internet connection on the AP, but you might have to tell Windows to connect first.

**Comment by lbernstone** [comment]
https://en.wikiversity.org/wiki/Wireshark/DHCP

**Comment by vidaxdu40** [comment]
hello,
I discovered sometime I can connect the pc to esp32.
When the connexion work i have this on wireshark 
![image](https://user-images.githubusercontent.com/39905777/41217447-340cdbfc-6d58-11e8-984e-678bb03c36c8.png)

but when the connexion fail i have nothing

**Comment by lbernstone** [comment]
If the client never asks for an address, the server can't give it one :smile: .

**Comment by vidaxdu40** [comment]
Yes of course ;) but what is strange is that even if I don't have communication shown on wireshark, when the connexion fail i have the SYSTEM_EVENT_AP_START event in the esp32

**Comment by vidaxdu40** [comment]
https://drive.google.com/open?id=1EjPk04hRMx9Wp94K9GDWjN0v6LvA0MOB
