### ISSUE TITLE
BLE UART example and IOS disconnecting

### ISSUE THREAD

**Issue by PhilColbert** [espressif/arduino-esp32#1465]
Hi,

Has anyone got this to stay stable, mine runs sporadically and randomly disconnects?

(W (25699) BT_APPL: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0008)

Which i guess is the iphone disconnecting ?

Using the BluePixel BLE scanner, also a custom flying app, both do the same. ( Iphone 4S )

Using a HM-10, it stays connected.....

Log

V (25524) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe71cc), owner: <N/A>
D (25542) GeneralUtils: 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f ----------------
D (25547) GeneralUtils: 0000 7c |
D (25554) FreeRTOS: Semaphore taking: name: ConfEvt (0x3ffe6c30), owner: <N/A> for notify
D (25562) FreeRTOS: Semaphore taken: name: ConfEvt (0x3ffe6c30), owner: notify
V (25569) FreeRTOS: >> wait: Semaphore waiting: name: ConfEvt (0x3ffe6c30), owner: notify for notify
V (25570) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe6c30), owner: notify
V (25585) FreeRTOS: << wait: Semaphore released: name: ConfEvt (0x3ffe6c30), owner: notify
V (25585) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe71cc), owner: <N/A>
D (25603) GeneralUtils: 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f ----------------
D (25608) GeneralUtils: 0000 7d }
D (25615) FreeRTOS: Semaphore taking: name: ConfEvt (0x3ffe6c30), owner: <N/A> for notify
D (25623) FreeRTOS: Semaphore taken: name: ConfEvt (0x3ffe6c30), owner: notify
V (25630) FreeRTOS: >> wait: Semaphore waiting: name: ConfEvt (0x3ffe6c30), owner: notify for notify
V (25632) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe6c30), owner: notify
V (25646) FreeRTOS: << wait: Semaphore released: name: ConfEvt (0x3ffe6c30), owner: <N/A>
V (25646) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe71cc), owner: <N/A>
D (25664) GeneralUtils: 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f ----------------
D (25669) GeneralUtils: 0000 7e ~
D (25676) FreeRTOS: Semaphore taking: name: ConfEvt (0x3ffe6c30), owner: <N/A> for notify
D (25684) FreeRTOS: Semaphore taken: name: ConfEvt (0x3ffe6c30), owner: notify
V (25691) FreeRTOS: >> wait: Semaphore waiting: name: ConfEvt (0x3ffe6c30), owner: notify for notify
W (25699) BT_APPL: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0008
V (25699) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe6c30), owner: notify
V (25715) FreeRTOS: << wait: Semaphore released: name: ConfEvt (0x3ffe6c30), owner: <N/A>
V (25715) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe71cc), owner: <N/A>
V (25730) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe6c30), owner: <N/A>
D (25733) GeneralUtils: 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f ----------------
V (25737) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffe71cc), owner: <N/A>
D (25745) GeneralUtils: 0000 7f .
start advertising

Thanks for any help!

**Comment by copercini** [comment]
Close as duplicated of https://github.com/nkolban/esp32-snippets/issues/545
