### ISSUE TITLE
Why not generate a warning or an error when setting pins above 33 as an output?

### ISSUE THREAD

**Issue by steffenmauch** [espressif/arduino-esp32#1469]
I just stumbled about the limitation that pins above 33 can only be an input.
I am asking myself why the code is not generating a warning or even an error when trying to do so.

Would such a patch make it into mainline or is the current behavior the desired one?

**Comment by stickbreaker** [comment]
@steffenmauch How would you generate the error?

```
void pinMode(uint8_t pin, uint8_t mode);
```
Would you add conditional debug output? Have it verify every value at every execution? These tests would only be useful to detect incorrectly written code?

I think it is the programmers responsibility to understand the hardware limitations.  When you program to bare metal, there are sharp edges.  You must educate yourself, the hardware datasheet / eratta documentation are your friend :grin:  

Chuck.

**Comment by gcormier** [comment]
+1 for this. This could be a compile-time check, no?

We're talking about Arduino - this is the fence around the sandbox for kids to play in. It's very easy to miss that GPIO34/35 are input only.
