### ISSUE TITLE
How to maximize free RAM?

### ISSUE THREAD

**Issue by cyberman54** [espressif/arduino-esp32#1470]
Any tips here, how to maximize free RAM while using arduino espressif32?
Either by using compile time options, or by using runtime modifications?

**Comment by stickbreaker** [comment]
@cyberman54 Don't use WiFi or BlueTooth.

Chuck.

**Comment by SoftwareGuy** [comment]
Also consider using something like PSRAM over SPI to increase available RAM, but this is experimental.

**Comment by timkoers** [comment]
I'd say, use pointers and references and delete them when you're finished with them. That might not gain as much in comparison to the other options.
