### ISSUE TITLE
hey i am switching frequency between 240 MHZ and 2 MHZ but i am unable to find how to adjust my baudrate

### ISSUE THREAD

**Issue by usmanshahid001** [espressif/arduino-esp32#1474]

**Comment by SoftwareGuy** [comment]
Baudrate for what? Serial?

**Comment by timkoers** [comment]
You can use Serial.begin(baudrate) 
You should check the datasheet of the serial to USB controller, if you have one, for the baudrate extremes.

**Comment by stickbreaker** [comment]
code to support CPU frequency changes has been implemented since V1.0.2
