### ISSUE TITLE
esp32 devkit C What do i need to do if i want the power to start automatically, instead of pressing EN

### ISSUE THREAD

**Issue by dtboy1995** [espressif/arduino-esp32#1475]
The usb power went off and the program did not start.
But sometimes the program will run after the EN button is pressed
Who knows why, ask for help
Thanks

**Comment by lbernstone** [comment]
Please ask questions like this on [gitter](https://gitter.im/espressif/arduino-esp32) or www.esp32.com.  This board is for issues with the arduino-esp32 code.

**Comment by dtboy1995** [comment]
@lbernstone thank you. i am sorry.
