### ISSUE TITLE
Can't change WiFi channel used by ESP AP in APSTA mode

### ISSUE THREAD

**Issue by marciodias2003** [espressif/arduino-esp32#1477]
### Hardware:
Board: ESP32 Dev Module
Core Installation/update date: latest
IDE name: Atmel Studio
Flash Frequency: 80Mhz
Upload Speed: 512000

### Description:
My solution uses about 20 ESP32 modules running one next other (in the same room). For config reasons, in a short period of time, I need that all the modules has an open access point waiting for connection. In order to reduce WiFi overhead, I need to choose a random channel to each ESP AP. This works well when ESP is in AP mode, but the APSTA mode seems not respect the channel number being passed as parameter.
When in APSTA mode the channel used is the wifi router's channel.

### Sketch:
```cpp
// This code works as expected
WiFi.mode(WIFI_MODE_AP);
WiFi.softAP("TEST", NULL, random(1,13));
// An Access Point is created with a random channel between 1 and 13

// This code doesn't works as expected
WiFi.mode(WIFI_MODE_APSTA);
WiFi.softAP("TEST", NULL, random(1,13));
// The Access Point created uses the same channel that has been used by the wifi router
```

### Debug Messages:
N/A

**Comment by beegee-tokyo** [comment]
Not 100% sure, but I think it is a hardware restriction. Same as with ESPnow and AP that must be configured on same channel or it doesn't work.

**Comment by marciodias2003** [comment]
Acording to this [https://esp32.com/viewtopic.php?t=538](post), there are two different interfaces to AP and Station, that can be configured separately.

**Comment by marciodias2003** [comment]
Unfortunately you are right beegee-tokyo.

"ESP32 is limited to only one channel, so when in the soft-AP+station mode, the soft-AP will adjust its channel automatically to be the same as the channel of the ESP32 station."

From: [http://esp-idf.readthedocs.io/en/latest/api-reference/wifi/esp_wifi.html](url)
