### ISSUE TITLE
prf_defs.h not found

### ISSUE THREAD

**Issue by kashyap-ravichandran97** [espressif/arduino-esp32#1479]
Hey, I am trying to create a bluetooth HID mouse. I tried to use the code present under tools>sdk>include>bluedroid>hid_le_prf.h

However when i try to compile the code, the IDE throws an error saying that prf_defs.h is not a valid file or header. 
what am i doing wrong?

### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			06-06-2018
-I-DE name:					        Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						921600

**Comment by lbernstone** [comment]
This looks like an upstream error in the library.  Can you post at https://github.com/espressif/esp-idf/issues and reference this issue?
