### ISSUE TITLE
ULP Programming - Discussion

### ISSUE THREAD

**Issue by timpur** [espressif/arduino-esp32#1491]
### Hardware:
Board:							ESP32 Dev Module (esp32doit-devkit-v1)
Core Installation/update date:	        01/06/2018?
IDE name:						Platform.io
Flash Frequency:					40Mhz
Upload Speed:				        115200

### Description:
Hi i was wondering if we could start discussing ULP programming and how this is going to be integrated into Arduino to hopefully make it easy to do :) Currently im using macros ... but not the best method for large ULP programs ...

**Comment by negativekelvin** [comment]
https://github.com/duff2013/arduino_ulp

**Comment by ivankravets** [comment]
We added support in PlatformIO. See https://github.com/platformio/platform-espressif32/releases/tag/v1.9.0
