### ISSUE TITLE
Update GCC compiler to use C++17 features (structured binding)

### ISSUE THREAD

**Issue by Sterpa** [espressif/arduino-esp32#1499]
### Hardware:
Board:							M5Stack-Core-ESP32
Core Installation/update date:		14/jun/2018
IDE name:						Arduino IDE 1.8.6
Flash Frequency:					80Mhz
Upload Speed:					921600

### Description:
error: expected unqualified-id before '[' token
when using structured binding

already turned-on the flag
compiler.cpp.flags=-std=gnu++17 
in esp32/platform.txt

but you use gcc-5.2.0 and "structured binding" and all other great C++17 features are only supported in gcc-7.2.0 and higher version

Could you please update GCC compiler to gcc-7.2.0 or higher to use more C++17 features?

### Sketch:
```cpp

#include <map>
#include <vector>
#include <string>

struct BookStats
{
    std::string title;
    std::vector<std::string> authors;
    std::vector<std::string> tags;
    unsigned pageCount = 0;
    unsigned publishingYear = 0;
};

void setup() {
  // put your setup code here, to run once:

  // structure
  const auto book = BookStats{
      u8"Pinoccio on the Moon",
      { u8"Nikolay Nosov" },
      { u8"nursery", u8"fantastic" },
      576,
      1965
  };
  // structured binding
  const auto [title, authors, tags, pagesCount, publishingYear] = book;
}
```

### Debug Messages:
```
C:\Downloads\ArduinoSketches\AirOne_01\AirOne_01.ino: In function 'void setup()':
AirOne_01:26:14: error: expected unqualified-id before '[' token
   const auto [title, authors, tags, pagesCount, publishingYear] = book;
              ^
exit status 1
expected unqualified-id before '[' token
```

**Comment by lbernstone** [comment]
That is an upstream issue.  You can post at https://github.com/espressif/esp-idf, but this is a dependency driven by the cpu manufacturer, so don't expect this to happen any time soon.
