### ISSUE TITLE
undefined reference to `esp_vfs_fat_sdmmc_unmount()'

### ISSUE THREAD

**Issue by luca-saggese** [espressif/arduino-esp32#150]
Maybe i'm missing something stupid...
I'm trying to communicate to the sd card on a custom dev board, however when i try to compile the schetch i get: undefined reference to `esp_vfs_fat_sdmmc_unmount()'

here is a sample code:
`#include <stdio.h>
#include <string.h>
#include <sys/unistd.h>
#include <sys/stat.h>
#include "esp_err.h"
#include "esp_log.h"
#include "esp_vfs_fat.h"
#include "driver/sdmmc_host.h"
#include "driver/sdmmc_defs.h"
#include "sdmmc_cmd.h"
//void app_main(void);

void setup()
{
    Serial.begin(115200);
    delay(10);

    Serial.println();
    Serial.println();
    Serial.print("test ");
    esp_vfs_fat_sdmmc_unmount();
}

int value = 0;

void loop()
{

}`

i get:
/var/folders/bv/tql51gj11jx70jfzwzl6phmh0000gn/T/arduino_build_60462/sketch/test_sd.ino.cpp.o:(.literal.setup+0x10): undefined reference to `esp_vfs_fat_sdmmc_unmount()'
/var/folders/bv/tql51gj11jx70jfzwzl6phmh0000gn/T/arduino_build_60462/sketch/test_sd.ino.cpp.o: In function `setup':
/Users/lsaggese/Desktop/test_sd/test_sd.ino:146: undefined reference to `esp_vfs_fat_sdmmc_unmount()'

Any help?

**Comment by me-no-dev** [comment]
put the includes in ```extern "C" {}```

**Comment by luca-saggese** [comment]
work perfectly thanks!
