### ISSUE TITLE
Missing include into dac.h

### ISSUE THREAD

**Issue by vgonet** [espressif/arduino-esp32#1500]
Hello,

### Hardware:
Board:							NodeMCU-32S (WROOM-32)
Core Installation/update date:			15/jun/2018
IDE name:							IDF component
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
In the file driver/dac.h, the type gpio_num_t used by the following function is unknown.

esp_err_t dac_pad_get_io_num(dac_channel_t channel, gpio_num_t *gpio_num);

Thank you very much. Best regards.
Vincent

### Sketch:
#include "driver/gpio.h"

### Debug Messages:
C:/msys32/home/xxx/esp/esp-idf/components/driver/include/driver/dac.h:44:53: error: unknown type name 'gpio_num_t'

**Comment by lbernstone** [comment]
Yep.  You can `#include "driver/gpio.h"` until a PR gets put in place.
