### ISSUE TITLE
Reduce memory impact of SD with configurable max_files

### ISSUE THREAD

**Issue by LaurentLouf** [espressif/arduino-esp32#1502]
Is there any way to make this parameter configurable ? As stated here https://www.esp32.com/viewtopic.php?t=5987 , this seems like a good way to reduce the memory impact of SD, which is quite huge at 27k. 

The concerned line is : https://github.com/espressif/arduino-esp32/blob/89859f7f4c07ce3e5d487a4b689dbda78f5d5c3a/libraries/SD_MMC/src/SD_MMC.cpp#L56

**Comment by lbernstone** [comment]
How much does it go down if you set it to 1 or 2?

**Comment by LaurentLouf** [comment]
According to the post mentioned, along with  the reduction of menuconfig > Component config > Wear levelling and change sector size from 4096 bytes to 512 bytes, it can go from 27k of heap to 3k of heap, that's fairly huge.
