### ISSUE TITLE
ESP32 equivalent of the ESP8266 "custom_crash_callback" function?

### ISSUE THREAD

**Issue by Rob58329** [espressif/arduino-esp32#1517]
Board: NodeMCU-32S
SW: Arduino-IDE with latest "github.com/espressif/arduino-esp32" software (as at 19Jun18)

To run your own code whenever there is an exception, for the ESP8266 you can use the function:
"extern "C" void custom_crash_callback(struct rst_info * rst_info, uint32_t stack, uint32_t stack_end ) {...}"

This function actually seems to compile for the ESP32, but does not appear to do anything (ie. does not appear to be run when there is an exception such as a divide-by-zero).  Instead you just get the normal crash info in the IDE-Serial-Monitor and the ESP32 reboots (giving: rtc_get_reset_reason(1)=12 "SW_CPU_RESET").

[In my case, I am trying to use the callback-function to store crash-info (in the RTC-memory and EEPROM), which works for the ESP8266, but does not appear to work for the ESP32.]

Is there an equivalent working "custom_crash_callback" function for the ESP32?

Test code shown below:
[the boards I have tested with are:
(a) "Wemos-D1-mini (ESP8266)" which works
and (b) "NodeMCU-32S (ESP32)" which does NOT work!  ]

----------------------------------------------------------------------

```
#include <EEPROM.h>
byte eeprom_read;

void setup() {
  Serial.begin(74880); Serial.println(); Serial.println();
  Serial.println("TEST custom_crash_callback");
  Serial.println("--------------------------");
  EEPROM.begin(1);
  eeprom_read=EEPROM.read(0);
  if (eeprom_read!=255) {
    Serial.println("NB. after loading this sketch, remember that you have to re-boot...");
    Serial.println("...the ESP8266 at-least ONCE before it will self-restart successfully!");
  }
  Serial.print("read=");Serial.println(eeprom_read);
  if (eeprom_read==255) Serial.println("Got 255 so custom_crash_callback SUCCESSFUL");
  else Serial.println("Standard reboot (ie. NO crash_callback)");
  randomSeed(analogRead(A0)); // seed with random noise
  byte random_number=random(0,254);
  EEPROM.write(0, random_number); 
  Serial.print("write=");Serial.println(random_number);
  EEPROM.commit(); 
}

void loop() {
  if (eeprom_read==255) {Serial.println("Test FINISHED (press RESET to restart)"); while(true) delay(1000);}
  else {
    Serial.println("Instructions:"); 
    Serial.println("* EITHER press the ESP8266/ESP32 RESET-button NOW to similulate a normal-reboot");
    Serial.println("* OR just WAIT for 10 seconds to cause a divide-by-zero crash..."); 
    delay(10000);
    byte x=0; Serial.print(5/x); // cause a divide-by-zero crash
    // while (true) {}; // interestingly, this "while (true) {}" does NOT cause a crash for the ESP32
    Serial.println("CRASH FAILED");
  }
}

// NB. the below WORKS for the ESP8266 (WeMos D1 mini), but
// does NOT appear to be called for the ESP32 (NodeMCU-32S) 
extern "C" void custom_crash_callback(struct rst_info * rst_info, uint32_t stack, uint32_t stack_end ) {
    EEPROM.write(0, 255); // the crash signal!
    EEPROM.commit(); 
}
```

**Comment by voelkerb** [comment]
bump

**Comment by atanisoft** [comment]
@voelkerb @Rob58329 there is no similar functionality and it is also not guaranteed to be possible. By the time the esp32 has "crashed" the esp32 is not able to do much more than try and print a stacktrace and reboot. It sometimes can't even do that fully. There is no possibility to hook into this flow to call user code unfortunately, at least not that I've been able to find anywhere.

**Comment by Rob58329** [comment]
@atanisoft: Thank for your comment ("_There is no possibility to hook into this flow to call user code unfortunately_") - This is a pity, but what I had guessed might be the case.  Interesting that this works fine for the ESP8266 (and pretty reliably from my experience), but has not been implemented for the ESP32 - oh well!

**Comment by atanisoft** [comment]
@Rob58329 agreed, but at the point of the crash handler almost everything is unavailable. There may be options in esp-idf but they won't work in arduino-esp32 today

**Comment by vslinuxdotnet** [comment]
Any crash_callback available? or this option is dead ?

**Comment by Rob58329** [comment]
@vslinuxdotnet:  Sadly "ESP32 ... custom_crash_callback" functionality is still not available in "github.com/espressif/arduino-esp32" (as far as I can tell), as discussed above.

**Comment by MassimilianoMontagni98** [comment]
Hi,
any news?

Thanks

**Comment by Rob58329** [comment]
@MassimilianoMontagni98: Sadly "ESP32 ... custom_crash_callback" functionality is still not available in "github.com/espressif/arduino-esp32" as at Jan22 (as far as I can tell), as discussed above.

FYI. In my projects I have got round this by saving “got_to” numbers in rtc-memory, and then after an unexpected reboot printing/displaying the “got_to” number so I know where it crashed.

Often I can then identify a pre-cursor to the crash (in my projects this is often memory issues caused by failures in SSL network access).  Where this is the case I check amount of free RAM/Stack/Heap before the crashing process, and if not enough do a controlled ESP32-reboot instead of allowing the crashing process to run.

**Comment by atanisoft** [comment]
@MassimilianoMontagni98 @Rob58329 custom crash callback is not something that is available in ESP-IDF (the underlying library for arduino-esp32). 

However, the approach I've taken for tracking data across reboots is something like this:

```
...
#include <esp32/rom/rtc.h>

static constexpr uint32_t RTC_BOOL_FALSE = 0;

static uint32_t RTC_NOINIT_ATTR bootloader_request;

void init(uint8_t reset_reason)
{
  if (reset_reason == POWERON_RESET)
  {
    bootloader_request = RTC_BOOL_FALSE;
  }
}

void setup()
{
  init(rtc_get_reset_reason(PRO_CPU_NUM));
}

```
