### ISSUE TITLE
Adding the WiPy 3.0 board

### ISSUE THREAD

**Issue by korstiaanS** [espressif/arduino-esp32#1519]
Hi,

Can somebody help/add the WiPy3.0 board?
I do not know how to do it.

This is a nice board with internal/**external** antenna, WS2812 RGB led, 8MB flash, ...
(Do not use the expansion board to connect, it is not compatible with Arduino or ESP-IDF. Just use a separate usb convertor and connect the DTR and RTS lines))
[https://pycom.io/product/wipy-3](https://pycom.io/product/wipy-3/)
Pins, etc...
[https://docs.pycom.io/chapter/datasheets/development/wipy3.html](https://docs.pycom.io/chapter/datasheets/development/wipy3.html)

Thanks for helping.

**Comment by copercini** [comment]
@korstiaanS please open a Pull request with this variant, it will certainly help other people with the same board =)

**Comment by korstiaanS** [comment]
Is added!
