### ISSUE TITLE
about wifi connect

### ISSUE THREAD

**Issue by 1163167506** [espressif/arduino-esp32#1523]
### Description:
I turn off the router first, then turn on esp32 to show that I am connecting WiFi and then turn on the router, but esp32 will never connect to the router forever. 

this is why

### Sketch:
#include "WiFi.h"
#include "esp_wifi.h"
//#include "esp_wifi_types.h"
const char* ssid ="UT-9061";  

const char* ssid2 ="TP-LINK_BE5F";  
const char*password2 =  "yutaikeji123456@";  

const char* ssid3 ="zhangfeitest";  
const char*password3 =  "13688313408";

const char* ssid4 ="zftest";
const char*password4 =  "12345678";

void setup()  
{  
  Serial.begin(115200);  
  delay(10);
  Serial.println("##################"); 
  //WiFi.disconnect(true);
  delay(1000);
  WiFi.mode(WIFI_STA);

  
  WiFi.begin(ssid2, password2);  
  while (WiFi.status()!= WL_CONNECTED) {  
    delay(500);  
    Serial.println("Connectingto WiFi..");  
  }  
  
  Serial.println("Connectedto the WiFi network");  
  Serial.print("IP address:\t");
  Serial.println(WiFi.localIP()); 
}  
void loop() { 
  
  delay(1000);
  
  Serial.print("IP address:\t");
  Serial.println(WiFi.localIP());
  
  Serial.print("channel:");
  Serial.print(WiFi.channel());

  Serial.print("rssi:");
  Serial.print(WiFi.RSSI());
   
} 
### Debug Messages:
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13256
entry 0x40078a90
##################
Connectingto WiFi..
Connectingto WiFi..
Connectingto WiFi..
Connectingto WiFi..
Connectingto WiFi..

**Comment by lbernstone** [comment]
Please try to run `python esptool.py erase_flash` from the command line to make sure your nvs is cleared and try again.  Your code is OK, and if that AP is good, it should connect.  You don't need the WiFi.mode line in there, but it certainly shouldn't hurt anything.  Can you try the WiFiScan example and make sure you can see the network?  Some devices have extremely poor antennae, and will not connect to weak (or even moderate) signals.
