### ISSUE TITLE
Hardware timer register must be declare as volatile?

### ISSUE THREAD

**Issue by kawakami-k** [espressif/arduino-esp32#1530]
### Description:
Because the hw_timer register is not declared as volatile, it causes potential bugs.
(Compiler optimization may omit register write, or reorder memory accesses.) 
Should we fix as follows?

### Original implementation in esp32-hal-timer.c:
typedef struct hw_timer_s {
        hw_timer_reg_t * dev;
        uint8_t num;
        uint8_t group;
        uint8_t timer;
        portMUX_TYPE lock;
} hw_timer_t;

### Revised implementation in esp32-hal-timer.c:
typedef struct hw_timer_s {
        volatile hw_timer_reg_t * dev;
        uint8_t num;
        uint8_t group;
        uint8_t timer;
        portMUX_TYPE lock;
} hw_timer_t;

**Comment by lbernstone** [comment]
You are more likely to get a response on this if you submit a PR.
