### ISSUE TITLE
Question about uart interrupt

### ISSUE THREAD

**Issue by sysizlayan** [espressif/arduino-esp32#1532]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:		25.06.2018
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:					921600

### Description:
Hi,
I am using the HardwareSerial for uart communication.  My device simply sends and receives 8-byte packages for communication. Sending from esp32 is working without a problem, but while receiving sometimes I cannot get full 8 bytes and also there are remaining characters in hardware buffer.
For example:
I am supposed to receive:
"00 00 00 00 24 00 00 24" message
To get that, I first set the timeout to 2 seconds and call Serial.readBytes(buffer, 8); to get that.
Problem here is I sometimes get 6 or 7 bytes from Serial.available command.
I dived into uart _hal code and saw that, Hardware serial simply reads all of the available characters into a queue and returns the number of characters inside of this queue. However, some of the bytes coming from my device remains in the hardware buffer. I understand that when I read the next message, first character of the message is the last character which I suppose to read inside the last message.

My question is what are the conditions of the UART interrupt so that characters can be written to queue?
```
void uartEnableInterrupt(uart_t* uart)
{
    UART_MUTEX_LOCK();
    uart->dev->conf1.rxfifo_full_thrhd = 112;
    uart->dev->conf1.rx_tout_thrhd = 2;
    uart->dev->conf1.rx_tout_en = 1;
    uart->dev->int_ena.rxfifo_full = 1;
    uart->dev->int_ena.frm_err = 1;
    uart->dev->int_ena.rxfifo_tout = 1;
    uart->dev->int_clr.val = 0xffffffff;

    esp_intr_alloc(UART_INTR_SOURCE(uart->num), (int)ESP_INTR_FLAG_IRAM, _uart_isr, NULL, &uart->intr_handle);
    UART_MUTEX_UNLOCK();
}

```
I am seeing only 112 bytes of buffer is allowed, more than that causes fifo_full interrupt.
  uart->dev->conf1.rx_tout_thrhd = 2; --> I do not understand this line. This causes timeout as far as I understand but what is the unit? 2 characters? 2 Os ticks?

As far as I understand, some higher priority task cuts the interrupt and one or two characters remains in the hardware buffer. 

Thanks in advance.

**Comment by stickbreaker** [comment]
Fixed in v1.0.2 buffer draining
