### ISSUE TITLE
SPI problems after commit a59eafb

### ISSUE THREAD

**Issue by MarkyAD** [espressif/arduino-esp32#1547]
A couple of my projects with spi tft displays stopped working after the latest commits of June 27, 2018. No crash, the wifi connects and i2c works, but the displays no longer init. Reverting to commit 7abd586 gets them working again. Nothing in debug output except:

E (194) spiram: SPI RAM enabled but initialization failed. Bailing out.

**Comment by me-no-dev** [comment]
hm... I see no reason for this behaviour. Can you debug it a bit more please?

**Comment by me-no-dev** [comment]
BTW SPI RAM message you can ignore

**Comment by MarkyAD** [comment]
Yep, I'll try to dig some more later today.

**Comment by me-no-dev** [comment]
I had a user complain that he did not see data on MISO/MOSI. Just a clue for you to check :)

**Comment by negativekelvin** [comment]
Which spi peripheral are you using and what pins?

**Comment by MarkyAD** [comment]
ili9341 tft. MOSI=23 SCLK=18 CS=5. Looked further and I definitely have activity on both MOSI and SCLK which doesnt look any different than the working version. Possibly something with the display library (TFT_eSPI), I'm not sure, its always worked until this commit.

**Comment by MarkyAD** [comment]
@me-no-dev your latest commit has fixed this problem. Closing and thanks for all the excellent work.

**Comment by me-no-dev** [comment]
you welcome :)

**Comment by fedy0** [comment]
@me-no-dev 
I ran into the same problem as @MarkyAD 
After your latest commit, my dev board couldn't run. Always Rebooting.
I updated my arduino-esp32 core again and compile but still ran into the same problem or rebooting

Board: NODEMCU-32S
IDE: arduino-1.8.5

**Comment by HCnorth** [comment]
@me-no-dev 
Tried your commit, received following error:

WiFiAP.cpp:167:40: error: 'REQUESTED_IP_ADDRESS' was not declared in this scope

Board: Adafruit Feather Esp32
IDE: arduino-1.8.5

**Comment by me-no-dev** [comment]
@fedy0 do you have any serial output/decoded exception?

@HCnorth something is not right in your env. Might be missing files from the repo. Try to reinstall or use board manager with url: https://dl.espressif.com/dl/package_esp32_dev_index.json

**Comment by HCnorth** [comment]
Thanks for fast responce!
I just tried your fork (to be fair, your libraries and package folder in the main lib) 
and my device works, fine!
.. ist there a problem in these folder in the main lib ?

I am new in this comunity by using it active .. and i am impressed.

**Comment by fedy0** [comment]
@me-no-dev 
There is no decoded exception

Here is the serial output
![serialoutput](https://user-images.githubusercontent.com/26013847/42239156-f9329a26-7efa-11e8-8bca-d6967f88ebf7.JPG)

**Comment by me-no-dev** [comment]
@HCnorth which fork?

@fedy0 can you enable debug (not all boards have it available but the dev board does)

**Comment by fedy0** [comment]
@me-no-dev
Sorry, It was my mistake. After a merge to a working directory where i tampered with the partition, there was a memory misalignment.
Nevertheless Thanks
