### ISSUE TITLE
Data on Serial2, even though not initialized

### ISSUE THREAD

**Issue by thomasklingbeil** [espressif/arduino-esp32#1550]
### Hardware:
Board:							DoIT ESP32
Core Installation/update date:			27/jun/2018 (a59eafbc9dfa3ce818c110f996eebf68d755be24)
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
For our application, we have used RX2 and TX2 on the DoIT ESP32 board (GPIO 16&17) for other purposes. This worked until recently, but not it seems, there is serial data being sent on those pins, even though I haven't initialized anything (i.e. I use an empty sketch).

I understand that there is the boot information on the first serial port, with which I am fine. But is there any way to prevent action on the other serial ports?

### Sketch:
```cpp
void setup() {
}

void loop() {
}
```

**Comment by hex86** [comment]
I tried updating my arduino-esp32 yesterday and also had significant problems with the hardwareserial 2 not working under conditions like the USB being connected but would immediately start working when unplugged and running off battery power on the adafruit feather. Had to roll back to a much older version for my projects to work as expected again.

**Comment by thomasklingbeil** [comment]
I did another little test today. Connected two LEDs to RX2/TX2 (i.e. GPIO16/17) and 3.3V with the sketch below.

On the most recent version RX2 seems to stay `HIGH` and TX2 `LOW` (only during boot both seem to be high(ish)).

![img_1819](https://user-images.githubusercontent.com/190958/42085754-938e2f08-7b91-11e8-81dd-187ecfd3aa5a.gif)

With an older version of arduino-esp32 everything works as I expected it to work.

![bild von ios](https://user-images.githubusercontent.com/190958/42085797-a811e9d8-7b91-11e8-8978-bd343de88b4e.gif)


```cpp
void setup() {
  pinMode(16, OUTPUT);
  pinMode(17, OUTPUT);
}

void loop() {
  digitalWrite(16, HIGH);
  digitalWrite(17, LOW);

  delay(500);
  digitalWrite(16, LOW);
  digitalWrite(17, HIGH);

  delay(500);
  }
```

**Comment by me-no-dev** [comment]
hmm... I will look into this and see what IDF guys think of it

**Comment by thomasklingbeil** [comment]
Thank you! @me-no-dev: Is there anything I can do to support?
