### ISSUE TITLE
I do not know where to find Core Installation / update date

### ISSUE THREAD

**Issue by odilonafonso** [espressif/arduino-esp32#1553]
### Hardware:
Board:							ESP32 DevkitV1
Core Installation/update date:			?do not know where to see this information?
IDE name:						Arduino IDE 1.8.5
Flash Frequency:					80Mhz
Upload Speed:						921600

### Description:
I do not know where to find Core Installation / update date

**Comment by lbernstone** [comment]
Release versions are coming soon. For now, just indicate whether you have pulled the latest git version.

**Comment by odilonafonso** [comment]
thanks @lbernstone
