### ISSUE TITLE
HTTPClient can't work in AP mode

### ISSUE THREAD

**Issue by Cooper-WJH** [espressif/arduino-esp32#1560]
### Hardware:
Board:							ESP32-PICO-KIT V4
Core Installation/update date:		Null
IDE name:						Eclipse
Flash Frequency:					40Mhz
Upload Speed:					921600

### Description:
Hi

I can use HTTPClient GET & POST in STA mode. But when ESP32 work in AP mode, I can't sent GET & POST request to the STA node which connects to AP and got IP.

Can't HTTPClient GET & POST work in AP mode?

**Comment by everslick** [comment]
AFAIK, there should be absolutely no difference for HTTPCLient. Are you sure you connect to the right IP (URL)? Is the webserver running on the ESP that connects to your ESP in AP mode?

**Comment by copercini** [comment]
What is your test scenario ?

**Comment by sysizlayan** [comment]
If your case is just AP mode, it is natural because in AP mode, esp32 waits for some client to connect itself.

Try AP_STA mode instead and be sure you have supplied necessary SSID and password for internet connection.
