### ISSUE TITLE
Compilation error after pulling the last commit

### ISSUE THREAD

**Issue by sysizlayan** [espressif/arduino-esp32#1573]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:		02.07.2018
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:					921600

### Description:
I get the compilation error after pulling the last commit. Probably due to idf component rebuilds. It was building before the pull. Please check.
![image](https://user-images.githubusercontent.com/6679898/42170019-0d7878d0-7e1e-11e8-902a-399057a84f57.png)

**Comment by dsptech** [comment]
#1559
