### ISSUE TITLE
arduino How to upgrade the compiled firmware

### ISSUE THREAD

**Issue by 1163167506** [espressif/arduino-esp32#1578]
### Hardware:
Board:							?ESP32 Dev Module?
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
arduino How to upgrade the compiled firmware 
like test.ino.esp32.bin

**Comment by karan6190** [comment]
So are you talking about an upgrade to bin file or what ??

**Comment by lbernstone** [comment]
The correct answer: Get the source code and compile/flash.
How I would do it: `python esptool.py write_flash 0x10000 ./test.ino.esp32.bin`
There are a ton of assumptions in that, mainly that you are using the default partition scheme and the bootloader on your device matches what that bin expects.
