### ISSUE TITLE
webpage content delivery slow after git update

### ISSUE THREAD

**Issue by sirluckyluke** [espressif/arduino-esp32#1581]
### Hardware:
Board:							ESP32 Dev Module

### Description:
I have setup my esp32-dev-module in AP mode and it delivers a website from the internal flash to the logged in user. For this, I used the git version (core) from 28 March and it worked fine. I decided to make a git pull to the newest version and now the content delivery is really slow...sometimes it crashes, sometimes it delivers just the half of the content. 

I replaced the core and the library files with my old version, but the problem still occurs. So it must be something internal... Did someone experience the same behaviour after the update?

**Comment by barneyman** [comment]
i've just ported some 8266 code to 32 (downloaded this GIT today). My code serves static pages and constructed JSON, both are much slower on the 32 (it's a goouuu-esp32 dev board) than the wemosD1

All the web-requests take at least 2 seconds to respond (chrome/inspect/network), the one's doing 'nothing' are 2.0s exactly!

**Comment by me-no-dev** [comment]
yup we are looking into it :)

**Comment by everslick** [comment]
should be fixed in current master! please test and close issue, if it works for you.

**Comment by sirluckyluke** [comment]
thx...it works for me now :-)
