### ISSUE TITLE
Problems with UART2 when resetting ESP32 (it has been already fixed over the web)

### ISSUE THREAD

**Issue by euquiq** [espressif/arduino-esp32#1584]
Hi!

I use the three hardware serial ports on my ESP32. Problem is that when I restart the ESP32, UART1 and UART2 are corrupted. That is: I cannot get anything through them, no matter what. 

I did google it, and found out that this already has been discussed in here and other places:

https://www.esp32.com/viewtopic.php?t=4960

But never actually been fixed.

So the manual patch for now was:

1) search for espressif\esp32\cores\esp32\esp32-hal-uart.c
2) Find the sub  void uartFlush(uart_t* uart)
3) And replace the whole sub with:

```
void uartFlush(uart_t* uart)
{
    if(uart == NULL)
    {
    return;
    }
    UART_MUTEX_LOCK();
    while(uart->dev->status.rxfifo_cnt != 0 || (uart->dev->mem_rx_status.wr_addr != uart->dev->mem_rx_status.rd_addr))
    {
       READ_PERI_REG(UART_FIFO_REG(uart->num));
    }
UART_MUTEX_UNLOCK();
}
```

I am posting this iisue as reminder that the problem is still here, but there is already a "fix" (at least for me, it gives me back UART2 after an ESP.restart())

Regards,

Enrique

**Comment by me-no-dev** [comment]
Here it is :) https://github.com/espressif/arduino-esp32/commit/12ca9e8b521127c5455b8e45b463371cc0cc6d3d
