### ISSUE TITLE
Test WiFi stability

### ISSUE THREAD

**Issue by 1163167506** [espressif/arduino-esp32#1587]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							?ESP32 Dev Module?
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
Set esp32 to connect router to sta mode and turn on debug. 
Every half an hour, it will be printed
_eventCallback (): Event: 5 - STA_DISCONNECTED
_eventCallback (): Reason: 2 - AUTH_EXPIRE
And then quickly connect it to success
_eventCallback (): Event: 4 - STA_CONNECTED
_eventCallback (): Event: 7 - STA_GOT_IP
Why does this happen?
In what case there will be AUTH_EXPIRE
thanks

### Sketch:
```cpp

//Change the code below by your sketch
#include "WiFi.h"

const char *ssid     = "123456789";
const char *password = "123456789";

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  
 // WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
   /* WiFi.begin(ssid, password);
    delay(3500);*/
    Serial.print("..........");
  }
  randomSeed(micros());
  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

}

void loop() {
  
  // put your main code here, to run repeatedly:
   /* while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print("WiFi loop");
    ESP.restart();
    }*/

    Serial.println("connect wifi succeed ");
    delay(1000);
    
    Serial.print("IP address:\t");
    Serial.println(WiFi.localIP());

    Serial.print("channel:");
    Serial.println(WiFi.channel());

    Serial.print("rssi:");
    Serial.println(WiFi.RSSI());
}


### Debug Messages:
IP address:	192.168.143.247

channel:6

rssi:-61

connect wifi succeed 

IP address:	192.168.143.247

channel:6

rssi:-60

connect wifi succeed 

[D][WiFiGeneric.cpp:293] _eventCallback(): Event: 5 - STA_DISCONNECTED

[W][WiFiGeneric.cpp:298] _eventCallback(): Reason: 2 - AUTH_EXPIRE

IP address:	0.0.0.0

channel:1

rssi:0

connect wifi succeed 

IP address:	0.0.0.0

channel:11

rssi:0

connect wifi succeed 

IP address:	0.0.0.0

channel:14

rssi:0

connect wifi succeed 

[D][WiFiGeneric.cpp:293] _eventCallback(): Event: 4 - STA_CONNECTED

[D][WiFiGeneric.cpp:293] _eventCallback(): Event: 7 - STA_GOT_IP

IP address:	192.168.143.247

channel:6

rssi:-60

connect wifi succeed 

IP address:	192.168.143.247

channel:6

rssi:-60

connect wifi succeed 

IP address:	192.168.143.247

**Comment by stickbreaker** [comment]
@1163167506 
Your Routers DHCP lease timeout is set to 30 minutes. Reconfig your router if you want a longer period.  A router has a limited number of DHCP address available, When it issues an IP address, It cannot re-issue that ip address to another device until the lease time expires. You can increase the lease duration as long as you don't issue all of the ip address to new devices before the 'old' leases expire. 

 There is nothing wrong with the ESP32.

Chuck.

**Comment by 1163167506** [comment]
@stickbreaker  thanks！！！
