### ISSUE TITLE
HSPI issue

### ISSUE THREAD

**Issue by vidaxdu40** [espressif/arduino-esp32#1591]
### Hardware:
Board:							Sparkfun thing
Core Installation/update date:			
IDE name:							arduino
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
hello,
I have a problem using both VSPI and HSPI on the sparkfun, i am sending the same information on both bus (just for testing), with the VSPI everything works, but with the HSPI, i lose information some bits change. 
Do you have a solution ? 

### code:
this is my spi config:

const int spiClk = 1000000; // depende de la frequencia que hemos puesto en la configuracion simulink del spi_B (Baud rate)
SPIClass * spi1 = NULL;
SPIClass * spi2 = NULL;
void SPI_config() {
  spi1 = new SPIClass(VSPI);
  //initialise spi with default pins
  //SCLK = 18, MISO = 19, MOSI = 23, SS = 5
  spi1->begin(18,19,23,5);
  pinMode(5, OUTPUT); //SPI SS
  digitalWrite(5, HIGH);

  spi2 = new SPIClass(HSPI);
  //initialise spi2 with default pins
  //SCLK = 14, MISO = 12, MOSI = 13, SS = 15
  spi2->begin(14,12,13,15);
  pinMode(15, OUTPUT); //SPI SS
  digitalWrite(15, HIGH);

**Comment by PrateekGoyal18** [comment]
Could you make it work?
