### ISSUE TITLE
Issuse: pp.c 2998

### ISSUE THREAD

**Issue by stephmack** [espressif/arduino-esp32#16]
It appears that when I use the example "WiFiClientEvents" and after connecting to a router, anywhere from 10-30 seconds, a pp.c 2998 appears on the serial monitor and then it looks likes the system hangs.

Has anyone else seen this and knows what's going on?

I don't recall seeing this when I was using a different router at home vs. at work (i'll verify tonight)...  Could it have something to do with the router it's connected to?

Thanks,

Steve

_Update_
It seems that if I have something being printed every time the program loops (e.g. "still running") I don't get the pp.c 2998.

_Update 2_
I don't seem to have a problem with the connection when at home - which is a different router.

**Comment by me-no-dev** [comment]
this sisue should be now resolved. If you still have issues, feel free to reopen :)

**Comment by blmhemu** [comment]
@me-no-dev . I think this issue still persists. When i used OTA example code with D-Link router i got this error and system hangs. When i run the same code this time using mobile hotspot, it is done instantaneously. Something guess something is wrong with libraries cause the router is working fine.

**Comment by me-no-dev** [comment]
can you try this now again please :)
