### ISSUE TITLE
WifiMulti is not working!!!!!!!

### ISSUE THREAD

**Issue by williamesp2015** [espressif/arduino-esp32#1600]
### Hardware:
Board:							ESP32 Dev Module?
Core Installation/update date:			5/july/2018
IDE name:							Platform.io
Flash Frequency:					240Mhz?
Upload Speed:						115200?

### Description:
Describe your problem here

### Sketch:
```cpp
#include <WiFi.h>
#include <WiFiMulti.h>

WiFiMulti wifiMulti;

void setup()
{
    Serial.begin(115200);
    Serial.setDebugOutput(true);
    delay(2000);
delay(2000);
    wifiMulti.addAP("ADSL1", "MyPass**");
  //  wifiMulti.addAP("ssid_from_AP_2", "your_password_for_AP_2");
  //  wifiMulti.addAP("ssid_from_AP_3", "your_password_for_AP_3");

    Serial.println("Connecting Wifi...");
    if(wifiMulti.run() != WL_CONNECTED) {
      Serial.print(".");
      delay(500);
       }
      else
      {
        Serial.println("");
        Serial.println("WiFi connected");
        Serial.println("IP address: ");
        Serial.println(WiFi.localIP());
      }

    
}

void loop()
{
    if(wifiMulti.run() != WL_CONNECTED) {
        Serial.println("WiFi not connected!");
        delay(1000);
    }
      delay(300);
}
```
### Debug Messages:
```
Connecting Wifi...
```
Program stops here without restart or error

**Comment by lbernstone** [comment]
Sounds like power issues.  How are you plugged in?

**Comment by lbernstone** [comment]
Unable to reproduce (in Arduino IDE).  Is this a valid or invalid ssid/pw?  What type of AP?  Turn on core debug level to verbose and see how far it gets in the connection process before failing.

**Comment by williamesp2015** [comment]
Thanks lbernstone 

Connecting Wifi...
Exception in thread rx:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\users\am\.platformio\penv\lib\site-packages\serial\tools\miniter
m.py", line 445, in reader

    data = self.serial.read(self.serial.in_waiting or 1)
  File "c:\users\am\.platformio\penv\lib\site-packages\serial\serialwin32.p
y", line 257, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinE
rror()))
SerialException: ClearCommError failed (WindowsError(5, 'Access is denied.'
))

**Comment by lbernstone** [comment]
Looks like your terminal crashed.  This points even more at a power issue.  Try a different cable/USB port.

**Comment by williamesp2015** [comment]
I really appreciate. It solved using different USB port.
