### ISSUE TITLE
WIFI_AP_STA mode problem

### ISSUE THREAD

**Issue by usmanshahid001** [espressif/arduino-esp32#1602]
hi i have updated the arduino core for esp32 after that i am having some issues related to WIFI_AP_STA mode if i use this mode and use wifi.begin() ap will never connect with my phone and AP only working fine in WIFI_AP mode

**Comment by lbernstone** [comment]
Set core debug level to verbose and post some logs while you try to connect the phone.

**Comment by usmanshahid001** [comment]
I (2266) wifi: wifi driver task: 3ffb7328, prio:23, stack:4096, core=0
I (4592) wifi: wifi firmware version: 4fd6a2c
I (4592) wifi: config NVS flash: enabled
I (4595) wifi: config nano formating: disabled
I (4609) wifi: Init dynamic tx buffer num: 32
I (4609) wifi: Init data frame dynamic rx buffer num: 10
I (4609) wifi: Init management frame dynamic rx buffer num: 10
I (4614) wifi: Init static rx buffer size: 1600
I (4618) wifi: Init static rx buffer num: 4
I (4622) wifi: Init dynamic rx buffer num: 10
I (4683) wifi: mode : sta (b4:e6:2d:86:c0:01) + softAP (b4:e6:2d:86:c0:02)

**Comment by usmanshahid001** [comment]
I (6556) wifi: ap channel adjust o:7,1 n:9,2
I (6556) wifi: n:9 0, o:7 0, ap:9 2, sta:9 0, prof:7
I (7289) wifi: state: init -> auth (b0)
I (7292) wifi: state: auth -> assoc (0)
I (7298) wifi: state: assoc -> run (10)
I (7315) wifi: connected with GRESHAM EASTERN, channel 9
I (7361) wifi: pm start, type: 1

**Comment by usmanshahid001** [comment]
when i try to connect my AP i receive this verbose

I (59995) wifi: n:9 0, o:9 0, ap:9 2, sta:9 0, prof:9
I (59995) wifi: station: 24:77:03:6d:79:ec join, AID=1, bgn, 20
but it refuse to connect

**Comment by lbernstone** [comment]
I'm unable to reproduce.  Can you connect to the AP with another device?

**Comment by usmanshahid001** [comment]
are u using the latest commit?

**Comment by usmanshahid001** [comment]
so i used the basic authentication code here with ap_sta


#include <WiFi.h>
#include <WiFiClient.h>
#include "includes.h"
#include "WiFiAP.h"
#include "esp_log.h"
HardwareSerial hmi(1);
IPAddress gateway(192, 168, 1, 1);
IPAddress subnet(255, 255, 255, 0);
IPAddress DNS(192, 168, 1, 249);
WiFiClient client[my_client];
 
hw_timer_t * timer = NULL;
portMUX_TYPE timerMux = portMUX_INITIALIZER_UNLOCKED;
///////////////////////////////////////////////////////////////////////// 
void IRAM_ATTR onTimer(){
        
        portENTER_CRITICAL_ISR(&timerMux);
        if(info.start_totalizer==1)
        {
        info.temp+=info.curr_flow;
        if((uint16_t)info.temp>=1)
        {
          Total_s.Total+=(uint16_t)info.temp;
          
          if(Total_s.Total>4294967290)
          Total_s.Total=0;
          info.temp-=(uint16_t)info.temp;
        }
        }
        if(mywdt>6)
        esp_restart_noos();
        mywdt++;
        digitalWrite(led_pin,link1);
        if(link1==0)
        link1=1;
        else
        link1=0;
        portEXIT_CRITICAL_ISR(&timerMux);
        
        
}


void setup() {
      Wire.begin(SCL,SDL,FREQUENCY );
 
      delay(1000);
      Serial.begin(115200);
      esp_log_level_set("*", ESP_LOG_VERBOSE);
      My_functions.feedback();
      app_init();
      My_functions.feedback();
      delay(10);
      My_functions.feedback();
      delay(1000);
      Time_Date.read_time();
      My_functions.feedback();delay(10);
      My_functions.feedback();
      initialization();
      analogReadResolution(12);
      analogSetPinAttenuation(A0, ADC_0db);
      analogSetPinAttenuation(A1, ADC_0db);
      xMutex = xSemaphoreCreateMutex();
      xMutex_client=xSemaphoreCreateMutex();
      
      
      xTaskCreate(client_tasks,"client_tasks",10000,NULL,(configMAX_PRIORITIES - 4),&client_Tasks);
      xTaskCreate(flow_cal_task,"flow_cal_task",4096,NULL,(configMAX_PRIORITIES - 2),&flow);
      xTaskCreate(time_take,"time_take",4096,NULL,(configMAX_PRIORITIES - 3),&time_taker);
      xTaskCreate(save_total_task,"save_total_task",4096,NULL,(configMAX_PRIORITIES - 1),&save_total);
      xTaskCreate(wifi_tasks,"wifi_tasks",4096,NULL,(configMAX_PRIORITIES - 5),&wifi_Tasks);
      xTaskCreate(TAB_task,"TAB_task",4096,NULL,(configMAX_PRIORITIES - 6),&tab);
      xTaskCreate(WDT_TASK,"WDT_TASK",4096,NULL,(configMAX_PRIORITIES - 7),&wdt_Handle);
      xTaskCreate(reconnect,"reconnect",4096,NULL,(configMAX_PRIORITIES - 7),&reconnect_Handle);
      xTaskCreate(hmi_task,"hmi_task",4096,NULL,(configMAX_PRIORITIES -8),&Hmi_task);
      esp_task_wdt_init(500,0);
      
   
   
}
 
void loop() {
      
       vTaskDelay( xDelay_one_second*300); 
       
}



void flow_cal_task(void * pvParameters)
{
    esp_task_wdt_add(NULL);
    vTaskDelay( xDelay_one_second*3);
    while(true)
    {
            portENTER_CRITICAL(&timerMux);
            My_functions.calculate_flow();
            portEXIT_CRITICAL(&timerMux);
            esp_task_wdt_reset(); 
            vTaskDelay( xDelay_one_second);
     
    }
}

void wifi_tasks(void * pvParameters)
{
           
           esp_task_wdt_add(NULL); 
           while(true){
           
           Server_handles.call_server_handler();
            
           
           esp_task_wdt_reset();
           vTaskDelay(200);    
}
 
}


void save_total_task(void * pvParameters)
{
            esp_task_wdt_add(NULL);
            vTaskDelay( xDelay_one_second*30 );
            while(true)
            {
                
                xSemaphoreTake(xMutex,portMAX_DELAY);
                eprom.save_total();
                
                esp_task_wdt_reset();
                xSemaphoreGive(xMutex);
                if(schedule_restart>96)
                esp_restart_noos();
                else
                schedule_restart++;
                vTaskDelay(xDelay_one_second*300);
             
            }
}
void client_tasks(void * pvParameters)
{
     
         if(!communication.pc_comm_enable)
         vTaskSuspend(client_Tasks);
         esp_task_wdt_add(NULL);
         My_functions.feedback();delay(10);My_functions.feedback();
         client[PC].connect(communication.HOST_PC,communication.PORT);
         while(true){
          
        
         xSemaphoreTake(xMutex_client,portMAX_DELAY);
         String line;
         if(pc_port_connection&&wifi_connection)
            {
             
              Serial.println("sending data to pc");
              communication.post_task();
              communication.printer();
              int sent_data_bits=client[PC].print(communication.final_string);
              vTaskDelay( xDelay_one_second*2);
              int received_response_bytes=client[PC].available();
              if(sent_data_bits<200||received_response_bytes<100)
              disconnected++;
              if(communication.modebus_enable)
              {
              
              while(client[PC].available())
              line = client[PC].readString();
              Serial.print(line);
              }  
              }  
              
              esp_task_wdt_reset();
              xSemaphoreGive(xMutex_client);
              vTaskDelay( xDelay_one_second*communication.pc_log_interval);   
              } 
              }
        
        
 
void TAB_task(void * pvParameters )
{
            if(!communication.tab_comm_enable)
            vTaskSuspend(tab);
            client[TAB].connect(communication.HOST_TAB,communication.PORT);
            esp_task_wdt_add(NULL);
            vTaskDelay( xDelay_one_second*30);
            while(true)
              {
                Serial.println("sending data to TAB");
                xSemaphoreTake(xMutex_client,portMAX_DELAY);
                String line;
            if(tab_port_connection&&wifi_connection)
             {
           
              communication.post_task();
              communication.printer_TAB(); 
              int sent_data_bits=client[TAB].print(communication.final_string);
              vTaskDelay( xDelay_one_second*2);
              int received_response_bytes=client[TAB].available();
              if(sent_data_bits<200||received_response_bytes<100)
              disconnected++;
              if(communication.modebus_enable)
              {
              while(client[TAB].available())
              line = client[TAB].readString();
              Serial.print(line);
              }  
             
              esp_task_wdt_reset();
              xSemaphoreGive(xMutex_client);
              vTaskDelay( xDelay_one_second*communication.tab_log_interval);
           }
}
}
void WDT_TASK(void * pvParameters)
{
            esp_task_wdt_add(NULL);
             while(true)
             {
              
              portENTER_CRITICAL(&timerMux);
              mywdt=0;
              portEXIT_CRITICAL(&timerMux);
              My_functions.feedback();
              esp_task_wdt_reset();
              vTaskDelay( xDelay_one_second*2);
             }
}

void time_take(void * pvParameters)
{            
            esp_task_wdt_add(NULL);
             while(true)
             {
              
              xSemaphoreTake(xMutex,portMAX_DELAY);
              Time_Date.read_time();
              esp_task_wdt_reset();
              xSemaphoreGive(xMutex);
              vTaskDelay( xDelay_one_second*60);
             }
}
void hmi_task(void * pvParameters)
{            
            vTaskDelay( xDelay_one_second*5);
            if(!communication.tft_enable)
            vTaskSuspend(Hmi_task);
            hmi.begin(9600,SERIAL_8N2,17,16);
            vTaskDelay( xDelay_one_second*3);
            esp_task_wdt_add(NULL);
            bool hmi_link=0;
            hmi_print();
             while(true)
             {
              
              
              hmi.printf("VALUES.line_temp.txt=\"%u\"",(uint16_t)info.PtTmp);
              hmi_print();
              hmi.printf("VALUES.line_pressure.txt=\"%u\"",(uint16_t)info.pressure);
              hmi_print();
              hmi.printf("VALUES.line_size.txt=\"%0.3f\"",info.line_size);//
              hmi_print();
              hmi.printf("VALUES.output.txt=\"%u\"",(uint16_t)info.output);
              hmi_print();
              hmi.printf("VALUES.d_pressure.txt=\"%0.1f\"",info.d_pressure);
              hmi_print();
              hmi.printf("VALUES.d_coeff.txt=\"%0.2f\"",info.compressibility);
              hmi_print();
              hmi.printf("VALUES.density.txt=\"%0.2f\"",info.density);
              hmi_print();
              
              if(hmi_link==1)
              hmi_link=0;
              else
              hmi_link=1;
              hmi.printf("VALUES.c0.val=%u",hmi_link);
              hmi_print();
              portENTER_CRITICAL(&timerMux);
              hmi.printf("VALUES.com_flow.txt=\"%u\"",(uint16_t)info.compensated_flow);
              hmi_print();
              hmi.printf("VALUES.total.txt=\"%0.3f\"",(double)Total_s.Total/1000);
              hmi_print();
              
              portEXIT_CRITICAL(&timerMux);
              esp_task_wdt_reset();
              vTaskDelay( xDelay_one_second*2);
            }
}
void reconnect(void * pvParameters)
{            
            
            if(!communication.wifi_auto_reconnect)
            vTaskSuspend(reconnect_Handle);
            esp_task_wdt_add(NULL);
             while(true)
             {
               if(disconnected>30)
              {
                esp_restart_noos();
              }
              if(WiFi.status() != WL_CONNECTED)
              {
                WiFi.reconnect();
                wifi_connection=0;
                disconnected++;
              }
              else
              {
                wifi_connection=1;
                if(!got_static_ip&&!communication.dhcp)
                {
                IPAddress ip(communication.static_ip[0],communication.static_ip[1],communication.static_ip[2],communication.static_ip[3]);
                WiFi.config(ip, gateway, subnet, DNS);
                got_static_ip=1;
                Serial.println(WiFi.localIP());
                }
                if(communication.pc_comm_enable==1)
                {
                  if(client[PC].connect(communication.HOST_PC,communication.PORT))
                  pc_port_connection=1;
                  else
                  {
                    pc_port_connection=0;
                    disconnected++;
                  }
                  
                }
                if(communication.tab_comm_enable==1)
                {
                  if(client[PC].connect(communication.HOST_PC,communication.PORT))
                  tab_port_connection=1;
                  else
                  {
                    tab_port_connection=0;
                    disconnected++;
                  }
                  
                }
              }
              
              esp_task_wdt_reset();
              Serial.println("reporting from wifi autoreconnect");
              vTaskDelay( xDelay_one_second*30);
            }
}
void initialization()
{
        
        uint32_t time_out=millis();bool reset=0;
        WiFi.mode(WIFI_AP_STA);
        bool x=WiFi.softAP("new_firmware","43255234",6);
        Serial.println("ap configuration");
        Serial.println(x);
        delay(1000);
      WiFi.begin("GRESHM EASTERN","lhrgel1947");
    while (((WiFi.status() != WL_CONNECTED))&&(millis()-time_out)<20000)
        {
          if(((millis()-time_out)>10000)&&!reset)
          {
          
          reset=true;
          My_functions.feedback();
         WiFi.reconnect();
          }
          My_functions.feedback();
          delay(1000);
          Serial.println("Establishing connection to WiFi..");
        }
       IPAddress ip(communication.static_ip[0],communication.static_ip[1],communication.static_ip[2],communication.static_ip[3]);  
        
     /* if(!communication.dhcp&&WiFi.status()== WL_CONNECTED)
        {
        WiFi.config(ip, gateway, subnet, DNS);
        got_static_ip=1;
        }
        Serial.println(WiFi.localIP());  */
        My_functions.feedback();delay(10);My_functions.feedback();
       initialize_server();
         
        delay(1000);
        startTimer();
        
}
void hmi_print()
{
            hmi.write(255);
            hmi.write(255);
            hmi.write(255 );
}


void startTimer()
{
      timer = timerBegin(0, 80, true); 
      timerAttachInterrupt(timer, &onTimer, true); 
      timerAlarmWrite(timer, 1000000, true); 
      timerAlarmEnable(timer);
}

**Comment by usmanshahid001** [comment]
whenever i try to connect i receive these verbose but i am unable to connect


I (55155) wifi: n:9 0, o:9 0, ap:9 2, sta:9 0, prof:9
I (55155) wifi: station: 24:77:03:6d:79:ec join, AID=1, bg, 20

**Comment by usmanshahid001** [comment]
problem occurs when wifi.begin() is call

**Comment by usmanshahid001** [comment]
system says password is incorrect but it works when i do not call wifi.begin

**Comment by stickbreaker** [comment]
@usmanshahid001 The ESP32 stores the successful connection info in NVS so without you specifically calling `Wifi.Begin()` it reuses the last successful credentials. Automagically logging in.

Chuck.

**Comment by lbernstone** [comment]
Note that the radio can only use one channel.  If you force the AP to use channel 6, and your STA needs a different channel, it may disconnect a client when it switches to the "correct" channel.

**Comment by usmanshahid001** [comment]
actually if i do not mention the channel AP never connects...actually i had working codes at previous commits may be 4 month old...today i updated my esp32 firmware now they are causing problem......

**Comment by usmanshahid001** [comment]
does anyone facing this problem

**Comment by zzpaf** [comment]
I am having the same exact problem. Removing WiFi.begin(ssid, password); AP mode works correctly, once WiFi.begin(ssid, password); is called, AP mode does not allow connection

**Comment by zzpaf** [comment]
> Note that the radio can only use one channel. If you force the AP to use channel 6, and your STA needs a different channel, it may disconnect a client when it switches to the "correct" channel.

This is a different behavior as in ESP8266, actually if client needs a different channel, AP will change channel, disconnecting current connections but will allow you to connect again, what happens now is that once you call Wifi.Begin() no matter what channel the client is using, the AP refuses any connections.

I would expect the same behavior as in ESP8266 where this work perfectly but as of now I can't get ESP32 connected both as AP and STA

**Comment by me21** [comment]
It's supposed to be fixed now in the latest release.

**Comment by pablodeymo** [comment]
I have the same problem that @usmanshahid001 described, using the ESP32 Dev Module.
I've downloaded the latest version of this repo, and I am using the files of _libraries/WiFi/src_ folder, and Arduino IDE version 1.8.9.

When ESP runs Wifi.begin(...), the AP **disappear** from the list of SSIDs.

Do you know if this problem is already fixed?

**Comment by asetyde** [comment]
WiFi has many problems also for me, I hope depends from update of ESP-IDF , hope is updated at last

**Comment by usmanshahid001** [comment]
i faced that problem when wifi.begin() failed to connect SSID due to wrong
password etc.if it connects successfully then i think AP connects..
