### ISSUE TITLE
Problem in enable 2 wake up source to wake up ESP32

### ISSUE THREAD

**Issue by beats0126** [espressif/arduino-esp32#1605]
i found the problem when i enable 2 different wake up mode.
it only function on the FIRST mode called.
below is my code :
void setup() {
	print_wakeup_reason();
	print_wakeup_touchpad();

	touchAttachInterrupt(T3, callback, Threshold);

	esp_sleep_enable_touchpad_wakeup();

	esp_sleep_enable_ext0_wakeup(GPIO_NUM_0, 0);
}

now it only wake up by the touch, but the second mode wake up with pin 0 cannot work.
is it any solution on this?

**Comment by kyrulkamal** [comment]
I have same issue with you.
