### ISSUE TITLE
Enabling BLE is causing WiFi connection to fail - any suggestions?

### ISSUE THREAD

**Issue by wegunterjr** [espressif/arduino-esp32#1606]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			July 2018
IDE name:							Platform.io
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
I am enabling BLE Server with notify to be available for client to connect and that appears to work, but when I try to enable WiFi later and connect to a SSID, then connect to an MQTT broker securely, I get back that it is failing - 
```

BLEDevice::init("iotDevice");
BLEServer *pServer = BLEDevice::createServer();

BLEService *pService = pServer->createService(SERVICE_UUID);

pCharacteristic = pService->createCharacteristic(
                    CHARACTERISTIC_UUID,
                    BLECharacteristic::PROPERTY_READ   |
                    BLECharacteristic::PROPERTY_WRITE  |
                    BLECharacteristic::PROPERTY_NOTIFY |
                    BLECharacteristic::PROPERTY_INDICATE
                                     );
BLEDescriptor *desc1= new BLEDescriptor(BLEUUID((uint16_t)0x2908));
const uint8_t desc1_val[] = {0x01, 0};
desc1->setValue((uint8_t*)desc1_val, 1);
pCharacteristic->addDescriptor(desc1);
pCharacteristic->addDescriptor(new BLE2902());

pCharacteristic->setCallbacks(new MyCallbacks());

char hex[] = {0xee,0xef};
pCharacteristic->setValue(hex);
pService->start();

BLEAdvertising *pAdvertising = pServer->getAdvertising();
pAdvertising->start();

while (status != WL_CONNECTED)
    {
        Serial.print("Attempting to connect to SSID: ");
        Serial.println(WIFI_SSID);
        // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
        status = WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

        // wait 5 seconds for connection:
        delay(5000);
    }

    Serial.println("Connected to wifi");
if(grillDevice.connect(HOST_ADDRESS,CLIENT_ID)== 0) // Connect to AWS using Host Address and Cliend ID
    {
        Serial.println("Connected to AWS");
        delay(1000);
    }
    else
    {
        Serial.println("AWS connection failed, Check the HOST Address");
        while(1);
    }

```

If I don't try and enable BLE before I do the WiFi connect, it connects just fine.

Am i supposed to separate the BLE setup and the WiFi Setup?
Do I need to disable the BLE then enable the WiFi, and vice Versa?
I want them both running at the same time once they are up and running.

**Comment by chegewara** [comment]
Hi,
its very hard to make it both work together. Its because ble is using a lot of ram and mbedTLS (ssl) needs a lot of ram for handshake. You can make it work togheter, but you need to free as much heap as you can before you even start, then connect with aws mqtt and when you are connected then you can finally connect to ble peer device.
In my app i am starting with over 200kB free heap and when i am connected to ble device i have about 20kB free heap.

**Comment by kapollo** [comment]
@chegewara how can you do that on Arduino, I mean free the heap before starting?

**Comment by chegewara** [comment]
https://github.com/chegewara/esp32-snippets/issues/2#issuecomment-405275150
