### ISSUE TITLE
Identify Version 

### ISSUE THREAD

**Issue by stickbreaker** [espressif/arduino-esp32#1610]
Can we set the name and version info in the `platform.txt` file to some identifiable values?

Currently `platfrom.txt` just defaults to:
>name=ESP32 Arduino
version=0.0.1

I would recommend it be changed for each version: 
>name=ESP32 Arduino RC1 
version=1.0.1rc

>name=ESP32 Arduino RC2
version=1.0.2rc

Chuck.

**Comment by lbernstone** [comment]
package.json has a spot for the version number as well.

**Comment by stickbreaker** [comment]
maybe even a new define:
>name=ESP32 Arduino RC2
version=1.0.0rc2
corename=ESP32_Arduino_RC2

I modified the `platform.txt`, changing the `build.extra_flags` to:
>build.extra_flags=-DESP32 -DCORE_DEBUG_LEVEL={build.code_debug} -DESP32_CORE_NAME="{corename}" -DESP32_CORE_VERSION="{version}"

`{name}` by itself was replaced with the `{board}.name` value, and embedded spaces also caused problems.
 
If we do this then we can easily identify which version is causing problems with:
```c++
Serial.printf("%s %s\n",ESP32_CORE_NAME,ESP32_CORE_VERSION);
```
Chuck.

**Comment by stickbreaker** [comment]
@me-no-dev I don't know how to inject it into `platform.txt`.  The reason I want it is that This name is displayed as the group header inside the Arduino Boards Selection pulldown.  I currently have 3 ESP32 sets of boards, My modified library, the Current Repo and RC2.  When they all said ESP32 is was a pain to use the correct "board/repo'.

How automated is your package process? Can we 'just' add a python script to your packaging process?

Chuck.

**Comment by me-no-dev** [comment]
you do not need to inject anything. there is a header in the package that you need to include. it's generated by the build script. Question is how to generate this when you are using git version and not a package

**Comment by me-no-dev** [comment]
can you elaborate a bit on this?

**Comment by lbernstone** [comment]
google knows far more than me. You could use python to modify a file when you pull/fetch from upstream, or even just sed.
https://www.startpage.com/do/dsearch?query=git+hook+modify+file+on+pull

**Comment by me-no-dev** [comment]
that is something else though. version in platform.txt will be updated now BTW (merged this morning).

**Comment by stickbreaker** [comment]
That is a good step.

 Can you append the version code to `name` field? that way under board manager it would be easy to see. 

I just noticed that the text in `platform.txt` is only uses `lf` termination. I hadn't noticed this before.

Chuck.
