### ISSUE TITLE
Trying to use arduino-esp32 as a component to the esp-idf get error:

### ISSUE THREAD

**Issue by esims11395** [espressif/arduino-esp32#1612]
I installed the arduino components inside of a simple esp32 example using this reference: https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md

When I run "make flash" i get this error: 
`$ make flash
CC build/arduino/cores/esp32/libb64/cencode.o
make[1]: execvp: xtensa-esp32-elf-gcc: Argument list too long
make[1]: *** [/home/Eric/esp/esp-idf/make/component_wrapper.mk:274: cores/esp32/libb64/cencode.o] Error 127
make: *** [C:/Users/Eric/Documents/msys32/home/Eric/esp/esp-idf/make/project.mk:450: component-arduino-build] Error 2
`
Looking at the make file, line 450 is:
`$(foreach component,$(COMPONENT_PATHS),$(eval $(call GenerateComponentTargets,$(component),$(notdir $(component)))))`

I'm not sure what to do about it. All help is appreciated. 

Thanks

**Comment by lbernstone** [comment]
Try moving to a shorter path.  Filepaths over 254 characters can cause issues.

**Comment by esims11395** [comment]
Thanks for the response. I checked my longest filepath and it was 113 chars. I ended up updating the esp-idf and that fixed it. Not sure what happened.

**Comment by QuadCorei8085** [comment]
fixed by #1853
