### ISSUE TITLE
Is there a way to determine between ESP32 Standard unit and an ESP32 WROVER unit?

### ISSUE THREAD

**Issue by SoftwareGuy** [espressif/arduino-esp32#1613]
### Hardware:
Not a hardware issue.

### Description:
Is there a reliable way like checking a register or something to determine if you have the extra on-board memory that the WROVER unit has? I have ordered a ESP32-WROVER Wemos board that is supposed to have 4MB of PSRAM vs the standard 520KB that the ESP32 normally has. However, I want to be able to access this extra RAM for application use.

I could check the esp_get_free_heap_size() counter on boot and if it's above a certain amount (usually that's around 223000 bytes on cold boot with Serial output active) then we're using a WROVER, but since I am using composite graphics code from bitluni (@me-no-dev probably knows what I'm talking about) the framebuffer does eat up a lot of RAM on a standard ESP32. Is there a function that I can call that asks the ESP32 to return a byte total of how much memory it knows about (ie. the grand total that it "sees").

How does the ESP32 handle this extra memory? Does it notice it and the RTOS adds it into it's memory manager? Or is there some special things going behind the scenes?

My idea is to be able to tell if the PSRAM is attached or not by some mechanism, and then alert the person controlling the ESP32 with a warning saying that they may suffer sudden reboots due to out of memory errors or other crazy things happening.

Thanks!

**Comment by cyberman54** [comment]
I'm using a ESP32 board with external PSRAM. Since Espressif32 v1.1.x core i get the extra RAM reported by esp_get_free_heap_size(), without any further tweaking of my software. So it may be sufficient if your application just checks the free RAM at startup.

Anyway, i also would be interested in a way to safely determine SoC type by software.

**Comment by dsptech** [comment]
Sorry, 
I've read now that the heap capability on SPI-RAM must be enabled in the ESP-IDF before compiling. 
I have do not know if a such option is enabled in the arduino library, but you could try.

**Comment by me-no-dev** [comment]
the option is now available (for the ESP32 dev board and on by default if you select WROVER module) and you have the functions `ps_malloc` and so on to manage PSRAM :)

**Comment by me-no-dev** [comment]
@cyberman54 while the chip revision can be detected, WROVER is just a normal ESP32 with extra chip added, so it will not show as different revision/chip.
There is also this (still requires you to select WROVER or enable PSRAM in the dev module)
```cpp
if(psramFound()){
  Serial.println("PSRAM was found and loaded");
}
```

**Comment by SoftwareGuy** [comment]
@me-no-dev would that work if we used the `#if` directive to wrap it to avoid it throwing a function not found compile error on non-PSRAM units?

```
#if HAS_PSRAM
if(psramFound()){
  Serial.println("PSRAM was found and loaded");
  // ....
}
#endif
```

**Comment by me-no-dev** [comment]
that function is already wrapped :) check esp32-hal-psram.c ;) if psram is disabled the function just returns false and no other code is compiled.

**Comment by SoftwareGuy** [comment]
Beauty. That solves my original issue - I can just check that and if it's anything other than false, we've got extra RAM.

Going to close this, but if there's any additional comments please keep the thread going. Cheers!
