### ISSUE TITLE
touchRead gives wrong value occasionally

### ISSUE THREAD

**Issue by glucee** [espressif/arduino-esp32#1615]
### Hardware:
Board:							ESP32 Huzzah
Core Installation/update date:		07/2018
IDE name:						Platform.io
Flash Frequency:					40Mhz
Upload Speed:					115200

### Description:
I use touchRead function in the loop to get the real-time value, I found the value is not always correct. When i don't touch it, it also occasionally gives wrong value. 

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
 Serial.begin(9600);
}

void loop() {
Serial.println(touchRead(15));
delay(100);
}
```

**Comment by me-no-dev** [comment]
yes, I have some new code that I need to add and it will work. Soon :)

**Comment by asetyde** [comment]
Soon .. when ? I also wait a bugfix :D thx

**Comment by l0rb** [comment]
This is still an issue, should be opened again.

**Comment by selman-nus** [comment]
Agreed, i see random values with 100ms delay.
