### ISSUE TITLE
SmartConfig example doesn't finish properly with ESPTouch android app

### ISSUE THREAD

**Issue by bzhang222** [espressif/arduino-esp32#1639]
### Hardware:
Board:							ESP32 WROOM
Core Installation/update date:			5/1/2018
IDE name:							Arduino IDE 
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
on ESP-32 module, I installed Arduino SmartConfig example, on Android device I installed ESPTouch Android App, I added comment in the smartConfig and I can see password/id is sent to device; and device is able to connect to WIFI AP successfully. But  android app ends with "ESPTouch Fail" message

This is a problem because when integrated with other part of android app, android app reports no device gets configured

### Sketch:
same as smartconfigure example
 #include "WiFi.h"

void setup() {
  Serial.begin(115200);

  //Init WiFi as Station, start SmartConfig
  WiFi.mode(WIFI_AP_STA);
  WiFi.beginSmartConfig();

  //Wait for SmartConfig packet from mobile
  Serial.println("Waiting for SmartConfig.");
  while (!WiFi.smartConfigDone()) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("SmartConfig received.");

  //Wait for WiFi to connect to AP
  Serial.println("Waiting for WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("WiFi Connected.");

  Serial.print("IP Address: ");
  Serial.println(WiFi.localIP());
  Serial.println(WiFi.SSID());
  
}

void loop() {
  // put your main code here, to run repeatedly:

}
### Debug Messages:
.................
SmartConfig received.
Waiting for WiFi
.....WiFi Connected.
IP Address: 10.0.0.153
busybox2

**Comment by chinswain** [comment]
Try using WIFI_STA instead if WIFI_AP_STA
