### ISSUE TITLE
about add pictures

### ISSUE THREAD

**Issue by 1163167506** [espressif/arduino-esp32#1649]
I used Arduino esp32 to make a web server, but how to add pictures.
thanks！！！

**Comment by per1234** [comment]
You are [consistently ](https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3A1163167506)submitting invalid issue reports to this repository. Issues are to be used to report bugs and feature requests, not to request support. These things should be asked on a forum NOT HERE.

By submitting invalid issue reports you waste the time of the repository administrators, which could instead be put to productive work. You also spam the 333 people who are subscribed to get an email for every issue report and comment made to this repository. Please stop.
