### ISSUE TITLE
OTA Update from server Error

### ISSUE THREAD

**Issue by smacyas** [espressif/arduino-esp32#1652]
WROOM ESP32, Arduino IDE

I use example from AWS_S3_OTA_Update to update flash and spiffs from server.

But i have a problem during update:

Update flash...
Connecting to: nevoton-ec.ru to download flash/spiffs
Fetching Bin: /wp_site/nevotonauto/flash.bin
Got 1097168 bytes from server
Got application/octet-stream payload.
contentLength : 1097168, isValidContentType : 1
Begin OTA. This may take 2 - 5 mins to complete. Things might be quite for a while..
Written only : 48546/1097168
Error Occurred. Error #: 12

and this error always occurs, but each time a different number of bytes written.
if (contentLength && isValidContentType)
  {
    // Check if there is enough to OTA Update
    bool canBegin = Update.begin(contentLength, needtoupdate);

    // If yes, begin
    if (canBegin)
    {
      Serial.println(F("Begin OTA. This may take 2 - 5 mins to complete. Things might be quite for a while.."));
  
      size_t written = Update.write(wifiClient);//Update.writeStream(wifiClient);

If i use size_t written = Update.writeStream(wifiClient) the device hangs, with size_t written = Update.write(wifiClient); device does not hangs but not update completely.

What could be the problem?

**Comment by pa4th** [comment]
Hello,

I got the same problem. Firefox is especting a response from the the esp32 and after sometime resending the request.

I took the Ota update out the server part. 

global 
boolean OnlineUpdate =  false;

in the server settings I call
Setup function 
server.on("/webupdate", HTTP_GET, webupdate);


void webupdate(AsyncWebServerRequest * request){
        Serial.print("OnlineUpdate true"  );
        OnlineUpdate=true;
        SendHandle( request, "handleButton_eind", "text/html", "OnlineUpdate true.  Wait 5 min" );
}

and in  the loop function

        if ( OnlineUpdate==true) {
                OnlineUpdate = false;
                execOTA();
        }
