### ISSUE TITLE
TLS Mutual Auth

### ISSUE THREAD

**Issue by Immortalin** [espressif/arduino-esp32#1658]
How does one use the mBed TLS Mutual Auth capabilities from Arduino?

**Comment by lbernstone** [comment]
WiFiClientSecure has a connect method with TLS auth baked in.
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/src/WiFiClientSecure.h#L47

**Comment by Immortalin** [comment]
@lbernstone thanks!
