### ISSUE TITLE
GIT GUI  error cloning submodules

### ISSUE THREAD

**Issue by RobbesU** [espressif/arduino-esp32#1660]
Installing the core for Aduino IDE 1.8.5 under Windows10 the GIT GUI (run as Administrator) correctly creates the "[Sketchbook Directory]/hardware/espressif/esp32" directory, and appears to download the repository but then get the following error.

![image](https://user-images.githubusercontent.com/33870532/43010669-fee371f2-8c38-11e8-8244-f23797e4f06b.png)

The created esp32 directory is empty and also deleted by GIT GUI after throwing the above error msg.

Suggestions?

**Comment by lbernstone** [comment]
Use Arduino IDE boards manager to install. https://github.com/lbernstone/arduino-esp32/blob/003b64c19c119171ac18bf47ac0a748ff12eaef9/docs/arduino-ide/boards_manager.md

**Comment by beegee-tokyo** [comment]
And also in the [Wiki](https://desire.giesecke.tk/index.php/2018/07/01/add-esp32-to-boards-manager-workaround/) if you need developer (staging) version

**Comment by RobbesU** [comment]
Thanks! Good to go.
