### ISSUE TITLE
error generate error messages

### ISSUE THREAD

**Issue by rrobinet** [espressif/arduino-esp32#1667]
### Hardware:
Board:							?WeMOS LOLIN32
Core Installation/update date:			?Latest commit e157ec0 6 days ago
IDE name:							?Arduino IDE
Flash Frequency:					?80Mhz?
Upload Speed:						?921600

### Description:
While defining a variable with the name "error", the script fails to compile because of a conflict with another "error" variable of the library.
The simple example below highlights the issue.
### Sketch:
```
byte error;
void setup() {
}
void loop() {
}
```
### Debug Messages:
```
.../Arduino/Sketch/hardware/espressif/esp32/tools/sdk/lib/libbtdm_app.a(arch_main.o):(.bss+0x4): multiple definition of `error'
/var/folders/bq/1_7b3x851wj3d2wxhqqntcnr0000gp/T/arduino_build_333423/sketch/sketch_jul22a.ino.cpp.o:(.bss.error+0x0): first defined here
.../Arduino/Sketch/Hardware/espressif/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: Warning: size of symbol `error' changed from 1 in /var/folders/bq/1_7b3x851wj3d2wxhqqntcnr0000gp/T/arduino_build_333423/sketch/sketch_jul22a.ino.cpp.o to 4 in .../Arduino/Sketch/hardware/espressif/esp32/tools/sdk/lib/libbtdm_app.a(arch_main.o)
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board WEMOS LOLIN32.
```

**Comment by lbernstone** [comment]
That is upstream.  If you really think you are entitled to that variable name, complain at https://github.com/espressif/esp-idf.

**Comment by rrobinet** [comment]
OK, 
I did submit it as:
https://github.com/espressif/esp-idf/issues/2217
Robert

**Comment by beegee-tokyo** [comment]
There are some variable names that are defined already globally by ESP-IDF and you cannot use them.

Try **`int operator = 0;`** and you get the same error.
In PlatformIO/MVSC it is quite easy to see, because such variable names are highlighted when you type them.
Just change the name from **`error`** to **`myError`** and it will compile.
