### ISSUE TITLE
WifiServer disconnects client.

### ISSUE THREAD

**Issue by feelfreelinux** [espressif/arduino-esp32#167]
When I send message to client via WifiServer.avalible, the user is disconnected from server - I can connect to it again, so server is not stopping.
[Sending the code - I am trying to write simple IRC bouncer.](https://gist.github.com/feelfreelinux/1e6ff6d8285b27a4bf06d94643a13c81)

**Comment by Dennis650** [comment]
Is this https://github.com/espressif/arduino-esp32/issues/119 the same problem?

Greetings
Dennis

**Comment by me-no-dev** [comment]
The biggest mistake is that you get the client with server.available, but then send to another server.available which might or might not be there. Send to BNC instead

**Comment by feelfreelinux** [comment]
@me-no-dev The problem still occur. Hmm, yes looks related to this issue.

**Comment by me-no-dev** [comment]
issue is resolved in the latest commits. I'm closing this now :)
