### ISSUE TITLE
Compilation issues with external libraries included

### ISSUE THREAD

**Issue by nathanjel** [espressif/arduino-esp32#1678]
I have some build error since this update.
I have added some libraries on my libraries folder and I have these warning :

/home/Jyce/esp/arduino/components/arduino/component.mk:3: avertissement : variable « CONFIG_ARDUINO_SELECTIVE_ESPAsyncWebServer » indéfinie
/home/Jyce/esp/arduino/components/arduino/component.mk:3: avertissement : variable « CONFIG_ARDUINO_SELECTIVE_AsyncTCP » indéfinie
/home/Jyce/esp/arduino/components/arduino/component.mk:3: avertissement : variable « CONFIG_ARDUINO_SEL

**Comment by me-no-dev** [comment]
i pushed a fix last night please pull latest and try again?

**Comment by psykokwak-com** [comment]
Just updated and it's ok.
Thanks.

**Comment by acasademont** [comment]
@nathanjel any updates on this? I enabled selective compilation and a standard library like HTTPUpdate is not compiled anymore, I have to disable selective compilation alltogether to have HTTPUpdate included.
