### ISSUE TITLE
BluetoothSerial + Password

### ISSUE THREAD

**Issue by buildlog** [espressif/arduino-esp32#1692]
Is there a way to use a password with the BlueToothSerial library?

**Comment by lbernstone** [comment]
Not yet, but the capability has been added to the upstream component, so it should be possible in the next month or two.

**Comment by bdring** [comment]
Has there been work done on this? Is there any way I can help?

**Comment by Netoperz** [comment]
that would be very interesting. Also wanted to help if needed.
