### ISSUE TITLE
/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/queue.c:1441 (xQueueGenericReceive)- assert failed!

### ISSUE THREAD

**Issue by afsfilho** [espressif/arduino-esp32#1699]
### Hardware:
Board:	                                    DOIT ESP32 DEVKIT V1
Core Installation/update date:    ?do not know where to see this information?
IDE name:				    Arduino IDE
Flash Frequency:			    80Mhz
Upload Speed:			    115200

### Description:
ESP32 is rebooting when execute the line code below:

xQueueReceive(Fifo, &element, portMAX_DELAY);

### Sketch:
teste_mc

QueueHandle_t Fifo;

void setup() {

  Serial.begin(115200);
  delay(10);
  xTaskCreatePinnedToCore(loop2, "loop2", 8192, NULL, 1, NULL, 0);
  delay(10);

  Fifo = xQueueCreate( 10, sizeof( int ) );
 
  if(Fifo == NULL){
    Serial.println("Queue creation error");
  }
}  
void loop() {
  for(int i = 0; i<10; i++){
    xQueueSend(Fifo, &i, portMAX_DELAY);
  }
}
void loop2(void*z)  //loop2 AtribuÃ­do ao core 0, com prioridade 1
{
  while (1)
  {
    int element;
    for(int i = 0; i<10; i++){
      xQueueReceive(Fifo, &element, portMAX_DELAY);
      Serial.print(element);
      Serial.print("|");
    }
    Serial.println();
    delay(1000);
  }
}
```

### Debug Messages:
```
/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/queue.c:1441 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40084f05 on core 0

Backtrace: 0x400883f8:0x3ffb4280 0x400885fb:0x3ffb42a0 0x40084f05:0x3ffb42c0 0x400d09a2:0x3ffb4300

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:808
load:0x40078000,len:6084
load:0x40080000,len:6696
entry 0x400802e4

```

**Comment by me-no-dev** [comment]
create the queue before you start the task
