### ISSUE TITLE
A fatal error occurred : Efuse FLASH_ENCRYPT_CNT failed to burn. Protected?

### ISSUE THREAD

**Issue by venkat3344** [espressif/arduino-esp32#1702]
I got the error 1000...

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun 8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun 8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun 8 2016 00:22:57
Burn the FLASH_CRYPT_CNT efuse again with the python script getting error : A fatal error occurred : Efuse FLASH_ENCRYPT_CNT failed to burn. Protected?

Check out the FLASH_CRYPT_CNT with espefuse.py --port "COM3" summary
it should still have the value: 1(4.bmp)

file:///C:/Documents%20and%20Settings/venkat.g/My%20Documents/My%20Pictures/esp_flash/4.bmp
file:///C:/Documents%20and%20Settings/venkat.g/My%20Documents/My%20Pictures/esp_flash/5.bmp

**Comment by copercini** [comment]
Close as duplicate of https://github.com/espressif/arduino-esp32/issues/1719
