### ISSUE TITLE
how to upload precompiled binary to esp32?

### ISSUE THREAD

**Issue by fabsenet** [espressif/arduino-esp32#1704]
I am the owner of an [open source ambilight](https://github.com/fabsenet/adrilight) software for windows and i want to bring it to the next level.

The current setup process includes downloading arduino ide, setting up board, com port and uploading. I want to get rid of this.

I would love to distribute the compiled version of my sketch together with my windows software. Then the user only connects his/hers esp32 via usb and clicks upload in my software. no arduino ide, no sketch, no nothing, only usability!

So question is:
- What do I need to upload a **precompiled binary** to an esp32 connected via usb on a bare windows pc (think fresh win10 installation)?
- What is the licensing on this? can I redistribute it?

**Comment by lbernstone** [comment]
In arduino IDE, turn on verbose logging during upload in File->Preferences.  Upload the sketch, and you will see the command written to esptool.  Esptool is GPL2, so it can be distributed with attribution/license.
Frankly, sounds like a support nightmare to me. Seems like one of these manufacturers might get a clue, and start distributing the devices with a simple sketch using WiFiManager and a http/s server that can take a file from your computer.

**Comment by fabsenet** [comment]
> sounds like a support nightmare to me

true! it already is 🐴 

Thanks for the info, i will try this!
