### ISSUE TITLE
WiFiEvent SYSTEM_EVENT_STA_DISCONNECTED not fired in master

### ISSUE THREAD

**Issue by Viper2000XXL** [espressif/arduino-esp32#1705]
----------------------------- Remove above -----------------------------

### Hardware:
Board:							?ESP32 Dev Module?
Core Installation/update date:			?31/jul/2018?
IDE name:							?Arduino IDE?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
In master the WiFiEvent SYSTEM_EVENT_STA_DISCONNECTED is not fired in Arduino. Switched back to an older WiFiGeneric.cpp "a59eafb" and it is working. So the problem seems to be somewhere in WiFiGeneric.cpp file. In Debug-Log in Serial Monitor i can see the STA_DISCONNECTED Event but the event is not pushed to example Arduino Code below. SYSTEM_EVENT_STA_GOT_IP is working as expected but the case SYSTEM_EVENT_STA_DISCONNECTED is never executed.

### Sketch:

`void WiFiEvent(WiFiEvent_t event){

    Serial.println(event);
    switch(event) {      
      case SYSTEM_EVENT_STA_GOT_IP:
          //When connected set 
          Serial.print("WiFi connected! IP address: ");
          Serial.println(WiFi.localIP());            
          connected = true;
          break;
      case SYSTEM_EVENT_STA_DISCONNECTED:    //<-- This Code is never reached because event Variable never gets value 5
          Serial.println("WiFi lost connection");
         /connected = false;
          break;
  }
}`

**Comment by Viper2000XXL** [comment]
I played a little bit with the code and when i comment out line 377 and 378 which contains following Code:

`WiFi.enableSTA(false);

WiFi.enableSTA(true);`

ist is working and the DISCONNECTED Event is Fired to Arduino Code.

**Comment by CircuitSetup** [comment]
> WiFi.enableSTA(false)

Curious what you meant by this. I can't get SYSTEM_EVENT_STA_DISCONNECTED to do anything on the front end either.
