### ISSUE TITLE
library ota automatic for server ftp 

### ISSUE THREAD

**Issue by moijerem59** [espressif/arduino-esp32#1715]
Hello everyone, is there a library that manages the automatic update of the esp if a new version was deposited in a folder of a ftp server? this and it is planned by the team?
Cordialy

**Comment by lbernstone** [comment]
FTP is a dying protocol.  https is highly supported and has a lighter server footprint than It is not in the core for the same reason we don't translate to Latin. Try http://www.rudiswiki.de/wiki9/WiFiFTPServer.
