### ISSUE TITLE
PSRAM in M5Stack FIRE

### ISSUE THREAD

**Issue by MhageGH** [espressif/arduino-esp32#1726]
### Hardware:
Board:							M5Stack FIRE
Core Installation/update date:			4/Aug/2018
IDE name:							Arduino IDE
Flash Frequency:					no menu for M5Stack FIRE
Upload Speed:						921600
PSRAM:							Enabled

### Description:
I can't allocate PSRAM by ps_malloc(). 
On the other hand, I can allocate internal RAM by malloc().
I tried with two hardware. Same problem happened.

### Sketch:
const int N = 10;
uint16_t* buf;

void setup(){
  Serial.begin(115200);
  if (buf = (uint16_t*)ps_malloc(sizeof(uint16_t)*N)) Serial.println("ps_malloc succeeded");
  else Serial.println("ps_malloc failed");
}

void loop() {
}

### Debug Messages:
ps_malloc failed

**Comment by MhageGH** [comment]
Thanks for comment, lbernstone.
M5Stack FIRE has 4M-PSRAM.

**Comment by MhageGH** [comment]
Thanks. I tried. I see that paramInit failed. I get below error message.
[W][esp32-hal-psram.c:30] psramInit(): PSRAM init failed!

By the way, someone told me that I should try to cut UART2 PINs because they are share with wires to PSRAM in this board. I tried, but it didn't work. I got the same error massage.

**Comment by MhageGH** [comment]
Someone told me that I should try to connect UART2 PINs to GND with 240Ω. I tried, but it didn't work. I got the same error massage.
![dsc_0031](https://user-images.githubusercontent.com/29541803/43775664-79d3ca26-9a88-11e8-834b-b72fca71f2b3.JPG)

**Comment by manecolooper** [comment]
Hi, tested that sketch in esp wrover module and it Works, ps_malloc succeeded

**Comment by MhageGH** [comment]
Thank you, manecolooper.
M5Stack Inc. announced psram issue of M5Stack FIRE.
They will start the replacement service for it.

**Comment by lbernstone** [comment]
Can you please close the issue, then?
