### ISSUE TITLE
ASSERT_PARAM(32 0), in rwble.c at line 222

### ISSUE THREAD

**Issue by ArTyGill** [espressif/arduino-esp32#1735]
### Hardware:
Board:	ESP32 Dev Module
Chip:	ESP32D0WDQ6 (revision 0)
IDE name:	VisualStudio (Arduino IDE)
Flash Frequency:	80Mhz
Upload Speed:	921600
esptool.py : v2.3.1

### Description:
ASSERT_PARAM(32 0), in rwble.c at line 222
error with ble + IRAM_ATTR + random

**Comment by ArTyGill** [comment]
Recently, I didn’t notice this problem probably fixing it.

**Comment by brunofgc** [comment]
Hi Guys, I'm facing a similar problem. Do you know the contact for rwble.c writer?

The Issue -> assert rwble.c 261, param 00020000 00000000
After it, the processor halts.

System:

Framework: Arduino;
IDE: Visual Studio;
Addon: PlatformIO;

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
    knolleary/PubSubClient@^2.8
    h2zero/NimBLE-Arduino@^1.3.8
    marian-craciunescu/ESP32Ping@^1.7
    plerup/EspSoftwareSerial@^6.16.1
    vshymanskyy/TinyGSM@^0.11.5

**Comment by LNqueen** [comment]
> 

me too, have you fixed this issue? and I also used the esp32-c3 chip.
