### ISSUE TITLE
Arduino Flashing esp32-devkitc v4

### ISSUE THREAD

**Issue by maramb81** [espressif/arduino-esp32#1736]
### Hardware:
Board:							       esp32-devkitc v4
Core Installation/update date:			?
IDE name:							Arduino IDE 1.8.1
Flash Frequency:					       40Mhz
Upload Speed:						921600

### Description:
Hi Guys

i bought the new espressif dev kit with WROOM-32D. 
i'm trying to upload firmware with Arduino IDE but the module doesn't response. 
if i try with other module DOIT WROOM 32 i haven't problem.

**Comment by lbernstone** [comment]
Try this: https://desire.giesecke.tk/index.php/2018/05/04/upload-of-code-over-usb-serial-fails-because-of-erroneous-code/
