### ISSUE TITLE
Serial1 is defined but not usable: Pin 9&10 are used for flash

### ISSUE THREAD

**Issue by Adminius** [espressif/arduino-esp32#1738]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							**Nodemcu 32s**
Core Installation/update date:			**7/aug/2018**
IDE name:							**Arduino IDE**
Flash Frequency:					**40Mhz**
Upload Speed:						**921k**

### Description:
I would like to define Serial1 on pins 16/17. 
But it already defined on pin 9/10. 
Problem 1: pins 9&10 are busy with the flash -> Serial1(1) is not usable
Problem 2: Nodemcu 32s has no menu to choose: NO_GLOBAL_INSTANCES or NO_GLOBAL_SERIAL

### Sketch:
```cpp


#include <Arduino.h>
HardwareSerial Serial1(2);
void setup() {
Serial1.being(115200);
}

void loop() {
}
```

### Debug Messages:
```
Serial1 already defined
```

**Comment by negativekelvin** [comment]
You pass the pins when you call begin

**Comment by copercini** [comment]
try with:

```cpp
void setup() {
Serial1.begin(115200, SERIAL_8N1, 16, 17);
}

void loop() {
}
```

**Comment by Adminius** [comment]
@copercini thx. this works.
now i have another issue: #600 :(

**Comment by lbernstone** [comment]
Please close the issue if it is resolved!

**Comment by Adminius** [comment]
this issue is solved... #600  still open
