### ISSUE TITLE
ESP32 FAT_DATE dos not work...

### ISSUE THREAD

**Issue by pcbtborges** [espressif/arduino-esp32#1739]
### Hardware:
Board:	ESP32 Dev Module
Core Installation/update date: 11/jul/2017
IDE name:	Arduino IDE
Flash Frequency:	80Mhz
Upload Speed:	921600

### Description:
Hi, I am porting a project that runs on a Mega256 where I use the following code to inform the SD routine to add date creation/update properly:
The code below does not work with ESP32's SD.h

Assistance welcome.

### Sketch:
<
//function to supply datetime to SD file system
void dateTime(uint16_t* date, uint16_t* time)
 {
  // return date using FAT_DATE macro to format fields
  *date = FAT_DATE(Clock.getYear() - 48, Clock.getMonth(Century), Clock.getDate());
  // return time using FAT_TIME macro to format fields
  *time = FAT_TIME(Clock.getHour(h12, PM), Clock.getMinute(), Clock.getSecond());
}
>

### Debug Messages:
exit status 1
'FAT_DATE' was not declared in this scope

**Comment by mateusz-kusmierz** [comment]
I have the same problem...

**Comment by jucaballa** [comment]
I have the same problem!

**Comment by ChumKiu** [comment]
I have the same problem!
