### ISSUE TITLE
New Arduino 1.0.0 ESP32 support

### ISSUE THREAD

**Issue by themindfactory** [espressif/arduino-esp32#1740]
My code was working fine, prior to using the new JSON links in board manager to automatically load the libraries..... I am unsure how to check what version I did have, but it was the lastest upto the 1.0.0 point....

One thing I noticed is when I connect my WIN7 machine to the ESP32 acting as an AP, i get this about 50% of the time.

Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited). Exception was unhandled.
Decoding stack results
0x40145cf2: handle_dhcp at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/apps/dhcpserver.c line 1035
0x4014e4b5: udp_input at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/core/udp.c line 417
0x40151741: ip4_input at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/core/ipv4/ip4.c line 705
0x401576ea: ethernet_input at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/netif/ethernet.c line 176
0x401450f1: tcpip_thread at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/api/tcpip.c line 143

### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			
IDE name:							Arduino IDE 1.0.0
Flash Frequency:					80Mhz
Upload Speed:						512000

**Comment by poengAlex** [comment]
I have the same problem. It fails with win10 and android as well. Did you fix your problem?
