### ISSUE TITLE
ESP sending TCP Resets

### ISSUE THREAD

**Issue by Uksa007** [espressif/arduino-esp32#1749]
### Hardware:
Board:							DOIT ESP32 DEVKIT V1
Core Installation/update date:		Boards Manager V1.0.0 latest
IDE name:					        Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:					921600

### Description:
Streaming Audio (AAC) from internet using a VS1053 for the playback. (not show here as issue here is the conncetion is closed before data starts.) Using Streamhttpclient.ino example for demonstation here.
Some streams work ok, some have major issues (start stop playback) and some like this example stop pretty much at the start with the ESP sending TCP Resets that get the connection closed.
Think there is an issues with inadequate TCP window or similar, suggestions?
See attached Wireshark capture 
https://imgur.com/a/RF5ajet

### Sketch:
```cpp

//Change the code below by your sketch
/**
 * StreamHTTPClient.ino
 *
 *  Created on: 24.05.2015
 *
 */

#include <Arduino.h>

#include <WiFi.h>
#include <WiFiMulti.h>

#include <HTTPClient.h>

#define USE_SERIAL Serial

WiFiMulti wifiMulti;

void setup() {

    USE_SERIAL.begin(115200);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

    for(uint8_t t = 4; t > 0; t--) {
        USE_SERIAL.printf("[SETUP] WAIT %d...\n", t);
        USE_SERIAL.flush();
        delay(1000);
    }

    wifiMulti.addAP("SSID", "Password");

}

void loop() {
    // wait for WiFi connection
    if((wifiMulti.run() == WL_CONNECTED)) {

        HTTPClient http;

        USE_SERIAL.print("[HTTP] begin...\n");

        // configure server and url
        http.begin("http://media.usq.edu.au:8010/stream");
        //http.begin("192.168.1.12", 80, "/test.html");

        USE_SERIAL.print("[HTTP] GET...\n");
        // start connection and send HTTP header
        int httpCode = http.GET();
        if(httpCode > 0) {
            // HTTP header has been send and Server response header has been handled
            USE_SERIAL.printf("[HTTP] GET... code: %d\n", httpCode);

            // file found at server
            if(httpCode == HTTP_CODE_OK) {

                // get lenght of document (is -1 when Server sends no Content-Length header)
                int len = http.getSize();

                // create buffer for read
                uint8_t buff[128] = { 0 };

                // get tcp stream
                WiFiClient * stream = http.getStreamPtr();

                // read all data from server
                while(http.connected() && (len > 0 || len == -1)) {
                    // get available data size
                    size_t size = stream->available();

                    if(size) {
                        // read up to 128 byte
                        int c = stream->readBytes(buff, ((size > sizeof(buff)) ? sizeof(buff) : size));

                        // write it to Serial
                        USE_SERIAL.write(buff, c);

                        if(len > 0) {
                            len -= c;
                        }
                    }
                    delay(1);
                }

                USE_SERIAL.println();
                USE_SERIAL.print("[HTTP] connection closed or file end.\n");

            }
        } else {
            USE_SERIAL.printf("[HTTP] GET... failed, error: %s\n", http.errorToString(httpCode).c_str());
        }

        http.end();
    }

    delay(10000);
}

```

### Debug Messages:
```
[SETUP] WAIT 3...
[SETUP] WAIT 2...
[SETUP] WAIT 1...
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 1 - SCAN_DONE
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:360] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:389] _eventCallback(): STA IP: 192.168.137.74, MASK: 255.255.255.0, GW: 192.168.137.1
[HTTP] begin...
[D][HTTPClient.cpp:181] beginInternal(): host: media.usq.edu.au port: 8010 url: /stream
[HTTP] GET...
[D][HTTPClient.cpp:850] connect():  connected to media.usq.edu.au:8010
[D][HTTPClient.cpp:968] handleHeaderResponse(): code: -1
[W][HTTPClient.cpp:1124] returnError(): error(-1): connection refused
[D][HTTPClient.cpp:1126] returnError(): tcp stop
[HTTP] GET... failed, error: connection refused
```

**Comment by Uksa007** [comment]
So any ideas how to fix this issue ?
Do I need to increase the TCP window size so it accept more data, and not send Resets?
Any advice on how to configure lwip to addess this would be great.

Thanks

**Comment by lbernstone** [comment]
If you turn on verbose logging, you can see the header that server returns.  It is ancient, and pretty badly formed.  You will need to mess around with handleHeaderResponse to get it to work.
@copercini Maybe a string ending in "200 OK" should be accepted?

**Comment by Uksa007** [comment]
Hi, 

Thanks @lbernstone for your response. 
I have the Arduino logging level set to Debug, no verbose option?
Are you refering to Wireshark, as I din't find an option for verbose logging?

Could you let me know which verbose logging you arre refering to.

Thanks.

**Comment by Uksa007** [comment]
thnaks @lbernstone, I Was looking in there but missed it. 

I ended up doing the following at line 940 which seems to work well.
`
            if(headerLine.startsWith("HTTP/1.")) {
                _returnCode = headerLine.substring(9, headerLine.indexOf(' ', 9)).toInt();
			} else if(headerLine.startsWith("ICY 200 OK")) {
				_returnCode = 200;
`
Now I just have to sort out why higher bitrates are jittery. 
Is it possible to increase the buffer in HTTPclient?

**Comment by Uksa007** [comment]
Like this one. 
http://162.211.86.137:8000/

**Comment by Uksa007** [comment]
@lbernstone 
Any clues on how to improve streaming I assume the lwip buffers need to be larger?

Thanks.

**Comment by lbernstone** [comment]
If you think you are going to improve the tuning on lwip, you should be using ESP-IDF, and see https://github.com/MrBuddyCasino/ESP32_MP3_Decoder.  As written, Serial writes will dominate the cpu time in this sketch.  If you want to stick with Arduino, try to fill the string buffer fully.  128 is a fairly arbitrary size for that buffer.  1400 is more appropriate, and should be able to sweep a packet payload out of the network buffers every pass.  Note, this sketch is just a demo, and will not be very useful for a real project where you don't want to be stuck in an infinite loop.

**Comment by Uksa007** [comment]
@lbernstone 
I'm using a 50,000 byte circular buffer, however the network buffer (size see below) is always 0 when I require more data to feed the VS1053 (dedicated MP3 processor). 
Serail writes are removed just feeding the VS1053 from the cicularbuffer and reading data from the netowork.  Loop is fine for now. 

To sumarise:  Network buffer -> 50K circular buffer -> VS1053 MP processor

This network buffer and my circular buffer is empty when I need data for the VS1053, how to keep network buffer full??
size_t size = stream->available();

**Comment by lbernstone** [comment]
You will want to use arduino as an esp-idf component so you can modify the WND settings in lwip. https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md
