### ISSUE TITLE
OTA code upload on esp32

### ISSUE THREAD

**Issue by mimansamaheshwari** [espressif/arduino-esp32#1770]
### Hardware:
Board:							        ESP32 Dev Module
Core Installation/update date:			11/jul/2017
IDE name:							Arduino IDE
Flash Frequency:				                40Mhz?
Upload Speed:						115200

Is it possible to upload code multiple times via OTA on esp32 in Arduino Ide? If yes then how?

**Comment by lbernstone** [comment]
As long as the uploaded code includes an OTA listener, you can do OTA upgrades as many times as you would like.
