### ISSUE TITLE
Unable to use touch matrix on esp32

### ISSUE THREAD

**Issue by ahmed847** [espressif/arduino-esp32#1772]
### Hardware:
Board:							ESP32 Devkit v1
Core Installation/update date:			18/June/2018
IDE name:						Sloeber
Flash Frequency:					40Mhz
Upload Speed:					115200

### Description:
I am working with touch of esp32. I want to use matrix touch like in the following link: https://github.com/espressif/esp-iot-solution/blob/master/examples/touch_pad_evb/main/evb_touch_matrix.cpp

But the problem is that "arduino-esp32" does not have the functions required for matrix touch. Please tell me how I can achieve this on "arduino-esp32".

Thanks in advance.

**Comment by jwktje** [comment]
If possible I'd like to see this issue reopened as I also would like to use the touch matrix in Arduino. Specifically this example with the ESP32-S2: https://github.com/espressif/esp-idf/tree/master/examples/peripherals/touch_element/touch_matrix

**Comment by lbernstone** [comment]
This example should work in 2.0.0alpha release.

**Comment by jwktje** [comment]
Could I use the exact same code without issue inside the Arduino Core instead of ESP-IDF when using 2.0.0alpha?

**Comment by jwktje** [comment]
@Ibernston

> This example should work in 2.0.0alpha release.

Would I [be able to use this directly](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/touch_element/touch_matrix/main/touch_matrix_example_main.c) in Arduino or would it need some rewriting to work?
