### ISSUE TITLE
Update failed! How to get back

### ISSUE THREAD

**Issue by robbie489** [espressif/arduino-esp32#1775]
### Hardware:
Board:							ESP32 Dev Module

IDE name:							Arduino IDE

### Description:
Hey, I need your help with the OTA Update. I know that there are 2 partitions. ota_0 and ota_1. and should I update my esp32 the second time the ota_1 partition will get the code. But what happens when this code is unable to start? Is there a possibility to switch back to ota_0 ? I mean is it possible to start with the old firmware in case of the new is damaged?

thank you for helping me

**Comment by lbernstone** [comment]
If the "new" OTA partition is unable to boot, it will switch back to the other partition.  https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/ota.html
