### ISSUE TITLE
Support for parity error in serial communication

### ISSUE THREAD

**Issue by mytrain** [espressif/arduino-esp32#1806]
### Hardware:
Board:							TTGO
Core Installation/update date:		?
IDE name:						Arduino IDE

### Description:
A would like to be able to detect parity errors.
Setting parity conf as SERIAL_8E1 and transmitting 9bit frame in order to generate some parity error with a third party device I want to be able to detect parity error.

Modifying the esp32-hal-uart.c 
-I activate the parity_err (the same way frame_err) is done.
-I look at the parity_err bit of int_raw in the ISR but this bit is always set (if parity is odd) or clear (if parity is even) but it does not reflect the fact the the parity bit was correctly set in the received frame.

More over I tried to configure the ESP32 without any parity in order to generate a frame error by sending the flowing 9N1 data frame  0(start) 101000010 (data)  (1)stop. Decoder by an esp32 configured 8N1 this shall generate a frame error as 9th data bit of the sent frame is cleared. NO FRAME ERROR is reported in the frame_err bit of the int-raw data.

Does somebody as developed any support for handling parity and frame error.

Regards

**Comment by dazca** [comment]
I am trying to decipher how to obtain a parity error in a ISR. I have put some insights in this other response: https://github.com/espressif/esp-idf/issues/9569#issuecomment-1552850181
