### ISSUE TITLE
Is it possible to let ESP32 operate in a master mode in order to connect to HC-06(in slave mode)?

### ISSUE THREAD

**Issue by Raymondcho99** [espressif/arduino-esp32#1815]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			11/jul/2018
IDE name:							Arduino IDE
Flash Frequency:					40Mhz
Upload Speed:				115200

### Description:

I'm trying to connect my ESP32 to HC-06 which is integrated with arduino pro mini.
But I couldn't find any example of ECSP32 SPP moster mode.

Is it possible to let ESP32 operate in a master mode?
If possible, could you give me a guide?
- Does it require any AT command to set SPP master mode?
- Does it need to set any PIN code to connect with a HC-06(slave) which has PIN code "1234"?
- Does it need to change baudrate of SPP connection with the same rate of HC-06's?

Please give me a guide.

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

**Comment by menox1981** [comment]
Make sure the pro mini can keep up with the data transfer rate you set in the esp32. You may need to slow down your clock rate to match that of the pro mini.

**Comment by Neliusmicrocare** [comment]
Hello Raymond, did you manage to get it working? I  have the same question

**Comment by discapacidad5** [comment]
Hi, I'm also looking for how to connect the esp32 to a buetooth keyboard without success. I still think it's the same problem.

**Comment by VojtechBartoska** [comment]
Hello, can you please confirm this is still valid on  [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1)? Take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable.

If it's still needed, please reopen the issue.

Thanks for understanding.
