### ISSUE TITLE
SoftAP Server issue

### ISSUE THREAD

**Issue by seopyoon** [espressif/arduino-esp32#182]
Hi, I am trying to build an application, where user will pass desired SSID and its password by connecting to ESP32 board acting as an AP.  Then remember the necessary information for network connectivity.

So, I have the following [code](https://gist.github.com/seopyoon/6d5b15e7d479bb9cd12c65b3e660ad6e).  This code is not fully implemented to get SSID and password, but it should at least connect, and when accessed at `http://192.168.4.1` it should show `hello world`.

But, instead, I get the following terminal message
<img width="682" alt="2017-02-08 18 41 15" src="https://cloud.githubusercontent.com/assets/8359372/22731724/f7952958-ee2e-11e6-87eb-74527319b935.png">

and, on phone, it cannot connect to the AP on the settings page.  I wanted something similar to [this](https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/example-sketch-ap-web-server).  `join` followed by an immediate `leave`

Could someone help me figure out where I might be doing wrong?

**Comment by me-no-dev** [comment]
what is the phone telling you? from the above output is visible connect/disconnect of a device. Does it get IP? what is actually happening?

**Comment by seopyoon** [comment]
The phone doesnt give any message. It attempts to connect and afrer about half a second of trying, it does not try any more. I press again, then it tries again for an even shorter time, and stops.

**Comment by me-no-dev** [comment]
that is not much to go by now is it :) try computer or something. You need to have better idea why you get disconnected from the AP.

**Comment by me-no-dev** [comment]
there are no errors in the logs above, code also looks fine (though you are running only on one core)

**Comment by clowrey** [comment]
Some phones will disconnect from APs if they can't get internet access in a short period of time, not sure if this is that issue..

**Comment by me-no-dev** [comment]
@clowrey good point! I had to do some tricks on mine too

**Comment by seopyoon** [comment]
What kind of tricks?? 
The same happens on my mac. I dunno how I could get some message from wifi connect attempts on Mac.

**Comment by me-no-dev** [comment]
try opening the Console.app and see if it says anything. As for the tricks, I had to confirm something somewhere... was pretty obscure (search in google).

**Comment by plerup** [comment]
To handle this you need a "captive portal" which means you have to have a local DNS server which redirects everything to a server which provides a 200 http request answer

**Comment by seopyoon** [comment]
@plerup you suggest that I implement something like [this](https://github.com/esp8266/Arduino/blob/master/libraries/DNSServer/examples/CaptivePortal/CaptivePortal.ino) in order to achieve what I am planning on doing?  (A SoftAP Server at initial launch to get information about home WiFi and password?)

**Comment by plerup** [comment]
Yes, we are just missing the webserver for now...

**Comment by seopyoon** [comment]
@plerup @me-no-dev Do we know when webserver will be available??

**Comment by eljefedelrodeodeljefe** [comment]
Has here been progress?
