### ISSUE TITLE
Passing argument to interruptHandler - sample doesnt work

### ISSUE THREAD

**Issue by hostmit** [espressif/arduino-esp32#1826]
Hello! Tested 
arduino-esp32/libraries/ESP32/examples/GPIOInterrupt/GPIOInterrupt.ino

attachInterruptArg(button1.PIN, isr, &button1, FALLING);

that never triggers function

void IRAM_ATTR isr(void* arg) {

ESP32

**Comment by lbernstone** [comment]
There is a pull request in the pipeline to fix this. https://github.com/espressif/arduino-esp32/pull/1776/files
