### ISSUE TITLE
files not found, when in library folder

### ISSUE THREAD

**Issue by jeffpkamp** [espressif/arduino-esp32#1827]
### Hardware:
Board:							Wemos mini32 v1.0.0
Core Installation/update date:			V1.0.0
IDE name:							?Arduino IDE, 1.6.7 windows 10 ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
I have downloaded several different libraries for the ESP32 (https://github.com/suculent/esp32-http-update and https://github.com/zhouhan0126/WIFIMANAGER-ESP32).  I unzip the libaries in my ~\Arduino\hardware\espressif\esp32\libraries\  folder.    When I include the libraries, they reference core libraries that are in the folders above them, where they normally are, however, the complier gives the following error:  

```Arduino\hardware\espressif\esp32\libraries\ESP32httpUpdate/ESP32httpUpdate.h:33:24: fatal error: HTTPClient.h: No such file or directory
```
But I can see the file:
Arduino\hardware\espressif\esp32\libraries\HTTPClient\src\HTTPClient.h

if I drop the required files into the same folder as the cpp file that has the include command in it, it finds it, but it will not look in the regular path for it.

This is only an issue for newly downloaded libraries for the ESP32 hardware as far as I can tell.  Libraries that were included with the core work fine.

### Sketch:
```
not relevant
```

### Debug Messages:
```
No upload, so not relevent
```

**Comment by stickbreaker** [comment]
@jeffpkamp I put new libraries into a `libraries` folder of my Arduino Sketches directory:
Windows 7 pro, Arduino 1.8.5
```
\documents\arduino\libraries\...
```
my Arduino sketches:
```
\documents\arduino\i2c_test\...
\documents\arduino\sdd1306_test\...
\documents\arduino\eeprom_copy\...
```

When Arduino compiles, it will use these libraries first.  I have been modifying `Wire()` so I leave the \Arduino\Hardware\.. directory alone.  My modified `Wire()` is:
```
\documents\arduino\libraries\Wire\src\Wire.h ...
```

Chuck.
