### ISSUE TITLE
Sending lage base 64 encoded char array over BluetoothSerial

### ISSUE THREAD

**Issue by Jeard** [espressif/arduino-esp32#1828]
### Hardware:
Board:							LOLIN32
Core Installation/update date:			29/aug/2018
IDE name:							Platform.io
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
I have a large (with more than 2000 array elements) char array containing base64 encoded data needs to be send over BluetoothSerial.
When I use `SerialBT.print()` or `SerialBT.printf("%c",array)`, The received array is split in to few lines. Same results on  `Serial.print()` or `Serial.printf("%c",array)` as well.
Is it possible to have the output in one line or is there a better way to send the char array other than those `.print` commands?

**Comment by Jeard** [comment]
@stickbreaker 
It worked but the android app that suppose to decode the data wasn't able to identify the array.

Asitha.

**Comment by copercini** [comment]
@Jeard  There is a bug in BTserial that large data can be truncated  =/

Try this branch: https://github.com/espressif/arduino-esp32/commits/bt-serial-overhaul it has a flow control that solves this lost data problem

**Comment by copercini** [comment]
@Jeard could you try cloning the last git code? (instructions [here](https://github.com/espressif/arduino-esp32/tree/master/docs/arduino-ide)
I think this was fixed by me-no-dev here https://github.com/espressif/arduino-esp32/commit/96822d783f3ab6a56a69b227ba4d1a1a36c66268

**Comment by copercini** [comment]
Fixed! https://github.com/espressif/arduino-esp32/commit/96822d783f3ab6a56a69b227ba4d1a1a36c66268

This implements a kinda of software flow control that waits when get a `ESP_SPP_CONG_EVT` and transmits again when channel is free again
