### ISSUE TITLE
esp32 wifi not connecting to network

### ISSUE THREAD

**Issue by oly99** [espressif/arduino-esp32#1829]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:	ESP32 Dev Module
Core Installation/update date:	esp has not been updated firmware is about 2 years old 
IDE name:			Arduino IDE
Flash Frequency:		40Mhz?
Upload Speed:		115200?

### Description:
the esp32 wont connect to  my network it just says connecting to wifi over and over and never connects 
it was working then it stopped could updating the esp32 firmware fix this or  is it another issue , also is there a different way to connect to wifi  that's different to the :

WiFi.begin(ssid,password);
 
while (WiFi.status() != WL_CONNECTED) {
Serial.println("Connecting to WiFi..");
delay(300);

}
 
that  might fix this issue 

### Sketch:
```cpp

//Change the code below by your sketch
#include <Adafruit_Sensor.h>
//#include "DHT.h"
#include <WiFi.h>
#include <PubSubClient.h>
#include "SparkFunHTU21D.h"
//Create an instance of the object
HTU21D myHumidity;

const char* ssid = "skynet";
const char* password = "Sexyfrog9919";
//const char* mqttServer = "192,168,0,196";
IPAddress mqttServer(192,168,0,196);
const int mqttPort = 1883;
const char* mqttUser = "ojosbourne";
const char* mqttPassword = "Skingsking9919";
//#define mqttPort "1883"
#define temperature_topic "topic/temp"       //Topic temperature
#define humidity_topic "topic/humid"         //Topic humidity
//#define debug_topic "debug"                   //Topic for debugging


//here we use pin IO23 of ESP32 to read data
//#define DHTPIN 14
//our sensor is DHT22 type
//#define DHTTYPE DHT22
//create an instance of DHT sensor
//DHT dht(DHTPIN, DHTTYPE);

WiFiClient espClient;
PubSubClient client(espClient);


void setup() {
//void setup() (

//   connect to wifi 



Serial.begin(115200);
WiFi.disconnect(true);
delay(3000);

//DO NOT TOUCH
    //  This is here to force the ESP32 to reset the WiFi and initialise correctly.
 //   Serial.print("WIFI status = ");
  //  Serial.println(WiFi.getMode());
  // WiFi.disconnect(true);
   // delay(3000);
   // WiFi.mode(WIFI_STA);
   // delay(1000);
    //Serial.print("WIFI status = ");
    //Serial.println(WiFi.getMode());
    // End silly stuff !!!

WiFi.begin(ssid,password);
 
while (WiFi.status() != WL_CONNECTED) {
Serial.println("Connecting to WiFi..");
delay(300);

}
 
Serial.println("Connected to the WiFi network");
 // connect to mqtt

client.setServer(mqttServer, mqttPort);
//mqttClient.setServer(mqttServer, mqttPort);
while (!client.connected()) {
Serial.println("Connecting to MQTT...");
 delay(300);

if (client.connect( "ESP32Client", mqttUser, mqttPassword )) {
 
Serial.println("connected");
 delay(300);

} else {
 
Serial.print("failed with state ");
Serial.print(client.state());
delay(200);
 
}
//}

  
  //Serial.begin(115200);
  //Serial.println("DHT22 sensor!");
  //call begin to start sensor
  //dht.begin();

  Serial.println("HTU21D Example!");

  myHumidity.begin();
}

}
 



void loop() {

  float h = myHumidity.readHumidity();
  float t = myHumidity.readTemperature();

  
  //use the functions which are supplied by library.
  //float h = dht.readHumidity();
  // Read temperature as Celsius (the default)
  //float t = dht.readTemperature();
  // Check if any reads failed and exit early (to try again).
  if (isnan(h) || isnan(t)) {
    Serial.println("Failed to read from htu21d sensor!");
    return;
  }
  // print the result to Terminal
  //client.publish(humidity_topic, (h));
  Serial.print("Humidity: ");
  Serial.print(h);
  Serial.print(" %\t");
 // client.publish(temperature_topic, (t));
  Serial.print("Temperature: ");
  Serial.print(t);
  Serial.println(" *C ");

   // Publish values to MQTT topics
    client.publish(temperature_topic, String(t).c_str(), true);   // Publish temperature on mosohomes/temp1
    //if ( debug ) {    
      Serial.println("Temperature sent to MQTT.");
    //}
    delay(200); //some delay is needed for the mqtt server to accept the message
    
    client.publish(humidity_topic, String(h).c_str(), true);      // Publish humidity on mosohomes/humid1
    
    //if ( debug ) {
                  Serial.println("Humidity sent to MQTT.");
                 //}
  //we delay a little bit for next read
  delay(10000);
}



### Debug Messages:

[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 0 - WIFI_READY
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:360] _eventCallback(): Reason: 202 - AUTH_FAIL
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..
Connecting to WiFi..

**Comment by lbernstone** [comment]
Looks like an incompatible WiFi security.  What is your AP and how is it set up?

**Comment by oly99** [comment]
@lbernstone its a tenda ac18   with standard setup do  need to give the esp32 a fixed ip then ?

**Comment by lbernstone** [comment]
The device is not authenticating, so a static IP is not going to work either.  Your AP is not allowing the esp to connect, so you will need to wireshark the process to see what is failing.

**Comment by panther1** [comment]
I am having the same problem. Stable esp code now very seldomly connects to Arris XB6 modem since it was installed.

`[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:360] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:360] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:360] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 2 - STA_START`

**Comment by jjassar** [comment]
In my case ESP32 dev kit does not reconnect automatically, i need to either call WiFi.reconnect()  or Wifi.Begin() again in loop.

**Comment by lbernstone** [comment]
OP has a very specific connection error.  If you do not have this problem, or a solution for him, then you are not solving the issue.

**Comment by oly99** [comment]
@lbernstone thanks i will install wireshark and have a look  tonight

**Comment by oly99** [comment]
@lbernstone ok i turned on my guest  network and it connects to 192.168.10.139
but gateway etc is 192.168.0.1   so im guessing that 192.168.10.xxx  is to do with it bebing the guest network separate from my other one

**Comment by oly99** [comment]
i did notice something weard with my other esp sonnoff that it kept on being given 192.168.0.1  as its ip and then would not connect after as thats reserved for the main router address i had to mess with tasmota to get it a fixed ip now its ok  i think it was because  IP Address  was 192.168.0.1
Subnet Mask:
255.255.255.0
DHCP Server  had 
IP Address Range:
192.168.0. 1  -200
so this clashed i have now changed the dhcp ip range to   10-200   not 1-200 .
i dont think that was helping either 
hopped back on regular AP  not working again

**Comment by oly99** [comment]
ok  got mqtt to connect  and now can see on node red so all seems ok and fixed 

many thanks   for your help

**Comment by Pythonaire** [comment]
It seem for me, you use Pin14 and 22 for measuring temperature. These Pins are ADC2 pins. As described by the ESP32 manufacturer, the ADC2 pins are used by the Wifi driver. you can use these Pins for ADC measuring if the Wifi is off (driver unloaded).Me too, stumble about this and wondering about unstable Wifi.

**Comment by lmayai** [comment]
I'm using pin14 for digital purposes (digital output to drive a LED). I've had some wifi connection problems in my projects, and I don't know if those problems are by use this pin.

Are there some problems for wifi connections if pin14 is used as a digital output?

**Comment by lmayainsite** [comment]
I'm using pin14 for digital purposes (digital output to drive a LED). I've had some wifi connection problems in my projects, and I don't know if those problems are by use this pin.

Are there some problems for wifi connections if pin14 is used as a digital output?

**Comment by Pythonaire** [comment]
As mentioned... GPIO14 (the interrupt) is used by Wifi. You Need to disable Wi-Fi first, in you like to use the Pin for other things.

**Comment by lmayainsite** [comment]
Pytho

> As mentioned... GPIO14 (the interrupt) is used by Wifi. You Need to disable Wi-Fi first, in you like to use the Pin for other things.

Could you show me where do you find that in the documentation? 

I understoot from documentation this (tell mee if I wrong): If pin14 will be use for ADC purposes, Wi-Fi  must be disable, because is a requirement for ADC, not for wifi-driver.

Thanks.

**Comment by Pythonaire** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/adc.html

**Comment by baodo3133s** [comment]
oly99, i am having the same issue, after you added the mac address onto your filter list did you do anything else to get the esp32 to connect t wifi?

**Comment by remata** [comment]
I have same observations as Pythonaire - if I use ADC2 pins for something that requires interrupts this impacts WiFi. In my case I used ports 26 and 27 for UART2 and WiFi couldn't connect to AP after soft reset. After moving UART2 pins to 16, 1, there were no more issues with WiFi connectivity.

**Comment by DhrubojyotiDey** [comment]
> In my case ESP32 dev kit does not reconnect automatically, i need to either call WiFi.reconnect() or Wifi.Begin() again in loop.

Can you please share the code? And is there any way to compile micropython in arduino?

**Comment by arvabhatrajesh** [comment]
esp32 WIFI not connecting for MOTO mobile 
I tried simple wifi code

#include "WiFi.h"
 
const char* ssid = "motog4";
const char* password =  "mymobilemoto";
 
void setup() {
 
Serial.begin(115200);
  //connect to WiFi
  Serial.printf("Connecting to %s ", ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(".");
  }
  Serial.println(" CONNECTED");
  //disconnect WiFi as it's no longer needed
  WiFi.disconnect(true);
  WiFi.mode(WIFI_OFF);
}
 
void loop() {}

other mobile hotspot is connecting  and only moto hotspot is not connecting 
solve this anyone Wise.....
thank you

**Comment by Salman1309** [comment]
Check for ESP status, if you get AUTH Fail at that time only disconnect and then reconnect. it works!!

**Comment by rfox12** [comment]
I downgraded from the 5ghz wifi ssid to 2.4ghz version and it worked for me.  Hope it helps someone else.

**Comment by RafaTaborga** [comment]
I am having this problem:
wifi station: retry to connect to the AP
It says that the ESP32 is already in station mode, but will not get an IP or "connect" completely to the network.
Did anyone have this problem?
Please, I need to have my network by Monday

**Comment by IanHarris6** [comment]
Was anyone able to get it to work?

**Comment by rob-bits** [comment]
I do not know if my issue is related but I had connection problems. First it was connecting to router pretty fast then after restart of the board it did not. I got a plenty of disconnect event, something like this:
`...[  2703][V][WiFiGeneric.cpp:362] _arduino_event_cb(): STA Disconnected: SSID: ****, BSSID: xx:d9:4d:xx:da:46, Reason: 2`

My problem was hardware related. I had 10uF + 100nF capacitors on the 3.3V lines. I am using ESP32-Wrover and the datasheet recommends 22uF capacitors and in the wrover-kit reference design a 100uF capacitor was used. I hacked 100uF capacitor to my board and the WiFi issue dismissed. It seems like working now.

**Comment by parzibyte** [comment]
Hi. Maybe it's a little obvious but I tried every solution listed here and at the end it was solved by restarting the router. I am connected through a repeater, so I restarted both the main router and the repeater, then everything worked well:
[  1090][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 4 - STA_CONNECTED

By the way, this is the code I am using, but the esp32 only connected after tried this code and restarting the router. I am using ESP32 S3 WROOM N16R8 with camera (maybe it's a clone because it does not have any psram).

```cpp
    WiFi.mode(WIFI_STA);
    WiFi.disconnect(true, true);
    delay(100);
    wl_status_t resultado = WiFi.begin("ssid", "password");
    Serial.printf("Result code %d", resultado);
    WiFi.setTxPower(WIFI_POWER_8_5dBm);

    while (WiFi.status() != WL_CONNECTED)
    {
        delay(300);
        Serial.print(".");
    }
```

My **platformio.ini** looks like this:

```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.psram = enabled
lib_deps = 
	esp32async/AsyncTCP@^3.3.6
	esp32async/ESPAsyncWebServer@^3.7.2
	;witnessmenow/UniversalTelegramBot@^1.3.0

build_flags = -DCORE_DEBUG_LEVEL=5 -DDEBUG_ESP_SSL

```
