### ISSUE TITLE
BLE service stops advertising after running time of random duration

### ISSUE THREAD

**Issue by deuded** [espressif/arduino-esp32#1830]
### Hardware:
Board:							Heltec WiFi LoRa ESP32
Core Installation/update date:			27/aug/2018
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						921600

### Description:
In my program, there is a BLE Service with a characteristic. The characteristic sends a value (to keep it simple here, it is always the same value) to an Android phone over BLE. The notifying works for a while and then the BLE service stops (GATT CONN Timeout in android app). The ESP32 is still running (serial output doesnt stop), but the BLE service is not visible anymore.
The time until the service stops is totally random, between 15 min and 4h. 
I reduced the code to an absolute minimum, but the error still occurs.

I would appreciate any help since I don't know why this error occurs.

What i tried so far:
- different esp32-boards
- new Arduino installation on different computer
- different android phones
- different android apps
- different power sources (battery pack, computer, phone charger)

### Sketch:
```
#include <BLE2902.h>
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>

static const char* BLE_DUST_UUID = "6e57fcf9-8064-4995-a3a8-e5ca44552192";
static const char* BLE_DUST_PM25_UUID = "9595592e-2baf-4156-9e0c-0dfaa2fac84d";
static const char* BLE_DEVICE_NAME = "AQNode_testing";

BLEServer* BleServer = nullptr;
BLEAdvertising* BleAdvertising = nullptr;
BLEService* BleSvcDust = nullptr;
BLECharacteristic* BleChcDustPm25 = nullptr; 

void setup() {
    BLEDevice::init(BLE_DEVICE_NAME);
    BleServer = BLEDevice::createServer();
    BleSvcDust = BleServer->createService(BLE_DUST_UUID);
    BleChcDustPm25 = BleSvcDust->createCharacteristic(BLE_DUST_PM25_UUID, BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
    BleChcDustPm25->addDescriptor(new BLE2902());
    BleChcDustPm25->setValue("-1");
    BleSvcDust->start();
    BleAdvertising = BleServer->getAdvertising();
    BleAdvertising->start();
}
void loop() {
  BleChcDustPm25->setValue("10");
  BleChcDustPm25->notify();
 	delay(500);
}

```

**Comment by menox1981** [comment]
You're delaying half a second in your main loop. That could be the cause of a Bluetooth dropout if no messages are sent/received within the phone's or maybe the hardware's timeout value. Consider a "heartbeat" message that you can send/receive so the connection doesn't automatically close.
