### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tarbear123** [espressif/arduino-esp32#1842]
Please fill the info fields, it helps to get you faster support ;)

----------------------------- Remove above -----------------------------

### Hardware:
Board:							 ESP8266 Module
Core Installation/update date:			
IDE name:							Platform.io
Flash Frequency:					?40Mhz?
Upload Speed:						9600

### Description:
will this library also work on a esp8266 and if it will, what is this library called on platformio?

//Change the code below by your sketch
#include <PxMatrix.h>
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <avr/pgmspace.h>
#include "FastLED.h"

#define NUM_LEDS 1024

#define  DATA_PIN (haven't fingered out what pin to use yet on the esp8266)

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "b3834e622f334105b1810f639baaa8fb";

// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "SSID";
char pass[] = "password";

void setup() {
  // Debug console
  Serial.begin(9600);

  Blynk.begin(auth, ssid, pass);
  // You can also specify server:
  //Blynk.begin(auth, ssid, pass, "blynk-cloud.com", 80);
  //Blynk.begin(auth, ssid, pass, IPAddress(192,168,1,100), 8080);

void loop () {

  Blynk.run();
  // You can inject your own code or combine it with other sketches.
  // Check other examples on how to communicate with Blynk. Remember
  // to avoid delay() function!

**Comment by MarkyAD** [comment]
@tarbear123 this is an esp32 repository, not esp8266. Since your question pertains to 3rd party libraries, you should probably be asking in the respository for those particular libraries or at a community forum.
