### ISSUE TITLE
Receiving data via Serial fails

### ISSUE THREAD

**Issue by robbie489** [espressif/arduino-esp32#1843]
Hello Community,

I am working on a Projekt with der ESP32. The main four is sending a .bin file with node.js via the SerialPort. 
I managed that the files get spliced into chunks of 256 Bytes and the ESP received the first chunk.
Now I have the problem to manage that the ESP wants to get the next Chunk.
Can anybody help me to fix this problem?

this is my .js code
`var fs = require('fs');
var SerialPort = require('serialport');

var portName = "/dev/cu.SLAB_USBtoUART";

var myPort = new SerialPort(portName, {
    baudRate: 115200
});

var buffer = fs.readFileSync('test.bin');
var imageLength = buffer.length;
console.log('Größe vom Image ' + imageLength);
var buffer = fs.readFileSync('test.bin');
var imageLength = buffer.length;
for(var i = 0, n = Math.ceil(imageLength/256/*nur test sonst256*/); i<n/; i++)
	{
	    var bufferPart = buffer.slice(256 * i,Math.min(imageLength - 1,((i+1)*256) ));	
	}

var Readline = SerialPort.parsers.Readline;
var parser = new Readline();
myPort.pipe(parser);

myPort.on('open', showPortOpen);
parser.on('data', readSerialData);
myPort.on('close', showPortClose);
myPort.on('error', showError);

function showPortOpen() {
    console.log('port open. Data rate: ' + myPort.baudRate);
    myPort.write(bufferPart); 
}
	
function readSerialData(data) {
    console.log(data);
}

function showPortClose() {
    console.log('port closed.');
}

function showError(error) {
    console.log('Serial port error: ' + error);
}	

`

**Comment by lbernstone** [comment]
This forum is for errors in the code base, not programming advice.  Please take this to another site.
