### ISSUE TITLE
Location of The esp tools/configs in arduino - installing via board manager

### ISSUE THREAD

**Issue by Netoperz** [espressif/arduino-esp32#1844]
Hello,
Can't find the answer - so asking here, where the hell is the espressif folder in linux and windows, when You install the esp in arduino using https://dl is installed using mhall119 from snap shop in ubuntu.
I'm looking for boards.tt and default.csv for partition map.

**Comment by MarkyAD** [comment]
In unix thats what the "find" command is for. For boards manager its ~/.arduino15/packages

**Comment by Netoperz** [comment]
![zrzut ekranu z 2018-09-06 14-00-07](https://user-images.githubusercontent.com/16330298/45156055-4945cc80-b1dd-11e8-9afd-1df77b4cd590.png)
Not really there
And whereis and find does not show any output,

system:
n37@n37--Stellar:~$ uname -a
Linux n37--Stellar 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
![zrzut ekranu z 2018-09-06 14-09-53](https://user-images.githubusercontent.com/16330298/45156502-b312a600-b1de-11e8-9a9b-06d89b4f7339.png)

Thank You for Your support, but in my case it is in /snaps, as this version of arduino comes from snap store.

And it does not show any output when using whereis or find . That's why i couldn't find it.
But after Your response i have looked deeper and everything is there, This case might help others, Thank You.
Closing
