### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by Senthanamuthan** [espressif/arduino-esp32#186]
Hi,
    Please anyone tell me how to run BLE and WiFi in ESP32 simultaneously
Thanks

**Comment by me-no-dev** [comment]
can't. You can run either but not both. ESP32 has one radio and one antenna

**Comment by me-no-dev** [comment]
seems I was wrong. Will leave this open until I integrate it in Arduino

**Comment by plerup** [comment]
http://esp32.com/viewtopic.php?f=2&t=847

**Comment by Senthanamuthan** [comment]
Thank you very much

**Comment by me-no-dev** [comment]
it's in
