### ISSUE TITLE
Bluetooth one port 

### ISSUE THREAD

**Issue by moijerem59** [espressif/arduino-esp32#1866]
### Hardware:
Board:							?ESP32 Dev Module
Core Installation/update date:			1/09/18
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:

Hello, currently windows assigns 2 com port to my esp32
off 1 single com port enough
is there a way for windows to assign only one com port? As for the usb?
A configuration of this and it is possible for esp32?
Thank you

**Comment by lbernstone** [comment]
This has nothing to do with the esp32, but instead with the USB->UART adapter (and driver) your manufacturer has used.  Most boards only create one port, so purchase a different device.
