### ISSUE TITLE
TG1WDT_SYS_RESET crashes while using Wifi calls

### ISSUE THREAD

**Issue by theDontKnowGuy** [espressif/arduino-esp32#1870]
Migrating ESP8266 project to ESP32. 

Created some layered network access functions to ease various calls.

Getting unstable network response (sometimes response received, sometimes not), getting different header response than in ESP8266 when using WiFiClient.

full code is in this branch: 
https://github.com/theDontKnowGuy/myRFDevicesHub/tree/ESP32-migration

19:29:30.565 -> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
19:29:30.602 -> configsip: 0, SPIWP:0xee
19:29:30.602 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
19:29:30.602 -> mode:DIO, clock div:1
19:29:30.602 -> load:0x3fff0018,len:4
19:29:30.602 -> load:0x3fff001c,len:952
19:29:30.602 -> load:0x40078000,len:6084
19:29:30.602 -> load:0x40080000,len:7936
19:29:30.602 -> entry 0x40080310

Another hung, less common, with Guru Meditation

Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
19:46:54.934 -> Debug exception reason: Stack canary watchpoint triggered () 
19:46:54.972 -> Core 1 register dump:
19:46:54.972 -> PC      : 0x40081440  PS      : 0x00050036  A0      : 0x3ffb0110  A1      : 0x3ffb0050  
19:46:54.972 -> A2      : 0x00000001  A3      : 0x3ffc0e20  A4      : 0x4008149d  A5      : 0xc0000000  
19:46:54.972 -> A6      : 0x3ffb0110  A7      : 0xff000000  A8      : 0x00000020  A9      : 0x40081458  
19:46:54.972 -> A10     : 0x3ffc13e8  A11     : 0x3ffbf7dc  A12     : 0x00000001  A13     : 0x00000000  
19:46:54.972 -> A14     : 0x00000000  A15     : 0x3ffb0040  SAR     : 0x0000001c  EXCCAUSE: 0x00000001  
19:46:55.008 -> EXCVADDR: 0x3e702f3c  LBEG    : 0x4000142d  LEND    : 0x4000143a  LCOUNT  : 0xffffe5da  
19:46:55.008 -> Core 1 was running in ISR context:
19:46:55.008 -> EPC1    : 0x40081440  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x4008c17f
19:46:55.008 -> 
19:46:55.008 -> Backtrace: 0x40081440:0x3ffb0050 0x3ffb010d:0xa5a5a5a5
19:46:55.008 -> 

Board:							ESP32 Dev Module
IDE name:							Arduino IDE
Flash Frequency:					tried both
PSRAM enabled:                                         tried both
Upload Speed:				          921600
Computer OS:                                            MacOS

**Comment by copercini** [comment]
`Stack canary watchpoint triggered` means that your task stack is not enough

**Comment by theDontKnowGuy** [comment]
Thank for copercini for your response!
Is this the case even if I am not using task scheduler at all ? 
Does it basically mean that the regular stack got full ?
thanks again.

**Comment by copercini** [comment]
yes, the stack of main task behind setup() and loop() is full

for test you can increase from 8192 to something bigger here https://github.com/espressif/arduino-esp32/blob/a59eafbc9dfa3ce818c110f996eebf68d755be24/cores/esp32/main.cpp#L24

but 8192 is already a large number, so this may a signal to you review your code structure ;)
