### ISSUE TITLE
question on howto build dependent libraries

### ISSUE THREAD

**Issue by markfink** [espressif/arduino-esp32#1872]
What you are trying to do.
build libfreertos.a (in tools/sdk/lib) 
a 3 month old version is included but I want to know how to build from scratch. I understand this lib includes the FreeRTOS kernel. Once I know how to build the kernel I can build libraries, too. For example I like to add "Amazon FreeRTOS libraries".

Describe your system( Hardware, computer, O/S, core version, environment)
recent Arch distro

**Comment by copercini** [comment]
Arduino for ESP32 is a compatibility layer from arduino code (wiring) to [ESP32 IDF](https://github.com/espressif/esp-idf). To speed up the compilation time the IDF SDK was pre-compiled and included on `tools/sdk/lib` . To compile everything in your machine, you are looking for [Arduino as IDF component](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md) this allow to get IDF from git and make the changes on FreeRTOS core to include/exclude things, change options and also still run Arduino codes on ESP32... If you don't want arduino anymore, you can simple run only ESP32 IDF that is based on FreeRTOS
