### ISSUE TITLE
ESP32 WIFI_AP with WPS

### ISSUE THREAD

**Issue by ripper121** [espressif/arduino-esp32#1873]
Is there a Sample about, how to use WIFI_AP with WPS?

Or is this not possible?

**Comment by copercini** [comment]
Based on https://github.com/espressif/esp-idf/blob/aaf12390eb14b95589acd98db5c268a2e56bb67e/components/esp32/include/esp_event.h#L29 there is only WPS events for STA and nothing for AP, but it's hard to be 100% sure due the WiFi library is not open source, you can try ask Espressif

**Comment by me-no-dev** [comment]
WPS is available only on STA and AFAIK there are not current plans to implement it for AP
