### ISSUE TITLE
i2cSetFrequency(): Fifo threshold=9

### ISSUE THREAD

**Issue by cyberman54** [espressif/arduino-esp32#1883]
In debug level verbose my app reports repeatedly a message

`[V][esp32-hal-i2c.c:1387] i2cSetFrequency(): Fifo threshold=9`

Is this normal behavoir= If not, where should i start with further analysis?

I'm using I2C bus on a Heltec Wifi/Lora Board, acting as a master for one single slave device, the OLED display.

**Comment by stickbreaker** [comment]
Its a debug message only emitted when the core debug level is set at VERBOSE. It is just reporting the fifo threshold. The i2c hardware has two 32byte first in first out buffers that handle the data going out and coming in the i2c bus. When the input fifo(rxFifo) fills to (32-threshold), in this example 23 bytes, the i2c peripheral issues a rxFifo_full interrupt. The peripheral keeps adding data to the fifo. The esp32 has to empty the fifo before it overflows at 32 bytes. As the bus frequency increases, the threshold increases to allow the Esp32 enough time respond.

If you don't want to see this message, reduce the debug level. 

Chuck.
