### ISSUE TITLE
How to use newlib's iconv  on ESP32?

### ISSUE THREAD

**Issue by TridentTD** [espressif/arduino-esp32#1893]
I want to use newlib's libiconv for converting utf8 to iso-8859-11.
Have any example to using iconv on Arduino-ESP32?

Thank you.

**Comment by lbernstone** [comment]
This is an ESP-IDF header.  I think you will have more luck asking [there](https://github.com/espressif/esp-idf/issues)

**Comment by TridentTD** [comment]
Thank you.
