### ISSUE TITLE
PWM functionallity is not workling correctly on channels > 7

### ISSUE THREAD

**Issue by hengesb** [espressif/arduino-esp32#1909]
The PWM functionality is not working correctly on channels 8 - 15. My program below works when I use a channel between 0 an 7 (an LED blinks). When I change to a channel above 7 than setting the value 0 is ignored, setting every other value works.

I take a look in esp32-hal-ledc.c in method ledcWrite and see that there is a different behavior between group 0 an 1 and when setting the value 0 and every other value (lines 174 - 178). I think here must be something wrong for group 1 setting value 0.

PWM Freq = 5000
PWM resolution = 8

### Hardware:
Board:							MH-ET LIVE ESP32 DevKit
Core Installation/update date:			14/jul/2018
IDE name:							Arduino IDE and Platform.io
Flash Frequency:					80Mhz
PSRAM enabled:                                          ?
Upload Speed:						921600
Computer OS:                                            Ubuntu

```cpp

#include <Arduino.h>

#define CHANNEL 8        // Change channel to < 8 to get a working example

void setup() {
  ledcSetup(CHANNEL, 5000, 8);
  ledcAttachPin(22, CHANNEL);
}

void loop() {
  ledcWrite(CHANNEL, 0);       // change value to >0 to see changing values even on channels > 7
  delay(1000);
  ledcWrite(CHANNEL, 100);  
  delay(1000);
}

**Comment by nkast** [comment]
I can confirm. 
When I set duty = 0 on channels 8 - 15 the PWM is not turned off. 

https://github.com/espressif/arduino-esp32/blob/7df50a97d17b0953ea01cad0355410a66bd8b8b4/cores/esp32/esp32-hal-ledc.c#L195-L210

**Comment by nkast** [comment]
bump

**Comment by lbernstone** [comment]
This was fixed 12/4/19.  Please test with v1.0.2.  I can confirm it is working now.
