### ISSUE TITLE
softAPConfig() in WiFiAP.cpp

### ISSUE THREAD

**Issue by yukini3** [espressif/arduino-esp32#191]
There are code error in this API. In softAPConfig, tcpip_adapter_set_ip_info() is called and expecting non-zero return value is successful but zero (ESP_OK) is successful value.
Calling tcpip_adapter_dhcps_start() also the same.

**Comment by me-no-dev** [comment]
aaah I though I fixed those a few days ago. Will do

**Comment by me-no-dev** [comment]
on another note :)
code is correct ;)
if tcpip_adapter_set_ip_info returns non-zero, then it failed and dhcps will be started. Error is that it should return false, regardless of what tcpip_adapter_dhcps_start returns.

**Comment by me-no-dev** [comment]
nevermind... too much code in my head... this is AP not STA
