### ISSUE TITLE
OTA Update from Node Express Server 

### ISSUE THREAD

**Issue by aravindara** [espressif/arduino-esp32#1923]
[](https://github.com/espressif/arduino-esp32/blob/master/libraries/Update/examples/AWS_S3_OTA_Update/AWS_S3_OTA_Update.ino)

I am using this example AWS_S3_OTA_Update i have changed the s3 link to the my server path

this is my node server  snippet
```
  response.writeHead(200, {
        "Content-Type": "application/octet-stream",
        "Content-Disposition": "attachment; filename=" + "ota_update_samples.ino.esp32.bin",
        "Accept-Ranges": "bytes",
        "Content-Length": getFilesizeInBytes(filePath)
      });
      fs.createReadStream(filePath).pipe(response);
      var s = fs.createReadStream(filePath);
```

Got application/octet-stream payload. Got 673456 bytes from server contentLength : 673456, isValidContentType : 1 Begin OTA. This may take 2 - 5 mins to complete. Things might be quite for a while.. Patience! Written only : 45240/673456. Retry? Error Occurred. Error #: 6

 most of the time only half is written i am hosting an node express server locally to test it is there is any other way to get things done.I need to make this happen consistently

Only few times the update is successful

**Comment by SunRag** [comment]
Hi,
I am getting the Error#6 too when using the example AWS_S3_OTA_Update. My file size is 661456, so about the same as yours. Were you able to solve this? Please help!
