### ISSUE TITLE
Remove yield macro

### ISSUE THREAD

**Issue by 256dpi** [espressif/arduino-esp32#193]
The [`yield` macro](https://github.com/espressif/arduino-esp32/blob/8e948096d45e1ba6b63f2da1cc9b95d01488e749/cores/esp32/esp32-hal.h#L43) is very ambiguous and therefore conflicts with other libraries that use `yield` as a symbol.

Now, if other included code uses the identifier `yield` it gets replaced by the macro. We currently have this issue with the  https://github.com/256dpi/arduino-mqtt/pull/56 library.

The best approach would be to declare a function that simply forwards the call:

```c++
// Before
#define yield() vPortYield()

// After
void yield() {
  vPortYield()
}
```

**Comment by me-no-dev** [comment]
done :)

**Comment by 256dpi** [comment]
Thanks!
