### ISSUE TITLE
SYSTEM_EVENT_AP_STACONNECTED event is not working?

### ISSUE THREAD

**Issue by akshar001** [espressif/arduino-esp32#1934]
Hello,
I am trying to connect two esps together one of is a soft-ap and second one in station mode and connected to first esp32 when i pulls the power off of the second esp32 (station mode) in first soft-ap esp32 mode the station disconnect event is not being triggered.

**Comment by beegee-tokyo** [comment]
Same here, however I see (in 50% of AP disappearing) the the event is thrown after up to 15 second, but soketimes not all. Same for LOST_IP event.
In my case I test how to detect the loss of connection to a WiFi router/DSL modem.
