### ISSUE TITLE
How to find IP address of ESP32?

### ISSUE THREAD

**Issue by nomanshahsyed** [espressif/arduino-esp32#1937]
I need to know the IP address of ESP32 on the local network. The idea is to do mDNS or UDP broadcast to send the IP to the android application. The app will then use that IP to do the communication. Is there someone who has already done it? Thanks.

**Comment by martinius96** [comment]
´WiFi.localIP();´
use it with serial print for instance:
´Serial.println(WiFi.localIP());´

**Comment by nomanshahsyed** [comment]
Hi martin thanks for reply. You didn't get my point. I need to know the IP address without serial monitor. I have tried mDNS which works fine but not on Android. I am now trying UDP with which I have some success.

**Comment by uzi18** [comment]
WiFi.localIP(); returns IPAddress, You can print it or use it somewhere.

**Comment by martinius96** [comment]
@nomanshahsyed set it static then :)
https://github.com/espressif/arduino-esp32/issues/1262#issuecomment-386448251

**Comment by nomanshahsyed** [comment]
Guys thanks for your answers. But please read the question before answering. Anyhow the answer to my question is to use UDP broadcast. mDNS is also working but not on android. UDP broadcast is working fine.

**Comment by chuledeco** [comment]
> Guys thanks for your answers. But please read the question before answering. Anyhow the answer to my question is to use UDP broadcast. mDNS is also working but not on android. UDP broadcast is working fine.

Can you please put here how did you solve this problem? Thanks

**Comment by uzairali001** [comment]
I also want to achieve this, can you please share the details how you managed to do it?

**Comment by martinius96** [comment]
mDNS must be enabled on devices and also on network... 
It is not that simple like.. I will start it on ESP and it will work on each device. You need to ALLOW Multicast DNS in your network and on your devices aswell..
