### ISSUE TITLE
ESP32 ETH LAN8720 probably Signal issues

### ISSUE THREAD

**Issue by SkyTheLie** [espressif/arduino-esp32#1938]
Hardware:
Board:							ESP32 Pico Board V4
ETH Modul:                                             LAN8720 ETH Board from Waveshare
IDE name:						Arduino IDE
Flash Frequency:					80MHz
PSRAM enabled:                                      Disabled
Upload Speed:				        115200
Computer OS:                                          Windows 10

Description:

Hello,

I'm trying to connect my ESP32 with the LAN8720 Module. I followed this guide https://sautter.com/blog/ethernet-on-esp32-using-lan8720/ and made a little pin change.
My Pin set up:

GPIO14 - PHY_POWER   : NC - Osc. Enable - 4k7 Pulldown (default is 17 -> change it to 14)
GPIO22 - EMAC_TXD1   : TX1
GPIO19 - EMAC_TXD0   : TX0
GPIO21 - EMAC_TX_EN  : TX_EN
GPIO26 - EMAC_RXD1   : RX1
GPIO25 - EMAC_RXD0   : RX0
GPIO27 - EMAC_RX_DV  : CRS
GPIO00 - EMAC_TX_CLK : nINT/REFCLK (50MHz) - 4k7 Pullup
GPIO23 - SMI_MDC     : MDC
GPIO18 - SMI_MDIO    : MDIO
GND                  : GND
3V3                  : VCC

The Problem is that i don't get a IP. Only one time it worked and i don't know why. I did not change the settings and it never happened again. I Tryed with static IP and it dosn't help. So i thought it would help if i use shorter wires and made a new board but it change nothing. 

I use this example https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/ETH_LAN8720/ETH_LAN8720.ino

I made same changes .:

>// Pin# of the enable signal for the external crystal oscillator (-1 to disable for internal APLL source)
>#define ETH_PHY_POWER   14
>
>// Type of the Ethernet PHY (LAN8720 or TLK110)
>#define ETH_TYPE        ETH_PHY_LAN8720
>
>// I2C-address of Ethernet PHY (0 or 1 for LAN8720, 31 for TLK110)
>#define ETH_ADDR        1
>#define ETH_PHY_ADDR  1
>
>// Pin# of the I2C clock signal for the Ethernet PHY
>#define ETH_MDC_PIN     23
>
>// Pin# of the I2C IO signal for the Ethernet PHY
>#define ETH_MDIO_PIN    18
>
>#define ETH_CLK_MODE ETH_CLOCK_GPIO0_IN
>
>....
>
>void setup()
>{
> Serial.begin(115200);
> WiFi.onEvent(WiFiEvent);
>  //ETH.begin();
>  ETH.begin(         PHY1     ,   14,           23,         18  ,            ETH_PHY_LAN8720);
> //I know that i already define this but i am a little paranoid
>  Serial.println("+");
>  //ETH.config(IPAddress(192, 168, 0, 155),IPAddress(192, 168, 0, 1),IPAddress(255, 255, 255, >0),IPAddress(192, 168, 0, 101),IPAddress(192, 168, 0, 102));
>}
>
>void loop()
>{
>  Serial.println("********************************");
>  Serial.print("IP: ");
>  Serial.println(ETH.localIP());
>  Serial.print("GateWay: ");
>  Serial.println(ETH.gatewayIP());
>  Serial.println("********************************");
>  if (eth_connected) {
>    testClient("google.com", 80);
>  }
>  delay(5000);
>}

output looks like this

<\n>*<\r>
<\n>********************************<\r>
<\n>ETH Started<\r>
<\n>IP: <\r>
<\n>0.0.0.0<\r>
<\n>GateWay: 0.0.0.0<\r>
<\n>********************************<\r>
<\n>ETH Disconnected<\r>  // Taked the ETH cable out 
<\n>ETH Connected<\r>      // Taked the ETH cable in
<\n>********************************<\r>
<\n>IP: 0.0.0.0<\r>
<\n>GateWay: 0.0.0.0<\r>
<\n>********************************<\r>
<\n>********************************<\r>
<\n>IP: 0.0.0.0<\r>
<\n>GateWay: 0.0.0.0<\r>
<\n>********************************<\r>

Here are some Pictures from my Board

![whatsapp image 2018-10-08 at 11 15 01 2](https://user-images.githubusercontent.com/43948226/46602784-7b569100-caf1-11e8-8d0a-de8b4318f771.jpeg)
![whatsapp image 2018-10-08 at 11 15 01 1](https://user-images.githubusercontent.com/43948226/46602799-85788f80-caf1-11e8-9c26-fb5ba1f2d39b.jpeg)
![whatsapp image 2018-10-08 at 11 15 01](https://user-images.githubusercontent.com/43948226/46602802-8a3d4380-caf1-11e8-8e67-e589aa768497.jpeg)

And some Pictures from my Signals that i get on my LAN8720 Board

RX0 Yellow and RX1 Blue
![tek00002](https://user-images.githubusercontent.com/43948226/46603515-91655100-caf3-11e8-8bcf-a01165d0981d.jpg)

MDIO Yellow and MDC Blue
![tek00001](https://user-images.githubusercontent.com/43948226/46603518-95916e80-caf3-11e8-82c5-19ff5a5e7794.jpg)

I tried 2 other ETH LAN8720 boards and one other ESP32 Pico board. It did not change something. The Oscillator is working right too. 

unimportant note.:

This is my first poste on GitHub. I hope you forgive me that I do not know so well with the ESP32 and on the whole i am not so experienced programmer.
I am sorry that my English is not the best.
I hope i did everything rigth and i would be happy if someone could help me.

**Comment by MarkyAD** [comment]
> ETH.begin( PHY1 , 14, 23, 18 , ETH_PHY_LAN8720);

Need to select external clock mode as the last parameter...

 ETH.begin( PHY1 , 14, 23, 18 , ETH_PHY_LAN8720, ETH_CLK_MODE);

**Comment by SkyTheLie** [comment]
Hi @MarkyAD ,

thanks for the fast reply.

>Your router/switch set to only allow certain mac addresses?

No, it is not. Router side is fine i am sure about it.

>ETH.begin( PHY1 , 14, 23, 18 , ETH_PHY_LAN8720, ETH_CLK_MODE);

I tryed this. Just to be sure and it did not change.

**Comment by MarkyAD** [comment]
No pullup on gpio0?

**Comment by MarkyAD** [comment]
ah I see it there, they're both 4.7k?

**Comment by MarkyAD** [comment]
I dunno it looks like its wired up ok, especially if its detecting cable disconnects thats a good sign, but its difficult to tell from here. Mine was really picky about the 50mhz clock. I tried breadboarding it at first and it was intermittent. Then I used pin headers to connect the 2 boards (kinda like Sautter did) with shorter wires (stranded silicone insulated 30ga) and its a lot more reliable.

**Comment by sauttefk** [comment]
@SkyTheLie the I²C/MD answers from the LAN8720 look very noisy. Maybe you should add some decoupling capacitors at the connector of the LAN8720 board. Also try to reduce ground bounce by using a thicker ground-wiring (just like I did on my testboard)

**Comment by SkyTheLie** [comment]
First.: I tried @sauttefk solution and it did not help.
>Maybe you should add some decoupling capacitors at the connector of the LAN8720 board. Also try to >reduce ground bounce by using a thicker ground-wiring

Then i tried @MarkyAD  solution and it helped. Now i get instant a conntection to google.com (or what ever)
>Then I used pin headers to connect the 2 boards with shorter wires and its a lot more reliable.

Second, thank you @MarkyAD and @sauttefk for the quick and helpful answers.

![2b61a2f0-6293-4595-88f5-f73db8fb6b5e](https://user-images.githubusercontent.com/43948226/46669355-749e4b80-cbcf-11e8-9cae-15d94c25810f.jpeg)

**Comment by MarkyAD** [comment]
Nice. I've been prototyping all my boards lately as shield-type designs that let me sandwich and stack various boards together, much like arduino or espduino. Either blank epoxy-glass proto boards or blank uno shield boards work well. If you can pick up some silicone insulated wire, its well worth it. It strips easy with diagonal cutters or nail trimmers and it doesnt melt, a lot like teflon wire without the hassle of having to strip it with precision strippers.

**Comment by sauttefk** [comment]
There have been several issues with the Ethernet / RMII interfacing in the past.

**My reminder for everyone trying to build this by using a breadbord or other simple DIY techniques**

* The RMII-Ethernet interface has a lot of high frequency signals (50MHz), that are problematic with these DYI-techniques.
* Ethernet-PHYs are power hungry and have transient power needs.

* Keep all signals extremely short - especially CLK, TX0, TX1, RX0 and RX1
* Add serial damping resistors ~33Ω on all high frequency signals
* Use a beefy power-supply
* Use thick wiring for Vcc and GND
* Add a decoupling capacitor ~100nF near the connector to the daughter board

* Buy a board from Olimex for 18EUR / ~20USD https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware

**Comment by xenpac** [comment]
This thread gets hit by google a lot!..in search for LAN8720 problems.
just INFO:
esp32 ethernet example with lan8720. idf 3.3.
I can confirm, its most probably a hardware issue.
Got 3 LAN8720 phy boards from china with 50 MHZ oscillator on it.
Two of them worked, one didnt. (init ok, but no traffic). (the others got ip-address and ping ok)
at first also no i2c readings (regs all 0xffff), after power cycle readings ok.

i placed a 1K2 resistor in series 50mhz wire to esp to dampen the signal on powerup(IO0). works.
My 10mhz scope was unable to see the 50mhz and also the i2c traffic...too fast.
Used my SDRsharp radiosniffer to detect the 50mhz signal nicely...even 5 meters away:-)

The software is ok.
