### ISSUE TITLE
send multiple variables using one http.POST request ESP32

### ISSUE THREAD

**Issue by anandpanchal** [espressif/arduino-esp32#1944]
### Hardware:
Board:							        ESP32 Dev Module
Core Installation/update date:			2018
IDE name:							Arduino IDE
Flash Frequency:					        80Mhz
PSRAM enabled:                                             no
Upload Speed:					        115200
Computer OS:                                                 Windows 7

### Description:
Hello Everyone,

i'm trying to send(POST) multiple(2or3) variables using http.POST , e.g http.POST(variable1,variable2) something like this,  but unable to do so. can anyone please help me in doing this ?

Thanks
Anand

![whatsapp image 2018-10-09 at 11 06 01 am](https://user-images.githubusercontent.com/34059153/46648801-43645200-cbb4-11e8-966b-5d807394063a.jpeg)

**Comment by chegewara** [comment]
You can pass one long string which is in form of:
```
grant_type=refresh_token&client_id=amzn1.application-oa2-client&refresh_token=Atzr%7CIwEBID5spY2iwIvtUw5sBKwzHSML
```
But you have to set header:
`Content-Type: application/x-www-form-urlencoded`

**Comment by anandpanchal** [comment]
thanks for the replay.
i do not want to send the url. i need to send date and time. e.g http.post(date, time) something like this

**Comment by anandpanchal** [comment]
http.addHeader("Content-Type", "application/x-www-form-urlencoded");
httpResponseCode = http.POST(date=dayStamp&timeis=timeStamp);
format of dayStamp = 08:09:2018
timeStamp = 12:14:34

error message : no match for 'operator&' (operand types are 'String' and 'String')

**Comment by chegewara** [comment]
`httpResponseCode = http.POST("date=dayStamp&timeis=timeStamp");`

**Comment by anandpanchal** [comment]
![whatsapp image 2018-10-09 at 12 21 41 pm](https://user-images.githubusercontent.com/34059153/46651537-f84f3c80-cbbd-11e8-8b25-9f0387cff502.jpeg)
i am getting this on server side. but i want something like 08:11:2018 12:23:45

**Comment by chegewara** [comment]
I understand, i just gave you example how to fix that error. Now you have to build string before you pass it as argument. Something like that:
```
char _post[40];
sprintf(_post, "date=%s&timeis=%s", dayStamp, timeStamp);
httpResponseCode = http.POST(_post);
```
Just check how to convert dayStamp and timeStamp to string (google it).

**Comment by mehrdad987** [comment]
hey
Is there any restriction on sending data?
I mean I am sending a file content as one string and after 210 lines it couldn't send
whats a problem?
