### ISSUE TITLE
WiFi.softAP Does not run in ESP32

### ISSUE THREAD

**Issue by williamesp2015** [espressif/arduino-esp32#1945]
ESP32
Arduino platform
tested on PlatformIO and Visual Studion 

One month ago I was bale to have an Access Point using WiFi.softAP but now is stopping in   WiFi.softAP(ssid, password);
please test the example : 
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino

**Comment by lbernstone** [comment]
It works fine in Arduino IDE. If you want help, please read the issue template and follow the directions there.
