### ISSUE TITLE
Need help resolving this error compiling for board Adafruit ESP32 Feather.

### ISSUE THREAD

**Issue by themethod01** [espressif/arduino-esp32#1954]
Board: Adafruit ESP32 Feather
Arduino 1.8.4
File: WiFi Scan example

Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/newlib/assert.h:23:25: fatal error: assert.h: No such file or directory

compilation terminated.

**Comment by lbernstone** [comment]
Try [installing through the boards manager](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md)

**Comment by themethod01** [comment]
Thanks, I had previously tried installing using both the boards manager AND the repository. Interesting exercise. Hella dumb.
