### ISSUE TITLE
[VFSImpl::open] cause "Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled." error

### ISSUE THREAD

**Issue by xiruilin** [espressif/arduino-esp32#1963]
In [VFSImpl::open] func, when parameter  "path" == NULL, the line #26 cause error:

`
if(!path || path[0] != '/') {
        log_e("%s does not start with /", path);
        return FileImplPtr();
    }
`

**Comment by lbernstone** [comment]
Your log_e is throwing the error. It can't cast a NULL to %s in the printf.
