### ISSUE TITLE
No library wifimanager ?

### ISSUE THREAD

**Issue by moijerem59** [espressif/arduino-esp32#1964]
Hello, the library wifi manager did not relate to the esp32? If i try the library wifimanager for esp8266 i have compile errors .Thank you
I think it would be interesting to integrate the file library thank you

**Comment by beegee-tokyo** [comment]
Try this one [WIFIMANAGER-ESP32](https://github.com/zhouhan0126/WIFIMANAGER-ESP32). I think it has some problems, but it is the version for the ESP32.

**Comment by moijerem59** [comment]
I tried this library unfortunately even the example does not compile

**Comment by lbernstone** [comment]
The source library at https://github.com/tzapu/WiFiManager works, but you need to use the development branch.

**Comment by lbernstone** [comment]
Why?  It is a separate project, and is actively developed there.
