### ISSUE TITLE
Why is only commit 7951347 of BLE included?

### ISSUE THREAD

**Issue by Bascy** [espressif/arduino-esp32#1970]
This library contains a submodule from BLE, but not the HEAD revision of it if I understand correctly.
Why is this?

There have been a number of commits since this version. Can I update the submodule ?

**Comment by chegewara** [comment]
It is the same commit. Main BLE (esp32-snippets) library is updated but this library is not:
https://github.com/nkolban/ESP32_BLE_Arduino/tree/7951347ed68313d75c367e1f2cce763cb56d1eb2

This is question/request to @nkolban
