### ISSUE TITLE
How to use Serial interrupt using arduino IDE?

### ISSUE THREAD

**Issue by JAICHANGPARK** [espressif/arduino-esp32#1978]
Hi all

I wonder .. How to use serial event( interrupt) of esp32 using arduino IDE?

**Comment by lbernstone** [comment]
The IDF functions are available when using arduino-esp32. https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/uart.html#using-interrupts

**Comment by JAICHANGPARK** [comment]
@JAICHANGPARK Thanks !!
