### ISSUE TITLE
RMT IR reception while using ETH PHY (Waveshare LAN8720) results in RMT error: `mem_full` flag set, `wait` state, `mem_waddr_ex = 0x40`

### ISSUE THREAD

**Issue by johannesmaibaum** [espressif/arduino-esp32#1993]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			Version 1.0.0 28/jul/2018
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                     no
Upload Speed:						921600
Computer OS:                                         Ubuntu 18.04

### Description:
Based on the ESP-IDF example code for the RMT IR reception/transmission (https://github.com/espressif/esp-idf/tree/ee0ebc1/examples/peripherals/rmt_nec_tx_rx) I have created an Arduino style library to send out and receive NEC IR messages. All works fine until I want to add a Waveshare LAN8720 PHY board to the mix (eventually, I want to have the option to switch between Wi-Fi and Wired LAN for my project). As soon as I'm trying to enable the IR reception part, I'm getting a `rmt: RMT[0] ERR` message with a status word that, decoded according to info provided in https://github.com/espressif/esp-idf/issues/1175#issuecomment-428055913, means:

- `mem_full` flag set
- `wait` state
- at `mem_waddr_ex = 0x40`

The question that I have is: Why does it work seamlessly when I'm using standard Wi-Fi mode?

Is the low-level ETH code not compatible with reception of IR messages using the RMT module at the same time?

Also, it's only the reception part which is not working when using the ETH PHY, i.e. IR sending works like a charm both with ETH and WiFi.

Any hint/help is much appreciated!

For reference, I have also created an ESP32.com forum thread for this issue (no answers yet over there): https://esp32.com/viewtopic.php?p=31964

### Sketch:
See this repo for a minimal sketch that shows the issue: https://github.com/johannesmaibaum/ESP32-LAN8720-RMT-test

### Debug Messages (from the sketch linked above, verbose debug level):
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:952
load:0x40078000,len:6084
load:0x40080000,len:7936
entry 0x40080310
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 20 - ETH_START
ETH Started
Trying to enable IR reception:
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 22 - ETH_CONNECTED
ETH Connected
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 24 - ETH_GOT_IP
[D][WiFiGeneric.cpp:425] _eventCallback(): ETH IP: 192.168.5.234, MASK: 255.255.255.0, GW: 192.168.5.1
ETH MAC: 30:AE:A4:24:0A:73, IPv4: 192.168.5.234, FULL_DUPLEX, 100Mbps
E (9428) rmt: RMT[0] ERR
E (9428) rmt: status: 0x14000040
```

**Comment by lbernstone** [comment]
No clue what would cause that, but you can decode the error message with esp_err_to_name().

**Comment by johannesmaibaum** [comment]
Hi @lbernstone , thanks for the hint to `esp_err_to_name`!

I added `Serial.printf` calls for all `esp_err_t`'s in the RX part of my test code, and also pushed these changes to the test repository linked to in the first post.

Yet, I only see `ESP_OK`'s in my log, now:

```
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:952
load:0x40078000,len:6084
load:0x40080000,len:7936
entry 0x40080310
Return value from rmt_config: ESP_OK
Return value from RX rmt_driver_install: ESP_OK
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 20 - ETH_START
ETH Started
Trying to enable IR reception...
Return value from rx_start_ret: ESP_OK
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 22 - ETH_CONNECTED
ETH Connected
[D][WiFiGeneric.cpp:345] _eventCallback(): Event: 24 - ETH_GOT_IP
[D][WiFiGeneric.cpp:425] _eventCallback(): ETH IP: 192.168.2.164, MASK: 255.255.255.0, GW: 192.168.2.1
ETH MAC: 30:AE:A4:24:0A:73, IPv4: 192.168.2.164, FULL_DUPLEX, 100Mbps
E (9594) rmt: RMT[0] ERR
E (9594) rmt: status: 0x14000040
Return value from rmt_get_ringbuf_handle: ESP_OK
Return value from rmt_get_ringbuf_handle: ESP_OK
Return value from rmt_get_ringbuf_handle: ESP_OK
Return value from rmt_get_ringbuf_handle: ESP_OK
Return value from rmt_get_ringbuf_handle: ESP_OK
```

So, it seems like the

```
E (9428) rmt: RMT[0] ERR
E (9428) rmt: status: 0x14000040
```

messages don't originate from any of these calls, but rather from some lower level part of the code that I didn't write. Any idea where I can capture the `esp_err_t`s for the above messages to pass them to `esp_err_to_name` as well?

Is it correct that the API related to the ringbuffers (e.g. `xRingbufferReceive` and friends) does never return any debug information? At least they don't return `esp_err_t`...

**Comment by johannesmaibaum** [comment]
FYI, the `rmt: status: 0x14000040` value doesn't seem to be an `esp_err_t`, because manually passing `0x14000040` to `esp_err_to_name` like this:

```c++
Serial.printf("What is 0x14000040?: %s\n", esp_err_to_name(0x14000040));
```

results in this output:

```
What is 0x14000040?: ERROR
```

**Comment by lbernstone** [comment]
Not exactly plain english, but there is a description of the status codes here:
https://github.com/espressif/esp-idf/issues/1175#issuecomment-428055913

**Comment by johannesmaibaum** [comment]
> Not exactly plain english, but there is a description of the status codes here:
> [espressif/esp-idf#1175 (comment)](https://github.com/espressif/esp-idf/issues/1175#issuecomment-428055913)

Thanks! Will try this next. Hopefully, this gets proper documentation soon!

> Have you tried other channels?

Yes, I tried all 8 channels, all result in the same error.

**Comment by lbernstone** [comment]
I think now that you have this narrowed down to the hardware issue, you need to cross post on https://github.com/espressif/esp-idf/issues/ where the espressif hardware guys can help out.

**Comment by johannesmaibaum** [comment]
I have created a new issue at: https://github.com/espressif/esp-idf/issues/2644

**Comment by johannesmaibaum** [comment]
Closing this now, as espressif/esp-idf#2644 solved my issue.
