### ISSUE TITLE
alway reboot

### ISSUE THREAD

**Issue by xiaodingding** [espressif/arduino-esp32#2006]
Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:952
load:0x40078000,len:6084
load:0x40080000,len:7944
entry 0x40080310

设备一直重启，使用的是USB供电。

**Comment by lbernstone** [comment]
This is a power issue.  Your source (USB?) is not supplying enough electrons.

**Comment by QuadCorei8085** [comment]
https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md

**Comment by copercini** [comment]
This is a power issue as lbernstone said =P
