### ISSUE TITLE
Error : Memory leaks when using BluetoothSerial.h

### ISSUE THREAD

**Issue by NickChungVietNam** [espressif/arduino-esp32#2009]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			?11/jul/2017?
IDE name:							Arduino IDE
Flash Frequency:					40Mhz

Upload Speed:						115200
Computer OS:                                            Windows 10

### Description:
I need create some thing like "SerialBT.restart() " by try this code, But it leaks memory even i Delete it. Please help me.

### Sketch: 
```cpp

#include "BluetoothSerial.h"

#if !defined(CONFIG_BT_ENABLED) || !defined(CONFIG_BLUEDROID_ENABLED)
#error Bluetooth is not enabled! Please run `make menuconfig` to and enable it
#endif


void setup() {
  Serial.begin(115200);
  uint8_t MY_BUFFER[50000];// Big buffer
BluetoothSerial *SerialBT;

while(true){
  SerialBT=new BluetoothSerial();
  SerialBT->begin("E");   delay(100);
   SerialBT->end();       delay(100);
   delete SerialBT;       delay(100);
   Serial.print("FreeHeap="); Serial.println(ESP.getFreeHeap());delay(100);
}
}

void loop() {
  
}
```

### Debug Messages:
```........
FreeHeap=108312
FreeHeap=104588
FreeHeap=100864
FreeHeap=97140
FreeHeap=93416
FreeHeap=89696
FreeHeap=85976
FreeHeap=82252
FreeHeap=78528
FreeHeap=74812
Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4000c46c  PS      : 0x00060630  A0      : 0x80113516  A1      : 0x3ffdaf50  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x0000001c  A5      : 0x00000000  
A6      : 0x401797dc  A7      : 0x00000001  A8      : 0x800d6c11  A9      : 0x3ffdaf10  
A10     : 0x3ffe96c4  A11     : 0x00000000  A12     : 0x00000001  A13     : 0x3ffe778c  
A14     : 0x3ffe15f4  A15     : 0x00000084  SAR     : 0x00000008  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000  

Backtrace: 0x4000c46c:0x3ffdaf50 0x40113513:0x3ffdaf60 0x40113de9:0x3ffdaf80 0x400ef449:0x3ffdafa0 0x400ef483:0x3ffdafc0



```

**Comment by Jeroen88** [comment]
It may not be the cause of your problem, but you are allocating 50,000 bytes on the stack. I do not know the size of the stack, but 50,000 is a lot. What happens if you declare MY_BUFFER outside of setup()

**Comment by NickChungVietNam** [comment]
OK, i removed the buffer, At the end, i still get leak memory.  
```
#include "BluetoothSerial.h"

#if !defined(CONFIG_BT_ENABLED) || !defined(CONFIG_BLUEDROID_ENABLED)
#error Bluetooth is not enabled! Please run `make menuconfig` to and enable it
#endif


void setup() {
  Serial.begin(115200);
BluetoothSerial *SerialBT;

while(true){
  SerialBT=new BluetoothSerial();
  SerialBT->begin("E");   delay(100);
   SerialBT->end();       delay(100);
   delete SerialBT;       delay(100);
   Serial.print("FreeHeap="); Serial.println(ESP.getFreeHeap());delay(100);
}
}

```
FreeHeap=170668
FreeHeap=166028
FreeHeap=161392
FreeHeap=156756
FreeHeap=153032
FreeHeap=149300
FreeHeap=145584
FreeHeap=141860
FreeHeap=138136
FreeHeap=134412
FreeHeap=130688
FreeHeap=126960
FreeHeap=123236
FreeHeap=119508
FreeHeap=115784
FreeHeap=112064
FreeHeap=108344
FreeHeap=104624
FreeHeap=100896
FreeHeap=97168
FreeHeap=93444
FreeHeap=89724
FreeHeap=86000
FreeHeap=82276
FreeHeap=78556
FreeHeap=74832
Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4000c46c  PS      : 0x00060230  A0      : 0x80113516  A1      : 0x3ffdae10  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x0000001c  A5      : 0x00000000  
A6      : 0x401797dc  A7      : 0x00000001  A8      : 0x800d6c11  A9      : 0x3ffdadd0  
A10     : 0x3ffe8fc4  A11     : 0x00000000  A12     : 0x00000001  A13     : 0x3ffe64a4  
A14     : 0x3ffe15f4  A15     : 0x00000084  SAR     : 0x00000008  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000  

Backtrace: 0x4000c46c:0x3ffdae10 0x40113513:0x3ffdae20 0x40113de9:0x3ffdae40 0x400ef449:0x3ffdae60 0x400ef483:0x3ffdae80

**Comment by lbernstone** [comment]
This is community, open source code.  Bolding your text is unlikely to fix the issue.

**Comment by NickChungVietNam** [comment]
Because this error can kill any project even we use it as example.

**Comment by copercini** [comment]
Are you using the last git version? or what version?

**Comment by NickChungVietNam** [comment]
Sorry, I don't remember which version to use, I still use the old library, just never turn it back on.
So the update has fixed this problem?

**Comment by NickChungVietNam** [comment]
@copercini  
Can you try the above code with your latest library, does it run?
