### ISSUE TITLE
IP_FORWARD not work

### ISSUE THREAD

**Issue by folny** [espressif/arduino-esp32#2010]
Hello friends

I'm trying to build the code for an ESP32 repeater but it does not want me to work if anyone can advise me on what the problem might be ? well thank you.

Code

#define IP_FORWARD 1

#include <WiFi.h>
#include <WiFiUDP.h>

// Set these to your desired credentials for ESP32 AP. */
const char *ssid = "EspAp";
const char *password = "";
IPAddress apIP(192, 168, 4, 1);

// Setup credentials for original WiFi, that we plan to repeat
const char* ssidExt = "SSID";
const char* passwordExt = "PASS";

const byte DNS_PORT = 53;

// A UDP instance to let us send and receive packets over UDP
WiFiUDP Udp;
byte packetBuffer[512]; //buffer to hold incoming and outgoing packets

WiFiUDP Udp8;

// Update these with values suitable for your network.
IPAddress ip(192, 168, 2, 222); //Node static IP
IPAddress gateway(192, 168, 2, 1);
IPAddress subnet(255, 255, 255, 0);

void setup()
{
  Serial.begin(115200);
  Serial.println();

  WiFi.mode(WIFI_AP_STA);
  WiFi.begin(ssidExt, passwordExt);
  WiFi.config(ip, gateway, subnet);

  //Wifi connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  WiFi.softAP(ssid, password);
  WiFi.softAPConfig(apIP, IPAddress(192, 168, 4, 1), IPAddress(255, 255, 255, 0));

  Udp.begin(DNS_PORT);
  Udp8.begin(DNS_PORT);
}

void loop()
{

  int noBytes = Udp.parsePacket();
  if ( noBytes ) 
  {

    Udp.read(packetBuffer, noBytes); // read the packet into the buffer

    IPAddress ip8(192, 168, 2, 1);
    Udp8.beginPacket(ip8, DNS_PORT); //NTP requests are to port 123
    Udp8.write(packetBuffer, noBytes);
    Udp8.endPacket();
    delay(100);

    int cb = Udp8.parsePacket();
    if (cb) {
      byte packetBuffer8[cb];
      Udp8.read(packetBuffer8, cb);
      Udp.beginPacket(Udp.remoteIP(), Udp.remotePort());
      Udp.write(packetBuffer8, cb);
      Udp.endPacket();
    }

  }
}

**Comment by lbernstone** [comment]
IP_FORWARD is compiled into the lwip library.  You will need to build [Arduino as an ESP-IDF component](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md)
