### ISSUE TITLE
WiFiClientSecure _connected is not declared in this scope

### ISSUE THREAD

**Issue by OultimoCoder** [espressif/arduino-esp32#2013]
Using platform io, I am trying to build my project which uses  the HTTPClient library which is dependant on the WiFiClientSecure library for the lolin esp 32. 

It works if I don't include the library but when I do I get this error repeated a lot:

framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:33:5: error: '_connected' was not declared in this scope

You can replicate this by just including these libraries and building on platformio. I have also tested with the latest library direct from the github in case it differed from the one I had downloaded.

//Change the code below by your sketch
#include <Arduino.h>
#include <WiFi.h>
#include <HTTPClient.h>

void setup() {
}

void loop() {
}
```

**Comment by Jeroen88** [comment]
A bit of a wild guess, but what if you #include <WiFiClient.h> before #include <WiFiClientSecure.h>? 
_connected is defined protected in WiFiClient and WiFiClientSecure is a public WiFiClient.

**Comment by OultimoCoder** [comment]
In the HTTPClient library it is already set up like that with #include <WiFiClient.h> being included before #include <WiFiClientSecure.h>.

**Comment by lbernstone** [comment]
I am unable to reproduce in Platform.IO using latest release or repo version. Check your ini file and make sure it is not pulling libraries from another location.

**Comment by martinius96** [comment]
Why are you talking WifiClientSecure library and using HTTP library (it supports HTTPS conection too)?
WifiClientSecure example: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino
HTTP library example: https://github.com/espressif/arduino-esp32/blob/master/libraries/HTTPClient/examples/BasicHttpClient/BasicHttpClient.ino

**Comment by KortoVos** [comment]
Had the same error.
After I replaced all folders in "arduinoespressif32\libraries" and it still didn´t work, i saw a "WiFi_ID870" folder in the "lib" folder. I don´t know where it came from, but after i deleted it everything worked fine.
