### ISSUE TITLE
ESP32 GPIO Toggling time is too long

### ISSUE THREAD

**Issue by anandpanchal** [espressif/arduino-esp32#2018]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:	        2018
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                      no
Upload Speed:				        115200
Computer OS:                                         Windows 7

### Description:
ESP32 GPIO High to Low and Low to High time delay is too much. for example if i press the switch(on) , connected to the gpio no 26, it will take around 10 seconds to turn on the lights. similarly if i press the switch(off) , it took around 10 seconds to turn off the lights.
i am confused why this is happening. can anybody help me in this regard ?
Thnaks

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>
const int relay_switch = 26;

void setup()
{
pinMode(relay_switch, INPUT_PULLUP); 

}

void loop()
{
if (digitalRead(relay_switch) == LOW)
{
digitalWrite(led , LOW);
}
if (digitalRead(relay_switch) == HIGH)
{
digitalWrite(led , HIGH);
}

**Comment by bertmelis** [comment]
in setup: `pinMode(led, OUTPUT);`

and try to debounce your relay input pin: https://www.arduino.cc/en/Tutorial/Debounce
