### ISSUE TITLE
firmware revert

### ISSUE THREAD

**Issue by yo2ldk** [espressif/arduino-esp32#203]
ok, 
 I have widora-air module, and I tried wifi scan example.
 Now How I can to revert on original firmware? 
I cannot with reset button and web interface upgrade..
please any tips for help, thank you !

**Comment by me-no-dev** [comment]
what original firmware?

**Comment by yo2ldk** [comment]
widora 
http://wiki.widora.io/doku.php?id=zh:webupdate

**Comment by me-no-dev** [comment]
no idea :) I do not read chinese and the english content is empty. I have no idea what was there before. Maybe contact the producer ;) We do Arduino here

**Comment by yo2ldk** [comment]
:)  Thank you anyway!
