### ISSUE TITLE
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 

### ISSUE THREAD

**Issue by shreyaspaqs** [espressif/arduino-esp32#2032]
after OTA update is done esp32 is restarting continuously 

### Hardware:
Board:							  ESP32 Dev Module
Core Installation/update date:	          8/jun/2016?
IDE name:						  Arduino IDE
Flash Frequency:					  40Mhz
PSRAM enabled:                                       no
Upload Speed:				          115200
Computer OS:                                           Windows 10

### Description:

after updating code from my server using OTA , esp32 is restarting continuously
i have uploaded blinky code through OTA , its was successful and also it blinks for 10 times esp32 getting restarting. 

//Change the code below by your sketch

#include <WiFi.h>
#include <Update.h>

    unsigned long timeout = millis();
    while (client.available() == 0) {
      if (millis() - timeout > 5000) {
        Serial.println("Client Timeout !");
        client.stop();
        return;
      }
    }
   
    if (canBegin) {
      Serial.println("Begin OTA. This may take 2 - 5 mins to complete. Things might be quite for a while.. Patience!");
      
      size_t written = Update.writeStream(client);

      if (written == contentLength) {
        Serial.println("Written : " + String(written) + " successfully");
      } else {
        Serial.println("Written only : " + String(written) + "/" + String(contentLength) + ". Retry?" );
       
      }
      if (Update.end()) {
        Serial.println("OTA done!");
        if (Update.isFinished()) {
          Serial.println("Update successfully completed. Rebooting.");
          ESP.restart();
        } else {
          Serial.println("Update not finished? Something went wrong!");
        }
      } else {
        Serial.println("Error Occurred. Error #: " + String(Update.getError()));
      }
    } else {
      Serial.println("Not enough space to begin OTA");
      client.flush();
    }
  } else {
    Serial.println("There was no content in the response");
    client.flush();
  }
}

void setup() {
  Serial.begin(115200);
  delay(10);

  Serial.println("Connecting to " + String(SSID));
  WiFi.begin(SSID, PSWD);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.print("."); // Keep the serial monitor lit!
    delay(500);
  
  Serial.println("");
  Serial.println("Connected to " + String(SSID));
  execOTA();
}

void loop() {
  
}

```

### Debug Messages:
```

Connecting to wifi_jammer
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 0 - WIFI_READY
...[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:386] _eventCallback(): STA IP: 192.168.43.119, MASK: 255.255.255.0, GW: 192.168.43.2

Connected to wifi_jammer
Connecting to: testwp.shreyas.com
Fetching Bin: /blinkerota/BlinkWithoutDelay1.ino.esp32.bin

HTTP/1.1 200 OK
Date: Thu, 08 Nov 2018 07:50:38 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Wed, 07 Nov 2018 09:02:05 GMT
ETag: "2ae80-57a0f5f541259"
Accept-Ranges: bytes
Content-Length: 175744
Connection: close
Content-Type: application/octet-stream

Got application/octet-stream payload.
Got 175744 bytes from server
contentLength : 175744, isValidContentType : 1

[D][Updater.cpp:129] begin(): OTA Partition: app1
Begin OTA. This may take 2 - 5 mins to complete. Things might be quite for a while.. Patience!
Written : 175744 successfully
OTA done!
Update successfully completed. Rebooting.
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1496
load:0x40078000,len:8596
load:0x40080400,len:6992
entry 0x400806f4
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1496
load:0x40078000,len:8596
load:0x40080400,len:6992
entry 0x400806f4
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1496
load:0x40078000,len:8596
load:0x40080400,len:6992
entry 0x400806f4
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1496
load:0x40078000,len:8596
load:0x40080400,len:6992
entry 0x400806f4
ets Jun  8 2016 00:22:57 
```

**Comment by lbernstone** [comment]
What is it that you are uploading into OTA?  That is what is causing the continuous reboots.

**Comment by shreyaspaqs** [comment]
Am uploading Arduino led  Blink example. and I have stored in my server in this format **blink.ino.esp32.bin**  calling the same file in OTA server link. 
or should I rename like **blink.ino.bin** in my server?

Thanks in advance.

**Comment by shreyaspaqs** [comment]
> What is it that you are uploading into OTA? That is what is causing the continuous reboots.

Am uploading Arduino led Blink example. and I have stored in my server in this format blink.ino.esp32.bin calling the same file in OTA server link.
or should I rename like blink.ino.bin in my server?

Thanks in advance

**Comment by copercini** [comment]
what happens if you try with another code instead  Arduino led Blink example ?

**Comment by shreyaspaqs** [comment]
I have not tried with another code. i will try today.

> what happens if you try with another code instead Arduino led Blink example?

Hi,

I have not tried any other code, today I will try.

And am loading bin file in this format blink.ino.esp32.bin is this way is correct or I need change like blink.ino.bin or blink.bin?

**Comment by shreyaspaqs** [comment]
**blinky code which I have uploaded to the server is** 



#define LED_BUILTIN 2
const int ledPin =  LED_BUILTIN;
int ledState = LOW;          
unsigned long previousMillis = 0;      
const long interval = 1000;         

void setup() {
  pinMode(ledPin, OUTPUT);
}
void loop() {
  unsigned long currentMillis = millis();

  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    if (ledState == LOW) {
      ledState = HIGH;
    } else {
      ledState = LOW;
    }
    digitalWrite(ledPin, ledState);
  }
}

**Comment by copercini** [comment]
try change `#define LED_BUILTIN` to 21 just for test

**Comment by shreyaspaqs** [comment]
> try change `#define LED_BUILTIN` to 21 just for test

sure I will test and update you.

**Comment by shreyaspaqs** [comment]
Hi, 

Now Code is started working issue was that File name should be changed to blink1.ino.esp32.bin to blink1.ino.bin

Thanks everyone.
