### ISSUE TITLE
OTAWebUpdater.ino - ESP32 becomes unreachable

### ISSUE THREAD

**Issue by ESP4Ever** [espressif/arduino-esp32#2035]
### Hardware:
Board:							ESP-WROOM32-based, different board types tested
Core Installation/update date:			this year
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                          no
Upload Speed:						115200
Computer OS:                                            Windows 7

### Description:
Hi there!
Just joined this community.

I'm using the code from the OTAWebUpdater.ino example in my project and I found that the board becomes inaccessible over the network after some time (from a few seconds to about a minute - timeout in the browser, no ping replies). I tried the unmodified example and got the same issue but it recovers time to time. If I remove mDNS (which is useless in my project) the board shuts up forever so it keeps the server alive somehow. Also the regular server access or pinging the board's IP will keep it alive too.
I tried several different boards with the same result. Can you please shoot this trouble?)

### Debug Messages: nothing special

**Comment by lbernstone** [comment]
Try WiFi.setSleep(false)

**Comment by ESP4Ever** [comment]
@lbernstone 
Thank you so much, it solved the problem!
I think that this should be done automatically by the server class initialization...
