### ISSUE TITLE
CMake dependency error "Can not found esp_bt.h" (menuconfiged)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/arduino-esp32#2039]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			08/Nov/2018
IDE name:							CLion
Flash Frequency:					40MHz
PSRAM enabled:                                          no
Upload Speed:						115200
Computer OS:                                            Ubuntu

### Description:
The native cmake and CLion built-in cmake do not compile the project with arduino-esp32 project residing in the local `components` directory.
The error was that the header `esp_bt.h` was not found. The `make` command worked.
I checked the CMake build output and found that the component `arduino` was inserted in the middle of the dependency list while it should be the last, just before the `main` component. 
I checked the `CMakeList.txt` of this repository and found that the dependent components did not contain `bt` [link](https://github.com/espressif/arduino-esp32/blob/85032b226c7775bae510e954112823a2ae32181a/CMakeLists.txt#L201)

I wonder whether this is an intended behavior or a bug?

After adding this dependency, I also found that the BLE submodule contains a compilation error. I forked both projects and now the `arduino` library works with CLion and CMake. If this error is confirmed. I will create a PR.
https://github.com/wuyuanyi135/arduino-esp32

Thank you!

**Comment by ahornerr** [comment]
Check my PR here https://github.com/espressif/arduino-esp32/pull/2172

**Comment by ahornerr** [comment]
My PR https://github.com/espressif/arduino-esp32/pull/2172 was merged, could you update and see if the issue still exists?

**Comment by wuyuanyi135** [comment]
Thanks. Will check it later.
