### ISSUE TITLE
HardwareSerial print not readable....

### ISSUE THREAD

**Issue by pacmenDE** [espressif/arduino-esp32#2042]
### Hardware:
Board:							esp32-devkitc V4
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE
Flash Frequency:					80Mh
PSRAM enabled:                                          ?no?
Upload Speed:						?921000?
Computer OS:                                            ?Windows 10?

### Description:
Hello,
i have some trouble with esp32 an HardwareSerial!
here my script for testing the Serial.
The Serial.print statemt shows me the correct String "Hello World"
But when i use the HardwareSerial1 then i get some other characters.
![grafik](https://user-images.githubusercontent.com/44900354/48267224-11a00e80-e432-11e8-9d54-6d2e93924e71.png)
(Serial.print()),
![grafik](https://user-images.githubusercontent.com/44900354/48267290-3ac09f00-e432-11e8-84c3-000540e388b4.png)
Myserial.print()

Where is the problem?

I would be glad if someone could help me with this....
Thank
Patrik

//Change the code below by your sketch
#include <HardwareSerial.h>
HardwareSerial Myserial(1);
void setup(){
 
   Serial.begin(9600);
   Myserial.begin(9600);
    delay(1000);
    Myserial.println("Hello World");
    Serial.println("Hello World");
}
void loop() {
{

**Comment by lbernstone** [comment]
The bootloader uses 115200 baud. You are seeing the boot sequence garbled.  Set your code to use 115200 on Serial.

**Comment by pacmenDE** [comment]
![grafik](https://user-images.githubusercontent.com/44900354/48270095-7dd24080-e439-11e8-872b-8da91be05f2d.png)
... the same.....

**Comment by pacmenDE** [comment]
![grafik](https://user-images.githubusercontent.com/44900354/48270200-c25ddc00-e439-11e8-8ba7-0dd94de67f00.png)
.....not resolved....:-(

**Comment by lbernstone** [comment]
Turn off Serial1 (MySerial).  Run this code:
```
void setup() {
    Serial.begin(115200);
    Serial.println("Hello World!");
    //Serial1.begin(9600);
    //Serial1.println("Hello World!");
}
void loop(){}
```

**Comment by pacmenDE** [comment]
![grafik](https://user-images.githubusercontent.com/44900354/48271389-837d5580-e43c-11e8-810c-52eff21a379c.png)

"Serial" is running fine....
