### ISSUE TITLE
Partition App

### ISSUE THREAD

**Issue by gigirizzi** [espressif/arduino-esp32#2052]
i don't understamd, can i define only one partition for app? where is the maximum memory?
my partition file is :

# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,     app,  ota_0,   0x10000, 0x1E0000,
app1,     app,  ota_1,   0x1F0000,0x1E0000,
eeprom,   data, 0x99,    0x3F0000,0x1000,
spiffs,   data, spiffs,  0x3F1000,0xF000,

Can i remove app1 for double space?

how can up load one sket for app0 an one for app1?

**Comment by lbernstone** [comment]
The apps will be managed by the [OTA updater](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/ota.html)

The [partition manager is documented here](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/partition-tables.html)
