### ISSUE TITLE
Some functions defined in esp32-hal-uart.c are not declared in esp32-hal-uart.h

### ISSUE THREAD

**Issue by AlessandroAU** [espressif/arduino-esp32#2063]
Some functions defined in esp32-hal-uart.c are not declared in esp32-hal-uart.h,

They are
```
void uartDetachRx(uart_t* uart)

void uartDetachTx(uart_t* uart)

void uartAttachRx(uart_t* uart, uint8_t rxPin, bool inverted)

void uartAttachTx(uart_t* uart, uint8_t txPin, bool inverted)
```

Is this intentional? 

Regards,
Alessandro

**Comment by stickbreaker** [comment]
I would say yes, these functions are just helper functions for `uartBegin()` and `uartEnd()`.  They are not designed to be used by the applications programmer.  

Chuck.

**Comment by AlessandroAU** [comment]
Hi Chuck 

Hmm fair enough, I need to implement bi-directional serial over 1 wire, my plan was to tie RX/TX together with an appropriate resistor and just Detach/Attach the TX pin when needed. Would there be an issue with using those functions to do so?

Regards,
Alessandro

**Comment by AlessandroAU** [comment]
I don't mind if my output shows back up in the input buffer. I can just ignore it in software.
I am interfacing with a RC transmitter which talks over one wire serial.

It sends a command packet every 4ms, and will accept a response in the window between them. Therefore there should not be a risk of both devices sending at once if timings are maintained. 

If I do the following:

detachTX as default
wait for and process command Packet,
attachTX, send response, detachTX,
Flush RX buffer
Wait for next Command Packet. 

Should it not work?

Regards,
Alessandro

**Comment by positron96** [comment]
So, I need to have tx pin inverted and rx pin non-inverted. What are my options, since uartBegin can only change both inversions and separate functions for uartAttachRx\Tx are not exported?

**Comment by lbernstone** [comment]
Please don't hijack issues.  If you want help, man up and open an issue.

**Comment by positron96** [comment]
Hm, sorry, I didn't mean you to get offended. I just think that my problem stems from this exact issue, so I'm not hijacking anything, just expanding.

**Comment by lbernstone** [comment]
It has absolutely nothing to do with the OP issue, other than using uart and esp32.
