### ISSUE TITLE
adc2_vref_to_gpio() odd VRef reading, far too low

### ISSUE THREAD

**Issue by rleinfellner** [espressif/arduino-esp32#2071]
### Hardware:
Board:							M5Stack
Core Installation/update date:		Sep-18
IDE name:					Arduino IDE
Flash Frequency:					80MHz
PSRAM enabled:                                      Not sure
Upload Speed:					921600
Computer OS:                                            Windows 10

### Description:
When trying to map VREF to GPIO 26 with 

esp_err_t status = adc2_vref_to_gpio(GPIO_NUM_26);	//ADC Ref Test
measured output reads 347.5mV not anywhere close to 1100mV as Documentation suggests

**Comment by MarkyAD** [comment]
You had wifi started? ADC2 is used by wifi, don't start wifi and measure again.

**Comment by rleinfellner** [comment]
Many thanks for the tip however I just do M5.begin() then the adc2_vref_to_gpio() so unless M5.begin enables it, I dont.

**Comment by MarkyAD** [comment]
Works as expected here on wroom and wrover modules. Either the pin is not set as an output or something else is using the pin (lora module on m5 uses gpio26).

**Comment by MarkyAD** [comment]
I don't have any m5 boards, but I would try not using M5.begin(); and using just Serial.begin(115200); if you need serial. M5.begin(); is just a wrapper around initializing the display, sd card, speaker and serial.

**Comment by rleinfellner** [comment]
OK, the tip about trying it before M5.begin() is spot on!
If I run it before I get 1.133V, after M5.begin() its corrupted, may be worth putting this into the docs.

**Comment by atanisoft** [comment]
@rleinfellner M5.begin() sets up the LoRA radio reset pin as GPIO 26, that is why you are observing corruption. You can see which pins M5Stack uses here: https://github.com/m5stack/M5Stack/blob/master/src/utility/Config.h#L33
