### ISSUE TITLE
FreeRTOS V8.2.0

### ISSUE THREAD

**Issue by Enderdead** [espressif/arduino-esp32#2082]
Hello,
It's possible to use FREERTOS V10  with your project than the current version (8.2) ?
If it's possible, how can I do this? 
Thank you.

**Comment by lbernstone** [comment]
FreeRTOS is included as part of the [ESP-IDF](https://github.com/espressif/esp-idf).
Short answer- not without a major amount of integration work.

**Comment by Enderdead** [comment]
Yes of course, I have to replace all .h files but I don't know how compile .a file ='(. 
This one : https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/lib/libfreertos.a

**Comment by lbernstone** [comment]
See #1142 and https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md
Be careful of the windmill, Don Quixote.
