### ISSUE TITLE
Using TX / RX as secondary I2C

### ISSUE THREAD

**Issue by YordanYanakiev** [espressif/arduino-esp32#2084]
### Hardware:
Board: ESPDUINO32
Core Installation/update date:			11/jul/2017
IDE name:							Arduino IDE
Flash Frequency:					40Mhz
PSRAM enabled:                                          no
Upload Speed:						115200
Computer OS:                                            Windows 8.1

### Description:
I am trying to switch RX0 and TX0 to SDA / SCL of secondary I2C ( Wire1 object ), but so far it does not works by some reason.

- How to make TX0 / RX0 -> SDA / SCL of secondary I2C - Wire1 object ?

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
	pinMode( 1, FUNCTION_3 );
	pinMode( 3, FUNCTION_3 );

	gpio_pad_select_gpio( GPIO_NUM_1 );
	gpio_set_direction( GPIO_NUM_1, GPIO_MODE_INPUT_OUTPUT );

	gpio_pad_select_gpio( GPIO_NUM_3);
	gpio_set_direction( GPIO_NUM_3, GPIO_MODE_INPUT_OUTPUT );

Wire1.begin( GPIO_NUM_1, GPIO_NUM_3, 100000 );
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by lbernstone** [comment]
Try `Serial.end()` to disconnect from UART.

**Comment by YordanYanakiev** [comment]
so - Serial on which I am debuging is causing issues with the GPIO1/3 ?

**Comment by YordanYanakiev** [comment]
@stickbreaker I am not quite sure how to do that :|

**Comment by stickbreaker** [comment]
Try this sequence.
```c++
Serial.begin();
Serial.end();
```

**Comment by YordanYanakiev** [comment]
Well.. seems like this doesn't work.
By some reason none of above works.

**Comment by YordanYanakiev** [comment]
finally found a way to free 1 more pin, and now I am using TX only as simple digital IO
It worked with this sequence :
setup()
{
	Serial.begin( 115200 );
	Serial.flush();
	Serial.end();
	Serial.flush();
	Serial.end();
...	
    pinMode( GPIO_NUM_1, FUNCTION_3 );
	gpio_pad_select_gpio( GPIO_NUM_1 );
	gpio_set_direction( GPIO_NUM_1, GPIO_MODE_INPUT_OUTPUT );
