### ISSUE TITLE
MLX 90614 , Problem with wire.h?

### ISSUE THREAD

**Issue by Uwe-HH** [espressif/arduino-esp32#2089]
### Hardware:
Board:							NODE ESP 32 from AZDelivery
Core Installation/update date:			20. Nov. 2018
IDE name:					       Arduino IDE
Flash Frequency:					80 MHz
PSRAM enabled:                                          no
Upload Speed:						115200
Computer OS:                                          Windows 10

### Description:
Hello from Germany, I habe a big problem after I have installed a new arduino IDE two days ago. All my old projekts, using MLX 90614 are not more working. I use a Node ESP32 Board. When I check the MLX with a logik analyser, everything was looking well. I use the right address and receive an Acknolge from the Sensor.
Maybe there is a problem with wire.h? I deleded the Arduino folders and reinstalled everything. Also the simple example for the MLX from Adafruit shows me only -273 Degrees temperature. 

Thank you!!

**Comment by stickbreaker** [comment]
What version of Arduino-Esp32 did you install? Release 1.0.0 or this Github dev version.

**Comment by Uwe-HH** [comment]
Thank you for your answer. 3 hours ago I found your informations about the bug in the wire.h and I replaced the four files as you told. Since 30 minutes the system works like I thought . I had no chance to solve the problem without your excellent work. 

At first I installed the _dev repository but the MLX had the same problems, now with the new files everything is OK.

Last question: were can I load the four files, I found only links and used drag and drop to change the contents of the files.

**Comment by stickbreaker** [comment]
#1962 is the same problem.  I have commented many times on this problem. 
on Windows 7, if Arduion-Esp32 is installed using the Arduino Board Manager it adds the repo here:

>C:\Users\\{user name}\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0

when this dev repo is installed it is load here:

> C:\Users\{user name}\Documents\Arduino\hardware\espressif\esp32

Chuck.

**Comment by Uwe-HH** [comment]
Thank you again.

Never change a running system. Now I have the second problem (after I reinstalled the Arduino IDE). My system shows me the WiFi Networks but could not connect to them. When I use a M5Stack with an old WiFi Sanner sketch it runs but after I reinstaled the software I have the same problem.On GITHUB I could not found any informations. Do you have an idea:

Uwe Bruno
