### ISSUE TITLE
WIFi+BT+BLE 

### ISSUE THREAD

**Issue by akshar001** [espressif/arduino-esp32#2093]
Hello,
We are using BT+BLE+WIFI in one of our project,
BT is specifically used for SPP server to view log over BT.
But There is some RF calibration error showing when all runs at same time?

**Comment by chegewara** [comment]
@akshar001 There is too few info. Could you show some logs or elaborate more the problem, also on esp-idf when you open issue you should mention it is arduino issue.

**Comment by akshar001** [comment]
I will share you with logs @chegewara sure.
