### ISSUE TITLE
SmartConfig doesn't work reliable

### ISSUE THREAD

**Issue by VircomSheep** [espressif/arduino-esp32#2095]
Hi,

I want to use Smartconfig to connect my ESP32 with the WiFi. So this is the method which starts the SmartConfig:

`void wifiClass::startSmartConfig()
{ unsigned long wifiCancelTime;  
  Log.notice( LCR );
  Log.notice("Waiting %i secs for SmartConfig packet from mobile...." CR, _smarCfgTimeout ); 

  wifiCancelTime = _smarCfgTimeout*1000 + millis();
  while ( !WiFi.smartConfigDone()  &&  (millis() < wifiCancelTime) )
	{ 	vTaskDelay(200 / TTICK);
    }
 	if (WiFi.smartConfigDone())
	{ 	Log.notice("SmartConfig packet from mobile received...." CR ); 
		vTaskDelay(1000 / TTICK)	 ;			
	//I save Ssid and psk, removed it for better overview
	} else {
		Log.error("SmartConfig packet from mobile failed...." CR ); 
	} 
}`

I implemented SmartConfig in a Xamarin app using this libraray:
[](https://github.com/lucafabbri/EspTouchBinding-Xamarin-iOS-Droid)
When Smartconfig is started on the ESP and on the phone, then the ESP does its job correctly and connects to the wifi given from the phone. The phone should receive the confirmation and the ip address from the ESP, but in 50% of the cases there comes nothing back from the esp. First I thought it's the Xamarin library, but the SmartConfig App from the PlayStore shows the same behaviour. 
Is there a solution for this?
Thank you in advance

**Comment by alf45tar** [comment]
Replace

vTaskDelay(1000 / TTICK);

with 

while (WiFi.status() != WL_CONNECTED) delay(500);


The following code works like a charme.

if (WiFi.smartConfigDone())
  {
    while (WiFi.status() != WL_CONNECTED) {
      delay(500);
    }
  }
