### ISSUE TITLE
Connection problems when using mobile devices

### ISSUE THREAD

**Issue by sirluckyluke** [espressif/arduino-esp32#2096]
Hello folks,

I am working on a project where I try to control servos over a web page. For this, the esp32 is set up in hotspot mode with a DNS server for name resolution and the async web server for content delivery. I am using the esp32 dev module with the latest files for core and async web server. 

Everything is working fine on my development machine (Ubuntu/Firefox/Chrome), I can connect to the esp32 and the web page is shown correctly and also a page refresh is possible. But when I try the same with my mobile phone (android 9) or my tablet (iPad / latest OS) it worked on the first try but when I refresh the page it gets stuck in the refreshing routine and nothing more happens. The weird thing is when I then try to connect from my dev machine the network manager shows an authentication error and wants me to type in the password again (which is not working then). After a hard reset, it is working in most cases till the page refreshing.
Another observation is, that the mobile devices are not really willing to connect to hotspots which are not providing internet. Sometimes my android phone and tablet are disconnecting themselves from the wifi because of no internet or they start using the cellular connection. Furthermore, I see on the web server that the devices requesting some files like "hotspot-detect.html" or "generate_204".

Could this be some problems with the captive portal detection of mobile devices? Which need some special response from the web server? Or a special authentification routine?

I hope someone could get me some advice on how to deal with this.

**Comment by chegewara** [comment]
Do you have routine for http error 404?

**Comment by sirluckyluke** [comment]
yes, to every undefined request I respond with 404...
