### ISSUE TITLE
Webserver re-instantiation

### ISSUE THREAD

**Issue by bot1131357** [espressif/arduino-esp32#2099]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:		Expressif Systems 1.0.0
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                      no
Upload Speed:					115200
Computer OS:                                          Windows 10

### Description:
I need to change the ESP32 to serve up different pages (for softAP mode and STA mode) so I tried re-instantiating the WebServer, but the server doesn't respond after the second instantiation.

Here is the shortest code (based on HelloServer.ino) that replicates the same behaviour. A new WebServer instance is created when millis() is more than 10000.
 
### Sketch:  
```#include <WiFi.h>
#include <WiFiClient.h>
#include <WebServer.h>
#include <ESPmDNS.h>

const char* ssid = "TPG-KRQW";
const char* password = "passqwerty";

WebServer *server=nullptr;

const int led = 13;

void handleRoot() {
  digitalWrite(led, 1);
  char buffer [100];
  sprintf(buffer,"hello from esp8266!\r\nmillis():%d",millis());
  server->send(200, "text/plain", buffer);
  digitalWrite(led, 0);
}

void setup(void) {
  pinMode(led, OUTPUT);
  digitalWrite(led, 0);
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.println("");

  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  if (MDNS.begin("esp32")) {
    Serial.println("MDNS responder started");
  }
  startServer();
}

void startServer()
{
  delete server;
  server = new WebServer(80);
  server->on("/", handleRoot);
  server->begin();
  Serial.println("HTTP server started");
}
int nTimes = 1;
const uint32_t timeToCreateServer = 10000;
void loop(void) {
  if(nTimes && millis()>timeToCreateServer)
  {
    --nTimes;
    startServer();
  }
  server->handleClient();
}
```

### Debug Messages:
```
.....
Connected to TPG-KRQW
IP address: 192.168.1.102
MDNS responder started
HTTP server started (working here)
HTTP server started (not working here)
```

**Comment by g01d10x** [comment]
Did you ever get any resolution to this? I'm having a similar problem.

**Comment by bot1131357** [comment]
I was going to implement a fix, but I never did get around to doing it. It seems like the WebServer classs does not have a proper destructor. 

A quick workaround would be to have the handler functions execute a function pointer which can be modified to access different functions during runtime. Something like this:

```
void serveMainPage()
{/*serve main page*/}

void serveAnotherPage()
{/*serve another page*/}

void (*function_ptr)(void) = &serveMainPage;

void changeFunctionPtr()
{
  function_ptr = &serveAnotherPage;
}
```
Hope this helps.

**Comment by bot1131357** [comment]
Good bot. I think this should be closed given the lack of interest.

**Comment by atanisoft** [comment]
@bot1131357 ESPAsyncWebServer can do exactly what you're wanting to do without reinit or changing the server config once started. I'd suggest looking at that instead of the WebServer.h code.

**Comment by bot1131357** [comment]
@atanisoft Noted. Thanks!
