### ISSUE TITLE
Unable to cache built core, please tell esp32 maintainers to follow http://goo.gl/QdCUjo

### ISSUE THREAD

**Issue by fabiuz7** [espressif/arduino-esp32#2105]
### Hardware:
Board:							Lolin D32
Core Installation/update date:			c3ec91f9683954e567ebddc77312c004ef42c933
IDE name:							Arduino IDE 1.8.7
Flash Frequency:					80Mhz
PSRAM enabled:                                          no
Upload Speed:						912600
Computer OS:                                            Windows 10

### Description:
Arduino IDE gives me the following error/warning while compiling:

> Unable to cache built core, please tell esp32 maintainers to follow http://goo.gl/QdCUjo

I'm using the last git version, but I've also tried with release 1.0.0, same issue.

**Comment by tedder** [comment]
Looks like esp8266 was patched in  https://github.com/esp8266/Arduino/commit/85e68093e94b4e5c5e711888b8b5facee1bd4f9f , which came out of https://github.com/esp8266/Arduino/issues/5169 , PR was https://github.com/esp8266/Arduino/pull/5018 .
