### ISSUE TITLE
Multitasking affecting loop()

### ISSUE THREAD

**Issue by beats0126** [espressif/arduino-esp32#2106]
in void setup called 
xTaskCreatePinnedToCore(
		core_two_task,          /* Function to implement the task */
		"core_two_task",        /* Name of the task */
		10000,                  /* Stack size in words */
		NULL,                   /* Task input parameter */
		20,                     /* Priority of the task */
		NULL,                   /* Task handle. */
		1);
to assign multitasking on core1.
But after that i found the function inside normal loop
void loop()
{
     Serial.println("123")
     delay(1000);
}
no work anymore...

this one happen when i upgrade to stable version 1.0
isit the void loop disable after applying multitasking?

and i also found that the WiFi.status() no working in multitask. When entry multitasking loop, the WiFi.status wont update anymore...
example: wifi connected, and Serial.println(WiFi.status()) will display "3", disconnected will display "6". But in the multitasking, after connected will display "3", but when disconnect wifi will still showin "3"...

have anyone meet the problem above?

**Comment by chegewara** [comment]
Try with task priority 15 or less. Wifi task may be 19 i think and your task wont allow it to update.

**Comment by chegewara** [comment]
What task is triggering watchdog?

**Comment by beats0126** [comment]
@chegewara  
void loop()
{
  Serial.println("123");
delay(1000);
}

void core_one_task(void *pvParameter)
{
	while (true)
	{
		LoopOne();
	}
	vTaskDelete(NULL);
}

void core_two_task(void *pvParameter)
{
	while (true)
	{
		LoopTwo();
	}
	vTaskDelete(NULL);
}

void LoopOne()
{
   if(WiFi.status() != WL_CONNECTED)
 {
   WiFi.begin(ssid, pass);
 }
while(WiFi.status() != WL_CONNECTED)
 {
  Serial.println("...");
  delay(1000);
 }
}

void LoopTwo()
{
int packetSize = LoRa.parsePacket();
	if (packetSize) 
  {
		// read packet
		while (LoRa.available()) 
       {
			Serial.print((char)LoRa.read());
       }
   }
}

**Comment by beats0126** [comment]
@chegewara  i dont think this few task will trigger it. i do it before, now the problem happen when i update the esp core to latest...
i have to use latest build because latest build fix the i2c pin and sleep mode. my old build cannot do it.

**Comment by beats0126** [comment]
after i do few testing. i can confirm the lora affecting wifi and multitasking work

/*
 Name:		CCU.ino
 Created:	11/28/2018 7:58:01 AM
 Author:	YzArC
*/

#include <WiFi.h>

#define W_SSID	"Omega"
#define W_PASS	"0166060853"

int w_retry = 0;
byte mac[6];

#include <LoRa.h>
#include <SPI.h>

#define BAND    433E6

#define SCK     5    // GPIO5  -- SX1278's SCK
#define MISO    19   // GPIO19 -- SX1278's MISnO
#define MOSI    27   // GPIO27 -- SX1278's MOSI
#define SS      18   // GPIO18 -- SX1278's CS
#define RST     14
#define DI0     26

// the setup function runs once when you press reset or power the board
void setup() {
	Serial.begin(115200);
	delay(50);

	wifi_begin();
	delay(50);

//point 1
	/*pinMode(DI0, INPUT);
	LoRa.setPins(SS, RST, DI0);
	if (!LoRa.begin(BAND)) {
		Serial.println("Starting LoRa failed!");
		while (1);
	}
	Serial.println("LoRa Initial OK!");
	delay(50);*/

	xTaskCreatePinnedToCore(
		core_one_task,          /* Function to implement the task */
		"core_one_task",        /* Name of the task */
		4096,                  /* Stack size in words */
		NULL,					/* Task input parameter */
		15,                     /* Priority of the task */
		NULL,                   /* Task handle. */
		0);

	xTaskCreatePinnedToCore(
		core_two_task,          /* Function to implement the task */
		"core_two_task",        /* Name of the task */
		4096,                  /* Stack size in words */
		NULL,                   /* Task input parameter */
		15,                     /* Priority of the task */
		NULL,                   /* Task handle. */
		1);
}

// the loop function runs over and over again until power down or reset
void loop() {
	Serial.println("shit");
	delay(1000);
}

void core_one_task(void *pvParameter)
{
	while (true)
	{
		if (LoopOne() == 1)
		{

		}
	}
	vTaskDelete(NULL);
}

void core_two_task(void *pvParameter)
{
	while (true)
	{
		if (LoopTwo() == 1)
		{

		}
	}
	vTaskDelete(NULL);
}

int LoopOne()
{
	Serial.println("Task 1");
	if (WiFi.status() != WL_CONNECTED)
	{
		wifi_begin();
	}
	delay(100);

	return 1;
}

int LoopTwo()
{
//point 2
	//int packetSize = LoRa.parsePacket();
	//if (packetSize) {
	//	// read packet
	//	while (LoRa.available()) {
	//		Serial.print((char)LoRa.read());
	//	}
	//}
        delay(10);
	return 1;
}

void wifi_begin()
{
	wifi_status();

	WiFi.begin(W_SSID, W_PASS);

	Serial.print("Connecting to ");
	Serial.print(W_SSID);

	while (WiFi.status() != WL_CONNECTED && w_retry <= 10)
	{
		Serial.print("...");
		w_retry++;
		delay(1000);
	}

	Serial.println();

	if (WiFi.status() == WL_CONNECTED)
	{
		Serial.println("Connected!");
		Serial.print("IP address: ");
		Serial.println(WiFi.localIP());

		WiFi.macAddress(mac);
		Serial.print("MAC: ");
		Serial.print(mac[0], HEX);
		Serial.print(":");
		Serial.print(mac[1], HEX);
		Serial.print(":");
		Serial.print(mac[2], HEX);
		Serial.print(":");
		Serial.print(mac[3], HEX);
		Serial.print(":");
		Serial.print(mac[4], HEX);
		Serial.print(":");
		Serial.println(mac[5], HEX);
	}
	else
	{
		Serial.println("No Connected... Will try next...");
	}

	w_retry = 0;
}

void wifi_status()
{
	Serial.print("WiFi Status : ");
	Serial.println(WiFi.status());
}

this is the code i using, uncomment point 1 and point 2 will come out my problem

**Comment by chegewara** [comment]
Everything fine, but could you show logs with watchdog?

**Comment by beats0126** [comment]
@chegewara 
i using esp32 core version 1.0.0 rc4
heltec wifi lora 32 board

Task watchdog got triggered. The following tasks did not reset the watchdog in time:
IDLE0 (CPU 0)
Tasks currently running:
CPU 0: core_one_task
CPU 1: IDLE1

**Comment by chegewara** [comment]
Now you have to find what is `core_one_task` because it is nothing in esp core library or wifi or any library i know.

**Comment by beats0126** [comment]
i create this task at 
void setup()
{
  xTaskCreatePinnedToCore(
	core_one_task,          /* Function to implement the task */
	"core_one_task",        /* Name of the task */
	4096,                  /* Stack size in words */
	NULL,					/* Task input parameter */
	15,                     /* Priority of the task */
	NULL,                   /* Task handle. */
	0);
}

void core_one_task(void *pvParameter)
{
     while (true)
       {
           if (LoopOne() == 1)
           {
            }
        }
       vTaskDelete(NULL);
}

int LoopOne()
{
    return 1;
}

is it my logic wrong? the core_one_task is the task name i pinned to the core

**Comment by chegewara** [comment]
Its all fine, but you have to change this task a little bit. This task is taking all time from core 0. There is a lot different techniques, but on beginning just add `delay(1)` in while loop.

**Comment by beats0126** [comment]
@chegewara the delay(1) will cause the LoRa receiver? because before this i try with delay(10) or delay(5) will causing lora miss the message from other lora. the delay(1) i havent try it. but is it will causing lora miss receive message?

the logic i know for this is delay is something like set a empty task for esp, during the task it wont do anything, so if the lora message send out at this moments will no received. 

btw after add in delay(1), the watchdog no triggered.

**Comment by chegewara** [comment]
`delay(1)` is very special delay in esp-idf. It is used to allow switch tasks when you have very CPU greedy task. Of course it not always works in app design, all depend on your app requirements.

**Comment by beats0126** [comment]
@chegewara 
thanks for help. just now i tried with set the LoRa.Receiver() , the lora receivercallback function. i think it is better way for my project. because my project is using esp32 lora board to make a gateway, the message from lora sender to lora receiver cannot missed, so if i put delay may causing some problem. so i think use the receivercallback will reach my target. by the way, thanks again for helping. i think i will close this issues now seen my issues got other solution.
