### ISSUE TITLE
ESP32-WROVER-I hangs and freeze!!!

### ISSUE THREAD

**Issue by ArTyGill** [espressif/arduino-esp32#2122]
ESP32-Wrover-i It hangs for no reason and does not work until the device is hard reset, there are 2 watchdog timers and work fine, but it still freezes once a week for no reason.

**Comment by ArTyGill** [comment]
Help me!

**Comment by snejky** [comment]
Hi. Same here. ESP32 TTGO + Wifi + Blynk + DHT22 + Phototransistor. In void loop i have only Blynk() and Timer(). I think its wifi-reconnecting related. My watchdogs works fine, but device still freeze once a day... Ive tesated different cables, power supplyes, watchdog implementations etc. So sad with that.

**Comment by snejky** [comment]
Thanks! Did it solve your problems? I try on Sunday.

**Comment by ArTyGill** [comment]
@snejky Yes, i don't have freezes on v1.0.0 :)

**Comment by ArTyGill** [comment]
Very stable version for me 1.0.3
