### ISSUE TITLE
About CONFIG_MBEDTLS_INTERNAL_MEM_ALLOC

### ISSUE THREAD

**Issue by xiruilin** [espressif/arduino-esp32#2129]
Hi, When CONFIG_MBEDTLS_INTERNAL_MEM_ALLOC = 1, available internal memory reduce 30K-40K,
maybe can change to CONFIG_MBEDTLS_DEFAULT_MEM_ALLOC = 1.
Thanks

**Comment by lbernstone** [comment]
Recommended is internal.  If you need to recover that memory, then you can compile [arudino as an esp-idf component](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md).
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html#config-mbedtls-mem-alloc-mode
