### ISSUE TITLE
adafruit esp32 feather Arduino IDE not port recognition  

### ISSUE THREAD

**Issue by guevarajoge** [espressif/arduino-esp32#2134]
----------------------------- Remove above -----------------------------

### Hardware:
Board:							ESP32 adafruit feather 

IDE name:							Arduino IDE

Computer OS:                                           Mac OS 10.13 
### Description:
Describe your problem here

Installing ESP32 adafruit feather in Arduino IDE - Mac OS 10.13 

After following  the installing from the git https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md, 

I select Tools>Boards>  "Adafruit ESP32 Feather" 
but Tools>Port > is not showing the board.

Can anybody can help me ?

**Comment by lbernstone** [comment]
https://desire.giesecke.tk/index.php/2018/01/30/esp32-not-showing-in-serial-port-mac-desktop-laptop-problem/
