### ISSUE TITLE
Compiler Corner Case

### ISSUE THREAD

**Issue by stickbreaker** [espressif/arduino-esp32#2138]
### Hardware:
Board:							Heltec_WIFI_LoRa_32
Core Installation/update date:			01NOV2018
IDE name:						Arduino IDE 1.8.5
Flash Frequency:					80Mhz
PSRAM enabled:                                      ?no?
Upload Speed:						921600
Computer OS:                                          Windows 7 pro

### Description:
Ok, this is a weird one.
I ran into what I think is a compiler corner case.  I am testing a modification to the `Wire()` library.
I am validating ReSTART Write/Read queuing. I have a known content of an EEPROM that I am randomly reading blocks from.  Both address and length are random, I create a list of address,length records that will fill the 128byte internal `Wire()` Read buffer.  Then I interleave the Write address selections(`Wire.endTransmission(false))` with `requestFrom(id,len,false)` Read operations, the last `Wire.requestFrom(id,len,TRUE);` actually causes all these queued operations to execute. 

My mod's to `Wire()` are working, but My TESTING failed.  I made a mistake with a variable declaration,  I should have used an uint16_t but used a uint8_t, so, I had a truncation problem.  BUT, the weird part was that I could change a constant used in a prior calculation to 'solve' the bad coding problem.  

This is the code of the misbehaving test function, notice `masterOffset` is declared at uint16_t, but it is stuffed into a `uint8_t` as `uint8_t b=masterOffset;`  so if `masterOffset` is >255 `b` only receives the lower byte.  `masterOffset` is a calculated value.  If I change the calculation it will correctly work.  
Failing calculation of `masterOffset` `(blocks[a].addr - 0x400)` working calculation `(blocks[a].addr - 0x0400)`
### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```c++
bool testBlock(uint8_t * master, uint16_t masterLen,
  uint8_t * data, uint16_t dataLen, uint16_t masterOffset, uint16_t dataDisplayOffset){
  uint8_t a = 0;
  uint8_t b = masterOffset;
  bool good = true;
  bool err=false;
  Serial.printf("TestBlock masterLen=%d, dataLen=%d, masterOffset=%d, dataDisplayOffset=0x%04X\n",masterLen,dataLen,b,dataDisplayOffset);
 while((a<dataLen)&&(b<masterLen)){
    if( master[b] != data[a]){
      if(!err){
        Serial.printf("MisMatch  0x%04X ",dataDisplayOffset+a);
        err = true;
      }
      Serial.printf("[%03X]%02x~%02x[%03X] ",b,master[b],data[a],a);
      good = false;
    } else {
      if( err){
        Serial.printf(": 0x%04X\n",dataDisplayOffset+a);
        err = false;
      }
    }
    a++;
    b++;
  }
  if(err)       Serial.printf(": 0x%04X\n",dataDisplayOffset+a);
  return good;
}

typedef struct blockRec_t{
  uint16_t addr;
  uint16_t len;
} blockRec_t;

//failing code
   Serial.printf(" testing offset=%d, len=%d, masterOffset = 0x%04X, addr = 0x%04X\n", offset, blocks[a].len,(blocks[a].addr-0x400),blocks[a].addr);
    testBlock((uint8_t*)&MASTERDATA,sizeof(MASTERDATA),(uint8_t*)&data[offset],blocks[a].len,(blocks[a].addr-0x400),blocks[a].addr);
 
 // working code by changing testBlock() calculation to -0x0400
   Serial.printf(" testing offset=%d, len=%d, masterOffset = 0x%04X, addr = 0x%04X\n", offset, blocks[a].len,(blocks[a].addr-0x400),blocks[a].addr);
    testBlock((uint8_t*)&MASTERDATA,sizeof(MASTERDATA),(uint8_t*)&data[offset],blocks[a].len,(blocks[a].addr-0x0400),blocks[a].addr);

 // working code by changing local variable declaration in testBlock from uint8_t to uint16_t
   uint16_t a = 0;
   uint16_t b = masterOffset;

``` 

### Debug Messages:
Failing output with `testBlock()` `masterOffset` calculated as `(blocks[a].addr-0x400)`
>testing offset=118, len=6, masterOffset = 0x012D, addr = 0x052D
TestBlock masterLen=512, dataLen=6, masterOffset=45, dataDisplayOffset=0x052D
>testing offset=126, len=2, masterOffset = 0x0100, addr = 0x0500
TestBlock masterLen=512, dataLen=2, masterOffset=0, dataDisplayOffset=0x0500
>testing offset=128, len=0, masterOffset = 0x018F, addr = 0x058F
TestBlock masterLen=512, dataLen=0, masterOffset=143, dataDisplayOffset=0x058F
>testing offset=128, len=0, masterOffset = 0x0180, addr = 0x0580
TestBlock masterLen=512, dataLen=0, masterOffset=128, dataDisplayOffset=0x0580

Working output by changing `masterOffset` calculation `(blocks[a].addr-0x0400)` in TestBlock() function call
The debug "TestBlock" output is showing the byte value, all offsets above 255 byte are displayed as bytes,
but are used as 16bit values, the test `master[b]==data[a]` is succeeding.

> testing offset=124, len=2, masterOffset = 0x0168, addr = 0x0568
TestBlock masterLen=512, dataLen=2, masterOffset=104, dataDisplayOffset=0x0568
testing offset=128, len=0, masterOffset = 0x01F0, addr = 0x05F0
TestBlock masterLen=512, dataLen=0, masterOffset=240, dataDisplayOffset=0x05F0
testing offset=128, len=0, masterOffset = 0x0074, addr = 0x0474
TestBlock masterLen=512, dataLen=0, masterOffset=116, dataDisplayOffset=0x0474
testing offset=128, len=0, masterOffset = 0x0060, addr = 0x0460
TestBlock masterLen=512, dataLen=0, masterOffset=96, dataDisplayOffset=0x0460
testing offset=128, len=0, masterOffset = 0x0156, addr = 0x0556
TestBlock masterLen=512, dataLen=0, masterOffset=86, dataDisplayOffset=0x0556
testing offset=128, len=0, masterOffset = 0x019A, addr = 0x059A
TestBlock masterLen=512, dataLen=0, masterOffset=154, dataDisplayOffset=0x059A
testing offset=128, len=0, masterOffset = 0x0087, addr = 0x0487
TestBlock masterLen=512, dataLen=0, masterOffset=135, dataDisplayOffset=0x0487

Working output by fixing local variable declaration from `uint8_t` to `uint16_t`
>testing offset=128, len=0, masterOffset = 0x0036, addr = 0x0436
TestBlock masterLen=512, dataLen=0, masterOffset=54, dataDisplayOffset=0x0436
testing offset=128, len=0, masterOffset = 0x01E5, addr = 0x05E5
TestBlock masterLen=512, dataLen=0, masterOffset=485, dataDisplayOffset=0x05E5
testing offset=128, len=0, masterOffset = 0x00F7, addr = 0x04F7
TestBlock masterLen=512, dataLen=0, masterOffset=247, dataDisplayOffset=0x04F7
testing offset=128, len=0, masterOffset = 0x012C, addr = 0x052C
TestBlock masterLen=512, dataLen=0, masterOffset=300, dataDisplayOffset=0x052C
testing offset=128, len=0, masterOffset = 0x0142, addr = 0x0542
TestBlock masterLen=512, dataLen=0, masterOffset=322, dataDisplayOffset=0x0542
testing offset=128, len=0, masterOffset = 0x0033, addr = 0x0433
TestBlock masterLen=512, dataLen=0, masterOffset=51, dataDisplayOffset=0x0433

Does anyone have an idea what should be done about this case?

Chuck.

**Comment by everslick** [comment]
I also experienced a compiler bug (but for the lx106 in my case) and did not find a good place to report it. I guess the tensilica gcc backend is directly maintained by tensilica inc. itself. no?

**Comment by stickbreaker** [comment]
yea, I think this corner case would be ignored by the compiler developers, and my mistake of incorrect type would emphasized.  I believe that this behavior could be a symptom of other subtle issues.  

I just needed to vent, wasted too much time tracking this down. I don't like unexplained reactions.  Ghosts in the machine can grow to catastrophic infections if the code relies on these subtle unintended interactions.  Just changing the constant from 0x400 to 0x0400 should never cause a different result.

Chuck.

**Comment by everslick** [comment]
for me it was a bogus calculation of the address of struct members when __attribute__(packed) was used. so the & operator ignored the *packed* but regular member access still worked. seems to be something that is not used (i.e. tested for) very often nowadays! :-D
