### ISSUE TITLE
Hardware Timers

### ISSUE THREAD

**Issue by williamhemmingsen** [espressif/arduino-esp32#214]
Are there any examples of hardware timers for Arduino IDE?  I have used ESP32 hw timers a lot, but can't make since of them in the ESP32.

I need to sample the adc a a specified rate.  I would like to attachinterrupt to and ISR.  Here is what I'm doing in the ESP8266.  How do I do this in the ESP32?

void timer_init(void) {
 timer1_isr_init();
  timer1_attachInterrupt(sample_isr);
  timer1_enable(TIM_DIV1, TIM_EDGE, TIM_LOOP);
  timer1_write(8333); //9600 samples/s
}

void ICACHE_RAM_ATTR sample_isr() {
...do some stuff
}

Thanks!

**Comment by me-no-dev** [comment]
```cpp
hw_timer_t * timer = NULL;

void onTimer(){
    Serial.print("timer ");
    Serial.println(millis());
}

// start/stop the timer
void toggleTimer(){
    if(timer){
        timerEnd(timer);
        timer = NULL;
    } else {
        timer = timerBegin(3, 80, 1);//div 80
        timerAttachInterrupt(timer, &onTimer, 1);
        timerAlarmWrite(timer, 1000000, true);//1000ms
        timerAlarmEnable(timer);
    }
}
```

**Comment by arcao** [comment]
There is example which call `onTimer` every second:
```cpp
hw_timer_t * timer = NULL;

void onTimer(){
  static unsigned int counter = 1;
  
  Serial.print("onTimer ");
  Serial.print(counter);
  Serial.print(" at ");
  Serial.print(millis());
  Serial.println(" ms");

  if (counter == 10)
    endTimer();

  counter++;
}

void startTimer() {
  timer = timerBegin(0, 80, true); // timer_id = 0; divider=80; countUp = true;
  timerAttachInterrupt(timer, &onTimer, true); // edge = true
  timerAlarmWrite(timer, 1000000, true);  //1000 ms
  timerAlarmEnable(timer);
}

void endTimer() {
  timerEnd(timer);
  timer = NULL; 
}

void setup() {
  Serial.begin(115200);
  startTimer();
}

void loop() {}
```

**Comment by me-no-dev** [comment]
@arcao you asked me as I was looking at the issue :D

**Comment by williamhemmingsen** [comment]
Thanks Guys, That was perfect.  Thanks again for the quick response

**Comment by me-no-dev** [comment]
:)

**Comment by arcao** [comment]
BTW I added example: https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/Timer/RepeatTimer/RepeatTimer.ino

**Comment by williamhemmingsen** [comment]
Thanks!  I used your timer example successfully to implement my project.
Thanks again

GitHub - williamhemmingsen/WSPR-ESP32: WSPR implementation using the ESP32 and Si5351


  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
GitHub - williamhemmingsen/WSPR-ESP32: WSPR implementation using the ESP32 ...
 WSPR-ESP32 - WSPR implementation using the ESP32 and Si5351  |   |

  |

  |

**Comment by tobozo** [comment]
Your comment is exposing your email address

**Comment by me-no-dev** [comment]
not anymore :)

**Comment by maxpromer** [comment]
How to restart timer ? I test by
```
hw_timer_t * timer = NULL;

void onTimer(){
    Serial.print("timer ");
    Serial.println(millis());
}

// start/stop the timer
void toggleTimer(){
    if(timer){
        timerEnd(timer);
        timer = NULL;
    } else {
        timer = timerBegin(3, 80, 1);//div 80
        timerAttachInterrupt(timer, &onTimer, 1);
        timerAlarmWrite(timer, 100000, true);//1000ms
        timerAlarmEnable(timer);
    }
}

void setup() {
  Serial.begin(115200);
}

void loop() {
  toggleTimer();
  delay(1000);
}
```
timer not new start.

**Comment by lrmoreno007** [comment]
```
hw_timer_t * timer = NULL;

void onTimer(){
	Serial.print("Alarm: make something at ");
	Serial.print(millis()/1000);
	Serial.println("s");
}

void setup() {
	Serial.begin(115200);
	timer = timerBegin(1, 80, 1);//Timer number 1, 80 is the CPU frequency, 1 counter up
	timerAttachInterrupt(timer, &onTimer, 1);
	timerAlarmWrite(timer, 1000000, true); //1 second and autoreload enabled
	timerAlarmEnable(timer);
}

void loop() {

}
```

**Comment by XingyumLee** [comment]
> ```c++
> hw_timer_t * timer = NULL;
> 
> void onTimer(){
>     Serial.print("timer ");
>     Serial.println(millis());
> }
> 
> // start/stop the timer
> void toggleTimer(){
>     if(timer){
>         timerEnd(timer);
>         timer = NULL;
>     } else {
>         timer = timerBegin(3, 80, 1);//div 80
>         timerAttachInterrupt(timer, &onTimer, 1);
>         timerAlarmWrite(timer, 1000000, true);//1000ms
>         timerAlarmEnable(timer);
>     }
> }
> ```
where to download the lib

**Comment by XingyumLee** [comment]
> **Edit:** @me-no-dev was faster :)
> 
> There is example which call `onTimer` every second:
> 
> ```c++
> hw_timer_t * timer = NULL;
> 
> void onTimer(){
>   static unsigned int counter = 1;
>   
>   Serial.print("onTimer ");
>   Serial.print(counter);
>   Serial.print(" at ");
>   Serial.print(millis());
>   Serial.println(" ms");
> 
>   if (counter == 10)
>     endTimer();
> 
>   counter++;
> }
> 
> void startTimer() {
>   timer = timerBegin(0, 80, true); // timer_id = 0; divider=80; countUp = true;
>   timerAttachInterrupt(timer, &onTimer, true); // edge = true
>   timerAlarmWrite(timer, 1000000, true);  //1000 ms
>   timerAlarmEnable(timer);
> }
> 
> void endTimer() {
>   timerEnd(timer);
>   timer = NULL; 
> }
> 
> void setup() {
>   Serial.begin(115200);
>   startTimer();
> }
> 
> void loop() {}
> ```
so if i end the timer,how can i restart it?

**Comment by XingyumLee** [comment]
> How to restart timer ? I test by
> 
> ```
> hw_timer_t * timer = NULL;
> 
> void onTimer(){
>     Serial.print("timer ");
>     Serial.println(millis());
> }
> 
> // start/stop the timer
> void toggleTimer(){
>     if(timer){
>         timerEnd(timer);
>         timer = NULL;
>     } else {
>         timer = timerBegin(3, 80, 1);//div 80
>         timerAttachInterrupt(timer, &onTimer, 1);
>         timerAlarmWrite(timer, 100000, true);//1000ms
>         timerAlarmEnable(timer);
>     }
> }
> 
> void setup() {
>   Serial.begin(115200);
> }
> 
> void loop() {
>   toggleTimer();
>   delay(1000);
> }
> ```
> 
> timer not new start.

is seems that it just relay for 1 seconds but dont know whether the timer is stopped or not
