### ISSUE TITLE
POST method on an ESP32

### ISSUE THREAD

**Issue by Medyrih** [espressif/arduino-esp32#2142]
Hello Mates,

I have an issue with my ESP32(server) communication to a browser(client). 
I'm trying to use the Post method with the http, but i dont know how to manage it. I can run a GET interface, but i need to send a picture (bmp) from my webinterface (browser as client) to my ESP32 (as server) and i want to use the post method.

So my question is, how can I send data via post to my ESP32 and how can i read the data on the ESP correctly. The ESP provides the HTML page.

Greetings Medyrih

**Comment by lbernstone** [comment]
The [WebUpdate example](https://github.com/espressif/arduino-esp32/blob/master/libraries/WebServer/examples/WebUpdate/WebUpdate.ino) shows how to receive a POSTed file.

**Comment by Medyrih** [comment]
Thank you for your answer. I cant see where the file is saved (variable). Do you have any idea how I can save data from a form into a array?
I dont understand the Post method here :/

**Comment by lbernstone** [comment]
Please look through the examples.  This forum is for issues with the code, not tutorials. https://github.com/espressif/arduino-esp32/blob/master/libraries/WebServer/examples/SDWebServer/SDWebServer.ino#L110
