### ISSUE TITLE
'btStart' was not declared in this scope

### ISSUE THREAD

**Issue by tatsutaigu** [espressif/arduino-esp32#2149]
Hi,

I checkout ESP-IDF master and arduino core for ESP32 yesterday.
I found BLEDevice.o build error.

I asked BLE arduino forum, he said arduino lib may be changed.
would you please check it?
[https://github.com/nkolban/esp32-snippets/issues/742#issuecomment-443928278](url)

**Comment by chegewara** [comment]
What I meant is that requires changes in BLE library code, in particular BLEDevice.cpp.
