### ISSUE TITLE
WiFiClientSecure.connected() always returns true

### ISSUE THREAD

**Issue by rdowning-triax** [espressif/arduino-esp32#2152]
### Hardware:
Board:							ESP32 Gateway
Core Installation/update date:			latest development
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                          ?no?
Upload Speed:						115200
Computer OS:                                            Windows 10

### Description:
When trying to stream a request to serial using WiFiClientSecure, I want to read all the bytes until there are none available and the host has disconnected (which it does in HTTP/1.0). However, .connected() always returns true and I am stuck in this loop forever. This works as expected with the regular WiFiClient

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp
#include <ssl_client.h>
#include <WiFiClientSecure.h>
#include <WiFi.h>

#define USE_SECURE

#ifdef USE_SECURE
#define PORT 443
#else
#define PORT 80
#endif

void testClient(const char * host, uint16_t port)
{
  Serial.print("\nconnecting to ");
  Serial.println(host);

#ifdef USE_SECURE
  WiFiClientSecure client;
#else
  WiFiClient client;
#endif
  if (!client.connect(host, port)) {
    Serial.println("connection failed");
    return;
  }
  client.setTimeout(1000);
  client.print("GET / HTTP/1.0\r\n\r\n");
  while (client.connected() || client.available()) {
    if (client.available()) {
      Serial.write(client.read());
    } 
//    else {
//      Serial.println("F");
//    }
  }
  //never gets here with WiFiClientSecure, even though we are reading all data out of the client in a while loop... instead, prints "F" forever
  Serial.println("\n\nclosing connection\n");
  client.stop();
}

void setup()
{
  Serial.begin(115200);
  WiFi.begin(NETWORK, PASSWORD);
  Serial.print("connecting to wifi");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

}


void loop()
{
  testClient("google.com", PORT);

  delay(10000);
}
```

**Comment by nae9** [comment]
client.stop() not work now as early - saddle bug. But i dont know when community repair it...
