### ISSUE TITLE
Wrover varient missing?

### ISSUE THREAD

**Issue by Ajb2k3** [espressif/arduino-esp32#2167]
Can find the Wroover varient in the varients folder?

**Comment by lbernstone** [comment]
Near the top of the list. "ESP32 Wrover Module"

**Comment by Ajb2k3** [comment]
Yes it’s defined but there is no folder with a pins.h file

**Comment by atanisoft** [comment]
it inherits the base esp32 headers

**Comment by Ajb2k3** [comment]
Ahhh, was having an issue tracing the inheratance path.
