### ISSUE TITLE
Why HTTPClient.h is generating error -11 (timeout) when ESP32's http POST?

### ISSUE THREAD

**Issue by pcbtborges** [espressif/arduino-esp32#2169]
Hi, I have an ESP32 app that accesses a MySQL database via a php script.
I noticed that INSERT was returning error but the data was being recorded successfully.
I finally traced the error message to be generated by HTTPClient.h 

The error, -11, generated by httpclient.h (https://github.com/espressif/arduino-es ... TPClient.h) reffers to timeout so I increased the timeout to http.setTimeout(10000); but it did nothing to solve the problem.
UPDATE, SELECT and DELETE work perfectly.
For some reason when it is an SQL INSERT it returns -11 but the INSERT executes successfully.

I also had a simulation from an http page posting the query and the key using http POST and it works flawlessly. 

The ESP32 c++ test code:

`
#include <HTTPClient.h>
 
const char* ssid = "MySSID";
const char* password =  "MyPass";

char* txtSQL[]={"INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)",
                "INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)",
                "INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)",
                "INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)",
                "UPDATE activity set value=333 where value=130",
                "SELECT sum(value) from activity where mac='a9c4952de6b4'",
                "DELETE from activity WHERE value=333"};
                
String SQLKEY = "19872007";
int sqlArray = 6;
 
void setup() {
 
  Serial.begin(115200);
  delay(4000); 
 
  WiFi.begin(ssid, password); 
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) { //Check for the connection
    delay(1000);
    Serial.print(".");
  }
  Serial.println("\nConnected to the WiFi network");
}
 
void loop() {
  int httpResponseCode;
  if(WiFi.status()== WL_CONNECTED){   //Check WiFi connection status
 
  for(int i=0;i<=sqlArray;i++){
  
   String _post  = "query=";
          _post += txtSQL[i];
          _post += "&key=";
          _post += SQLKEY;

   HTTPClient http;
   http.setTimeout(6000);   
   http.begin("http://www.mysite.com/ESP32web/mysql.php?" + _post); 
   http.addHeader("Content-Type", "application/x-www-form-urlencoded");
   httpResponseCode = http.POST(_post);
    
   if(httpResponseCode>0){
 
    String response = http.getString();                       //Get the response to the request
    Serial.println(_post);
    Serial.print("HttpResponse: ");  
    Serial.print(response);
    Serial.print(" * ");
    Serial.print("  httpResponseCode: ");
    Serial.println(httpResponseCode);   //Print return code

   }else{

    String response = http.getString();                       //Get the response to the request
    Serial.println(_post);
    Serial.print("HttpResponse: ");  
    Serial.print(response);
    Serial.print(" - ");
    Serial.print("  httpResponseCode: ");
    Serial.println(httpResponseCode);   //Print return code
   }
   http.end();  //Free resources
  }
 }else{
    Serial.println("Error in WiFi connection");   
 }
  delay(2000);  //Send a request every 10 seconds 
}`

I set the monitor to check what was being returned and got:

`Connecting to WiFi.
Connected to the WiFi network
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=UPDATE activity set value=333 where value=130&key=19872007
HttpResponse: 4 *   httpResponseCode: 201                -------------------->PROOF INSERT worked
query=SELECT sum(value) from activity where mac='a9c4952de6b4'&key=19872007
HttpResponse: 1332  *   httpResponseCode: 200
query=DELETE from activity WHERE value=333&key=19872007
HttpResponse: 4 *   httpResponseCode: 201
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
.....`

The PHP script doing the job is as below (mysql.php) :

`<?php
in﻿﻿clude('connection.php');

//these are just in case setting headers forcing it to always expire 
header('Cache-Control: no-cache, must-revalidate');

error_log(print_r($_POST,TRUE));

if( isset($_POST['query']) && isset($_POST['key']) ){                                   //checks if the tag post is there and if its been a proper form post
  header('C﻿ontent-type: application/x-www-form-urlencoded');
  if($_POST['key﻿']==$SQLKEY){                                                           //validates the SQL key
    $query=urldecode($_POST['query']);
    if(get_magic_quotes_gpc()){     //check if the worthless pile of crap magic quotes is enabled and if it is, strip the slashes from the query
      $query=stripslashes($query);
    }﻿
    $conn = new m﻿ysqli($DB_ADDRESS,$DB_USER,$DB_PASS,$DB_NAME);    //connect

    if($conn->connect_error){                                                           //checks connection
      header("HTTP/1.0 400 Bad Request");
      echo "ERRO﻿R Database Connection Failed: " . $conn->connect_error, E_USER_ERROR;   //reports a DB connection failure
    } else {

      $result=$conn->query($query);                                                     //runs the posted query                        

      if($result === false){
        header("﻿HTTP/1.0 400 Bad Request");                                             //sends back a bad request error
        echo "Wrong SQL: " . $query . " Error: " . $conn->error, E_USER_ERROR;    //errors if the query is bad and spits the error back to the client
      } else {﻿
        if (strlen(stristr($query,"SELECT"))>0) {                                       //tests if it's a SELECT statement
          $csv = '';                                                                                // bug fix Undefined variable: csv
          while ($fieldinfo = $result->fetch_field()) {
            $csv .= $fieldinfo->name.",";
          }
          $csv = rtrim($csv, ",")."\n";
//********************************          echo $csv;                    //prints header row
          $csv = '';﻿

          $result->data_seek(0);
          while($row = $result->fetch_assoc()){
            foreach ($row as $key => $value) {
              $csv .= $value.",";
            }﻿﻿
            $csv = rtrim($csv, ",");                                                 //."\n";
          }
          echo $csv;﻿                                                                    //prints all data rows
        } else {
          header("HTTP/1.0 201 Rows");
          echo $conn->affected_rows;       //if the query is anything but a SELECT, it will return the number of affected rows (INSERT IS ﻿ RETURNING -11)
        }﻿
      }
      $conn->close();                                          //closes the DB
    }﻿
  } else {
     header("HTTP/1.0 400 Bad Request");
     echo "-Bad Request";                                       //reports if the secret key was bad
  }
} else {
        header("HTTP/1.0 400 Bad Request");
        echo "*﻿Bad Request";
}
?>﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿`

Any help will be much appreciated.
Than﻿ks﻿

Paulo Borg﻿e﻿s

**Comment by Jeroen88** [comment]
I do not know if this causes your error, but you should URL Encode both the URL and the payload.

Since you send the full query in the URL you could also do a GET

**Comment by pcbtborges** [comment]
HI, thanks for the response.

The portion of the code that sends the request is:

`   HTTPClient http;
   http.setTimeout(5000);   
   http.begin("http://www.infotecservices.com.br/ESP32web/hydroflux.php?" + _post); 
   http.addHeader("Content-Type", "application/x-www-form-urlencoded");
   httpResponseCode = http.POST(_post);`

How would I do to encode both the URL and the payload?

The reason I am not venturing on changing the PHP script is that my Android app uses it extensively and it would mean to change it. As the ESP32 side interacts only once a day to upload sensor data it should be easier to change it.

Thanks again
Paulo

**Comment by Jeroen88** [comment]
You could try this:
```
String urlencode(const String &s) {
  static const char lookup[]= "0123456789abcdef";
  String result;
  size_t len = s.length();

  for(size_t i = 0; i < len; i++) {
    const char c = s[i];
    if(('0' <= c && c <= '9') || ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || (c=='-' || c=='_' || c=='.' || c=='~')) {
      result += c;
    } else {
      result += "%" + String(lookup[(c & 0xf0) >>4]) + String(lookup[c & 0x0f]);
    }
  }

  return result;
}
```

**Comment by pcbtborges** [comment]
Dear Jeroen88, do you mean something like this?

String myVar = urlencode("http://www.mysite.com/ESP32web/hydroflux.php?" + _post);
HTTPClient http;
http.begin(myVar);
http.addHeader("Content-Type", "application/x-www-form-urlencoded");
httpResponseCode = http.POST(_post);


Thanks
Paulo

**Comment by Jeroen88** [comment]
> Also remember that only INSERT is experiencing problems. DELETE, UPDATE and SELECT also make use of payloads and somehow are performing ok.

Maybe because they contain less special characters.

I do not write php myself, but I also think I noted that you do not send a response header when the query is SELECT

**Comment by pcbtborges** [comment]
About the response header for the SELECT, yes, I also noticed that but it is working so I did not bother checking it out. 
Thanks

**Comment by pcbtborges** [comment]
Some things to note:
INSERT does not return any of the BAD REQUESTS on the list of things that can go wrong.
On the http.begin("http://www.mysite.com/ESP32web/hydroflux.php?" + _post);
above, if I misspell the URL it still returns the exact same message as can be seem above but for the SELECT, UPDATE and DELETE the return message will be some BAD REQUEST.
Simulating the post from a bare bone post.html it works like magic not even content type specified.
I am puzzled...

I will try your suggestion as soon as I understand how to apply it properly.
Thanks again for your time.
Paulo

**Comment by Jeroen88** [comment]
Thats easy: after http.setTimeout() add:

`_post = urlencode(_post);`

That's it

**Comment by pcbtborges** [comment]
Hi, just tested.
That is the monitor before the change above:

Connecting to WiFi.
Connected to the WiFi network
query=INSERT INTO activity (mac,jd,date,time,area,type,value)VALUES('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=INSERT INTO activity (mac,jd,date,time,area,type,value) VALUES ('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=INSERT INTO meters(mac,custnumber,area,label) VALUES ('a9c4952de6b4',4,'Area0001','Apt-101')&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=UPDATE activity set value=333 where value=130&key=19872007
HttpResponse: 4 *   httpResponseCode: 201
query=SELECT sum(value) from activity where mac='a9c4952de6b4'&key=19872007
HttpResponse: 1332
 *   httpResponseCode: 200
query=DELETE from activity WHERE value=333&key=19872007
HttpResponse: 4 *   httpResponseCode: 201
query=INSERT INTO activity (mac,jd,date,time,area,type,value)VALUES('a9c4952de6b4',2458454,'2018-12-01','10:22','Area0002','h',130)&key=19872007
HttpResponse:  -   httpResponseCode: -11


AFTER the change:

Connecting to WiFi.
Connected to the WiFi network
query%3dINSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29VALUES%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29%26key%3d19872007
HttpResponse: *Bad Request *   httpResponseCode: 400
query%3dINSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29%20VALUES%20%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29%26key%3d19872007
HttpResponse: *Bad Request *   httpResponseCode: 400
query%3dINSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29%20VALUES%20%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29%26key%3d19872007
HttpResponse: *Bad Request *   httpResponseCode: 400
query%3dINSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29%20VALUES%20%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29%26key%3d19872007
HttpResponse: *Bad Request *   httpResponseCode: 400
query%3dINSERT%20INTO%20meters%28mac%2ccustnumber%2carea%2clabel%29%20VALUES%20%28%27a9c4952de6b4%27%2c4%2c%27Area0001%27%2c%27Apt-101%27%29%26key%3d19872007
HttpResponse: *Bad Request *   httpResponseCode: 400
query%3dUPDATE%20activity%20set%20value%3d333%20where%20value%3d130%26key%3d19872007
HttpResponse:  -   httpResponseCode: -11
query%3dSELECT%20sum%28value%29%20from%20activity%20where%20mac%3d%27a9c4952de6b4%27%26key%3d19872007
HttpResponse: *Bad Request *   httpResponseCode: 400
query%3dDELETE%20from%20activity%20WHERE%20value%3d333%26key%3d19872007
HttpResponse: *Bad Request *   httpResponseCode: 400
query%3dINSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29VALUES%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29%26key%3d19872007
HttpResponse: *Bad Request *   httpResponseCode: 400

Thanks
Paulo

**Comment by Jeroen88** [comment]
That was too quick a fix. Remove the line I suggested and replace

```
String _post = "query=";
_post += txtSQL[i];
_post += "&key=";
_post += SQLKEY;

```
With

```
String _post = "query=";
_post += urlencode(txtSQL[i]);
_post += "&key=";
_post += urlencode(SQLKEY);
```

In the logging above though you can see that now you get a timeout only once. That suggest that your php code is causing the trouble.

I don use php myself, but might it be possible that you miss some kind of end the response to the client?

You can also measure the time between on the ESP just before the POST and just after the POST, and on your server at the entry of the script and at the exit. Your database access might cost to much time.

At least I am quite convinced that your issue _is not a HTTPClient library issue_.

**Comment by pcbtborges** [comment]
Hi, thanks again for your time.
I will implement the changes and test again.

I am not the original developer of this php script and not a proficient php developer, I downloaded this script for use with an Android app and it is performing ok so far.
Currently I am using the ESP32 to collect sensor data and use GET to send this data to the server.
As the sensor side have config functions I have an specific php script, very simple, for each function. I have for instance an insert.php, a delete.php, an update.php and so on so I decided to unify everything by posting the sql string to a single php script and naturally chose the one already in use by the Android side.

But understanding the problem is not with the library is important at this point, I understand more php than libraries.

Thanks again for your time.
I will test the code above and report back.
Regards
Paulo

**Comment by pcbtborges** [comment]
Dear Jeroen88, it worked like magic!

I cannot thank you enough for taking the time to analytically look into so much text and with the necessary knowledge to suggest a solution to this problem.

Thanks very much for your time
Paulo Borges

**Comment by Jeroen88** [comment]
That's nice! You're welcome!

**Comment by pcbtborges** [comment]
As promissed:

Connecting to WiFi.
Connected to the WiFi network
query=INSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29VALUES%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29&key=19872007
HttpResponse: 1 *   httpResponseCode: 201
query=INSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29%20VALUES%20%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29&key=19872007
HttpResponse: 1 *   httpResponseCode: 201
query=INSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29%20VALUES%20%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29&key=19872007
HttpResponse: 1 *   httpResponseCode: 201
query=INSERT%20INTO%20activity%20%28mac%2cjd%2cdate%2ctime%2carea%2ctype%2cvalue%29%20VALUES%20%28%27a9c4952de6b4%27%2c2458454%2c%272018-12-01%27%2c%2710%3a22%27%2c%27Area0002%27%2c%27h%27%2c130%29&key=19872007
HttpResponse: 1 *   httpResponseCode: 201
query=INSERT%20INTO%20meters%28mac%2ccustnumber%2carea%2clabel%29%20VALUES%20%28%27a9c4952de6b4%27%2c4%2c%27Area0001%27%2c%27Apt-101%27%29&key=19872007
HttpResponse: 1 *   httpResponseCode: 201
query=UPDATE%20activity%20set%20value%3d333%20where%20value%3d130&key=19872007
HttpResponse:  -   httpResponseCode: -11
query=SELECT%20sum%28value%29%20from%20activity%20where%20mac%3d%27a9c4952de6b4%27&key=19872007
HttpResponse: 1332
 *   httpResponseCode: 200
query=DELETE%20from%20activity%20WHERE%20value%3d333&key=19872007
HttpResponse: 4 *   httpResponseCode: 201

**Comment by pcbtborges** [comment]
Jeroen88, I am embarrassed to bother you again but I was so focused on the INSERT that did not notice that now the problem moved to the UPDATE.

Please take a look at the post above.

I checked the encoded characters and it seems to be OK.
Why is this happening?

Thanks
Paulo

**Comment by Jeroen88** [comment]
I really don't know, except from that you might really get a timeout on the UPDATE. You could test in your PHP script at what time the request is received (at the beginning of the function) and at what time the query is completed (just after $result=$conn->query($query); ). This gives you an impression of the duration. This should be (well) below the timeout at the client, that you set at 6000 ms.

Your database may expect uppercase, although SQL mostly is case insensitive. Try SET and WHERE instead of set and where.

I can't think of anything else...

**Comment by pcbtborges** [comment]
Jeroen88, I think you gave me enough background so I can try and find what is causing this problem.
I will keep the research as now I can switch the problem on and off.
Thanks again for your effort.
Paulo

**Comment by Jeroen88** [comment]
You're welcome, good luck in finding the issue!

**Comment by desiFish** [comment]
URL Encoding fixed my issue too! I was getting randomly HTTPResponseCode Error -11
I implemented urlencoding and it fixed the issue. I stumbled upon this issue accidentally, thanks!

I used this:
`String urlEncode(const String &str)
{
  String encodedString = "";
  char c;
  char code0;
  char code1;
  for (int i = 0; i < str.length(); i++)
  {
    c = str.charAt(i);
    if (c == ' ')
    {
      encodedString += '+';
    }
    else if (isalnum(c))
    {
      encodedString += c;
    }
    else
    {
      code1 = (c & 0xf) + '0';
      if ((c & 0xf) > 9)
        code1 = (c & 0xf) - 10 + 'A';
      c = (c >> 4) & 0xf;
      code0 = c + '0';
      if (c > 9)
        code0 = c - 10 + 'A';
      encodedString += '%';
      encodedString += code0;
      encodedString += code1;
    }
  }
  return encodedString;
}`
