### ISSUE TITLE
ADC Sample rate

### ISSUE THREAD

**Issue by williamhemmingsen** [espressif/arduino-esp32#217]
Anyone know the MAX ADC sample rate?  I'm attempting to sample the ADC at 9600 sps,   I'm using the analogread(); function.  Is there a faster way?  Or is the ADC just too slow for this sample rate?

Thanks!

**Comment by me-no-dev** [comment]
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-adc.h

**Comment by freemind64** [comment]
hi
how can I set the sample rate to 4kS/s ?
I need to measure vibration and I want to have sample rate about 4kS/s?

thanks.
