### ISSUE TITLE
Arduino as IDF Component make problem

### ISSUE THREAD

**Issue by Goldenstarc** [espressif/arduino-esp32#2170]
I'm using this as template project for idf:
**https://github.com/espressif/esp-idf-template**
if I change main.c to main.cpp and put my sketch into it I`ll get this error : 

make[1]: *** No rule to make target `somelocation/ESP-IDF/IDF-Arduino/main/main.c', needed by `main.o'.  Stop.
make: *** [component-main-build] Error 2

but if I change main.c  to ANYTHING.cpp . compiler can make bin
what's the solution ?!

**Comment by igrr** [comment]
I think the build system does not handle the case of such rename, since both main.c and main.cpp would compile to the same object file, main.o.

If you clear the build directory (`rm -rf build`) and build again, then it should work with `main.cpp` as well.
