### ISSUE TITLE
eeprom can't work

### ISSUE THREAD

**Issue by nitroge** [espressif/arduino-esp32#2174]
#include <MyConfig.h>
#include <M5Stack.h>
MyConfig myConfig;
MyConfig::WifiInfo info;
void setup()
{

  Serial.begin(9600);
  Serial.println();
  Serial.println("start");
  myConfig.saveWifiInfo(info);
  delay(100);
  MyConfig::WifiInfo temp = myConfig.readWifiInfo();
  delay(100);
  Serial.println(temp.ssid.c_str());
  Serial.println(temp.pwd.c_str());
  Serial.println("done");

}

void loop()
{
  // put your main code here, to run repeatedly:
}

#ifndef MY_CHONFIG_H
#define MY_CHONFIG_H
#include <WString.h>
class MyConfig
{
  public:
    struct WifiInfo
    {
        String ssid;
        String pwd;
    };
    void saveWifiInfo(WifiInfo info);
    WifiInfo readWifiInfo();
};

#endif

#include <MyConfig.h>
#include "EEPROM.h"

EEPROMClass INFO("eeprom0", 0x1000);

void MyConfig::saveWifiInfo(MyConfig::WifiInfo info)
{
    INFO.put(0, info);
    INFO.commit();
}

MyConfig::WifiInfo MyConfig::readWifiInfo()
{
    MyConfig::WifiInfo temp;
    temp = INFO.get(0, temp);
    return temp;
}

output:
start

0

done

**Comment by lbernstone** [comment]
Not sure if it is an issue with the structure you are using?  This works for me:
```
#include <EEPROM.h>

EEPROMClass INFO("eeprom0", 0x1000);

void setup() {
  Serial.begin(115200);
  INFO.put(0,(char*)"test");
    
}

void loop() {
  char* t=INFO.get(0,t);
  Serial.println(t);
  delay(1000);
}
```

**Comment by nitroge** [comment]
Thank you for your answer.
Please try this.
step 1 upload this 
#include <EEPROM.h>

EEPROMClass INFO("eeprom0", 0x1000);

void setup() {
  Serial.begin(115200);
  INFO.put(0,(char*)"test");
    
}

void loop() {
  char* t=INFO.get(0,t);
  Serial.println(t);
  delay(1000);
}

This output is correct.

step 2 upload this


#include <EEPROM.h>

EEPROMClass INFO("eeprom0", 0x1000);

void setup() {
  Serial.begin(115200);
 // INFO.put(0,(char*)"test");
    
}

void loop() {
  char* t=INFO.get(0,t);
  Serial.println(t);
  delay(1000);
}

no output

This output is error.

**Comment by SocketNet** [comment]
I had the same problem. 😂

**Comment by lbernstone** [comment]
Ok, I looked through the code to  refresh my memory of how this works.
You need to have a .begin() for the EEPROM instance.  Initializing creates the data structures, but does not attach them to the physical partition.  begin does so, and will return false if it is unable to open the partition you have named.

**Comment by nitroge** [comment]
> I had the same problem. 😂

EEPROM.begin(EEPROM.length())  改为固定大小似乎可以, 比如  EEPROM.begin(2048)；
