### ISSUE TITLE
Problem with high speed PWM (1 Mhz)

### ISSUE THREAD

**Issue by williamesp2015** [espressif/arduino-esp32#2195]
Unfortunately the actual frequency with this setting is 23.8 Khz not 1024 Khz
void PulseGenerator()
{
/////////PWM 50% duty 1.024 MHz
double freq=ledcSetup(0, 1024000,3);
Serial.print("FREQUENCY: ");
Serial.println(freq);
ledcAttachPin(PIN_Pulse, 0);//channel 0
ledcWrite(0, 4);//50% DUTY CYCLE
}
![image](https://user-images.githubusercontent.com/12815126/50046688-9f6bbb00-00bc-11e9-9be1-a65032ba59f2.png)

**Comment by lbernstone** [comment]
I don't have a scope handy.  Can you try the [IDF functions](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/ledc.html) and see if they give the same result?
```
#include "driver/ledc.h"

#define LEDC_0_PIN 22

void setup() {
  Serial.begin(115200);
  
  ledc_timer_config_t ledc_timer;
  ledc_timer.speed_mode = LEDC_HIGH_SPEED_MODE;           // timer mode
  ledc_timer.duty_resolution = LEDC_TIMER_3_BIT; // resolution of PWM duty
  ledc_timer.timer_num = LEDC_TIMER_0;            // timer index
  ledc_timer.freq_hz = 1024000;                      // frequency of PWM signal
  // Set configuration of timer0 for high speed channels
  esp_err_t result = ledc_timer_config(&ledc_timer);
  if (result == ESP_OK)
     Serial.printf("frequency: %d", ledc_get_freq(LEDC_HIGH_SPEED_MODE, LEDC_TIMER_0));
  ledc_channel_config_t ledc_channel = {
          .gpio_num   = LEDC_0_PIN,
          .speed_mode = LEDC_HIGH_SPEED_MODE,
          .channel    = LEDC_CHANNEL_0,
          .intr_type  = LEDC_INTR_DISABLE,
          .timer_sel  = LEDC_TIMER_0,
          .duty       = 4,
          .hpoint     = 0
  };
  // Set LED Controller with previously prepared configuration
  ledc_channel_config(&ledc_channel);
}

void loop() {vTaskDelete(NULL);}
```

**Comment by wgaylord** [comment]
I seem to be having this problem. I can't get it to go past 78 Khz unless I use that code snippet. No idea why. Also I have a problem where even with that snippet it will be off freq by almost 2Khz some times. When trying to use a freq of 14 Mhz. (Way lower then the documented max of 40 Mhz)

**Comment by wgaylord** [comment]
Hello has the problem been solved yet. As I mentioned above this is still not working,
