### ISSUE TITLE
gen_esp32part.exe generates .elf file with corrupted name, character lost 

### ISSUE THREAD

**Issue by Bascy** [espressif/arduino-esp32#2196]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:		26/nov/2018
IDE name:						Eclipse Sloeber plugin
Computer OS:                                          Windows 10

### Description:
When building my project with commit 04963009eedfbc1e0ea2e1378ae69e7cebda6fd6 (Update IDF to a0468b2 (#2108)) the resulting .elf file of my project, generated by gen_esp32part.exe, has a strange name: `csMaiMaster.elf` in stead of `csMainMaster.elf`

The last step of the toolchain, esptools.exe fails because of this, as it cannot find the .elf file..
If I build with any earlier commit everything works fine and the filename is correct.

```
"D:\sloeber4.3\/arduinoPlugin/packages/arduino-esp32/tools/gen_esp32part.exe" -q "D:\sloeber4.3\/arduinoPlugin/packages/arduino-esp32/tools/partitions/min_spiffs.csv" "D:\C-Sense2.0\source\csMainMaster/Debug/csMainMaster.partitions.bin"
"D:\sloeber4.3\/arduinoPlugin/packages/arduino-esp32/tools/esptool/esptool.exe" --chip esp32 elf2image --flash_mode "dio" --flash_freq "80m" --flash_size "4MB" -o "D:\C-Sense2.0\source\csMainMaster/Debug/csMainMaster.bin" "D:\C-Sense2.0\source\csMainMaster/Debug/csMainMaster.elf"
esptool.py v2.5.0
makefile:107: recipe for target 'csMainMaster.hex' failed
Traceback (most recent call last):
  File "esptool.py", line 2849, in <module>
  File "esptool.py", line 2842, in _main
  File "esptool.py", line 2615, in main
  File "esptool.py", line 2159, in elf2image
  File "esptool.py", line 1709, in __init__
IOError: [Errno 2] No such file or directory: 'D:\\C-Sense2.0\\source\\csMainMaster/Debug/csMainMaster.elf'
Failed to execute script esptool
make: *** [csMainMaster.hex] Error -1

```

**Comment by atanisoft** [comment]
gen_esp32part.exe doesn't generate the elf file, it would appear your makefile instead is not generating it correctly. I would also suggest open this up against Eclipse Sloeber instead of arduino-esp32.
