### ISSUE TITLE
eTaskGetState() Always returns 1 (ready) even when task is active

### ISSUE THREAD

**Issue by euquiq** [espressif/arduino-esp32#2203]
Weird thing:
I declare a task handle:

`TaskHandle_t h_gsm_loop;`

Then on my loop() I start a task:

`xTaskCreate(gsm_taskloop, "gsm_taskloop", 2000, NULL, 0, &h_gsm_loop);`

The task itself outputs it's ongoing work over Serial Port, and I can see it is working.

But on the loop() each 500ms I query the task status with:

`Serial.println("L" + (String)eTaskGetState(&h_gsm_loop));`

And I still get 1 as result (task ready) instead of task running ...

Furthermore, I add the same printout inside the task itself, and from the actual task, running, I also get a 1 (task ready) value in return, instead of 0 (task running).

I think eTaskGetState() is just a dummy function ? Or most probably, I must be doing something lamely wrong.

Regards,

Enrique

**EDIT**

AS @chegewara  points out on a replay below, on IDF,

https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/freertos.html?#_CPPv213eTaskGetState12TaskHandle_t

You should pass handle by value not by reference to function.

**BUT**

If I take the "&" in front of the handle and try:

`Serial.println("L" + (String)eTaskGetState(h_gsm_loop));`

Then I get this error when reaching that line code:

```
/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/tasks.c:1510 (eTaskGetState)- assert failed!
abort() was called at PC 0x4008dcd9 on core 1

Backtrace: 0x40090068:0x3ffb1ee0 0x4009023d:0x3ffb1f00 0x4008dcd9:0x3ffb1f20 0x400d6595:0x3ffb1f40 0x40150d38:0x3ffb1fb0 0x4008c011:0x3ffb1fd0

Rebooting...

```

Hence this may be an actual bug ...

**Comment by chegewara** [comment]
Just put this line in your `gsm_taskloop`:
`Serial.println("L" + (String)eTaskGetState(&h_gsm_loop));`

**Comment by euquiq** [comment]
@chegewara yes, as I state at my first post, such line IS there, and returns 1 (task READY) instead of 0, task Running ... which is the weird part

**Comment by chegewara** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/freertos.html?#_CPPv213eTaskGetState12TaskHandle_t

You should pass handle not handle reference to function.

**Comment by euquiq** [comment]
@chegewara Yes I already seen that, for IDF. If I take out the "&" ... the code crashes with "GURU MEDITATION" when reaching the eTaskGetState(h_gsm_loop) ... So I would think it is different in Arduino, (or wrongly implemented, and thus, a bug, hence this issue may be a true one)

**Comment by me-no-dev** [comment]
I think that you should post this in IDF's issue tracker :) better chance to get a proper response/fix for this.

**Comment by alexvazquez** [comment]
@euquiq Hi, having same issue. Did you find out?

**Comment by playmiel** [comment]
I think this problem will never be fixed

**Comment by chegewara** [comment]
Im pretty sure it is working good. Here is quick test output:
```
06:44:35.166 > Task1 0
06:44:35.270 > Task2 0
06:44:36.167 > Task1 0
```
- `Task1` is some task running on core 0
- `Task2` is inside `loop()`

Like i said long time ago, you have to pass properly task handle, by value, not by reference.
This is decalaration:
```
eTaskState eTaskGetState( TaskHandle_t xTask ) PRIVILEGED_FUNCTION;
```
and this is code:
```
Serial.println("Task2 " + (String)eTaskGetState(&h_gsm_loop)); <------------ WRONG
Serial.println("Task2 " + (String)eTaskGetState(h_gsm_loop));  <------------ GOOD
```

**Comment by playmiel** [comment]
thanks I thought it was a bug now it works
