### ISSUE TITLE
Sensor VEML770  not work with last 1.0.1 rc2

### ISSUE THREAD

**Issue by asetyde** [espressif/arduino-esp32#2207]
After some correction and disabling ALS algorithm , with 1.0.1 rc1 all working, today I test rc2 sensor return only 0 and 1511.5199 value .. something wrong ... @stickbreaker  something change from rc1 to rc2 ?

**Comment by stickbreaker** [comment]
yes, we decided to remove the I2C_ERROR_CONTINUE.

change any code that looks for `err!=7` back to `err != 0`

```c++
// 1.0.1Rc2
uint8_t err = Wire.endTransmission(false);
if(err != 0 ) { // problem
   return err;
} else { // everything good
  Wire.requestFrom(id,len);
  while ( Wire.available()){
     Wire.read();
  }
}
```

Chuck.

**Comment by asetyde** [comment]
I use your variant https://github.com/stickbreaker/arduino-VEML7700

**Comment by asetyde** [comment]
<img width="609" alt="schermata 2018-12-18 alle 12 52 31" src="https://user-images.githubusercontent.com/6162152/50152408-ca742b80-02c3-11e9-94b6-36e25b4949ac.png">
Also seems it's not correct loaded from compiler, esp32 part of code is obfuscated as unused

**Comment by asetyde** [comment]
Also I'm not sure that change influence a result , at now library result only 151.519...

**Comment by asetyde** [comment]
at now value is unusable, I came back to rc1

**Comment by stickbreaker** [comment]
cut out that #ifdef ,  The `Wire()` coding has changed, there is no longer any difference between ESP32 coding and AVR Arduino coding.

Just change it to:
```
if(Wire.endTransmission(false)){ // NB: don't send stop here
    return STATUS_ERROR;
}
```

Chuck.

**Comment by asetyde** [comment]
Ok as I've done . Thanks Chuck , your re best
