### ISSUE TITLE
ESP32 HAL Documentation

### ISSUE THREAD

**Issue by fabiuz7** [espressif/arduino-esp32#2209]
Hi all,
I've just read some issues like #1363 and #1148, but still i'm wondering why there isn't documentation for the esp32 HAL layer. I know that idf layer is well documented, as well as Arduino Classes, Functions and methods (well documented on Arduino.cc). However, for some peripherals like *[timer](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-timer.h)*, there isn't any Arduino specification about methods and functions, hence an end-user should access directly to esp32 HAL layer or directly to IDF.

Hence the question is: should I decided for HAL (higher abstration level, not well documented) or IDF (well documented, faster)?

**Comment by me-no-dev** [comment]
It's up to you what you want to use. Arduino's HAL is made to allow for easy implementation of it's API and classes, so it more or less follows minimalistic design. You can just as well not at all use Arduino's HAL and instead use IDF's. Really up to you. Though I do agree that documentation is necessary, currently there are not many people putting hours into the project, so it's not easy :)
You could also look into the examples? There you will see baicaly all HAL being used.
