### ISSUE TITLE
Is there a way to configure the way ESP32 behaves after panic ?

### ISSUE THREAD

**Issue by euquiq** [espressif/arduino-esp32#2216]
My code is crashing under certain stress ... the error is not much helpful, there is no tracking data for debugging, etc. and execution is HALTING.

I would rather like the processor to REBOOT by itself after a "GURU MEDITATION".

I just seen the `CONFIG_ESP32_PANIC`  configuration at make time under IDF.

Is there any way Arduino can cope with this issue / configuration ?

That is -sorry if my question is lame- I would like to know if there is any way I can change or set the `CONFIG_ESP32_PANIC` behavior through Arduino code.

**Comment by lbernstone** [comment]
The behavior configured in [arduino-esp32](https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/sdkconfig#L305) is set for CONFIG_ESP32_PANIC_PRINT_REBOOT, so it should attempt to reboot.  Perhaps you have strapping pins held high, or something else is preventing the reboot (overheating or power?).

**Comment by euquiq** [comment]
@lbernstone Hi! ... nope. No power or heat problems ... I got problems between RFM69X library and SPI usage, I get the Guru Meditation "treatment" and the ESP32 just halts after that. Or just repeats an error 20 or 40 times and then halts. Like this:

https://github.com/espressif/arduino-esp32/issues/2027

**Comment by me-no-dev** [comment]
which pins do you use for the RFM? Anything else connected to the board?

**Comment by euquiq** [comment]
@me-no-dev for RFM, I use:

```
//			MISO			gpio19
//			MOSI			gpio23
//			NSS				gpio05
//			CLK				gpio18
//			DIO				gpio04
```

I also use hardwareSerial 2 (gpio16 and gpio17) with a SIM900L gsm modem...

I also use GPIO14 and GPIO15 to actuate two relays

I also use an AM receiver, thru gpio12 to read data, and gpio33 to read signal Strength... There is an interrupt that runs my data receiving code in IRAM_ATTR, whenever gpio12 changes.

`	attachInterrupt(digitalPinToInterrupt(pin_radiodata), hcs301_interrupt, CHANGE);				//Interrupt that reads such data`

I use gpio36 to read digital data signaled from my PSU / UPS (HIGH using AC, LOW using DC).

And last but not least, I use GPIO27 for reading a vibration sensor (digital input)

**Comment by lbernstone** [comment]
https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card#note-about-gpio12

**Comment by euquiq** [comment]
@lbernstone Interesting, thanks for that info: I was not aware of this gpio12 idiosyncracy. 

I am using gpio12 as an Input, to read the data being output from the radio AM receiver. Which is always sending "random" bytes to me (due to radio noise) until a transmitter starts sending data, remotely.

I would supose things are OK on my configuration with this fact, since my project works fine (for days on a row). 

Right now I think I circumvented the problem which generated the Guru Meditations (I am time testing it!) by putting the RFM69 radio transceiver to SLEEP, before using SPIFFS subsystem, so the SPI is used only for that.

My issue is: I would like very much the ESP32 to reboot / reset itself, whenever a GURU MEDITATION happens, and not just stop (and making someone to press the reset button).

Regards,

Enrique

**Comment by lbernstone** [comment]
It absolutely should reboot after a panic.  The strapping pins can interfere with this, especially gpio 0, 2 and 12.  Those pins have specific functions at boot, so if they are in an invalid state, it can prevent booting (or restarting).  I am sure you have seen the normal behavior where the system does reboot in other configurations.  I pointed you at that location because it is good general info, not necessarily related to SD cards.  It explains how you can turn the strapping behavior of gpio12 permanently off.
