### ISSUE TITLE
HTTPS Not working on ESP32 with BLE

### ISSUE THREAD

**Issue by wezleysherman** [espressif/arduino-esp32#2219]
Hello, how do I properly do an HTTP GET request on an https link?

I'm utilizing the `HTTPClient.h` library
I've tried the following with no avail -- (I keep getting a response of -1)
`
http.begin("https url", "SHA1 fingerprint");`
and
`http.begin("https url", "raw rsa certificate");`

I've even tried utilizing the tutorial here (following it exactly) with the same issue:
https://techtutorialsx.com/2017/11/18/esp32-arduino-https-get-request/

I know the tutorial is old -.. has something in the library changed? I've even tried having it connect to Google. Performing GET requests on regular http links work fine. 

With Google:

```
const char* HTTPS_CERT = "-----BEGIN CERTIFICATE-----\n" \
"MIIDujCCAqKgAwIBAgILBAAAAAABD4Ym5g0wDQYJKoZIhvcNAQEFBQAwTDEgMB4G\n" \
"A1UECxMXR2xvYmFsU2lnbiBSb290IENBIC0gUjIxEzARBgNVBAoTCkdsb2JhbFNp\n" \
"Z24xEzARBgNVBAMTCkdsb2JhbFNpZ24wHhcNMDYxMjE1MDgwMDAwWhcNMjExMjE1\n" \
"MDgwMDAwWjBMMSAwHgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMjETMBEG\n" \
"A1UEChMKR2xvYmFsU2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjCCASIwDQYJKoZI\n" \
"hvcNAQEBBQADggEPADCCAQoCggEBAKbPJA6+Lm8omUVCxKs+IVSbC9N/hHD6ErPL\n" \
"v4dfxn+G07IwXNb9rfF73OX4YJYJkhD10FPe+3t+c4isUoh7SqbKSaZeqKeMWhG8\n" \
"eoLrvozps6yWJQeXSpkqBy+0Hne/ig+1AnwblrjFuTosvNYSuetZfeLQBoZfXklq\n" \
"tTleiDTsvHgMCJiEbKjNS7SgfQx5TfC4LcshytVsW33hoCmEofnTlEnLJGKRILzd\n" \
"C9XZzPnqJworc5HGnRusyMvo4KD0L5CLTfuwNhv2GXqF4G3yYROIXJ/gkwpRl4pa\n" \
"zq+r1feqCapgvdzZX99yqWATXgAByUr6P6TqBwMhAo6CygPCm48CAwEAAaOBnDCB\n" \
"mTAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUm+IH\n" \
"V2ccHsBqBt5ZtJot39wZhi4wNgYDVR0fBC8wLTAroCmgJ4YlaHR0cDovL2NybC5n\n" \
"bG9iYWxzaWduLm5ldC9yb290LXIyLmNybDAfBgNVHSMEGDAWgBSb4gdXZxwewGoG\n" \
"3lm0mi3f3BmGLjANBgkqhkiG9w0BAQUFAAOCAQEAmYFThxxol4aR7OBKuEQLq4Gs\n" \
"J0/WwbgcQ3izDJr86iw8bmEbTUsp9Z8FHSbBuOmDAGJFtqkIk7mpM0sYmsL4h4hO\n" \
"291xNBrBVNpGP+DTKqttVCL1OmLNIG+6KYnX3ZHu01yiPqFbQfXf5WRDLenVOavS\n" \
"ot+3i9DAgBkcRcAtjOj4LaR0VknFBbVPFd5uRHg5h6h+u/N5GJG79G+dwfCMNYxd\n" \
"AfvDbbnvRG15RjF+Cv6pgsH/76tuIMRQyV+dTZsXjAzlAcmgQWpzU/qlULRuJQ/7\n" \
"TBj0/VLZjmmx6BEP3ojY+x1J96relc8geMJgEtslQIxq/H5COEBkEveegeGTLg==\n" \
"-----END CERTIFICATE-----\n";

http.begin("https://www.google.com", HTTPS_CERT);
```

UPDATE:

My code is utilizing BLE as well -.. When I disable BLE then HTTPS works perfectly. 

Is there a way to reinitialize BLE after disabling/free'ing its memory?

**Comment by copercini** [comment]
This is probably a non enough heap problem...
You can get a board with PSram, and this will be magically solved or try optimize BLE and mbedtls to save resources and work together (requires moving to Arduino as IDF component)

**Comment by wezleysherman** [comment]
Is there a quick and dirty fix for this? Can I adjust the heap size within the partition table?

What I’m doing right now is, I’m enabling BLE and polling for a few seconds, then I disable BLE and free the memory. After that I’m making my https request without any issues. The problem is enabling BLE again after I’ve made the HTTPS request — everything works fine up to where I’m creating the BLE Service (it hangs up here). Is there a way I can free the memory used by TLS after the https request is returned? 

I’ve just been resetting the ESP32 module via software afterwards to restore BLE.

**Comment by chegewara** [comment]
@wezleysherman In case you described there may be problem with free heap (ram) or with ble library. What you can do is to check free internal memory just before your app stuck/crash.

**Comment by czuvich** [comment]
@wezleysherman I run into the same issues on the WROVER module with PSRAM (4MB) when invoking HTTPS.  I think it's an issue with the internal mbed or wifi libraries.  I think BLE is actually fairly well-behaved (but RAM intense).  I really don't think extra heap will fix your problem.  Someone needs to dive in and diagnose the issue.

**Comment by czuvich** [comment]
@wezleysherman Also, in regards to a dirty fix... if you can get away with resetting your board between BLE and WiFi, that should work.  In other words, when it's time to run WiFi set a flag and reset your board and run WiFi.  Once finished with WiFi, reset the flag and run BLE again.

**Comment by wezleysherman** [comment]
@czuvich Thank you! That's the current way I'm doing it. It seems to work fine -.. My only concern is the 1-2 second delay before BLE is available again. 

This'll be something I look into when I move my code to use the ESP-IDF instead.
