### ISSUE TITLE
Assert failed in esp_err_t nvs::PageManager:

### ISSUE THREAD

**Issue by czuvich** [espressif/arduino-esp32#2221]
I am getting the following error randomly when trying to connect over WiFi to HTTPS using HttpClient.post().

E (4865) boot: Assert failed in esp_err_t nvs::PageManager::requestNewPage(), /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/nvs_flash/src/nvs_pagemanager.cpp:175 (usedEntries == newPage->getUsedEntryCount())
Task watchdog got triggered. The following tasks did not reset the watchdog in time:
13:33:10.838 ->  - IDLE (CPU 0)
13:33:10.838 -> Tasks currently running:
13:33:10.838 -> CPU 0: wifi
13:33:10.838 -> CPU 1: IDLE

Eventually, my own watchdog will catch it.  I am running the WiFi execution in a task.  Is this a task starvation/priority issue?

Board: WROVER DEV 4.1
Arduino IDE
1.0.0 release SDK

**Comment by marbalon** [comment]
Sometimes I have a similar problem but when I clean the whole project and then erase flash and upload again everything seems to work fin again.
