### ISSUE TITLE
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)

### ISSUE THREAD

**Issue by huynh213** [espressif/arduino-esp32#2230]
Hello,

I got this error and have been searching for an answer but no luck, and not sure if this's the right place to post the question. Please delete or move it if this's not a valid location.

Goal: Loading firmware to my custom board using ESP32 Download Tool.

I've been developing my code on my custom board (use ESP32-WROOM32D module) in Arduino IDE, and it loads the firmware perfectly and works great using Arduino:

For Arduino
Board: ESP32 Dev Module
Upload Speed: 115200
Flash frequency: 80Mhz
Flash Mode: DIO
Flash Size 4MB
Partition Scheme: Minimal SPIFFS (since I need more space for Wifi, BLE, and OTA libs)

For the ESP32 Bootloader:
Crystal Frequency: 40M
SPI speed: 80MHz
SPI mode: DIO
Flash size: 32Mbit
SpiAuoSet: unchecked
DonotChgBin: unchecked

For bin files

For the bootloader:
I did try to use bootloader_dio_80m.bin at the address 0x1000
-> I got the file from Arduino\hardware\espressif\esp32\tools\sdk\bin
-> For the address, I am not sure which one to put there so I use a random address that I found online, where other people use it.

For the partition:
I have min_spiffs.bin at the address 0x4000
->I used Python to generate the bin file from the min_spiffs.csv from the folder Arduino\hardware\espressif\esp32\tools\partitions
-> Same as the bootloader's address, I really don't know what to use for the partition address.

For my firmware:
I have the .bin file generated by Arduino, address at 0x10000. It looks like this is a valid address.

Some other info for reference:
--------------------------Arduino Message when successful loading firmware and board works-------
esptool.py v2.3.1
Connecting......
Chip is ESP32D0WDQ5 (revision 1)
Features: WiFi, BT, Dual Core, Embedded Flash
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 8MB (**I will switch my hardware module to 4MB later)
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 65525.1 kbit/s)...
Hash of data verified.
Flash params set to 0x023f
Compressed 13696 bytes to 8946...

Writing at 0x00001000... (100 %)
Wrote 13696 bytes (8946 compressed) at 0x00001000 in 0.8 seconds (effective 134.8 kbit/s)...
Hash of data verified.
Compressed 1509936 bytes to 871891...

Writing at 0x00010000... (1 %)
.................

--------------------------Using ESP32 Download Tool, the board doesn't work-------

From the ESP32 Download Tool:

.Uploading stub...
Running stub...
Stub running...
test offset : 4096 0x1000
case ok
test offset : 16384 0x4000
case ok
test offset : 65536 0x10000
case ok
CONNECT BAUD: 115200
.Efuse CONSOLE_DEBUG_DISABLE is already burned.
Uploading stub...
Running stub...
Stub running...

Then from Arduino Serial Monitor after resetting the power

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1324
load:0x40078000,len:7788
ho 0 tail 12 room 4
load:0x40080400,len:6448
csum err:0xd0!=0xff
ets_main.c 371
ets Jun 8 2016 00:22:57

**Comment by lbernstone** [comment]
I don't use windows, so I don't use the flash tool.  If you are able to upload through the Arduino IDE, you can go into preferences and set verbose output during upload.  This will show you the exact command used by [esptool](https://github.com/espressif/esptool) during an upload.  You should be able to match this up with the settings in the flash tool (or just use the esptool to do your uploading)

**Comment by huynh213** [comment]
@lbernstone: I set all the setting in ESP32 Download Tool the same as in the Arduino. 

Though I am not sure if my bootloader .bin file and its address are correct. Is there anyway to check that?

**Comment by lbernstone** [comment]
Set verbose output during upload.  This shows you the exact command (and files) used for upload.  esptool gets much more testing than the flash tool.

**Comment by copercini** [comment]
Try to flash the partitions.bin at `0x8000` instead `0x4000` this is the [default address](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html#config-partition-table-offset)

**Comment by huynh213** [comment]
@copercini: I did try the 0x8000, and somehow it works for the first few seconds but then restarts itself again with the error end the end.

Also, during the firmware loading, I got this error, not sure if that impacts to the loading process: "_....Efuse CONSOLE_DEBUG_DISABLE is already burned._"

Error from Arduino Serial Monitor: 
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1324
load:0x40078000,len:7788
ho 0 tail 12 room 4
load:0x40080400,len:6448
entry 0x400806e8
Starting...
Setting up pins...
Finished setting up pins
OTA_check1: 794
ets Jun  8 2016 00:22:57

**Comment by huynh213** [comment]
> Set verbose output during upload. This shows you the exact command (and files) used for upload. esptool gets much more testing than the flash tool.

@lbernstone: your way works great. I did use the same PY command from Arduino to CMD, and it works perfectly by using that way. 

Though my goal is using ESP32 Download Tool, so I can pass my Bin files to other people who might not have a proper environment to run PY. I did mirror all the addresses and settings to the ESP32 Download Tool: boot_app0.bin at 0xe000, bootloader at 0x1000, partition at 0x8000, and my firmware at 0x1000. 

However, I keep getting the error below:

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1496
load:0x40078000,len:8596
load:0x40080400,len:6992
entry 0x400806f4
Starting...
Setting up pins...
Finished setting up pins
ets Jun  8 2016 00:22:57

I also got this error from the ESP32 Download Tool: ._Efuse CONSOLE_DEBUG_DISABLE is already burned._
Wonder if you have any though?

**Comment by lbernstone** [comment]
It is running your app and rebooting.  You need to troubleshoot your code.  Add some print statements to figure out what is causing the reboot. [CONSOLE_DEBUG_DISABLE](https://www.esp32.com/viewtopic.php?t=3958)

**Comment by huynh213** [comment]
@lbernstone: 

I doubt that's caused my code though. When I load and run with Arduino, it works perfect the way it it. But I did add some print statement, and it always reset right after by OTACheck1. 

  ledcWrite(LED_INDICATOR, 255);
  delay(5000);
  OTA_check1 = analogRead(PIN_LIGHT_SENSE);
  Serial.print ("OTA_check1: "); Serial.print(OTA_check1); Serial.println( );
  ledcWrite(LED_INDICATOR, 0);
  delay(1000);
  ledcWrite(LED_INDICATOR, 255);
  delay(5000);
  OTA_check2 = analogRead(PIN_LIGHT_SENSE);
  Serial.print ("OTA_check2: "); Serial.print(OTA_check2); Serial.println( );
  ledcWrite(PWM_CHANNEL_INDICATOR, 0);
  delay(1000);

The burned Efuse seems not to be an issue.

**Comment by copercini** [comment]
what are `LED_INDICATOR` and `PWM_CHANNEL_INDICATOR` ?

**Comment by huynh213** [comment]
@lbernstone @

> what are `LED_INDICATOR` and `PWM_CHANNEL_INDICATOR` ?

They are just my indicator LEDs

**Comment by huynh213** [comment]
@lbernstone: I got a problem solved. The ESP32 Download Tool modified my Bin files and caused the error on my code. I did enable the "do not change my bin files" on my original files, and it works great now. Thanks much.

**Comment by murrellrr** [comment]
Just an FYI, in the `idf.py menuconfig` you may have enabled the RTC watchdog timer, which will cause a RTCWDT_RTC_RESET reset at some regular interval. If this is the case (the error is NOT at random time intervals) then you either need to "feed" or "kick" the RTC WDT timer or disable it altogether. Check the "CONFIG_BOOTLOADER_WDT_DISABLE_IN_USER_CODE" pre-processor definition to know if the RTC WDT is enabled or not...

To feed it import "soc/rtc_wdt.h" and invoke "rtc_wdt_feed();" at the correct interval, or disable via idf.py menuconfig at "Bootloader config"->"Use RTC watchdog in start code" -  Select this option, then tick "Allows RTC watchdog disable in user code". You can also change the RTC timeout settings in that configuration.

**Comment by adel1972** [comment]
Good morning
I’m using ESP32 devKitC, and my question is how to know the Board type of my ESP?
When I choose for example ESP32 Dev Module it works, but m=not all the pins are working
This is the log after compilation
esptool.py v2.5.0
Serial port COM6
Connecting........_
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core
MAC: 30:ae:a4:6b:03:60
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47..

**Comment by atanisoft** [comment]
@adel1972 please open a new issue with full details of your issue rather than comment on a very old issue.
