### ISSUE TITLE
Unexpected restart 

### ISSUE THREAD

**Issue by i4things** [espressif/arduino-esp32#2244]
14:01:01: /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/queue.c:1445 (xQueueGenericReceive)- assert failed!
14:01:01: abort() was called at PC 0x4009642f on core 1
14:01:01: 3ffbeed0 0x40081775:0x3ffbeef0 0x400826dd:0x3ffbef10 0x40083a64:0x00000000
14:01:01: Rebooting...

any suggestions ?  code is latest from github....

**Comment by me-no-dev** [comment]
decode that stack trace and post your code. As is nobody could help you with it. I will actually close this issue so you can open a new one and actually fill the issue form provided.
