### ISSUE TITLE
xEventGroupSetBitsFromISR Documentation

### ISSUE THREAD

**Issue by i4things** [espressif/arduino-esp32#2247]
The documentation about xEventGroupSetBitsFromISR

in :  https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/freertos.html#task-api

the example states to call : 

portYIELD_FROM_ISR( xHigherPriorityTaskWoken );

but ( I guess ) it should be changed to :

if( xHigherPriorityTaskWoken )
{
  portYIELD_FROM_ISR ();
}

as the macro : portYIELD_FROM_ISR  takes 0 parameters

**Comment by copercini** [comment]
Those FreeRTOS things refers more to IDF repository, so you probably will get a more precise answer asking here: https://github.com/espressif/esp-idf or http://esp32.com

This Arduino-ESP32 repo is more for issues related with Arduino APIs

**Comment by i4things** [comment]
OK moving to other group
