### ISSUE TITLE
Expired SSL Certificate

### ISSUE THREAD

**Issue by ChrisRomer** [espressif/arduino-esp32#2251]
SSL certificate expired for the suggested URL, on 12/28/2018:
https://dl.espressif.com/dl/package_esp32_index.json

I also tried the following URL, but am unable to find/select "ESP32 Dev Mode" in Arduino IDE any longer.
https://raw.githubusercontent.com/espressif/arduino-esp32/master/package/package_esp32_index.template.json

**Comment by mathstudi** [comment]
Problem fixed :-)).

**Comment by danuker** [comment]
This is happening again!

**Comment by HubertWagnerVE** [comment]
certs for https://dl.espressif.com/ are expired as of ‎Tuesday, ‎24 ‎September ‎2019 7:47:32 PM

**Comment by NidasioAlberto** [comment]
Having the same issue here. Hopefully tomorrow they will fix the problem.

**Comment by perca23** [comment]
Having the same issue here.

**Comment by jamesguang** [comment]
Same issue here.  They may fix it tomorrow but only valid for 90 days.
It looks that espressif uses some DIY certificate agency ("**Let's Encrypt**" is their name) which is only valid for 90 days. So it will happen again on Dec 23, 2019.
Too bad it will be Christmas time.

Hope espressif can use a good long lasting certificate.
![ESP32_Error](https://user-images.githubusercontent.com/23010378/65553938-21afc800-def6-11e9-926f-e40d193ff53f.JPG)

**Comment by jamesguang** [comment]
Work around:

Change the date of your computer to Sept 23 or before. Then go to Arduino IDE board manager. The download should be OK. Then you can install ESP32 now.
DO not forget to change the date back to correct date.

**Comment by me-no-dev** [comment]
certificate is fixed. This is a private server that is just linked to espressif domain.
