### ISSUE TITLE
Initialize BT controller failed with 0x103 ESP_ERR_INVALID_STATE error

### ISSUE THREAD

**Issue by rob-bits** [espressif/arduino-esp32#2253]
### Hardware:
Board:							OLIMEX ESP32-GATEWAY
Core Installation/update date:			2018.12.30
IDE name:							Sloeber IDE, esp32-arduino master (commit ids: 6dd8be3, 6f6ee98)
Flash Frequency:					?40Mhz?
PSRAM enabled:                                          ?no?
Upload Speed:						115200
Computer OS:                                            Windows 10

### Description:
I am trying to implement the ESP-IDF A2DP Source example with the ESP32-arduino library but Igot 0x103 ESP_ERR_INVALID_STATE error.

### Sketch: 
```cpp
void setup()
{
  Serial.begin(115200); //start serial for debug
  Serial.println(__func__);
  Serial.println(_firmware_version); //print the firmware version to debug interface
  Serial.println("-------------");
  Serial.println("API Started!");
  Serial.println("-------------");
// Add your initialization code here
  esp_err_t ret = nvs_flash_init();
  if (ret == ESP_ERR_NVS_NO_FREE_PAGES) {
      ESP_ERROR_CHECK(nvs_flash_erase());
      ret = nvs_flash_init();
  }

 esp_bt_controller_mem_release(ESP_BT_MODE_BLE);

  esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();

  ret = esp_bt_controller_init(&bt_cfg);
  if (ret != ESP_OK)  //this comes true with ret = 0x103
  {
      Serial.print("In function: ");
      Serial.println(__func__);
      Serial.println("initialize controller failed");
      Serial.println(ret);
      return;
  }

.
.
.
}
```
What can be the problem?

**Comment by lbernstone** [comment]
Please search through [old issues](https://github.com/espressif/arduino-esp32/issues?utf8=%E2%9C%93&q=is%3Aissue+esp_bt_controller_mem_release+sort%3Aupdated-desc+) before posting.  You cannot release BT memory unless you compile [arduino as an ESP-IDF component](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md)

**Comment by me-no-dev** [comment]
Also Arduino has it's own API to do esp_bt_controller_init! Do not use IDF one

**Comment by rob-bits** [comment]
Thank you very much for the guidance. Now everything works like a charm!

**Comment by me-no-dev** [comment]
great! :)
