### ISSUE TITLE
Can not find gitgui to run

### ISSUE THREAD

**Issue by AbySet** [espressif/arduino-esp32#2254]
- I'm trying to reinstall git removed few days ago, it's needed to flash esp32-grbl.
- My system is: Board: ESP32 devkit 1, Desk PC, Windows 10 x64, IDE: Arduino ver1.8.8
- Describe what is failing: I'm trying to follow tutorial how to install Git on windows 10 but after install finished i can not get to the git Gui interface, i have just Git Bash acces, not even found into installation folder.

### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:		No idea (sorry)
IDE name:						Arduino IDE, Windows10 x64 (IDF: i don't know wha this is)
Flash Frequency:					80Mhz
PSRAM enabled:                                     I don't know
Upload Speed:				       115200
Computer OS:                                         Windows 10

### Description:
I'm following tutorial how to install GitGui but i'm stuck at a step that need me to open Git IDE to include the update path because after installation i have only acces to GitBash, nothing else is installed.

I need to reinstall Git because i have a file missing when i try to flash esp32-grbl into ESP32 DEVKIT 1 and the result of compiling is this:

_Multiple libraries were found for "WiFi.h"
serial2socket.cpp:32:30: error: WebSocketsServer.h: No such file or directory

 Used: C:\Users\Phoenix\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WiFi
compilation terminated.

 Not used: C:\Users\Phoenix\Desktop\Arduino\libraries\WiFi
Multiple libraries were found for "SD.h"
 Used: C:\Users\Phoenix\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\SD
 Not used: C:\Users\Phoenix\Desktop\Arduino\libraries\SD
exit status 1
WebSocketsServer.h: No such file or directory_

Thank you.

**Comment by me-no-dev** [comment]
you have options to use the package manager and not deal with git. In any way, the error above shows you have a missing library. I am closing this as it is not a fault in this repository.
