### ISSUE TITLE
Change sdkconfig / "make menuconfig" properties

### ISSUE THREAD

**Issue by Curclamas** [espressif/arduino-esp32#229]
What would be the preferred way on changing the default sdconfig.h content which seems to be auto generated in a "make menuconfig" fashion?

Example: If we would like to have the following panic behavior:

```
# CONFIG_ESP32_PANIC_PRINT_HALT is not set
CONFIG_ESP32_PANIC_PRINT_REBOOT=y
# CONFIG_ESP32_PANIC_SILENT_REBOOT is not set
# CONFIG_ESP32_PANIC_GDBSTUB is not set
```
But in ```sdconfig.h``` (https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/include/config/sdkconfig.h) of the arduino repo we have:

```#define CONFIG_ESP32_PANIC_PRINT_HALT 1```

What ways could there be to achieve something like this? Also from a general perspective as well es from a sketch by sketch based approach?

**Comment by me-no-dev** [comment]
not doable because all libs are already prebuilt from IDF. if you want to mess with sdkconfig, see in README how to install arduino as IDF component.
