### ISSUE TITLE
ACS712 give strange current value

### ISSUE THREAD

**Issue by gabovich** [espressif/arduino-esp32#2292]
### Hardware:
Board:	                                        NodeMCU-32s
Core Installation/update date:	11/jul/2018
IDE name:	                                Arduino IDE 1.8.5  
Flash Frequency:	                        80Mhz
Upload Speed:	                       115200

### Description:
Trying to measure current via ACS712 (30A module) sensor current with esp32. From some reason I get all the time values about ~2750. Try to measure with different resistance and still get the same values.  I know that I need to take into account output sensitivity of the and all, but first I want to see that I get reasonable values that depends on the resistance connected. 
See the code attached.

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

const int analogIn = 36;

void setup(){ 
Serial.begin(115200);
pinMode(analogIn, INPUT);
}

void loop(){

  Serial.println(analogRead(analogIn));
 delay(250);
}
```

**Comment by lbernstone** [comment]
Have you put a multimeter on the pin?  2750 => 2750/4096*3.3 = 2216 mV at default settings.

**Comment by gabovich** [comment]
2750 is default value i get from analog pin. To centralize it I need to subtract 702 to get 4096/2=2048.
And then I get 2048/4096*5 = 2.5v at default settings.

**Comment by lbernstone** [comment]
google "capacitor stabilize analog reading".  ACS7XX meters are inherently noisy. See https://github.com/espressif/arduino-esp32/issues/1804 for calibration.  This forum is for errors in the code base, please use www.esp32.com for general issues.

**Comment by a-c-sreedhar-reddy** [comment]
@gabovich  did placing a capacitor solve your issue?

**Comment by gabovich** [comment]
@a-c-sreedhar-reddy  no, i still get the same wide range of values.

**Comment by a-c-sreedhar-reddy** [comment]
> @a-c-sreedhar-reddy no, i still get the same wide range of values.

are you measuring AC or DC

**Comment by gabovich** [comment]
for start i'm trying to measure 0A n

> > @a-c-sreedhar-reddy no, i still get the same wide range of values.
> 
> are you measuring AC or DC

**Comment by gabovich** [comment]
> for start i'm trying to measure 0A n
> 
> > > @a-c-sreedhar-reddy no, i still get the same wide range of values.
> > 
> > 
> > are you measuring AC or DC

for start i'm trying to measure 0A current but i'm getting wrong and unstable values.

**Comment by gabovich** [comment]
@a-c-sreedhar-reddy The capacitor improved the noise immunity, but the main problem is the non-linearity of the ADC in ESP32. Tried to test it with different resolutions but still I get inaccuracy results.
Is anyone knows how to fix the non-linearity ADC issue in ESP32?

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/issues/1804
Note, the ACS is also quite non-linear near 0A.  What @a-c-sreedhar-reddy is getting at with his question, is that the value is going to be sinusoidal when measuring AC values.

**Comment by FrKiko** [comment]
@gabovich are you being able to connect AC712 sensor (5V needed) with ESP32? How are you doing it?
