### ISSUE TITLE
How has the ESP32 SD library to be changed to work with HSPI instead of VSPI?

### ISSUE THREAD

**Issue by CaNiRaspUsomethinG** [espressif/arduino-esp32#2298]
Make your question, not a Statement, inclusive. Include all pertinent information:

What you are trying to do.
Describe your system( Hardware, computer, O/S, core version, environment)
Describe what is failing
Show the shortest possible code that will duplicate the error
Show the EXACT error message(it doesn't work is not enough)
Then if someone is interested and knowledgeable you might get a answer.  All of this work on your part shows us that you have worked to solve YOUR problem. The more complete your issue posting is, the more likely someone will volunteer their time to help you.

If you have a Guru Meditation Error or Backtrace, ***please decode it***:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							?ESP32 Dev Module? ?node32? ?ttgo_lora?
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
PSRAM enabled:                                          ?no?
Upload Speed:						?115200?
Computer OS:                                            ?Windows 10? ?Mac OSX? ?Ubuntu?

### Description:
Describe your problem here

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by CaNiRaspUsomethinG** [comment]
I want to run my SDcard-reader module on HSPI. What changes do I need to perform to use the Arduino-ESP32 SD library with HSPI?

**Hardware:**
Board:	ESP32 Wroom32 Doit Devkit

Description:

As I'm new to programming I'm not able to make the desired changes to the SD library to make a sdcard reader module work with not standard SPI = HSPI. My VSPI is already used for other purposes.

**Comment by me-no-dev** [comment]
```cpp
SPIClass SDSPI(HSPI);

void setup(){
  SDSPI.begin(sck, miso, mosi, -1);
  SD.begin(ss, SDSPI);
}
```

**Comment by PrateekGoyal18** [comment]
@me-no-dev When using the HSPI pins for interfacing SD card, the pinout says to connect MISO to GPIO12, but when it is connected we cannot upload the code since on GPIO 12 "boot fail if pulled high". So when we disconnect the MSIO and upload the code, it doesn't work.

**Comment by intensite** [comment]
Out of curiosity, where you ever able to make it work with HSPI?  I am having a similar issue where I had a bunch of PCB custom made which uses a W25Q64 flash chip,  just to discover that HSPI pins don't seem to work with the ESP32 DevKit V4

SPI | MOSI | MISO | CLK | CS
-- | -- | -- | -- | --
HSPI | GPIO 13 | GPIO 12 | GPIO 14 | GPIO 15

**Comment by PrateekGoyal18** [comment]
@intensite yes I was able to use the HSPI pins on ESP32, but uploading the code while MISO connected is still a problem for me. So when uploading the code, I disconnect the MISO jumper and when the code is uploaded, I connect it back.
The code that @me-no-dev gave will work for HSPI pins, but let me know if it doesn't work, I'll share my code snippet with you.

**Comment by davemaster** [comment]
Finally, it would be possible use HSPI for smartmatrix-teensylc ESP32 compatible library, with this pins arrangement in MatrixHardware_ESP32_V0.h smartmatrix file, 

    **#define R1_PIN  GPIO_NUM_2
    #define G1_PIN  GPIO_NUM_23//15
    #define B1_PIN  GPIO_NUM_4
    #define R2_PIN  GPIO_NUM_16
    #define G2_PIN  GPIO_NUM_27
    #define B2_PIN  GPIO_NUM_17

    #define A_PIN   GPIO_NUM_5
    #define B_PIN   GPIO_NUM_18
    #define C_PIN   GPIO_NUM_19
    #define D_PIN   GPIO_NUM_21
    #define E_PIN   GPIO_NUM_33//12
    #define LAT_PIN GPIO_NUM_26
    #define OE_PIN  GPIO_NUM_25**


And this in the smartmatrix_player.ino

SPIClass spiSD(HSPI);

// Chip select for SD card
#if defined(ESP32)
    #define SD_CS 15     // 5 **
#elif defined (ARDUINO)
    #define SD_CS BUILTIN_SDCARD
    //#define SD_CS 15
#endif
.......................
.......................
.......................

Serial.print("Initializing SD card...");

spiSD.begin(14, 32, 13, 15); //SCK,MISO,MOSI,SS //HSPI1
     
if (!SD.begin( SD_CS, spiSD )) 
{
   Serial.println("Card Mount Failed");
   return;
}

Then, it run perfectly, loading gifs from /gifs directory

Best Regards
