### ISSUE TITLE
Blink.ino only works when Serial Monitor is open

### ISSUE THREAD

**Issue by hexagon5un** [espressif/arduino-esp32#23]
Steps to reproduce: 
1) flash Blink,ino with an LED on GPIO13
2) Hit reset.
3) No blinky.
4) Open serial terminal of your choice.
5) Hit reset.
6) Blinks.

Multiple resets fail to get blinking, and the first one after a serial terminal is connected works every time. The same effect occurs regardless of which pin is used for GPIO, and across terminals (Arduino's serial monitor, picocom, etc.).

Fun bug!  That baffled me for a bit.  

(Using Arduino 1.6.8 and fresh pulls from esp-idf and arduino-esp32 from today. Board is a blue WROOM dev board.)

[Edit a bit later]: This seems to be a wider issue.  I get the same behavior with the esp-idf template app.  I'm going to file over there instead.  Feel free to close this one.

**Comment by me-no-dev** [comment]
this has to do with the dev board hardware design rather than code issue :)
should be fixed in the next hardware revision of the dev module

**Comment by hexagon5un** [comment]
Yup.  Sorry about that.  [Here](https://github.com/espressif/esp-idf/issues/59) is the link to the discussion about the hardware.  I'll close this one.

It was such a strange bug, I figured it had to be software.  :)

**Comment by jjmonteiro** [comment]
Hi guys, sorry for reviving an old issue but is there any hw or sw fix for this?
