### ISSUE TITLE
Sodaq_SHT2x Issue

### ISSUE THREAD

**Issue by asetyde** [espressif/arduino-esp32#2306]
Sodaq_SHT2x Issue

Read sensor with esp32 devkit gives strange value near zero with last pre-release 1.0.1 rc4
I can't see why

@stickbreaker  you can save me ? :)

**Comment by me-no-dev** [comment]
how about you delete this issue and start again actually filling the bug report form? There is code formatting and so on involved...

**Comment by asetyde** [comment]
ok, it's not so useful
