### ISSUE TITLE
RMT SetCarrier duty cycle fix

### ISSUE THREAD

**Issue by MarkLogiCom** [espressif/arduino-esp32#2316]
Board:							ESP32 Dev Module
Core Installation/update date:			9 Jan 2019
IDE name:					       Platform.io 
Flash Frequency:					40Mhz?
PSRAM enabled:                                      no
Upload Speed:						115200
Computer OS:                                          Windows 10

I had issues trying to set the duty cycle of the RMT carrier, looks like a copy and paste bug in the Arduino framework.
"\arduino-esp32\cores\esp32\esp32-hal-rmt.c"

bool rmtSetCarrier(rmt_obj_t* rmt, bool carrier_en, bool carrier_level, uint32_t low, uint32_t high)
{
    :
    RMT.carrier_duty_ch[channel].low = low;
    RMT.carrier_duty_ch[channel].low = high;
    :
}
The second .low should be .high - then it works fine.
Thanks for providing the RMT module, saved me a heap of time.
Mark

**Comment by me-no-dev** [comment]
Hey :) thanks for finding this :) fixed in Master!
