### ISSUE TITLE
wifi server compatible with the web server of the library?

### ISSUE THREAD

**Issue by moijerem59** [espressif/arduino-esp32#2321]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			13/jan/2019?
IDE name:							Arduino IDE
Flash Frequency:					240Mhz
PSRAM enabled:                                          no
Upload Speed:						115200
Computer OS:                                            Windows 10

### Description:
Hello, we use the library wifi server and the library web server and example wifitelnettoserial.
Everything seems to work perfectly until you use the ota function. The server is running and the page is accesible. We select the file.bin then we validate. then nothing happens.
If we use the ota function separately it works perfectly. Are both libraries compatible? Thks 

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

**Comment by lbernstone** [comment]
The libraries are compatible.  All these libraries provide a lot of information if you turn on the core debug level to verbose in the Tools menu (Use ESP32 dev module).
