### ISSUE TITLE
millis() rollover inconvenience

### ISSUE THREAD

**Issue by vtomanov** [espressif/arduino-esp32#2330]
the current implementation of millis() will rollover every 72min  WITHOUT filling the uin32 number in full - which in fact make all arduino libraries which calculate time interval using millis() to fail at the point of rollover - will be good if there is a exact match of arduino millis() on ESP32 as this will enable the available arduino libraries to work correctly..

**Comment by lbernstone** [comment]
This was a bug, [fixed](https://github.com/espressif/arduino-esp32/blame/master/cores/esp32/esp32-hal-misc.c#L118) in latest repo and release version.
