### ISSUE TITLE
Serial2 FREEZES Esp32 after OTA update ...

### ISSUE THREAD

**Issue by euquiq** [espressif/arduino-esp32#2331]
This started happening to me after the latests commits (over the last two or three weeks) but I cannot pinpoint it exactly. 

On my setup() I initialize Serial port for debug purposes and Serial2 port for talking with a GSM Modem.

I have the following code:

```
		Serial.println("A");
		delay(100);
		Serial2.begin(115200, SERIAL_8N1);	//GSM MODEM CONNECTIVITY
		Serial.println("B");
		delay(100);
```

When starting the Esp32, everything behaves OK, and I can read the "A" and "B" as expected.

When I command my Esp32 to perform an OTA update, first I end / close / turn off all non-needed tasks and interrupts. Among other things I issue a:

`Serial2.end();`

When the Ota is finished, I do an:

`ESP.restart();`

Right there, after restarting, I only get the "A" printout from Serial port, and Esp32 freezes. No error, no nothing, it just sits there indefinitely.

If I comment out the 

`//Serial2.end();`

... before OTA start, then the Esp32 resets fine at the end of the firmware upload / update, and I can read the "A" and "B" and everything works fine.

This seems to be a bug, but it can perfectly be just me wrongly using the serial ports. Anyway, it seems to be similar to: https://github.com/espressif/arduino-esp32/issues/1145

regards,

Enrique

**Comment by me-no-dev** [comment]
There is a hardware bug in Serial2 that is probably the reason for this. Try using Serial1 instead and just start it with the pins you need: `Serial1.begin(115200, SERIAL_8N1, 16, 17);`

**Comment by dneault333** [comment]
Same issue using Serial1.end().
Independent of OTA, cause same core dump each time.
//Serial1.end() .... no issue, but I need to Set Serial1 too a different baud rate, otherwise I would just not use it.


Backtrace: 0x40099dc7:0x3ffca470 0x4009980a:0x3ffca490 0x40087591:0x3ffca4b0 0x4008764d:0x3ffca4d0 0x40086b49:0x3ffca520 0x4013259d:0x3ffca540 0x400fd9a9:0x3ffca570 0x400e2ef9:0x3ffca590 0x400dc6ca:0x3ffca690 0x400eac83:0x3ffca700 0x40096531:0x3ffca720

**Comment by mars000** [comment]
@me-no-dev I'm using Serial2 and have some issues - can you point to information explaining the hardware bug pls.

**Comment by dneault333** [comment]
Serial 0,1 or 2...makes no difference, Serial.end() causes core dump.
No issue, unless, like my design, you have several mod's on same serial bus, which you turn on / off, so they don't interfere with each other, but you must change baud rate.

Changing Serial baud, without end, has same effect :(
