### ISSUE TITLE
SPIFFS Error: esptool not found after updated to V1.0.1

### ISSUE THREAD

**Issue by onghw84** [espressif/arduino-esp32#2339]
### Hardware:
Board:							Multiple ESP32 Dev Modules
Core Installation version:			1.0.1
IDE name:						Arduino IDE
Flash Frequency:					240Mhz
PSRAM enabled:                                     no
Upload Speed:				       921600
Computer OS:                                        Windows 10

### Description:
When using ESP32 Sketch Data Upload to upload files, error "SPIFFS Error: esptool not found!" occurs and upload failed. This was working perfectly fine at V1.0.0. The sketch can be uploaded fine though.

After copying esptool folder (available in V1.0.0) into the \esp32\tools\ folder, and edit package_esp32_index.json file to include the esptool in the toolsDependencies of version1.0.1, the error is temporarily resolved. But the package_esp32_index.json file is constantly being reset to the original one, maybe by arduino. Hence the solution above only works temporarily. 

### Debug Messages:
SPIFFS Error: esptool not found!

**Comment by me-no-dev** [comment]
grab the latest version of the tool :) this is updated
