### ISSUE TITLE
ESP32 strange WiFi behavior at standard example codes:

### ISSUE THREAD

**Issue by nae9** [espressif/arduino-esp32#2345]
Release example codes for arduino esp32 have some problem...
If i compile for example SimpleWiFiServer.ino and try to connect by web-browser then serial terminal shows that after right connection led wrong client with free rx buffer and it led to close this client by timeout (freezes main loop). (client.stop() not work properly)

It seemed that wifi go in to sleep mode after beginning and disable sleep mode after Wifi.begin() fix this problem. And all examples work fine with hi speed http response, as at very old libraries (before rx buffer introduce into wifi lib).

void setup()
{
...
WiFi.begin(ssid, password);
WiFi.setSleep(false);// this code solves my problem
...
}

But may be some body pull this parameter as default into release libs? Or change ALL example codes in such manner?
Or may be there is some bugs in libs that dont allow wifi work correct in sleepmode at fast http querry?

**Comment by mcuadros** [comment]
@nae9 is your router a Linksys EA?

**Comment by nae9** [comment]
> 
> 
> @nae9 is your router a Linksys EA?

EA4500 , openwrt git-18.228.31946-f64b152

**Comment by mcuadros** [comment]
https://github.com/me-no-dev/ESPAsyncWebServer/issues/437

I have a EA6300 with stock firmware, and I am having the same issues, the problem is that for me setSleep() doesn't solve my problems for output connections. 

The only way to fix the problem in my case is doing a ping to the IP until wakeups

**Comment by nae9** [comment]
Not linksys EA router can help issue?

**Comment by mcuadros** [comment]
Here, I only have this router here, but I will try with another routers. Based on the issue referred and the fact that you have a very similar issue and the same brand and series of mine, I can imagine that the problem is only related with the routers.

**Comment by mcuadros** [comment]
I can confirm that in my case, with outer routers works flawless, using same sever and board
