### ISSUE TITLE
lwip_connect_r: 113 - specifying timeout

### ISSUE THREAD

**Issue by siochs** [espressif/arduino-esp32#2348]
### Hardware:
Board: Heltec WiFi Lora 32
Core Installation/update date: 07/Jan/2019
IDE name: Platformio IDE
Flash Frequency: 40000000L
PSRAM enabled: no
Upload Speed: 115200
Computer OS: Windows 10

### Description:
I try to use HTTPClient to pull data from a remote server. This works. When the remote server is no longer reachable (because I pulled the plug), I get a `[E][WiFiClient.cpp:213] connect(): lwip_connect_r: 113` after 20 seconds. I tried to change this timeout by setting `http.setTimeout(...)` but this has no effect on `lwip_connect_r`. Is there any other way to change this timeout span in `lwip_connect_r`?

### Sketch: 
```cpp
HTTPClient http;  
http.begin("http://192.168.0.2/something");  
http.GET();
String response = http.getString();
http.end();
return response;
```

### Debug Messages:
Could not find how to get these with platformio.

**Comment by atanisoft** [comment]
setTimeout only works for existing connections and not for timing out the connection attempt. There is currently no API available for that part of the stack that I'm aware of.
