### ISSUE TITLE
SPIFFS Upload Failed with Version 1.0.1

### ISSUE THREAD

**Issue by mikey60** [espressif/arduino-esp32#2350]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:		        1.0.1
IDE name:						Arduino IDE
Flash Frequency:					80Mhz?
PSRAM enabled:                                     no
Upload Speed:				       921600
Computer OS:                                        Windows 10

### Description:
SPIFFS upload failed after I updated to version 1.0.1.  SPIFFS uploaded correctly after reverting back to 1.0.0.  I also removed and reinstalled ESP32 version 1.0.1 and SPIFFS upload failed.  SPIFFS upload then worked correctly when I reverted back to 1.0.0. 

### Debug Messages:
```
[SPIFFS] data   : C:\Users\Mike\Documents\Arduino\Files\ESP32\ESP32_Async_Web_Server\data
[SPIFFS] start  : 2691072
[SPIFFS] size   : 1468
[SPIFFS] page   : 256
[SPIFFS] block  : 4096
/index.html

/index.html.bak

/index.html.sav

/style.css

/style.css.bak

[SPIFFS] upload : C:\Users\Mike\AppData\Local\Temp\arduino_build_520450/ESP32_Async_Web_Server.spiffs.bin
[SPIFFS] address: 2691072
[SPIFFS] port   : COM6
[SPIFFS] speed  : 921600
[SPIFFS] mode   : dio
[SPIFFS] freq   : 80m

error: Invalid argument or value after --chip (argument #2)

SPIFFS Upload failed!

```

**Comment by mikey60** [comment]
I found a way to work around the problem.  If I select Board:->Heltec ESP32 Arduino->WIFI_LoRa_32, the SPIFFS upload works properly.

**Comment by 1TekPro** [comment]
@mikey60  I'm glad you found a solution. Just for curiosity, I would run the "getchipID" sketch. I have a suspicion that is in-fact a LoRa board and would make sure there isn't a boards/core issue.

Kindly close this issue when you are satisfied with the solution. Thank you.

**Comment by wfraga18** [comment]
Having the same issue, have to downgrade ?

**Comment by mikey60** [comment]
@wfraga18  Have you upgraded to the latest version of Arduino-esp32fs-plugin?  That solved the issue for me.

**Comment by Stasikiii** [comment]
After Update to 1.0.1 OLD UPLOADER starts, but UPLOADING get error like topic starter.
NEW UPLOADER don't works at all.. No UPLOAD menu.

**Comment by robertgregor** [comment]
Hi, is this working for you? Seems, that I have the same issue. The last version, where it is working OK, is 1.0.1 rc1. The newer versions are failing with exactly same errors. Any idea?

**Comment by 1TekPro** [comment]
This is a closed issue. If the solution (upgrading to the latest version of the arduino-esp32fs-plugin) did not work for you, please start a new issue.
