### ISSUE TITLE
No readings from grideye sensor w/ ESP32 

### ISSUE THREAD

**Issue by MatWhiteside** [espressif/arduino-esp32#2357]
### Hardware:
Board:							ESP32 thing
Core Installation/update date:			?
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                          No
Upload Speed:						115200
Computer OS:                                            Windows 10

### Description:
I have an ESP32 thing (DEV-13907) with a Grid-EYE Infrared Array Breakout (AMG8833) sensor. The two are connected using a Qwiic Cable - Breadboard Jumper (4-pin) with:
 - Black wire: GND
 - Red wire: 3v3
 - Yellow wire: 22
 - Blue wire: 21

The device is detected using a simple scanner: "I2C device found at address 0x69" however I'm not getting any readings from the device when trying to use the given examples for GRIDEYE.

Not sure if this is an issue with the ESP32 or the sensor or the SparkFun_GridEYE_Arduino_Library; or am I missing something?

For reference, here's the example I'm trying to run: https://github.com/sparkfun/SparkFun_GridEYE_Arduino_Library/blob/master/examples/Example3-DeviceTemperature/Example3-DeviceTemperature.ino

and I'm just getting the output:
Thermistor Temperature in Celsius: 0.00
Thermistor Temperature in Fahrenheit: 32.00
Thermistor Temperature register contents: 0

...which indicates to me values aren't being received from the sensor?

Any help would be appreciated.

### Sketch: 
```cpp

#include <SparkFun_GridEYE_Arduino_Library.h>
#include <Wire.h>

GridEYE grideye;

void setup() {

  // Start your preferred I2C object 
  Wire.begin();
  // Library assumes "Wire" for I2C but you can pass something else with begin() if you like
  grideye.begin();
  // Pour a bowl of serial
  Serial.begin(115200);

}

void loop() {

  Serial.print("Thermistor Temperature in Celsius: ");
  Serial.println(grideye.getDeviceTemperature());
  Serial.print("Thermistor Temperature in Fahrenheit: ");
  Serial.println(grideye.getDeviceTemperatureFahrenheit());
  Serial.print("Thermistor Temperature register contents: ");
  Serial.println(grideye.getDeviceTemperatureRaw(), BIN);

  Serial.println();
  Serial.println();

  delay(1000);
  
}
```

**Comment by stickbreaker** [comment]
@MatWhiteside you are going to have to do the debugging, because you have the hardware. I would recommend you update to the newest release v1.0.1 use these instructions [Board Manager install](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md).
Then read through [i2c Debugging](https://github.com/stickbreaker/arduino-esp32/wiki/i2c-Debugging)

* set the CORE DEBUG LEVEL to DEBUG.
* Enable [i2c Debug buffer](https://github.com/stickbreaker/arduino-esp32/wiki/i2c-Debugging#enable-debug-buffer)

Change your code to this:
```c++
#include <SparkFun_GridEYE_Arduino_Library.h>
#include <Wire.h>

GridEYE grideye;

void setup() {

  // Start your preferred I2C object 
  Wire.begin();
  // Library assumes "Wire" for I2C but you can pass something else with begin() if you like
  grideye.begin();
  // Pour a bowl of serial
  Serial.begin(115200);

  uint32_t flags = 0x3 << 16;
  Wire.setDebugFlags(flags,0); // have it dump every i2c transaction 

  Serial.print("Thermistor Temperature in Celsius: ");
  Serial.println(grideye.getDeviceTemperature());
  Serial.print("Thermistor Temperature in Fahrenheit: ");
  Serial.println(grideye.getDeviceTemperatureFahrenheit());
  Serial.print("Thermistor Temperature register contents: ");
  Serial.println(grideye.getDeviceTemperatureRaw(), BIN);
}

void loop() { }
```

Then Post the generated log so I can review it.

Chuck.

**Comment by MatWhiteside** [comment]
Ah, I did all your steps; got the generated log and then realized it was now working! Guess the update from 1.0.0 to 1.0.1 fixed something. 

Thanks for your help, appreciate it.

**Comment by stickbreaker** [comment]
ok, close this issue
