### ISSUE TITLE
ESP32 USART causing BLE to disconnect and stop advertising

### ISSUE THREAD

**Issue by wezleysherman** [espressif/arduino-esp32#2365]
Hi, I'm trying to run hardware USART through the HardwareSerial.h library and broadcast the outputs via BLE.

This works for awhile, but then the BLE randomly disconnects and the device is no longer advertising (however it is still on and performing work -.. e.i. changing LEDs). There are no error messages, no debug output, not crashing, etc. The BLE just completely stops working until a hardware reset is manually performed.

I have an idea that it's the USART buffer causing a memory issue and for my BLE server to crash. 
Is there a way I can disable the USART flow buffer? 

Is there anything else that could cause this issue? Thanks!
----------------------------- Remove above -----------------------------

### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.1
IDE name:						Arduino IDE
Flash Frequency:					40Mhz
PSRAM enabled:                                    ?no? ?yes?
Upload Speed:					115200
Computer OS:                                       Ubuntu

**Comment by stickbreaker** [comment]
HardwareSerial only uses the UART txfifo, no memory buffer.
 
Interrupts are only used for Rx. Which uses rxfifo and FreeRTOS queue.

Calls to write stall until all characters are added to the txfifo(128 bytes).

If the code is returning from `Serial.print()` serial isn't the problem.

**Comment by wezleysherman** [comment]
In that case -.. Maybe it's my BLE client that's cutting the connection prematurely. 

Thank you again @stickbreaker!
