### ISSUE TITLE
ESP32 not working

### ISSUE THREAD

**Issue by psimec** [espressif/arduino-esp32#2368]
My esp32 stopped working today... I was messing around with some code for soil moisture sensor and when I tried upload code I got an error:"a fatal error occurred failed to connect to esp32 timed out waiting for packet header". I have no red light on my esp32 like I had before. Can someone help me? Is my ESP dead and I needed to buy a new one?

**Comment by ArTyGill** [comment]
@psimec Measure the power supply at pin 3.3V

**Comment by ArTyGill** [comment]
The voltage regulator may have failed.

**Comment by remcoNL** [comment]
This worked fo me:

> You can try holding down the button marked "BOOT" or "FLASH" while esptool.py is "Connecting...". If you see esptool.py connect then you can release this button.

https://github.com/espressif/arduino-esp32/issues/2368
