### ISSUE TITLE
Hardware serial TX Only

### ISSUE THREAD

**Issue by CheetahGod** [espressif/arduino-esp32#2377]
I am trying to only use one pin for tx only. When I use Serial_TX_Only it says not declared in this scope. How would I add this functionality? It works for arduino uno but doesnt look like the hardware serial file for esp32 contains an init method with the option for tx only.

**Comment by 1TekPro** [comment]
I don't think you would need to change any code for this. If you don't connect a RX pin, does the RX code matter?

**Comment by CheetahGod** [comment]
You still have to put a rx pin number in. I don't have any extra gpio pins.

**Comment by lbernstone** [comment]
Did you try using NULL for the RX pin?

**Comment by tablatronix** [comment]
'SERIAL_TX_ONLY' was not declared in this scope

This needs to be fixed
