### ISSUE TITLE
All data from EEPROM dissapears after 2-3 week

### ISSUE THREAD

**Issue by szenciattila** [espressif/arduino-esp32#2379]
Greetings!
First of all I want to say thank you for this amazing job.

### Hardware:
Board:							ESP-WROOM-32D in custom PCB
Core Installation version:			1.0.0
IDE name:						Platform.io
Computer OS:                                          Mac OSX
Partition table:                                         min_spiffs.csv

### Description:
We deployed some PCB-s with ESP32 which are works perfectly until this week.
The problem is interesting, after 2-3 week some boards stopped working and after debugging I realized the following problem:
Every byte of EEPROM (4096) was returned to default value (255).
First time I think that the flash memory was broken, but when i reconfigured the device it's continues working perfectly. I think it's not a hardware issue, because it's happened on 3 devices.
We write to EEPROM maximum 10 times per day.

### Sketch:
The data is saved in structures. Below I put a code snippet to show how I save/load data (this not the whole source, but I only doing this with EEPROM).
```cpp
#include <Arduino.h>

#define EEPROM_SIZE 4096

struct NetworkConfiguration
{
    IPAddress IP;
    IPAddress defaultGateway;
    IPAddress subnetMask;
    IPAddress serverAddress;

    byte connectionType;
    boolean staticIP;
    uint16_t MQTTport;

    char WifiSSID[32];
    char WifiPassword[32];
}NetworkConfig;

void setup() 
{
    Serial.begin(115200);
    !EEPROM.begin(EEPROM_SIZE) && Serial.println("\n[EEPROM] Failed to initialize EEPROM");
    EEPROM.put(0, NetworkConfig); //Writing to EEPROM
    EEPROM.commit(); //Writing to EEPROM

    EEPROM.get(0, NetworkConfig); //Reading from EEPROM
}

void loop() {}
```

Thank you!

**Comment by stickbreaker** [comment]
@szenciattila More than likely you are running into a watchdog reset will the EEPROM(FLASH) is being erased. I would use NVS (Non Volatile Storage), a subsystem already built into the ESP32 ecosystem. It handles changing data better.  It is designed around the FLASH idiosyncrasies.

Chuck.
