### ISSUE TITLE
Not all String constructors work

### ISSUE THREAD

**Issue by hcs-svn** [espressif/arduino-esp32#24]
Example: 
String test = String(12.1);

Result:
core.a(WString.cpp.o)*: (.literal._ZN6StringC2Edh+0x0): undefined reference to dtostrf
core.a(WString.cpp.o)*: In function String::String(double, unsigned char)
WString.cpp:614: undefined reference to dtostrf

Possible solution:
Adding core_esp8266_noniso.c from the ESP8266 core (with another name that fits) solves the problem

**Comment by me-no-dev** [comment]
Done! :) https://github.com/espressif/arduino-esp32/commit/d7aed639ef9f08b2cb8a7d19cc73d30b3eb87ae5
