### ISSUE TITLE
Adding as an IDF component in an existing git clone

### ISSUE THREAD

**Issue by tmeysson** [espressif/arduino-esp32#2400]
The help file regarding "Adding arduino-esp32 as an IDF component" states that it should be cloned into the components/arduino directory of an existing IDF projetct, like esp-idf-template.

While this will be enough to build and flash an application using the arduino libraries, one should definitely not do this when it implies cloning into a subdirectory of an existing git clone. In that case, it should be added as a submodule, with the following syntax:

(at root of the template project)
git submodule add https://github.com/espressif/arduino-esp32.git components/arduino

This will make use of git in the resulting clone possible; otherwise git will complain when the untracked files in components/arduino are added and it finds out they are another clone.

Please confirm I am right about this; if so, then please add it to the installation instructions.
Thanks,
TM

**Comment by me-no-dev** [comment]
generally your projects should not be in the IDF folder at all. You should have your projects in their own folder and then just link to IDF. In that case, Arduino will be cloned to your project folder and not inside IDF's tree.
