### ISSUE TITLE
Can't get good reply from HTTP Server over softAP

### ISSUE THREAD

**Issue by GeorgeFlorian** [espressif/arduino-esp32#2406]
### Hardware:
Board:							ESP32 DEVKIT1
Core Installation version:			1.0.1-git this one https://github.com/espressif/arduino-esp32#development-status
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Linux Mint 19.1 Mate

### Description:

I'm trying to connect to the ESP32 via WiFi, through a given SSID and Password and to receive a webpage. The webpage is composed from a index.html + login.css + 2 images. I've uploaded them onto the flash memory using ESP32 Sketch Data Upload.

This is what I end up getting: https://i.postimg.cc/qM1VH3v3/Screenshot-20190130-174623-Chrome.jpg

What goes wrong ? I can't figure it out, because I've just started doing this. I am a complete noob. Thank you !

Also, as an added bonus: the Arduino's Serial Monitor works randomly. Sometimes it has a readable output, sometimes it has unreadable characters. I've tried different baud rates but it has no effect. Why is it random ? Shouldn't it get the same output for the same code ? I have to upload the sketch several times until it works properly.

Another bonus is that I have to press on the BOOT button every time I upload a sketch.

### Sketch: 
```
#include "SPIFFS.h"
#include "WiFi.h"
#include "ESPAsyncWebServer.h"

const char* ssid1 = "ESP32_Test";
const char* password1 = "123456789";

AsyncWebServer server(80);

void setup() {
  
  Serial.begin(115200);
  delay(2000);
  
  if(!SPIFFS.begin(true)) {
      Serial.println("An Error has occured while mounting SPIFFS");
      return;
    }

  WiFi.softAP(ssid1, password1);

  Serial.println();
  Serial.println("IP Address:   ");
  Serial.print(WiFi.softAPIP());
  Serial.println();

  server.on("/login", HTTP_GET, [](AsyncWebServerRequest *request) {
      request->send(SPIFFS, "/index.html", "text/html");
    });

  server.on("/login.css", HTTP_GET, [](AsyncWebServerRequest *request) {
      request->send(SPIFFS, "/login.css", "text/css");
    });

  server.on("/back-image.jpg", HTTP_GET, [](AsyncWebServerRequest *request) {
      request->send(SPIFFS, "/back-image.jpg", "image/jpeg");
  });

  server.on("/logo-metrici.png", HTTP_GET, [](AsyncWebServerRequest *request) {
      request->send(SPIFFS, "/logo.png", "image/png");
  });
  
    server.begin();

  Serial.println("index.html: ");
  Serial.print(SPIFFS.exists("/index.html"));
  Serial.println();
  Serial.println("login.css: ");
  Serial.print(SPIFFS.exists("/login.css"));
  Serial.println();
  Serial.println("back-image.jpg: ");
  Serial.print(SPIFFS.exists("/back-image.jpg"));
  Serial.println();
  Serial.println("logo-metrici.png: ");
  Serial.print(SPIFFS.exists("/logo-metrici.png"));
}

void loop() {
  
  }
```

### Debug Messages:
```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:10088
load:0x40080400,len:6380
entry 0x400806a4
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 0 - WIFI_READY

IP Address:   
192.168.4.1
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 13 - AP_START
index.html: 
1
login.css: 
1
back-image.jpg: 
1
logo-metrici.png: 
1E (36975) event: mismatch or invalid event, id=63
E (36976) event: default event handler failed!
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 15 - AP_STACONNECTED
dhcps: send_offer>>udp_sendto result 0
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 17 - AP_STAIPASSIGNED

```

**Comment by GeorgeFlorian** [comment]
> @GeorgeFlorian What's in index.html?

Does it really matter ?

`<!DOCTYPE html>
<html>
    
<head>
    <meta charset = "utf-8">
    <title>Login Form</title>
    <link rel = "stylesheet" href = "login.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
        
<body>
    <div class="login-box">
        <div class = "box-head">
            <div class = "logo-metrici"><img url="https://i.postimg.cc/fL0MX99P/logo-metrici-2x.png"></div>
            <div class = "network-title"><h1>Network Login</h1></div>
        </div>
        <div class ="textbox">
            <i class="fas fa-wifi"></i>
            <input type="text" placeholder="Network Name" name="" value="">
        </div>
        
        <div class="textbox">
            <i class="fas fa-key"></i>
            <input type="password" placeholder="Password" name="" value="">
        </div>
        
        <input class="button" type="button" name="" value="Sign in">
        
    </div>
    
</body>    

<footer>
    
</footer>

</html>`

**Comment by Jeroen88** [comment]
IMHO the ESP does exactly what you ask it to do: serve a web page. About the random characters, the serial monitor should match the baudrate you set with Serial.begin(). Add a two Serial.println() to start at a fresh line. About the boot button, this is normal behaviour, depending on your board. I advise you: read the docs before posting an issue. Also, this is not a helpdesk, but a place to report issues in the core software.

**Comment by 1TekPro** [comment]
@georgeFlorian Try sending it as a string
server.on("/login", HTTP_GET, [](AsyncWebServerRequest *request){
    request->send(SPIFFS, "/index.html", String(), false, processor);

**Comment by GeorgeFlorian** [comment]
> IMHO the ESP does exactly what you ask it to do: serve a web page. About the random characters, the serial monitor should match the baudrate you set with Serial.begin(). Add a two Serial.println() to start at a fresh line. About the boot button, this is normal behaviour, depending on your board. I advise you: read the docs before posting an issue. Also, this is not a helpdesk, but a place to report issues in the core software.

It doesn't serve the web page I need, or at least not all of it, as you can see in the screenshot I posted.

The serial monitor always matches the baudrate given with Serial.begin().
I even added <delay(2000);> after Serial.begin(115200) and I still have to upload the sketch several times until I get something readable.

I am sorry for posting here, but I have no idea where to post. If his isn't a helpdesk, point me towards one please ! Thank you !


> @GeorgeFlorian Try sending it as a string
> server.on("/login", HTTP_GET, [](AsyncWebServerRequest *request){
> request->send(SPIFFS, "/index.html", String(), false, processor);
> 
> "Does it really matter ?"
> Sure it does. What if the file contained "foo bar" and nothing else?

I got an error saying: "processor was not declared in this scope". I deleted it, changed the code to this, and it still doesn't work. It doesn't serve me the whole page, just what you see in the screenshot I posted:
I added the ESP.restart(); as a workaround to the Serial Monitor working when it wants to. Now, if it doesn't work from the first try, I just wait until the first restart, instead of uploading the sketch every time.

```
#include "SPIFFS.h"
#include "WiFi.h"
#include "ESPAsyncWebServer.h"

const char* ssid1 = "ESP32_Test";
const char* password1 = "123456789";

AsyncWebServer server(80);

void setup() {
  
  Serial.begin(115200);
  delay(2000);
  
  if(!SPIFFS.begin(true)) {
      Serial.println("An Error has occured while mounting SPIFFS");
      return;
    }

  WiFi.softAP(ssid1, password1);

  Serial.println();
  Serial.println("IP Address:   ");
  Serial.print(WiFi.softAPIP());
  Serial.println();

  server.on("/Login", HTTP_GET, [](AsyncWebServerRequest *request) {
      request->send(SPIFFS, "/index.html",String(), false);
    });

  server.on("/login.css", HTTP_GET, [](AsyncWebServerRequest *request) {
      request->send(SPIFFS, "/login.css", String(), false);
    });

    server.begin();
  
  File indexFile = SPIFFS.open("/index.html");

  if(!indexFile){
      Serial.println("Failed to open file for reading");
      return;
    }

  Serial.print("File Content: ");

  while(indexFile.available()) {
      Serial.write(indexFile.read());
    }
    
  indexFile.close();

}

void loop() {

   Serial.println("Restarting in 40 seconds");
  delay(40000);

  ESP.restart();
  
  }
```

**Comment by 1TekPro** [comment]
@GeorgeFlorian Does "Serial.print("File Content: ");" print the entire file?

**Comment by GeorgeFlorian** [comment]
> @GeorgeFlorian Does serial print the entire file?

Yes,it does. 

I found one thing: ESP32 Sketch Data Upload does not upload images. That's why my web page looks only half done.

I have a .jpg and a .png in the data folder waiting to be uploaded but they aren't.

**Comment by Jeroen88** [comment]
There is a community forum [here](www.esp32.com)

I assume that you are requesting a font and images from the public internet while you are connected to the softAP served by the ESP. Did you connect the computer / telephone requesting the page to the WiFi Access Point of the ESP? If this is the case the public internet can not be reached by your browser.

You can solve this by uploading the font and images to SPIFFS too and change the links in your HTML. I think you can solve this as well by _NOT_ setting up a softAP but connect your ESP to your router, connect the machine requesting the page to the same router and point your browser to the IP assigned to the ESP by your router.

[Here](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/get-started-devkitc.html) you can find the correct use of the buttons for uploading.

**Comment by GeorgeFlorian** [comment]
> There is a community forum [here](www.esp32.com)
> 
> I assume that you are requesting a font and images from the public internet while you are connected to the softAP served by the ESP. Did you connect the computer / telephone requesting the page to the WiFi Access Point of the ESP? If this is the case the public internet can not be reached by your browser.
> 
> You can solve this by uploading the font and images to SPIFFS too and change the links in your HTML. I think you can solve this as well by _NOT_ setting up a softAP but connect your ESP to your router, connect the machine requesting the page to the same router and point your browser to the IP assigned to the ESP by your router.
> 
> [Here](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/get-started-devkitc.html) you can find the correct use of the buttons for uploading.

Actually, the images are in the data folder and the paths are correctly set inside the HTML and CSS respectively. I tested them out before trying to upload them into the flash memory. They work as intended on PC. 

I can't find the community forum you are talking about. I click on your link and it says: "Not Found".

I don't want the ESP32 to go online. I've already tried that way and it works, but it is beside the point.
I want to have a web page on the flash memory that I can access by connecting to the softAP via WiFi and then accessing the web page via IP.

The problem now is that I get a HTML page with CSS styling but for some reason it doesn't show the images.

**Comment by Jeroen88** [comment]
The image is pointing to a public URL, not a link relative to the root in the ESP:

> 
img url="https://i.postimg.cc/fL0MX99P/logo-metrici-2x.png"

The same is true for the font. Also, there is no route on the ESP to serve these files.

All your questions have nothing to do with the ESP core

I made a mistake in the community link, it is actually here: www.esp32.com.

**Comment by Jeroen88** [comment]
You must have a server.on() for each file you want to serve. 

Sketch upload should work (almost ever) in one go. Maybe you do not use the buttons correctly, see:

> Here you can find the correct use of the buttons for uploading.

or maybe there is something wrong with your USB cable / port, etc. Sometimes closing the serial monitor before uploading will help.

**Comment by GeorgeFlorian** [comment]
> You must have a server.on() for each file you want to serve.
> 
> Sketch upload should work (almost ever) in one go. Maybe you do not use the buttons correctly, see:
> 
> > Here you can find the correct use of the buttons for uploading.
> 
> or maybe there is something wrong with your USB cable / port, etc. Sometimes closing the serial monitor before uploading will help.

I did it ! Thank you !

**Comment by Jeroen88** [comment]
Nice! Please close the issue.
