### ISSUE TITLE
[I2C] MLX90614 temp sensor not working over ESP32 I2C interface

### ISSUE THREAD

**Issue by marquesn** [espressif/arduino-esp32#2408]
### Hardware:
Board:							ESP-WROOM-32 (ESP32_DevKitc_V4)
Core Installation version:			        1.0.1
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                       No
Upload Speed:					        921600
Computer OS:                                          Windows 10

### Description:
I have been trying to get a MLX90614 IR temperature sensor to work with the ESP32 - this sensor makes use of the I2C interface. However, the values are always reported back as 1037 C and 1899F. 

I have been using pins 22 and 21 for SCL and SDA, and have tried supplying the sensor with both 3.3V and 5V. I have also connected 4.7K pull-up resistors to the SDA and SCL lines (also tried 2K7, 10K, and with no pull-ups).

I am using the "Adafruit_MLX90614" library, and have also tried to use the Sparkfun MLX90614 (although Sparkfun is giving me a compiling error when trying to compile for the ESP32). I have also tried to connect another MLX90614 to the ESP32 on the off chance that one of them might've just been broken, but the results were the same.

I have also seen similar issues to this as in:
https://github.com/espressif/arduino-esp32/issues/1694
https://github.com/espressif/arduino-esp32/issues/2089
https://github.com/espressif/arduino-esp32/issues/1962

Based on the solutions provided in the links shown above, I also tried to update the latest version of the arduino-esp32 using the arduino boards manager to version 1.0.1.

### Sketch:
```cpp

#include <Wire.h>
#include <Adafruit_MLX90614.h>
 
Adafruit_MLX90614 mlx = Adafruit_MLX90614();
 
void setup()
{
  Serial.begin(9600);
  mlx.begin();
}
 
void loop()
{
  Serial.print("Ambient = ");
  Serial.print(mlx.readAmbientTempC());
  Serial.print("*C\tObject = ");
  Serial.print(mlx.readObjectTempC());
  Serial.println("*C");
  Serial.print("Ambient = ");
  Serial.print(mlx.readAmbientTempF());
  Serial.print("*F\tObject = ");
  Serial.print(mlx.readObjectTempF());
  Serial.println("*F");
   
  Serial.println();
  delay(1000);
}
```

**Comment by stickbreaker** [comment]
@marquesn I don't have access to  MLX90614 so I can't directly test it. 

I looked at the adafruit library, it is very simple and does not test for any error codes / i2c failure codes.

I recommend you add debug code to your copy of the library and see what errors are being returned by i2c(Wire).

Change every `Wire.endTransmission()` into:
```c++
uint_8 err = Wire.endTransmission();
if(err != 0) {
  Serial.printf("fail %d(%s)/n",err, Wire.getErrorText(err));
}

// after each requestFrom() add
if(Wire.lastError() !=0 ){
Serial.printf("fail %d(%s)/n",err, Wire.getErrorText(err));
}
```

See what is actually happening.

Chuck.

**Comment by marquesn** [comment]
@stickbreaker Many thanks for having a look at this!

I've inserted that piece of code into the Adafruit library and I got the following in the serial output window:
```
ɭշ⸮⸮8⸮"/-n^.p⸮⸮⸮5Q⸮N⸮⸮⸮[V][esp32-hal-i2c.c:1483] i2cInit(): num=0 sda=21 scl=22 freq=0
[V][esp32-hal-i2c.c:1677] i2cSetFrequency(): freq=100000Hz
[V][esp32-hal-i2c.c:1692] i2cSetFrequency(): cpu Freq=240Mhz, i2c Freq=100000Hz
[V][esp32-hal-i2c.c:1698] i2cSetFrequency(): Fifo delta=1
fail 2(ACK)/nfail 2(ACK)/n1037.55*C
Ambient = fail 2(ACK)/nfail 2(ACK)/n1899.59*F	Object = fail 2(ACK)/nfail 2(ACK)/n1899.59*F

Ambient = fail 2(ACK)/nfail 2(ACK)/n1037.55*C	Object = fail 2(ACK)/nfail 2(ACK)/n1037.55*C
Ambient = fail 2(ACK)/nfail 2(ACK)/n1899.59*F	Object = fail 2(ACK)/nfail 2(ACK)/n1899.59*F
```

**Comment by stickbreaker** [comment]
@marquesn ok, that is telling you the I2C communication succeeded.
now you need to look at the data it received.
Write out the raw data byte from the sensor.

```c++
 // where it receives data with Wire.read(), print the raw byte out
uint16_t Adafruit_MLX90614::read16(uint8_t a) {
  uint16_t ret;

  Wire.beginTransmission(_addr); // start transmission to device 
  Wire.write(a); // sends register address to read from
  uint8_t err =  Wire.endTransmission(false); // end transmission
  if(err !=0){
    Serial.printf("Selecting sensor register failed =%d(%s)\n",err, Wire.getErrorText(err)));
  }
  uint8_t count =Wire.requestFrom(_addr, (uint8_t)3);// send data n-bytes read
  If(count != 3){
    Serial.printf("Receiving sensor data failed, expected 3 bytes received %d.\n Wire() error =%d(%s)\n",
     count,Wire.lastError(),Wire.getErrorText(Wire.lastError()));
  }
  uint8_t raw = Wire.read();
  Serial.printf(" first byte = 0x%02x",raw);
  ret = raw; // receive DATA
  raw = Wire.read();
   Serial.printf(" Second Byte = 0x%02x\n",raw);
  ret |= raw << 8; // receive DATA

  uint8_t pec = Wire.read();
  Serial.printf(" pec=0x%02x\n", pec);
  return ret;
}
```

Chuck.

**Comment by marquesn** [comment]
> 
> 
> @marquesn ok, that is telling you the I2C communication succeeded.
> now you need to look at the data it received.
> Write out the raw data byte from the sensor.
> 
> ```c++
>  // where it receives data with Wire.read(), print the raw byte out
> uint16_t Adafruit_MLX90614::read16(uint8_t a) {
>   uint16_t ret;
> 
>   Wire.beginTransmission(_addr); // start transmission to device 
>   Wire.write(a); // sends register address to read from
>   uint8_t err =  Wire.endTransmission(false); // end transmission
>   if(err !=0){
>     Serial.printf("Selecting sensor register failed =%d(%s)\n",err, Wire.getErrorText(err)));
>   }
>   uint8_t count =Wire.requestFrom(_addr, (uint8_t)3);// send data n-bytes read
>   If(count != 3){
>     Serial.printf("Receiving sensor data failed, expected 3 bytes received %d.\n Wire() error =%d(%s)\n",
>      count,Wire.lastError(),Wire.getErrorText(Wire.lastError()));
>   }
>   uint8_t raw = Wire.read();
>   Serial.printf(" first byte = 0x%02x",raw);
>   ret = raw; // receive DATA
>   raw = Wire.read();
>    Serial.printf(" Second Byte = 0x%02x\n",raw);
>   ret |= raw << 8; // receive DATA
> 
>   uint8_t pec = Wire.read();
>   Serial.printf(" pec=0x%02x\n", pec);
>   return ret;
> }
> ```
> 
> Chuck.

Thanks Chuck. This code gives me the following:

```
[V][esp32-hal-i2c.c:1483] i2cInit(): num=0 sda=21 scl=22 freq=0
[V][esp32-hal-i2c.c:1677] i2cSetFrequency(): freq=100000Hz
[V][esp32-hal-i2c.c:1692] i2cSetFrequency(): cpu Freq=240Mhz, i2c Freq=100000Hz
[V][esp32-hal-i2c.c:1698] i2cSetFrequency(): Fifo delta=1
Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1037.55*C
Ambient = Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1899.59*F	Object = Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1899.59*F
```
But changing:
```
uint8_t err =  Wire.endTransmission(false); // end transmission
```
to:
```
uint8_t err =  Wire.endTransmission(); // end transmission
```
gives me:
```
[V][esp32-hal-i2c.c:1483] i2cInit(): num=0 sda=21 scl=22 freq=0
[V][esp32-hal-i2c.c:1677] i2cSetFrequency(): freq=100000Hz
[V][esp32-hal-i2c.c:1692] i2cSetFrequency(): cpu Freq=240Mhz, i2c Freq=100000Hz
[V][esp32-hal-i2c.c:1698] i2cSetFrequency(): Fifo delta=1
1037.55*C	Object = Selecting sensor register failed =2(ACK)
Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1037.55*C
Ambient = Selecting sensor register failed =2(ACK)
Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1899.59*F	Object = Selecting sensor register failed =2(ACK)
Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1899.59*F
```

**Comment by stickbreaker** [comment]
The Error 2, ACK is telling you the sensor did not respond when the ESP32 sent out it's request.. Since it did not respond, no data was received. the 0xff is the response from `Wire.read()` when no data is available.

The code that produces this:
```
=Ambient = fail 0(OK)/n1037.55*C	Object = fail 0(OK)/n1037.55*C
Ambient = fail 0(OK)/n1899.59*F	Object = fail 0(OK)/n1899.59*F

Ambient = fail 0(OK)/n1037.55*C	Object = fail 0(OK)/n1037.55*C
Ambient = fail 0(OK)/n1899.59*F	Object = fail 0(OK)/n1899.59*F
```

the (ok) shows that the device can answer. 

does your circuit had 3.3k pullups on SCL and SDA?

Once you can get no errors reported by `Wire()` then we can see what the data conversion problems are.

Chuck.

**Comment by marquesn** [comment]
I see... I have 4.7K pull-ups on the SCL and SDA lines. 

I believe I had tried other resistor values as well, but I will try again when I get back to the office, and I'll report back here with the results.

Once again, thanks for the clarifications @stickbreaker

**Comment by marquesn** [comment]
@stickbreaker I have just tried this with the 3.3K pull-ups but the result is the same:
```
[V][esp32-hal-i2c.c:1483] i2cInit(): num=0 sda=21 scl=22 freq=0
[V][esp32-hal-i2c.c:1677] i2cSetFrequency(): freq=100000Hz
[V][esp32-hal-i2c.c:1692] i2cSetFrequency(): cpu Freq=240Mhz, i2c Freq=100000Hz
[V][esp32-hal-i2c.c:1698] i2cSetFrequency(): Fifo delta=1
Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1037.55*C
Ambient = Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1899.59*F	Object = Receiving sensor data failed, expected 3 bytes received 0.
 Wire() error =2(ACK)
 first byte = 0xff Second Byte = 0xff
 pec=0xff
1899.59*F
```
Also just tried it with the other MLX sensor that I have, as well as with another ESP32 of the same model, and the results were the same.

Just in case I may be doing something wrong with with the debug code in the Adafruit library, here is a pastebin link of my Adafruit_MLX90614.cpp library after substituting in the debug code that you provided:

https://pastebin.com/WBr8Bihy

**Comment by marquesn** [comment]
Does anyone else have any other ideas regarding this issue?

**Comment by asetyde** [comment]
I've same problem with SHT21 value is not correct, probably all is linked to cpu/i2c relationship I think, this part of code is changed, test if, as I, with previous releases work

**Comment by elasly** [comment]
I am having the exact same issue with the same versions of libraries, Any one figured the reason behind this or how to solve it. Thanks in advance

**Comment by martinlaurentfr** [comment]
As i m a noob, I've been spendaing days and days to find a solution on this.
It seems defaut frequency is not the right one, when i specified it, the probleme disepeared

i2c = machine.I2C(scl=machine.Pin(sdaPin), sda=machine.Pin(sclPin),freq=100000)

hope it can help

**Comment by nae9** [comment]
I set i2c speed to 50000 and mlx start answer fine!!!

**Comment by SpoturDeal** [comment]
I have changed line 25 in Adafruit_mlx90614.h

to
```
#define MLX90614_I2CADDR 0x0E
``` 

The original address was 0x5A
No i am reading proper values

```
Ambient = 27.65*C       Object = 26.83*C
Ambient = 81.77*F       Object = 80.29*F
```

**Comment by francisreader** [comment]
> I set i2c speed to 50000 and mlx start answer fine!!!
The other suggestions did not work for me, but when I changed from the default (50kHz) to 100kHz now getting reliable comms.

**Comment by nae9** [comment]
> > I set i2c speed to 50000 and mlx start answer fine!!!
> > The other suggestions did not work for me, but when I changed from the default (50kHz) to 100kHz now getting reliable comms.

In my files default was 100k :)

**Comment by crizgem** [comment]
I also had this problem, I tried to find out what was going on. I found that the adafruit library has the wrong address of the sensor. So i checked the available i2C adreess using i2C master library (https://github.com/rambo/I2C). 
Here the code.

`#include <I2C.h>

void setup() {
  // put your setup code here, to run once:
  I2c.begin();
  Serial.begin(9600);
}

void loop() {
  // put your main code here, to run repeatedly:
  I2c.scan();
  delay(1000);
}`

I got this:

![i2c_adrees](https://user-images.githubusercontent.com/68703867/88313664-77e9c500-ccd9-11ea-9092-ef4b8823f5f2.JPG)

I changed the devide I2C address, in Adafruit_MLX90614 library
![Inkedlib_LI](https://user-images.githubusercontent.com/68703867/88314947-44a83580-ccdb-11ea-8662-222eabeef4a9.jpg)

Now, I get the proper values. After this, the 0x5A address magically started working. ¬¬
![temp](https://user-images.githubusercontent.com/68703867/88314738-f98e2280-ccda-11ea-8931-418cd5be8939.JPG)

**Comment by martinberlin** [comment]
For me it worked lowering frequency and setting right PIN modes:

```c++
  pinMode(22, OUTPUT);       // Clock goes from master to peripherical  
  pinMode(21, INPUT_PULLUP); // Data should be internally pulled up (or 4.7K pullup to 3.3v)
  Wire.begin(21,22,10000); 
```

**Comment by isarafx** [comment]
I try fixing by change i2c address or change wire frequency but still not work
but when I change from 3.3v from my esp32 to 5v arduino nano
It worked fine now(even I change back to old 3.3v)
hope this help :)
ps.btw in case you're using external source to power the module don't forget to connect gnd to esp32 like me!
