### ISSUE TITLE
Eclipse editor lists errors for esp-idf includes

### ISSUE THREAD

**Issue by william-ferguson-au** [espressif/arduino-esp32#2426]
### Hardware:
Board:							NA - ESP32 Dev Module
Core Installation version:			git master 86fdb5b23dbc90a37ffa140dadf22b599fd9913f
IDE name:						IDF component using Eclipse
Flash Frequency:					NA
PSRAM enabled:                                    NA
Upload Speed:					NA
Computer OS:                                        Windows 10

### Description:
I am using arduino-esp32 as an esp-idf component.
I am using Eclipse as the IDE.

The app compiles fine, both via Make and through Eclipse.
The Eclipse editor window shows many esp-idf functions as being in error (underlined in red).

Eg the ESP_LOGI macro
```
  static const char* TAG = "wt_comms";
  ESP_LOGI(TAG, "Reconnecting to WiFi");
```

In the case above it is because the esp_log_level_t is declared as an anonymous enum and is declared in 2 places. Once in esp-idf folder and once in components/arduino-esp32/tools/sdk/include.

But they are many other functions that also show as in fault because they appear in both places.

See https://www.esp32.com/viewtopic.php?f=13&t=9110&p=38091#p38091

What needs to be done to the arduino-esp32/component.mk to not include tools/sdk/include?

**Comment by CanHobby** [comment]
I have the same problem with:

Eclipse IDE for C/C++ Developers
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200
OS: Linux, v.5.3.0-19-generic, x86_64 / gtk 3.24.12
Java version: 12.0.2

no problem compiling and uploading but the editor redlines a lot of esp32 stuff..
