### ISSUE TITLE
ULP processor

### ISSUE THREAD

**Issue by q-bird** [espressif/arduino-esp32#2427]
Hi there,

Are there any ways to program for Ultra Low Power coprocessor using Arduino IDE?
(Running parallel with the main core or jst run the ULP while main core sleeping)

Thank you

**Comment by MarkyAD** [comment]
Its fairly easy in an esp-idf project but I also had luck with ulptool https://github.com/duff2013/ulptool.git

**Comment by boarchuz** [comment]
ULP Macros:
https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/ulp_macros.html
