### ISSUE TITLE
Request: Connect() function for Bluetooth Classic

### ISSUE THREAD

**Issue by peterkydas** [espressif/arduino-esp32#2440]
Bluetooth Serial is working fine with the `"BluetoothSerial.h"` and a device connects to the ESP32. The only issue I have is that there is no way for the ESP32 to initiate a connection to another Bluetooth device. The Bluetooth device I want to connect to doesn't have an interface to initiate the connection. Is it possible to add in a `connect()` function that would take a MAC address of a device and begin the connection? I've tried using the IDF Bluetooth examples but comms isn't my strong point.

**Comment by iZhangHui** [comment]
Have the same requirement with you. :)
