### ISSUE TITLE
Just want to verify this does NOT work with IOS

### ISSUE THREAD

**Issue by Sparkinman** [espressif/arduino-esp32#2441]
As far as I can tell, this will not work with IOS devices, can anyone please confirm for sure?

**Comment by lbernstone** [comment]
arduino-esp32 is quite specifically for programming the [ESP32 SoC](https://www.espressif.com/en/products/hardware/esp32/overview).  [Arduino](https://www.arduino.cc) is a platform independent programming IDE.  It does not run on IOS, because if you can afford a $1000 phone, you probably have a real computer.

**Comment by Sparkinman** [comment]
Not exactly what I meant!  As near as I can tell, there is no IOS support for serial over bluetooth communication (SPP), rendering this library unusable on IOS devices...correct?

**Comment by lbernstone** [comment]
Sorry, my mind reading doesn't work so well on Sunday. https://github.com/espressif/arduino-esp32/tree/master/libraries/BluetoothSerial

**Comment by Sparkinman** [comment]
I see that on the front page, it SAYS that it works with IOS, but using the example sketch, and the recommended app on IOS, the device doesn't even show up in a BT scan (however from Windows, Android, and Mac) it does, and works fine from them.  Am I doing something wrong, or is it simply IOS being a problem, and help would be appreciated!

**Comment by Arduingo** [comment]
One reason is because the suggested iOS App (https://github.com/hoiberg/HM10-BluetoothSerial-iOS) is scanning for a different service a Characteristic IDs

    /// UUID of the service to look for.
    var serviceUUID = CBUUID(string: "FFE0")
    
    /// UUID of the characteristic to look for.
    var characteristicUUID = CBUUID(string: "FFE1")

**Comment by chegewara** [comment]
> One reason is because the suggested iOS App (https://github.com/hoiberg/HM10-BluetoothSerial-iOS) is scanning for a different service a Characteristic IDs
> 
> ```
> /// UUID of the service to look for.
> var serviceUUID = CBUUID(string: "FFE0")
> 
> /// UUID of the characteristic to look for.
> var characteristicUUID = CBUUID(string: "FFE1")
> ```

This is BLE app, BluetoothSerial is classic BT protocol.

**Comment by Arduingo** [comment]
> > One reason is because the suggested iOS App (https://github.com/hoiberg/HM10-BluetoothSerial-iOS) is scanning for a different service a Characteristic IDs
> > ```
> > /// UUID of the service to look for.
> > var serviceUUID = CBUUID(string: "FFE0")
> > 
> > /// UUID of the characteristic to look for.
> > var characteristicUUID = CBUUID(string: "FFE1")
> > ```
> 
> This is BLE app, BluetoothSerial is classic BT protocol.

The HM10 is a BLE module that can be used as an UART, I have used the example with own "terminal" writing and reading data using BLE, now BLE does not support native UART so each vendor should implement their own "Simulated" UART. The HM10 implemented this, but the sketch espressif is giving us is not compatible. In other words the suggested app in IOS is useless.
