### ISSUE TITLE
Can't connect Esp32 and 4x4 keypad

### ISSUE THREAD

**Issue by palsayantan** [espressif/arduino-esp32#2443]
I was trying to connect a 4x4 alphanumeric keypad with the ESP32 based NodeMCU board. I want to connect them to the ADC pins of nodeMCU. So I modified the example customkeypad code and assigned the row and column pins to 36,39,34,35 and 32,33,25,26 respectively. But that didn't work and I get no response. Please help.

**Comment by GeorgeFlorian** [comment]
Hello ! I would like to try something similar. Did you manage to make it work ?

**Comment by palsayantan** [comment]
Yah it's working properly

**Comment by GeorgeFlorian** [comment]
> Yah it's working properly

And how did you do it ?

**Comment by palsayantan** [comment]
Actually you can't use certain pins on the esp32 with matrix keypad. For me it won't work on the pin 34,35,36 and 39. So I changed the pin numbers in the Code and it worked. 
You can check out my SMART VENDING MACHINE repo for reference.

**Comment by atanisoft** [comment]
Pins 34-39 are input only and can be used for matrix inputs if the library is configured correctly.

**Comment by GeorgeFlorian** [comment]
> Pins 34-39 are input only and can be used for matrix inputs if the library is configured correctly.

What library ? How can I use a keypad ? I don't suppose that I'll just buy one and connect it to the ESP and it will work like magic.

**Comment by atanisoft** [comment]
> What library ? How can I use a keypad ? I don't suppose that I'll just buy one and connect it to the ESP and it will work like magic.

A very quick search here on GitHub resulted in this lib https://github.com/Nullkraft/Keypad which appears that it should work with the esp32. The rows pins are used as INPUT and cols are OUTPUT.

**Comment by GeorgeFlorian** [comment]
> > What library ? How can I use a keypad ? I don't suppose that I'll just buy one and connect it to the ESP and it will work like magic.
> 
> A very quick search here on GitHub resulted in this lib https://github.com/Nullkraft/Keypad which appears that it should work with the esp32. The rows pins are used as INPUT and cols are OUTPUT.

I guess I don't have to use 1 pin per key, correct ?

I actually need a bigger keypad, something more like a keyboard. Something that has all the alphanumerical keys, an enter and a backspace.

Can this be done in ESP32 ? Or should I move to a Raspberry Pi Zero ?

I need something like this:
[![maxresdefault.jpg](https://i.postimg.cc/wBhzc28x/maxresdefault.jpg)](https://postimg.cc/94FscGQs)

**Comment by palsayantan** [comment]
You can visit electronoobs channel on YouTube. He worked on a similar project
