### ISSUE TITLE
vTaskResume can unblock tasks that are suspended by ulTaskNotifyTake

### ISSUE THREAD

**Issue by k8C** [espressif/arduino-esp32#2445]
### Hardware:
Board:							NodeMCU-32S
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:					115200
Computer OS:						Windows 10

### Description:
I have a task which periodically uploads sensor data to cloud, this task is controlled by a timer with Direct to Task Notification (`xTaskNotifyGive` & `ulTaskNotifyTake`). It is also suspended and resumed depending on WiFi event STA_DISCONNECTED or STA_GOT_IP. If the task has finished uploading data and is waiting for new notification, and at the same time the WiFi access point reboots, `vTaskResume` gets called and causes the task to be unblocked. This breaks my code. I also tried replacing `ulTaskNotifyTake` with `xTaskNotifyWait `but no difference. So I think the problem is with vTaskResume. The sketch below is an example in which I use `xTaskResumeFromISR `in timer to unblock loop task to blink the built-in LED.

### Sketch:
```cpp
hw_timer_t * timer;
TaskHandle_t LoopTH;

void IRAM_ATTR onTimer() {
  xTaskResumeFromISR(LoopTH);
//  vTaskNotifyGiveFromISR(LoopTH, NULL);
}

void setup() {
  pinMode(2, OUTPUT);
  LoopTH = xTaskGetCurrentTaskHandle();
  
  timer = timerBegin(0, 40000, true);
  timerAttachInterrupt(timer, &onTimer, true);
  timerAlarmWrite(timer, 2000, true);
  timerAlarmEnable(timer);
}

void loop() {
  ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
//  xTaskNotifyWait(NULL, NULL, NULL, portMAX_DELAY);
  digitalWrite(2, !digitalRead(2));
}

**Comment by lbernstone** [comment]
FreeRTOS issues will need to posted to [esp-idf](https://github.com/espressif/esp-idf/issues).  Arduino-esp32 uses those functions from upstream.
