### ISSUE TITLE
[BLE] Any plans for BLE Mesh support on the arduino side?

### ISSUE THREAD

**Issue by marquesn** [espressif/arduino-esp32#2449]
Pretty much as the title says - if there are any future plans of bringing the BLE mesh capability over from the ESP-IDF to the arduino side?

**Comment by chegewara** [comment]
It would be nice, but ble mesh is not supported yet in esp-idf. It is only supported in separate branch.
Yesterday ive been looking at ble mesh and how i could wrap it with c++, but it will take some time, especially i am quite busy. 

Maybe someone else could do it.

**Comment by chanjackie** [comment]
Is there any update on BLE mesh support with Arduino? Or will it have to wait until Espressif releases a stable release with BLE mesh?

**Comment by tedder** [comment]
#1645 went stale, was the same thing.

**Comment by atanisoft** [comment]
@tedder #1645 was for WiFi mesh and not BLE mesh so not the same thing. BLE Mesh does not appear to be available in ESP-IDF in a stable release yet. Until it shows up in a stable release it won't make it to the arduino-esp32 side except through an external library possibly.

**Comment by matt-attack** [comment]
It looks like it has been released now. Is there any chance of this happening? I'd be happy to help if there's something relatively straightforward to do for this.

**Comment by atanisoft** [comment]
@matt-attack is it on esp-idf v3.3 or v3.2? If it is only on v4.x beta it is not ready for use as only stable releases are integrated with arduino-esp32.

**Comment by matt-attack** [comment]
@atanisoft Ah. Didn't realize that there were beta releases, I assumed they were all, well, stable.

**Comment by atanisoft** [comment]
@matt-attack in general they are relatively stable but are not considered stable until a final release is made.

**Comment by TheGreenToaster** [comment]
Looks like 4.0 was released today.

**Comment by atanisoft** [comment]
@TheGreenToaster it will show up soon enough in the v4.0 branch on here

**Comment by faxik** [comment]
Still impossible to compile: I've added details in #3846.
