### ISSUE TITLE
Double support. Quick question

### ISSUE THREAD

**Issue by yo90bosses** [espressif/arduino-esp32#2451]
Does the esp32 in Arduino support 8 byte doubles or is it like with the uno just a 4 byte float?
I'm using a gps and need cm precision using an IMU and I'm having problems with the precision of floats, so it would be good if doubles work.

**Comment by lbernstone** [comment]
```
void setup() {
  Serial.begin(115200);
  Serial.printf("size of double: %d\n", sizeof(double));
  Serial.printf("size of float: %d\n", sizeof(float));
}
void loop() {}
```
<h2>debug</h2>

```
size of double: 8
size of float: 4
```
