### ISSUE TITLE
Update a particular field of JSON array in the SPIFF

### ISSUE THREAD

**Issue by Bhavikjp** [espressif/arduino-esp32#2464]
**Hello,**
I have some queries. I have placed my ESP32 device(spiff uploaded) at a remote place.
Now I need to change the SPIFF data. **Is it possible to update a particular field of JSON array in the SPIFF?**
Example:
**{"Test1":[{"id":"1","Status":"On","StartHr":"0","StartMin":"5","EndHr":"0","EndMin":"10"}]}**
The data i got through Http get request.
If I want to update the StartHr and StartMin, how to change it. Because I didn't find any command to change this.
It's urgent.
**Thanks!!**

**Comment by lbernstone** [comment]
https://www.google.com/search?q=edit+file+in+c%2B%2B

**Comment by me-no-dev** [comment]
not an issue in Arduino
