### ISSUE TITLE
Multiple WifiServer Instances

### ISSUE THREAD

**Issue by St3venAU** [espressif/arduino-esp32#247]
I'm working on a project that necessitates running multiple servers (e.g. telnet and ftp and http, etc). I had no problem with 1, 2 or 3 instances of WifiServer, but when I got to the point where I needed to use 4 instances, suddenly none of the four would work.

[Here's my test sketch](https://gist.github.com/St3venAU/0217b384d4fe5a67a71e4d43844c3734)

In the above code I have commented out the code for the 4th WifiServer, and I am able to telnet in to the first three on ports 23, 24 and 25 just fine. As soon as I un-comment the code for the 4th WifiServer, none of them work any more. It seems that the client is disconnected immediately upon connection to any of them.

Is there a limit on the number of WifiServer instances? I have successfully used more than 4 in the past on the ESP8266, so I would be surprised if this was a technical limitation of the ESP32? Thanks.

**Comment by me-no-dev** [comment]
The number of concurrent server is limited but not to 4 or 3, so this is rather strange... does it break when you just uncomment the lines r does it break when you try to connect to the fourth server?

**Comment by St3venAU** [comment]
All four break as soon as I uncomment server4.begin();
After that I am unable to connect to any of the ports.

**Comment by hcs-svn** [comment]
Same problem here. Only three servers work. On more breaks all of them.

**Comment by St3venAU** [comment]
Any ideas on what may be causing this? It's got me stumped, but what I have found is that WiFiUDP instances also count towards this limit of 3, as does the use of ArduinoOTA. Anything that can be done to get to the bottom of this would be greatly appreciated.

**Comment by me-no-dev** [comment]
Fixed in the latest commit ;) number up from 4 to 10

**Comment by eroom1966** [comment]
Out of interest could you uys share your code for the telnet server ?
I have tried to create the simplest telnet server in the world, at the moment just streaming characters to the client.
[](https://github.com/espressif/arduino-esp32/issues/307)
However, after approx 30-60 mins, there is a disconnect between the server(esp32) and the client(telnet iPad or x86ubuntu)

Having instrumented the code, the WifClient::write reports an errno=104 which is ECONNRESET
I have very similar code running on a RaspberryPi which runs for weeks without an issue, so I am totally lost as to where the issue could be or how to resolve.

If you have working code I would very much like to take a look to see if this fixes the stability of what I am seeing.

E.
