### ISSUE TITLE
Esp-wroom-32 is getting crazy

### ISSUE THREAD

**Issue by PeWos** [espressif/arduino-esp32#248]
Hi, I have a problem with the esp-wroom-32 module, I have flashing the firmware with arduino IDE and now the esp takes strange measurements from sensors and does not do what I have programes in the sketch, the same sketch works correctly with the dev kit from espressif.

**Comment by me-no-dev** [comment]
maybe show some sketch? isn't that wroom module just the esp32 module? The same one that get's put on boards?

**Comment by PeWos** [comment]
I already solved it, it was an error in the connection of the sensor
