### ISSUE TITLE
Guru Meditation with wifi.h

### ISSUE THREAD

**Issue by tomxygen** [espressif/arduino-esp32#2486]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.1
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                    no
Upload Speed:					115200?
Computer OS:                                        MacOS

I have a project based on the ESP32 and a DHT11 sensor that reads the temperature and uploads it to a webpage.
Unfortunately the wifi.h seems to be the responsible for the crash of the board.
This is the error shown in the serial display:

`[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[V][esp32-hal-i2c.c:1442] i2cInit(): num=0 sda=27 scl=26 freq=0
[V][esp32-hal-i2c.c:1643] i2cSetFrequency(): Fifo threshold=3
[V][esp32-hal-i2c.c:1643] i2cSetFrequency(): Fifo threshold=15
Connecting to NETGEAR_11ng
Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40146d40: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstrucGuru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered () 
Guru Meditation Error: Core  1 panic'ed (Guru Meditation Error: Core  1 panic'ed (Guru Meditation Error: Core  1 panic'ed (Unknown reason)
`

I'm not sure how to decode the issue, since mine is kind of different.

```
#include <WiFi.h>
#include <RH_ASK.h>
#include <SPI.h>
#include <DHT.h>
#include <Wire.h>
#include "SSD1306Wire.h"

const char* ssid     = "mySSID";
const char* password = "myPassword";


WiFiServer server(80);
#define DHTPIN 14    
#define DHTTYPE DHT11
DHT dht(DHTPIN, DHTTYPE);

RH_ASK driver(2000, 22, 3, 0);

#define leftButton 13
#define centerButton 25
#define rightButton 32


String ip = "";

SSD1306Wire  display(0x3c, 27, 26);

int insideOrOutside = 0;
int locationSelected = 0;
int isConnected = 0;
int canProceed = 0;
int intHumidity;
int intTemperature;

void setup() {
 Serial.begin(115200);
   WiFi.begin(ssid, password);

driver.init();

dht.begin();
 
display.init();

display.flipScreenVertically();

  pinMode(leftButton, INPUT_PULLUP);
  pinMode(centerButton, INPUT_PULLUP);
  pinMode(rightButton, INPUT_PULLUP);

}

void loop() {

while (isConnected == 0) { 

  
    Serial.print("Connecting to ");
    Serial.println(ssid);
    display.setFont(ArialMT_Plain_10);
    display.drawString(10, 10, "Connecting to:");
    display.setFont(ArialMT_Plain_16);
    display.drawString(3, 30, ssid);
    display.display();
    

    while (WiFi.status() != WL_CONNECTED) {
    
        delay(500);
        Serial.print(".");
        for (int x=40; x<70; x=x+7) {
          display.setPixel(x, 60);
          display.display();
          delay(200);
        }
    }
    display.clear();
    display.display();
    IPAddress(ip) = WiFi.localIP();
    
    display.setFont(ArialMT_Plain_10);
    display.drawString(10, 6, "Wi-Fi is connected");
    Serial.println("WiFi connected.");
    display.setFont(ArialMT_Plain_16);
    String lol = String(WiFi.localIP());
    display.drawString(10, 20, ip.toString());
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());

    Serial.println(ip);
    display.display();
    display.setFont(ArialMT_Plain_10);
    display.drawString(10, 50, "Press OK to continue");
    display.display();    
    
    server.begin();
    isConnected = 1;

  
}


while (canProceed == 0) {
  if (digitalRead(centerButton) == HIGH) {
        Serial.print("Confirm Button\n");
        canProceed = 1; 
        delay(100);
        
}
}

  
  // Reading temperature or humidity takes about 250 milliseconds!
  // Sensor readings may also be up to 2 seconds 'old' (its a very slow sensor)
  intHumidity = dht.readHumidity();
  intTemperature = dht.readTemperature(true); //false = celsius, true = fahreneith
  
  display.clear();

  Serial.print("Temperature: ");
  Serial.print(intTemperature);
  Serial.print("°F    ");
  Serial.print("Humidity: ");
  Serial.print(intHumidity);
  Serial.println("%");


//----------------------INT/EXT-MENU----------------------//

//locationSelected -> 0 = still on the choice menu | 1 = choice has been made
//insideOrOutside -> 0 = inside | 1 = outside

while (locationSelected == 0) {
  intHumidity = dht.readHumidity();
  intTemperature = dht.readTemperature(true);
  wifi(intTemperature, intHumidity);
  
  if (insideOrOutside == 0) {
    
    display.clear();
    display.setFont(ArialMT_Plain_16);
    display.drawString(4, 28, "INSIDE");
    
    for (int y=27; y<47; y++) {
      display.setPixel(1, y);
    }
  
    for (int x=1; x<60; x++) {
      display.setPixel(x, 26);
    }
  
    for (int y=27; y<47; y++) {
      display.setPixel(60, y);
    }
  
    for (int x=1; x<61; x++) {
      display.setPixel(x, 47);
    }
    display.setFont(ArialMT_Plain_10);
    display.drawString(75, 30, "OUTSIDE");
    display.display();
  }

  if (insideOrOutside == 1) {
    intHumidity = dht.readHumidity();
    intTemperature = dht.readTemperature(true);
    wifi(intTemperature, intHumidity);
    display.clear();
    display.setFont(ArialMT_Plain_10);
    display.drawString(4, 30, "INSIDE");

    display.setFont(ArialMT_Plain_16);
    display.drawString(51, 28, "OUTSIDE");
    

    for (int y=26; y<46; y++) {
      display.setPixel(48, y);
    }
  
    for (int x=48; x<127; x++) {
      display.setPixel(x, 26);
    }
  
    for (int y=26; y<47; y++) {
      display.setPixel(126, y);
    }
  
    for (int x=48; x<127; x++) {
      display.setPixel(x, 46);
    }

    display.display();  
  }
  delay(100);

  if (digitalRead(leftButton) == HIGH) {
        Serial.print("Left Button\n");
        insideOrOutside = 0;
        delay(100);
        display.clear();
        display.display();
      }

  if (digitalRead(rightButton) == HIGH) {
        Serial.print("Right Button\n");
        insideOrOutside = 1;
        delay(100);
        display.clear();
        display.display();
      }

   if (digitalRead(centerButton) == HIGH) {
        Serial.print("Confirm Button\n");
        locationSelected = 1;
        delay(100);
        display.clear();
        display.display();
      }
}

while (locationSelected == 1) {
  
  intHumidity = dht.readHumidity();
  intTemperature = dht.readTemperature(true);

  
  if (insideOrOutside == 0) {
   
    display.setFont(ArialMT_Plain_10);
    display.drawString(20, 4, "Internal Sensors");
    display.drawString(1, 30, "Temperature:");
    display.drawString(70, 30, "Humidity:");
    display.setFont(ArialMT_Plain_16);
    display.setColor(BLACK);
    display.fillRect(15, 45, 40, 20);
    display.fillRect(72, 45, 40, 20);
    display.display();
    display.setColor(WHITE);
    display.drawString(15, 45, String(intTemperature) + "°F");
    display.drawString(75, 45, String(intHumidity) + "%");
    display.display();
    delay(100);
    

    if (digitalRead(leftButton) == HIGH) {
        Serial.print("Left Button\n");
        locationSelected = 0;
        delay(100);
        display.clear();
        display.display();
      }

  if (digitalRead(rightButton) == HIGH) {
        Serial.print("Right Button\n");
        locationSelected = 0;
        delay(100);
        display.clear();
        display.display();
      }

   if (digitalRead(centerButton) == HIGH) {
        Serial.print("Confirm Button\n");
        locationSelected = 0;
        delay(100);
        display.clear();
        display.display();
      }
    
  }

  if (insideOrOutside == 1) {
    display.setFont(ArialMT_Plain_10);
    display.drawString(20, 4, "External Sensors");
    display.display();

    if (digitalRead(leftButton) == HIGH) {
        Serial.print("Left Button\n");
        locationSelected = 0;
        delay(100);
        display.clear();
        display.display();
      }

  if (digitalRead(rightButton) == HIGH) {
        Serial.print("Right Button\n");
        locationSelected = 0;
        delay(100);
        display.clear();
        display.display();
      }

   if (digitalRead(centerButton) == HIGH) {
        Serial.print("Confirm Button\n");
        locationSelected = 0;
        delay(100);
        display.clear();
        display.display();
      }
    
  }
  wifi(intTemperature, intHumidity);
  delay(200);
/*
  uint8_t buf[100];
    uint8_t buflen = sizeof(buf);

    if (driver.recv(buf, &buflen)) {
      Serial.println((char*)buf);
    }
    */
  
  }


Serial.println("end");

}

//---------------WIFI FUNCTION---------------------

void wifi(int intTemperature, int intHumidity) {

  WiFiClient client = server.available();
  Serial.println("--- Wi-Fi Breakpoint ---");

  if (client) {
  Serial.println("New connection");
      String currentLine = "";                // make a String to hold incoming data from the client
    while (client.connected()) {            // loop while the client's connected
      if (client.available()) {             // if there's bytes to read from the client,
        char c = client.read();             // read a byte, then
        Serial.write(c);                    // print it out the serial monitor
        if (c == '\n') {                    // if the byte is a newline character

          // if the current line is blank, you got two newline characters in a row.
          // that's the end of the client HTTP request, so send a response:
          if (currentLine.length() == 0) {
            // HTTP headers always start with a response code (e.g. HTTP/1.1 200 OK)
            // and a content-type so the client knows what's coming, then a blank line:
            client.println("HTTP/1.1 200 OK");
            client.println("Content-type:text/html");
            client.println();

            // the content of the HTTP response follows the header:
            client.print("<h1>Current temperature: </h1>" + String(intTemperature) + "&deg;F");
            client.print("<br>");
            client.print(String((intTemperature-32)*5/9) + "&deg;C");
            Serial.print("Temperature on the server");
            Serial.println(intTemperature);
            client.print("<br>");
            client.print("<br>");
            client.print("<h1>Current humidity: </h1>" + String(int(intHumidity)) + "%");
            // The HTTP response ends with another blank line:
            client.println();
            // break out of the while loop:
            break;
          } else {    // if you got a newline, then clear currentLine:
            currentLine = "";
          }
        } else if (c != '\r') {  // if you got anything else but a carriage return character,
          currentLine += c;      // add it to the end of the currentLine
        }


      }
    }
    // close the connection:
    client.stop();
    Serial.println("Client Disconnected.");
  }
  
}
``` `

**Comment by jestebanes** [comment]
Same trouble here, but with different code

**Comment by atanisoft** [comment]
The original poster issue doesn't appear to have anything to do specifically with wifi. The first error in the stack is pointing to an ISR doing something it shouldn't be doing which flash is being accessed. Most likely it is in the DHT or RH_ASK library that is being compiled into the app. The SSD1306 library uses I2C and from the include name looks like the same library I use and it doesn't use an ISR internally.

Try commenting the driver.init() line and see if the issue goes away. If so, open an issue against that library. Similarly for the DHT library..

**Comment by tomxygen** [comment]
@atanisoft thank you for spotting out the issue.
Indeed, removing the driver.init() in my code, the issue goes away, while removing dht.begin() does't fix it.

**Comment by atanisoft** [comment]
@tomxygen I'd suggest closing this issue and opening a new one for the maintainer of the RH_ASK library (not even sure what that is!).

**Comment by tomxygen** [comment]
@atanisoft I’ll close the issue soon.
RH_ASK is a sub-library of the RadioHead library that deals with wireless communication.
ASK stands for radio amplitude shifting, and I use it with this module: 
https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.uw29VZi4mRZhD27-ldb3aAHaE6%26pid%3D15.1&f=1

**Comment by atanisoft** [comment]
from what I can read of the RH_ASK library, it is not specifically written to support the ESP32 (though it has support for the esp8266) so it will need to be updated to support the ESP32.
