### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by williamesp2015** [espressif/arduino-esp32#249]
It would be very nice if ESP32 provide websocket support like ESP8266 (https://github.com/Links2004/arduinoWebSockets/tree/master/examples)

**Comment by me-no-dev** [comment]
not an issue though :) maybe ping @Links2004 ?

**Comment by Links2004** [comment]
the port isnt that hard since the WiFiClient and WiFiServer interface is likely the same,
but I currently not on a ESP32 for testing.
In theory its only some ```ifdefs``` in 
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h

**Comment by me-no-dev** [comment]
@Links2004 nice to see you again mate ;) it's been a while :)

**Comment by Links2004** [comment]
Linking issue:
https://github.com/Links2004/arduinoWebSockets/issues/161

@me-no-dev yes, loots todo right now, and unfortunately less to no time for all the open source projects where  I working on.

**Comment by vindolin** [comment]
@Links2004 I gladly send you one :)
