### ISSUE TITLE
WiFiClientSecure gets stuck, when send buffers get full

### ISSUE THREAD

**Issue by everslick** [espressif/arduino-esp32#2494]
When we send too fast (faster then the TLS connection allows), eventually the send buffers will fill up and write() returns 0 (indicating, that nothing could be written). Normally this means we just retry until all data is sent, but in this case the TLS socket never recovers from this condition (buffers stay full). The only thing we can do is close the socket and go home.

**Comment by everslick** [comment]
still valid, don't close.

**Comment by everslick** [comment]
https://github.com/esp8266/Arduino/pull/6104

could be the same bug as on ESP8266. @me-no-dev ?

**Comment by everslick** [comment]
still relevant, don't close.

**Comment by everslick** [comment]
still relevant, don't close.

**Comment by everslick** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp#L183

My guess is, when `send_ssl_data()` returns an error we silently close the socket, and do not inform the caller. write should return int, but returns size_t.

**Comment by everslick** [comment]
@me-no-dev what do you think?

**Comment by everslick** [comment]
Doing more tests with idf-release/v4.2 shows the bug still present. So this could very easily be a issue with WiFiClientSecure. It hink this is serious and worth looking into before next stable release. What can I do to bring this foward besides the what I commented above?

**Comment by sansillusion** [comment]
wow I feel bad for you, not even a single aknowledgment of you issue and you have to fight the stale bot to keep it open. I hope you get the attention you need on this issue, unfortunately I can't help.
