### ISSUE TITLE
Arduino.h - missing defines

### ISSUE THREAD

**Issue by hcs-svn** [espressif/arduino-esp32#25]
Most of the defines that we have in Arduino AVR and in the Arduino core for ESP8266 are missing here.

Some examples: lowByte, highByte, bitRead, bitSet, bitClear, bitWrite, LSBFIRST, MSBFIRST, ...

**Comment by me-no-dev** [comment]
yes, thanks for pointing it out. I'll add them

**Comment by me-no-dev** [comment]
done :) https://github.com/espressif/arduino-esp32/commit/29feaaa2d04308b9deb9f1bf009e3af1bf3763a9
