### ISSUE TITLE
Using the RX0 TX0 to communicate with the Arduino UNO

### ISSUE THREAD

**Issue by DeltaVetal26** [espressif/arduino-esp32#2500]
Hi,

I use RX0 TX0 for UART ESP32 <-> Arduino UNO communication.
For levels (3.3 V - 5 V) I use a BSS138 based transistor.

Which Serial should I install to work with the RX0 TX0? (I thought that Serial0, but this does not exist, but simply Serial sends data to the USB serial port.)

**Comment by baaridunnasr** [comment]
Which board are you using? Is your transistor configuration correctly switching from 3V3 to 5V?
I'd suggest you to use a bi directional level shifter. It's better for debugging if you don't have to worry about so many components.

Serial0 does not exist.

The UART(RX0 and TX0) can be used using Serial.begin(<your baud rate>);

Serial1 and Serial2 are the other two UART controllers present.
