### ISSUE TITLE
Connecting Neurosky with esp32 via bluetooth

### ISSUE THREAD

**Issue by misha11720** [espressif/arduino-esp32#2502]
I am trying to connect esp32 with Neurosky. I don't know how to pair my mindwave mobile with esp32. Please help.

**Comment by misha11720** [comment]
I am using arduino IDE as well

**Comment by misha11720** [comment]
Is there anyone to help????

**Comment by lbernstone** [comment]
This forum is for issues with the arduino-esp32 code base.  General questions should be directed to esp32.com, or maybe linkedin if you want a developer to write code for you.
