### ISSUE TITLE
Problem with getting mac address after commit "Major IDF and Arduino Update"

### ISSUE THREAD

**Issue by An00bIS47** [espressif/arduino-esp32#251]
Hi,

first of all thanks for the hard work you put into this :)

Sadly, this commit "Major IDF and Arduino Update" 1d759380a6ff0d201145658bf54c423ffbef4c7b  broke my app and i am trying to break down the issues. It seems this commit changed some things in the Wifi and Preferences classes? 

For example, I am trying to get an unique device ID via the mac address. this command worked prior the commit and i got the mac address.

```
#include <Arduino.h>
#include <WiFi.h>

void setup()
{

	Serial.begin(115200);
	uint8_t mac[6];
	
	WiFi.macAddress(mac);

	char deviceID[12 + 1];
	sprintf(deviceID, "%02x%02x%02x%02x%02x%02x", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);

	Serial.print("deviceID: ");
	Serial.println(deviceID);
}


void loop() {
}
```
But afterwards the mac address is filled with 0 and this message appears in the serial monitor:
```
￿E (183) wifi: esp_wifi_get_mac 1171 wifi is not init
deviceID: 000000000000
```

Maybe you can help me with this? Thank you!

**Comment by me-no-dev** [comment]
before that commit we had to init phy and wifi radio prior to starting the arduino code. Now we can start/stop WiFi and BLE at will so you need to start WiFi in some sort. Calling ```WiFi.mode(WIFI_MODE_STA)``` will do the trick.
