### ISSUE TITLE
CameraWebServer - Which file sends the "Start Stream" button text to Client Browser?

### ISSUE THREAD

**Issue by CameraWebServer** [espressif/arduino-esp32#2512]
### Hardware:
Board:							?ESP32 Dev Module? ?node32? ?ttgo_lora?
Core Installation version:			?1.0.0? ?1.0.1-rc4? ?1.0.1? ?1.0.1-git?
IDE name:						Arduino IDE
Flash Frequency:					?40Mhz?
PSRAM enabled:                                    ?no? ?yes?
Upload Speed:					?115200?
Computer OS:                                        Windows 10

### Description:
Want to Add/Delete some buttons on the original CameraWebServer program.
Also want to Add/Delete/Change some Words/Options that shows in the Client Browser.
So, Which file contains the "Get Still", "Start Stream", "Enroll Face" instructions - that is sent - to the Client Browser?

**Comment by me-no-dev** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/Camera/CameraWebServer/camera_index.h
It's gzipped and turned into bytes. You can extract it from your browser once you open it there and then edit, gzip and turn into bytes again. I use this to turn it into bytes: https://gist.github.com/me-no-dev/f137a950ce6dedb641d427d8db6355d2
