### ISSUE TITLE
Any compatibility of deep-sleep with Time.h?

### ISSUE THREAD

**Issue by Jorfuenst** [espressif/arduino-esp32#2513]
I need to report a current time every moment (RTC or NTP), include in deep-sleep moments. I must to use Time.h library (Paul Stroffregen) for that.

Thanks.

**Comment by lbernstone** [comment]
Short answer, no.  Long answer, deep sleep only has access to the [ULP](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/ulp.html).  You would need to write something that could be compiled to ULP assembly.
