### ISSUE TITLE
missing esptool.exe

### ISSUE THREAD

**Issue by ouki-wang** [espressif/arduino-esp32#252]
the lastest script using esptool.exe。but i can not find it

**Comment by me-no-dev** [comment]
run get.exe. It's explained in the guide

**Comment by eric-schleicher** [comment]
This should be re-opened since running get.exe doesn't work for many since the SSL cert make it not work on system with good ssl hygene.

Is there a workaround?

**Comment by shirish47** [comment]
hey, how do I get esptool.exe? it only has esptool.py and I get esptool.exe does not exist in windows

**Comment by beegee-tokyo** [comment]
In the [Wiki](https://desire.giesecke.tk/index.php/2018/04/02/get-exe-get-py-fails-to-download-required-files/) I listed all download links including for esptool.exe

**Comment by flywire** [comment]
Very poor process, [wiki](https://desire.giesecke.tk/index.php/2018/04/02/get-exe-get-py-fails-to-download-required-files/) links to outdated software. Also see https://github.com/espressif/esptool/issues/181#issuecomment-508980616
