### ISSUE TITLE
Using WiFiClientSecure and doing a connect sometimes locks up (stops)

### ISSUE THREAD

**Issue by IraSch** [espressif/arduino-esp32#2523]
### Hardware:
Board:							Adafruit ESP32 Feather
Core Installation/update date:			not sure, 
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                          no
Upload Speed:						921600
Computer OS:                                            Windows 7

### Description:

Sometimes the following statement never returns control: 

` if (!client.connect("api.scriptrapps.io",httpPort) {
   // more code here
}`

It usually works, but sometimes never returns control. When it fails to return control, it will always be on the first attempt after the project starts. When it works, it will continue to work indefinitely. 

Connection to Wifi is good and returns a valid IP address. 

Under what conditions will it fail to return control?

**Comment by atanisoft** [comment]
@IraSch the connect call is a blocking call and will block until successful connection to the remote host/port. Recently however a timeout has been introduced for connect so it should return control as expected with a connect failure type response.
