### ISSUE TITLE
WPS support?

### ISSUE THREAD

**Issue by dalbert2** [espressif/arduino-esp32#253]
I am new to arduino-esp32 so I apologize if this is a dumb question:
Is there an ESP32 analog to WiFi.beginWPSConfig()  ?
If not, is there  away to include and use idf library functions (e.g. esp_wifi_wps_enable(WPS_TYPE_PBC);) ?

I'd like to step up from the ESP8266 to the ESP32 but I need WPS support.

Thanks to anyone who can point me in the right direction!

**Comment by copercini** [comment]
@Raienryu97 Implemented it here https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi/examples/WPS =)
