### ISSUE TITLE
CameraWebServer: Changing 192.168.1.199, when using many ESP32-Camera boards?

### ISSUE THREAD

**Issue by CameraWebServer** [espressif/arduino-esp32#2532]
Use Arduino IDE.
CameraWebServer works 100%.

When using 2+ ESP32-Camera boards on the same WiFi/Network, 
how/where do we change the //192.168.1.199 on each board?

We need more info on when and how to change the //192.168.1.199.

**Comment by me-no-dev** [comment]
:D change what? Why is your nickname "CameraWebServer"? Did you make an account just to ask this?

**Comment by lbernstone** [comment]
It gets the address from DHCP
