### ISSUE TITLE
Cannot find ESP32 on WireScanner

### ISSUE THREAD

**Issue by MattLogue** [espressif/arduino-esp32#2534]
### Hardware:
Board:							?ESP32 Dev Module? ?node32? ?ttgo_lora?
Core Installation version:			?1.0.0? 
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                    ?no? ?yes?
Upload Speed:					?115200?
Computer OS:                                        Windows 8.1

### Description:
Why can't I get Wire to work on either the ESP8266 or ESP32? I'm using an Uno wireScanner and it only finds the LCD attached. Does not reveal an address for the ESP.

I tried:
Adding a Level Shifter
Trying pins 4/5, 21/22, 16/17
Trying multiple Wire Libraries
Flipping SDA and SCL
Disconnecting the LCD

Still no response from the ESP modules.

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Wire.h>
//#include <PolledTimeout.h>

#define SDA_PIN 21
#define SCL_PIN 22
const int16_t I2C_MASTER = 0x42;
const int16_t I2C_SLAVE = 0x08;

void setup() {
  Serial.begin(115200);  // start serial for output
  Wire.begin(SDA_PIN, SCL_PIN, I2C_MASTER);        // join i2c bus (address optional for master)
}

void loop() {
}
### Debug Messages:
```
15:20:44.394 ->  Scanning I2C Addresses
15:20:44.394 -> .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 
15:20:44.394 -> .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 
15:20:44.394 -> .. .. .. .. .. .. .. 27 .. .. .. .. .. .. .. .. 
15:20:44.394 -> .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 
15:20:44.394 -> .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 
15:20:44.428 -> .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 
15:20:44.428 -> .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 
15:20:44.428 -> .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 
15:20:44.428 -> Scan Completed, 1 I2C Devices found.
15:20:44.428 -> 
15:20:44.428 -> Discovering eeprom sizes 0x50..0x57
15:20:44.529 -> 0x50: Not Present.
15:20:44.632 -> 0x51: Not Present.
15:20:44.735 -> 0x52: Not Present.
15:20:44.837 -> 0x53: Not Present.
15:20:44.938 -> 0x54: Not Present.
15:20:45.041 -> 0x55: Not Present.
15:20:45.109 -> 0x56: Not Present.
15:20:45.212 -> 0x57: Not Present.

**Comment by lbernstone** [comment]
Arduino-esp32 does not have I2C slave mode yet, and it certainly will not be the default behavior.  BTW, the third parameter of Wire::begin is the frequency.
