### ISSUE TITLE
esp32-hal-misc.c: 164:5: error: unknown type name 'esp_ota_img_states_t

### ISSUE THREAD

**Issue by arnold-b** [espressif/arduino-esp32#2545]
Freshly installed. can not compile

### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.2rc
IDE name:						VMicro
Flash Frequency:					80
PSRAM enabled:                                    ?no? ?
Upload Speed:					?115200?
Computer OS:                                        ?Windows 10?

Error compiling core
esp32-hal-misc.c: In function initArduino
Build failed for project 'rollo'
 
esp32-hal-misc.c: 164:5: error: unknown type name 'esp_ota_img_states_t
   esp_ota_img_states_t ota_state
 
esp32-hal-misc.c: 166:26: error: 'ESP_OTA_IMG_PENDING_VERIFY' undeclared (first use in this function)
   if (ota_state == ESP_OTA_IMG_PENDING_VERIFY) {
esp32-hal-misc.c:166: note  each undeclared identifier is reported only once for each function it appears in

**Comment by PaulEverblix** [comment]
Hello !

I'm having the same issue as you. Working with the Arduino Core for ESP32 on PlatformIO, I have compiling errors.
When creating a new project, it compiles with no problem.
However, when I enable the rollback feature (implemented in the 1.8 release of the core), I get the same errors as you.
To enable it, I alter the `.platformio\packages\framework-arduinoespressif32\tools\sdk\include\config\sdkconfig.h` file, adding `#define CONFIG_APP_ROLLBACK_ENABLE`
It appears that the files in `.platformio\packages\framework-arduinoespressif32\tools\sdk\include\bootloader_support` are not the latest and do not include the mandatory classes and enums.

OTA works fine in 1.7, but do lack the rollback feature, that I need.
Have you found a way to avoid the problem and get your code to compile ?
Thanks a lot.
