### ISSUE TITLE
Many MBEDTLS Errors on comilation

### ISSUE THREAD

**Issue by arnold-b** [espressif/arduino-esp32#2546]
check_config.h: 411:2: error: #error "MBEDTLS_PLATFORM_STD_CALLOC defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_CALLOC defined, but not all prerequisites"
 
check_config.h: 415:2: error: #error "MBEDTLS_PLATFORM_STD_CALLOC defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_CALLOC defined, but not all prerequisites"
 
check_config.h: 419:2: error: #error "MBEDTLS_PLATFORM_STD_FREE defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_FREE defined, but not all prerequisites"
 
check_config.h: 424:2: error: #error "MBEDTLS_PLATFORM_STD_EXIT defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_EXIT defined, but not all prerequisites"
 
check_config.h: 430:2: error: #error "MBEDTLS_PLATFORM_STD_TIME defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_TIME defined, but not all prerequisites"
 
check_config.h: 435:2: error: #error "MBEDTLS_PLATFORM_STD_FPRINTF defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_FPRINTF defined, but not all prerequisites"
 
check_config.h: 440:2: error: #error "MBEDTLS_PLATFORM_STD_PRINTF defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_PRINTF defined, but not all prerequisites"
 
check_config.h: 445:2: error: #error "MBEDTLS_PLATFORM_STD_SNPRINTF defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_SNPRINTF defined, but not all prerequisites"
 
esp_config.h:2665: In file included from
net_sockets.h:30: from
net.h:28: from
ssl_client.h:8: from
WiFiClientSecure.h:26: from
WiFiClientSecure.cpp:21: from
 
check_config.h: 411:2: error: #error "MBEDTLS_PLATFORM_STD_CALLOC defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_CALLOC defined, but not all prerequisites"
 
check_config.h: 415:2: error: #error "MBEDTLS_PLATFORM_STD_CALLOC defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_CALLOC defined, but not all prerequisites"
 
check_config.h: 419:2: error: #error "MBEDTLS_PLATFORM_STD_FREE defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_FREE defined, but not all prerequisites"
 
check_config.h: 424:2: error: #error "MBEDTLS_PLATFORM_STD_EXIT defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_EXIT defined, but not all prerequisites"
 
check_config.h: 430:2: error: #error "MBEDTLS_PLATFORM_STD_TIME defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_TIME defined, but not all prerequisites"
 
check_config.h: 435:2: error: #error "MBEDTLS_PLATFORM_STD_FPRINTF defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_FPRINTF defined, but not all prerequisites"
 
check_config.h: 440:2: error: #error "MBEDTLS_PLATFORM_STD_PRINTF defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_PRINTF defined, but not all prerequisites"
 
check_config.h: 445:2: error: #error "MBEDTLS_PLATFORM_STD_SNPRINTF defined, but not all prerequisites"
   #error "MBEDTLS_PLATFORM_STD_SNPRINTF defined, but not all prerequisites"
Error compiling libraries

OS: Windows 10 
VMicro with Visual Studio

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
