### ISSUE TITLE
Missing rtcUserMemoryWrite and read 

### ISSUE THREAD

**Issue by arnold-b** [espressif/arduino-esp32#2551]
Hello in ESP8266 there are function like ESP.rtcUserMemoryWrite and also read.
or getResetInfo
 Exist this function also in esp32 ?

Thanks

**Comment by Onno-Dirkzwager** [comment]
I ran into the same problem and started using [preferences](https://github.com/espressif/arduino-esp32/blob/master/libraries/Preferences/examples/StartCounter/StartCounter.ino) instead.
