### ISSUE TITLE
Can i add my own partition scheme

### ISSUE THREAD

**Issue by arnold-b** [espressif/arduino-esp32#2553]
Hello, can i add my own Additional partition scheme ?. 
I tried to add in the board conf and made my own .csv but i still can not see it 

I know i need to change on eache chain update. for now i just changed the default

Thanks

**Comment by beegee-tokyo** [comment]
Maybe this helps.
Step by step:
[Change partition size (Arduino IDE)](https://desire.giesecke.tk/index.php/2018/04/20/change-partition-size-arduino-ide/)

**Comment by iwanraflis** [comment]
Hi I am currently new. But I managed to add a new partition earlier by adding some stuffs in the boards.txt

For example:

![image](https://user-images.githubusercontent.com/48351044/54022662-4a0ee980-4193-11e9-8a48-c5026b4a0d86.png)

Result:
![image](https://user-images.githubusercontent.com/48351044/54022749-86424a00-4193-11e9-8fcd-cd9447460db8.png)

Make sure you edit the correct config. I am using EPS32 Dev  Module. So i add some new config to **esp32.menu.PartitionScheme**
Lets say if you are using esp32 wrover, they you have to add new config too **esp32wrover.menu.PartitionScheme**
Hope this helps
