### ISSUE TITLE
serial.printf ("   %s\n,uri()) crash the system

### ISSUE THREAD

**Issue by arnold-b** [espressif/arduino-esp32#2562]
crash the system:	
Serial.printf("WebserverClass  HandleServerCall: %s\n",uri().c_str());
or 
Serial.printf("WebserverClass  HandleServerCall: %s\n",uri());

	
This works
Serial.print("WebserverClass  HandleServerCall: ");
	Serial.println(uri());

ESP32 Dev Module
Core Installation version:	?1.0.1? 
IDE name:	?Arduino I
Flash Frequency:	?40Mhz?
 PSRAM enabled: ?no? 
Upload Speed:	?115200? 
Computer OS: ?Windows 10?

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/tree/master/.github/ISSUE_TEMPLATE
