### ISSUE TITLE
wrong pin definition for M5CAM

### ISSUE THREAD

**Issue by PepeTheFroggie** [espressif/arduino-esp32#2565]
This is for the M5CAM sold from banggood for $14. There seem to be a lot of different versions with different pin config from M5STACK. See here:
https://camo.githubusercontent.com/52bae30bf9fcea048318f841481ad7b88db9f499/68747470733a2f2f6d35737461636b2e6f73732d636e2d7368656e7a68656e2e616c6979756e63732e636f6d2f696d6167652f6d352d646f63735f7461626c652f63616d6572615f636f6d70617269736f6e2f43616d65726150696e436f6d70617269736f6e5f656e2e706e67

arduino-esp32/libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino
      
after 
#elif defined(CAMERA_MODEL_M5STACK_PSRAM)
wrong:
#define Y2_GPIO_NUM       32
should be:  
#define Y2_GPIO_NUM       17

**Comment by sanchosk** [comment]
Had the same issue, took me 2 hours to identify the problem :) And when reporting it, I found this comment :)
