### ISSUE TITLE
Using Serial1 causes fault

### ISSUE THREAD

**Issue by yukini3** [espressif/arduino-esp32#258]
With the sdk version of v2.0-rc1-265-gcc7fd3c, using Serial1 causes fault.

Code:
`
HardwareSerial Serial1(1);

void setup()
{
	Serial.begin(115200);
	Serial.print("*** ESP-IDF SDK Version="); 
	Serial.println(ESP.getSdkVersion());

	Serial1.begin(115200);
}

void loop()
{
	Serial.println("Loop");
	delay(2000);
}
`

Output:
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0x00
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0008,len:8
load:0x3fff0010,len:2016
load:0x40078000,len:7780
ho 0 tail 12 room 4
load:0x40080000,len:252
entry 0x40080034
*** ESP-IDF SDK Version=v2.0-rc1-265-gcc7fd3c
Guru Meditation Error of type LoadProhibited occurred on core  1. Exception was unhandled.
Register dump:
PC      : 0x40080b80  PS      : 0x00060830  A0      : 0x800d0aad  A1      : 0x3ffca260  
A2      : 0x0000000a  A3      : 0x00000002  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0xff000000  A8      : 0x3f401304  A9      : 0x03999e21  
A10     : 0x0008e09f  A11     : 0x00000058  A12     : 0x00000000  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000017  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x0008e09f  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

Backtrace: 0x40080b80:0x3ffca260 0x400d0aad:0x3ffca280 0x400d0d6e:0x3ffca2a0 0x400d07f8:0x3ffca2d0 0x400d0679:0x3ffca300 0x400e1f7a:0x3ffca320

CPU halted.

Something wrong with my code? Please advise.
Thanks!

**Comment by me-no-dev** [comment]
Serial1 runs on pins 9 an 10 and those are attached to QIO enabled Flash, so you need to run it on other pins, else you break your flash ;)
