### ISSUE TITLE
Brownout voltage level set to 2.8Volt

### ISSUE THREAD

**Issue by mzafar3** [espressif/arduino-esp32#2580]
### Hardware:
Board:							        ESP32 Dev Module
Core Installation/update date:			8/jun/2016
IDE name:							Arduino IDE
Flash Frequency:					        80Mhz
PSRAM enabled:                                             no
Upload Speed:					        115200
Computer OS:                                                  Windows 10

### Description:

I want to set ESP32 Brown out reset voltage 2.8Volt, instead of by default 3.3Volt.

I can disable the brown out detection succesfully using below in setup. but how can set volate to 2.8volt when i am using module as a BLE in our application.

#include "soc/soc.h"
#include "soc/rtc_cntl_reg.h"

void setup() {
  WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0); //disable brownout detector
  .......
}

Thanks in advance!!

**Comment by lbernstone** [comment]
That is controlled by a CONFIG_ variable, so you would need to compile [arduino as an esp-idf component](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md).  However, it looks to me like it is set at 2.43V in the default arduino sdkconfig.
