### ISSUE TITLE
BLE discover & connect timing with android app

### ISSUE THREAD

**Issue by mzafar3** [espressif/arduino-esp32#2595]
### Hardware:
Board:				          			ESP32 Dev Module
Core Installation/update date:			6/jun/2016
IDE name:							Arduino IDE
Flash Frequency:					        40Mhz
PSRAM enabled:                                           no
Upload Speed:						115200
Computer OS:                                                Windows 10

### Description:

I have a issue in ESP32 BLE Connection time with my custom android BLE app. 

ESP32 takes generally 1 sec to discover and connect With android BLE app.

But if I am disabling the Brown OUT detection using below code in my setup.

#include "soc/soc.h"
#include "soc/rtc_cntl_reg.h"

void setup() {
WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0); //disable brownout detector
.......
}

Then ESP32 BLE Connection with android app slightly increased, it takes 3 - 4 sec to discover and connect with android app.

If I am reverse the changes in code or comment the brown out detection disabled line, it takes again 1 sec for discover and connect.

I don't why it takes time to discover & connect with app, if I am disabled the BROWN OUT DETECTION.

Thanks in advance!

Regards
MD

**Comment by copercini** [comment]
Why are you disabling the brown out detector?
