### ISSUE TITLE
ESP32 + APA102 Question

### ISSUE THREAD

**Issue by Edris89** [espressif/arduino-esp32#2599]
Hi there,

I am doing a project with the ESP32 and the APA102 SMD RGB LEDs.
My project is about a text logo its called VUSAM, 5 letters.

I wanted to fill those letters with SMDs and have each letter it's own channel so that it could have different effects for each letter.

I understand that each letter would have it's own data pin.
But the APA102 has also a clock pin.
And this is where it's getting a bit confusing for me.

I have some couple of questions.

1. Which gpio pins can I use for the data pins for each of the 5 channels?
2. Must I also have 5 different clock pins for each channel? Or can I connect all those clocks with one clock pin?
3. Question about question 2. What's the difference between using 5 different clock pins or 1 clock pin for all the 5 channels.
4. Which pin or pin's can I use for the clock pin.
5. Can I use the ESP32 pins to drive the APA102 smd leds with 3.3V Logic? Or must this be 5V logic?

Thanks in advance.

**Comment by PureTek-Innovations** [comment]
Use FastLED, see "Getting four hardware SPI lines for the APA102 out of the Teensy 3.0/3.1/3.2" on this page https://github.com/FastLED/FastLED/wiki/SPI-Hardware-or-Bit-banging.
It shows you how to use a smaller number of pins to drive clock and data, ignore the references to a Teensy and just choose a selection of ESP32 pins. I've used this trick for 4 strips of APA102Cs on an ESP32, there's no reason why you can't expand it to eight strips.
ESP32 is now a supported MCU
For FastLED support go here https://www.reddit.com/r/FastLED/
