### ISSUE TITLE
arduino API incompatibility for BSSID + inverted array for both macAddress and BSSID

### ISSUE THREAD

**Issue by aster94** [espressif/arduino-esp32#2613]
working in a project i noted that the WIFI api is different and i thought to open an issue if you would like to fix it, all the resources are here:

BSSID official API
site: https://www.arduino.cc/en/Reference/WiFiBSSID 
code: https://github.com/arduino-libraries/WiFi/blob/master/src/WiFi.cpp#L189

ESP32
BSSID: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiSTA.cpp#L521 and https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiScan.cpp#L234

solution: something like you did for the [macAddress](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiSTA.cpp#L416) where there are two function with the same name, so if i pass a parameter to macAddress i will fill the array if not i will receive a String:
```cpp
uint8_t* WiFiSTAClass::macAddress(uint8_t* mac)
{
    if(WiFiGenericClass::getMode() != WIFI_MODE_NULL){
        esp_wifi_get_mac(WIFI_IF_STA, mac);	
    }
    else{
        esp_read_mac(mac, ESP_MAC_WIFI_STA);
    }
    return mac;
}

String WiFiSTAClass::macAddress(void)
{
    uint8_t mac[6];
    char macStr[18] = { 0 };
    if(WiFiGenericClass::getMode() == WIFI_MODE_NULL){
        esp_read_mac(mac, ESP_MAC_WIFI_STA);
    }
    else{
        esp_wifi_get_mac(WIFI_IF_STA, mac);
    }
    sprintf(macStr, "%02X:%02X:%02X:%02X:%02X:%02X", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    return String(macStr);
}
```

The same could be done with the BSSID, if i pass a parameter (which now is not possibile while it should be) i will fill the array; and if i just call I will get a String. Also this will make the behaviour between BSSID and macAddress the same while now is not.

EDIT: also note that arduino functions return an array which have to be read from 5 to 0, see [here](https://github.com/arduino-libraries/WiFiNINA/blob/cc0563ec08099768e1b769af4821324722c6b7fc/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino#L127-L138) while esp32 from 0 to 5 bringing to more incompatibility of code

**Comment by aster94** [comment]
@me-no-dev would you like to accept a PR with a fix to make it compatible with the arduino API?

**Comment by aster94** [comment]
Just commenting to suggest to reopen it

**Comment by atanisoft** [comment]
@aster94 feel free to reopen the issue and send in a PR for it.
