### ISSUE TITLE
ESP-IDF SDK need update ?

### ISSUE THREAD

**Issue by asetyde** [espressif/arduino-esp32#2628]
I register many bugs on WiFi and other peripherals that are closed with upgrade of SDK beta 3.2 b3, at now on 1.0.2 rc1 we use v3.3-beta1-506-gebdcbe8c6 , I not able a direct check  ,  is possible upgrade manually on my code or i must wait ? 

About new realese, I think you wait 3.3 sdk stable to update ? I correct ? 

At now we use more thank 2000 esp32 chips for our device but as esp8266 firmware stability is not so stable, complicating job of developer work on big scale use.

**Comment by asetyde** [comment]
@me-no-dev  do you update to  v3.2 286202c ESP-IDF Release , I need this to resolve a bug on my system

**Comment by asetyde** [comment]
I see commit on 3.2 , perfect. Thanks

**Comment by me-no-dev** [comment]
yup 3.2 final is almost ready :) That means that 1.0.2 is also around the corner, but be aware that after release, I will sync master again with IDF master, so you might want to stick to 1.0.2 as a stable version :)
