### ISSUE TITLE
SimpleWiFiServer with high data loss rate

### ISSUE THREAD

**Issue by copercini** [espressif/arduino-esp32#263]
Using SimpleWiFiServer with CSS and html some lines are just not printed by client. 

For test I adapted the SimpleWiFiServer example for print a list from 0 to 999, and it have a considerable amount of missing data, here is the test code:
``` c
            client.println("0 to 999 list<br>");
            for (int i = 0; i < 1000; ++i){
              client.print(i);
              client.println("<br>");         
            }
```

Some errors:
![screenshot_2](https://cloud.githubusercontent.com/assets/21266776/23917159/36b254fe-08cd-11e7-8df9-1d83e528f0bc.png)

screenshot2:
![screenshot_1](https://cloud.githubusercontent.com/assets/21266776/23917158/36ae6768-08cd-11e7-9fee-559baaf66ddb.png)

**Comment by copercini** [comment]
Increasing ` #define WIFI_CLIENT_SELECT_TIMEOUT_US (100000)` to 1000000 in libraries/WiFi/src/WiFiClient.cpp fix this issue. 

Maybe change this constant just for WiFi Server or allow user set it on arduino IDE code solve it.

**Comment by me-no-dev** [comment]
Done and thanks :)
