### ISSUE TITLE
HTTPClient getString halts if getSize is equal -1

### ISSUE THREAD

**Issue by alexodus** [espressif/arduino-esp32#2667]
the condition inside getString

` if(_size) {`

when _size==-1, is incorrect

**Comment by Jeroen88** [comment]
If no _Content-Length_ header is sent, _size seems to be -1 indeed. But more changes are needed than just checking for _size == -1.

**Comment by me-no-dev** [comment]
@alexodus very short report mate... what happens, when it happens, why it happens, where it happens (line number or something). Give some info here :P

**Comment by alexodus** [comment]
@me-no-dev I'm sorry for the short report! :P
When I call getString in a successfull request to Google IoT Core http bridge, the wemos lolin32 with Arduino ESP32 1.0.1 hangs / halts without reset itself. 

```
 if (httpCode == HTTP_CODE_OK || httpCode == HTTP_CODE_MOVED_PERMANENTLY) {
            if  (https.getSize()>0) {        
              String payload = https.getString(); // <- halt
              Serial.println(payload);
            }
          } 

```

I have to check the size of response:

```
 if (httpCode == HTTP_CODE_OK || httpCode == HTTP_CODE_MOVED_PERMANENTLY) {
            if  (https.getSize()>0) {        
              String payload = https.getString();
              Serial.println(payload);
            }
          } 

```

In my opinion it's a bad behaviour to permit the halt with _size==-1

**Comment by me-no-dev** [comment]
seems like a viable fix :) how about you PR this line?

**Comment by me-no-dev** [comment]
1.0.2 will come out (today?) so you might want to hurry :D

**Comment by alexodus** [comment]
> seems like a viable fix :) how about you PR this line?

no, it's no a fix, it's a simple control in my code

**Comment by alexodus** [comment]
> 1.0.2 will come out (today?) so you might want to hurry :D

I've another  issue, much more important,  about HTTPClient in arduino esp32 version 1.0.2 rc2 (in 1.0.1 is ok). I hope to submit it today! :P
