### ISSUE TITLE
How do I make a GPIO stably floating?

### ISSUE THREAD

**Issue by philip100** [espressif/arduino-esp32#2679]
### Hardware:
Board:							ESP32 DevKitC V.4
Core Installation version:			(recent??)
IDE name:						Arduino IDE (1.9.0)
Flash Frequency:				        80Mhz
PSRAM enabled:                                      false
Upload Speed:				        921600
Computer OS:                                          Mac OSX

### Description:

I'm struggling with GPIO's.

I'm using Pololu DRV8834 stepper driver board, which supports 1/32 step resolution. In order to achieve this, I have to drive its M0 pin "floating". It's "floating" by default, but I'd like to be able to change microstepping resolution on the fly - therefore I have to use one of the ESP32 board GPIO's to drive it either "HIGH", "LOW", or "INPUT_PULLUP" (floating)

So, after some tests I believe that the GPIO's I use (as I have only those left) are not able to keep stable floating state:

 - GPIO 4 (I can't get it floating at all)
 - GPIO 16
 - GPIO 17 

My stepper motor works in 1/32 resolution for a while, then its being move jerky / unstable. When I disconnect GPIO that drives MS0 to "INPUT_PULLUP", the movement gets stable again. 

I've tried the same with "INPUT HIGH" and "INPUT LOW" - the same results, it's stable just for a few seconds...

How do I make a GPIO **TRUELY** floating?  And which GPIO's are the best for?

### Sketch:  
irrevelant I think...

### Debug Messages:
none...

**Comment by Jeroen88** [comment]
Did you try pin mode INPUT?
