### ISSUE TITLE
ICACHE_RAM_ATTR question

### ISSUE THREAD

**Issue by ccfoo242** [espressif/arduino-esp32#268]
Hello,
I'm trying to get EspSoftwareSerial working (https://github.com/plerup/espsoftwareserial) and it doesn't look like ICACHE_RAM_ATTR is defined anywhere. 

I changed it from including "gpio.h" to <driver/gpio.h> after getting a file not found for gpio.h. Next the compiler is complaining about expected initializer for:

void ICACHE_RAM_ATTR sws_isr_0() { ObjList[0]->rxRead(); };

Any suggestions? Also, is this the proper place to ask this type of question, is there a forum that would be more appropriate?

[edit - this isn't very important to me, I technically don't need this right now, was just curious if something I wrote for the esp8266 would build on the esp32]

Thanks,
Steve

**Comment by me-no-dev** [comment]
That library would not work on ESP32. Why would you need it though? Arduino supports 3 serials on any pin you like.

**Comment by ccfoo242** [comment]
Thanks. Shows how ignorant I am :-)
