### ISSUE TITLE
ESP8266AVRISP library porting on ESP32

### ISSUE THREAD

**Issue by VashTheProgrammer** [espressif/arduino-esp32#269]
Hi,
I'm trying porting of this library: https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266AVRISP
on arduino-esp32 repository but I don't have successful.

I have solved the compilation problems, but I can not load the firmware on my atmega microprocessor for some reason. Have any of you tried to import this library?

I published the library with my changes on this github repo so everyone can work on it.
link: https://github.com/VashTheProgrammer/ESP32AVRISP

Thanks so much.

**Comment by me-no-dev** [comment]
I intend to write better programmer actually  (I already have some uploaders and bootloaders written for AVR)

**Comment by VashTheProgrammer** [comment]
Perfect, I'm waiting you, if you want close the issue you can.
Thank you

If I can help you, tell me.

**Comment by cybergogo** [comment]
Hi All, any news on this?

**Comment by hgpt** [comment]
Any update?

**Comment by tab4moji** [comment]
I ported this library to micropython on ESPs.
https://github.com/tab4moji/ESPAVRISP

**Comment by ferchinas** [comment]
Hi All, any news? I´m very interested in this feature.
Thanks

**Comment by TimotF** [comment]
Looks like it has been done here => https://github.com/lbernstone/ESP_AVRISP

**Comment by igrr** [comment]
Let's consider this feature implemented in https://github.com/lbernstone/ESP_AVRISP. We won't add AVRISP functionality to arduino-esp32 core at this time.
