### ISSUE TITLE
Fail to Build while using esp-idf v3.2

### ISSUE THREAD

**Issue by Nathan-ma** [espressif/arduino-esp32#2702]
I'm having issues to build the MASTER arduin-esp32 with the matching esp-idf commit (I suppose)

### Hardware:
Board:	ESP32 Dev Module
Core Installation version: 1.0.1-git
IDE name: Esp-idf
Flash Frequency: 40Mhz
PSRAM enabled: yes
Upload Speed: 115200
Computer OS: Windows 10

### Description:
Trying to build a simple blink file using the arduino-esp32 as a component, the latest esp-idf compatible is the v3.2 as far as I know, there is a few instructions under the v3.2 build saying Remove BLE submodule ; Add BLE lib source. I belive thats my problem, only it does not make any sense to me.

Error MSG:
![image](https://user-images.githubusercontent.com/11060905/56583252-85cd0980-65af-11e9-8707-333f90ef927b.png)

**Comment by atanisoft** [comment]
You need to make sure you have the correct dependencies in place for using the WiFiClientSecure library, this includes the SSL (mbed tls) libraries. You can check the tools/sdk/sdkconfig file in the arduino-esp32 tree to see what differences there are (I'd actually suggest using this as the starting point and modify for your project)

**Comment by me-no-dev** [comment]
arduino is currently NOT tracking the master and is on v3.2 instead. Will go back to tracking master soon. Need to make sure that if there are any issues in 3.2 that we fix them first. I am also preparing an easy-start repo for building Arduino with IDF

**Comment by DarvosBR** [comment]
> arduino is currently NOT tracking the master and is on v3.2 instead. Will go back to tracking master soon. Need to make sure that if there are any issues in 3.2 that we fix them first. I am also preparing an easy-start repo for building Arduino with IDF

I'm actualy using v3.2

`commit 286202caa31b61c2182209f37f8069a0b60fb942 (HEAD, tag: v3.2-rc, tag: v3.2)
`

This one to be more specific!



> You need to make sure you have the correct dependencies in place for using the WiFiClientSecure library, this includes the SSL (mbed tls) libraries. You can check the tools/sdk/sdkconfig file in the arduino-esp32 tree to see what differences there are (I'd actually suggest using this as the starting point and modify for your project)

I wish I could only switch WiFiClientSecure off, but this option is no valid for me on Menuconfig, it seems to me a few WiFi libs are mandatory.

**Comment by DarvosBR** [comment]
> You need to make sure you have the correct dependencies in place for using the WiFiClientSecure library, this includes the SSL (mbed tls) libraries. You can check the tools/sdk/sdkconfig file in the arduino-esp32 tree to see what differences there are (I'd actually suggest using this as the starting point and modify for your project)

Brilliant, ur tip solve almost all my problems, thank you, I was stuck on it for 5 hours.

Only one question to close this, 
`rtc_wdt_flashboot_mode_enable` in function `esp_restart_noos` of the file `system_api.o` is saying undefined reference, i'm about to get in there and see if I can just comment or take it out, but before i do this, any menuconfig can help me with it? taking it out is a good idea? idk, just want an opinion, besides that i'm supper happy, the only bug there is left!!

**Comment by atanisoft** [comment]
esp_restart_noos was deprecated long back and removed IIRC from ESP-IDF.

**Comment by DarvosBR** [comment]
> esp_restart_noos was deprecated long back and removed IIRC from ESP-IDF. I'd just remove it.

ok ty once again, gonna try to remove it

**Comment by atanisoft** [comment]
another option is replace it with esp_restart()

**Comment by DarvosBR** [comment]
I commented the whole function and replaced when it was used with esp_restart(), thank you!
