### ISSUE TITLE
Does ESPnDNS update its mDNS cache automaticly?

### ISSUE THREAD

**Issue by JulianS-Uni** [espressif/arduino-esp32#2708]
I am not that into mDNS but I read several times now that mDNS machines can update their mDNS cache automaticly.

> When an mDNS client needs to resolve a host name, it sends an IP multicast query message that asks the host having that name to identify itself. That target machine then multicasts a message that includes its IP address. All machines in that subnet can then use that information to update their mDNS caches. [Wikipedia]https://en.wikipedia.org/wiki/Multicast_DNS#Protocol_overview)

Does ESPmDNS library does this too or is it only possible to query for a host or a service which are both bllocking operations?

**Comment by me-no-dev** [comment]
We do not keep a cache, since that will use some of the RAM that we don't have much of anyway. The rest of the service conforms to specs and is certified by Apple.
