### ISSUE TITLE
Is synchronization needed between callback and loop function?

### ISSUE THREAD

**Issue by vmario42** [espressif/arduino-esp32#2713]
Hello,

As I can see there's option to register callback functions for some events. Do callbacks execute in other thread (task) different  than the thread the loop function executes in?

Is there a need to synchronize shared variables with semaphores ?

**Comment by me-no-dev** [comment]
Yes, events are called from a separate thread. Semaphores are the best option, but if you want to poll or wait for something, you can use the status bits interface: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiGeneric.h#L80-L81
and
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiGeneric.h#L52-L66
