### ISSUE TITLE
RMTLoopback.ino (xEventGroupWaitBits)- assert failed!

### ISSUE THREAD

**Issue by JyeSmith** [espressif/arduino-esp32#2727]
Running RMTLoopback.ino with the latest release aborts with the below exception.

RMTLoopback.ino line 50
```
xEventGroupWaitBits(events, RMT_FLAG_RX_DONE, 1, 1, portMAX_DELAY);
```

real tick set to: 100.000000ns
/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/event_groups.c:350 (xEventGroupWaitBits)- assert failed!
abort() was called at PC 0x40087b9b on core 1

Backtrace: 0x40086388:0x3ffb1f20 0x400865b5:0x3ffb1f40 0x40087b9b:0x3ffb1f60 0x400d0c36:0x3ffb1f90 0x400e6852:0x3ffb1fb0 0x40087da9:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9220
load:0x40080400,len:6300
entry 0x400806a4

```
Decoding stack results
0x40086388: invoke_abort at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/panic.c line 155
0x400865b5: abort at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/panic.c line 170
0x40087b9b: xEventGroupWaitBits at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/event_groups.c line 350
0x400d0c36: loop() at C:\Users\smithjg\Documents\Arduino\hardware\espressif\esp32\libraries\ESP32\examples\RMT\RMTLoopback/RMTLoopback.ino line 50
0x400e6852: loopTask(void*) at C:\Users\smithjg\Documents\Arduino\hardware\espressif\esp32\cores\esp32\main.cpp line 17
0x40087da9: vPortTaskWrapper at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/port.c line 143
```

**Comment by maxdd** [comment]
Can confirm
