### ISSUE TITLE
support Scheduler library

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [espressif/arduino-esp32#274]
Is there a way to use the [Scheduler](https://www.arduino.cc/en/Reference/Scheduler) library?
Would be great to have multiple tasks/loops running.
(it would be also great to have priorities too)

original source on [github](https://github.com/arduino-libraries/Scheduler)

**Example use:**
```
#include <Scheduler.h>

int counter = 0;
int counter1 = 0;

void setup()
{
  Scheduler.startLoop(loop1);
}

void loop () {
 analogWrite(9, counter);
 counter++;
 if (counter > 255){
  counter = 0;
 }
 delay(33);
}

void loop1 () {
 analogWrite(10, counter1);
 counter1=counter1+5;
 if (counter1 > 255){
  counter1 = 0;
 }
 delay(10);
 yield();
}
```

**Comment by forthlightning** [comment]
Do tasks do what you need? You can access them from the arduino environment.

http://www.freertos.org/a00125.html

**Comment by Jorgen-VikingGod** [comment]
wow great - did not know, that it is accessible within arduino environment.
So Maybe I build my own helper class and using **xTaskCreate** and **vTaskDelay**

**Comment by hreintke** [comment]
@Jorgen-VikingGod : 
Did not look into it yet so this is not a comment on usability and/or quality.
https://github.com/michaelbecker/freertos-addons

**Comment by copercini** [comment]
I made a little example of multiples loops , check this out: https://github.com/copercini/esp32-iot-examples/blob/master/multiloop/multiloop.ino

**Comment by copercini** [comment]
Since the arduino core run over FreeRTOS and you can call the APIs directly in the Arduino sketch, so it's not necessary an additional library

**Comment by eadmaster** [comment]
the Scheduler.h API is simpler to use and does not require to specify a stacksize, maybe this can be reconsidered?
