### ISSUE TITLE
Prevent hidden use of non-IRAM interrupt service routines via FunctionalInterrupt API

### ISSUE THREAD

**Issue by dok-net** [espressif/arduino-esp32#2748]
If one uses the FunctionaInterrupt attachInterrupt, the ESP32 will accept and execute ISRs that are not in IRAM. The C++ compiler currently does not (same problem in ESP8266) honor IRAM_ATTR for std::bind, std::function, or lambdas - probably never will, or otherwise a lot of std-namespace code would have to be marked as IRAM_ATTR.
This problem is avoided by either either removing (#2734 ) the problematic FunctionalInterrupt interface, or by providing safe scheduling for std::function, std::bind, lambdas through "scheduled ISRs." (TBD, under investigation )

**Comment by dok-net** [comment]
#1344 btw is not thread-safe AFAIK.

**Comment by fim13** [comment]
This may save some people some time. @dok-net Thank you for the clarification.
