### ISSUE TITLE
smartconfig bug

### ISSUE THREAD

**Issue by chenkaiyao** [espressif/arduino-esp32#275]
I use the smartconfig example, but had a problem. 
when I config a device to connect to Router1， it  return:
``
Waiting for SmartConfig.
....................
SmartConfig received.
Waiting for WiFi
.....WiFi Connected.
IP Address: 192.168.3.207
ets Jun  8 2016 00:22:57 
``

I change the Router2, it return:

``
Waiting for SmartConfig.
............................................................................................................................
SmartConfig received.
Waiting for WiFi
.....WiFi Connected.
IP Address: 192.168.3.207
``

why IP Address is the same?

**Comment by chenkaiyao** [comment]
the Router2 IP Address should be 192.168.1.***

**Comment by me-no-dev** [comment]
hmm.. can you confirm that it connects actually to the other access point? If you use ArduinoIDE, please enable debug level "Verbose" or "Debug" so we see what events come from WiFi. When printing the IP, print SSID as well.

**Comment by chenkaiyao** [comment]
**ok! it connects to one access point, it printing:**


[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 12 - AP_START
[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 13 - AP_STOP
Waiting for SmartConfig.
..............................................................................[D][WiFiSTA.cpp:564] _smartConfigCallback(): ssid     = MOLMC_HUAWEI
[D][WiFiSTA.cpp:565] _smartConfigCallback(): password = 12345678
.
SmartConfig received.
Waiting for WiFi
....[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 7 - STA_GOT_IP
.WiFi Connected.
IP Address: 192.168.3.239
SSID: MOLMC_HUAWEI


**connets the other access point, it pringting:** 


[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 12 - AP_START
[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 13 - AP_STOP
Waiting for SmartConfig.
................


iCh lock
.


.

...[D][WiFiSTA.cpp:564] _smartConfigCallback(): ssid     = MOLMC-NETGRAR
[D][WiFiSTA.cpp:565] _smartConfigCallback(): password = 12345678
.
SmartConfig received.
Waiting for WiFi
....[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:174] _eventCallback(): Event: 7 - STA_GOT_IP
.WiFi Connected.
IP Address: 192.168.3.239
SSID: MOLMC_HUAWEI

**I am printing the Received ssid and password, but connecting seems no work!**

**Comment by copercini** [comment]
Both are on the same network? and have DHCP enabled?

**Comment by chenkaiyao** [comment]
@me-no-dev smartconfig example is ok for you ?

**Comment by me-no-dev** [comment]
Sorry guys, just forgot to reply, but I will advise you to file the issue at espressif/esp-idf, because the problem is somewhere in the system wifi libs. It looks like once you connect, the configuration is not overwritten and it connects to the last station configured.
Now we can hack this to clear the configuration when smart config is enabled, but that is a hack and not the proper way to do things :)

**Comment by me-no-dev** [comment]
OK, let me try a few things and see if I can fix this without hackery.

**Comment by me-no-dev** [comment]
Oh this is embarrassing :D check which interface is the new setting set on... https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiSTA.cpp#L564

**Comment by chenkaiyao** [comment]
thanks!
