### ISSUE TITLE
WiFi Strange behavior about connection/reconnection

### ISSUE THREAD

**Issue by asetyde** [espressif/arduino-esp32#2769]
### Hardware:
Board:							ESP32 WROOM 32D
Core Installation version:			1.0.2 stable 
IDE name:						Arduino IDE/ Visual Micro on Visual Studio
Flash Frequency:					80cpu/80flash
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Windows 10

### Description:
In this month we 've fond many issue that weren't on 1.0.0, but we need temperature reduction with low core, therefore we must use 1.0.2.
WiFi fail sometimes to reconnect, also watchdog sometimes fail to reboot board , we not find any issue about our code.
We ve see many issue but no response from espressif coders, we ve also use ESP-IDF base sdk but issue is hide on WiFi core working and we not investigate inside.

We hope a fast resolving bugfix because devices are not stable and not usable.

### Debug Messages:
Always verbose logs about fail reconnection says "AUTH_EXP" looping
about watchdog , says not triggered many times continuosly, core 0 seems live but core 1 freezed and try rebooting but nothing do, board freeze.

**Comment by asetyde** [comment]
If not fast resolution coming we must come back to 1.0.0 but we ve some problems with i2c, millis, core temperature and some big bug

**Comment by me-no-dev** [comment]
there is a fix coming for the wifi issues.

**Comment by asetyde** [comment]
Many Thanks

**Comment by me-no-dev** [comment]
I have merged updated IDF lib. It's only available through github. Could you try them and see if your issues are resolved?

**Comment by asetyde** [comment]
Yes now I'm loading on devices, test require 24/48h max .

**Comment by me-no-dev** [comment]
thanks :)

**Comment by asetyde** [comment]
can use 1.0.3 rc  from board manager ? git give me always strange issue

**Comment by me-no-dev** [comment]
yes :) I tagged it so you and other people with wifi issues can test

**Comment by asetyde** [comment]
not download , give error on board manager

**Comment by me-no-dev** [comment]
something went wrong the first time. I have updated the release. Please try again :)

**Comment by asetyde** [comment]
ok it go !

**Comment by asetyde** [comment]
Report:   (connection go )


[wifi_start] Connessione fallita
[wifi_start] Tentativo di connessione (EEPROM) 2 di 3
Smartconfig
maggio2014
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:379] _eventCallback(): STA IP: 192.168.1.163, MASK: 255.255.255.0, GW: 192.168.1.1
[wifi_start] Connesso!
 --------------------------------------- 
 - Wifi SSID : Smartconfig
 - Wifi ip : 192.168.1.163
 - Size of structt : 3812
 - Wifi Mac : 30:AE:A4:D4:20:C0
- WIFI signal : -58
- Signal level is  < -67 Very Good 
 - Firm.Chip :v3.2-111-g524308c98
 - EHI SW : 1.1
 - IP configuration : system on DHCP
 - IP on dhcp : 192.168.1.163
 - IPGateway on dhcp : 192.168.1.1
 - IPmask on dhcp : 255.255.255.0
 - Server : 192.168.1.89
 - Serial : 192.168.1.201
 - Broadcast : 192.168.1.255
 --------------------------------------- 
[INFO] Entrata in iamaliveSQLforecast
	Connessione...
Connected to server version 5.5.5-10.1.38-MariaDB-0+deb9u1
Disconnected.
	Query eseguita
[SETUP] WiFi inizializzato
[INFO] PIN TOUCHX :0

[INFO] Avvio Server UDP...

[SISTEMA] Fase 4 - Avvio sistema
[INFO] Stati resettati

[INFO] Setup canali
[INFO] Elenco canali input configurati:
[INFO] Diagnostica canali terminata
SHTX TEST test!
Found model SHT25 Rev(1) Serial #[INFO] Gestione sensore Termperatura: ON
[INFO] Gestione sensore luce: ON
[INFO] Gestione sensore Humi : ON

[SISTEMA] Setup completato
[SISTEMA] Inizio loop.

[INFO] Led backgroud Full
[SETUP] Invio del messaggio di diagnostica
[INFO] Calibrazione Touch

**Comment by asetyde** [comment]
Now I test it, first connection not go (always), second go , now I test many situations

**Comment by asetyde** [comment]
example : 

Port open
[wifi_start] Stato WiFi: WL_NO_SSID_AVAIL
[wifi_start] Tentativo di connessione (EEPROM) 2 di 3
Smartcondfig
maggio2014
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:351] _eventCallback(): Reason: 201 - NO_AP_FOUND
[wifi_start] Stato WiFi: WL_NO_SSID_AVAIL
[wifi_start] Tentativo di connessione (EEPROM) 3 di 3
Smartcondfig
maggio2014
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:351] _eventCallback(): Reason: 201 - NO_AP_FOUND
[wifi_start] Stato WiFi: WL_NO_SSID_AVAIL
[wifi_start] Tentativo di connessione (Recovery) 1 di 3
Smartconfig
maggio2014
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:351] _eventCallback(): Reason: 202 - AUTH_FAIL
[wifi_start] Connessione fallita
[wifi_start] Tentativo di connessione (Recovery) 2 di 3
Smartconfig
maggio2014
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:336] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:379] _eventCallback(): STA IP: 192.168.1.163, MASK: 255.255.255.0, GW: 192.168.1.1

**Comment by asetyde** [comment]
now we test all days , I report as soon as possible

**Comment by asetyde** [comment]
Note : We new library 1.0.3 i start to use our chip of memory , eprom is not use anymore

**Comment by asetyde** [comment]
About some devices : 3 lost connection and 2 of this after 30/40 min re-connected. Our code not use autoconnect and disabile it, also we use olle manual begin with user and password, we disconnect every time we see lost connection and our code begin our code routine to connect again

**Comment by asetyde** [comment]
We se only auth exp but we see many logs inside  esp-idf this library not report it

**Comment by asetyde** [comment]
About SSID we underline with router with wireless access point , seems esp not choose best signal but choose randomlly, also we see on ESP MDF  where channel is fixed and esp not capace to change it 
Hope advice you, we continue test on it

about watchdog , one device it blocks on loop wifi, watchdog unable to reset it

**Comment by asetyde** [comment]
a question , your update is not 3.3 beta IDF correct ? I see many improvements to wifi 
0acf19a Update IDF to v3.2 977854975 (#2771)

**Comment by me-no-dev** [comment]
Yup we are on the latest IDF 3.2 with whatever bugfixes were added to it.
How is WiFi doing?

**Comment by asetyde** [comment]
WiFi seems has same problems, but now I test it in STATIC mode, it seems work without reconnection, I suppose two reason , Arduino library not manage correctly or not manage a WL_STATUS, or ISSUE of re-connection is a mask for a issue of DHCP , I give to you an example of our routine , but I think we restrict issue to this two ways, DHCP or WL-STATUS (after reconnections. ? )

**Comment by asetyde** [comment]
wl_status_t wifi_connect(boolean recovery)
{
	static unsigned long conn_timeout = 5000;
	static unsigned long t0, t1 = 0;
	char wssid[30], wpasswd[30];

	if (WiFi.status() == WL_CONNECTED)
	{
		WiFi.disconnect();
	}

	WiFi.mode(WIFI_MODE_STA);
	WiFi.setHostname("Electric Labs Device");

	if (recovery)
	{
		snprintf(wssid, sizeof(wssid), "Smartconfig");
		snprintf(wpasswd, sizeof(wpasswd), "maggio2014");
	}
	else
	{
		if (memory.iptype == 100)
		{
			WiFi.config(convertfromStringSTD(memory.ipset), convertfromStringSTD(memory.ipgateway), convertfromStringSTD(memory.ipmask));
		}
		snprintf(wssid, sizeof(wssid), memory.ssid);
		snprintf(wpasswd, sizeof(wpasswd), memory.password);
	}

	WiFi.begin(wssid, wpasswd);

	t0 = t1 = millis();
	while ((WiFi.status() != WL_CONNECTED) && ((t1 - t0) < conn_timeout))
	{
		delay(500);            // internal memory                         // revovery memory
		if (!recovery){ledcommands(false, false, 0, 2);} else { ledcommands(false, false, 0, 2);}
		delay(500);
		if (!recovery){ledcommands(true, false, 0, 2);} else { ledcommands(false, true, 0, 2); }
		t1 = millis();
	}

	return WiFi.status();
}

**Comment by asetyde** [comment]
wl_status_t wifi_connect(boolean recovery)
{
	static unsigned long conn_timeout = 5000;
	static unsigned long t0, t1 = 0;
	char wssid[30], wpasswd[30];

	if (WiFi.status() == WL_CONNECTED)
	{
		WiFi.disconnect();
	}

	WiFi.mode(WIFI_MODE_STA);
	WiFi.setHostname("Electric Labs Device");

	if (recovery)
	{
		snprintf(wssid, sizeof(wssid), "Smartconfig");
		snprintf(wpasswd, sizeof(wpasswd), "maggio2014");
	}
	else
	{
		if (memory.iptype == 100)
		{
			WiFi.config(convertfromStringSTD(memory.ipset), convertfromStringSTD(memory.ipgateway), convertfromStringSTD(memory.ipmask));
		}
		snprintf(wssid, sizeof(wssid), memory.ssid);
		snprintf(wpasswd, sizeof(wpasswd), memory.password);
	}

	WiFi.begin(wssid, wpasswd);

	t0 = t1 = millis();
	while ((WiFi.status() != WL_CONNECTED) && ((t1 - t0) < conn_timeout))
	{
		delay(500);            // internal memory                         // revovery memory
		if (!recovery){ledcommands(false, false, 0, 2);} else { ledcommands(false, false, 0, 2);}
		delay(500);
		if (!recovery){ledcommands(true, false, 0, 2);} else { ledcommands(false, true, 0, 2); }
		t1 = millis();
	}

	return WiFi.status();
}
boolean wifi_start()
{
	WiFi.setAutoReconnect(false);

	int RETRY_MAX = 3;
	int retry = 0;
	boolean memory_connected = false;

	wdtreset();
	while (retry < RETRY_MAX)
	{
		debug("[wifi_start] Tentativo di connessione (EEPROM) "); debug((retry + 1)); debug(" di "); debugn(RETRY_MAX);
		wl_status_t result = wifi_connect(false);
		int rssi = 0;
		int value2 = 0;

		switch (result)
		{
			case WL_CONNECT_FAILED:
				debugn("[wifi_start] Connessione fallita");
				break;

			case WL_CONNECTED:
				currentIP.fromString(WiFi.localIP().toString());
				server[0] = currentIP[0];
				server[1] = currentIP[1];
				server[2] = currentIP[2];
				server[3] = 89;
				serial[0] = currentIP[0];
				serial[1] = currentIP[1];
				serial[2] = currentIP[2];
				broadcast[0] = currentIP[0];
				broadcast[1] = currentIP[1];
				broadcast[2] = currentIP[2];
				broadcast[3] = 255;
				WiFi.SSID().toCharArray(datassid, 30);

				debugn("[wifi_start] Connesso!");
				debugn(" --------------------------------------- ");
				debug(" - Wifi SSID : ");
				debugn(datassid);
				debug(" - Wifi ip : ");
				debugn(currentIP.toString());
				debug(" - Size of structt : ");
				debugn(sizeof(memory));
				debug(" - Wifi Mac : ");
				debugn(macAddress);
				debug("- WIFI signal : ");
				rssi = WiFi.RSSI();
				debugn(rssi);
				value2 = abs(rssi);
				if (value2 <= 30) { debugn("- Signal level is < -30 Perfect "); }
				if ((value2 > 30) && (value2 <= 67)) { debugn("- Signal level is  < -67 Very Good "); }
				if ((value2 > 67) && (value2 <= 70)) { debugn("- Signal level is < -70 Ok but is low >30mbit "); }
				if ((value2 > 72) && (value2 <= 80)) { debugn("- Signal level is < -80 not so Good  (about 15-5 mbit) "); }
				if (value2 > 80) { Serial.println("- Signal level is > -80 - Warning is UNSTABLE "); }
				debug(" - Firm.Chip :");
				debugn(ESP.getSdkVersion());
				debug(" - EHI SW : ");
				debugn(systemversion);
				debug(" - IP configuration : ");
				if (memory.iptype == 100) { debugn("system uses Ip fixed"); }
				else {
					debugn("system on DHCP");
					debug(" - IP on dhcp : ");
					debugn(WiFi.localIP());
					debug(" - IPGateway on dhcp : ");
					debugn(WiFi.gatewayIP());
					debug(" - IPmask on dhcp : ");
					debugn(WiFi.subnetMask());
				}
				if (memory.iptype == 100) {
					debug(" - IP fixed : ");
					debugn(memory.ipset);
					debug(" - IPmask fixed : ");
					debugn(memory.ipmask);
					debug(" - IPGateway fixed : ");
					debugn(memory.ipgateway);
				}
				debug(" - Server : ");
				debugn(server);
				debug(" - Serial : ");
				debugn(serial);
				debug(" - Broadcast : ");
				debugn(broadcast);
				debugn(" --------------------------------------- ");
				memory_connected = true;
				connessioneScelta = 1;
				retry = RETRY_MAX;
				iamaliveSQLforecast();
				break;

			default:
				debug("[wifi_start] Stato WiFi: "); printWiFiStatus(WiFi.status());
				break;
		}
		retry++;
	}

	if (!memory_connected)
	{
		wdtreset();
		retry = 0;
		while (retry < RETRY_MAX)
		{
			debug("[wifi_start] Tentativo di connessione (Recovery) "); debug((retry + 1)); debug(" di "); debugn(RETRY_MAX);
			wl_status_t result = wifi_connect(true);
			int rssi = 0;
			int value2 = 0;

			switch (result)
			{
				case WL_CONNECT_FAILED:
					debugn("[wifi_start] Connessione fallita");
					break;

				case WL_CONNECTED:
					currentIP.fromString(WiFi.localIP().toString());
					WiFi.SSID().toCharArray(datassid, 30);
					server[0] = currentIP[0];
					server[1] = currentIP[1];
					server[2] = currentIP[2];
					server[3] = 89;
					serial[0] = currentIP[0];
					serial[1] = currentIP[1];
					serial[2] = currentIP[2];
					broadcast[0] = currentIP[0];
					broadcast[1] = currentIP[1];
					broadcast[2] = currentIP[2];
					broadcast[3] = 255;
					WiFi.SSID().toCharArray(datassid, 30);

					debugn("[wifi_start] Connesso!");
					debug("\tModalità: Recovery");
					debugn(" --------------------------------------- ");
					debug(" - Wifi SSID : ");
					debugn(datassid);
					debug(" - Wifi ip : ");
					debugn(currentIP.toString());
					debug(" - Size of structt : ");
					debugn(sizeof(memory));
					debug(" - Wifi Mac : ");
					debugn(macAddress);
					debug("- WIFI signal : ");
					rssi = WiFi.RSSI();
					debugn(rssi);
					value2 = abs(rssi);
					if (value2 <= 30) { debugn("- Signal level is < -30 Perfect "); }
					if ((value2 > 30) && (value2 <= 67)) { debugn("- Signal level is  < -67 Very Good "); }
					if ((value2 > 67) && (value2 <= 70)) { debugn("- Signal level is < -70 Ok but is low >30mbit "); }
					if ((value2 > 72) && (value2 <= 80)) { debugn("- Signal level is < -80 not so Good  (about 15-5 mbit) "); }
					if (value2 > 80) { Serial.println("- Signal level is > -80 - Warning is UNSTABLE "); }
					debug(" - Firm.Chip :");
					debugn(ESP.getSdkVersion());
					debug(" - EHI SW : ");
					debugn(systemversion);
					debug(" - IP configuration : ");
					if (memory.iptype == 100) { debugn("system uses Ip fixed"); }
					else {
						debugn("system on DHCP");
						debug(" - IP on dhcp : ");
						debugn(WiFi.localIP());
						debug(" - IPGateway on dhcp : ");
						debugn(WiFi.gatewayIP());
						debug(" - IPmask on dhcp : ");
						debugn(WiFi.subnetMask());
					}
					if (memory.iptype == 100) {
						debug(" - IP fixed : ");
						debugn(memory.ipset);
						debug(" - IPmask fixed : ");
						debugn(memory.ipmask);
						debug(" - IPGateway fixed : ");
						debugn(memory.ipgateway);
					}
					debug(" - Server : ");
					debugn(server);
					debug(" - Serial : ");
					debugn(serial);
					debug(" - Broadcast : ");
					debugn(broadcast);

					debugn(" --------------------------------------- ");
					connessioneScelta = 2;
					retry = RETRY_MAX;
					iamaliveSQLforecast();
					break;

				default:
					debug("[wifi_start] Stato WiFi: "); printWiFiStatus(WiFi.status());
					break;
			}
			retry++;
		}
	}

	return WiFi.status() == WL_CONNECTED;
}
void printWiFiStatus(wl_status_t state)
{
	switch (state)
	{
		case WL_NO_SHIELD:
			debugn("WL_NO_SHIELD");
			break;
		case WL_CONNECTED:
			debugn("WL_CONNECTED");
			break;
		case WL_IDLE_STATUS:
			debugn("WL_IDLE_STATUS");
			break;
		case WL_NO_SSID_AVAIL:
			debugn("WL_NO_SSID_AVAIL");
			break;
		case WL_SCAN_COMPLETED:
			debugn("WL_SCAN_COMPLETED");
			break;
		case WL_CONNECT_FAILED:
			debugn("WL_CONNECT_FAILED");
			break;
		case WL_CONNECTION_LOST:
			debugn("WL_CONNECTION_LOST");
			break;
		case WL_DISCONNECTED:
			debugn("WL_DISCONNECTED");
			break;
	}
}

**Comment by asetyde** [comment]
void printWiFiStatus(wl_status_t state)
{
	switch (state)
	{
		case WL_NO_SHIELD:
			debugn("WL_NO_SHIELD");
			break;
		case WL_CONNECTED:
			debugn("WL_CONNECTED");
			break;
		case WL_IDLE_STATUS:
			debugn("WL_IDLE_STATUS");
			break;
		case WL_NO_SSID_AVAIL:
			debugn("WL_NO_SSID_AVAIL");
			break;
		case WL_SCAN_COMPLETED:
			debugn("WL_SCAN_COMPLETED");
			break;
		case WL_CONNECT_FAILED:
			debugn("WL_CONNECT_FAILED");
			break;
		case WL_CONNECTION_LOST:
			debugn("WL_CONNECTION_LOST");
			break;
		case WL_DISCONNECTED:
			debugn("WL_DISCONNECTED");
			break;
	}
}`

**Comment by me-no-dev** [comment]
please read how to paste code :)

**Comment by asetyde** [comment]
sorry I do with cell phone, it's a bit confusing, thanks for reformat

**Comment by asetyde** [comment]
UPDATE :  With static configuration and this library, no issue, therefore I thin something with disconnection and DHCP is wrong. We can not investigate inside, we not have other information about AUTH_EXP

**Comment by asetyde** [comment]
Other test and continuos operative test on STATIC IP not has issue, I think we can close circle on DHCP

**Comment by asetyde** [comment]
Continues test and no issue, uses watchdog with while(1) blocking function it works.
We have find some strange casual issue about data from .RSSI sometimes values is corrupted .. this can say something but I don't know

**Comment by asetyde** [comment]
Now it working so better without freeze, but I see sometimes reconnection and sometimes reboot of ESP32 WROOM D. I hope soon @me-no-dev  you will upgrade to new IDF with new bug fix about wifi, I see on logs many correction , we need stable working library. Hope to improve signal performance, it's lower than first firmware.

**Comment by GeorgeFlorian** [comment]
I am experiencing something similar: https://github.com/espressif/arduino-esp32/issues/2999

Any luck with this ?

**Comment by asetyde** [comment]
now I see new IDF loaded .. I'm waiting new RC to test it .. at now go better but signal so so .. sometimes not freeze but reboot .. i wait to test it

**Comment by CircuitSetup** [comment]
I'm wondering if this has to do with this issue: https://github.com/espressif/arduino-esp32/issues/2899

However, in the last IDF update CONFIG_ESP32_WIFI_RX_BA_WIN was changed to 16 from 6

**Comment by CircuitSetup** [comment]
I'm curious if the problems people are having with reconnecting to wifi have anything to do with the power being provided? This seems to only happen to me when running a smaller power supply. 

When it tries to reconnect to the AP, it fails and eventually freezes. It seems to not disconnect in the first place with more power, but if it does, it reconnects easier.

**Comment by CircuitSetup** [comment]
> now I see new IDF loaded .. I'm waiting new RC to test it .. at now go better but signal so so .. sometimes not freeze but reboot .. i wait to test it

You could just copy the current files in the repository. I did this, but unfortunately it didnt solve my issue.
