### ISSUE TITLE
Problem with Ethernet.h compilation after board library update from 1.0.1 to 1.0.2

### ISSUE THREAD

**Issue by xdigyx** [espressif/arduino-esp32#2786]
Hi,

as in the title: after updating the board library, all my projects including Ethernet.h lib don't compile. Virtual functions error.

**Comment by xdigyx** [comment]
reverting back to 1.0.1 helps.

**Comment by SRGDamia1** [comment]
Is this the same issue as #2755?

**Comment by HighTML** [comment]
When downgrading to 1.0.1 I get:
`/Users/marcel/Development/Arduino/libraries/M5Stack/src/utility/Power.cpp:361:28: error: 'gpio_deep_sleep_hold_dis' was not declared in this scope
   gpio_deep_sleep_hold_dis();`
