### ISSUE TITLE
SSL - No CA Chain is set, but required to operate

### ISSUE THREAD

**Issue by salqadri** [espressif/arduino-esp32#279]
I'm getting the following debug logs when using WifiClientSecure to connect to an https endpoint:

Free heap before TLS 124336
Seeding the random number generator
Setting up the SSL/TLS structure...
Performing the SSL/TLS handshake...

SSL - No CA Chain is set, but required to operate

MbedTLS message code: -30336

Cleaning SSL connection.

This used to work fine in the ESP8266 version of WifiClientSecure, but doesn't work under esp32. What may be going on here?

**Comment by copercini** [comment]
Same as https://github.com/espressif/arduino-esp32/issues/265
