### ISSUE TITLE
Can we get an HttpClient library for esp32?

### ISSUE THREAD

**Issue by salqadri** [espressif/arduino-esp32#280]
The esp8266 has a great HttpClient library: https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266HTTPClient

Can we get something like this for ESP32 as well please?

**Comment by bbx10** [comment]
@copercini ported the ESP8266 version to ESP32. Works fine for me.

https://github.com/espressif/arduino-esp32/commit/51a4432ca8e71be202358ceb068f3047bb8ad762

**Comment by copercini** [comment]
Implemented here: https://github.com/espressif/arduino-esp32/tree/master/libraries/HTTPClient
