### ISSUE TITLE
missing: WebServer.h  lib (like for esp8266)

### ISSUE THREAD

**Issue by dsyleixa** [espressif/arduino-esp32#2803]
Hello,
I can't find a lib WebServer.h  (like available for esp8266), with a similar, easily portable API syntax and features.
Is there such a thing available yet?

**Comment by atanisoft** [comment]
Did you look in the included libraries? https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer

**Comment by dsyleixa** [comment]
thanks, my bad, I looked but nonetheless didn't find them.
My apologies.
