### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by EduardoManusse** [espressif/arduino-esp32#2808]
Description:
I simply cannot get the esp32 support on arduino IDE to work. I keep getting this error:

exec: "C:\Users\[myname]\Documents\Arduino\hardware\espressif\esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++": file does not exist
Error compiling for board TTGO LORA32 OLED V2.

Thank you for your help.

**Comment by lbernstone** [comment]
The [issue template](https://github.com/espressif/arduino-esp32/tree/master/.github/ISSUE_TEMPLATE) is there to help us help you.
Reinstall the board [using board manager](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md)
