### ISSUE TITLE
HTTP UPDATE FAILED Error 

### ISSUE THREAD

**Issue by belnj** [espressif/arduino-esp32#2809]
I'm using HTTPUpdate to make OTA updates, but sometimes i get this error HTTP_UPDATE_FAILED Error (6): Update error: Stream Read Timeout.

DOES SOMEBODY KNOW WHERE THIS ERROR COMES?

**Comment by RudyFiero** [comment]
Did you do a search in the search box at the top left of this page? 

https://github.com/espressif/arduino-esp32/search?q=HTTP_UPDATE_FAILED&unscoped_q=HTTP_UPDATE_FAILED
