### ISSUE TITLE
Partition Table ESP32 Arduino

### ISSUE THREAD

**Issue by robcim** [espressif/arduino-esp32#2815]
Hi all,
I’m Roberto.
I have this question:
    To use the OTA programming mode on my esp32, if my sketch is 2MB in size, should I have 2MB 
     free in the flash? So sketch partition = 2MB and OTA partition = 2MB?

Thank
Roberto

**Comment by lbernstone** [comment]
Yes. https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/ota.html#

**Comment by robcim** [comment]
OK. Thanks for your help.
