### ISSUE TITLE
ESP-32 Camera Brightness, Contrast, Saturation problem

### ISSUE THREAD

**Issue by Dzandaa** [espressif/arduino-esp32#2819]
### Hardware:
Board: TTGO T-Camera ESP32 WROVER with PSRAM Camera Module OV2640
Core Installation version:	1.02
IDE name: Arduino IDE
Flash Frequency: 80Mhz
PSRAM enabled: yes
Upload Speed:	921600
Computer OS:  Windows 7 Pro 64b, Ubuntu Mint 64b

### Description:
The Camera Brightness, Contrast, Saturation, slider on the "CameraWebServer"  doesn't not react correctly, also in a program, the last action deletes other actions, for example change the saturation after the brightness reset the brightness

### Sketch: 
```
//  Value and Type are int
  sensor_t * s = esp_camera_sensor_get();    
    switch(Type)
    {
      case CBrightness:
        s->set_brightness(s, Value);  
      break;  
      case CSaturation:
        s->set_saturation(s, Value);   
      break;
      case CContrast:
        s->set_contrast(s, Value);   
      break;      
    }    
```

### Debug Messages:
```

```

**Comment by mosazahany** [comment]
Strange problems in adjusting the saturationand the brightness in ov2640
These bugs do not actually exist and are a problem of the available documents
When you execute the following commands
set_brightness(s,2);
set_contrast(s,2);
set_brightness(s,2);
The last command is always active and the previous commands are canceled.
To solve this problem, you must activate the desired effect and this is done with the following command

Run the following command at the end of all settings.

unsigned char enable_effect=	1(saturation and hue enable)+
				2(aditional saturation enable)+
				4(brighnes and contrast enable)+
				8(spital effect1 enable green -> blue)+
				16(spital effect1 enable gray -> read)+
				32(remove (UV) in YUV color system)+
				64(enable negative effect)+
				128(remove (Y) in YUV color system)  ;
write_SCCB(0xff, 0x00);
write_SCCB(0x7c, 0x00);
write_SCCB(0x7d,enable_effect);

command 
write_SCCB(0x7c, ADRESS);
Preparing the address for data injection

ofter that use
The following command to inject data
write_SCCB(0x7d,byte_0);
write_SCCB(0x7d,byte_1);
write_SCCB(0x7d,byte_2);
.
.
.

The memory structure is as follows
byte_0 =enable_effect  
         byte_0->bit0  =saturation and hue 
         byte_0->bit1  =saturation enable
         byte_0->bit2  =brighnes and contrast enable
         byte_0->bit3  =green -> blue spitial effect (Antique and blunish and greenish and readdish and b&w) enable
         byte_0->bit4  =gray  -> read spitial effect (Antique and blunish and greenish and readdish and b&w) enable
         byte_0->bit5  =remove (UV) in YUV color system
         byte_0->bit6  =negative enable
         byte_0->bit7  =remove (Y) in YUV color system
byte_1 =saturation1  0-255
byte_2 =hue 0-255
byte_3 =saturation2  0-255
byte_4 =reenter saturation2 in documents
byte_5 =spital effect green -> blue   0-255
byte_6 =spital effect gray  -> read   0-255
byte_7 =contrast uper  eadge  0-255
byte_8 =contrast lower eadge  0-255
byte_9 =brighnes 0-255
byte_10= if byte_10==4 contrast effective 

mosazahany@gmail.com
با تشکر
