### ISSUE TITLE
WiFi.scanNetworks doesn't stop return WIFI_SCAN_RUNNING, if scan was started under connecting condition

### ISSUE THREAD

**Issue by EricMc1289** [espressif/arduino-esp32#2823]
Hey guys,
if you start a scan for networks if the esp is connecting to an ap the scan request is aborted by the sdk without returning an error. See here https://github.com/espressif/esp-idf/issues/3044 for reference. 

In my case the scan routine is running in its own thread so i can't assume when the scanNetworks is triggered. If it gets triggered while the esp is connecting the connect scan has priority and the SYSTEM_EVENT_SCAN_DONE event is never triggered. In that particular case the WIFI_SCANNING_BIT is never cleared and you're not able to scan for networks without a reset. 

To prevent that case i modified the WiFiScan.ccp to include a timeout mechanism to reset an failed scan. So I added a define SCAN_ERROR_DELAY with a value of 10000 for 10s as timeout and the parameter _scanStarted.

If the  SYSTEM_EVENT_SCAN_DONE event is not fired within the SCAN_ERROR_DELAY the scanComplete method returns WIFI_SCAN_FAILED to indicate that the scan failed. 

I added my modified WIFIScan.cpp here if someone encounters the same issue or if you guys want to add these changes to the repo.
[WiFiScan.cpp.zip](https://github.com/espressif/arduino-esp32/files/3219602/WiFiScan.cpp.zip)

**Comment by guntang68** [comment]
Thanks. This is help me so much.
