### ISSUE TITLE
ESP32 Keeps rebooting after code uploaded

### ISSUE THREAD

**Issue by bhavish030** [espressif/arduino-esp32#2829]
Hello all,

I've seen the previous similar issues, but i don't know yet if there has been a fix to this since i can't really understand the explanations and i a newbie to ESP32. Very sorry for that but can anyone explain to me clearly, if possible, how to fix my ESP32.
These are the errors appearing on my serial monitor:

```
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:10088
load:0x40080400,len:6380
entry 0x400806a4
assertion "offset == dataSize" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/nvs_flash/src/nvs_storage.cpp", line 438, function: esp_err_t nvs::Storage::readMultiPageBlob(uint8_t, const char*, void*, size_t)
abort() was called at PC 0x400d64fb on core 0

Backtrace: 0x4008c470:0x3ffb53b0 0x4008c6a1:0x3ffb53d0 0x400d64fb:0x3ffb53f0 0x400db231:0x3ffb5420 0x400db29c:0x3ffb54a0 0x400da366:0x3ffb5500 0x400da899:0x3ffb5540 0x400d8cb1:0x3ffb5560 0x400d907a:0x3ffb55d0 0x400d9422:0x3ffb5600 0x4010d501:0x3ffb5630 0x4010d604:0x3ffb5660 0x4010d8fa:0x3ffb5690 0x4010da7b:0x3ffb56c0 0x400885e4:0x3ffb56e0 0x4008e6f1:0x3ffb5720
```

Am really desperate at this since i cannot work on my university project. Actually i have 4 ESP32 and each one of them used to work perfectly until last week 3 of them started to behave abnormally for no reasons.
I've been working on this project for 5 months and just in 3 days i've got my presentation and my ESPs decides to behave like this at that critical time.
If anybody can help me out to fix this, that would really save my life>.
Thank you

**Hardware:**
Board:	ESP-wroom-32 Dev Module / DEVKITV1
IDE name:	Arduino IDE 1.8.9
Upload Speed: 921600
CPU Frequency: 204MHz (WiFi/BT)
Flash Frequency:	80Mhz
Flash Mode: QIO
Flash Size: 4MB
Partition Scheme: Default
Core Debug Level: None
PSRAM: None

**Comment by lbernstone** [comment]
It looks like invalid partitioning.  Try wiping one of the devices by running `python esptool.py erase_flash` from the command line.  If you get the same error after reflashing, you have a problem in your code.  Figure out where with the [exception decoder](https://github.com/me-no-dev/EspExceptionDecoder)
