### ISSUE TITLE
EEPROM, and WiFiClient issues with updated library .

### ISSUE THREAD

**Issue by tommakov** [espressif/arduino-esp32#2846]
Using the libraries from the middle of 2018 I was able to successfully use the EEPROM and WiFiClientSecure libraries.  After updating the libraries to the current versions.

1 ) The EEPROM library only reads zeros as the current data state, where previously the unprogrammed state was all "ones" as in 0xFF's with data being present that I previously programmed.

2 ) When operating in Access Point mode directly to a PC's web browser, the WiFiClientSecure was able to send messages that got posted on the web page using the println function.  Now with the new libraries nothing gets posted but the println function return the number of bytes "supposedly" sent.

What do I need to change in my software to get both of these libraries working again?  Or are these "bugs" in the updated libraries?

Tom

**Comment by lbernstone** [comment]
EEPROM was just me not knowing the spec.
https://github.com/espressif/arduino-esp32/blob/master/libraries/EEPROM/src/EEPROM.cpp#L114
-       memset(key_data, 0, size);
+       memset(key_data, 0xFF, size);

**Comment by tommakov** [comment]
I changed the one line of code mentioned above and it did not fix the issue.  It still reads zeros.

**Comment by lbernstone** [comment]
You'll need to wipe the EEPROM (or the device).  It only fills the empty space on init.
