### ISSUE TITLE
ESP now with hidden Slave SSID

### ISSUE THREAD

**Issue by perf3ct1on666** [espressif/arduino-esp32#2878]
Wanna to ask the ESP now isit just can found the visible SSID? i tested with hidden ssid on slave with WiFi.SoftAP(ssi,d pass, 1, 1), then i cannot found my slave...
and also i using WiFiScan to scan all wifi ssid nearby working area, the hidden wifi only show like this:
                   scan start
                   scan done
                   31 networks found
                   1:  (-41)0-*
                   2: KHK Group (-62)9-*
                   3: dmarina (-68)7-*
                   4: Tower 1 (-68)7-*

the first device is the hidden slave. and also it showing 0 string length...
i tried with LoRa (TTGO LoRa32, 433Mhz), the problem i meet the loss packet chance quite high. I just want to try do a data send and receive on ESP. other than BLE and LoRa, do u guys have any suggestion?

**Comment by atanisoft** [comment]
ESP-Now is not from arduino-esp32, this issue should be transferred to https://github.com/espressif/esp-idf
