### ISSUE TITLE
ESP-32-can-not-support-its-wifi-maximum-range-when-a-mqtt-server-is-also-running-simultenously

### ISSUE THREAD

**Issue by MAINAKMONDAL98** [espressif/arduino-esp32#2886]
I noticed that my esp 32 is disconnected from mqtt server when the hotspot is far away from esp 32.
If I switched off my hotspot then the esp 32 is disconnected from internet and stops all the linked features.
Then when I turned on the hotspot,it again connected and started all the server client relationship.
If I am providing my hotspot from long distance to esp it is coonected with wifi but failed to coonect with mqtt server.
client.state() ==-2 or -3.
If I take esp closer to hotspot it reconnected and client.state()==0
It again rebuild the pubsubclient relationship
I attached four pictures of all states in this repository.
https://github.com/MAINAKMONDAL98/ESP-32-can-not-support-its-wifi-maximum-range-when-a-mqtt-server-is-also-running-simultenously
https://github.com/MAINAKMONDAL98/ESP-32-can-not-support-its-wifi-maximum-range-when-a-mqtt-server-is-also-running-simultenously/blob/master/HOTSPOT%20FROM%20LONG%20RANGE%20AND%20MQTT%20DISCONNECTED.png
https://github.com/MAINAKMONDAL98/ESP-32-can-not-support-its-wifi-maximum-range-when-a-mqtt-server-is-also-running-simultenously/blob/master/HOTSPOT%20FROM%20SMALL%20RANGE%20THEN%20MQTT%20CONNECTED.png

**Comment by MAINAKMONDAL98** [comment]
https://github.com/MAINAKMONDAL98/ESP-32-can-not-support-its-wifi-maximum-range-when-a-mqtt-server-is-also-running-simultenously

**Comment by atanisoft** [comment]
Pictures without code is not meaningful. Very likely it has nothing to do with MQTT but instead WiFi signal strength being weak when the hotspot is far away.
