### ISSUE TITLE
Arduino install Esp32 and Esp8266 Boards Manager problem

### ISSUE THREAD

**Issue by electrocoder** [espressif/arduino-esp32#2889]
Hi maker.
I want to esp8266 and esp32 board install Arduino IDE. Problem is only esp8266 or esp32 in view.  Only the last one is displayed.

Thanks.

### Hardware:
Board:							ESP32 and ESP8266
IDE name:							Arduino IDE 1.8.9
Computer OS:                                            Ubuntu 18.04.2 LTS 64 bit

**Comment by lbernstone** [comment]
It is definitely possible to have both.  Can you run the following from a terminal prompt:
`
ls ~/.arduino15/packages/esp8266/hardware/esp8266/*/boards.txt
ls ~/.arduino15/packages/esp32/hardware/esp32/*/boards.txt
`

**Comment by electrocoder** [comment]
e@e:~$ ls ~/.arduino15/packages/esp8266/hardware/esp8266/*/boards.txt
/home/e/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/boards.txt
e@e:~$ ls ~/.arduino15/packages/esp32/hardware/esp32/*/boards.txt
/home/e/.arduino15/packages/esp32/hardware/esp32/1.0.2/boards.txt
e@e:~$

**Comment by atanisoft** [comment]
How did you install the boards? Did you use the board manager option? If so, did you list both esp32 and esp8266 json files with a comma separator?

**Comment by electrocoder** [comment]
I didn't separate json files with commas. I'm trying now.

**Comment by electrocoder** [comment]
Solved. Thank you.
