### ISSUE TITLE
ESP series WiFi cache BUG (including ESP8266)

### ISSUE THREAD

**Issue by mxlbb** [espressif/arduino-esp32#2895]
The cache cannot be cleared using Scan Network and Smart Distribution Network in the Arduino sample project.
Performance: If you use these two features before the wireless LAN is not connected, then WiFi multiple scans will be the same result. The scan result is cleared only after rebooting or connecting to the wireless network again.
This bug has not been debugged with the ESPRESSIF development tool.
I hope to solve it as soon as possible, thank you!

**Comment by atanisoft** [comment]
@mxlbb do you have a reproducible test case? Also please follow the [issue template](https://github.com/espressif/arduino-esp32/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
