### ISSUE TITLE
Watchdog is not enabled by default

### ISSUE THREAD

**Issue by toomasz** [espressif/arduino-esp32#2911]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.2
IDE name:						Visual Micro
Flash Frequency:					40Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Windows 10

### Description:
Watchdog is not triggerred when i create endless while loop inside loop() method

### Sketch: 
```cpp

void setup()
{
	Serial.begin(115200);
	Serial.println("setup");
}

void loop()
{
	while (true)
	{
	}
}
```

**Comment by atanisoft** [comment]
It is intentionally disabled by default, you will need to call enableLoopWDT() in setup to enable it.

**Comment by toomasz** [comment]
@atanisoft do you know the reason why it's disabled by default? in arduino esp8266 its enabled

**Comment by atanisoft** [comment]
@toomasz you would need to ask @me-no-dev that one.

**Comment by GeorgeFlorian** [comment]
> @atanisoft do you know the reason why it's disabled by default? in arduino esp8266 its enabled

> so WDT is disabled in order to "help" run some code that is never meant to run on RTOS chip.

**Comment by atanisoft** [comment]
@GeorgeFlorian that is a quote taken out of context and is not why the WDT is not enabled by default.

**Comment by GeorgeFlorian** [comment]
> @GeorgeFlorian that is a quote taken out of context and is not why the WDT is not enabled by default.

I thought I could help.
Here's the context: https://github.com/me-no-dev/ESPAsyncWebServer/issues/524
