### ISSUE TITLE
How to read analog pin?

### ISSUE THREAD

**Issue by szerwi** [espressif/arduino-esp32#292]
Hi,
How to read from analog pins in ESP32? What should I type in analogRead()? What pin?

**Comment by me-no-dev** [comment]
the pin that you want to read. pins that support analog are shown in the image in this repository's README

**Comment by szerwi** [comment]
I was trying but when I connected some resistors I had only value 0 or 4056.

**Comment by me-no-dev** [comment]
what did you try? which pin? show some code :)

**Comment by szerwi** [comment]
float odczyt;

void setup() 
{
  // put your setup code here, to run once:
  Serial.begin(115200);

}

void loop() 
{
  odczyt = analogRead(A4);
  Serial.println(odczyt);
  delay(1000);
}


If I give "4" instead of "A4" it's writing 0 on all pins.

**Comment by copercini** [comment]
Your wire is connected in GPIO32 or GPIO04 for use "A4"?

**Comment by szerwi** [comment]
32 and it's giving only 0 or 4095 value.

**Comment by copercini** [comment]
What is your circuit?

**Comment by szerwi** [comment]
2 pins from potentiometer are connected first to Vcc second to GND and middle pin to analog pin. I'm checking the same with Arduino and value is only 0 or 1023 so I connected something wrong :/

**Comment by szerwi** [comment]
Oh, it's working mow! :D Before I had only 1 pin to Vcc and another to analog pin. When I connected one to Vcc, second to GND and third to analog it's working :D

**Comment by copercini** [comment]
=)
