### ISSUE TITLE
Off-by-one Error In RMT Example

### ISSUE THREAD

**Issue by tedhenry100** [espressif/arduino-esp32#2921]
In https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/RMT/RMTWriteNeoPixel/RMTWriteNeoPixel.ino lines 64 and 65 there is an off by one error.

The shift is too much. for the first iteration of the loop `1<<(8-0)` is `100000000` which is not the desired bit mask. The desired bit mask is `1000000`. It should be `1<<(7-0)`

            for (bit=0; bit<8; bit++){
                if ( (color[col] & (1<<(8-bit))) && (led == led_index) ) {

There is a comment from @VerusLogic in the related commit about this problem.

https://github.com/espressif/arduino-esp32/commit/4e96bffe0ef0e3929ba0ecf540c9c6f299b31e14#diff-e59a7abf6f432b9f3d716a15f5f9b715

@david-cermak

**Comment by david-cermak** [comment]
Hi @tedhenry100 

sorry for such a late response.
Yes, there's an off by one error, thanks for noting! Posted a [PR](https://github.com/espressif/arduino-esp32/pull/2986)
