### ISSUE TITLE
How to feed WDT inside a while loop ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [espressif/arduino-esp32#2922]
Board: ESP32 DevKitV4 Wrover-B
OS: Linux Mint 19.1

Hello !

I am experiencing issues with `enableCore1WDT();`. I am trying to set this WDT to keep the ESP32 from becoming unresponsive whenever ESPAsyncWebServer decides to hangs or freeze. I was advised to do so by me-no-dev. The problem is that this, for me, is uncharted territory.

I dropped `enableCore1WDT();` at the beginning of `void setup()`:
```
void setup() {
  Serial.begin(115200);
  delay(1000);
  enableCore1WDT();
//...
```

I'm using a function that starts the AP:
```
void startAP() {  
  delay(50);
  logOutput((String)"Starting AP ... ");
  logOutput(WiFi.softAP(ssidAP, passwordAP) ? "Ready" : "WiFi.softAP failed ! (Password must be at least 8 characters long )");
  delay(500);
  logOutput((String)"Setting AP configuration ... ");
  logOutput(WiFi.softAPConfig(local_IP_AP, local_IP_AP, subnetAP) ? "Ready" : "Failed!");
  delay(500);
  logOutput((String)"Soft-AP IP address: ");
  logOutput(WiFi.softAPIP().toString());
  // digitalWrite(LED, HIGH);
  delay(500);
  while (WiFi.softAPgetStationNum() == 0) {
    matrix->clear();
    matrix->setFont(NULL);
    matrix->setCursor(1,8);
    matrix->setTextColor(LED_PURPLE_HIGH);
    matrix->print((String)ssidAP);   
    matrix->setTextColor(LED_CYAN_HIGH);
    matrix->setCursor(1,0);
    matrix->print("Connect to");
    matrix->setCursor(1,16);
    matrix->print("Wireless");
    matrix->setCursor(1,24);
    matrix->print("Network"); 
    matrix->show();
  }
//...
}
```

This is where the WDT gets caught up and reboots the ESP.

The thing is that I need that while. But the WDT gets triggered by it.

How can I peace them out ?

**Comment by GeorgeFlorian** [comment]
The answer is that you can add a `delay()` inside a `while` loop and that will let other tasks run.

**Comment by pfeerick** [comment]
It doesn't need to be much of a delay either... a `delay(1)` should be enough to let the the underlying RTOS do it's thing. That, or is `yield()` a thing on the ESP32 also? Basically, anything that prevents the watchdog from being fed for any length of time (can't remember... is it 500ms?) ... is likely to end in grief and exceptions.

**Comment by pfeerick** [comment]
Oh... a matrix will colours... I'm running a couple of red led matrix panels... 7219 based... with ESP8266s... what ones are they, and what library do you use with them?

**Comment by GeorgeFlorian** [comment]
> It doesn't need to be much of a delay either... a `delay(1)` should be enough to let the the underlying RTOS do it's thing. That, or is `yield()` a thing on the ESP32 also? Basically, anything that prevents the watchdog from being fed for any length of time (can't remember... is it 500ms?) ... is likely to end in grief and exceptions.

`yield()` did not work.

I am using an ESP32 DevKitV4 Wrover-B that drives a SMD 2727 RGB LED Panels using https://github.com/pixelmatix/SmartMatrix/tree/teensylc
On top of that I also have https://github.com/marcmerlin/SmartMatrix_GFX for added functionality.

**Comment by gearsincorg** [comment]
I agree.  yield() does not work.

It would be nice if you could call delay(0) and JUST have it to a task yield without incurring any extra un-needed delay.
Currently delay(0) just returns and does not feed the WDT.

**Comment by me-no-dev** [comment]
it would, but since the task that you are trying to yield to (and feed WDT) is lower priority than the one you are in, you need to delay for more than one RTOS tick in order to make sure that the scheduler will switch to it. `delay(2)` will do exactly that (Arduino uses 1kHz RTOS tick)

**Comment by gearsincorg** [comment]
Ah...that helps to explain some other interesting timing I was seeing.   
Question: I know where the ESP-IDF reference is, but is there somewhere that covers the Arduino implementation (and explains things like the clock and the default cores and priorities)?
