### ISSUE TITLE
ESP32 Web Camera Test Guru Error 

### ISSUE THREAD

**Issue by CyborgAsh12** [espressif/arduino-esp32#2930]
Im using the camera web server test, but i get this message in output

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4000c2f9  PS      : 0x00060930  A0      : 0x800f9585  A1      : 0x3ffe3460  
A2      : 0x3ffe3494  A3      : 0xc2248360  A4      : 0x0000000c  A5      : 0x3ffe3494  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffe3430  
A10     : 0x3ffaff10  A11     : 0x000000f0  A12     : 0x3ffe3800  A13     : 0x3ffe39f0  
A14     : 0x400a0000  A15     : 0x00000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0xc2248360  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

How do I solve this?

**Comment by lbernstone** [comment]
Please use https://github.com/espressif/arduino-esp32/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
