### ISSUE TITLE
ESP32 - Bug Issue - Power Reset needed

### ISSUE THREAD

**Issue by thinkispossible** [espressif/arduino-esp32#2936]
I have a problem on my ESP32-WROOM-32.
My project is a Smart Lighting over Wi-Fi and maybe Bluetooth with 60 Neopixels (on D4 pin) but my board doing something strange.

When my board doesn't get any http command about luminosity, speed, color or effects over Wi-Fi for 1 hour or more, the light take a very bright white color and the board no longer responds to http commands over Wi-Fi.

I try to get any information over USB Serial Interface but I didn't get any information.

The board temperature is normal.

So I heard about the deep sleep mode of the ESP32, I think this is maybe that.

**Comment by EricMc1289** [comment]
I do the same with Neopixels and there is no bug like this. 
About deepsleep, this function normally must be called directly from code. 
Without code it is not possible to figure out the error.
