### ISSUE TITLE
DRAM segment data does not fit, but using PROGMEM

### ISSUE THREAD

**Issue by ivoras** [espressif/arduino-esp32#2943]
### Hardware:
Board:							DEVKIT 1
Core Installation version:			1.0.2
IDE name:						Arduino IDE
PSRAM enabled:                                    no
Computer OS:                                        Windows 10

### Description:

I have a couple of large structures - byte arrays of parts of a web page actually, which I thought I'd serve from PROGMEM via AsyncWebServer.

However, I get the "DRAM segment data does not fit" error -- which confuses me because:

1. The data is less than 100 KiB in size and I have more than 200 KiB of free memory even if it were to fit in RAM
2. The structures are declared with PROGMEM, which I thought would mark them for inclusion into the code portions of flash, not loaded into RAM.

So... why does this happen?

EDIT: more details:

If I just comment out a reference (in AsyncWebServerResponse) to a 23 KiB data structure, the result of the compilation is:

```
Sketch uses 886386 bytes (67%) of program storage space. Maximum is 1310720 bytes.
Global variables use 108240 bytes (33%) of dynamic memory, leaving 219440 bytes for local variables. Maximum is 327680 bytes.
```

I read this as more than 400 KiB of program storage and more than 200 KiB of dynamic RAM available. If I simply remove the comment, the original error appears.

EDIT2: That's strange: adding PROGMEM to the declaration of the large array does nothing to the numbers above.

### Sketch:  
```
unsigned char bootstrap.min.css[] PROGMEM = {
...
};

...


  web.on("/bootstrap.min.css", HTTP_GET, [](AsyncWebServerRequest *req) {
    Serial.println("Got request for boostrap.min.css");
    AsyncWebServerResponse *resp = req->beginResponse_P(200, "text/css", bootstrap_min_css_gz, bootstrap_min_css_gz_len);
    resp->addHeader("Content-Encoding", "gzip");
    req->send(resp);
  });
```

### Debug Messages:
```

c:/users/ivoras/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-80-g6c4433a-5.2.0/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\ivoras\AppData\Local\Temp\arduino_build_459698/SevenBoard1.ino.elf section `.dram0.bss' will not fit in region `dram0_0_seg'

c:/users/ivoras/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-80-g6c4433a-5.2.0/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: DRAM segment data does not fit.

c:/users/ivoras/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-80-g6c4433a-5.2.0/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `dram0_0_seg' overflowed by 8456 bytes
```

**Comment by lbernstone** [comment]
PROGMEM is just a [compatibility word in esp32](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/pgmspace.h#L32).  Use the [Preferences library](https://github.com/espressif/arduino-esp32/tree/master/libraries/Preferences) to store data in flash (the NVS partition).

**Comment by atanisoft** [comment]
@lbernstone he is embedding a file in the code not trying to store it in nvs/flash. Progmem is fine for this.

The issue though is there is something tagged as DRAM_ATTR that is exceeding the capacity of the dram segment declared in the ld file.

**Comment by ivoras** [comment]
Nope, see EDIT2 above, and the memory sizes reported by the compiler.

OTOH, declaring the data as const together with PROGMEM works, in the sense that it doesn't get counted in "dynamic memory". 

That makes sense since, per ibernstone's link, PROGMEM is a no-op on ESP32.

**Comment by ivoras** [comment]
I'll close this issue with that conclusion: PROGMEM is no-op on ESP32, it does nothing. Declaring a variable as const does something similar to what PROGMEM does in other platforms, makes the data reside in flash until it's needed, without special handling.
