### ISSUE TITLE
Stuck at mbedtls_err_ssl_want_write()

### ISSUE THREAD

**Issue by thedim-witted** [espressif/arduino-esp32#2956]
### Hardware:
Board:							?ESP32 Dev Module?
Core Installation version:			1.0.2
IDE name:						?Arduino IDE?
Flash Frequency:					?40Mhz?
PSRAM enabled:                                     ?yes?
Upload Speed:					?115200?
Computer OS:                                        ?Windows 10?

### Description:

I am using the esp32 to upload a JSON packet to a server. However, after some time the code seems to get stuck with the ret as mbedtls_err_ssl_want_write. I tried putting in a line which calls the ssl_write function again but it is only writing about 1-2 bytes at a time and is getting stuck at that for a very long time. Also, I have noticed that the heap memory is not renewing after the ssl connection. The function ssl_free_cert is getting called but the heap is not getting reset and it is constantly decreasing every cycle.

I tried debugging but wasn't able to view the source of the functions so I'm stuck.

**Comment by lbernstone** [comment]
CSB. If you actually want some help, make a minimal sketch.  If you are working from the [esp-idf example](https://github.com/espressif/esp-idf/blob/v3.2.2/examples/protocols/https_mbedtls/main/https_mbedtls_example_main.c), you may get more traction asking your question there.

**Comment by thedim-witted** [comment]
Reproduced this from the WiFiClientSecure example code

`#include <ArduinoJson.h>
#include <WiFiClientSecure.h>

const char* ssid     = "xxxxxxxxx";     // your network SSID (name of wifi network)
const char* password = "xxxxxxxxxx"; // your network password

const char*  host = "xxxxxxxxx";  // Server URL
const char* url   = "/xxxxxxxxx";
const char* fingerprint = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
int connection_iterator;
int SAMPLE_SIZE = 350;
uint64_t chipid;
uint32_t low;
uint32_t high;

WiFiClientSecure client;

void setup() {
  //Initialize serial and wait for port to open:
  Serial.begin(115200);
  delay(100);
  chipid = ESP.getEfuseMac();
  low = chipid % 0xFFFFFFFF;
  high = (chipid >> 32) % 0xFFFFFFFF;
  Serial.println(String(low, HEX) + String(high, HEX));
  Serial.println("2002");

  pinMode(2, OUTPUT);
  digitalWrite(2, LOW);
}

DynamicJsonBuffer jsonBuffer(14700);

void loop() {
  connection_iterator = 0;

  WiFi.begin(ssid, password);

  //   attempt to connect to Wifi network:
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    // wait 1 second for re-trying
    delay(1000);
  }

  Serial.print("Connected to ");
  Serial.println(ssid);

  jsonBuffer.clear();
  JsonObject &rootObject = jsonBuffer.createObject();
  JsonObject &dataObject = rootObject.createNestedObject("data");
  JsonArray &X1dataObject = dataObject.createNestedArray("X1");
  JsonArray &Y1dataObject = dataObject.createNestedArray("Y1");
  JsonArray &Z1dataObject = dataObject.createNestedArray("Z1");
  Serial.print("Heap:  ");
  Serial.println((int)esp_get_free_heap_size());


  for (int iterator = 0; iterator < SAMPLE_SIZE; iterator++) {
    X1dataObject.add(iterator*0.1);
    Y1dataObject.add(iterator*0.2);
    Z1dataObject.add(iterator*0.3);
  }


  rootObject["coreid"] = String(low, HEX) + String(high, HEX);
  //rootObject["coreid_high"] = String(high, HEX);
  rootObject["sample_time"] = 554;
  rootObject["firmware_version"] = 2002;
  rootObject.prettyPrintTo(Serial);

  Serial.print("connecting to ");
  Serial.println(host);

  while ((!client.connect(host, 443))) {
    connection_iterator++;
    Serial.println("connection failed! Retrying..");
    delay(5000);

    if (connection_iterator >= 10)
      ESP.restart();
  }
    digitalWrite(2, HIGH);
  Serial.print("requesting URL: ");
  Serial.println(url);
  client.println(String("POST ") + url + " HTTP/1.1");
  client.println(String("Host: ") + host);
  client.println("Cache-Control: no-cache");
  client.println("Content-Type: application/json");
  client.print("Content-Length: ");
  client.println(rootObject.measureLength());
  client.println();
  rootObject.printTo(client);
  Serial.println("request sent");
  //  free(NULL);
  connection_iterator = 0;
  while ((client.connected())) {
    String line = client.readStringUntil('\n');
    connection_iterator++;
    if (line == "\r") {
      Serial.println("headers received");
      break;
    }
    Serial.println("Waiting for Headers");
    delay(500);
    if (connection_iterator > 30)
      break;
  }
  String line = client.readStringUntil('\n');
  if (line.startsWith("{")) {
    Serial.println("esp32/Arduino CI successfull!");
//    successfull_attempts++;
  } else {
    Serial.println("esp32/Arduino CI has failed");
  }
  Serial.println("reply was:");
  Serial.println("==========");
  Serial.println(line);
  Serial.println("==========");
  Serial.println("closing connection");
  digitalWrite(2, LOW);
}`

**Comment by lbernstone** [comment]
Scoping matters.  Calling WiFi.begin every loop is not going to help your cause.
```
#include <ArduinoJson.h>
#include <WiFiClientSecure.h>

//const char* ssid = "xxxxxxxxx"; // your network SSID (name of wifi network)
//const char* password = "xxxxxxxxxx"; // your network password

const char* host = "www.google.com"; // Server URL
const char* url = "/";
int connection_iterator;
int SAMPLE_SIZE = 350;
uint32_t low;
uint32_t high;

WiFiClientSecure client;

void setup() {
//Initialize serial and wait for port to open:
  Serial.begin(115200);
  delay(100);
  uint64_t chipid = ESP.getEfuseMac();
  low = chipid % 0xFFFFFFFF;
  high = (chipid >> 32) % 0xFFFFFFFF;
  Serial.println(String(low, HEX) + String(high, HEX));
  Serial.println("2002");
  
  pinMode(2, OUTPUT);
  digitalWrite(2, LOW);

  WiFi.begin();
  if (!WiFi.waitForConnectResult()) {
    Serial.println("Connection failed");
    return;  
  }
  Serial.print("Connected to ");
  Serial.println(WiFi.SSID());  
}

void jsonOut() {
  DynamicJsonBuffer jsonBuffer(14700);
  connection_iterator = 0;
  
  jsonBuffer.clear();
  JsonObject &rootObject = jsonBuffer.createObject();
  JsonObject &dataObject = rootObject.createNestedObject("data");
  JsonArray &X1dataObject = dataObject.createNestedArray("X1");
  JsonArray &Y1dataObject = dataObject.createNestedArray("Y1");
  JsonArray &Z1dataObject = dataObject.createNestedArray("Z1");
  Serial.printf("Heap: %d\n", esp_get_free_heap_size());
  
  for (int iterator = 0; iterator < SAMPLE_SIZE; iterator++) {
    X1dataObject.add(iterator*0.1);
    Y1dataObject.add(iterator*0.2);
    Z1dataObject.add(iterator*0.3);
  }
  
  rootObject["coreid"] = String(low, HEX) + String(high, HEX);
  //rootObject["coreid_high"] = String(high, HEX);
  rootObject["sample_time"] = 554;
  rootObject["firmware_version"] = 2002;
  rootObject.prettyPrintTo(Serial);
  
  client.println(rootObject.measureLength());
  client.println();
  rootObject.printTo(client);
}

void loop() {
  Serial.print("connecting to ");
  Serial.println(host);
  
  while ((!client.connect(host, 443))) {
    connection_iterator++;
    Serial.println("connection failed! Retrying..");
    delay(5000);
    
    if (connection_iterator >= 10)
      ESP.restart();
    }
    digitalWrite(2, HIGH);
    Serial.print("requesting URL: ");
    Serial.println(url);
    client.println(String("POST ") + url + " HTTP/1.1");
    client.println(String("Host: ") + host);
    client.println("Cache-Control: no-cache");
    client.println("Content-Type: application/json");
    client.print("Content-Length: ");
    jsonOut();
    Serial.println("request sent");
    connection_iterator = 0;
    while (client.connected()) {
      String line = client.readStringUntil('\n');
      connection_iterator++;
      if (line == "\r") {
        Serial.println("headers received");
        break;
      }
      Serial.println("Waiting for Headers");
      delay(500);
      if (connection_iterator > 30) break;
    }
    String line = client.readStringUntil('\n');
    if (line.startsWith("{")) {
      Serial.println("esp32/Arduino CI successfull!");
      // successfull_attempts++;
    } else {
      Serial.println("esp32/Arduino CI has failed");
    }
  Serial.println("reply was:");
  Serial.println("==========");
  Serial.println(line);
  Serial.println("==========");
  Serial.println("closing connection");
  digitalWrite(2, LOW);
}
```

**Comment by thedim-witted** [comment]
It's great that you restructured my test code. Thank You. However, this doesn't solve the issue. Also, I am getting this particular more often than getting stuck in the mbedtls_err_ssl_want_write() function


>21:11:13.151 -> [V][ssl_client.cpp:280] send_ssl_data(): ret < 0
>21:11:13.151 -> [E][ssl_client.cpp:33] handle_error(): UNKNOWN ERROR CODE (0050)
>21:11:13.151 -> [E][ssl_client.cpp:35] handle_error(): MbedTLS message code: -80
>21:11:13.184 -> [V][ssl_client.cpp:243] stop_ssl_socket(): Cleaning SSL connection.
