### ISSUE TITLE
Pinchange interrupt during eeprom write -> crash.

### ISSUE THREAD

**Issue by PepeTheFroggie** [espressif/arduino-esp32#2984]
Describe your system( Hardware, computer, O/S, core version, environment).
esp32, arduino ide

Describe what is failing.
Pinchange interrupt during eeprom write -> crash.

Show the EXACT error message(it doesn't work is not enough).
Guru Meditation Error: Core 1 panic'ed (Cache disabled but cached memory region accessed)
Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40149a4c: bad00bad bad00bad bad00bad

Detaching IR, writing eeprom and reenabling IR does fix the problem.

Oh, btw pinchange interrupt "rising" or "falling" doesent work anyway, its always "change". 
Ran into that problem "mid air" with this https://www.esp32.com/download/file.php?id=3320

**Comment by lbernstone** [comment]
See https://github.com/espressif/arduino-esp32/issues/2953.  Also, please test with the [1.0.3-rc1 version](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md), which uses nvs instead of spi flash to emulate eeprom.
