### ISSUE TITLE
example / description of using pcnt.h

### ISSUE THREAD

**Issue by SALLDHMF** [espressif/arduino-esp32#2985]
Can I find an example / description of using pcnt.h (https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/pcnt.h) somewhere? I need to count the frequency of pulses on one of the ESP 32 inputs without using interrupts.

**Comment by lbernstone** [comment]
There is no arduino-esp32 HAL for the pcnt peripheral, so you will need to use the esp-idf functions. https://github.com/espressif/esp-idf/tree/master/examples/peripherals/pcnt

**Comment by SALLDHMF** [comment]
Thanks a lot
