### ISSUE TITLE
Can't seem to use gpio10

### ISSUE THREAD

**Issue by AEnimaH** [espressif/arduino-esp32#299]
The pin with label FLASH D3 which corresponds to GPIO10 does not work with DigitalWrite, is this correct?

When I do this in my code:
pinMode(10, OUTPUT);

Response on serial:

![schermafbeelding 2017-04-05 om 11 55 05](https://cloud.githubusercontent.com/assets/17111933/24700229/c596f5e6-19f6-11e7-92db-317105939325.png)

**Comment by me-no-dev** [comment]
Yes it is. That pin (as labeled) is connected to the flash memory chip, so when you try to do something, you break the sketch
