### ISSUE TITLE
http update needs authentication

### ISSUE THREAD

**Issue by fabltd** [espressif/arduino-esp32#2993]
It appears there is no way to added authentication to http/https update?

Suggest an optional for a token / secret.

**Comment by lbernstone** [comment]
The WebServer manages authentication.  Examples are included in the [library](https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer/examples).

**Comment by fabltd** [comment]
This is for the t_httpUpdate_return ret = httpUpdate.update(client, server); method. There is no way to specify authentication.

**Comment by collin80** [comment]
What kind of auth do you need? Basic where it sends in plaintext? Or digest perhaps? There are examples out there for doing auth but you're right, they don't seem to be integrated into the core library HTTPClient like you'd want/hope for them to be. In particular, digest is a pain but code does exist to do it externally of the HTTPClient library.

**Comment by fabltd** [comment]
I was thinking JWT. Currently I have a work around by passing a JWT in the current version param. There should be an extra option when declaring the instance for example: String &authKey

**Comment by atanisoft** [comment]
@fabaff feel free to submit a PR to add auth to the HTTPUpdate library..
