### ISSUE TITLE
analogRead() not implemented

### ISSUE THREAD

**Issue by vshymanskyy** [espressif/arduino-esp32#3]

**Comment by me-no-dev** [comment]
will be when the driver is ready

**Comment by keith204** [comment]
Is there a rough timeline of when that driver will be ready?

**Comment by igrr** [comment]
Should be ready in ESP-IDF 1.0, which is planned for release at the end of the month.

**Comment by keith204** [comment]
Thanks Ivan.  

I won't hold you to it, but I'll stop checking hourly until later this month.

**Comment by jrobeson** [comment]
analogRead is now implemented

**Comment by me-no-dev** [comment]
yup :)
