### ISSUE TITLE
Ticker not implemented

### ISSUE THREAD

**Issue by forthlightning** [espressif/arduino-esp32#30]
My sketch is in large part based on [Ticker.h](https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/libraries/Ticker/Ticker.h) in the Arduino core for the esp8266. Any idea when this library will be implemented on the 32?

**Comment by iAchyut** [comment]
How can I implement Ticker.h for my ESP32 ?

**Comment by forthlightning** [comment]
I use timers: http://www.freertos.org/FreeRTOS-Software-Timer-API-Functions.html

There is a bit more code for configuration but they work nicely.

**Comment by lonerzzz** [comment]
I ported my code over to using FreeRTOS as well and it works quite reasonably.

**Comment by sansillusion** [comment]
Any news on that ?
It would make it easier to code rather than using if conditions to detect esp8266 or esp32 etc...

**Comment by bertmelis** [comment]
If you want backward (of is it forward?) compatibility you can use a quick and dirty library: https://github.com/bertmelis/Ticker-esp32

**Comment by copercini** [comment]
Closed due it was implemented here: https://github.com/espressif/arduino-esp32/pull/1057
