### ISSUE TITLE
Flash frequency affects WiFi and BLE functionality

### ISSUE THREAD

**Issue by Smrtokvitek** [espressif/arduino-esp32#301]
I have the "HIMALAYA ESP32" board and I tried the arduino-esp32 but with strange behaviour. When I set the cpu frequency to 80MHz any example from WiFi and BLE causes CPU halt. If I use 40MHz option WiFi works but the BLE still causes CPU halt.

Can it be possible HW problem (design flaw maybe)?

![](https://eckstein-shop.de/media/image/product/11891/lg/himalaya-esp32-dev-board-wifi-bluetooth-cp2102-usb-to-serial-mit-lipo-charger~8.jpg)

**Comment by me-no-dev** [comment]
CPU or Flash frequency? I think you are talking about flash frequency and that depends on the chip used. Generally it should not upset the WiFi/BT stacks regardless of the setting

**Comment by Smrtokvitek** [comment]
You are right, my bad I'm used to change the cpu frequency from that kind of menu for different Arduino boards. Nevertheless it acts like I've described it. So is it possible the esp module is bad?

**Comment by me-no-dev** [comment]
Try giving it a better power source, use better USB cable, things like that might help. The module is probably OK, but it's badly powered

**Comment by Smrtokvitek** [comment]
I've tried different cable and different power source. It is the same. It looks like I cannot make it work on 80MHz. 40MHz setting is working now.

I found out why the `ble` halts the CPU. I have to put `WiFi.mode(WIFI_STA)` before first `ble.begin` command and  then it works even if I don't want to use the wifi.

**Comment by me-no-dev** [comment]
great and strange at the same time (about the flash frequency) :)

**Comment by gggabo** [comment]
@Smrtokvitek hello, you have any example to code, please.
