### ISSUE TITLE
OTA dual core question

### ISSUE THREAD

**Issue by atlask1** [espressif/arduino-esp32#3017]
Hi,
I have a question: what happen if I permorm OTA and I'm using dual core or the new sketch from OTA use dual core? 
OTA need one core free? 
thanks

**Comment by lbernstone** [comment]
OTA uses cpu cycles from whatever transport mechanism you are using (wifi, bluetooth, uart, etc).  The OTA firmware update process itself is simply an MD5 checksum, and marking the new firmware as active.  It behaves essentially the same with single core or dual.

**Comment by atlask1** [comment]
Ok, thanks .
I’ve tested now. It’s ok . 
But it’s possible also via BLE?

**Comment by atanisoft** [comment]
@atlask1 OTA over BLE is possible. One example which uses ESP-IDF APIs: https://github.com/chegewara/esp32-ota-with-ble-setup. There are very likely other examples to be found via GitHub search...
