### ISSUE TITLE
I2S

### ISSUE THREAD

**Issue by alecapu80** [espressif/arduino-esp32#302]
When will be available a I2S library for recording and playback via I2S bus like: 
https://www.arduino.cc/en/Reference/I2S ??

**Comment by me-no-dev** [comment]
I have something similar already working but it's not ready for release.

**Comment by alecapu80** [comment]
Can you send it to me to study it and try to understand how to use I2S???

2017-04-06 10:27 GMT+02:00 Me No Dev <notifications@github.com>:

**Comment by filipeaguiar22** [comment]
I am also interested in the code. I would like to parse A2DC to I2S  data.
If you could share the code, it would be a great advance, for me.

**Comment by alecapu80** [comment]
@me-no-dev can't you provide us your working code? We can be useful for testing, improving, etc etc

**Comment by chenkaiyao** [comment]
@ me-no-dev can you release the I2S library! it is very important funtion to us

**Comment by me-no-dev** [comment]
I will when it's done. Currently I have other urgent things to take care of :)
You can use IDF's API through Arduino also.
https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/i2s.h

**Comment by AdySan** [comment]
Here's a good esp-idf project that uses i2s audio https://github.com/MrBuddyCasino/ESP32_MP3_Decoder

**Comment by alecapu80** [comment]
Yes I know but this is a play example (output). There isn't a recording (input) example? ???

**Comment by NickWaterton** [comment]
Just FYI, I have a test i2s input program working using two ics43434 i2s microphones (left and right).

**Comment by alecapu80** [comment]
Have you some sample code??
Thank you

Il 12 Giu 2017 01:25, "NickWaterton" <notifications@github.com> ha scritto:

**Comment by DaTebe** [comment]
Is there now an input example?
