### ISSUE TITLE
Is there any way to communicate trought Ethernet/IP protocol with esp32?

### ISSUE THREAD

**Issue by zekageri** [espressif/arduino-esp32#3022]
I wonder if it is possible somehow with async tcp lib or somehow else.
I want ot communicate with a PLC wich is uses the Ethernet/IP protocoll.
I don't know much about this protocoll but i know that i have to send some kind of a xml or gsd file where i list the data properties like the length and type etc..

**Comment by lbernstone** [comment]
Yes
This forum is for issues with the arduino-esp32 codebase.  It is not for tutorials, or asking someone to write your code.

**Comment by zekageri** [comment]
> Yes
> This forum is for issues with the arduino-esp32 codebase. It is not for tutorials, or asking someone to write your code.

I know. Sorry. Do you know where can i ask a question like this?

**Comment by lbernstone** [comment]
https://esp32.com
