### ISSUE TITLE
Feature request: need handlerFunction for IP_EVENT_AP_STAIPASSIGNED

### ISSUE THREAD

**Issue by ThinkalVB** [espressif/arduino-esp32#3023]
https://github.com/espressif/esp-idf/pull/3605
When a station connects to the softAP I think the IP address assigned to the station is very much important. However, the event handler only gives us the MAC address and the aid that ESP32 soft-AP gives to the station. If we can access the IP when a station connects to the AP that would be a great feature we can use.

**Comment by atanisoft** [comment]
@ThinkalVB if/when the referenced PR has been merged to ESP-IDF *AND* it has reached a STABLE release (ie: 3.2, 3.3, etc) it will become available automatically in arduino-esp32. There will not be any specific work to be done as the event data is transparently passed through to the handler.
