### ISSUE TITLE
upload error if GPIO2 connect VCC

### ISSUE THREAD

**Issue by ouki-wang** [espressif/arduino-esp32#303]
VCC--R--GPIO2

**Comment by igrr** [comment]
GPIO2 is a bootstrapping pin; in download mode, it must be low on reset. It has an internal weak pulldown, but if you pull it up externally the chip will not be able to enter download mode.
Newer boards such as Wrover-Kit v3 pull down GPIO2 same way the pull down GPIO0, when entering download mode.
Closing this as this is not a software related issue.
