### ISSUE TITLE
Serial2.end() not reseting GPIO17

### ISSUE THREAD

**Issue by ionini** [espressif/arduino-esp32#3032]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			Latest?
IDE name:						None.
Flash Frequency:					40Mhz
PSRAM enabled:                                    yes
Upload Speed:					115200
Computer OS:                                        Mac OSX

### Description:
When calling Serial2.begin(9600); then Serial2.end() the GPIO17 pin is disabled and not usable for GIO.

I found that calling gpio_reset_pin(GPIO_NUM_17); is the only way to regain control over GPIO17.

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
  // This works.
  pinMode(17, OUPUT);
  digitalWrite(17, HIGH);
  digitalWrite(17, LOW);
  pinMode(17, INPUT);

  // This also works.
  Serial2.begin(9600);
  Serial2.write(1);
  delay(100);
  Serial2.flush();
  Serial2.end();

  
  // This does NOT work.
  pinMode(17, OUPUT);
  digitalWrite(17, HIGH);
  digitalWrite(17, LOW);
  pinMode(17, INPUT);



  gpio_reset_pin(GPIO_NUM_17);

  // This DOES work now.
  pinMode(17, OUPUT);
  digitalWrite(17, HIGH);
  digitalWrite(17, LOW);
  pinMode(17, INPUT);
}

void loop() {
}
```

**Comment by dmn8s5** [comment]
Thank you very much for this, it helped me solve an issue I was experiencing.
