### ISSUE TITLE
getCoreVersion()

### ISSUE THREAD

**Issue by hcs-svn** [espressif/arduino-esp32#305]
Will we get something like getCoreVersion() that we had for ESP8266?
Like getSdkVersion()

And getResetReason() + getResetInfo() would also be helpful

**Comment by me-no-dev** [comment]
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Esp.h#L63

Please use gitter to let me know that you want something and not file an issue. Looking through the headers might also answer your questions ;)
