### ISSUE TITLE
Esp32  flash read err, 1000 ets_main.c 371 rebooting

### ISSUE THREAD

**Issue by mmashraf** [espressif/arduino-esp32#3057]
I buy new ESP32 from Ali express and after first program of blink , it is continuously showing the sw_reset issue on serial port. i also try python esptool.py erase_flash but it does not work and also following error. I explore all forums but get no resolution and positive response to fix it. Please help me to sort it.

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371

**Comment by lbernstone** [comment]
Sounds like your code upload is failing
See https://github.com/espressif/arduino-esp32/issues/3036

**Comment by TheMrPhantom** [comment]
I had this problem after connecting 2 leds on different grounds, so maybe it's a wiring problem?
After connecting the leds to the same ground it worked properly again

**Comment by Mbonea-Mjema** [comment]
I have the same problem, I am even not able to erase the chip....

**Comment by hdpklm** [comment]
i have dthe same problem and fix it with changing the settings of programmer in Adruino IDE

i think is find start program from an address not exist in nand flash

![ESP SPI](https://user-images.githubusercontent.com/35699848/130322814-903d7e55-e1d2-4e7c-b152-cee9eda5be91.png)
