### ISSUE TITLE
Error compiling IDF gatt_server example.

### ISSUE THREAD

**Issue by tushaar** [espressif/arduino-esp32#306]
Trying to compile IDF gatt_server example on arudino IDE.

` esp_ble_gatts_add_char_descr(
        gl_profile_tab[PROFILE_APP_ID].service_handle,
        &gl_profile_tab[PROFILE_APP_ID].descr_uuid,
        ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE,
        NULL,
        NULL);`

In file included from /Users/tu/Desktop/BleDevice/BleDevice.ino:14:0:
/Users/tu/Documents/Arduino/hardware/espressif/esp32/tools/sdk/include/bluedroid/esp_gatts_api.h:393:11: note:   initializing argument 3 of 'esp_err_t esp_ble_gatts_add_char_descr(uint16_t, esp_bt_uuid_t*, esp_gatt_perm_t, esp_attr_value_t*, esp_attr_control_t*)'
 esp_err_t esp_ble_gatts_add_char_descr (uint16_t service_handle,
           ^
exit status 1
invalid conversion from 'int' to 'esp_gatt_perm_t' [-fpermissive]

Please help: Sorry in advance if this is a bad post.

**Comment by me-no-dev** [comment]
It says it in the error :) you need to cast the permissions to the correct type.
```cpp
esp_ble_gatts_add_char_descr( gl_profile_tab[PROFILE_APP_ID].service_handle, &gl_profile_tab[PROFILE_APP_ID].descr_uuid, (esp_gatt_perm_t)(ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE), NULL, NULL);
```
