### ISSUE TITLE
Why does restart because of power gives  16 14 as reasons?

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [espressif/arduino-esp32#3063]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.2
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Ubuntu

### Description:
When ESP is restarted due to power even then restart reason is shown as 16 14.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/494
