### ISSUE TITLE
UpdateClass::printError should take a Print instead of a Stream

### ISSUE THREAD

**Issue by ssilverman** [espressif/arduino-esp32#3067]
`UpdateClass::printError` should take a `Print` and not a `Stream`. It's not possible to pass in custom `Print` implementations without also implementing `Stream`.

See: https://github.com/espressif/arduino-esp32/blob/fa55a2c91d31eab673c0115bc57e9437350488cc/libraries/Update/src/Update.h#L81

**Comment by ssilverman** [comment]
Any word on this? (Just pinging the issue to avoid it being auto-closed.)

**Comment by atanisoft** [comment]
@ssilverman send a PR with the update and I'm sure @me-no-dev will consider it.

**Comment by puuu** [comment]
Please have also a look, how this was fixed for the esp8266 platform: esp8266/Arduino#4117

**Comment by puuu** [comment]
Please see pull request #3763
