### ISSUE TITLE
mcpwm_isr_register() compile error

### ISSUE THREAD

**Issue by mrguen** [espressif/arduino-esp32#3068]
I would like to test this mcpwm example script in the Arduino IDE 1.8.9, but it does not compile

https://github.com/espressif/esp-idf/blob/master/examples/peripherals/mcpwm/mcpwm_basic_config/main/mcpwm_basic_config_example.c

1) This reference is not good:

#include "soc/mcpwm_periph.h"

 And this one should be added

 #include "soc/mcpwm_struct.h"

2) After un-comenting the capture configuration section there is an error on this line

mcpwm_isr_register(MCPWM_UNIT_0, isr_handler, NULL, ESP_INTR_FLAG_IRAM, NULL);  //Set ISR Handler

"invalid conversion from 'void (*)()' to 'void (*)(void*)' [-fpermissive]"

**Comment by lbernstone** [comment]
arduino-esp32 is currently using esp-idf v3.2.  If you use the example from that version, I think it will work properly.

**Comment by mrguen** [comment]
Thanks for this answer. 
I can't see an esp-idf-3.2 examples directory.
Is there a documentation for Arduino implementation of isp-idf-3.2?

**Comment by lbernstone** [comment]
https://github.com/espressif/esp-idf/blob/release/v3.2/examples/peripherals/mcpwm/mcpwm_basic_config/main/mcpwm_basic_config_example.c
[esp-idf documentation](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/mcpwm.html)

**Comment by mrguen** [comment]
Thank you very much!
