### ISSUE TITLE
Bluetooth MAC

### ISSUE THREAD

**Issue by joseitor** [espressif/arduino-esp32#3071]
Dear mates,

I'm trying to get the BLE MAC but I can't find a way to do it. Is there anyone? If not we should find a way to get it, since it can be really important to some jobs.

Of course I can get the wifi MAC using "ESP.getEfuseMac()", but sometimes you need the same that appear in an APP when you scan and want to connect by BLE to the device.

**Comment by beegee-tokyo** [comment]
What do you get with
```
	BLEAddress thisAddress = BLEDevice::getAddress();

	Serial.printf("BLE address: %s\n", thisAddress.toString().c_str());
```
?

Mine says **`BLE address: 24:0a:c4:81:ce:9e`**
