### ISSUE TITLE
Uploading code: very misleading end statement

### ISSUE THREAD

**Issue by Fugit185** [espressif/arduino-esp32#3073]
When uploading code to ESP32 using Arduino IDE, last line is "Hard resetting via RST pin" Even this is actual action and correct message itself, it is very confusing.

In other projects if I had any "resetting" messages, something was WRONG in code.

so, could you add something like "uploading (successfully) done"

**Comment by atanisoft** [comment]
First... please use the [new issue template](https://github.com/espressif/arduino-esp32/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Second... That output line is coming from esptool itself and not arduino-esp32 owned code.
