### ISSUE TITLE
HttpClient should be given a Client instead of WiFiClient

### ISSUE THREAD

**Issue by lal12** [espressif/arduino-esp32#3074]
I am currently using an ESP32 with an GSM AT modem to make HTTP Requests. Doing this I noticed that (unlike the standard Arduino) the HTTPClient class expects a WiFiClient handle instead of just a `Client` (abstract base class). Therefore I couldn't pass my `GSMClient` (which implements/inherits `Client`). I now copied the header and source and modified it to just use `Client` for my use. 

However I think that this should be changed in general to just Client or maybe a template class (to have the correct return value without needing to cast in `getStream`) e.g. 
```C++
template<typename T = Client, typename = std::enable_if<std::is_base_of<Client, T>::value>>
class HTTPClient{
HTTPClient(T client, ...);
}
``` 
Considering size restrictions, not using a template might be preferable, since I am not sure if the compiler detects that different template arguments don't change anything except the only compiletime relevant return type.

I could do a PR if wanted.

**Comment by lbernstone** [comment]
I think your mod is probably appropriate.  It was built as WiFiClient so WiFiClientSecure could be used, but I think the more flexible, the better.
