### ISSUE TITLE
ESP32: monitor directly after programming

### ISSUE THREAD

**Issue by knseir** [espressif/arduino-esp32#3078]
**THE QUESTION** 

I'm trying to keep an eye on the serial terminal immediately after uploading a program. 
That is : after upload is complete, some information is printed to the serial terminal in the setup code. However, because previously opened terminal sessions have to be disconnected for programming, Those few lines of information do not appear when I re-open the terminal after programming. I have to open a terminal session then press the reset button to reinitialise.

**How can I directly program and monitor the first few lines of serial output printed in the setup fonction ?**

**THE SETUP** 

platform: espressif32; board: esp32dev; framework: arduino
PLATFORM: Espressif 32 1.9.0 > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash

Using visual studio code with platfotm IO (latest, downloaded yesterday, August 9 2019)

Then used the terminal and tried This command (sent at once for simultaneous exécution): 

` platformio run --target upload; platformio device monitor -b 115200`

Which hase't fixe the issue, still have to press reset

**Comment by atanisoft** [comment]
In VS Code you can click on the PIO button (looks like an alien) on the left side and then select the option "Build and Upload" which will do exactly what you are trying to do.

Also this issue/question would be better suited to https://github.com/platformio/platform-espressif32 or https://community.platformio.org
