### ISSUE TITLE
BLE bond

### ISSUE THREAD

**Issue by eried** [espressif/arduino-esp32#3080]
Hello! I am trying to detect my smartwatch presence and it works perfectly using the ble_scan.ino example if the watch is in "discovery" mode. However I need it to work with discovery off (because battery life of the watch). Is there is a way to bond the device using the esp32? 

Thanks!

**Comment by lbernstone** [comment]
Did you try any of the other [examples](https://github.com/espressif/arduino-esp32/tree/master/libraries/BLE/examples)?

**Comment by eried** [comment]
Yes, all 😔
