### ISSUE TITLE
ESP32 with ymodem 

### ISSUE THREAD

**Issue by ambujsaxena1** [espressif/arduino-esp32#3083]
I am trying to update new firmware into another microcontroller using ESP.

To get there, first of all I have to download the file from wifi where ESP comes in picture, once files has been downloaded, I send the file through UART lines to another microcontroller in my case STM32F3 controller using Ymodem protocol.

Could you help me

**Comment by lbernstone** [comment]
I can't write your code for you, but this is a port of ESP8266AVRISP.
https://github.com/lbernstone/ESP32AVRISP
