### ISSUE TITLE
ESP32 reload when Fan is power on

### ISSUE THREAD

**Issue by mmashraf** [espressif/arduino-esp32#3091]
I have connected Esp32 with relay module, all is ok except when Fan is power on from button or from webserver.  it was through mediation error, I have changed almost every component for this project.
below is error and decode information of error but was not able to resolve it.
********
Guru Meditation Error: Core 0 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 0 register dump:
PC : 0x0000000e PS : 0x00060430 A0 : 0x801044ed A1 : 0x3ffb3dd0
A2 : 0x3ffc853c A3 : 0x0000000e A4 : 0x00000005 A5 : 0x00000001
A6 : 0x0000000e A7 : 0x00000006 A8 : 0x801032e3 A9 : 0x0000ffff
A10 : 0x00000000 A11 : 0x3ffc8900 A12 : 0x3ffb3238 A13 : 0x00000000
A14 : 0x3ffb328c A15 : 0x00000000 SAR : 0x00000018 EXCCAUSE: 0x00000014
EXCVADDR: 0x0000000c LBEG : 0x4000c2e0 LEND : 0x4000c2f6 LCOUNT : 0xffffffff

Backtrace: 0x0000000e:0x3ffb3dd0 0x401044ea:0x3ffb3df0 0x400f06c9:0x3ffb3e10 0x4008877d:0x3ffb3e40

decoder results:
PC: 0x0000000e
EXCVADDR: 0x0000000c
********
######## exception 2 
Meditation Error: Cere  1 panic'ed (Unhandled debug exceptionGuru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x4008ca54: 66d0a451 14260253 0b636604
Core 1 register dump:
PC      : 0x4008ca5b  PS      : 0x00060035  A0      : 0x40081444  A1      : 0x3ffb1b50  
A2      : 0x3ffb1b90  A3      : 0x00000001  A4      : 0x00000001  A5      : 0x3ffbfe74  
A6      : 0x3ffb1b50  A7      : 0x0000000f  A8      : 0x8008ca44  A9      : 0x3ffb1b40  
A10     : 0x3ffb1b50  A11     : 0x3ffc0228  A12     : 0x00000020  A13     : 0x3ffb1b70  
A14     : 0x3ffbfef8  A15     : 0x3ffbff18  SAR     : 0x0000001f  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000019  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  

Backtrace: 0x4008ca5b:0x3ffb1b50 0x40081441:0x3ffb1b90
decode results:
PC: 0x4008ca5b: panicHandler at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/panic.c line 241
EXCVADDR: 0x00000019

Decoding stack results
0x4008ca5b: panicHandler at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/panic.c line 241

#########
Hardware:
Board:	ESP32 Dev Module esp32
Arduino IDF component? v1.8.9   Flash Frequency: 240Mhz? PSRAM enabled: ?no? Upload Speed:	115200, Computer OS: Windows 10
flash mode DIO

[Web_server_with_timeout-AC-New5-3button00.zip](https://github.com/espressif/arduino-esp32/files/3504427/Web_server_with_timeout-AC-New5-3button00.zip)

**Comment by lbernstone** [comment]
Please follow the [issue template instructions](https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md)

**Comment by mmashraf** [comment]
Ibernstone: describe as advise. futher looking forward for response from people. as I come to know that ESP32 is very sensitive to AC voltage

**Comment by lbernstone** [comment]
These errors look like code problems, not power (brownout) issues.  Try a simple blink sketch and see if you have the same errors.

**Comment by mmashraf** [comment]
There is no error if ESP32 is running code except when // Assign output variables to GPIO pins
const int output26 = 19; as given in code. I have changed Pin to other Pins but issue remains same , this problem is related to 220v Fan control via relay module.  if I run LED bulb etc on same pin, there is no issue, it works fine with with any error.

**Comment by lbernstone** [comment]
This forum is for problems with the code, not electrical issues.
You need to add capacitors if you have voltage issues, or a diode if you have backflow EMF.

**Comment by mmashraf** [comment]
I understand but above errors are related to ESP32 code issues. further please advise where to add capacitor(value and where to put it) or diode suitable for it. Further I have already added 1N5817 schottky diode in  between relay module input Pin and coming power pin of esp32 to relay module

**Comment by lbernstone** [comment]
If the exact same code works without the relay connected, then it is not a code error.  You are not explaining your problem well.
[flyback diode](https://www.google.com/search?q=flyback+diode+relay+arduino)
I cannot size your capacitor, since I don't have any idea what your system looks like (and I don't care to).  Please use google instead of wasting our time here.

**Comment by parth2326** [comment]
Has anyone find a solution for it. I got the same issue when I control AC fan some time ESP32 module restart or hang. How can I reduce electromagnetic interference of fan operation to work properly?
