### ISSUE TITLE
Зависает карта памяти.

### ISSUE THREAD

**Issue by ArTyGill** [espressif/arduino-esp32#3117]
Никто не сталкивался с проблемой, что на esp32 arduino зависает карта памяти? Причем она просто перестает отвечать на запросы, до полного сброса питания.

**Comment by ArTyGill** [comment]
Библиотека sd_mmc

**Comment by ArTyGill** [comment]
Пробовал сбрасывать подтяжку, и pnp транзистор, который отключает питание на 80 ms.

**Comment by rel1ct** [comment]
Варианта два:
1. никто не сталкивался
2. не владеют русским
в этом сообществе язык общения - английский

**Comment by ArTyGill** [comment]
Да Вы возможно правы, я понял в чем была проблема, перезагрузка карты памяти не работала потому что, хоть pnp транзистор  и закрывался, карта памяти подтягивала паразитное питание через порты ввода/вывода esp32.
