### ISSUE TITLE
undefined reference to  rtc_isr_register which exists in libdriver.a(rtc_module) While other functions in it are available 

### ISSUE THREAD

**Issue by londonxue** [espressif/arduino-esp32#3149]
sketch/ESP32_BLE.ino.cpp.o:(.literal._Z18app_main_start_ulpv+0x70): undefined reference to `rtc_isr_register(void (*)(void*), void*, unsigned int)'
sketch/ESP32_BLE.ino.cpp.o: In function `app_main_start_ulp()':
/Users/londonxue/Documents/Arduino/ESP32_BLE/ESP32_BLE.ino:90: undefined reference to `rtc_isr_register(void (*)(void*), void*, unsigned int)'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board ESP32 Wrover Module.

```
static void ulp_isr_install()
{
    ESP_ERROR_CHECK(rtc_isr_register(ulp_isr_handler, NULL, RTC_CNTL_ULP_CP_INT_ENA_M));
    REG_SET_BIT(RTC_CNTL_INT_ENA_REG, RTC_CNTL_ULP_CP_INT_ENA_M);
}
```

**Comment by ctag-fh-kiel** [comment]
Having the same issue, how did you fix it?
