### ISSUE TITLE
Bluetooth and WIFI not connecting simultaneously.

### ISSUE THREAD

**Issue by Harichozhan** [espressif/arduino-esp32#3158]
Hi.. I have been working on an ESP 32 project which is supposed 1) to get the rssi between ESP32 and the paired android mobile through wifi. 2) to receive the data sent from mobile app through bluetooth. I created an app which can send the data from my android mobile to ESP32 through Bluetooth. It worked just fine when the wifi part is not included and I could view the data in Serial Monitor... But when I added the Wifi part, the bluetooth connection gets disconnected. Here is the code. I tried to keep the code simple by using "Bluetoothserial.h". I need to stabilize the code such that both wifi and bluetooth works simultaneously. 

```
#include <WiFi.h>
//SSID of your network
char ssid[] = "Chozhan";
//password of your WPA Network
char pass[] = "chozhan0n";

#include "BluetoothSerial.h"
BluetoothSerial ESP_BT;
String value = "";
int i_value, tot, avg;

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
  Serial.println("Wifi paired");
  ESP_BT.begin("Bluetooth Begin");
  Serial.println("Bluetooth Device is Ready to Pair");
}

void loop() {
  long rssi = WiFi.RSSI();
  Serial.print("RSSI:");
  Serial.println(rssi);
  if (ESP_BT.available())  {
    for (int i = 0; i < 10; i++) {
      ESP_BT.readStringUntil('\n');
      value = ESP_BT.readStringUntil('\n');
      //      Serial.println(value);
      i_value = value.toInt();
      //      Serial.println(i_value);
      tot = tot + i_value;
    }
  }
  Serial.print("Total : ");
  Serial.println(tot);
  avg = tot / 10;
  Serial.print("Average : ");
  Serial.println(avg);
  delay(1000);
  value = "";
  i_value = 0;
  tot = 0;
  avg = 0;
}
```
Thanks in advance.

**Comment by wakwak-koba** [comment]
WiFi and Bluetooth share antennas, and when used at the same time, they seem to interfere and become unstable.
There was such exchange in the past.
https://esp32.com/viewtopic.php?t=6707
