### ISSUE TITLE
Reading Bmp buffer

### ISSUE THREAD

**Issue by CharlesLeeeee** [espressif/arduino-esp32#3159]
How am I suppose to read the bmp image output buffer if the output buffer is a double pointer and there is only output length but not height also?

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md

**Comment by CharlesLeeeee** [comment]
Inside https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/include/esp32-camera/img_converters.h, ```bool frame2bmp(camera_fb_t * fb, uint8_t ** out, size_t * out_len);
```

**Comment by stickbreaker** [comment]
~~~
Uint8_t out;
Size_t outlen;

Frame2bmp(fp,&out,&outlen);
~~~
Height & width are part of ~fp~

Look at conversion example:[to_bmp.c](
https://github.com/espressif/esp32-camera/blob/1b8fdfe335b3c8c8b9e091e3615b0aee16946ef0/conversions/to_bmp.c
#L313)

Chuck.
