### ISSUE TITLE
Worked here in the Brazil, Instituto Federal do Rio Grande do Norte (IFRN - Campus Currais Novos)

### ISSUE THREAD

**Issue by linker1124** [espressif/arduino-esp32#3170]
It worked nice
![image](https://user-images.githubusercontent.com/45953017/64180540-566eb900-ce3b-11e9-96f2-89830132d6df.png)

**Comment by everslick** [comment]
I have no idea, what you are trying to say here. If you have an issue, pls provide relevant information.
