### ISSUE TITLE
parse v 3.2 to arduino ide

### ISSUE THREAD

**Issue by athleticmistud** [espressif/arduino-esp32#3173]
can not get a bluetooth speaker connection with arduino ide, need the v3.2 with bluetooth code fix  parsed to arduino ide

## Environment

- Development Kit:      [ESP32-Wrover-Kit|ESP32-DevKitC|ESP32-PICO-Kit|ESP32-LyraT|ESP32-LyraTD-MSC|none]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROOM-32|ESP32-WROOM-32D|ESP32-WROOM-32U|ESP32-WROVER|ESP32-WROVER-I|ESP32-WROVER-B|ESP32-WROVER-IB|ESP32-SOLO-1|ESP32-PICO-D4|ESP32]
- IDF version (run ``git describe --tags`` to find it): 
    // v3.2-dev-1148-g96cd3b75c
- Build System:         [Make|CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows|Linux|macOS]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description

//Detailed problem description goes here.

### Steps to repropduce

1. step1
2. ...

// It helps if you attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{
    
}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by athleticmistud** [comment]
here is the data from serial monitor on the d32 here is what we did

i load code on d32 

then load our code on d1   only connection between the 2 is on pin 16 on d32
our device connects to speaker but no sound
then i press our test button on our config page our light works but no sound
then i press the reset button on the d 32 the d32 disconnects and reconnects to the speaker
then i press our test button on our config page and it works both the light and sound play 

so it is something to do when i press reset on the d32 that fixes the code issue?
  i attached it here
[naten2.txt](https://github.com/espressif/arduino-esp32/files/3577666/naten2.txt)

**Comment by me-no-dev** [comment]
which core version are you using? Did you try 1.0.3-RC3?
