### ISSUE TITLE
Guru Meditation Error trying to send TCP packet while in interrupt handler

### ISSUE THREAD

**Issue by sixtyfive** [espressif/arduino-esp32#3178]
Over at https://github.com/plapointe6/EspMQTTClient/issues/20, we're wondering about a Guru Meditation Error occurs when trying to send a TCP packet while inside an interrupt handler. It's working fine on ESP8266, so perhaps there's a way to make it work on ESP32 by changing something in the Arduino Core?

**Comment by sixtyfive** [comment]
Well, I would still be interested in any kind of comment, dear bot.

**Comment by me-no-dev** [comment]
you can not do that from interrupt because it involves things that are stopped. You have options to message a task and run whatever you want in it. Look into Queues if you need to pass data or EventBits if you just need to pass a flag like "send a packet now"

**Comment by sixtyfive** [comment]
Thank you! :)
