### ISSUE TITLE
pin mappings

### ISSUE THREAD

**Issue by zenmanenergy** [espressif/arduino-esp32#318]
In the esp8266 codebase, D0, D1, D2, D3 etc are all mapped to their respective values. I find that useful as I can never remember what the integer values are.

**Comment by zenmanenergy** [comment]
Wait, are these mappings the exact same? i.e. does D2=2? What kind of sorcery is this?!

**Comment by igrr** [comment]
The whole thing with Dx defines is due to some 8266 boards (NodeMCU...) which didn't use GPIO numbers for pin labels and needed some sort of mapping. For the ESP32 none of the existing boards do that, so labels correspond 1:1 to GPIO numbers.

**Comment by zenmanenergy** [comment]
How very logical and simple. Thanks igrr
