### ISSUE TITLE
IPAddress.h fromString dosen't work

### ISSUE THREAD

**Issue by thbl** [espressif/arduino-esp32#3198]
fromString function returns wrong result.
```
void setup() {

  Serial.begin(115200);

  IPAddress apip;

  const char *apipch;
  apipch = "192.168.4.1";

Serial.println(apip.fromString(apipch));

}

void loop() {
  // put your main code here, to run repeatedly:
}
```
Returns 1 but should return 192.168.4.1

**Comment by Jeroen88** [comment]
See [here](https://github.com/espressif/arduino-esp32/blob/a59eafbc9dfa3ce818c110f996eebf68d755be24/cores/esp32/IPAddress.cpp#L82), fromString() returns 'true' (ie 1) to show that the conversion was successful.
