### ISSUE TITLE
wificlient is slow

### ISSUE THREAD

**Issue by waayst** [espressif/arduino-esp32#32]
I write a program to download files, only 4 ~ 5 KB/s speed, but the same program on esp8266, it can be as high as 500 KB/s

**Comment by nkolban** [comment]
Would you be able to post a minimal program that illustrates the issue?

**Comment by waayst** [comment]
while(true){
    if(client.available()) client.read();
  }

**Comment by me-no-dev** [comment]
you are reading byte-by-byte and this is done much differently on powerful chips like the ESP32. Much better to read in bulk as much as it's available or in some sort of chunks.
