### ISSUE TITLE
compile error - in function 'esp_err_t capture_handler(httpd_req_t*)':

### ISSUE THREAD

**Issue by die-tueftelei** [espressif/arduino-esp32#3204]
### Hardware:
Board:							espressif32 - esp32cam
IDE name:						Platform.io
Upload Speed:					115200
Computer OS:                                        Mac OSX 10.14.2

### Description:

Compiling .pio/build/esp32cam/lib316/WiFi/WiFiGeneric.cpp.o
src/app_httpd.cpp: In function 'esp_err_t capture_handler(httpd_req_t*)':
src/app_httpd.cpp:286:25: error: 'box_array_t {aka struct tag_box_list}' has no member named 'score'
         free(net_boxes->score);
                         ^

**Comment by me-no-dev** [comment]
The build is passing, so something in your PIO install did not go well :)
https://travis-ci.org/espressif/arduino-esp32/jobs/584357979#L1015-L1099

@ivankravets maybe files did not update properly?

**Comment by valeros** [comment]
Hi @die-tueftelei ! Does it work with Arduino IDE? If so, please upload your project somewhere so we can reproduce the issue. Thanks!

**Comment by die-tueftelei** [comment]
Hi @valeros I just copied the following example: https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer

**Comment by die-tueftelei** [comment]
& I did not try Arduino IDE - I use Atom & Platform.IO

**Comment by atanisoft** [comment]
@die-tueftelei using "master" branch with the current release available in PIO is the problem. PIO has not updated to 1.0.3 release, it will soon though.

you can fix it in your project by adding the following to your platformio.ini file:
```
[env]
platform_packages =
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
```

This will force override the version of the arduino-esp32 code that PIO uses to the latest version available in GIT. This is a temporary solution until PIO has packaged the latest arduino-esp32 1.0.3 release for PIO.

**Comment by die-tueftelei** [comment]
perfect - yep that solves it !
