### ISSUE TITLE
Feature Request: T5-Ink-Screen-Series

### ISSUE THREAD

**Issue by zehrer** [espressif/arduino-esp32#3235]
Feature Request.
Please support the TTGO EPaper Series board(s).
All details are to find here:
https://github.com/Xinyuan-LilyGO/T5-Ink-Screen-Series

**Comment by zehrer** [comment]
requested here: https://github.com/platformio/platform-espressif32/issues/225

**Comment by zehrer** [comment]
What to do to remove stale ? Is this comment sufficient ?

**Comment by ruipires** [comment]
I too am interested in this board.
Is there anything I can do to help it get supported ?
