### ISSUE TITLE
SPI::writeBytes first param is not const

### ISSUE THREAD

**Issue by Makuna** [espressif/arduino-esp32#3241]
### Description:
SPI::writeBytes is defined differently between Esp82666 and Esp32; where the first param is const on esp8266 it is not on Esp32.  Since the data should not be overwritten, this param should be marked as const.
Esp32 => void SPIClass::writeBytes(uint8_t * data, uint32_t size)
Esp8266 => void SPIClass::writeBytes(const uint8_t * data, uint32_t size);

This causes compile issues when the environement is set to strict compile option.

**Comment by me-no-dev** [comment]
done ;)
