### ISSUE TITLE
add support for standard C++ coding form

### ISSUE THREAD

**Issue by Master811129** [espressif/arduino-esp32#3243]
### Hardware:
Board:							        ESP32 Dev Module
Core Installation/update date:			latest  stable relaese
IDE name:							Arduino IDE
IDE version:                                                     1.8.10
Flash Frequency:		 	     		        40Mhz
PSRAM enabled:                                             ?no?
Upload Speed:						115200
Computer OS:                                                  Windows 10

### Description:
hello developers!
i have a problem with this core when i want to coding with standard C++ style the core gives me some errors:
C:\Users\USER\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\cores\esp32/main.cpp:14: undefined reference to `setup()'

C:\Users\USER\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\cores\esp32/main.cpp:17: undefined reference to `loop()'
it forces me to add setup and loop functions.

but the official board like uno, nano, nano Every, mega supports this method like a charm
please add it to the core.

thanks
```C++

//Change the code below by your sketch
#include <Arduino.h>
int main (void)
{
   init();
   while(1)
   {
       
   }
}
```

**Comment by me-no-dev** [comment]
not possible here. ESP32 is multicore FreeRTOS MCU that handles this differently. If you want to do something close to your requirements is to go with Arduino as IDF component (see the instructions in the readme).
