### ISSUE TITLE
wifi library using freeRTOS

### ISSUE THREAD

**Issue by vignesh13404387** [espressif/arduino-esp32#3250]
can we use WiFi.h library in FreeRTOS while creating a separate task?   Pls give some example links

**Comment by me-no-dev** [comment]
yes. wifi already runs in it's own task though ;)

**Comment by vignesh13404387** [comment]
#include <WiFi.h>
void wifi(void *pvParameters);
TaskHandle_t wifi_connect;
void setup() {
  Serial.begin(115200);
  xTaskCreate(wifi, "wifi connection", 1024, NULL, 1, &wifi_connect);
}

void loop() {
  vTaskDelay(2000);
}

void wifi(void *pvParameters) {
  for ( ;; ) {
    const char* ssid = "ACT02";
    const char* pass = "fbwelcome123";
    WiFi.begin(ssid, pass);
    while (WiFi.status() != WL_CONNECTED ) {
      vTaskDelay(500);
      Serial.print(".");
    }
    Serial.println("WiFi connected");
    Serial.print("IP address is ");
    Serial.println(WiFi.localIP());
  }
}

**Comment by me-no-dev** [comment]
why? because you are running connect in a busy loop? why do you connect, then connect again and again and again?

**Comment by vignesh13404387** [comment]
what will happen if I create a task without for loop?

**Comment by me-no-dev** [comment]
Why do you use vTaskDelay? it depends on tick configuration ;) 
```cpp
#include <WiFi.h>
void wifi(void *pvParameters);
TaskHandle_t wifi_connect;
void setup() {
  Serial.begin(115200);
  xTaskCreate(wifi, "wifi connection", 4096, NULL, 1, &wifi_connect);
}

void loop() {
  delay(2000);
}

void wifi(void *pvParameters) {
  const char* ssid = "ACT02";
  const char* pass = "fbwelcome123";
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED ) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("WiFi connected");
  Serial.print("IP address is ");
  Serial.println(WiFi.localIP());
  for ( ;; ) {
    delay(1000);
  }
}
```

**Comment by Rafinha29** [comment]
> yes. wifi already runs in it's own task though ;)

in which core is running?
