### ISSUE TITLE
created separate task to connect with wifi

### ISSUE THREAD

**Issue by vignesh13404387** [espressif/arduino-esp32#3251]
#include <WiFi.h>
void wifi(void *pvParameters);
TaskHandle_t wifi_connect;

const char* ssid = "ssid";
const char* pass = "pass";
void setup() {
  Serial.begin(115200);
  xTaskCreate(wifi, "wifi_connection", 1024, NULL, 1, &wifi_connect);
}

void loop() {
  vTaskDelay(2000);
}

void wifi(void *pvParameters) {
  for ( ;; ) {
    WiFi.enableSTA(true);
    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, pass);
    while (WiFi.status() != WL_CONNECTED ) {
      vTaskDelay(500);
      Serial.print(".");
    }
    Serial.println("WiFi connected");
    Serial.print("IP address is ");
    Serial.println(WiFi.localIP());
  }
}
 and the output is 

rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8
ets Jun  8 2016 00:22:57

**Comment by me-no-dev** [comment]
no need to open more than one ticket ;) you are having and issue with your code and we are discussing this in another ticket.

**Comment by rgov** [comment]
For other search engine wanderers: The discussion happened in https://github.com/espressif/arduino-esp32/issues/3250 and the conclusion was that Wi-Fi already runs in its own task.
