### ISSUE TITLE
wifi initialization in arduino IDE

### ISSUE THREAD

**Issue by vignesh13404387** [espressif/arduino-esp32#3257]
#include <WiFi.h>
void setup() {
  Serial.begin(115200);
  Serial.println("Initializing WiFi");
  initialize_wifi();
}

void loop() {
  // put your main code here, to run repeatedly:

}
void initialize_wifi() {
  esp_log_level_set("wifi", ESP_LOG_INFO); // Enable wifi driver logging
  tcpip_adapter_init();
  wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
  ESP_ERROR_CHECK( esp_wifi_init(&cfg) );
}
 
I am trying to create a wifi task but in Arduino IDE wifi_init_config_t datatype is not detected, what is the problem here? Why some code does not work on Arduino IDE? Please explain in detail.

**Comment by lbernstone** [comment]
WiFi.h provides the Arduino WiFi class.  You are using the esp-idf methods, so you would need to include those headers (esp_wifi.h)
