### ISSUE TITLE
Certificate expired on https://dl.espressif.com/

### ISSUE THREAD

**Issue by DeuxVis** [espressif/arduino-esp32#3259]
The TLS certificate on dl.espressif.com expired as of today.

This mean we can no longer use the arduino boards manager method to install the esp32 boards definitions.

Thanks for your help.

**Comment by LonzGer** [comment]
A short-term solution is to date back the system time during installation.

**Comment by beegee-tokyo** [comment]
@me-no-dev    
If Espressif needs help to automatically renew their certificate for https, I can help them. My https site get an updated cert everytime it is about to expire. It's very simple to implement. I see this issue coming up every 3 months and IMHO it's embarrassing for a company like Espressif (stock listed) to let it happen.

**Comment by me-no-dev** [comment]
@beegee-tokyo I agree. this should have been fixed last time round. no idea what happened. This breaks IDF also, so the issue is beyond Arduino. For Arduino, we could do things, but sadly it's not easy to change board json link ;) hard to propagate.

**Comment by beegee-tokyo** [comment]
@me-no-dev     
I don't know your relation to Espressif, but if there is any, could you forward my help offer to them?

**Comment by me-no-dev** [comment]
it's bad timing :) that is all. Espressif does have people in charge of this. Just that this server is not managed by them and the person in charge is in transit. I run SSL as well, but do not have execute access either.

**Comment by pvint** [comment]
I needed this quickly just now, so I put a copy of the package_esp32_index.json on my github. If anyone needs it you can use it with this URL: https://github.com/vintlabs/ESP32-Zip/raw/master/package_esp32_index.json

**Comment by lbernstone** [comment]
There are other files within the json that also come from the affected server, so just moving the json file will not work.

**Comment by pvint** [comment]
Ah, but it did work... well, upon closer inspection it appears that I had all the requisite files in ~/.arduino15/staging

If I wipe those out you're right - it does fail. Curiously, it gets one file (esp32-1.0.3.zip) and then fails on the next one (xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz)

**Comment by xk** [comment]
In the meantime DO NOT open the boards manager it wiped out all my esp boards from the boards menu.

**Comment by salmanfarisvp** [comment]
I think the problem is solved, Espressif renewed the certificate today, so try to the official ESP32 Board definition URL to download Board definition

URL : https://dl.espressif.com/dl/package_esp32_dev_index.json

More details :https://community.makergram.com/topic/36/arduino-boards-manager-error-while-installing-the-esp32-boards-definitions 

![Capture](https://user-images.githubusercontent.com/11945360/65569481-6467b380-df7b-11e9-926e-aaf9b4e36797.PNG)

**Comment by DeuxVis** [comment]
Just verified it works. Thank you for the prompt action.

**Comment by jhonvera97** [comment]
alparecer se tiene nuevamente el problema

**Comment by jhonvera97** [comment]
quien me puede ayudar con algun repositorio que funcione

**Comment by lbernstone** [comment]
Los archivos ya no están alojados en dl.espressif.com.  Por favor se usa https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

[guia de installacion](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html)

**Comment by jhonvera97** [comment]
Arduino:1.8.19 (Windows Store 1.8.57.0) (Windows 10), Tarjeta:"DOIT ESP32 DEVKIT V1, 80MHz, 921600, None"

 #include <bits/cpu_defines.h>

          ^~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Error compilando para la tarjeta DOIT ESP32 DEVKIT V1.

**Comment by jhonvera97** [comment]
me sale este error de compilacion
