### ISSUE TITLE
get message body from server.on/handleClient

### ISSUE THREAD

**Issue by aster94** [espressif/arduino-esp32#3262]
hello,

using the server.on() is possible to get the request body or other parameters?

It would be wonderful if these could be easily obtained:
body
User-Agent
Host
Connection
Accept-Encoding

**Comment by lbernstone** [comment]
The WebServer library is very simplistic.  For a more full featured server, use [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer)

**Comment by aster94** [comment]
Ok thanks for the tip 😃 I am closing
