### ISSUE TITLE
Trojan Horse detected on espota.exe using Norton

### ISSUE THREAD

**Issue by mjs513** [espressif/arduino-esp32#327]
See Image below.  Can you confirm?
![capture](https://cloud.githubusercontent.com/assets/5366213/25308943/0d1739a4-278e-11e7-9aec-1d1068c6254e.PNG)

**Comment by mjs513** [comment]
Just excluded the file but probably should warn people.

**Comment by me-no-dev** [comment]
the file is just a compiled version of the python script. Compilation is done on a disconnected clean machine, but it's still a script in a binary form and that is probably why NC is complaining.
