### ISSUE TITLE
cannot download from Fehler beim Herunterladen von https://github.com/espressif/arduino-esp32/releases/download/package_esp32_dev_index.json Fehler beim Herunterladen von https://dl.espressif.com/dl/package_esp32_dev_index.json Fehler beim Herunterladen von https://github.com/espressif/arduino-esp32/releases/download/package_esp32_index.json

### ISSUE THREAD

**Issue by mikewolf** [espressif/arduino-esp32#3271]
in Arduino ide
Fehler beim Herunterladen von https://github.com/espressif/arduino-esp32/releases/download/package_esp32_dev_index.json
Fehler beim Herunterladen von https://dl.espressif.com/dl/package_esp32_dev_index.json
Fehler beim Herunterladen von https://github.com/espressif/arduino-esp32/releases/download/package_esp32_index.json

**Comment by reddden** [comment]
me too but in Russia

**Comment by pfeerick** [comment]
In Australia, I can't access `https://dl.espressif.com/dl/package_esp32_index.json` either. If this URL has changed, this means the instructions at [docs/arduino-ide/boards_manager.md](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md) are incorrect. 

I'm not familiar with the other two links, but they don't work for me either. I was, however, able to update to 1.0.3 by using the [package_esp32_index.json
](https://github.com/espressif/arduino-esp32/releases/download/1.0.3/package_esp32_index.json) included in that release.

**Comment by leng-yue** [comment]
me too in the United States

**Comment by atmosuwiryo** [comment]
Yup, https://dl.espressif.com/dl/ is not accessible.

**Comment by sogeniusio** [comment]
Is there a country where this is working?

**Comment by leng-yue** [comment]
> Is there a country where this is working?

I think no

**Comment by me-no-dev** [comment]
will be fixed today, I've been told.

**Comment by atmosuwiryo** [comment]
It's working right now. Should do mirroring of this while alive

**Comment by pfeerick** [comment]
Yup, https://dl.espressif.com/dl/package_esp32_dev_index.json is working again. Is there a particular reason it's not hosted in the repo, or in it's own if you don't want updates to it polluting the changelog? Not getting the benefits and reliability of AWS hosting this way... ;)
