### ISSUE TITLE
HTTPS failed

### ISSUE THREAD

**Issue by FMParo** [espressif/arduino-esp32#3273]
Hi, I did my app using the https client demo from Arduino. Until yesterday it worked fine. After the last update (24/09/2019) my app and the demo doesn't work either.  It respond with "send header failed"

**Comment by cyberman54** [comment]
Same problem here:

> [I][ota.cpp:89] start_ota_update(): Starting OTA update, attempt 1 of 5
> [I][ota.cpp:121] do_ota_update(): Checking latest firmware version on server
> [E][ssl_client.cpp:33] handle_error(): SSL - Bad input parameters to function
> [E][ssl_client.cpp:35] handle_error(): MbedTLS message code: -28928
> [W][HTTPClient.cpp:1318] returnError(): error(-2): send header failed

This came in with a recent update. I am using platformio, with platform-espressif32 v1.9.0 my code works, with 1.10.0 it breaks.
