### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed

### ISSUE THREAD

**Issue by emry78** [espressif/arduino-esp32#3280]
Hi All,
I have problem with esp32 crash. Any idea or sugggestion to solve this issue. Thanks

Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstrucGuru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered (⸮⸮?⸮) 
Guru Meditation Error: Core  1 panic'ed (Double exception)
Guru Meditation Error: Core  1 panic'ed (Double exception)
 ⸮⸮?8⸮⸮?X⸮⸮?x⸮⸮?Error: Core  1⸮@⸮⸮⸮?d (Unhandled de%)
Debu⸮@6
 ⸮⸮?8⸮⸮?X⸮⸮?x⸮⸮? 1⸮@⸮⸮⸮?d (Unhandled de%)
Debu⸮@6x⸮⸮?I⸮@⸮W⸮?&⸮⸮?⸮@⸮@4⸮⸮⸮? ⸮⸮?8⸮⸮?X⸮⸮?x⸮⸮? 1⸮@⸮⸮⸮?d (

**Comment by tanakamasayuki** [comment]
More Info

ArduinoIDE
Tools > Core Debug Level > Verbose or Debug

**Comment by husigeza** [comment]
Does anyone have any idea when this issue is dropped?

**Comment by lbernstone** [comment]
This was closed because it the OP abandoned it.  It is impossible to determine what caused the issue, no code was provided, and more debug info is needed.  The general problem is that something (apparently a large amount of data) is being written to a pointer out of scope.  The system ran out of memory and crashed.

**Comment by jayrawatrj** [comment]
> Hi All,
> I have problem with esp32 crash. Any idea or sugggestion to solve this issue. Thanks
> 
> Guru Meditation Error: Core 1 panic'ed (Cache disabled but cached memory region accessed)
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstruction). Exception was unhandled.
> Memory dump at 0x401613ec: bad00bad bad00bad bad00bad
> Guru Meditation Error: Core 1 panic'ed (IllegalInstrucGuru Meditation Error: Core 1 panic'ed (Unhandled debug exception)
> Debug exception reason: Stack canary watchpoint triggered (⸮⸮?⸮)
> Guru Meditation Error: Core 1 panic'ed (Double exception)
> Guru Meditation Error: Core 1 panic'ed (Double exception)
> ⸮⸮?8⸮⸮?X⸮⸮?x⸮⸮?Error: Core 1⸮��@⸮⸮⸮?d (Unhandled de%)
> Debu⸮��@6
> ⸮⸮?8⸮⸮?X⸮⸮?x⸮⸮?� 1⸮��@⸮⸮⸮?d (Unhandled de%)
> Debu⸮��@6x⸮⸮?I⸮�@⸮W⸮?&⸮⸮?⸮@⸮�@4⸮�⸮⸮? ⸮⸮?8⸮⸮?X⸮⸮?x⸮⸮?� 1⸮��@⸮⸮⸮?d (

i am having same issue does any one got the solution??

**Comment by jayrawatrj** [comment]
I think no one have the solution for this????

**Comment by atanisoft** [comment]
This issue won't be looked at further as there is not enough information to assist in resolving it. There is no code provided, no stack trace, nothing to work from.
