### ISSUE TITLE
Can't connect to more than three devices simultaneously. 

### ISSUE THREAD

**Issue by djohns27** [espressif/arduino-esp32#3283]
I have an ESP 32 client that needs to connect to four servers simultaneously.
I have tried editing the sdkconfig file:
...\esp32\hardware\esp32\1.0.2\tools\sdk\sdkconfig

by changing the lines:
CONFIG_BTDM_CONTROLLER_BLE_MAX_CONN=4 //was 3
CONFIG_BTDM_CONTROLLER_BLE_MAX_CONN_EFF=4 //was 3
CONFIG_BT_ACL_CONNECTIONS=4

I also tried changing the sdkconfi.h file:
...\esp32\hardware\esp32\1.0.2\tools\sdk\include\config\sdkconfig.h

by changing the lines
#define CONFIG_BTDM_CONTROLLER_BLE_MAX_CONN 4 //was 3
#define CONFIG_BTDM_CONTROLLER_BLE_MAX_CONN_EFF 4 //was 3

even with these alterations I am unable to more than three devices.
Is there something more that I need to do?

**Comment by me-no-dev** [comment]
those changes will not affect anything. that configuration only reflects how IDF was compiled to get the libs for Arduino. Look into Arduino as IDF component if you want to alter that config and get an effect :)
