### ISSUE TITLE
Maximum duration of sleeping phase.

### ISSUE THREAD

**Issue by fbambusi** [espressif/arduino-esp32#3286]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.3-rc3
IDE name:						Arduino IDE
Flash Frequency:					40Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Ubuntu

### Description:
Good morning everybody, I am programming esp32-wroom-32 module using Arduino IDE v. 1.8.10, with core https://github.com/espressif/arduino-esp32 version 1.0.0-rc3.
My question is: 

**what is the max value of the paramter esp_sleep_enable_timer_wakeup(uint_64t time_in_us)?**
I am executing  the following code

When I set the highlighted parameter **durationOfSleepingPhaseInSeconds** to a value higher than approximately 1800s (half an hour), the board immediately exits deep sleep mode and the following message is printed:

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

 void setup()
{
esp_err_t deepSleepTimerEnabled=esp_sleep_enable_timer_wakeup(**durationOfSleepingPhaseInSeconds** * uS_TO_S_FACTOR);
  if(deepSleepTimerEnabled==ESP_OK)
  {
    Serial.println("Will wake up thanks to timer");
  }
  else
  {
    Serial.println("ERROR WHILE SETTING UP THE TIMER");
  }


  esp_deep_sleep_start();
} 
void loop() {
}
```

### Debug Messages:
```
18:52:17.471 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
18:52:17.505 -> configsip: 0, SPIWP:0xee
18:52:17.505 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
18:52:17.505 -> mode:DIO, clock div:1
18:52:17.505 -> load:0x3fff0018,len:4
18:52:17.505 -> load:0x3fff001c,len:952
18:52:17.505 -> load:0x40078000,len:6084
18:52:17.505 -> load:0x40080000,len:7936
18:52:17.505 -> entry 0x40080310
18:52:17.803 -> ets Jun  8 2016 00:22:57 
```

**Comment by lbernstone** [comment]
See the latest update to the example.  You must explicitly tell the compiler that your result will be a 64bit number.
https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/DeepSleep/TimerWakeUp/TimerWakeUp.ino#L22
