### ISSUE TITLE
WifiClient setTimeout problem

### ISSUE THREAD

**Issue by der-Lemmi** [espressif/arduino-esp32#330]
wen setting a timeout:
`Wificlient client = server.avalible();`
`client.setTimeout(2000);`
`...`
`while(client.connected()) {`
` `  `  if(client.availible()) {`
`...`
this will have no effect.

If a client is connected and sends no data -> server hangs in the client.connected() loop because the timeout will not terminate the client.

**Comment by bbx10** [comment]
#377 might be related to this problem.

**Comment by me-no-dev** [comment]
Can you please try the latest code?

**Comment by der-Lemmi** [comment]
seems to work now!

I logged for 24h and all clients with no data requests are got the timeout :-)

**Comment by marioelectron** [comment]
serverClients[i].setTimeout(1);
 serverClients[i].print(PString) ;  ///  when the wireless is lost it gets stuck in the mission  serverClients[i].print(PString)  esp32 not 
                                                                                                                                                                                            //timeout
