### ISSUE TITLE
Wrover psram issue in Arduino IDE

### ISSUE THREAD

**Issue by thbl** [espressif/arduino-esp32#3301]
When using wrover module in arduino IDE psram dosen't work.
When running
```
void setup() {
  Serial.begin(115200);
  Serial.println(ESP.getFreeHeap());
}

void loop() {
}
```
It only returns 353492

**Comment by atanisoft** [comment]
PSRAM is not included in heap by default in arduino-esp32. If you want to use it as heap you have two options:
1) Arduino as IDF component.
2) use ps_malloc to allocate from PSRAM.
