### ISSUE TITLE
WiFi.status() returns 255 (No Shield) in softAP mode.

### ISSUE THREAD

**Issue by n9wxu** [espressif/arduino-esp32#3305]
I am operating alternately in softAP and STA modes.  When I am in STA mode, WiFi.Status() == WL_CONNECTED (3). However, when I am operating in softAP mode the WiFi.Status() returns WL_NO_SHEILD (255).  This is very strange and certainly not what I expected.

I am using PlatformIO ESP32 Platform version 1.10.0

**Comment by atanisoft** [comment]
@n9wxu This is expected as the WiFi.status() method is only applicable to the STATION mode, as can be seen in the comments [here](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiSTA.h#L78-L81).
