### ISSUE TITLE
SDWebServer text editor folder tree not loading

### ISSUE THREAD

**Issue by bpor** [espressif/arduino-esp32#3331]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			?11/jul/2017?
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                          no
Upload Speed:						921600
Computer OS:                                            Windows 10

### Description:
I am trying to use the SDwebserver with the text editor. I only updated the ssid and password in the SDWebServer.ino. I loaded the "SdRoot" folder to a 4GB sd card. index and other site are loading ok but the text editor is not loading the folder tree and the file upload is not working. 

![image](https://user-images.githubusercontent.com/10067528/66334270-fd61db80-e938-11e9-86d9-fd7c4e184153.png)

On the page console, I am getting net::ERR_CONNECTION_RESET at the GET instruction. If I just run the GET /list?dir=/ from console I am getting a response for the esp32.

![image](https://user-images.githubusercontent.com/10067528/66334219-defbe000-e938-11e9-8e79-3e1a10534fcf.png)

Is anyone having the same issue. Tried it with various ESP32 modules and also used old versions of SDWebserver and I am getting the same problem

**Comment by atanisoft** [comment]
Check the serial console output from the esp32, it likely is failing to mount the SD card.

**Comment by bpor** [comment]
The SD card is mounting and the web pages are loading. 
The printDirectory function is never called. other web pages are loading. the only sdcardnotfound that i am getting is for the favicon.ico but I know that that is not on the sd card.

![image](https://user-images.githubusercontent.com/10067528/66336310-1ff5f380-e93d-11e9-8a52-2d80b1d7c9f5.png)
