### ISSUE TITLE
WiFi does not connect

### ISSUE THREAD

**Issue by fedyfausto** [espressif/arduino-esp32#3337]
Hello! i'm using the ai-thinker esp2-cam and i'm trying to connect to my 2.4 wifi with a simple ssid and password (wpa and wpa2 activated) but actually the WiFi.status return zero and it does not connect to the router :<
```c
#include <Arduino.h>
#include <WiFi.h>
#include <wifikeys.h>

void setup() {
  // Wi-Fi connection
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");
  Serial.print(WiFi.localIP());

}
```
How can i fix? My platformio.ini:
```
[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
```

My logs:
```bash
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
I (1444) wifi: wifi driver task: 3ffb5784, prio:23, stack:3584, core=0
I (3000) wifi: wifi firmware version: 7997e4b
I (3001) wifi: config NVS flash: enabled
I (3001) wifi: config nano formating: disabled
I (3001) wifi: Init dynamic tx buffer num: 32
I (3005) wifi: Init data frame dynamic rx buffer num: 32
I (3010) wifi: Init management frame dynamic rx buffer num: 32
I (3016) wifi: Init management short buffer num: 32
I (3021) wifi: Init static rx buffer size: 1600
I (3025) wifi: Init static rx buffer num: 16
I (3029) wifi: Init dynamic rx buffer num: 32
I (3101) wifi: mode : sta (30:ae:a4:d7:41:84)
I (5167) wifi: n:12 0, o:1 0, ap:255 255, sta:12 0, prof:1
I (5168) wifi: state: init -> auth (b0)
I (5172) wifi: state: auth -> assoc (0)
I (5186) wifi: state: assoc -> run (10)
I (5210) wifi: connected with labiotweb, channel 12, BW20
I (5215) wifi: pm start, type: 1
..............................................................
```

**Comment by ddwood** [comment]
I had a similar issue where the status would progress 0 (IDLE).. to some "fatal" status such as 6 /WL_DISCONNECTED. I also had some "Brownout" detection's.
Once you hit a fatal error, then you are stuck in the loop forever. I added a test for fatal status errors and if I got one I would call ESP.restart() (Defined in Esp.h)
I am guessing the main reason for my failed connections was due to the insufficient power supply on my PC's USB port. The restart call does not seem to be called after I moved to a better power source.
The while loop above makes the assumption that the connection will eventually occur, however there are reasons that this could fail. 

I am not sure about this, but I suspect that the main loop method should be checking the status from time to time as well.

**Comment by fedyfausto** [comment]
i tried to move all in the main loop but it does not work :( i'm using the last version i think so do you suggest to try an older version?

**Comment by ddwood** [comment]
I changed the while loop like this:
  // Start the WIFI radio and join the specified LAN
  wl_status_t wifiStatus = WiFi.begin(ssid, password);
  wl_status_t lastWifiStatus = wifiStatus;
  while (wifiStatus  != WL_CONNECTED) {
     if(wifiStatus != lastWifiStatus) {
       Serial.print("WiFi status is ");
       Serial.println(WlStatusAsString(wifiStatus));
       lastWifiStatus = wifiStatus;
     }
     if(WifiStatusIsFatal(wifiStatus)) 
     {
       delay(2000);
       Serial.println("..");
       ESP.restart();
     } else {
       delay(500);
       Serial.print("..");
     }
     wifiStatus = WiFi.status();
  }

The following helper functions were used in the while loop - put these above your setup method.

const char *WlStatusAsString(wl_status_t status)
{
   static const char * WiFiResultCodeStrings[] =
     { "WL_IDLE_STATUS",
       "WL_NO_SSID_AVAIL",
       "WL_SCAN_COMPLETED",
       "WL_CONNECTED",
       "WL_CONNECT_FAILED",
       "WL_CONNECTION_LOST",
       "WL_DISCONNECTED",
       "WL_NO_SHIELD255"
    };

  if(WL_NO_SHIELD == status)
  {
    return "WL_NO_SHIELD";
  }
  if(status < sizeof(WiFiResultCodeStrings)/sizeof(const char *))
  {
    return WiFiResultCodeStrings[(int)status];
  }
  return "WL_UNKNOWN_STATUS";
}

bool WifiStatusIsFatal(wl_status_t status)
{
   switch(status) {
     case WL_IDLE_STATUS:
     case WL_SCAN_COMPLETED:
     case WL_CONNECTED:
     case WL_DISCONNECTED:
       return false;
     default:
        return true;
   }
}

Don't forget to add this at the top of your file:

#include "Esp.h"

**Comment by ddwood** [comment]
Simpler option is to put a limit on the loop count while waiting for the status to be WL_CONNECTED.
If it is not connected after so many loops the likelihood is that it will not be connecting.

So why reset the board? This should not be necessary, but like I said earlier, if my power supply / USB is not enough, then I was getting issues starting the WiFi component.
