### ISSUE TITLE
4-bit data SPI

### ISSUE THREAD

**Issue by dr4nc3s** [espressif/arduino-esp32#336]
Hello,
Will there be an implementation for 4-bit data SPI coming in the future for the Arduino core?

**Comment by me-no-dev** [comment]
what do you mean by 4 bit? 4 parallel data lines? like QIO?

**Comment by dr4nc3s** [comment]
Yes, that's what I meant. Forgot "QIO" for a moment. I also figured out how to do it after some more reading. :)
