### ISSUE TITLE
race condition between init() and enable() for bt controller

### ISSUE THREAD

**Issue by croisez** [espressif/arduino-esp32#338]
I am currently playing with ESP32-arduino toolchain.

I am doing esp_bt_controller_init(), followed by esp_bt_controller_enable().
This last function is returning an error 0x103, meaning that I apparently did not call esp_bt_controller_init() before calling esp_bt_controller_enable().

But this is not the case. I read the code in the file from esp-idf: bt.c. There is a chance that esp_bt_controller_enable() to be executed before bt_controller_task() is actually started.

I experimented the following:
as libbt is not recompiled on-the-fly inside Arduino IDE, I put some LOG_E() traces just after 
ret = xTaskCreatePinnedToCore(bt_controller_task, "btController"... line in bt.c at line 226 (current release). This to verify that the process were well going through this function.
I recompiled it inside Eclipse/esp-idf sources, and copied libbt.a in the Arduino environment.
And then error 0x103 disappeared.
My conclusion is that there is indeed a race condition.  bt_controller_task() is responsible to set the bt internal state to ESP_BT_CONTROLLER_STATUS_INITED, but has not done it already, when esp_bt_controller_enable() is called. This function detect it, and returns 0x103 error value.

There should be a way for esp_bt_controller_init() to wait, after xTaskCreatePinnedToCore(bt_controller_task... , that bt_controller_task() is actually running. 

For example, by blocking on a xEventGroupWaitBits() function to synchronize esp_bt_controller_init() with bt_controller_task()

What is your advice?

Nota Bene: I do not get such race condition in the app compiled with Eclipse/esp-idf (v2.0-rc1), but well with latest ESP32-Arduino toolchain

**Comment by me-no-dev** [comment]
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-bt.h#L25
Use the arduino method for starting BT
