### ISSUE TITLE
What are the well tested I2C baud rates for communication with MPU9250

### ISSUE THREAD

**Issue by shomedas** [espressif/arduino-esp32#3380]
### Hardware:
Board:						ESP32 wroom NodeMCU
Core Installation version:			1.02
IDE name:					Arduino IDE
Flash Frequency:				80Mhz
PSRAM enabled:                               ?no? ?yes?
Upload Speed:					921600
Computer OS:                                  Ubuntu

### Description:
I am trying to interface an MPU9250 with ESP32. I need to avoid any delay between the movement of the IMU and the changes in the sensor readings. **I need to know which is the best release among(1.01 to 1.04) for stable i2c. Also I need to know which i2c baud rates are well tested.** I read from forums that there could a delay in the reading of the data due to prevelant bugs in esp32 i2c. I suppose that during testing some baud rates could have been more tested than others.

**Can the i2c bus resistance cause delay in the response of the senor values**

**Comment by stickbreaker** [comment]
The only problems you will run into with the ESP32 is its limited SCL stretching ability. The ESP32 will timeout after 13.1ms of SCL stretch and abort the transaction. 
from [MPU-9250 Product SpecificationDocument  Number:  PS-MPU-9250A-01Revision: 1.1Release Date: 06/20/2016Page 33of 42](https://www.invensense.com/wp-content/uploads/2015/02/PS-MPU-9250A-01-v1.1.pdf)
>START and STOP Conditions Data Format / Acknowledge
I2C data bytes are defined to be 8-bits long.  There is no restriction to the number of bytes transmitted per data transfer.    Each  byte  transferred  must  be  followed  by  an acknowledge  (ACK)  signal.    The  clock  for  the acknowledge signal is generated by the master, while the receiver generates the actual acknowledge signal by pulling down SDA and holding it low during the HIGH portion of the acknowledge clock pulse.  **If a slave is busy and cannot transmit or receive another byte of data until some other task has been performed, it can hold SCL LOW, thus forcing the master into a wait state.  Normal data transfer resumes when the slave is ready, and releases the clock line (refer to the following figure).**

There is no specified max wait period.  if the 13.1ms timeout is exceeded. an `I2C_ERROR_TIMEOUT` will be generated. you will have to recover from this timeout in your app. `bool success=Wire.begin();` should be used to recover the i2c bus, it will return false until the slave releases SCL, the Slave will usually still be in a READ state until you reset it. 

Bus speed does not effect this timeout, only CPU frequency.  The timeout is limited to 2^20 APB clock cycles.  APB clock is derived from either 80MHz or CPU frequency, whichever is lower.  So, if you reduce CPU frequency below 80MHz you increase the timeout period.  At 10MHz(min CPU freq with 40MHZ xtal) the timeout period is 104ms. 

If you use the standard `Wire()` single byte methods (`read(),write()`) you are limited to 128byte transactions.  if you use block methods:
```c++
// External Wire.h equivalent error Codes
typedef enum {
    I2C_ERROR_OK=0,
    I2C_ERROR_DEV,
    I2C_ERROR_ACK,
    I2C_ERROR_TIMEOUT,
    I2C_ERROR_BUS,
    I2C_ERROR_BUSY,
    I2C_ERROR_MEMORY,
    I2C_ERROR_CONTINUE,
    I2C_ERROR_NO_BEGIN
} i2c_err_t;

    i2c_err_t writeTransmission(uint16_t address, uint8_t* buff, uint16_t size, bool sendStop=true);
    i2c_err_t readTransmission(uint16_t address, uint8_t* buff, uint16_t size, bool sendStop=true, uint32_t *readCount=NULL);
``` 
Data size is limited to available 64k-1 bytes. 
Chuck.
