### ISSUE TITLE
Can't connect to ESP32 BLE via Service UUID

### ISSUE THREAD

**Issue by mrdc** [espressif/arduino-esp32#3397]
Hello,

I'm trying to connect to ESP32-Wroom from my iOS app via BLE using Service UUID, but I get an error that no device is connected. I can connect via BLE DeviceName or via DeviceUUID.

### Hardware:
Board:							ESP32 DevKit (38pin) (ESP32D0WDQ6 (revision 1))
Core Installation/update date:			ESP32 by Espressif v1.0.4
IDE name:					        Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                       no
Upload Speed:						921600
Computer OS:                                           Win

```cpp

Code was here

```

**Comment by chegewara** [comment]
This looks like issue with iPhone app.

**Comment by lyusupov** [comment]
@chegewara 

Should that:
```
  pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
  pAdvertising->setMinPreferred(0x12);
```
be actually coded like this:
```
  pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
  pAdvertising->setMaxPreferred(0x12);
```
?

**Comment by mrdc** [comment]
> be actually coded like this:

Probably yes, I've taken this code (marked as working) from one of issues: https://github.com/espressif/arduino-esp32/issues/2401
The sketch is from @chegewara

**Comment by chegewara** [comment]
> @chegewara
> 
> Shouldn't that:
> 
> ```
>   pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
>   pAdvertising->setMinPreferred(0x12);
> ```
> 
> be actually coded like this:
> 
> ```
>   pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
>   pAdvertising->setMaxPreferred(0x12);
> ```
> 
> ?

Yes, its typo.

**Comment by mrdc** [comment]
Makes no difference - iOS app can connect via DeviceName but via Service UUID.

**Comment by chegewara** [comment]
Check service UUID, maybe you have typo in iOS app.

**Comment by mrdc** [comment]
I've checked - it's copy paste from ESP32 sources...
