### ISSUE TITLE
How to set DHCP Client Name for ESP ? ETH.setHostname(); does not work !

### ISSUE THREAD

**Issue by GeorgeFlorian** [espressif/arduino-esp32#3398]
Board: Olimex ESP32-EVB

OS: Linux Mint 19.1

In the DHCP Client List of my Access Point, the ESP's Client Name is `unknown`.

I am using an ETH connection so I have tried using `ETH.setHostname(host_name);` but this doesn't work and, on top of that, I have also added `WiFi.setHostname("host_name");` which also seems to not resolve my issue.

How can I fix this ? Thank you !

**Comment by atanisoft** [comment]
I believe this is a know issue and is tracked in esp-idf as this functionality is provided by the LwIP layer and not the arduino-esp32 side.

**Comment by GeorgeFlorian** [comment]
> I believe this is a know issue and is tracked in esp-idf as this functionality is provided by the LwIP layer and not the arduino-esp32 side.

This roughly translates to "whoever uses arduino-esp32 can't set hostname", correct ?

**Comment by atanisoft** [comment]
Worse than that, it is not sent via the DHCP packets at all for esp-idf either.

You can however set the hostname via mdns which will work for other usecases.

**Comment by atanisoft** [comment]
https://github.com/espressif/arduino-esp32/issues/2537

**Comment by GeorgeFlorian** [comment]
Can I use `mDNS` with `ETH` and `ESPAsyncWebServer` and `UDP` and `TCP` ? It looks like `mDNS` is some sort of server.

**Comment by atanisoft** [comment]
Yes, it should work fine with all interfaces. mDNS uses a background task to listen and respond to UDP broadcast packets from other devices. Take a look at the examples [here](https://github.com/espressif/arduino-esp32/tree/master/libraries/ESPmDNS).

**Comment by Shuptuu** [comment]
Got a workaround based on the one used for WiFi.setHostname.
If you're using WiFi.onEvent, in case SYSTEM_EVENT_ETH_CONNECTED, add:
`ETH.config(INADDR_NONE, INADDR_NONE, INADDR_NONE, INADDR_NONE);
ETH.setHostname("myhostname");`
it works for me, no more "unknown" on my router.

**Comment by GeorgeFlorian** [comment]
> Got a workaround based on the one used for WiFi.setHostname.
> If you're using WiFi.onEvent, add in case SYSTEM_EVENT_ETH_CONNECTED:
> `ETH.config(INADDR_NONE, INADDR_NONE, INADDR_NONE, INADDR_NONE);`
> `ETH.setHostname("myhostname");`
> it works for me, no more "unknown" on my router.

Isn't `ETH.setHostname("myhostname");` used for Ethernet connection ? Why would it work on a WiFi connection ?

**Comment by mepster** [comment]
> Got a workaround based on the one used for WiFi.setHostname.
> If you're using WiFi.onEvent, add in case SYSTEM_EVENT_ETH_CONNECTED:
> `ETH.config(INADDR_NONE, INADDR_NONE, INADDR_NONE, INADDR_NONE);`
> `ETH.setHostname("myhostname");`
> it works for me, no more "unknown" on my router.

@Shuptuu thanks for the tip... from your suggestion I found that this simpler version works for me:

WiFi.begin(ssid, pass);
// doesn't work without the following line
WiFi.config(INADDR_NONE, INADDR_NONE, INADDR_NONE, INADDR_NONE);
WiFi.setHostname("FOOBAR");
 
I found that I did not have to set those event handlers.
