### ISSUE TITLE
super slow download from arduino ide board manager

### ISSUE THREAD

**Issue by ThomasWaldmann** [espressif/arduino-esp32#3413]
Does your server have a performance or other problem?

I am currently downloading the esp32 boards support from arduino ide's "boards manager" at about 20kB/s. Sometimes it is even much slower than that.

Last try, it aborted after downloading half of the 69.248kB package and the whole procedure is taking hours already, which is rather annoying.

I have a 250Mbit/s connection here and a speed test shows ok speed for my connection, so it seems to be either the server or the connection to it in the internet.

Debian Linux "stretch", Arduino IDE 1.8.10 64bit.

**Comment by ThomasWaldmann** [comment]
https://github.com/espressif/arduino-esp32/releases/download/1.0.4/esp32-1.0.4.zip

This is from the console log. So, is github slow or throttling connections?

**Comment by lbernstone** [comment]
How exactly would you like this issue resolved?

**Comment by ThomasWaldmann** [comment]
Does it matter? If it is resolved at all, I'm fine.

**Comment by WereCatf** [comment]
> Does your server have a performance or other problem?

Github is run by Espressif, it's not "their server." Github is owned by Microsoft.

> I have a 250Mbit/s connection here and a speed test shows ok speed for my connection, so it seems to be either the server or the connection to it in the internet.

And on the other hand, I just tested it and I got 9.78MBps, or 78.24Mbps.

The issue could very well be e.g. a routing-problem at your ISP or somewhere between your ISP and Github, for example. It's not necessarily anything to do with Github itself.

**Comment by ThomasWaldmann** [comment]
I can test it monday from another ISP to see if it can be reproduced.

**Comment by ThomasWaldmann** [comment]
Hmm, still need to test it again. If somebody else gets to it before me, feel free.

**Comment by fusionstream** [comment]
Obviously this is not espressif's problem but thought I'd chime in here that I'm having the same issue. Unbelievably slow. Visiting the sites is fine. Tried downloading the release directly via a download manager and that too is incredibly slow. Slower in fact. 3.4KBps is the peak and it's constantly cutting out. Each request to add a new chunk is replied with a 403.

**Comment by bepitulaz** [comment]
I'm also having the same issue. Downloading is very very very slow.

**Comment by canDry** [comment]
Ditto.  Getting ridiculously throttled by somebody!!

**Comment by ThomasWaldmann** [comment]
Considering that likely a lot of people are seeing this: reopen issue?

**Comment by chegewara** [comment]
Reopen issue wont change too much. Its problem with slow github server and solution is to use different servers provider, but its no point to use github in that case.

**Comment by hikmahgumelar** [comment]
it's other server to download? Download too slow from my country

**Comment by ThomasWaldmann** [comment]
@igrr reopen and try to provide a faster distribution mechanism?

**Comment by lbernstone** [comment]
If you could build a worldwide CDN to provide your 50MB of free software, that'd be great.

**Comment by GasAlbert** [comment]
Actually seems to be the espressif server thats extreamly slow:

**Comment by s-a-tanjim** [comment]
I had the same issue. 
I downloaded those file separately from the browser(as it was faster than downloading from Arduino IDE) 
1. https://github.com/espressif/arduino-esp32/releases/download/1.0.4/esp32-1.0.4.zip
2. https://dl.espressif.com/dl/esptool-2.6.1-windows.zip
3. https://dl.espressif.com/dl/xtensa-esp32-elf-win32-1.22.0-80-g6c4433a-5.2.0.zip
4. https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp32-win32.zip
Download this 4file from given link. and copy those to "C:\Users\[UserName]\AppData\Local\Arduino15\staging\packages\" directory.
Then open Arduino Board Manager, Search for "esp32", and click install. As those files were already downloaded, so this time it will just install those files.
Note: If you can't find "esp32" in board manager, make sure you added this link : "https://dl.espressif.com/dl/package_esp32_index.json" into "Additional Board Manager URLs" (You will find this option in File>Preference)

**Comment by atanisoft** [comment]
> 4\. Note: If you can't find "esp32" in board manager, make sure you added this link : "https://dl.espressif.com/dl/package_esp32_index.json" into "Additional Board Manager URLs" (You will find this option in File>Preference)

Note that link is not valid or supported. The correct link is https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json as documented [here](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md).

**Comment by AugustoOspal** [comment]
I've just found the solution. I was trying to download the file from Argentina, but then I tried by downloading it using a VPN, and it worked perfectly.

**Comment by dropthemasquerade** [comment]
> I had the same issue.
> I downloaded those file separately from the browser(as it was faster than downloading from Arduino IDE)
> 
> 1. https://github.com/espressif/arduino-esp32/releases/download/1.0.4/esp32-1.0.4.zip
> 2. https://dl.espressif.com/dl/esptool-2.6.1-windows.zip
> 3. https://dl.espressif.com/dl/xtensa-esp32-elf-win32-1.22.0-80-g6c4433a-5.2.0.zip
> 4. https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp32-win32.zip
>    Download this 4file from given link. and copy those to "C:\Users[UserName]\AppData\Local\Arduino15\staging\packages" directory.
>    Then open Arduino Board Manager, Search for "esp32", and click install. As those files were already downloaded, so this time it will just install those files.
>    Note: If you can't find "esp32" in board manager, make sure you added this link : "https://dl.espressif.com/dl/package_esp32_index.json" into "Additional Board Manager URLs" (You will find this option in File>Preference)

I tried this solution yesterday, but it automatic remove what I have done, and do download itself again! so I think it maybe have a mark or flag, which I need to set, and then I can skip download from internet. But I can't find that right now. Can anyone help?

**Comment by andialles** [comment]
I had that issue as well, solved it by using a VPN to Hong Kong...

**Comment by tomg404** [comment]
> 
> 
> I had that issue as well, solved it by using a VPN to Hong Kong...

Solved the issue for me as well!

**Comment by RandomVertebrate** [comment]
The VPN does seem to help. Routing through Singapore rn.

**Comment by applehat** [comment]
Just adding that I too am downloading at a somewhat reasonable speed now that I'm VPN'
d to Hong Kong

**Comment by jacoblann** [comment]
> I had the same issue.
> I downloaded those file separately from the browser(as it was faster than downloading from Arduino IDE)
> 
> 1. https://github.com/espressif/arduino-esp32/releases/download/1.0.4/esp32-1.0.4.zip
> 2. https://dl.espressif.com/dl/esptool-2.6.1-windows.zip
> 3. https://dl.espressif.com/dl/xtensa-esp32-elf-win32-1.22.0-80-g6c4433a-5.2.0.zip
> 4. https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp32-win32.zip
>    Download this 4file from given link. and copy those to "C:\Users[UserName]\AppData\Local\Arduino15\staging\packages" directory.
>    Then open Arduino Board Manager, Search for "esp32", and click install. As those files were already downloaded, so this time it will just install those files.
>    Note: If you can't find "esp32" in board manager, make sure you added this link : "https://dl.espressif.com/dl/package_esp32_index.json" into "Additional Board Manager URLs" (You will find this option in File>Preference)

This method works really well for me! Thanks!

**Comment by spielzimmer3000** [comment]
I connected to my smartphone's hotspot before installing the esp8266 package in Boards Manager and it worked very well. Connected to my WiFi at home it was unbelievably slow.

**Comment by RandomVertebrate** [comment]
For me what finally worked was restarting the download late at night (3am)

**Comment by ChR-iSz** [comment]
Same here. Need 3 Days to download! What a shit!

**Comment by me-no-dev** [comment]
links for the upcoming releases have been switched to github. You can use the dev package manager json to give them a shot.

**Comment by lbernstone** [comment]
Are we going to open a new issue for complaints about slow downloads in China, or can we reuse this one?

**Comment by me-no-dev** [comment]
we will need to have separate json hosted there and pointing to the files there for CN users.

**Comment by xlla** [comment]
> I had the same issue.
> I downloaded those file separately from the browser(as it was faster than downloading from Arduino IDE)
> 
> 1. https://github.com/espressif/arduino-esp32/releases/download/1.0.4/esp32-1.0.4.zip
> 2. https://dl.espressif.com/dl/esptool-2.6.1-windows.zip
> 3. https://dl.espressif.com/dl/xtensa-esp32-elf-win32-1.22.0-80-g6c4433a-5.2.0.zip
> 4. https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp32-win32.zip
>    Download this 4file from given link. and copy those to "C:\Users[UserName]\AppData\Local\Arduino15\staging\packages" directory.
>    Then open Arduino Board Manager, Search for "esp32", and click install. As those files were already downloaded, so this time it will just install those files.
>    Note: If you can't find "esp32" in board manager, make sure you added this link : "[https://dl.espressif.com/dl/package_esp32_index.json"[*]](https://dl.espressif.com/dl/package_esp32_index.json%22%5B*%5D) into "Additional Board Manager URLs" (You will find this option in File>Preference)
> 
> [*]Update: Use this link "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json" as documented here.

For mac user, where is the corresponding folder of "C:\Users[UserName]\AppData\Local\Arduino15\staging\packages"

**Comment by asdf23** [comment]
Japan is now working as well.. it's not slow, it halts after an exact amount around 40,000kb
