### ISSUE TITLE
Ble Beacon Scan  ISSUE

### ISSUE THREAD

**Issue by miracle0419** [espressif/arduino-esp32#3423]
I have trying BLE SCAN by ESP32.
but, The result is that one device B cannot scan.
It is current BLEscan value, and Device B  cannot scan even if the setting is changed.
PLS let me no if you have any idea.

  pBLEScan->setInterval(50);
  pBLEScan->setWindow(30);  // less or equal setInterval value
  foundDevices = pBLEScan->start(5 /*scanTime*/, false);

![Screenshot_20191029-005017_nRF Connect](https://user-images.githubusercontent.com/23492439/67776856-2a784a00-fa1e-11e9-9d0a-fbfe64c1f7c3.png)

**Comment by sachinrana2k11** [comment]
hi man, it works just you have to change something, look this code it will help https://github.com/sachinrana2k11/Arnowa_NODES_CODES/blob/master/BLE_SCAN_ESP32/src/main.cpp

**Comment by miracle0419** [comment]
Thanks for your update. but, still have problem.

Below, company all product  not found.
http://www.skylabmodule.com/products-list/bluetooth-beacons/

As I know this product used  nRF52832 chipset of Nordic.

**Comment by sachinrana2k11** [comment]
Can you poat some pictures of the outputs. What are you getting? While scanning those beacons.

**Comment by miracle0419** [comment]
Hi Please see below my result. Also, I trying source code for es-idf-v3.2.3/ble_ibeacon and arduino.

**Comment by chegewara** [comment]
Hi,
from 1st screenshot you can see that nRF connect does not recognize iBeacon B as a real iBeacon, which means its advertising format is incorrect. This is probably the reason you cant find it with scanner.

**Comment by miracle0419** [comment]
Tow testing device works fine on the nrf connect by Nordic.


![Screenshot_20200109-123310_nRF Connect](https://user-images.githubusercontent.com/23492439/72102956-08802b00-32dd-11ea-800f-a007a47599da.png)

**Comment by tekinyasin02** [comment]
Hello. I have this problem. Did you solve it?

**Comment by yuzuka4573** [comment]
@tekinyasin02 maybe not
I had a similar situation happen to me. I'm trying with the library samples "BLE_iBeacon" and "BLE_Beacon_Scanner", but the scanner doesn't detect BLE_iBeacon.  
Android apps (nRF Connect and Beacon Analyzer) do detect it as an iBeacon. Conversely, BLE_Beacon_Scanner detects commercially available iBeacons, but I still haven't figured out what's causing it.

**Comment by siifuu** [comment]
@yuzuka4573 Hello! I have the exact same issue, have you figured out its cause?

**Comment by yuzuka4573** [comment]
@siifuu 
Partially solved. If you don't use Deepsleep, the iBeacon will send successfully, but the error itself doesn't go away.( https://github.com/espressif/arduino-esp32/issues/4462 )
