### ISSUE TITLE
Can't init sda=1, scl=0 while scanning device BME280 

### ISSUE THREAD

**Issue by desmatron** [espressif/arduino-esp32#3424]
### Hardware:
Board: ESP32 Dev Module - ESP32D0WDQ6 (revision 1)
Core Installation version: 1.0.4
IDE name: Arduino IDE
Flash Frequency: 40Mhz
Flash Mode: DIO
PSRAM enabled: no
Upload Speed: 115200
Computer OS: Windows 10

### Description:
I'm not able to see sensor BME280 with my ESP32, while connecting it to pin 21 (SDA) and 22 (SCL) I'm receiving this error: 

_[E][esp32-hal-i2c.c:1426] i2cCheckLineState(): Bus Invalid State, TwoWire() Can'                                                                                                        t init sda=0, scl=1
Found 0 device(s)._

### Sketch:  
```cpp

// ESP32 I2C Scanner
// Based on code of Nick Gammon  http://www.gammon.com.au/forum/?id=10896
// ESP32 DevKit - Arduino IDE 1.8.5
// Device tested PCF8574 - Use pullup resistors 3K3 ohms !
// PCF8574 Default Freq 100 KHz 

#include <Wire.h>

void setup()
{
  Serial.begin (115200);  
  Wire.begin (21, 22);   // sda= GPIO_21 /scl= GPIO_22
}

void Scanner ()
{
  Serial.println ();
  Serial.println ("I2C scanner. Scanning ...");
  byte count = 0;

  Wire.begin();
  for (byte i = 8; i < 120; i++)
  {
    Wire.beginTransmission (i);          // Begin I2C transmission Address (i)
    if (Wire.endTransmission () == 0)  // Receive 0 = success (ACK response) 
    {
      Serial.print ("Found address: ");
      Serial.print (i, DEC);
      Serial.print (" (0x");
      Serial.print (i, HEX);     // PCF8574 7 bit address
      Serial.println (")");
      count++;
    }
  }
  Serial.print ("Found ");      
  Serial.print (count, DEC);        // numbers of devices
  Serial.println (" device(s).");
}

void loop()
{
  Scanner ();
  delay (3000);
}
```

**Comment by stickbreaker** [comment]
@desmatron do you have pullup resistors on SDA and SCL?

  The error message is telling you that the SDA pin (GPIO21) is being held low by something.  A hardware Error. Either no pullup, or your BME280 sensor is holding SDA low?.

Measure the voltage on your SDA pin, it should be 3.3v most of the time.

Chuck.
