### ISSUE TITLE
[Using as ESP-IDF component : No such file or directory] esp_bt_defs.h and esp_bt_main.h	

### ISSUE THREAD

**Issue by ESP32DE** [espressif/arduino-esp32#343]
**Using as ESP-IDF component**

hi 

tested just in time this procedure
install arduino as component under template project [like this description](https://github.com/espressif/arduino-esp32#using-as-esp-idf-component)

after doings i start make, and get error 

> fatal error: esp_bt_defs.h: No such file or directory	
> esp32-hal-bt.c	/_template_empty_esp32_arduino/components/arduino/cores/esp32	
> line 18	C/C++ Problem
> 

> fatal error: esp_bt_defs.h: No such file or directory	
> esp32-hal-bt.c	/_template_empty_esp32_arduino/components/arduino/cores/esp32	
> line 19	C/C++ Problem
> 

for this two files:

https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-bt.c#L18
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-bt.c#L19

after comment the includes for this two files, 

```
// #include "esp_bt_defs.h"
// #include "esp_bt_main.h"

```
compile is ok.

best wishes
rudi ;-)

**Comment by Curclamas** [comment]
Hey Rudi, it looks like you have BT disabled in sdkconfig/```make menuconfig```. When you enable it the code should compile without the commented out includes.
FYI I did encounter the same problem and fixed it by:
```c++
#ifdef BT_ENABLED
#include "esp_bt_defs.h"
#include "esp_bt_main.h"
...
#endif
```

@me-no-dev we talked about that on gitter, maybe we should have this ifdef and the possibility to "opt out" from BT in ```make menuconfig``` (while leaving it default on of course)
