### ISSUE TITLE
Connect between 2 ESP32

### ISSUE THREAD

**Issue by gamer421** [espressif/arduino-esp32#3437]
Is it possible to pair 2 ESP32 and be able to send data between them?

Thanks

**Comment by lbernstone** [comment]
There are probably 100 ways to do this.  Maybe explain which you mean.

**Comment by gamer421** [comment]
> There are probably 100 ways to do this. Maybe explain which protocol you mean.

I am sorry, I am new to this. 
So basically I have two ESP32 and I want to connect them using bluetooth serial, I want to be able to send data from one ESP32 to the other one to activate physical sensor readings.
I haven't found anything explaining on how to connect two ESP32 using bluetooth. The only thing I find is to teach you how to connect an ESP32 to a smartphone through a bluetooth terminal app.
I really just need help to connect them. I can't find a way because there's no interface like the bluetooth terminal app where you just click the device you want to connect to.

Thanks

**Comment by gamer421** [comment]
Anyone? Please?

**Comment by beegee-tokyo** [comment]
Serial
Bluetooth
WiFi
I2C
SPI

You choose, hit Google Search, and will get solutions

**Comment by gamer421** [comment]
> Serial
> Bluetooth
> WiFi
> I2C
> SPI
> 
> You choose, hit Google Search, and will get solutions

Like I said in the previous post, I couldn't find any information on how to communicate between 2 ESP32 using bluetooth classic.

**Comment by beegee-tokyo** [comment]
Issues are for bugs and mistakes in the Arduino - ESP32 framework, not a training/help forum. Check the examples here https://github.com/espressif/arduino-esp32/tree/master/libraries/BluetoothSerial/examples

**Comment by gamer421** [comment]
> Issues are for bugs and mistakes in the Arduino - ESP32 framework, not a training/help forum. Check the examples here https://github.com/espressif/arduino-esp32/tree/master/libraries/BluetoothSerial/examples

I am new at this, I'm sorry... Anyway I don't see a reason for you to act like that, but thank you for all the help.

**Comment by gamer421** [comment]
Would appreciate if anyone else could help me do this.

**Comment by atanisoft** [comment]
@gamer421 I'd suggest posting this in the forum on esp32.com instead of here since as @beegee-tokyo mentioned this tracker is for bugs in the arduino-esp32 code only.

**Comment by gamer421** [comment]
> @gamer421 I'd suggest posting this in the forum on esp32.com instead of here since as @beegee-tokyo mentioned this tracker is for bugs in the arduino-esp32 code only.

Ok thank you.

**Comment by me-no-dev** [comment]
you have the examples in the link above. they will connect two ESPs together over BT serial. All you have to do is properly configure both sketches. If you are new, this will be a good example for  you to get on with reading example code. You will need this in the future.
