### ISSUE TITLE
Type comparison is always false due to limited range of data type [-Wtype-limits]

### ISSUE THREAD

**Issue by ESP32DE** [espressif/arduino-esp32#344]
hi

https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/libb64/cdecode.c#L15
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/libb64/cdecode.c#L45
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/libb64/cdecode.c#L55
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/libb64/cdecode.c#L66
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/libb64/cdecode.c#L77

best wishes
rudi ;-)

**Comment by me-no-dev** [comment]
Yes I've seen those and I wonder what they are about. The library is working fine though. Char is signed AFAIK, so I really do not get the reason for the warnings.

**Comment by me-no-dev** [comment]
Nevermind :) found it
