### ISSUE TITLE
Arduino Blink sketch does not start on my ESP32 board

### ISSUE THREAD

**Issue by croisez** [espressif/arduino-esp32#346]
The first sketch I try, generally, when I want to test a new Arduino board, is the blink one.
Here it is:
<PRE>
#define LED_BUILTIN 13

// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_BUILTIN, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  Serial.println("Hello world");
  digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}
</PRE>

So did I on my brand new ESP32 WEMS board (7$ on Aliexpress).

The flashing was finally ok (though pushing on BOOT button is required before flashing process begin)
<PRE>
Linking everything together...
"/Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc" -nostdlib "-L/Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/sdk/lib" "-L/Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/sdk/ld" -T esp32_out.ld -T esp32.common.ld -T esp32.rom.ld -T esp32.peripherals.ld -u call_user_start_cpu0 -Wl,--gc-sections -Wl,-static -Wl,--undefined=uxTopUsedPriority  -Wl,--start-group "/var/folders/zx/4rs36y2j0315wny99n1j7fj80000gn/T/arduino_build_866408/sketch/Blink.ino.cpp.o" "/var/folders/zx/4rs36y2j0315wny99n1j7fj80000gn/T/arduino_build_866408/arduino.ar" -lgcc -lstdc++ -lapp_update -lbootloader_support -lbt -lbtdm_app -lc -lc_nano -lcoap -lcoexist -lcore -lcxx -ldriver -lesp32 -lethernet -lexpat -lfatfs -lfreertos -lhal -ljsmn -ljson -llog -llwip -lm -lmbedtls -lmdns -lmicro-ecc -lnet80211 -lnewlib -lnghttp -lnvs_flash -lopenssl -lphy -lpp -lrtc -lsdmmc -lsmartconfig -lsoc -lspi_flash -ltcpip_adapter -lulp -lvfs -lwpa -lwpa2 -lwpa_supplicant -lwps -lxtensa-debug-module -Wl,--end-group -Wl,-EL -o "/var/folders/zx/4rs36y2j0315wny99n1j7fj80000gn/T/arduino_build_866408/Blink.ino.elf"
python "/Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/gen_esp32part.py" -q "/Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/partitions/default.csv" "/var/folders/zx/4rs36y2j0315wny99n1j7fj80000gn/T/arduino_build_866408/Blink.ino.partitions.bin"
"/Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/esptool" --chip esp32 elf2image --flash_mode "dio" --flash_freq "80m" --flash_size "4MB" -o "/var/folders/zx/4rs36y2j0315wny99n1j7fj80000gn/T/arduino_build_866408/Blink.ino.bin" "/var/folders/zx/4rs36y2j0315wny99n1j7fj80000gn/T/arduino_build_866408/Blink.ino.elf"
esptool.py v2.0-beta2

Sketch uses 119,358 bytes (11%) of program storage space. Maximum is 1,044,464 bytes.
Global variables use 9,492 bytes (3%) of dynamic memory, leaving 285,420 bytes for local variables. Maximum is 294,912 bytes.
/Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/esptool --chip esp32 --port /dev/cu.SLAB_USBtoUART --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_freq 80m --flash_mode dio --flash_size 4MB 0x1000 /Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/sdk/bin/bootloader.bin 0x8000 /var/folders/zx/4rs36y2j0315wny99n1j7fj80000gn/T/arduino_build_866408/Blink.ino.partitions.bin 0xe000 /Users/lmc/Dropbox/arduino/hardware/espressif/esp32_/tools/partitions/boot_app0.bin 0x10000 /var/folders/zx/4rs36y2j0315wny99n1j7fj80000gn/T/arduino_build_866408/Blink.ino.bin 
esptool.py v2.0-beta2
Connecting.....
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Attaching SPI flash...
Configuring flash size...
Flash params set to 0x022f
Compressed 12352 bytes to 7462...

Writing at 0x00001000... (100 %)
Wrote 12352 bytes (7462 compressed) at 0x00001000 in 0.1 seconds (effective 1136.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 105...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (105 compressed) at 0x00008000 in 0.0 seconds (effective 7389.2 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 35159.6 kbit/s)...
Hash of data verified.
Compressed 202928 bytes to 65006...

Writing at 0x00010000... (25 %)
Writing at 0x00014000... (50 %)
Writing at 0x00018000... (75 %)
Writing at 0x0001c000... (100 %)
Wrote 202928 bytes (65006 compressed) at 0x00010000 in 1.5 seconds (effective 1058.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting...
</PRE>

And After pushing on RST button to restart the board, the sketch does not start as expected:

<PRE>
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0x00
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0008,len:8
load:0x3fff0010,len:2036
load:0x40078000,len:9988
load:0x40080000,len:252
entry 0x40080034
</PRE>

I expected a "Hello World" message on the terminal, and a blinking LED at 1Hz. But the program seems to be stuck during boot.

I know there are different binaries that are flashed along with the user binary (containing the sketch).
As the board is working well when programmed by Eclipse/esp-idf toolchain, there shall be a difference here with ESP32-Arduino.
What could be the problem? What is wrong, or missing ? 
How could I debug this?

EDIT:
Note that if I flash the NodeMcu-Esp32 firmware binary file (https://github.com/Nicholas3388/LuaNode/blob/master/LuaNode_Esp32/firmware/LuaNode_201703021524.bin), this firmware does start and is apparently working ok.

<PRE>
hardware/espressif/esp32_/tools/esptool --chip esp32 --port /dev/cu.SLAB_USBtoUART --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_freq 80m --flash_mode dio --flash_size 4MB 0x1000 LuaNode_201703021524.bin 
esptool.py v2.0-beta2
Connecting....
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Attaching SPI flash...
Configuring flash size...
Flash params set to 0x022f
Compressed 734848 bytes to 395779...
Wrote 734848 bytes (395779 compressed) at 0x00001000 in 7.0 seconds (effective 835.4 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting...
</PRE>

This LuaNode firmware is given as one big piece, flashing starting from 0x1000.
On the contrary, the Arduino binary is flashed in multiple pieces as follows:
0x1000 bootloader.bin
0x8000 Blink.ino.partitions.bin
0xe000 boot_app0.bin
0x10000 Blink.ino.bin

**Comment by copercini** [comment]
You forgot to start the Serial, like: 
`Serial.begin(115200);`
