### ISSUE TITLE
Ethernet Mac Address

### ISSUE THREAD

**Issue by vito45h** [espressif/arduino-esp32#3466]
I am looking to use the function uint8_t * macAddress(uint8_t* mac); provided in ETH.h
I'm using the latest arduino Espressif 32 1.11.1
The following code works for Wifi but gives a compile error with ETH.macAddress(mac);
I made a change to ETH.cpp line 270 to uint8_t * ETHClass::macAddress(uint8_t* mac) and now the code compiles and works.
Should the macAddress function be added to the ETH class or is there a different way of accessing the ethernet mac?

` 
uint8_t mac[6];
                if (getNetworkMode() == ETHERNET)
                {
                        ETH.macAddress(mac);
                }
                else
                {
                        WiFi.macAddress(mac);
                }
`

**Comment by lbernstone** [comment]
You are welcome to submit any pull requests to the code.  This is a community supported project.
