### ISSUE TITLE
package_esp32_index.json not accessible

### ISSUE THREAD

**Issue by tjmc** [espressif/arduino-esp32#3474]
Command to run
`curl -v https://dl.espressif.com/dl/package_esp32_index.json`

```
*   Trying 119.9.91.16...
* TCP_NODELAY set
* Connected to dl.espressif.com (119.9.91.16) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.espressif.com:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.espressif.com:443 
```

https://www.isitdownrightnow.com/dl.espressif.com.html reports down as well

**Comment by diogosm** [comment]
Same here, so, I can't install the board :(

**Comment by rdvojmoc** [comment]
Same issue here. When we can expect a working server?

**Comment by cmaile** [comment]
+1

**Comment by nikmess** [comment]
+1

**Comment by Masonl23** [comment]
+1

**Comment by hoverflow** [comment]
+1

**Comment by chegewara** [comment]
Should be fixed by now.

**Comment by tjmc** [comment]
Thanks for the quick response!

**Comment by jramonlab** [comment]
Hello,
I think server is down again.
I get error when setting the ESP32 board on the board manager.
**Error downloading https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json**

**Comment by jramonlab** [comment]
Hi,
I´ve found this link in other issue:
[https://dl.espressif.com/dl/package_esp32_index.json](url)

It seems to work. But not sure about the difference between this and the one on the installation instructions.
This is version 1.0.4.
