### ISSUE TITLE
DNS no detected 

### ISSUE THREAD

**Issue by moijerem59** [espressif/arduino-esp32#3477]
Hello
How do we change the DNS name on esp32 (currently expressive.local) Thank you
Because I use the library mdns.
If I connect via the web page via the dns configured no problem
If I ping this address I have a ping answer
On the other hand if I interrogate the DNS of my Box this one is not identical: s

**Comment by sansillusion** [comment]
Use :
MDNS.begin("namehere");

Le mer. 13 nov. 2019 12 h 52 p.m., moijerem59 <notifications@github.com> a
écrit :
