### ISSUE TITLE
Little problem in BasicOTA.ino without md5 password...

### ISSUE THREAD

**Issue by lrmoreno007** [espressif/arduino-esp32#348]
Hi, there is a little problem using the BasicOTA.ino example. There are 3 ways to identify yourself:
- Without password
- With password
- With MD5 password

When using the first and second option, you get the error: [ERROR]: 1460. But interestingly the sketch has been loaded and has overwritten the previous one perfectly, I've checked it by including a variable that increases the version number. Therefore the problem is only that it gives the process as error and the red sign appears in Arduino.

When I use the third option (MD5) everything is perfect.

Regards and thanks for everything.
----------------------------------------------------------------------------------------------------
- Git version
- ESP32-ST (WEMOS Lolin32 is selected)
![sin titulo](https://cloud.githubusercontent.com/assets/7408539/25680094/f420c468-304f-11e7-85fd-ce26d7f6849d.jpg)

**Comment by me-no-dev** [comment]
Do not mind this error ;) I know about it and just have not properly caught the reason for it. Sketch is uploaded OK unless you get a more meaningful error. 1460 is the size of the packets it got, so all is good ;)

**Comment by lrmoreno007** [comment]
It's solved with the last git version.

Thanks.
