### ISSUE TITLE
Secure Connection to Gmail SMTP server fails

### ISSUE THREAD

**Issue by Al-Imran** [espressif/arduino-esp32#3482]
### Hardware:
Board:							WEMOS LOLIN32
Core Installation/update date:		15/Nov/2019 - esp32 v1.0.4
IDE name:						Arduino IDE v1.8.7 and Visual Studio w Visual Micro Ext.
Flash Frequency:					80Mhz
PSRAM enabled:                                      Default
Upload Speed:					921600
Computer OS:                                          Windows 10

### Description:
I can not establish a secure connection to the gmail smtp server. It always fails. I can not get past the following line. It returns 0.

### Issue:
`client.connect(_GMailServer, 465)`

### Arduino Code:
`
#include<esp_wifi.h>
#include<WiFiClientSecure.h>

WiFiClientSecure client;

const char* _GMailServer = "smtp.gmail.com";

void setup() {
	Serial.begin(115200);
	delay(10);

	Serial.print("Connecting to ");
	Serial.println(_ssid);

	WiFi.begin(_ssid, _password);
	while (WiFi.status() != WL_CONNECTED) {
		delay(500);
		Serial.print(".");
	}
	Serial.println("");
	Serial.println("My IP address: ");
	Serial.println(WiFi.localIP());

	delay(1000);
	Serial.println("Attempting to connect to GMAIL server"); 
	if (client.connect(_GMailServer, 465) == 1) {
		Serial.println(F("Connected"));
	}
	else {
		Serial.print(F("Connection failed:")); 
                char err_buf[100];
		if (client.lastError(err_buf, 100) < 0) {
			Serial.println(err_buf);
		}
		else {
			Serial.println("Connection error");
		}
		return 0;
	}

        ...
}

void loop() {
}

`

### Serial Output:
Connecting to SSID
..
My IP address: 
192.XXX.YYY.ZZZ
Attempting to connect to GMAIL server
Connection failed:UNKNOWN ERROR CODE (0001)

**Comment by atanisoft** [comment]
unless you put in some certs the WiFiClientSecure will always reject the SSL connection as it can't validate the connection.

**Comment by Al-Imran** [comment]
How do I obtain the certificate? Thanks @atanisoft

**Comment by lbernstone** [comment]
0 is a successful connection.  If there is no cert, it will accept whatever the server hands out.  Turn on verbose debugging.

**Comment by Al-Imran** [comment]
@lbernstone It might be a foolish question but how would I do so? What exactly am I looking for?

**Comment by lbernstone** [comment]
Use the "ESP32 dev module" board.  Core debug level is in the tools menu.  You aren't looking for anything in particular, it will just show you the SSL transaction (and any errors).

**Comment by Al-Imran** [comment]
This is what the verbose output looks like:
`Attempting to connect to GMAIL server
[V][ssl_client.cpp:56] start_ssl_client(): Free internal heap before TLS 265456
[V][ssl_client.cpp:58] start_ssl_client(): Starting socket
[E][ssl_client.cpp:87] start_ssl_client(): Connect to Server failed!
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1
[V][ssl_client.cpp:248] stop_ssl_socket(): Cleaning SSL connection.`

**Comment by Al-Imran** [comment]
Apparently, the code failed to connect to the server since I was on my organization network. Probably, because some special ports are blocked on the firewall for security purposes. Creating a WiFi hotspot on my phone solved the issue. Thanks all. Hope it will help someone in the future.
