### ISSUE TITLE
[FR] Include SoftwareSerial by default in Arduino core for ESP32

### ISSUE THREAD

**Issue by Hedda** [espressif/arduino-esp32#3484]
[Feature Request] Please include the SoftwareSerial library (SoftwareSerial.h & SoftwareSerial.cpp) by default in Arduino core for ESP32 as it is among other things is required by teemuatlut "TMCStepper" library.

https://github.com/arduino-org/Arduino/tree/master/hardware/arduino/samd/libraries/SoftwareSerial

For reference see https://github.com/teemuatlut/TMCStepper/issues/35 and https://github.com/teemuatlut/TMCStepper/issues/59

SoftwareSerial library is required by teemuatlut TMCStepper Arduino library for Trinamic TMC stepper motor drivers used by Marlin Firmware (the optimized firmware for RepRap 3D printers based on the Arduino platform, see http://www.marlinfw.org ) as Marlin 2.0 will be supported to run on ESP32).

Without that SoftwareSerial library included by default the Arduino core for ESP32 is not a Software Serial Compatible Platform (a.k.a. "SW serial capable platforms") and then needs a workaround like https://github.com/teemuatlut/TMCStepper/pull/62

**Comment by atanisoft** [comment]
With three hardware uarts on the esp32 it doesn't make much sense to use SoftwareSerial. Per the issues and PR you linked to that library already supports using a real uart so it would be better to use that approach.

**Comment by lbernstone** [comment]
There is a software serial [library](https://github.com/plerup/espsoftwareserial) in the Arduino library manager.

**Comment by Hedda** [comment]
@atanisoft UART does not fully replace Serial interface for all scenarios in the world of stepper motors as used by robots, 3D-printers, CNC machines, laser and vinyl cutters, etc..  

Having the option to simply choose if Serial should be used instead of UART and vice versa is a very convenient and user-friendly usability feature.

Just saying that you can use UART instead of Serial is not a solution to this feature request, that can at best only be seen as a workaround. Please don't close this feature request with only that statement as the final answer.

**Comment by atanisoft** [comment]
@Hedda the HardwareSerial interface works quite well for almost any application. There are a few usecases for not using it on the esp32 but they are very specialized protocols typically. As @lbernstone mentions there is a SoftwareSerial lib available today in the library manager inside the Arduino IDE so it doesn't necessarily need to be included as part of the arduino-esp32 core and be maintained as such.

**Comment by me-no-dev** [comment]
@Hedda at the same time you do not have enough pins for many steppers, so maybe look into TMC2209 and chain them properly (one UART used and each has it's own ID, much like I2C)

**Comment by me-no-dev** [comment]
Oh... you can also switch the pins of the UART around and use again only 1

**Comment by me-no-dev** [comment]
To clarify why we are against SoftSerial: ESP32 runs on FreeRTOS, which does not guarantee any time for your code. SoftSerial uses delays to send and receive data and the ESP kernel can at any point switch to another task and make the delay incorrect.
