### ISSUE TITLE
feature question: utilize  320kB RAM for static variables in Arduino IDE?

### ISSUE THREAD

**Issue by dsyleixa** [espressif/arduino-esp32#3486]
will it be possible soon to  utilize the esp32's entire 320kB RAM for static variables in the Arduino IDE?

**Comment by chegewara** [comment]
Sure, but you have to connect 10 esp32 in parallel.

**Comment by dsyleixa** [comment]
on a s

**Comment by stickbreaker** [comment]
@dsyleixa 
Nope.

If you want to use the full hardware abilities write your code to  bare metal, ditch Arduino/ESPIDF and write your own environment.

Ardunio-Esp32 is the Arduino Environment, on top of ESP-IDF which is base on FreeRTOS.   If you want all resources under your control, you have to take responsibility for those resources. 

Chuck.

**Comment by chegewara** [comment]
On boards with PSRAM you can use extra ram to do it.
