### ISSUE TITLE
ESP32 SerialToSerialBTM logs "Connected Succesfully!" even without any connection. And it don't asks for a PIN on a device too

### ISSUE THREAD

**Issue by SergioUno** [espressif/arduino-esp32#3490]
### Hardware:
Board:							clean ESP32 DEVKIT V1, not paired before to any devices.
Core Installation version:			1.0.4
IDE name:						Arduino IDE 1.8.9
Flash Frequency:					?40Mhz?
PSRAM enabled:                                    ?no? ?yes?
Upload Speed:					921600
Computer OS:                                        Windows 10

### Description:
ESP32 SerialToSerialBTM sketch prints in log "Connected Succesfully!" even without any connection
It logs tihis even with all devices aroung in flight mode!

### Sketch: 
SerialToSerialBTM.ino example without changes

### Debug Messages:
```
The device started in master mode, make sure remote BT device is on!
Connected Succesfully!
```
"Connected Succesfully!" appeares with delay about 30 seconds (looks like a time-out)

**Comment by Havolture** [comment]
I have the same issue on a Himalaya Matrix Core board, too.
In terminal I have the "Connected Succesfully!" message but no connection.
