### ISSUE TITLE
"#pragma region" and "#pragma endregion" not possible with compiler warning on Arduino IDE

### ISSUE THREAD

**Issue by wrgallo** [espressif/arduino-esp32#3494]
**Bug reproduction steps:**

1. Arduino 1.8.10 IDE > File > Preferences > Set Compiler Warnings to "More" or "All"

2. In your code divide your region with "#pragma region NAME_OF_REGION" and "#pragma endregion"

Example:
```
#pragma region CONSTANTS
const int myConstant = 3;
#pragma endregion // CONSTANTS
```

3. Try to Verify/Upload

**Expected Result:**

#pragma region , #pragma endregion won't be treated as unknown pragmas

**Actual Result:**

The warning of the unknown pragma region, and endergion will be treated as errors ([-Werror=unknown-pragmas]).

---

Pragma region is very popular and useful to collapse regions with others editors such Visual Studio Code. (https://docs.microsoft.com/en-us/cpp/preprocessor/region-endregion?view=vs-2019)

---
How to divide my code with #pragma region and still be able to see all the warnings with Arduino IDE?

**Comment by lbernstone** [comment]
Near the top of <arduino-esp32>/platform.txt there are lines for compiler.c.flags and compiler.cpp.flags.  Add the -Wno-unknown-pragmas flag to those, and restart the IDE.
