### ISSUE TITLE
Can I use a keyboard with an ESP32 ? Or a keypad ? How ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [espressif/arduino-esp32#3496]
Hello !

I am interested into connecting a keyboard to an ESP32. I would need to to have all the number keys, an Enter and a Backspace. Much like an ATM keyboard.

I couldn't find anything useful online, other than users saying that is very hard to implement this.

Any thoughts or ideas ? Thank you !

**Comment by beegee-tokyo** [comment]
It is old, but might work
[Arduino Playground Keypad](https://playground.arduino.cc/Code/Keypad/)
[Github Keypad](https://github.com/Chris--A/Keypad)
[Arduino Library Info Keypad](https://www.arduinolibraries.info/libraries/keypad)

**Comment by GeorgeFlorian** [comment]
> It is old, but might work
> [Arduino Playground Keypad](https://playground.arduino.cc/Code/Keypad/)
> [Github Keypad](https://github.com/Chris--A/Keypad)
> [Arduino Library Info Keypad](https://www.arduinolibraries.info/libraries/keypad)
> 
> **[EDIT] I didn't try the libray!**

Should this work with an ESP ? https://www.banggood.com/Small-2_4GHz-Wireless-Numeric-Keypad-Mini-Suspension-Number-Pad-Keyboard-for-Laptop-PC-p-1412420.html?rmmds=buy&cur_warehouse=CN

From what I've found there can be wired, Bluetooth and WiFi keypads. Is this correct ? Do I simply plug in the keypad to the ESP and it should work with some code ?

**Comment by GeorgeFlorian** [comment]
> It is old, but might work
> [Arduino Playground Keypad](https://playground.arduino.cc/Code/Keypad/)
> [Github Keypad](https://github.com/Chris--A/Keypad)
> [Arduino Library Info Keypad](https://www.arduinolibraries.info/libraries/keypad)
> 
> **[EDIT] I didn't try the libray!**

I actually need a bigger keypad, something more like a keyboard. Something that has all the alphanumerical keys, an enter and a backspace.

Can this be done in ESP32 ? Or should I move to a Raspberry Pi Zero ?

I need something like this:
[![maxresdefault.jpg](https://i.postimg.cc/wBhzc28x/maxresdefault.jpg)](https://postimg.cc/94FscGQs)
