### ISSUE TITLE
[request] factory reset bootloader

### ISSUE THREAD

**Issue by chegewara** [espressif/arduino-esp32#3504]
Hi folks,
as far as i understand we have few precompiled bootloaders. I have question then, we are close to upgrade to esp-idf v3.3, could we have at least 1 bootloader with enabled factory reset option?
Of course i can build one by myself, that's not a problem, and at the moment i don't need it, but maybe there is more users interested in such option.

Thanks.

**Comment by me-no-dev** [comment]
if there are no conequences to the rest of the functionality, I see no reason not to add it as default :)
you can create a PR in the lib builder repo with the new option in the sdkconfig.
https://github.com/espressif/esp32-arduino-lib-builder

**Comment by chegewara** [comment]
Hi @me-no-dev 
what version of esp-idf should i use? v3.2 or v3.3?

**Comment by me-no-dev** [comment]
3.3 :) I do not plan to keep updating 3.2 ;)

**Comment by me-no-dev** [comment]
there is a branch there for 3.3 . use that :)
