### ISSUE TITLE
esp32 en button must be pressed for the serial to be recognized

### ISSUE THREAD

**Issue by neuberfran** [espressif/arduino-esp32#3523]
Hii,

My esp32 board need EN  button must be pressed for the serial to be recognized:

![20191127_225405](https://user-images.githubusercontent.com/38701397/69770858-74e50780-113f-11ea-80dd-af5b04cb93cd.jpg)

Pls help me

**Comment by TD-er** [comment]
By pressing that button at boot, you may prevent the ESP from booting, so it will consume less power right after powering on,  allowing the PC to recognize the serial chip.
Can you try using a better USB cable?

**Comment by neuberfran02** [comment]
@TD-er I already changed the usb cable and it did not solve. I also put a 0.22uF ceramic capacitor between EN and GND and it didn't solve either. **Please, what else can I try**?
 
![taltaltal](https://user-images.githubusercontent.com/57755450/69968735-c69fe000-14f9-11ea-98e5-6788b5cd9cca.jpg)

**Comment by neuberfran** [comment]
No solved

**Comment by neuberfran** [comment]
not solved yet

**Comment by atanisoft** [comment]
@neuberfran No fix will be provided in this code base as it would seem you have a hardware issue with the board you are trying to use.
