### ISSUE TITLE
The network freeze issue with esp32 board

### ISSUE THREAD

**Issue by DhrubojyotiDey** [espressif/arduino-esp32#3532]
The board is an esp32 DEVKITV1 with the chip ESP32-WROOM-32D

 I'm trying to make the board more responsive for IoT projects regardless of idleness. Now I have a few queries to know about.
 In the shell the following data is shown. 

I (455) cpu_start: Pro cpu up.
I (455) cpu_start: Application information:
I (455) cpu_start: Compile time:     Nov  5 2019 00:35:52
I (458) cpu_start: ELF file SHA256:  0000000000000000...
I (464) cpu_start: ESP-IDF:          v3.3
I (469) cpu_start: Starting app cpu, entry point is 0x400832d0
I (0) cpu_start: App cpu up.
I (479) heap_init: Initializing. RAM available for dynamic allocation:
I (486) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (492) heap_init: At 3FFBA458 len 00025BA8 (150 KiB): DRAM
I (499) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (505) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (511) heap_init: At 40092A3C len 0000D5C4 (53 KiB): IRAM
I (518) cpu_start: Pro cpu start user code
I (200) cpu_start: Chip Revision: 1
W (201) cpu_start: Chip revision is higher than the one configured in menuconfig. Suggest to upgrade it.
I (204) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (60) modsocket: Initializing
I (505) phy: phy_version: 4102, 2fa7a43, Jul 15 2019, 13:06:06, 0, 0

1. What are these "I" before each line and what does it signifies? 
2. There is a "W" before the 5th line what does this mean? If it "suggest to upgrade it." How can I upgrade it? 
3. On the last 3 lines there is mentioned 2 different CPU,s how are these different from one another? 
4. Can I run 2 application simultaneously on each CPU? If so HOW?

### Hardware:
Board:							 esp32 DEVKITV1
Core Installation/update date:			Don't know exactly
IDE name:							micropython and arduino
Flash Frequency:					don't know exactly
PSRAM enabled:                                          ?no?
Upload Speed:						115200
Computer OS:                                            Windows 7 & raspberry pi4

### Description:
The esp32 network webpage opens good, thats really impressive but the major flaw there is that after remaining in an idle state for quite a long time the board doesn't respond which makes it quite annoying. Is there any kind of solution for this? The board however responds after the EN (enable) button is pressed, but after quite a long time of idleness the problem repeats. I'm working on a windows 7 with thonny IDE because I am more familiar with python than Arduino.

### Sketch:  
##BELOW IS THE MICROPYTHON CODE FOR THE ESP32##

try:
  import usocket as socket
except:
  import socket
from machine import Pin
import network

import esp
#esp.osdebug(None)

import gc
gc.collect()

ssid = 'MicroPython-AP'
password = '123456789'

ap = network.WLAN(network.AP_IF)
ap.active(True)
ap.config(essid=ssid, password=password)

while ap.active() == False:
  pass

print('Connection successful')
print(ap.ifconfig())

def web_page():
  if led.value() == 1:
    gpio_state="ON"
  else:
    gpio_state="OFF"
  
  html = """<html><head> <title>ESP Web Server</title> <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="data:,"> <style>html{font-family: Helvetica; display:inline-block; margin: 0px auto; text-align: center;}
  h1{color: #0F3376; padding: 2vh;}p{font-size: 1.5rem;}.button{display: inline-block; background-color: #e7bd3b; border: none; 
  border-radius: 4px; color: white; padding: 16px 40px; text-decoration: none; font-size: 30px; margin: 2px; cursor: pointer;}
  .button2{background-color: #4286f4;}</style></head><body> <h1>ESP Web Server</h1> 
  <p>GPIO state: <strong>""" + gpio_state + """</strong></p><p><a href="/?led=on"><button class="button">ON</button></a></p>
  <p><a href="/?led=off"><button class="button button2">OFF</button></a></p></body></html>"""
  return html

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(('', 80))
s.listen(5)

led = Pin(2, Pin.OUT)
while True:
  conn, addr = s.accept()
  print('Got a connection from %s' % str(addr))
  request = conn.recv(1024)
  request = str(request)
  print('Content = %s' % request)
  led_on = request.find('/?led=on')
  led_off = request.find('/?led=off')
  if led_on == 6:
    print('LED ON')
    led.value(1)
  if led_off == 6:
    print('LED OFF')
    led.value(0)
  response = web_page()
  conn.send('HTTP/1.1 200 OK\n')
  conn.send('Content-Type: text/html\n')
  conn.send('Connection: close\n\n')
  conn.sendall(response)
  conn.close()

### Debug Messages:
```The first serial output is as follows.(After running the above code)
Connection successful
('192.168.x.x', '255.255.255.0', '192.168.x.x', '0.0.0.0')

after a device gets connected the following shows up.

Got a connection from ('192.168.xx.xx', xxxxx)
Content = b'GET /?led=off HTTP/1.1\r\nHost: 192.168.43.240\r\nConnection: keep-alive\r\nCache-Control: max-age=0\r\nDNT: 1\r\nSave-Data: on\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Linux; Android 9; Redmi 7A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.62 Mobile Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\r\nReferer: http://192.168.43.240/?led=on\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7\r\n\r\n'
LED OFF
Got a connection from ('192.168.xx.xx', xxxxx)


but after leaving it for a around 20 minutes it gets disconnected with a serial display like this.

Connection lost (EOF)


```
As I have mentioned above that the board works/responds again after a reboot. I've also found that there's a feature called deep sleep, after which the board responds like it had a reboot  so I have a theory that is if I run a timer program that executes after a specific interval of time and that runs alongside my primary program and sends it to deep sleep for a second and then wakes the board up. So the board is supposed to function just as if it has been rebooted.
My Querry.
1. How can I make the board more responsive? without freezing?
2. Is there any process by which I can run 2 programs on it simultaneously?
3. What's the difference between deep sleep and light sleep?
4. How can I implement it in micropython?
5. Where can I get some example codes? or better if someone shares some.
6. I also appreciate arduino codes

**Comment by lbernstone** [comment]
This forum is for issues with arduino-esp32 code- not a tutorial, nothing about micropython.  Your general questions should be directed to esp32.com .
The synchronous WebServer library performs poorly compared to [EspAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer).  The loop servicing model just doesn't work so well on a multithreaded OS.  For any significant work, use the async libraries.
