### ISSUE TITLE
general question: preprocessor directive for a board #define MACRO to identify both  esp32 and esp8266 Boards ?

### ISSUE THREAD

**Issue by dsyleixa** [espressif/arduino-esp32#3539]
which is the correct preprocessor directive for a board #define MACRO to identify both esp32 and esp8266 Boards ?

e.g.,, I need to declare the preprocessor directive
#if defined (SAM)
   #include "avr/dtostrf.h"
#elseif defined (? ESP ?) // <<<<<<<<<<<<< ????
  #include <stdlib_noniso.h>
#endif

**Comment by atanisoft** [comment]
ESP32 for ESP32 and probably ESP8266 for the other....

**Comment by dsyleixa** [comment]
is one ring to rule them all?

**Comment by atanisoft** [comment]
Pretty much yes, there is a platform specific define created for each architecture, you can see it in platform.txt for each.

**Comment by dsyleixa** [comment]
in boards.txt I don't see board macros which rule both ESP32 and ESP8266 boards

**Comment by atanisoft** [comment]
boards.txt is not the same as [platform.txt](https://github.com/espressif/arduino-esp32/blob/master/platform.txt)...

**Comment by dsyleixa** [comment]
in platform.txt I don't see a macro both for ESP32 and ESP8266 boards - do you?

**Comment by atanisoft** [comment]
obviously you won't see ESP8266 in the ESP32 platform.txt, you will need to look at the ESP8266 platform.txt for that platform. This repo only covers ESP32.

**Comment by dsyleixa** [comment]
no, I mean: a mcro which matches boh, all at once.

Like 
SAM
both covers __SAMD__ and __SAM3X8E__

**Comment by atanisoft** [comment]
There isn't one

**Comment by dsyleixa** [comment]
I'll then try
#elseif defined(ESP32) || defined(ESP8266)  // <<<<<<<<<<<<< ????

**Comment by atanisoft** [comment]
I believe that should work, you will need to confirm with the ESP8266 side though to ensure what define is available for that platform.
