### ISSUE TITLE
scanNetworks with async = true

### ISSUE THREAD

**Issue by bmitov** [espressif/arduino-esp32#354]
Is the scanNetworks( true ) implemented?
It does not seem like the static void _scanDone(); is used anywhere in the code, and when I call 👍 
scanNetworks( true );

    int n;
    for(;;)
    {
      Serial.println("scanning...");
      n = WiFi.scanComplete();
      if( n != WIFI_SCAN_RUNNING )
        break;

      Serial.println( n );
      delay( 1000 );      
    }

the loop runs forever...
How to use scanNetworks asynchronous? I want to perform other tasks while scanning in the main loop

**Comment by me-no-dev** [comment]
It's called here: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiGeneric.cpp#L177
Try to raise the debug level for Arduino and see what messages you get in Serial
