### ISSUE TITLE
BLE device name length limitation when reporting Service UUID

### ISSUE THREAD

**Issue by gism** [espressif/arduino-esp32#3578]
Hello,
Sorry, not really an issue but it took me a time to understand.

Exaple: arduino-esp32/libraries/BLE/examples/BLE_server_multiconnect/
is not updated to support device long name devices as: BLE/examples/BLE_server/

This should be a known issue because of following line:
`BLEDevice::init("Long name works now");`

From my understanding fix is to change:
```
  pAdvertising->setScanResponse(false);
  pAdvertising->setMinPreferred(0x0);  // set value to 0x00 to not advertise this parameter
```

To:
```
  pAdvertising->setScanResponse(true);
  pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
  pAdvertising->setMinPreferred(0x12);
```

**Comment by chegewara** [comment]
Only this is required to set true:
`pAdvertising->setScanResponse(false);`

Setting this to 0x0 is giving even more bytes for long name:
`pAdvertising->setMinPreferred(0x0); `
