### ISSUE TITLE
Feature request: add cleanAPlist() to wifiMulti, like ESP8266.

### ISSUE THREAD

**Issue by mike-s123** [espressif/arduino-esp32#3581]
Self explanatory - ESP32 libraries should be kept in sync with ESP8266 ones.

**Comment by mike-s123** [comment]
Issue still exists.

**Comment by allanyates** [comment]
I'll second this one. I have a use case where I need connect to one of many access points, on a one time basis, then switch to a different access point. So, I would need to clean the AP list in between. The only workaround appears to be to force an ESP32 restart between the two sets of connections.
