### ISSUE TITLE
TLS session resumption

### ISSUE THREAD

**Issue by smdjeff** [espressif/arduino-esp32#3598]
It seems most ESP32 users are setting up and tearing down the TLS session for each and every transaction.  Unfortunately, "Using TLS on the ESP32 requires a significant amount of energy. Compared to an unencrypted transmission, approximately 14 times more energy is required to establish a full TLS session." via
http://www2.inf.h-brs.de/~mradem2m/files/myPaperVersionsForWebsite/2019-ESP32-TLS-Power.pdf

Has anyone attempted TLS session resumption?  Perhaps something like esp_tls_conn_http_new() would return a resumption ticket id that can be used as input into the esp_tls_cfg_t parameter in the next call?

**Comment by smdjeff** [comment]
No one?

**Comment by jbbr** [comment]
I'm also interested in this feature 
(hope adding a comment will reopen the issue)
