### ISSUE TITLE
How to capture information via GET or POST request

### ISSUE THREAD

**Issue by manbomb** [espressif/arduino-esp32#3601]
I am creating a system where I use an access point to configure the wifi SSID and password that will be used to connect to Firebase. But I still don't understand how this can be done, how is it possible to get the headers?

**Comment by lbernstone** [comment]
This forum is for issues with the code, not help/tutorials.  Take a look at [WiFiManager](https://github.com/tzapu/WiFiManager/tree/development) and the [header for Webserver](https://github.com/espressif/arduino-esp32/blob/master/libraries/WebServer/src/WebServer.h#L106-L111)

**Comment by manbomb** [comment]
Sorry, thanks.
