### ISSUE TITLE
Fatal error occurred while including "asio.hpp"

### ISSUE THREAD

**Issue by imcort** [espressif/arduino-esp32#3610]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.4
IDE name:						 Arduino IDE
Computer OS:                                          Both Windows 10 & Mac OSX

### Description:
I'm trying to run ASIO example in the Arduino sketch, it just got an error when including asio.hpp
[esp-idf ASIO example](https://github.com/espressif/esp-idf/tree/master/examples/protocols/asio/chat_client)

**/Documents/Arduino/hardware/espressif/esp32/tools/sdk/include/lwip/arpa/inet.h:18:49: fatal error: ../../../lwip/src/include/lwip/inet.h: No such file or directory**

How could I run this example in the Arduino sketch?

**Comment by lbernstone** [comment]
This clearly hasn't been tested in a long time (if ever).  I can get you past the immediate error, but there are much nastier problems ahead.
Change tools/sdk/include/lwip/arpa/inet.h to use an absolute location:
```
diff --git a/tools/sdk/include/lwip/arpa/inet.h b/tools/sdk/include/lwip/arpa/inet.h
index 90428f6..94c6c17 100644
--- a/tools/sdk/include/lwip/arpa/inet.h
+++ b/tools/sdk/include/lwip/arpa/inet.h
@@ -15,6 +15,6 @@
 #ifndef INET_H_
 #define INET_H_
 
-#include "../../../lwip/src/include/lwip/inet.h"
+#include "lwip/inet.h"
 
 #endif /* INET_H_ */
