### ISSUE TITLE
Unable to fetch content in AWS s3 OTA update

### ISSUE THREAD

**Issue by Nakul93** [espressif/arduino-esp32#3625]
I have set up everything correctly. Here is my output:

Got application/macbinary payload.
Got 744384 bytes from server
contentLength : 744384, isValidContentType : 0
There was no content in the response

why is isValidContentType is 0, I am using HTTPS with 443 as port

**Comment by DeltaVetal26** [comment]
Hello @Nakul93 ,
You can try to completely reset the chip with the ESP tool: https://github.com/espressif/esptool

1) Connect ESP and open a command prompt
2) While holding the BOOT button on ESP, enter esptool.py erase_flash
3) ESP must be completely reset

Perhaps the ESP tool will detect the ESP chip.

**Comment by jeffapp** [comment]
Check client whether to set  set timeout  time  .

**Comment by chegewara** [comment]
Why is payload type:
`application/macbinary`
