### ISSUE TITLE
BT Classic & BLE at the same time?

### ISSUE THREAD

**Issue by mattygsa** [espressif/arduino-esp32#3644]
Is it possible to utilise BT Classic & BLE at the same time?

I am trying to build a transmitter remote control that sends a near instant throttle signal to a receiver unit. (Both ESP32s)
Also I would like to be able to send temperature, speed and other sensor data back to the remote control at regular intervals  for display on an LCD screen.

Any help or hints would be much appreciated. Thanks you

**Comment by me-no-dev** [comment]
yes, though your mileage will vary :) when we move to 4.X things should get a bit better.
