### ISSUE TITLE
ESP32-Pico - Which pins support digitalwrite()?

### ISSUE THREAD

**Issue by rei-vilo** [espressif/arduino-esp32#3662]
I'm playing with the basic _Blinky_ example, an LED and a 330 Ω resistor.

### Hardware:
Board:							ESP32-Pico v4.1
Core Installation version:			1.0.4
IDE name:						Arduino IDE
Flash Frequency:					40Mhz
Partition scheme:                                  default
Upload Speed:					115200
Computer OS:                                        macOS

### Description:
Surprise, first test on GPIO27 failed. So does GPIO38.

After looking at #1204, GPIO4 blinks.

+ What are the GPIOs supporting `digitalwrite()`? 

+ Or should they managed with `REG_WRITE`as per #1901?

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

#define LED_BUILTIN 4

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}
```

**Comment by lbernstone** [comment]
There is a [pinmap](https://github.com/espressif/arduino-esp32#esp32dev-board-pinmap) on the front page.  GPIO27 should work unless you have something else connected with a pull up/down.
