### ISSUE TITLE
WiFiClientSecure and Google App Script

### ISSUE THREAD

**Issue by bestpika** [espressif/arduino-esp32#368]
I can't get any response.
```cpp
WiFiClientSecure client;
...
if(client.connect("script.google.com", 443)) {
    client.println("POST /macros/s/.../exec HTTP/1.1");
    client.println("Host: script.google.com");
    client.println("Content-Type: application/x-www-form-urlencoded");
    client.println("Content-Length: 3");
    client.println();
    client.println("a=a");
    client.print("\r\n\r\n");
    while (!client.available()) { // loop forever
        delay(50);
        Serial.print(".");
    }
    while (client.available()) {
        char c = client.read();
        Serial.write(c);
    }
    client.stop();
}
```

**Comment by copercini** [comment]
I fixed this possible infinite loop here: https://github.com/espressif/arduino-esp32/pull/347/files#diff-78da625bea886a01b784f9d1563acf3aL90

But it's not merged yet

**Comment by electronicsguy** [comment]
@bestpika you won't get a direct response from google apps script since it uses redirection. Use this: [HTTPSRedirect](https://github.com/electronicsguy/ESP8266/tree/master/HTTPSRedirect). 

It works well on esp8266. I'll test it on ESP-32 and update. In case you test it and get any errors, please post them.

**Comment by bestpika** [comment]
@electronicsguy I can't get any response, so HTTPSRedirect not work.

**Comment by copercini** [comment]
@bestpika please enable Core Debug Level as verbose in your arduino IDE and post here

**Comment by electronicsguy** [comment]
@bestpika that probably indicates an error in the google apps scripts permissions. What settings is your we app published with?

**Comment by bestpika** [comment]
@electronicsguy
![image](https://cloud.githubusercontent.com/assets/5698157/25977110/b6c897b0-36eb-11e7-9704-94dbafdf2a27.png)

**Comment by electronicsguy** [comment]
@bestpika   You can use a service like [hurl](hurl.it) to test the webapp externally. Please see if that gives any response and errors, if any. Could you post the webapp URL here?

**Comment by bestpika** [comment]
If no post data, I can get response, but result is wrong.
If I send post data, I can get any response.

**Comment by me-no-dev** [comment]
What I can tell is that ```a=a``` is not url encoded, therefore the request is wrong. That value should be ```a%3Da```

**Comment by me-no-dev** [comment]
but that could also be caused by wrong account data

**Comment by bestpika** [comment]
If app script no return, then not redirect.
I will change send data and try.

**Comment by bestpika** [comment]
I rewrite http request, then It is working okay.
```cpp
void doSendThis() {
  Serial.println("Send...");
  if (client.connect(HOST, 443)) {
    String postData(String("gssid=") + GSSID + "&sheet=" + SHEET + "&value=" + "0|1|2");
    Serial.println(postData);
    client.println("POST " + String(PATH) + " HTTP/1.1");
    client.println("Host: " + String(HOST));
    client.println("Content-Type: application/x-www-form-urlencoded");
    client.println("Content-Length: " + String(postData.length()));
    client.println();
    client.println(postData);
    client.print("\r\n\r\n");
    Serial.println("Response...");
    while (!client.available()) {
      delay(100);
      Serial.print(".");
    }
    Serial.println();
    Serial.println("-----------");
    while (client.available()) {
      Serial.write(client.read());
    }
    Serial.println();
    Serial.println("-----------");
  }
  client.stop();
}
```

**Comment by swetapriyadarshi** [comment]
@bestpika 
Hey i know this post is closed but still can u post the complete method of datalogging in google sheet as i am not able to do it.
Thanks

**Comment by chandan2002x** [comment]
At last uploaded to Spreadsheet with esp-idf. But loosing 76 byte heap at every transaction. Any clue?

**Comment by Voha888** [comment]
> I rewrite http request, then It is working okay.
> 
> ```c++
> void doSendThis() {
>   Serial.println("Send...");
>   if (client.connect(HOST, 443)) {
>     String postData(String("gssid=") + GSSID + "&sheet=" + SHEET + "&value=" + "0|1|2");
>     Serial.println(postData);
>     client.println("POST " + String(PATH) + " HTTP/1.1");
>     client.println("Host: " + String(HOST));
>     client.println("Content-Type: application/x-www-form-urlencoded");
>     client.println("Content-Length: " + String(postData.length()));
>     client.println();
>     client.println(postData);
>     client.print("\r\n\r\n");
>     Serial.println("Response...");
>     while (!client.available()) {
>       delay(100);
>       Serial.print(".");
>     }
>     Serial.println();
>     Serial.println("-----------");
>     while (client.available()) {
>       Serial.write(client.read());
>     }
>     Serial.println();
>     Serial.println("-----------");
>   }
>   client.stop();
> }
> ```
> 
> ```
> HTTP/1.1 200 OK
> Content-Type: text/html; charset=utf-8
> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> Pragma: no-cache
> Expires: Mon, 01 Jan 1990 00:00:00 GMT
> Date: Fri, 12 May 2017 06:45:28 GMT
> P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
> P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
> X-Content-Type-Options: nosniff
> X-XSS-Protection: 1; mode=block
> Server: GSE
> Set-Cookie: ...
> Set-Cookie: ...
> Alt-Svc: quic=":443"; ma=2592000; v="37,36,35"
> Accept-Ranges: none
> Vary: Accept-Encoding
> Transfer-Encoding: chunked
> ```
> 
> ![image](https://cloud.githubusercontent.com/assets/5698157/25986368/37e77330-3722-11e7-848a-9a88e1986eee.png)

Hello. What is the value in your PATH string?

**Comment by Amrutha-bv** [comment]
> > I rewrite http request, then It is working okay.
> > ```c++
> > void doSendThis() {
> >   Serial.println("Send...");
> >   if (client.connect(HOST, 443)) {
> >     String postData(String("gssid=") + GSSID + "&sheet=" + SHEET + "&value=" + "0|1|2");
> >     Serial.println(postData);
> >     client.println("POST " + String(PATH) + " HTTP/1.1");
> >     client.println("Host: " + String(HOST));
> >     client.println("Content-Type: application/x-www-form-urlencoded");
> >     client.println("Content-Length: " + String(postData.length()));
> >     client.println();
> >     client.println(postData);
> >     client.print("\r\n\r\n");
> >     Serial.println("Response...");
> >     while (!client.available()) {
> >       delay(100);
> >       Serial.print(".");
> >     }
> >     Serial.println();
> >     Serial.println("-----------");
> >     while (client.available()) {
> >       Serial.write(client.read());
> >     }
> >     Serial.println();
> >     Serial.println("-----------");
> >   }
> >   client.stop();
> > }
> > ```
> > 
> > 
> > ```
> > HTTP/1.1 200 OK
> > Content-Type: text/html; charset=utf-8
> > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> > Pragma: no-cache
> > Expires: Mon, 01 Jan 1990 00:00:00 GMT
> > Date: Fri, 12 May 2017 06:45:28 GMT
> > P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
> > P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
> > X-Content-Type-Options: nosniff
> > X-XSS-Protection: 1; mode=block
> > Server: GSE
> > Set-Cookie: ...
> > Set-Cookie: ...
> > Alt-Svc: quic=":443"; ma=2592000; v="37,36,35"
> > Accept-Ranges: none
> > Vary: Accept-Encoding
> > Transfer-Encoding: chunked
> > ```
> > 
> > 
> > ![image](https://cloud.githubusercontent.com/assets/5698157/25986368/37e77330-3722-11e7-848a-9a88e1986eee.png)
> 
> Hello. What is the value in your PATH string?

Were you able to get the value for PATH? Please let me know, HttpsRedirect didnot work for me

**Comment by bestpika** [comment]
The HOST and PATH just GAS's execute URL.

**Comment by Amrutha-bv** [comment]
I did try this.

My google script ID recognizes "Name" and pastes it in that respective column.

``
const char* host = "script.google.com";
String url = String("/macros/s/") + GScriptId + "/exec?cal";
payload = "Name=hi";
client.println("POST` " + String(url) + " HTTP/1.1");
    client.println("Host: " + String(host));
    client.println("Content-Type: application/x-www-form-urlencoded");
    client.println("Content-Length: " + String(payload.length()));
    client.println();
    client.println(payload);
    client.print("\r\n\r\n");`

I am able to read string rceived from host. Data is not being received at spreadsheet. What am I missing here?

**Comment by Nimmi147** [comment]
#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
#include "DHT.h"
#define DHTPIN D1
#define DHTTYPE DHT11 
 
const char* ssid     = "ningu";
const char* password = "14071996";
const char* host = "script.google.com"; 
const char* fingerprint = "‎‎CD 3E 63 37 0D 07 56 7A 9B 10 6B 7A 3D 64 57 9B 1E 4B B6 D5";
String url;

DHT dht(DHTPIN, DHTTYPE);

void setup() {
  Serial.begin(115200);
  delay(100);
  dht.begin();
  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  
  WiFi.begin(ssid, password); 
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
 
  Serial.println("");
  Serial.println("WiFi connected");  
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  Serial.print("Netmask: ");
  Serial.println(WiFi.subnetMask());
  Serial.print("Gateway: ");
  Serial.println(WiFi.gatewayIP());
}

 
void loop() {
 
  Serial.print("connecting to ");
  Serial.println(host);
 
  WiFiClientSecure client;

  const int httpsPort = 443;
  if (!client.connect(host, httpsPort)) {
    Serial.println("connection failed");
    return;
  }

 if (client.verify(fingerprint, host)) {
  Serial.println("certificate matches");
  } else {
  Serial.println("certificate doesn't match");
  }

  float h = dht.readHumidity();
  float t = dht.readTemperature();
  if (isnan(h) || isnan(t)) {
     Serial.println("Failed to read from DHT sensor!");
     return;
  }
  
  url = "/macros/s/AKfycbzBr2x17f5TMmWrV_rs3SF8cyLYlRG52nfwzAoAluaDD-jAsDI/exec?func=addData&val="+ String(t);
  Serial.print("Requesting URL: ");
  Serial.println(url);
  
  client.print(String("GET ") + url + " HTTP/1.1\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");
  delay(500);
  String section="header";
  while(client.available()){
    String line = client.readStringUntil('\r');
    Serial.print(line);
  }
  Serial.println();
  Serial.println("closing connection");
  delay(3000);
}
![query](https://user-images.githubusercontent.com/64248475/86538155-d78e5500-bf11-11ea-86b3-134cc0f307c5.PNG)


It showing an error called connecting to script.google.com connection failed please help me where i did mistake.
