### ISSUE TITLE
A simple loop is slower than esp8266

### ISSUE THREAD

**Issue by waayst** [espressif/arduino-esp32#37]
`long t;int i;int j;
for(i=0;i<10000;i++)
for(j=0;j<1000;j++)
t=t+j;`

**Comment by me-no-dev** [comment]
what do you think we can do about it?

**Comment by waayst** [comment]
Improve esp-idf or xtensa compiler,It isn't arduino-esp32 problem

**Comment by me-no-dev** [comment]
then please file that issue there (esp-idf). Also do mention if you are comparing to ESP8266-NONOS or ESP8266-RTOS as that does matter :)
