### ISSUE TITLE
USB port not listed on Mac OS X

### ISSUE THREAD

**Issue by homofortis** [espressif/arduino-esp32#370]
I have esp-wroom-32 dev board with USB connector but when I plug it in the board is not visible in Arduino IDE port option (Mac OS X 10.12.4 with ch341 v 1.4 usb driver). Could you please help.

**Comment by homofortis** [comment]
Resolved. In case anyone else has the same problem, you need to install Silicon Labs VCP Driver.

**Comment by BrendanFDMoore** [comment]
Oh wow - thank you so much for sharing this solution. Was driving me crazy!

**Comment by JonasRKirkegaard** [comment]
YES Thank you!!! Hurra!!!

**Comment by JuanPotato** [comment]
@homofortis Did you install any other drivers?

**Comment by luongs3** [comment]
not working for me. Still not showing any ports.

**Comment by steengroentved** [comment]
Not working for me either
