### ISSUE TITLE
WHY ESP32 gets exceptions multiple times and stucks?

### ISSUE THREAD

**Issue by Gopal123456789** [espressif/arduino-esp32#3706]
Hi all. I am scanning for BLE devices and sending the received advertised data, to server. The scanning and then sending the data to the server part runs in loop(). It works fine for few days and suddenly stops. I have set WDT for 30 second wait time in case it hangs. When it hangs after this point it doesn't  even reset. I have log of the exception it sends on serial. When I try to decode it in the exception decoder, it does not show anything. I have attached the screenshot. 

The error message is:
Guru Meditation Error: Core  1 panic'ed (Double exception)
Core 1 register dump:
PC      : 0x400803c0  PS      : 0x00050f36  A0      : 0x80082154  A1      : 0x3fffffe0  
A2      : 0x40000050  A3      : 0x00000000  A4      : 0x00000001  A5      : 0x00000001  
A6      : 0x00060820  A7      : 0x00000000  A8      : 0x8008f894  A9      : 0x00003500  
A10     : 0x00000003  A11     : 0x00060823  A12     : 0xe52009d5  A13     : 0x09f53009  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000020  EXCCAUSE: 0x00000002  
EXCVADDR: 0x00003500  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  
Guru Meditation Error: Core  1 panic'ed (LoadStoreError). Exception was unhandled.
Core 1 register dump:
PC      : 0x40091d79  PS      : 0x00060035  A0      : 0x80091f5f  A1      : 0x3ffffe00  
A2      : 0x40080da0  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x3ffc8424  
A6      : 0x00000003  A7      : 0x00060023  A8      : 0x40080da0  A9      : 0x0000007d  
A10     : 0x0000002a  A11     : 0x3ffd1350  A12     : 0x3ffc84c4  A13     : 0x00000001  
A14     : 0x00000001  A15     : 0x14baa17c  SAR     : 0x0000000a  EXCCAUSE: 0x00000003  
EXCVADDR: 0x40080da0  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  
Guru Meditation Error: Core  1 panic'ed (LoadStoreError). Exception was unhandled.
Core 1 register dump:
PC      : 0x40091d79  PS      : 0x00060033  A0      : 0x80091f5f  A1      : 0x3ffffc40  
A2      : 0x40080da0  A3      : 0x00000000  A4      : 0x800923cb  A5      : 0x3ffffec0  
A6      : 0x3fffff20  A7      : 0x00000001  A8      : 0x40080da0  A9      : 0x0000007d  
A10     : 0x0000000a  A11     : 0x3ffffea0  A12     : 0x80092150  A13     : 0x3ffffe40  
A14     : 0x3fffff20  A15     : 0x00000001  SAR     : 0x00000017  EXCCAUSE: 0x00000003  
EXCVADDR: 0x40080da0  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  
Guru Meditation Error: Core  1 panic'ed (LoadStoreError). Exception was unhandled.
Core 1 register dump:
PC      : 0x40091d79  PS      : 0x00060033  A0      : 0x80091f5f  A1      : 0x3ffffa80  
A2      : 0x40080da0  A3      : 0x00000000  A4      : 0x80092454  A5      : 0x3ffffd00  
A6      : 0x3ffffd40  A7      : 0x00000001  A8      : 0x40080da0  A9      : 0x0000007d  
A10     : 0x0000000a  A11     : 0x3ffffce0  A12     : 0x80092150  A13     : 0x3ffffc80  
A14     : 0x3ffffd40  A15     : 0x00000001  SAR     : 0x0000001e  EXCCAUSE: 0x00000003  
EXCVADDR: 0x40080da0  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  
Guru Meditation Error: Core  1 panic'ed (LoadStoreError). Exception was unhandled.
Core 1 register dump:
PC      : 0x40091d79  PS      : 0x00060033  A0      : 0x80091f5f  A1      : 0x3ffff8c0  
A2      : 0x40080da0  A3      : 0x00000000  A4      : 0x80092454  A5      : 0x3ffffb40  
A6      : 0x3ffffb80  A7      : 0x00000001  A8      : 0x40080da0  A9      : 0x0000007d  
A10     : 0x0000000a  A11     : 0x3ffffb20  A12     : 0x80092150  A13     : 0x3ffffac0  
A14     : 0x3ffffb80  A15     : 0x00000001  SAR     : 0x00000015  EXCCAUSE: 0x00000003  
EXCVADDR: 0x40080da0  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  

It continues for some time and finally stops.
This message has come repeatedly 73 times in 5 seconds. Then it stopped. What could be the reason?

### Hardware:
Board:							ESP32 Dev WROOM32
IDE name:						Arduino IDE
CPU frequency:                                       240Mhz (WiFi/BT) according to arduino->tools->CPU frequency
Flash Frequency:					80Mhz according to arduino->tools->Flash frequency
Upload Speed:					921600
Computer OS:                                        Windows 10

![Screenshot (175)](https://user-images.githubusercontent.com/53169824/73657324-1183d280-46b8-11ea-8fb0-8676b2d448ac.png)

Thank you.

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md
