### ISSUE TITLE
 ESP.getPsramSize() returnes incorrect PSRAM size for Wroover-B. Error or fake module?

### ISSUE THREAD

**Issue by mrdc** [espressif/arduino-esp32#3716]
## Hardware:
Board:							TTGO ESP32 Mini32
Core Installation/update date:			1.0.4 Oct 2019
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                         yes
Upload Speed:						115200
Computer OS:                                            Windows 7

### Description:
Hello, `ESP.getPsramSize()` returnes incorrect PSRAM size for the board based on ESP32 Wroover-B: it shows 4194252 (~4MB) but it should be 8388608 (8MB).
Is it correct behaviour or my module is not Wroover-B, but the regular Wroover?

```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
  Serial.begin(115200);
  Serial.printf("PSRAM Total heap %d, PSRAM Free Heap %d\n",ESP.getPsramSize(),ESP.getFreePsram());
}

void loop() {
}
```

**Comment by atanisoft** [comment]
From a very quick search I found https://www.tindie.com/products/ttgo/lilygor-ttgo-mini32-esp32-wrover-b-module/ which shows the board has 4MB flash and 4MB PSRAM... So it appears the function is working as intended.

**Comment by mrdc** [comment]
> 
> 
> From a very quick search I found https://www.tindie.com/products/ttgo/lilygor-ttgo-mini32-esp32-wrover-b-module/ which shows the board has 4MB flash and 4MB PSRAM... So it appears the function is working as intended.

Based on info from Espressif, ESP32 Wrover-B modules have 8MB PSRAM.
Here is a photo of the dev board I'm using - it definately says it's Wrover-B...

![image](https://user-images.githubusercontent.com/16876990/73857878-9b62a580-4848-11ea-8c4f-9f225d863754.png)

Dev board manufacturer also declares that it has Wrover-B with 8MB PSRAM.

![image](https://user-images.githubusercontent.com/16876990/73858387-5e4ae300-4849-11ea-834c-65c4aa1f676a.png)

**Comment by atanisoft** [comment]
This should likely be routed to https://github.com/espressif/esp-idf as ESP.getPsramSize() simply calls:
```
uint32_t EspClass::getPsramSize(void)
{
    multi_heap_info_t info;
    heap_caps_get_info(&info, MALLOC_CAP_SPIRAM);
    return info.total_free_bytes + info.total_allocated_bytes;
}
```

**Comment by lbernstone** [comment]
I'm not sure v3.2 had code for 8MB PSRAM.  Can you try with the v4.0 branch?

**Comment by chegewara** [comment]
I think that only on boot esp-idf can recognize size of PSRAM bigger than 4MB. 
I have only m5stack fire to tests at the moment and it has only 32Mbits SPIRAM.

**Comment by mrdc** [comment]
Everything is fine - this himem code https://github.com/TridentTD/arduino_esp32_himem helps:

```
15:34:08.934 -> PSRAM total size     : 8388608 
15:34:08.934 -> ----------------------------------------
15:34:08.934 -> PSRAM first 4MB size : 3932108 
15:34:08.934 -> PSRAM first 4MB free : 3932108 
15:34:08.934 -> PSRAM HI-MEM    size : 4456448 
15:34:08.934 -> PSRAM HI-MEM    free : 4456448 
```
