### ISSUE TITLE
UART BaudRate - Is it 110 possible?

### ISSUE THREAD

**Issue by allexotecnologia** [espressif/arduino-esp32#3723]
Hardware:
Board: ESP32 WROOM 32U
IDE name: Arduino IDE? 
Flash Frequency: 80Mhz
PSRAM enabled: disabled
Upload Speed: 912600 Computer OS: ?Windows 10? ?Mac OSX? ?Ubuntu?

Description:
I'm trying to use one of the serial ports (1) to read a monodirectional serial stream coming from a energy meter. The thing is the baud of the meter comes at 110. 
I've tried to read it, but it stops entering in "Serial.Available()" after the first "Serial.read()" and never comes back inside.

Sketch: 
```
#define SSUSerial Serial1
#define RXD1 5
#define TXD1 18

char dataSSU[255];

 if (SSUSerial.available()) 
    {
      RS485Serial.println("Serial Available");
      RS485Serial.flush();
      if (dataSSUComplete == true)
      {
        char dataSSU[255];
        dataSSUComplete = false;
      }
      if (dataSSUComplete == false)
      {
      while (SSUSerial.available())
      {
        RS485Serial.println("LOOP LEITURA Serial Available");
        RS485Serial.flush();
        char caractereSSU = SSUSerial.read();
        dataSSU[countSSU] = caractereSSU;
        countSSU++;
        RS485Serial.println(countSSU);
        RS485Serial.flush();
        delay(10);
      }
      dataSSUComplete = true;
    }
    String conteudo = "";
    char caractere;
    int count = 0;
    digitalWrite(SSerialTxControl, RS485Transmit); // Enable RS485 Transmit
    for(int i=0; i<countSSU; i++){
      RS485Serial.print("[");
      RS485Serial.print(int(dataSSU[i]), DEC);
      RS485Serial.print("]");
    }
    digitalWrite(SSerialTxControl, RS485Transmit); // Enable RS485 Transmit
    RS485Serial.print("Numero de Bytes Recebidos:");
    RS485Serial.print(countSSU);
    RS485Serial.flush();
}
```

**Comment by lbernstone** [comment]
Please follow the [issue template](https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md).

**Comment by allexotecnologia** [comment]
> Please follow the [issue template](https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md).

Sorry, @lbernstone ! Already edited to help the understanding of the problem. Thanks in advance.
