### ISSUE TITLE
Missing xtensa-esp32-elf when install on Raspberry Pi

### ISSUE THREAD

**Issue by whizzCoder** [espressif/arduino-esp32#374]
When I followed the instruction for Linux to install on Raspberry Pi, the xtensa-esp32-elf folder is missing. Is it supported on Raspberry Pi?

Thanks.

**Comment by me-no-dev** [comment]
Not officially yet, but you can build the toolchain on it and use it.

**Comment by whizzCoder** [comment]
Thanks for the advise. 
is there any instructions somewhere? :)

**Comment by me-no-dev** [comment]
I think on the esp-idf repo readme/docs. On the phone currently so its hard to find :)

**Comment by whizzCoder** [comment]
Thanks ... I'm still searching for the doc. :)

Hi everyone else, if you happen to know any place that I can download the toolchain for raspberry pi 3, or instruction on how to build the toolchain, please let me know. Million thanks. :)

**Comment by tobozo** [comment]
[Pre built binaries for rpi3](http://www.neilkolban.com/esp32/downloads/xtensa-esp32-elf.tar.gz) but it's not recent, also [this video](https://youtu.be/jt0aaMQD1WI)

**Comment by me-no-dev** [comment]
https://github.com/espressif/crosstool-NG

**Comment by whizzCoder** [comment]
Thanks for all the help.
I've started to compile the toolchain.
Almost 2h passed, likely many more to go. :)

**Comment by whizzCoder** [comment]
The toolchain build took 170mins to complete.
I'm able to compile and upload a blinking LED sketch to my ESP32 dev board successfully.
Thank you all for your help.
Happy weekend!

**Comment by pearsilva** [comment]
> The toolchain build took 170mins to complete.
> I'm able to compile and upload a blinking LED sketch to my ESP32 dev board successfully.
> Thank you all for your help.
> Happy weekend!

Could you help me with this?
I'm starting my knowledge on ESP32 using the Raspberry Pi.

Thanks for your attention.

**Comment by urbanze** [comment]
Hi guys, I trying to do this but my knowledge in linux is not the best. When compile IDF, terminal return something similar

`make all -j4
/home/pi/mcu/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: 1: /home/pi/mcu/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: Syntax error: "(" unexpected
expr: syntax error
/bin/sh: 1: xtensa-esp32-elf-gcc: Exec format error
/bin/sh: 1: xtensa-esp32-elf-gcc: Exec format error
Toolchain path: /home/pi/mcu/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
WARNING: Failed to find Xtensa toolchain, may need to alter PATH or set one in the configuration menu`

What I need to do? I not understand "crosstoll-ng"...

**Comment by beegee-tokyo** [comment]
ESP32 toolchain is not available readily for the Raspberry.
Some time ago someone compiled the toolchain for the RPi, but I do not know if it still works:
[Building ESP32 toolchain on ARM (Armbian Raspbian)](https://desire.giesecke.tk/index.php/2018/01/30/building-esp32-toolchain-on-arm-armbian-raspbian/)

**Comment by tobozo** [comment]
@beegee-tokyo I followed the [video](https://youtu.be/jt0aaMQD1WI) tutorial a couple of weeks ago, and it worked just fine.

**Comment by urbanze** [comment]
Well, sucess! I use crosstool-NG to recompile toolchain for arm (raspberry), worked perfecly in most recent master branch of IDF and last toolchain. Followed tutorial:https://docs.espressif.com/projects/esp-idf/en/latest/get-started/linux-setup-scratch.html

**Comment by syswombat** [comment]
Hello
on a Raspberry Pi 4 with Buster is there a easy way to solve the problem!

Tool xtensa-esp32-elf-gcc is not available for your operating system.
java.lang.RuntimeException: java.lang.Exception: Tool xtensa-esp32-elf-gcc is not available for your operating system.
at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Tool xtensa-esp32-elf-gcc is not available for your operating system.
at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:85)
at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
... 1 more
