### ISSUE TITLE
Errors while interacting with SD card

### ISSUE THREAD

**Issue by katzuv** [espressif/arduino-esp32#3741]
### Hardware:
Board:							ESP32-CAM
Core Installation/update date:			
IDE name:						Arduino IDe
Flash Frequency:					don't know
PSRAM enabled:                                          yes
Upload Speed:						115200
Computer OS:                                            Ubuntu 16.04

### Description:
I have an ESP32-CAM board with a microSD card attached (16GB). In my `setup` function I create a directory. In `loop` the ESP32-CAM takes images and stores in the directory.
The code successfully creates the directory and captures one image inside the directory. However, when the `loop` function runs the second time, I get the following errors:
```
E (10911) sdmmc_cmd: sdmmc_read_sectors_dma: sdmmc_send_cmd returned 0xffffffff
E (10912) diskio_sdmmc: sdmmc_read_blocks failed (-1)
E (11913) sdmmc_req: sdmmc_host_wait_for_event returned 0x107
E (11913) sdmmc_cmd: sdmmc_read_sectors_dma: sdmmc_send_cmd returned 0x107
E (11914) diskio_sdmmc: sdmmc_read_blocks failed (263)
```
What can I do to fix those?
Thank you!

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
[Link to gist](https://gist.github.com/katzuv/64da2ecc04374809f5dd1cbd718fab72)
### Debug Messages:
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
Can't find "debug" in tools menu of Arduino IDE.

**Comment by CharStiles** [comment]
I am running into the same issue, I am able to follow this tutorial alright! https://dronebotworkshop.com/esp32-cam-microsd/
so i know my SD card isnt bad. The issue arises when I try to use a TFT display. I think that the pins that the TFT are using interfere with SD card reading. 
I am not a well seasoned embedded programmer, so there might be something obvious i am missing
