### ISSUE TITLE
mcpwm.h  is missing the first 4 enums in mcpwm_sync_signal_t

### ISSUE THREAD

**Issue by gouldpa** [espressif/arduino-esp32#3743]
Please update the mcpwm.h file with the following code

`/**
 * @brief MCPWM select sync signal input
 */
typedef enum {
   MCPWM_SELECT_SYNC_OFF	/*!< SYNC is off*/
   MCPWM_SELECT_SYNC_INT0,    /*!<Select SYNC0 as internal*/
   MCPWM_SELECT_SYNC_INT1,    /*!<Select SYNC1 as internal*/
   MCPWM_SELECT_SYNC_INT2,    /*!<Select SYNC2 as internal*/
    MCPWM_SELECT_SYNC0,  	      /*!<Select SYNC0 as input*/
    MCPWM_SELECT_SYNC1,         /*!<Select SYNC1 as input*/
    MCPWM_SELECT_SYNC2,         /*!<Select SYNC2 as input*/
} mcpwm_sync_signal_t;`

The purpose of this code is to use the internal Sync feature for Three Phase PWM signals

https://github.com/espressif/arduino-esp32/blob/04963009eedfbc1e0ea2e1378ae69e7cebda6fd6/tools/sdk/include/driver/driver/mcpwm.h

**Comment by lbernstone** [comment]
This file comes from the upstream source (esp-idf).  You can raise an issue [there](https://github.com/espressif/esp-idf/issues)
