### ISSUE TITLE
Is it good way to restart ESP32?

### ISSUE THREAD

**Issue by varunsavita** [espressif/arduino-esp32#3750]
Actually, my hardware  PCB is not allow me to restart the controller due to which  I don't want to use ESP.restart in my final code.
Is it a good way to use code without adding ESP.restart .
I used MQTT, OTA, WiFi- AP and STA mode, Task.

**Comment by 2010019970909** [comment]
I'll look to FreeRTOS to start a task with your services and then being able to kill, pause, resume, or restart a service.
