### ISSUE TITLE
arduino core does not work in eclipse with esp-idf 4.0

### ISSUE THREAD

**Issue by gbortnikov** [espressif/arduino-esp32#3753]
I set up the project at https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html#related-documents

added arduino bark according to the instructions https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md

fatal error: Arduino.h: No such file or directory

**Comment by ivog1** [comment]
The problem still persists. Only workaround is to change **platform = espressif32** to **platform = espressif32@1.11.2**
But seems that there is no workaround for **platform = espressif32**
