### ISSUE TITLE
How to GET ESP32 CORE Version ?

### ISSUE THREAD

**Issue by laercionit** [espressif/arduino-esp32#3759]
I'm having trouble getting CORE installed on ESP32, currently using 1.0.4.
From what I analyzed there is no function for that. Would it be possible to include this feature?

In ESP8266 we have the following functions returning a string. I think I can even make some changes to the core and submit, but I don't know where to get the CORE Version.
ESP.getCoreVersion ()
ESP.getSdkVersion ()
ESP.getChipId ()

**Comment by jaggil** [comment]
you can see this:
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Esp.h#L63
