### ISSUE TITLE
Esp32_arduino_wifi_error

### ISSUE THREAD

**Issue by razi123** [espressif/arduino-esp32#376]
'Class wifi class has no member named mode'

Some thing same.. 
https://github.com/espressif/arduino-esp32/issues/103

Please help me I am new to programming, explain me the steps to follow.

Thanks..

**Comment by me-no-dev** [comment]
I would guess you did not select the correct board in the Arduino menu.

**Comment by 5mi73y** [comment]
If you still have esp8266 board liberary then your wifi class will depend on esp8266. Rename the WiFi.h of esp32 and include that in your *.ino file.
