### ISSUE TITLE
GPIO16 and 17

### ISSUE THREAD

**Issue by kriswiner** [espressif/arduino-esp32#3762]
I am using the ESP32 PICO D4 in a custom board design based on the ESP32Eye design, among others, which all work fine. But I have not been able to make use of GPIO16 and 17. I just realized that none of the board variants (including ESP32 Dev Module that I have been using) lists GPIO16 or 17 in the pins_arduino.h file. So no wonder my attempts to blink and led with these pins has never worked.

Is there someway I could add these pins to the pins_arduino.h list without messing up the other pin functions? And why aren't these pins typically included in most f not all of the ESP32 dev board variants?

**Comment by stickbreaker** [comment]
GPIO16 and 17 are standard pins, UNLESSf you have PSRAM. The WROVER base ESP32 use those pins, so like the GPIO6..11 they are off limits.

Chuck.

**Comment by lbernstone** [comment]
Pins 16 and 17 are used by the internal flash in Pico chips.
https://dl.espressif.com/dl/schematics/esp32-pico-kit-v4_schematic.pdf

**Comment by kriswiner** [comment]
Thanks, that explains why they are not included in the pin list...

**Comment by G6EJD** [comment]
@kriswinder, should you not close this issue now you know what the problem was?

**Comment by kriswiner** [comment]
OK

**Comment by mkeyno** [comment]
I use wroom and both pins are free, however, when I use simple lrdc or timer library, they work fine, but if use extra timer they are not working
Does anybody knows which peripheral or API affect this pin functionality

**Comment by mkeyno** [comment]
I use wroom and both pins are free, however, when I use simple lrdc or timer library, they work fine, but if use extra timer they are not working
Does anybody know which peripheral or API affects this pin functionality?
