### ISSUE TITLE
Please, add TTGO T-Camera Plus board to plateformIO 

### ISSUE THREAD

**Issue by ZeRico** [espressif/arduino-esp32#3766]
hello, 
can you please add the TTGO T-Camera Plus board on plateformIO so as to be programmable with this IDE?
thank you very much

**Comment by Gavitron** [comment]
I too would like this, ref: https://github.com/platformio/platform-espressif32/issues/190

**Comment by HaJo10** [comment]
I would like to use this board "TTGO T-Camera Plus" on PlatformIO too.
I am new to PlatformIO and esp32, so this would be great!
