### ISSUE TITLE
How accurate is 8 MHz internal oscillator and how to use it for millis()?

### ISSUE THREAD

**Issue by ghost** [espressif/arduino-esp32#3776]
Hi. I want to use arduino core with [this](https://dstike.com/products/dstike-esp32-watch-devkit) devkit. I want to measure time using millis(), but that devkit doen't have RTC and I don't want to sync with NTP all the time. I googled information about it and there are two oscillators - 150khz RC and 8Mhz unspecified. And the last one is more accurate. According to old datasheeet it's 1% accuracy is guaranteed by design. But 1% for day is 14.4 min, so it is VERY inaccurate. But this info was removed in nowadays datasheet. So am I right and even 8Mhz oscillator is so inaccurate?
And the second question is, how to enable that oscillator to use with millis()?

**Comment by fededim** [comment]
I'm interested in this issue too....is it possible to change the RTC clock source from default 150Khz RC oscillator to internal 8Mhz ? In [esp-IDF](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html) it is possible by configuring  CONFIG_ESP32_RTC_CLK_SRC. Any plan to port it also to Arduino framework ?
