### ISSUE TITLE
How to role switch (Master to Slave) with ESP32 Bluetooth classic functionality?

### ISSUE THREAD

**Issue by Darram007** [espressif/arduino-esp32#3788]
I am trying to implement role switch (master to slave or slave to master) functionality with esp32 Bluetooth classic.  Device which I want to connect, has a two mode first, it does the pairing and in the second mode it transfers the data (in this mode it sends the request to already paired device during step 1). 

I am wondering, is it possible to implement two functionalities with esp32 board. (pairing mode with master and then salves mode for data transfer)?

Are there any examples in esp-idf? if you come across then please let me know.

Examples:  a mouse connects to the pc. The mouse initiates the connection, so it is the master, after the connection is made, a role switch occurs so that the pc becomes the master and the mouse becomes a slave.

**Comment by LaserTagMods** [comment]
Did you figure out getting master to work?
