### ISSUE TITLE
Help me please !!

### ISSUE THREAD

**Issue by giorgos27** [espressif/arduino-esp32#3789]
hey guys i bought an esp32 devkitc v4 and I want to code using Arduino IDE.
After a lot of searching I can't find support for that model.
please help me (:

**Comment by chegewara** [comment]
It is `esp32 devkitc `, thats all you need to know.

**Comment by Sagar73594** [comment]
Have you tried to upload code using ESP32 Devkitc?

**Comment by giorgos27** [comment]
I can't find it

**Comment by Sagar73594** [comment]
> I can't find it

Okay, Now please describe in brief what problem/error you are facing?
