### ISSUE TITLE
arducore.h missing

### ISSUE THREAD

**Issue by elFallino** [espressif/arduino-esp32#38]
In "cores\esp32\wiring_private.h" line 32 there is an include for arducore.h but that files seems not to exist.

**Comment by ladyada** [comment]
normally this would be #include "Arduino.h" but when that's done, get an odd complaint about the random() prototypes conflicting which is kinda unusual. see
https://github.com/adafruit/arduino-esp32/commit/871f28ed9b594bf4b4e82bc124293024b878a552

**Comment by me-no-dev** [comment]
fixed [here](https://github.com/espressif/arduino-esp32/commit/a5d52ac4f7917745d988b8ea00a03dda16a01202)
