### ISSUE TITLE
Ticker::active() is not implemented

### ISSUE THREAD

**Issue by fabiuz7** [espressif/arduino-esp32#3812]
I was trying to use this method in my project, but the compiler tells me the following message:

    undefined reference to `Ticker::active()'

I've looked at the [latest commit on master](https://github.com/espressif/arduino-esp32/blob/0f772270fbb32099cad72053755d6b4c7e8e1f82/libraries/Ticker/src/Ticker.h#L96), and it seems it is not implemented.

**Comment by laercionit** [comment]
bool Ticker::active() const
{
    return _timer;
}

Include on ticker.cpp
