### ISSUE TITLE
esp_now_mod_peer() crash-bug

### ISSUE THREAD

**Issue by WereCatf** [espressif/arduino-esp32#3815]
Make your question, not a Statement, inclusive. Include all pertinent information:

What you are trying to do?
Describe your system( Hardware, computer, O/S, core version, environment).
Describe what is failing.
Show the shortest possible code that will duplicate the error.
Show the EXACT error message(it doesn't work is not enough).
All of this work on your part shows us that you have worked to solve YOUR problem. The more complete your issue posting is, the more likely someone will volunteer their time to help you.

If you have a Guru Meditation Error or Backtrace, ***please decode it***:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							Many different ones
Core Installation version:			git-0f772270fbb32099cad72053755d6b4c7e8e1f82
IDE name:						Arduino IDE
Flash Frequency:					40MHz and 80MHz
CPU Frequency:					80MHz, 160MHz and 240MHz
PSRAM enabled:                                    Yes and no
Upload Speed:					921600
Computer OS:                                        Windows 10

### Description:
calling esp_now_mod_peer() crashes the CPU, if called on a peer that didn't initially have encryption enabled, but you're now trying to enable encryption.
### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp
#include <esp_now.h>
#include <WiFi.h>

esp_now_peer_info_t nowHost;

void setup() {
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  esp_now_init();
  memset((void *) &nowHost, 0, sizeof(esp_now_peer_info_t));
  nowHost.encrypt = 0; //Set this to 1 and the following esp_now_mod_peer won't crash!
  esp_now_add_peer(&nowHost);

  nowHost.encrypt = 1;
  esp_now_mod_peer(&nowHost); //CRASH
  while(true) delay(1000); //Never reaches this
}

void loop() {
}
```

### Debug Messages:
```
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10864
load:0x40080400,len:6432
entry 0x400806b8
[D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
[D][WiFiGeneric.cpp:332] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:332] _eventCallback(): Event: 2 - STA_START
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400da771  PS      : 0x00060430  A0      : 0x800daa30  A1      : 0x3ffb1f20  
A2      : 0x3ffafed0  A3      : 0x3ffc11ce  A4      : 0x00000010  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000006  A9      : 0x00000000  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x000000a0  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x00000001  SAR     : 0x00000010  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x000000b0  LBEG    : 0x4000c349  LEND    : 0x4000c36b  LCOUNT  : 0xffffffff  

ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000

Backtrace: 0x400da771:0x3ffb1f20 0x400daa2d:0x3ffb1f50 0x400da5e8:0x3ffb1f70 0x400d125c:0x3ffb1f90 0x400d24da:0x3ffb1fb0 0x40090329:0x3ffb1fd0

Rebooting...
```

**Comment by lbernstone** [comment]
Please follow the [issue template](https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md)

**Comment by lbernstone** [comment]
What makes you think the original add_peer is working?  You are giving it an empty structure.  See the example at https://github.com/espressif/esp-idf/blob/master/examples/wifi/espnow/main/espnow_example_main.c#L302-L315.  They always check to see if the structure is empty before doing anything with it...

**Comment by WereCatf** [comment]
@lbernstone  No, they aren't. They are using malloc to allocate the memory for the structure and then checking if the pointer to the structure is NULL, ie. if the malloc succeeded. In the above code, I am not using a malloc/free and am just allocating the structure from the get-go.
