### ISSUE TITLE
Native resolving .local domain

### ISSUE THREAD

**Issue by Cicicok** [espressif/arduino-esp32#3822]
ESP8266 Arduino library supports native resolving of local domains like `serve.local`. But why ESP32 don't?
This one works perfectly on ESP8266:
```
client.connect(serve.local, 80);
```
but on ESP32 produces error `hostByName(): DNS Failed for server.local`

Where is the difference? Which part of code or library is here missing?

**Comment by lbernstone** [comment]
If you have a local DNS server with avahi/Bonjour (mDNS) capabilities, it will resolve just fine.  I am able to resolve .local mDNS addresses on my esp32.

**Comment by asier70** [comment]
This probably depends on LWIP library. Arduino ESP32 library uses very old version, ESP8266 library inludes newer version.

**Comment by Cicicok** [comment]
That could be it. esp8266 community uses the latest 2.1.2 version https://github.com/d-a-v/esp82xx-nonos-linklayer, but here we're stuck with 2.0.3
https://github.com/espressif/arduino-esp32/blob/0f772270fbb32099cad72053755d6b4c7e8e1f82/tools/sdk/include/lwip/lwip/init.h#L52-L57

**Comment by MikaAK** [comment]
This stale bot seems like a real kicker, stale issues just get closed when they're actually valid 😮 What's the solution to this?

**Comment by markg85** [comment]
Un-stale please.
I too have this issue and am looking for a solution. One that does allow me to keep using .local names and does not require me to setup a local dns server.

**Comment by NorthernMan54** [comment]
Latest release candidate doesn't appear to resolve this

**Comment by moimart1** [comment]
Any workaround at least ?

**Comment by moimart1** [comment]
Finally, I found this https://www.tutorialfor.com/questions-324359.htm

```
  #include<ESPmDNS.h>

  mdns_init ();// Add
  IPAddress ipaddr = MDNS.queryHost("my-host-without-dot-local", 5000 /* ms */);
  if (ipaddr == INADDR_NONE)
  {
    // If not valid
    ipaddr.fromString("192.168.0.1");
  }
```

**Comment by markg85** [comment]
> Finally, I found this https://www.tutorialfor.com/questions-324359.htm
> 
> ```c++
>   #include<ESPmDNS.h>
> 
>   mdns_init ();// Add
>   IPAddress ipaddr = MDNS.queryHost("my-host-without-dot-local", 5000 /* ms */);
>   if (ipaddr == INADDR_NONE)
>   {
>     // If not valid
>     ipaddr.fromString("192.168.0.1");
>   }
> ```

Hi!

While that is a nice trick, it might or might not work. It entirely depends on other factors in your home network (particularly your router) if it works.

In my case i have a pc that i can only ping by name if i ping with the explicit .local suffix.
If i leave that out then it won't resolve and won't ping.
This is a DNS thingy where it depends on your network settings if you can "ping both", in that case the above trick works.

I'm still searching for a way to make the .local thingy work too... I'll let it know if i find something.

**Comment by markg85** [comment]
I took a deep dive into this issue and documented my findings here: https://github.com/espressif/esp-idf/issues/2507#issuecomment-761836300

The actual issue is that for whatever reason the ESP32 SDK blindly adds ".local" to mdns queries. That's downright wrong as ".local" is something a user can change (.local is the default) and doing this makes it a lot more difficult to lookup names.
