### ISSUE TITLE
Question: ESP32-CAM

### ISSUE THREAD

**Issue by FilipeOS** [espressif/arduino-esp32#3843]
Hi guys,

I've bought the `ESP32-CAM WiFi + bluetooth Camera Module Development Board ESP32 With Camera Module OV2640 IPEX 2.4G SMA Antenna` from Greekcreit with module cam-progShort from Tindie (to add USB) and when I was installtion Arduino and following instructions, when I go to Tools->Board, which should I choose in this case? ESP32 Dev Module?

**Specifications:**
Module model | ESP32-CAM
-- | --
Package | DIP-16
Size | 27*40.5*4.5(±0.2)mm
SPI Flash | default 32Mbit
RAM | internal520KB+external 4M PSRAM
bluetooth | bluetooth4.2BR/EDR and BLE standards
Wi-Fi | 802.11 b/g/n/e/i
Support interface | UART, SPI, I2C, PWM
Support TF card | Maximum support 4G
IO port | 9
Serial port rate | default 115200 bps
Image output format | JPEG (only supported by OV2640), BMP, GRAYSCALE
Spectrum range | 2412 ~ 2484MHz
Antenna form | onboard PCB antenna , gain 2dBi
Transmit power | 802.11b: 17±2 dBm (@11Mbps)802.11g: 14±2 dBm (@54Mbps)802.11n: 13±2 dBm (@MCS7)
Receiving sensitivity | CCK, 1 Mbps : -90dBmCCK, 11 Mbps: -85dBm6 Mbps (1/2 BPSK): -88dBm54 Mbps (3/4 64-QAM): -70dBmMCS7 (65 Mbps, 72.2 Mbps): -67dBm
Power consumption | Turn off the flash: 180mA@5VTurn on the flash and adjust the brightness to the maximum: 310mA@5VDeep-sleep: The lowest power consumption can reach 6mA@5VModerm-sleep: up to 20mA@5VLight-sleep: up to 6.7mA@5V
Security | WPA/WPA2/WPA2-Enterprise/WPS
Power supply range | 5V
Operating temperature | -20 °C ~ 85 °C
Storage environment | -40 °C ~ 90 °C, < 90%RH

My objective is to integrate it with Android+iOS using the Bluetooth or Wifi or Camera for research purposes using Android Studio and Java.

Thank you

**Comment by WereCatf** [comment]
> when I go to Tools->Board, which should I choose in this case? ESP32 Dev Module?

The "AI Thinker ESP32-CAM"
