### ISSUE TITLE
Implementing MAP/PBAP

### ISSUE THREAD

**Issue by welle108** [espressif/arduino-esp32#3851]
### Hardware:
Board:							Adafruit ESP32 WROOM
IDE name:						Espressif IDF
Computer OS:                                          Debian 10

### Description:
I want to implement either MAP or PBAP on the ESP32. I've read the bluetooth specs for both and know they operate over OBEX, but am unsure how to translate that to the esp32. I'm relatively new to bluetooth programming, so my main confusion is figuring out what architecture I need to code and what the bluedroid stack already has that I can use. My questions are:

* Is this possible?
* Can I use the OBEX implementation that BIP runs on top of on the esp32?
* If not, what do I need to learn/do get MAP or PBAP working on an esp?
* Is there a way to do this with GATT/BLE? I know I'd need to access some kind of GATT server on the phone I'd be connecting to (Using my Android as a test device), but I see handsfree car kits which don't require me to download an app in order to use this functionality, so I was wondering if this is possible or there's something I'm missing.

Thank you for any responses in advance

**Comment by lbernstone** [comment]
This is a better question for https://esp32.com . This forum is for problems with the arduino codebase.
