### ISSUE TITLE
 Would you please make a arduino lib to support Hilink 

### ISSUE THREAD

**Issue by myie9** [espressif/arduino-esp32#3858]
ESP8266WiFi library of arduino is very good.
   I used it for 2 years.
   The smartconfig function of it is very nice.

   Would you please make a arduino lib to support Hilink of config network ?

  Hilink is supported by Huawei Wifi router. Users  can config network by just press one button on the router.

Here is some reference:
hilink api doc:
https://developer.huawei.com/consumer/cn/doc/development/smarthome-References/3090501

code:
https://github.com/myie9/esp8266-hilink

**Comment by lbernstone** [comment]
ESP32 supports the industry standard WPS for one touch config:
https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi/examples/WPS

**Comment by myie9** [comment]
thank u very much


发自我的iPhone

------------------ Original ------------------
