### ISSUE TITLE
setTimeZone should not be static

### ISSUE THREAD

**Issue by Nagymadar** [espressif/arduino-esp32#3873]
setTimeZone is a pretty easy way to change time zone and summer time. This function should be available to be called from outside esp32-hal-time.c. Is there a particular reason to be static?

**Comment by hitecSmartHome** [comment]
Why is it static?

**Comment by me-no-dev** [comment]
It can not be called on it's own. NTP has to be started an that requires other things to be started as well.

**Comment by jprouty** [comment]
For my particular use case, I want to use NTP to sync the time (roughly) once, after the first boot. Once the RTC time has been established, I will use a series of deep sleeps to conserve energy (on battery). On each subsequent boot (coming out of deep sleep) I only require setting the timezone (via setTimeZone) to then reinterpret the time in local time once again.

Electively, I could every so often sync with NTP to prevent skew.
