### ISSUE TITLE
Webserver.h fails on ESP32 when it has to load multiple parts of one web page

### ISSUE THREAD

**Issue by ullix** [espressif/arduino-esp32#3890]
I'm using an ESP32-Dev to serve web pages using the "WebServer.h" lib. Works well when serving a plain, complete page, but fails when the page requires loading e.g. *.css and *.js as separate files also located in the ESP32, either created in the code on-the-fly, or stored as regular text files in an FFat on flash. No problem when the files are loaded from an internet resource.
Looking at the page loading with Chromium Developer Tools shows this:

![Auswahl_340](https://user-images.githubusercontent.com/9335726/78991700-d7143700-7b39-11ea-9621-fa649a402ed3.png)

The web page code is straight forward, here an excerpt for the download part: (impossible to past html code here? so i use pic) 

![Auswahl_339](https://user-images.githubusercontent.com/9335726/78991506-5d7c4900-7b39-11ea-97a9-65d9a122a912.png)

The files in red are single-digit kB, but the d3* file is >200kB. 

All files, also the (relatively) large d3* file, load without any problem from the ESP32, when they are the **only** file to load. 

At the same time the terminal shows this response, when loading that failing page:

>     [D][WiFiClient.cpp:509] connected(): Disconnected: RES: 0, ERR: 128
>     [D][WiFiClient.cpp:509] connected(): Disconnected: RES: 0, ERR: 128
>     [D][WiFiClient.cpp:509] connected(): Disconnected: RES: 0, ERR: 128
>     [D][WiFiClient.cpp:509] connected(): Disconnected: RES: 0, ERR: 128
>     [D][WiFiClient.cpp:509] connected(): Disconnected: RES: 0, ERR: 128

My interpretation: The webserver (or Wificlient?) is disconnecting after the initiating page starts, because it can handle only a single connection. After that it can't resume, and everything is lost until enough time has passed that the favicon.png file can be loaded again. 

If so, what can I do to convince Webserver to load all pages? 

Note: I had used the ESPAsyncWebserver before, where this particular problem is absent. However, I had so much other trouble with it, that I am now tried WebServer.

Having to load a few pages in addition to the initiating page is a rather ordinary task when serving webpages. I can't believe that Webserver can't do that?

**Comment by ElToberino** [comment]
I'm facing the same issue and searching the web I read a lot of posts describing exactly this problem.
I can't believe this hasn't been fixed yet. As the thread opener wrote, loading external css or calling additional data with a script on page loading isn't a rare but a trivial and everyday task for a browser - a web server should be able to handle this easily!

**For me, the problem occurs with Chrome or Chromium based browsers, with Firefox everything works fine, fast and smoothly.** (Tested this on Win10 and Android.)

Btw: The same sketch runs on an ESP8266 without an issues - with Firefox AND Chrome!
