### ISSUE TITLE
Any support for ov7725 possible?

### ISSUE THREAD

**Issue by kupince** [espressif/arduino-esp32#3897]
Hi is it possible to use [ov7725 camera](https://www.aliexpress.com/item/4000130895345.html?spm=a2g0o.productlist.0.0.703baad3AlJs18&algo_pvid=a3912fe0-b649-4a08-8f9d-13d76a24b79f&algo_expid=a3912fe0-b649-4a08-8f9d-13d76a24b79f-3&btsid=0b0a050115866882663537492e4c01&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) in "camerawebserver.ino" 
if yes how to configure the code ?
thanks

**Comment by lbernstone** [comment]
The ov7725 is supported.  I cannot guarantee that camerawebserver.ino can use it, but it should.

**Comment by kupince** [comment]
i use arduino ide and i dont know how do i get a image or stream from browser
