### ISSUE TITLE
 Is there an ESP32 with 16MB flash memory?

### ISSUE THREAD

**Issue by Pietro1994** [espressif/arduino-esp32#3907]
I'm trying to search around the internet (digikey, amazon, ebay, mouser, etc.)
for an ESP32 DEVKIT with 8/16 Mb of memory. 
That you know exists and is available on some store?

I own this card: https://www.amazon.it/gp/product/B071P98VTG/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1

this card has a memory of 4 MB.
I need an esp32 devkit with much more memory.

Thanks.

**Comment by chegewara** [comment]
This or similar, there is few versions and you can find one with 16MB:
https://pl.mouser.com/ProductDetail/Espressif-Systems/ESP32-DevKitC-VB?qs=w%2Fv1CP2dgqq1iFM3SpreoA%3D%3D

**Comment by Pietro1994** [comment]
thank you so much
