### ISSUE TITLE
ESP32 suddenly disconnect from usb ports

### ISSUE THREAD

**Issue by IrfanGazali** [espressif/arduino-esp32#3923]
Hello guys, my esp32 suddenly disconnect and i tried update and download cp20x and ch340 drivers also didn't work. Before this, the board is working well. There are no sound when connect the board to pc and the led is off also the COM port not appear. I also tried change about 3 different usb cables. What is the problem my board or pc? thank you hopefully it can be fix.

**Comment by BF-Andrew** [comment]
You will need a logic analyzer or oscilloscope to figure this out.  Probe the TX pins on boot.  It should go from high to low during the boot.  This is the boot message being sent out on TX.
