### ISSUE TITLE
ETH BLE Disconnect

### ISSUE THREAD

**Issue by LoxSimi** [espressif/arduino-esp32#3938]
Hello!
Eth connection is established successfully and if
ble ad or search is launched you will be constantly disconnected.
Why is that?

ETH Connected
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 25 - MAX
[D][WiFiGeneric.cpp:421] _eventCallback(): ETH IP: 192.168.100.66, MASK: 255.255.255.0, GW: 192.168.100.1
D, FULL_DUPLEX, 100Mbps
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 24 - ETH_GOT_IP
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 23 - ETH_DISCONNECTED
ETH Connected
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 25 - MAX
[D][WiFiGeneric.cpp:421] _eventCallback(): ETH IP: 192.168.100.66, MASK: 255.255.255.0, GW: 192.168.100.1
, IPv4: 192.168.100.66, FULL_DUPLEX, 100Mbps
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 24 - ETH_GOT_IP
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 23 - ETH_DISCONNECTED
ETH Connected
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 25 - MAX
[D][WiFiGeneric.cpp:421] _eventCallback(): ETH IP: 192.168.100.66, MASK: 255.255.255.0, GW: 192.168.100.1
, IPv4: 192.168.100.66, FULL_DUPLEX, 100Mbps

**Comment by bluelu** [comment]
@LoxSimi I have the same issue. Which board are you using? https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware ?
