### ISSUE TITLE
Would it make sense to make getService() public in BLECharacteristic.h ? 

### ISSUE THREAD

**Issue by JasXSL** [espressif/arduino-esp32#3963]
In `libraries/BLE/src/BLECharacteristic.h` > `class BLECharacteristic`, the method `getService();` (which returns the service the characteristic is tied to) is private. Would it make sense to make this method public? So we can get the service a characteristic is tied to in the onWrite callback?

I've edited it locally and it works fine, but I'm curious if there's any particular reason it's private? For an example the BLEService class allows you to get its parent server object the same way.

Defined here:
https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/src/BLECharacteristic.h#L118

**Comment by chegewara** [comment]
Yes, it is good change to make it public. I saw few use cases where it was useful, probably ive got one use case i needed it too and modified library locally.
