### ISSUE TITLE
ESP32 boards.txt data

### ISSUE THREAD

**Issue by weswitt** [espressif/arduino-esp32#3967]
My question is about the ESP32 Arduino support and use of the boards.txt file.

The definitions in the PartitionScheme section are very terse yet the IDE seems to have information that is not present in the file.  For example the definitions for the d32 board look like this:

d32.menu.PartitionScheme.default=Default
d32.menu.PartitionScheme.default.build.partitions=default
d32.menu.PartitionScheme.minimal=Minimal (2MB FLASH)
d32.menu.PartitionScheme.minimal.build.partitions=minimal
d32.menu.PartitionScheme.no_ota=No OTA (Large APP)
d32.menu.PartitionScheme.no_ota.build.partitions=no_ota
d32.menu.PartitionScheme.no_ota.upload.maximum_size=2097152
d32.menu.PartitionScheme.min_spiffs=Minimal SPIFFS (Large APPS with OTA)
d32.menu.PartitionScheme.min_spiffs.build.partitions=min_spiffs
d32.menu.PartitionScheme.min_spiffs.upload.maximum_size=1966080

There is nothing here about the flash size, SPIFFS size, page size, block size, etc.  However when the IDE invokes tools like mkspiffs, esptool, etc. it needs and in fact somehow has that information. For the ESP8266 boards this information is all fully specified in the boards.txt file.

My question is where is this detailed information kept if not in the boards.txt file??

**Comment by lbernstone** [comment]
The partition scheme matches up to a csv file in tools/partitions.  Page size and block size are essentially fixed.  Only the entries included in boards.txt show up; NB there are many more options for esp32 than a minimally defined device like d32.  We get the information from the community, so if you want it improved, submit a PR.  esp8266 uses a script to generate boards.txt, so it is much more consistent.  That is on the to-do list, but not a high priority.

**Comment by weswitt** [comment]
thanks
