### ISSUE TITLE
Joystick and wifi connected with ADC1 pin

### ISSUE THREAD

**Issue by amirjak** [espressif/arduino-esp32#3994]
### Hardware:
Board:							?ESP32 Dev Module? 
Core Installation version:			?1.0.4?
IDE name:						?Arduino IDE? 
Flash Frequency:					?80Mhz?
PSRAM enabled:                                    ?no? 
Upload Speed:					?115200?
Computer OS:                                        ?Windows 10?

### Description:
Describe your problem here

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>
#include <WiFi.h>

void setup() {

  Serial.begin(115200);
  Serial.print("Connecting to Network");
  WiFi.mode(WIFI_STA);                      // Mode Station
  WiFi.begin(ssid, password);               // Matching the SSID and Password
  // Waiting to connect to wifi
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);

}

void loop() {
  int x = analogRead(34);
  int y = analogRead(27);
  Serial.print("x : ");
  Serial.print(x);
  Serial.print("____ y : ");
  Serial.println(y);
}

**Comment by amirjak** [comment]
x : 2672____ y : 4095

**Comment by amirjak** [comment]
serial monitor

x : 2666____ y : 4095
x : 2654____ y : 4095
x : 2669____ y : 4095
x : 2671____ y : 4095
x : 2655____ y : 4095
x : 2659____ y : 4095
x : 2684____ y : 4095

**Comment by amirjak** [comment]
I use pin 27 ADC2_ch7 and ADC1_ch6 
Whine wifi connected not working correct
pin  32-33-34-35-36-39 not working correct 


serial monitor

x : 2666____ y : 4095
x : 2654____ y : 4095
x : 2669____ y : 4095
x : 2671____ y : 4095
x : 2655____ y : 4095
x : 2659____ y : 4095
x : 2684____ y : 4095

**Comment by amirjak** [comment]
![Joe-Steak-256x256](https://user-images.githubusercontent.com/46311349/81772579-7fcc0280-94fb-11ea-941a-461bd82a1822.jpg)

**Comment by amirjak** [comment]
I use pin 27 ADC2_ch7 and ADC1_ch6
Whine wifi connected not working correct
pin 32-33-34-35-36-39 not working correct

serial monitor

x : 2666____ y : 4095
x : 2654____ y : 4095
x : 2669____ y : 4095
x : 2671____ y : 4095
x : 2655____ y : 4095
x : 2659____ y : 4095
x : 2684____ y : 4095

**Comment by amirjak** [comment]
I use pin 27 ADC2_ch7 and ADC1_ch6
When I am not touching the joystick and wifi connected not working correct 
pin 32-33-34-35-36-39 not working correct

serial monitor Read:

x : 2666____ y : 4095
x : 2654____ y : 4095
x : 2669____ y : 4095
x : 2671____ y : 4095
x : 2655____ y : 4095
x : 2659____ y : 4095
x : 2684____ y : 4095

**Comment by amirjak** [comment]
I use ADC2 pin and find out. ADC2 is used by the Wi-Fi driver. Therefore the application can only use ADC2 when the Wi-Fi driver has not started.

But not working whit ADC1 pin.

**Comment by atanisoft** [comment]
27 is on ADC2, while WiFi is active only ADC1 should be used which maps to pins above 30.

**Comment by atanisoft** [comment]
Can you share your connections on the joystick module?

**Comment by amirjak** [comment]
Hi, thank you for your quick answering

**Comment by amirjak** [comment]
#define SW_PIN 5
#define VRY_PIN 34
#define VRX_PIN 27
#define LOW_RANGE 0
#define HIGH_RANGE 3500
#define RANGE_DIVITION 100

**Comment by amirjak** [comment]
#define VRY_PIN 34 or 35.36.39
#define VRX_PIN 27  or 34.35.36.39

**Comment by amirjak** [comment]
When  wifi connected not working correct

**Comment by atanisoft** [comment]
And how are you powering the joystick module? If you use say 34 and 35 for x and y, does it always read 4095 for y? Can you swap the pins for x and y?

**Comment by amirjak** [comment]
### **I change my code**

#define SW_PIN 5
#define VRY_PIN 35
#define VRX_PIN 34
#define LOW_RANGE 0
#define HIGH_RANGE 4095
#define RANGE_DIVITION 100

### **now**   Up and the right work together at same time

**Comment by amirjak** [comment]
### **but left and dawn  working correct**

**Comment by amirjak** [comment]
Powering the joystick module with 5v

**Comment by atanisoft** [comment]
Power the joystick with 3.3v as anything higher will read as 4095 when you are beyond a certain point in the axis.

**Comment by atanisoft** [comment]
And an example found via Google: https://esp32.com/viewtopic.php?f=19&t=14803 (where this should have likely been posted since it looks like user error or faulty joystick module)

**Comment by amirjak** [comment]
Power the joystick with 3.3v 
### **working correct**
 thank you for your quick answering
### **When it's up**
 Up: 1 | Down: 0 | Left: 0 | Right: 0 | VRx: 2002 | VRy: 4095 | SW: 1 |
### **When it's Right**
Up: 0 | Down: 0 | Left: 0 | Right: 1 | VRx: 4095 | VRy: 1840 | SW: 1 |
### **When it's Down**
Up: 0 | Down: 1 | Left: 0 | Right: 0 | VRx: 2066 | VRy: 0 | SW: 1 |
### **When it's Left**
Up: 0 | Down: 0 | Left: 1 | Right: 0 | VRx: 0 | VRy: 1781 | SW: 1 |

**Comment by amirjak** [comment]
thanks a lot### ****

**Comment by amirjak** [comment]
### **thanks a lot**

**Comment by atanisoft** [comment]
Keep in mind the esp32 is a 3v3 device even if it has a 5v pin on most boards, which is usually connected to the USB connection and prior to the voltage regulator for the esp32.

If your issue has been fixed please close.

**Comment by amirjak** [comment]
### **Thanks for information.**
