### ISSUE TITLE
Allow DTLS in MBEDTLS

### ISSUE THREAD

**Issue by alorbach** [espressif/arduino-esp32#3999]
Please enable CONFIG_MBEDTLS_SSL_PROTO_DTLS=y for the next release, which includes DTLS Support into MBEDTLS library.

There are some API's using DTLS in Smart Home environment like (Philips Hue Entertainment API). And without DTLS it is not possible to use them.

I have compiled libraries myself with DTLS support and got it successfully running with Philips Hue Entertainment API.

**Comment by lbernstone** [comment]
This will be set in the IDF 4.2 release (probably the next version).

**Comment by alorbach** [comment]
thanks that are awesome news :)
