### ISSUE TITLE
EEPROM crashes

### ISSUE THREAD

**Issue by rocio0504** [espressif/arduino-esp32#4015]
Hardware:
Board:							DOIT ESP32 DEVKIT V1
Core Installation version:			1.8.8
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:					921600
Computer OS:                                        Windows 10?

Description:

Hello, 

I am having problems with EEPROM. The data saved remains there even when the ESP32 resets or when power is removed but when I upload the same programm from another computer the data is lost.
Why is it happening?

**Comment by lbernstone** [comment]
Since April 2019, EEPROM data is stored in the nvs partition.  This should not be affected when you upload a new program, unless the partition structure changes.  Test by using esptool or espota to transfer just the application partition.
