### ISSUE TITLE
ESPRUINO QIO/DIO

### ISSUE THREAD

**Issue by Zibri** [espressif/arduino-esp32#4033]
Today I was trying to flash ESPRUINO on ESP32-WROOM-32.

I noticed that if I flash it using QIO the boot fails.
If I flash it with DIO it works.

Any Idea why?

My module is this:

![image](https://user-images.githubusercontent.com/855176/83201754-7d49e980-a146-11ea-967d-426ebf21771a.png)

**Comment by Zibri** [comment]
Note: also QOUT seems to work.
But if I flag SpiAutoSet, it selects QIO and QIO does not work.

**Comment by Zibri** [comment]
By the way on this board the right LED is blue and is connected to D2... in espruino ESP32 LED1 is not defined.

**Comment by lbernstone** [comment]
Putting jet fuel in the tank will not make your car fly.  If the board is manufactured with DIO flash ram, it is not capable of QIO operation.

**Comment by Zibri** [comment]
I just don't know.. because it works both ways apparently.
