### ISSUE TITLE
Macbook pro unable to connect to esp32 AP

### ISSUE THREAD

**Issue by MarkerDave** [espressif/arduino-esp32#4037]
Make your question, not a Statement, inclusive. Include all pertinent information:

What you are trying to do?
Connecting Macbook pro with an Esp32 that is setup as a Access Point.

Describe your system( Hardware, computer, O/S, core version, environment).
Macbook Pro 15inch 2019, macOS Catalina version 10.15.4

Describe what is failing.
It takes a while for the Macbook to find the Esp32 and when trying to connect it keeps asking for the password. on the Esp32 side the is no message about anything trying to connect with it.

Using an Android phone it is possible to connect with the Esp32 no problem.

Show the shortest possible code that will duplicate the error.

Show the EXACT error message(it doesn't work is not enough).
On MacOS The Wi-Fi network "yourAP" requires a WPA2 password.

### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.4
IDE name:						Arduino IDE and Platform.io
Flash Frequency:				       160Mhz
PSRAM enabled:                                    no
Upload Speed:				       115200
Computer OS:                                       macOS Catalina version 10.15.4

### Description:
Unable to connect an Macbook pro with an Esp32 in AP mode.

It takes a while for the Macbook to find the Esp32 and when trying to connect it keeps asking for the password. on the Esp32 side there is no message about anything trying to connect with it.

Using an Android phone it is possible to connect with the Esp32 no problem.

### Debug Messages:
none

**Comment by kele6ra** [comment]
I have had equal problem when I had SSID with extra symbols after the '\0' symbols, check your SSID. Try to read 'wifi_config.ap.ssid' as a char or hex buffer and look what you have there.
