### ISSUE TITLE
ESP32 does not wake from deep sleep

### ISSUE THREAD

**Issue by theDontKnowGuy** [espressif/arduino-esp32#4044]
Bought 20 WEMOS LOLIN32 with Bat adaptor and connected them to new fully charged lipo 3.7V batteries. 
Code is similar to all: do something short, then sleep for 30 minutes, then wake up and so on.
Also, I attached T3 as a touch button to the wake-up triggers on top of the timer.

the issue is: in ±5 of 8 cases, wake up is not triggered, sporadically, and across all 20 devices.
Both triggers (don't) work the same: Timer doesn't always wake up the board as planned, same for the touch button. Sometimes works, some other time doesn't.

Problem existed before I added the touch button option.

Obviously this is very painful cause my project is running already and a lot of money was paid.

The codebase is here: https://github.com/theDontKnowGuy/GreenPlanet

What am I missing ?

Thanks a bunch.

**Comment by chegewara** [comment]
T3 or T4?
https://github.com/theDontKnowGuy/GreenPlanet/blob/master/GreenPlanet/deep_sleep.ino#L62

If you turn off periph then how it can works(touch pins)
https://github.com/theDontKnowGuy/GreenPlanet/blob/master/GreenPlanet/deep_sleep.ino#L66
