### ISSUE TITLE
wifi: addba response cb: ap bss deleted

### ISSUE THREAD

**Issue by TryingToGITthis** [espressif/arduino-esp32#4052]
I'm getting this error when WiFi clients, I'm assuming, disconnect. Is it an issue? What does it mean? How do I turn it off?

**Comment by sebhuet** [comment]
I have the same firmware running on hundreds of ESP32 i also have this message on some chips (10%) not on others. I suspect chip/design issue but i would be happy to know this could be related with software.

**Comment by TryingToGITthis** [comment]
Interesting. I have noticed it is tied to certain boards even running the same code.

**Comment by sebhuet** [comment]
Need to be confirmed but it looks like connecting with a fixed ip instead of dhcp lowers the amount of fails. could you test this on your side ?

**Comment by TryingToGITthis** [comment]
What I found is that using a fixed IP does help a lot. However, I had to drop back to 1.11.2 to keep my code from having issues. DHCP client just dies in the latest versions and won't give out any new IPs.

**Comment by CelliesProjects** [comment]
I only heard about this problem from people using my apps. I could not reproduce it on any of my boards, but indeed a fixed IP solved the problem.

@TryingToGITthis 
>  However, I had to drop back to 1.11.2 to keep my code from having issues.

Drop back what? Unclear what you mean.

**Comment by TryingToGITthis** [comment]
Versions 1.12.X of arduino-esp32 cause issues. If I use version 1.11.2 it doesn't experience the problem.

**Comment by TryingToGITthis** [comment]
I'm am using ESP32-WROOM-32D.

**Comment by atanisoft** [comment]
@TryingToGITthis there is no such version of arduino-esp32. However, what you are showing is a platformio-espressif32 version.

**Comment by TryingToGITthis** [comment]
My bad, you are correct.

**Comment by natitomato** [comment]
Are you using reconnect()? or passing the ssid and password everytime you connect to WiFi?
If you've been using reconnect, try disconnecting first and then starting the WiFi again using WiFi.being(ssid, pwd)
This solved the issue for me (I'm using WROOM-32U).

**Comment by kevin4dhd** [comment]
> I'm am using ESP32-WROOM-32D.

Any solution for this model, I also have the same error in ESP32-WROOM-32D, my wifi disconnects after a few seconds
