### ISSUE TITLE
Is there a way to change flash speed via OTA?

### ISSUE THREAD

**Issue by Schaggo** [espressif/arduino-esp32#4062]
Hi, 
I am trying to increase the flash speed from 40MHz to 80MHz.  
Is there a way to do this via OTA similar to setCpuFrequencyMhz()?

Cheers and thanks for your time!

**Comment by dynek** [comment]
Hey,

Trying to do the opposite, lowering flash speed from 80 to 40 to see if it fixes some crashes I am currently having on one ESP32.

Seems like this guy also tried it without success https://esp32.com/viewtopic.php?t=8815

Any way to do it when flashing OTA?

Thank you
