### ISSUE TITLE
I2S ADC strange signals

### ISSUE THREAD

**Issue by marina936** [espressif/arduino-esp32#4083]
I am trying to read from ADC with I2S. I configure I2S frequency to 120 KHz, 16 bit and only channel right, like this:

    static const i2s_config_t i2s_config = {
    .mode = I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_ADC_BUILT_IN,
    .sample_rate = 120000,
    .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
    .channel_format = I2S_CHANNEL_FMT_ONLY_RIGHT,
    .communication_format = 0,
    .intr_alloc_flags = 0, // default interrupt priority
    .dma_buf_count = 3,
    .dma_buf_len = NUM_SAMPLES,
    .use_apll = true,  
    .fixed_mclk = 120000
    };

I add continuos square signals of 1KHz and amplitude 1V to the ADC.

This is what I receive reading ADC with I2S.

![transitorios_señal](https://user-images.githubusercontent.com/66781072/84480800-6b635d00-ac95-11ea-97da-dcfd73313445.png)

In the signals I receive I show some kind of peaks  (transitories) in the edge of the signals.

Can anyone explain why this happens? And how I can delete these peaks?

**Comment by lbernstone** [comment]
Not an arduino question.  Ask at [ESP-IDF](https://github.com/espressif/esp-idf/issues)
