### ISSUE TITLE
ESP32-S2 support for USB HID

### ISSUE THREAD

**Issue by HelloDB** [espressif/arduino-esp32#4108]
Does esp32-s2 support USB mouse and keyboard? Can you provide sample code

**Comment by lbernstone** [comment]
Yes, but you will need to be patient or use example code from IDF for now.  esp32-s2 is still in beta.

**Comment by me-no-dev** [comment]
working on it ... HID needs to be tied to IDF's HID lib.

**Comment by pefford** [comment]
Hi, I couldn't find any library to use ESP32 as an HID/MIDI...
Is there any solution? Any code example, so far?
Thanks in advance!

**Comment by chegewara** [comment]
There is one i know about, but it is not complete yet, especially in HID.
https://github.com/chegewara/EspTinyUSB

**Comment by chegewara** [comment]
And another i just found:
https://github.com/lathoub/Arduino-AppleMIDI-Library

**Comment by pefford** [comment]
Thanks @chegewara, though seems to me that these libr are intended for the new ESP32-S2?

**Comment by chegewara** [comment]
The first one, as described in readme, is for esp32 s2 and is using native USB.
Second one is using ethernet/wifi and can be used with old esp32 so i am guessing it will works with S2 too (its midi only).

**Comment by pefford** [comment]
Thanks @chegewara, i will manage an ESP32-S2 to test... i was initially expecting to use the "old" ESP32 as an HID, but seems not to be possible, except for using BLE...

**Comment by chegewara** [comment]
If you have some interesting project i may update my library to add support for more HID devices.

**Comment by chegewara** [comment]
@HelloDB i just added HID to my library:
https://github.com/chegewara/EspTinyUSB/tree/master/examples/hid

**Comment by pefford** [comment]
Hi @chegewara, is your library update then now valid for the "old" ESP32 to let it act as an HID when physically plugged into the USB slot of a PC (not pairing it over BLE) ?

**Comment by chegewara** [comment]
esp32-S1 will never have standalone USB support. Hardware is not capable of it. But you can add S2 to your project (cheap) or wait till S3 is available: `S1 + S2 + extras = S3`

**Comment by pefford** [comment]
Ahhh... Thanks for clarifying!

**Comment by Murilo-la** [comment]
Hello @chegewara im working in a project to read barcodes with hid scanner, can you help me with the code? Does the keyboard example works with the device or do i need to make changes? Thank you in advance

**Comment by chegewara** [comment]
Hi,
actually my library is no longer working with arduino-esp32 v2.0.0 or master branch. It is caused by conflict with hal library in arduino-esp32. Its because some tinyusb callbacks has to be called in library, but are used in hal code and there is conflict.
Sorry for that

**Comment by Murilo-la** [comment]
No problem, thank you for the reply

**Comment by chegewara** [comment]
@Murilo-la 
There are few older commits of arduino-esp32 you could still use with my library, but they are considered as not stable.

**Comment by Murilo-la** [comment]
@chegewara
My team have a solution using esp32 wroom 32u and a max3421 ic, i ll try to adapt it in the esp32 s2, and if it shows difficulties i ll stay with the 32u solution

**Comment by Angeliccare** [comment]
Just a fix to a link with the examples: https://github.com/chegewara/EspTinyUSB/blob/master/examples/device/hid/keyboard/keyboard.ino

**Comment by Pol-Moreno** [comment]
Hi @chegewara,
I'm starting at this world and I need some help.
I'm working too in a project to read barcodes with hid barcode scanner. Is it possible to do that with any library? 
Could you help me with the code I must upload to my ESP32-s2 for reading the codes sent by barcode scanner since the serial monitor from this one?

Thanks!

**Comment by vigyanabikshu1** [comment]
I can see USB HID device examples in esp-idf repository
