### ISSUE TITLE
ARM64 unable to install through board manager

### ISSUE THREAD

**Issue by ComputerLag** [espressif/arduino-esp32#4111]
### Hardware:
Board:						ESP32 Dev Module
Core Installation version:			1.04
IDE name:					Arduino IDE
Computer OS:                                 Debian Linux
Architecture:                                    aarch64 GNU/Linux
Kernel:                                             4.19.113-08528-g5803a1c7e9f9

### Description:
Unable to install esp32 through board manager. The following error message is displayed:
### Debug Messages:
```
Tool esptool_py is not available for your operating system.
```

**Comment by lbernstone** [comment]
ARM64 is not a supported platform in 1.0.4 (IDF 3.3).  The toolchain is compiled for ARM64 in the gcc8.2 versions, so this will likely be available in the next version.
