### ISSUE TITLE
ArduinoOTA is failing with W5500 Ethernet module

### ISSUE THREAD

**Issue by Miq1** [espressif/arduino-esp32#4122]
**### [Updated as I found a local solution worth a feature change]**

### Hardware:
Board:							ESP32 WROOM DevkitC V4
Core Installation version:			1.12.4
IDE name:						PlatformIO
Flash Frequency:					?
PSRAM enabled:                                    ?
Upload Speed:					n/a
Computer OS:                                   Windows 10

### Description:
I am trying to get ArduinoOTA.h working over Ethernet without success. I have a W5500 module connected to the ESP32 and successfully am using that to do several TCP and UDP communication with the ESP. 

I finally got there by changing a few lines in ArduinoOTA.h and ArduinoOTA.cpp:

``ArduinoOTA.h:4``
```
#include <Ethernet.h>
```
(instead of ``#include <WiFi.h>``)

``ArduinoOTA.h:84``
```
    EthernetUDP _udp_ota;
```
(instead of `` WiFiUDP _udp_ota;``)

``ArduinoOTA.cpp:5``
delete ``#include <WiFiUDP.h>``

``ArduinoOTA.cpp:119``
```
        // WiFi.macAddress(mac);
```
(comment out the line - losing the default host name feature!)

``ArduinoOTA.cpp:256``
```
    EthernetClient client;
```
(instead of ``WiFiClient client;``)

I would suggest integrating a similar modification into the core ArduinoOTA to enable Ethernet OTA for everyone needing it.

**Comment by Miq1** [comment]
I am doubting someone is interested at all, but anyway...

There seems to be another issue with ArduinoOTA/W5500. After having run the ESP32 for a day or so, espota.py is unable to trigger an OTA process on the ESP32 anymore. Only a reset of the ESP32 will solve the issue temporarily.
Other TCP and UDP connections are working regardless, so this is confined to the ArduinoOTA communication.

**Comment by TheNetStriker** [comment]
@Miq1 I've just tested your code changes with the Adafruit Ethernet FeatherWing and it works perfectly. It would be nice to have this feature in the official library.

**Comment by Miq1** [comment]
Thanks for the confirmation. For all that it is worth I created a PR for it: [#4298](https://github.com/espressif/arduino-esp32/pull/4298)

**Comment by Miq1** [comment]
No one is doing anything about this, so I am giving it up. 😠

**Comment by BobLynas** [comment]
HI Miq1, I just came across this post, and I am very interested in this solution, to be honest I didn't think ESP32/W5500/OTE was possible, but now i'm going to give it a go, thanks

**Comment by Miq1** [comment]
Hi Bob, 

the patch is really simple (as is described in the first post of this issue). You also may look at the commit I mode: [in my forked repository](https://github.com/Miq1/arduino-esp32/commit/feff52b86eb71df0668aefaebc67ab02efd414d3). But please note that the master repository had quite some commits since. Plus: I left in the ``mDNS`` stuff, knowing it will not work via EThernet right away. Using the IP address of your ESP will do.
