### ISSUE TITLE
ESPmDNS.h 'usage:' comments talk about adding am update method to the loop, but there is no update method (and I assume one is not needed).

### ISSUE THREAD

**Issue by rhoggarth** [espressif/arduino-esp32#4124]
### Hardware:
Board:							Wemos Lolin32
IDE name:						Arduino IDE
Computer OS:                                        Ubuntu

### Description:
I don't have a problem - code works fine.   I'm using the ESPmDNS library.  The comments on line 19 of ESPmDNS.h reference a method 'update' (which I remember was present in the 8266 version of the library).  There is no update() method in the ESPmDNS library so the comment which is there to help users 'use' the library is misleading.

**Comment by lbernstone** [comment]
> Make your question, not a Statement, inclusive. Include all pertinent information:
> What you are trying to do?
> Describe what is failing.

**Comment by rhoggarth** [comment]
@lbernstone assuming it's just a comment change, you would know better than I whether the update() method is no longer needed or is an omission in the library.

**Comment by atanisoft** [comment]
@rhoggarth the update method is not needed and that comment in the code should be cleaned up.
