### ISSUE TITLE
BLE esp32 sending data

### ISSUE THREAD

**Issue by baamiis** [espressif/arduino-esp32#4127]
### Hardware:
Board:							ESP32 Dev Module?
Core Installation version:			1.4
IDE name:						Arduino IDE
Flash Frequency:					?40Mhz?
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Windows 10

### Description:
this is used from the idf examples the program hangs waiting for retrieve the service attributes indefinitly so I turned debug on and the output from debug is included: 

Can someone please help me resolve this the code bellow, thank yoy :)

###the code:
#define TARGET_SERVICE  "6E400001-B5A3-F393-E0A9-E50E24DCCA9E" // UART service UUID
#define TARGERT_CHARAC  "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"
class MyAdvertisedDeviceCallbacks: public BLEAdvertisedDeviceCallbacks {
    void onResult(BLEAdvertisedDevice advertisedDevice) {
      
      Serial.printf("Advertised Device: %s \n", advertisedDevice.toString().c_str());
      if(String(advertisedDevice.toString().c_str()).indexOf("dd:5b:80:6a:c9:06") >= 0) {
        Serial.println(" - FOUND Address:");
        
        pServerAddress = new BLEAddress("dd:5b:80:6a:c9:06");
        MicrobitAlive = true;
 
      }

    }
};

void setup() {
  Serial.begin(115200);
  Serial.println("Scanning...");

  BLEDevice::init("");
  pBLEScan = BLEDevice::getScan(); //create new scan
  pBLEScan->setAdvertisedDeviceCallbacks(new MyAdvertisedDeviceCallbacks());
  pBLEScan->setActiveScan(true); //active scan uses more power, but get results faster
  pBLEScan->setInterval(100);
  pBLEScan->setWindow(99);  // less or equal setInterval value
}

void loop() {
  if(MicrobitAlive == true) {
        Serial.print("Forming a connection to ");
        BLEClient*  pClient  = BLEDevice::createClient();
        pClient->connect(*pServerAddress);
        Serial.println(" - Connected to server");
        // Obtain a reference to the service we are after in the remote BLE server.
        BLERemoteService* pRemoteService = pClient->getService(TARGET_SERVICE);
        if (pRemoteService == nullptr) {
          Serial.print("Failed to find our service UUID: ");
          Serial.println(TARGET_SERVICE);
        }
        Serial.println(" - Found our service");
        // Obtain a reference to the characteristic in the service of the remote BLE server.
        pRemoteCharacteristic = pRemoteService->getCharacteristic(TARGERT_CHARAC);
        if (pRemoteCharacteristic == nullptr) {
          Serial.print("Failed to find our characteristic UUID: ");
          Serial.println(TARGERT_CHARAC);
        }
        MicrobitAlive = false;
  }
  else {
      // put your main code here, to run repeatedly:
      BLEScanResults foundDevices = pBLEScan->start(scanTime, false);
      Serial.print("Devices found: ");
      Serial.println(foundDevices.getCount());
      Serial.println("Scan done!");
      pBLEScan->clearResults();   // delete results fromBLEScan buffer to release memory
      delay(20000);
  }
}

###the debug output:
ets Jun  8 2016 00:22:57
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
Scanning...
[D][BLEAdvertisedDevice.cpp:452] setRSSI(): - setRSSI(): rssi: -66
[D][BLEAdvertisedDevice.cpp:281] parseAdvertisement(): Type: 0x01 (), length: 1, data: 06
[D][BLEAdvertisedDevice.cpp:281] parseAdvertisement(): Type: 0x09 (), length: 21, data: 424243206d6963726f3a626974205b7a6f7075765d
[D][BLEAdvertisedDevice.cpp:441] setName(): - setName(): name: BBC micro:bit [zopuv]
Advertised Device: Name: BBC micro:bit [zopuv], Address: dd:5b:80:6a:c9:06 
 - FOUND Address:
[D][BLEAdvertisedDevice.cpp:452] setRSSI(): - setRSSI(): rssi: -89
[D][BLEAdvertisedDevice.cpp:281] parseAdvertisement(): Type: 0xff (), length: 29, data: 0600010920020fb57abdbb2d57134afca25913974e4a0e37212c90e634
[D][BLEAdvertisedDevice.cpp:429] setManufacturerData(): - manufacturer data: 0600010920020fb57abdbb2d57134afca25913974e4a0e37212c90e634
Advertised Device: Name: , Address: 2a:5a:db:2e:6f:f5, manufacturer data: 0600010920020fb57abdbb2d57134afca25913974e4a0e37212c90e634 
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring dd:5b:80:6a:c9:06, already seen it.
[D][BLEScan.cpp:97] handleGAPEvent(): Ignoring 2a:5a:db:2e:6f:f5, already seen it.
[W][BLEScan.cpp:69] handleGAPEvent(): ESP_GAP_SEARCH_INQ_CMPL_EVT
Devices found: 2
Scan done!
Forming a connection to [I][BLEDevice.cpp:614] addPeerDevice(): add conn_id: 0, GATT role: client
[D][BLEDevice.cpp:148] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEClient.cpp:158] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEDevice.cpp:148] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEClient.cpp:158] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
 - Connected to server
[I][BLEDevice.cpp:625] removePeerDevice(): remove: 0, GATT role client
[E][BLEUUID.cpp:116] BLEUUID(): ERROR: UUID value not 2, 4, 16 or 36 bytes
[D][BLEDevice.cpp:148] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEDevice.cpp:148] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown

**Comment by chegewara** [comment]
2 problems:
1) `[I][BLEDevice.cpp:625] removePeerDevice(): remove: 0, GATT role client` <--- peer device is disconnected here
2) `[E][BLEUUID.cpp:116] BLEUUID(): ERROR: UUID value not 2, 4, 16 or 36 bytes`

**Comment by baamiis** [comment]
Any idea as to why apart from the disconnection ??

**Comment by chegewara** [comment]
No, no idea. There is not enough info.

**Comment by baamiis** [comment]
I don’t understand What more info you need :)
You have the code and you have it’s output.

**Comment by chegewara** [comment]
Its very simple, neither code nor logs explain disconnection reason. Or i am just dumb, that could explain.

**Comment by h2zero** [comment]
> this is used from the idf examples the program hangs waiting for retrieve the service attributes indefinitly so I turned debug on and the output from debug is included

Are you using the esp32-arduino master branch? If so checkout v1.0.4 instead and try it. Master is using a bugged BLE controller.

**Comment by baamiis** [comment]
You are not dump. The device is not disconnecting. And I just cannot see it disconnecting. Very strange :)

**Comment by baamiis** [comment]
Thanks for your help h2zero. Much appreciated

**Comment by baamiis** [comment]
just checked the version. I am using version v1.0.4. If any one has a solution to this please help thanks.

**Comment by buxtronix** [comment]
You should check the return value of connect(), it might be false (ie failed to connect). And increase debugging level to Verbose.
