### ISSUE TITLE
PC: 0x40170620: circular_queue ::push(unsigned int&&)

### ISSUE THREAD

**Issue by georgepopovici** [espressif/arduino-esp32#4148]
################
Backtrace:
.Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Core 1 register dump:
PC      : 0x40170620  PS      : 0x00060034  A0      : 0x8008135c  A1      : 0x3ffbe780  
A2      : 0x3ffc1288  A3      : 0x00000001  A4      : 0x0a417eb9  A5      : 0x3ffbe790  
A6      : 0x3ffbe7d8  A7      : 0x00000001  A8      : 0x8008125a  A9      : 0x00000000  
A10     : 0x3ffafdc8  A11     : 0x3ffbe78c  A12     : 0x8008ad87  A13     : 0x3ffbe760  
A14     : 0x00000008  A15     : 0x00000001  SAR     : 0x00000001  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
Core 1 was running in ISR context:
EPC1    : 0x40087435  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40170620

Backtrace: 0x40170620:0x3ffbe780 0x40081359:0x3ffbe7b0 0x40085185:0x3ffbe7d0 0x40087432:0x3ffba190 0x40083583:0x3ffba1b0 0x40089591:0x3ffba1d0

################
Decoded backtrace:

PC: 0x40170620: circular_queue ::push(unsigned int&&) at C:\Users\gpopovici\Documents\Arduino\libraries\EspSoftwareSerial\src\circular_queue/circular_queue.h line 269
EXCVADDR: 0x00000000

Decoding stack results
0x40170620: circular_queue ::push(unsigned int&&) at C:\Users\gpopovici\Documents\Arduino\libraries\EspSoftwareSerial\src\circular_queue/circular_queue.h line 269
0x40081359: __onPinInterrupt at C:\Users\gpopovici\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32\esp32-hal-gpio.c line 232
0x40087432: spi_flash_op_block_func at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/spi_flash/cache_utils.c line 81
0x40083583: ipc_task at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/ipc.c line 62
0x40089591: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c line 143

#################
Serial output:

Going to sleep now
ets Jun  8 2016 00:22:57

rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac
Boot number: 7
Wakeup caused by timer
Setup ESP32 to sleep for every 15 Seconds
Simple TinyGPS library v. 13
by Mikal Hart

Attempting to connect to SSID: priv1
.Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Core 1 register dump:
PC      : 0x40170620  PS      : 0x00060034  A0      : 0x8008135c  A1      : 0x3ffbe780  
A2      : 0x3ffc1288  A3      : 0x00000001  A4      : 0x0a4b349d  A5      : 0x00000000  
A6      : 0x3ffc1a50  A7      : 0xffffffff  A8      : 0x8008125a  A9      : 0x00000000  
A10     : 0x3ffafdc8  A11     : 0x3ffbe78c  A12     : 0x3ffba264  A13     : 0x0000abab  
A14     : 0x3ffc384c  A15     : 0x3ffba264  SAR     : 0x00000001  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
Core 1 was running in ISR context:
EPC1    : 0x40087440  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40170620

Backtrace: 0x40170620:0x3ffbe780 0x40081359:0x3ffbe7b0 0x40085185:0x3ffbe7d0 0x4008743d:0x3ffba190 0x40083583:0x3ffba1b0 0x40089591:0x3ffba1d0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac
Boot number: 1
Wakeup was not caused by deep sleep: 0
Setup ESP32 to sleep for every 15 Seconds
Simple TinyGPS library v. 13
by Mikal Hart

Attempting to connect to SSID: priv1
.
Connected.
IP address: 
192.168.0.226
LAT=44.418774 LON=26.043592 SAT=6 PREC=739 CHARS=539 SENTENCES=2 CSUM ERR=0
Humidity: 40.70%  Temperature: 26.90°C 80.42°F  Heat index: 26.82°C 80.28°F
Channel update successful.
H_thresh: 50
Going to sleep now

####################
### Hardware:
Board:							Lolin32 v1.0.0
Core Installation version:			1.0.0
IDE name:						Arduino IDE 1.8.13
Flash Frequency:					80Mhz
PSRAM enabled:                                    ?
Upload Speed:					115200
Computer OS:                                        Windows 10
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Auto-detected Flash size: 4MB

### Description:
Hello,

I am getting these core dumps and I would like to fix them.
The code is basically reading temperature / humidity / gps coordinates / upload data to ThingsSpeak / go to deepsleep for 15 seconds and repeat. Sometimes it reproduces after 2 repeats, sometimes after 5 or 10 so there is no pattern.

The board eventually does what I need but I'd like to fix this core dump if possible.

Thanks for the help!
George

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include "ThingSpeak.h"
#include "secrets.h"
#include <WiFi.h>
#include <SoftwareSerial.h>
#include <TinyGPS.h>
#include "DHT.h"
#include "ESP32_MailClient.h"

#define DHTPIN 32
#define DHTTYPE DHT22
#define emailSenderAccount    "XXX"    
#define emailSenderPassword   "XXX"
#define emailRecipient        "XXX"
#define smtpServer            "smtp.gmail.com"
#define smtpServerPort        465
#define emailSubject          "Message from caravan"

#define uS_TO_S_FACTOR 1000000  /* Conversion factor for micro seconds to seconds */
#define TIME_TO_SLEEP  15        /* Time ESP32 will go to sleep (in seconds) */

RTC_DATA_ATTR int bootCount = 0;

void print_wakeup_reason(){
  esp_sleep_wakeup_cause_t wakeup_reason;

  wakeup_reason = esp_sleep_get_wakeup_cause();

  switch(wakeup_reason)
  {
    case ESP_SLEEP_WAKEUP_EXT0 : Serial.println("Wakeup caused by external signal using RTC_IO"); break;
    case ESP_SLEEP_WAKEUP_EXT1 : Serial.println("Wakeup caused by external signal using RTC_CNTL"); break;
    case ESP_SLEEP_WAKEUP_TIMER : Serial.println("Wakeup caused by timer"); break;
    case ESP_SLEEP_WAKEUP_TOUCHPAD : Serial.println("Wakeup caused by touchpad"); break;
    case ESP_SLEEP_WAKEUP_ULP : Serial.println("Wakeup caused by ULP program"); break;
    default : Serial.printf("Wakeup was not caused by deep sleep: %d\n",wakeup_reason); break;
  }
}

/* This sample code demonstrates the normal use of a TinyGPS object.
   It requires the use of SoftwareSerial, and assumes that you have a
   4800-baud serial GPS device hooked up on pins 4(rx) and 3(tx).
   GPS TX - LOLIN port 33
   GPS RX - LOLIN port 34
*/

DHT dht(DHTPIN, DHTTYPE);
TinyGPS gps;
SoftwareSerial ss(33, 34);
SMTPData smtpData;
WiFiClient  client;

char ssid[] = SECRET_SSID;   // your network SSID (name) 
char pass[] = SECRET_PASS;   // your network password
int keyIndex = 0;            // your network key Index number (needed only for WEP)


unsigned long myChannelNumber = SECRET_CH_ID;
const char * myWriteAPIKey = SECRET_WRITE_APIKEY;
const char * myReadAPIKey = SECRET_READ_APIKEY;

// Initialize our values
String myStatus = "";

void sendCallback(SendStatus info);

void setup() {
  Serial.begin(115200);  //Initialize serial
  delay(500);

  //Increment boot number and print it every reboot
  ++bootCount;
  Serial.println("Boot number: " + String(bootCount));

  //Print the wakeup reason for ESP32
  print_wakeup_reason();

  /*
  First we configure the wake up source
  We set our ESP32 to wake up every 5 seconds
  */
  esp_sleep_enable_timer_wakeup(TIME_TO_SLEEP * uS_TO_S_FACTOR);
  Serial.println("Setup ESP32 to sleep for every " + String(TIME_TO_SLEEP) +
  " Seconds");


  WiFi.mode(WIFI_STA);   
  ThingSpeak.begin(client);  // Initialize ThingSpeak
  ss.begin(9600);
  dht.begin();
  
  Serial.print("Simple TinyGPS library v. "); Serial.println(TinyGPS::library_version());
  Serial.println("by Mikal Hart");
  Serial.println();

  int statusCode = 0;
  // Connect or reconnect to WiFi
  if(WiFi.status() != WL_CONNECTED){
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(SECRET_SSID);
    while(WiFi.status() != WL_CONNECTED){
      WiFi.begin(ssid, pass);  // Connect to WPA/WPA2 network. Change this line if using open or WEP network
      Serial.print(".");
      delay(5000);     
    } 
    Serial.println("\nConnected.");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
  }

  // Get GPS data
  bool newData = false;
  unsigned long chars;
  unsigned short sentences, failed;

  // For one second we parse GPS data and report some key values
  for (unsigned long start = millis(); millis() - start < 1000;)
  {
    while (ss.available())
    {
      char c = ss.read();
      // Serial.write(c); // uncomment this line if you want to see the GPS data flowing
      if (gps.encode(c)) // Did a new valid sentence come in?
        newData = true;
    }
  }

  if (newData)
  {
    float flat, flon;
    unsigned long age;
    gps.f_get_position(&flat, &flon, &age);
    Serial.print("LAT=");
    Serial.print(flat == TinyGPS::GPS_INVALID_F_ANGLE ? 0.0 : flat, 6);
    Serial.print(" LON=");
    Serial.print(flon == TinyGPS::GPS_INVALID_F_ANGLE ? 0.0 : flon, 6);
    Serial.print(" SAT=");
    Serial.print(gps.satellites() == TinyGPS::GPS_INVALID_SATELLITES ? 0 : gps.satellites());
    Serial.print(" PREC=");
    Serial.print(gps.hdop() == TinyGPS::GPS_INVALID_HDOP ? 0 : gps.hdop());
    ThingSpeak.setField(3, flat);
    ThingSpeak.setLatitude(flat);
    ThingSpeak.setField(4, flon);
    ThingSpeak.setLongitude(flon);
  }
  
  gps.stats(&chars, &sentences, &failed);
  Serial.print(" CHARS=");
  Serial.print(chars);
  Serial.print(" SENTENCES=");
  Serial.print(sentences);
  Serial.print(" CSUM ERR=");
  Serial.println(failed);
  if (chars == 0)
    Serial.println("** No characters received from GPS: check wiring **");

  //Get DHT22 data
  // Reading temperature or humidity takes about 250 milliseconds!
  // Sensor readings may also be up to 2 seconds 'old' (its a very slow sensor)
  float h = dht.readHumidity();
  // Read temperature as Celsius (the default)
  float t = dht.readTemperature();
  // Read temperature as Fahrenheit (isFahrenheit = true)
  float f = dht.readTemperature(true);

  // Check if any reads failed and exit early (to try again).
  if (isnan(h) || isnan(t) || isnan(f)) {
    Serial.println(F("Failed to read from DHT sensor!"));
    return;
  }

  // Compute heat index in Fahrenheit (the default)
  float hif = dht.computeHeatIndex(f, h);
  // Compute heat index in Celsius (isFahreheit = false)
  float hic = dht.computeHeatIndex(t, h, false);

  Serial.print(F("Humidity: "));
  Serial.print(h);
  Serial.print(F("%  Temperature: "));
  Serial.print(t);
  Serial.print(F("°C "));
  Serial.print(f);
  Serial.print(F("°F  Heat index: "));
  Serial.print(hic);
  Serial.print(F("°C "));
  Serial.print(hif);
  Serial.println(F("°F"));

  // set the fields with the values
  // 1 is humidity
  // 2 is temperature
  // 3 and 4 are latitude and longitude
  
  ThingSpeak.setField(1, h);
  ThingSpeak.setField(2, t);
  ThingSpeak.setField(7, bootCount);

  ThingSpeak.setStatus(myStatus);
  
  // write to the ThingSpeak channel
  int x = ThingSpeak.writeFields(myChannelNumber, myWriteAPIKey);
  if(x == 200){
    Serial.println("Channel update successful.");
  }
  else{
    Serial.println("Problem updating channel. HTTP error code " + String(x));
  }
  long h_thres = ThingSpeak.readLongField(myChannelNumber, 8, myReadAPIKey);  

   // Check the status of the read operation to see if it was successful
  statusCode = ThingSpeak.getLastReadStatus();
  if(statusCode == 200){
    Serial.println("H_thresh: " + String(h_thres));
    if(h > h_thres){
      //send email
      smtpData.setLogin(smtpServer, smtpServerPort, emailSenderAccount, emailSenderPassword);
      smtpData.setSender("ESP32", emailSenderAccount);
      smtpData.setPriority("High");
      smtpData.setSubject(emailSubject);
      smtpData.setMessage("Humidity is: "+ String(h) + " - Expected < " + String(h_thres), false);
      smtpData.addRecipient(emailRecipient);
      smtpData.setSendCallback(sendCallback);
      if (!MailClient.sendMail(smtpData))
        Serial.println("Error sending Email, " + MailClient.smtpErrorReason());
      smtpData.empty();
    }
      
  }
  else{
    Serial.println("Problem reading channel. HTTP error code " + String(statusCode)); 
  }
  
  Serial.println("Going to sleep now");
  delay(1000);
  Serial.flush(); 
  esp_deep_sleep_start();
  Serial.println("This will never be printed");
  //delay(20000); // Wait 20 seconds to update the channel again

}

void loop() {
  
}

void sendCallback(SendStatus msg) {
  // Print the current status
  Serial.println(msg.info());

  // Do something when complete
  if (msg.success()) {
    Serial.println("----------------");
  }
}
```

**Comment by lbernstone** [comment]
You are trying to access something in an ISR that is not in IRAM.  This is often something trying to access flash.  You need to figure out what component is causing the issue.  Using SoftwareSerial is not recommended on esp32.

**Comment by georgepopovici** [comment]
Thanks @lbernstone ! Would you be able to provide more details on how to figure out what component is causing the issue? Maybe some debug code that I could add or an approach I could follow to narrow this down?

Regards,
George

**Comment by georgepopovici** [comment]
An update from my side:

1. Removed the software serial part and dependent code - eps32 board does not crash anymore
2. Added hardware serial replacement for the above:
#define RXD2 16
#define TXD2 17
 Serial2.begin(9600, SERIAL_8N1, RXD2, TXD2);
and used this serial for getting GPS data
This worked and there's been no crashes.

Thanks,
George
