### ISSUE TITLE
Board request TTGO-T-DISPLAY

### ISSUE THREAD

**Issue by DavidThijs** [espressif/arduino-esp32#4150]
### Hardware:
Board:							ESP32 TTGO-T-DISPLAY
Core Installation version:			1.0.4
IDE name:						Platform.io
Flash Frequency:					40Mhz
PSRAM enabled:                                      no
Upload Speed:				        921600
Computer OS:                                         Windows 10

### Description:

Please add support for TTGO-T-Display board:
https://github.com/Xinyuan-LilyGO/TTGO-T-Display

Chipset
ESPRESSIF-ESP32 240MHz Xtensa® single-/dual-core 32-bit LX6 microprocessor
FLASH
QSPI flash 4MB
SRAM 
520 kB SRAM
USB to TTL
CP2104
Display
IPS ST7789V 1.14 Inch

**Comment by atanisoft** [comment]
@DavidThijs from the referenced repository they recommend using the "ESP32 Dev Module" with all of the defaults used as-is.
