### ISSUE TITLE
HTTPS POST <body> is lost during redirect ESP2866/Arduino

### ISSUE THREAD

**Issue by GamerClassN7** [espressif/arduino-esp32#4163]
Hi,
i am working on custome SimpleHome (SmartHome Server) project i run in to the issue. If i want to use HTTPs, ESP lose request payload i realy try to do every possible alternative and nothing worked can someone sugest what i am dooing wrong ? i am running code on ESP2866 custome borad based on NodeMCU. Thanks for any answer.

Server response
Make your question, not a Statement, inclusive. Include all pertinent information:

### Description:
ESP is not able to send POST body on redirect, but if i test API with Insomnia of Curl everithing works fine.
### Server Response:
![image](https://user-images.githubusercontent.com/22167469/87278314-6851cb80-c4e4-11ea-9fe5-c84d1809976c.png)

**Comment by lbernstone** [comment]
esp32 != esp8266
https://github.com/esp8266/Arduino/issues

**Comment by GamerClassN7** [comment]
@lbernstone Thanks!
