### ISSUE TITLE
can't get "xtensa-esp32-elf"file

### ISSUE THREAD

**Issue by ultimatemasashi** [espressif/arduino-esp32#419]
I did use "get.exe"file.     Can't get "xtensa-esp32-elf"file.
It appeared  "UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 9: ordinal not in range(128)"for dos prompt.

Is python code Probrem?

**Comment by ultimatemasashi** [comment]
If file name is Japanese can't use get.exe

**Comment by Cpt-Hook** [comment]
How to fix this problem?

**Comment by me-no-dev** [comment]
@Cpt-Hook ? what problem?
