### ISSUE TITLE
HTTPClient.h not compatible with DELETE method?

### ISSUE THREAD

**Issue by LuHoang** [espressif/arduino-esp32#4203]
### Hardware:
Board:							ESP32 Dev Module
IDE name:							Arduino IDE

### Description:

I was using the HTTPclient library for the Arduino IDE. I looked through the source codes, examples, etc. and found no mention of the DELETE method. I only have seen the GET, POST, and PUT. Is there a limitation that currently limited it? thanks.

**Comment by Jeroen88** [comment]
You are right, DELETE is not there. You could do a sendRequest("DELETE") though I think.Or take a look at PR #3848.

**Comment by jshep321** [comment]
Still needed.  Reopen!

**Comment by jasza2** [comment]
still needed , reopen
