### ISSUE TITLE
Hardwareserial flush TX only

### ISSUE THREAD

**Issue by bertmelis** [espressif/arduino-esp32#4204]
https://github.com/espressif/arduino-esp32/blob/4d98cea085d619bed7026b37071bd8402a485d95/cores/esp32/esp32-hal-uart.c#L362

flush TX only should only flush TX. 

This false should be true.

**Comment by bertmelis** [comment]
#4263

**Comment by bertmelis** [comment]
Please solve this one. It's a small mistake with breaking consequences.

It'd be a shame if this slips into a release.

**Comment by Miq1** [comment]
@bertmelis CI has been fixed an hour ago, so you may close and reopen your PR to pass.

**Comment by bertmelis** [comment]
Merged master branch into the PR. CI passed now.

Could someone please look into this? This error is so obvious but has breaking consequences.
