### ISSUE TITLE
ESP32 SOLO 1 problems with Arduino IDE

### ISSUE THREAD

**Issue by aledoors** [espressif/arduino-esp32#4233]
Hi all
I carry out the step-by-step procedure to be able to use my ESP32 SOLO 1 on Arduino IDE, but after compiling and uploading my program to the microcontroller I have the error that my ES32 has a single core and I don't know where I can change its configuration to not have this problem. Using ESP IDF I execute the instruction "idf.py menuconfig" and I can select to use one core, but on Arduino IDE I can't do it.
Thanks in advance.

**Comment by bfaliszek** [comment]
try: https://github.com/lbernstone/arduino-esp32-solo

**Comment by bfaliszek** [comment]
The problem returned with the Arduino core for the ESP32 - 1.0.5

**Comment by sixtyfive** [comment]
It seems #5183 is the official place for this now.
