### ISSUE TITLE
   WiFi.begin(ssid, password);  not working

### ISSUE THREAD

**Issue by dinurwahyu** [espressif/arduino-esp32#4241]
### Description:
i try to connect esp01 to internet but its not working 

### Sketch:  

//Change the code below by your sketch
#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiServer.h>
#include <WiFiUdp.h>

#include <SerialESP8266wifi.h>

//#include <ESP8266WiFi.h>        // Include the Wi-Fi library

const char* ssid     = "waipai";         // The SSID (name) of the Wi-Fi network you want to connect to
const char* password = "dindin46";     // The password of the Wi-Fi network

void setup() {
  Serial.begin(115200);         // Start the Serial communication to send messages to the computer
  delay(10);
  Serial.println('\n');
  
  WiFi.begin(ssid, password);             // Connect to the network
  Serial.print("Connecting to ");
  Serial.print(ssid); Serial.println(" ...");

  int i = 0;
  while (WiFi.status() != WL_CONNECTED) { // Wait for the Wi-Fi to connect
    delay(1000);
    Serial.print(++i); Serial.print(' ');
  }

  Serial.println('\n');
  Serial.println("Connection established!");  
  Serial.print("IP address:\t");
  Serial.println(WiFi.localIP());         // Send the IP address of the ESP8266 to the computer
}

void loop() { }

**Comment by lbernstone** [comment]
esp32 != esp8266
https://github.com/esp8266/Arduino
