### ISSUE TITLE
can we use pulse counting module(PCNT) with deep sleep? 

### ISSUE THREAD

**Issue by mightChamp** [espressif/arduino-esp32#4267]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			16/jun/2020
IDE name:							Arduino IDE
Flash Frequency:					 80Mhz
PSRAM enabled:                                          no
Upload Speed:						115200
Computer OS:                                            Windows 10

### Description:
can we use pulse counting module(PCNT) with deep sleep?

**Comment by lbernstone** [comment]
No.  You could count pulses using the ULP (in assembly), but PCNT is part of the main processor.

**Comment by mightChamp** [comment]
> No. You could count pulses using the ULP (in assembly), but PCNT is part of the main processor.

Thanks
