### ISSUE TITLE
Using BLE for very short distance

### ISSUE THREAD

**Issue by ivj94** [espressif/arduino-esp32#4269]
Hi,

I just bought a NodeMCU-ESP32 board. I created a BLE Server on the board in Arduino IDE. I'd like to build a Check In-Check Out system where people can use their smartphone to connect to ESP32 and check in or check out. It works fine but I want to decrease the strength of the signal because currently anybody can connect to it within ~10 meters. I want to reduce the distance to only a few centimeters. I changed ::setPower but it seems to me that the strength of the signal doesn't change at all no matter what value I set.
Here is the part of the code:

```
BLEDevice::init("MyESP32");
  BLEDevice::setPower(ESP_PWR_LVL_N14);
  //BLEDevice::setPower(ESP_PWR_LVL_P7);

  pServer = BLEDevice::createServer();
  pServer->setCallbacks(new MyServerCallbacks());

  BLEService *pService = pServer->createService(SERVICE_UUID);

 pCharacteristic = pService->createCharacteristic(
                                         CHARACTERISTIC_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_WRITE
                                       );

  pCharacteristic->setCallbacks(new MyCallbacks());

  pCharacteristic->setValue("Hello World");
  pService->start();
```
Is there any way to reduce the distance between devices to a few centimeters only?

**Comment by chegewara** [comment]
Few options:
- filter by RSSI value,
- use `esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, (esp_power_level_t) txPower); ` to set advertising tx power, but here you are limited to -12dbm
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/controller_vhci.html#_CPPv417esp_power_level_t
