### ISSUE TITLE
boot crash: /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!

### ISSUE THREAD

**Issue by shreyaskv** [espressif/arduino-esp32#4274]
I am using ESP32 TTGO T Call to send data to firebase.

My code compiles fine, but crashes with the following output:

OK
 OK
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40088599 on core 1

Backtrace: 0x4008c118:0x3ffb1920 0x4008c349:0x3ffb1940 0x40088599:0x3ffb1960 0x4011c646:0x3ffb19a0 0x4011c846:0x3ffb19c0 0x4010e35c:0x3ffb19e0 0x4010e3c5:0x3ffb1a00 0x4010b562:0x3ffb1a20 0x4010a3ec:0x3ffb1a40 0x4010dbe0:0x3ffb1a80 0x400d5a30:0x3ffb1aa0 0x400d57ae:0x3ffb1d10 0x400d58a9:0x3ffb1d40 0x40120729:0x3ffb1d60 0x400d5119:0x3ffb1d80 0x400d51a9:0x3ffb1db0 0x400d5281:0x3ffb1df0 0x400d34da:0x3ffb1e10 0x400d364d:0x3ffb1ef0 0x400d36d7:0x3ffb1f50 0x400d2c32:0x3ffb1f80 0x400d765d:0x3ffb1fb0 0x400888ad:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac

Here is the current code:

int int_val = 100;

// Your GPRS credentials (leave empty, if not needed)
const char apn[]      = "airtelgprs.com"; // APN (example: internet.vodafone.pt) use https://wiki.apnchanger.org
const char gprsUser[] = ""; // GPRS User
const char gprsPass[] = ""; // GPRS Password

// SIM card PIN (leave empty, if not defined)
const char simPIN[]   = "1234"; 

#define FIREBASE_HOST "ibeacon-e6ce1.firebaseio.com"
#define FIREBASE_AUTH "7qncFEWjZDT4NbRqNoTnh5XyEa3HyPabCJMfwOMK"

// Server details
// The server variable can be just a domain name or it can have a subdomain. It depends on the service you are using
//const char server[] = "example.com"; // domain name: example.com, maker.ifttt.com, etc
//const char resource[] = "/post-data.php";         // resource path, for example: /post-data.php
//const int  port = 80;                             // server port number

// Keep this API Key value to be compatible with the PHP code provided in the project page. 
// If you change the apiKeyValue value, the PHP file /post-data.php also needs to have the same key 
//String apiKeyValue = "tPmAT5Ab3j7F9";

// TTGO T-Call pins
#define MODEM_RST            5
#define MODEM_PWKEY          4
#define MODEM_POWER_ON       23
#define MODEM_TX             27
#define MODEM_RX             26
#define I2C_SDA              21
#define I2C_SCL              22
//// BME280 pins
//#define I2C_SDA_2            18
//#define I2C_SCL_2            19

// Set serial for debug console (to Serial Monitor, default speed 115200)
#define SerialMon Serial
// Set serial for AT commands (to SIM800 module)
#define SerialAT Serial1

// Configure TinyGSM library
#define TINY_GSM_MODEM_SIM800      // Modem is SIM800
#define TINY_GSM_RX_BUFFER   1024  // Set RX buffer to 1Kb

// Define the serial console for debug prints, if needed
#define DUMP_AT_COMMANDS

#include <Wire.h>
#include <TinyGsmClient.h>

#ifdef DUMP_AT_COMMANDS
  #include <StreamDebugger.h>
  StreamDebugger debugger(SerialAT, SerialMon);
  TinyGsm modem(debugger);
#else
  TinyGsm modem(SerialAT);
#endif

//#include <Adafruit_Sensor.h>
//#include <Adafruit_BME280.h>

// I2C for SIM800 (to keep it running when powered from battery)
//TwoWire I2CPower = TwoWire(0);

// I2C for BME280 sensor
//TwoWire I2CBME = TwoWire(1);
//Adafruit_BME280 bme; 

// TinyGSM Client for Internet connection
TinyGsmClient client(modem);

#define uS_TO_S_FACTOR 1000000     /* Conversion factor for micro seconds to seconds */
#define TIME_TO_SLEEP  3600        /* Time ESP32 will go to sleep (in seconds) 3600 seconds = 1 hour */

#define IP5306_ADDR          0x75
#define IP5306_REG_SYS_CTL0  0x00

//bool setPowerBoostKeepOn(int en){
//  I2CPower.beginTransmission(IP5306_ADDR);
//  I2CPower.write(IP5306_REG_SYS_CTL0);
//  if (en) {
//    I2CPower.write(0x37); // Set bit1: 1 enable 0 disable boost keep on
//  } else {
//    I2CPower.write(0x35); // 0x37 is default reg value
//  }
//  return I2CPower.endTransmission() == 0;
//}

void setup() {
  // Set serial monitor debugging window baud rate to 115200
  SerialMon.begin(115200);

  // Start I2C communication
//  I2CPower.begin(I2C_SDA, I2C_SCL, 400000);
//  I2CBME.begin(I2C_SDA_2, I2C_SCL_2, 400000);

  // Keep power when running from battery
//  bool isOk = setPowerBoostKeepOn(1);
//  SerialMon.println(String("IP5306 KeepOn ") + (isOk ? "OK" : "FAIL"));

  // Set modem reset, enable, power pins
  pinMode(MODEM_PWKEY, OUTPUT);
  pinMode(MODEM_RST, OUTPUT);
  pinMode(MODEM_POWER_ON, OUTPUT);
  digitalWrite(MODEM_PWKEY, LOW);
  digitalWrite(MODEM_RST, HIGH);
  digitalWrite(MODEM_POWER_ON, HIGH);

  // Set GSM module baud rate and UART pins
  SerialAT.begin(115200, SERIAL_8N1, MODEM_RX, MODEM_TX);
  delay(3000);

  // Restart SIM800 module, it takes quite some time
  // To skip it, call init() instead of restart()
  SerialMon.println("Initializing modem...");
  modem.restart();
  // use modem.init() if you don't need the complete restart

  // Unlock your SIM card with a PIN if needed
  if (strlen(simPIN) && modem.getSimStatus() != 3 ) {
    modem.simUnlock(simPIN);
  }
  
  // You might need to change the BME280 I2C address, in our case it's 0x76
//  if (!bme.begin(0x76, &I2CBME)) {
//    Serial.println("Could not find a valid BME280 sensor, check wiring!");
//    while (1);
//  }

  // Configure the wake up source as timer wake up  
  esp_sleep_enable_timer_wakeup(TIME_TO_SLEEP * uS_TO_S_FACTOR);
  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
  delay(10);
}

void loop() {
  SerialMon.print("Connecting to APN: ");
  SerialMon.print(apn);
  if (!modem.gprsConnect(apn, gprsUser, gprsPass)) {
    SerialMon.println(" fail");
  }
  else {
    SerialMon.println(" OK");
    
   // SerialMon.print("Connecting to ");
   // SerialMon.print(" firebase");
    Firebase.setInt("Val",int_val);
    delay(1000);
//    SerialMon.print(server);
//    if (!client.connect(server, port)) {
//      SerialMon.println(" fail");
//    }
//    else {
//      SerialMon.println(" OK");
//    
//      // Making an HTTP POST request
//      SerialMon.println("Performing HTTP POST request...");
//      // Prepare your HTTP POST request data (Temperature in Celsius degrees)
//      String httpRequestData = "api_key=" + apiKeyValue + "&value1=" + String(bme.readTemperature())
//                             + "&value2=" + String(bme.readHumidity()) + "&value3=" + String(bme.readPressure()/100.0F) + "";
//      // Prepare your HTTP POST request data (Temperature in Fahrenheit degrees)
//      //String httpRequestData = "api_key=" + apiKeyValue + "&value1=" + String(1.8 * bme.readTemperature() + 32)
//      //                       + "&value2=" + String(bme.readHumidity()) + "&value3=" + String(bme.readPressure()/100.0F) + "";
//          
//      // You can comment the httpRequestData variable above
//      // then, use the httpRequestData variable below (for testing purposes without the BME280 sensor)
//      //String httpRequestData = "api_key=tPmAT5Ab3j7F9&value1=24.75&value2=49.54&value3=1005.14";
//    
//      client.print(String("POST ") + resource + " HTTP/1.1\r\n");
//      client.print(String("Host: ") + server + "\r\n");
//      client.println("Connection: close");
//      client.println("Content-Type: application/x-www-form-urlencoded");
//      client.print("Content-Length: ");
//      client.println(httpRequestData.length());
//      client.println();
//      client.println(httpRequestData);
//
//      unsigned long timeout = millis();
//      while (client.connected() && millis() - timeout < 10000L) {
//        // Print available data (HTTP response from server)
//        while (client.available()) {
//          char c = client.read();
//          SerialMon.print(c);
//          timeout = millis();
//        }
//      }
//      SerialMon.println();
//    
//      // Close client and disconnect
//      client.stop();
//      SerialMon.println(F("Server disconnected"));
//      modem.gprsDisconnect();
//      SerialMon.println(F("GPRS disconnected"));
//    }
  Firebase.setInt("Val",int_val);
  delay(1000);
  modem.gprsDisconnect();
  }
  // Put ESP32 into deep sleep mode (with timer wake up)
  esp_deep_sleep_start();
}

Please help me to fix this error

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32#decoding-exceptions
