### ISSUE TITLE
PSTR Support for rootCA in HTTPClient / Fingerprint checking

### ISSUE THREAD

**Issue by nikeee** [espressif/arduino-esp32#4280]
### Description:
I'm using the HTTPClient with a root CA like in this blog post:
https://techtutorialsx.com/2017/11/18/esp32-arduino-https-get-request/

I am assuming that the `const char*` will be put in the RAM section.
As the entire certificate string can get quite large (~1.2kB in my case), this is not optimal. The ESP8266 allowed checking the SHA-1 fingerprint, which does not seem possible anymore (I understand that SHA-1 is insecure as of now), even with different algorithms.

So my questions are:
- Is it possible to put this inside the PROGMEM using `F()` or `PSTR()`? There is no overload taking a FlashStringHelper.
- Did I get something wrong and checking the fingerprint is still available?
- Is there a different solution that does not take up so much RAM?
- Does this even take up RAM?

**Comment by atanisoft** [comment]
@nikeee PROGMEM and F() are not used on the esp32. Declare it as `static constexpr const char * ...` and it will work as you expect. It won't change the RAM usage very much though.
