### ISSUE TITLE
SimpleBLE.cpp not found header file

### ISSUE THREAD

**Issue by W-M-open** [espressif/arduino-esp32#429]
#include "bta_api.h"
#include "esp_gap_ble_api.h"
#include "esp_gatts_api.h"
#include "esp_bt_defs.h"
#include "esp_bt_main.h"

Could not compile, since the above file are not found.

**Comment by me-no-dev** [comment]
Enable bluetooth in IDF's menuconfig

**Comment by W-M-open** [comment]
Yes. Got it!
