### ISSUE TITLE
OTAWebUpdater example is missing an 'tr' opening in loginIndex

### ISSUE THREAD

**Issue by jellewie** [espressif/arduino-esp32#4293]
Example of 'OTAWebUpdater' has an closing '/tr' but no opening. there is a 'tr' missing. 
I suppose after line 28 (Username:) ?
 
https://github.com/espressif/arduino-esp32/blob/master/libraries/ArduinoOTA/examples/OTAWebUpdater/OTAWebUpdater.ino#L30

Wrong formatting shown by Google Chrome (see line 20):
![image](https://user-images.githubusercontent.com/1545223/91046055-14282400-e618-11ea-9960-22ca53c08334.png)

**Comment by jellewie** [comment]
Great...
How to deal with problems? Just do like they do not exist, and remove them automatically

**Comment by atanisoft** [comment]
@jellewie feel free to submit a PR with the fix.
