### ISSUE TITLE
After upgrading to 1.0.4 UART problem

### ISSUE THREAD

**Issue by tkralj** [espressif/arduino-esp32#4318]
Hello, after upgrading to version 1.0.4 UART seems to skip some bytes sometimes. I can reproduce this behaviour every time i compile code with 1.0.4 or 1.0.3 versions. When downgrade to 1.0.2 code works as expected.

**Comment by lbernstone** [comment]
See if https://github.com/espressif/arduino-esp32/commit/49b76649f13acdb8abaf795015d2740bc5f6b340 fixes it.

**Comment by rljonesau** [comment]
I've had a related problem, likewise after updating.

I was getting random -1 (0xff) added to the received data when using this construct:

`if (Serial2.available()) {  
    data = Serial2.read();   
}`

**Comment by Miq1** [comment]
@rljonesau - thanks a lot, your post saved me hours of chasing a bug. To not have to patch the core over and over (the maintainers seem to not have any troubles, else it would have been changed since), I now am using this construction:
```
if (serial.available()) {
  int c = serial.read();
  if (c >= 0) {
    ... (use c) ...
  }
}
```
