### ISSUE TITLE
Why Serial2 is not responding when I am calling Serial1.begin() in the loop?

### ISSUE THREAD

**Issue by KreakEmp** [espressif/arduino-esp32#4319]
Why Serial2 is not responding when I am calling Serial1.begin() in the loop?
If I am moving both the Serial begin to setup then the GSM serial is responding and working fine. What is the relation of serial2 with serial1.begin()?
Attaching a sample code for the reference:

### Hardware:
Board:							ESP32 Dev Module

### Sketch: 

//Change the code below by your sketch
#include <Arduino.h>

#define GSM_SERIAL Serial2  
#define BAUD_RATE   115200

void setup() {
      Serial.begin(115200);
}

void loop() {
                Serial1.begin(115200);

		do{			
			pinMode(26, OUTPUT);	
			digitalWrite(26,HIGH);  delay(1500);
			
                        DebugSerial.println(F("Pwr_key ON."));
			
			digitalWrite(GSM_POWER_KEY_PIN,LOW);  delay(500);
	
			GSM_SERIAL.begin(BAUD_RATE); 
			GSM_SERIAL.setRxBufferSize(2048);
			delay(500);
			GSM_SERIAL.println(F("AT"));
			delay(1000);
			
		}while( GSM_SERIAL.available() <= 0 );

               // print response of gsm 
               GSM_SERIAL.println(F("AT")); delay(1000);
		while(GSM_SERIAL.available() > 0){
			char c= GSM_SERIAL.read();
			Serial.print(c);
		}
}

**Comment by lbernstone** [comment]
The relationship between the Serial devices has nothing to do with whatever your problem is.
The default pins for Serial1 are unavailable on most boards.  Serial.begin should only be called once during setup, unless you .end it.
```
#define GSM_SERIAL Serial2
const unsigned long BAUD_RATE 115200
const uint8_t GSM_POWER_KEY_PIN = 26;
const int8_t Serial1_Rx = 25;
const int8_t Serial1_Tx = 27;

void setup() {
    Serial.begin(BAUD_RATE);
    Serial1.begin(BAUD_RATE, SERIAL_8N1, Serial1_Rx, Serial1_Tx);
    pinMode(GSM_POWER_KEY_PIN, OUTPUT);	
    Serial.println("Pwr_key ON.");
    GSM_SERIAL.begin(BAUD_RATE); 
    GSM_SERIAL.setRxBufferSize(2048);
}

void loop() {
	while( GSM_SERIAL.available() <= 0 ) {			
        digitalWrite(GSM_POWER_KEY_PIN,HIGH);
        delay(1500);
		digitalWrite(GSM_POWER_KEY_PIN,LOW);
        delay(1000);
		GSM_SERIAL.println("AT");
		delay(1000);		
	}

    // print response of gsm 
	while(GSM_SERIAL.available() > 0){
		char c= GSM_SERIAL.read();
		Serial.print(c);
    }
}
```
