### ISSUE TITLE
[E][WiFiGeneric.cpp:654] hostByName(): DNS Failed for xxxx - still continues on ESP32

### ISSUE THREAD

**Issue by davidkjackson54** [espressif/arduino-esp32#4320]
The issue reported and subsequently closed in 
https://github.com/espressif/arduino-esp32/issues/3203
appears to still be l present.

I have just moved code from an ESP8266 to ESP32.
I have MQTT running on a Raspberry p[i which is also running avahi with defaults , so Avahi returns a .local suffix.
I can ping the RPi  using:
raspberrypi
raspberrypi.local
raspberroypi.localdomain
These are all successfully able to be pinged from Windows 10.

My code:

`// Initializes the espClient 
WiFiClient espClient;
PubSubClient client(espClient);
.
client.setServer("raspberrypi.localdomain", 1883); // set ip address of Raspberry pi and default mqtt port number
client.setCallback(callback); // set callback for messages that arrive on a topic
.
.
// This function reconnects the ESP32 to the MQTT broker
void reconnect() {
//**************  
  // Loop until reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    if (!client.connect("ESP32Client")) {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    } else { 
      Serial.println("connected");  
      // now we subscribe to all our topics that we are interested in 
      subscription();      
    } 
  }
}
.
.
void loop() {
//*********    
 
  if (!client.connected()) {
    reconnect();
  }
  if(!client.loop())
    client.connect("ESP32Client");
}`
This all works fine but if I change it to **raspberrypi.local** , I get
**[E][WiFiGeneric.cpp:654] hostByName(): DNS Failed**

Using **raspberrypi.local**  worked fine on ESP8266 but fails on ESP32. Having to use localdomain is really not much use where as .local is the mDNS standard and in theory should be able to be hardcoded (as it was for ESP8266) .

Unfortunately, I cannot find any avahi logs on the pi to see what if anything it is doing at that end and if it is getting a prompt from the ESP32 for the IP address.   As it worked fine on ESP8266, and nothing changed on the RPi, I  have to believe that the something is going on in the ESP332 side.  

I have stopped the avahi service on the RPi and as expected can no longer ping raspberrypi.local.   Restarted the avahi daemon and ping raspberrypi.local  then works but will not connect within the code.    

One difference between ESP8266 and ESP32 is that I am using the Development stream of WifiManager as it supports ESP32.

Any help on trying to debug this would be appreciated.

**Comment by markg85** [comment]
I too have this issue. I wonder why you closed your own issue and ask for help...
Probably by accident i suppose?

I'm using the exact same stack as you it seems. Also with WifiManager.

**Comment by ollie1400** [comment]
I ran into this as well, and google took me to https://github.com/espressif/arduino-esp32/issues/3822 and https://www.tutorialfor.com/questions-324359.htm

Seems like on the ESP32 you have to do the MDNS lookup explicitly.

**Comment by markg85** [comment]
> I ran into this as well, and google took me to #3822 and https://www.tutorialfor.com/questions-324359.htm
> 
> Seems like on the ESP32 you have to do the MDNS lookup explicitly.

I took a deep dive into this issue and documented my findings here: https://github.com/espressif/esp-idf/issues/2507#issuecomment-761836300

The actual issue is that for whatever reason the ESP32 SDK blindly adds ".local" to mdns queries. That's downright wrong as ".local" is something a user can change (.local is the default) and doing this makes it a lot more difficult to lookup names.

I'll add this to #3822 too.

**Comment by Timmmy001** [comment]
it seems to be a tool chain problem:
https://github.com/espressif/esp-idf/issues/6590#issuecomment-827086670
