### ISSUE TITLE
touchAttachInterrupt() userfunc parameter should not be void

### ISSUE THREAD

**Issue by ericgu** [espressif/arduino-esp32#4321]
I'm working on some code that uses the touch subsystem and the arduino HAL. 

I can call touchAttachInterrupt() multiple times for different pins. The underlying code in __touchISR() knows which routine to call for a specific pin, but it doesn't pass any pin information on. 

This forces me to write something like:
touchAttachInterrupt(4, Touch0Interrupt, 20);
...
touchAttachment(32, Touch9Interrupt, 20);

touchAttachInterrupt() should store the pin number away at the same time it stores the function pointer away and then pass it on the callback. That would let me write a routine like:

void MyTouchHandler(int pinNumber)
{
  
}

and handle all the touch pins with a single chunk of generic code.

**Comment by sansillusion** [comment]
Not sure as I'm not much of a programmer but would something like that work ? :
    touchAttachInterrupt(4, TouchInterrupt(0), 20);
    touchAttachment(32, TouchInterrupt(9), 20);

**Comment by ericgu** [comment]
Unfortunately, that does not work, but you did get me thinking that I can probably do something with the C++ lambda support. Something like:

int pin = 32;
touchAttachInterrupt(pin, [pin](){MyInterruptHandler(pin);});

assuming I have my lambda syntax correct. That's not great but it's better than what I had planned from a syntax perspective, though the overhead might be worse...

**Comment by ericgu** [comment]
Lambdas do work but not in the format I used; you can't pass lambdas that do captures to function pointers, so they aren't really any better than my initial implementation.

**Comment by Leo-C** [comment]
Hi,
I believe that function [`esp_sleep_get_touchpad_wakeup_status()`](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#_CPPv436esp_sleep_get_touchpad_wakeup_statusv) can help you.

Interrupt handler can not get a parameter indicating pin touched, but calling function above as first instruction, you'll have same information

Leonardo

**Comment by SuGlider** [comment]
New Touch API will have this function ```touchAttachInterruptArg(...)```

``` dart
/*
 * Set cycles that measurement operation takes
 * The result from touchRead, threshold and detection
 * accuracy depend on these values. Defaults are
 * 0x1000 for measure and 0x1000 for sleep.
 * With default values touchRead takes 0.5ms
 * */
void touchSetCycles(uint16_t measure, uint16_t sleep);

/*
 * Read touch pad (values close to 0 mean touch detected)
 * You can use this method to chose a good threshold value
 * to use as value for touchAttachInterrupt
 * */
uint32_t touchRead(uint8_t pin);

/*
 * Set function to be called if touch pad value falls (ESP32)
 * below the given threshold / rises (ESP32-S2/S3) by given increment (threshold). 
 * Use touchRead to determine a proper threshold between touched and untouched state
 * */
void touchAttachInterrupt(uint8_t pin, void (*userFunc)(void), uint32_t threshold);
void touchAttachInterruptArg(uint8_t pin, void (*userFunc)(void*), void *arg, uint32_t threshold);
void touchDetachInterrupt(uint8_t pin);

/*
 * Specific functions to ESP32 
 * Tells the dirver if it shall activate the ISR if the sensor is Lower or Higher than the Threshold
 * Default if Lower.
 **/
void touchInterruptSetThresholdDirection(bool mustbeLower);
```

**Comment by jdeltoft** [comment]
Does this new touchAttachInterruptArg() api support wake up from deep sleep?  Or is that only supported with touchAttachInterrupt().

I have this for setup:

```
void setup() {
  touch_pad_init();

  for(int i=0; i<TOUCH_PIN_COUNT; i++) {
    touchAttachInterruptArg(pinNames[i], gotTouch, &pinIds[i], capTouchThreshold);
    touchSleepWakeUpEnable(pinNames[i], 500);
  }

  esp_sleep_enable_touchpad_wakeup();
}
```

And then if I call `esp_deep_sleep_start();` I lose my serial connection and never seem to wake up from any touch.  If I just remove this deep sleep call, everything works perfect for the 5 cap touch inputs.
