### ISSUE TITLE
The Write function of WifiServer.h

### ISSUE THREAD

**Issue by qinannan** [espressif/arduino-esp32#4330]
The  member function Write of WifiServer.h is an empty function, so how do I use it when I use this function to write data to the Client? Can you add this function?

**Comment by lbernstone** [comment]
The WiFiServer is a listener.  Once a client connects, you should attach it to a WiFiClient object and write to that object.  See https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino
