### ISSUE TITLE
ESP32 WROVER IB and FTDI

### ISSUE THREAD

**Issue by hyeriii** [espressif/arduino-esp32#4331]
### Hardware:
Board:							ESP32 wrover Module
Core Installation version:			?1.0.0? ?1.0.1-rc4? ?1.0.1? ?1.0.1-git? ?1.0.2? ?1.0.3?
IDE name:					      Arduino IDE
Flash Frequency:				      80Mhz
PSRAM enabled:                                    ?no? ?yes?
Upload Speed:				      115200
Computer OS:                                        Windows 10

![esp32](https://user-images.githubusercontent.com/52684070/92563068-f0204000-f2b1-11ea-9304-4ec323be70da.PNG)
![image](https://user-images.githubusercontent.com/52684070/92563086-f8787b00-f2b1-11ea-9991-78de9e144bf1.png)

The following problem occurred while uploading an Arduino sketch using ESP32 WROVER IB and FTDI.

**Comment by MarkyAD** [comment]
The unused pin next to TX on the FTDI is DTR. Set it to GND level.
