### ISSUE TITLE
OTA via BLE

### ISSUE THREAD

**Issue by EmanueleFeola** [espressif/arduino-esp32#4333]
Is there an arduino code example of OTA via BLE for esp32 available?

**Comment by lbernstone** [comment]
LMGTFY:
https://www.google.com/search?q=Is+there+an+arduino+code+example+of+OTA+via+BLE+for+esp32+available

**Comment by Jeroen88** [comment]
@lbernstone I read the [Sparkfun ](https://learn.sparkfun.com/tutorials/esp32-ota-updates-over-ble-from-a-react-web-application/all)tutorial. Nice! I am going to try that once!
