### ISSUE TITLE
core Print/Stream API is old. availableForWrite is missing

### ISSUE THREAD

**Issue by jandrassy** [espressif/arduino-esp32#4336]
this should be applied
https://github.com/arduino/ArduinoCore-API/pull/104

**Comment by jandrassy** [comment]
so using a stale boot assumes that developers don't stale

**Comment by drmpf** [comment]
Yes a duplicate, was marked as stale.  
Merge PULL request [#4664](https://github.com/espressif/arduino-esp32/issues/4336) to fix this

**Comment by jandrassy** [comment]
> was marked as stale.

only 2 hours at 11/11
