### ISSUE TITLE
HttpClient - Not able to make a request over WiFi when ethernet conencted

### ISSUE THREAD

**Issue by maganuk** [espressif/arduino-esp32#4341]
### Hardware:
Board:							ESP32-Ethernet-Kit
Core Installation version:			1.0.3
IDE name:						Platform.io
Flash Frequency:					40Mhz
PSRAM enabled:                                     yes
Upload Speed:					115200
Computer OS:                                        Windows 10

### Description:
Make a request using the HTTPClient when both WiFi and Ethernet are connected. If both are connected, the HTTPClient will always make the request over Ethernet. How can I change this priority?

### Sketch:  
```cpp

HTTPClient httpClient;
if (isEthernet)
{
  WiFiClient wifiClient;
  httpClient.begin(wifiClient, serverCheckUrl);
}
else
{
  httpClient.begin(serverCheckUrl);
}
```

**Comment by Jeroen88** [comment]
As you can see [here](https://github.com/espressif/arduino-esp32/blob/37a7fb3d6ada8a9230c96e2df999c95ef10fd4d3/libraries/HTTPClient/src/HTTPClient.h#L137) you can only pass in a WiFiClient and not an ethernet client. So it will not work.

Maybe you can use my PR #3848.
