### ISSUE TITLE
Arduino IDE isn't recognizing ESPASyncWebServer

### ISSUE THREAD

**Issue by josetomas** [espressif/arduino-esp32#4345]
### Hardware:
Adafruit feather ESP32 WROOM - 32
IDE: Platformio
Upload Speed: 115200
Computer OS: Windows
Core Installation version: No idea, as it came from fabric
Flash frequency: 40 MHz

### Description:
The Arduino IDE isn't recognizing the ESPAsyncWebServer.h.

### Sketch:  
Same problem with every sketch. 

### Debug Messages:
```
C:\Users\corne\OneDrive\Documentos\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:33:22: fatal error: AsyncTCP.h: No such file or directory
compilation terminated.
exit status 1
Error compilando para la tarjeta Adafruit ESP32 Feather.
```

**Comment by lbernstone** [comment]
This forum is for issues with the repository codebase, not your programs.

**Comment by josetomas** [comment]
Sorry, I thought ESPAsyncWebServer was also a librarie of your repo. If anyone has the same problem you can follow the issue [here](https://github.com/me-no-dev/ESPAsyncWebServer/issues/848)
