### ISSUE TITLE
#error Architecture or board not supported, but only have one SD.h file

### ISSUE THREAD

**Issue by questionask** [espressif/arduino-esp32#4349]
### Hardware:
Board:							m5Stack Core ESP32
Core Installation/update date:			01/jul/2020
IDE name:					        Arduino IDE
Flash Frequency:					80Mhz
Computer OS:                                           Windows 10

### Description:
I keep getting the following message:

In file included from C:\Program Files\WindowsApps\...\libraries\SD\src/utility/Sd2Card.h:26:0,

C:\Program Files\WindowsApps\...\libraries\SD\src/utility/Sd2PinMap.h:524:2: error: #error Architecture or board not supported.

 #error Architecture or board not supported.

  ^

exit status 1

Error compiling for board M5Stack-Core-ESP32.

I've looked on many different forums, and it seems like this issue usually results from there being an extra SD.h file which needs to be deleted. In my case though, I only have one SD.h file to work with, so I have no idea what is causing this error.

**Comment by lbernstone** [comment]
It comes from the 3rd party library that you are using (Sd2Card).  It indicates in its properties that it does not support esp32.
