### ISSUE TITLE
Support for NAT routing (to be ported from esp8266)

### ISSUE THREAD

**Issue by bmellink** [espressif/arduino-esp32#4354]
Can we please get support for NAT routing (lwip/napt.h) added?

This is part of the ESP8266 Arduino core for a while, but has not yet been ported to the esp32 side.

There a few implementations done by others. Examples are
```
https://github.com/Lucy2003/ESP32-NAPT-For-Arduino 
https://github.com/martin-ger/esp32_nat_router
```
but it would be better to have it supported here

**Comment by lbernstone** [comment]
In the next release, this will be a one liner.  However, it will require changes to the IP stack which will not be appropriate for general deployment (IP forwarding).  I'll compile a drop-in library similar to what I do for [SOLO](https://github.com/lbernstone/arduino-esp32-solo) to enable forwarding and NAT bridging.
