### ISSUE TITLE
HardwareSerial.end() not cleaning up pins

### ISSUE THREAD

**Issue by dka23** [espressif/arduino-esp32#4356]
Reopening issue #3205. This issue is still present in the current version (as seen in Tasmota). It seems to be fixable by calling gpio_reset_pin(pinNumber).

See also comment by @WayneKeenan in https://github.com/espressif/arduino-esp32/issues/3205#issuecomment-581040749_

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/pull/3894

**Comment by dka23** [comment]
Thanks @lbernstone - closing this as duplicate.
