### ISSUE TITLE
Error compiling for board ESP32 Wrover Module.

### ISSUE THREAD

**Issue by Liam1324** [espressif/arduino-esp32#4362]
Arduino: 1.8.13 (Mac OS X), Board: "ESP32 Wrover Module, Minimal SPIFFS (1.9MB APP with OTA/190KB SPIFFS), QIO, 80MHz, 921600, None"

In file included from /Users/liam/Documents/Arduino/libraries/WiFi/src/WiFiSTA.h:28:0,
Multiple libraries were found for "WiFi.h"
 Used: /Users/liam/Documents/Arduino/libraries/WiFi
                 from /Users/liam/Documents/Arduino/libraries/WiFi/src/WiFi.h:32,
 Not used: /private/var/folders/70/vlp7lcr95b3gf3cg1fzcrmfm0000gn/T/AppTranslocation/8F8E0161-733F-4D29-8A4C-DA2673E24E02/d/Arduino.app/Contents/Java/libraries/WiFi
 Not used: /Users/liam/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/WiFi
                 from /Users/liam/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/ArduinoOTA/src/ArduinoOTA.h:4,
                 from /Users/liam/Documents/Arduino/libraries/am43-master/examples/MQTTBlinds/MQTTBlinds.ino:31:
/Users/liam/Documents/Arduino/libraries/WiFi/src/WiFiGeneric.h:31:39: fatal error: wifi_provisioning/manager.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board ESP32 Wrover Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by NodeSolo88** [comment]
So no solution??
