### ISSUE TITLE
PWM and millis

### ISSUE THREAD

**Issue by arnoldvillasanta** [espressif/arduino-esp32#4378]
I'm trying to use a CIS (Contact Image Sensor) with esp32 Devkit.
I use PWM for CIS clock and millis to schedule the scanning interval.
For signal trace, I’m using PICO Scope.

What works (as it seems):
when scanInteval = 1 millis, the data signal trace is okay, showing the LOW voltage below half of 3.3V.

What didn't work:
when scanInterval = 1000 millis, the data signal trace shows the LOW voltage way up in the HIGH voltage rating and the data is somewhat compressed (timeline at x-axis).

Notice in the code that I tried to set the CLOCK pin in the scan function as I thought it might resolve the issue.

Below are the signal trace and code.

The Data Trace when scanInterval <20 millis:

![Screen Shot 2020-10-01 at 10 03 52 AM](https://user-images.githubusercontent.com/31164013/94763172-25fda380-03dc-11eb-9739-69413c89987f.png)

The Data Trace when scanInterval > 100 millis:

![Screen Shot 2020-10-01 at 10 05 54 AM](https://user-images.githubusercontent.com/31164013/94763050-d9b26380-03db-11eb-84b2-13875b3c06e9.png)

> //For CIS - Scanner
#define READPIN 25
#define START 26
#define CLOCK 27

> //For Scanner Data
String cisData;
volatile unsigned long previousScanMillis;
const long scanInterval = 20;

> // setting PWM properties
const int clockChannel = 0;
const int clockResolution = 4;
const int clockFreq = 3000000;
const int clockDutyCycle = 7;

> //=======================================================================
//                    Power on SETUP
//=======================================================================
void setup() {
  Serial.begin(115200);

>  //For CIS Sensor
  pinMode(CLOCK, OUTPUT);
  pinMode(START, OUTPUT);
  pinMode(READPIN, INPUT_PULLUP);

  > // Configure CLOCK signal
  //  ledcSetup(clockChannel, clockFreq, clockResolution);
  //  ledcAttachPin(CLOCK, clockChannel);
  //  ledcWrite(clockChannel, clockDutyCycle);
}

> //=======================================================================
//                    MAIN PROGRAM Loop
//=======================================================================

> void loop() {
  // Scan Image
  scanLine();
}

> //=======================================================================
//                    Functions (CIS Sensor)
//=======================================================================

> void scanLine() {
  //  delay(100);
  unsigned long currentScanMillis = millis();
  if (currentScanMillis - previousScanMillis >= scanInterval) {
    previousScanMillis = currentScanMillis;
    cisData = "";
    ledcSetup(clockChannel, clockFreq, clockResolution);
    ledcAttachPin(CLOCK, clockChannel);
    digitalWrite(START, HIGH);
    ledcWrite(clockChannel, clockDutyCycle);
    delay(1);
    digitalWrite(START, LOW);

>     for (int i = 0; i < 200; i++) {
      cisData += digitalRead(READPIN);
    }
>   cisData += "\n";
    //  Serial.print("*");
    Serial.println(cisData);
    //  cisDataToSend += 1;
    ledcDetachPin(CLOCK);
    pinMode(CLOCK, OUTPUT);
    digitalWrite(CLOCK, LOW);
>   }
> }`

**Comment by bareaescobar** [comment]
hi! 

Did you manage to connect a CIS module to a ESP32 and make it usable?
