### ISSUE TITLE
How to get connected to xfinity public wifi

### ISSUE THREAD

**Issue by ToyboxZach** [espressif/arduino-esp32#4381]
I am trying to see if I can get my esp32 connected to an xfinity public network, and I can get it connected to the point that I get STA_CONNECTED, but I can't actually communicate with my server.

I can get an Xfinity Secure profile to connect my computer, but I'm curious how to translate that into certificates that the esp32 can use. There are a bunch of options I don't completely understand so if someone has done this or a place to find more information that would be super helpful.

I know I can just connect to other networks, but I would like the option to connect to this network if I want.

**Comment by 6feb-cell** [comment]
USDOT
