### ISSUE TITLE
Wrong analogReadMilliVolts() in esp32s2

### ISSUE THREAD

**Issue by fabiuz7** [espressif/arduino-esp32#4386]
#4072 # Hardware:
Board:							ESP32-S2 Saola
Core Installation version:			esp32s2 branch lates commit
IDE name:						Arduino IDE

### Description:
Hi, I was trying ESP32-S2 Saola breakout board, I would read analog values. I had used a variable lab bench power supply to test the ADC, but function  analogReadMilliVolts() gives values 60% higher than the right value: i.e. if I set 1V, analogReadMilliVolts returns 1.6V. This behavior is constant all over the range (from 0 to 2.5V). 

I think that the problem is about the fixed 13bit width in esp32-s2 while in esp32 ranges between 9 and 12.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/adc.html#_CPPv416adc_bits_width_t

Am I missing something?

Temporarily, I manage to use the following line to read input voltage:

    int sensorValueRaw = analogRead(analogInPin);
    int sensorValue = map(sensorValueRaw, 0, 8192, 0, 2600);

No other configuration were made to the ADC.

**Comment by newHeiko** [comment]
JFTR: Still true on the current idf-release/v4.2 branch (current HEAD: https://github.com/espressif/arduino-esp32/commit/beedeea4541116106b38fc5c3a03821cdf6fe288)

Minimal sketch to check:
```
void setup() {
  Serial.begin(115200);
}

void loop() {
  uint32_t analogValue = analogReadMilliVolts(8);
  Serial.println(analogValue);
}
```

...with an ESP32-S2-WROOM and about 1.74V at Pin 8 I get readings around 2518...2522mV.

Let me know what I can do to help debug this.

Heiko
