### ISSUE TITLE
Windows Install instructions dont work for non-default sketchbook location

### ISSUE THREAD

**Issue by jdunne525** [espressif/arduino-esp32#439]
I followed the Windows Installation instructions and everything seemed fine.  Ran get.exe which finished without errors.
I open Arduino IDE and I am not seeing any ESP32 boards listed.  

I figured it out as I was writing this.  Please point out in the instructions that the "Target Directory" should match the setting in Arduino IDE preferences: "Sketchbook location"

**Comment by joeybab3** [comment]
I'll update windows.md for this.
