### ISSUE TITLE
PSRAM detection issue

### ISSUE THREAD

**Issue by Sanketa54** [espressif/arduino-esp32#4417]
Hi, 
IHardware:
Board:  ESP32 Dev module ( ESP32D2WD chip )
IDE name: Arduino IDE
?IDF component =  No 
Flash Frequency: ?40Mhz
PSRAM enabled: ?Yes
Upload Speed: ?115200
Computer OS: ?Windows 10

Description:

Hi,
I'm interfacing external PSRAM of 64Mb with ESP32D2WD chip.
Tried following things :

1. ENABLED Psram from BOARD settings. --- "psram not supported "msg
2. Used arduino / idf commands to check the PSRAM total/free memory size.
3. Tried by ENABLING CONFIG_SPIRAM_BOOT_INIT in sdkconfig file. ---- SHowing no memory
4. Tried by changing pin configuration in sdkconfig file for psram.

Sketch: (leave the backquotes for code formatting)
//Change the code below by your sketch
//#include <SPI.h>

#include <Arduino.h>
#include<esp32-hal.h>

void setup() {
  
  Serial.begin(115200);
//  delay(2000);
  Serial.print("Total heap:");
  Serial.println(ESP.getHeapSize());
  Serial.print("Free heap: ");
  Serial.println(ESP.getFreeHeap());
  //Serial.print("TOtal psram size : ");
  //Serial.println(esp_spiram_get_size());
  Serial.print("PSRAM INIT : ");
  Serial.println(psramInit());
   Serial.print("PSRAM Found : ");
  Serial.println(psramFound());
//if(psramFound()){
    
  Serial.print("Total PSRAM using caps:");
  Serial.println(heap_caps_get_free_size(MALLOC_CAP_SPIRAM));
  Serial.print("Total PSRAM:");
  Serial.println(ESP.getPsramSize());
  Serial.print("Free PSRAM: ");
  Serial.println(ESP.getFreePsram());
  
//  }
  delay(2000);
  }
  
 // Serial.setDebugOutput(true);
  
}

void loop() {}
  
Debug Messages:
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
(11:30:37.161) [D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
(11:30:37.193) Total heap:388100
(11:30:37.193) Free heap: 362108
(11:30:37.193) PSRAM INIT : 1
(11:30:37.193) PSRAM Found 
(11:30:37.208) : 1

**Comment by lbernstone** [comment]
Please follow the [issue template](https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md).  You need to provide more information if you want help with your problem.

**Comment by Sanketa54** [comment]
> Please follow the [issue template](https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md). You need to provide more information if you want help with your problem.

I have updated .. Please check if there's any solution

**Comment by me-no-dev** [comment]
your debug messages show that PSRAM was enabled 👍 
in any case, list what PSRAM chip you are using and how you have it connected to the ESP

**Comment by Sanketa54** [comment]
> your debug messages show that PSRAM was enabled 👍
> in any case, list what PSRAM chip you are using and how you have it connected to the ESP

Its showing ENABLE when I changed the sdkconfig.h i.e CONFIG_SPIRAM_BOOT_INIT is Enabled
I think its hould be enabled inspite of any changes in sdkconfig.h

**Comment by Sanketa54** [comment]
> your debug messages show that PSRAM was enabled 👍
> in any case, list what PSRAM chip you are using and how you have it connected to the ESP
@me-no-dev  : PSRAM :  APS6404L-SQR-ZR  (64Mb)
