### ISSUE TITLE
Error Compiling the new ESP32_TFT_library

### ISSUE THREAD

**Issue by sfranchin63** [espressif/arduino-esp32#442]
Hi,
I tried to compile the demo : https://github.com/loboris/ESP32_TFT_library
But I gave the following errors.
The Gcc version is 6.3.0 and esp-idf-v2.0.
Can someone help me ?
Best regards
Thank you
Stefano
![error demo loboris_esp32_tft_library](https://user-images.githubusercontent.com/23196408/27095810-51cee1f0-506f-11e7-823f-433a542349ea.JPG)

**Comment by me-no-dev** [comment]
looks like old IDF code
