### ISSUE TITLE
I2C Errors:  [I][esp32-hal-i2c.c:1130] i2cProcQueue(): Bus busy, reinit

### ISSUE THREAD

**Issue by githufsb** [espressif/arduino-esp32#4425]
Getting above message with 	CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG

**Comment by jesse-schein** [comment]
I actually looked at this yesterday, I think these are harmless logging by the i2c hal. It's chatty if you use i2c in any way with log levels set above 3

**Comment by githufsb** [comment]
Ok thanks!  I was looking at a user error in my implementation, but I got it working.
