### ISSUE TITLE
Arduino IDE - Hello world trial - Encoded output 

### ISSUE THREAD

**Issue by Eman-Hussein** [espressif/arduino-esp32#443]
I tried to run a simple example on ESP32 to print hello world every second using arduino IDE. At the very begining, I got an encoded output that I dont know the reason behind it, then I got hello world printed. Any idea why this happens ?
I attached a screenshot 
![2017-06-13](https://user-images.githubusercontent.com/4370333/27104476-6ebb2c7a-505a-11e7-829d-e5669632532d.png)

**Comment by bbx10** [comment]
Change the baud rate in the console window to 115200 then you will be able to read the gibbersh. Also change Serial.begin(9600) to Serial.begin(115200).

**Comment by Eman-Hussein** [comment]
It worked. Thanks a lot for your help.
