### ISSUE TITLE
WiFiClient improperly treats zero data available for read as an error

### ISSUE THREAD

**Issue by MHotchin** [espressif/arduino-esp32#4435]
In "arduino-esp32/libraries/WiFi/src/WiFiClient.cpp".

If the client has run out of data that has been received, it will return an error, instead of returning 0 (indicating no data available right now).

Starting line 106:

```
    int read(uint8_t * dst, size_t len){
        if(!dst || !len || (_pos == _fill && !fillBuffer())){
            return -1;

```
Change to:

```
    int read(uint8_t * dst, size_t len){
        if(!dst || !len || (_pos == _fill && !fillBuffer())){
            return _failed ? -1: 0;
```

**Comment by MHotchin** [comment]
This appears to be the cause of #4390 as well.

**Comment by MHotchin** [comment]
Add to fix - function `'read()` needs to handle the zero data available case as well.  Found by using `readBytes()`, which calls the single byte version of `read()`.
```
int WiFiClient::read()
{
    uint8_t data = 0;
    int res = read(&data, 1);
    if(res < 0) {
        return res;
    }
    if (res == 0) {
        return -1;
    }
    return data;
}

```

**Comment by MarkusAD** [comment]
@MHotchin you should submit your changes as a pull request so that they can be reviewed and merged into the current code base.

**Comment by MHotchin** [comment]
PR  #4448 submitted.
