### ISSUE TITLE
ESP32-S2 I2C slave mode not defined in the library

### ISSUE THREAD

**Issue by nedimkivanc** [espressif/arduino-esp32#4437]
code:

#include <Wire.h>

void setup()
{
  Wire.begin(4);                // join i2c bus with address #4
  Wire.onReceive(receiveEvent); // register event
  Serial.begin(9600);           // start serial for output
}

void loop()
{
  delay(100);
}

void receiveEvent(int howMany)
{
  while(1 < Wire.available()) 
    char c = Wire.read(); 
    Serial.print(c);        
  }
  int x = Wire.read();    
  Serial.println(x);       
}

Debug:

undefined reference to `TwoWire::onReceive(void (*)(int))'

**Comment by lbernstone** [comment]
arduino-esp32 does not have i2c slave, period.  Not sure where you got this code, but Wire.begin() only has one definition, which is a master. https://github.com/espressif/arduino-esp32/blob/master/libraries/Wire/src/Wire.h#L74
