### ISSUE TITLE
can't connect to an AP 4WAY-HANDSHAKE_TIMEOUT

### ISSUE THREAD

**Issue by Speedy2k** [espressif/arduino-esp32#4460]
I have a ZTE MF288 LTE router and i can't no matter what settings i put in it's wifi configuration get my ESP32 to connect to it. I alway get 4WAY-HANDSHAKE_TIMEOUT, i have tried all security option even open network without password and nothing to do.

This code is working proberly on my shop router, my cell phone sharing etc, this is the first router model that i can't connect to. Is there anything to do with that?

Starting a WiFi Scan.
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 2 - STA_START
WiFi client started
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 1 - SCAN_DONE
  Programmed WiFi: ZTE MF288CCBB-2.4G
  Available network:
    ZTE MF288CCBB-2.4G -> Trying!
    mFi 4C9908
    070300002
    060300005
    040300513
    040300519
    060300035
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:353] _eventCallback(): Reason: 15 - 4WAY_HANDSHAKE_TIMEOUT
WiFi disconnected: WIFI_REASON_4WAY_HANDSHAKE_TIMEOUT
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 3 - STA_STOP

Thanx a lot!

**Comment by cagney** [comment]
could this be #3225
