### ISSUE TITLE
Please synchronize WiFiClientSecure with BearSSL used in ESP8266 Arduino 

### ISSUE THREAD

**Issue by dalbert2** [espressif/arduino-esp32#4463]
### Hardware:
Board:							ESP-WROOM-32
Core Installation/update date:			2.0.0
IDE name:							VSCode/PlatformIO
Flash Frequency:					40Mhz
PSRAM enabled:                                          no
Upload Speed:						430600
Computer OS:                                            Windows 10

### Description:
The ESP8266 WiFiClientSecure is significantly advanced relative to the ESP32 version; it uses BearSSL and has many added features, some of which are critical to good embedded performance.  In particular, the ability to save an SSL session and resume it later *without having to re-negotiate keys and protocols* makes re-connections nearly instant - essential for IoT devices that need to sleep a lot.  Otherwise there is a delay of 1-3 seconds each time an SSL connection is established.  BearSSL is well documented and has numerous utility functions related to buffer sizes, testing whether there is space available in the write buffer, etc.

Please see: https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi/src
files: WiFiClientSecureBearSSL.h, WiFiClientSecureBearSSL.cpp, WiFiClientSecure.h

Sorry if this is the wrong place to post such a request, if  it belongs elsewhere, please point me in the right direction.

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
N/A

### Debug Messages:
N/A

**Comment by minhaj6** [comment]
what's the situation now? I am facing same type of difficulty with esp32. `#include <WiFiClientSecureBearSSL.h>` doesn't work on esp32
