### ISSUE TITLE
Firmware update on esp32 encoded

### ISSUE THREAD

**Issue by workpage2** [espressif/arduino-esp32#4465]
I use update.h to update esp32 and it works great.
I have encoded esp32 flash memory according to this instruction: https://github.com/espressif/arduino-esp32/issues/1387. I also coded a new firmware file. update.h has stopped working. I get an error

    UPDATE_ERROR_MAGIC_BYTE
Tell me how to properly update the firmware via the web on an encoded esp32?

**Comment by lbernstone** [comment]
Encrypted images are only useful in development mode.  In release mode, you will not know anything about the internal encryption key.  So, you must pass the raw image file to OTA, and it will write it to disk encrypted.  You can transfer the raw image over [https](https://github.com/espressif/arduino-esp32/tree/master/libraries/Update/examples/HTTPS_OTA_Update) to keep the data secure on route.
