### ISSUE TITLE
unable to modify the RX fifo full threshold in HardwareSerial

### ISSUE THREAD

**Issue by AldoLodos** [espressif/arduino-esp32#4468]
Hello,

I have a problem with the behaviour of HardwareSerial regarding how and when the fifo is copied in the receive queue.
As far as I understood there are two case that trigger the emptying of the Fifo.:
•	The UART hardware receives 112 or more bytes.
•	Or, if the UART sees the receive pin inactive for two byte periods it triggers an interrupt to empty the fifo. 
The Serial() object only sees the receive queue. So until either of those two cases happen, the data is only in the hardware Fifo.

My issue: on a serial 1200 bauds com I have to receive  a 120 bytes message sent in a row and i need to receive them bytes by bytes ( to be able to answer quickly )
With the current behaviour of Serial.available() I have to wait for the first 112 bytes (which is almost 1 second) before  to get the first byte sent.

In the file esp32-hal-uart.c I can see this function 

> void uartEnableInterrupt(uart_t* uart)
> {
>     UART_MUTEX_LOCK();
>     uart->dev->conf1.rxfifo_full_thrhd = 112;
>     uart->dev->conf1.rx_tout_thrhd = 2;
>     uart->dev->conf1.rx_tout_en = 1;
>     uart->dev->int_ena.rxfifo_full = 1;
>     uart->dev->int_ena.frm_err = 1;
>     uart->dev->int_ena.rxfifo_tout = 1;
>     uart->dev->int_clr.val = 0xffffffff;
> 
>     esp_intr_alloc(UART_INTR_SOURCE(uart->num), (int)ESP_INTR_FLAG_IRAM, _uart_isr, NULL, &uart->intr_handle);
>     UART_MUTEX_UNLOCK();
> }

I tried to set the uart->dev->conf1.rxfifo_full_thrhd to 1 and it solve my issue, the bytes can be read one by one.

But it is not a good idea to modify the code of the library 

So as a test  I added the following line to   HardwareSerial.h 
>         uart_struct_t* get_uart();
and the following line to HardwareSerial.cpp
>        uart_struct_t* HardwareSerial::get_uart() {return _uart;} 

and in my sketch (I use the arduino IDE) :

> #include <HardwareSerial.h>
> #include "driver/uart.h"
> #include <esp32-hal-uart.h>
> 
> HardwareSerial MySerial1(1);
> 
> #define RX1     15
> #define TX1     17
> 
> struct uart_struct_t {
>     uart_dev_t * dev;
> //#if !CONFIG_DISABLE_HAL_LOCKS
>  //   xSemaphoreHandle lock;
> //#endif
>     uint8_t num;
>     xQueueHandle queue;
>     intr_handle_t intr_handle;
> }; 
> 
> uart_struct_t* Uart1;
> 
> void setup() {
>   Serial.begin(115200);
>   Serial.println("ESP32 Serial Test");
>   MySerial1.begin(1200 ,SERIAL_8N1, RX1, TX1);
>   Uart1 = MySerial1.get_uart();
>   Uart1->dev->conf1.rxfifo_full_thrhd= 1;
> }

It works and I can set the parameters without modifying the library (and even on the fly)

Would it be possible to add such a function or at least a function to modify the values in uart->dev->   because it is not easy to work with a library where these parameters are hardcoded.

Of course in my test I didn’t handle the UART_MUTEX_LOCK() present in uartEnableInterrupt neither the #if !CONFIG_DISABLE_HAL_LOCKS of uart_struct_t as I have no clue about these

Thanks

**Comment by bertmelis** [comment]
If you want to use Platformio, you can patch the file yourself before building.

Method is described in Platformio's docs and we have an example here: https://github.com/eModbus/eModbus/tree/master/examples/RTUserver-patched
