### ISSUE TITLE
May IDF be updated to git version?

### ISSUE THREAD

**Issue by gmag11** [espressif/arduino-esp32#447]
I'm getting some troubles in Arduino with bluetooth. Same code works fine in Eclipse using IDF. Main diference is that, for eclipse, I use curent git version and Arduino-esp32 uses release 2.1.

May I copy header files and precompiled libraries (and all other needed files) to update IDF in Arduino-esp32?

**Comment by me-no-dev** [comment]
yes, maybe they desynced? I'll refresh the libs today
