### ISSUE TITLE
BLERemoteCharacteristic writeValue fails to write std::strings containing null character '\0'

### ISSUE THREAD

**Issue by snosrap** [espressif/arduino-esp32#4472]
Unlike C-style strings, `std::string`s can contain the `null` character. For example `std::string("hello\0world")`.

However, in [BLERemoteCharacteristic.cpp](https://github.com/espressif/arduino-esp32/blob/f7fb00632e04d74a7890a77fa7dbbb8ae572e866/libraries/BLE/src/BLERemoteCharacteristic.cpp#L538), the `std::string newValue` is converted to a C-style string before being sent to [writeValue](https://github.com/espressif/arduino-esp32/blob/f7fb00632e04d74a7890a77fa7dbbb8ae572e866/libraries/BLE/src/BLERemoteCharacteristic.cpp#L561). This means that any characters after a null character in `newValue` will *not* be sent to `writeValue`. For example, `std::string("hello\0world")` will be converted into the C-style/null-terminated string `"hello\0"`.

https://github.com/espressif/arduino-esp32/blob/f7fb00632e04d74a7890a77fa7dbbb8ae572e866/libraries/BLE/src/BLERemoteCharacteristic.cpp#L538

A fix would be to use the `data()` method on `std::string` and, more importantly, the `length()` method on `std::string`. `newValue.length()` will give the total length of the string (including any null characters), however `strlen` will only return the length up to the first null character.

```c++
void BLERemoteCharacteristic::writeValue(std::string newValue, bool response) {
	writeValue((uint8_t*)newValue.data(), newValue.length(), response);
} // writeValue
```

**Comment by chegewara** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/src/BLERemoteCharacteristic.h#L50

**Comment by snosrap** [comment]
@chegewara, I'm not sure I understand your comment. Are you suggesting I not use `writeValue(std::string newValue, bool response = false)` in cases where `newValue` may contain null characters?

**Comment by chegewara** [comment]
Sorry, i didnt read carefully your OP. Yes, this change is good.
