### ISSUE TITLE
Make Stream::timedRead / timedPeek public?

### ISSUE THREAD

**Issue by thewavelength** [espressif/arduino-esp32#4480]
The functions `Stream::timedRead()` and `Stream::timedPeek()` are private.

Is there a reason for this?

I have multiple use-cases where I would like to have access to these methods when reading stuff from the network. As a workaround I have to make ugly calls to `Stream::readBytesUntil()` even though I don't need this and only use it as a gate function.

If there is nothing speaking against it, I could quickly create a PR. Please let me know.

**Comment by nikeee** [comment]
I'd welcome this change in my projects, too.
