### ISSUE TITLE
several random GuruMeditations with Bluetooth 

### ISSUE THREAD

**Issue by R0MBERT** [espressif/arduino-esp32#4486]
Hello and sorry for a forum newbie, 
even unable to EspExceptionDecode - but I don't believe this would solve my issue in the moment...? 

I have a (sadly complex) stepmotor driving program that is working well via 2 ISR's like
e.g. void IRAM_ATTR timerISR_2() 

Really, fine. But as soon as I add 
#include "BluetoothSerial.h"
the trouble begins. Of course, Bluetooth as a simple application like Serial-To-Bluetooth terminal, works well, too. 

I need it in order to motor control via smartphone, it's working, but randomly and reproducably I get several Gurus. But neither "Core" (sometimes 0 sometimes 1) nor "reason" (sometimes LoadProhibited, sometimes different) are foreseeable or helpful information...

3 examples: 

Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x40028dcf  PS      : 0x00060b30  A0      : 0x8001a63a  A1      : 0x3ffcf290  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000001  A5      : 0x00000000  
A6      : 0x3ffafd68  A7      : 0x3ffafd68  A8      : 0x80028dbd  A9      : 0x3ffcf270  
A10     : 0x3ffcb90c  A11     : 0x00000000  A12     : 0x00000014  A13     : 0x00000008  
A14     : 0x3ffcb900  A15     : 0x00000001  SAR     : 0x0000001b  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000043  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0xffffffff  
Backtrace: 0x40028dcf:0x3ffcf290 0x4001a637:0x3ffcf2d0 0x40019d11:0x3ffcf300 0x40055b4d:0x3ffcf320 0x40168e37:0x3ffcf340 0x4016938d:0x3ffcf360 0x4008eb21:0x3ffcf390
Rebooting...

Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Core 1 register dump:
PC      : 0x400d7c10  PS      : 0x00060034  A0      : 0x80081d98  A1      : 0x3ffbe940  
A2      : 0x00000006  A3      : 0x3ffbedac  A4      : 0x00000000  A5      : 0x40308000  
A6      : 0x3ff42000  A7      : 0x700000eb  A8      : 0x80081161  A9      : 0x3ffbe920  
A10     : 0x00000000  A11     : 0x4058c000  A12     : 0x000007fe  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000014  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x40001609  LEND    : 0x4000160d  LCOUNT  : 0x00000000  
Core 1 was running in ISR context:
EPC1    : 0x40062206  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x400d7c10
Backtrace: 0x400d7c10:0x3ffbe940 0x40081d95:0x3ffbe960 0x4008521d:0x3ffbe980 0x40062203:0x3ffca8c0 0x400947d7:0x3ffca8e0 0x4009480e:0x3ffca910 0x40094b64:0x3ffca940 0x40094db9:0x3ffca960 0x40087995:0x3ffca990 0x40087c0c:0x3ffca9b0 0x400e3373:0x3ffcaa00 0x400e3ac2:0x3ffcaa50 0x400e49a4:0x3ffcaaa0 0x400e2792:0x3ffcaac0 0x400e2d8e:0x3ffcab40 0x400e2199:0x3ffcabb0 0x400d4cf9:0x3ffcabf0 0x400d24a6:0x3ffcac10 0x400d3304:0x3ffcac30 0x400d7835:0x3ffcac50 0x4008eb21:0x3ffcac70
Rebooting...

Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Core 1 register dump:
PC      : 0x4006373b  PS      : 0x00060034  A0      : 0x80080f79  A1      : 0x3ffbe780  
A2      : 0x00000000  A3      : 0x40b53a00  A4      : 0x00000000  A5      : 0x40b90000  
A6      : 0x7ff00000  A7      : 0x000c3a00  A8      : 0x3ff44000  A9      : 0x3ff5f024  
A10     : 0xe00a1000  A11     : 0x00000000  A12     : 0x00000006  A13     : 0x00000000  
A14     : 0xe00a1000  A15     : 0x0012f200  SAR     : 0x0000000d  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  
Core 1 was running in ISR context:
EPC1    : 0x4008161a  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x4006373b
Backtrace: 0x4006373b:0x3ffbe780 0x40080f76:0x3ffbe790 0x40081f09:0x3ffbe7b0 0x40085305:0x3ffbe7d0 0x40081617:0x3ffb1f60 0x400d12d1:0x3ffb1f80 0x400d5201:0x3ffb1fb0 0x40088f2d:0x3ffb1fd0
Core 0 register dump:
PC      : 0x400ee1a2  PS      : 0x00060134  A0      : 0x800d736a  A1      : 0x3ffbbff0  
A2      : 0x00000000  A3      : 0x00000001  A4      : 0x00000000  A5      : 0x00000001  
A6      : 0x00060120  A7      : 0x00000000  A8      : 0x800d6f32  A9      : 0x3ffbbfc0  
A10     : 0x00000000  A11     : 0x00000001  A12     : 0x8008913c  A13     : 0x3ffbbef0  
A14     : 0x00000000  A15     : 0x3ffbbce0  SAR     : 0x00000000  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
Backtrace: 0x400ee1a2:0x3ffbbff0 0x400d7367:0x3ffbc010 0x4008a6ce:0x3ffbc030 0x40088f2d:0x3ffbc050
Rebooting...

Meanwhile, by Verbose, I get plausible things like 
[I][BluetoothSerial.cpp:510] _init_bt(): device name set
[I][BluetoothSerial.cpp:310] esp_spp_cb(): ESP_SPP_START_EVT
[V][BluetoothSerial.cpp:275] esp_spp_cb(): ESP_SPP_DATA_IND_EVT len=6 handle=385

Any idea if I could do something better with 
- ISR configuration? Tried void ICACHE_RAM_ATTR timerISR_2()  already.
- Bluetooth configuration / parameters? 
... ? 

### Hardware:
Board:					ESP32 Dev Module Node32 
Core Installation version:		NO IDEA ? what is it?  ?1.0.0? ?1.0.1-rc4? ?1.0.1? ?1.0.1-git? ?1.0.2? ?1.0.3?
IDE name:				Arduino IDE 1.8.13 
Flash Frequency:			80Mhz
PSRAM enabled:                     DISABLED 
CPU frequency 240MHz (WiFi/BT)   

### or should it be about 
- PSRAM? 
- Partition Scheme? I don't know what it is, here is what ArduinoIDE default setting is: 
"Default 4MB with spiffs (1.2 MB APP/1.5MB SPIFFS)" 
should I temper with that? Or: What must I read about this, if relevant? 

Thank you for any hint, also if regarding my unexperienced use of GitHub - SORRY FOR THAT

**Comment by Bmooij** [comment]
Never call network (bluetooth) operations from a interrupt. especially BluetoothSerial! 
A write to BluetoothSerial could lock a task for a very long time. ([source](https://github.com/espressif/arduino-esp32/blob/dcff2e9774c1a712e601fd62d08a68a5e74dbc62/libraries/BluetoothSerial/src/BluetoothSerial.cpp#L143))

As an alternative you could do something like this:
```cpp

volatile bool _timerFlag = false;

IRAM_ATTR timerISR_2() {
     _timerFlag = true;
}

void loop() {
  if (_timerFlag) {
     timerFlag = false;
     // Your BluetoothSerial call
  }
}
```
If you want a very fancy solution, you could use a [Queue](https://www.freertos.org/a00018.html) in combination with a [Task](https://www.freertos.org/a00019.html)
