### ISSUE TITLE
POOR LTE signal strength CAUSE [WiFiClient.cpp:212] connect(): socket: 23

### ISSUE THREAD

**Issue by mehrdad987** [espressif/arduino-esp32#4504]
**Hardware:**
Board: ESP-WROOM-32 module
Core Installation version: 1.0.4
IDE name: Arduino IDE
Flash Frequency: 80Mhz
PSRAM enabled: dis
Upload Speed: 921600
Computer OS: w10

hi
I'm using esp32 to send data to my server by  http.post
`    HTTPClient http;                           
    http.begin("http://.../esp32");    
    
    http.addHeader("Content-Type", "text/plain");     
    int httpResponseCode = http.POST(buffer_JSON);   
    if (httpResponseCode > 0) {              
      response = http.getString();             
      Serial.println(httpResponseCode);`
After a poor LTE signal strength continues for a while, this error occurs even if it regains the signal strength

**Debug Messages:**
```
17:29:15.200 -> [D][HTTPClient.cpp:265] beginInternal(): host: ---.net port: 80 url: /api/-
17:29:15.233 -> [E][WiFiClient.cpp:212] connect(): socket: 23
17:29:15.233 -> [D][HTTPClient.cpp:996] connect(): failed connect to ---.net:80
17:29:15.233 -> [W][HTTPClient.cpp:1288] returnError(): error(-1): connection refused
17:29:15.233 -> [D][HTTPClient.cpp:369] disconnect(): tcp is closed
```

and after that, if I disconnect wifi and reconnect that it still has that error
```
   WiFi.disconnect(true);
   if (wifiMulti.run() != WL_CONNECTED) { 
       Serial.print("Try to Connect");
    }

```

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md

**Comment by mehrdad987** [comment]
hey
anyone knows about the cause of this error I appreciate if it can help me
