### ISSUE TITLE
UDP send packages crashes

### ISSUE THREAD

**Issue by ImanolGo** [espressif/arduino-esp32#453]
I'm Using Sparkfun ESP32 Thing and sending simple udp messages to a given IP Address. 

```
 //Send a packet
      udp.beginPacket(ipRemote,udpPort);
       for(int i = 0; i< NUM_TOUCH_PINS; i++)
      {
          udp.print(touchRead(touchPins[i]));  // get value using Ti
          udp.print(" ");
      }  
      udp.endPacket();
```

The connection works fine and it's starts sending packages right away. But after a few seconds of sending different values it always crashes, showing:

`
Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
`

I'm not even reading udp messages nor using udp.begin(). 

Maybe you have some insights or workaround to solve this issue.

**Comment by ImanolGo** [comment]
I changed the board to the HIMALAYA ESP32 Dev Board and that solved the issue.

**Comment by me-no-dev** [comment]
that does not explain the reason though... interesting. I have never seen this error

**Comment by lonerzzz** [comment]
@ImanolGo Is this issue still present in the latest software version? Are you able to confirm?

**Comment by ImanolGo** [comment]
@lonerzzz I returned the Sparkfun ESP32 modules so unfortunately I cannot test it against the newest software version.
