### ISSUE TITLE
digtalWrite to PIN 34 and 35 not working

### ISSUE THREAD

**Issue by leonyuhanov** [espressif/arduino-esp32#454]
Is there something special that needs to be done to get GPIO pin 34 and 35 to work as DIGITAL WRITE pins?

```
byte pinNum = 34;
void setup() 
{
  pinMode(pinNum, OUTPUT);
}
void loop() 
{
  digitalWrite(pinNum, HIGH);   
  delay(100);                      
  digitalWrite(pinNum, LOW);   
  delay(50);
}
```
The above code does not work for pins 34 and 35. All other pins work fine. I have tried several boards.
I have one of these [LuaNode ESP32 Dev Board](https://camo.githubusercontent.com/7003d0c415143b35403c6bfd90ceabd230655425/687474703a2f2f696d67302e70682e3132362e6e65742f665f3655445a467347697747484b62617670617245673d3d2f363633323533363731333233333238333238382e706e67)

**Comment by copercini** [comment]
These pins are input only.
page 4 of https://espressif.com/sites/default/files/documentation/esp_wroom_32_datasheet_en.pdf
