### ISSUE TITLE
BLE with Sleep mode

### ISSUE THREAD

**Issue by MihirKhara** [espressif/arduino-esp32#4555]
I wanted to know if it is possible to use BLE as a wake-up source for sleep modes (preferably deep sleep) in Arduino Core.

The ESP-IDF GitHub repo shows that they were going to add this feature in version ESP-IDF v3.1, although there is no official documentation for this on their website that indicates it was added.

I'm using -
Arduino IDE - 1.8.12
Latest ESP32 Arduino Core (v1.0.4)
Board - DOIT ESP32 Devkit v1

I will be hosting a BLE server on ESP32. I would like to add functionality that wakes up the device whenever there is an incoming connection request from a mobile app via BLE.
If a BLE connection is requested, the device should exit deep sleep mode and fetch sensor data, transmit it, and go back to sleep again.

Is there any way this can be implemented in Arduino IDE?
If not in Arduino Core, can it be implemented using ESP-IDF?

**Comment by chegewara** [comment]
Lets think about it. Turn off radio and use radio, is it possible? I think its not.

**Comment by MihirKhara** [comment]
That's the question I have asked. I didn't say anything like turning it off and then using it (which btw is common sense).
My question was, is it possible with Arduino Core, because it seems possible with ESP-IDF according to a few Github issue chats.

**Comment by chegewara** [comment]
The whole idea of sleep mode is to turn off radio which is most power hungry peripheral, but maybe there is some other sleep mode im not aware of.

**Comment by MihirKhara** [comment]
Okay, it seems it's not possible with the current version of Arduino core, will need to find some other workaround.
Thanks for the immediate reply.

**Comment by chegewara** [comment]
There is option to use light sleep mode but requires external XTAL IIRC and is not turned on in arduino, only esp-idf.

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/issues/947#issuecomment-500312453

**Comment by MihirKhara** [comment]
Yeah I did find this, seems like the option to go with right now.

**Comment by chegewara** [comment]
One more thing. This library works pefectly fine with esp-idf, and if you need to use arduino libraries then arduino as component is the way to go.

**Comment by MihirKhara** [comment]
Yes I am aware, just need to import Arduino libraries in Eclipse IDE with ESP-IDF right?

**Comment by chegewara** [comment]
https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md

**Comment by MihirKhara** [comment]
Thanks for posting.
