### ISSUE TITLE
Conflicting wake-up trigger with touch and GPIO interrupt

### ISSUE THREAD

**Issue by yo90bosses** [espressif/arduino-esp32#4556]
I'm trying to get the ESP32 to wake up with the touch sensors and a high signal coming from another device to one of the GPIO pins.
I only want to use light sleep, not deep sleep. As far as I understand (and see here) you can't use touch wake sources while using GPIO wake-up sources.

But is there anyway around this? I need touch for the user interface and GPIO for a radio module I'm using.
The user interface should show up as soon as i touch the inputs and i need to wake the cpu up as soon as the radio module sends an interrupt.

        gpio_wakeup_enable(gpio_num_t(DIO1), GPIO_INTR_HIGH_LEVEL);
        esp_sleep_enable_gpio_wakeup();
        gpio_hold_en(gpio_num_t(TXEN));
        gpio_hold_en(gpio_num_t(RXEN));
        gpio_hold_en(gpio_num_t(NSS));
        gpio_hold_en(gpio_num_t(NRESET));
        touchAttachInterrupt(TOUCHINPUTPIN1, callBack, UserInterface::touchThreshold(0));
        touchAttachInterrupt(TOUCHINPUTPIN2, callBack, UserInterface::touchThreshold(1));
        touchAttachInterrupt(TOUCHINPUTPIN3, callBack, UserInterface::touchThreshold(2));
        esp_sleep_enable_touchpad_wakeup();
        Serial.println("CPU Sleeping");
        esp_sleep_enable_timer_wakeup(5*1000000L);
        delay(10);
        esp_light_sleep_start();
        Serial.println("CPU Awake");

        gpio_hold_dis(gpio_num_t(TXEN));
        gpio_hold_dis(gpio_num_t(RXEN));
        gpio_hold_dis(gpio_num_t(NSS));
        gpio_hold_dis(gpio_num_t(NRESET));

It appears to also work with both (even though im getting an error) but unreliably and sometimes doesnt.

Error message is Conflicting wake-up trigger:

**Comment by trullock** [comment]
Did you solve this?
