### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by sajeelahmed34** [espressif/arduino-esp32#457]
I have attached the link below from where I used code. I hope to get helpful resource from you. Thanks :) ;) https://www.youtube.com/watch?v=uGUrgOV_6ro

**Comment by copercini** [comment]
Hahahahah Don't panic!

You probably are using a local IP only, like 192.168.whatever

For your friend control your LED from the other side of globe, you should you a cloud version https://github.com/marcoschwartz/aREST/blob/master/examples/ESP32_cloud/ESP32_cloud.ino
https://arest.io/cloud

**Comment by sajeelahmed34** [comment]
Hey. Thanks for increasing my hope level. Well, in this code somewhere I
need "UNIQUE ID" so what to put in this ??

Thanks once more'

SajeelAhmed

**Comment by copercini** [comment]
It's the value which you will use in the control link: https://github.com/marcoschwartz/aREST#cloud-access-esp8266

**Comment by me-no-dev** [comment]
Horrible joke incoming: So... you are in Pakistan, your friend is in USA, your issue is DANGEROUS... are you sure you are trying to switch a light bulb and not something else :D

**Comment by sajeelahmed34** [comment]
Haha! I like your sense of humor. Well first of all "THANKS" for your kind
help, you have really solved my problem!
Actually, I am working with my friend to innovate an electronic project in
which we have to use APA102 rgb leds and to control them from Wifi and BLE
device. We are in initial stage and just to check whether we are trying to
glow led or not. I have stucked because I have not worked on esp8266/esp32
before in life. I have no any idea about networking as well but I want to
learn things and get hands on experience on this device. The code you have
provided me open ways for me to think out of box. Thanks! Our purpose is to
control rgb colors from BLE and wifi from anywhere in the world and because
of wifi we called we are globally communicated.

Today, I am working on eclipse IDE because Arduino does not support BLE of
esp32. Have you worked on eclipse? Do you know what is MQTT, OpenHab2. ??
Is this provides me cloud storage or not ??

Sajeel Ahmed

**Comment by lonerzzz** [comment]
@sajeelahmed34 Is this issue resolved? Can we close it?

**Comment by copercini** [comment]
@lonerzzz As I remember this issue was solved then @sajeelahmed34 delete all his posts and change the title, lol
