### ISSUE TITLE
Unauthorized users can't submit PR anymore?

### ISSUE THREAD

**Issue by Heltec-Aaron-Lee** [espressif/arduino-esp32#4578]
Just submitted a new PR #4577 to arduino-esp32 project, but I was told `Merging is blocked. The base branch restricts merging to authorized users.`

Now only authorized users can submit PR?
![image](https://user-images.githubusercontent.com/32860565/100238646-69ebcf80-2f6b-11eb-8963-b98363265f5b.png)

**Comment by lbernstone** [comment]
The UI has changed, not the process.  me-no-dev will merge the PR.

**Comment by Heltec-Aaron-Lee** [comment]
Thanks for your information. Greeting!
