### ISSUE TITLE
pSRAM memory size showing 0

### ISSUE THREAD

**Issue by sanketa-54** [espressif/arduino-esp32#4581]
Make your question, not a Statement, inclusive. Include all pertinent information:

### Hardware:
Board:							ESP32 Wrover standalone kit
Core Installation version:			1.0.4
IDE name:						?Arduino IDE?
Flash Frequency:					?40Mhz?
PSRAM enabled:                                   Not applicable
Upload Speed:					?115200?
Computer OS:                                        ?Windows 10

### Description:
I'm using the ESP32 Wrover standalone chip and trying to detect the psram .
Same I tested on IDF , Its showing me psram memory size = 8388608

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <SPI.h>

#include <Arduino.h>
#include<esp32-hal.h>



void setup() {
  
  Serial.begin(115200);
  //delay(2000);
// pinMode(3,OUTPUT);
// delay(200);
//
//  digitalWrite(3,HIGH);
//  delay(500);

  
  
 // Serial.setDebugOutput(true);
  
}

void loop() {
  Serial.print("Total heap:");
  Serial.println(ESP.getHeapSize());
  Serial.print("Free heap: ");
  Serial.println(ESP.getFreeHeap());
//  Serial.print("TOtal psram size : ");
//  Serial.println(esp_spiram_get_size());
  Serial.print("PSRAM INIT : ");
  Serial.println(psramInit());
   Serial.print("PSRAM Found : ");
  Serial.println(psramFound());
if(psramFound()){
    
//  Serial.print("Total PSRAM using caps:");
//  Serial.println(heap_caps_get_free_size(MALLOC_CAP_SPIRAM));
  Serial.print("Total PSRAM:");
  Serial.println(ESP.getPsramSize());
  Serial.print("Free PSRAM: ");
  Serial.println(ESP.getFreePsram());
  
  }
  delay(2000);
  }
```

### Debug Messages:
```
4:41:22.873 -> [D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
14:41:22.920 -> Total heap:388228
14:41:22.920 -> Free heap: 360968
14:41:22.920 -> PSRAM INIT : 1
14:41:22.920 -> PSRAM Found : 1
14:41:22.920 -> Total PSRAM:0
14:41:22.920 -> Free PSRAM: 0

```

**Comment by me-no-dev** [comment]
did you enable PSRAM in the board menu? You do not need to call `psramInit` that is done at boot if you have selected the proper options

**Comment by sanketa-54** [comment]
ESP wrover dont have option for psram enable.
And its automatically detecting and enabling also.
Can u please mention options ..If I have left something

**Comment by sanketa-54** [comment]
I'm using WROVER-B standalone chip

**Comment by sanketa-54** [comment]
Need to add the following to use on Arduino IDE :
extern "C" {
#include <esp_spiram.h>
#include <esp_himem.h>
}

**Comment by badre2911** [comment]
not work with 8MB psram, it show 4MB

**Comment by lbernstone** [comment]
Please don't hijack closed issues.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/himem.html#the-himem-allocation-api
