### ISSUE TITLE
HTTPUpdate with HTTPC_FORCE_FOLLOW_REDIRECTS?

### ISSUE THREAD

**Issue by AleksaA21** [espressif/arduino-esp32#4582]
Board:							ESP32 Dev Module
IDE name:						Platform.io

I am trying to do HTTPUpdate of the software with httpUpdate.update() method. My HTTPS server needs to redirect before the update. On the esp8266 there was an option to setFollowRedirects() to the httpUpdate object. Here there is no such option? I always get error 302. 

Is there a workaround?

I've fixed it by modifying the HTTPUpdate with my own method that enables HTTP redirects, but I would prefer a universal solution. 

Code that would replicate this issue would go like:
WiFiClientSecure wifiClientSecure;
downloadBufferUrl = "myHttpsUrl";
httpUpdate.update(wifiClientSecure, downloadUrlBuffer);

**Comment by DTTerastar** [comment]
I put in a fix for this.  Should be in master.
