### ISSUE TITLE
ifndef not working for RX2/TX2 redefinition

### ISSUE THREAD

**Issue by jshep321** [espressif/arduino-esp32#4583]
I am trying to redefine the pins for my serial port using Serial2 -- RX2/TX2.  If I comment out the #define in HardwareSerial.cpp, everything works as expected with my new pins.  This works:

```
#ifndef RX2
#define RX2 16 //default
//#define RX2 14 //esp32cam available pin
#endif

#ifndef TX2
#define TX2 17 //default
//#define TX2 15 //esp32cam available pin
```

However, if I #define them in my application, the defaults are used and the #ifndef are ignored.  Any suggestions on how to make these visible *without* editing the (common file) HardwareSerial.cpp?

**Comment by lbernstone** [comment]
`Serial2.begin(9600, SERIAL_8N1, 14, 15);`
If you are doing something more complicated, and really need to use RX2/TX2, please elaborate.
