### ISSUE TITLE
SPIFFS and Preferences

### ISSUE THREAD

**Issue by HelloDB** [espressif/arduino-esp32#459]
Hello, thank you for your project. When will the SPIFFS library be available to Arduino?
Also, what is the maximum capacity of Preferences?

**Comment by me-no-dev** [comment]
SPIFFS is to be implemented soon ;) Preferences is not a large storage. The partition for it is 20K but there are other things stored inside also (wifi, system settings)

**Comment by hellodb** [comment]
Thanks for the reply and look forward to SPIFFS

**Comment by lbernstone** [comment]
Bump. Any ETA from Ivan on SPIFFS?

**Comment by lonerzzz** [comment]
A temporary version is available as detailed here (https://github.com/espressif/arduino-esp32/issues/411)

**Comment by me-no-dev** [comment]
almost there ;) sorry for the delay but there were some unforseen complications with other modules that I am working on. SPIFFS is definitely the next thing to implement into IDF and VFS

**Comment by me-no-dev** [comment]
SPIFFS is in
