### ISSUE TITLE
Enable core dump to flash feature

### ISSUE THREAD

**Issue by tietzedk** [espressif/arduino-esp32#4598]
I am trying to debug some rare crashes on a remote located device that is connected to the local network.

It would be help full if the core dump to flash feature that is present in the ESP32-IDF, is enabled in the ESP32 arduino framework so that the core dump can be downloaded from the webserver in the ESP32 device.

**Comment by sabado** [comment]
This is a very useful feature. Only a bot can stale this.

**Comment by vadimceb** [comment]
Is there any plan for this feature?
