### ISSUE TITLE
ESP32 factory reset or update bootloader

### ISSUE THREAD

**Issue by Montepaso** [espressif/arduino-esp32#4607]
Hello,

I uploaded code with Arduino IDE in bootloader mode after pressing BOOT+EN buttons on ESP32 DEV KIT V1. Serial monitor was showing:
rst:0x1 (POWERON_RESET),boot:0x7 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download

After that when i upload any sketch it competes ok but does nothing. Cant find any guide on intranet how to reset or update bootloader. Is there a simple way to fix this?

Now if restart ESP32 it does nothing just says:
`rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac
ets Jun  8 2016 00:22:57
`

**Comment by lbernstone** [comment]
https://www.youtube.com/results?search_query=getting+started+esp32+arduino
Arduino uploads the 2nd stage bootloader along with your firmware.
