### ISSUE TITLE
Using Timer Interrupt Causing Core 1 was running in ISR Context

### ISSUE THREAD

**Issue by danishahmed219** [espressif/arduino-esp32#4613]
I was using timer interrupt in my code which was interrupting after every 7200 microseconds. In the loop section of the code. I was checking wifi connectivity after 10 seconds. If it is not connected then I was calling wifi.begin function. I notice whenever it connect to the wifi using this function or using wifi.reconnect Core 1 was running in ISR exception comes up. While I was using IRAM ATTR with my timer interrupt handler.

**Comment by alexvazquez** [comment]
> I was using timer interrupt in my code which was interrupting after every 7200 microseconds. In the loop section of the code. I was checking wifi connectivity after 10 seconds. If it is not connected then I was calling wifi.begin function. I notice whenever it connect to the wifi using this function or using wifi.reconnect Core 1 was running in ISR exception comes up. While I was using IRAM ATTR with my timer interrupt handler.

I have the same issue. Did you find out how to solve it? Thanks
