### ISSUE TITLE
SSP Functionality Incomplete

### ISSUE THREAD

**Issue by richardclli** [espressif/arduino-esp32#4622]
I have tried to make use of SSP and setup ESP32 device as slave to accept binding request from smart phones, PCs, etc.  However I figure out that the SSP implementation is incomplete.  Normally the binding process involves the Smart Phone initiate a binding request with a key code.  User can verify the code in the ESP32 device screen, and select the desire action (either accept or reject) in the ESP32 device.

However, just make use of the BluetoothSerial API cannot make the job done.  The API seems missing some callbacks mechanism for the binding process.

I need to copy and modify the BluetoothSerial source code to make this works, and I think I can contribute my work to the source as a pull request.  So, if I do this, is there anybody who will review the code and merge it?

**Comment by me-no-dev** [comment]
Yup :) please make the pull request :)
