### ISSUE TITLE
WiFi issue in SoftAP and Station Mode

### ISSUE THREAD

**Issue by naakhtar** [espressif/arduino-esp32#4623]
### Hardware:
Board:							ESP32-DOWD
Core Installation version:			1.9
IDE name:						Docklight
Flash Frequency:					
PSRAM enabled:                                    
Upload Speed:					115200bits/sec
Computer OS:                                        WINDOW 7

### Description:
Describe your problem here
> Esp32 module while using WIFI mode in SoftAP and station in both getting below issue.

> After executing (AT+RESTORE) all other command gives -y only.
For example. 
> Restore Command (AT+RESTORE) it gives status Ok. 
> Execute WIFI mode command (AT+CWMODE) receive status  [RX} –y, 
> Execute all other command receive status [RX] - y .  

![esp32](https://user-images.githubusercontent.com/75293334/101868493-77c46600-3ba3-11eb-8435-887f81207a30.png)

**Comment by lbernstone** [comment]
If you are running arduino code, please post it.  Otherwise, move your issue to https://esp32.com

**Comment by naakhtar** [comment]
“AT+HTTPCLIENT=1,3,"http://103.43.40.23:8581/UPSData/GS19183100001DCB","103.43.40.23:8581",,1” command to test .
