### ISSUE TITLE
BLE more services with different characteristics

### ISSUE THREAD

**Issue by thewizard1983** [espressif/arduino-esp32#463]
I am developing a BLE application and I need to create different services; some 32bit uuid, some 128bit uuid.
Eg. 
0x1800
0x180A
0x180D
+ 128bit custom uuid

How can I do this?
I am only able to create 1 uuid service,

**Comment by me-no-dev** [comment]
This is not a complete code, but you will get the idea:
https://gist.github.com/me-no-dev/64db423cd2037c5842d05393f73ab09c
