### ISSUE TITLE
How many bytes is the payload size of UDP?

### ISSUE THREAD

**Issue by testuserlog** [espressif/arduino-esp32#4642]
libraries/WiFi/src/WiFiUdp.cpp
MTU =1500 , IP header size =20 ,TCP header size = 20,UDP header size = 8
payload 
TCP = 1500 - 20 -20 = 1460
UDP = 1500 -20- 8 =1472 

1460 is for TCP, and 1472 for UDP.
But WiFiUdp is 1460 , shouldn't it be 1472?

**Comment by Syed-ATiFHashmi** [comment]
how to increase udp-RX payload
1 want to receive 11500 bytes of datagram or packet
for live video stream over udp socket
