### ISSUE TITLE
BLE doesn't start advertise automatically after disconnection.

### ISSUE THREAD

**Issue by JLightMedia** [espressif/arduino-esp32#4644]
Hi everyone! 
I worked in 1.0.4 version, but after update MAC OS to BigSur I had to update to 1.0.5 library because the old version didn't work more.
But after that I have noticed one issue with advertise function. In setup function I start advertise BLE service, but when client disconnected from BLE server, ESP32 don't start advertising again. I fixed that added addition line in Callbacks service 

```cpp
     void onDisconnect(BLEServer* pServer) {
      pServer->getAdvertising()->start();
    }
```

Why BLE library doesn't start Advertising again, when client disconnected?

**Comment by chegewara** [comment]
Its not starting advertising after disconnect because its not always expected or required.

**Comment by raphael-bmec-co** [comment]
Seeing the same issue.

**Comment by chegewara** [comment]
Not an issue, it is intended.

**Comment by raphael-bmec-co** [comment]
Okay thank you. Can you confirm this is a change from 1.0.4?

**Comment by chegewara** [comment]
Its not a change, it was from beginning.

**Comment by raphael-bmec-co** [comment]
Good to know. Thanks again. Much appreciated.
