### ISSUE TITLE
ADC conflicts UART (Serial2)

### ISSUE THREAD

**Issue by slavendam** [espressif/arduino-esp32#4649]
Hi!
I'm using ESP32 WROOM. I connected GPS over UART (Serial 2 - pins 16 and 17) and it works like it should. 
But after I added line for analog reading on GPIO34, my Serial2 doesn't work anymore, it blocks, no communication. I'm using "analogRead(34);" for reading.
Does anyone have some idea what to do? 

Thanks

**Comment by mehrdad987** [comment]
[https://github.com/espressif/arduino-esp32/issues/782](url)
