### ISSUE TITLE
WiFi.disconnect() does not actually disconnect.

### ISSUE THREAD

**Issue by sticilface** [espressif/arduino-esp32#465]
Need to replace it with the actual disconnect function.

http://esp-idf.readthedocs.io/en/latest/api-reference/wifi/esp_wifi.html#_CPPv219esp_wifi_disconnectv

```cpp
bool WiFiSTAClass::disconnect(bool wifioff)
{
    bool ret;
    ret = esp_wifi_disconnect() == ESP_OK;

    if(wifioff) {
        WiFi.enableSTA(false);
    }

    return ret;
}
```

**Comment by sticilface** [comment]
https://github.com/espressif/arduino-esp32/pull/466

**Comment by lonerzzz** [comment]
@sticilface Is this issues completely covered by https://github.com/espressif/arduino-esp32/pull/466. Can we close this issue?

**Comment by copercini** [comment]
Solved in https://github.com/espressif/arduino-esp32/pull/466
