### ISSUE TITLE
unused parameter in BLERemoteService::getCharacteristics()

### ISSUE THREAD

**Issue by cyberman54** [espressif/arduino-esp32#4660]
My compiler complains on a unused, but set, parameter in `BLERemoteService::getCharacteristics()`:

`*pCharacteristicMap = m_characteristicMapByHandle; `
ist set, but neither used in the function, nor returned by it.

Maybe shall this function have a return value, other than void()?

/cc @kolban

**Comment by chegewara** [comment]
I dont remember now why there is 2 `getCharacteristics()`, but you can use this one:
https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/src/BLERemoteService.cpp#L217

**Comment by cyberman54** [comment]
@chegewara thanks for the hint! Would be nice to delete the redundant function, if not needed (where?), to get rid of the compiler warning.

**Comment by chegewara** [comment]
Feel free to make PR, for example add this in function with warning:
`(void)pCharacteristicMap`

**Comment by cyberman54** [comment]
I am careful to make changes here, as long as i don't know sure what i am doing in this code.

**Comment by chegewara** [comment]
It is easy change, you can try it in your code. That change does nothing in code except is fooling compiler.

**Comment by cyberman54** [comment]
issue is now adressed by PR #4669
