### ISSUE TITLE
How i can use the Internal RTC of the ESP32 without NTP? I want to set the time Manuell.

### ISSUE THREAD

**Issue by Trackhe** [espressif/arduino-esp32#4662]
How i can use the Internal RTC of the ESP32 without NTP? I want to set the time Manuell.

I use the Arduino IDE.

Board:							ESP32 Dev Module
Core Installation version:			I dont know?
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                    no
Upload Speed:				       460800
Computer OS:                                        Mac OSX

### Description:
I dont know to set the Time without NTP
```
 configTime(gmtOffset_sec, daylightOffset_sec, ntpServer);
```
Without NTP no working and i dont find any solution without NTP and External RTC.

**Comment by thomasleftwite** [comment]
use "ESP32Time" library.
