### ISSUE TITLE
Intermittently fail to connect when uploading code on SparkFun ESP32 Thing

### ISSUE THREAD

**Issue by dwc309** [espressif/arduino-esp32#4663]
How does one fix an connection issue on the usb serial port when uploading code after a rebuild of the code in the Arduino IDE?

I am trying to re-build the code and upload it.  This will only sporadically work.  

I am running on a HP Elitebook running Windows 10 Pro.  Arduino IDE 1.8.13 which is the latest according to the Arduino site. 

Am getting the following error when trying to rebuild then re-upload the sketch.
 
It doesn't matter what sketch is being used.  I also doesn't matter which ESP32 Thing is used as I've tried 2.  I believe that I had both of them working with this same setup several months ago.  I have added other programs during that time.  The only other USB devices are a Trackball.

Interestingly, each ESP32 Thing uses a different COMM port, one is 4 and the other is 5.

In the Device Manager, the ESP32 Thing is the only device that shows in the Ports  (Comm & LPT).  It is detected right away when the USB cable is connected.

The error output is below 

Sketch uses 213337 bytes (16%) of program storage space. Maximum is 1310720 bytes.
Global variables use 15380 bytes (4%) of dynamic memory, leaving 312300 bytes for local variables. Maximum is 327680 bytes.
esptool.py v2.6
Serial port COM5
Traceback (most recent call last):
  File "esptool.py", line 2959, in <module>
  File "esptool.py", line 2952, in _main
  File "esptool.py", line 2652, in main
  File "esptool.py", line 222, in __init__
  File "site-packages\serial\__init__.py", line 88, in serial_for_url
  File "site-packages\serial\serialwin32.py", line 62, in open
serial.serialutil.SerialException: could not open port 'COM5': WindowsError(5, 'Access is denied.')
Failed to execute script esptool
the selected serial port Failed to execute script esptool
 does not exist or your board is not connected
  

When searching the net for the error, there is an indication that something else is using the serial port but there is nothing else connected to the laptop right now.  There is also suggestions made that the ESP32 Thing doesn't get closed or the build process tries to open it again.  To my knowledge, this is not under my control.  There are a number of "fixes" but none of the them have worked so far.

I have attempted to close the serial monitor in the Arduino IDE and then re-open it.  That worked once but hasn't since.  I have uninstalled the Arduino IDE and re-installed it.  That didn't change the issue.  I have unplugged the USB cable multiple times and that doesn't always work.

```

**Comment by chegewara** [comment]
That board is equipped with FT231X UART to USB and as far as i remember you need to install drivers on windows. You see 2 COM port in manager because that FTDI is dual port.
