### ISSUE TITLE
availableForWrite missing from Print.h

### ISSUE THREAD

**Issue by drmpf** [espressif/arduino-esp32#4665]
### Hardware:
Board:							All
Core Installation version:			Latest gitHub Master 29th Dec 2020
IDE name:					Arduino-esp32/core
Flash Frequency:			        N/A
PSRAM enabled:                                N/A
Upload Speed:					N/A
Computer OS:                                    All

### Description:
int availableForWrite()  method is missing from Print.h
This causes ESP32 compiles to fail with Arduino compatible libraries that use Stream or Print and call availableForWrite()
(The ESP8266 lib has availableForWrite() method in Print.h)
Merge PULL request  https://github.com/espressif/arduino-esp32/pull/4664 to fix this

**Comment by jandrassy** [comment]
duplicate of https://github.com/espressif/arduino-esp32/issues/4336
