### ISSUE TITLE
Add WifiServer .on() method

### ISSUE THREAD

**Issue by joeybab3** [espressif/arduino-esp32#468]
The current wifi server implementation seems to be lacking a ".on()" method as the example only has a currentline.endsWith() example which is harder to work with.

**Comment by copercini** [comment]
As far as I know, @me-no-dev is working o SPIFFS library for the full port of ESP8266WebServer.

For now, I have a example using SimpleWiFiServer which may can help you: https://github.com/copercini/esp32-iot-examples/blob/master/WiFi_portal/WiFi_portal.ino#L170
