### ISSUE TITLE
Restarting ESP32 - rst:0x1 (POWERON_RESET)

### ISSUE THREAD

**Issue by Anton2k** [espressif/arduino-esp32#4689]
Hi, more of a question than an issue, I am trying to restart my ESP32, but by
`rst:0x1 (POWERON_RESET)` 
rather than
`rst:0xc (SW_CPU_RESET)` which calling `ESP.restart();` in the Arduino IDE achieves.

By board is a LILYGO T5 v2.3 (ESP32), it has a physical reset button and when pressing it produces this `rst:0x1 (POWERON_RESET)`  condition, just want to know if there is a way to force this via code in my sketch.

Thanks

**Comment by mike-s123** [comment]
Have you tried hairpinning a GPIO back into EN, then setting that GPIO low?

**Comment by Anton2k** [comment]
@mike-s123 never thought of that but I'll give it a go.
