### ISSUE TITLE
Equivalent to ESP.getVcc() on ESP8266?

### ISSUE THREAD

**Issue by kaofishy** [espressif/arduino-esp32#469]
Hi,

I'm wondering if there is an equivalent to the ESP.getVcc() function that's available in the ESP8266 Arduino core. I see that in the ROM library there is rom_phy_get_vdd33() but the name suggests it's used by the (WiFi? BT?) PHY so would it be safe to use when WiFi or BT is on? From some quick testing it seems to work the same as ESP.getVcc() from ESP8266.

Tony

**Comment by rmhomecouk** [comment]
I don't suppose you have an example for this please?

**Comment by rummyr** [comment]
Corking!
extern "C" int rom_phy_get_vdd33();

Using arduino IDE I find that this call returns valid values if WiFi or Bluetooth are "ON"...
Not tried it in anger yet, so can't say if it interferes with proper operation though it seems to only take ~45 microSec, so it's not doing much.

FWIW if you don't need Wifi/BT then btStart and btStop seem to be MUCH faster than Arduino WiFi.mode(WIFI_STA) and WiFi.mode(WIFI_OFF), though that could well be Arduino getting in the way.

I believe that even after turning bt or wifi off will still consume a higher baseline power than if you never turn them on.

**Comment by AusUser5** [comment]
Do you have an example? on my esp32 I looped the wifi scanner sketch to turn on wifi and still get a reading of 0

**Comment by kosso** [comment]
I'm confused why there is no ESP32 equivalent to `ESP.getVcc()`

This seems like something many people would need.

Or am I missing something obvious why the ESP32 doesn't have this basic method?

**Comment by ldab** [comment]
Especially for battery powered setups.

**Comment by marcelstoer** [comment]
@me-no-dev closing because of what exactly?

**Comment by atanisoft** [comment]
@marcelstoer unsupported as there is no built-in functionality for this.

**Comment by AndreKR** [comment]
For people who come here from searches, we should mention the equivalent code:
```c
extern "C" int rom_phy_get_vdd33();
float voltage = ((float)rom_phy_get_vdd33()) / 1000;
```

**Comment by atanisoft** [comment]
@AndreKR Unfortunately that function is not exposed in the supported APIs and is not guaranteed to return any valid data.

**Comment by AndreKR** [comment]
It does return valid data on all ESP32 I own.

I don't think it matters if it's official or not, it's not like the Espressif documentation is very accurate.

**Comment by atanisoft** [comment]
@AndreKR while it may work on the boards you have there is absolutely no guarantee that it will always work. It is not recommended to use internal / non-exposed APIs for any purpose...

**Comment by nutfrey** [comment]
Obviously there must be some way to read this, otherwise how are brownouts detected?

**Comment by paolovr70** [comment]
Unfortunately sometime it works in other cases not. For instance, in my case when ESP32  is connected to wifi it reports 0.5v and when it is disconnect volts are is 5.6v .

`extern "C" int rom_phy_get_vdd33();
float voltage = ((float)rom_phy_get_vdd33()) / 1000;
`

**Comment by TheRealDJ** [comment]
Couldn't you just jump Vcc to an analog input are read said analog input?

**Comment by lbernstone** [comment]
Run it through a voltage divider to 1V1- but yes, you should read this through the ADC.  The internal meter was unreliable, that is why the function was not supported, and ultimately removed.

**Comment by jockm** [comment]
> Couldn't you just jump Vcc to an analog input and read said analog input?

Assuming you have control of the schematic, but if you are trying to add a feature to an existing board that cannot be changed.  Being able to read the internal voltage is a very useful feature if it can be implemented
