### ISSUE TITLE
Data loss when receiving from the Queue

### ISSUE THREAD

**Issue by hmhuang0501** [espressif/arduino-esp32#4697]
Hi, I am doing a project with writing two tasks both pinned to core 0 with TTGO LoRa ESP32 as a server device. One task (say, Task 1) for sending data (which is received from other client esps via LoRa radio) to the Queue, one (say, Task 2) for receiving data from the Queue. 

The code for Task 1 is below:
```cpp
xTaskCreatePinnedToCore( receiveWiFiDeviceData,             // Task function
                             "TaskForReceivingWiFiDeviceData",  // Task name
                             10000,                             // Stack size in words
                             NULL,                              // Parameter passed as input to task
                             1,                                 // Task priority
                             NULL,                              // Task handle
                             0 );                               // Core ID
```
```cpp
void receiveWiFiDeviceData( void* parameter )
{
  LoRa.receive();   // puts the radio in continuous receive mode

  for(;;)
  {
    receiveFromSlaveDevice( LoRa.parsePacket() );
    
    delay(100);
  }

} // receiveWiFiDeviceData
```
```cpp
void receiveFromSlaveDevice( int packetSize )
{
  if ( !packetSize )
  {
    return;
  }
  else
  {
      wifiDevicePayload WiFiDevicePayload;

      // read packet
      int recipient = LoRa.read();
      int sender = LoRa.read();
      
      String incomingPayload = "";   // payload of incoming WiFi device packet
      while ( LoRa.available() )
      {            
        incomingPayload = LoRa.readString();
        // incomingPayload format: packetID + '/' + MAC address + '\t' + RSSI + '\n'
      }
      
      if ( recipient != localAddress )
      {
        //Serial.println( "ERROR - Recipient address does not match local address!" );
        return;
      }

      WiFiDevicePayload.slaveID = sender;
 
      int pos1 = incomingPayload.indexOf('/');
      int pos2 = incomingPayload.indexOf('\t', pos1);
      int pos3 = incomingPayload.indexOf('\n', pos2);

      WiFiDevicePayload.packetID = (uint32_t) strtoul( incomingPayload.substring(0, pos1).c_str(), NULL, 0 );    // packetID
      strcpy( WiFiDevicePayload.mac, incomingPayload.substring(pos1 + 1, pos2).c_str() );                        // MAC Address
      WiFiDevicePayload.rssi = (int8_t) incomingPayload.substring(pos2 + 1, pos3).toInt();                       // RSSI

      // display payload information:
      //printWiFiDevicePayload( WiFiDevicePayload );

     xQueueSend( g_queueBetweenReceiveAndLog, &WiFiDevicePayload, portMAX_DELAY );
  }

} // receiveFromSlaveDevice
```

The code for Task 2 is below:
```cpp
 xTaskCreatePinnedToCore( logWiFiDeviceData,                        // Task function
                                         "TaskForLoggingWiFiDeviceData",    // Task name
                                         10000,                                           // Stack size in words
                                         NULL,                                            // Parameter passed as input to task
                                         0,                                                  // Task priority (0 is the lowest priority)
                                         NULL,                                            // Task handle
                                         0 );                                                // Core ID
```

```cpp
void logWiFiDeviceData( void* parameter )
{
  wifiDevicePayload payload;

  for(;;)
  {
    for ( size_t i = 0; i < cg_queueSizeBetweenReceiveAndLog; ++i )
    {
      xQueueReceive( g_queueBetweenReceiveAndLog, &payload, portMAX_DELAY );
      
     if ( strcmp( payload.mac, DESIRED_DEVICE_MAC_ADDRESS ) == 0 )
      {
        Serial.println( "MAC matched!" );
        Serial.print( "Slave ID = " );
        Serial.println( payload.slaveID );
        Serial.print( "MAC = " );
        Serial.println( payload.mac );
        Serial.print( "RSSI = " );
        Serial.println( payload.rssi );
        Serial.print( "Packet ID = " );
        Serial.println( payload.packetID ); 
      }
     }
     vTaskDelay( 1 / portTICK_PERIOD_MS );
  }

} // logWiFiDeviceData
```

The struct wifiDevicePayload is defined as:
```cpp
typedef struct
{
  char mac[100] = {0};
  uint32_t packetID;
  int8_t rssi;                           
  int8_t slaveID;

} __attribute__((packed)) wifiDevicePayload;
```

The output is as follows:
![2021-01-09 00 10 38](https://user-images.githubusercontent.com/43208378/104075873-8dfe2a00-5214-11eb-8884-249c41c06b03.jpg)

**My question is: why are the information of payload.slaveID, payload.rssi, payload.packetID (which are type of int8_t, int8_t, uint32_t, respectively) got lost after transmitted by the Queue?**
I am sure that the three members have non-zero values before sending into the Queue. They should be something like:

```
MAC matched!
Slave ID = 4
MAC = 38:10:D5:5C:58:62
RSSI = -76
packetID = 3465
```

**What could be the reason of this strange behavior and how can I resolve this problem?**
I really can't figure out why I got this result and have nothing to do with this weird issue.....
Any help is greatly appreciated!

**Comment by chegewara** [comment]
This is only half code. We dont see xQueueSend part, so hard to say.

**Comment by hmhuang0501** [comment]
@chegewara Thanks for reminding me! I added them into the post.

**Comment by chegewara** [comment]
> WiFiDevicePayload.rssi = (int8_t) incomingPayload.substring(pos2 + 1, pos3).toInt(); 

Did you confirm this value is correct? I think it should be `pos3 - 1`. Either way, did you print this value to logs to make sure it is expected value and different than received by xQueueReceive?

> WiFiDevicePayload.packetID = (uint32_t) strtoul( incomingPayload.substring(0, pos1).c_str(), NULL, 0 ); 

Same question here.

**Comment by hmhuang0501** [comment]
> > WiFiDevicePayload.rssi = (int8_t) incomingPayload.substring(pos2 + 1, pos3).toInt();
> 
> Did you confirm this value is correct? I think it should be `pos3 - 1`. Either way, did you print this value to logs to make sure it is expected value and different than received by xQueueReceive?
> 
> > WiFiDevicePayload.packetID = (uint32_t) strtoul( incomingPayload.substring(0, pos1).c_str(), NULL, 0 );
> 
> Same question here.

@4695  Yes, I did compare the values before and after the Queue. The output is below:
![2021-01-09 11 00 57](https://user-images.githubusercontent.com/43208378/104089038-b1a08f00-526b-11eb-8a6f-fd09ac009510.jpg)

As you can see, the payload.mac didn't lose but the other three did. I only come up with the data type of each of them may be related to this problem. Really strange....

**Comment by chegewara** [comment]
I didnt see Serial logs from received packets, thats why i asked.
QueueSend/Receive code looks good to me.


btw, in my opinion you should simplify packets format:
`incomingPayload format: packetID + '/' + MAC address + '\t' + RSSI + '\n'`
to
`incomingPayload format: packetID + RSSI + MAC address` - packetID is uint32_t, RSSI is int8_t, so it is 5 bytes, remaining is MAC, which is easier to parse.

**Comment by hmhuang0501** [comment]
@chegewara Thank you very much for your help! I solved this issue by moving char mac[100] = {0}; as the last member in the struct as you said. I never come up with this problem could be from the order of struct members. Could you give me some explanations why this is the case? Thanks!

**Comment by chegewara** [comment]
I dont have good explanation for that, just i thought when mac is shorter than 100 bytes, then for some reason rssi and slaveID are taken from mac, which is all 0s. Maybe its some weird compiler optimization or something else i dont know yet.
