### ISSUE TITLE
ESP32-S2 I2C does not honor repeated-start (no stop) in API?

### ISSUE THREAD

**Issue by ladyada** [espressif/arduino-esp32#4729]
hey @me-no-dev[ i verified someone trying an ESP32-S2 with an lc709203f](https://forums.adafruit.com/viewtopic.php?f=63&t=173731) and i _am pretty sure_ that the issue is that when we ask for no-stop in `uint8_t TwoWire::endTransmission(bool sendStop)` its sending a stop anyways.

This is the correct I2C transaction to read the ID code (on avr chipset)
![image](https://user-images.githubusercontent.com/1214161/104860412-67697e80-58f9-11eb-83a0-d6a3a209dc2b.png)
we write 0x11 register command to i2c device 0xB, don't stop, then read 3 bytes of data

if we run the same code on ESP32-S2 I get:
![image](https://user-images.githubusercontent.com/1214161/104860432-954ec300-58f9-11eb-96e3-9d2efd416994.png)
(there's a delay due to serial printf)
with wrong data 0xFF

if we go back to avr and turn ON stop (which is incorrect), we get the same resulting trace:
![image](https://user-images.githubusercontent.com/1214161/104860454-b7e0dc00-58f9-11eb-94c5-6c335a5a0b0e.png)
same wrong data

this could be the root cause for
https://github.com/espressif/arduino-esp32/issues/4589
https://github.com/espressif/arduino-esp32/issues/4561
https://github.com/espressif/arduino-esp32/issues/4375
https://github.com/espressif/arduino-esp32/issues/4403

those are also repeated-start devices. not all i2c devices require repeated start

**Comment by me-no-dev** [comment]
@ladyada sorry for the delay. I2C for S2 uses ESP-IDF's I2C driver. I did not find a way to ensure no-stop there and remember that in order for that to work, write and read need to happen in one bus transaction (not really Arduino-friendly and with possible multitasking issues). Unfortunately we have not heard from @stickbreaker in a loong time (he was maintaining the driver) but we are looking into getting some help internally to be able to handle that in near future.

**Comment by ladyada** [comment]
hihi thanks for replying - there's quite a few chips that require write-then-read in one no-stop transaction. we haven't heard of this problem before for ESP32 (just S2) so it could be a regression in v4.2 or for S2

either way its OK if there's a separate call just for write-then-read added, we have abstracted away the API for all our sensors so we could easily add that exception - just let me know :)

**Comment by erichiller** [comment]
Is there a surround workaround for this? Perhaps @ladyada you know of one?
I'm encountering this with:
* Adafruit ESP32-S2 Metro
* Adafruit MLX90640 (55°)

**Comment by ladyada** [comment]
there is no work-around, it must be fixed here/IDF :)

**Comment by me-no-dev** [comment]
we are aware of the issue, it will be fixed before 2.0.0 is released :)

**Comment by ladyada** [comment]
awesome thank you @me-no-dev  :)

**Comment by VojtechBartoska** [comment]
This issue is solved internally in ESP-IDF ([IDF-3460](https://jira.espressif.com:8443/browse/IDF-3460)

**Comment by hallard** [comment]
ahah Just came up here after scratching my head for 2 hours trying to have battery monitoring on Metro ESP32 S2. Glad to see it's not on our side. Just let us know if there is a fixed branch to test before official release of 2.0.0

**Comment by SuGlider** [comment]
@ladyada , I just submitted a PR #5664 that shall fix the issue you reported.
Could you please apply it to your environment and verify if it solves this issue?

Thanks!

**Comment by ladyada** [comment]
@SuGlider LC709 works right now, so it seems to have solved at least that issue!

**Comment by me-no-dev** [comment]
Hi @ladyada could you please re-test with this new PR: https://github.com/espressif/arduino-esp32/pull/5683
I have only MLX90614 as sensor that requires repeated start and that worked without issues.
