### ISSUE TITLE
WebServer.h POST receive example

### ISSUE THREAD

**Issue by redakker** [espressif/arduino-esp32#4730]
Hi,

Could you provide me a POST receiving example for ESP32?
Maybe it is my fault but I have not found it yet.

I would like to get the **body** of the POST request (**not** a file upload). How can I do that?

Thank you!

**Comment by mehrdad987** [comment]
[https://github.com/G6EJD/ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory](url)

**Comment by redakker** [comment]
> [https://github.com/G6EJD/ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory](url)
@mehrdad987 I have no result under that link

**Comment by redakker** [comment]
@mehrdad987 Sorry, got it. I needed to copy-paste instead of clicking on it.
Thx

**Comment by StevenDeRoover** [comment]
> @mehrdad987 Sorry, got it. I needed to copy-paste instead of clicking on it.
> Thx

Did you manage to get the values of a POST form?

I'm too struggling with this.

**Comment by redakker** [comment]
> > @mehrdad987 Sorry, got it. I needed to copy-paste instead of clicking on it.
> > Thx
> 
> Did you manage to get the values of a POST form?
> 
> I'm too struggling with this.

I've solved with GET request for the time being. I have not tried it yet.

**Comment by StevenDeRoover** [comment]
I did find a solution:
`server.on("<post uri>", HTTP_POST, [] {
    server.arg("<input from HTML form>").toCharArray(<variable>, <length of variable>);
    server.sendHeader("Connection", "close");
    server.send(200, "text/plain", "OK");
});`

**Comment by rferrese** [comment]
An example of this would be really helpful.

**Comment by lbernstone** [comment]
I don't know if the cert validation still works, but the POST args definitely do.
https://github.com/lbernstone/setCerts/blob/master/setCerts.ino
