### ISSUE TITLE
WiFi.localIP() returns 255.255.255.255 after connect

### ISSUE THREAD

**Issue by SvenArke** [espressif/arduino-esp32#4732]
### Hardware:
Board:							ESP32-WROOM-32
Core Installation version:			        1.0.4 & 1.0.5 rc6
IDE name:						Arduino 1.8.13

### Description:

With 1.0.6 - any version i get always 255.255.255.255 as IP address from WiFi.localIP()

Code:
      log_i("Connected to: ");
      log_i( "%s", WiFi.SSID() );
      log_i( "%s", WiFi.localIP().toString().c_str() );

Core 1.0.4 returns:
[I][Test-2020.ino:85] setup(): Connected to: 
[I][Test-2020.ino:86] setup(): NET1
[I][Test-2020.ino:87] setup(): 192.168.0.169

Core 1.0.5 rc1 to rc6 returns:
[I][Test-2020.ino:85] setup(): Connected to: 
[I][Test-2020.ino:86] setup(): NET1
[I][Test-2020.ino:87] setup(): 255.255.255.255

Tested all rc versions - no luck. Code runs only on 1.04 flawless. Any suggestions ?

Thank you !

**Comment by SvenArke** [comment]
Found the problem !
Sketch contained a bugfix for "hostname not sent via dhcp" - >https://github.com/espressif/arduino-esp32/issues/2537

WiFi.config(INADDR_NONE, INADDR_NONE, INADDR_NONE); 

This kills WiFi.localIP() on Core 1.0.5 rc6 ...

**Comment by me-no-dev** [comment]
done :) thanks for finding this

**Comment by gerab** [comment]
wow, surprisingly it's still there!

**Comment by thomastech** [comment]
Yes, I ran into this bug too. As mention before, no problem if I remove the bugfix for "hostname not sent via dhcp" - >#2537. Is that the final/only solution? Hoping for some words of wisdom from the devs.

**Comment by VojtechBartoska** [comment]
@me-no-dev Can you please test this again?

**Comment by YordanYanakiev** [comment]
Same issue here in all around the projects. :'(

**Comment by VojtechBartoska** [comment]
@YordanYanakiev tested on v2.0.3-rc1?

**Comment by YordanYanakiev** [comment]
yes, also the previous ones downto 2.0.0

**Comment by SuGlider** [comment]
This issue is linked to #6610

**Comment by SuGlider** [comment]
The main issue is that <lwip/inet.h> declares ```#define INADDR_NONE IPADDR_NONE``` and it includes <lwip/ip4_addr.h> that declares ```#define IPADDR_NONE ((u32_t)0xffffffffUL)``` (IP 255.255.255.255)

When <lwip/inet.h> is included, it makes the Arduino declaration of "IPAddress INADDR_NONE(0,0,0,0)" invalid. 

This process occurs in all the WiFi/ETH Arduino Libraries.

**Comment by SuGlider** [comment]
This is the test case used to verify/test this issue and PR Fix:

``` cpp
#include <Arduino.h>
#include <WiFi.h>

void setup() {
  WiFi.begin("Your_SSID", "Your_wifi_password");
  String nodeName = "NODE-" + WiFi.macAddress();
  nodeName.replace(":", "");
  char _nodeName[20]; nodeName.toCharArray(_nodeName, 20);
  WiFi.setHostname(_nodeName);
  WiFi.config(INADDR_NONE, INADDR_NONE, INADDR_NONE);
  WiFi.mode(WIFI_STA);

  log_i("Connected to: ");
  log_i( "%s", WiFi.SSID() );
  log_i( "%s", WiFi.localIP().toString().c_str() );
  log_i( "%s", WiFi.getHostname());
}

void loop() {
}
```

**Comment by rysiulg** [comment]
In This arduino libraries bugs and workaround for hostname on esp32 ...
any version i get always 255.255.255.255 as IP address from WiFi.localIP()

use:
 WiFi.config(((u32_t)0x0UL),((u32_t)0x0UL),((u32_t)0x0UL)); 
or 
#ifdef INADDR_NONE
#undef INADDR_NONE
#define INADDR_NONE ((u32_t)0x0UL)
#endif
WiFi.config(INADDR_NONE ,INADDR_NONE ,INADDR_NONE );


to get config definitions of ip 0.0.0.0 and be able to obtain dhcp values. 
By default arduino resolves definitions INADDR_NONE -> IPADDR_NONE -> ((u32_t)0xffffffff0UL) which gives 255.255.255.255 ip and dhcp resolution doesn't work.

best regards


> ### Hardware:
> Board: ESP32-WROOM-32 Core Installation version: 1.0.4 & 1.0.5 rc6 IDE name: Arduino 1.8.13
> 
> ### Description:
> With 1.0.6 - any version i get always 255.255.255.255 as IP address from WiFi.localIP()
> 
> Code: log_i("Connected to: "); log_i( "%s", WiFi.SSID() ); log_i( "%s", WiFi.localIP().toString().c_str() );
> 
> Core 1.0.4 returns: [I][Test-2020.ino:85] setup(): Connected to: [I][Test-2020.ino:86] setup(): NET1 [I][Test-2020.ino:87] setup(): 192.168.0.169
> 
> Core 1.0.5 rc1 to rc6 returns: [I][Test-2020.ino:85] setup(): Connected to: [I][Test-2020.ino:86] setup(): NET1 [I][Test-2020.ino:87] setup(): 255.255.255.255
> 
> Tested all rc versions - no luck. Code runs only on 1.04 flawless. Any suggestions ?
> 
> Thank you !

**Comment by SuGlider** [comment]
> In This arduino libraries bugs and workaround for hostname on esp32 ... any version i get always 255.255.255.255 as IP address from WiFi.localIP()
> 
> use: WiFi.config(((u32_t)0x0UL),((u32_t)0x0UL),((u32_t)0x0UL)); or #ifdef INADDR_NONE #undef INADDR_NONE #define INADDR_NONE ((u32_t)0x0UL) #endif WiFi.config(INADDR_NONE ,INADDR_NONE ,INADDR_NONE );
> 
> to get config definitions of ip 0.0.0.0 and be able to obtain dhcp values. By default arduino resolves definitions INADDR_NONE -> IPADDR_NONE -> ((u32_t)0xffffffff0UL) which gives 255.255.255.255 ip and dhcp resolution doesn't work.
> 
> best regards
> 
> > ### Hardware:
> > Board: ESP32-WROOM-32 Core Installation version: 1.0.4 & 1.0.5 rc6 IDE name: Arduino 1.8.13
> > ### Description:
> > With 1.0.6 - any version i get always 255.255.255.255 as IP address from WiFi.localIP()
> > Code: log_i("Connected to: "); log_i( "%s", WiFi.SSID() ); log_i( "%s", WiFi.localIP().toString().c_str() );
> > Core 1.0.4 returns: [I][Test-2020.ino:85] setup(): Connected to: [I][Test-2020.ino:86] setup(): NET1 [I][Test-2020.ino:87] setup(): 192.168.0.169
> > Core 1.0.5 rc1 to rc6 returns: [I][Test-2020.ino:85] setup(): Connected to: [I][Test-2020.ino:86] setup(): NET1 [I][Test-2020.ino:87] setup(): 255.255.255.255
> > Tested all rc versions - no luck. Code runs only on 1.04 flawless. Any suggestions ?
> > Thank you !

@rysiulg - The PR #6659 works for Arduino Core 2.0.3 onward.
In your post you say it doesn't work for Arduino 1.0.4 and 1.0.5, right?
In that case I suggest not using `INADDR_NONE` within these core versions, as you said.

`INADDR_NONE` can be replaced by `IPAddress(0,0,0,0)` or `(u32_t)0UL` as you wrote.
