### ISSUE TITLE
getting error on printf

### ISSUE THREAD

**Issue by arnold-b** [espressif/arduino-esp32#4734]
Hello, 
i can´´t remember which version i used before. just now i´m using the current version. 

if i try to compile my project(around 1,1/2 year old i get a lot printf compilation errors

who know why suddenly ?
716:   Serial.printf("DoCommand %s %s\n", str1,param->c_str());

774: uint16_t val = getnumber(str1);
        String str2 = GetFirstParam(param, ')'); // Must be Var type
        Serial.printf("tki2cread Bus:%d  var:%s", val, str2);

1055: Serial.printf("eval 832 %s, %d %d\n", s, len, val);

thanks

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		716:59: error: format '%s' expects argument of type 'char*', but argument 3 has type 'String*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	716	
Fehler		774:60: error: format '%s' expects argument of type 'char*', but argument 4 has type 'String*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	774	
Fehler		1042:67: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1042	
Fehler		1055:54: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1055	
Fehler		1062:58: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1062	
Fehler		1069:66: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1069	
Fehler		1072:54: error: format '%d' expects argument of type 'int', but argument 5 has type 'char*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1072	
Fehler		1072:54: error: format '%d' expects argument of type 'int', but argument 4 has type 'char*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1072	
Fehler		1091:58: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1091	
Fehler		1094:66: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1094	
Fehler		1100:66: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1100	
Fehler		1116:66: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1116	
Fehler		1138:66: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1138	
Fehler		1150:60: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1150	
Fehler		1191:60: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1191	
Fehler		1202:60: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1202	
Fehler		1243:74: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1243	
Fehler		1249:74: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1249	
Fehler		1263:70: error: format '%d' expects argument of type 'int', but argument 5 has type 'int*' [-Werror=format=]		J:\PrjArduino\HoTControl\src\script.cpp	1263

**Comment by mkfrey** [comment]
There is no way this code ever compiled. Read the error messages and adjust the types of your parameters accordingly, e.g. in ` Serial.printf("tki2cread Bus:%d var:%s", val, str2);` the variable `str2` is of type `String`, but ist has to be a `char*`.
