### ISSUE TITLE
Esp not working when serial disconnected from computer 

### ISSUE THREAD

**Issue by Elsaligi** [espressif/arduino-esp32#4750]
Hi..am facing a weird problem with esp32 and arduino am working with.. when debugging port connected to my computer everything works well.. if I disconnect ftdi cable everything stops working... I tried with different baud rates too . But same issue...

Any body faces similar issues?
I am sure it is nothing to do with hardware as same hardware is working with different codes.

**Comment by chegewara** [comment]
Did you check power supply?

**Comment by Kiznoh** [comment]
Hi, can you post a picture of you setup?

**Comment by pipi61** [comment]
Enable pin pull up resistor?
https://electronics.stackexchange.com/questions/428531/minimal-hardware-requirements-esp32-wroom/445811

**Comment by Elsaligi** [comment]
> Did you check power supply?

Actually supply vcc is provided from external supply even during debugging .only tx,rx, gnd lines were used for debugging also

**Comment by Elsaligi** [comment]
> Enable pin pull up resistor?
> https://electronics.stackexchange.com/questions/428531/minimal-hardware-requirements-esp32-wroom/445811

Thank you so much..I will check this.. but my problems seems to be weird as same setup working with another code ..will it happen?

**Comment by Elsaligi** [comment]
> Enable pin pull up resistor?
> https://electronics.stackexchange.com/questions/428531/minimal-hardware-requirements-esp32-wroom/445811

Hi,

I checked with my schematic, I pulled up EN with a 10K resistor...
