### ISSUE TITLE
AsyncUDPMulticastServer.ino not responding on Multicast-IP

### ISSUE THREAD

**Issue by fliesskomma** [espressif/arduino-esp32#4751]
Hi there,
AsyncUDPMulticastServer.ino from AsyncUDP examples does not respond in Arduino-Serial-Monitor on Multicast-IP and Port.
Responding works as expected on all broadcasts and local IPs, but not on defined Multicast IP.
These are the adresses I'm sending to:
Broadcast: 192.168.178.51:1234 (responding)
Unicast: 192.168.178.51:1234 (responding)
Multicast: 239.1.2.3:1234 (not responding)

See here:
![grafik](https://user-images.githubusercontent.com/38496994/106077821-88f51200-6112-11eb-8040-78ba73282adf.png)

Here's the example code:
```
#include "WiFi.h"
#include "AsyncUDP.h"

const char * ssid = "SSID";
const char * password = "PASSWORD";

AsyncUDP udp;

void setup()
{
    Serial.begin(115200);
    delay(200);
    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, password);
    if (WiFi.waitForConnectResult() != WL_CONNECTED) {
        Serial.println("WiFi Failed");
        while(1) {
            delay(1000);
        }
    }
    if(udp.listenMulticast(IPAddress(239,1,2,3), 1234)) {
        Serial.print("UDP Listening on IP: ");
        Serial.println(WiFi.localIP());
        udp.onPacket([](AsyncUDPPacket packet) {
            Serial.print("UDP Packet Type: ");
            Serial.print(packet.isBroadcast()?"Broadcast":packet.isMulticast()?"Multicast":"Unicast");
            Serial.print(", From: ");
            Serial.print(packet.remoteIP());
            Serial.print(":");
            Serial.print(packet.remotePort());
            Serial.print(", To: ");
            Serial.print(packet.localIP());
            Serial.print(":");
            Serial.print(packet.localPort());
            Serial.print(", Length: ");
            Serial.print(packet.length());
            Serial.print(", Data: ");
            Serial.write(packet.data(), packet.length());
            Serial.println();
            //reply to the client
            //packet.printf("Got %u bytes of data", packet.length());
        });
        //Send multicast
        udp.print("Hello!");
    }
}

void loop()
{
    delay(1000);
    //Send multicast
    udp.print("Anyone here?");
}
```
As I understand this part of the above code, the first line distinguishes the packet type, and the 6th line prints the packet type to Serial Monitor:
```
if(udp.listenMulticast(IPAddress(239,1,2,3), 1234)) {
        Serial.print("UDP Listening on IP: ");
        Serial.println(WiFi.localIP());
        udp.onPacket([](AsyncUDPPacket packet) {
            Serial.print("UDP Packet Type: ");
            Serial.print(packet.isBroadcast()?"Broadcast":packet.isMulticast()?"Multicast":"Unicast");
            Serial.print(", From: ");
            Serial.print(packet.remoteIP());
            Serial.print(":");
            Serial.print(packet.remotePort());
            Serial.print(", To: ");
            Serial.print(packet.localIP());
            Serial.print(":");
            Serial.print(packet.localPort());
            Serial.print(", Length: ");
            Serial.print(packet.length());
            Serial.print(", Data: ");
            Serial.write(packet.data(), packet.length());
            Serial.println();
```
The Serial Monitor should type the packet types Broadcast, Unicast, or Multicast.
Well, it doesn't work for Multicast so.

For testing I used the Windows App 'Packet Sender'. Next to the 'Send' buttons 1, 2 and 3, in the screenshot, you see the parameters that were sent:
![grafik](https://user-images.githubusercontent.com/38496994/106081056-8c8b9780-6118-11eb-91fb-55d60d37fc24.png)

Does anybody have an idea, whats wrong?

### Hardware
Lolin32 Development board (ESP32)
Arduino IDE

**Comment by fliesskomma** [comment]
Hey there,
does anybody have any idea, how to solve the above Problem? Or does anybody have similar unsolved Problems? I read many postings about similar problems with ESP8266. But I couldn't transfer the solution to ESP32.

Any ideas?

**Comment by jpcavanagh** [comment]
I don't know much about multicast in this situation.  I suggest that you ensure the multicast packet actually makes it onto the network and there reaches the ESP.  I say this because it seems the multicast address is on a different IP network and the PC may not have a route for it.

**Comment by nhatuan84** [comment]
This issue still exists!!!
