### ISSUE TITLE
Redeclaration errors when including both WebServer.h and HttpsOTAUpdate.h

### ISSUE THREAD

**Issue by tomjschwanke** [espressif/arduino-esp32#4758]
### Hardware:
Board:							Board not connected, compiling for ESP32 dev-module
Core Installation version:			1.0.5-rc6
IDE name:						Arduino Pro IDE
Computer OS:                                        Windows 10

### Description:
When I include both `WebServer.h` and `HttpsOTAUpdate.h` the IDE gives me tons of redeclaration errors

### Sketch: 
```cpp
#include <WebServer.h>
#include <HttpsOTAUpdate.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

### Compile output:
https://gist.github.com/tomjschwanke/e4756747343163e2a5c3a5ddc50c54ab

**Comment by jameszah** [comment]
Here is a workaround - my specific problem was WebServer.h and esp_http_server.h -- I think it might be the same problem.  Was it HTTP_GET redeclaration?

https://github.com/tzapu/WiFiManager/issues/1184
