### ISSUE TITLE
HTTPClient does not set/reset httpCode correctly to 200 but is stuck with 30X till followed too offten and gets 404

### ISSUE THREAD

**Issue by DEvil0000** [espressif/arduino-esp32#4763]
What you are trying to do?
I try to follow https://github.com/wolf128058/esp32-led-matrix/releases/latest/download/version.txt to download it's payload.
Describe what is failing.
HTTPClient follows till the final URL but when it should have a 200 and return the payload it tries to follow once more and gets a 404 after that. Looks like the http return code is not reset when the HTTPClient gets reused internally on the follow.
Show the shortest possible code that will duplicate the error.
```
        http.setFollowRedirects(HTTPC_STRICT_FOLLOW_REDIRECTS);
        http.begin(client, url);     // Webseite aufrufen
```

### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.5-rc6
IDE name:						Platform.io
Upload Speed:					115200
Computer OS:                                        Ubuntu

### Description:
guess I did that above.
Not reusing the connection (no follow) works.

**Comment by me-no-dev** [comment]
Done :) It was actually redirecting to a new host, but the old connection was not disconnected first, so it asked the same server for non-existing URL
