### ISSUE TITLE
httpUpdate.update & a url with parameters

### ISSUE THREAD

**Issue by pavluchenkor** [espressif/arduino-esp32#4764]
I use update in two ways 
1. String server_FW = "https://my_domain.com/update/firmware.bin";
2. String server_FW = "https://my_domain.com/update?controller=" + controller_type + "&ver=" + version + "&type=firmware" + "&t=" + time_now + "&key=" + md5_key(key);
(the line is something like this https://my_domain.com/update?controller=xzxzxz&ver=210130&type=firmware&t=1612223376&key=53acbd18db4cc2f85cedef654fccc4a4d8)
  
 t_httpUpdate_return ret = httpUpdate.update(client, server_FW);
 
 In the first case I get the update with no problem, in the second I get the error
 [E][HTTPUpdate.cpp:358] handleUpdate(): HTTP Code is (301)
 
At the same time, in the second case, my request does not even reach the server (I record each call to the PHP script in a separate file) What could be the reason?

**Comment by cpainchaud** [comment]
Hi it was probably due to the redirect and should be fixed now
https://github.com/espressif/arduino-esp32/issues/4931
