### ISSUE TITLE
Build in WiFi library or the AsyncWebServer library?

### ISSUE THREAD

**Issue by tsctrl** [espressif/arduino-esp32#4772]
Make your question, not a Statement, inclusive. Include all pertinent information:

I would like to use esp as soft ap server and host static html files from spiffs. but i not sure should i use the build in WiFi library or the ESPAsyncWebServer library instead. 
1. Is the build in library have enough apis to cover the basic requirement above? 
2. What is the different between build in library and the ESPAsyncWebServer? 
3. between this two option which one library have more feature then other or is it the same library just split into different build in library in arduino-esp32?

Thank you.

**Comment by tsctrl** [comment]
@me-no-dev

**Comment by jandrassy** [comment]
try the examples
