### ISSUE TITLE
ESP32 Write error

### ISSUE THREAD

**Issue by arivvid27** [espressif/arduino-esp32#4780]
HI,
I have an error regarding the installation of Micropython onto my esp32.
The first command worked perfectly (```esptool.exe --chip esp32 --port COM4 erase_flash```), but the second command (```esptool.py --chip esp32 --port COM4 --baud 460800 write_flash -z 0x1000 esp32-20190125-v1.10.bin```) does not seem to work.
I keep getting this error when trying to write micropython :
```esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'esp32-20190125-v1.14.bin'```
I have a Windows 10, with all updates.

Thanks in advance,
-arivvid27

**Comment by lbernstone** [comment]
This forum is for arduino-esp32
https://github.com/micropython/micropython
https://github.com/espressif/esptool
