### ISSUE TITLE
Can't find board esp-wroom-32

### ISSUE THREAD

**Issue by Benedito821** [espressif/arduino-esp32#4781]
Hello !
I bought the board esp-wroom-32 an I'm trying to find it in platformio. I'm using vs code+platformio. I installed the libraries esp32 and esp8266 but there is not my board in the board list. How can I find or add it?

**Comment by meltdown03** [comment]
The board should be `esp32dev` in platformio

**Comment by Benedito821** [comment]
good, That is it!
