### ISSUE TITLE
make variants' i2c pins do what they're expected to do

### ISSUE THREAD

**Issue by ladyada** [espressif/arduino-esp32#48]
tested!
https://github.com/adafruit/arduino-esp32/commit/3b56ee9515e54171309c8240f0d3b0bdb8eaa171
i'd also recommend removing
```
#define I2C0_DEFAULT_SDA_PIN 21
#define I2C0_DEFAULT_SCL_PIN 22
```
from the Wire.h to avoid confusion

**Comment by me-no-dev** [comment]
fixed [here](https://github.com/espressif/arduino-esp32/commit/b5e0ebfc899f4d74365f8f8dbfcc57223470f267) thanks
