### ISSUE TITLE
Branch idf-release/v3.3

### ISSUE THREAD

**Issue by v-nereutsa** [espressif/arduino-esp32#4803]
Why the branch idf-release/v3.3 disappeared?

**Comment by bertmelis** [comment]
Maybe because of this: https://github.com/espressif/arduino-esp32/commit/cee659563d38434abbe7fb3523f186f0f308bffc

**Comment by lbernstone** [comment]
Experimental branches often will be created as proving grounds for changes.  Once they are validated, the changes are merged into master and the branch removed.
