### ISSUE TITLE
HTTPClient needs to support content-length larger than 32,767

### ISSUE THREAD

**Issue by frankcohen** [espressif/arduino-esp32#4806]
esp32/HTTPClient/src/HTTPClient.cpp and HTTPClient.h are coded to use int values for content-length responses. For example:

int HTTPClient::getSize(void)
{
    return _size;
}

if(headerName.equalsIgnoreCase("Content-Length")) {
    _size = headerValue.toInt();
}

Downloading content over HTTP may use content-length response header values above 32,767. Think about downloading an image or movie file (jpeg, mpeg).

**Comment by lbernstone** [comment]
int is a 32-bit word (hence esp32).

**Comment by frankcohen** [comment]
Thanks for the reminder. Going back to coding. :-D

**Comment by everslick** [comment]
pls close issue
