### ISSUE TITLE
Missing quite popular TTGO T-Call boards 

### ISSUE THREAD

**Issue by slavino** [espressif/arduino-esp32#4825]
Please add TTGO variants

https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800
https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G

**Comment by me-no-dev** [comment]
Board support is added either by the board manufacturers or by users who have them. We do not and can not have all boards available out there :)
