### ISSUE TITLE
configTime "gmtOffset_sec" issue

### ISSUE THREAD

**Issue by bestpika** [espressif/arduino-esp32#484]
My location is GMT+8 timezone, so I think **gmtOffset_sec** I should input 28800.
But in this function I have to input **-28800**.
I think it's a bug, right?

```cpp
#include <ctime>
...
time_t timeNow = time(nullptr);
tm *dateTime = localtime(&timeNow);
Serial.println(asctime(dateTime));
```

**Comment by copercini** [comment]
Solved here: https://github.com/espressif/arduino-esp32/commit/d208a3683630212b130f381e23a3e77475f4df0f

=)
