### ISSUE TITLE
ESP-32-Wroom-32D Flash Corrupted

### ISSUE THREAD

**Issue by naakhtar** [espressif/arduino-esp32#4841]
### Description:

 - ESP32 WROOM 32D modules stopped working on site, after almost a month of operation. On getting back to our factory, we had to reprogram the bootloader into it, then re flash the firmware. It started working again. Seems like the flash got corrupted. Kindly let us know what possible reasons could lead to this so we can ensure this does not happen again.

**Comment by me-no-dev** [comment]
It is hard to tell without proper description of wha your firmware does :) does it write to flash? EEPROM?
