### ISSUE TITLE
timing issues when working with GPIO

### ISSUE THREAD

**Issue by celesteking** [espressif/arduino-esp32#4849]
This is something that I've encountered for the first time, this doesn't happen on atmel arduino. The problem is that I'm getting some sort of delay in about half through the loop. When `ii == 4`, it delays by ~40us more than it should've been. I just can't wrap my head around it as other pulses have the right length (+ some *constant* delay for instructions of course).  I'm setting XTAL to 20Mhz. It gets better the higher the freq is, but what the hell, even 10Mhz should've been just enough to flip some pins, I'm not trying to run a spaceship off this chip!

```c
#define HDQ_DELAY_THW1                  30
#define HDQ_DELAY_THW0                  90
#define HDQ_DELAY_TCYCH         200
#define SET_HIGH (GPIO.out_w1ts = (1 << pin));
#define SET_LOW (GPIO.out_w1tc = (1 << pin));

// payload=0 in this test
        for (uint8_t ii = 0; ii < 8; ii++) {
            if (payload >> ii & 0x01) {
                SET_LOW
                delayMicroseconds(HDQ_DELAY_THW1);
                SET_HIGH
                delayMicroseconds(HDQ_DELAY_TCYCH - HDQ_DELAY_THW1);
            } else {
                SET_LOW
                delayMicroseconds(HDQ_DELAY_THW0);
                SET_HIGH
                delayMicroseconds(HDQ_DELAY_TCYCH - HDQ_DELAY_THW0);
            }
        }
```

### Hardware:
Board: Doit ESP32 Devkit-1
Core Installation version:			latest development, I guess
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                    no
Upload Speed:					1K
Computer OS:                                        osx

**Comment by me-no-dev** [comment]
The ESP32 as opposed to other MCUs is running on FreeRTOS, which can halt each CPU and switch tasks if it needs to. What it does have though is great peripherals that can read/write just about any signal. Your case up there looks like prime candidate for RMT :)
