### ISSUE TITLE
1.0.5 not yet conatined in https://dl.espressif.com/dl/package_esp32_index.json

### ISSUE THREAD

**Issue by careyer** [espressif/arduino-esp32#4856]
Why has 1.0.5 not yet been added to the package list at: https://dl.espressif.com/dl/package_esp32_index.json ?

Cheers!

**Comment by me-no-dev** [comment]
Please use the URLs here: https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md
