### ISSUE TITLE
set GPIO logic level

### ISSUE THREAD

**Issue by gepd** [espressif/arduino-esp32#486]
I'm doing an external wake up of the esp but the external trigger signal keeps low for some minutes, so the esp reboots each 1 second (aprox). Seems like esp hasn't nothing similar to the trigger modes in the arduino devices (LOW, CHANGE, RISING... etc) 

I've googled about this problem and seems like one solution can be change the GPIO level just before the device wakes up.

until now I understand that I should implement a `deep_sleep_wake_stubs` and so change the GPIO level, but I'm not sure if can get this using "arduino code"

Is it possible to do this?

**Comment by Raienryu97** [comment]
Maybe [this example](https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/DeepSleep/ExternalWakeUp/ExternalWakeUp.ino) can help you out?
