### ISSUE TITLE
base64_decode() out_len seems to be a lot bigger than it should be

### ISSUE THREAD

**Issue by playground** [espressif/arduino-esp32#4886]
### Hardware:
Board:							featheresp32
Core Installation version:			1.0.5
IDE name:						Platform.io
Flash Frequency:					40Mhz
PSRAM enabled:                                      No
Upload Speed:					115200
Computer OS:                                          Mac OSX

### Description:
I'm trying to save the response from https://texttospeech.googleapis.com/v1/text:synthesize as mp3 file
{
    "input": {
        "text": "Hello world!"
    },
    "voice": {
        "languageCode":"en-gb",
        "name":"en-GB-Standard-A",
        "ssmlGender":"FEMALE"
    },
    "audioConfig": {
        "audioEncoding":"MP3"
    }
}

`void saveMP3(char *toDecode) {
  size_t outputLength;

  unsigned char * decoded = base64_decode((const unsigned char *)toDecode, strlen(toDecode), &outputLength);

  Serial.println("writing...");
  file = SPIFFS.open("/hello.mp3, "w");
  if(!file) {
    file.write((uint8_t *)decoded, outputLength);
    file.close();
 }
}`

outputLength has the value of **1073516968** when the toDecode length is only **5631**

When perform 
`base64 --decode helloworld.txt > helloworld.mp3 `
produced file size of **4062**

What am I doing wrong with base64_decode()?

**Comment by lbernstone** [comment]
I think you may be ending up with the pointer rather than the value.  I would recommend you use the base64 from mbedtls. https://github.com/espressif/arduino-esp32/issues/1599#issuecomment-402739293
