### ISSUE TITLE
Error upload code in esp32-s2!

### ISSUE THREAD

**Issue by Javito68** [espressif/arduino-esp32#4910]
Hello everyone, I have the following error when uploading code:

-Arduino 1.8.13 in windows 10
-Hardware: https://es.aliexpress.com/item/1005001922366220.html?spm=a2g0s.9042311.0.0.36d463c0nw301j
-code: https://github.com/volca/esp-soil/blob/pio/src/main.ino
![image](https://user-images.githubusercontent.com/46301145/110248570-22191300-7f72-11eb-8aea-d5e990f90513.png)
![image](https://user-images.githubusercontent.com/46301145/110248599-4248d200-7f72-11eb-9598-b121e71dff53.png)
I have installed the Arduino core for the ESP32 la branche esp32s2 according to:
![image](https://user-images.githubusercontent.com/46301145/110248618-57256580-7f72-11eb-82a9-a0c4d1a91afd.png)

What am I doing wrong? What do I have to do to make it work?
Thanks !!!

**Comment by chegewara** [comment]
It is not error. You entered download mode with buttons and after flashing you have rest with button. It is how it works.

**Comment by Javito68** [comment]
Thanks for answering chegewara, how do I get rest with button? what is rest button?

a greeting!

**Comment by chegewara** [comment]
Sorry, typo. Its `reset`.

**Comment by Javito68** [comment]
chegewara  Could you help me with the scheme, I don't see the reset button.
[schematic (1).pdf](https://github.com/espressif/arduino-esp32/files/6097682/schematic.1.pdf)

**Comment by Javito68** [comment]
K1, K2 o S1?

**Comment by chegewara** [comment]
K2. Or you can just unplug from power source (USB and battery).

**Comment by Javito68** [comment]
if I press K2 button the com port is disabled
![com](https://user-images.githubusercontent.com/46301145/110249805-44ae2a80-7f78-11eb-88d4-41180db43a45.jpg)

**Comment by Javito68** [comment]
What would be the correct procedure to upload the program? Thanks!

**Comment by Javito68** [comment]
If I keep K1 pressed and press k2 then the com port is enabled but I enter download mode ..., something escapes me

**Comment by chegewara** [comment]
Its all fine, windows just change com port when you enter download mode. The screenshots shows you already flashed device, so i dont see any problems you may have.

**Comment by Javito68** [comment]
well in the end I have achieved it, I have changed from uart to usb cdc in the IDE:
![comi2](https://user-images.githubusercontent.com/46301145/110250802-ae7d0300-7f7d-11eb-9d12-462c0a64faa2.jpg)

thanks chegewara, you always learn something. Salut!

**Comment by chegewara** [comment]
Thats strange, because it is not working to me on windows, and not only to me, thats why i didnt mention it.

**Comment by Javito68** [comment]
Well, this is how it is working and the port is enabled. All the best!

![image](https://user-images.githubusercontent.com/46301145/110251470-dae64e80-7f80-11eb-9731-62e8c2be42e4.png)

**Comment by ozgurbostan** [comment]
Hi @Javito68,

Have you used USB CDC feature without any button pressig? and with Win 10?

**Comment by Javito68** [comment]
Hi ozgurbostan, I'm sorry for answering late. I've had a job, I'll explain how I proceed:
  -Arduino ide in USB CDC mode
-To load the program: press button IO0 + EN (reset)
-To work, press the EN button (reset)
it works -> OK

**Comment by ozgurbostan** [comment]
Thanks @Javito68 for your answer.

**Comment by Javito68** [comment]
now I have another problem reading battery values, see thread: help to read battery in esp32-s2.
This I close.
Thanks!!!
