### ISSUE TITLE
Arduino IDE reports Error in <Arduino.h>

### ISSUE THREAD

**Issue by ericlangel** [espressif/arduino-esp32#4917]
In included file: unknown type name '_read'
C:\Users\eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.5/tools/sdk/include/newlib\sys/reent.h:195:36:
note: error occurred hereclang(unknown_typename)

Project compiles, but the #include <Arduino.h> is underlined Red and show the Error above

**Comment by me-no-dev** [comment]
please show some code that can replicate the issue. We do not see it on our end

**Comment by ericlangel** [comment]
![ESP_IDE](https://user-images.githubusercontent.com/40859702/110485365-d5f1de00-80eb-11eb-830f-172185e3a4e1.jpg)

You dont need Code.

Also a new sketch shows this Error.

**Comment by me-no-dev** [comment]
you are using Beta IDE. Also does this prevent you from compiling and running the sketch?

**Comment by ericlangel** [comment]
Compiling is fine,

i thought that it could be an Error (missing include or something else)
maybe the related functions are unused?

**Comment by me-no-dev** [comment]
This is the line that causes the issue: https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/include/newlib/sys/reent.h#L195

`_READ_WRITE_RETURN_TYPE` expands to `int` which is not an unknown typename :) I guess that `clang` for the beta IDE is not setup correctly and is not picking the correct definition.
