### ISSUE TITLE
Stop when change the baudrate

### ISSUE THREAD

**Issue by qlalfdu** [espressif/arduino-esp32#4934]
Board: ESP32 Dev Module
Version/Date: 1.0.5, today's master
IDE name: Arduino IDE

Below is my sketch

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  Serial.println("bauds=9600");
  delay(1000);
  Serial.begin(115200);
}

void loop() {
  // put your main code here, to run repeatedly:
 delay(1000);
 Serial.println(millis());
}

### Debug Messages:
No debug messages
Just STOP and do nothing
![PN20-1052](https://user-images.githubusercontent.com/24924909/110844233-84647180-82ec-11eb-9061-bc06713a9caf.png)

**Comment by chegewara** [comment]
Dont try to `begin()` twice, better update bitrate:
`Serial.updateBaudRate(bitrate);`

**Comment by qlalfdu** [comment]
It worked in 1.0.4, but it didn't work in 1.0.5, so I was embarrassed.
Serial.updateBaudRate(bitrate);
It works fine.
Thank you.
