### ISSUE TITLE
spiTransferBytesNL() writes past end of data_out

### ISSUE THREAD

**Issue by erikboto** [espressif/arduino-esp32#4935]
spiTransferBytesNL(spi_t * spi, const void * data_in, uint8_t * data_out, uint32_t len) will write too much data when len is not a factor of 4.

Since it copies word by word from the SPI buffer, it will write 0-3 bytes more then `len` bytes into `data_out`. I couldn't see any mention of this, and the non-NL version spiTransferBytes() does not suffer from the same limitation.

**Comment by me-no-dev** [comment]
Done :) thanks!
