### ISSUE TITLE
bluethoot pipe crash when wifi connected

### ISSUE THREAD

**Issue by kobigozlan** [espressif/arduino-esp32#4955]
the bluethoot and the wifi dont work together ,
the bluethoot work on the setup fine and print the data perfectly ,
when the wifi success to connect to the netwotk the bluethoot pipe broken 
what i need to let them work together 
on the previous version it was work fine 
ewhat i need to do?

**Comment by me-no-dev** [comment]
already should be fixed in master. the new version is coming soon
