### ISSUE TITLE
How can i build my own SDK for example libesp32.a

### ISSUE THREAD

**Issue by mirecta** [espressif/arduino-esp32#4962]
There isnt exact manual to do this

i want customize sdkconfig and build own SDK libraries

How can i do this ?

**Comment by lbernstone** [comment]
[esp-idf component](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md) or [lib-builder](https://github.com/espressif/arduino-esp32/blob/master/docs/lib_builder.md)

**Comment by chill117** [comment]
Those solutions look overly complex for what is really needed: To override a few build flags.
