### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by advik1995** [espressif/arduino-esp32#4968]
I have a problem with my ESP32 WROOM 32 which is soldered to a pcb board, the device constantly restarts which shouldn't happen. I have flashed it and given a try but not working.

**Comment by brunojoyal** [comment]
Sounds to me like it's either the hardware, or the software.

**Comment by bigu1975** [comment]
> I have a problem with my ESP32 WROOM 32 which is soldered to a pcb board, the device constantly restarts which shouldn't happen. I have flashed it and given a try but not working.

How do you power your unit: either by usb or by Vin pin?
