### ISSUE TITLE
ble api question

### ISSUE THREAD

**Issue by ouki-wang** [espressif/arduino-esp32#497]
Will the espressif transplants general BLE API in arduino platform? Such as mbed BLE API. 
Thank you for your help!

**Comment by lemio** [comment]
This is still in progress: https://github.com/espressif/arduino-esp32/issues/423 I made a rather specific https://github.com/lemio/esp32_ble_wedo library (where the esp32 connects (as a Central) to a wedo2.0 (the Peripheral), if you want to do something like that (use the esp32 as central) you can take a look at it

**Comment by copercini** [comment]
Let's concentrate all BLE API things in the https://github.com/espressif/arduino-esp32/issues/423 to keep the repository organized =)
