### ISSUE TITLE
After some time wifi client stops working and blocks

### ISSUE THREAD

**Issue by Joelmaca9** [espressif/arduino-esp32#4985]
Iḿ performing a connection to a server to retrieve data trough HTTPS with the Arduino HTTP client. Wen I try it with ethernet it works great bur with the wifi (only wifi enabled, not both) after some time making get request to the server it fails with the following error:

[ssl_client.cpp:93] start_ssl_client(): Connect to Server failed!

After that i need to reset my board because it gets stuck in the function lwip_connect (file: ssl_client.cpp line 81) 

### Hardware:
Board:							ESP32-wrover-E
Core Installation version:			release v4.2
IDE name:						IDF component
Flash Frequency:					40Mhz
PSRAM enabled:                                    yes
Upload Speed:					115200
Computer OS:                                        Ubuntu

### Description:
Describe your problem here

**Comment by bwjohns4** [comment]
I may be off base, but I believe I ran into this problem a while back and ended up putting a delay(1000) [delay(100) also worked but I put 1000 just to be sure] after the wificlientsecure.connect() function and it solved the issue. Somehow if the connect() failed it got hung up tearing down the socket or some other background process where putting delay() AFTER connect() solved it for me. It seems like a strange fix to put the delay AFTER connect(), but it appears to have resolved the hang issue on failed connect().
