### ISSUE TITLE
does the esp32_s2 support the arduino framework?

### ISSUE THREAD

**Issue by anishp55** [espressif/arduino-esp32#4997]
Make your question, not a Statement, inclusive. Include all pertinent information:
Does platformio support the arduino framework for the esp32_s2
What you are trying to do?

Describe your system( Hardware, computer, O/S, core version, environment).

platformio installed on a remote linux machine using visual studio code.

### Hardware:
Board:							esp32-s2-saola-1
IDE name:						Platform.io
Flash Frequency:					?40Mhz?

Computer OS:                                        Ubuntu

### Description:
i have an existing esp32 project that i would like to try to run on an esp32_s2

i've losts much of the config i've cycled through at this point, but i currently have the following. I've tried various esp32_s2 boards as well.

```
[env:esp32_s2]
board = featheresp32-s2
platform = espressif32@3.2
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#idf-master
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags_esp32}
```

the result of this config is much like the others that i have gone through with the following output

```Processing esp32_s2 (board: featheresp32-s2; platform: espressif32@3.2; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/featheresp32-s2.html
PLATFORM: Espressif 32 (3.2.0) > Adafruit ESP32-S2 Feather Development Board
HARDWARE: ESP32S2 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 0.0.0+sha.46d5afb
 - tool-esptoolpy 1.30000.201119 (3.0.0)
 - toolchain-esp32s2ulp 1.22851.191205 (2.28.51)
 - toolchain-xtensa32s2 1.80400.210211 (8.4.0)
Converting monitor.ino
Error: This board doesn't support arduino framework!
```

**Comment by Jason2866** [comment]
Platformio does not support ESP32-S2. You have to build your own framework to get it going.
I have done a experimental setup for project Tasmota. Tasmota crashes (changes are needed...)
Example sketches are working. See https://github.com/arendst/Tasmota/blob/development/platformio_override_sample.ini#L171 
you have to (re)define a board. See  https://github.com/arendst/Tasmota/blob/development/boards/esp32s2.json
