### ISSUE TITLE
analogInputToDigitalPin() macros not implemented

### ISSUE THREAD

**Issue by vshymanskyy** [espressif/arduino-esp32#5]

**Comment by me-no-dev** [comment]
will be when the driver is ready

**Comment by jrobeson** [comment]
this was needed for analogRead wasn't it?

**Comment by me-no-dev** [comment]
Well, to be honest it's not needed at all :) all methods take the GPIO pin and not the analog channel

**Comment by vshymanskyy** [comment]
The macros should be implemented, as it is used in some libraries ;)
