### ISSUE TITLE
ESP32-S2 "get.exe" not installing xtensa-esp32s2-elf-gcc

### ISSUE THREAD

**Issue by lewispg228** [espressif/arduino-esp32#5001]
Dear Espressif,
I have noticed something that I think may need to be updated. The windows "get.exe" file does not seem to download the necessary tools to compile for the EXP32-S2.

![image](https://user-images.githubusercontent.com/601236/113316626-cc632c80-92cb-11eb-94f7-a09c2ccf0b64.png)

However, when I run the python module "get.py" it works wonderfully.

![image](https://user-images.githubusercontent.com/601236/113317092-41366680-92cc-11eb-864c-e2bc9f8aa90f.png)

We are happy to instruct users to use the python module for installation, but I thought it was worth bringing to your attention.

Please let me know if there is anything else I can do to help resolve this issue.

Cheers and thank you very much!

Pete Lewis
SparkFun Electronics

**Comment by me-no-dev** [comment]
are you sure that you ran the commands on the same branch? (`idf-master`)

**Comment by lewispg228** [comment]
Whoops. I was running it on the "master" branch. Sorry for my mistake. I must have switched branches in between running get.exe and get.py. 

Thanks for getting back to me so quickly. 
Have a great rest of your day!
