### ISSUE TITLE
Program stalls when serial port is reopened at 1.0.5/1.0.6

### ISSUE THREAD

**Issue by thorv** [espressif/arduino-esp32#5004]
The program following is expected show "3", "6" on Serial, and then blink LED on GPIO 21.
It's OK on board package version 1.0.4, but NG on 1.0.5/1.0.6.
It shows only 3 but not 6, LED on GPIO 21 is not blinking
No debugging messages or core dump etc.
```cpp
void setup() {
  Serial.begin(115200);
  Serial.println(__LINE__); //3
  delay(10);
  Serial.begin(115200);
  Serial.println(__LINE__); //6
  delay(10);
  pinMode(GPIO_NUM_21, OUTPUT);
 }

void loop() {
  digitalWrite(GPIO_NUM_21,HIGH);
  delay(500);
  digitalWrite(GPIO_NUM_21,LOW);
  delay(500);
}
```
So, we discussed at teratail.com (Japanese Q&A site) https://teratail.com/questions/326026 , concluded that the countermeasure to Issue #3878 seems to be causing this phenomenon. 
I think it's the same phenomenon as #4948  but its impact will be more widespread than just M5Stack.

### Hardware:
Board: Devkit-C/M5Stack
Core Installation version:	1.0.5/1.0.6
IDE name: Arduino IDE
Flash Frequency: 40Mhz
PSRAM enabled: no
Upload Speed:	921600
Computer OS:  Windows 10

**Comment by SuGlider** [comment]
Issue is solved with PR #5385
