### ISSUE TITLE
espidf-arduino-blink example - missing branch: idf-release/v4.0

### ISSUE THREAD

**Issue by andreaskuster** [espressif/arduino-esp32#5007]
### Hardware:
Board:							ESP32 Dev Module (Feather Board)
Platformio Version:			                5.1.1
IDE name:						PlatformIO Integration Visual Studio Code & CLion
Computer OS:                                         Windows 10 & Ubuntu

### Description:

The espidf-arduino-blink platformio example project does not compile anymore due to a dependency to ` https://github.com/espressif/arduino-esp32.git#idf-release/v4.0`, which does not seem to exist (anymore), see platformio.ini config line:

`platform_packages =
  ; use a special branch
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#idf-release/v4.0
`

You should probably coordinate with the developers from the [github.com/platformio/platform-espressif32/examples](https://github.com/platformio/platform-espressif32/tree/master/examples/espidf-arduino-blink) project.

### Debug Messages:
```
/home/andreas/.platformio/penv/bin/pio -c clion run --target debug
Processing esp32dev (board: esp32dev; platform: espressif32; framework: arduino, espidf)
--------------------------------------------------------------------------------
Tool Manager: Installing git+https://github.com/espressif/arduino-esp32.git#idf-release/v4.0
git version 2.25.1
Cloning into '/home/andreas/.platformio/.cache/tmp/pkg-installing-fryzo74r'...
warning: Could not find remote branch idf-release/v4.0 to clone.
fatal: Remote branch idf-release/v4.0 not found in upstream origin
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', 'idf-release/v4.0', 'https://github.com/espressif/arduino-esp32.git', '/home/andreas/.platformio/.cache/tmp/pkg-installing-fryzo74r']

Process finished with exit code 1
```

**Comment by VioletGiraffe** [comment]
#4998
