### ISSUE TITLE
Calling configTime should set system time immediately, or this name is misleading.

### ISSUE THREAD

**Issue by happyme531** [espressif/arduino-esp32#5008]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			idf-master (latest)
IDE name:						Platform.io
Flash Frequency:				        40Mhz
PSRAM enabled:                                     yes
Upload Speed:				       2000000
Computer OS:                                        Windows 10

### Description:
Just get confused for many days that configTime just "not working" and not correcting system time.
Imagine you are making a watch that have an external RTC to hold time, and from time to time the watch will connect to the internet to make the time accurate.  
And you chose the configTime function and expecting it will "config" the correct time each time you called the function.
Actrually it won't. It only works as "configNTPServer". And time is fetched if the system time is horribly wrong when calling getLocalTime()...

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
//setting up wifi and etc

rtc2sys(); // Custom function to set system time from a RTC.

// now the time is inaccurate, eg. 5 minutes slower
int retryCount = 0;
struct tm time;

do {
    retryCount++;
    configTime(8 * 3600, 0, "time4.aliyun.com" "pool.ntp.org");    //It wont config time for you.
  } while (!getLocalTime(&time) && retryCount < 10);
  if (retryCount != 10) { //NTP succeed...?
    sys2rtc();
// now the time is still inaccurate, eg. 5 minutes slower
  } 
}

void loop() {
}
```

**Comment by lbernstone** [comment]
You are looking for the posix function settimeofday().
https://github.com/lbernstone/ESP32_settimeofday/blob/master/settimeofday.ino
