### ISSUE TITLE
Can't find S2 boards on Arduino IDE

### ISSUE THREAD

**Issue by E-Seeker101** [espressif/arduino-esp32#5009]
S2 board
ESP32-S2,MX Linux,Arduino
I can't find S2 boards on Arduino IDE
Are they removed for Arduino support?
Any idea?

**Comment by lbernstone** [comment]
https://learn.adafruit.com/adafruit-metro-esp32-s2/arduino-ide-setup
The experimental branch is now called idf-master

**Comment by E-Seeker101** [comment]
Thank you :: https://github.com/espressif/arduino-esp32/tree/idf-master
