### ISSUE TITLE
In ledc_types.h, LEDC_CHANNEL_6 is skipped

### ISSUE THREAD

**Issue by Dlloydev** [espressif/arduino-esp32#5016]
I'm attempting to add full AnalogWrite support to my repo and my concern is that the commit adding [initial ESP32-C3 support](https://github.com/espressif/esp-idf/commit/7c08be57719757e454ec2c78a0597d58ed6281a2) has introduced a bug in support for ESP32s with 16 PWM channels (2 groups of 8) that effectively reduces this to 14 channels (channel 6 is skipped). I think this could create other issues when working with the ledc functions.

In this typedef in [ledc_types.h](https://github.com/OS-Q/E52A/blob/b07fb5cff19c4d90774849cf9bbf7d7755cdb87c/components/hal/include/hal/ledc_types.h):

typedef enum {
    LEDC_CHANNEL_0 = 0, /*!< LEDC channel 0 */
    LEDC_CHANNEL_1,     /*!< LEDC channel 1 */
    LEDC_CHANNEL_2,     /*!< LEDC channel 2 */
    LEDC_CHANNEL_3,     /*!< LEDC channel 3 */
    LEDC_CHANNEL_4,     /*!< LEDC channel 4 */
    LEDC_CHANNEL_5,     /*!< LEDC channel 5 */
#if SOC_LEDC_CHANNEL_NUM > 6
    LEDC_CHANNEL_6,     /*!< LEDC channel 6 */
    LEDC_CHANNEL_7,     /*!< LEDC channel 7 */
#endif
    LEDC_CHANNEL_MAX,
} ledc_channel_t;

Channel 6 is skipped ... should be CHANNEL_NUM > 5

**Reference:**
[ESP32-C3 datasheet Page 25](https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf), LED PWM, ledc_ls_sig_out0-5, Six independent PWM channels
[ESP32 datasheet Page 39](https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf), LED PWM, ledc_hs_sig_out0-7, ledc_ls_sig_out0-7, 16 independent channels

**Comment by lbernstone** [comment]
I haven't looked thoroughly, but SOC_LEDC_CHANNEL_NUM probably isn't indexed at 0, while the LEDC_CHANNEL_X is.

**Comment by Dlloydev** [comment]
Thanks, I'll open an issue there.
Just a note that in the following typedef (ledc_timer_bit_t), they used SOC_LEDC_CHANNEL_NUM being indexed at 0.
