### ISSUE TITLE
fatal error occurred: Timed out waiting for packet header

### ISSUE THREAD

**Issue by lroboredo** [espressif/arduino-esp32#5018]
I am tying up load a sketch and I get the following result:

![imagem](https://user-images.githubusercontent.com/82038185/113716488-8ef30a80-96e2-11eb-848a-1dce9fda2048.png)

Please help how I can fixit?

![ESP32 WROVER](https://user-images.githubusercontent.com/82038185/113716740-ce215b80-96e2-11eb-917f-a5365fc6172b.png)

**Comment by lbernstone** [comment]
Bad usb cable

**Comment by lroboredo** [comment]
Thank you for your sugestion.
I change the usb cable by a ew one certified 480Mbps and I got the same!

**Comment by lroboredo** [comment]
![imagem](https://user-images.githubusercontent.com/82038185/113766821-caf39300-9715-11eb-95e7-dada8d51d3f4.png)
This is the configuration.

**Comment by lroboredo** [comment]
![imagem](https://user-images.githubusercontent.com/82038185/113767112-2c1b6680-9716-11eb-95f5-f19dec4f0a88.png)
When I press Boot button I get this answer in the COM8 monitor

**Comment by lbernstone** [comment]
Verify that nothing is using gpio pins 6-11.  Try setting flash to DIO/40MHz. It seems like your flash may be damaged.

**Comment by lroboredo** [comment]
Now I got
![imagem](https://user-images.githubusercontent.com/82038185/113768239-85d06080-9717-11eb-8d90-47e3a322fbf5.png)

**Comment by lroboredo** [comment]
This is the board

**Comment by lroboredo** [comment]
![Uploading imagem.png…]()
