### ISSUE TITLE
Cannot compile developmental version if stable is installed

### ISSUE THREAD

**Issue by fabiuz7** [espressif/arduino-esp32#5025]
Hi,
I was used to having the latest version of esp32-core through Arduino Board Manager, and the developmental version in Arduino sketchbook to test new features or do experiment. I was able to switch between them seamlessly in Arduino IDE. However, checking out the latest commit, the developmental version fails to compile since Arduino IDE searches the toolchain in the path of **stable** esp32-core, which is not more compatible with the latest commit 371f382db7dd36c470bb2669b222adf0a497600d. If I delete the stable version, I can compile the developmental version.

### Hardware:
Core Installation version:			1.0.6
IDE name:						Arduino IDE
Computer OS:                                        Windows 10

Log when stable is installed:

> c:/users/user/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find crt1-sim.o: No such file or directory
> c:/users/user/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find _vectors.o: No such file or directory
> collect2.exe: error: ld returned 1 exit status
> exit status 1
> Errore durante la compilazione per la scheda WEMOS LOLIN32.

**Comment by me-no-dev** [comment]
what you have been doing has always been a bad idea :) tools are not necessarily the same between versions and Arduino will always fall-back on the one from the Board Manager URL

**Comment by fabiuz7** [comment]
> Arduino will always fall-back on the one from the Board Manager URL

Didn't know this. I was thinking the different cores were well-isolated like in "sandboxes". Maybe a note in the installation guide would be helpful.

Thanks!

**Comment by RudyFiero** [comment]
I make a portable install of Arduino for different versions.

**Comment by fabiuz7** [comment]
@RudyFiero link?

**Comment by lbernstone** [comment]
This can also be fixed by adding a platform.local.txt in your sketchbook folder (eg, \<HOME\>/Arduino/hardware/espressif/esp32) with the following:
`compiler.path={runtime.platform.path}/tools/{build.tarch}-{build.target}-elf/bin/`
