### ISSUE TITLE
Migrate Arduino IDE 2.0 

### ISSUE THREAD

**Issue by JAICHANGPARK** [espressif/arduino-esp32#5040]
In Arduino IDE 2.0, information that can be set for each board in the existing IDE is not displayed.

![image](https://user-images.githubusercontent.com/19484515/114298318-b5ed7a00-9af0-11eb-91ab-86b85c43e9a9.png)

**Comment by chansheunglong** [comment]
Does selecting ESP32 Dev Module show anything? My Arduino IDE 2.0.0 with arduino-ESP32 is showing the configuration normally.

**Comment by JAICHANGPARK** [comment]
@chansheunglong 
Thanks to comment 
can you show your IDE tools tab screen??

**Comment by chansheunglong** [comment]
![20210414_121326](https://user-images.githubusercontent.com/12199482/114653817-75257900-9d1b-11eb-8b35-422697404854.jpg)

Sure
I install arduino-esp32 via the board manager, haven't tried manual installation.
