### ISSUE TITLE
analogSetPinAttenuation does not work with Board v1.0.5 and v1.0.6, but it works with board 1.0.4. How can i fix this problem?

### ISSUE THREAD

**Issue by cbkaefer** [espressif/arduino-esp32#5041]
### Hardware:
|||
|:---|---|
|<B>Board</B>|ESP32 Dev Module|
|<B>Version/Date</B>|1.0.6||
|<B>IDE name</B>|Arduino IDE|
|<B>Flash Frequency</B>|80Mhz|
|<B>PSRAM enabled</B>|no|
|<B>Upload Speed</B>|115200|
|<B>Computer OS</B>|Windows 10|

### Description:
analogSetPinAttenuation does not work with Board v1.0.5 and v1.0.6, but it works with board 1.0.4. 
There is no fault message, the compiler works with this code, but it takes no effect.
How can i fix this problem?

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
analogSetPinAttenuation(34, ADC_0db);
adcAttachPin(34);
}

void loop() {
Serial.println(analogRead(34);
}

**Comment by Triangulix** [comment]
Looks like they completely broke the ADC API. Non-blocking reading is also gone.

**Comment by ssieb** [comment]
There's a bug in https://github.com/espressif/arduino-esp32/pull/3377.

**Comment by jesserockz** [comment]
Specifically a bug with 
https://github.com/espressif/arduino-esp32/blob/21947ebe76cf6380fe06aa885390b86cc477709a/cores/esp32/esp32-hal-adc.c#L132 

being called every time the adc pin is attached to, which overrides the `analogSetPinAttenuation` called from the code above
