### ISSUE TITLE
The ESP32 processor hangs on a second call to Serial.begin(115200) when compiled for ESP32 Dev Module.

### ISSUE THREAD

**Issue by ZinggJM** [espressif/arduino-esp32#5043]
```
// SerialBeginTwice test by Jean-Marc Zingg
//
// Purpose: test issue with ESP32 compiled for ESP32 Dev Module

void setup()
{
  Serial.begin(115200);
  delay(100);
  Serial.println("going to call Serial.begin(115200); a second time. Should tell success ...");
  delay(100);
  Serial.begin(115200);
  delay(100);
  Serial.println("... success, returned from second call to Serial.begin(115200); Bye and out.");
  delay(100);
}

void loop() {}
```

I verified this on a ESP32 Dev Module clone, on a Wemos LOLIN32 Lite, and on the Waveshare e-Paper ESP32 Driver Board.

The GxEPD2 examples call Serial.begin(115200) in setup() to Serial.print("setup"), and again in display.init(115200).

Related post in Arduino Forum Displays: https://forum.arduino.cc/index.php?topic=487007.msg4952538#msg4952538

**Comment by lbernstone** [comment]
Please follow the [ISSUE_TEMPLATE](https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md).

**Comment by ZinggJM** [comment]
Never mind if you are not interested. All relevant information is there, can be verified easily.

OS: Windows 10 - not relevant
Arduino IDE: 1.8.13
package: actual
target: 3 mentioned - not relevant
Error message: none
expected behavior: see both lines in Serial Monitor
actual behavior: only first line, processor hangs.

**Comment by lbernstone** [comment]
Can you please indicate what version of the code you are running?

**Comment by ZinggJM** [comment]
1.0.6 - is this the version you mean?

**Comment by lbernstone** [comment]
Well, there's an easy workaround.  I'll put in a PR and see if someone with JTAG can figure out what is actually causing the hang.

**Comment by ZinggJM** [comment]
I just repeated the test with ESP32-Wrover on LOLIN D32 PRO:
works when compiled for LOLIN D32 PRO
fails when compiled for ESP32 Wrover Module

**Comment by lbernstone** [comment]
If you set core debugging to verbose it will work.  This is a timing issue.

**Comment by ZinggJM** [comment]
Ok, thank you, I will try. But how to explain this to users of my library?

**Comment by ZinggJM** [comment]
Verbose didn't help, on LOLIN D32 PRO.

**Comment by ZinggJM** [comment]
Thank you for the fast response. Glad the issue is verified and a solution is found.

**Comment by ZinggJM** [comment]
This issue seems still to be present. See e.g. https://forum.arduino.cc/t/esp32-e-paper-display-upload-but-no-output/927375/3

**Comment by DriekdeGadgetfreak** [comment]
Here is the fix:.
In uartBegin the output buffer is flushed:
uartFlush(uart);
Change this to 
uartFlushTxOnly(uart,false);  // also flush the input buffer:

**Comment by ZinggJM** [comment]
**Maybe someone should make the old download link invalid, remove the version pointed to!**
I still get issues reported by users of this outdated version.

Jean-Marc
