### ISSUE TITLE
Example "GPIOInterrupt.ino" does not seem to compile

### ISSUE THREAD

**Issue by mars000** [espressif/arduino-esp32#5046]
Hi
I'm trying to compile the example:
`arduino-esp32/libraries/ESP32/examples/GPIO/GPIOInterrupt/GPIOInterrupt.ino`

using PlatformIO on latest esp32 arduino build but get following errors, am I doing something wrong ?:
![image](https://user-images.githubusercontent.com/19469711/114396997-908c6900-9be1-11eb-9aab-e92dad2a8058.png)

my` platformio.in`i file is:
![image](https://user-images.githubusercontent.com/19469711/114397062-9da95800-9be1-11eb-8993-0bceda7a6c58.png)

**Comment by felmue** [comment]
Hello @mars000 

about 7 days ago the example has been modified to work with ESP32S2 it seems. However those changes have not made it into PlatformIO yet. Or in other words, the example from github is too new for the esp32 Arduino library that comes with PlatformIO.

The two recent changes replaced `IRAM_ATTR` with `ARDUINO_ISR_ATTR`. So you could try to change them back.

Thanks
Felix

**Comment by mars000** [comment]
thanks Felix ;-)
