### ISSUE TITLE
Failed to resolve component 'arduino_tinyusb'.

### ISSUE THREAD

**Issue by bembite** [espressif/arduino-esp32#5054]
### Hardware:
Board:							ESP32-WROOM-32
Core Installation version:			1.0.3
IDE name:						IDF component
Computer OS:                                        Debian

Followed [this](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md) instructions to install arduino-esp32 to use as a component of ESP-IDF. Using sample sketch from this page. **I cannot build project with idf.py build**. Cmake output:

`Executing action: all (aliases: build)
Running cmake in directory /home/bembite/Projects/help-micro/esp32/dev/hello_world/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DIDF_TARGET=esp32 -DCCACHE_ENABLE=0 /home/bembite/Projects/help-micro/esp32/dev/hello_world"...
-- Found Git: /usr/bin/git (found version "2.30.0") -- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/bembite/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/bembite/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/bembite/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
CMake Error at /home/bembite/Projects/help-micro/esp32/esp-idf/tools/cmake/build.cmake:186 (message):
  Failed to resolve component 'arduino_tinyusb'.
Call Stack (most recent call first):
  /home/bembite/Projects/help-micro/esp32/esp-idf/tools/cmake/build.cmake:217 (__build_resolve_and_add_req)
  /home/bembite/Projects/help-micro/esp32/esp-idf/tools/cmake/build.cmake:426 (__build_expand_requirements)
  /home/bembite/Projects/help-micro/esp32/esp-idf/tools/cmake/project.cmake:395 (idf_build_process)
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "/home/bembite/Projects/help-micro/esp32/dev/hello_world/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1`

**Can I disable tinyusb as a component and how** (it is not supported by esp32)?   
My idf working fine for other projects and examples from esp-idf. Thanks!

**Comment by lbernstone** [comment]
Should be https://github.com/espressif/arduino-esp32/blob/master/CMakeLists.txt#L162
You may also need to turn off usb in menuconfig.
