### ISSUE TITLE
Hi, ESP32 ADC calibration problem

### ISSUE THREAD

**Issue by hzhh110** [espressif/arduino-esp32#5059]
Ok, I want to get the external voltage of the relay, and I found that the analogRead obtained is not accurate and non-linear. How to calibrate it?

There are also discrepancies in the acquisition of analogReadMilliVolts, and when there is Bluetooth and wifi, the discrepancy is even greater

**Comment by chansheunglong** [comment]
I replied to your close issue, so I will post it here again

You can reference this image from [this ](https://esp32.com/viewtopic.php?t=13089)link.
ESP32's ADC is non-linear, a quote from a forum member

> SAR is always going to be biased towards the ends of the scale, and the esp32 seems particularly insensitive there.

Take a look at this issue too: [https://esp32.com/viewtopic.php?t=13089](https://esp32.com/viewtopic.php?t=13089)

You will need to do an offset either using the official method in the documentation or simply just apply an offset/equation for your ADC reading in your code.

For the official documentation, it's here: [https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/adc.html#adc-calibration](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/adc.html#adc-calibration)

![ezgif-3-eb9a47b79de6](https://user-images.githubusercontent.com/12199482/114683485-a5344280-9d42-11eb-894d-947a957b3b64.jpg)
