### ISSUE TITLE
Compile errors for ESP32-C3

### ISSUE THREAD

**Issue by Jason2866** [espressif/arduino-esp32#5071]
Hi great work for supporting the C3!!

I encountered two errors from core when trying to compile project Tasmota for the C3
1st:
https://github.com/espressif/arduino-esp32/blob/master/tools/platformio-build-esp32c3.py#L74
it seems not supported from riscv32 gcc. Removing did solve
2nd:
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Esp.h#L114
not working for C3

@me-no-dev can you take a look?

Thx Jason

**Comment by me-no-dev** [comment]
@Jason2866 I did not encounter any build errors. Flags are extracted from ESP-IDF's build. As for some things not working... yeah :) still in early alpha

**Comment by Jason2866** [comment]
Changing too
```
{
    uint32_t ccount;
    //__asm__ __volatile__("esync; rsr %0,ccount":"=a" (ccount));
    asm volatile ("rdcycle x1" : "=r" (ccount) );
    return ccount;
}
```
in Esp.h solved

**Comment by lbernstone** [comment]
That change crashes my C3.  Does `systimer_hal_get_counter_value(SYSTIMER_COUNTER_0);` from hal/systimer_hal.h give you the correct value?  This should ultimately work for all the devices once the hal is functional.

**Comment by Jason2866** [comment]
Yes, you are right. Thx for your suggestion. Looks better now. Now crashes later ;-)
