### ISSUE TITLE
Unwanted debug message

### ISSUE THREAD

**Issue by qlalfdu** [espressif/arduino-esp32#5087]
|<B>Board</B>|ESP32 Dev Module|
|<B>Version/Date</B>|today's master|
|<B>IDE name</B>|Arduino IDE|
|<B>Flash Frequency</B>|80Mhz|
|<B>PSRAM enabled</B>no|
|<B>Upload Speed</B>|115200|
|<B>Computer OS</B>|Windows 10|

### Debug Messages: dhcps: send_nak>>udp_sendto result 0

WiFi.mode(WIFI_AP_STA) and
connect anything (smartphone, IOT divice, etc..) to the same router then A debug message of
"dhcps: send_nak>>udp_sendto result 0"

I want to turn this off, but I can't see it even after searching all the libraries. How can I turn it off?

![PN20-1233](https://user-images.githubusercontent.com/24924909/115315087-8e15aa80-a1b1-11eb-93a0-ca0de57992dd.png)

**Comment by lbernstone** [comment]
Verified fixed in both 1.0.6 and master.
