### ISSUE TITLE
How is WiFi radiation pattern of ESP32S2-saola-1

### ISSUE THREAD

**Issue by uecken** [espressif/arduino-esp32#5120]
Could you tell me WiFi radiation pattern of ESP32S2-saola-1 ?
I think this use meandered inverted F pattern.
I think ESP32 can communicate with 50m~100m if they set on ling of sight and the each beam are match.

**Comment by galed3e3** [comment]
Why are you asking a hardware question on a software issues site?
Anyway, you may find this interesting or helpful: http://www.jtl-engineering.nl/antenna.html  
Googling the antenna pattern name plus the word "directionality" would have led you there.
