### ISSUE TITLE
espressif huzzah cannot get usb driver working on macos

### ISSUE THREAD

**Issue by rednaxus** [espressif/arduino-esp32#5130]
Have tried all combinations found on the web...cannot get usb driver to load on mac no matter what I do...any advice?

e.g. installed usb and uart bridge, etc., but cu.xxx never shows up in /dev

https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers

**Comment by TheRealDJ** [comment]
What MAC OS version?

**Comment by rednaxus** [comment]
thanks ...  going to cancel this comment... was problem with the USB cable being the wrong type as some other has mentioned above
