### ISSUE TITLE
FreeRTOS V8.2 to V10.2 for arduino IDE

### ISSUE THREAD

**Issue by Rp777** [espressif/arduino-esp32#5143]
Hi All,

Are we going to get an update for freeRTOS from V8.2 to V10.2 for Arduino IDE?
When i install the ESP32 package on Arduino IDE V1.8.13, I see in the list that it still uses FreeRTOS V8.2
How can we upgrade to V10.2 in Arduino IDE?
Any pointers on this would be much helpful.

I know that we can use Arduino code to compile under ESP-IDF but as of now I do not want to use ESP-IDF .

I see that ESP-IDF now uses V10.2

**Comment by lbernstone** [comment]
Already included in the [development release](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md).

**Comment by Rp777** [comment]
> Already included in the [development release](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md).
@lbernstone Thank you.!
