### ISSUE TITLE
every Task running 2 times

### ISSUE THREAD

**Issue by nimaltd** [espressif/arduino-esp32#5149]
I am using platformio and esp-wroom32 . core 5.1.1
i create a new task. but my task run 2 times 
![image](https://user-images.githubusercontent.com/4112219/116979066-c51fac00-acd9-11eb-8d36-8478d28d0701.png)

**Comment by smarq8** [comment]
please share full code or prepare simplified example, screenshot is not suefficient to determine what happen.

**Comment by nimaltd** [comment]
in setup

**Comment by nimaltd** [comment]
TaskHandle_t                        hTaskASK;

void TaskASK(void * pvParameters);

void setup()
{
  xTaskCreatePinnedToCore(
        TaskASK,   /* Task function. */
        "TaskASK", /* name of task. */
        10000,     /* Stack size of task */
        NULL,      /* parameter of the task */
        4,         /* priority of the task */
        &hTaskASK, /* Task handle to keep track of created task */
        0);        /* pin task to core 0 */
}

and my new task 

void TaskASK(void * pvParameters)
{
    int x;
 
   while (1)
    {
   
        x++;
        Serial.println(x);
        delay(1000);
    }
}

**Comment by nimaltd** [comment]
I found it. I created a init() function. I think in arduino platform it called again.
