### ISSUE TITLE
ESP.restart() skips the first stage bootloader.

### ISSUE THREAD

**Issue by aovestdipaperino** [espressif/arduino-esp32#5151]
### Hardware:
Board:							ESP32 Dev Module

### Description:
ESP.restart() skips the first stage bootloader.
I have some strapped pins but they get ignored when I issue ESP.restart() (probably by executing the second stage bootloader).

I cannot find a way to get the board do a full reboot. Maybe add a parameter to restart to indicate if the first stage bootloader should be skipped?

**Comment by lbernstone** [comment]
I'm not sure, but I think abort() should behave more like a power reset.
