### ISSUE TITLE
Bug/error in Wire library

### ISSUE THREAD

**Issue by lgLindstrom** [espressif/arduino-esp32#5153]
Hi

**read** returns **int** when it should be **uint8_t**, same as **rxBuffer**. 

```
int TwoWire::read(void)
{
    int value = -1;
    if(rxIndex < rxLength) {
        value = rxBuffer[rxIndex];
        ++rxIndex;
    }
    return value;
}
```

**Comment by lbernstone** [comment]
This is part of the Arduino spec.  It is defined as int there.

**Comment by lgLindstrom** [comment]
Well...

This is reference documentation https://www.arduino.cc/en/Reference/WireRead

**Comment by VojtechBartoska** [comment]
@lgLindstrom Can I consider it solved?
