### ISSUE TITLE
Windows 10-esp32 bluetooth connection

### ISSUE THREAD

**Issue by DavidePasero** [espressif/arduino-esp32#5164]
### Hardware:
Board:							DOIT esp32 DEVKIT V1
Core Installation version:			don't know
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                     no
Upload Speed:				       115200
Computer OS:                                        Windows 10

### Description:
Hello everyone, I'm trying to connect via bluetooth my DOIT esp32 DEVKIT V1 with my windows 10 pc. I have a desktop pc, and in order to implement bluetooth I have a Bluetooth adapter; the problem is that my pc sees Esp32test, but when I try to pair them (after pressing the EN button on the esp32 board) a weird error message appears: 
ASSERT_WARN(103 23), in lc_task.c at line 8775ASSERT_WARN(103 24), in lc_task.c at line 8775.
(Solution is in my last comment)

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/tree/master/libraries/BluetoothSerial

**Comment by DavidePasero** [comment]
> https://github.com/espressif/arduino-esp32/tree/master/libraries/BluetoothSerial

What does it mean?

**Comment by DavidePasero** [comment]
To everyone who will have the same problem: use esp32 core installation 1.0.4 instead of 1.0.6 (which, right now in 2021 is the latest). To do that you go on Arduino IDE - Board manager - uninstall esp32 libraries - reinstall esp32 library but use version 1.0.4

**Comment by Lukaswnd** [comment]
I got the same Problem. Any Windows 10 system (i tried 4 different) have huge issues to connect to a esp32.
I also tried to use all of my esp32's including esp32s, esp32-woover-e, esp32-wroom,  esp32-wroom-e,  esp32-wroom-u.

There was one chip among 10, that could make a connection to win10, but it was by far not the first tries.
10 Minutes ago i found this issue and BAM with version 1.0.4 it works perfectly fine

**Comment by LIUHanyang96** [comment]
> I got the same Problem. Any Windows 10 system (i tried 4 different) have huge issues to connect to a esp32. I also tried to use all of my esp32's including esp32s, esp32-woover-e, esp32-wroom, esp32-wroom-e, esp32-wroom-u.
> 
> There was one chip among 10, that could make a connection to win10, but it was by far not the first tries. 10 Minutes ago i found this issue and BAM with version 1.0.4 it works perfectly fine

The same issue. I cannot pair Win 11 or Android with ESP32-WROOM, but it can pair with Macbook.

**Comment by erikaemma** [comment]
But I am using 1.0.6, Win10 and Android works fine, but Bluetooth LE Explorer can't scan it.
