### ISSUE TITLE
A fatal error occurred: Invalid head of packet (0x01)

### ISSUE THREAD

**Issue by Rudy25** [espressif/arduino-esp32#5170]
greetings, someone could help me, please with the ESP32-WROOM-32 on my macBook Air I get this error:

esptool.py v3. 0-dev
Serial port /dev/cu.usbserial-1410
Connecting.....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, vref calibration in effuse, Coding Scheme None
Crystal is 40MHz
MAC: 84: cc: a8: 5f: ba: 34
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...

A fatal error occurred: Invalid head of packet (0x01)
A fatal error occurred: Invalid head of packet (0x01)

**Comment by lbernstone** [comment]
Try a different cable.  There are many existing issues with tips about this.  95% boil down to a bad/charging cable.

**Comment by carryonrewardless** [comment]
I needed to change Upload Speed to 115200 to get this error resolved.  No good at 91600 on any cable.
