### ISSUE TITLE
 bug: Arduino IDE 'Export compiled Binary' doesn't work (2.0.0-alpha1 only)

### ISSUE THREAD

**Issue by societyofrobots** [espressif/arduino-esp32#5174]
'Export compiled Binary' should place a .bin file into my project folder.

This works as expected using 1.0.6, however does not work with alpha1. Both compile fine without error.

```
Arduino IDE + alpha1
Windows 10
```

In the meantime, I can still locate the .bin file here:
`C:\Users\X\AppData\Local\Temp\arduino_build_XXXX\`

**Comment by calkoe** [comment]
Faced the same issue with the latest Version, 
get a slightly older commit and it works fine.

use this in your platform.ini:

```
platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#7856de7
    toolchain-xtensa32 @ ~2.80400.0
```
