### ISSUE TITLE
esp32 shows 240Mhz seems working at 160Mhz

### ISSUE THREAD

**Issue by gkourtis** [espressif/arduino-esp32#5191]
The bellow code makes the led at pin 21 flash with a period of roughly 27.5 seconds (half of them on half of).
Given that 256*256*65536/160,000,000=26,84... it makes sense to suppose that the clock entering the unit gets a clock at 160MHz. 
querying for the speed via rtc_clk_cpu_freq_get() it gives 3 that meaning 240MHz.
So what is going on ?

MCPWM1.clk_cfg.prescale=255;
  MCPWM1.timer[0].period.prescale = 255;        // Set timer 0 prescaler to 199 (800kHz/(199+1))=4kHz)
  MCPWM1.timer[0].period.period=65535;
  MCPWM1.channel[0].cmpr_value[0].val=MCPWM1.timer[0].period.period/2;
  MCPWM1.channel[0].generator[0].utez = 2;      // Set the PWM0A ouput to go high at the start of the timer period
  MCPWM1.channel[0].generator[0].utea = 1;      // Clear on compare match
  MCPWM1.timer[0].mode.mode = 1;                // Set timer 0 to increment
  MCPWM1.timer[0].mode.start = 2; 
  
  mcpwm_gpio_init(MCPWM_UNIT_1, MCPWM0A, 21);

**Comment by lbernstone** [comment]
The maximum (ie div=1) is 40MHz as per [docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/ledc.html#supported-range-of-frequency-and-duty-resolutions).
It seems like it would just be a lot easier to use mcpwm_set_frequency and let the computer do the math for you.  They are really good at that.
