### ISSUE TITLE
How to use http ota without certificates?

### ISSUE THREAD

**Issue by shariq-azim** [espressif/arduino-esp32#5200]
Hello,
I would just like to know how to use the example mentioned in 

https://github.com/espressif/arduino-esp32/blob/master/libraries/Update/examples/HTTPS_OTA_Update/HTTPS_OTA_Update.ino
but without the   certificates, and what other changes do we need to  do there?

Regards,
Shariq

**Comment by TheRealDJ** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/HTTPUpdate/examples/httpUpdate/httpUpdate.ino

**Comment by chegewara** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/Update/src/HttpsOTAUpdate.cpp#L87
`skip_cert_common_name_check = true`
NOT RECOMMENDED

**Comment by shariq-azim** [comment]
Try this?
