### ISSUE TITLE
ESP 32 AsyncWebServer download a .txt file? 

### ISSUE THREAD

**Issue by ebm9991** [espressif/arduino-esp32#5212]
I work with the ESP32, I use an AsyncWebServer, at some point I have to press a botton of the html interface to save data in a file named test.txt, and download this file automatically at the end of save on browser, i tried using code below, button works, save function works, but obtained file is not downloaded to browser at the end !! how can I do to fix this please? thank you.

server.on("/Rgs", HTTP_GET, [](AsyncWebServerRequest *request){
Serial.println(" /Rgs exécuted ...");
saveValues();  // function to save values on test.txt file
request->send(SPIFFS, "/test.txt", "text/html", true);
});

**Comment by BoYi0126** [comment]
Maybe you can try this,
request->send(SPIFFS, "/test.txt", String(), true);
