### ISSUE TITLE
Arduino IDE Compiler Warnings

### ISSUE THREAD

**Issue by zfields** [espressif/arduino-esp32#5243]
### Hardware:
Board:							Adafruit Huzzah32
Core Installation version:			1.0.6
IDE name:						Arduino IDE
Flash Frequency:					40Mhz
PSRAM enabled:                                    ?
Upload Speed:					921600
Computer OS:                                        Ubuntu

### Description:

Compiling a sketch produced the following errors.

### Debug Messages:
```
/home/zak/.arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/esp32-hal-spi.c: In function 'spiTransferBytesNL':
/home/zak/.arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
                                       ^
/home/zak/.arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/esp32-hal-spi.c:923:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_data8 = &last_data;
                                        ^
```

**Comment by lbernstone** [comment]
already fixed in 2.0
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-spi.c#L1273-L1274
