### ISSUE TITLE
ESP Rainmaker does not compile for ESP32S2/C3

### ISSUE THREAD

**Issue by JohnMacrae** [espressif/arduino-esp32#5244]
### Hardware:
Board:							ESP32 Dev Module - OK ESP32S2 dev module - FAIL ESP32C3 Dev module _ FAIL
Core Installation version:			Current alpha in stalled via boards manager
IDE name:						Arduino IDE
Flash Frequency:					40Mhz
PSRAM enabled:                                    no
Upload Speed:					?115200?
Computer OS:                                        Windows 10

### Description:
Attempt to compile to single given example "RMakerDevice" for ESP Rainmaker for ESP32S2 or C3

*Describe what is failing.

Example compiles and runs on ESP32 (ESP32Dev Module) just fine
Using C3 or S2, compiling fails with "'Switch' does not name a type"

### Debug Messages:
```
Not core debug but here is the compiler log. I suspect the Arduino version of Rainmaker is not compiled for these modules.
[CompileLog.txt](https://github.com/espressif/arduino-esp32/files/6595676/CompileLog.txt)

**Comment by VojtechBartoska** [comment]
I contacted ESP Rainmaker team about this issue. Will give you an update.

**Comment by JohnMacrae** [comment]
Thank you :)
