### ISSUE TITLE
esp32 c3 的hardwareSerial库不能用，串口不能收发

### ISSUE THREAD

**Issue by BG2CRW** [espressif/arduino-esp32#5247]
esp32 c3 的hardwareSerial库不能用，串口不能收发

**Comment by BG2CRW** [comment]
代码如下：

HardwareSerial mySerial1(1);
void setup() {
  mySerial1.begin(115200, SERIAL_8N1, 5, 18); //rx:5,tx:18
}

void loop() {
	mySerial1.println("hello world");
	delay(1000);

}

**Comment by lbernstone** [comment]
Yes.  HardwareSerial needs to be rewritten to use the new driver/hal.

**Comment by VojtechBartoska** [comment]
@BG2CRW Please keep your issue in English here.

**Comment by lengbuyu** [comment]
@VojtechBartoska 
He's mean is 
ESP32 C3 can't use HardwareSerial Library, the serial port cannot receive and send.

Code：
HardwareSerial mySerial1(1);
void setup() {
mySerial1.begin(115200, SERIAL_8N1, 5, 18); //rx:5,tx:18
}

void loop() {
mySerial1.println("hello world");
delay(1000);
}

Just help translate.

**Comment by lybgo** [comment]
When can we solve this problem?
I have products that also need to use Serial1 communication
