### ISSUE TITLE
HardwareSerial doesn't work anymore from 1.0.4 to 1.0.6

### ISSUE THREAD

**Issue by Titibo26** [espressif/arduino-esp32#5259]
Hello,

I updated though arduino IDE board manager from 1.0.4 to 1.0.6 and now i can't compile sketches, it gives me the following error :

`C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\HardwareSerial.cpp: In member function 'void HardwareSerial::begin(long unsigned int, uint32_t, int8_t, int8_t, bool, long unsigned int, uint8_t)':
C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\HardwareSerial.cpp:84:102: error: too many arguments to function 'uart_t* uartBegin(uint8_t, uint32_t, uint32_t, int8_t, int8_t, uint16_t, bool)'
  _uart = uartBegin(_uart_nr, baud ? baud : 9600, config, rxPin, txPin, 256, invert, rxfifo_full_thrhd);
                                                                                                      ^
In file included from C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\esp32-hal.h:52:0,
                 from C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\HardwareSerial.h:44,
                 from C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\HardwareSerial.cpp:7:
C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\esp32-hal-uart.h:54:9: note: declared here
 uart_t* uartBegin(uint8_t uart_nr, uint32_t baudrate, uint32_t config, int8_t rxPin, int8_t txPin, uint16_t queueLen, bool inverted);
         ^
C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\HardwareSerial.cpp:100:102: error: too many arguments to function 'uart_t* uartBegin(uint8_t, uint32_t, uint32_t, int8_t, int8_t, uint16_t, bool)'
    _uart = uartBegin(_uart_nr, detectedBaudRate, config, rxPin, txPin, 256, invert, rxfifo_full_thrhd);
                                                                                                      ^
In file included from C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\esp32-hal.h:52:0,
                 from C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\HardwareSerial.h:44,
                 from C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\HardwareSerial.cpp:7:
C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\esp32-hal-uart.h:54:9: note: declared here
 uart_t* uartBegin(uint8_t uart_nr, uint32_t baudrate, uint32_t config, int8_t rxPin, int8_t txPin, uint16_t queueLen, bool inverted);
`

Any clue on what happens ? (working on esp32 devkit doit)

**Comment by chegewara** [comment]
```
C:\Users\Thibaud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\HardwareSerial.cpp:100:102: error: too many arguments to function 'uart_t* uartBegin(uint8_t, uint32_t, uint32_t, int8_t, int8_t, uint16_t, bool)' _uart = uartBegin(_uart_nr, detectedBaudRate, config, rxPin, txPin, 256, invert, rxfifo_full_thrhd);
```
https://github.com/espressif/arduino-esp32/blob/1.0.6/cores/esp32/HardwareSerial.cpp#L100
