### ISSUE TITLE
Using HSPI port on ESP32

### ISSUE THREAD

**Issue by lengbuyu** [espressif/arduino-esp32#5264]
### Hardware:
Board:							ESP32-Dev
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Windows 10

### Description:
My case with https://github.com/espressif/arduino-esp32/issues/1219 same have SD cad and RC522.
But I cannot successfully connect to RC522.
I also reference these issues to try to solve my problem:
[https://github.com/espressif/arduino-esp32/issues/1219](url)
[https://github.com/miguelbalboa/rfid/issues/497](url)
[https://github.com/nkolban/esp32-snippets/issues/61](url)

Could anyone help me ?
### Sketch:
```cpp
#include <SPI.h>
#include <MFRC522.h>

#define RFID_RST_PIN  27
#define RFID_H_MISO   12
#define RFID_H_MOSI   13
#define RFID_H_CLK    14
#define RFID_H_SS     15

SPIClass spiRFID(HSPI);
MFRC522 mfrc522(RFID_H_SS, RFID_RST_PIN);

void setup(){
  Serial.begin(115200);
  while(!Serial);
  //CLK, MISO, MOIS, SS
  spiRFID.begin(RFID_H_CLK, RFID_H_MISO, RFID_H_MOSI, RFID_H_SS); 
  mfrc522.PCD_Init();

  delay(4);

  mfrc522.PCD_DumpVersionToSerial();
}

void loop(){

}
```

### Debug Messages:
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
Firmware Version: 0x0 = (unknown)
WARNING: Communication failure, is the MFRC522 properly connected? 
```

**Comment by me-no-dev** [comment]
the problem is that the library is not made to accept another SPI class and instead relies on the main `SPI`. There is no issue in this Arduino repository.
