### ISSUE TITLE
UART2 receive - 2 stop bit, not responding

### ISSUE THREAD

**Issue by padmaraj1008** [espressif/arduino-esp32#528]
Hi,
We are working with ESP wroom 32 and communicating to TI's ultrasonic AFE PGA460 through UART2 interface. 
We are unable to get data  back from PGA chip on UART2 of ESP32 with 2 stop bits, we are able to communicate with proper data on UART2 interface with pic, MSP and all other controllers but not with ESP 32. 
We are struggling with this issue since many days, still didn't got any solution about this. 
We are able to send data from esp32 but no response from PGA(serial available not getting any bytes)

Kindly requesting you to reply asap with the solution to fix the problem.
Thank you in advance.

**Comment by copercini** [comment]
Are you running the last git version?
It looks like this has been fixed few days ago: https://github.com/espressif/arduino-esp32/pull/461/

**Comment by padmaraj1008** [comment]
Hello,
We did changes to latest version but still PGA is not responding for two stop bits.

**Comment by copercini** [comment]
Just for check, how are you starting the Serial2 ?

**Comment by copercini** [comment]
Try something like this:

```cpp
HardwareSerial Serial2(2);

Serial2.begin(9600, SERIAL_8N2, 16, 17); //baud rate, 8 data bits - no parity - 2 stop bits, RX pin, TX pin
```

**Comment by padmaraj1008** [comment]
Hello,

Thanks for your valuable suggestions,
Tx and Rx pins from ESP wroom32 are internally pulled down because of this reason UART2 not responding,I included  pull up resistor of 10k on both pins to get it working now it is responding.

Thank you.

**Comment by sundar19** [comment]
Hi , can you please tell me how did you achieve it? I am trying to interface pga460q1psm evm with arduino mega. I am using the modified energia libraries provided by TI but it didnt help us out
