### ISSUE TITLE
Esp32c3 `Serial.baudRate()` is 2x too high

### ISSUE THREAD

**Issue by s-hadinger** [espressif/arduino-esp32#5287]
### Hardware:
Board:							ESP32-C3-DevKitM-1
Core Installation version:			2.0.0 alpha1
IDE name:						Platform.io
Flash Frequency:					40Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Mac OSX

### Description:
Describe your problem here

The baudrate returned by `Serial.baudRate()` is twice the expected value.

The Serial port is opened with 115200, but `Serial.baudRate()` returns ~230400.

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp
#include <Arduino.h>

void setup() {
  Serial.begin(115200);
}

void loop() {
  Serial.printf(">> Serial baudrate: %d\n", Serial.baudRate());
  delay(1000);
}
// Output:
// >> Serial baudrate: 230423
```

**Comment by lbernstone** [comment]
Yes, uart needs to be rewritten.  This should be a workaround until then:
```
#include <driver/uart.h>
void setup() {
  Serial.begin(115200);
  uint32_t br;
  uart_get_baudrate(0, &br);
  Serial.println(br);
}
```

**Comment by s-hadinger** [comment]
Thanks, this works fine.

**Comment by SuGlider** [comment]
UART is being refactored to be based on IDF and this issue shall be solved when it is released.
