### ISSUE TITLE
v1.0.5 and above slow down the ADC speed

### ISSUE THREAD

**Issue by englandsaurus** [espressif/arduino-esp32#5325]
Hello, I am wondering what was changed in between 1.0.4 and 1.0.5 that made the ADC read happen more slowly. I have an application that reads the ADC as a mic input and subsequently performs an FFT on the signal. With a fresh install of Arduino on a new computer I found that my code ran about 10x slower. I was able to narrow this down to the difference between using 1.0.4 and 1.0.5/6. Unsure what the issue is here. I'm using the ArduinoFFT library and also end up using `#include <driver/adc.h>`

Not a big issue for me at the moment since I just rolled back to 1.0.4 but let me know if there's any investigating I can do.

**Comment by ssieb** [comment]
Most likely caused by https://github.com/espressif/arduino-esp32/pull/3377.
