### ISSUE TITLE
Reduce code size

### ISSUE THREAD

**Issue by savagerex** [espressif/arduino-esp32#5326]
I use esp32 with 4M flash, But our program has exceeded it, is there any way to reduce the program ???

### Hardware:
Board : ESP32 dev module
Core install version: 1.0.4
IDE name : Arduino
Flash Frequency : 80MHz
PSRAM Enable : yes
upload speed :115200
computer os : win10

**Comment by maxgerhardt** [comment]
The compiler is already set for `-Os` (optimize for size), you should probably just select a different partition table inte `Tools` settings to allow for a larger `app0` size.

**Comment by chegewara** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/index.html
