### ISSUE TITLE
millis() resolution 10 msec only 

### ISSUE THREAD

**Issue by vortex314** [espressif/arduino-esp32#533]
Posted probably in the wrong repository : https://github.com/espressif/esp-idf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20millis

**Comment by everslick** [comment]
your provided link points to nowhere.

**Comment by vortex314** [comment]
correct, the issue is closed there and the url is looking for the open issue. 
https://github.com/espressif/esp-idf/issues/829
root cause the time tick of freeRTOS is by default 100Hz, it can be changed by menuconfig to 1000Hz.
