### ISSUE TITLE
What is the schedule to support USB DFU for ESP32 S2 and C3

### ISSUE THREAD

**Issue by jonesfu** [espressif/arduino-esp32#5347]
We have project with ESP32 S2 chip, we hope use USB DFU function for low cost concern.

**Comment by igrr** [comment]
@jonesfu Could you clarify, what kind of support do you expect from the Arduino-ESP32 project? USB DFU is a feature of ESP32-S2 chip, you can use with existing tool such as [dfu-util](http://dfu-util.sourceforge.net/).

Regarding ESP32-C3, unlike ESP32-S2 this chip doesn't have a programmable USB device controller, so it doesn't support DFU.

**Comment by jonesfu** [comment]
How to use dfu-util on ESP32 S2?

**Comment by jonesfu** [comment]
Another, the best way is doing DFU by arduino

**Comment by me-no-dev** [comment]
@jonesfu any particular reason why not use USB-CDC instead? It uses the same USB lines and works out of the box.

**Comment by lbernstone** [comment]
I get that C3 doesn't have a USB controller, but is it possible to get simple console output on the USB for debugging purposes?  I can program easily with CDC in the bootloader, but am essentially blind after that.  Sorry to hijack.

**Comment by jonesfu** [comment]
> @jonesfu any particular reason why not use USB-CDC instead? It uses the same USB lines and works out of the box.

Because we expect remove USB-CDC chip for cost concern

**Comment by me-no-dev** [comment]
@jonesfu I do not mean to use the USB-UART chip connected to TX and RX, I mean using a USB port connected to GPIOs 18 and 19, booting into download and uploading using esptool. You do not need external chip for that. Download mode on S2 supports both DFU and CDC flashing over the internal USB port

**Comment by jonesfu** [comment]
@me-no-dev Yes! After connect USB port by USB D- to GPIO20 and USB D+ to GPIO19,  and press boot key when ESP32 S2 chip power up, then we can found USB CDC device in windows. But there are some problem as blew:

1. Under Win10, there is no default USB CDC driver for ESP32 S2, need install another driver as https://www.esp32.com/viewtopic.php?t=15222

2. under Arduino PlatformIO build environment, it will error report after flash firmware bin as:
ERROR: ESP32-S2FH32 chip was placed into download mode using GPIO0.
esptool.py can not exit the download mode over USB. To run the app, reset the chip manually.
To suppress this error, set --after option to 'no_reset'.

We think it should be WARNING, not treated as ERROR, could you please fix it?

**Comment by me-no-dev** [comment]
the message comes from esptool to notify you that it can not auto-reboot the board and you need to do it manually. You can submit an issue in esptool's repository, if you want to talk to the devs about changing the message. But even if changed, esptool as binary needs to return error anyway, because executables either succeed or fail in execution.

**Comment by igrr** [comment]
https://github.com/espressif/esptool/issues/631 has changed the "ERROR" message to "WARNING", this fix can be included next time esptool is updated.

**Comment by igrr** [comment]
This is fixed in the v2.0.3-rc1 release.
