### ISSUE TITLE
Installation instructions for Mac OS have some problems

### ISSUE THREAD

**Issue by Tinyu-Zhao** [espressif/arduino-esp32#5349]
system:macos Big Sur 11.4 

An error occurred during the execution of the following code and failed to solve it after many attempts
`mkdir -p ~/Documents/Arduino/hardware/espressif && \
cd ~/Documents/Arduino/hardware/espressif && \
git clone https://github.com/espressif/arduino-esp32.git esp32 --depth 1 && \
cd esp32 && \
git submodule update --init --recursive --depth 1 && \
cd tools && \
python get.py `

Error code in the terminal:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/44396641/124300325-08d74a80-db91-11eb-92a4-8e7b2f302f5f.png">

The same is true when I use python3 to execute:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/44396641/124300855-94e97200-db91-11eb-85cf-6eed4054bced.png">

**Comment by lbernstone** [comment]
Are you able to download https://github.com/espressif/crosstool-NG/releases/download/esp-2020r3/xtensa-esp32s2-elf-gcc8_4_0-esp-2020r3-macos.tar.gz in a browser?  You do not seem to have the necessary SSL certificate root.

**Comment by Tinyu-Zhao** [comment]
> Are you able to download https://github.com/espressif/crosstool-NG/releases/download/esp-2020r3/xtensa-esp32s2-elf-gcc8_4_0-esp-2020r3-macos.tar.gz in a browser? You do not seem to have the necessary SSL certificate root.

Yes, it works in my browser

**Comment by marcelstoer** [comment]
Isn't this exactly what's documented in the 2nd to last bullet point at https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/mac.md#installation-instructions-for-mac-os?
