### ISSUE TITLE
Add partition table

### ISSUE THREAD

**Issue by ulas95** [espressif/arduino-esp32#5359]
hi, i am trying to develop hardware with wroom 16mb. I need a partition table with 3mb app and 12.9mb spiffs and no ota. Can you add this in ESP32 Dev Module? I made an example partition table. I am sharing this below.

### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.3
IDE name:						Arduino IDE
Flash Frequency:					40Mhz
PSRAM enabled:                                      no
Upload Speed:					115200
Computer OS:                                        Windows 10

3mb app 12.9mb spiffs, No ota partition table:

# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,     app,  ota_0,   0x10000, 0x300000,
spiffs,   data, spiffs,  0x310000, 0xCF0000,

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/issues/4551
