### ISSUE TITLE
ESP32 4M & 8m

### ISSUE THREAD

**Issue by savagerex** [espressif/arduino-esp32#5366]
i use code and upload to esp32 4M. it's ok

but same code upload to esp32 4M. esp32 always reboot.

below is exception tool loag.

![image](https://user-images.githubusercontent.com/79502707/124925175-c13c3d00-e02e-11eb-96a5-a42ea561e6b9.png)

**Comment by savagerex** [comment]
sorry 

 same code upload to esp32 8M. esp32 always reboot.

**Comment by me-no-dev** [comment]
So once you flashed 4M chip and then 8M chip with the same firmware and you got different result?
The trace seem to point into stack error. Are you running out of memory? The flash size should not play a role into that.

**Comment by pipi61** [comment]
try: select 8M and compile again

**Comment by lbernstone** [comment]
Perhaps you are choosing 8M, but your board does not have 8M?  Please read the [issue template](https://github.com/espressif/arduino-esp32/blob/master/docs/ISSUE_TEMPLATE.md ) carefully.

**Comment by savagerex** [comment]
@me-no-dev   Yes, I got different result.

same firmware upload.

**Comment by me-no-dev** [comment]
@savagerex that makes no sense, unless there is something physically wrong with the board/chip. Error points at stack/memory error and should have been the same on all boards. Can you try on more boards?

**Comment by savagerex** [comment]
Sorry ,  it is solved.   i choose wrong flash size.

Thx
