### ISSUE TITLE
Set Static ip 

### ISSUE THREAD

**Issue by savagerex** [espressif/arduino-esp32#5369]
Sorry, there is the problem

(esp32 connect phone)
when i set Static ip , then https work.   
after reset esp32, then https work.  

(esp32 connect Wifi - AP)
when i set Static ip , then https work.   
after reset esp32, then https fail.

**Comment by me-no-dev** [comment]
@savagerex please use the issue template. You are not providing nearly enough information again.
We need code, serial logs and so on.

**Comment by savagerex** [comment]
@me-no-dev   I will send the code to esp fae Ma Li.

but i suggest you connect to my computer and use "anydesk" software.

because you have code, no our board.
