### ISSUE TITLE
Core 2.0.0 complie error

### ISSUE THREAD

**Issue by savagerex** [espressif/arduino-esp32#5370]
when i complie the code in core 1.0.4 , it's ok

but i complie the code in core 2.0.0 , it's fail
----------------------------- Remove above -----------------------------

### Hardware:
Hardware:
Board : ESP32 dev module
Core install version: 2.0.0
IDE name : Arduino
Flash Frequency : 80MHz
PSRAM Enable : yes
upload speed :115200
computer os : win10

below is error

![image](https://user-images.githubusercontent.com/79502707/125067148-73830b80-e0e6-11eb-98f3-900eaa7b3b11.png)

**Comment by me-no-dev** [comment]
did you restart the IDE? something is missing from the package

**Comment by savagerex** [comment]
Yes!!  i has restarted Arduino IDE

it still appear error

![image](https://user-images.githubusercontent.com/79502707/125069545-716e7c00-e0e9-11eb-8a1b-c3f8d0cd73b3.png)

**Comment by me-no-dev** [comment]
then try uninstalling and reinstalling the package. You have missing/wrong files.

**Comment by savagerex** [comment]
i has install esp32 https server package.

![image](https://user-images.githubusercontent.com/79502707/125070677-e0000980-e0ea-11eb-84fd-aa3a4d81e301.png)

but still have error.

**Comment by savagerex** [comment]
all lib ,  i has reinstall.

**Comment by me-no-dev** [comment]
not the libs! the core! the esp32 core version 2.0.0beta1 is that you need to reinstall

**Comment by savagerex** [comment]
OK!!!  i try it

**Comment by savagerex** [comment]
what device i need to choose??

before i choose "ESP32 Dev Module".

![image](https://user-images.githubusercontent.com/79502707/125076437-7c79da00-e0f2-11eb-8081-71157e62b55c.png)

**Comment by savagerex** [comment]
there is 2.0.0 alpha1.  don't have 2.0.0beta1

![image](https://user-images.githubusercontent.com/79502707/125077316-89e39400-e0f3-11eb-8464-4f6a820a73e8.png)

**Comment by Jason2866** [comment]
alpha is the correct one. There is no beta

**Comment by savagerex** [comment]
After reinstall core  2.0.0 alpha1, still have error!!!

**Comment by me-no-dev** [comment]
rename the library folder to NOT have chinese symbols.

**Comment by savagerex** [comment]
the path and folder is no chinese.

![image](https://user-images.githubusercontent.com/79502707/125261720-1ed4d000-e334-11eb-872f-80afb2c59ff2.png)

**Comment by me-no-dev** [comment]
Not the core... your libraries:

![125077316-89e39400-e0f3-11eb-8464-4f6a820a73e8](https://user-images.githubusercontent.com/12663778/125262238-af96b600-e30a-11eb-8bb8-a742ce603c59.png)

**Comment by savagerex** [comment]
now i can complie.

Crashes during compilation.

Arduino ide will close by itself.

**Comment by savagerex** [comment]
it always stuck in here!!

![image](https://user-images.githubusercontent.com/79502707/125263236-70ca2580-e335-11eb-8f6a-128103943a2f.png)

**Comment by me-no-dev** [comment]
there is no error shown. Did you try another computer as Ma Li suggested?

**Comment by savagerex** [comment]
Ok,i try another computer

**Comment by savagerex** [comment]
I use "Arduino 1.8.15" & core 2.0.0.
it can complie.

test https.  
if all tesk enable, https fail.
if all tesk disable, https ok.

the memory is not enough.

**Comment by me-no-dev** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html#restrictions
https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/esp32/sdkconfig#L529

So short answer is NO, long is that you should look into optimizing your task's stack sizes, allocate using malloc, rather than on the stack, or build your custom SDK with CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY enabled (complicated task).

**Comment by savagerex** [comment]
OK!!! THX

**Comment by savagerex** [comment]
@me-no-dev 

finally, we use https communication several times. the heap will Keep decreasing.
the memory don't release.

when memory is not enough, the https fail.

**Comment by savagerex** [comment]
@me-no-dev 

i find use  https  "Put"  command. ESP32 heap will decrease.

how to release memory???

**Comment by VojtechBartoska** [comment]
Hello @savagerex, I'm closing this issue. If you still need help you can reopen this one or create a new issue. Thanks for your contribution.
