### ISSUE TITLE
Modify the face recognition threshold in arduino-esp32

### ISSUE THREAD

**Issue by dazhao168** [espressif/arduino-esp32#5377]
**Hardware:**
Board:ESP32-CAM
Version:1.0.4
IDE name:Arduino IDE
Flash Frequency:80MHz
PARAM enabled:yes
Upload Speed:921600
Computer OS:Windows10
**Descriptions:**
In the C:\Users\XXX\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\tools\sdk\include\esp-face path, has the FACE_REC_THRESHOLD in the fr_forward.h file been enabled? I changed the threshold value of 0.5 to 0.9 or 0.1, there is no obvious change in the recognition accuracy?
What changes are needed to increase the accuracy rate? thank!

Sketch:
mtmn_config.min_face = 56;
config.frame_size = FRAMESIZE_QQVGA;

In fr_forward.h, modify the FACE_REC_THRESHOLD macro definition to 0.9

**Comment by VojtechBartoska** [comment]
@dazhao168 Please provide more info about your issue by following Issue template. Keep in mind that main language here is English.

**Comment by dazhao168** [comment]
@VojtechBartoska Please take a look, can this clearly describe the problem?

**Comment by VojtechBartoska** [comment]
Hello @dazhao168  , sorry for late reply. Are you able to test your issue on development version [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) to check if this is still valid? You can take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by VojtechBartoska** [comment]
Hello, due to no answer I'm closing this issue as expired.

If you still need help, please reopen it.

Thanks for understanding!
