### ISSUE TITLE
Refactoring of UART of ESP-IDF APIs

### ISSUE THREAD

**Issue by VojtechBartoska** [espressif/arduino-esp32#5382]
Related issues:
#5112
#5047 
#5362

Resolution will be added later.

### Hardware:
Board:							ESP32. ESP32-S2
Core Installation version:			2.0.0 alpha

**Comment by SuGlider** [comment]
Issue #5112 and issue # 5047 solved and closed with PR https://github.com/espressif/arduino-esp32/pull/5385
Already merged in master

**Comment by SuGlider** [comment]
Issue #5362 solved with PR https://github.com/espressif/arduino-esp32/pull/5389

**Comment by SuGlider** [comment]
All issues listed are solved/closed.
