### ISSUE TITLE
ESP32 built-in hall sensor is not working

### ISSUE THREAD

**Issue by Dcmwrnd** [espressif/arduino-esp32#5400]
I have tried a few ESP32 boards & the built-in hall sensor does not work with v1.0.5 or newer. When I revert to v1.0.4, it works perfectly.

int val;

void setup() {
  Serial.begin(115200);
}

void loop() {
  val = hallRead();
  Serial.print("Hall Sensor Reading: ");
  Serial.println(val);
  delay(200);
}

**Comment by lbernstone** [comment]
Fixed in https://github.com/espressif/arduino-esp32/pull/5268

**Comment by VojtechBartoska** [comment]
Closing due there is merged PR already.
