### ISSUE TITLE
Support for manually change smartconfig protocol (to new ESPTOUCH_V2)

### ISSUE THREAD

**Issue by abobija** [espressif/arduino-esp32#5409]
ArduinoESP32 currenty uses [hardcoded esptouch V1](https://github.com/espressif/arduino-esp32/blob/d5e8c9dddc59bc492f8a254febfb5fb49bf036d0/libraries/WiFi/src/WiFiSTA.cpp#L671) protocol for smartconfig, but there is a new improved [version V2](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_smartconfig.html#_CPPv418smartconfig_type_t) of esptouch protocol.

It would be great if we were able to manually set the protocol before using `Wifi.beginSmartConfig` method.

I think that would solve #5226 as well.

**Comment by Wang-Yumin** [comment]
Is there anyone to help with this problem? Thank you, boss.

**Comment by me-no-dev** [comment]
@P-R-O-C-H-Y want to have a go at updating the esp-touch implementation inside WiFi?

**Comment by Wang-Yumin** [comment]
@P-R-O-C-H-Y Great! Thank you so much!

**Comment by abobija** [comment]
Thanks @P-R-O-C-H-Y 👍🏼
