### ISSUE TITLE
Support for ESP32-S2 and ESP32-C3 chips on PlatformIO

### ISSUE THREAD

**Issue by ullix** [espressif/arduino-esp32#5410]
The two chips can be defined on PIO, but compilation only results in the message `Error: This board doesn't support arduino framework!`.

I see this announcement for S2 and C3 support https://github.com/espressif/arduino-esp32#esp32-s2-and-esp32-c3-support , but if I am not mistaken, this applies only to the Arduino IDE?

How can I use this on PlatformIO?

**Comment by me-no-dev** [comment]
Please ask this question in PlatformIO :)
