### ISSUE TITLE
[documentation] std::thread: failsafe when using delay(n) instead of std::this_thread::sleep_for(std::chrono::milliseconds(n)); ??

### ISSUE THREAD

**Issue by dsyleixa** [espressif/arduino-esp32#5412]
`std::thread`: 
is it failsafe when using e.g. delay(500) inside of threads 
instead of  std::this_thread::sleep_for(std::chrono::milliseconds(500));
(i.e., to have trustworthy non-blocking sleep() ) ?

**Comment by dsyleixa** [comment]
still not answered or solved

**Comment by me-no-dev** [comment]
Please ask such question on esp32.com forum. This is an issue tracker for Arduino, not a questionnaire :) Also std::thread comes from ESP-IDF and not Arduino, so folks there might have a better idea if vTaskDelay could be an issue
