### ISSUE TITLE
More Big Sur Flashing Issues

### ISSUE THREAD

**Issue by rhl-** [espressif/arduino-esp32#5413]
Hi, I am on Big Sur 11.4 I have a board with a `DOIT ESP32 DEVKIT V1` chip. 

I've install esp32 module v 1.0.6 via this location: https://dl.espressif.com/dl/package_esp32_index.json,http://arduino.esp8266.com/stable/package_esp8266com_index.json 

I've installed the latest Silab 2102x driver from here: https://www.silabs.com/documents/public/software/Mac_OSX_VCP_Driver.zip

This is my upload experience (while holding the button down on my device):

```
/Users/rhl/Library/Arduino15/packages/esp32/tools/esptool_py/3.0.0/esptool --chip esp32 --port /dev/cu.SLAB_USBtoUART --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0xe000 /Users/rhl/Library/Arduino15/packages/esp32/hardware/esp32/1.0.6/tools/partitions/boot_app0.bin 0x1000 /Users/rhl/Library/Arduino15/packages/esp32/hardware/esp32/1.0.6/tools/sdk/bin/bootloader_dio_80m.bin 0x10000 /var/folders/_f/ysbftd0x5nzgm5sxpf6kz4xw0000gn/T/arduino_build_515485/WiFiScan.ino.bin 0x8000 /var/folders/_f/ysbftd0x5nzgm5sxpf6kz4xw0000gn/T/arduino_build_515485/WiFiScan.ino.partitions.bin 
Serial port /dev/cu.SLAB_USBtoUART

Connecting........_____....._____....._____....._____....._____....._____.....____An error occurred while uploading the sketch
_

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

```

Aside from reinstalling all of this software for the 1000x time, or bashing head against the wall, is there anything I can do to debug this further?

Also odd, the device presents two USB devices on osx, the one above and:

`/dev/cu.usbserial-0202C751`

_Originally posted by @rhl- in https://github.com/espressif/arduino-esp32/issues/4408#issuecomment-881974278_

**Comment by me-no-dev** [comment]
Your installation is fine, the error is that you can not communicate well with the device. Since Big Sur, I am using the `/dev/cu.usbserial-x` ports for upload and communication. Make sure your cable is OK and you can also manually enter download mode by resetting while holding GPIO0 LOW
