### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by marshalcn** [espressif/arduino-esp32#5416]
exit status 1
为开发板 ESP32C3 Dev Module 编译时出错。

i got the error while compile the ESP32 BLE_scan sample from esp32 samples 

### Hardware:
Board:							?ESP32 c3 Dev Module?
Core Installation version:			?2.0.0-alpha1?
IDE name:						?Arduino IDE?
Flash Frequency:					?40Mhz?
Upload Speed:					?115200?
Computer OS:                                        ?Windows 10?

### Description:
Describe your problem here

### Debug Messages:
```
exit status 1
为开发板 ESP32C3 Dev Module 编译时出错。
```

**Comment by VojtechBartoska** [comment]
Hello @marshalcn, I'm closing this one as Expired with more info needed. If you need, please reopen the issue and provide more information. Thank you.
