### ISSUE TITLE
Re: SimpleWiFiServer example; here: submit button click states for HIGH and LOW to different website instances

### ISSUE THREAD

**Issue by dsyleixa** [espressif/arduino-esp32#5428]
as to wifiserver example: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/SimpleWiFiServer/SimpleWiFiServer.ino

after having a "buttonlink" mouse-clicked for LED HIGH or LOW, 
```
  client.print("Click <a href=\"/H\">here</a> to turn the LED on pin 5 on.<br>");
  client.print("Click <a href=\"/L\">here</a> to turn the LED on pin 5 off.<br>");
```
either a /H or a /L is added to the url, e.g.
http://mysite.net/
becomes 
http://mysite.net/H
which then remains unchanged until a new mouse click will happen, 
(or http://mysite.net/L for LOW respectively).

Given I  enabled autorefresh (10s), 
```
  client.println( "<meta http-equiv=\"refresh\" content=\"10\" > " );
```
and then opened the website on 2 different devices (PC, smartphone):
how can I submit a new mousclick (e.g., to HIGH) on the 1st device to the website on the 2nd device (to change the former LOW over there also to HIGH and vice versa?
Otherwise either device will always send the local state, so the 1st website will always send 
http://mysite.net/H for HIGH,  
whilst the 2nd device still would repeatedly  send http://mysite.net/L for LOW,  
 and the 1st one then back to HIGH and so on, so it always will toggle to infinity.

(not sure If could describe and express the problem correctly, and it's admittedly not an issue but a request for help, tbh)

**Comment by dsyleixa** [comment]
still not answered or even solved

**Comment by me-no-dev** [comment]
i do not see how this is in any way connected to Arduino. The basic example is not meant to do what you want it to do. Surely you can look into HTML and JavaScript and try to figure out how to do it. Refreshing the same URL is not the answer
