### ISSUE TITLE
Board list request: LOLIN D32 Pro

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [espressif/arduino-esp32#5431]
Per [Espressif board docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/boards/boards.html#third-party) page:

>All the information must be provided by the vendor. If your favorite board is not here, consider creating an issue on GitHub and directly link/mention the vendor in the issue description.

Board: [LOLIN D32 Pro](https://www.wemos.cc/en/latest/d32/d32_pro.html)
Vendor: @wemos (company now branded as LOLIN)

**Comment by VojtechBartoska** [comment]
@pedrominatel we can provide link to Wemos D32 docs.

**Comment by pedrominatel** [comment]
Hi @wemos. Can you add details about the boards in the official documentation?

We can add links but we need to guarantee that all information provided is the latest and the vendor has agreed with it.

**Comment by wemos** [comment]
@pedrominatel 
LOLIN D32 Pro
https://www.wemos.cc/en/latest/d32/d32_pro.html

**Comment by wemos** [comment]
LOLIN D32
https://www.wemos.cc/en/latest/d32/d32.html

**Comment by pedrominatel** [comment]
@VojtechBartoska and @wemos PTAL at the linked PR.
