### ISSUE TITLE
Update IDF to v2.1

### ISSUE THREAD

**Issue by copercini** [espressif/arduino-esp32#546]
Since [IDF v2.1 was released](https://github.com/espressif/esp-idf/releases), please update it on Arduino Core

**Comment by lonerzzz** [comment]
@me-no-dev Can you comment on why this is closed without comment?

**Comment by me-no-dev** [comment]
because I updated Arduino to the latest version

**Comment by lonerzzz** [comment]
Comment appreciated. Thanks.
