### ISSUE TITLE
How to override sdkconfig #defines ?

### ISSUE THREAD

**Issue by fmuntean** [espressif/arduino-esp32#5461]
I am using Platform.io
How can I overwrite #defines that are defined under the sdkconfig file? the generated sdkconfig.h does not contains failsafe #ifndef
to allow to overwrite it at the compile time using -D 
Please advise.

**Comment by Jason2866** [comment]
You can not change settings from sdkconfig.h. This settings are "burned in" when compiling the ardunio libs is done. The sdkconfig.h file is for reference which options are set. If you want to change you have to build your own libs. This can be done with https://github.com/espressif/esp32-arduino-lib-builder
You can do the changes you want in the sdkconfig files and the libs are builded with this options.

**Comment by fmuntean** [comment]
Thank you for the explanation.
