### ISSUE TITLE
WebServer Arduino Board Library 1.0.6 do not function anymore: 1.0.4 was OK.

### ISSUE THREAD

**Issue by rocrail** [espressif/arduino-esp32#5464]
The function 
`virtual WebClient client()`
always returns NULL after a client did connect.
So the WebServer is no longer compatible with 1.0.4.
Please fix this.

Used Browser: macOS Safari.
After downgrading to 1.0.4 it works again.

**Comment by VojtechBartoska** [comment]
@rocrail Hi, can you please try this with latest 2.0.0 rc1?

**Comment by rocrail** [comment]
Sorry, no cure.

**Comment by rocrail** [comment]
Please fix this incompatibility issue.
2.0.0 rc1 does not fix it.
For the CAM I have to stick with 1.0.4, but my application must switch from SPIFFS to LittleFS which is not available in 1.0.4...

**Comment by me-no-dev** [comment]
what is that WebServer and WebClient library? Could you provide any code that can help replicate the issue?

**Comment by VojtechBartoska** [comment]
Closing as Expired, if needed, please open new issue @rocrail. Thanks.
