### ISSUE TITLE
board manager link for esp32 c3 is not accessible

### ISSUE THREAD

**Issue by aileenfun** [espressif/arduino-esp32#5468]
The board manager link https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
is not accessible now. Does it move to somewhere else?
I also tried https://www.isitdownrightnow.com/ to double check.

**Comment by chegewara** [comment]
I can open it.

**Comment by VojtechBartoska** [comment]
@aileenfun Works for me as well. Did you try it again?
