### ISSUE TITLE
ESP32-S2 Example for USB HID

### ISSUE THREAD

**Issue by carlosarmentac** [espressif/arduino-esp32#5469]
Please provide an ESP32-S2 USB HID Keyboard example as the way you provided the USBSerial.

Thank you so much.

**Comment by lbernstone** [comment]
https://github.com/chegewara/EspTinyUSB/tree/master/examples/hid

**Comment by carlosarmentac** [comment]
Hello @lbernstone , the library and example that you mentioned is not compatible with Arduino-esp32 2.0.0-rc1.

**Comment by me-no-dev** [comment]
it's coming soon :)

**Comment by huangganggui** [comment]
> Hello @lbernstone , the library and example that you mentioned is not compatible with Arduino-esp32 2.0.0-rc1.

Hi @carlosarmentac . Did you try this example (https://github.com/chegewara/EspTinyUSB/blob/dcbb68d0f922d01b338b5cf6f2e5cdac6659a6c9/examples/hid/keyboard/keyboard.ino)?  Did it work well? I want to make a keyboard with ESP32-S2 and I want to Know it work well or not.

**Comment by carlosarmentac** [comment]
> > Hello @lbernstone , the library and example that you mentioned is not compatible with Arduino-esp32 2.0.0-rc1.
> 
> Hi @carlosarmentac . Did you try this example (https://github.com/chegewara/EspTinyUSB/blob/dcbb68d0f922d01b338b5cf6f2e5cdac6659a6c9/examples/hid/keyboard/keyboard.ino)? Did it work well? I want to make a keyboard with ESP32-S2 and I want to know it work well or not.

Hi @huangganggui it works but you need to make some changes in Arduino Core ESP32,. Please read the Know issues ( https://github.com/chegewara/EspTinyUSB ):

> Currently library is not working with vanila arduino-esp32. It is due some tinyusb callbacks cant be overriden and are used by arduino-esp32. To make it works it is required to add __attribute__ ((weak)) in 3 lines in local arduino file: https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-tinyusb.c#L266 https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-tinyusb.c#L275 https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-tinyusb.c#L284

**Comment by chegewara** [comment]
@carlosarmentac This is already fixed in master branch.
