### ISSUE TITLE
WPA2 Enterprise, EAP-TTLS support

### ISSUE THREAD

**Issue by hgshoggins** [espressif/arduino-esp32#5483]
Trying to have EAP-TTLS support on a NodeMCU-ESP32 for WiFi 802.1X authentication.
The board tries to authenticate itself with MSCHAPv2 method, but I need it to use TTLS for phase 2. 

It is suggested here (https://github.com/espressif/esp-idf/issues/7011#issuecomment-866485582) to use `esp_wifi_sta_wpa2_ent_set_ttls_phase2_method(ESP_EAP_TTLS_PHASE2_PAP);` but all I get is a dreaded error message when compiling: 
```
'ESP_EAP_TTLS_PHASE2_PAP' was not declared in this scope
```
Is there any documentation where I can find details on arguments that need to be passed to the `esp_wifi_sta_wpa2_ent_set_ttls_phase2_method()` method?

**Comment by VojtechBartoska** [comment]
Hello, 

as there was no answer in last 14 days, I'm **closing the issue as expired** to keep our backlog manageable. If it's still needed, please reopen the issue.

Thanks for understanding.
