### ISSUE TITLE
Touch INterrupt Problem on ARDUINO IDE

### ISSUE THREAD

**Issue by KaruF** [espressif/arduino-esp32#5493]
Hi,

I want to use touch interrupt feature on esp32. So ı opened example code from library: TouchInterrupt. 
When ı compile and upload to esp32 ı saw just that texts  on serial port screen ; 

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1240
load:0x40078000,len:13012
load:0x40080400,len:3648
entry 0x400805f8
ESP32 Touch Interrupt Test

I touched T0 and T3 pins but esp32 has never went into interrupt functions. I tried that code multiple computer but result was same. 

I use Arduino IDE 1.8.15 version with Nodemcu V1 ESP32 Devkit.

Note that touchRead function works very well. Only problem is about touch interrupt.

Code:

```
/*
This is an example how to use Touch Intrrerupts
The bigger the threshold, the more sensible is the touch
*/

int threshold = 40;
bool touch1detected = false;
bool touch2detected = false;

void gotTouch1(){
 touch1detected = true;
}

void gotTouch2(){
 touch2detected = true;
}

void setup() {
  Serial.begin(115200);
  delay(1000); // give me time to bring up serial monitor
  Serial.println("ESP32 Touch Interrupt Test");
  touchAttachInterrupt(T0, gotTouch1, threshold);
  touchAttachInterrupt(T3, gotTouch2, threshold);
}

void loop(){
  if(touch1detected){
    touch1detected = false;
    Serial.println("Touch 1 detected");
  }
  if(touch2detected){
    touch2detected = false;
    Serial.println("Touch 2 detected");
  }
}
```

**Comment by KaruF** [comment]
Anyone!!!

**Comment by me-no-dev** [comment]
you did not fill the issue template. There is missing information :) What version of the ESP32-Arduino are you using?

**Comment by KaruF** [comment]
@me-no-dev  I tried with 2 version of Arduino IDE. Arduino IDE 1.8.15 and Arduino IDE 1.8.5. Both of them doesn't work for me.
I installed latest version of esp32-arduino file from github.

**Comment by me-no-dev** [comment]
@KaruF I can confirm the issue. Was able to get around it by calling `touchRead(pin)` for each used pin in the loop. Will look into it
