### ISSUE TITLE
Does the Arduino-ESP32 C3 support BLE Mesh?

### ISSUE THREAD

**Issue by lybgo** [espressif/arduino-esp32#5495]
Are there any examples if supported?
If not, are you ready to support it in the future?

**Comment by me-no-dev** [comment]
if it's supported in ESP-IDF, then it is also supported here. Maybe ask there?

**Comment by me-no-dev** [comment]
then it is also supported here :) Do you have an example in ESP-IDF that you want to try in Arduino?

**Comment by chegewara** [comment]
> then it is also supported here :) Do you have an example in ESP-IDF that you want to try in Arduino?

Well, it is not that easy. BLE mesh is supported only when it is enabled in menuconfig explicitly.

**Comment by lybgo** [comment]
> then it is also supported here :) Do you have an example in ESP-IDF that you want to try in Arduino?

I don't know how to use the ESP-IDF API in Arduino, can you give an example?

**Comment by VojtechBartoska** [comment]
Hello, I'm closing this one as there is no traction. If needed, you can reopen it.
