### ISSUE TITLE
Test between 2.0.0-RC1 and 1.0.6 - Possible Issue with Interrupt Functions

### ISSUE THREAD

**Issue by ale-trevizoli** [espressif/arduino-esp32#5497]
Hi.
Two important things happen when migrate same code compiled with 1.0.6 to 2.0.0-RC1.
One is Memory. Memory will be lower with 2.0.0-RC1.
Second very important: I'm using an Wiegand Library adapted from Arduino to ESP32 (Yet another Wiegand Library from Paulo-Raca). I had to rewrite some functions using IRAM_ATTR because have interrupts firing while reading or writing on flash.
But it's not the big problem. 
The problem is that on 1.0.6 It can works with no problem, but on 2.0.0-RC1, I don't know if have some problem with trigger interrupts, but from 10 tries of read an RFID card on simple wiegand reader we have 9 with bit error reading and 1 that we receive complete number.
It's happens only if I'm reading and writing flash (FATFS) - maybe can happen with another intensive process but not checked - and version 2.0.0-RC1 is used. I have a process that send a lot of information to a TXT file write in FLASH using POST HTTP and interrupt can be triggered in this moment. But on 1.0.6 same behavior not happens.

I can't put code here, because it's very big and complex, but I review a lot of times to check for bugs, and can't found.
The most important is: it's happen only in 2.0.0-RC1.
I'd like to know what changed in this version, that can produce this issue. I'm guessing is something with Interrupts routines and Flash routines.

Thanks to all the developers who are responsible for the framework, for their dedication and for making the open source world even better so that other developers can create new products.
Sorry for my poor english. I'm Brazilian.

**Comment by Jason2866** [comment]
No offense. How should a issue be found without code that demonstrate the problem or
a exact description what changes are made that are problematic.

**Comment by SuGlider** [comment]
Please check #5474 regarding heap free memory.
We need more detailed information about the issue.

Please fill the issue template.
