### ISSUE TITLE
Missing Serial.write(const char*) in HardwareSerial.h?

### ISSUE THREAD

**Issue by minyk** [espressif/arduino-esp32#55]
Hi,

[Freematics](http://freematics.com)'s [ArduinoOBD](https://github.com/stanleyhuangyc/ArduinoOBD) library uses `Serial.write(const char*)`, but with Arduino-ESP32, it dose not complie with below error: 
```
/Users/minyk/Documents/Arduino/libraries/OBDI2C/src/OBD.cpp: In member function 'virtual void COBD::write(const char*)':
/Users/minyk/Documents/Arduino/libraries/OBDI2C/src/OBD.cpp:112:17: error: call of overloaded 'write(const char*&)' is ambiguous
  OBDUART.write(s);
```

So I dug the original Arduino Core code up, then found this line from `HardwareSerial.h`:
```cpp
    using Print::write; // pull in write(str) and write(buf, size) from Print
```

Arduino-ESP32's `HardwareSerial.h` does not have that part of code. Is this on purpose?

Thank you.

**Comment by me-no-dev** [comment]
To be honest I did not know that Serial.write(const char *) existed :) Will add it it's trivial
```cpp
size_t HardwareSerial::write(const char * str){
  return write(str, strlen(str));
}
```
