### ISSUE TITLE
abort() was called at PC 0x40191a13 on core 1

### ISSUE THREAD

**Issue by Connect-and-Exchange** [espressif/arduino-esp32#5501]
During normal runtime their was a abort() which i could not trace to any of the code we made.  there are ?? ??:0 parts in the backtrace whereas i have no idea what they mean. When checking the ESP documentation then it highlights it is a heap releated problem. 

Can someone take a look at the trace and let me know what can be done to find the actual cause? 

abort() was called at PC 0x40191a13 on core 1

ELF file SHA256: 0000000000000000

Backtrace: 0x40093eb8:0x3ffeb3d0 0x40094131:0x3ffeb3f0 0x40191a13:0x3ffeb410 0x40191a5a:0x3ffeb430 0x40191133:0x3ffeb450 0x4019146a:0x3ffeb470 0x401911d1:0x3ffeb490 0x40109e62:0x3ffeb4b0 0x40109ead:0x3ffeb4d0 0x400f8740:0x3ffeb4f0 0x400f8768:0x3ffeb510 0x4010a5a1:0x3ffeb530 0x400e0269:0x3ffeb550 0x400f7f62:0x3ffeb580 0x400f7fed:0x3ffeb5d0 0x400f352a:0x3ffeb5f0 0x400f35ad:0x3ffeb630 0x400f3c32:0x3ffeb650 0x40095136:0x3ffeb680

Rebooting...

   Error
   : ?? ??:0
   : ?? ??:0
   : ?? ??:0
   : ?? ??:0
   0x40093eb8 reconfigureAllWdts
   0x40094131 commonErrorHandler_dump
   : ?? ??:0
   0x40191133 qsort
   0x4019146a ethernet_low_level_init
   0x401911d1 qsort
   :?:::0x40109e62:ieee80211_set_max_rate
   :?:::0x40109ead:ieee80211_set_max_rate
   0x400f8740 AsyncAbstractResponse
   0x400f8768 AsyncAbstractResponse
   :?:::0x4010a5a1:ieee80211_parse_wpa
   0x400e0269 ArduinoJson6183_91
   (inlined by) ArduinoJson6183_91
   0x400f7f62 std
   0x400f7fed AsyncAbstractResponse
   0x400f352a checkDigestAuthentication(char const*, char const*, char const*, char const*, char const*, bool, char const*, char const*, char const*)
   0x400f35ad checkDigestAuthentication(char const*, char const*, char const*, char const*, char const*, bool, char const*, char const*, char const*)
   0x400f3c32 AsyncStaticWebHandler
   0x40095136 xQueueTakeMutexRecursive

**Comment by Connect-and-Exchange** [comment]
I’m using visual micro in visual studio to compile the binaries. When a crash occurs the serial monitor allows for the crash dump data to be decoded. 

Once done I can click through the output and it takes me to the line of code where the event occurred.

**Comment by VojtechBartoska** [comment]
Hello @Connect-and-Exchange, sorry for answering late. Is this issue still valid?

If yes, are you able to test this on v2.0.3-RC1?

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable.

If it's still needed, please reopen the issue.

Thanks for understanding.
