### ISSUE TITLE
PlatformIO builder script and platform.txt not in sync

### ISSUE THREAD

**Issue by maxgerhardt** [espressif/arduino-esp32#5505]
### Hardware:
Board:							ESP32C3 and ESP32C2
Core Installation version:			 latest git  5bb8177aa1feec665938be97607b526a4f0ec0bb
IDE name:						Platform.io
Flash Frequency:					40Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Windows 10

### Description:

The Arduino-IDE compiles with settings from the `platform.txt`, for the ESP32S2

https://github.com/espressif/arduino-esp32/blob/5bb8177aa1feec665938be97607b526a4f0ec0bb/platform.txt#L48

and ESP32C3

https://github.com/espressif/arduino-esp32/blob/5bb8177aa1feec665938be97607b526a4f0ec0bb/platform.txt#L63

and ESP32

https://github.com/espressif/arduino-esp32/blob/5bb8177aa1feec665938be97607b526a4f0ec0bb/platform.txt#L33

These flags are not enabled equivalently in the PlatformIO builder scripts

https://github.com/espressif/arduino-esp32/blob/5bb8177aa1feec665938be97607b526a4f0ec0bb/tools/platformio-build-esp32s2.py#L278-L292

https://github.com/espressif/arduino-esp32/blob/5bb8177aa1feec665938be97607b526a4f0ec0bb/tools/platformio-build-esp32c3.py#L278-L292

https://github.com/espressif/arduino-esp32/blob/5bb8177aa1feec665938be97607b526a4f0ec0bb/tools/platformio-build-esp32.py#L292-L306

Compile settings between the Arduino IDE and PlatformIO should always be equalized to get the same experience.

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
None relevant
### Debug Messages:
None relevant

**Comment by me-no-dev** [comment]
you define those in the board config or your project config. Not something that should be predefined for PIO
