### ISSUE TITLE
uartAvailable() has race condition

### ISSUE THREAD

**Issue by rob-deutsch** [espressif/arduino-esp32#5512]
### Hardware:
Board: DOIT ESP32 DEVKIT v1
Core Installation version: 1_0_6
IDF Version: 3.3.5-1-g85c43024c
IDE name: VS Code with platform.io
Flash Frequency: 40MHz
PSRAM enabled: no
Upload Speed: 115200
Computer OS: macOS

### Description:
I am experiencing race conditions with `HardwareSerial.available()` and `HardwareSerial.read()`. The following single-threaded code is returning -1 from `HardwareSerial.read()`, which shouldn't be possible after checking that `HardwareSerial.available() > 0`.

This seems to be caused by the underlying HAL `uartAvailable()` function.

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
    Serial.begin(115200);
}

void loop() {
    if (Serial.available() > 0) {
        int b = Serial.read();
        if (b == -1) {
            Serial.println("error reading");
        }
    }
    doOtherStuff()
}
```

**Expected result:** Nothing output on serial console
**Actual result:** Eventually "error reading" output on serial console

### Possible cause

This issue seems to be caused by a race condition with the following line:

https://github.com/espressif/arduino-esp32/blob/5bb8177aa1feec665938be97607b526a4f0ec0bb/cores/esp32/esp32-hal-uart.c#L344

I think that `uartAvailable()` should turn off interrupts and call `UART_MUTEX_LOCK()` in order to avoid the race condition.

**Comment by SuGlider** [comment]
You should have filled the issue template fully. 
It is not clear what version of ESP32-Arduino you are running. 
Please provide more information.

**Comment by rob-deutsch** [comment]
Thank you @SuGlider, I have updated the top post.

My apologies I didn't use the template. The template didn't come up when I used Github's "reference in new issue" link.

**Comment by SuGlider** [comment]
Thanks for the extra information @rob-deutsch.

I could not reproduce such issue. I tested it using Core 1.0.6 and 2.0.0RC1.
Please run the sketch below to find out the Arduino Core and IDF version you are currently running, and then report the output back to us.

''' javascript
#include <Arduino.h>
#include "core_version.h"

void setup() {
    Serial.begin(115200);

    Serial.println("IDF Version:");
    Serial.println(ESP.getSdkVersion());

    Serial.println("Arduino Core Version:");
    Serial.println(ARDUINO_ESP32_RELEASE);
}

void loop() {
}
'''

**Comment by rob-deutsch** [comment]
Thank you SuGlider, I have added that information to the original post.

I've also given a better demonstratino Sketch, with an added call to a function called DoOtherStuff(). This is a race situation, so the error doesn't always occur.

**Comment by SuGlider** [comment]
@rob-deutsch, please notice that uxQueueMessagesWaiting() doesn't consume any data and reading the value of the Register status.rxfifo_cnt also doesn't consume any data from FIFO.

Maybe the racing condition issue is Application related and not Arduino Core related.

Anyway esp32-hal-uart.c has changed since version 1.0.6.
A newer version 2..0.0 is about to be relaeased.
At this point PlatformIO only supports 1.0.6.

**Comment by SuGlider** [comment]
Hi @rob-deutsch. thank you for your time on this issue. 

I tried to reproduce the issue several times and it always went well (in both 1.0.6 and 2.0.0)
Could you please provide sample code to effectively reproduce this problem?

**Comment by SuGlider** [comment]
Hi @rob-deutsch, thank you for pointing out this issue.

In fact, in case there is a task reading the  UART at the same time that another task  tries to get uartAvailable() on this same UART, a race condition may happen and the information returned could be outdated.

Currently the code of esp32-hal-uart.c is being refactored.
This issue will be solved in the core verion 2.

I'll post back here as soon as a correction is released.

**Comment by SuGlider** [comment]
esp32-hal-uart.c is being refactored. This issue will be solved in the process.
