### ISSUE TITLE
Could you add an example of BLE mesh to the Arduino

### ISSUE THREAD

**Issue by anshilike** [espressif/arduino-esp32#5539]
I strongly recommend adding BLE mesh, which is found in ESP-IDF, but it is troublesome to install this software. As a novice, I use arduino a lot, but there are no ble mesh examples in The Arduino. Could you please add BLE mesh to the Arduino?

**Comment by chegewara** [comment]
You cant use BLE mesh with arduino-ide:
https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/esp32/sdkconfig#L405

Maybe you can do it using nimBLE, but im not sure.

**Comment by lybgo** [comment]
need an example of  BLE mesh too

**Comment by arihantdaga** [comment]
Is it available now ? 
How can we use some code examples shown in esp idf in our arduino projects. 
I tried to include these files into my Arduino projects- 
```
#include "esp_ble_mesh_defs.h"
#include "esp_ble_mesh_common_api.h"

```
But it throws error saying cant find these libraries

**Comment by arihantdaga** [comment]
It's relavant. We need to implement BLE Mesh example for Arduino.

**Comment by VojtechBartoska** [comment]
Adding this to Documentation Roadmap.

**Comment by mnour94** [comment]
Are there any updates on this? A BLE mesh implementation in Arduino would be greatly appreciated

**Comment by VojtechBartoska** [comment]
Can you take a look on this @lucasssvaz?

Current list of BLE examples is here: https://github.com/espressif/arduino-esp32/tree/master/libraries/BLE/examples

**Comment by lucasssvaz** [comment]
There's no BLE mesh library for now. A makeshift solution is required for the time being.

I modified some files to be able to properly compile and run the [ESP-IDF example](https://github.com/espressif/esp-idf/tree/82cceabc6e/examples/bluetooth/esp_ble_mesh/ble_mesh_node/onoff_server). Note that it requires to manually recompile the libraries to add support for specific BLE Mesh functions (this isn't trivial if you haven't done it before).

https://gist.github.com/lucasssvaz/bd105988aaf72ec291ecf94ecc2c692d

**Comment by skyfly200** [comment]
Thanks for your help on this @lucasssvaz!
I too am looking to use this functionality in Arduino

**Comment by VojtechBartoska** [comment]
Closing this as solved for now as @lucasssvaz provided workaround for IDF examples. For now, this is a first step, should be later on replaced by proper BLE Mesh library.

**Comment by verdiluca** [comment]
hi, @lucasssvaz @skyfly200 @VojtechBartoska  I'm trying to compile the project of @lucasssvaz, but I saw that you have to modify the libraries but I didn't understand how to do it, would you be able to explain it to me? Thank you

**Comment by lucasssvaz** [comment]
@verdiluca Check https://github.com/espressif/esp32-arduino-lib-builder. You can edit the Sdkconfig files to suit your needs.

**Comment by dtsitses** [comment]
Hi @lucasssvaz @skyfly200 @VojtechBartoska. I'm trying to compile the [project](https://gist.github.com/lucasssvaz/bd105988aaf72ec291ecf94ecc2c692d) of @lucasssvaz but I'm getting multiple compilation errors. Checking the recommended lib builder [here](https://github.com/espressif/esp32-arduino-lib-builder) does not help as it's unclear what configuration changes are required, and also how the recompiled lib is referenced from the ino project which seems to still want to use the standard one installed in Arduino IDE via the board manager.

Would it be possible to make a step-by-step guide so that we can get this to work? Many thanks!

**Comment by lucasssvaz** [comment]
@dtsitses Sorry about that, I've updated the links in the gist to use the 5.1 tag of IDF. You should be able to find the options needed now. Also, we just added an UI to the lib builder. Feel free to try that (although it is probably still harder than just using Arduino as a component and changing the IDF settings).
