### ISSUE TITLE
ESP32 Node MCU Is rebooting itself !  ERROR ets Jan  8 2013,rst cause:2, boot mode:(3,0)

### ISSUE THREAD

**Issue by DiptanshuMalviya** [espressif/arduino-esp32#5548]
Introduction: 
I am making project on the multiple Node Mcu esp32 connecting via Mac Address . There are two Node MCU i am using for communication :  first is Server_Robot and second is Client_Robot_  . When i Code the Robot creating the creating the error in the middle of the code it. Reset the program. 
I have also done with the Main . When i add the Server_Robot with Mega via SCL and SDA .It also creating another Issue which i will update later . But now this issue is causing me.

-------------------------------------------------------------------------------------------------------------
ERROR:

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffdb0 end: 3fffffc0 offset: 01a0
3fffff50:  402161a9 3ffef0dc 4023b510 402161b8  
3fffff60:  0000000b 00000001 0000000a 40100f24  
3fffff70:  00000004 3ffee640 00000000 4010028f  
3fffff80:  00000000 3ffee640 3ffee678 40201279  
3fffff90:  3fffdad0 00000000 3ffee6f0 3ffee704  
3fffffa0:  3fffdad0 00000000 3ffee6f0 402020b0  
3fffffb0:  feefeffe feefeffe 3ffe85f0 40100c05  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,0)

load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v000432a0

----------------------------- Remove above -----------------------------

### Hardware:
Board:							?ESP32  NODE MCU12-E
Core Installation version:			?1.0.0? ?1.0.1-rc4? ?1.0.1? ?1.0.1-git? ?1.0.2? ?1.0.3?
IDE name:						Arduino IDE
Flash Frequency:					40Mhz?
PSRAM enabled:                                     Default
Upload Speed:					115200?
Computer OS:                                        Windows 11

----------------------------------------------------------------------------------------
Describe your problem here

PROBLEM (1) : , I have Connected One Node Mcu to another Node Mcu via Mac Address.  . When done the programming it works perfectly but in the middle of running , node mcu stops. giving some decoder Eror something else. 

----------------------------------------------------------------------------------------------------------------
1 . Server_robot Coding

// MAKE THE MAC ADDRESS WITH THE MAC WIFI STA (STATION) ::::

//After Getting the MAC ADDRESS Put the in the Address:: 
// THIS IS THE SENDER MESSAGE:::::

#include <ESP8266WiFi.h>
#include <espnow.h>
#include <Wire.h>

int button=D3;
int first=1;
int led_light=D5;
// REPLACE WITH RECEIVER MAC Address
uint8_t broadcastAddress[] = {0xE8,0xDB,0x84,0x9B,0x01,0x79};//Server1

// Structure example to send data
// Must match the receiver structure
//THIS IS FOR THE TO CREATE VALUE AND SEND TO RECIEVER::

typedef struct ORDER
{
  int value;
//  int updated; //We have to make function for to update the nex command  for the ]
//  int second_turn;
  //For the memcpy function::::::::::::
}ORDER;

ORDER one;

typedef struct Order_two
{
  
  int updated; //We have to make function for to update the nex command  for the ]
  int second_turn;
  
  }Order_two;

Order_two two;

// Callback when data is sent
//THIS IS ONLY FOR THE CHECKING THE Sender_Working
// esp_now_register_send_cb(OnDataSent_Sender_Working);
//||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
//VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
void OnDataSent_Sender_Working(uint8_t *mac_addr, uint8_t sendStatus) {
  Serial.print("Last Packet Send Status: ");
  if (sendStatus == 0){
    Serial.println("Delivery success Sender_Working");
  }
  else{
    Serial.println("Delivery fail Sender_Working");
  }
}

//THIS IS FUNCTION CALLED WHEN RECIVE BY THE RECIVER BOARD
void Updated_value(uint8_t * mac, uint8_t *incomingData, uint8_t len)
  {
    
    memcpy(&two, incomingData, sizeof(two));
//    memcpy(&Client_sendbtn, incomingData, sizeof(Client_sendbtn));
    Serial.println("UPDATING PROCESS");
    int updated_value=two.updated;
    int second_turn_value=two.second_turn;
    Serial.print("updated_value :");
    Serial.print(updated_value);
    
 if(updated_value==2)
  {
    Serial.print("THE SECOND CAR STARTED");
//     Wire.beginTransmission(8); /* begin with device address 8 */
//     Wire.write(4);  /* sends hello string */
//    Wire.endTransmission();    /* stop transmitting */
  }
 if(second_turn_value==2)
  {
// Wire.beginTransmission(8); /* begin with device address 8 */
// Wire.write(2);  /* sends hello string */
// Wire.endTransmission();    /* stop transmitting */
  }
  
  }

void setup() {
  // Init Serial Monitor
  Serial.begin(115200);
  pinMode(button,INPUT);
  pinMode(led_light,OUTPUT);
  digitalWrite(led_light,LOW);
//  Wire.begin(D1, D2);
 
  // Set device as a Wi-Fi Station
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  // Init ESP-NOW
  if (esp_now_init() != 0) {
    Serial.println("Error initializing ESP-NOW Sender_Working ");
    return;
  }
  esp_now_set_self_role(ESP_NOW_ROLE_COMBO);
  esp_now_register_send_cb(OnDataSent_Sender_Working);
  esp_now_add_peer(broadcastAddress, ESP_NOW_ROLE_COMBO, 1, NULL, 0);
 
  // Register for a callback function that will be called when data is received
   esp_now_register_recv_cb(Updated_value);
 

}
 
void loop() {
int new_button=digitalRead(button);
if(new_button==0){  
if(first==1){ 
  one.value=1;
  Serial.print("UPDATED VALUE :1 is send Server Address");
  esp_now_send(broadcastAddress, (uint8_t *) &one, sizeof(one));
 while(1)
 {
// Wire.beginTransmission(8); /* begin with device address 8 */
// Wire.write(1);  /* sends hello string */
// Wire.endTransmission();    /* stop transmitting */ //THIS IS THE LIGHT OF GREEENNNN
  //THIS one.updated is by the ROBOTS:::
  if(two.updated==2)
    {     
      while(1)//THIS LOOP IS FOR THE SECOND ROBOT
      {

        if(two.second_turn==2)
        {
          
          while(1)
          {
            Serial.print("RUNNNNNN");
            digitalWrite(led_light,HIGH);
            }
          }
//         Wire.beginTransmission(8); /* begin with device address 8 */
//         Wire.write(3);  /* sends hello string */
//         Wire.endTransmission();
//         
         /* stop transmitting *///THIS will light the MEGA of LED INBUILT Both Yellow and Green
//        esp_now_send(Client_1, (uint8_t *) &one, sizeof(one)); 
     //This is one for the Client:::::
     // -------->>>      
      }
     }
  }
}
first=first+1;
}
Serial.print("BUTTON VALUE: 1 is out of the Loop:");
Serial.println(new_button);
}

-------------------------------------------------------------------------------------------------------------------------------

2. Client Robot Coding 

//PROGRAMING FOR THE ROBOT 1 take the ORDERS FROM MAIN
//IT Will be the Value 1 :::::

#include <ESP8266WiFi.h>
#include <espnow.h>

uint8_t  Main_Address[] = {0xE8,0xDB,0x84,0x9B,0x5A,0x57};

int Sensor_1=13;
int Sensor=12;
int Led_1=9;
int Led_2=10;

typedef struct ORDER
{
  int value;

  //For the memcpy function::::::::::::
}ORDER;

ORDER one;

typedef struct Order_two
{
  
  int updated; //We have to make function for to update the nex command  for the ]
  int second_turn;
}Order_two;

Order_two two;

//CHECKING OF THIS WIFI
//----------------------------------------------------------------------------
void this_mcu_testing_working(uint8_t *mac_addr, uint8_t sendStatus) 
{
  Serial.print("Last Packet Send Status: ");
  if (sendStatus == 0){
    Serial.println("Delivery success Sender_Working");
  }
  else{
    Serial.println("Delivery fail Sender_Working");
  }
}
//-----------------------------------------------------------------------------

//THIS IS THE FUNCTION FOR UPDATE VALUE OF THIS VALUE

//THIS IS TO FUNCTION WHERE ROBOT CHANGES::::
void Updated_value(uint8_t * mac, uint8_t *incomingData, uint8_t len)//THIS IS COME FROM THE RECIVER
{
  
  memcpy(&one, incomingData, sizeof(one));

 if(two.updated==2)
  {
    Serial.print("THE SECOND CAR STARTED");
  }
  
  
}
//--------------------------------------------

void setup() {
  // put your setup code here, to run once:

 Serial.begin(115200);
 pinMode(Led_1,OUTPUT);
 pinMode(Led_2,OUTPUT);
 pinMode(Sensor,INPUT);
 pinMode(Sensor_1,INPUT);
 digitalWrite(Led_1,LOW);
 digitalWrite(Led_2,LOW);
 WiFi.mode(WIFI_STA);
 WiFi.disconnect();
  if (esp_now_init() != 0) {
    Serial.println("Error initializing ESP-NOW Sender_Working ");
    return;
  }
esp_now_set_self_role(ESP_NOW_ROLE_COMBO);
//TO CHECK THE IS IT WORKING OR NOT::
esp_now_register_send_cb(this_mcu_testing_working);

esp_now_add_peer(Main_Address, ESP_NOW_ROLE_COMBO, 1, NULL, 0);

//THE UPDATED VALUE one.updated ,one.value==1
esp_now_register_recv_cb(Updated_value);

//REGISTER TO PEER TO MAIN::::: MAIN

}

void loop() 
{
//   digitalWrite(Led_1,LOW);
// digitalWrite(Led_2,LOW);
  Serial.print(" ENTER:::");
  Serial.print(one.value);
  Serial.print("ONE THE LOOP");
 if(one.value==1)
 {
  Serial.print(" ENTER:::");
  Serial.print(one.value);
  Serial.println("FIRST STEP BEGIN");
  int sensors=digitalRead(Sensor);
  Serial.println("FIRST SENSOR VALUE BUTTON: D2 ");
  Serial.print(sensors);
    while(sensors==1)//HERE THE AND COMES:: BOTH SNESOR FIND TO CHANGE THE DIRECTION
    {
     //motor RUN FUNCTION the high:: 
     Serial.print("THE FIRST INDICATION");
     digitalWrite(Led_1,HIGH);
     sensors=digitalRead(Sensor);
    }//SENSOR FUNCTIONs
  digitalWrite(Led_1,LOW);
//  sensors=digitalRead(Sensor);
  two.second_turn=2;//THIS message the light yellow in the mega
  esp_now_send(Main_Address, (uint8_t *) &one, sizeof(one)); 
  //HERE THIS NEW SIGNAL WHICH ROBOT WILL go to to bacl until the turn

  int sensors_1=digitalRead(Sensor_1);// SECOND TURN  TWO SENSOR AND CONDDITOPN
// TOP SENSOR AND LEFT SENSOR:::::::::::
  while(sensors_1==1)
  {
    digitalWrite(Led_2,HIGH);
   int sensors_1=digitalRead(Sensor_1);
   if(sensors_1==0)
   {while(1){Serial.println("SECOND SENSOR");}
    
    }
   }
  digitalWrite(Led_2,LOW);
  //if magnet sensor true:: 
  //while l
   one.value=2;
  }
  two.updated=2;
  esp_now_send(Main_Address, (uint8_t *) &two, sizeof(two)); 
  // put your main code here, to run repeatedly:

}

**Comment by atanisoft** [comment]
@DiptanshuMalviya You appear to be using an ESP8266 and not an ESP32 board. I'd suggest filling this issue against the [ESP8266](https://github.com/esp8266/Arduino) repository instead.
