### ISSUE TITLE
LittleFS not working with ESP32-S2

### ISSUE THREAD

**Issue by Jason2866** [espressif/arduino-esp32#5550]
What you are trying to do?
Use LittleFS with the ESP32-S2 (the same example does work with the ESP32-C3 and ESP32)
Using LittleFS with IDF4.4 does work with the ESP32-S2. Tested with https://github.com/wreyford/demo_esp_littlefs

Describe your system(ESP32-S2, Win10 latest, branch master).
Describe what is failing.
Error messages during initalizing LittleFS
Maybe SPI init is wrong?

Show the shortest possible code that will duplicate the error.
Example in lib folder `LittleFS` see bottom
Show the EXACT error message(it doesn't work is not enough).

```
ESP-ROM:esp32s2-rc4-20191025

Build:Oct 25 2019

rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)

SPIWP:0xee

mode:DOUT, clock div:1

load:0x3ffe6100,len:0x7c

load:0x4004c000,len:0x810

load:0x40050000,len:0x23e4

entry 0x4004c164

./components/esp_littlefs/src/littlefs/lfs.c:998:error: Corrupted dir pair at {0x0, 0x1}

E (93) esp_littlefs: mount failed,  (-84)

E (93) esp_littlefs: Failed to initialize LittleFS

[   561][E][esp32-hal-misc.c:125] disableCore0WDT(): Failed to remove Core 0 IDLE task from WDT

./components/esp_littlefs/src/littlefs/lfs.c:1685:debug: Bad block at 0x0

./components/esp_littlefs/src/littlefs/lfs.c:1691:warn: Superblock 0x0 has become unwritable

E (3980) esp_littlefs: Failed to format filesystem

[  4448][E][LittleFS.cpp:119] format(): Formatting LittleFS failed! Error: -1

[  4454][E][LittleFS.cpp:94] begin(): Mounting LittleFS failed! Error: -1

LittleFS Mount Failed
```

### Hardware:
Board:							ESP32-S2 Dev Module
Core Installation version:			git master
IDE name:						Platform.io
Flash Frequency:					80Mhz
PSRAM enabled:                                   no
Upload Speed:					115200
Computer OS:                                        Windows 10

### Description:
LittleFS does not initialize correctly and is not working
Sketch https://github.com/espressif/arduino-esp32/tree/master/libraries/LittleFS/examples/LITTLEFS_PlatformIO

Used `platformio.ini`:

```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32s2


[env]
framework               = arduino
monitor_speed           = 115200
upload_speed            = 115200
upload_port             = COM5
upload_resetmethod      = nodemcu

[env:esp32c3]
board                   = esp32-c3-devkitm-1
platform                = https://github.com/platformio/platform-espressif32.git#feature/arduino-idf-master
platform_packages       = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
                          platformio/tool-mklittlefs @ ~1.203.200522
build_unflags           = -Wswitch-unreachable
build_flags             = -Wno-switch-unreachable
monitor_filters         = esp32_exception_decoder
extra_scripts           = ./littlefsbuilder.py

[env:esp32s2]
board                   = esp32-s2-saola-1
upload_port             = COM5
platform                = https://github.com/platformio/platform-espressif32.git#feature/arduino-idf-master
platform_packages       = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
                          platformio/tool-mklittlefs @ ~1.203.200522
build_unflags           = -Wswitch-unreachable
build_flags             = -Wno-switch-unreachable
monitor_filters         = esp32_exception_decoder
extra_scripts           = ./littlefsbuilder.py

[env:esp32]
board                   = esp32dev
upload_port             = COM4
platform                = https://github.com/platformio/platform-espressif32.git#feature/arduino-idf-master
platform_packages       = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
                          platformio/tool-mklittlefs @ ~1.203.200522
build_unflags           = -Wswitch-unreachable
build_flags             = -Wno-switch-unreachable
monitor_filters         = esp32_exception_decoder
extra_scripts           = ./littlefsbuilder.py
```

**Comment by Jason2866** [comment]
@me-no-dev do you need more infos or logs?

**Comment by me-no-dev** [comment]
is this issue particular to platformio @Jason2866 ?

**Comment by Jason2866** [comment]
No, i tried the example https://github.com/espressif/arduino-esp32/blob/master/libraries/LittleFS/examples/LITTLEFS_test/LITTLEFS_test.ino with Arduino IDE. Same error.

**Comment by Dario-Ciceri** [comment]
> @me-no-dev No, i tried the example https://github.com/espressif/arduino-esp32/blob/master/libraries/LittleFS/examples/LITTLEFS_test/LITTLEFS_test.ino with Arduino IDE. Same error.

did you fix it? i have this problem too with SPIFFS: does not start with /

**Comment by lbernstone** [comment]
@Dario-Ciceri Please do not hijack issues.  Where do you see this error in the post?  If you have a problem with SPIFFS, open a new issue.

**Comment by Dario-Ciceri** [comment]
> 

I'm sorry, I didn't know about hijacking... btw I fixed it was a problem due to a missing "/", still getting problems since I get error 6 as it can't read the file. I'm trying to display gifs on led matrix

**Comment by oleksandr007** [comment]
I dont't really understand what was the solution to this issue? I have ESP32-S2 mini and im trying days to figure out how to make LittleFS work. The compiler say it's everything ok but ESP32 can't mount LittleFS.

**Comment by Jason2866** [comment]
The issue is solved since the bootloader uses the correct flash mode. Safe to use since core 2.0.6

**Comment by diegostf** [comment]
> The issue is solved since the bootloader uses the correct flash mode. Safe to use since core 2.0.6

Where can I find the settings/flash mode?
