### ISSUE TITLE
When ESP32 C3 is used as ADC, GPIO0 cannot output high level normally

### ISSUE THREAD

**Issue by Kaibin11** [espressif/arduino-esp32#5561]
When ESP32 C3 is used as ADC, GPIO0 cannot output high level normally

**Comment by VojtechBartoska** [comment]
Hello @Kaibin11, sorry for late reply. Are you able to test your issue on development version [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) to check if this is still valid? You can take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by VojtechBartoska** [comment]
Hello, due to no answer I'm closing this issue as expired.

If you still need help, please reopen it.

Thanks for understanding!
