### ISSUE TITLE
2.0.0-RC1 -  cam_hal: EV-EOF-OVF errors

### ISSUE THREAD

**Issue by lunadm** [espressif/arduino-esp32#5564]
* Development Board: ESP32-CAM
* Module or chip used: ESP32-S
* IDF version: Arduino  2.0.0-RC1
* Operating System: Mac
* Power Supply: [USB/battery]
* Chip is ESP32-D0WD (revision 1)

Testing  2.0.0-RC1  - im getting the following camera errors
E (3090) cam_hal: EV-EOF-OVF
E (3089) cam_hal: EV-EOF-OVF
E (21054) cam_hal: EV-VSYNC-OVF
E (50605) cam_hal: EV-EOF-OVF
…..
The errors are generated by changing the camera config quality setting, say to 6.

Apart from these error messages everything works correctly. 

int framesize = FRAMESIZE_HD;
static esp_err_t  config_camera(){
 config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM;
  config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000; 
  config.pixel_format = PIXFORMAT_JPEG;
  config.frame_size = FRAMESIZE_UXGA; 
  config.jpeg_quality = 6;  // 1 to 63 - smaller number is higher 
  config.fb_count = 7;

  sensor_t * ss = esp_camera_sensor_get();
  //enable both for landscape camera
  ss->set_vflip(ss, 0);          
  ss->set_hmirror(ss, 0);   

  ss->set_quality(ss, 6);
  ss->set_framesize(ss, (framesize_t)framesize);

  ss->set_brightness(ss, -1);
  ss->set_saturation(ss, -1);
  ss->set_sharpness(ss, 1);

  camera_fb_t * fb = esp_camera_fb_get();
  delay(800);
  for (int j = 0; j < 2; j++) {
    camera_fb_t * fb = esp_camera_fb_get();
    esp_camera_fb_return(fb);
    delay(50);
  }
  Serial.printf("\nCamera started correctly, Type is %x (hex) of 9650, 7725, 2640, 3660, 5640\n\n", ss->id.PID);
  return (1);
}

**Comment by me-no-dev** [comment]
how about you set `config.fb_count = 2;`
