### ISSUE TITLE
2.0.0-RC1 -Framesize_HD causes cam to crash

### ISSUE THREAD

**Issue by lunadm** [espressif/arduino-esp32#5565]
* Development Board: ESP32-CAM
* Module or chip used: ESP32-S
* IDF version: Arduino 2.0.0-RC1 
* Operating System: Mac
* Power Supply: [USB/battery]
* Chip is ESP32-D0WD (revision 1)

Testing  2.0.0-RC1 -
Selecting Framesize_HD causes it to crash and restart a number of times (it varies min is 4 restarts but I've had 8+)
 eventually it restarts normally with the error code
E (3062) cam_hal: EV-EOF-OVF
It then proceeds to run normally

If I change the framesize back to FRAMESIZE_SVGA - this behaviour doesn't occur

Error
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40130d94: f01d08b3 81004136 afa2819a
Core  1 register dump:
PC      : 0x40130d9a  PS      : 0x00060031  A0      : 0x80086fdc  A1      : 0x3ffbf140  
A2      : 0x3ffb30c8  A3      : 0x00000000  A4      : 0x3ffbf178  A5      : 0x3ff42000  
A6      : 0x00000003  A7      : 0xe0000020  A8      : 0x80086f03  A9      : 0x3ffbf110  
A10     : 0x3ffbf14c  A11     : 0x3ffbf14c  A12     : 0x3ffbf178  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x3ffb38d8  SAR     : 0x00000018  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x4008bf4c  LEND    : 0x4008bf68  LCOUNT  : 0x00000000  

Backtrace:0x40130d97:0x3ffbf1400x40086fd9:0x3ffbf170 0x40086a09:0x3ffbf1a0 0x4008bf4d:0x3ffb2390 0x40097e15:0x3ffb23a0 0x40082269:0x3ffb2420 0x400e436a:0x3ffb2460 0x40124433:0x3ffb2490 0x40128412:0x3ffb24c0 0x40125c5d:0x3ffb24f0 0x40127629:0x3ffb2540 0x401250e9:0x3ffb2580 0x40123c68:0x3ffb25b0 0x400ea751:0x3ffb2610 0x401712b1:0x3ffb2630 0x400e0506:0x3ffb2650 0x400dfba3:0x3ffb26b0 0x400d2e81:0x3ffb26e0 0x400d38e7:0x3ffb2720 0x400d4080:0x3ffb2790 0x400e2ddf:0x3ffb2820 
ELF file SHA256: 0000000000000000

…..

int framesize = FRAMESIZE_HD;

static esp_err_t  config_camera(){
 config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM;
  config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000; 
  config.pixel_format = PIXFORMAT_JPEG;
  config.frame_size = FRAMESIZE_UXGA; 
  config.jpeg_quality = 6;  // 1 to 63 - smaller number is higher 
  config.fb_count = 7;

  sensor_t * ss = esp_camera_sensor_get();
  //enable both for landscape camera
  ss->set_vflip(ss, 0);          
  ss->set_hmirror(ss, 0);   
  ss->set_quality(ss, 6);
  ss->set_framesize(ss, (framesize_t)framesize);
  ss->set_brightness(ss, -1);
  ss->set_saturation(ss, -1);
  ss->set_sharpness(ss, 1);

  camera_fb_t * fb = esp_camera_fb_get();
  delay(800);
  for (int j = 0; j < 2; j++) {
    camera_fb_t * fb = esp_camera_fb_get();
    esp_camera_fb_return(fb);
    delay(50);
  }
  Serial.printf("\nCamera started correctly, Type is %x (hex) of 9650, 7725, 2640, 3660, 5640\n\n", ss->id.PID);
  return (1);
}

**Comment by me-no-dev** [comment]
no need to open two issues. add the missing info to the other one and provide a decoded backlog
