### ISSUE TITLE
spiffs 3MB upload failed

### ISSUE THREAD

**Issue by minhhieuec** [espressif/arduino-esp32#5588]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.6
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                     no
Upload Speed:				        921600
Computer OS:                                         Windows 10

### Description:

```
- Select flash size 4MB
- Select partition scheme: No OTA (1MB APP/3MB SPIFFS)
```

1. i'm using appendFile function in SPIFFS_Test.ino file to test spiffs of esp32. But maximum size of characters i can write to the file is 2240640 bytes (not match with 3MB SPIFFS define in partition file).

2. cannot upload the text file over 2,235,904 bytes when using [**Esp8266 Sketch data upload**](https://github.com/me-no-dev/arduino-esp32fs-plugin)
```
[SPIFFS] data   : F:\GITHUB\esp32-bluetooth-serial\data
[SPIFFS] start  : 1114112
[SPIFFS] size   : 3008
[SPIFFS] page   : 256
[SPIFFS] block  : 4096
/dat1.txt
SPIFFS_write error(-10001): File system is full.

error adding file!

SPIFFS Create Failed!
```

**Comment by minhhieuec** [comment]
[dat1.txt](https://github.com/espressif/arduino-esp32/files/7038899/dat1.txt)

**Comment by VojtechBartoska** [comment]
Hello @minhhieuec , sorry for late reply. Are you able to test your issue on development version [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) to check if this is still valid? You can take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in last 14 days, I'm closing the issue as expired to keep our backlog manageable. If it's still needed, please reopen the issue.

Thanks for understanding.
