### ISSUE TITLE
ESP32-S3 Support

### ISSUE THREAD

**Issue by VojtechBartoska** [espressif/arduino-esp32#5594]
Adding support for ESP32-S3 chipset.

_Please specify what's needed and tag issues which will be solved by this._

**Update:**
- development branch [esp32-s3-support](https://github.com/espressif/arduino-esp32/tree/esp32-s3-support) have been added
- you can give it a try
- it supports any Mass production versions of the chip, Beta versions are not supported

**Testing is tracking [here in Github Discussions](https://github.com/espressif/arduino-esp32/discussions/6197) if you want to help us, feel free to comment there :)**

**Comment by heipp** [comment]
A fatal error occurred: This chip is ESP32-83(beta3) not ESP32-S3(beta2). Wrong --chip argument?
This error occurred when I was make flash,why?

**Comment by me-no-dev** [comment]
@heipp there is no S3 support yet. You can not build for it.

**Comment by chegewara** [comment]
then hurry up, i just ordered few of those ;)

**Comment by ozkarah** [comment]
Hi, I appreciate your work. 
Are there any updates on this task? Or any planned finish date?

**Comment by MartinPatarinski** [comment]
The flash command works on the master branch.
By default the release 4.3 of EPS-IDF is downloaded and it does not support esp32s3 officially.
Below is the dependency described:
![image](https://user-images.githubusercontent.com/96256400/146530155-3ba6d2b5-cfa8-437d-b15e-1dab5b6f9198.png)

**Comment by gtjoseph** [comment]
Back to the original topic though...  arduino-esp32 still does NOT support the S3 even though esp-idf does.

**Comment by afredsa** [comment]
Hello,
Sorry Quick questions for clarification
The current release (2.0.1) says it is based on ESP-ID 4.4 (according to the release page).   Is the S3 supported as stated in the previous pic? (sorry, I am not sure what is trying to be said.

I have ESP32-S3 of "Chip is ESP32D0WDQ6 (revision 0)"
@chegewara  said only S0 chips will be supported.  Is this the S0 (or newer) chip required?  And will this chip also be removed from support when the Rev 1 chips are released?   (I assume it is as I am able to flash in ESP 4.4 cl and vscode but not Arudino or PIO yet).

Thank you for any help and patience with my perhaps noobish question.

**Comment by Miraculix200** [comment]
2.0.1 is "S3 ready", but it's not selectable yet. I installed it and looked at the folders, and there's S3 files inside. But it's not in the boards.txt yet. So you can't select the board in Arduino IDE.

**Comment by VojtechBartoska** [comment]
@Miraculix200 that folder is just initial preparation for S3 support.

**Comment by Mchaney3** [comment]
I am currently using idf 4.4 and master and both work well with the S3. Arduino support will be amazing for this board. S3-C1n8r2 is the perfect board for all my projects.

What can we do to assist porting funtionality?

**Comment by me-no-dev** [comment]
we are already doing it :) stay put, support is around the corner.

**Comment by bunalti** [comment]
I am thinking about using S3 in next project, I see there already is a dedicated branch for this. Can I compile and flash using  the software in esp32-s3-support branch ? When you plan to publish the support ? And lastly which chip versions should I get ?

**Comment by me-no-dev** [comment]
@bunalti 
1. Yes you can use that branch, but SPI and flashing from TinyUSB(USB-OTG) does not work currently. SPI is on the way, can't comment on the other. If you want to use the built-in USB, then do not select USB-OTG mode in the board menu.
2. We will publish as soon as SPI is done and some basic tests have confirmed that the hardware is mostly working (can not promise that will not be any bugs at the beginning)
3. You should get any MP version. Beta chips are not supported.

**Comment by gtjoseph** [comment]
Thanks for the update!

**Comment by ewpa** [comment]
Hello, any hints to get my 32 MB Flash ESP32-S3-WROOM-2 D3N32R8V working with this branch?  Uploading any simple sketch results in a boot loop:
```
entry 0x403b61c0
assert failed: do_core_init startup.c:298 (flash_ret == ESP_OK)

Backtrace:0x40376b3e:0x3fceb1800x4037bd65:0x3fceb1a0 0x40381825:0x3fceb1c0 0x4200b58a:0x3fceb2f0 0x40376659:0x3fceb320 0x403bae57:0x3fceb350 0x403bb0de:0x3fceb380 0x403b6215:0x3fceb4b0 0x40045c01:0x3fceb570  |<-CORRUPTED
Rebooting...
```

Whereas the IDF v4.4 boots (with DIO):
```
I (222) cpu_start: ESP-IDF:          v4.4-172-g730ca0ea43-dirty
I (229) heap_init: Initializing. RAM available for dynamic allocation:
I (236) heap_init: At 3FC94AF8 len 0004B508 (301 KiB): D/IRAM
I (242) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (249) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (255) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (262) spi_flash: detected chip: mxic
W (266) spi_flash: Detected flash size > 16 MB, but access beyond 16 MB is not supported for this flash model yet.
I (277) spi_flash: flash io: dio
W (281) spi_flash: Detected size(32768k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
```

**Comment by me-no-dev** [comment]
@ewpa what options have you selected in the board menu?

**Comment by me-no-dev** [comment]
@ericlangel same question

**Comment by codewitch-honey-crisis** [comment]
Hi folks. I'm not sure if this is the right place to ask this, but how do I actually use the development branch of the Arduino framework for the S3? What url do I reference in Arduino IDE, or better yet, what do I include in platformio.ini to get it in there. Failing that, is there another way to use this branch? Forgive my ignorance.

**Comment by ericlangel** [comment]
@me-no-dev 
![grafik](https://user-images.githubusercontent.com/40859702/154280894-dc6af7aa-5f4d-484a-a7d6-cdc55c2cb7f9.png)

**Comment by me-no-dev** [comment]
@ericlangel BTW with what you have selected, you can just directly use Serial and it will be routed to the hardware CDC+JTAG

**Comment by me-no-dev** [comment]
there should not be a hint, because on the S3 there are 2 USB peripherals. One is integrated in hardware CDC+JTAG and the other is a full on USB-OTG peripheral that can be device or host. In both cases, depending on which USB is active "CDC on Boot" will route it to "Serial" and the hardware serial port becomes "Serial0", so for regular UART, you should disable CDC on Boot

**Comment by ewpa** [comment]
> @ewpa what options have you selected in the board menu?

@me-no-dev please see below my options (hope image is okay).  I tried changing many options already.
![Screenshot from 2022-02-16](https://user-images.githubusercontent.com/34030942/154291098-cee7d7ed-b8fa-4cda-be96-df332d39872e.png)

**Comment by ericlangel** [comment]
@me-no-dev 
and what can i do with "hardware cdc + jtag"?

**Comment by ewpa** [comment]
Thanks @me-no-dev setting PSRAM to OPI was enough to stop the boot loop.

**Comment by surajdevs** [comment]
Follow this link to get working Arduino ESP32-S3 support 

[https://github.com/surajdevs/ESP32-S3-Support/blob/main/README.md]

**Comment by P-R-O-C-H-Y** [comment]
@surajdevs There is official branch called esp32-s3-support. You can get ESP32-S3 working with this branch easily.
No need to download from external links :)

**Comment by ericlangel** [comment]
@flybeyond use NimBLE 
just tested Version 1.3.7 on the S3 and its working without problems

**Comment by flybeyond** [comment]
> @flybeyond use NimBLE just tested Version 1.3.7 on the S3 and its working without problems

I tried NimBLE_Sever, this is output:

C:\Users\xxx\Documents\Arduino\libraries\NimBLE-Arduino\src\NimBLEDevice.cpp: In static member function 'static void NimBLEDevice::init(const string&)':
C:\Users\xxx\Documents\Arduino\libraries\NimBLE-Arduino\src\NimBLEDevice.cpp:763:16: error: 'struct esp_bt_controller_config_t' has no member named 'mode'
         bt_cfg.mode = ESP_BT_MODE_BLE;
                ^~~~
C:\Users\xxx\Documents\Arduino\libraries\NimBLE-Arduino\src\NimBLEDevice.cpp:764:16: error: 'struct esp_bt_controller_config_t' has no member named 'ble_max_conn'; did you mean 'ble_max_act'?
         bt_cfg.ble_max_conn = CONFIG_BT_NIMBLE_MAX_CONNECTIONS;
                ^~~~~~~~~~~~
                ble_max_act
exit status 1
Error compiling for board ESP32S3 Dev Module.

**Comment by ericlangel** [comment]
did you used the latest Nimble Version 1.3.7?

with an older version i had the same output

**Comment by flybeyond** [comment]
This is what I used. 
![image](https://user-images.githubusercontent.com/7434686/155288764-c97024d7-16e4-44db-836f-42d1a27123de.png)

**Comment by ericlangel** [comment]
i use the same,

but i had some trouble to update it. In the end i copied the release manually.
maybe you having a similar issue

**Comment by flybeyond** [comment]
@ericlangel  The issue was resolved by recent commit. Thanks a lot for your help.

**Comment by HYXianghua** [comment]
Esp-idf 4.4-ESP32 S3
In the function
uint32_t ledc_get_freq(ledc_mode_t speed_mode, ledc_timer_t timer_num)
The clock_Divider in the formula when the frequency is returned is 0 and is used as the denominator
Causes a direct restart when using this function
Prompt message "IntegerDivideByZero"

**Comment by HYXianghua** [comment]
Esp idf-4.4  ESP32S3 
When sampling with ADC Digi 
esp_err_t adc_digi_read_bytes(uint8_t *buf, uint32_t length_max, uint32_t *out_length, uint32_t timeout_ms); 
All the data read is zero, even when using the official example, and the all related functions return ESP_OK

**Comment by syedhayi** [comment]
Can anyone please mention the steps for getting started with esp32s3 in arduino with brief explanation?

**Comment by lbernstone** [comment]
The [instructions for installation](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) are the same for esp32-s3 as for the rest of the chips.  However, you cannot use the board manager for the s3 until 2.0.3 is released, so you would need to install with the git instructions.

**Comment by syedhayi** [comment]
@[lbernstone](https://github.com/lbernstone) 
Hello, Thank you for your reply. 
I tried with git instruction in Ubuntu but ESP32S3 board doesn't shown up. also couldn't find esp32s3 in board.txt file. Is there any other instruction on how to program esp32s3 using arduino IDE?

**Comment by P-R-O-C-H-Y** [comment]
> @[lbernstone](https://github.com/lbernstone)
> Hello, Thank you for your reply.
> I tried with git instruction in Ubuntu but ESP32S3 board doesn't shown up. also couldn't find esp32s3 in board.txt file. Is there any other instruction on how to program esp32s3 using arduino IDE?

Hi, did you use the s3-support branch when pulling Arduino-esp32 from GitHub?

**Comment by touchgadget** [comment]
@syedhayi 
One extra step to I use on Ubuntu Linux to get the ESP32S3 branch.

```
mkdir -p ${IDEDIR}/hardware/espressif
cd ${IDEDIR}/hardware/espressif
git clone https://github.com/espressif/arduino-esp32.git esp32
cd esp32
git checkout --track origin/esp32-s3-support    # <<<
cd tools
python3 get.py
cd ${IDEDIR}
```

**Comment by meltdown03** [comment]
That last commit to file `cores/esp32/esp32-hal-tinyusb.c` breaks builds for non-S3 and C3 boards because there is no `hal/usb_serial_jtag_ll.h` file for those boards. Need to add an `#if def` statement before including it maybe.

**Comment by khoih-prog** [comment]
I've tested the new [**ESP32 core 2.0.3-RC1**](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) using many libraries, and everything is working OK so far to replace the temporary `s3-support branch`. Thanks for so good jobs and it's now so much easier to install via Arduino Library Manager.

**Comment by me-no-dev** [comment]
> The name of the port in the Arduino IDE tools menu ESP32C3 Dev Module is wrong though, it should probably read ESP32S3 Dev Module for less confusion.

the integrated JTAG+CDC that is used for flashing has the same USB PID/VID. We do not have a way to distinguish the board that way, so it picks one of them.

Nothing has been changed to cause crashes to not show ;)

**Comment by tobozo** [comment]
@me-no-dev I'm testing this crash code:

```C++
void setup()
{
  Serial.begin(115200);
  Serial.setDebugOutput(true);

  char a[2] = {0,0};
  sprintf(a, "%s", millis() );
}
```

Serial console output loops on this, but produces no "Exception was unhandled" message or backtrace :

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x42028672
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x43c
load:0x403b6000,len:0xbd0
load:0x403ba000,len:0x29c8
entry 0x403b61d8
[    91][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled

```

openocd output:

```
Info : esp32s3.cpu0: Target halted, PC=0x42028686, debug_reason=00000000
Info : esp32s3.cpu1: Target halted, PC=0x40374400, debug_reason=00000001
```

**Comment by me-no-dev** [comment]
<img width="908" alt="Screenshot 2022-03-31 at 0 43 30" src="https://user-images.githubusercontent.com/12663778/160936041-87ff3cda-d45c-4fc1-a7bd-a46a51bb80a0.png">

**Comment by me-no-dev** [comment]
probably your issue is that you are attached to the USB port of the chip (integrated CDC+JTAG) and not through the UART0 port, where backtrace will be printed. I will check later to confirm

**Comment by tobozo** [comment]
That's odd though, as all `ESP_LOG*`, `log_*` and `Serial.print()` statements I've tried are showing up correctly.

Now I suspect this also happens on esp32-s2.

If there is no particular reason to the minimalism of ESP32-S3-Box profile in boards.txt, I will experiment and extend it with some of the ESP32S3-DEV menu options, then submit a PR.

**Comment by me-no-dev** [comment]
the reason is that it has all settings related to the board already. Your USB port is not UART0 but instead connected to the chip directly. If you want to try options, maybe switch to the ESP32S3 Dev Module and adjust there.

**Comment by tobozo** [comment]
I've tried very hard using every possible combination from the ESP32S3 Dev Module but never got to print the stack trace to the serial console.

The usb port number keeps on changing which makes the flash&monitor operation very challenging.

While testing all combinations I could observe that the ESP32-S3-Box bootloops on all partition schemes except the default 4MB, is that worth testing custom partition.csv in the sketch folder or does this require a custom booloader to actually work?

A also observed that SPI DMA won't send more than 32k data at once, which seems like a downgrade compared to the ESP32, is that limit particular to octal spi?

**Comment by me-no-dev** [comment]
> I also observed that SPI DMA won't send more than 32k data at once, which seems like a downgrade compared to the ESP32, is that limit particular to octal spi?

Arduino does not use DMA

> I've tried very hard using every possible combination from the ESP32S3 Dev Module but never got to print the stack trace to the serial console.

The board you are using has UART0 pins broken out on the back. I suggest you connect external USB-UART to them. Correct settings in the ESP32S3 Dev Module for S3-Box are: Flash-QIO-80m, PSRAM-OPI/Off, CDC on Boot (On means that Serial will be the USB port, else it's UART0)

> The usb port number keeps on changing which makes the flash&monitor operation very challenging.

That can be true if you select USB-OTG and TinyUSB with some examples.

**Comment by tobozo** [comment]
> Arduino does not use DMA

Those settings (using SPI_DMA_CH_AUTO) don't appear to produce problems, does it mean it has no effects? 

```
init(): spi::init host:2, sclk:7, miso:0, mosi:6, dma:3
```

https://www.youtube.com/watch?v=dOZSOzYs3QY

The 32kb transfer limit is still puzzling though.

**Comment by Grungel** [comment]
I have tried around alot and all seems well. Great work!

**Comment by VojtechBartoska** [comment]
Hello,

as we are on the way of releasing 2.0.3-stable, this ticket can be consider as solved.

It serves the purpose of collecting feedback for ESP32-S3 support and testing.

Thanks to everyone for help!

If you will face some issue regarding ESP32-S3 (for sure there will be some in the future 😆) please open a new ticket.

**Comment by Paryavi** [comment]
Thank you for moving towards S3 stable edition in Arduino core, when do you plan to make it stable?

Here are the issues I have encountered installing ESP32 2.0.4 in Arduino IDE using ESPS3 with 8 MB of PSRAM and 16 MB of flash memory;

**SHA-256 Issue:**
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x2a (SPI_FAST_FLASH_BOOT)
Saved PC:0x420b37da
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x39c
load:0x403c9700,len:0x9bc
load:0x403cc700,len:0x28dc
SHA-256 comparison failed:
Calculated: 9477899d59fa5164e630d8218cb3994031873358e9105b31f53911d2dfd36c72
Expected: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Attempting to boot anyway...
entry 0x403c98c0
[   261][D][esp32-hal-cpu.c:214] setCpuFrequencyMhz(): PLL: 480 / 6 = 80 Mhz, APB: 80000000 Hz
[   261][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled

**WiFi connection is really slow and I get this;**
[   333][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   389][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 2 - STA_START
Connecting to WiFi...[   549][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
.[  1168][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  1169][D][WiFiGeneric.cpp:991] _eventCallback(): STA IP: 192.168.0.100, MASK: 255.255.255.0, GW: 192.168.0.1

**Guru Panicked error**
Also, I get Guru Panicked error when reaching the line below sometimes;
camera_fb_t *fb = NULL;  //I solved this by lowering CPU speed to 80 MHz and using DIO

Guru Meditation Error: Core  0 panic'ed (LoadStoreError). Exception was unhandled.

Core  0 register dump:
PC      : 0x4003f9b0  PS      : 0x00060530  A0      : 0x8003d7a2  A1      : 0x3fce9960  
A2      : 0x400057a8  A3      : 0x3fcf41d0  A4      : 0x00000304  A5      : 0x0000000f  
A6      : 0x3c57fca1  A7      : 0x00000000  A8      : 0x8003f92c  A9      : 0x403d3b36  
A10     : 0x3d80292c  A11     : 0x3fcef944  A12     : 0x191d1e17  A13     : 0x0001e847  
A14     : 0x3fcf41c4  A15     : 0x00000002  SAR     : 0x00000000  EXCCAUSE: 0x00000003  
EXCVADDR: 0x403d3b36  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0xffffffff  

Backtrace:0x4003f9ad:0x3fce9960 |<-CORRUPTED

Thanks

**Comment by Gustavomurta** [comment]
> Thank you for moving towards S3 stable edition in Arduino core, when do you plan to make it stable?
> 
> Here are the issues I have encountered installing ESP32 2.0.4 in Arduino IDE using ESPS3 with 8 MB of PSRAM and 16 MB of flash memory;
> 
> **SHA-256 Issue:** ESP-ROM:esp32s3-20210327 Build:Mar 27 2021 rst:0xc (RTC_SW_CPU_RST),boot:0x2a (SPI_FAST_FLASH_BOOT) Saved PC:0x420b37da SPIWP:0xee mode:DIO, clock div:1 load:0x3fce3808,len:0x39c load:0x403c9700,len:0x9bc load:0x403cc700,len:0x28dc SHA-256 comparison failed: Calculated: 9477899d59fa5164e630d8218cb3994031873358e9105b31f53911d2dfd36c72 Expected: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff Attempting to boot anyway... entry 0x403c98c0 [ 261][D][esp32-hal-cpu.c:214] setCpuFrequencyMhz(): PLL: 480 / 6 = 80 Mhz, APB: 80000000 Hz [ 261][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
> 
> **WiFi connection is really slow and I get this;** [ 333][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 0 - WIFI_READY [ 389][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 2 - STA_START Connecting to WiFi...[ 549][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 4 - STA_CONNECTED .[ 1168][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 7 - STA_GOT_IP [ 1169][D][WiFiGeneric.cpp:991] _eventCallback(): STA IP: 192.168.0.100, MASK: 255.255.255.0, GW: 192.168.0.1
> 
> **Guru Panicked error** Also, I get Guru Panicked error when reaching the line below sometimes; camera_fb_t *fb = NULL; //I solved this by lowering CPU speed to 80 MHz and using DIO
> 
> Guru Meditation Error: Core 0 panic'ed (LoadStoreError). Exception was unhandled.
> 
> Core 0 register dump: PC : 0x4003f9b0 PS : 0x00060530 A0 : 0x8003d7a2 A1 : 0x3fce9960 A2 : 0x400057a8 A3 : 0x3fcf41d0 A4 : 0x00000304 A5 : 0x0000000f A6 : 0x3c57fca1 A7 : 0x00000000 A8 : 0x8003f92c A9 : 0x403d3b36 A10 : 0x3d80292c A11 : 0x3fcef944 A12 : 0x191d1e17 A13 : 0x0001e847 A14 : 0x3fcf41c4 A15 : 0x00000002 SAR : 0x00000000 EXCCAUSE: 0x00000003 EXCVADDR: 0x403d3b36 LBEG : 0x40056f5c LEND : 0x40056f72 LCOUNT : 0xffffffff
> 
> Backtrace:0x4003f9ad:0x3fce9960 |<-CORRUPTED
> 
> Thanks

Paryavi, I encountered a similar error, but I found the solution.

My Environment:
ESP32-S3 DevKitC-1  V1.0  N32R8V ( 32MB Flash and 8MB PSRAM) 
Arduino IDE V1.8.19      ESP32 V2.0.5

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021

Message error with Loop:

assert failed: do_core_init startup.c:298 (flash_ret == ESP_OK)
Backtrace:0x40377612:0x3fceb1800x4037a23d:0x3fceb1a0 0x4037f621:0x3fceb1c0 0x420072c2:0x3fceb2f0 0x40376f7d:0x3fceb320 0x403cd6ef:0x3fceb350 0x403cd9ae:0x3fceb380 0x403c992d:0x3fceb4b0 0x40045c01:0x3fceb570  |<-CORRUPTED

Solution:
Arduino Board Manager:   ESP32 S3 Dev Module
**Configure Flash mode = DIO 80 MHz or OIP 80 MHz**
QIO 80 MHz or QIO 120 MHz doesn't work on my board.

**Comment by lbernstone** [comment]
> > Thank you for moving towards S3 stable edition in Arduino core, when do you plan to make it stable?
> > Here are the issues I have encountered installing ESP32 2.0.4 in Arduino IDE using ESPS3 with 8 MB of PSRAM and 16 MB of flash memory;
> 
> ....
> 
> > **Guru Panicked error** Also, I get Guru Panicked error when reaching the line below sometimes; camera_fb_t *fb = NULL; //I solved this by lowering CPU speed to 80 MHz and using DIO
> > Guru Meditation Error: Core 0 panic'ed (LoadStoreError). Exception was unhandled.
> > Core 0 register dump: PC : 0x4003f9b0 PS : 0x00060530 A0 : 0x8003d7a2 A1 : 0x3fce9960 A2 : 0x400057a8 A3 : 0x3fcf41d0 A4 : 0x00000304 A5 : 0x0000000f A6 : 0x3c57fca1 A7 : 0x00000000 A8 : 0x8003f92c A9 : 0x403d3b36 A10 : 0x3d80292c A11 : 0x3fcef944 A12 : 0x191d1e17 A13 : 0x0001e847 A14 : 0x3fcf41c4 A15 : 0x00000002 SAR : 0x00000000 EXCCAUSE: 0x00000003 EXCVADDR: 0x403d3b36 LBEG : 0x40056f5c LEND : 0x40056f72 LCOUNT : 0xffffffff
> > Backtrace:0x4003f9ad:0x3fce9960 |<-CORRUPTED
> > Thanks
> 
> Paryavi, I encountered a similar error, but I found the solution.
> 
> My Environment: ESP32-S3 DevKitC-1 V1.0 N32R8V ( 32MB Flash and 8MB PSRAM) Arduino IDE V1.8.19 ESP32 V2.0.5
> 
> ESP-ROM:esp32s3-20210327 Build:Mar 27 2021
> 
> Message error with Loop:
> 
> assert failed: do_core_init startup.c:298 (flash_ret == ESP_OK) Backtrace:0x40377612:0x3fceb1800x4037a23d:0x3fceb1a0 0x4037f621:0x3fceb1c0 0x420072c2:0x3fceb2f0 0x40376f7d:0x3fceb320 0x403cd6ef:0x3fceb350 0x403cd9ae:0x3fceb380 0x403c992d:0x3fceb4b0 0x40045c01:0x3fceb570 |<-CORRUPTED
> 
> Solution: Arduino Board Manager: ESP32 S3 Dev Module **Configure Flash mode = DIO 80 MHz or OIP 80 MHz** QIO 80 MHz or QIO 120 MHz doesn't work on my board.

If you have an issue, please open a new issue.  This is a tracking thread for a feature that was added a year ago.
