### ISSUE TITLE
Add external library

### ISSUE THREAD

**Issue by roysG** [espressif/arduino-esp32#5596]
Hi,
I want to work with the library: "https://github.com/vshymanskyy/TinyGSM"

I tried to put this package in the esp32-arduino-lib-builder/arduino/components/arduino/libraries. 
But there is no any effected.

What do i miss?

**Comment by 1kc** [comment]
@roysG 
You could do something like this. For the [Adafruit_BusIO](https://github.com/adafruit/Adafruit_BusIO) library for example.

Clone it under your idf project's components.
Just add `CMakeLists.txt` 
```
idf_component_register(
    SRCS "Adafruit_I2CDevice.cpp" "Adafruit_BusIO_Register.cpp" "Adafruit_SPIDevice.cpp"
    INCLUDE_DIRS "."
    REQUIRES arduino
)
```

and `component.mk`
```
COMPONENT_ADD_INCLUDEDIRS = .
```

Running this [library example](https://github.com/adafruit/Adafruit_BusIO/blob/master/examples/i2c_address_detect/i2c_address_detect.ino)
```cpp
#include "Arduino.h"
#include "Adafruit_I2CDevice.h"

#include <Adafruit_I2CDevice.h>

Adafruit_I2CDevice i2c_dev = Adafruit_I2CDevice(0x10);

void setup() {
  while (!Serial) { delay(10); }
  Serial.begin(115200);
  Serial.println("I2C address detection test");

  if (!i2c_dev.begin()) {
    Serial.print("Did not find device at 0x");
    Serial.println(i2c_dev.address(), HEX);
    while (1);
  }
  Serial.print("Device found on address 0x");
  Serial.println(i2c_dev.address(), HEX);
}

void loop() {
  
}

extern "C" void app_main()
{
    initArduino();
    pinMode(4, OUTPUT);
    digitalWrite(4, HIGH);
    // Do your own thing
}
```

**Comment by roysG** [comment]
The most library i succeeded to add successfully with the "CMakeLists.txt",
But there is a specific library that i still get errors in build.

This library is: https://github.com/OPEnSLab-OSU/SSLClient

Maybe someone know what are required steps?
