### ISSUE TITLE
when update I2s for ESP-C3?

### ISSUE THREAD

**Issue by xpdrycry** [espressif/arduino-esp32#5597]
I2s for ESP-c3,can not use, how to solve this trouble？

**Comment by VojtechBartoska** [comment]
Hello @xpdrycry , sorry for late reply. I2S was implemented already. Are you able to test your issue on development version [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) to check if this is still valid? You can take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in last 14 days, I'm closing the issue as expired to keep our backlog manageable. If it's still needed, please reopen the issue.

Thanks for understanding.
