### ISSUE TITLE
Disable async, block async or call as sync request to http server

### ISSUE THREAD

**Issue by tsctrl** [espressif/arduino-esp32#5602]
### Hardware:
Board:							ESP32 Dev Module
IDE name:						IDF component?
Flash Frequency:				       40Mhz
PSRAM enabled:                                    no
Upload Speed:				      115200?
Computer OS:                                        Windows 10

### Description:
I have problem to make http sync call to webserver api:

background:
when i call arduino httpwebserver api one time on one uri path ex: path/toget
the path contains multiple call EEPROM.get multiple time from same function with different eeprom address as params and assigned to different variable
the result is inconsistent, variable for eeprom address 1 will sometime get eeprom value from address 2 and is random.
delay after the eeprom get function did not help
i not sure whats the reason, cant find the cause but i guess the web server running in different task causing the issue or the async with the slow eeprom read.

below is the get char eeprom function that called in the api path:
```
char* getEEPROM(int addr)
{
	static char out[152];
	char buf[150] = { 0 };
	EEPROM.get(addr, buf);
	snprintf(out, sizeof(out), "%s", buf);
	return out;
}
```

i have the same way on writing the eeprom but did not have any issue. only during read.

solution that might i think to try:
calling the api by disabling the async 
do some task blocking function for eeprom get
make the function synchronize function
rtos way of blocking async function call

espressif team, how to achieve the mentioned solution for me to try as above?

out of option to solve this issue. do anyone have the same problem as i am?
anyone can suggest solution for this issue?
shed me some light, do guess too what the problem and i can try for the suggestion on my end.

thanks!
TS

cc: @me-no-dev , @igrr

**Comment by VojtechBartoska** [comment]
Hello @tsctrl , sorry for late reply. Are you able to test your issue on development version [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) to check if this is still valid? You can take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in last 14 days, I'm closing the issue as expired to keep our backlog manageable. If it's still needed, please reopen the issue.

Thanks for understanding.
