### ISSUE TITLE
CaptivePortal.ino is not working in windows

### ISSUE THREAD

**Issue by williamesp2015** [espressif/arduino-esp32#5617]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			latest
IDE name:						Platform.io
Flash Frequency:					40Mhz?
Computer OS:                                        Windows 10

I was using Captive portal in Win 10 but after while it stop working. Some changes I made to adjust the latest Wifi changes like:

  WiFi.mode(WIFI_MODE_AP);
 WiFi.softAPConfig(ip, ip, nm);
 WiFi.softAP(APssid.c_str(), "", AP_CHANNEL, false, AP_MAX_CLIENTS);
 delay(500);
 Serial.println(F("OK"));
 Serial.print(F("Soft-AP IP address = "));
 Serial.println(WiFi.softAPIP());
     // Set redirection of all DNS queries to itself
    Serial.print(F("Configuring DNS..."));
    delay(100);
    Serial.println("OK");
    /* Setup the DNS server redirecting all the domains to the apIP */
 dnsServer.start(DNS_PORT, "*", ip);//apIP

But still not working

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable. If it's still needed, please reopen the issue.

Thanks for understanding.
