### ISSUE TITLE
Malformed board options in arduino-cli for atmegazero_esp32s2 and deneyapmini

### ISSUE THREAD

**Issue by manchoz** [espressif/arduino-esp32#5618]
### Hardware:
Board:							atmegazero_esp32s2, deneyapmini
Core Installation version:			2.0.0/2.0.0-rc2/Upstream
IDE name:						Arduino CLI
Flash Frequency:					N/A
PSRAM enabled:                                     N/A
Upload Speed:					N/A
Computer OS:                                         All the Arduino CLI supported platforms

### Description:

`boards.txt` has errors on `atmegazero_esp32s2` and `deneyapmini` board options.

`arduino-cli` output on any board-related operation, e.g. `arduino-cli board listall`:

```Error initializing instance: loading platform release esp32:esp32@2.0.0: loading boards: skipping loading of boards esp32:esp32:atmegazero_esp32s2, esp32:esp32:deneyapmini: malformed custom board options```

**Comment by atanisoft** [comment]
@me-no-dev looks like both of these boards still reference `SerialMode` which should now be `CDCOnBoot`

**Comment by manchoz** [comment]
Changing `SerialMode` to `CDCOnBoot` fixes the issue, thanks @atanisoft!

@me-no-dev let me know if you need a PR from me.

**Comment by me-no-dev** [comment]
@manchoz please do send a PR :)

**Comment by VojtechBartoska** [comment]
Hello @manchoz, is this still valid?

**Comment by manchoz** [comment]
@VojtechBartoska no, it has been fixed in https://github.com/espressif/arduino-esp32/pull/5673
