### ISSUE TITLE
esptool.exe 3.1.0 not work in x86 Windows, only x64 

### ISSUE THREAD

**Issue by dialmak** [espressif/arduino-esp32#5629]
Arduino: 1.8.15 (Windows 7), Board :"DOIT ESP32 DEVKIT V1, 40MHz, 921600, None"

> C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\3.1.0/esptool.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

**Comment by VojtechBartoska** [comment]
Hello, closing. Please take a look on #6012.
