### ISSUE TITLE
Built-in Temperature sensor

### ISSUE THREAD

**Issue by bill-orange** [espressif/arduino-esp32#563]
I see there is an example for the built-in hall effect sensor.  Is the built-in temperature sensor available for use?  I did not notice any examples.  I doubt it would be of much use except perhaps to initiate a shut down if the chip got too hot.

### Hardware:
Board:						ESP32 Dev Module  (LOLIN CLONE)
Core Installation/update date:			unknown
IDE name:					Arduino IDE
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
Is built-in temperature sensor enabled in the Arduino IDE?

I have one other related question.  Does anyone know why the hall effect sensor is included in the ESP32?

**Comment by copercini** [comment]
@bill-orange Please, take a look: https://github.com/espressif/arduino-esp32/issues/625
