### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by JakeSays** [espressif/arduino-esp32#5640]
Any plans to add support for the Arduino IDE on linux?

**Comment by chegewara** [comment]
What kind of linux?
It is perfectly working on ubuntu since beginning.

**Comment by JakeSays** [comment]
That's version 1. Version 2 currently has no linux support, or at least I can't find it.

**Comment by chegewara** [comment]
What do you mean by version 2?

I am using master branch, idf-master branch and there should be tag in board manager with version v2.0.0-something.

https://docs.espressif.com/projects/arduino-esp32/en/latest/getting_started.html

**Comment by MarkusAD** [comment]
It's on https://www.arduino.cc/en/software to the right of "Arduino IDE 2.0 beta" it shows
Linux (X86_64 only).

**Comment by atanisoft** [comment]
@JakeSays Arduino IDE 2.0 (beta) and Arduino-esp32 2.0.0 appear to work as expected on Linux. What sort of issue are you facing?

**Comment by lbernstone** [comment]
As noted, this is off topic, since this repo has little control over [Arduino](https://github.com/arduino/Arduino/).

**Comment by JakeSays** [comment]
@lbernstone i'm not talking about the ide.

@chegewara @atanisoft turns out I was using an old board manager link. I'm using the right one now and have esp32 2.0 working. Thanks!
