### ISSUE TITLE
xtensa-esp32-elf-g++: error: esp32dev.map: No such file or directory *** [.pio/build/esp32dev/firmware.elf] Error 1

### ISSUE THREAD

**Issue by jitendra1607** [espressif/arduino-esp32#5646]
```
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
platform_packages =
   framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.0
board_build.filesystem = littlefs
```

xtensa-esp32-elf-g++: error: esp32dev.map: No such file or directory
*** [.pio/build/esp32dev/firmware.elf] Error 1

with the above platformio.ini, I got above error on build. If i remove below line then no issues.
```
platform_packages =
   framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.0
```

Platform - macos
board- esp-wroom-32

**Comment by lbernstone** [comment]
Looks like you have a mismatched toolchain.  Please ask platform.io specfic questions at https://github.com/platformio/platform-espressif32/issues

**Comment by Jason2866** [comment]
You have too add:
```
platform                    = https://github.com/platformio/platform-espressif32.git#feature/arduino-idf-master
```

**Comment by VojtechBartoska** [comment]
Hello, I'm closing this issue. You can find more info and workaround in this issue #6044.
