### ISSUE TITLE
ESP32 WROVER IE not programming, WROVER B programs ok

### ISSUE THREAD

**Issue by manecolooper** [espressif/arduino-esp32#5647]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.6
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                    yes
Upload Speed:					921600
Computer OS:                                        Windows 10

### Description:

i received some Wrover IE instead of WROVER B ,and can´t program those from Arduino IDE, error is Timed out waiting for packet header.
Same sketch programs perfect on WROVER B

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by me-no-dev** [comment]
Maybe check your connections, cables, etc. There is nothing in Arduino to prevent you from flashing WROVER-IE
