### ISSUE TITLE
S2 Minii not in Arduino package 

### ISSUE THREAD

**Issue by PaulF8080** [espressif/arduino-esp32#5655]
### Description:
package/package_esp32_index.template.json doesn't have the new Wemos/Lolin S2 Mini

https://www.wemos.cc/en/latest/s2/s2_mini.html

**Comment by Jason2866** [comment]
Yes, correct. Boards are in boards.txt

**Comment by PaulF8080** [comment]
I got the S2 Mini and couldn't see the it in Tools->Board list of the Arduino IDE. Looks like I  pointed to the wrong file.  Closing .
