### ISSUE TITLE
Enable progress bar on ArduinoOTA upload

### ISSUE THREAD

**Issue by tbertels** [espressif/arduino-esp32#5656]
Is there a reason why PROGRESS isn't enabled in platform.txt?
https://github.com/espressif/arduino-esp32/blob/master/platform.txt#L13
https://github.com/espressif/arduino-esp32/blob/master/tools/espota.py#L304

I tested it with it enabled, it works fine.
The progress is shown based on the size of the file sent, so it should always work.

![image](https://user-images.githubusercontent.com/3265870/132897764-48481eaf-99a9-4cfa-bd5e-89fed5e1fe0c.png)
vs
![image](https://user-images.githubusercontent.com/3265870/132897666-d718d111-1574-43d8-976a-ff06402d6714.png)

**Comment by me-no-dev** [comment]
the reason is that ArduinoIDE's console does not support carriage return, so it will print a whole lot of lines as percentage grows.

**Comment by tbertels** [comment]
It actually does now.
Here are captures with the platform.txt patch:
![1](https://user-images.githubusercontent.com/3265870/133435001-f36a4233-885c-4882-a563-e0ce98df981a.png)
![2](https://user-images.githubusercontent.com/3265870/133435015-57e1ca9a-acb4-4c71-8247-bdfd05ac9ba5.png)

When uploading by USB instead of OTA however, it still does indeed output multiple lines.

**Comment by me-no-dev** [comment]
hmm interesting. will check it out. I reopened the pull request
