### ISSUE TITLE
esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_TIMER); not working as expected

### ISSUE THREAD

**Issue by lunadm** [espressif/arduino-esp32#5659]
* Development Board: ESP32-CAM
* Module or chip used: ESP32-S
* IDF version: Arduino 2.0.0-release
* Operating System: Mac
* Power Supply: [USB/battery]
* Chip is ESP32-D0WD (revision 1)

Disable wakeup source isn’t working as expected
Keeps waking up from deep sleep based on the previous timer
 
esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_TIMER);

Using the following 
  esp_sleep_enable_timer_wakeup((60 * 15) * 1000000); //15 mins
  esp_sleep_enable_ext0_wakeup(GPIO_NUM_13, 0);
  esp_light_sleep_start();

  esp_sleep_wakeup_cause_t cause = esp_sleep_get_wakeup_cause();
  const char *cause_str;
  switch (cause) {
    case ESP_SLEEP_WAKEUP_GPIO:
      cause_str = "GPIO";
      break;
    case ESP_SLEEP_WAKEUP_UART:
      cause_str = "UART";
      break;
    case ESP_SLEEP_WAKEUP_TIMER:
      cause_str = "timer";
      esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_TIMER); //disable light sleep timer
      esp_sleep_enable_ext0_wakeup(GPIO_NUM_13, 0);
      esp_deep_sleep_start();
      break;
    default:
      cause_str = "unknown";
  }
  Serial.println(cause_str);
  printf("cause %d\n", cause);

**Comment by felmue** [comment]
Hello @lunadm 

just curious, have you tried without enabling `ext0` wakeup? E.g. only with the timer? Just to make sure the wakeup isn't triggered by the GPIO?

Thanks
Felix

**Comment by lunadm** [comment]
HI
thanks
The cam is logging the time it goes to sleep, the wakeup reset reason and start-up time.
Going through the logs 'deep sleep wakeup, Wakeup caused by timer' every 15 minutes (the previous light sleep time).
Its a strange one because I've just been testing this on another board/usb/ and its not occurring
im going to close this issue and test it further  thanks
