### ISSUE TITLE
Compile time defines for ESP32 *MCU* type?

### ISSUE THREAD

**Issue by mrfaptastic** [espressif/arduino-esp32#5660]
Sorry for the potentially stupid question, but are there standard compile time defines in an Arduino ide  + esp32-arduino sketch to identify between the underlying SoC/MCU design:

ESP32 (old school original)
ESP32S2
ESP32C3 ?

For the love of me I can't figure out what they are. ESP32 'varient' doesn't work as that means a sketch with potentially hundreds of #ifdefs.

**Comment by Jason2866** [comment]
You find a example here https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/ResetReason/ResetReason.ino

**Comment by mrfaptastic** [comment]
Excellent. Thank you!
