### ISSUE TITLE
Change request CONFIG_BTC_TASK_STACK_SIZE

### ISSUE THREAD

**Issue by nkolban** [espressif/arduino-esp32#567]
When working in ESP-IDF, we have access to the "make menuconfig" tool to change configurations on a per project basis.

In the projects I am working on in the context of ESP-IDF, I am finding I have to increase the property value for CONFIG_BTC_TASK_STACK_SIZE from the default of 2048 to 8000.   This issue asks for the Arduino project recommendation of how to change the corresponding value for Arduino sketches?

Back story
There are many parameters that can be configured in "make menuconfig".  This results in a header file called "sdkconfig.h" which is distributed by the Arduino project.  Is it the intent that "users" of the Arduino library should edit this file by hand?  If yes, then thats the end of the story and I'll start writing up how to edit certain fields and their ramifications.

If no, then if a sketch needs a property changed from its current existent value, what is the recommended procedure/story to request a change?

**Comment by copercini** [comment]
Increased here: https://github.com/espressif/arduino-esp32/commit/8bca8d546639e81bf8de842c81540f8990ad1761#diff-2f6c51c0d9a7c54fe420b345f9b6f61eR71
to 8192

=)
