### ISSUE TITLE
error: 'CONFIG_ESP32_RTC_CLOCK_SOURCE' was not declared in this scope

### ISSUE THREAD

**Issue by hdpklm** [espressif/arduino-esp32#5693]
Hello.

I test the code from library of ESP32 > DeepSleep > TimerWakeUp
I try to configure RTC with internal clock to sleep and wake up every 15 sec.
I use this code

```
CONFIG_ESP32_RTC_CLOCK_SOURCE(CONFIG_ESP32_RTC_CLOCK_SOURCE_INTERNAL_RC);
esp_sleep_enable_timer_wakeup(TIME_TO_SLEEP * uS_TO_S_FACTOR);
esp_deep_sleep_start();
```

but when I build the code I get this error

```
[Starting] Verifying sketch 'max-reg-config.ino'
[Warning] Output path is not specified. Unable to reuse previously compiled files. Build will be slower. See README.
Cargando configuración...
Inicializando paquetes...
Preparando tarjetas...
Verficando...
c:\hassan\wito-SmartWatch\test - max30001\max-reg-config\max-reg-config.ino: In function 'void power_mode_init()':
max-reg-config:108:73: error: 'CONFIG_ESP32_RTC_CLOCK_SOURCE' was not declared in this scope
CONFIG_ESP32_RTC_CLOCK_SOURCE(CONFIG_ESP32_RTC_CLOCK_SOURCE_INTERNAL_RC);
```

I dont know how to run RTC with internal clock and i try to run without CONFIG_ESP32_RTC_CLOCK_SOURCE function and its not wakeup after 15 seconds

Note: when I upload the code in ESP-WROOM-32 without change RTC clock it wotk. but in my pcb when it sleep it not wake up again.

thank you so mutch.

**Comment by me-no-dev** [comment]
please fill properly the issue template. Include minimal sketch example, arduino version and so on. I will close this now, so you can open a proper one :)
