### ISSUE TITLE
SoftAP not working (error)

### ISSUE THREAD

**Issue by VladimirVecera** [espressif/arduino-esp32#5709]
I am using ESP32 core 2.0.0 on my Wroom-32-U and unfortunately the connection to ESP32 via wifi (AP) via the SoftAP library does not work. Wifi ESP32 can be seen, but as soon as they start connecting to ESP32 and it has to generate an IP address, ESP32 crashes, restarts.
I tried to put the IP address on hard, it won't help either. 

`WiFi.softAP(ssid, password);`

**Comment by me-no-dev** [comment]
Please fill the proper issue template with all requested information.
