### ISSUE TITLE
_handle_error(): [data_to_read():324]: (-30592) SSL - A fatal alert message was received from our peer

### ISSUE THREAD

**Issue by gomegs** [espressif/arduino-esp32#5710]
How to HTTPS GET protected file using HTTPClient and WiFiClientSecure using private client certificate and private client key to appache2 when “SSLVerifyClient require” is set in <Location /private_folder>

**Example code:**
```c++
#include <Arduino.h>
#include <FS.h>
#include <LittleFS.h>
#include <WiFi.h>  //  WiFi version 2.0.0 
#include <HTTPClient.h>  //  HTTPClient version 2.0.0 
#include <WiFiClientSecure.h>  //  WiFiClientSecure version 2.0.0

const char* fn_ca_crt = "/ca.crt";
const char* fn_client_crt = "/client.crt";
const char* fn_client_key = "/client.key";

void readFile(fs::FS& fs, const char* path)
{
    Serial.printf("\n\nReading file: %s\n", path);

    File file = fs.open(path);
    if (!file)
    {
        Serial.println("Failed to open file for reading");
        return;
    }

    //Serial.print("Read from file: ");
    while (file.available())
    {
        Serial.write(file.read());
    }
    file.close();
}

// Not sure if WiFiClientSecure checks the validity date of the certificate. 
// Setting clock just to be sure...
void setClock()
{
    configTime(0, 0, "pool.ntp.org");

    Serial.print(F("Waiting for NTP time sync: "));
    time_t nowSecs = time(nullptr);
    while (nowSecs < 8 * 3600 * 2)
    {
        delay(500);
        Serial.print(F("."));
        yield();
        nowSecs = time(nullptr);
    }

    Serial.println();
    struct tm timeinfo;
    gmtime_r(&nowSecs, &timeinfo);
    Serial.print(F("Current time: "));
    Serial.print(asctime(&timeinfo));
}

void setup()
{
    Serial.begin(115200);
    // Serial.setDebugOutput(true);

    Serial.println();
    Serial.println();

    if (!LittleFS.begin(true))
    {
        Serial.println("ERR: Mount LittleFS");
        return;
    }

    // Debug ca, private cert and private key file content
    //readFile(LittleFS, fn_ca_crt);
    //readFile(LittleFS, fn_client_crt);
    //readFile(LittleFS, fn_client_key);

    // wait for WiFi connection
    Serial.print("\nWaiting for WiFi to connect...");
    WiFi.begin("SomeAP", "SomePW");
    while ((WiFi.status() != WL_CONNECTED))
    {
        Serial.print(".");
        delay(1000);
    }
    Serial.println("WiFi connected");

    setClock();
}

void loop()
{
    WiFiClientSecure* client = new WiFiClientSecure;
    if (client)
    {
        File file;
        file = LittleFS.open(fn_ca_crt);
        client->loadCACert(file, file.size());
        file.close();

        file = LittleFS.open(fn_client_crt);
        client->loadCertificate(file, file.size());
        file.close();
        
        file = LittleFS.open(fn_client_key);
        client->loadPrivateKey(file, file.size());
        file.close();

        {
            // Add a scoping block for HTTPClient https to make sure it is destroyed before WiFiClientSecure *client is 
            HTTPClient https;

            Serial.print("[HTTPS] begin...\n");
            if (https.begin(*client, "https://some.host/private_folder/index.html"))
            {  // HTTPS
                Serial.print("[HTTPS] GET...\n");
                // start connection and send HTTP header
                int httpCode = https.GET();

                // httpCode will be negative on error
                if (httpCode > 0)
                {
                    // HTTP header has been send and Server response header has been handled
                    Serial.printf("[HTTPS] GET... code: %d\n", httpCode);

                    // file found at server
                    if (httpCode == HTTP_CODE_OK || httpCode == HTTP_CODE_MOVED_PERMANENTLY)
                    {
                        String payload = https.getString();
                        Serial.println(payload);
                    }
                }
                else
                {
                    Serial.printf("[HTTPS] GET... failed, error: %s\n", https.errorToString(httpCode).c_str());
                }

                https.end();
            }
            else
            {
                Serial.printf("[HTTPS] Unable to connect\n");
            }

            // End extra scoping block
        }

        delete client;
    }
    else
    {
        Serial.println("Unable to create client");
    }

    while (1);
}
```

**Serial console output:**
Waiting for WiFi to connect...[    51][D][WiFiGeneric.cpp:808] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   144][V][WiFiGeneric.cpp:96] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
[   143][V][WiFiGeneric.cpp:272] _arduino_event_cb(): STA Started
[   150][D][WiFiGeneric.cpp:808] _eventCallback(): Arduino Event: 2 - STA_START
...[  2234][V][WiFiGeneric.cpp:284] _arduino_event_cb(): STA Connected: SSID: SomeAP, BSSID: 00:0c:42:fc:66:57, Channel: 1, Auth: WPA2_PSK
[  2235][D][WiFiGeneric.cpp:808] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  2246][V][WiFiGeneric.cpp:294] _arduino_event_cb(): STA Got New IP:172.26.1.239
[  2249][D][WiFiGeneric.cpp:808] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  2256][D][WiFiGeneric.cpp:857] _eventCallback(): STA IP: 172.26.1.239, MASK: 255.255.255.0, GW: 172.26.1.3
WiFi connected
Waiting for NTP time sync: ...
Current time: Mon Sep 27 09:44:16 2021
[HTTPS] begin...
[  4686][V][HTTPClient.cpp:245] beginInternal(): url: https://some.host/firmware/index.html
[  4686][D][HTTPClient.cpp:293] beginInternal(): protocol: https, host: some.host port: 443 url: /firmware/index.html
[HTTPS] GET...
[  4706][D][HTTPClient.cpp:579] sendRequest(): request type: 'GET' redirCount: 0

[  4706][V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 211459
[  4712][V][ssl_client.cpp:65] start_ssl_client(): Starting socket
[  4730][V][ssl_client.cpp:141] start_ssl_client(): Seeding the random number generator
[  4731][V][ssl_client.cpp:150] start_ssl_client(): Setting up the SSL/TLS structure...
[  4735][V][ssl_client.cpp:166] start_ssl_client(): Loading CA cert
[  4783][V][ssl_client.cpp:215] start_ssl_client(): Loading CRT cert
[  4833][V][ssl_client.cpp:224] start_ssl_client(): Loading private key
[  4887][V][ssl_client.cpp:234] start_ssl_client(): Setting hostname for TLS session...
[  4888][V][ssl_client.cpp:249] start_ssl_client(): Performing the SSL/TLS handshake...
[  6242][D][ssl_client.cpp:262] start_ssl_client(): Protocol is TLSv1.2 Ciphersuite is TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
[  6242][D][ssl_client.cpp:264] start_ssl_client(): Record expansion is 29
[  6248][V][ssl_client.cpp:270] start_ssl_client(): Verifying peer X.509 certificate...
[  6256][V][ssl_client.cpp:279] start_ssl_client(): Certificate verified.
[  6263][V][ssl_client.cpp:294] start_ssl_client(): Free internal heap after TLS 171095
[  6270][D][HTTPClient.cpp:1125] connect():  connected to some.host:443
[  6277][V][ssl_client.cpp:332] send_ssl_data(): Writing HTTP request with 164 bytes...
**[  7638][E][ssl_client.cpp:36] _handle_error(): [data_to_read():324]: (-30592) SSL - A fatal alert message was received from our peer**
[  7639][V][ssl_client.cpp:302] stop_ssl_socket(): Cleaning SSL connection.
[  7645][D][HTTPClient.cpp:603] sendRequest(): sendRequest code=-5

[  7651][W][HTTPClient.cpp:1419] returnError(): error(-5): connection lost
[HTTPS] GET... failed, error: connection lost
[  7668][D][HTTPClient.cpp:400] disconnect(): tcp is closed

[  7668][V][ssl_client.cpp:302] stop_ssl_socket(): Cleaning SSL connection.
[  7674][V][ssl_client.cpp:302] stop_ssl_socket(): Cleaning SSL connection.

**Apache error log:**
[Mon Sep 27 09:11:47.818064 2021] [ssl:info] [pid 139454] [client <ip>:<port>] AH01964: Connection to child 5 established (server some.host:443)
[Mon Sep 27 09:11:47.818768 2021] [ssl:debug] [pid 139454] ssl_engine_kernel.c(2372): [client <ip>:61295] AH02043: SSL virtual host for servername some.host found
[Mon Sep 27 09:11:47.875202 2021] [ssl:debug] [pid 139454] ssl_engine_kernel.c(1764): [client <ip>:61295] AH02275: Certificate Verification, depth 1, CRL checking mode: none (0) [subject: emailAddress=my@email.com, OU=generate-CA,O=AO,CN=A_CN / issuer: emailAddress=my@email.com,OU=generate-CA,O=A_O,CN=A_CN / serial: 542286744A38515167908C91111466AD20 / notbefore: Sep 12 05:37:57 2021 GMT / notafter: Sep  9 05:37:57 2032 GMT]
[Mon Sep 27 09:11:47.875310 2021] [ssl:debug] [pid 139454] ssl_engine_kernel.c(1764): [client <ip>:61295] AH02275: Certificate Verification, depth 0, CRL checking mode: none (0) [subject: CN=test / issuer: emailAddress=my@email.com,OU=generate-CA,O=A_O,CN=A_CN / serial: 7D2387987AB2D2B97648A4 / notbefore: Sep 15 08:37:38 2021 GMT / notafter: Sep 12 08:37:38 2032 GMT]
[Mon Sep 27 09:11:49.094594 2021] [socache_shmcb:debug] [pid 139454] mod_socache_shmcb.c(493): AH00831: socache_shmcb_store (0x39 -> subcache 25)
[Mon Sep 27 09:11:49.094629 2021] [socache_shmcb:debug] [pid 139454] mod_socache_shmcb.c(847): AH00847: insert happened at idx=0, data=(0:32)
[Mon Sep 27 09:11:49.094632 2021] [socache_shmcb:debug] [pid 139454] mod_socache_shmcb.c(850): AH00848: finished insert, subcache: idx_pos/idx_used=0/1, data_pos/data_used=0/1320
[Mon Sep 27 09:11:49.094634 2021] [socache_shmcb:debug] [pid 139454] mod_socache_shmcb.c(515): AH00834: leaving socache_shmcb_store successfully
[Mon Sep 27 09:11:49.094643 2021] [ssl:debug] [pid 139454] ssl_engine_kernel.c(2254): [client <ip>:61295] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
[Mon Sep 27 09:11:49.147136 2021] [ssl:debug] [pid 139454] ssl_engine_kernel.c(415): [client <ip>:61295] AH02034: Initial (No.1) HTTPS request received for child 5 (server some.host:443)
[Mon Sep 27 09:11:49.147244 2021] [ssl:debug] [pid 139454] ssl_engine_kernel.c(782): [client <ip>:61295] AH02255: Changed client verification type will force renegotiation
[Mon Sep 27 09:11:49.147253 2021] [ssl:info] [pid 139454] [client <ip>:61295] AH02221: Requesting connection re-negotiation
[Mon Sep 27 09:11:49.147301 2021] [ssl:debug] [pid 139454] ssl_engine_kernel.c(984): [client <ip>:61295] AH02260: Performing full renegotiation: complete handshake protocol (client does support secure renegotiation)
[Mon Sep 27 09:11:49.147370 2021] [ssl:debug] [pid 139454] ssl_engine_kernel.c(2254): [client <ip>:61295] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
[Mon Sep 27 09:11:49.147379 2021] [ssl:info] [pid 139454] [client <ip>:61295] AH02226: Awaiting re-negotiation handshake
[Mon Sep 27 09:11:49.158937 2021] [socache_shmcb:debug] [pid 139454] mod_socache_shmcb.c(555): AH00837: socache_shmcb_remove (0x39 -> subcache 25)
[Mon Sep 27 09:11:49.158952 2021] [socache_shmcb:debug] [pid 139454] mod_socache_shmcb.c(939): AH00852: possible match at idx=0, data=0
[Mon Sep 27 09:11:49.158954 2021] [socache_shmcb:debug] [pid 139454] mod_socache_shmcb.c(944): AH00853: shmcb_subcache_remove removing matching entry
[Mon Sep 27 09:11:49.158956 2021] [socache_shmcb:debug] [pid 139454] mod_socache_shmcb.c(570): AH00839: leaving socache_shmcb_remove successfully
**[Mon Sep 27 09:11:49.159006 2021] [ssl:error] [pid 139454] [client <ip>:61295] AH02261: Re-negotiation handshake failed**
[Mon Sep 27 09:11:49.159023 2021] [ssl:error] [pid 139454] SSL Library Error: error:14094153:SSL routines:ssl3_read_bytes:no renegotiation
[Mon Sep 27 09:11:49.159078 2021] [headers:debug] [pid 139454] mod_headers.c(899): AH01503: headers: ap_headers_error_filter()
[Mon Sep 27 09:11:49.159140 2021] [ssl:debug] [pid 139454] ssl_engine_io.c(1368): [client <ip>:61295] AH02007: SSL handshake interrupted by system [Hint: Stop button pressed in browser?!]
[Mon Sep 27 09:11:49.159150 2021] [ssl:info] [pid 139454] [client <ip>:61295] AH01998: Connection closed to child 5 with abortive shutdown (server some.host:443)

The following works using the same ca.crt, client.crt and client.key files using curl on another centos machine.

```
curl -v --cert ./client.crt --key ./client.key --cacert ./ca.crt https://some.host:443/private_folder/index.html
```

**Console output:**
```
[root@somewhere]# curl -v --cert ./client.crt --key ./client.key --cacert ./ca.crt https://some.host:443/private_folder/some_file.txt
* About to connect() to some.host port 443 (#0)
*   Trying <ip>...
* Connected to some.host (a ip address) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: ./ca.crt
  CApath: none
* NSS: client certificate from file
*       subject: CN=test
*       start date: Sep 15 08:37:38 2021 GMT
*       expire date: Sep 12 08:37:38 2032 GMT
*       common name: test
*       issuer: E=my@email.com,OU=generate-CA,O=A_O,CN=A_CN
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: E=my@email.com,OU=generate-CA,O=A_O,CN=some.host
*       start date: Sep 12 05:37:57 2021 GMT
*       expire date: Sep 09 05:37:57 2032 GMT
*       common name: some.host
*       issuer: E=my@email.com,OU=generate-CA,O=A_O,CN=A_CN
> GET /private_folder/index.html HTTP/1.1
> User-Agent: curl/7.29.0
> Host: some.host
> Accept: */*
>
* NSS: client certificate from file
*       subject: CN=test
*       start date: Sep 15 08:37:38 2021 GMT
*       expire date: Sep 12 08:37:38 2032 GMT
*       common name: test
*       issuer: E=my@email.com,OU=generate-CA,O=A_O,CN=A_CN
< HTTP/1.1 200 OK
< Date: Thu, 23 Sep 2021 14:34:17 GMT
< Server: Apache/2.4.41 (Ubuntu)
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Last-Modified: Thu, 23 Sep 2021 07:09:04 GMT
< ETag: "17-5cca44e4e2400"
< Accept-Ranges: bytes
< Content-Length: 23
< Content-Type: text/html
<
Hi from private file<br/>
* Connection #0 to host some.host left intact
```

**Apache2 log when using curl for testing:**
[Mon Sep 27 10:01:33.734960 2021] [ssl:info] [pid 137587] [client <ip>:50138] AH01964: Connection to child 2 established (server some.host:443)
[Mon Sep 27 10:01:33.735216 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(2372): [client <ip>:50138] AH02043: SSL virtual host for servername some.host found
[Mon Sep 27 10:01:33.749220 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(1764): [client <ip>:50138] AH02275: Certificate Verification, depth 1, CRL checking mode: none (0) [subject: emailAddress=my@email.com,OU=generate-CA,O=A_O,CN=A_CN / issuer: emailAddress=my@email.com,OU=generate-CA,O=A_O,CN=A_CN / serial: 5422867DB44A4638515167908C9107111466AD20 / notbefore: Sep 12 05:37:57 2021 GMT / notafter: Sep  9 05:37:57 2032 GMT]
[Mon Sep 27 10:01:33.749294 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(1764): [client <ip>:50138] AH02275: Certificate Verification, depth 0, CRL checking mode: none (0) [subject: CN=test / issuer: emailAddress=my@email.com,OU=generate-CA,O=A_O,CN=A_CN / serial: 7D2387987AB2DC2DE0C86ED2B97648A4 / notbefore: Sep 15 08:37:38 2021 GMT / notafter: Sep 12 08:37:38 2032 GMT]
[Mon Sep 27 10:01:33.749525 2021] [socache_shmcb:debug] [pid 137587] mod_socache_shmcb.c(493): AH00831: socache_shmcb_store (0xc9 -> subcache 9)
[Mon Sep 27 10:01:33.749573 2021] [socache_shmcb:debug] [pid 137587] mod_socache_shmcb.c(847): AH00847: insert happened at idx=0, data=(0:32)
[Mon Sep 27 10:01:33.749588 2021] [socache_shmcb:debug] [pid 137587] mod_socache_shmcb.c(850): AH00848: finished insert, subcache: idx_pos/idx_used=0/1, data_pos/data_used=0/1320
[Mon Sep 27 10:01:33.749605 2021] [socache_shmcb:debug] [pid 137587] mod_socache_shmcb.c(515): AH00834: leaving socache_shmcb_store successfully
[Mon Sep 27 10:01:33.749625 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(2254): [client <ip>:50138] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
[Mon Sep 27 10:01:33.751077 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(415): [client <ip>:50138] AH02034: Initial (No.1) HTTPS request received for child 2 (server some.host:443)
[Mon Sep 27 10:01:33.751138 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(782): [client <ip>:50138] AH02255: Changed client verification type will force renegotiation
[Mon Sep 27 10:01:33.751156 2021] [ssl:info] [pid 137587] [client <ip>:50138] AH02221: Requesting connection re-negotiation
[Mon Sep 27 10:01:33.751170 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(984): [client <ip>:50138] AH02260: Performing full renegotiation: complete handshake protocol (client does support secure renegotiation)
[Mon Sep 27 10:01:33.751212 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(2254): [client <ip>:50138] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
[Mon Sep 27 10:01:33.751231 2021] [ssl:info] [pid 137587] [client <ip>:50138] AH02226: Awaiting re-negotiation handshake
[Mon Sep 27 10:01:33.752621 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(2372): [client <ip>:50138] AH02043: SSL virtual host for servername some.host found
[Mon Sep 27 10:01:33.760862 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(1764): [client <ip>:50138] AH02275: Certificate Verification, depth 1, CRL checking mode: none (0) [subject: emailAddress=my@email.com,OU=generate-CA,O=A_O,CN=A_CN / issuer: emailAddress=my@email.com,OU=generate-CA,O=A_O,CN=A_CN / serial: 5422867DB44A4638515167908C9107111466AD20 / notbefore: Sep 12 05:37:57 2021 GMT / notafter: Sep  9 05:37:57 2032 GMT]
[Mon Sep 27 10:01:33.761010 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(1764): [client <ip>:50138] AH02275: Certificate Verification, depth 0, CRL checking mode: none (0) [subject: CN=test / issuer: emailAddress=my@email.com,OU=generate-CA,O=A_O,CN=A_CN / serial: 7D2387987AB2DC2DE0C86ED2B97648A4 / notbefore: Sep 15 08:37:38 2021 GMT / notafter: Sep 12 08:37:38 2032 GMT]
[Mon Sep 27 10:01:33.761408 2021] [socache_shmcb:debug] [pid 137587] mod_socache_shmcb.c(493): AH00831: socache_shmcb_store (0x72 -> subcache 18)
[Mon Sep 27 10:01:33.761456 2021] [socache_shmcb:debug] [pid 137587] mod_socache_shmcb.c(847): AH00847: insert happened at idx=0, data=(0:32)
[Mon Sep 27 10:01:33.761471 2021] [socache_shmcb:debug] [pid 137587] mod_socache_shmcb.c(850): AH00848: finished insert, subcache: idx_pos/idx_used=0/1, data_pos/data_used=0/1296
[Mon Sep 27 10:01:33.761480 2021] [socache_shmcb:debug] [pid 137587] mod_socache_shmcb.c(515): AH00834: leaving socache_shmcb_store successfully
[Mon Sep 27 10:01:33.761497 2021] [ssl:debug] [pid 137587] ssl_engine_kernel.c(2254): [client <ip>:50138] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
[Mon Sep 27 10:01:33.761520 2021] [authz_core:debug] [pid 137587] mod_authz_core.c(817): [client <ip>:50138] AH01626: authorization result of Require all granted: granted
[Mon Sep 27 10:01:33.761533 2021] [authz_core:debug] [pid 137587] mod_authz_core.c(817): [client <ip>:50138] AH01626: authorization result of <RequireAny>: granted
[Mon Sep 27 10:01:33.763246 2021] [ssl:debug] [pid 137587] ssl_engine_io.c(1102): [client <ip>:50138] AH02001: Connection closed to child 2 with standard shutdown (server some.host:443)

Hardware: ESP32 dev module
O/S: Windiows 10
IDE: Arduino 1.8.13).

**Comment by VojtechBartoska** [comment]
Hello @gomegs , sorry for late reply. Are you able to test your issue on development version [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) to check if this is still valid? You can take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable. 

If it's still needed, please reopen the issue.

Thanks for understanding.
