### ISSUE TITLE
Examples for HomeKit 

### ISSUE THREAD

**Issue by zhengxi0922** [espressif/arduino-esp32#5722]
Hi is there any chance that you guys can add some HomeKit examples in this?
Tried the IDF, but the complexity made me back out

**Comment by RoCorbera** [comment]
@zhengxi0922, you can find it already in Arduino Libraries. 
Go to ArduinoIDE Menu --> Sketch --> Include Library --> Manage Libraries 
Open Library Manager and serach for HomeSpan library from Gregg (version 1.3.0)

Then go to ArduinoIDE Menu --> File --> Examples --> HomeSpan --> several examples there

I hope it helps you!
