### ISSUE TITLE
Errors and warnings compiling the same sketch with the new ESP32 v2.0.0

### ISSUE THREAD

**Issue by pberna67** [espressif/arduino-esp32#5729]
Dear Developer

**_I've noticed errors and warnings compiling the attached sketch using_**
**Espressif System Package 2.0.0-rc2 or 
Espressif System Package 2.0.0**

_**But no errors nor warnings emerges when the**_ 
**Espressif System Package 1.0.6 or below versions  are used**

No other changes have been done, only  System Package has been changed

_**The errors/warnings found compiling the sketch with the  System package Package 2.0.0 are the following**_

In file included from C:\Users\pabe\Documents\Arduino\MyExamples\MySimpleMQTT\TemperatureMonitor8MQTTClient_GitHub\TemperatureMonitor8MQTTClient_GitHub.ino:12:
C:\Users\pabe\Documents\Arduino\libraries\ESP32TimerInterrupt\src/ESP32TimerInterrupt.h:56:4: warning: #warning Using ESP32TimerInterrupt Library [-Wcpp]
   #warning Using ESP32TimerInterrupt Library
    ^~~~~~~
In file included from C:\Users\pabe\Documents\Arduino\libraries\OneWire\OneWire.cpp:144:
C:\Users\pabe\Documents\Arduino\libraries\OneWire\util/OneWire_direct_gpio.h: In function 'void directModeInput(uint32_t)':
C:\Users\pabe\Documents\Arduino\libraries\OneWire\util/OneWire_direct_gpio.h:161:26: error: 'rtc_gpio_desc' was not declared in this scope
         uint32_t rtc_reg(rtc_gpio_desc[pin].reg);
                          ^~~~~~~~~~~~~
C:\Users\pabe\Documents\Arduino\libraries\OneWire\util/OneWire_direct_gpio.h:161:26: note: suggested alternative: 'rtc_io_desc'
         uint32_t rtc_reg(rtc_gpio_desc[pin].reg);
                          ^~~~~~~~~~~~~
                          rtc_io_desc
C:\Users\pabe\Documents\Arduino\libraries\OneWire\util/OneWire_direct_gpio.h: In function 'void directModeOutput(uint32_t)':
C:\Users\pabe\Documents\Arduino\libraries\OneWire\util/OneWire_direct_gpio.h:189:26: error: 'rtc_gpio_desc' was not declared in this scope
         uint32_t rtc_reg(rtc_gpio_desc[pin].reg);
                          ^~~~~~~~~~~~~
C:\Users\pabe\Documents\Arduino\libraries\OneWire\util/OneWire_direct_gpio.h:189:26: note: suggested alternative: 'rtc_io_desc'
         uint32_t rtc_reg(rtc_gpio_desc[pin].reg);
                          ^~~~~~~~~~~~~
                          rtc_io_desc
Multiple libraries were found for "WiFiClient.h"
 Used: C:\Users\pabe\Documents\ArduinoData\packages\esp32\hardware\esp32\2.0.0\libraries\WiFi
 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.51.0_x86__mdqgnx93n4wtt\libraries\WiFi
exit status 1
Error compiling for board u-blox NINA-W10 series (ESP32).

---------------------------------------------------------------------------------------------------------------------
**Describe your system( Hardware, computer, O/S, core version, environment).**
Board: u.blox NINA B102 board with ESP32
Core Installation/update date: ESP 32 lib available in this site today
IDE name: Arduino IDE
Flash Frequency: https://www.u-blox.com/en/product/evk-nina-w10
PSRAM enabled: unnknown
Upload Speed: 115200
Computer OS: Windows 10

**Additional not standard Libraries used:**
SD                                 v1.2.4
Wifi                               v.2.4
Dellas T%emperature   v2.9.0
DS18B29                       v1.0.0
ESP32TimerInterrupt    v1.4.0
ESOMQTTClient            v1.11.1
OneWire                       v2.3.5
PubSubLinbet                v2.8.9
RTCLib                           v1.14.1
uRTCLib                         v6.4.0

**Added sketch** 
[TemperatureMonitor8MQTTClient_GitHub.zip](https://github.com/espressif/arduino-esp32/files/7274309/TemperatureMonitor8MQTTClient_GitHub.zip)

Please try to compile (it is not necessary to have the target board) the attached sketch with Espressif System Package 2.0.0 and with the above listed libraries and pleaese indicate way it is not possible any more to recompile it

**Comment by me-no-dev** [comment]
This is a problem with the OneWire library. They access the GPIO on a level lower than Arduino.

**Comment by pberna67** [comment]
It seems that there is also a problem in WiFi lib
