### ISSUE TITLE
Modules with PSRAM take long to boot

### ISSUE THREAD

**Issue by mcer12** [espressif/arduino-esp32#5737]
Seems like PSRAM is tested during boot, which can be disabled in menuconfonfig ("Run memory test on SPI RAM initialization" option). This causes **~500ms delay in boot**. It would be nice to be able to disable the PSRAM test in arduino environment as well.

It is mentioned here:
https://esp32.com/viewtopic.php?t=9448

**Comment by mcer12** [comment]
Any news on this? I know 500ms doesn't seem like a big deal but on battery powered devices, it can mean weeks of extra deep sleep time :)

**Comment by SuGlider** [comment]
@mcer12 
Sorry for the delay. I already have a solution for it.
Using ```BYPASS_SPIRAM_TEST(bool);``` will allow you to bypass PSRAM test and make the WROVER boot fast.

Example:

``` dart
BYPASS_SPIRAM_TEST(true);

void setup() {
  Serial.begin(115200);
  Serial.println("\n Testing SPIRAM test bypass!");
  Serial.println("Check how long does it take to boot in a WROVER module.");
}

void loop() {
  static uint8_t count = 0;
  Serial.print("-");
  delay(500);
  if (++count == 32) {
    count = 0;
    Serial.println();
  }
}
```

**Comment by SuGlider** [comment]
The PR #6135  will solve your need.

**Comment by ashald** [comment]
How do I use it? I'm getting an error when I'm trying to add it as in the comment above:
```
src/main.cpp:32:19: error: expected constructor, destructor, or type conversion before '(' token
 BYPASS_SPIRAM_TEST(true);
```
