### ISSUE TITLE
Esp32s2 Run httpUpdata Example Serial port error E (11914) ESP_image: image at 0x10000 has invalid magic byte (nothing flashed here?)

### ISSUE THREAD

**Issue by Kevin-CEN** [espressif/arduino-esp32#5742]
There is no problem running the httpUpdata sample using ESP32 -S, and OTA can succeed.
When I changed the chip to ESP32S2, I did the corresponding configuration, compile and burn no problem, when in ESP32S2
Esp32s2 Run httpUpdata Example Serial port error E (11914) ESP_image: image at 0x10000 has invalid magic byte (nothing flashed here?)
=================================================
Here's my burning tip:
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: /dev/cu.usbserial-14330
Uploading .pio/build/esp32dev/firmware.bin
esptool.py v3.1
Serial port /dev/cu.usbserial-14330
Connecting....
Chip is ESP32-S2
Features: WiFi, ADC and temperature sensor calibration in BLK2 of efuse
Crystal is 40MHz
MAC: 7c:df:a1:39:02:e0
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00001000 to 0x00004fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x000c8fff...
Compressed 12576 bytes to 8732...
Writing at 0x00001000... (100 %)
Wrote 12576 bytes (8732 compressed) at 0x00001000 in 0.4 seconds (effective 251.5 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.1 seconds (effective 392.1 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 638.5 kbit/s)...
Hash of data verified.
Compressed 756832 bytes to 496550...
Writing at 0x00010000... (3 %)
Writing at 0x0001a588... (6 %)
Writing at 0x000254d3... (9 %)
Writing at 0x0003387a... (12 %)
Writing at 0x00039805... (16 %)
Writing at 0x0003efa4... (19 %)
Writing at 0x00044e2d... (22 %)
Writing at 0x0004a588... (25 %)
Writing at 0x0004f9e3... (29 %)
Writing at 0x00054e83... (32 %)
Writing at 0x00059fd1... (35 %)
Writing at 0x0005ef8e... (38 %)
Writing at 0x00063e24... (41 %)
Writing at 0x00068b7e... (45 %)
Writing at 0x0006de6f... (48 %)
Writing at 0x0007316c... (51 %)
Writing at 0x0007865a... (54 %)
Writing at 0x0007d877... (58 %)
Writing at 0x00082ba5... (61 %)
Writing at 0x00087bb8... (64 %)
Writing at 0x0008c978... (67 %)
Writing at 0x00091bb3... (70 %)
Writing at 0x000969fd... (74 %)
Writing at 0x0009beeb... (77 %)
Writing at 0x000a115e... (80 %)
Writing at 0x000a671e... (83 %)
Writing at 0x000ac109... (87 %)
Writing at 0x000b19b8... (90 %)
Writing at 0x000bb0cf... (93 %)
Writing at 0x000c1fd4... (96 %)
Writing at 0x000c7026... (100 %)
Wrote 756832 bytes (496550 compressed) at 0x00010000 in 12.4 seconds (effective 490.3 kbit/s)...
Hash of data verified.

Leaving...
 [SUCCESS] Took 18.77 seconds 

Process finished with exit code 0
=================================================
Here is my configuration information:
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.mcu = esp32s2
platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.0-alpha1

**Comment by Kevin-CEN** [comment]
Esp32s2 Run httpUpdata Example Serial port error ：
[SETUP] WAIT 4...
[SETUP] WAIT 3...
[SETUP] WAIT 2...
[SETUP] WAIT 1...
OTA...
blink...
E (11803) esp_image: image at 0x10000 has invalid magic byte (nothing flashed here?)
E (11805) esp_image: image at 0x10000 has invalid magic byte (nothing flashed here?)
[ 25154][E][HTTPUpdate.cpp:422] runUpdate(): Update.end failed! (Flash Read Failed)

[ 25155][E][HTTPUpdate.cpp:348] handleUpdate(): Update failed

HTTP_UPDATE_FAILED Error (3): Update error: Flash Read Failed
E (28722) esp_image: image at 0x10000 has invalid magic byte (nothing flashed here?)
[ 42638][E][HTTPUpdate.cpp:422] runUpdate(): Update.end failed! (Flash Read Failed)

[ 42639][E][HTTPUpdate.cpp:348] handleUpdate(): Update failed

**Comment by chegewara** [comment]
Maybe stupid question: did you maybe by accident OTA update with binary for other esp32 family, like S2 binary on old esp32?

**Comment by VojtechBartoska** [comment]
Hello @Kevin-CEN, do you still need help?

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable. 

If it's still needed, please reopen the issue.

Thanks for understanding.
