### ISSUE TITLE
TouchRead and TouchInterrupt examples doesn't work in ESP32-S2

### ISSUE THREAD

**Issue by FBSeletronica** [espressif/arduino-esp32#5745]
I'm trying to use TouchRead and TouchInterrupt examples on ESP32-S2 but they aren't working.

The examples are compiling but not working correctly. Analyzing the library I realized that it was not implemented for ESP32-S2.

Is anyone working on this implementation?

If not, I'll try to implement the code for ESP32-S2 and if I get a positive result I'll send a PR.

**Comment by me-no-dev** [comment]
it is on the roadmap, but we can always appreciate the help :)

**Comment by darianbjohnson** [comment]
So, I was able to get _wake from sleep_ and _interrupts while awake_ to work with touchpads on ESP32-S2 using codebase 2.0.0. I wrote the code in a h file in my Arduino program (leveraging some of the ESP-IDF examples). It's not elegant, but I can share if that helps. I might get around to updating the actual library if/when I get some time - though that probably won't be for a few months

**Comment by Johboh** [comment]
@darianbjohnson please share 😊!

**Comment by darianbjohnson** [comment]
Here you go. Good luck - [https://gist.github.com/darianbjohnson/268bff40ea72642dd2e05123ec5b8c40](https://gist.github.com/darianbjohnson/268bff40ea72642dd2e05123ec5b8c40)

**Comment by Johboh** [comment]
@darianbjohnson I just tried it and it works on my S2 mini board. Thanks!

**Comment by SuGlider** [comment]
This shall be solved with #6194 
New features, APIs and examples.
