### ISSUE TITLE
ESP.restart() does not always reset ESP32.

### ISSUE THREAD

**Issue by sblantipodi** [espressif/arduino-esp32#5752]
### Hardware:
Board:							ESP32 from D32 board from Lolin
Core Installation version:			1.0.6
IDE name:						Platformio (platform-espressif32 v.3.2.1)
LIB Used:                                                 no libs
Flash Frequency:					40Mhz
PSRAM enabled:                                      no
Upload Speed:					460800
Computer OS:                                         Windows 10 and Ubuntu 

### Description:
ESP.restart() does not always reset ESP32.
Sometimes it seems that it reset but then it does not boot and I need to manually use the reset button to make the ESP start again.

**Comment by TD-er** [comment]
What is connected to GPIO-0?

**Comment by sblantipodi** [comment]
@TD-er nothing. it seems that the problem happen if I write something to storage using LittleFS.

```
if (SPIFFS.begin()) {
    // SPIFFS.format();
    File configFile = SPIFFS.open("/" + filename, "w");
    if (!configFile) {
      helper.smartPrintln("Failed to open [" + filename + "] file for writing");
    }
    serializeJsonPretty(jsonDoc, Serial);
    serializeJson(jsonDoc, configFile);
    configFile.close();
    helper.smartPrintln("[" + filename + "] written correctly");
  } else {
    helper.smartPrintln(F("Failed to mount FS for write"));
  }
ESP.restart()
```

this code writes well things into Little FS but hangs ESP32 at the restart point.
ESP32 is restarted but then it does not boot until I manually press the reboot button.

**Comment by TD-er** [comment]
And if you close the filesystem first before calling the `ESP.restart()` ?

**Comment by sblantipodi** [comment]
latest IDF solved my problem
