### ISSUE TITLE
 platformio esp32 cannot find crt1-sim.o and _vectors.o

### ISSUE THREAD

**Issue by fBn0523** [espressif/arduino-esp32#5755]
### Hardware:
this is my ini file
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
board_build.f_cpu = 240000000L
monitor_speed =115200

platform_packages = 
   framework-arduinoespressif32 @  https://github.com/espressif/arduino-esp32.git

### Description:
I come from China please forgive me my poor engilsh 
When I use the latest ESP32 package, the compiler reports the following error, But I had to use the latest one to complete the new feature  .I beg your help

### Debug Messages:
```
c:/users/administrator/.platformio/packages/toolchain-xtensa32@2.50200.97/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find crt1-sim.o: No such file or directory
c:/users/administrator/.platformio/packages/toolchain-xtensa32@2.50200.97/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find _vectors.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\nodemcu-32s\firmware.elf] Error 1
```

**Comment by VojtechBartoska** [comment]
Thanks @atanisoft for fast feedback! :)

@fBn0523 Can I consider this as solved?

**Comment by lrlin5656** [comment]
@VojtechBartoska : I fixed the same problem pre your suggestion. Thanks :)
