### ISSUE TITLE
connect doesn't work with printer device

### ISSUE THREAD

**Issue by kickoune** [espressif/arduino-esp32#5759]
hello, i have project for customers.

```
 SerialBT.begin(pMyNamePt,true); 

      SerialBT.setPin(pCodePin);
      SerialBT.connect(pDeviceName);

      if (SerialBT.connected())
        Serial.println("connected bluetooth");
      else
        Serial.println("not connected bluetooth");
```

connect don't work with printer device for example but in branch arduino idf 4.2 in espressif it's work's.

an idea? project is stopped.

thank's for your response.

**Comment by VojtechBartoska** [comment]
Hello, 

as there was no answer in last 14 days, I'm **closing the issue as expired** to keep our backlog manageable. If it's still needed, please reopen the issue.

Thanks for understanding.
