### ISSUE TITLE
Missing Pin in 

### ISSUE THREAD

**Issue by Thro42** [espressif/arduino-esp32#576]
### Hardware:
Board:							Noduino Quantum
Core Installation/update date:			11/jul/2017
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
 I miss the definition of Port A1 and A2 in arduino-esp32/variants/quantum/pins_arduino.h

**Comment by lonerzzz** [comment]
@Thro42 Can you attach an example of what you are expecting to see in that file that is missing?

**Comment by Thro42** [comment]
As you can see in arduino-esp32/variants/quantum/pins_arduino.h, the definition of Port A1 and A2 is missing.
....
static const uint8_t A0 = 36;
static const uint8_t A3 = 39;
static const uint8_t A4 = 32;
static const uint8_t A5 = 33;
.....
As I known the full Mapping must be:
static const uint8_t A0 = 36;
**static const uint8_t A1 = 37;
static const uint8_t A2 = 38;**
static const uint8_t A3 = 39;
static const uint8_t A4 = 32;
static const uint8_t A5 = 33;

**Comment by copercini** [comment]
But there are no GPIO37 and 38 in Noduino quantum....
![Noduino quantum schematic](http://wiki.jackslab.org/images/Noduino-quantum-v0.8-sch.png)

**Comment by lonerzzz** [comment]
@Thro42 Did copercini answer your question or is additional information available to better describe the situation?

**Comment by copercini** [comment]
Since Noduino Quantum don't expose these pins and even if exposed they do not seem to work as ADC when connected to the 270pF sampling capacitors as described in https://espressif.com/sites/default/files/documentation/esp32_hardware_design_guidelines_en.pdf session 3.1.6
