### ISSUE TITLE
Compilation error from 1.0.6 to 2.0.0

### ISSUE THREAD

**Issue by Speedy2k** [espressif/arduino-esp32#5762]
I have some code that are compiling very well on 1.0.6 but trying to update to 2.0.0 and now i got this error:

exit status 1
'union arduino_event_info_t' has no member named 'disconnected'; did you mean 'eth_connected'?

the code is just to print the wifi disconnect reason:

```cpp

Serial.println(info.disconnected.reason);
```
Is there anything i do wrong here?

Thanx a lot!

**Comment by P-R-O-C-H-Y** [comment]
Hi @Speedy2k,
There is `wifi_sta_disconnected` in  `arduino_event_info_t`. Can you try this instead?
`Serial.println(info.wifi_sta_disconnected.reason);`
