### ISSUE TITLE
Getting Client IP Address

### ISSUE THREAD

**Issue by kamshory** [espressif/arduino-esp32#5766]
I make a program with ESP32 and WiFi (mode STA and AP). I will only allow client to access the web server if client connected to hot spot from ESP32 (not via Wifi where ESP32 connected to)

I make static IP for the ESP32. How to get the client IP address?

My project is https://github.com/kamshory/OTP-Mini

**Comment by jandrassy** [comment]
start the WebServer only for the SoftAP interface.
`server.begin(softApIP, port);`

**Comment by kamshory** [comment]
Thank you
