### ISSUE TITLE
Preferences vs EEPROM

### ISSUE THREAD

**Issue by programmer131** [espressif/arduino-esp32#578]
are they using same space in flash memory or different? is it possible to use both at same time?

**Comment by copercini** [comment]
They use different spaces in flash memory. So you can use Preferences (aka NVS), EEPROM and SPIFFS at the same time

**Comment by lonerzzz** [comment]
@programmer131 Does this answer your question? Can we close the issue?

**Comment by dhavals1212** [comment]
What exactly is the space for each? Max storage I can utilise?
