### ISSUE TITLE
WiFiClientSecure doesn't validate time and date for server certificate

### ISSUE THREAD

**Issue by mrdc** [espressif/arduino-esp32#5780]
Hello,

`WiFiClientSecure `doesn't validate time and date for server certificate: connection to a https server is established without setting proper time and date for ESP32 - after boot time is `1970-01-01T00:00:00Z`, server certificate is `2021-2022`, so it should be rejected by `WiFiClientSecure`.
Would be nice to have an option, to disable time and date validation if user needs it, but validate by default.

### Hardware:
Board:  ESP32 Wrover-B
Core Installation version:			2.0.0 (sha.44c1198)
IDE name:						Platform.io
Flash Frequency:					40Mhz
PSRAM enabled:                                    yes
Upload Speed:					460800
Computer OS:                                    Windows 10

### Description:
`WiFiClientSecure `doesn't validate time and date for server certificate.

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>
#include <WiFiClientSecure.h>

WiFiClientSecure net;

void setup() {
 net.setCACert(CA);
 net.setCertificate(cert);
 net.setPrivateKey(key);
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by VojtechBartoska** [comment]
Hello @mrdc, sorry for late reply. Are you able to test your issue on development version [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) to check if this is still valid? You can take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by VojtechBartoska** [comment]
Hello, 

as there was no answer in last 14 days, I'm **closing the issue as expired** to keep our backlog manageable. If it's still needed, please reopen the issue.

Thanks for understanding.
