### ISSUE TITLE
Arduino & ESP32 Download Tool

### ISSUE THREAD

**Issue by BoYi0126** [espressif/arduino-esp32#5793]
I want to upload program to esp32 by "ESP32 Download Tool 3.9.0", and I use Arduino IDE to develop.
So I used the bin-file generated by Arduino IDE to upload program by "ESP32 Download Tool",
but it was always restart.

### Hardware:
Chip:							ESP32-WROOM-32E (128Mbit)
Core Installation version:			1.06
IDE name:						Arduino IDE 1.8.15
Flash Frequency:					80Mhz
Upload Speed:					921600
Computer OS:                                        Windows 10

### Description:
I use ESP32 Download Tool to upload program into esp32, but esp32 would restart repeatedly.
I got the information of bin file from Arduino IDE console.
1.  C:\Users\username\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6/tools/partitions/boot_app0.bin  (Flash at 0xe000)
2. C:\Users\username\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6/tools/sdk/bin/bootloader_qio_80m.bin  (Flash at 0x1000)
3. C:\Users\username\AppData\Local\Temp\arduino_build_895119/mainApp.ino.bin  (Flash at 0x10000)
4. C:\Users\username\AppData\Local\Temp\arduino_build_895119/mainApp.ino.partitions.bin (Flash at 0x8000)

Btw,  I upload program by Arduino IDE first, and upload bin each to check which file casue restart.
Step1. Upload program by Arduino IDE
Step2. Upload bin-file by ESP32 Download Tool only one file
Step3. Check the esp32 status

I found the bootloader_qio_80m.bin is the reason, but I try 4 mode already(qio、dio、qout、dout).

### Debug Messages:
The following message is show form Arduino IDE monitor
```
rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
ets Jul 29 2019 12:21:46

```

Thanks for everyone!

**Comment by VojtechBartoska** [comment]
Hello, I'm closing this one as expired. If needed, open a new issue.
