### ISSUE TITLE
Build failed for esp32 (IDFGH-6079)

### ISSUE THREAD

**Issue by roysG** [espressif/arduino-esp32#5797]
Hi,
I am using latest idf(5.0.0) with esp32-arduino-lib-builder(latest)
The build is working great for esp32-s2 esp32-c3

For esp32 i get build fail with errors:

[1052/1315] Building C object es...ores/esp32/esp32-hal-timer.c.obj
FAILED: esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-timer.c.obj
/Users/roysabah/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -I/Users/roysabah/esp/esp32-arduino-lib-builder/build/config -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/variants/esp32 -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32 -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/ArduinoOTA/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/AsyncUDP/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/BLE/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/BluetoothSerial/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/DNSServer/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/EEPROM/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/ESP32/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/ESPmDNS/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/FFat/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/FS/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/HTTPClient/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/HTTPUpdate/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/LittleFS/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/NetBIOS/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/Preferences/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/RainMaker/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/SD_MMC/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/SD/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/SimpleBLE/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/SPIFFS/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/SPI/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/Ticker/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/Update/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/USB/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/WebServer/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/WiFiClientSecure/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/WiFi/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/WiFiProv/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/libraries/Wire/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/libb64 -I/Users/roysabah/esp/esp-idf/components/newlib/platform_include -I/Users/roysabah/esp/esp-idf/components/freertos/include -I/Users/roysabah/esp/esp-idf/components/freertos/include/esp_additions/freertos -I/Users/roysabah/esp/esp-idf/components/freertos/port/xtensa/include -I/Users/roysabah/esp/esp-idf/components/freertos/include/esp_additions -I/Users/roysabah/esp/esp-idf/components/esp_hw_support/include -I/Users/roysabah/esp/esp-idf/components/esp_hw_support/include/soc -I/Users/roysabah/esp/esp-idf/components/esp_hw_support/include/soc/esp32 -I/Users/roysabah/esp/esp-idf/components/esp_hw_support/port/esp32/. -I/Users/roysabah/esp/esp-idf/components/heap/include -I/Users/roysabah/esp/esp-idf/components/log/include -I/Users/roysabah/esp/esp-idf/components/lwip/include/apps -I/Users/roysabah/esp/esp-idf/components/lwip/include/apps/sntp -I/Users/roysabah/esp/esp-idf/components/lwip/lwip/src/include -I/Users/roysabah/esp/esp-idf/components/lwip/port/esp32/include -I/Users/roysabah/esp/esp-idf/components/lwip/port/esp32/include/arch -I/Users/roysabah/esp/esp-idf/components/soc/include -I/Users/roysabah/esp/esp-idf/components/soc/esp32/. -I/Users/roysabah/esp/esp-idf/components/soc/esp32/include -I/Users/roysabah/esp/esp-idf/components/hal/esp32/include -I/Users/roysabah/esp/esp-idf/components/hal/include -I/Users/roysabah/esp/esp-idf/components/hal/platform_port/include -I/Users/roysabah/esp/esp-idf/components/esp_rom/include -I/Users/roysabah/esp/esp-idf/components/esp_rom/include/esp32 -I/Users/roysabah/esp/esp-idf/components/esp_rom/esp32 -I/Users/roysabah/esp/esp-idf/components/esp_common/include -I/Users/roysabah/esp/esp-idf/components/esp_system/include -I/Users/roysabah/esp/esp-idf/components/esp_system/port/soc -I/Users/roysabah/esp/esp-idf/components/esp_system/port/public_compat -I/Users/roysabah/esp/esp-idf/components/esp32/include -I/Users/roysabah/esp/esp-idf/components/xtensa/include -I/Users/roysabah/esp/esp-idf/components/xtensa/esp32/include -I/Users/roysabah/esp/esp-idf/components/driver/include -I/Users/roysabah/esp/esp-idf/components/driver/esp32/include -I/Users/roysabah/esp/esp-idf/components/esp_pm/include -I/Users/roysabah/esp/esp-idf/components/esp_ringbuf/include -I/Users/roysabah/esp/esp-idf/components/efuse/include -I/Users/roysabah/esp/esp-idf/components/efuse/esp32/include -I/Users/roysabah/esp/esp-idf/components/vfs/include -I/Users/roysabah/esp/esp-idf/components/esp_wifi/include -I/Users/roysabah/esp/esp-idf/components/esp_event/include -I/Users/roysabah/esp/esp-idf/components/esp_netif/include -I/Users/roysabah/esp/esp-idf/components/esp_eth/include -I/Users/roysabah/esp/esp-idf/components/tcpip_adapter/include -I/Users/roysabah/esp/esp-idf/components/esp_phy/include -I/Users/roysabah/esp/esp-idf/components/esp_phy/esp32/include -I/Users/roysabah/esp/esp-idf/components/esp_ipc/include -I/Users/roysabah/esp/esp-idf/components/app_trace/include -I/Users/roysabah/esp/esp-idf/components/esp_timer/include -I/Users/roysabah/esp/esp-idf/components/spi_flash/include -I/Users/roysabah/esp/esp-idf/components/mbedtls/port/include -I/Users/roysabah/esp/esp-idf/components/mbedtls/mbedtls/include -I/Users/roysabah/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -I/Users/roysabah/esp/esp-idf/components/mdns/include -I/Users/roysabah/esp/esp-idf/components/console -I/Users/roysabah/esp/esp-idf/components/esp_adc_cal/include -I/Users/roysabah/esp/esp-idf/components/wifi_provisioning/include -I/Users/roysabah/esp/esp-idf/components/protocomm/include/common -I/Users/roysabah/esp/esp-idf/components/protocomm/include/security -I/Users/roysabah/esp/esp-idf/components/protocomm/include/transports -I/Users/roysabah/esp/esp-idf/components/nvs_flash/include -I/Users/roysabah/esp/esp-idf/components/nghttp/port/include -I/Users/roysabah/esp/esp-idf/components/nghttp/nghttp2/lib/includes -I/Users/roysabah/esp/esp-idf/components/fatfs/diskio -I/Users/roysabah/esp/esp-idf/components/fatfs/vfs -I/Users/roysabah/esp/esp-idf/components/fatfs/src -I/Users/roysabah/esp/esp-idf/components/wear_levelling/include -I/Users/roysabah/esp/esp-idf/components/sdmmc/include -I/Users/roysabah/esp/esp-idf/components/app_update/include -I/Users/roysabah/esp/esp-idf/components/bootloader_support/include -I/Users/roysabah/esp/esp-idf/components/spiffs/include -I/Users/roysabah/esp/esp-idf/components/openssl/include -I/Users/roysabah/esp/esp-idf/components/esp_hid/include -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/esp-rainmaker/components/esp_rainmaker/include -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/esp-rainmaker/components/qrcode/include -I/Users/roysabah/esp/esp-idf/components/esp_https_ota/include -I/Users/roysabah/esp/esp-idf/components/esp_http_client/include -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/esp_littlefs/src -I/Users/roysabah/esp/esp32-arduino-lib-builder/components/esp_littlefs/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=/Users/roysabah/esp/esp32-arduino-lib-builder=. -fmacro-prefix-map=/Users/roysabah/esp/esp-idf=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4-dev-3573-gfb24a2941c\" -DESP_PLATFORM -DARDUINO=10812 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD=\"ESP32_DEV\" -DARDUINO_VARIANT=\"esp32\" -DESP32 -MD -MT esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-timer.c.obj -MF esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-timer.c.obj.d -o esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-timer.c.obj -c /Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c
/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c: In function 'timerBegin':
/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c:236:16: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'int_ena'
         TIMERG1.int_ena.val &= ~BIT(timer->timer);
                ^
/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c:243:16: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'int_ena'
         TIMERG0.int_ena.val &= ~BIT(timer->timer);
                ^
/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c: In function 'timerAttachInterrupt':
/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c:286:20: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'int_ena'
             TIMERG1.int_ena.val &= ~BIT(timer->timer);
                    ^
/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c:293:20: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'int_ena'
             TIMERG0.int_ena.val &= ~BIT(timer->timer);
                    ^
/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c:330:20: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'int_ena'
             TIMERG1.int_ena.val |= BIT(timer->timer);
                    ^
/Users/roysabah/esp/esp32-arduino-lib-builder/components/arduino/cores/esp32/esp32-hal-timer.c:336:20: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'int_ena'
             TIMERG0.int_ena.val |= BIT(timer->timer);
                    ^
[1061/1315] Building C object es...d25519/ref10/ed25519_ref10.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by VojtechBartoska** [comment]
Hello, closing as it was created by compability issue btw versions. Now Arduino-esp32 core v2.0.2 and newer support ESP-IDF v4.4 for using Arduino as ESP-IDF Component.
