### ISSUE TITLE
WiFi AP Mode, clients can't authenticate or connect

### ISSUE THREAD

**Issue by davidkleng** [espressif/arduino-esp32#5806]
### Hardware:
Board:							ESP WROOM 32
Core Installation version:			latest from Platform.io
IDE name:						Platform.io
Flash Frequency:					40Mhz
Upload Speed:					115200
Computer OS:                                        Windows 10

### Description:

I have a Async Web Server with Web Sockets and LittleFS. When the ESP32 starts, I print the AP SSID, Password and IP, clients like a Tablet can connect to it. After some idle time, clients get disconnected from the network and can't reconnect. If i try to connect with a new client or forgeting the network and trying again, the error in the device is "Failed to authenticate" as if the password were wrong.
I can tell that the programm in the ESP32 is still running correctly but the WiFi as I have prints in the Serial port and the outputs continue to operate.

The error disapears when the ESP is restarted but come back after a some minutes runing. 

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>
#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiAP.h>
#include <esp_wifi.h>

void initWiFi_AP(bool useStaticIP = false)
{
    Serial.println("SETUP: WIFI AP SETUP");

    WiFi.mode(WIFI_AP);
    WiFi.softAPenableIpV6();

    Serial.println("SETUP: WIFI DISABLE POWER SAVE");
    Serial.println(esp_wifi_set_ps(WIFI_PS_NONE));

    Serial.print("AP NAME: ");
    Serial.println(APname.c_str());

    WiFi.setHostname(APname.c_str());
    WiFi.softAPsetHostname(APname.c_str());

    if (useStaticIP)
        WiFi.softAPConfig(APip, APgateway, APsubnet);

    while (!WiFi.softAP(APname.c_str(), APpass.c_str()))
    {
        Serial.println(".");
        delay(100);
    }

    delay(2000);

        Serial.println("");
        Serial.print("WIFI: Iniciado AP:\t");
        Serial.println(WiFi.softAPSSID());
        Serial.print("WIFI: IP address:\t");
        Serial.println(WiFi.softAPIP());
        Serial.print("WIFI: pass:\t\t");
        Serial.println(APpass.c_str());
}
```

### Debug Messages:

On the first connection, i got this messages in the serial output and everything works fine.

[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 16 - AP_STACONNECTED
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 18 - AP_STAIPASSIGNED

then if i leave the tablet connected, with the screen locked, when I unlock it and try to reload the web server page, after 1 or 2 minutes i get this:

[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 17 - AP_STADISCONNECTED

and inmediatly get kicked out of the WiFi AP. 

If i try to reconnect to the AP, no Serial messages and in the device i get "Authenticating" for a while, then stops trying. No connection.

If i delete the AP data from the Tablet and input the password again, the tablet shows that the "Password is incorrect" and its unnable to connect. No serial output.

**Comment by rv9c** [comment]
Experiencing a similar problem using AsyncWebServer. In addition, if you use AsyncWebServer after some time of use, the esp 32 module spontaneously reboots.

I did not notice this on older versions of the kernel. Updated to the extreme version and started ...

**Comment by davidkleng** [comment]
Still having problem with web server, ESP32 resets. 

[E][AsyncTCP.cpp:797] _flushWriteQueue(): socket 59 lwip_write() failed errno=104

**Comment by VojtechBartoska** [comment]
Hello @davidkleng, do you still face this issue on v2.0.3-RC1?

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable.

If it's still needed, please reopen the issue.

Thanks for understanding.
