### ISSUE TITLE
Nothing output if write 64 bytes to esp32c3 HWCDC

### ISSUE THREAD

**Issue by xmeow** [espressif/arduino-esp32#5815]
### Hardware:
Board:							ESP32C3 dev
Core Installation version:			master-git
IDE name:						Arduino IDE 1.8.16
Flash Frequency:					40Mhz
Upload Speed:					115200
USB CDC on boot:                                   Disabled
Computer OS:                                        Windows 10

### Description:
Please take look at the sketch below, Nothing output from uart terminal if chunk write of 64 bytes to hardware cdc . And there is no guarantee that all data reset in a single transfer.

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

#include <Arduino.h>

uint8_t buff[256];

void setup() {
  for (int i=0;i<256;i++){
    buff[i]= i;
  }
  Serial.begin(115200);
  USBSerial.begin();
}

void loop() {
  delay(1000);
  USBSerial.write(buff, 64); // nothing output 
  // USBSerial.write(buff, 63); // this works fine
  USBSerial.flush();
}
```

### Debug Messages:
```
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xd (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x484
load:0x403ce000,len:0x90c
load:0x403d0000,len:0x2398
SHA-256 comparison failed:
Calculated: 293bbd2824884ff8e9e6e9df6347ebe647177796efc2f665a6ef9cc4658c4d05
Expected: fb396d172fd068522c3ea62ba7387443250e7e77b119dfa86deae393d7661487
Attempting to boot anyway...
entry 0x403ce000

```

**Comment by xmeow** [comment]
Looks like that we meet the edge case here, both 63 and 65 bytes write works, or even a 1-byte write after a 64-byte write will release the endpoint from freezing.  I am using webserial and node-serial, but this happens to all terminal tools including putty and arduino ide. My application was ported from esp32s2 and assuming each interrupt reading is 64bytes aligned. Resolved by modifying the webserial reader app.

**Comment by chegewara** [comment]
Recently ive found similar case with S3. When host is sending device descriptor requests with 256 (multiple of 64) bytes S3 respond with 0 bytes.

**Comment by igrr** [comment]
The following code seems to work with ESP-IDF, writing 64 bytes per iteration. So the hardware is probably okay. Maybe we need to look into the difference between this and the equivalent Arduino code.

```c++
#include <stdio.h>
#include <unistd.h>
#include <assert.h>

void app_main(void)
{
    while(1) {
#define SIXTEEN_BYTES "0123456789abcdef"
        const char* data = SIXTEEN_BYTES SIXTEEN_BYTES SIXTEEN_BYTES SIXTEEN_BYTES;
        size_t len = fwrite(data, 1, 64, stdout);
        assert(len == 64);
        fflush(stdout);
        fsync(fileno(stdout));
        usleep(500000);
    }
}
```

**Comment by Spritetm** [comment]
Note that it's very likely this is a difference between OS handling of these packets. Did you try that code on a Win10 machine?

**Comment by me-no-dev** [comment]
@igrr not Arduino code issue. I have no issues on MacOS and @Spritetm has no issues on Linux.
