### ISSUE TITLE
In version 2.0.0 slow connection to Wifi hotspot in AP mode.

### ISSUE THREAD

**Issue by robertgregor** [espressif/arduino-esp32#5817]
Hi,
I have installed the v 2.0.0. Till this version, the connection to my WiFi network took around 600 ms.
After installation of the 2.0.0 version, the connection to wifi take around 2.5 seconds !!!
BTW I am using static IP assignment and passing it using WiFi.config() - see the log.
Here is the log:

[    71][D][WiFiGeneric.cpp:808] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   167][V][WiFiGeneric.cpp:272] _arduino_event_cb(): STA Started
[   168][D][WiFiGeneric.cpp:808] _eventCallback(): Arduino Event: 2 - STA_START
[   168][V][WiFiGeneric.cpp:96] set_esp_interface_ip(): Configuring Station static IP: 192.168.1.150, MASK: 255.255.255.0, GW: 192.168.1.1
[  2365][V][WiFiGeneric.cpp:284] _arduino_event_cb(): STA Connected: SSID: Bob, BSSID: 98:da:c4:38:f4:8a, Channel: 11, Auth: WPA2_PSK
[  2366][D][WiFiGeneric.cpp:808] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  2368][V][WiFiGeneric.cpp:294] _arduino_event_cb(): STA Got New IP:192.168.1.150
[  2381][D][WiFiGeneric.cpp:808] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  2388][D][WiFiGeneric.cpp:857] _eventCallback(): STA IP: 192.168.1.150, MASK: 255.255.255.0, GW: 192.168.1.1

**Comment by VojtechBartoska** [comment]
Hello @robertgregor, sorry for answering late. Are you able to test your code under v2.0.3-RC1? Thanks!

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable.

If it's still needed, please reopen the issue.

Thanks for understanding.
