### ISSUE TITLE
How use I2S to read multiple ADC channel?

### ISSUE THREAD

**Issue by IamMrUnderstand** [espressif/arduino-esp32#5835]
Hi,

I want to read  read multiple ADC channel by using I2S

like this
```c
  static const adc_i2s_pattern_t adc_i2s_pattern[] = {
    {.atten = ADC_ATTEN_DB_11, .bits = ADC_WIDTH_BIT_12, .channel = ADC1_CHANNEL_0},
    {.atten = ADC_ATTEN_DB_11, .bits = ADC_WIDTH_BIT_12, .channel = ADC1_CHANNEL_3},
    {.atten = ADC_ATTEN_DB_11, .bits = ADC_WIDTH_BIT_12, .channel = ADC1_CHANNEL_4},
    {.atten = ADC_ATTEN_DB_11, .bits = ADC_WIDTH_BIT_12, .channel = ADC1_CHANNEL_5},
    {.atten = ADC_ATTEN_DB_11, .bits = ADC_WIDTH_BIT_12, .channel = ADC1_CHANNEL_6},
    {.atten = ADC_ATTEN_DB_11, .bits = ADC_WIDTH_BIT_12, .channel = ADC1_CHANNEL_7}
  };
```

and it seems didn't implement in Arduino IDE
Does there have any other ways to read multiple channel by I2S in Arduino IDE?

**Comment by me-no-dev** [comment]
what you show is IDF API and not Arduino. If it works in IDF, there is no reason for it not to work in Arduino.

BTW there is an issue template that you should have filled. It is not clear what version you are using and so on.
