### ISSUE TITLE
BLE Device: disconnect all existing connections when only one device disconnected

### ISSUE THREAD

**Issue by tientu0001** [espressif/arduino-esp32#5843]
Hardware:
Board: ESP32 Dev Module
IDE name: Arduino IDE
Flash Frequency: 80Mhz
OS: Windows 10

Description:
I use example BLE_Client and custom, now i use 3 ble client will scan and connect to 3 ble server. All works excellent
But when one ble server disconnected, so all all existed connections was disconnected too.

Debug:
23:19:02.359 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
23:19:02.359 -> [D][BLEClient.cpp:165] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
23:19:02.359 -> [D][BLEClient.cpp:146] disconnect(): >> disconnect()
23:19:02.359 -> [D][BLEClient.cpp:152] disconnect(): << disconnect()
23:19:02.359 -> [I][BLEDevice.cpp:610] removePeerDevice(): remove: 0, GATT role client
23:19:02.359 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 5] ... Unknown
23:19:02.406 -> [D][BLEClient.cpp:165] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 5] ... Unknown
23:19:02.406 -> [D][BLEClient.cpp:146] disconnect(): >> disconnect()
23:19:02.406 -> [D][BLEClient.cpp:152] disconnect(): << disconnect()
23:19:02.406 -> [I][BLEDevice.cpp:610] removePeerDevice(): remove: 1, GATT role client
23:19:02.406 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 5] ... Unknown
23:19:02.406 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 6] ... Unknown
23:19:02.406 -> [D][BLEClient.cpp:165] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 6] ... Unknown
23:19:02.453 -> [D][BLEClient.cpp:146] disconnect(): >> disconnect()
23:19:02.453 -> [D][BLEClient.cpp:152] disconnect(): << disconnect()
23:19:02.453 -> [I][BLEDevice.cpp:610] removePeerDevice(): remove: 2, GATT role client
23:19:02.453 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
23:19:02.453 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
23:19:02.453 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 5] ... Unknown
23:19:02.500 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 6] ... Unknown
23:19:02.500 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
23:19:02.500 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 5] ... Unknown
23:19:02.500 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 6] ... Unknown
23:19:02.500 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 6] ... Unknown
23:19:02.540 -> [D][BLEDevice.cpp:151] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 6] ... Unknown

![z2903239480591_b41eb24e61a13262ea1633f67ec7d83d](https://user-images.githubusercontent.com/17722577/140102617-e54dfa87-f4c7-402d-a5c7-763354549248.jpg)

**Comment by P-R-O-C-H-Y** [comment]
Hi, please can you add more info from issue template?
`Arduino-esp32 version`
`Sample of code / sketch`
Thanks

**Comment by P-R-O-C-H-Y** [comment]
@tientu0001 Can you add more info that I asked before?
