### ISSUE TITLE
reading error SPI  value after connect Wifi

### ISSUE THREAD

**Issue by dungdao191299** [espressif/arduino-esp32#5852]
I'm trying use ESP32 read SPI from ADC module  to read analog value with high resolution and high sampling rate (about 5000 samples in 1s) for my energy monitoring project. After that i use WiFi to publish payload via MQTT. But after connected to WiFi, ESP32 received error value. I'm pretty sure the reason is at the Wifi library because if i don't connect wifi, ESP32 received correct value:

![3](https://user-images.githubusercontent.com/54898195/140485058-f583f4ca-6945-489a-9395-424791e4db6b.png)

**Comment by atanisoft** [comment]
Pretty sure this will not get anywhere as there is no code example or steps to reproduce.

**Comment by VojtechBartoska** [comment]
@dungdao191299 Can you please provide more info?
