### ISSUE TITLE
[Docs] Writing a new Arduino documentation about GPIO

### ISSUE THREAD

**Issue by halyssonJr** [espressif/arduino-esp32#5855]
### Summary:
Writing a new Arduino documentation about GPIO

### Impact:
None

@pedrominatel

**Comment by pedrominatel** [comment]
Thanks, @halyssonJr for taking this task!

Please, follow the same format and style as the other libraries. You can use as reference:

https://docs.espressif.com/projects/arduino-esp32/en/latest/api/i2c.html
and
https://docs.espressif.com/projects/arduino-esp32/en/latest/api/wifi.html

**Comment by halyssonJr** [comment]
Ok, @pedrominatel.

**Comment by halyssonJr** [comment]
@pedrominatel, submit PR  #5894 !

**Comment by pedrominatel** [comment]
Please, fix the issues on this PR that I already mentioned there.

**Comment by VojtechBartoska** [comment]
Closing as PR was merged already.
