### ISSUE TITLE
16 MB esp32 Wrover HIMEM

### ISSUE THREAD

**Issue by marchingband** [espressif/arduino-esp32#5857]
I use the ESP32 WROVER-B 16MB in an audio board that I released on Kickstarter this year, and I would like to someday make use of all that PSRAM, and allow my users to take advantage of the huge potential that it offers, while working in the Arduino IDE. 
Is there a roadmap, or any hope of getting access to it, like I would in the esp-idf?

Ideally I would like to be able to use the esp-idf himem api.

thanks!

**Comment by me-no-dev** [comment]
- Select the Wrover board in the board menu
- Use SPIFFS
- Access himem through the IDF API
