### ISSUE TITLE
ESP_ARDUINO_VERSION_PATCH not updated by build script in 2.0.1-RC1 and 2.0.1

### ISSUE THREAD

**Issue by tobozo** [espressif/arduino-esp32#5864]
Hello,

The new `ESP_ARDUINO_VERSION ` macro can't be used yet to distinguish 2.0.0 from 2.0.1-RC1 and 2.0.1.

Something is probably missing in the build scripts to increment the values.

![image](https://user-images.githubusercontent.com/1893754/140921537-8791f32a-71d7-4f3d-ab4f-f0a17be87da7.png)

![image](https://user-images.githubusercontent.com/1893754/140921502-18aa45bd-99d2-4717-90fb-bf975ece19d1.png)

[edit]

I'm using this macro to distinguish versions:

```C
#if defined ESP_ARDUINO_VERSION_VAL
  #if __has_include("core_version.h") // for platformio
    #include "core_version.h"
  #endif
  #if ESP_ARDUINO_VERSION_VAL(2,0,1) >= ESP_ARDUINO_VERSION || ARDUINO_ESP32_GIT_VER == 0x15bbd0a || ARDUINO_ESP32_GIT_VER == 0xd218e58f || ARDUINO_ESP32_GIT_VER == 0xcaef400f
    #pragma message "Filesystem can create subfolders on file creation"
    #define FS_CAN_CREATE_PATH
  #endif
#endif
```

[edit] updated snippet with 2.0.2 git version

**Comment by Tomat7** [comment]
The same issue on 2.0.2 :-(

**Comment by VojtechBartoska** [comment]
Hi, @Tomat7 and @tobozo we will fix this in 2.0.3. Adding the milestone.

**Comment by tobozo** [comment]
@me-no-dev @VojtechBartoska 

it's remotely related but none of the bundled libraries that were recently modified had their version number increased in their respective library.properties file either 

e.g. SD.h and Wire.h are still at 2.0.0

**Comment by me-no-dev** [comment]
@tobozo are those versions used somewhere?

**Comment by tobozo** [comment]
@me-no-dev those version numbers are visible in the Arduino IDE compilation recap so there's at least an added value for debugging.

It's also a good signal when one of the bundled libraries has changed e.g. SimpleBLE is unchanged since arduino-esp32-2.0.0 whereas BlueToothSerial received changes for arduino-esp32-2.0.2, would it make sense to synchronize the version numbers of the modified libraries with their respective arduino-esp320xxx version instead of using semver?

I know  platformio can to pick one particular version, for example it made the difference when SD.h was bumped to 2.0.0 even though no code in the library was changed.

**Comment by drws** [comment]
@VojtechBartoska If you're fixing this one, please also consider the related and partly overlapping #5536. It is currently tagged for 2.1.0, but it makes sense to fix these two at once. Thanks!

**Comment by VojtechBartoska** [comment]
This issue was closed by merging S3 support into master branch.
