### ISSUE TITLE
Rollback with Arduino as ESP-IDF Component

### ISSUE THREAD

**Issue by GKFernandes** [espressif/arduino-esp32#5871]
Hello everyone,

I ran into the same issue as stated in: espressif/arduino-esp32#3318 and also in espressif/arduino-esp32#3749

I think this issue about the weakly defined verify0ta() should be fixed and made in such a way that the user can perform the verification later in the code instead of inside the initArduino() function.

**Comment by me-no-dev** [comment]
How about we add a new weak function `bool verifyRollbackLater()` to allow you to skip verification in `initArduino` and do it yourself later?

**Comment by GKFernandes** [comment]
Hello @me-no-dev , I think this could be a solution, but can the function verifyOta() just be removed?

What do you think @atanisoft @marcovannoord?

**Comment by marcovannoord** [comment]
Yeah that would be a perfect solution i think, and it would just skip the verifyOTA() function.
In that case, if users want to use the verifyOTA to immediately verify rollback, then they can still use that function if they override the weak function.

**Comment by me-no-dev** [comment]
if you overwrite `verifyRollbackLater`, then `verifyOTA` will not be called at all. This whole block will not execute: https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-misc.c#L215-L226

**Comment by marcovannoord** [comment]
Yeah i think that's the perfect solution. That way, users can add this feature, while keeping legacy things intact.

**Comment by me-no-dev** [comment]
Done :)

**Comment by zekageri** [comment]
Any example for this?
