### ISSUE TITLE
WiFiProv BLE Not Working

### ISSUE THREAD

**Issue by rsmck** [espressif/arduino-esp32#5885]
### Hardware:
Board:							ESP32
Core Installation version:			2.0.1
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                   no
Upload Speed:					921600
Computer OS:                                       macOS 

### Description:
WiFiProv simply doesn't seem to work for me at all.

When using the sample Sketch https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino the BLE doesn't appear within the ESPRESSIF app.

On one occasion it appeared, but as Prov_123 despite a different value set in the `WiFiProv.beginProvision()` call.

Using another BLE explorer app like LightBlue showed the device advertising `prov-scan`, `prov-session`, `prov-config`, `prov-ver` but it seems impossible to actually provision using the ESP tools.

It's also worth noting I ran `esp_tool.py erase_flash` to ensure no old data remained but the same behaviour resulted after reflashing, I also tried with a different ESP32 board.

### Sketch: 

(The void SysProvEvent(arduino_event_t *sys_event) {} is as https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino)

```cpp
void setup() {
  Serial.begin(115200);
  WiFi.onEvent(SysProvEvent);
  WiFiProv.beginProvision(WIFI_PROV_SCHEME_BLE, WIFI_PROV_SCHEME_HANDLER_FREE_BTDM, WIFI_PROV_SECURITY_1, "ATLN3915", "HA123");
}
```

### Debug Messages:
```
[�HH⸮⸮0][D][esp32-hal-cpu.c:211] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[    21][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 0 - WIFI_READY
[    21][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 33 - PROV_INIT
[    24][I][WiFiProv.cpp:142] beginProvision(): Starting AP using BLE. service_name : HA123, pop : ATLN3915
[   117][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 2 - STA_START
[   525][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 35 - PROV_START

Provisioning started
Give Credentials of your access point using " Android app "
```

However the app (tried both iOS and Android) doesn't see it at all.

**Comment by coderforlife** [comment]
I am also having this issue on the ESP32-C3 chip. I have tried iOS. The LightBlue app asks for approval to use Bluetooth services while the ESP app does not. It seems the ESP app isn't using Bluetooth at all? This is sounding more like an issue to https://github.com/espressif/esp-idf-provisioning-ios/tree/master/ESPProvision

**Comment by coderforlife** [comment]
Check out https://github.com/espressif/esp-idf-provisioning-ios/issues/35 (at least for iOS).

**Comment by VojtechBartoska** [comment]
Hello, can you please test this with 2.0.3-RC1 version?

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable.

If it's still needed, please reopen the issue.

Thanks for understanding.
