### ISSUE TITLE
Erase Flash options are missing from Tools menu for ESP32 Dev Module (and others?)

### ISSUE THREAD

**Issue by daxliniere** [espressif/arduino-esp32#5902]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.6
IDE name:						Arduino IDE
Flash Frequency:					80Mhz
PSRAM enabled:                                     no
Computer OS:                                         Windows 10

### Description:
For ESP8266 devices, we have Erase Flash options in the Tools menu. These are not present when using my ESP-WROOM-32 (38-pin dev module) and potentially other ESP32 boards.

Issue was reported [here](https://www.esp32.com/viewtopic.php?t=20621), ESP_Sprite suggested logging a bug report here.

**Comment by daxliniere** [comment]
Any news on this?

Happy holidays!

**Comment by VojtechBartoska** [comment]
Hello, not yet. We will take a look on this soon and let you know about our resolution.

**Comment by daxliniere** [comment]
Thank you, Vojtech! 😊

**Comment by DanielMarcato** [comment]
This needs higher priority!

**Comment by lbernstone** [comment]
I know it doesn't say "Erase flash", but this works.
Tools->Programmer->Esptool
Burn Bootloader

**Comment by PilnyTomas** [comment]
HI, can you please give an example of which boards do have this option, and where is it located on the menu?

**Comment by daxliniere** [comment]
> HI, can you please give an example of which boards do have this option, and where is it located on the menu?

It's all there in the original post, Pilny :)

**Comment by lbernstone** [comment]
I think this was added in 2.0.2
https://github.com/espressif/arduino-esp32/blob/master/platform.txt#L226-L233

**Comment by daxliniere** [comment]
> I think this was added in 2.0.2 https://github.com/espressif/arduino-esp32/blob/master/platform.txt#L226-L233

Thanks @lbernstone, I can't seem to see a 2.0.2 pre or public release online. The Arduino site has 2.0.0 rc9 plus the nightly builds (which have no version number)
