### ISSUE TITLE
S3 support

### ISSUE THREAD

**Issue by wxzed** [espressif/arduino-esp32#5914]
When will s3 support

**Comment by chegewara** [comment]
When its ready.

**Comment by wxzed** [comment]
Is there an approximate time?

**Comment by igrr** [comment]
Hi @wxzed, please follow the link to https://github.com/espressif/arduino-esp32/issues/5594 and click "subscribe" there to get notified about S3 support progress.

@chegewara I appreciate you helping respond to Github issues, your comments are generally very helpful! I kindly ask you to keep making constructive comments in the future, or ignore the issue if you don't see a way to respond constructively.

**Comment by chegewara** [comment]
Constructive response:
- please use search:
- https://github.com/espressif/arduino-esp32/issues?q=is%3Aissue+s3+support+is%3Aclosed
