### ISSUE TITLE
SD card only mounts when connected to and programmed from a specific PC

### ISSUE THREAD

**Issue by brahmajit** [espressif/arduino-esp32#5922]
I've a custom PCB with ESP32 Wroom 32 and SD module. When trying to mount the SD card (using the default ESP32 sd_test sketch) the card mount fails only when it's connected to one of my two laptops and stays so. I've to connect and reprogram from the other computer to get the SD card working.

I've no clue what could be the issue here. Mind you the PCB, the USB cable all remains the same.

**Comment by VojtechBartoska** [comment]
Hello @brahmajit, can you please test this with v2.0.3-RC1? Thanks!

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable.

If it's still needed, please reopen the issue.

Thanks for understanding.
