### ISSUE TITLE
Webserver - How respond to HTTP POST request?

### ISSUE THREAD

**Issue by DeepSheth01** [espressif/arduino-esp32#593]
I want to make a web server on my ESP32 that can host a HTML form and can submit data using POST method. Can anybody give me any idea how to do that with some sample code?

**Comment by copercini** [comment]
Like this?
https://github.com/bbx10/WebServer_tng/tree/master/examples

**Comment by DeepSheth01** [comment]
Yes thanks! Got it working with [WebServer_tng](https://github.com/bbx10/WebServer_tng/tree/master/examples) library, but I guess there is no way of doing the same with official Webserver library.

**Comment by bot1131357** [comment]
Not sure if anyone is still looking, but POST data can be retrieved with the String arg(String name) method as below:
```
void handlePost() {
	Serial.print("Data: ");
	Serial.println(server->arg("myData1"));
	Serial.print("Data: ");
	Serial.println(server->arg("myData2"));
}
```
Hope this helps.

**Comment by pcbtborges** [comment]
bot1131357, what library are you talking about?
Thanks

**Comment by bot1131357** [comment]
Just the WebServer from arduino-esp32. Here's a [link](https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer/examples) to the examples.
