### ISSUE TITLE
[QUESTION] Uninitialized WiFI/BT are powered or not powered?

### ISSUE THREAD

**Issue by garageeks** [espressif/arduino-esp32#5964]
I was unable to find a conclusive answer about this, so I ask here:

I have a simple application where I won't use the radio at all, but using ESP32 chip for future upgrades where I might use it.

If I don't initialize radio, i.e. not including Wi-Fi and Bluetooth libraries, are the hardware modules unpowered?

OR do I need to include libraries and explicitly turn radio off for both Wi-Fi and Bluetooth, like below?

Thanks for the clarification

```
#include "WiFi.h" 
#include <esp_wifi.h>
#include <esp_bt.h>


void switchOff()
{
  Serial.println("Switch off radio...");
  WiFi.disconnect(true);
  WiFi.mode(WIFI_OFF);
  btStop();

  esp_wifi_stop();
  esp_bt_controller_disable();

}
```

**Comment by VojtechBartoska** [comment]
Closing as answered.
