### ISSUE TITLE
MDNS.begin(hostname) including uppercase letters will not work

### ISSUE THREAD

**Issue by euquiq** [espressif/arduino-esp32#597]
I have a nicely working web server inside my ESP32.  I am using MDNS so it can be easily discovered by different web browsers over my LAN. I discovered the following (bug ?): 

`void mymdns() {
	char myhostname[] = "Esp32";
	if (!MDNS.begin(myhostname)) {
		while (1) {
			delay(1000);
		}
	}
	MDNS.addService("http", "tcp", 80); 
}`

If hostname includes any uppercase letters, i.e.  char myhostname[] = "Esp32"; then later when I type http://Esp32.local as an URL in any web browser, such url is automatically converted into lowercase (http://esp32.local) ... while my Esp32 mDNS server seems to broadcast it as originally typed (with uppercase letters included) .  

So "Esp32" as hostname won't work, but if I edit that string into "esp32" (all lowercase) it will.

This behavior may be by design, but it is to note that inside the older ESP8266 mDNS library, this situation was taken into account (so the above code would work just fine). 

If I correctly recall, ESP8266 mDNS library automatically converts the HostName into lowercase, so this kind of situations are handled automatically by it.

Regards,

Enrique

**Comment by me-no-dev** [comment]
big update to mdns is coming and this is included in it :) hang tight
