### ISSUE TITLE
esp32 multicast example stops working

### ISSUE THREAD

**Issue by nhatuan84** [espressif/arduino-esp32#6002]
Hello

I try to make an example using WiFiUDP multicast and it is not working.
Then I just run AsyncUDPMulticastServer/AsyncUDPMulticastServer.ino example. And it is still not working.

Please support.

**Comment by VojtechBartoska** [comment]
Hello, due to no answer I'm closing this issue as expired.

If you still need help, please reopen it.

Thanks for understanding!
