### ISSUE TITLE
Arduino-ESP32-S3

### ISSUE THREAD

**Issue by Carol-001** [espressif/arduino-esp32#6071]
### Related area

Arduino

### Hardware specification

ESP32-S3-Devkitc-1

### Is your feature request related to a problem?

目前Arduino 还没有支持ESP32-S3，预计什么时间可以支持S3

### Describe the solution you'd like

或者有没有测试版的demo，可以使Arduino支持ESP32-S3

**Comment by Miraculix200** [comment]
There is no date yet. Maybe they want to wait for ESP-IDF 4.4 being the stable release, before they add it to Arduino.

**Comment by me-no-dev** [comment]
duplicate
