### ISSUE TITLE
ESP32 Devkit v1 not recognized by PC after blink test (Platform IO)

### ISSUE THREAD

**Issue by scarecrow2k6** [espressif/arduino-esp32#6074]
### Board

ESP32 DEVKIT V1

### Device Description

It is a bare bone ESP32 DEVKIT V1.

### Hardware Configuration

No

### Version

v2.0.1

### IDE Name

Platform IO

### Operating System

Windows 11

### Flash frequency

Don't know

### PSRAM enabled

no

### Upload speed

96000 (probably)

### Description

I found out about Platform IO recently and wanted to give it a shot. Set everything up accordingly and loaded a blink sketch and uploaded. The pin was 2 (onboard LED I believe). After uploading and the auto reset after upload, it did nothing. So I disconnected and connected again. Now the board is not recognized by the PC. Nothing shows up on comport on device manager (using win11). The power light on the ESP32 lights up but that is pretty much it. Help would be much appreciated, thanks.

UPDATE: After holding BOOT + EN, the pc recognizes the COM port but if I try to write a sketch, it fails and the board vanishes from COM port.

### Sketch

```cpp
int LED_BUILTIN = 2;
void setup() {
pinMode (LED_BUILTIN, OUTPUT);
}
void loop() {
digitalWrite(LED_BUILTIN, HIGH);
delay(1000);
digitalWrite(LED_BUILTIN, LOW);
delay(1000);
}
```

### Debug Message
I don't have the original debug message. This is what I got after BOOT + EN and the COM port showing up.

```plain
Sketch uses 198842 bytes (15%) of program storage space. Maximum is 1310720 bytes.
Global variables use 13248 bytes (4%) of dynamic memory, leaving 314432 bytes for local variables. Maximum is 327680 bytes.

--------------------------
Compilation complete.
esptool.py v3.0-dev
Serial port COM3
Connecting...
Traceback (most recent call last):
  File "esptool.py", line 3682, in <module>
  File "esptool.py", line 3675, in _main
  File "esptool.py", line 3330, in main
  File "esptool.py", line 512, in connect
  File "esptool.py", line 492, in _connect_attempt
  File "esptool.py", line 431, in sync
  File "esptool.py", line 362, in command
  File "site-packages\serial\serialutil.py", line 352, in timeout
  File "site-packages\serial\serialwin32.py", line 222, in _reconfigure_port
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: WindowsError(433, 'A device which does not exist was specified.')
Failed to execute script esptool
Upload error: Failed uploading: uploading error: exit status 4294967295
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hi, probably problem with your environment setup. PlatfromIO doesn't support v2.0.0 and latest versions out of the box.

Take a look here for a workaround: https://github.com/platformio/platform-espressif32/issues/619
