### ISSUE TITLE
SD.h: rename File and/or copy File

### ISSUE THREAD

**Issue by dsyleixa** [espressif/arduino-esp32#6080]
### Related area

SD.h

### Hardware specification

for either ESP32 plus SD slot

### Is your feature request related to a problem?

I am missing a certain SD card <SD.h> functionality

### Describe the solution you'd like

similar to 
#include <SD.h>
File myFile; 
SD.remove("example.txt");

now additionally:

int SD.rename("example.txt", "newname.txt");
and
int SD.copy("example.txt", "newname.txt");

Return value
If the file is successfully renamed or copied, a zero value is returned.
On failure, a nonzero value has to be returned.
Perhaps, an errno variable is also set to a system-specific error code on failure.

### Describe alternatives you've considered

nothing similar found

**Comment by dsyleixa** [comment]
no, rename does not create a 2nd file additionally, it just renames the 1 and only existing one. 
So the copy command still needs to be impemented.

**Comment by me-no-dev** [comment]
@dsyleixa `copy` is not part of Arduino SD/FS API. The reason is that there are different types of `copy` and is not necessary that the destination is on the same volume/filesystem as the source, so you should `copy` the data yourself. Just open the source for reading, the destination for writing and manually read/write from one to the other.

**Comment by dsyleixa** [comment]
that is what has to be simplified for file copies on the same SD.
e.g.
copy( /Seamus.txt, /backup/Floyd.txt);

**Comment by prof955** [comment]
i don't understand why they refuse to understand what is needed. its "copy" guys. very very normal thing to ask. 
I am new to Fs library please tell me if i am missing comething. But what @dsyleixa is asked very normal. I encountered same need for eg. and let me tell you many people are looking for the same thing. Rename as you @P-R-O-C-H-Y say is jusr deleting the original file. creating destination with same content and deleting original file. Why we can't have a "copy" ?? please explain me as i am 5yo.

why we can't have this as a very easy tihng: 
e.g.
copy( "/Seamus.txt", "/backup/Floyd.txt"); ----> "Seamus.txt" will not be removed from the folder. just "Floyd.txt" will be created.

at this point i can't believe that i am explaing how copy works :D this means i am definetly missing something
or this is very very hard to do so no one wants to add to library. this normal too.
