### ISSUE TITLE
请问怎么使用串口中断功能？

### ISSUE THREAD

**Issue by zouzhe1** [espressif/arduino-esp32#6085]
### Board

esp32模块

### Device Description

devkitc v4

### Hardware Configuration

不需要

### Version

v2.0.1

### IDE Name

platformio

### Operating System

win10

### Flash frequency

40M

### PSRAM enabled

no

### Upload speed

115200

### Description

请问怎么使用串口中断，因为我看arduino官方的串口中断是假的，每次要在loop()函数执行后才执行event函数内容。那么我们esp32应该怎么使用硬件串口中断？不要假的！

### Sketch

```cpp
不需要
```

### Debug Message

```plain
不需要
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
@zouzhe1 Please rewrite your issue into English, it's the main language of this repository.
