### ISSUE TITLE
Static IP(AP_STA

### ISSUE THREAD

**Issue by akaneko1019** [espressif/arduino-esp32#609]
I want to fix IP addresses in the ESP-WROOM-32.
Believe in the station and access point mode and want to fix.
But do not know where samples are not for specifically what to do.
So tell me is hope. Thank you in advance.

**Comment by copercini** [comment]
Here it is https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiClientStaticIP/WiFiClientStaticIP.ino
=)
