### ISSUE TITLE
Ticker::active() is declared but not implemented.

### ISSUE THREAD

**Issue by everslick** [espressif/arduino-esp32#6097]
### Board

ALL

### Device Description

NONE

### Hardware Configuration

NO

### Version

latest master

### IDE Name

NONE

### Operating System

GNU/Linux

### Flash frequency

40Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

see title

### Sketch

```cpp
Ticker t;

bool act = t.active();
```

### Debug Message

```plain
undefined reference to `Ticker::active()'
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by everslick** [comment]
https://github.com/espressif/arduino-esp32/pull/5919

**Comment by VojtechBartoska** [comment]
Hi @everslick, what's the purpose of this issue? Seems to me it can be discussed directly in mentioned PR above.

**Comment by everslick** [comment]
I posted it, before I found the PR, I'm fine with closing the issue.

**Comment by VojtechBartoska** [comment]
Oki, nevermind. We can move to the PR then. Thanks for your contribution.
