### ISSUE TITLE
Unable to set hostname

### ISSUE THREAD

**Issue by sorscode** [espressif/arduino-esp32#61]
First off, great work on the Arduino Core.

On the ESP8266, I'm able to set the hostname of the of ESP via:
WiFi.hostname(myhostname);

However this does not work on the ESP32.
I do have the ArduinoJSON library and the PubSubClient library working, to do basic PWM on Meanwell LDD LED drivers.

**Comment by me-no-dev** [comment]
https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/include/tcpip_adapter/tcpip_adapter.h#L386
API was added in the last commit of IDF changes, but has not made it into the Arduino classes yet

**Comment by me-no-dev** [comment]
see https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiIPv6/WiFiIPv6.ino#L78 for setting hostname

**Comment by jeroenst** [comment]
wifi.setHostname("hostname");
