### ISSUE TITLE
U2TXD (IO17) No longer functions using Serial2 on version 2.0.2 

### ISSUE THREAD

**Issue by JonGordon123** [espressif/arduino-esp32#6112]
### Board

ESP32 Wroom-32D

### Device Description

Sparkfun ESP32 Thing Plus

### Hardware Configuration

No

### Version

latest master

### IDE Name

Arduino 1.8.19

### Operating System

Win10

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

When using 2.0.2, the Serial2 TX pin (IO17) does not seem to transmit. The RX pin seems to still work.
When rolling back to 1.0.6 everything works as expected.

### Sketch

```cpp
void setup() {
  Serial.begin(115200);
  Serial2.begin(9600, SERIAL_8N1, 16, 17);
}

void loop() {
  Serial.println("Test");
  Serial2.println("Hello");
  delay(500);
  while(Serial2.available()){
    Serial.print(char(Serial2.read()));
  }
  delay(500);
}
```

### Debug Message

```plain
NA
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello, can you please retest this on v2.0.3-rc1?

**Comment by VojtechBartoska** [comment]
Hi,

I'm closing the issue due to no response. 

If needed you can reopen it. 

Thanks for your contribution & understanding!
