### ISSUE TITLE
Using pre-compiled libraries fails during link

### ISSUE THREAD

**Issue by rei-vilo** [espressif/arduino-esp32#6121]
### Board

ESP32-DevKitC

### Device Description

ESP32-DevKitC

### Hardware Configuration

N/A

### Version

v1.0.6

### IDE Name

Arduino IDE A.8.6

### Operating System

N/A

### Flash frequency

N/A

### PSRAM enabled

no

### Upload speed

N/A

### Description

Using pre-compiled libraries fails during link

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### Other Steps to Reproduce

N/A

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
@rei-vilo Thanks for the PR, we will take a look. It wasn't necessary to create an issue as there is not any additional info but nevermind :)

**Comment by rei-vilo** [comment]
I'll know next time!

**Comment by VojtechBartoska** [comment]
I'm closing the issue as PR was also closed as not applicable.
