### ISSUE TITLE
Keyboard.write always return success when no keyboard is plugged in

### ISSUE THREAD

**Issue by adipascu** [espressif/arduino-esp32#6131]
### Board

ESP32-S2

### Device Description

Using the [ESP32-S2-Saola-1 board](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/hw-reference/esp32s2/user-guide-saola-1-v1.2.html) with nothing attached

### Hardware Configuration

Nothing connected

### Version

2.02

### IDE Name

PlatformIO

### Operating System

Ubuntu 20.04 and macOS

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

460800

### Description

```c++
 size_t result = Keyboard.write(key);
 ```
 The variable `result` is always true, even when a physical keyboard is not plugged in. I expect this to return false.

### Sketch

```c++
#include <Arduino.h>
#include <USB.h>
#include <USBHIDKeyboard.h>

USBHIDKeyboard Keyboard;

void setup()
{
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Keyboard.begin();
  USB.begin();
}

void loop(){
  size_t result = Keyboard.write(KEY_RETURN);
  Serial.printf("Result %u", result);
}
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
You could listen to USB events and know when it's plugged in. Success comes from the fact that the usb peripheral accepted the package, not necessarily that it was able to send it to the host
