### ISSUE TITLE
ESP32 ethernet and Using ESPAsyncWebServer lib

### ISSUE THREAD

**Issue by savagerex** [espressif/arduino-esp32#6147]
### Board

ESP32 dev module

### Device Description

ESP32 module + Rtl8201(ethernet PHY)

### Hardware Configuration

not yet known

### Version

v2.0.1

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

40M hz

### PSRAM enabled

yes

### Upload speed

921600

### Description

If i use esp32 +rtl8201 (ethernet phy) to get ip address.

this lib(ESPAsyncWebServer lib), Can i use ???..... is it work???

lib website as below.

https://github.com/me-no-dev/ESPAsyncWebServer

### Sketch

```cpp
none
```

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello, can you please retest this on v2.0.3-rc1?

**Comment by VojtechBartoska** [comment]
I'm closing the issue as expired due to no answer.

If needed, please reopen it.

Thanks for understanding.
