### ISSUE TITLE
AsyncTCP.h: No such file or directory

### ISSUE THREAD

**Issue by nardev** [espressif/arduino-esp32#616]
I'm trying to compile one project which is for ESP8266 initially but i get this... 
could it be a path issue?

src/../lib/ESPAsyncWebServer/src/ESPAsyncWebServer.h:33:22: fatal error: AsyncTCP.h: No such file or directory

**Comment by copercini** [comment]
I think you should get these files from here: https://github.com/me-no-dev/AsyncTCP

**Comment by nardev** [comment]
Great but now an issue with SPIFFS

```
lib/ESPAsyncWebServer/src/SPIFFSEditor.h:6:20: fatal error: SPIFFS.h: No such file or directory
```

:(

**Comment by copercini** [comment]
This is very recent ( few hours ago) @me-no-dev is still adjusting the things to release officially...

Soon everything will work fine =)

**Comment by nardev** [comment]
@copercini thnx

**Comment by me-no-dev** [comment]
you can get it going without SPIFFS if you edit one file ;)
comment ```#include "SPIFFS.h"``` and remove ```=SPIFFS``` from the constructor [here](https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/SPIFFSEditor.h). Feel free to substitute with "SD" or "SD_MMC" also

**Comment by me-no-dev** [comment]
I actually adjusted the code so it no longer requires SPIFFS at all.
To enable the editor, on ESP32 you need to give the FileSystem as first argument:
```cpp
//SPIFFS
server.addHandler(new SPIFFSEditor(SPIFFS, "user","password"));
//SD
server.addHandler(new SPIFFSEditor(SD, "user","password"));
//SD_MMC
server.addHandler(new SPIFFSEditor(SD_MMC, "user","password"));
```

**Comment by copercini** [comment]
@nardev with last git version everything should work fine now =)
