### ISSUE TITLE
CRC error - Boards update

### ISSUE THREAD

**Issue by rtek1000** [espressif/arduino-esp32#6167]
### Board

ESP32-CAM Ai-Thinker

### Device Description

ESP32-CAM Ai-Thinker

### Hardware Configuration

ESP32-CAM Ai-Thinker

### Version

v2.0.2

### IDE Name

Arduino IDE 1.8.19

### Operating System

Xubuntu 20.04

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

There is an error when updating the ESP32 board.

### Sketch

```cpp
None
```

### Debug Message

```plain
CRC doens't match
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by rtek1000** [comment]
![Boards_Update_Error](https://user-images.githubusercontent.com/8660811/150435986-0da4709b-ccfa-4b26-ac5c-a726d4c97e76.png)

**Comment by me-no-dev** [comment]
probably really a temporary issue with Github or something on your system causing CRC to fail. There is no general issue with the package otherwise

**Comment by VojtechBartoska** [comment]
Hello @rtek1000, can I consider this as solved? Thanks

**Comment by VojtechBartoska** [comment]
Hi,

I'm closing the issue due to no response. 

If needed you can reopen it. 

Thanks for your contribution & understanding!
