### ISSUE TITLE
Truncated text when compiling

### ISSUE THREAD

**Issue by rtek1000** [espressif/arduino-esp32#6169]
### Board

ESP32

### Device Description

ESP32

### Hardware Configuration

ESP32

### Version

v2.0.2

### IDE Name

Arduino IDE 1.8.19

### Operating System

Xubuntu 20.04

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

Please see screenshot.

I started to notice this problem after updating the IDE to the latest version, version 1.8.13 didn't have it.

### Sketch

```cpp
This occurs when compiling the examples for the ESP32 board.
```

### Debug Message

```plain
Ref.: https://github.com/arduino/arduino-ide/issues/761
```

### Other Steps to Reproduce

![arduino_ide_debug](https://user-images.githubusercontent.com/8660811/150464431-25b58675-4086-4b80-86d4-3518c72f68e7.png)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
some graphical issue with the IDE. Nothing to do with this repo. Closing
