### ISSUE TITLE
Cannot Compile Under Arduino IDE 1.8.16

### ISSUE THREAD

**Issue by robboz4** [espressif/arduino-esp32#6198]
### Board

ESP AI Tinker

### Device Description

I've followed the tutorials several times including reloading everything from scratch but I cannot get passed this issue:
pp_httpd.cpp:22:10: fatal error: fd_forward.h: No such file or directory
 #include "fd_forward.h"
          ^~~~~~~~~~~~~~
compilation terminated.
 Used: /Users/daverobinson/Library/Arduino15/packages/esp32/hardware/esp32/2.0.1/libraries/WiFi
 Not used: /Users/daverobinson/Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
fd_forward.h: No such file or directory

There are no relevant files in that directory:
examples		library.properties
keywords.txt		src

I did compile another program atet test out the antenna strength and that compiled and download to the board successfully. Are these files missing  fro the latest bundle or I have loaded the wrong examples?

### Hardware Configuration

Using these boards :
https://www.amazon.com/dp/B097H2KLCH?ref_=pe_623860_70668520_dpLink

### Version

v2.0.1

### IDE Name

Arduino 1.8.16

### Operating System

Mac OS 12.1

### Flash frequency

40Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

Can't compile missing file from example and installed libraries 

### Sketch

```cpp
app_htppd.cpp

...
#include "fb_gfx.h"
#include "fd_forward.h"
#include "fr_forward.h"
```

### Debug Message

```plain
Multiple libraries were found for "WiFi.h"
app_httpd.cpp:22:10: fatal error: fd_forward.h: No such file or directory
 #include "fd_forward.h"
          ^~~~~~~~~~~~~~
compilation terminated.
 Used: /Users/daverobinson/Library/Arduino15/packages/esp32/hardware/esp32/2.0.1/libraries/WiFi
 Not used: /Users/daverobinson/Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
those files are no longer available. The face detection/recognition library has changed
