### ISSUE TITLE
Can't create more than 1 USBCDC on esp32s2

### ISSUE THREAD

**Issue by GEEKiDoS** [espressif/arduino-esp32#6233]
### Board

ESP32S2 Dev Module

### Device Description

nanoESP32S2

### Hardware Configuration

~

### Version

v2.0.2

### IDE Name

Arduino IDE

### Operating System

Window 10

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

When creating 2 USBCDC devices, there's only 1 com port displayed on host.

### Sketch

```cpp
#include "USB.h"

USBCDC USerial0(0);
USBCDC USerial1(1);

void setup() {
	USerial0.begin();
    USerial1.begin();

	USB.begin();
}

void loop() {
	// my loop logic, doesn't matter here
}
```

### Debug Message

```plain
~
```

### Other Steps to Reproduce

~

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
this is not a bug. we just do not support more than one cdc at the moment :) classes are prepared for it, but the rest is not.
