### ISSUE TITLE
toolchain-xtensa32 dangerous relocation: windowed longcall crosses 1GB boundary; return may fail: init

### ISSUE THREAD

**Issue by miqmago** [espressif/arduino-esp32#6240]
### Board

ESP32 Dev

### Device Description

PLATFORM: Espressif 32 (3.5.0) > Espressif ESP32 Dev Module
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 0.0.0+sha.d011dd7 
 - framework-espidf 3.40001.200521 (4.0.1) 
 - tool-cmake 3.16.4 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - tool-mkspiffs 2.230.0 (2.30) 
 - tool-ninja 1.9.0 
 - toolchain-esp32ulp 1.22851.191205 (2.28.51) 
 - toolchain-xtensa32 2.80400.210211 (8.4.0)

### Hardware Configuration

HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash

### Version

latest master

### IDE Name

PlatformIO

### Operating System

macOS 11.2.3

### Flash frequency

240MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

I'm running `pio run -t upload`. It was working fine few months ago. I've updated some parameters, but didn't touch any libdeps or includes. It compiles fine but when linking it fails with `dangerous relocation: windowed longcall crosses 1GB boundary; return may fail: init`:

```
Building in release mode
Linking .pio/build/esp32dev/firmware.elf
/Users/mmgadmin/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/esp32dev/esp-idf/framework-arduinoespressif32/libframework-arduinoespressif32.a(esp32-hal-misc.o): in function `initArduino':
/Users/mmgadmin/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-misc.c:228:(.text.initArduino+0x7c): dangerous relocation: windowed longcall crosses 1GB boundary; return may fail: init
collect2: error: ld returned 1 exit status
*** [.pio/build/esp32dev/firmware.elf] Error 1
```

### Sketch

```cpp
I've been reading that it could be related to SPIFFS, but I'm not using it, I'm using Fat32


#include <Arduino.h>
#include <FFat.h>
...


    FFat.begin(false, "/ffat", 10, "web");



```cpp
#if !CONFIG_AUTOSTART_ARDUINO
void arduinoTask(void *pvParameter) {
    setup();
    while (1) {
        loop();
    }
}

extern "C" void app_main() {
    // initialize arduino library before we start the tasks
    initArduino();
    xTaskCreate(&arduinoTask, "arduino_task", configMINIMAL_STACK_SIZE, NULL, 5, NULL);
}
#endif
```

(I've tried with and without `extern "C"`)
```


### Debug Message

```plain
`platformio.ini`:


[platformio]
default_envs = esp32dev

[env]
platform = espressif32
framework = 
	arduino
	espidf
monitor_speed = 115200
platform_packages = framework-arduinoespressif32 @ https://github.com/marcovannoord/arduino-esp32.git#idf-release/v4.0
board_build.partitions = partitions/partitions_singleapp_large.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DESP32=1
lib_deps = 
	me-no-dev/ESP Async WebServer@^1.2.3
	me-no-dev/ESPAsyncTCP@^1.2.2
	https://github.com/hilch/Bcrypt.cpp

[env:esp32dev]
board = esp32dev
```

`partitions_singleapp_large.csv`:

# Name,   Type, SubType, Offset,  Size, Flags
# Note: if you have increased the bootloader size, make sure to update the offsets to avoid overlap
nvs,      data, nvs,     ,        0x6000,
phy_init, data, phy,     ,        0x1000,
factory,  app,  factory, ,        2M,
web,      data, fat,     ,        1900K,
```
```

### Other Steps to Reproduce

I've read also read:
- https://github.com/espressif/arduino-esp32/issues/1422

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Are you using Arduino as IDF-Component? That Arduino branch you are targeting seems to be on some fork: https://github.com/marcovannoord/arduino-esp32 maybe try to look for info there? This repository does not support officially any other IDF version than 4.4
