### ISSUE TITLE
Change Arduino SDK

### ISSUE THREAD

**Issue by urbanze** [espressif/arduino-esp32#625]
Hi! I using idf-component to use this mcu (to change sdk configs in arduino ide) and I can't find how to read temperature sensor. How can I do this ? 

ps: I tryed app_main with and without InitArduino(), both worked. What this function do ?
----------------------------- Remove above -----------------------------

### Hardware:
Board:							ESP32 DoIt Nodemcu
Core Installation/update date:			?11/jul/2017?
IDE name:							IDF component with Arduino boot
Flash Frequency:					80Mhz
Upload Speed:						115200

**Comment by copercini** [comment]
@urbanze what temperature sensor?

**Comment by urbanze** [comment]
![image](https://user-images.githubusercontent.com/29230962/30511092-3d5695dc-9aa8-11e7-9391-bb7e093b68e2.png)

This sensor, from technical_reference datasheet.

**Comment by copercini** [comment]
There are some examples from @pcbreflux here: https://github.com/pcbreflux/espressif/blob/master/esp32/arduino/sketchbook/ESP32_int_temp_sensor/ESP32_int_temp_sensor.ino

Also a video explaining the things: https://www.youtube.com/watch?v=d57LKkHCVgI

**Comment by urbanze** [comment]
Oh, the secret of temperature sensor is "extern "C" "........ I forgot this -_-. Thank you for reply, see you later :D

**Comment by copercini** [comment]
See you =)
