### ISSUE TITLE
WROVER-B won't use QIO flash mode

### ISSUE THREAD

**Issue by marchingband** [espressif/arduino-esp32#6262]
### Board

ESP32 WROVER-B module

### Device Description

WROVER-B on a custom PCB

### Hardware Configuration

I am using the eMMC peripheral and the i2S peripheral

### Version

v2.0.1

### IDE Name

Arduino IDE

### Operating System

macOS 10.13

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

I set FLASH MODE to QIO in the Arduino IDE tools menu.
In my code i run`ESP.getFlashMode()` but it returns `2` (DIO mode)
I have fiddled with boards.txt, and tried passing `--build-property build.flash_mode=qio` when using arduino-cli, but nothing works.

### Sketch

```cpp
log_i("Flash Speed = %d Flash mode = %d", ESP.getFlashChipSpeed(), (int)ESP.getFlashChipMode());
```

### Debug Message

```plain
[   885][I][wvr_0.3.cpp:79] wvr_init(): Flash Speed = 80000000 Flash mode = 2
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
the ESP class reads this value from the bootloader and it does not show the actual mode. That is because the bootloader can not start in QIO and needs to be started in DIO and then switched to QIO.
