### ISSUE TITLE
Add option to switch PSRAM frequency 40/80mhz

### ISSUE THREAD

**Issue by mcer12** [espressif/arduino-esp32#6263]
### Related area

PSRAM speed

### Hardware specification

ESP32-WROVER-B

### Is your feature request related to a problem?

Arduino IDE PSRAM seems to be set to 40mhz and can't be changed to 80mhz. This makes some projects much slower in Arduino IDE. In platformio (arduino framework) it  is set to 80mhz by default and works perfectly fine.

### Describe the solution you'd like

by default use:
CONFIG_SPIRAM_SPEED_80M=y

### Describe alternatives you've considered

Or add an option in Arduino IDE to switch PSRAM frequency - similar to the flash frequency option - for modules that have PSRAM.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by Msq001** [comment]
@me-no-dev 
Hi. Is there any way to set PSRAM speed of ESP32S3R8 to 120MHz now?
the PSRAM of ESP32S3R8  is OCT(opi).
I know the following settings are required in ESP-IDF, but I don't know how to set them in Arduino.
```
CONFIG_IDF_EXPERIMENTAL_FEATURES=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_SPEED_120M=y
CONFIG_SPIRAM_SPEED=120
```
