### ISSUE TITLE
Change psram cs and clk pins

### ISSUE THREAD

**Issue by marnov042** [espressif/arduino-esp32#6273]
### Board

Esp32

### Device Description

Ttgo t-display

### Hardware Configuration

Gpio 16 is connected to display interface, so it can't be used with psram

### Version

v2.0.2

### IDE Name

Arduino ide

### Operating System

Windows 10

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

921600

### Description

I want to connect psram module to ttgo t-display, but gpio 16 (which is usually used with psram) is already connected to onboard display

### Sketch

```cpp
None
```

### Debug Message

```plain
None
```

### Other Steps to Reproduce

None

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
You can not use PSRAM on that board then :)

**Comment by marnov042** [comment]
Wait, but in esp-idf you can change the ps-ram cs and pin in configuration, so i am wondering if it is also possible to change that for Arduino ide?

**Comment by marnov042** [comment]
I also tryed changing the default pin configuration in sdk config for Arduino ide, but jt didn't work, so i think it's like with bootloader (it's already precompiled) so would it be possible to compile the library in esp-idf and then use it with Arduino ide?

**Comment by me-no-dev** [comment]
just install esp-idf, switch to use the `release/v4.4` branch, execute `idf.py menuconfig` and set the proper psram config, then you should `idf.py bootloader` and `cp build/bootloader/bootloader.bin [your sketch folder]`, then when you compile and upload, that bootloader will be used. It could be good option to ensure that you have also set the proper flash speed and size in Arduino IDE and also make sure that you do not enable PSRM test on boot in `idf.py menuconfig` as that is done by Arduino when starting (with PSRAM enabled in the menu).

**Comment by marnov042** [comment]
One question, i tried changing the cs and scl pins from default in menuconfig, to see if it will still find the ps ram, after i changed them, it still found the psram so i wanted to know, if it defaults to the normal ones, or how does it work?  (Tested on esp32s2 with 8mb build in ps ram)
