### ISSUE TITLE
WiFi.setHostname() not working

### ISSUE THREAD

**Issue by dsilletti** [espressif/arduino-esp32#6278]
### Board

ESP32

### Device Description

plain module

### Hardware Configuration

N/A

### Version

latest master

### IDE Name

Arduino IDE

### Operating System

macOS 12.1

### Flash frequency

40Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

WiFi.setHostname() does not work, hostname remain always esp32-XXXXXX

### Sketch

```cpp
WiFi.disconnect(true,true);
delay(1000);
WiFi.mode(WIFI_STA);
esp_wifi_set_country_code("IT", true);
WiFi.setHostname("hostname");
```

### Debug Message

```plain
N/A
```

### Other Steps to Reproduce

WiFi.setHostname("hostname");

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
how did you test this? it's often that the DHCP server might cache the hostname

**Comment by dsilletti** [comment]
@me-no-dev I power cycled the Wi-Fi router that provides the DHCP server several times, power cycled the esp32 several times, but the hostname is always esp32-XXXXXX

**Comment by JonGordon123** [comment]
On most routers if you want to clear the cache, you have to reset it using the reset button... and not just power cycle it. You could... connect to a different router, or reset the router, or change the esp32 MAC address to confirm the hostname shows up in the router.

**Comment by me-no-dev** [comment]
I have mikrotiks here for routers and they have "clear leases" option that allowed me to confirm the hostname change, else I also thought it did not work.

**Comment by dsilletti** [comment]
Interesting that even if I change the MAC address, the IP address I've got from the DHCP is different, but the hostname I see on the router is still the same esp32-XXXXXX. @me-no-dev could you please share your relevant code lines, this is in my running sketch (including the MAC address change I applied now for testing):
```
  WiFi.disconnect(true,true);
  delay(1000);
  WiFi.mode(WIFI_STA);
  uint8_t newMACAddress[] = {0x32, 0xAE, 0xA4, 0x07, 0x0D, 0x66};
  esp_wifi_set_mac(WIFI_IF_STA, &newMACAddress[0]);
  esp_wifi_set_country_code("IT", true);
  WiFi.setHostname(hostname);
```

**Comment by gonzabrusco** [comment]
Apparently WiFi.setHostname should be called before setting WiFi.mode in order to work.

**Comment by dsilletti** [comment]
Thank you @gonzabrusco it works! 
Calling WiFi.setHostname before WiFi.mode solved the issue.

```
 WiFi.disconnect(true,true);
  delay(1000);
  WiFi.setHostname("hostname");
  WiFi.mode(WIFI_STA);  
```

**Comment by Xylopyrographer** [comment]
Wouldn't it be super if the all the WiFi call setting sequences were documented somewhere... 😉

**Comment by wwmoo7** [comment]
I have the same problem， i read the source code and found the real set name is in  mode() function, and  when 
 mode not change it will return ,look blow, so you can  call  WiFi.mode(WIFI_MODE_NULL); first ,and then call WiFi.mode(WIFI_STA); ,it will change the hostname sucess.
WiFiGenericClass::mode(wifi_mode_t m)
{
    wifi_mode_t cm = getMode();
    if(cm == m) {
        return true;
    }
