### ISSUE TITLE
Backtrace:0x400839b1:0x3ffbeedc |<-CORRUPTED

### ISSUE THREAD

**Issue by gdanov** [espressif/arduino-esp32#6298]
### Board

wemos lolin d32 pro

### Device Description

none

### Hardware Configuration

happens both with and without attached peripherials

### Version

v2.0.2

### IDE Name

emacs

### Operating System

osx 12.1

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

1000000

### Description

The crash messages have incomplete backtrace.
Below is example using `pio device monitor` with `monitor_filters = time, default, esp32_exception_decoder`. Using platformio for build too.

```
00:09:22.640 >
00:09:22.640 > abort() was called at PC 0x40086097 on core 1
00:09:22.756 >
00:09:22.756 >
00:09:22.756 > Backtrace:0x400839b1:0x3ffbeedc |<-CORRUPTED
00:09:22.810 > #0 0x400839b1:0x3ffbeedc in panic_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:402
00:09:22.810 >
00:09:22.810 >
00:09:22.810 >
00:09:22.811 >
00:09:22.811 > ELF file SHA256: 0000000000000000
```
Tried to acquire the core dump as explained [here](https://docs.espressif.com/projects/esp-idf/en/v3.2.2/api-guides/core_dump.html#running-espcoredump-py) but got message `corefile.ESPCoreDumpLoaderError: Core dump version "0x9000" is not supported!`

flash was dumped with `esptool.py -p /dev/ttyUSB0 read_flash 32768 3072 /tmp/tmp2kvu_ifh`

### Sketch

```cpp
don't know the reason for the crash
```

### Debug Message

```plain
00:09:22.756 > Backtrace:0x400839b1:0x3ffbeedc |<-CORRUPTED
00:09:22.810 > #0 0x400839b1:0x3ffbeedc in panic_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:402
```

### Other Steps to Reproduce

happens on two separate boards, same model, flashed in the same way

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
if you do not provide your code, we have no way to assist you here

**Comment by TobbeG** [comment]
i have the same kind of issue, WDT gets triggered after a few hours or half a day.
I have 5 units ESP322 Touchdown with same software, same problem with all - so its seems iots not hardware.
I am using Arduino IDE 1.8.16 , ESP32 Dev Module - espressif system ESP32 Dev version 2.0.5
Arduino runs on Core 1
EVents runs on Core 1

Apart from this issue, everything works fine and Serial.print shows HEAP is stable and not the cause.

Debug prints 
18:01:05.764 -> E (54025027) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
18:01:05.764 -> E (54025027) task_wdt:  - IDLE (CPU 0)
18:01:05.764 -> E (54025027) task_wdt: Tasks currently running:
18:01:05.764 -> E (54025027) task_wdt: CPU 0: esp_timer
18:01:05.764 -> E (54025027) task_wdt: CPU 1: IDLE
18:01:05.764 -> E (54025027) task_wdt: Aborting.
18:01:05.764 -> 
18:01:05.764 -> abort() was called at PC 0x4011e2dc on core 0
18:01:05.764 -> 
18:01:05.764 -> 
18:01:05.764 -> Backtrace:0x40083bf5:0x3ffbec6c |<-CORRUPTED
18:01:05.764 -> 
18:01:05.764 -> 
18:01:05.764 -> 
18:01:05.764 -> 
18:01:05.764 -> ELF file SHA256: 0000000000000000
18:01:05.764 -> 
18:01:05.764 -> Rebooting...
18:01:05.810 -> ets Jun  8 2016 00:22:57
18:01:05.810 -> 
18:01:05.810 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
18:01:05.810 -> configsip: 0, SPIWP:0xee
18:01:05.810 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
18:01:05.810 -> mode:DIO, clock div:1
18:01:05.810 -> load:0x3fff0030,len:1344
18:01:05.810 -> load:0x40078000,len:13864
18:01:05.810 -> load:0x40080400,len:3608
18:01:05.810 -> entry 0x400805f0
18:01:06.173 -> [     4][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz

**Comment by Totalgeek9224** [comment]
Bump- Similar issue

**Comment by apbodrov** [comment]
I had exactly the same bootloop, only the address in the backtrace is different. Using another microUSB cable helped

**Comment by Qtakruri** [comment]
Anyone found the cause of this yet ?

**Comment by neonflex** [comment]
10:46:49.791 -> Server Task started on Core 0
10:48:55.082 -> >>> handlePortal() entered
10:48:55.156 -> GET request...
10:48:55.157 -> Getting scrollingText from EEPROM...
10:48:55.179 -> Sending HTML response in chunks...
10:48:56.317 -> >>> handlePortal() finished
10:49:01.292 -> E (71361) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
10:49:01.421 -> E (71361) task_wdt:  - IDLE0 (CPU 0)
10:49:01.453 -> E (71361) task_wdt: Tasks currently running:
10:49:01.484 -> E (71361) task_wdt: CPU 0: ServerHandle
10:49:01.549 -> E (71361) task_wdt: CPU 1: IDLE1
10:49:01.581 -> E (71361) task_wdt: Aborting.
10:49:01.612 -> 
10:49:01.612 -> abort() was called at PC 0x400e75e9 on core 0
10:49:01.645 -> 
10:49:01.677 -> 
10:49:01.677 -> Backtrace: 0x40083fd5:0x3ffbed0c |<-CORRUPTED
10:49:01.708 -> 
10:49:01.708 -> 
10:49:01.708 -> 
10:49:01.708 -> 
10:49:01.708 -> ELF file SHA256: 66a0d3ddd07f3c57
10:49:01.785 -> 
10:49:01.817 -> Rebooting...

---------------------------------------

ESP32 IN CORE 0 OR 1 SAME PROBLEM
SAME CODE WORKING PERFECTLY IN ESP8266
