### ISSUE TITLE
PCNT counter will not start after calling pcnt_unit_config

### ISSUE THREAD

**Issue by andz885** [espressif/arduino-esp32#6312]
### Board

ESP32

### Device Description

esp32 devkit v1

### Hardware Configuration

GPIO22 connected with GPIO15

### Version

latest master

### IDE Name

Visual Studio Code with PlatformIO

### Operating System

Win10

### Flash frequency

default from platform IO

### PSRAM enabled

no

### Upload speed

default from platform IO

### Description

In PCNT driver [documentation ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/pcnt.html)is stated that counting starts immediately after calling `pcnt_unit_config` function. But counter returns value 0 and will not start counting until function `pcnt_counter_clear` is called.

### Sketch

```cpp
#include "Arduino.h"
#include "driver/pcnt.h"

void setup() {

    pcnt_config_t pcnt_config = {
        .pulse_gpio_num = GPIO_NUM_15,
        .ctrl_gpio_num = PCNT_PIN_NOT_USED,
        .lctrl_mode = PCNT_MODE_KEEP,
        .hctrl_mode = PCNT_MODE_KEEP,
        .pos_mode = PCNT_COUNT_DIS,
        .neg_mode = PCNT_COUNT_INC,
        .counter_h_lim = 32767,
        .counter_l_lim = -32768,
        .unit = PCNT_UNIT_0,
        .channel = PCNT_CHANNEL_0,
    };

    pcnt_unit_config(&pcnt_config); // <-- calling this should start pulse counter
    pcnt_set_filter_value(PCNT_UNIT_0, 100);
    pcnt_filter_enable(PCNT_UNIT_0);
    pcnt_event_enable(PCNT_UNIT_0, PCNT_EVT_H_LIM);
    pcnt_event_enable(PCNT_UNIT_0, PCNT_EVT_THRES_0);
    pcnt_counter_pause(PCNT_UNIT_0);
    pcnt_counter_clear(PCNT_UNIT_0); // <-- commenting this out will will cause counter to not start
    pcnt_counter_resume(PCNT_UNIT_0);

    Serial.begin(115200);
    pinMode(22, OUTPUT);
}

void loop() {
    for (int i = 0; i < 50; i++) {
        digitalWrite(22, HIGH);
        delay(1);
        digitalWrite(22, LOW);
        delay(1);
    }

    delay(1000);
    Serial.println(REG_READ(PCNT_U0_CNT_REG));
}
```

### Debug Message

```plain
not needed
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
I'm closing the issue as expired due to no answer.

If needed, please reopen it.

Thanks for understanding.
