### ISSUE TITLE
No HSPI communication possible with Arduino-ESP32 now

### ISSUE THREAD

**Issue by mgo-tec** [espressif/arduino-esp32#634]
### Hardware:
Board:							ESP32-DevKitC
Core Installation/update date:			13/sep/2017
IDE name:							Arduino IDE 1.8.3
Flash Frequency:					80Mhz
Upload Speed:						921600

### Description:
In the Arduino core for ESP32 which is currently released, HSPI communication has become impossible.
The one before it moves without problems.
why?

**Comment by jestebanes** [comment]
Is the same for me. I need to back to version 10/9/2017

I've got an external flash connected to HSPI and I lost it with the last update to IDF 9a26296

**Comment by me-no-dev** [comment]
OK, I might have a clue ;)

**Comment by me-no-dev** [comment]
Can you guys pull the latest master?

**Comment by mgo-tec** [comment]
Great!
It worked without problems.
Thank you very much for your quick response.

**Comment by jestebanes** [comment]
Ok! it works again
Thank you @me-no-dev

**Comment by me-no-dev** [comment]
Thank you guys for reporting it :D
