### ISSUE TITLE
When update USB MSC Host feature on ESP32S2 platform?

### ISSUE THREAD

**Issue by ChinoLuo** [espressif/arduino-esp32#6344]
### Related area

ESP32S2

### Hardware specification

ESP32S2 DevKit

### Is your feature request related to a problem?

None

### Describe the solution you'd like

USB MSC Host has been implemented with esp-idf version...
So when will implement USB MSC Host feature on ESP32S2 platform?

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
MSC Host is very new. Not all fixes have been backported to 4.4 yet. We will provide support once everything on IDF side is OK and finalized. You are free to use the IDF code in Arduino. It should compile as-is.
