### ISSUE TITLE
Missing pcnt_struct.h for C3 SDK

### ISSUE THREAD

**Issue by shuoxinma4** [espressif/arduino-esp32#6346]
### Board

ESP32-C3 Dev Module

### Device Description

Generic board

### Hardware Configuration

Generic board

### Version

v2.0.2

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

There are no "pcnt_struct.h" file for the C3 core, even as it is include in "sdk/esp32c3/include/soc/include/soc/pcnt_periph.h" as #include "soc/pcnt_struct.h", just like that in ESP32 and ESP32-s2 cores.
Some libraries (namely ESP32Encoder) directly references that file, thus cannot be compiled on c3.

### Sketch

```cpp
#include "driver/pcnt.h" // this compiles 
#include <soc/pcnt_struct.h> // No such file or directory
void setup() {}
void loop() {}
```

### Debug Message

```plain
fatal error: soc/pcnt_struct.h: No such file or directory
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
The C3 does not have PCNT peripheral at all. That is why it can not work :)
