### ISSUE TITLE
ESP32 ExternalWakeUp example won't compile on ESP32C3 Mini

### ISSUE THREAD

**Issue by kriswiner** [espressif/arduino-esp32#6352]
### Board

ESP32 C3 Mini

### Device Description

Custom dev board with all GPIO exposed at the edge.

### Hardware Configuration

Native USB on GPIO 18/19

### Version

v2.0.2

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

Trying to compile ExternalWakeUp example for ESP32 C3 Dev Module and I see:

esp_sleep_enable_ext0_wakeup' was not declared in this scope

### Sketch

```cpp
#define BUTTON_PIN_BITMASK 0x200000000 // 2^33 in hex

RTC_DATA_ATTR int bootCount = 0;

/*
Method to print the reason by which ESP32
has been awaken from sleep
*/
void print_wakeup_reason(){
  esp_sleep_wakeup_cause_t wakeup_reason;

  wakeup_reason = esp_sleep_get_wakeup_cause();

  switch(wakeup_reason)
  {
    case ESP_SLEEP_WAKEUP_EXT0 : Serial.println("Wakeup caused by external signal using RTC_IO"); break;
    case ESP_SLEEP_WAKEUP_EXT1 : Serial.println("Wakeup caused by external signal using RTC_CNTL"); break;
    case ESP_SLEEP_WAKEUP_TIMER : Serial.println("Wakeup caused by timer"); break;
    case ESP_SLEEP_WAKEUP_TOUCHPAD : Serial.println("Wakeup caused by touchpad"); break;
    case ESP_SLEEP_WAKEUP_ULP : Serial.println("Wakeup caused by ULP program"); break;
    default : Serial.printf("Wakeup was not caused by deep sleep: %d\n",wakeup_reason); break;
  }
}

void setup(){
  Serial.begin(115200);
  delay(1000); //Take some time to open up the Serial Monitor

  //Increment boot number and print it every reboot
  ++bootCount;
  Serial.println("Boot number: " + String(bootCount));

  //Print the wakeup reason for ESP32
  print_wakeup_reason();

  /*
  First we configure the wake up source
  We set our ESP32 to wake up for an external trigger.
  There are two types for ESP32, ext0 and ext1 .
  ext0 uses RTC_IO to wakeup thus requires RTC peripherals
  to be on while ext1 uses RTC Controller so doesnt need
  peripherals to be powered on.
  Note that using internal pullups/pulldowns also requires
  RTC peripherals to be turned on.
  */
  esp_sleep_enable_ext0_wakeup(BUTTON_PIN_BITMASK,1); //1 = High, 0 = Low

  //If you were to use ext1, you would use it like
  //esp_sleep_enable_ext1_wakeup(BUTTON_PIN_BITMASK,ESP_EXT1_WAKEUP_ANY_HIGH);

  //Go to sleep now
  Serial.println("Going to sleep now");
  esp_deep_sleep_start();
  Serial.println("This will never be printed");
}

void loop(){
  //This is not going to be called
}
```

### Debug Message

```plain
esp_sleep_enable_ext0_wakeup' was not declared in this scope
```

### Other Steps to Reproduce

Tried version 2.0.0 and still get:

C:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\riscv32-esp-elf-gcc\\gcc8_4_0-esp-2021r1/bin/riscv32-esp-elf-g++" -DHAVE_CONFIG_H "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -D_GNU_SOURCE "-DIDF_VER=\"v4.4-dev-2313-gc69f0ec32\"" -DESP_PLATFORM "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/config" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/newlib/platform_include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/freertos/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/freertos/port/riscv/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_hw_support/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_hw_support/include/soc" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_hw_support/include/soc/esp32c3" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_hw_support/port/esp32c3" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_hw_support/port/esp32c3/private_include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/heap/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/log/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/lwip/include/apps" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/lwip/include/apps/sntp" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/lwip/lwip/src/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/lwip/port/esp32/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/lwip/port/esp32/include/arch" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/soc/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/soc/esp32c3" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/soc/esp32c3/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/hal/esp32c3/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/hal/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/hal/platform_port/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_rom/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_rom/esp32c3" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_rom/include/esp32c3" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_common/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_system/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_system/port/soc" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_system/port/include/riscv" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_system/port/public_compat" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/riscv/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/driver/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/driver/esp32c3/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_pm/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_ringbuf/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/efuse/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/efuse/esp32c3/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/vfs/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_wifi/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_event/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_netif/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_eth/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/tcpip_adapter/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_phy/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_phy/esp32c3/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/app_trace/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_timer/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_ipc/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/mbedtls/port/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/mbedtls/mbedtls/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/mbedtls/esp_crt_bundle/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/app_update/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/spi_flash/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/bootloader_support/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/nvs_flash/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/pthread/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_gdbstub/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_gdbstub/riscv" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_gdbstub/esp32c3" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/espcoredump/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/espcoredump/include/port/riscv" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/wpa_supplicant/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/wpa_supplicant/port/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/wpa_supplicant/include/esp_supplicant" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/ieee802154/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/asio/asio/asio/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/asio/port/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/bt/common/osi/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/bt/include/esp32c3/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/bt/common/api/include/api" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/bt/common/btc/profile/esp/blufi/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/bt/common/btc/profile/esp/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/bt/host/bluedroid/api/include/api" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/cbor/port/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/unity/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/unity/unity/src" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/cmock/CMock/src" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/coap/port/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/coap/port/include/coap" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/coap/libcoap/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/coap/libcoap/include/coap2" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/console" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/nghttp/port/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/nghttp/nghttp2/lib/includes" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp-tls" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp-tls/esp-tls-crypto" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_adc_cal/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_hid/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/tcp_transport/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_http_client/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_http_server/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_https_ota/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_https_server/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_lcd/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_lcd/interface" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/protobuf-c/protobuf-c" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/protocomm/include/common" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/protocomm/include/security" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/protocomm/include/transports" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/mdns/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_local_ctrl/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/sdmmc/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_serial_slave_link/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_websocket_client/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/expat/expat/expat/lib" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/expat/port/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/wear_levelling/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/fatfs/diskio" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/fatfs/vfs" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/fatfs/src" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/freemodbus/common/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/idf_test/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/idf_test/include/esp32c3" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/jsmn/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/json/cJSON" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/libsodium/libsodium/src/libsodium/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/libsodium/port_include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/mqtt/esp-mqtt/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/openssl/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/spiffs/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/wifi_provisioning/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_littlefs/src" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/esp_littlefs/include" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0/tools/sdk/esp32c3/include/fb_gfx/include" -march=rv32imc -ffunction-sections -fdata-sections -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -ggdb -Wno-error=format= -nostartfiles -Wno-format -Og -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu++11 -fno-exceptions -fno-rtti -MMD -c -DF_CPU=80000000L -DARDUINO=10815 -DARDUINO_ESP32C3_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32C3_DEV\"" "-DARDUINO_VARIANT=\"esp32c3\"" -DESP32 -DCORE_DEBUG_LEVEL=4 -DARDUINO_HW_CDC_ON_BOOT=0 "@C:\\Users\\kris\\AppData\\Local\\Temp\\arduino_build_854527/build_opt.h" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0\\cores\\esp32" "-IC:\\Users\\kris\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.0\\variants\\esp32c3" "C:\\Users\\kris\\AppData\\Local\\Temp\\arduino_build_854527\\sketch\\ExternalWakeUp.ino.cpp" -o "C:\\Users\\kris\\AppData\\Local\\Temp\\arduino_build_854527\\sketch\\ExternalWakeUp.ino.cpp.o"
C:\Users\kris\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\ESP32\examples\DeepSleep\ExternalWakeUp\ExternalWakeUp.ino: In function 'void setup()':
ExternalWakeUp:69:3: error: 'esp_sleep_enable_ext0_wakeup' was not declared in this scope
   esp_sleep_enable_ext0_wakeup(BUTTON_PIN_BITMASK,1); //1 = High, 0 = Low
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\kris\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\ESP32\examples\DeepSleep\ExternalWakeUp\ExternalWakeUp.ino:69:3: note: suggested alternative: 'esp_sleep_enable_wifi_wakeup'
   esp_sleep_enable_ext0_wakeup(BUTTON_PIN_BITMASK,1); //1 = High, 0 = Low
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   esp_sleep_enable_wifi_wakeup
exit status 1
'esp_sleep_enable_ext0_wakeup' was not declared in this scope

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by felmue** [comment]
Hello @kriswiner 

I think this is not supported on the C3 - see [here](https://github.com/espressif/arduino-esp32/issues/5194).

Thanks
Felix

**Comment by kriswiner** [comment]
Thanks, verified timed deep sleep does work.
