### ISSUE TITLE
UART Callback on TX FIFO empty.

### ISSUE THREAD

**Issue by gonzabrusco** [espressif/arduino-esp32#6385]
### Related area

UART

### Hardware specification

ESP32

### Is your feature request related to a problem?

Nowadays, most modbus libraries based on Arduino, when writing to UART have to wait for flush() to be able to toggle the 485 transceiver pin. That means waiting a lot of time that could be used for something else. 

I don't know if it's technically possible, but it would be very useful to have a callback on TX complete (TX FIFO is empty).

Is this possible?

Thanks
Gonzalo

### Describe the solution you'd like

A callback on TX complete

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
@gonzabrusco 

IDF UART driver controls all the Interrupt events from the ESP32 for UART.

There is an interrupt available, called UART_TX_DONE_INT, but **IDF UART driver doesn't use it to send any event to the user application**.

### Sorry, but we won't ESP32 be able to fulfill your request.

You can try to do something around IDF call [```esp_err_t uart_wait_tx_done(uart_port_t, uart_num, TickType_t ticks_to_wait)```](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/uart.html#_CPPv417uart_wait_tx_done11uart_port_t10TickType_t), like a task that keeps checking it or something similar.

**Comment by gonzabrusco** [comment]
Thanks @SuGlider for taking your time checking this.
