### ISSUE TITLE
spiTransferBits missing in esp32-hal-spi.c

### ISSUE THREAD

**Issue by nepeee** [espressif/arduino-esp32#640]
libraries\SPI\SPI.cpp.o:(.literal._ZN8SPIClass12transferBitsEjPjh+0x0): undefined reference to `spiTransferBits'

libraries\SPI\SPI.cpp.o: In function `SPIClass::transferBits(unsigned int, unsigned int*, unsigned char)':

C:\Users\nepe\Documents\Arduino\hardware\espressif\esp32\libraries\SPI\src/SPI.cpp:252: undefined reference to `spiTransferBits'

**Comment by me-no-dev** [comment]
Wow! I wonder how nobody noticed this till now :) Fixing...
