### ISSUE TITLE
esp32 ble client 搜不全服务器的服务和通道 (Incomplete server services and channels)

### ISSUE THREAD

**Issue by JachinY** [espressif/arduino-esp32#6431]
### Board

ESP32

### Device Description

DEVKIT

### Hardware Configuration

none

### Version

v2.0.2

### IDE Name

Arduino

### Operating System

Windows11

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

921600

### Description

获取的service不全
只能获取到两个
实际上有四个service

English Translation:
The obtained service is incomplete
only get two
There are actually four services

### Sketch

```cpp
ble_client.ino示例 (ble_client.ino example)
```

### Debug Message

```plain
03:22:24.244 -> BLE Advertised Device found: Name: HJX2_86BA4B440224, Address: 86:ba:4b:44:02:24, manufacturer data: ba867b00, serviceUUID: 0000180d-0000-1000-8000-00805f9b34fb, serviceUUID: 0000fef5-0000-1000-8000-00805f9b34fb
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment]
Please keep posts in English so others can help you.

**Comment by SuGlider** [comment]
@JachinY 
Please explain the issue with more details. Thanks.

**Comment by VojtechBartoska** [comment]
I'm closing this issue because more info wasn't provided. If needed, consider reopening @JachinY.
