### ISSUE TITLE
WiFi.getNetworkinfo always returns channel 0

### ISSUE THREAD

**Issue by Crsarmv7l** [espressif/arduino-esp32#6438]
### Board

Lillygo T-watch 2020 v-1

### Hardware Configuration

Normal T-watch

### IDE Name

Platform IO

### Operating System

Win10

### PSRAM enabled

yes

### Upload speed

115200

### Description

Espressif32@3.3.0

Using WiFi.Scan, on ScanComplete I call WiFi.getNetworkinfo with a pointer. All information is correct (BSSID, RSSI, etc) except channel always returns 0.

Tried looking for an already open issue with no luck.

Any ideas?

**Comment by VojtechBartoska** [comment]
Hello, are you able to test this on Arduino core esp32 v2.0.3-rc1? Thanks!

**Comment by VojtechBartoska** [comment]
any updates?

**Comment by VojtechBartoska** [comment]
Due to no response, I'm closing this issue as expired.

If needed, you can reopen it.

Thanks for understanding.

**Comment by Crsarmv7l** [comment]
Sorry. I am not going to reopen the issue as it may be fixed in Arduino core esp32 v2.0.3-rc1, but I cannot change.

Instead I used a cumbersome workaround: Grab the BSSID from the scan, go into promiscuous mode with a beacon packet filter, if BSSID matches the sender of the beacon packet, pull the channel and stop promiscuous.
