### ISSUE TITLE
log_x does not display in color

### ISSUE THREAD

**Issue by ultrapalace** [espressif/arduino-esp32#6454]
### Board

esp32s2

### Device Description

plain module on a custom pcb

### Hardware Configuration

NA

### Version

latest master

### IDE Name

VSCODE

### Operating System

macOS

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

115200

### Description

I expect the logs to be coloured in my console (like in esp-idf), but they are not. I have tried using screen, minicom, coolterm, Aruduino serial Monitor, etc
Is there a way to turn on color?
It is very helpful when debugging large projects.

### Sketch

```cpp
loop(){
  log_e("error");
  vTaskDelay(1000);
}
```

### Debug Message

```plain
[  1278][E][mainframe.ino:35] loop(): error
[  2278][E][mainframe.ino:35] loop(): error
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
add `-DCONFIG_ARDUHAL_LOG_COLORS=1` to your build flags, or add the define manually on top of `esp32-hal-log.h`
