### ISSUE TITLE
Sending multipart data from HTTPCLIENT on ESP32

### ISSUE THREAD

**Issue by srinadhpotnuru** [espressif/arduino-esp32#646]
I am looking for sending a multipart data(in my case to send a binary file) from ESP32 httpclient to a server. But in httpclient library I found only String data type in payload. Can anyone help or redirect to a correct issue thread.

Thanks

**Comment by copercini** [comment]
Take a look here: https://github.com/adjavaherian/solar-server/blob/master/lib/Poster/Poster.cpp

Maybe you can use this library to send your file using multipart data, or at least have an inspiration of how it works =)
