### ISSUE TITLE
Add RISING/FALLING for esp_sleep_ext1_wakeup_mode_t in esp_sleep.h

### ISSUE THREAD

**Issue by T365** [espressif/arduino-esp32#6483]
### Related area

Deep sleep esp_sleep.h extra function

### Hardware specification

ESP32

### Is your feature request related to a problem?

Missing RISING / FALLING in esp_sleep_enable_ext1_wakeup

### Describe the solution you'd like

In esp_sleep.h I want to use
esp_sleep_enable_ext1_wakeup (RISING/FALLING)
there is only:

 	typedef enum {
		ESP_EXT1_WAKEUP_ALL_LOW = 0,    //!< Wake the chip when all selected GPIOs go low
		ESP_EXT1_WAKEUP_ANY_HIGH = 1    //!< Wake the chip when any of the selected GPIOs go high
	} esp_sleep_ext1_wakeup_mode_t;

	On page 77 https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf
	I found this:
	
RTCIO_RTC_GPIO_PINn_INT_TYPE GPIO interrupt type selection. (R/W)
0: GPIO interrupt disable;
1: rising edge trigger;
2: falling edge trigger;
3: any edge trigger;
4: low level trigger;
5: high level trigger

I want to use
1: rising edge trigger;
2: falling edge trigger;

### Additional context

![esp_sleep_enable_ext1_wakeup](https://user-images.githubusercontent.com/30527665/160110599-95dbd02e-2bdd-4e19-ba7d-486ecfad0ee1.png)

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by igrr** [comment]
@T365 The register you are referring to is not related to EXT1 wakeup source. It is related to GPIO wakeup source.

One ESP32, you can use GPIO wakeup source for light sleep only. To use GPIO wakeup source, use functions esp_sleep_enable_gpio_wakeup and gpio_wakeup_enable. This functionality is demonstrated in the following ESP-IDF example: https://github.com/espressif/esp-idf/blob/9763125c1c4aaec8fb6c85d97abb52ccb72066c9/examples/system/light_sleep/main/gpio_wakeup.c#L36-L58
