### ISSUE TITLE
Strange values from uartGetBaudRate

### ISSUE THREAD

**Issue by luc-github** [espressif/arduino-esp32#649]
Hi,
 ESP32 miss one function to get current baudrate unlike ESP8266
so I added it in HardwareSerial
```
uint32_t  HardwareSerial::baudRate()

{
	return uartGetBaudRate(_uart);
}
```
But I got inconsistent values when using it:

Setting 57000 give 57000 ->Ok
Setting **115200** give **115201** ->**Different**
Setting **230400** give  **230423** ->**Different**
Setting 250000 give  250000 ->Ok

There is not such issue on ESP8266

here test sketch which display results at 115200
```
String result;
void setup() {
	result="Set 57000 get ";
	Serial.begin(57000);
	delay(1000);
	result+=String(Serial.baudRate());
	result+="\nSet 115200 get ";
	Serial.begin(115200);
	delay(1000);
	result+=String(Serial.baudRate());
	result+="\nSet 230400 get ";
	Serial.begin(230400);
	delay(1000);
	result+=String(Serial.baudRate());
	result+="\nSet 250000 get ";
	Serial.begin(250000);
	delay(1000);
	result+=String(Serial.baudRate());
	Serial.begin(115200);
}

void loop() {
	Serial.println(result);

	delay(3000);

}
```

Is that normal ?

**Comment by me-no-dev** [comment]
Yup :) it's a integer math error. Here it is with PHP:
Baud: 57000, res: 57000
Baud: 115200, res: 115201
Baud: 230400, res: 230423
Baud: 250000, res: 250000

**Comment by luc-github** [comment]
Thank you for confirming I just have one unit on hand, so was not sure was only me
Ok, so if you change UART driver it may fix the issue ?
I guess I can do the PR for baudRate function API won't change, right?

**Comment by me-no-dev** [comment]
yes :) I will implement it on top of IDF's driver but that will be done in the esp32-hal-uart, so API for both will not change.

**Comment by luc-github** [comment]
Thank you PR (https://github.com/espressif/arduino-esp32/pull/651) done

**Comment by me-no-dev** [comment]
Thanks :) will merge as soon as the tests are done

**Comment by me-no-dev** [comment]
maybe we can close this now?

**Comment by luc-github** [comment]
sure thank you
