### ISSUE TITLE
Face Detection in CameraWebServer Example Not Working in 2.0.3

### ISSUE THREAD

**Issue by HaydenHu** [espressif/arduino-esp32#6508]
### Board

ESP32-CAM

### Device Description

CAMERA_MODEL_AI_THINKER  ESP32-CAM

### Hardware Configuration

#define SIOD_GPIO_NUM     26
#define SIOC_GPIO_NUM     27

### Version

latest master

### IDE Name

arduino IDE

### Operating System

win10

### Flash frequency

40MHZ

### PSRAM enabled

yes

### Upload speed

115200

### Description

![image](https://user-images.githubusercontent.com/30103277/161090119-24d90fa6-7548-4578-a591-9694cc52cf70.png)

### Sketch

```cpp
#define CAMERA_MODEL_AI_THINKER // Has PSRAM
```

### Debug Message

```plain
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13516
load:0x40080400,len:3604

entry 0x400805f0
[mum2-hal-cpu.c:214] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[   842][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled



[  1122][D][WiFiGeneric.cpp:852] _eventCallback(): Arduino Event: 0 - WIFI_READY
[  1223][D][WiFiGeneric.cpp:852] _eventCallback(): Arduino Event: 2 - STA_START
...
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
yes, the API for image recognition changed and we need to update the examples. It will be done.

**Comment by Lupo-Grigio** [comment]
@me-no-dev Thank you. I can add a little bit of info to this issue. Under Arduino IDE 2.0.0.rc5 and Arduino IDE 1.8.19
If you enable face detection or recognition by either one or both of the following #define
```
#define CONFIG_ESP_FACE_DETECT_ENABLED 1
#define CONFIG_ESP_FACE_RECOGNITION_ENABLED 1
```
causes 2 files to be included that do not exist
In the file app_httpd.cpp starting at 34
```
#if CONFIG_ESP_FACE_DETECT_ENABLED

#include "fd_forward.h"

#if CONFIG_ESP_FACE_RECOGNITION_ENABLED
#include "fr_forward.h"

#define ENROLL_CONFIRM_TIMES 5
#define FACE_ID_SAVE_NUMBER 7
#endif
```

Those files where #included in earlier versions of the sample, but it appears that the files where never placed in the sample directory. Looks like they existed somewhere in the face detection library. I've briefly looked for they the espressif github repo but came up empty. I will continue searching as my active project uses face detection and when I moved to 2.0.2 to get working I2C functionality, face detection broke. 

Am happy to help any way I can. I've got 4 or 5 of the cam modules various  types.

**Comment by 547176052** [comment]
我也碰到这个问题,应该怎么解决呢

**Comment by VojtechBartoska** [comment]
Hello, please keep in mind main and only language of this repository is English.
