### ISSUE TITLE
ESP32-S3: Guru Meditation Error when WiFi STA + analogRead

### ISSUE THREAD

**Issue by cod3gen** [espressif/arduino-esp32#6549]
### Board

ESP32-S3-WROOM-1

### Device Description

ESP32-S3-WROOM-1 on custom board. GPIO 5 Currently not connected to anything on board, also tested with GPIO 6 which is pulled low, same result on both
![esp32s3_1](https://user-images.githubusercontent.com/14929298/162267901-79c9a90d-f022-42e7-8d39-f7dbb1494ba4.png)
![esp32s3_2](https://user-images.githubusercontent.com/14929298/162267911-bcdce5f7-82c4-4f99-8c8c-6fa11a1d56f4.png)
![esp32s3_3](https://user-images.githubusercontent.com/14929298/162267924-5a559451-fd60-43b7-a307-e392b5b3d9b6.png)
.

### Hardware Configuration

GPIO35/36/37/1(CS): SPI. GPIO48 also CS, but not connected atm.
GPIO15/16: I2C

### Version

latest master

### IDE Name

Arduino IDE + Platform IO

### Operating System

Windows 10

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1): error happens on some cycles when analogRead is being executed. Seems to only happen when wifi is connected(STA), does not seem to happen when in AP mode. 

Same result on both Arduino 1.8.19 with 2.0.3-RC1, and PIO with https://github.com/tasmota/platform-espressif32.git & framework-arduinoespressif32@https://github.com/Jason2866/esp32-arduino-lib-builder/releases/download/803/framework-arduinoespressif32-v4.4_dev-40d126bfd1.tar.gz

Tested on GPIO 5 and 6. Commenting out analogRead(6); and the code have been running for one whole day without issues.
Included example to reproduce is with [https://github.com/me-no-dev/ESPAsyncWebServer](url), however the same error also happens with [https://github.com/prampec/IotWebConf](url) when its in STA mode.

### Sketch

```cpp
#include <Arduino.h>
#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>

AsyncWebServer server(80);

void setup() {
    Serial.begin(115200);
    WiFi.mode(WIFI_STA);
    WiFi.begin("XX", "XX");
    server.begin();
}

void loop() {
  analogRead(6);
}
```

### Debug Message

```plain
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x2b (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x1660
load:0x403b6000,len:0xf0c
load:0x403ba000,len:0x32c8
entry 0x403b6328
[0;32mI (25) boot: ESP-IDF v4.4-367-gc29343eb94 2nd stage bootloader[0m
[0;32mI (25) boot: compile time 22:20:55[0m
[0;32mI (25) boot: chip revision: 0[0m
[0;32mI (28) qio_mode: Enabling default flash chip QIO[0m
[0;32mI (33) boot.esp32s3: Boot SPI Speed : 80MHz[0m
[0;32mI (38) boot.esp32s3: SPI Mode       : QIO[0m
[0;32mI (43) boot.esp32s3: SPI Flash Size : 8MB[0m
[0;32mI (47) boot: Enabling RNG early entropy source...[0m
[0;32mI (53) boot: Partition Table:[0m
[0;32mI (56) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (64) boot:  0 nvs              WiFi data        01 02 00009000 00005000[0m
[0;32mI (71) boot:  1 otadata          OTA data         01 00 0000e000 00002000[0m
[0;32mI (79) boot:  2 ota_0            OTA app          00 10 00010000 00200000[0m
[0;32mI (86) boot:  3 ota_1            OTA app          00 11 00210000 00200000[0m
[0;32mI (94) boot:  4 uf2              factory app      00 00 00410000 00040000[0m
[0;32mI (101) boot:  5 ffat             Unknown data     01 81 00450000 003b0000[0m
[0;32mI (109) boot: End of partition table[0m
[0;32mI (613) esp_image: segment 0: paddr=00010020 vaddr=3c080020 size=1ce98h (118424) map[0m
[0;32mI (631) esp_image: segment 1: paddr=0002cec0 vaddr=3fc934c0 size=03158h ( 12632) load[0m
[0;32mI (634) esp_image: segment 2: paddr=00030020 vaddr=42000020 size=70d8ch (462220) map[0m
[0;32mI (707) esp_image: segment 3: paddr=000a0db4 vaddr=3fc96618 size=016f8h (  5880) load[0m
[0;32mI (708) esp_image: segment 4: paddr=000a24b4 vaddr=40374000 size=0f4b8h ( 62648) load[0m
[0;32mI (725) esp_image: segment 5: paddr=000b1974 vaddr=50000000 size=00010h (    16) load[0m
[0;32mI (731) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (732) boot: Disabling RNG early entropy source...[0m
[   784][D][WiFiGeneric.cpp:852] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   854][V][WiFiGeneric.cpp:283] _arduino_event_cb(): STA Started
[   855][V][WiFiGeneric.cpp:96] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
[   855][D][WiFiGeneric.cpp:852] _eventCallback(): Arduino Event: 2 - STA_START
[  2956][V][WiFiGeneric.cpp:295] _arduino_event_cb(): STA Connected: SSID: XX, BSSID: 04:d9:f5:e2:f7:50, Channel: 5, Auth: WPA2_PSK
[  2957][D][WiFiGeneric.cpp:852] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  3161][V][WiFiGeneric.cpp:305] _arduino_event_cb(): STA Got New IP:192.168.1.38
[  3162][D][WiFiGeneric.cpp:852] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  3165][D][WiFiGeneric.cpp:914] _eventCallback(): STA IP: 192.168.1.38, MASK: 255.255.255.0, GW: 192.168.1.1
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1). 

Core  1 register dump:
PC      : 0x40035871  PS      : 0x00060134  A0      : 0x8003589a  A1      : 0x3fce2eb0  
A2      : 0x02000000  A3      : 0x030a086b  A4      : 0x00000200  A5      : 0x00ce0000  
A6      : 0x3fcef3d4  A7      : 0x00000000  A8      : 0x05000000  A9      : 0x3fce2e90  
A10     : 0x6000e000  A11     : 0x04ce0269  A12     : 0x6000e000  A13     : 0x00000200  
A14     : 0x00000005  A15     : 0x00000001  SAR     : 0x00000019  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x4200b0f2  LEND    : 0x4200b0fe  LCOUNT  : 0x00000004  


Backtrace:0x4003586e:0x3fce2eb0 |<-CORRUPTED


Core  0 register dump:
PC      : 0x400356de  PS      : 0x00060534  A0      : 0x80035725  A1      : 0x3fce8d60  
A2      : 0x02000000  A3      : 0x030a086b  A4      : 0x6000e004  A5      : 0x01910864  
A6      : 0x00000800  A7      : 0x00910000  A8      : 0x01000000  A9      : 0x6000e000  
A10     : 0x00000000  A11     : 0x6000e05c  A12     : 0x00000001  A13     : 0x00060523  
A14     : 0x3fce7bb4  A15     : 0x00000000  SAR     : 0x0000001c  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0xffffffff  


Backtrace:0x400356db:0x3fce8d60 |<-CORRUPTED




ELF file SHA256: 0000000000000000

Rebooting...

```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Please also provide actual minimal example that can reproduce the issue and decode those exceptions using the ExceptionDecoder

**Comment by Jason2866** [comment]
Probably this issue is hitted from bug #6507 since it uses LittleFS.

**Comment by cod3gen** [comment]
@me-no-dev Updated with minimal example, and updated serial output. Not able to decode the exeption, just says "Decoding stack results" Maybe due to Backtrace:0x4003586e:0x3fce2eb0 **|<-CORRUPTED**

**Comment by cod3gen** [comment]
@Jason2866 Updated with minimal example, without usage of FileFS, same error.

**Comment by cod3gen** [comment]
Ive created a similiar application in ESP-IDF, and it seems i have the same results here. Will be opening an issue over there.

**Comment by Jason2866** [comment]
You can not use ADC2 with wifi.

**Comment by cod3gen** [comment]
> You can not use ADC2 with wifi.

Auch, darn. New round with JLC soon then 😝

**Comment by igrr** [comment]
> You can not use ADC2 with wifi.

@Jason2866 I thought this is an ESP32-specific limitation. Are you sure it applies to S3?

According to the docs, on ESP32-S2, C3, S3 both ADC units can be used with Wi-Fi. There is a limitation that in certain cases Wi-Fi will have priority over user's ADC reading, and then `adc2_get_raw` function will return an error code. But it's still possible to retry reading the ADC value in that case.

**Comment by Jason2866** [comment]
@igrr Thx, i tried (a while ago). The results doing this where not really useable and i had wdt now and than. So i thought the docs maybe are not correct.

**Comment by igrr** [comment]
Okay, not sure about "usable" result (maybe indeed something unavoidable?) but the interrupt watchdog triggering is definitely a bug. Let's see what IDF folks say.

**Comment by cod3gen** [comment]
GPIO 5/6 is not ADC2 btw @Jason2866. Will keep the thread over at IDF open

**Comment by richcj10** [comment]
Do you have an update on this? I am getting wdt on CPU 1 with reading pin one on the C3 module. It has been bugging me for a while, lol
