### ISSUE TITLE
ESP32-A1S support

### ISSUE THREAD

**Issue by serkansatuk** [espressif/arduino-esp32#6557]
### Related area

ESP32-A1S support

### Hardware specification

ESP32-A1S

### Is your feature request related to a problem?

Hello.
Please add ESP32-A1S board.
Thanks...

### Describe the solution you'd like

Hello.
Please add ESP32-A1S board.
Thanks...

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
Hello, adding third-party boards is more likely up to the manufacturers of these boards. We are not able to be aware of all types and their specifications of non-Espressif Boards.

You can take a look on some closed PRs, how in general are boards added into Arduino IDE.

**Comment by VojtechBartoska** [comment]
Closing as won't fix. We are not able to help as mentioned above.
