### ISSUE TITLE
RainMaker support for ESP32-S2, S3 and C3.

### ISSUE THREAD

**Issue by pedrominatel** [espressif/arduino-esp32#6573]
### Board

ESP32-S2, ESP32-S3 and ESP32-C3

### Device Description

ESP32-S2-DevKitC-1
ESP32-S3-DevKitC-1
ESP32-C3 Rust Board (custom board)

### Hardware Configuration

Nothing connected.

### Version

other

### IDE Name

Arduino IDE

### Operating System

Linux

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

- Add RainMaker partition table scheme on each generic board.
- Change the provisioning method for ESP32-S2 to WiFi and for S3 and C3 BLE.

### Sketch

```cpp
RMakerSwitch.ino
```

### Debug Message

```plain
N/A
```

### Other Steps to Reproduce

N/A

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
[rainmaker_partitions.patch.zip](https://github.com/espressif/arduino-esp32/files/8480956/rainmaker_partitions.patch.zip)
here is the patch for the partition scheme support on all boards

**Comment by VojtechBartoska** [comment]
Probably related issue which can be closed by this one: https://github.com/espressif/arduino-esp32/issues/6435

**Comment by pedrominatel** [comment]
Not sure @VojtechBartoska. I'll test on ESP32 and try to reproduce the #6435.
