### ISSUE TITLE
MacOS Python Path

### ISSUE THREAD

**Issue by a7hybnj2** [espressif/arduino-esp32#6619]
### Board

ESP32 Dev Module

### Device Description

I was attempting to compile for 'esp32 dev module' it was naked at the time.

### Hardware Configuration

Naked

### Version

v2.0.2

### IDE Name

Arduino IDE

### Operating System

macOS 12.3.1

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

115200

### Description

On macOS there is not python and I tried setting symlinks and adding it to /etc/paths.d/ and all kinds of things to fix the `"exec: "python": executable file not found in $PATH` error but nothing worked. I ended up needing to edit the `$HOME/Library/Arduino15/packages/esp32/hardware/esp32/2.0.2/platform.txt` file and replacing `python` with `python3` `:%s/=python /=python3 /g`

I am mainly putting this here in case anyone else has this issue with macOS. I found https://github.com/espressif/arduino-esp32/issues/5750 and https://docs.espressif.com/projects/arduino-esp32/en/latest/troubleshooting.html#missing-python-python-executable-file-not-found-in-path but that didn't help for macOS.

### Sketch

```cpp
Example Sketch
```

### Debug Message

```plain
exec: "python": executable file not found in $PATH
Error compiling for board ESP32 Dev Module.
```
```


### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
fixed in master. it is already present in 2.0.3-rc1 and will be part of the upcoming 2.0.3
