### ISSUE TITLE
WiFi Promiscuous filter breaks w/ WIFI_PROMIS_FILTER_MASK_ALL

### ISSUE THREAD

**Issue by SoftwareSamurai** [espressif/arduino-esp32#663]
After calling esp_wifi_set_promiscuous_filter() with the filter set to WIFI_PROMIS_FILTER_MASK_ALL and starting up the WiFi, I randomly get this output:

"E (51478) wifi: wdev.c wdevProcessRxSucDataAll 1008"

When I get that, the Promiscuous callback appears to never get called. But it doesn't happen all the time. In fact, I can reset the ESP32 via the button (not even re-uploading my program) and sometimes it happens and sometimes it runs fine. 

--Details--
Board: ESP32 Dev Module, Rev 0.
IDE: PlatformIO (Also tried this on Arduino IDE - same results)
Core: Latest arduino-esp32 branch.

**Comment by me-no-dev** [comment]
Can I please ask you to submit this in https://github.com/espressif/esp-idf ? those functions are out of the scope of Arduino. :)

**Comment by SoftwareSamurai** [comment]
Done. I'll close this one then. Thanks!
