### ISSUE TITLE
Port name is incorrect - not using board name based on PID/VID - showing C3 instead of S3.

### ISSUE THREAD

**Issue by UnexpectedMaker** [espressif/arduino-esp32#6631]
### Board

TinyS3, ProS3 & FeatherS3

### Device Description

Plain board, no external HW connected.

### Hardware Configuration

Plain board, no external HW connected.

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

MacOS 12.3.1

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

N/A

### Description

Flashing the board should set the name in ( ) in the ports list based n the board name using the VID/PID provided - not only does it not put the correct board name, but it says it's an ESP32C3 Dev Module - when in fact they are ESP32-S3 boards
<img width="789" alt="Screen Shot 2022-04-26 at 3 58 01 pm" src="https://user-images.githubusercontent.com/3156212/165232878-7cb6660d-1bc0-4bf0-8c9e-6240fc84cd29.png">

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### Other Steps to Reproduce

Happens in 2.0.3RC1 as well.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by UnexpectedMaker** [comment]
Oh, actually, it works when `USB Mode` set to OTG - but not when it's set to HW CDC/Serial JTAG.
So just need the `HW CDC/Serial JTAG` path to also use the correct naming.

**Comment by me-no-dev** [comment]
@UnexpectedMaker we can not change the PID/VID of the integrated CDC/JTAG. We can only do it on the OTG peripheral. And both S3 and C3 have the same PID/VID so they show as the same board. It is not something we can adjust.

**Comment by UnexpectedMaker** [comment]
Ok, bummer, thanks for the confirmation @me-no-dev !
