### ISSUE TITLE
enroll_face_id_to_flash_with_name  return -2

### ISSUE THREAD

**Issue by davidbcf** [espressif/arduino-esp32#6637]
### Board

ESP32-S2

### Device Description

ESP32-CAM 

### Hardware Configuration

4 pins：5V ，U0R ， UOT ，GND

### Version

v1.0.6

### IDE Name

Arduino IDE

### Operating System

win 10

### Flash frequency

80

### PSRAM enabled

yes

### Upload speed

115200

### Description

enroll_face_id_to_flash_with_name  return -2 

E (8869) fr_flash: Not found
Camera Ready! Use 'http://10.8.4.177' to connect
enroll_face 2
enroll_face 1
E (28570) fr_flash: Not found
enroll_face -2
enroll_face 2
enroll_face 1

### Sketch

```cpp
static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)
{
  ESP_LOGD(TAG, "START ENROLLING");
  int left_sample_face = enroll_face_id_to_flash_with_name(face_list, new_id, st_name.enroll_name);
  ESP_LOGD(TAG, "Face ID %s Enrollment: Sample %d",
           st_name.enroll_name,
           ENROLL_CONFIRM_TIMES - left_sample_face);
  Serial.print("enroll_face ");
  Serial.println(left_sample_face);
  return left_sample_face;
}
```

### Debug Message

```plain
E (5872) fr_flash: Not found
Camera Ready! Use 'http://10.8.4.177' to connect
[D][face_test.ino:213] do_enrollment(): START ENROLLING
[D][face_test.ino:217] do_enrollment(): Face ID 1 Enrollment: Sample 1
enroll_face 2
[D][face_test.ino:213] do_enrollment(): START ENROLLING
[D][face_test.ino:217] do_enrollment(): Face ID 1 Enrollment: Sample 2
enroll_face 1
[D][face_test.ino:213] do_enrollment(): START ENROLLING
E (24797) fr_flash: Not found
[D][face_test.ino:217] do_enrollment(): Face ID 1 Enrollment: Sample 5
2
[D][face_test.ino:213] do_enrollment(): START ENROLLING
[D][face_test.ino:217] do_enrollment(): Face ID 1 Enrollment: Sample 1
enroll_face 2
[D][face_test.ino:213] do_enrollment(): START ENROLLING
[D][face_test.ino:217] do_enrollment(): Face ID 1 Enrollment: Sample 2
enroll_face 1
```

### Other Steps to Reproduce

no other steps 

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by davidbcf** [comment]
how to solve the problem : @return -2                   Flash partition not found

**Comment by me-no-dev** [comment]
1.0.6 is no longer supported and the face recognition library has since changed much. Unfortunately Face Recognition is also no longer supported on ESP32 and ESP32-S2. My Guess is that you are missing a "data" partition with name "fr" to save the faces.

**Comment by me-no-dev** [comment]
Here is an example partition scheme for 4MB camera support (but on the new version): https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/Camera/CameraWebServer/partitions.csv

I do not guarantee  that it will work, but this is what the error suggests. Did you try the CameraWebServer example?

**Comment by davidbcf** [comment]
i tryed this partition below, it seems like error occured when save info the  3th time.

enroll_face 2
enroll_face 1
E (141165) fr_flash: Not found
enroll_face -2
enroll_face 2
enroll_face 1
E (144223) fr_flash: Not found
enroll_face -2
![image](https://user-images.githubusercontent.com/42029408/165666623-ffa33a18-962a-4849-bcb2-74db2ea4545e.png)



i tryed  CameraWebServer example, when open Face Detetion ,it crashed....

![image](https://user-images.githubusercontent.com/42029408/165668702-ed97a5fc-7994-4c78-8a54-bb9b74c20576.png)

**Comment by davidbcf** [comment]
is somewhere  i can find the definition table  of flash type, flash subtype and flags?

**Comment by me-no-dev** [comment]
CameraWebServer is working with github master of this repo. You will have it working when we release 2.0.3

**Comment by me-no-dev** [comment]
Closing because 2.0.3 is released.

**Comment by me-no-dev** [comment]
@jlarnal you should ask this question in the esp-dl repo: https://github.com/espressif/esp-dl

**Comment by jlarnal** [comment]
Thanks for the Link @Me_No_Dev

I will ask this question there, if it isn't answered yet. 😊👍

**Comment by QianZhongLi** [comment]
this will be ok，without partition not found error
![分区表说明](https://github.com/espressif/arduino-esp32/assets/108188447/fbe92d8a-f769-490a-8eb0-e17c6b337302)



# Name,   Type,  SubType, Offset,   Size,    Flags
nvs,      data,  nvs,     0x9000,   0x5000,
otadata,  data,  ota,     0xe000,   0x2000,
app0,     app,   ota_0,   0x10000,  0x3d0000,
fr,0x20,0x20,  0x3e0000, 0x20000,
![image](https://github.com/espressif/arduino-esp32/assets/108188447/334b6f54-3459-4e0a-ad6e-947d6b8be545)
