### ISSUE TITLE
SPI init Error

### ISSUE THREAD

**Issue by South-River** [espressif/arduino-esp32#6641]
### Board

ESP-S3-12K-kit

### Device Description

ESP-S3-12K-kit

### Hardware Configuration

spi
GPIO37 - MISO
GPIO36 - SCLK
GPIO35 - MOSI
GPIO34 - CS0
GPIO33 - CS1

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

240Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

Hi!
SPI.begin() can't being correctly executed. I managed to print "Hello" through Serial.println() before, and try to use SPI to communicate with my sensors. 
But it continuously send me messages I don't know(Is it continuous boot and reboot?)
I want to know how to correctly use I2C and SPI to link my devices to this board
Below are my code
```
/* Definition of SPI Pins */
#define HSPI_MISO 31//19 
#define HSPI_MOSI 29//23 
#define HSPI_SCLK 30 
#define HSPI_CS0 28 // accel chip
#define HSPI_CS1 27 // gyro chip

SPIClass hspi(HSPI);
/* accel object */
BMI085Accel accel(hspi,HSPI_CS0);
/* gyro object */
BMI085Gyro gyro(hspi,HSPI_CS1);

void setup() 
{
  /* SPI init */
  hspi.begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_CS0); //SCLK, MISO, MOSI, SS 
  hspi.begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_CS1); //SCLK, MISO, MOSI, SS 
  int status;
  /* USB Serial to print data */
  Serial.begin(115200);
  Serial.println("Hello");
}
```
![QQ图片20220427175103](https://user-images.githubusercontent.com/52597530/165492084-76a5b2c3-f822-47ec-bbab-7080bdfa0bcd.png)
.

### Sketch

```cpp
/* Definition of SPI Pins */
#define HSPI_MISO 31//19 
#define HSPI_MOSI 29//23 
#define HSPI_SCLK 30 
#define HSPI_CS0 28 // accel chip
#define HSPI_CS1 27 // gyro chip

SPIClass hspi(HSPI);
/* accel object */
BMI085Accel accel(hspi,HSPI_CS0);
/* gyro object */
BMI085Gyro gyro(hspi,HSPI_CS1);

void setup() 
{
  /* SPI init */
  hspi.begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_CS0); //SCLK, MISO, MOSI, SS 
  hspi.begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_CS1); //SCLK, MISO, MOSI, SS 
  int status;
  /* USB Serial to print data */
  Serial.begin(115200);
  Serial.println("Hello");
}
void loop()
{}
```

### Debug Message

```plain
ehhhh? Maybe this is not useful?
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
You are trying to use SPI on pins that are for the internal Flash/PSRAM. Try other pins :)
