### ISSUE TITLE
MacAddress.h

### ISSUE THREAD

**Issue by mrengineer7777** [espressif/arduino-esp32#6658]
### Related area

WiFi Library

### Hardware specification

ESP32, no specific hardware

### Is your feature request related to a problem?

I'm finding handling BSSID info to be a pain.  Parsing from string, printing to string, saving, checking if null, etc.  Is there a library for BSSIDs/MAC like IPAddress.cpp/h?

If not, I will create one patterned after IPAddress.cpp/h and submit a PR.

Just making sure I'm not duplicating work, and I'd like to know if this would be useful to others.

### Describe the solution you'd like

Say yes and I'll write a library and submit a PR.  I just don't want to waste my time and yours if a solution already exists.

### Describe alternatives you've considered

Searched Google extensively and didn't find functions to handle BSSID/mac within ESP32/arduino

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by mrengineer7777** [comment]
I've started writing a library because it will make our project cleaner.

**Comment by dpnebert** [comment]
I’m not sure if it is what you are looking for, but my PR for getting the MAC addresses was just merged.  #8618
