### ISSUE TITLE
SPI bus inconsistency

### ISSUE THREAD

**Issue by reaper7** [espressif/arduino-esp32#666]
I looked at the SPI lib source files
and I found some inconsistency:
https://github.com/espressif/arduino-esp32/blob/master/libraries/SPI/src/SPI.h#L54
set default spi bus to HSPI

but inside cpp file:
https://github.com/espressif/arduino-esp32/blob/master/libraries/SPI/src/SPI.cpp#L278
spi bus is set to VSPI

Is it correct?

**Comment by nepeee** [comment]
In the first file, the HSPI is just a default value for the constructor so the VSPI is used by default.

**Comment by me-no-dev** [comment]
And i will probably need to move both to HSPI because os PSRAM support, which was not in the picture when the driver was written :)

**Comment by reaper7** [comment]
@nepeee thanks for the explanation ;)
@me-no-dev 👍
