### ISSUE TITLE
Problem with ssid and netwrok connection in latest version

### ISSUE THREAD

**Issue by roysG** [espressif/arduino-esp32#6660]
### Board

esp32 dev module

### Device Description

Devkit

### Hardware Configuration

none

### Version

latest development Release Candidate (RC-X)

### IDE Name

arduino ide

### Operating System

mac OS Monetery

### Flash frequency

80mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

I have code that run for 1 year without any problem.

Yesterday, i install the latest version in other computer (windows) and i start to get annoying 2 problems.

1. the ssid length of wifi shorter to 31 instead of 32 characters!
2.  I am working with mqtt library call: "TinyGsm" and "[PubSubClient](https://pubsubclient.knolleary.net/)"
   And i am getting someting like 30 sec to 1.5 minutes error of "Unhandled" networks errors.

It is very important to understand that when the same code is compiles with your 1 of your older version, everthing run smoothly and without any problem!

Please assist me to understand how to know which old version of your library is installed in my old computer.
I Followed by your instructions and installed the library by add some url line in the prefernces, and then install it.

How can i track which old versions is installed in my end?

Thanks.

### Sketch

```cpp
```

### Debug Message

```plain
No i do not have
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment]
Without a example sketch or more details it is not possible to help.
