### ISSUE TITLE
I2S_FIFO_WR_REG & I2S_FIFO_WR_REG undefined in sdk

### ISSUE THREAD

**Issue by HoverClub** [espressif/arduino-esp32#6662]
### Board

WeMOS D1 mini ESP32

### Device Description

none

### Hardware Configuration

GPIO 22, 25, 26 connected to I2S bck, wr & data

### Version

v2.0.2

### IDE Name

PlatformIO

### Operating System

Linux

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

500000

### Description

As it says in the title the I2S_FIFO_WR_REG & I2S_FIFO_WR_REG aren't defined in the SDK.  These regs are documented in the tech ref manual 12.7 and actually work correctly at those addresses.

### Sketch

```cpp
// Any ref to I2S0(or 1).fifo_wr or I2S0(or 1).fifo_rd fails to compile.
```

### Debug Message

```plain
Compiling .pio/build/wemos_d1_mini32/src/testfifo1.cpp.o
src/testfifo1.cpp: In function 'void i2s_init()':
src/testfifo1.cpp:189:10: error: 'i2s_dev_t' {aka 'volatile struct i2s_dev_s'} has no member named 'fifo_wr'
     I2S0.fifo_wr = 0x44993388; // init some data for testing
          ^~~~~~~~~~~
*** [.pio/build/wemos_d1_mini32/src/testfifo1.cpp.o] Error 1
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
This is a purely esp-idf question, so I would recommend you ask [there](https://github.com/espressif/esp-idf/issues)
The header for that struct is at https://github.com/espressif/esp-idf/blob/master/components/soc/esp32/include/soc/i2s_struct.h
