### ISSUE TITLE
DNSServer memory leak

### ISSUE THREAD

**Issue by alex-code** [espressif/arduino-esp32#6663]
### Board

DFRobot FireBeetle2

### Device Description

None

### Hardware Configuration

None

### Version

v2.0.2

### IDE Name

PlateformIO

### Operating System

Win11

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

115200

### Description

A project I'm working on uses `DNSServer` on demand and I noticed a memory leak.

Memory is allocated in the `DNSServer` class constructor but there's no destructor to free it.

https://github.com/espressif/arduino-esp32/blob/master/libraries/DNSServer/src/DNSServer.cpp#L16
https://github.com/espressif/arduino-esp32/blob/master/libraries/DNSServer/src/DNSServer.cpp#L17

### Sketch

```cpp
None
```

### Debug Message

```plain
None
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment]
That's true.  Several libraries have that issue.  However since DNSServer is generally only called once and then remains in memory, it is basically a global allocation.  If it really bothers you, write the destructor and submit a PR.

**Comment by SuGlider** [comment]
> That's true. Several libraries have that issue. However since DNSServer is generally only called once and then remains in memory, it is basically a global allocation. If it really bothers you, write the destructor and submit a PR.

I think it would be good to review the whole code and fix these similar issues.
Thanks @alex-code for reporting!

**Comment by alex-code** [comment]
> That's true. Several libraries have that issue. However since DNSServer is generally only called once and then remains in memory, it is basically a global allocation. If it really bothers you, write the destructor and submit a PR.

It may typically be used globally but if it allocates memory it should really free it too.

I don't mind doing a PR for allocations that need freeing if it'll be useful.

**Comment by SuGlider** [comment]
@alex-code - PR #6707 shall fixes it. 
Please let me know if you can confirm that it solves this issue.

**Comment by alex-code** [comment]
> @alex-code - PR #6707 shall fixes it. Please let me know if you can confirm that it solves this issue.

Looks good to me, testing again with the changes the free memory reported before construction is the same after destroying 👍

**Comment by SuGlider** [comment]
@alex-code - Thanks for testing and confirming the resolution of this issue.
