### ISSUE TITLE
Disable Brown Out

### ISSUE THREAD

**Issue by gamecompiler** [espressif/arduino-esp32#675]
### Description:
Hi, i would like to disable or change the Brownout detection level.

How can i do that using arduino-esp32? 
Using espressifs dev kit i was able to do that using makeconfig, but how im able to do this in Arduino?

Thanks in advance,
gamecompiler

**Comment by me-no-dev** [comment]
its a compile time setting in idf (menuconfig) so for you to change it you need to use arduino as idf component. can not be done dynamically in Arduino itself :) idf is prebuilt here
