### ISSUE TITLE
Services are duplicating when 16-bit UUID Number is used for a service

### ISSUE THREAD

**Issue by aarbmx6s** [espressif/arduino-esp32#6750]
### Board

DOIT ESP32 DEVKIT V1

### Device Description

DOIT ESP32 DEVKIT V1

### Hardware Configuration

Nothing attached

### Version

v2.0.2

### IDE Name

Arduino IDE

### Operating System

macOS 12.3.1

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

Hi there!

I am faced with the situation when service UUID is a 16-bit UUID Number taken from the official specifications document, for example, `0x180D` (`"180D"`), and the LightBlue app shows that peripheral has 2 services:

![image](https://user-images.githubusercontent.com/22832351/168492927-54255ba0-c6d2-41c1-836b-b49307e52ec5.png)

Inside the peripheral device in the advertisement section UUIDs of service are displayed twice:

![image](https://user-images.githubusercontent.com/22832351/168492997-1d8f027c-876d-4763-85f1-2e1928078488.png)

[I used the next example ](https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/examples/BLE_server/BLE_server.ino) where I replaced UUIDs on my own.

When service UUID is random (like in the example) everything is OK.

### Sketch

```cpp
/*
    Based on Neil Kolban example for IDF: https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLE%20Tests/SampleServer.cpp
    Ported to Arduino ESP32 by Evandro Copercini
    updates by chegewara
*/

#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>

// See the following for generating UUIDs:
// https://www.uuidgenerator.net/

#define SERVICE_UUID        "180D"
#define CHARACTERISTIC_UUID "2A19"

void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE work!");

  BLEDevice::init("Long name works now");
  BLEServer *pServer = BLEDevice::createServer();
  BLEService *pService = pServer->createService(SERVICE_UUID);
  BLECharacteristic *pCharacteristic = pService->createCharacteristic(
                                         CHARACTERISTIC_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_WRITE
                                       );

  pCharacteristic->setValue("Hello World says Neil");
  pService->start();
  // BLEAdvertising *pAdvertising = pServer->getAdvertising();  // this still is working for backward compatibility
  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->addServiceUUID(SERVICE_UUID);
  pAdvertising->setScanResponse(true);
  pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
  pAdvertising->setMinPreferred(0x12);
  BLEDevice::startAdvertising();
  Serial.println("Characteristic defined! Now you can read it in your phone!");
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(2000);
}
```

### Debug Message

```plain
-
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by podaen** [comment]
Don't use those, generate your own uuid.

https://www.uuidgenerator.net/

**Comment by VojtechBartoska** [comment]
is this still valid @aarbmx6s?

**Comment by aarbmx6s** [comment]
@VojtechBartoska I was playing around with the different configurations and found that the application Light Blue on macOS and iOS sometimes showed even very old UUID with old descriptions. I may suppose it is may a problem with cashing devices/services in the  bluetooth of the device.

**Comment by lyusupov** [comment]
> is this still valid ?

the issue **still remain in 2.0.9**

![](https://github.com/espressif/arduino-esp32/assets/5849637/61dcccca-d1ec-40e2-a19e-7a967c18b479)
![](https://github.com/espressif/arduino-esp32/assets/5849637/aa74931b-f538-47da-88ce-84034fd4a8bf)

**16-bit UUIDs are the only affected**. ( 128 bit UUIDs are doing good )

**Comment by lucasssvaz** [comment]
I can confirm that this still happens in version 2.0.12. I'll take a look to see if I can find the cause of the problem.

**Comment by SuGlider** [comment]
In order to have both 16-bit UUIDs listed only one time:

``` cpp
void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE work!");

  BLEDevice::init("Long name works now");
  BLEServer *pServer = BLEDevice::createServer();
  BLEService *pService = pServer->createService(SERVICE_UUID);
  BLECharacteristic *pCharacteristic = pService->createCharacteristic(
                                         CHARACTERISTIC_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_WRITE
                                       );

  pCharacteristic->setValue("Hello World says Neil");
  pService->start();
  // BLEAdvertising *pAdvertising = pServer->getAdvertising();  // this still is working for backward compatibility
  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();

  //=======>>>> replacing this part of the code:
  //pAdvertising->addServiceUUID(SERVICE_UUID);
  BLEAdvertisementData BLEAdvData;
  BLEAdvData.setCompleteServices(BLEUUID(SERVICE_UUID));
  pAdvertising->setAdvertisementData(BLEAdvData);
  
  pAdvertising->setScanResponse(true);
  pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
  pAdvertising->setMinPreferred(0x12);
  BLEDevice::startAdvertising();
  Serial.println("Characteristic defined! Now you can read it in your phone!");
}
```

**Comment by lyusupov** [comment]
##  Before

```
      pAdvertising->addServiceUUID(BLEUUID(UART_SERVICE_UUID16)); // 0xFFE0
      pAdvertising->addServiceUUID(BLEUUID(UUID16_SVC_BATTERY));  // 0x180F
      pAdvertising->addServiceUUID(BLEUUID(MIDI_SERVICE_UUID));   // 0x00C7C4...
```

## After

```
      BLEAdvData.setCompleteServices(BLEUUID(UART_SERVICE_UUID16)); // 0xFFE0
      BLEAdvData.setCompleteServices(BLEUUID(UUID16_SVC_BATTERY));  // 0x180F
      BLEAdvData.setCompleteServices(BLEUUID(MIDI_SERVICE_UUID));   // 0x00C7C4...
```

## Results

![](https://github.com/espressif/arduino-esp32/assets/5849637/dab68d44-38f0-43fe-bbf2-b069c118058e)

**Comment by SuGlider** [comment]
@lyusupov 
 For your case I'd suggest this workaround:
 
 ```cpp
  //=======>>>> replacing this part of the code:
  //pAdvertising->addServiceUUID(SERVICE_UUID);
  
  uint8_t advData[] = {
    //  Complete List of two 16-bit UUIDs 0xFFE0 0x180F
    0x05, 0x03, 0xE0, 0xFF, 0x0F, 0x18, // two 16bits UUIDs
    // Complete List of 128bits UUID 03B80E5A-EDE8-4B33-A751-6CE34EC4C700
    0x11, 0x07, 
    0x00, 0xC7, 0xC4, 0x4E, 0xE3, 0x6C, 0x51, 0xA7, 
    0x33, 0x4B, 0xE8, 0xED, 0x5A, 0x0E, 0xB8, 0x03,
  };

  BLEAdvertisementData BLEAdvData;
  BLEAdvData.setFlags(0x06);
  BLEAdvData.addData(std::string((const char*)advData, sizeof(advData)));
  BLEAdvData.setName("SoftRF-5f5cb0-LE");
  pAdvertising->setAdvertisementData(BLEAdvData);
  BLEDevice::setPower(ESP_PWR_LVL_P3);
 ```

**Comment by SuGlider** [comment]
@lyusupov - Does it solve your need?

**Comment by lyusupov** [comment]
@SuGlider 
Yes, explicit
```
BLEAdvData.setFlags(0x06);
```
gives positive effect necessary.
Thanks for the tip!

**Comment by SuGlider** [comment]
@aarbmx6s @lyusupov @lucasssvaz 

Reading the code from Arduino and from IDF examples, I have concluded that, by default, BLE will send Advertising Data with UUID information and also send the Advertising Response with the same information.

BLE 4.2 has about 62 bytes for advertising information.
31 bytes for the main Advertising data block and another 31 for the Advertising Response data block. 
**Most BLE scanning tools will show both data block as one, creating an ilusion that it is duplicated, but actually, it is not.**

In order to "do not duplicate information", it is necessary to add (or replace) this line:
` pAdvertising->setScanResponse(true); // this is the dafault value` by 
` pAdvertising->setScanResponse(false);`

Doing it, the UUID will show up just once in both Advertising Data blocks.
"The duplication" doesn't create any problem for the central BLE device.
The user can also create a customized Advertising Data and/or Advertising Response Data, to add more information, like a more UUIDs or Manufacturer data, for instance, .

Therefore, there is no issue here to be solved.

**Comment by lucasssvaz** [comment]
@SuGlider That's great news. Thanks for the investigation!

**Comment by trullock** [comment]
@SuGlider Am I missing something here? `pAdvertising->setScanResponse(false)` makes the UUID not show up at all in the scan response. If you pass `true` it shows up twice as above...
