### ISSUE TITLE
On Fatfs time zone is ignored on file time

### ISSUE THREAD

**Issue by luc-github** [espressif/arduino-esp32#679]
Hi when using fatfs function f_stat to get last access date/time I found time zone is ignored and only UTC time is given

I did a script to show issue on SD : https://gist.github.com/luc-github/9124cbb2b1e0ed0b3696b4e6223b8e6e

**Comment by luc-github** [comment]
After investigation it seems the function to get timestamp in libfatfs : `get_fattime`
use `gmtime` instead of `localtime_r` but this part is in IDF

**Comment by me-no-dev** [comment]
you can submit an issue or pr there :) those are looked at and taken care of as well :)

**Comment by luc-github** [comment]
Yes I am currently setting up the environnement to compile IDF to test first - so I will be able to do PR 😄

**Comment by me-no-dev** [comment]
put arduino as component and set up under sloeber/eclipse :) you might like it

**Comment by luc-github** [comment]
Ok will try it thank you- I get used to geany (http://www.geany.org/)  which is  a light cross platform  code editor

**Comment by me-no-dev** [comment]
sure :D whatever floats your boat :P

**Comment by luc-github** [comment]
I cannot for some unknown reason compile using arduino-esp32 as ESP-IDF component but was able to get modified libfatfs.a and replaced  arduino-esp32 one
and it works so fix is confirmed I will do PR on IDF later

**Comment by luc-github** [comment]
PR done

**Comment by luc-github** [comment]
wow seems this issue is still open - I close it sorry for the delay
