### ISSUE TITLE
LED Intensity support is missed in the example CameraWebServer

### ISSUE THREAD

**Issue by DmytroKorniienko** [espressif/arduino-esp32#6790]
### Board

ESP32-CAM

### Device Description

CAMERA_MODEL_AI_THINKER ESP32-CAM

### Hardware Configuration

GPIO_NUM_4 // GPIO_NUM_4 = 4

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

win10

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

![image](https://user-images.githubusercontent.com/26786760/169807797-8a1f16e3-f329-4254-a4f4-f260e0763890.png)

LED Intensity support is missed, moreover brownout detector was triggered raised periodically for CAMERA_MODEL_AI_THINKER ESP32-CAM

### Sketch

```cpp
https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer
```

### Debug Message

```plain
Brownout detector was triggered
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment]
Brownout trigger is not a software issue. It is a function in the ESP32 chip which triggers when the needed power supply voltage is under 3.3V

**Comment by DmytroKorniienko** [comment]
@Jason2866 Agree, but this issue is typical for a CAMERA_MODEL_AI_THINKER ESP32-CAM board, even if power supply is good enough. So my suggestion - disable this detection for this particular board.

**Comment by Jason2866** [comment]
I have this board too. It does work well with a good power supply. Not a single brownout.
Disable brownout detection is not a good idea. Power problems creates weird issues.

**Comment by DmytroKorniienko** [comment]
@Jason2866 If you will use intensive WiFi exchange of 1600*1200 streams with a enabled led you might got this too. Are you ever tried measure power consumption at different cases with multimeter & oscilloscope for this board? Onboard AMS1117 weak and not stable.

**Comment by Jason2866** [comment]
I use highest possible resolution. Powering the device with a extern 3.3V power supply.
When lowering the resolution the onboard AMS1117 is capable to deliver.
So you just said the same it is a hardware issue. It is no solution to change the brownout detection.

**Comment by SuGlider** [comment]
@DmytroKorniienko 
Regarding disabling brownout, I think it won't happen for the ESP Arduino Framework. Check #675
Doing it may lead to unpredictable new issues.

But you can do it in your own personal project when using Arduino as Component in an IDF project.
Or you can also create your own precompiled libraries using Arduino Lib Builder.
In both cases, brownout can be disabled using IDF Menuconfig 
(make menuconfig -> Component Config -> ESP32-specific -> Hardware brownout detect & reset)


#### Other Brownout discussions at 
https://github.com/nkolban/esp32-snippets/issues/168
https://www.esp32.com/viewtopic.php?t=2462
https://github.com/espressif/arduino-esp32/issues/863

#### SW way to disable it - not tested
**use at your own risk**  https://github.com/espressif/arduino-esp32/issues/863#issuecomment-671055308

**Comment by DmytroKorniienko** [comment]
> SW way to disable it - not tested

Why you think so? I made a lot of my own tests and can provide screenshot with more than month uptime.

![Screenshot_2021-12-15-09-12-36-533_com android chrome](https://user-images.githubusercontent.com/26786760/170133408-ea6edab5-679a-4c00-b75d-0a7bb6ccee2f.jpg)

You can find this project in my repo and check by yourself :).

**Comment by SuGlider** [comment]
>Why you think so? I made a lot of my own tests and can provide screenshot with more than month uptime.

Ok, I didn't test it myself - just that. 
But if you say so, I believe you :-)

**Comment by rodyeo** [comment]
The ESP32-CAM Flight Light LED Illuminator solution which everyone is awaiting is now resolved by the blog author and programmer Bye Renzo

https://www.mischianti.org/forums/topic/esp32-cam-upgrade-camerawebserver-with-flash-on-esp32-framework-2-0-4/

Thank you ;)

**Comment by PUPPY98** [comment]
Does anybody know the details of the Flash led . like name?
