### ISSUE TITLE
WPA3 not shown correctly with verbose output

### ISSUE THREAD

**Issue by Rotzbua** [espressif/arduino-esp32#6792]
### Board

nodemcu

### Device Description

normal board

### Hardware Configuration

normal config

### Version

v2.0.3

### IDE Name

Arduino IDE

### Operating System

win

### Flash frequency

40

### PSRAM enabled

no

### Upload speed

11520

### Description

The verbose message does not show the encryption correctly, if new (WPA2-)WPA3 methods are used. Just `UNKNOWN` is shown.

The strings are missing:
https://github.com/espressif/arduino-esp32/blob/1a7962ece8a4c6ffa1d64c5a86ed8ee58dde10ba/libraries/WiFi/src/WiFiGeneric.cpp#L243-L268

### Sketch

```cpp
// regular
WiFi.begin("wifi", "password");
```

### Debug Message

```plain
[V][WiFiGeneric.cpp:295] _arduino_event_cb(): STA Connected: SSID: wifi, BSSID: xxxx, Channel: 1, Auth: UNKNOWN
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@Rotzbua - Thanks for reporting this issue.
I'll add a PR to fix it.
