### ISSUE TITLE
I2C wrong callback order on repeated start command

### ISSUE THREAD

**Issue by YehorFedorov** [espressif/arduino-esp32#6793]
### Board

ESP32 C3

### Device Description

ESPRESSIF ESP32 C3 mini 1

### Hardware Configuration

GPIO 5 - SDA
GPIO 6 - SCL

### Version

v2.0.3

### IDE Name

Arduino IDE

### Operating System

macOS Big Sur v 11.6.5

### Flash frequency

80 Mhz

### PSRAM enabled

no

### Upload speed

460800

### Description

I'm trying to establish communication via i2c between 2 esp32 c3 devices. The idea is simple, I want to send non stop request to slave (with repeated start), where master write 2 bytes first and read data from slave. And it's working somehow but not in the way I expected because slave firstly run onRequest callback and then onReceive. This looks like a bug for me (correct me if I'm wrong)

As a result I'm receiving data from previous request...

Attaching my wiring and logic analyzer data for 2 requests
![wiring](https://user-images.githubusercontent.com/29597884/170024424-1bdd4f83-820c-488d-aeb4-2ba7d57cb82b.jpeg)
![first_req](https://user-images.githubusercontent.com/29597884/170024418-c0d94d31-d0cb-45f1-bd8d-9ad504101691.jpeg)
![second_req](https://user-images.githubusercontent.com/29597884/170024430-3fed6c68-c0ff-493d-b442-1ed5c111f9d1.jpeg)

### Sketch

```cpp
### MASTER
#include "Wire.h"

#define I2C_DEV_ADDR 0x10

uint32_t i = 0;
int func = 0;
int reg = 10;

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  bool res = Wire.begin(5, 6, (uint32_t)400000);
  Serial.print("Connected: ");
  Serial.println(res ? "true" : "false");
}

void loop() {
  delay(5000);
  unsigned int first, second;

  //Write message to the slave
  Wire.beginTransmission(I2C_DEV_ADDR);
  Wire.write(func);
  Wire.write(reg);
  Wire.endTransmission(false);
  Wire.requestFrom(I2C_DEV_ADDR, 2, true);
  first = Wire.read();
  second = Wire.read();

  Serial.print("First: ");
  Serial.println(first);
  Serial.print("Second: ");
  Serial.println(second);

  Serial.print("Func: ");
  Serial.println(func);
  Serial.print("Register: ");
  Serial.println(reg);

  func++;
  reg++;
}


### SLAVE
#include "Wire.h"

#define I2C_DEV_ADDR 0x10

uint32_t i = 0;
uint8_t arr[2] = {0, 0};

void onRequest(){
  Wire.slaveWrite(arr, 2);
}

void onReceive(int len){
  arr[0] = Wire.read();
  arr[1] = Wire.read();
}

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Wire.onReceive(onReceive);
  Wire.onRequest(onRequest);
  Wire.begin((uint8_t)I2C_DEV_ADDR,5,6,(uint32_t)400000);
  Serial.println("SETUP");
}

void loop() {

}
```

### Debug Message

```plain
Connected: true

// FIRST REQUEST //
First: 0
Second: 0
Func: 0
Register: 10
// END //

// SECOND REQUEST //
First: 0
Second: 10
Func: 1
Register: 11
// END //
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@me-no-dev PTAL, thanks.

**Comment by me-no-dev** [comment]
Resolution is rather simple. Do not use repeated start :)
The ESP I2C slave peripheral will not execute the transaction until you also `requestFrom` which can cause some issues in the ISR and order of things. Not using repeated start will ensure that `onReceive` is called first.
Any reason to chose repeated start?

**Comment by YehorFedorov** [comment]
I just thought it's a better soulution rather than 2 separate requests :)
I'm just wondering if it's only esp related problem?

Because I've spend a lot of time researching this issue and I saw that there are some i2c slave devices that working with repeated start

**Comment by me-no-dev** [comment]
It is ESP related "problem" when both devices are ESPs. Catching the repeated start as Slave is rather complicated and that coupled with the way that the master sends the transaction could get you in such situation. Using separate write and read transactions (not calling `Wire.endTransmission` with `false`) would allow the slave to properly detect each step, extract/fill that data you want and so on.

**Comment by YehorFedorov** [comment]
Thanks, @me-no-dev !

Closing this issue

**Comment by albertlt** [comment]
Hi, I have exactly the same problem. Basically, after writing to slave, master always receive previous result. I used serial output on the slave and everything seems to be in correct order but master always receive previous "requestFrom" result. Is this not fixed? I used Wire.endTransmission() and tried both requestFrom(I2C_DEV_ADDR, 2) and requestFrom(I2C_DEV_ADDR, 2, true) without success. So frustrated, I hope someone can shed some lights.

**Comment by albertlt** [comment]
Also in my case, I did write and read from master twice consecutively and it seems that the slave haven't finish preparing the data on the second request and I received partly "⸮⸮⸮⸮⸮" jibberish data. Adding delay(1000) in between each write read sequence seems to fix the issue although the order of result is still incorrect as described above. Is there an elegant way for Master device to properly wait until slave is ready instead of predicting the processing time using delay?

**Comment by YehorFedorov** [comment]
Hi @albertlt!
What boards do you use for master and slave?

**Comment by albertlt** [comment]
Hi. Both are esp32


Sent from Yahoo Mail for iPhone


On Monday, July 11, 2022, 20:59, YehorFedorov ***@***.***> wrote:




Hi @albertlt!
What boards do you use for master and slave?

**Comment by albertlt** [comment]
I used: "esptool.py chip_id" and found out the master is: ESP32-D0WDQ6-V3 (revision 3) and slave is:  ESP32-PICO-D4 (revision 1).  Are they affected by the issue that you mentioned?

**Comment by albertlt** [comment]
By the way, is there any method in Wire to clear everything in it's buffer? I tried Wire.flush() on slave at the end of each session but it doesn't seem to work as it still gave me the previous result every time I start a new request from master.

**Comment by albertlt** [comment]
The flow of my program is as follow:

1. Master send cmd 1.
2. Slave decode in onReceive() and put result in a global variable: strResult.
3. Master request result of cmd 1 ( Assume strResult = "abc" )
4. Slave send the content of strResult in onRequest().
5. Master send clear cmd after retrieving the result.
6. Slave set strResult = "" and execute Wire.flush() in onReceive().

Several minutes later, master send cmd 2 with expected result = "def" but I still get "abc" even though strResult was already cleared at the end of previous iteration. It seems that "previous result" was still stored somewhere in the Wire library. I'd like to clear it if possible.

**Comment by RaghuRamaBL** [comment]
hello hi i am also facing same issue can you please let me know whether you have got any solution

**Comment by Pepito-design** [comment]
Have a similar problem with ESP32 S3 I2C  master <-> slave.  
Adruino IDE, version 2.3.6
Bibliothek Wire in Version 3.3.2
.arduino15/packages/esp32/hardware/esp32/3.3.2

Chip type:              ESP32-S3 (QFN56) (revision v0.2)
Features:               Wi-Fi, BT 5 (LE), Dual Core + LP Core, 240MHz, Embedded Flash 4MB (XMC), Embedded PSRAM 2MB (AP_3v3)
Crystal frequency:  40MHz
USB mode:           USB-Serial/JTAG

Trying to get a float from slave.
It works great for some time ( pull-up's = 1,5k, 100kHz, 400kHz, 1,5MHz ). Problem is not related to SCK frequency.
Connection is 6cm, soldered, no bread board.
For a couple of minutes, everything looks ok. ( 5 transfers / sec, nothing else to do )
Slave address = 0x55
But then ... the master receives the slave address, shifted left by 1 +1 ( 0x55 => 0xab )
0101 0101 => 1010 1010 => 1010 1011
      0x55     =>       0xaa    =>     0xab

Think it's a known issue with the ESP32 S3 as I2C Slave.
I checked with different modules, always equal. 
Power is stable, no noise on it. ( checked with Tektronix THS730A )
SDA and SCL are looking great, no setup or hold violation.

Question is, what is to do? 

The slave ( twowire(1) job is finally to provide some temperatures ( OneWire ), voltages and digital inputs ( currently not active , use only test data ).
The first I2C ( twowire(0) ) channel of this device is I2C master for a A-D converter ( works perfect ).
The master job is to display the data on LCD, build human interface ( currently not active ).
Have to solve the I2C issue first.

**Comment by me-no-dev** [comment]
@Pepito-design please provide minimal sketches for both devices to replicate

**Comment by Pepito-design** [comment]
Thanks for very quick response.
Going to provide testcase for master and slave. 
ESP32-S3-zero modules.
Have a good day
