### ISSUE TITLE
SD mount failed on HSPI

### ISSUE THREAD

**Issue by tsctrl** [espressif/arduino-esp32#6801]
### Board

ESP32 Dev Module

### Device Description

DevKit

### Hardware Configuration

pin_spi_sck set to 14
pin_spi_miso set to 12
pin_spi_mosi set to 13
pin_sd_cs set to 32

### Version

v2.0.3

### IDE Name

IDF Component, Arduino IDE

### Operating System

Windows 10

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

Sorry for creating this issue at first. I have SD not working properly issue on HSPI. I have functioning sd connected to VSPI pin with VSPI definition but i am not able to mount it on HSPI pin as above.

On VSPI. sometime i need to reinsert the card if the sd conflicting with other SPI peripheral or not detected during boot and is successfully mounted. It is not free from issue but it works. I have recently using LAN8072 that using VSPI pin and required to use HSPI pin for the sd operation. I am still using arduino SPI class without creating new VSPI bus class. 

I have added 3.7k pull up to miso, removing the bootstap pin on MISO GPIO12. reusing old sd library but no success.
 tested on master branch and also 2.0.3 branch with the same result.

Thanks at the earliest!

### Sketch

```cpp
/*
 * Connect the SD card to the following pins:
 *
 * SD Card | ESP32
 *    32       CS
 *    13      MOSI
 *    GND      GND
 *    VDD      3.3V
 *    14      SCK
 *    12       MISO
 */
 
#include "FS.h"
#include "SD.h"
#include "SPI.h"

void setup(){
    Serial.begin(115200);
    SPI.begin(14, 12, 13, 15);
    if(!SD.begin(32, SPI, 4000000)){
        Serial.println("Card Mount Failed");
        return;
    }
    uint8_t cardType = SD.cardType();
    if(cardType == CARD_NONE){
        Serial.println("No SD card attached");
        return;
    }
}

void loop(){}
```

### Debug Message

```plain
on mount failed:
[ 22341][E][sd_diskio.cpp:801] sdcard_mount(): f_mount failed: (13) There is no valid FAT volume
[ 22342][W][sd_diskio.cpp:174] sdCommand(): no token received
Card Mount Failed

if no card inserted:
I (22004) gpio: GPIO[32]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
[ 20741][W][sd_diskio.cpp:174] sdCommand(): no token received
[ 20845][W][sd_diskio.cpp:174] sdCommand(): no token received
[ 20945][W][sd_diskio.cpp:174] sdCommand(): no token received
[ 21044][E][sd_diskio.cpp:199] sdCommand(): Card Failed! cmd: 0x00
[ 21045][W][sd_diskio.cpp:515] ff_sd_initialize(): GO_IDLE_STATE failed
[ 21048][E][sd_diskio.cpp:801] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
[ 21058][W][sd_diskio.cpp:174] sdCommand(): no token received
[ 21164][W][sd_diskio.cpp:174] sdCommand(): no token received
[ 21264][W][sd_diskio.cpp:174] sdCommand(): no token received
[ 21364][E][sd_diskio.cpp:199] sdCommand(): Card Failed! cmd: 0x00
```

### Other Steps to Reproduce

Tested on VSPi with default SPI pin and is working

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
See https://github.com/espressif/arduino-esp32/blob/master/libraries/SPI/examples/SPI_Multiple_Buses/SPI_Multiple_Buses.ino for an example of how to create and begin an SPI bus object.  Also, you create the SPI bus with CS as pin 15, then use SD on pin 32....

**Comment by tsctrl** [comment]
hi @lbernstone,
SPI has other module that using pin 15, sd CS is on pin 32. this is not an issue for VHSPI. or i have to begin SPI 2 times with different cs?
if using build in SPI Class causing issue? i will try to create HSPI class bus and try.

**Comment by lbernstone** [comment]
It is not exactly an issue, but I pointed it out as a possible problem.  It suggests that you are complicating matters that you did not explain in your issue.  Make sure that you are testing this on its own, and that the SD is working on HSPI before you connect another device.  I would also say that trying to have multiple data-heavy devices on a single SPI bus (eg SD and OLED display) is going to give you suboptimal performance on both if they are running simultaneously.

**Comment by tsctrl** [comment]
sure, i have pull out all slave and left only sd on cs 15 with the same issue.

I (23261) gpio: GPIO[15]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
[ 22005][E][sd_diskio.cpp:801] sdcard_mount(): f_mount failed: (13) There is no valid FAT volume
[ 22007][W][sd_diskio.cpp:174] sdCommand(): no token received

**Comment by lbernstone** [comment]
In your first post you said this was working on VSPI.  This is no longer the case?

**Comment by tsctrl** [comment]
vspi is working, with all the slave. but not on hspi.
![20220526_100106](https://user-images.githubusercontent.com/75555993/170400070-6d4ae9e2-f473-4f02-ab70-75577abe7b5a.jpg)

**Comment by tsctrl** [comment]
using HSPI class also failed:

```
#include "FS.h"
#include "SD.h"
#include "SPI.h"

SPIClass* hspi = NULL;
void setup(){
    Serial.begin(115200);
    hspi = new SPIClass(HSPI);
    hspi->begin(14, 12, 13, 15); //SCLK, MISO, MOSI, SS
    if(!SD.begin(15, *hspi, 200000)){
        Serial.println("Card Mount Failed");
        return;
    }
    uint8_t cardType = SD.cardType();
    if(cardType == CARD_NONE){
        Serial.println("No SD card attached");
        return;
    }
}

void loop(){}
```

**Comment by tsctrl** [comment]
hi all, @lbernstone ,

i am sorry to say that the issue was fixed. i have created the issue too early. i have reinstall esp32 arduino library to fix the issue and also had done a hard format the sd and it work now.

appreciate and thanks for the prompt response and your time.
