### ISSUE TITLE
int Comparison in loop inside header file failed.

### ISSUE THREAD

**Issue by jc999** [espressif/arduino-esp32#6845]
### Board

esp32doit-devkit-v1

### Device Description

esp32 on wemos d1. 

### Hardware Configuration

none.

### Version

v2.0.3

### IDE Name

PIO

### Operating System

macOS

### Flash frequency

40

### PSRAM enabled

no

### Upload speed

115200

### Description

Working code on 1.0.6, not working on 2.0.3
Test of int in a header file doesn't work in 2.0.3

Working on 
PLATFORM: Espressif 32 (3.5.0) > DOIT ESP32 DEVKIT V1

Not working on 
PLATFORM: Espressif 32 (4.4.0) > DOIT ESP32 DEVKIT V1

;platform = espressif32
platform = espressif32 @ ~3.5.0 

### Sketch

```cpp
main.c:------------------------------------------

#include <Arduino.h>
#include "test.h"

void setup() {
    Serial.begin(115200, SERIAL_8N1);

    testLoop(3);
    Serial.println("");
    Serial.println("done");

}

void loop() {
}


test.h----------------------------------------------------


#ifndef FXROUGE_H
#define FXROUGE_H

#include "Arduino.h"

uint16_t testCount = 6;


int testLoop(int quarter){
        uint8_t r = 0 ;
        while((uint8_t)r < (uint8_t)testCount){
            uint8_t test = ((uint8_t)r < (uint8_t)testCount);
            Serial.print(String(r) + "." + String(testCount) + " " + String(test) + " ");
            r++;
        }
}

#endif
```

### Debug Message

```plain
No error message.
Result expected:
----------------------------------
0.6 1 1.6 1 2.6 1 3.6 1 4.6 1 5.6 1 
done
----------------------------------
```

### Other Steps to Reproduce

just run the code. on the last version, the loop never ends and the r keep increasing.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by jc999** [comment]
I added all the cast for testing purpose. The loop was first a for statement, I tested a while with the same behaviour.

**Comment by bertmelis** [comment]
Omitting the return statement in a function which has a return type that is not void is undefined behaviour. So anything can happen and in this case "anything" means "and endless loop".

**Comment by jc999** [comment]
ok, just tested. This was ok on a previous version, but the return has to be included in the last version...
The ticket can be closed then, adding the return on the new version fix the behaviour difference.

**Comment by jc999** [comment]
linked to
[https://github.com/espressif/arduino-esp32/issues/5867](url)
