### ISSUE TITLE
BluetoothSerial  phone can pair but cannot connect

### ISSUE THREAD

**Issue by liangzhichao63** [espressif/arduino-esp32#6847]
### Board

ESP32 PICO KIT

### Device Description

ESP32 PICO KIT 

### Hardware Configuration

Empty development board

### Version

v1.0.6

### IDE Name

arduino ide

### Operating System

win10

### Flash frequency

40Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

Arduino  bluetoothserial code example, you can pair but cannot connect.

### Sketch

```cpp
#include "BluetoothSerial.h"

#if !defined(CONFIG_BT_ENABLED) || !defined(CONFIG_BLUEDROID_ENABLED)
#error Bluetooth is not enabled! Please run `make menuconfig` to and enable it
#endif

BluetoothSerial SerialBT;

void setup() {
  Serial.begin(115200);
  SerialBT.begin("ESP32test"); //Bluetooth device name
  Serial.println("The device started, now you can pair it with bluetooth!");
}

void loop() {
  if (Serial.available()) {
    SerialBT.write(Serial.read());
  }
  if (SerialBT.available()) {
    Serial.write(SerialBT.read());
  }
  delay(20);
}
```

### Debug Message

```plain
No Debug Message
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
have you tried with version 2.0.3?

**Comment by liangzhichao63** [comment]
Yes, I have. The connection works when using BLE.But the BluetoothSerial was not working properly.

**Comment by SuGlider** [comment]
@liangzhichao63

I have just made it work correctly with a ESP32-DevKit board and Arduino Core 2.0.3.
Basically, I just paired it in Win11 and then open the Device Manager to see the COM port associated to the Bluetooth Serial connection. Finally I open 2 Putty windows, one for the ESP32-UART and another for the Bluetooth COM port.

When I type in one of the Putty windows, it displays in the other one, as expected.

**Comment by SuGlider** [comment]
![image](https://user-images.githubusercontent.com/65977697/173081648-c59a144b-adb2-4c31-acde-25af8b062dd2.png)

![image](https://user-images.githubusercontent.com/65977697/173081796-088ba349-8bbc-4809-b3cb-52faf4a401c2.png)

**Comment by liangzhichao63** [comment]
It may be that the ESP32 PICO D4 chip is not adapted, thank you for helping me verify.

**Comment by VojtechBartoska** [comment]
@liangzhichao63 Can I consider this as solved?

**Comment by VojtechBartoska** [comment]
Closing as expired, explanation was provided and there were not further questions.
