### ISSUE TITLE
Support of ESP32-H2

### ISSUE THREAD

**Issue by VojtechBartoska** [espressif/arduino-esp32#6854]
This issue tracks support of [ESP32-H2](https://www.espressif.com/en/news/ESP32_H2) SoC.

Support will be breakdown into subtasks later.

**Main specifications of H2:**
ESP32-H2 combines important connectivity technologies, such as IEEE 802.15.4 radio connectivity, which is vital to mesh architectures with low power consumption. ESP32-H2 also makes the Thread and Zigbee protocols available, thus addressing a variety of cases in application development. Furthermore, Bluetooth LE supports point-to-point, broadcast and mesh communication topologies, while it also enables the direct communication between a smartphone and an ESP32-H2-based device.

The combined availability of IEEE 802.15.4 and Bluetooth LE connectivity enables building devices for the Matter protocol, which intends to bring interoperability for smart-home devices.

**Comment by MacSass** [comment]
Just out of curiosity: Is my understanding correct that this ESP32-H2 Soc would not feature any WIFI capability?
As much as I can read, this is not part of IEEE 802.15.4, right?

**Comment by me-no-dev** [comment]
correct @MacSass no WiFi :)

**Comment by Suxsem** [comment]
We are starting to see ESP32-H2 being sold on aliexpress at a reasonable price, it has the potential to disrupt the IoT segment with zigbee and matter-over-thread support. Arduino IDE support will be the sparkle to have this board becoming massively popular through makers, please think about adding it!

**Comment by TD-er** [comment]
IMHO is the C6 way more interesting as it has both 802.15.4 and WiFi.

**Comment by Suxsem** [comment]
Yes but usually you don't use two different radio channels for IoT devices. Furthermore, the H2 is already available and fills a big gap in DIY community for matter devices

**Comment by VojtechBartoska** [comment]
@TD-er We will add support for both in Arduino ESP32 Core, C6 & H2.

**Comment by TD-er** [comment]
Great!
That means I could add support for both at the same time in my project.
Saves a lot of time.

**Comment by P-R-O-C-H-Y** [comment]
## Table with Support overview

_We will keep this table up to date._

Date of last update: 3.7.2023

| **ESP32-H2 Support Overview**   |      |                |             |              |
|---------------------------------|:------------:|:--------------:|:-----------:|:------------:|
|          **Peripheral**         |   Assignee  |   **Testing**  | **Updates** | **Comments** |
|               ADC               | @P-R-O-C-H-Y |             |             | WIP on ESP-IDF side |
|          Ethernet  SPI          |              |                |             |  In progress  |
|               GPIO              | @P-R-O-C-H-Y |             |             |              |
|       I2C (Slave & Master)      |            |                |             |              |
|               I2S               |              |                |             |  In progress |
|             LEDC & PWM             |  @P-R-O-C-H-Y  | Fully OK |             |              |
|               RMT               |   @SuGlider  |            |             |              |
|               SPI               | @P-R-O-C-H-Y  |             |             |               |
|               TWAI              |              |                |             | run examples |
|           Temp. Sensor          | @P-R-O-C-H-Y  |           |             |              |
|               UART              |   @SuGlider  |              |             |              |
|         USB Serial/JTAG         |  @SuGlider |             |             |              |
|            SigmaDelta           | @P-R-O-C-H-Y |             |             |              |
| Timers (System/General-purpose) | @P-R-O-C-H-Y |                |             |              |
|           **General**           |              |                |             |              |
|              Wi-Fi              |               |              |             | not available |
|            Bluetooth            |  @SuGlider |            |             |              |
|           Bluetooth LE          |   @SuGlider  |             |             |              |
|             802.15.4  protocol  |              |                |             | support missing |
|              Thread             |              |                |             |  support missing |
|              Zigbee             |              |                |             |  support missing |
|              Power management |              |                |             |  under investigation |

**Comment by 229311JK** [comment]
I'd like to help w/this...

**Comment by VojtechBartoska** [comment]
@229311JK with what exactly? Support is available in latest Development 3.0.0-apha 3 release, you can test and use already ESP32-H2, we are working on the stable release right now.

**Comment by OgLocGreen** [comment]
When i was trying to use the BLE examples for the ESP32-H2 it uses the older [ESP32 BLE Arduino](https://www.arduino.cc/reference/en/libraries/esp32-ble-arduino/) and not the newer [Arduino BLE](https://www.arduino.cc/reference/en/libraries/arduinoble/).
Is this on purpose or is there a plan to switch to the Arduino BLE lib?

**Comment by 229311JK** [comment]
> @229311JK with what exactly? Support is available in latest Development 3.0.0-apha 3 release, you can test and use already ESP32-H2, we are working on the stable release right now.

working w/the ESP Thread/border Zigbee router V1.2...  Will be in touch...

**Comment by jlabrada71** [comment]
Hi, I'm trying to use the ESP32-H2 in Arduino IDE,
When I install the board lib 2.0.16 (the latest stable) using the stable link
https://espressif.github.io/arduino-esp32/package_esp32_index.json

The ESP32-H2 doesn't get listed in the boards list. What could I be missing?
What would be a work around for this?

**Comment by 229311JK** [comment]
Been distracted w/the Esp32 programming board 4-the 32-C6 module.  It's nice;  Within the US, we have some excellent vendors to get hard to acquire Espresif HW.

**Comment by xvolte** [comment]
Hello all
Is it available now?
Is there a way to test it?
I have a esp32-h2-mini-1 and would love to test it!

**Comment by jlabrada71** [comment]
> Hello all Is it available now? Is there a way to test it? I have a esp32-h2-mini-1 and would love to test it!
Follow the install steps in this page and you will be able to tested. I received mine last week an it worked like a charm.

https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html

**Comment by 229311JK** [comment]
> Hello all Is it available now? Is there a way to test it? I have a esp32-h2-mini-1 and would love to test it!

Here you go:  https://github.com/espressif/arduino-esp32/releases   Now the hard part, scroll down & read.

**Comment by 229311JK** [comment]
> Hello all Is it available now? Is there a way to test it? I have a esp32-h2-mini-1 and would love to test it!

Did you get this squared away yet?  Enjoy your H2...

**Comment by xvolte** [comment]
> > Hello all Is it available now? Is there a way to test it? I have a esp32-h2-mini-1 and would love to test it!
> 
> Did you get this squared away yet? Enjoy your H2...

I don t know how i did it, but i mixed two github projects… i wrote on the incorrect one…

this is the project :
https://github.com/tbnobody/OpenDTU

Sorry for inconveniance…

**Comment by VojtechBartoska** [comment]
Hello all,

version [3.0.0-stable](https://github.com/espressif/arduino-esp32/releases/tag/3.0.0) was released yesterday and it includes support for ESP32-H2.

I am closing this ticket as solved and if you find any new issue related to ESP32-H2 chip, please open a new ticket.

Thanks for your contribution.
