### ISSUE TITLE
ESP-WROOM-32 problem

### ISSUE THREAD

**Issue by szvarhegyi** [espressif/arduino-esp32#686]
### Hardware: http://www.ebay.com/itm/DIYmall-4-Channel-ESP8266-Wifi-Bluetooth-Network-Relay-Module-Buit-ESP32-ESP32S-/282369807279
Board:							ESP32 Dev Module
Core Installation/update date:			20/sept/2017
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
I flash the device but relay state not changed. I have an another normal ESP-WROOM-32 dev board and the code is running good but this DIYMALL relay shield not working good. I write another program and i can connect to my home WiFi but i can't change the relay state. The original flash is working good but if i flash another firmware gpio is not working. Official firmware: https://github.com/cmmakerclub/esp32-webserver

What do you think what is the problem?

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
  Serial.begin(115200);
 pinMode(2, OUTPUT);
 pinMode(3, OUTPUT);
 pinMode(4, OUTPUT);
}

void loop() {
  Serial.println("GPIO4 is LOW");
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  delay(10000); 
  Serial.println("GPIO4 is HIGH");
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  delay(10000); 
}
```

**Comment by me-no-dev** [comment]
Relay is on pin 16
