### ISSUE TITLE
Add Support for ESP Insights in arduino core

### ISSUE THREAD

**Issue by osamahnini** [espressif/arduino-esp32#6866]
### Related area

https://github.com/espressif/esp-insights

### Hardware specification

All esp32 devices

### Is your feature request related to a problem?

no

### Describe the solution you'd like

Add ESP Insights modules to Arduino core. So, you can use this in Arduino development environments.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
What is your opinion @shahpiyushv? Thanks for sharing your 2c :)

**Comment by mrengineer7777** [comment]
@osamahnini I believe Insights was added a few months ago.
