### ISSUE TITLE
Can ESP32 only connect to WPA2? Can't connect to WPA and WPA3?

### ISSUE THREAD

**Issue by hzhh110** [espressif/arduino-esp32#6873]
### Related area

ESP32-S

### Hardware specification

ESP32-S

### Is your feature request related to a problem?

Can ESP32 only connect to WPA2? Can't connect to WPA and WPA3?

### Describe the solution you'd like

Can ESP32 only connect to WPA2? Can't connect to WPA and WPA3?

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
merged in lib-builder: https://github.com/espressif/esp32-arduino-lib-builder/pull/72
