### ISSUE TITLE
WiFiClientSecure fails to compile, claiming that no ciphersuites are enabled when there are

### ISSUE THREAD

**Issue by matthew798** [espressif/arduino-esp32#6891]
### Board

ESP32 dev module

### Device Description

ESP DOIT Devkit V1.0

### Hardware Configuration

Nothing

### Version

latest master (checkout manually)

### IDE Name

VS Code

### Operating System

Ubuntu

### Flash frequency

NA

### PSRAM enabled

yes

### Upload speed

NA

### Description

When attempting to compile an app using WiFiClientSecure, the build fails with:

`Please configure IDF framework to include mbedTLS -> Enable pre-shared-key ciphersuites and activate at least one cipher`

Though the ciphersuites _are_ enabled. Here is an example of the relevant SDKCONFIG section used when the error occurs:
```
#
# TLS Key Exchange Methods
#
CONFIG_MBEDTLS_PSK_MODES=y
CONFIG_MBEDTLS_KEY_EXCHANGE_PSK=y
CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_PSK=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_PSK=y
CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_PSK=y
CONFIG_MBEDTLS_KEY_EXCHANGE_RSA=y
CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_RSA=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA=y
```

Further investigation reveals that, in "ssl_client.cpp", `MBEDTLS_KEY_EXCHANGE__SOME__PSK_ENABLED` does not seem to be defined, causing the following to skip the body of the file:
```
#ifndef MBEDTLS_KEY_EXCHANGE__SOME__PSK_ENABLED
#  warning "Please configure IDF framework to include mbedTLS -> Enable pre-shared-key ciphersuites and activate at least one cipher"
#else
```

Replacing the above lines with:
```
#if !defined(MBEDTLS_KEY_EXCHANGE__SOME__PSK_ENABLED) && !defined(MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED)
#  warning "Please configure IDF framework to include mbedTLS -> Enable pre-shared-key ciphersuites and activate at least one cipher"
#else
```

Fixes the issue. Taken from [here](https://community.platformio.org/t/i-got-a-message-please-configure-idf-framework-to-include-mbedtls-after-updating-esp32-to-version-4-4-0/28196/3)

Digging further, it seems the correct DEFINE to look for is `MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED` and not `MBEDTLS_KEY_EXCHANGE__SOME__PSK_ENABLED` as that is what is defined in ssl_ciphersuites.h when a ciphersuite is enabled:
```
/* Key exchanges using a PSK */
#if defined(MBEDTLS_KEY_EXCHANGE_PSK_ENABLED)           || \
    defined(MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED)       || \
    defined(MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED)       || \
    defined(MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED)
#define MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED
#endif
```

### Sketch

```cpp
#include <WiFiClientSecure.h>



void main(){
    WiFiClientSecure client;
}
```

### Debug Message

```plain
Not run on hardware
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
I suspect that define comes from `CONFIG_COAP_MBEDTLS_PSK=y`, but AFAIK there is no dependency on libcoap in ssl_client, so it should be using the macro you suggest.  If you [edit the file on github](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/src/ssl_client.cpp), you can directly submit a PR from there.

**Comment by me-no-dev** [comment]
you sure you have the correct source code? This has been fixed already: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/src/ssl_client.cpp#L23
