### ISSUE TITLE
make max_files in SD_MMC accessible by begin function

### ISSUE THREAD

**Issue by Jilbers** [espressif/arduino-esp32#6911]
### Related area

SD_MMC

### Hardware specification

ESP32

### Is your feature request related to a problem?

I must have more than 5 files open at the same time but the SD_MMC library doesn't allow this.
Instead max_files is set with a magic number.
It took me some time to find it. I didn't find any documentation about this limitation.

### Describe the solution you'd like

When using the begin function a parameter where max_files can be set would be nice.

### Describe alternatives you've considered

At the moment I call 
`esp_vfs_fat_sdmmc_mount("/sdcard", &host, &slot_config, &mount_config, NULL);` 
before begin with the same parameters as in the begin function but with max_files set to a higher number.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
Fixed by @lbernstone in the PR above
