### ISSUE TITLE
ledc fails since 2.0.2 for Arduino-IRremote

### ISSUE THREAD

**Issue by ArminJo** [espressif/arduino-esp32#6923]
### Board

ESP32DevModule

### Device Description

no

### Hardware Configuration

Ledc Output pin is D4

### Version

v2.0.3

### IDE Name

Arduino, Sloeber

### Operating System

%

### Flash frequency

%

### PSRAM enabled

no

### Upload speed

%

### Description

see https://github.com/Arduino-IRremote/Arduino-IRremote/issues/997

### Sketch

```cpp
SendDemo example of the Arduino-IRremote library
can be reduced to:
ledcSetup(0, 38000, 8);
ledcAttachPin(4, 0);
ledcWrite(0, 76);
delay(1);
ledcWrite(0, 0);
delay(1);
ledcWrite(0, 76);
delay(1);
ledcWrite(0, 0);
delay(1);
...
```

### Debug Message

```plain
%
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
@P-R-O-C-H-Y PTAL.

**Comment by ArminJo** [comment]
Sorry, the correct sketch is:
void setup() {
  Serial.begin(115200);
  ledcSetup(0, 38000, 8);
  ledcAttachPin(4, 0);
  **pinMode(4, OUTPUT);** // this is not required for ESP but for all AVR CPUs...
}

void loop() {
   ledcWrite(0, 76);
   delay(1);
   ledcWrite(0, 0);
   delay(1);
}
