### ISSUE TITLE
= should not be in #define

### ISSUE THREAD

**Issue by hairybaboon** [espressif/arduino-esp32#6939]
### Board

ESP32 Adafruit Feather V2

### Device Description

ESP32 Adafruit Feather V2

### Hardware Configuration

Builtin button so nothing need be connected

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

compiler fails before flash

### PSRAM enabled

yes

### Upload speed

compiler fails before flash

### Description

#define  shouldn't have an equals sign - if used as is it causes compilation errors when using BUTTON in place of pin 38.

### Sketch

```cpp
int button_builtin = BUTTON;
void setup() {
  pinMode(button_builtin , INPUT);  // built in switch 38
}
void loop() {
  Builtin_Status = !digitalRead(button_builtin);
}
```

### Debug Message

```plain
dfg
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@hairybaboon - thanks for reporting!

**Comment by me-no-dev** [comment]
@ladyada PTAL :)
