### ISSUE TITLE
ESP32 - Clean, Build, Upload button/menu items do all build, but not clean and not upload

### ISSUE THREAD

**Issue by beegee-tokyo** [espressif/arduino-esp32#697]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:		4/oct/2017
IDE name:						Platform.io
Flash Frequency:					default
Upload Speed:					default

### Description:
Not sure if this is the right place to post the problem.

Atom version: 1.19.3 ia21
PlatformIO version Home 0.3.0 Core 3.5.0a16
Espressif 32 version 0.10.0
Espressif 32 (Stage) version aba1d7d
OS: Windows XP

When I create a project in a custom folder, e.g. (B:\Projects\ESP32\TestBoard) the Clean, Build and Upload button/menu items in PlatformIO all do only a build, no clean or upload of the project.

When I create a project in the default project folder location e.g. (C:\SPB_Data\Documents\PlatformIO\Projects...) the buttons/menu items in PlatformIO work as expected.

On ESP8266 projects I can create projects in a custom folder location and the buttons work as expected. 

### Sketch:
Any sketch as long as it is outside the default project folder

### Debug Messages:
None

**Comment by me-no-dev** [comment]
Please submit this issue in paltformio and not here :)
