### ISSUE TITLE
bug fix for wificlient.cpp 

### ISSUE THREAD

**Issue by marsjupiter1** [espressif/arduino-esp32#6975]
### Board

generic esp32

### Device Description

n/a

### Hardware Configuration

n/a

### Version

v2.0.3

### IDE Name

Arduino IDE

### Operating System

n/a

### Flash frequency

40

### PSRAM enabled

no

### Upload speed

115000

### Description

I'm supplying a bug fix to:
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiClient.cpp

essentially if stop() is called it fails to call the destructor on the socket handle.

### Sketch

```cpp
void WiFiClient::stop()
{
    clientSocketHandle = NULL;
    _rxBuffer = NULL;
    _connected = false;
}
is wrong as it simply nullifies clientSocketHandle, so when the class is deleted the socket will not get a close call.

void WiFiClient::stop()
{
    if (clientSocketHandle){
        delete clientSocketHandle;
        clientSocketHandle = NULL;
    }
    _rxBuffer = NULL;
    _connected = false;
}
should be:
void WiFiClient::stop()
{
    if (clientSocketHandle){
        close(clientSocketHandle->fd());
       clientSocketHandle = NULL;
    } 
    _rxBuffer = NULL;
    _connected = false;
}

### Debug Message

```plain
not really relevant, just found after making a few connections and calling stop before deletion, I could no longer make a connection.
```

### Other Steps to Reproduce

n/a

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
I guess this should become a PR instead of an issue?!

**Comment by bertmelis** [comment]
clientSocketHandle is a shared_ptr. It deletes the object when another us assigned
