### ISSUE TITLE
What about Framework Configuration? 

### ISSUE THREAD

**Issue by moelski** [espressif/arduino-esp32#7]
Hi, 
great that work has begun on this topic :-)
In the ESP32 samples I see often a framework configuration. But I can´t find anything here in this code tree. 
Don´t we need the config for the arduino-esp part? Or will it be implemented later? 

![kconfig](https://cloud.githubusercontent.com/assets/17078960/19179167/f707a780-8c5a-11e6-84eb-7062cab4a429.jpg)

btw: Hope to get my first ESP32 next week. So I can do some tests..

Dominik

**Comment by me-no-dev** [comment]
currently all libs that come in IDF are prebuilt. Configuration used is in tools/sdk/include/config.
What you can do though is start an IDF project and import the repo as component (clone in components/arduino in the project) then you can use the menuconfig to setup anything you want and compile all from source.
