### ISSUE TITLE
WiFiClient fails after 3 loops

### ISSUE THREAD

**Issue by espuser** [espressif/arduino-esp32#70]
Hi,
please insert a port disconnect into examples code

...
Serial.println("closing connection");
client.stop();
}

BR

**Comment by me-no-dev** [comment]
Since ```client`` is a local variable for the function, at function end, the destruct method for client will be called, which will close the connection (call client.stop())

**Comment by espuser** [comment]
Hi,
from point of view loop() you are right but the channel will be kept open
so after 3 loops (> MAXSOCKETS?) I get an connect fail in my case
BR

**Comment by me-no-dev** [comment]
that is rather strange... it behaves fine when I try it here. What is the web server?

**Comment by espuser** [comment]
Apache Server with simple Index.html "It works" content
connecting to 192.168.10.22
Requesting URL: /index.html....................?private_key=....................&value=2
HTTP/1.1 200 OK
Date: Mon, 28 Nov 2016 12:36:47 GMT
Server: Apache/2.4.10 (Win32) OpenSSL/1.0.1i mod_jk/1.2.40 PHP/5.5.15
Last-Modified: Sat, 30 Mar 2013 11:29:00T
....
closing connection

**Comment by sorscode** [comment]
Post your code? I'll try and duplicate.

**Comment by me-no-dev** [comment]
i see openSSL there, you are not connecting to HTTPS correct?

**Comment by me-no-dev** [comment]
@espuser you know what? You might be correct! Destruct was not closing the client. Could you please try the latest commit?

**Comment by espuser** [comment]
Hi,
the client runs without client.stop() now, but since You use the latest libs for WiFi from espressif I have the same problem as with the espressif/esp-idf toolchain, my esp32 NodeMCU cyclic reboots (about every 30 sec) or hangs
BR

**Comment by me-no-dev** [comment]
There are lots of thing being worked on the network stack on IDF. Soon it will all be working :)

**Comment by me-no-dev** [comment]
BTW pinMode time depends on which pin you apply it too. If it's an RTC pin, it's 2.6 us, if not it's 0.744us
