### ISSUE TITLE
Input Output with opend drain support

### ISSUE THREAD

**Issue by Rafinha29** [espressif/arduino-esp32#7022]
### Board

ESP32

### Device Description

DevkitC

### Hardware Configuration

none

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

I want to use the "Input output with open drain" option for GPIO configuration but its not listed in the options, from https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-gpio.h

//GPIO FUNCTIONS
#define INPUT             0x01
// Changed OUTPUT from 0x02 to behave the same as Arduino pinMode(pin,OUTPUT) 
// where you can read the state of pin even when it is set as OUTPUT
#define OUTPUT            0x03 
#define PULLUP            0x04
#define INPUT_PULLUP      0x05
#define PULLDOWN          0x08
#define INPUT_PULLDOWN    0x09
#define OPEN_DRAIN        0x10
#define OUTPUT_OPEN_DRAIN 0x12
#define ANALOG            0xC0

Can I pass to the pinMode() function something like "(OUTPUT | OPEN_DRAIN ) ?                 

### Sketch

```cpp
.
```

### Debug Message

```plain
.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
@P-R-O-C-H-Y can you please help with triaging and possibly answering this one? Thanks.

**Comment by P-R-O-C-H-Y** [comment]
Hi @Rafinha29, even the option is not listed in the `esp32-hal-gpio.h` file, you can call: 
`pinMode( PIN , (OUTPUT_OPEN_DRAIN | INPUT));` or `pinMode( PIN , (OUTPUT | OPEN_DRAIN ));` like you mentioned. It should setup the pin as input/output with open drain. Feel free to test it and let us know if that worked for you :)

**Comment by VojtechBartoska** [comment]
any news @Rafinha29?

**Comment by Rafinha29** [comment]
Sorry I didn't have the time to try it yet, finally I used two GPIO

**Comment by P-R-O-C-H-Y** [comment]
@Rafinha29 I am closing this as there is no reply from you for a long time. If you still need some help, feel free to reopen this :)
