### ISSUE TITLE
WiFiSmartConfig save settings (AP, PASS)

### ISSUE THREAD

**Issue by yankobogdan** [espressif/arduino-esp32#705]
WiFiSmartConfig connection working good. But after reboot changes unsaved. I try to get AP name and PASS to write to EEPROM but both unsuccessful. Any advise?

**Comment by me-no-dev** [comment]
can you please post minimal sketch that shows the issue?

**Comment by bill-orange** [comment]
I have the same issue. Please see #810.

**Comment by bill-orange** [comment]
Has there been any progress in fixing this?  I have a couple of application that just won't work if the settings obtained with smart config are lost.

**Comment by chinswain** [comment]
Agree with @bill-orange, can this be standard functionality? I think most users would assume the smart config settings are preserved between reboots, regardless of past experience with the esp8266.

**Comment by ironoman** [comment]
Thanks alot @bill-orange . i have been looking for a solution

**Comment by ehsanmqn** [comment]
Any updates? Does anyone solved the problem?

**Comment by bill-orange** [comment]
Beyond the work-around I posted 9 months ago, I don’t think so.

**Comment by copercini** [comment]
There is a solution here: https://github.com/espressif/arduino-esp32/issues/1100#issuecomment-392397250

that saves the SmartConfig credentials to NVS, then load it on boot
