### ISSUE TITLE
Broken software serial when using the latest Arduino core

### ISSUE THREAD

**Issue by Fattorino** [espressif/arduino-esp32#7098]
### Board

Adafruit ESP32 feather

### Device Description

The esp32 board is connected to a Grove Air530 GPS module.

### Hardware Configuration

Pin 23 and 23 are used for the serial communication between the esp board and the GPS module

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Windows 10

### Flash frequency

40Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

The provided sketch outputs:
```
$GNGS3,⸮b⸮⸮b⸮⸮b⸮⸮b⸮⸮bb,3.1,2.1,2.3,1⸮&H9M,3,10,19,27,30,46,<⸮,<3.⸮r⸮,2.3,⸮*
$GPG_V,3,1,1⸮,05,10,202,10,10,32?,⸮12,16,219<,13⸮b⸮⸮⸮b⸮⸮b⸮R⸮⸮
$GPGSV⸮b⸮b12,14⸮32,051,28,15,b⸮⸮⸮bb⸮⸮b⸮⸮b⸮ʂ~⸮b⸮9,28,12⸮,0%⸮
$⸮Y,3,⸮,12,>3,2⸮⸮bb⸮b⸮⸮b⸮ºb~⸮⸮bb,31,30,09,087⸮b⸮51⸮
$B⸮e⸮b⸮b⸮⸮b⸮⸮b⸮⸮~⸮⸮⸮b⸮⸮b⸮⸮b⸮⸮b⸮b⸮⸮Ⓔb⸮⸮b⸮⸮⸮b⸮⸮b⸮⸮b⸮⸮b⸮⸮⸮b⸮⸮b⸮r⸮⸮
$BDGSVb⸮b⸮⸮b⸮⸮,35,0⸮4⸮⸮R⸮⸮
⸮G
220350.000,A,4<50.⸮⸮⸮⸮b0⸮045.7⸮⸮50.00<281.<6,070822,⸮V02
$GE⸮r⸮⸮b<M,r⸮⸮b0>00,K,A:2A
$GNZDA,220350.00b⸮⸮b⸮⸮b⸮⸮⸮⸮b⸮⸮b⸮⸮R⸮
$GP⸮⸮⸮⸮b⸮⸮b⸮⸮bANTENNA O{35
$GNG⸮A,220351.000,4450.8?164,N,01045.?0957,},1⸮b⸮.1,?1.8,M,42.3,M,
```
and only when downgrading to version espressif32@3.5.0 (version 1.0.6 of the core) instead of espressif32 (version 2.0.4 of the core) I get the correct output:
```
$GNGGA,220005.000,0,N,0,E,1,10,2.2,24.1,M,42.3,M,78
$GNGLL,0,N,0,E,220005.000,A,A4E
$GNGSA,A,3,13,14,17,19,30,3.3,2.2,2.5,13C
$GNGSA,A,3,10,19,27,30,46,3.3,2.2,2.5,43E
$GPGSV,3,1,12,05,12,203,10,09,328,12,15,218,13,62,139,18,06A
$GPGSV,3,2,12,14,34,052,26,15,73,251,19,17,33,092,20,19,26,126,24,068
$GPGSV,3,3,12,23,25,301,24,41,286,28,31,30,10,086,24,05F
$BDGSV,2,1,05,10,28,051,13,19,24,181,14,27,16,072,25,30,12,122,19,075
$BDGSV,2,2,05,46,36,064,25,043
$GNRMC,220005.000,A,0,N,0,E,3.19,276.28,070822,A,V0E
$GNVTG,276.28,T,M,3.19,N,5.91,K,A2C
$GNZDA,220005.000,07,08,2022,00,0040
$GPTXT,01,01,01,ANTENNA OK*35
```

### Sketch

```cpp
#include <Arduino.h>
#include <SoftwareSerial.h>

SoftwareSerial ss;

void setup()
{
  ss.begin(9600, SWSERIAL_8N1, 23, 22, false, 256);
  Serial.begin(9600);
}

void loop()
{
  if (ss.available()) {
    while (ss.available()) {
      Serial.write((uint8_t)ss.read());
    }
  }
}
```

### Debug Message

```plain
(I don't have any specific debug messages due to the nature of this bug but pls let me know if something is needed)
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@Fattorino - SoftwareSerial may use some Arduino functions that have changed after Arduino Core 2.0.0+, which has been refactored to use IDF as system base. In that case, maybe this Library may need to be changed as well and this can be done reporting this same issue to the respective Library repository issue's list.

Let's see if someone from the community can bring some ideas or new libraries to be used to replace the one you are using.
From an Arduino Core perspective, there is nothing clearly to be done, given the SoftwareSerial is actually a third party piece of software.
