### ISSUE TITLE
ESP32-S3 DevKit 8MB partition scheme mislabeled

### ISSUE THREAD

**Issue by cmsavage** [espressif/arduino-esp32#7113]
### Board

ESP32-S3-DevKitC

### Device Description

N/A

### Hardware Configuration

N/A

### Version

v2.0.4

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

N/A

### PSRAM enabled

yes

### Upload speed

N/A

### Description

For the ESP32-S3 Dev Module, the 8MB partition scheme is listed as "[8M Flash (3MB APP/1.5MB FAT)](https://github.com/espressif/arduino-esp32/blob/3e65a5721ae17b578136db1c55accb549a4d0204/boards.txt#L154)", but the corresponding [default_8MB.csv](https://github.com/espressif/arduino-esp32/blob/3e65a5721ae17b578136db1c55accb549a4d0204/tools/partitions/default_8MB.csv) file shows SPIFFS is used, not FAT.  For consistency with other partition schemes, the relevant boards.txt line should be something like:
`esp32s3.menu.PartitionScheme.default_8MB=8M Flash (3MB APP/1.5MB SPIFFS)`

There is also a lack of consistency between the various partition scheme labels: ffat/FAT/FATFS, spiffs/SPIFFS, two entries labeled as default, etc.

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
Yes, you are right, thanks for reporting!
It deserves a full review of all the schemes, names and files.
