### ISSUE TITLE
Practical usage of Wokwi Online Arduino Simulator

### ISSUE THREAD

**Issue by VojtechBartoska** [espressif/arduino-esp32#7130]
This issue is tracking implementation of [Wokwi simulator](https://wokwi.com/) into Arduino ESP32 repository.

### [ ] Add Wokwi link & description into Issue report template

**Motivation:**
_This project is very often used as a welcome gate into Embedded World thanks to Arduino framework and it's popularity. It means there is a bunch of new users and also many different types of HW and also SW solutions. Very often we are facing the problem that we are not able to replicate the issue due to more reasons as for example unknown HW, unknown SW setup and so on...Here comes a Wokwi simulator which can be handy for those cases. If the Author of the issue is able to provide the failing code running under Wokwi platform, Espressif developers can easily reproduce the issue and make next development steps. This can speed up the development process and also improve Users's experience._

### [ ] Use Wokwi more actively by Developers in answers

**Motivation:**
_This step is relate to task above. Wokwi can be also used as an example and proper answer to the particular problem. Instead of just saying, your code is wrong and you need to change this function. Developers can just share a Wokwi simulation which is showing properly working piece of the code. This tasks is meant firstly for Espressif Devs but this approach can be used by anyone._

### [ ] Compilation tests of favorite librariers in Wokwi

**Motivation:**
_Arduino offers tons of different libraries. This project is moving forward and we are not able to cover all resources so it happens that we broke something. Having a test for most favorite libraries can help us with spotting that and be aware of the consequences._

There is already written automated tests framework available [in this GH repository](https://github.com/wokwi/wokwi-tests).

**Subtasks:**
- investigate how we can run those testes on scheduled basis
- write tests sketches

**5 libraries for first version of Libraries compilation tests: (proposed candidates)**
1. [Blynk](https://www.arduinolibraries.info/libraries/blynk)
2. [Adafruit NeoPixel](https://www.arduinolibraries.info/libraries/adafruit-neo-pixel)
3. [AsyncWebServer](https://www.arduinolibraries.info/libraries/async-web-server_rp2040-w)
4. [Adafruit GFX Library](https://www.arduinolibraries.info/libraries/adafruit-gfx-library)
5. [FastLED](https://www.arduinolibraries.info/libraries/fast-led)

More can be added later.

This is an intitial description which will be updated up to the investigations.

**Comment by VojtechBartoska** [comment]
**Wokwi docs links:**
- [ESP32 documentation](https://docs.wokwi.com/guides/esp32)
- [diagram.json file format](https://docs.wokwi.com/diagram-format)

**Comment by urish** [comment]
List of the 15 most popular libraries on Wokwi:

| Library             | Project Count |
| ------------------- | ------------- |
| LiquidCrystal_I2C.h | 47647         |
| Servo.h             | 30721         |
| LiquidCrystal.h     | 20950         |
| WiFi.h              | 19537         |
| DHT.h               | 16404         |
| Adafruit_GFX.h      | 14452         |
| Adafruit_SSD1306.h  | 13165         |
| FastLED.h           | 11625         |
| ArduinoTrace.h      | 10857         |
| Keypad.h            | 9483          |
| DHTesp.h            | 8523          |
| RTClib.h            | 7270          |
| PubSubClient.h      | 5302          |
| Adafruit_NeoPixel.h | 5272          |
| EEPROM.h            | 5029          |

**Comment by VojtechBartoska** [comment]
We do have now library tests implemented.

Wokwi is used from time to time for demonstration.

I think for now we can close this ticker as there are no action points.

**Comment by urish** [comment]
Yeah, been open for a long time!
