### ISSUE TITLE
Implementing ESP-IDF LEDC fading functions

### ISSUE THREAD

**Issue by davorvr** [espressif/arduino-esp32#7136]
### Related area

LEDC, PWM

### Hardware specification

ESP32

### Is your feature request related to a problem?

Aside from LED fading, it would be useful for adjusting servos more slowly.

### Describe the solution you'd like

I would like [`esp32-hal-ledc.c`](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-ledc.c) to also include functions to wrap the existing fading functionality present in ESP-IDF's [`ledc.c` driver](https://github.com/espressif/esp-idf/blob/master/components/driver/ledc.c)

### Describe alternatives you've considered

This can be done with a for loop using a specified delay, as in the [`LEDCSoftwareFade.ino`](https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/AnalogOut/LEDCSoftwareFade/LEDCSoftwareFade.ino) example, but since this functionality exists at a hardware level, implementation of this would be nice, especially since it can also work in a non-blocking manner.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by davorvr** [comment]
Thanks guys, looking forward to 2.1.0! 😄

**Comment by VojtechBartoska** [comment]
Hello @davorvr, yeah, we would like to implement this feature in the next major milestone 2.1.0.

**Comment by P-R-O-C-H-Y** [comment]
Closing this as Fade implementation PR #8338 was already merged.

**Comment by P-R-O-C-H-Y** [comment]
Closing this as Fade implementation PR https://github.com/espressif/arduino-esp32/pull/8338 was already merged.
