### ISSUE TITLE
simple_ota_example error :  esp-tls-mbedtls: Failed to set client configurations, returned [0x8017] (ESP_ERR_MBEDTLS_SSL_SETUP_FAILED) (IDFGH-8036)

### ISSUE THREAD

**Issue by DreamPWJ** [espressif/arduino-esp32#7138]
![image](https://user-images.githubusercontent.com/16730031/184107222-ce7af8ea-a471-4831-b052-da79dfa351bc.png)

When I do the ota upgrade, there is an error as shown in the figure, I want to know how this pem is generated? What is the role of existence code?

**Comment by mahavirj** [comment]
@DreamPWJ Code snippet you shared above is using ESP Arduino framework and hence we shifted the issue in this repository. CC @me-no-dev

**Comment by me-no-dev** [comment]
@mahavirj the only Arduino related code is `Serial` which just prints to UART. The code with issue is all ESP-IDF
