### ISSUE TITLE
Support for vTaskList() in Arduino core so we can monitor task status

### ISSUE THREAD

**Issue by osamahnini** [espressif/arduino-esp32#7179]
### Related area

FreeRTOS

### Hardware specification

All esp32 devices

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Current when you use vTaskList() FreeRTOS API and try to compile, you get this error: "undefined reference".
The runtime stats must be enabled in FreeRTOS so you can use this API. I think the solution is to enable runtime stats by default.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
We need to check if this will cause any performance/memory degradation first.

**Comment by qnxsgwy** [comment]
If can view the cpu usage, is very useful for debugging, hope to support this function. 
But performance degradation also needs attention，hopefully as an option that can be on/off at compile time.

**Comment by fknrdcls** [comment]
Well, I'm no stranger to squeezing performance out of the ESP32 and I use it by default on my projects.
48kHz stereo realtime MP3 encoder: https://www.esp32.com/viewtopic.php?f=2&t=9186
Using it to gauge performance really didn't notice any issues at all. I think there is certainly more benefit than potential issues. Also Arduino being something that is also used as a learning tool, it would be extremely beneficial to allow users to see tasks usage and CPU affinity. Happy to add an example if it's added.

**Comment by davepl** [comment]
I too would very much appreciate this support in the Arudino variant... just hit this omission myself!

**Comment by zekageri** [comment]
+1

**Comment by szerwi** [comment]
+1, I would also need that feature in my project

**Comment by everslick** [comment]
me 2

**Comment by yekomS** [comment]
also need this feature :-)

**Comment by marnov999** [comment]
so any new info on this? I would need it too, or maybe some way to recompile the lib ourself with the feature enabled?

**Comment by davepl** [comment]
I wound up making my own idle threads that whack the watchdog and track whatever idle cycles they can burn, and that gives me overall CPU, but not per-task…

**Comment by bobemoe** [comment]
Yeah defo missing this too, just started using RTOS tasks, and need a way to list and monitor them. This looks like just the ticket.

**Comment by synologic** [comment]
All, this has been discussed all over the internet for quite a while now, we should get it :)

**Comment by VojtechBartoska** [comment]
Hello all, changing this to 3.1.0 milestone, we are starting investigating of this is doable and let you know. 

@lucasssvaz will do the research and share the updates later here.

**Comment by lucasssvaz** [comment]
We'll first need to implement some way to easily reconfigure and recompile the libs for the users. Currently working on that.

**Comment by me-no-dev** [comment]
Will something like that work? https://github.com/espressif/arduino-esp32/pull/10515#issue-2610981384

**Comment by hitecSmartHome** [comment]
It would be the best if it would return or populate an array or json instead of printing it out. That way we could actually do something with the results

**Comment by me-no-dev** [comment]
@hitecSmartHome that is up to you to implement. You can use the code in the PR as starting point. Array is already used there and that is what is printed.

**Comment by hitecSmartHome** [comment]
I see.
