### ISSUE TITLE
Add ability to connect to hidden ssid when using WifiMulti

### ISSUE THREAD

**Issue by ShortPutt** [espressif/arduino-esp32#7189]
### Related area

WiFiMulti

### Hardware specification

ESP32

### Is your feature request related to a problem?

I have my IoT devices connect to a hidden ssid. The ssid is hidden not because of security concerns, just simply don't want it listed in list of available networks. The hidden ssid is broadcast on three different APs (w different channels of course). Unlike WiFi, WiFiMulti does a good job of connecting to the AP w/ the strongest signal. I hacked WiFiMulti.cpp to get it to work. It was simple - modified the scanNetworks call to include hidden ssids - WiFi.scanNetworks(false, true) - and then used the hidden ssid for the networks returned by the scan w/o an ssid. Its an unelegant hack, so I'm not going to submit my code, but I think I submitted enough info for someone to make it a feature. I have a number of ESP32's in my IoT. I program them w/ Arduino using the arduino-esp32 lib.

### Describe the solution you'd like

WifiMulti feature to connect to hidden ssid w/ strongest RSSI

### Describe alternatives you've considered

I looked at various other wifi libs for ESP32. None offer this feature.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
Thanks for the information.

`int16_t WiFiScanClass::scanNetworks(bool async, bool show_hidden, bool passive, uint32_t max_ms_per_chan, uint8_t channel, const char * ssid, const uint8_t * bssid)` has default `show_hidden` as `false`.

It is used in `uint8_t WiFiMulti::run(uint32_t connectTimeout)`

This can be obtained by using IDF call [`show_hidden`](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv418wifi_scan_config_t) flag in [`esp_err_t esp_wifi_scan_start(const wifi_scan_config_t *config, bool block)`](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv419esp_wifi_scan_startPK18wifi_scan_config_tb) 

@ShortPutt - feel free to add a PR with your or some other implementation that you may think that could help this Arduino community.
