### ISSUE TITLE
USBHIDKeyboard SendReport(): report 1 wait failed

### ISSUE THREAD

**Issue by FallingSnow** [espressif/arduino-esp32#7197]
### Board

ESP32-S2-DevKitM-1

### Device Description

Connected via USB via 5V, GND, GPIO 19, and GPIO 20.

### Hardware Configuration

5V, GND, GPIO 19, and GPIO 20

### Version

v2.0.4

### IDE Name

PlatformIO

### Operating System

No OS

### Flash frequency

Default (Not Sure)

### PSRAM enabled

no

### Upload speed

916200

### Description

I boot a PC with ESP32-s2 connected from a separate USB with [Ventoy](https://ventoy.net/en/index.html) on it. Within Ventoy I cannot use the ESP USB keyboard and the serial interface fills with usb `report 1 wait failed` errors. If I plug in a physical USB keyboard it works as expected.

Once I boot into an operating system, the ESP USB keyboard works as expected.

### Sketch

```cpp
#include "USB.h"
#include "USBHIDKeyboard.h"
#include "USBHIDMouse.h"
#include "USBHIDSystemControl.h"

USBHIDMouse Mouse;
USBHIDKeyboard Keyboard;
USBHIDSystemControl SystemControl;
USBCDC USBSerial;

Mouse.begin();
Keyboard.begin();
SystemControl.begin();

USB.begin();
```

### Debug Message

```plain
[364586][E][USBHID.cpp:340] SendReport(): report 1 wait failed
[364686][E][USBHID.cpp:340] SendReport(): report 1 wait failed
```

### Other Steps to Reproduce

Once in Arch Linux OS it works as expected.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by RefactorFactory** [comment]
This pull request might (probably) solve the problem: #6964
