### ISSUE TITLE
Arduino IDE - Error downloading https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

### ISSUE THREAD

**Issue by manuelchaves** [espressif/arduino-esp32#7204]
### Board

no one

### Device Description

n/a

### Hardware Configuration

default

### Version

latest development Release Candidate (RC-X)

### IDE Name

Aruino IDE

### Operating System

Windows 10 and 11

### Flash frequency

40mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

Error downloading https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

Not download V2,xx ESP32
Old versio, 1.XX ok
ESP8266 ok

Arduino IDE V1.8.19 and  2.0.0.rc 9.2
Windows 11 and other PC Windows 10 64Bits

### Sketch

```cpp
n/a
```

### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
Are you able to get to that location through a browser?  Perhaps there is a firewall blocking your access?
