### ISSUE TITLE
Add examples | documentation for Low Power | High Performance

### ISSUE THREAD

**Issue by SuGlider** [espressif/arduino-esp32#7206]
### Related area

Examples | Documentation

### Hardware specification

All boards

### Is your feature request related to a problem?

No Problem. Just a request to add Documentation and/or Examples.

### Describe the solution you'd like

Documentation and/or Examples about how to achieve Lower Power Consumption possible using Arduino as well as How to get the Highest Performance possible using all the supported SoC.

### Describe alternatives you've considered

None.

### Additional context

None.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
Hi @SuGlider, I am closing this ticket in favor of https://github.com/espressif/arduino-esp32/issues/6563. They duplicate each other.
