### ISSUE TITLE
Parallel compilation?

### ISSUE THREAD

**Issue by nkolban** [espressif/arduino-esp32#724]
Would it be possible to perform parallel compilation through threading or processes?

In an ESP-IDF environment, I commonly run "make -j5" to execute parallel makes and have so far not run into any issues.  I have found that the time to complete a compilation dramatically decreases as I consume more of my CPU resources.

Would it be possible to achieve this capability within the Arduino IDE / ESP32 environment?

**Comment by copercini** [comment]
https://github.com/arduino/arduino-builder/pull/242

I get the feeling that it will never be merged, like the others zillions of PRs.... , but you can download the [files compiled by arduino bot](http://downloads.arduino.cc/PR/arduino-builder/arduino-builder-242.zip) and replace by yourself =)
