### ISSUE TITLE
the bin  which contains nvs or eeprom can't be download by espressif download tools

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/arduino-esp32#7245]
### Board

ESP32-WROOM

### Device Description

ESP32-WROOM

### Hardware Configuration

ESP32-WROOM

### Version

v2.0.4

### IDE Name

arduino

### Operating System

win10

### Flash frequency

80M

### PSRAM enabled

no

### Upload speed

921600

### Description

I wrote a code which contains nvs(also tried eeprom) in arduino,and  i exported the bin in arduino.Then I use espressif download tools to program these bins.(totally four:
1.\tools\partitions\default.bin   0x8000
2.\tools\partitions\boot_app0.bin   0xe000
3.\tools\sdk\esp32\bin\bootloader_qio_80m.bin   0x1000
4.nvs.ino.esp32.bin    0x10000)
But it will reset and reset.
If  the code doesn't contain nvs or eeprom ,it will be ok.
So would anyone please tell me how to fix this problem? THANKS!

### Sketch

```cpp
THIS IS MY CODE:
#include "esp_system.h"
#include "nvs_flash.h"
#include "nvs.h"
void setup() {
  Serial.begin(9600);
//
  esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        err = nvs_flash_init();
    }
    ESP_ERROR_CHECK( err );
}
void loop()
{
}
```

### Debug Message

```plain
Rebooting...
E (79) partition: No MD5 found in partition table
E (80) partition: load_partitions returned 0x105
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment]
I believe there is another partition entry that defines the rest of the partition locations.  Reply if you want me to look that up when I'm at work.
