### ISSUE TITLE
Cannot open a new file in LittleFS subfolders

### ISSUE THREAD

**Issue by dsilletti** [espressif/arduino-esp32#7266]
### Board

ESP32-WROOM-32E

### Device Description

ESP32-WROOM-32E

### Hardware Configuration

N/A

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE 2.0

### Operating System

macOS 12.6

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

Cannot open a new file in subfolder, it works with no issues in the root folder

### Sketch

```cpp
File testfile = LittleFS.open("/subfolder/test.txt", "a");
if (testfile) {
  testfile.println("Test");
  testfile.close();
}
```

### Debug Message

```plain
N/A
```

### Other Steps to Reproduce

try to open a file in a LittleFS subfolder

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by P-R-O-C-H-Y** [comment]
Hi @dsilletti, sorry for later reply. You have 2 options to make it work :)
1. Add true as 3rd parameter to the open function `File testfile = LittleFS.open("/subfolder/test.txt", "a", true);`. Setting it to true (default is false) will create all dirs (subdirs) to the file. Works with modes write and append.
2. Create the subfolder by `LittleFS.mkdir("/subfolder");` and then use `File testfile = LittleFS.open("/subfolder/test.txt", "a");`

Closing this as solved. Feel free to reopen if needed :)
