### ISSUE TITLE
random board name appended to Arduino Port menu listing

### ISSUE THREAD

**Issue by jake653** [espressif/arduino-esp32#7292]
### Board

AI-Thinker (NodeMCU) ESP32-C3-01M-KIT

### Device Description

ESP32-C3 board (not in list), using "ESP32C3 Dev Module" board name.

### Hardware Configuration

Using internal USB IO18, IO19

### Version

v2.0.4

### IDE Name

Arduino IDE 2.0.0-rc8 (same behavior with 1.8.19)

### Operating System

MacOS Catalina

### Flash frequency

40 mhs

### PSRAM enabled

no

### Upload speed

115200

### Description

The Port Select Menu lists:  /dev/cu.wchusbserial1410 (some board name)

The board name randomly changes when resetting board, this causes the no board selection, have to re-select current name displayed in menu to reactivate port.   The current port menu title lists just the port name: "/dev/cu.wchusbserial1410"

This change in behavior started some time in September, I assume an Arduino or espressif board plugin update introduced the new behavior.

In a dozen resets I might see a variation of port names like:
/dev/cu.wchusbserial1410 (ESP32S3 Dev Module)
/dev/cu.wchusbserial1410 (AirM2M-Core-ESP32C3)
/dev/cu.wchusbserial1410 (ESP32-S3-Box)
/dev/cu.wchusbserial1410 (Adafruit QT PY ESP32-C3)
/dev/cu.wchusbserial1410 (LOLIN C3 Mini)
/dev/cu.wchusbserial1410 (DFRobot BeetleESP32-C3)

### Sketch

```cpp
Not sketch related

Actually using: ESP32 by espressif 2.0.5
```

### Debug Message

```plain
Compile/Upload result after reset changed port menu listing:

Failed uploading: no upload port provided
```

### Other Steps to Reproduce

FYI using ESP32-C3 micro-USB connection, I get 2 port choices: 

/dev/cu.wchusbserial1410  which works for code uploads.

/dev/cu.usbserial1410  which works for serial monitoring

(I might have 2 CH340 drivers installed?)

Also found patching boards.txt entries to TRUE helps serial monitoring work

esp32c3.serial.disableDTR=true
esp32c3.serial.disableRTS=true

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Because the USB PID and VID of our boards are the same, the IDE can not differentiate which board is connected and usually shows the first one that matches VID/PID. This is not something that we can fix.

As for `serial.disableDTR/RTS` values, those might depend on the USB UART chip and/or EN/BOOT setup of the board.
