### ISSUE TITLE
The device could not be reconnected!

### ISSUE THREAD

**Issue by hzhh110** [espressif/arduino-esp32#7296]
### Related area

ESP32-WROOM-32D

### Hardware specification

ESP32-WROOM-32D

### Is your feature request related to a problem?

I don't know what's going on. When customers use the device, it often happens that the device can't connect to the WiFi, and then it is connected to the WiFi immediately after power off and restart. There are reconnections, and it can't be reproduced on my side.

### Describe the solution you'd like

 if(WiFi.status() == WL_CONNECTED){
     WiFi.disconnect();
    DebugPrintln(_myDeviceDetails.wifissid);
    DebugPrintF("_myDeviceDetails.wifissid:%s ;  _myDeviceDetails.wifipassword:%s", _myDeviceDetails.wifissid,    _myDeviceDetails.wifipassword);
    WiFi.begin(_myDeviceDetails.wifissid, _myDeviceDetails.wifipassword);
    delay(1000);
    vTaskDelay(5000);
}  
 

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by mrengineer7777** [comment]
May be resolved by #7344
