### ISSUE TITLE
Empty payload on an MQTT

### ISSUE THREAD

**Issue by podaen** [espressif/arduino-esp32#7310]
### Board

ESP32

### Device Description

ESP32 dev Module

### Hardware Configuration

No

### Version

v2.0.4

### IDE Name

1.8.19

### Operating System

Windows 7

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

I notist that I having some issues with an empty payload if I use a CA. With insecure everything just works fine! As well HTTP and HTTPS (MQTT) clients disconnecting (because of a timeout) after receiving the empty payload. I think you guys might be interested.

### Sketch

```cpp
...
```

### Debug Message

```plain
see my description.
```

### Other Steps to Reproduce

I do.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by podaen** [comment]
it's sync (non blocking).

**Comment by podaen** [comment]
To be clear, the timeout is not the issue. The empty payload is with a CA.

**Comment by VojtechBartoska** [comment]
@SuGlider Can you please help with triage of this issue? Thank you.

**Comment by bertmelis** [comment]
This can be closed.

**Comment by podaen** [comment]
I just did the test over with the modification I have made and it works. Two reasons that could be the issue for this.

1. Power suffering, but just enough to work without payload when insecure.
2. Only WiFi_Protocol_11b was set.

I solved those issues and now it's working with CA and without payload.
