### ISSUE TITLE
Part of the development version is missing in Arduino IDE 2.0, but it can be found in Arduino 1.8.19.

### ISSUE THREAD

**Issue by Tinyu-Zhao** [espressif/arduino-esp32#7317]
### Board

M5Stack-Station

### Device Description

M5Stack-Station

### Hardware Configuration

none

### Version

v2.0.5

### IDE Name

Arduino

### Operating System

macOS 11.7

### Flash frequency

none

### PSRAM enabled

no

### Upload speed

none

### Description

Part of the development version is missing in Arduino IDE 2.0, but it can be found in Arduino 1.8.19.

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/44396641/193394700-c3b3e2c2-2865-4dbb-a515-295d0122645a.png">

### Sketch

```cpp
None
```

### Debug Message

```plain
None
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
This is not our core (this repository). Please post an issue in M5Stack's fork.

**Comment by Tinyu-Zhao** [comment]
> This is not our core (this repository). Please post an issue in M5Stack's fork.

I am the maintainer of M5Stack, and I don't know how to deal with this issue.

**Comment by me-no-dev** [comment]
Do you see the boards in the normal menu up on top of your screen? Maybe something else missing? Does it work fine with this core?

**Comment by Tinyu-Zhao** [comment]
M5Station can be found in Arduino 1.8.19, and there are no errors when using M5Station.

Tinyu Chiu
2022年10月3日 +0800 15:38 espressif/arduino-esp32 ***@***.***>，写道：
>
> Reply

**Comment by me-no-dev** [comment]
<img width="2005" alt="Screenshot 2022-10-03 at 10 47 14" src="https://user-images.githubusercontent.com/12663778/193525972-52ee5403-dea8-4f84-867e-fa7f62630a1c.png">

Works in our core. I am again asking if it shows in the top menu?

<img width="1671" alt="Screenshot 2022-10-03 at 10 48 34" src="https://user-images.githubusercontent.com/12663778/193526235-080687b1-9466-45a1-903f-219345dbd5a8.png">

**Comment by Tinyu-Zhao** [comment]
🤔 surprisingly it can appear in the official board, I don't have that installed, I will check our configuration in comparison, thank you

Tinyu Chiu
2022年10月3日 +0800 15:49 Me No Dev ***@***.***>，写道：
