### ISSUE TITLE
How to change  Arduino  ESP32  SDK config？

### ISSUE THREAD

**Issue by ningmen7294** [espressif/arduino-esp32#7335]
### Related area

ESP32 SDK

### Hardware specification

ESP32-WROOM-32D

### Is your feature request related to a problem?

<img width="958" alt="dc482a6509bc46b5e3fa1aa1628dc04" src="https://user-images.githubusercontent.com/8636831/194746131-42e14831-9492-42a7-89d1-3b4a9d3eb067.png">
![Uploading 994ce618aa7aeacb806312d7ab9eaca.png…]()

蓝牙底层无法分配到内存导致程序崩溃

### Describe the solution you'd like

提供arduino ESP32 下 修改SDK 默认配置的方法

### Describe alternatives you've considered

蓝牙底层无法分配到内存导致程序崩溃

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by lbernstone** [comment]
Changing CONFIG values does not magically make more memory.  You can chase that ghost if you like. https://github.com/espressif/esp32-arduino-lib-builder allows you to rebuild the archive libraries.
A real solution is reducing your memory usage. Perhaps using a device with PSRAM will allow you to offload some memory there.  The [NimBLE library](https://github.com/h2zero/NimBLE-Arduino) is a lightweight BLE library.
