### ISSUE TITLE
SD linrary disable card free heap ptr error

### ISSUE THREAD

**Issue by usermicrodevices** [espressif/arduino-esp32#734]
**Hardware:**
Board: ESP32, NodeMCU-32S, WROOM-32

**Description:**
SD linrary disable card free heap ptr error

Please fix line 34 of source file SD.cpp from:
`    if(_pdrv == 0xFF) {`
to:
`    if(_pdrv == 0xFF || !_pdrv) {`

**Comment by me-no-dev** [comment]
why? 0 is a valid drive number ;)

**Comment by usermicrodevices** [comment]
if card not installed, it is memory free error
