### ISSUE TITLE
Mac V:12.6 (21G115) +  VSCODE + Platformio   The problem

### ISSUE THREAD

**Issue by hzhh110** [espressif/arduino-esp32#7347]
### Related area

ESP32

### Hardware specification

ESP32

### Is your feature request related to a problem?

python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

pio platform install espressif32

mkdir ~/Documents/PlatformIO/Projects/testproj1
cd ~/Documents/PlatformIO/Projects/testproj1

pio project init --board nodemcu-32s

After completion, it can be opened normally

However, as long as there are other versions of platform = espressif32 @ ~3.5.0 in the project, you have to repeat the above process, even if you change back to platform = espressif32, it will not work properly

### Describe the solution you'd like

python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

pio platform install espressif32

mkdir ~/Documents/PlatformIO/Projects/testproj1
cd ~/Documents/PlatformIO/Projects/testproj1

pio project init --board nodemcu-32s

After completion, it can be opened normally

However, as long as there are other versions of platform = espressif32 @ ~3.5.0 in the project, you have to repeat the above process, even if you change back to platform = espressif32, it will not work properly

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by hzhh110** [comment]
I tried it many times in a row, but the result was the same

**Comment by SuGlider** [comment]
@hzhh110 
This issue sounds to be related exclusively to PlatformIO.
I think that you will get a better response if it is open within 
https://github.com/platformio/platform-espressif32/issues
or
https://github.com/platformio/platformio-vscode-ide/issues

**Comment by Jason2866** [comment]
@hzhh110  Thats not the recommended way to install Platformio when used with VSC
Install Platformio VSC Extension. The extension installs Platformio. No manuall install.

**Comment by VojtechBartoska** [comment]
Closing. Please follow recommendations above. Thank you @SuGlider & @Jason2866.
