### ISSUE TITLE
WiFiClientSecure / WiFiClient inconsistency in get/set timeout

### ISSUE THREAD

**Issue by cziter15** [espressif/arduino-esp32#7355]
No details about the device required as whole ecosystem is affected.

Affected component: WiFiClientSecure, WiFiClient 

### Description

Shortly, there's inconsistent behavior:
- setTimeout uses seconds as parameter while
- getTimeout returns number of miliiseconds

I've encountered that when building framework for my devices. I've been passing timeout from WiFiClient to another component using getTimeout method. Since there is no unit specified I've expected that get will return same unit as set method uses.

### Sketch

```cpp
WiFiClientSecure s;
s.setTimeout(10); // <= this overrides virtual method and sets _timeout to passed value multiplied by 1000
int gv = s.getTimeout();  // <= comes from Stream due to derived chain of classes and returns _timeout

Serial.println(gv); //will print 10000
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello @cziter15,

this is already discussed in this Pull Request: https://github.com/espressif/arduino-esp32/pull/6676

It's planned for next major release as it's a breaking change.

**Comment by cziter15** [comment]
Closing issue then.

**Comment by VojtechBartoska** [comment]
PR got merged, closing this as solved.
