### ISSUE TITLE
Update `WiFiScan` example to show more useful data

### ISSUE THREAD

**Issue by Rotzbua** [espressif/arduino-esp32#7377]
### Related area

Example

### Hardware specification

All

### Is your feature request related to a problem?

Simple examples are often used for quick debugging or function testing.

But currently the output of the `WiFiScan` example is not very useful:

```
Setup done
scan start
scan done
17 networks found
1: IoTNetwork (-62)*
2: WiFiSSID (-62)*
3: B3A7992 (-63)*
```

It does not show what the esp32 board recognizes, like encryption or channel.

### Describe the solution you'd like

Add more useful data to the output.

E.g
```
Setup done
Scan start
Scan done
17 networks found
Nr | SSID            | RSSI | CH | Encryption
 1 | IoTNetwork      |  -62 |  1 | WPA2
 2 | WiFiSSID        |  -62 |  1 | WPA2-EAP
 3 | B3A7992         |  -63 |  6 | WPA+WPA2
 4 | WiFi            |  -63 |  6 | WPA3
 5 | IoTNetwork2     |  -64 | 11 | WPA2+WPA3
```

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
Hello @Rotzbua,

thanks a lot for your contribution. We'll review your PR soon.
