### ISSUE TITLE
Changes  in boards.txt and partitions doesn't take effect

### ISSUE THREAD

**Issue by lucassanders** [espressif/arduino-esp32#7379]
### Board

ESP32 DEV MODULE

### Device Description

Custom Hardware

### Hardware Configuration

Custom Hardware

### Version

v2.0.5

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

40MHZ

### PSRAM enabled

no

### Upload speed

115200

### Description

In previous versions of IDE and board, I was enabled to modify boards.txt and partitions and create a custom partition with different sizes for OTA and APP. But in the most recent versions, changing the files in C:\Users\<user>\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.5 does not appear in IDE.

### Sketch

```cpp
-
```

### Debug Message

```plain
-
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
You do not say which IDE you are using, but you can always select "Huge App" in the menu and add your custom partitions file to your sketch folder. No need to edit the ones in the core.

p.s. Arduino IDE 2.0 caches board configs and does not show the changes.
