### ISSUE TITLE
ESP32-C3 SPI EXAMPLE

### ISSUE THREAD

**Issue by wukongxuetang** [espressif/arduino-esp32#7389]
### Related area

SPI

### Hardware specification

ESP32-C3

### Is your feature request related to a problem?

ESP32 have four SPI but ESP32-C3 have three spi，SPI0 and SPI1 have used for inner flash，only spi2 can use.
SPI library in aduino IDE library has one example about SPI，but it will give an error “'VSPI' was not declared in this scope
” when use esp32 c3.

### Describe the solution you'd like

would like give an example about spi for ESP32 c3? Thanks.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
That example is not meant to run on C3. Example is for using multiple buses and as you noted, the C3 has just one. On C3 you just use the regular Arduino `SPI` class
