### ISSUE TITLE
Vulnerable to KRACK attack (WPA2 attack)?

### ISSUE THREAD

**Issue by davejm** [espressif/arduino-esp32#739]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			11/jul/2017
IDE name:							Arduino IDE
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:

It was recently discovered that correctly implemented WPA2 WiFi protocols are vulnerable to attack. I was wondering if the ESP32 is vulnerable and if a patch could be made.

Reference site: https://www.krackattacks.com/

**Comment by me-no-dev** [comment]
Patched last night :)

**Comment by pieman64** [comment]
@me-no-dev where can we see the patch?

**Comment by Testato** [comment]
is there a commit that make evidence of the file changed ?

**Comment by copercini** [comment]
Here is more information about this: https://esp32.com/viewtopic.php?f=13&t=3349
