### ISSUE TITLE
ESP32S2 USB CDC Self Powered Device

### ISSUE THREAD

**Issue by HX2003** [espressif/arduino-esp32#7390]
### Related area

USB

### Hardware specification

ESP32S2 Dev Module

### Is your feature request related to a problem?

In the ESP-IDF programming guide, there is a section that states self-powered devices must monitor the voltage level on USB’s VBUS signal. https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/usb_device.html#self-powered-device I was wondering if there is a need to do that (equivalent api) when using the ESP32S2 as a USB Serial Device, it seems that even without the monitoring connecting and disconnecting works.

### Describe the solution you'd like

-

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
@SuGlider Please help with triage.

**Comment by me-no-dev** [comment]
The IDF documentation above is for ESP-IDF v5.1. Support for VBUS monitoring is not available before that. In Arduino we abuse the "RESET" event a bit to make disconnection work. We will have proper support with pin monitoring in ESP32 Arduino 3.0.0
