### ISSUE TITLE
i use esp32(arduino) to scan fliles on the SD card,but can't  support chinese filename?

### ISSUE THREAD

**Issue by justdomyself** [espressif/arduino-esp32#7391]
### Board

ESP32 DEV

### Device Description

i use esp32(arduino) to scan fliles on the SD card,but can't  support chinese filename? how can this suport chinese file name? thanks.

### Hardware Configuration

IIS 

### Version

v2.0.4

### IDE Name

arduino

### Operating System

win 7

### Flash frequency

40M

### PSRAM enabled

no

### Upload speed

115200

### Description

i use esp32(arduino) to scan fliles on the SD card,but can't  support chinese filename? how can this suport chinese file name? thanks.

### Sketch

```cpp
#include "FS.h"
#include "SD_MMC.h"

//最大文件数量
#define MAX_ROWS  300
//文件名最大长度
#define MAX_COLS  50

//文件信息结构体定义
typedef struct 
{
    char listSongs[100][50];
    int index = 0;
}list_t;


list_t listInst;

//插入文件名到列表
int InserSong(char *name)
{
    int idx = listInst.index;

    if( strstr(name, ".mp3") == NULL ) return -1;

    memset( listInst.listSongs[idx], 0, MAX_COLS );
    strcpy(listInst.listSongs[idx], "/");
    strcat( listInst.listSongs[idx], name);
    listInst.index++;

    return 0;
}

//获取可用曲名数量
int GetSongCounts()
{
   return listInst.index;
}

//获取磁盘文件列表
void listDir(fs::FS &fs, const char * dirname, uint8_t levels)
{
    Serial.printf("Listing directory: %s\n", dirname);

    File root = fs.open(dirname);
    if(!root)
    {
        Serial.println("Failed to open directory");
        return;
    }
    if(!root.isDirectory())
    {
        Serial.println("Not a directory");
        return;
    }

    File file = root.openNextFile();
    while(file)
    {
        if(file.isDirectory())
        {
            Serial.print("  DIR : ");
            Serial.println(file.name());
            if(levels)
            {
                listDir(fs, file.path(), levels -1);
            }
        } 
        else 
        {
            Serial.print("  FILE: ");
            Serial.print(file.name());
            Serial.print("  SIZE: ");
            Serial.println(file.size());

            InserSong(file.name());
        }

        file = root.openNextFile();
    }
}
```

### Debug Message

```plain
..................
```

### Other Steps to Reproduce

NO

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello,

we already have this request.

https://github.com/espressif/arduino-esp32/issues/7246

Please follow the issue above I've shared. It's already assigned to one of our Developer to help with answering this.

I'm closing this issue as duplicate.
