### ISSUE TITLE
ENC28j60 or any ethernet support for ota from https

### ISSUE THREAD

**Issue by KJPOUNDY132** [espressif/arduino-esp32#7397]
### Board

ESP32 dev mıodule

### Device Description

DevKit C

### Hardware Configuration

just esp32 with 1 led and button

### Version

latest master (checkout manually)

### IDE Name

Arduino  IDE

### Operating System

macOS

### Flash frequency

40

### PSRAM enabled

yes

### Upload speed

115200

### Description

Hi wanto make ota updates from https server via ethernet how does it support?

### Sketch

```cpp
f
```

### Debug Message

```plain
f
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
This link may help:
https://forum.arduino.cc/t/esp32-with-enc28j60-module-update-via-ethernet/1038318

You may try this (at your risk):
https://github.com/jandrassy/ArduinoOTA
https://stackoverflow.com/questions/60432074/updating-esp32-firmware-via-ethernetinternet

**Comment by VojtechBartoska** [comment]
is this still valid?

**Comment by VojtechBartoska** [comment]
Hello, I'm closing this issue as expired. If needed, you can reopen it.
