### ISSUE TITLE
ESP-WROOM32

### ISSUE THREAD

**Issue by thl-mot** [espressif/arduino-esp32#74]
Hi,
I tried to run blink on an ESP-WROOM32. Download seams to work. RxD and TxD flashes while download. But no reaction from the ESP-Board. 
Another try with Serial: I expected a flashing TxD-LED but here as well: no reaction.
What is wrong? Where can I debug to get more information.
Thomas

**Comment by lbernstone** [comment]
I have no idea if LED_BUILTIN is set to the correct pin right now.  me_no_dev is probably very busy trying to integrate the new IDF, so maybe try setting up a little breadboard with an led, resistor and your esp32, and set things up to write to a numbered pin instead of LED_BUILTIN. (https://www.arduino.cc/en/tutorial/blink)

**Comment by clowrey** [comment]
There is no built in LED on the ESP-WROOM32 module itself but it is defined in the library you can easily find the pin by searching for LED_BUILTIN in this repository like so:
https://github.com/espressif/arduino-esp32/search?utf8=%E2%9C%93&q=LED_BUILTIN

**Comment by thl-mot** [comment]
I checked several output pins with the LED, no result with the basic blink example.
Even a small Serial-Sender like the following one did not work:
```
void setup() {
    Serial.begin(9600)
}
void loop() {
    Serial.print("Hello");
  delay(1000);                      
}
```
I don't get any output at TxD.

Thomas

**Comment by thl-mot** [comment]
I got it working, you have to press the button under the usb connector. So main problem solved, it is running in arduino-ide. Now I have to try this on sloeber-ide. This seams to be more work. Because the package-json does not yet contain all information to get it started.

**Comment by me-no-dev** [comment]
no clue what package.json you refer to, but I have it running fine inside sloeber.

**Comment by thl-mot** [comment]
with the package.json I ment the definition file for the package manager. As I included your esp32-package as custom hardware and libraries it works in sloeber-ide. I think the better way would be to include it by the package manager. At least its working now. There are some small things, because the ide shows errors even though its perfectly compiling.
The following lines of the WiFiScan example show errors:
Serial.print(WiFi.SSID(i));
Serial.print(WiFi.RSSI(i));
Do you have an idea where these errors come from and how I can fix it.
Thomas

**Comment by me-no-dev** [comment]
not errors, eclipse tripping because it does not understand the methods correctly. Nothing is wrong with anything.
Package manager will come once we have some sort of stable Arduino. There are many many things still that need work.

**Comment by thl-mot** [comment]
Do you have timeline/backlog/"list of things to do". Maybe I can help. Will you also include Bluetooth support or is this functionality outside the scope of Arduino?

**Comment by me-no-dev** [comment]
Bluetooth will be included. Things are done as they come available in IDF, so there isn't a backlog really.

**Comment by zhivko** [comment]
Maybe a raletd topic to this one - the other way I tried GPIO34, and I was not able to make it work.
However https://learn.sparkfun.com/tutorials/esp32-thing-hookup-guide#arduino-example-blink ledpin=5 worked as it supposed.
@me-no-dev maybe you know what could be the reason GPIO34 does not work?

**Comment by me-no-dev** [comment]
pins 34 and up can be only inputs

**Comment by zhivko** [comment]
Oh... They should be then naped GPI and not GPIO ... Do you have any other idea how to visually represent this information on [https://github.com/espressif/arduino-esp32/blob/master/doc/esp32_pinmap.png].
I saw that on this link there are diferrent colors for each pin - can you put up a color legend with meaning?

**Comment by me-no-dev** [comment]
you might find this useful: http://espressif.com/sites/default/files/documentation/esp32_chip_pin_list_en.pdf

**Comment by aspiringguru** [comment]
link above was broken for me. this link worked for me > http://wiki.ai-thinker.com/_media/esp32/docs/esp32_chip_pin_list_en.pdf
