### ISSUE TITLE
Consider using arduino-lint in CI

### ISSUE THREAD

**Issue by igrr** [espressif/arduino-esp32#7451]
### Related area

CI, development workflow

### Hardware specification

any

### Is your feature request related to a problem?

Sketches and libraries sometimes end up with inconsistent naming or code style, or in generally don't comply with the Arduino guidelines.

### Describe the solution you'd like

Arduino team provides an arduino-lint tool which can run some checks on sketches, libraries, and cores:
https://arduino.github.io/arduino-lint/

The ideal solution is to use the tool in CI or as a pre-commit hook, to check the new contributions.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
Closing this in favor of https://github.com/espressif/arduino-esp32/issues/7975
