### ISSUE TITLE
Ethernet ESP32 Gateway

### ISSUE THREAD

**Issue by bhaessig83** [espressif/arduino-esp32#746]
### Hardware:
Board:							Olimex ESP32 Gateway
Core Installation/update date:		Today
IDE name:						Arduino IDE
Flash Frequency:					80MHz
Upload Speed:					115200

### Description:

Hello everybody,

I've bought the ESP32 gateway from Olimex and I would like to communicate with the ethernet cable with my Mosquitto server.

I've done some tests with the wifi connection and it is working as expected.

I've loaded the DHCP.ino example of the project, but the setup process ends with the MAC address. I never get the information "ETH connected".

I've taken this fork : https://github.com/fesch/arduino-esp32

Do you have an idea what could be the issue ?
Thanks a lot for your feedback.

### Sketch:
```cpp

#include <Ethernet.h>
#include "WiFi.h"

// declare the ethernet adapter
ESP32Ethernet ethernet;

void WiFiEvent(WiFiEvent_t event){
    switch(event) {
        case SYSTEM_EVENT_ETH_START:
            //set eth hostname here
            ethernet.setHostname("esp32-eth");
            Serial.println("ETH started");
            Serial.print("ETH MAC: ");
            Serial.println(ethernet.getMacAddress());
            break;
        case SYSTEM_EVENT_ETH_CONNECTED:
            Serial.println("ETH connected");
            break;
        case SYSTEM_EVENT_ETH_GOT_IP:
            Serial.print("ETH IPv4: ");
            Serial.println(ethernet.localIP());
            break;
        case SYSTEM_EVENT_ETH_DISCONNECTED:
            Serial.println("ETH disconnected");
            break;
        default:
            break;
    }
}

void setup(){
  // start the serial console 
  Serial.begin(115200);
  // attach the callback event handler
  WiFi.onEvent(WiFiEvent);
  // start the ethernet
  ethernet.begin();
}

void loop(){
  // nothing yet to do here
}
```

### Debug Messages:
```
ETH started
ETH MAC: 24:0A:C4:0C:2C:CB
```

**Comment by me-no-dev** [comment]
yup. there is a bug in idf and it sends the wrong event. sta instead of eth for got ip. fix is on the way
