### ISSUE TITLE
WLAN with special characters in SSID doesn't work

### ISSUE THREAD

**Issue by matze-dev** [espressif/arduino-esp32#7488]
### Board

Olimex

### Device Description

BSB-LAN project

### Hardware Configuration

config like [https://1coderookie.github.io/BSB-LPB-LAN/SSA_ESP32.html](url)

### Version

v2.0.2

### IDE Name

Arduino IDE

### Operating System

Windows 11

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

WLAN with SSID "WLAN-2" is used. The board is not able to connect to the network.
The monitor shows a usable IP-address but the connection won't work (no PING, no access via network).

When the name was changed to "WLAN2" all is OK.
suppose there are no correct treatment of special characters in names of WLAN-SSIDs

failure:
#define WIFI                             // Activate this definement if you want to use WiFi. Note: MAC address can't be set individually.
char wifi_ssid[32] = "WLAN-2";                      // enter your WiFi network name (SSID) here
char wifi_pass[64] = "xxxxxxxx";  // enter your WiFi password here
#define WIFI_SPI_SS_PIN 12

OK:
#define WIFI                             // Activate this definement if you want to use WiFi. Note: MAC address can't be set individually.
char wifi_ssid[32] = "WLAN2";                      // enter your WiFi network name (SSID) here
char wifi_pass[64] = "xxxxxxxx";  // enter your WiFi password here
#define WIFI_SPI_SS_PIN 12

### Sketch

```cpp
BSB-LAN project
therein BSB_lan_config.h

failure:
#define WIFI                             // Activate this definement if you want to use WiFi. Note: MAC address can't be set individually.
char wifi_ssid[32] = "WLAN-2";                      // enter your WiFi network name (SSID) here
char wifi_pass[64] = "xxxxxxxx";  // enter your WiFi password here
#define WIFI_SPI_SS_PIN 12

OK:
#define WIFI                             // Activate this definement if you want to use WiFi. Note: MAC address can't be set individually.
char wifi_ssid[32] = "WLAN2";                      // enter your WiFi network name (SSID) here
char wifi_pass[64] = "xxxxxxxx";  // enter your WiFi password here
#define WIFI_SPI_SS_PIN 12
```

### Debug Message

```plain
no debug message
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
My SSID also has a dash (and has had since forever), so I can not reproduce this issue. Could you enable debug to level Verbose and post the logs?

**Comment by matze-dev** [comment]
Hi all, then it seems to be OK. I had trouble with the WLAN access point, it worked not properly. You can close the issue.
Thanx for all.
