### ISSUE TITLE
Custom device support with ESP32 Rainmaker and Google home

### ISSUE THREAD

**Issue by atanudasgupta** [espressif/arduino-esp32#7491]
### Board

esp232

### Device Description

esp32 devKit

### Hardware Configuration

testing with custom rainmaker device. It works well. I am able to connect with Alexa , but google Home is unable to find the rainmaker custom device
static Device my_device("TEST Geyser", "custom.device.geyser", &gpio_relay); 

### Version

v2.0.5

### IDE Name

arduino ide

### Operating System

macos

### Flash frequency

40

### PSRAM enabled

no

### Upload speed

115200

### Description

I want to know why google home is unable to find rainmaker custom device by alexa is able to find it\

### Sketch

```cpp
static Device my_device("TEST Geyser", "custom.device.geyser", &gpio_relay);
```

### Debug Message

```plain
google home during linking with rainmaker finds no rainmaker device
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
https://github.com/espressif/esp-rainmaker

**Comment by SuGlider** [comment]
@sanketwadekar - Any guess about it? Thanks!

**Comment by sanketwadekar** [comment]
Hi @atanudasgupta
Google Home does not support custom devices but Alexa does. You can check the [list of devices](https://rainmaker.espressif.com/docs/standard-types.html#devices) supported by Alexa and GVA to find more information.

**Comment by mrengineer7777** [comment]
GVA doesn't support "Other". Consider using "Outlet" instead.
![image](https://user-images.githubusercontent.com/44048235/203574583-0f831961-4b1b-4b24-b500-35766e4d8ade.png)

**Comment by VojtechBartoska** [comment]
Can I consider this as answered @atanudasgupta?

**Comment by atanudasgupta** [comment]
Yes i would liked to see custom device support in rainmaker 

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 15, 2022 at 7:08 PM, Vojtěch ***@***.***> wrote:   


Can I consider this as answered @atanudasgupta?

**Comment by sanketwadekar** [comment]
> @atanudasgupta - I think that @sanketwadekar  mentioned that GVA, or even GHA, doesn't support Custom Device.
> It seems that RainMaker does, as well as Alexa.
> Therefore, the issue would be with Google, not Rainmaker.
> 
> So it would be possible to have RainMaker Custom Devices with Alexa but not with Google, due to Google's limitation.
> Is that it, @sanketwadekar?

Yes, GVA doesn't support Custom devices as of now but Alexa and Rainmaker do.

**Comment by VojtechBartoska** [comment]
Closing as it was already answered.
