### ISSUE TITLE
Possible regression of serial communication performance since version 2.x

### ISSUE THREAD

**Issue by awawa-dev** [espressif/arduino-esp32#7505]
### Board

ESP32 dev module

### Device Description

Board capable of 2Mb serial speed (CH9102x)

### Hardware Configuration

nothing  is connected

### Version

v2.0.5

### IDE Name

Arduino IDE, PlatformIO

### Operating System

Windows, Linux

### Flash frequency

default

### PSRAM enabled

no

### Upload speed

default

### Description

As of version 2.x I observe possible performance regression compared to version 1.x when high-speed communication is used (2 000 000 baud). We verify the integrity of the frame data to make sure the frame is complete and undamaged.

Simplified sketch and python test client provided as an attachment.  'Esp32 dev module' with CH9102x 

With version 1.0.6 was working fine.
![image](https://user-images.githubusercontent.com/69086569/203595291-fa84e91f-e9fe-4bbc-b87c-b108cbd01627.png)

Sending 900 bytes frames without any problem to ESP32 board. The reception is confirmed.

![image](https://user-images.githubusercontent.com/69086569/203595719-f1988661-5f51-45b7-b625-aa12fd6cefe0.png)

Since version 2.x the same sketch does not work anymore, which was first reported by our users and then confirmed by us after testing. We are unable to maintain such communication, all 900 byte frames are damaged or incomplete:

![image](https://user-images.githubusercontent.com/69086569/203596076-d3d14231-895e-4f52-b672-9ebec7aafc30.png)

None of 900 byte frames is receive undamaged and completed.

![image](https://user-images.githubusercontent.com/69086569/203596262-ec780dd6-a001-49ed-8f31-23835541f89c.png)

It starts to work for ~600 byte frame but with high error rate:

![image](https://user-images.githubusercontent.com/69086569/203596421-92170e4b-a541-46fa-9474-ccb2d376e5d8.png)
[client_and_sketch.zip](https://github.com/espressif/arduino-esp32/files/10077331/client_and_sketch.zip)

### Sketch

```cpp
Test client and sketch provided as an attachment in the description section.
```

### Debug Message

```plain
not applicable since it's not a bug
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello @awawa-dev, thanks for the issue.

I'm tagging @SuGlider who did bunch of improvements to Serial recently.

**Comment by SuGlider** [comment]
@awawa-dev - Please turn on Log messages (Core Debug Level: "Verbose") in the Arduino IDE.
You shall see this message:
`RX Buffer can't be resized when Serial is already running.`

Change your `setup()` to:
``` cpp
void setup()
{
	Serial.setRxBufferSize(MAX_BUFFER);  // before begin()
	Serial.begin(COM_SPEED);
	
	Serial.setTimeout(50);
        Serial.write("Hello tester!");
}

```

**Comment by awawa-dev** [comment]
So 2.x caused that breaking change? Still it doesn't resolve the issue.
It's better for 900 byte frame but still experience degraded performance and very high error rate:
![obraz](https://user-images.githubusercontent.com/69086569/204067529-d74add21-d89f-4509-a9b6-c3d5fec301e5.png)

For comparison 1.0.6 could handle even 1800 byte frames:

![obraz](https://user-images.githubusercontent.com/69086569/204067533-e5de8a07-44bc-466e-8db0-8fda8dadb232.png)

**Comment by SuGlider** [comment]
For 900, the solution is to replace `Stream::readBytes()` with `HardwareSerial::read()`

``` cpp
  uint16_t internalIndex = min(Serial.available(), MAX_BUFFER);
  if (internalIndex > 0)
  {
    lastDataTime = millis();
//    internalIndex = Serial.readBytes(buffer, internalIndex);
    internalIndex = Serial.read(buffer, internalIndex);
  }
  else if (lastDataTime + 1000 < millis())
  {
    Serial.println(framesReceived);
    lastDataTime = millis();
    framesReceived = 0;
    state = TestProtocol::HEADER_A;
  }
```

**Comment by SuGlider** [comment]
Anyway, it doesn't work well with 1800. Let me analyze it further.

**Comment by awawa-dev** [comment]
Thank you for your time and effort. I can confirm that it works for 1200 bytes frames now with usually no errors. Then it gets worse quickly if the frame is only slightly bigger.

**Comment by SuGlider** [comment]
@awawa-dev 
PR #7525 allows the sketch presented in this issue to run perfectly fine with no errors.
I tested it with 5000 as packet size.

**Comment by awawa-dev** [comment]
Great! I will test it right away.

**Comment by awawa-dev** [comment]
@SuGlider Great job 😄  I've tested your PR not only using test sketch but also my main project: I confirm everything works now perfectly. Hope this PR will be merged soon. And that along with the changes you recommended here will finally allow me to upgrade my ESP32 LED driver to Arduino ESP32 ver. 2. Because of that performance issue, it was on hold for almost a year (I'm aware that it could be difficult to detect due specific serial chip capability and large frame/speed transmission configuration)

**Comment by SuGlider** [comment]
Excelent!

**Comment by SuGlider** [comment]
Added new change to override `Stream:readBytes()`. Now the original code using this Stream function runs correctly as well.

**Comment by awawa-dev** [comment]
Thank you for the update. Just for your information, as I just received the ESP2-S2 mini lolin: it seems that the problem described here does not apply to this board, possibly due to the integrated onboard UART instead of the external one.

**Comment by SuGlider** [comment]
> Thank you for the update. Just for your information, as I just received the ESP2-S2 mini lolin: it seems that the problem described here does not apply to this board, possibly due to the integrated onboard USB-UART instead of the external one.

Yes, but in that case the ESP32-S2 mini lolin uses USB CDC instead of UART. Therefore, it doesn't use `HardwareSerial` class, but `HWCDC`  instead. Those two have completely different implementations.

**Comment by awawa-dev** [comment]
> Yes, but in that case the ESP32-S2 mini lolin uses USB CDC instead of UART. 

Is there any preprocessor `defined` based on the board model (platformio) that could tell us, if we compile a firmware for CDC or for UART based Serial? Seems there are more differences like the buffer size (CDC could return much larger chunk of data than UART).

**Comment by SuGlider** [comment]
>Is there any preprocessor defined based on the board model (platformio) that could tell us, if we compile a firmware for CDC or for UART based Serial? Seems there are more differences like the buffer size (CDC could return much larger chunk of data than UART).

Yes, it is in the source files:
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/HardwareSerial.h#L192-L207
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/HardwareSerial.cpp#L99-L103
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/HWCDC.h#L101-L107
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/HWCDC.cpp#L384-L392

`ARDUINO_USB_CDC_ON_BOOT` is set in the IDE Board menu and this is set in the building process.

**Comment by SuGlider** [comment]
For the ESp32-S2 mini lolin, it is set by default in the Board menu and setup in the `boards.txt` file:

https://github.com/espressif/arduino-esp32/blob/master/boards.txt#L5583

**Comment by awawa-dev** [comment]
Thank you very much. Now I can handle all the cases for the different board variants I have.
