### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by DennisMart** [espressif/arduino-esp32#7511]
### Board

esp32S2 

### Device Description

ESP-ROM:esp32s2-rc4

### Hardware Configuration

WiFiClientSecure net = WiFiClientSecure();
MQTTClient awsClient = MQTTClient(----);

### Version

v2.0.5

### IDE Name

Visual studio code 

### Operating System

windows 10 

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

Hi everyone, i am new in this foro, i working in one proyect about esp32 but i received this error ssl (-29184) SSL - An invalid SSL record was received them my esp32 reebot with this error, my program good running 10 hours that and then show this error, but this error random show, and
I can't force to apper this error.
05:43:28 [49347651][V][ssl_client.cpp:369] send_ssl_data(): Writing HTTP request with 2 bytes...
05:43:38 [49357653][V][ssl_client.cpp:369] send_ssl_data(): Writing HTTP request with 2 bytes...
05:43:48 [49367656][V][ssl_client.cpp:369] send_ssl_data(): Writing HTTP request with 2 bytes...
05:43:48 [49367737][E][ssl_client.cpp:37] _handle_error(): [data_to_read():361]: (-29184) SSL - An invalid SSL record was received
05:43:48 [49367739][V][ssl_client.cpp:324] stop_ssl_socket(): Cleaning SSL connection.
05:43:48 Guru Meditation Error: Core 0 panic'ed (LoadProhibited). Exception was unhandled.
05:43:48
05:43:48 Core 0 register dump:
05:43:48 PC : 0x400cdecb PS : 0x00060730 A0 : 0x800ce215 A1 : 0x3fff0310
05:43:49 A2 : 0x3ffcfb50 A3 : 0x00000000 A4 : 0x00000005 A5 : 0x3fff0370
05:43:49 A6 : 0x00000000 A7 : 0x0000000b A8 : 0x800cd9d8 A9 : 0x3fff0300
05:43:49 A10 : 0x00000000 A11 : 0x3fff0e00 A12 : 0x00000005 A13 : 0x3ffc88e0
05:43:49 A14 : 0x3fff0330 A15 : 0x00000001 SAR : 0x00000015 EXCCAUSE: 0x0000001c
05:43:49 EXCVADDR: 0x00000005 LBEG : 0x00000005 LEND : 0x3ffc88e0 LCOUNT : 0x40028140
05:43:49
05:43:49
05:43:49 Backtrace:0x400cdec8:0x3fff03100x400ce212:0x3fff0340 0x400ce936:0x3fff03b0 0x4008e49e:0x3fff03d0 
                0x4008d1c9:0x3fff03f0 0x4008d144:0x3fff0410 0x40126aaa:0x3fff0430 0x40126d75:0x3fff0460 0x4008a654:0x3fff0480
05:43:49 ELF file SHA256: 0000000000000000
05:43:49 Rebooting...
05:43:49 ESP-ROM:esp32s2-rc4-20191025

### Sketch

```cpp
WiFiClient espClient;
WiFiClientSecure net = WiFiClientSecure();
MQTTClient awsClient = MQTTClient(PORT);

  net.setCACert(root.c_str());
  net.setCertificate(cert_pem.c_str());
  net.setPrivateKey(private_key.c_str());

  net.setHandshakeTimeout(60);
```

### Debug Message

```plain
Decoding stack results
0x4008e49e: _vfprintf_r at /builds/idf/crosstool-NG/.build/HOST-i686-w64-mingw32/xtensa-esp32s2-elf/src/newlib/newlib/libc/stdio/vfprintf.c line 1410
0x4008d1c9: _vfprintf_r at /builds/idf/crosstool-NG/.build/HOST-i686-w64-mingw32/xtensa-esp32s2-elf/src/newlib/newlib/libc/stdio/vfprintf.c line 1056
0x4008d144: _vfprintf_r at /builds/idf/crosstool-NG/.build/HOST-i686-w64-mingw32/xtensa-esp32s2-elf/src/newlib/newlib/libc/stdio/vfprintf.c line 1017
0x4008a654: (anonymous namespace)::pool::free(void*) at /builds/idf/crosstool-NG/.build/HOST-i686-w64-mingw32/xtensa-esp32s2-elf/src/gcc/libstdc++-v3/libsupc++/eh_alloc.cc line 23
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [ ] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment]
Need more info to troubleshoot the issue
