### ISSUE TITLE
select 32k external clock source

### ISSUE THREAD

**Issue by rubenfrolic** [espressif/arduino-esp32#7527]
### Board

ESP32

### Device Description

Custom PCB, based on ESP32-S3FN8

### Hardware Configuration

32kHz crystal connected to XTAL_32K pins. 

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

macOS

### Flash frequency

40mHz

### PSRAM enabled

no

### Upload speed

115200

### Description

We've designed a board with a 32kHz crystal connected to the XTAL32 pins of the ESP32 S3FN8 SoC as per design reference. 

The problems is that we're not managing to find how to correctly use the external clock using the Arduino Core. Where and how can we select the external crystal so we can use it for RTC applications?

### Sketch

```cpp
n/a
```

### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello, closing this issues as expired due to no answer. If needed, you can reopen this.
