### ISSUE TITLE
Unable to flash ESP32

### ISSUE THREAD

**Issue by primeBiceps** [espressif/arduino-esp32#7549]
### Board

ESP-WROOM-32

### Device Description

![image](https://user-images.githubusercontent.com/33923770/205626906-59b8a028-977f-4feb-b4a3-22192ac5e309.png)

### Hardware Configuration

GPIO 32-35 are conencted to a decoder and GPIO 22, 23 are inputs. Other pins are floating while programming.

### Version

v2.0.5

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

40 MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

When i try uploading the sketch to the custom board with ESP32 I get the following error.

![image](https://user-images.githubusercontent.com/33923770/205628895-f32f597a-4793-4f11-815b-cb294bb861d5.png)

I tried it BOOT pin pulled to GND, pulled to GND until the uploading reaches connnecting... status, holding the CPU in reset as I read in some forums but none of the options helped.

As I understand and as I read in some forums the problem might be if I would have external components connected to some pins that are part of SPI interface, but in my case those pins are not used while flashing.

### Sketch

```cpp
int a1 = 6;
int b1 = 9;
int c1 = 8;
int d1 = 7;


void setup() {
  pinMode(a1, OUTPUT);
  pinMode(b1, OUTPUT);
  pinMode(c1, OUTPUT);
  pinMode(d1, OUTPUT);

}

void loop() {
  digitalWrite(a1, LOW);
  digitalWrite(b1, LOW);
  digitalWrite(c1, LOW);
  digitalWrite(d1, LOW);

  delay(500);

  digitalWrite(a1, HIGH);
  digitalWrite(b1, LOW);
  digitalWrite(c1, HIGH);
  digitalWrite(d1, LOW);
  
  delay(500);

}
```

### Debug Message

```plain
![image](https://user-images.githubusercontent.com/33923770/205628895-f32f597a-4793-4f11-815b-cb294bb861d5.png)
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment]
Your module has probably no flash chip. You have to connect a flash chip externally.

**Comment by lbernstone** [comment]
That sketch is certainly not going to work, since it is using pins assigned to the SPI flash.  However, that wouldn't keep it from flashing.  You probably have something pulling gpio12 up during boot, so it isn't supplying power properly to the flash.

**Comment by primeBiceps** [comment]
> Your module has probably no flash chip. You have to connect a flash chip externally.

I am using an external FTDI module FT232RL.

**Comment by primeBiceps** [comment]
> That sketch is certainly not going to work, since it is using pins assigned to the SPI flash. However, that wouldn't keep it from flashing. You probably have something pulling gpio12 up during boot, so it isn't supplying power properly to the flash.

Actually most of those connections are off board, so while flashing the pins are floating. The only on-board connected chips are on pins IO32...IO35 and IO22 and IO23. So pins assigned to the SPI flash and gpio12 don't have anything connected and are floating. I measured voltage on gpio12 and its around 1.3V.

**Comment by primeBiceps** [comment]
> The error you see is typical when no flash chip is found or flash chip is defect. I do not talk about the USB serial module used to "talk" to the eap32 via serial.

Ok, I understand what you are saying. The supplyer specs state that the module should have 4MB flash chip.

![image](https://user-images.githubusercontent.com/33923770/206168282-2093dfa0-3aea-490c-94b4-c1da7f46eff4.png)

Do you know a way to test if the flash chip is defect? Is there any forum about using and setting the external flash?

Thanks for the help.

**Comment by Jason2866** [comment]
Just try a different module. If this one works, you know the first one is defect.

**Comment by VojtechBartoska** [comment]
Hello, closing this issues as expired due to no answer. If needed, you can reopen this.
