### ISSUE TITLE
Platformio broken with actual master

### ISSUE THREAD

**Issue by Jason2866** [espressif/arduino-esp32#7572]
### Board

every

### Device Description

not relevant

### Hardware Configuration

not relevant

### Version

latest master (checkout manually)

### IDE Name

Platformio (custom self build)

### Operating System

macOS 12.3

### Flash frequency

40 Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

@me-no-dev 
Compile fails with Platformio at the stage where esptool.py merge command is done.
https://github.com/espressif/arduino-esp32/blob/master/tools/platformio-build.py#L91 

There are no `bootloader*.bin` files anymore in folder `sdk/esp*/bin` just `*.elf` files

### Sketch

```cpp
Every sketch
```

### Debug Message

```plain
none
```

### Other Steps to Reproduce

none

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
@Jason2866 that is true. We need PIO to update their stuff to generate bins, like we do in the IDE.

cc @ivankravets @valeros

**Comment by Jason2866** [comment]
@me-no-dev Interested in reason for the change. What is the benefit for using *.elf files?

**Comment by me-no-dev** [comment]
@Jason2866 if we use precompiled bins, the bootloader complains that the checksum of the firmware is wrong any time that settings (partitions, size, speed, etc.) differ from what the bootloader was compiled with. In order to get around that, we need to use elfs and turn them into bins with the same settings as the firmware at build time.

@ivankravets you are welcome :) Sorry I did not mention this earlier!

**Comment by TD-er** [comment]
What does this do to OTA updates?

**Comment by me-no-dev** [comment]
@TD-er as long as you keep the settings the same, it does nothing to OTA. You will see the error if you change flash speed/size.

**Comment by TD-er** [comment]
So no issues with checksums?

**Comment by me-no-dev** [comment]
no issues with checksums. elf2bin is done based on flash/psram settings, not based on the firmware image.

**Comment by Jason2866** [comment]
Thx! Tested and working.
