### ISSUE TITLE
Arduino word function used in typedef

### ISSUE THREAD

**Issue by NevynUK** [espressif/arduino-esp32#76]
The Arduino web site defines _word()_ as a function for casting bytes to a word.  

This port has word defined as _typedef unsigned int word_ on line 120 of Arduino.h.

This is breaking the Sparkfun TSL2561 libraray code.

Regards,
Mark

**Comment by me-no-dev** [comment]
hmm... thanks for noticing this! I really wonder how that define got there, especially since the correct methods are implemented :)

**Comment by hcs-svn** [comment]
removing "typedef unsigned int word;" breaks a lot of my code.
The avr core Arduino.h has both:

Line 121:
typedef unsigned int word;

and

Line 238:
uint16_t makeWord(uint16_t w);
uint16_t makeWord(byte h, byte l);
#define word(...) makeWord(__VA_ARGS__)

if you have both you can do:
word w = word(1, 2);
