### ISSUE TITLE
ETH_LAN8720 WiFiEvent never set eth_connected = true;

### ISSUE THREAD

**Issue by pipi61** [espressif/arduino-esp32#762]
### Hardware:
Board:							?ESP32 Dev Module?
Core Installation/update date:			20171021
IDE name:							Arduino IDE184
Flash Frequency:					80Mhz
Upload Speed:						921600

### Description:
in original example https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/ETH_LAN8720/ETH_LAN8720.ino
never set eth_connected variable to true;
the WiFiEvent() never call with SYSTEM_EVENT_ETH_GOT_IP.
after ETH Connected message, the ipaddress valid, connect to google valid

### Sketch:
```cpp

//Change the code below by your sketch
....
...

void setup()
{
  Serial.begin(115200);
  WiFi.onEvent(WiFiEvent);
  //ETH.begin();
  ETH.begin(         PHY1     ,   17,           23,         18  ,            ETH_PHY_LAN8720);  //waveshare lan8720
  //begin(uint8_t phy_addr, int power, int mdc, int mdio, eth_phy_type_t type) 

}


void loop()
{

 Serial.println(ETH.localIP());
 Serial.print("eth_connected=");
 Serial.println(eth_connected);
 // if (eth_connected)
 {
    testClient("google.com", 80);
  }
  delay(2000);
}
---------------------
0.0.0.0
eth_connected=0
connecting to google.com
connection failed
ETH Started
0.0.0.0
eth_connected=0
connecting to google.com
connection failed
0.0.0.0
eth_connected=0
connecting to google.com
connection failed
ETH Connected
192.168.0.108
eth_connected=0
connecting to google.com
HTTP/1.1 302 Found
Cache-Control: private
Content-Type: text/html; charset=UTF-8

**Comment by me-no-dev** [comment]
known bug ;) is in process of being fixed. ```SYSTEM_EVENT_STA_GOT_IP``` is currently called instead
