### ISSUE TITLE
gen_insights_package.py. -> [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mhendriks** [espressif/arduino-esp32#7649]
### Board

ESP32C3

### Device Description

EsP32C3-MINI-1 developer board

### Hardware Configuration

EsP32C3-MINI-1 developer board

### Version

v2.0.6

### IDE Name

Arduino 1.latest

### Operating System

MacOS latest

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

package below in de 2.0.6 tools is missing.

/packages/esp32/hardware/esp32/2.0.6/tools/gen_insights_package.py': [Errno 2] No such file or directory

### Sketch

```cpp
MinimalDiagnostics example
```

### Debug Message

```plain
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/User/Library/Arduino15/packages/esp32/hardware/esp32/2.0.6/tools/gen_insights_package.py': [Errno 2] No such file or directory
Multiple libraries were found for "WiFi.h"
 Used: /Users/User/Library/Arduino15/packages/esp32/hardware/esp32/2.0.6/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
 Not used: /Users/User/Documents/Arduino/libraries/WiFiNINA
exit status 2
/Applications/Arduino.app/Contents/Java/arduino-builder returned 2
Error compiling for board ESP32C3 Dev Module.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
oops... you can grab it from here, but it is a "bug" on our side to not include it in the zip

**Comment by mhendriks** [comment]
np, thks for the info and the py file.

**Comment by jpsuarezq** [comment]
I have the same problem usign ESP32MiniS2 with win10 and Arduino IDE 2.2.1 

```
Traceback (most recent call last):
  File "gen_insights_package.py", line 56, in <module>
  File "gen_insights_package.py", line 30, in main
  File "shutil.py", line 435, in copy2
  File "shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Juan\\Suarez\\AppData\\Local\\Temp\\arduino\\sketches\\4E71F556FA12624D44CA39DD3F998B13.bin'
[16252] Failed to execute script 'gen_insights_package' due to unhandled exception!

exit status 1

Compilation error: exit status 1
```

I'm using RMakerSwitch.ino Example code
