### ISSUE TITLE
Change STA 

### ISSUE THREAD

**Issue by holema** [espressif/arduino-esp32#765]
### Hardware:
Board:							Node 32S
Core Installation/update date:			23.10.2017
IDE name:						Platform.io
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
I tried to change the STA during the runtime with a Websockecket command. On the ESP8266 it was posible to use:

```cpp
	Serial.println(input);		
	WiFi.disconnect();
	WiFi.begin(daten["daten"][0].as<const char*>(), daten["daten"][1].as<const char*>());
```
To change the STA.

To test this snippet, I connected the ESP in combination with an AP sucessfull to a router and changed the connection with the above command. 
The result is:
It disconnects from the network and gives the Status 1 (no SSID found) and never connect with the network.

**Comment by copercini** [comment]
`Serial.println(daten["daten"][0].as<const char*>());` shows the correct SSID?

**Comment by holema** [comment]
Yes, it returns the correct ssid.

**Comment by holema** [comment]
It is working now correctly.
I did the WiFi.begin() command in the asyncWebSocket Routine which leads to the failure.
Now I set an flag and do the connectin in the main loop.

This works like a charme:

```cpp
Serial.printf("Connection status: %d\n", WiFi.status());
Serial.println(WiFi.status());
if(WiFi.status() == WL_CONNECTED){
     WiFi.disconnect();
     Serial.printf("Connection status: %d\n", WiFi.status());
     while (1) {
         if(WiFi.status() != WL_CONNECTED){
         break;
          }
    }
}
delay(100);

if (WiFi.status() != WL_CONNECTED) {
	Serial.printf("Connection status: %d\n", WiFi.status());
	WiFi.begin(ssid.c_str(), ssidPassword.c_str());
	WiFi.reconnect();
	WiFi.waitForConnectResult();
	Serial.printf("Connection status: %d\n", WiFi.status());
}
```
