### ISSUE TITLE
Invalid library BLE

### ISSUE THREAD

**Issue by Testato** [espressif/arduino-esp32#766]
Updated today to last master repo, on arduino IDE is there this warning
`Invalid library found in \SKETCH\hardware\espressif\esp32\libraries\BLE:`

IDE 1.8.4 on Win10

**Comment by me-no-dev** [comment]
run ```git submodule update --init --recursive``` in the esp32 arduino folder

**Comment by Testato** [comment]
No git here :-)

**Comment by nodtem66** [comment]
For platformIO:
I rewrite ***platformio.ini*** into
```ini
[env:your_target]
platform = https://github.com/platformio/platform-espressif32.git#feature/stage
framework = arduino
```
For arduino ide:
I suggested to download the latest version (**master** branch) of this git and replace in `esp32-arduino` installation folder

**Comment by Curclamas** [comment]
I suggest to update the [guide](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/windows.md), since there is now a submodule, we have to clone recursively:
```git clone --recursive -j8 https://github.com/espressif/arduino-esp32.git```

**Comment by aurelien35** [comment]
As Curclamas said, I also suggest to update the guide, which is really clear (even for beginners) but missing this step

**Comment by hiphigi** [comment]
Even after trying Curclamas' suggestion I get the same error. Has anything changed? Seems that even the guide itself (Windows) is incomplete at this time.
