### ISSUE TITLE
Ethernet functionality is broken if MCPWM is enabled

### ISSUE THREAD

**Issue by rob-bits** [espressif/arduino-esp32#7670]
### Board

Closed source product with ESP32-Wrover-IE.N16R8

### Device Description

It is an unique designed acquisition device. The following ESP32 functionalities are used (so far):

- Ethernet / Webserver function, RTL8201 phy, 50MHz clock connected to GPIO0 and inverted signal connected to REF clock of the PHY
- SPI - connected to ADC 20MHz SCLK, MISO/MOSI lines used, 16bit data, CS streched x4 burst transfer, period of 20us 
- x2 channel PWM with MCPWM

### Hardware Configuration

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rober/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rober/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

GPIO | Notes | Assigment
-- | -- | --
35 | input only | MISO
32 |   | MOSI
33 |   | SCLK
25 | EMAC_RXD0 | MAC_RXD0(RMII)
26 | EMAC_RXD1 | MAC_RXD1(RMII)
27 | EMAC_RX_DV | MAC_RX_CRS_DV
14 | EMAC_TXD2 | I2C_SDA
12 | EMAC_TXD3 | I2C_SCL
13 | EMAC_RX_ER | CS
15 | Strapping pin, EMAC_RXD3 | PWM1
2 | Strapping pin, bootloader low | PWM2
0 | Strapping pin, bootloader low | MAC_CLK_IN
18 | DIO(RMII) | DIO(RMII)
19 | EMAC_TXD0 | MAC_TXD0(RMII)
21 | EMAC_TX_EN | MAC_TX_EN(RMII)
RXD0 |   | SerialRXD
TXD0 | EMAC_RXD2 | SerialTXD
22 | EMAC_TXD1 | MAC_TXD1(RMII)
23 |   | MDC(RMII)

</body>

</html>

### Version

v2.0.6

### IDE Name

PlatformIO

### Operating System

Windows 10

### Flash frequency

40

### PSRAM enabled

yes

### Upload speed

115200

### Description

If the MCPWM is configured and started (**pwm_init**() called) the ethernet stops working. Events are not generated. If the MCPWM does not configured (**pwm_init**() does not called)  the ethernet works properly. I have issues ethernet + SPI as well but I could not strip down the closed source firmware to share a test code.

### Sketch

```cpp
/*
    This sketch shows the Ethernet event usage
*/
#include <Arduino.h>
#include <ETH.h>

#include "esp_log.h"
#include "esp_check.h"

#include "soc/mcpwm_periph.h" //for mcpwm_periph_signals
#include "driver/mcpwm.h"
#include "soc/mcpwm_struct.h"
#include "esp_rom_gpio.h" //for esp_rom_gpio_connect_out_signal

static bool eth_connected = false;

const int PS_PHY_EN = 4; 
const int START_DELAY_MS = 5000; //miliseconds

void WiFiEvent(WiFiEvent_t event)
{
  switch (event) {
    case ARDUINO_EVENT_ETH_START:
      Serial.println("ETH Started");
      //set eth hostname here
      ETH.setHostname("esp32-ethernet");
      break;
    case ARDUINO_EVENT_ETH_CONNECTED:
      Serial.println("ETH Connected");
      break;
    case ARDUINO_EVENT_ETH_GOT_IP:
      Serial.print("ETH MAC: ");
      Serial.print(ETH.macAddress());
      Serial.print(", IPv4: ");
      Serial.print(ETH.localIP());
      if (ETH.fullDuplex()) {
        Serial.print(", FULL_DUPLEX");
      }
      Serial.print(", ");
      Serial.print(ETH.linkSpeed());
      Serial.println("Mbps");
      eth_connected = true;
      break;
    case ARDUINO_EVENT_ETH_DISCONNECTED:
      Serial.println("ETH Disconnected");
      eth_connected = false;
      break;
    case ARDUINO_EVENT_ETH_STOP:
      Serial.println("ETH Stopped");
      eth_connected = false;
      break;
    default:
      break;
  }
}

void testClient(const char * host, uint16_t port)
{
  Serial.print("\nconnecting to ");
  Serial.println(host);

  WiFiClient client;
  if (!client.connect(host, port)) {
    Serial.println("connection failed");
    return;
  }
  client.printf("GET / HTTP/1.1\r\nHost: %s\r\n\r\n", host);
  while (client.connected() && !client.available());
  while (client.available()) {
    Serial.write(client.read());
  }

  Serial.println("closing connection\n");
  client.stop();
}

void pwm_init()
{     
  mcpwm_config_t pwm_config;
  pwm_config.frequency = 12500; //20;    //frequency = 110Hz
  pwm_config.cmpr_a = 0;       //duty cycle of PWMxA = 60.0%
  pwm_config.cmpr_b = 0;       //duty cycle of PWMxA = 60.0%
  pwm_config.counter_mode = MCPWM_UP_COUNTER;
  pwm_config.duty_mode = MCPWM_DUTY_MODE_0;

  //REF1
  mcpwm_init(MCPWM_UNIT_0, MCPWM_TIMER_0, &pwm_config);   //Configure PWM0A & PWM0B with above settings

  mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_A,50);
  mcpwm_set_duty_type(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_A, MCPWM_DUTY_MODE_0);

  mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_B,50);
  mcpwm_set_duty_type(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_B, MCPWM_DUTY_MODE_0);
  
  //configure GPIO
  gpio_set_direction((gpio_num_t) 15, GPIO_MODE_INPUT_OUTPUT);
  gpio_set_direction((gpio_num_t) 2, GPIO_MODE_INPUT_OUTPUT);
  gpio_set_direction((gpio_num_t) 20, GPIO_MODE_INPUT_OUTPUT);

  esp_rom_gpio_connect_out_signal((gpio_num_t)15, mcpwm_periph_signals.groups[MCPWM_UNIT_0].operators[MCPWM0B / 2].generators[MCPWM0B % 2].pwm_sig, 0, 0);
  esp_rom_gpio_connect_out_signal((gpio_num_t)2, mcpwm_periph_signals.groups[MCPWM_UNIT_0].operators[MCPWM0B / 2].generators[MCPWM0A % 2].pwm_sig, 0, 0);
  esp_rom_gpio_connect_out_signal((gpio_num_t)20, mcpwm_periph_signals.groups[MCPWM_UNIT_0].operators[MCPWM0A / 2].generators[MCPWM0A % 2].pwm_sig, 0, 0);

  mcpwm_start(MCPWM_UNIT_0, MCPWM_TIMER_0);
}

void setup()
{
  Serial.begin(115200);

  log_e("Initialization is starting");
  delay(START_DELAY_MS);

  pinMode(PS_PHY_EN, OUTPUT);
  digitalWrite(PS_PHY_EN, LOW);
  delay(200);
  digitalWrite(PS_PHY_EN, HIGH);
  delay(200);

  pwm_init();
  
  WiFi.onEvent(WiFiEvent);
  ETH.begin(ETH_PHY_ADDR, PS_PHY_EN, ETH_PHY_MDC, ETH_PHY_MDIO, ETH_PHY_RTL8201, ETH_CLOCK_GPIO0_IN, false);
}


void loop()
{
  if (eth_connected) {
    testClient("google.com", 80);
  }
  delay(10000);
}
```

### Debug Message

```plain
Log message from normal operation:
rst:0x1 (POWERON_RESET),boot:0x23 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13104
load:0x40080400,len:3036
entry 0x400805e4
[     6][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[    29][E][main.cpp:76] setup(): Initialization is starting
[  8367][V][WiFiGeneric.cpp:437] _arduino_event_cb(): Ethernet Started
[  8367][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 18 - ETH_START
ETH Started[  8370][V][WiFiGeneric.cpp:430] _arduino_event_cb(): Ethernet Link Up

[  8380][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 20 - ETH_CONNECTED
ETH Connected
[ 10371][V][WiFiGeneric.cpp:434] _arduino_event_cb(): Ethernet Link Down
[ 10371][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 21 - ETH_DISCONNECTED
ETH Disconnected
[ 14371][V][WiFiGeneric.cpp:430] _arduino_event_cb(): Ethernet Link Up
[ 14371][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 20 - ETH_CONNECTED
ETH Connected[ 14381][V][WiFiGeneric.cpp:445] _arduino_event_cb(): Ethernet got newip:192.168.0.16

[ 14384][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 22 - ETH_GOT_IP
[ 14389][D][WiFiGeneric.cpp:1032] _eventCallback(): ETH IP: 192.168.0.16, MASK: 255.255.255.0, GW: 192.168.0.1
ETH MAC: 90:38:0C:B0:7A:5F, IPv4: 192.168.0.16, FULL_DUPLEX, 100Mbps

connecting to google.com
HTTP/1.1 301 Moved Permanently
Location: http://www.google.com/
Content-Type: text/html; charset=UTF-8
Cross-Origin-Opener-Policy-Report-Only: same-origin-allow-popups; report-to="gws"
Report-To: {"group":"gws","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/gws/other"}]}
Date: Fri, 06 Jan 2023 09:04:05 GMT
Expires: Sun, 05 Feb 2023 09:04:05 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 219
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
                                                                              <TITLE>301 Moved</TITLE></HEAD><BODY>
                                                                                                                   <H1>301 Moved</H1>
                                                                                                                                     The document has moved
          <A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
closing connection

Bad operation:

rst:0x1 (POWERON_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13104
load:0x40080400,len:3036
entry 0x400805e4
[     6][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[    29][E][main.cpp:111] setup(): Initialization is starting
[  9468][V][WiFiGeneric.cpp:437] _arduino_event_cb(): Ethernet Started
[  9468][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 18 - ETH_START
ETH Started
```

### Other Steps to Reproduce

Platformio configuration:

[env:esp-wrover-kit]
platform = espressif32@^5.3.0
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=5

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
I see that you are trying to use GPIO20 for PWM and also that GPIO15 does have RMII functionality. What if you do not start MCPWM on those two pins? Does IO2 work?

**Comment by rob-bits** [comment]
> I see that you are trying to use GPIO20 for PWM and also that GPIO15 does have RMII functionality. What if you do not start MCPWM on those two pins? Does IO2 work?

Good catch! I am checking.
The GPIO20 is used to monitor a delayed MCPWM signal state. I have to check the state of a delayed PWM signal at a specific time. And I do not have additional outputs so I am using an internal signal as @Esp_sprite suggested on esp32.com forum:
https://esp32.com/viewtopic.php?f=13&t=31171

**Comment by kostaond** [comment]
```c
gpio_set_direction((gpio_num_t) 20, GPIO_MODE_INPUT_OUTPUT);

...
esp_rom_gpio_connect_out_signal((gpio_num_t)20, mcpwm_periph_signals.groups[MCPWM_UNIT_0].operators[MCPWM0A / 2].generators[MCPWM0A % 2].pwm_sig, 0, 0);
```
Please double check usage of GPIO20. ESP32 does not have output at GPIO20, see TRM Section "4 IO_MUX and GPIO Matrix (GPIO, IO_MUX)". However, the strange thing is that `gpio_set_direction` allowed you to configure it. I'll try to get more information internally and let you know later.

**Comment by rob-bits** [comment]
> ```c
> gpio_set_direction((gpio_num_t) 20, GPIO_MODE_INPUT_OUTPUT);
> 
> ...
> esp_rom_gpio_connect_out_signal((gpio_num_t)20, mcpwm_periph_signals.groups[MCPWM_UNIT_0].operators[MCPWM0A / 2].generators[MCPWM0A % 2].pwm_sig, 0, 0);
> ```
> 
> Please double check usage of GPIO20. ESP32 does not have output at GPIO20, see TRM Section "4 IO_MUX and GPIO Matrix (GPIO, IO_MUX)". However, the strange thing is that `gpio_set_direction` allowed you to configure it. I'll try to get more information internally and let you know later.

See my comment before yours. The GPIO20 is an undocumented internal signal, it is used as a loopback signal. It would be nice if that would be listed on the documentation.

**Comment by kostaond** [comment]
I see, I didn't know about it. Regarding GPIO15, you don't have to worry about it. It is used for only when PHY is connected via MII.

**Comment by rob-bits** [comment]
Okay, so the thing is, if the esp_rom_gpio_connect_out_signal() is called for any of the three GPIO (2, 15, 20) the ethernet is broken. If the function is not called at all the ethernet works however I do not have PWM signals on the output. 

So if I remove the function call from the pwm_init() function and still call the pwm_init() the ethernet works. PWM signals does not.

**Comment by mrengineer7777** [comment]
esp_rom_gpio_connect_out_signal() appears to be a core function of ESP-IDF.  I was not able to find the source code, but it is referenced in many functions for IO.

**Comment by rob-bits** [comment]
Yes, I noticed, other people also was wondering the function of this. However as the name of the function and the header suggests, this function relates to the configuration of the IO mux and the GPIO matrix. The Technical Reference Manual is describing these registers so I guess I can write my function to enable the proper function on the selected GPIO. If the error will still preswnt then it will be a chip bug probably.

**Comment by Jason2866** [comment]
Calling a bug when using a non documented function? Probably it works different as you assume.

**Comment by rob-bits** [comment]
Sure, if the source code of that function would be released, the situation would be much cleaner. And as I said I can implement my function to configure the IO Mux and GPIO Matrix so theoretically that function can be left out and I can verify the operation of MCPWM + Ethernet.

**Comment by rob-bits** [comment]
> Calling a bug when using a non documented function? Probably it works different as you assume.

So I just did the testing. Configuring these registers (GPIO2 -> MCPWM0 OUTB signal):


volatile gpio_dev_t* sgGPIO_LL = (((volatile gpio_dev_t*) DR_REG_GPIO_BASE ));
  sgGPIO_LL->func_out_sel_cfg[2].func_sel = 33; //pwm0_outb is routed to signal 33
  sgGPIO_LL->func_out_sel_cfg[2].oen_sel = 1; //If the signal should always be enabled as an output, set the GPIO_FUNCx_OEN_SEL bit 
  sgGPIO_LL->enable |= 0x04;

Breaks the ethernet. So this is not firmware or software stuff. I just configure the GPIO matrix registers. Configuring these bits the MCPWM signal appears at the output however the ethernet is broken (as it is in my example).

Any idea what to check?

**Comment by rob-bits** [comment]
I did further testing and seems like GPIO2 causing the issue. If I assign the signal to 33, 14, 12, 13, 5,15, 20 GPIOs then the ethernet works fine. If I set for GPIO it got broken.

I repeated the testing with **esp_rom_gpio_connect_out_signal**() function and seems like the ethernet fails only with input parameter 2. Seems like I messed something last time...

Anyway, any idea why cannot I use GPIO2 for MCPWM?

**Comment by kostaond** [comment]
Could you please try to call
```
gpio_hal_iomux_func_sel(YOUR_GPIO, PIN_FUNC_GPIO);
```
following
`esp_rom_gpio_connect_out_signal` call?

There not much special about GPIO2 as of I know. Only just it is used as bootstrap pin.

**Comment by rob-bits** [comment]
> 



> Could you please try to call
> 
> ```
> gpio_hal_iomux_func_sel(YOUR_GPIO, PIN_FUNC_GPIO);
> ```
> 
> following `esp_rom_gpio_connect_out_signal` call?
> 
> There not much special about GPIO2 as of I know. Only just it is used as bootstrap pin.

Hmm, I do not know what is happening. I have two project, one is configured with the example project that I shared here. It is using Arduino v2.0.6. And I have another project, the main fw for our device, where a plenty of other things are configured. That uses arduino and esp-idf framework (v4.4.3 with unique menuconfig configuration). 

And after programming the main fw and reprogramming the example code now the MCPWM is working on GPIO2. Previously it was not working. I tried this with multiple programming tries before. And on Friday the ethernet did not work with any of the GPIO that I am using... So something odd is happening. Seems like something could be present in flash, after reprogramming when changing the esp-idf core, and that causes issues for me. I try to find out this now.

**Comment by rob-bits** [comment]
Ok I found out the issue is related to the hardware that we are using...

So I have this MCPWM signal (GPIO2) which goes over the lines of ethernet (EMAC_CLK_IN, EMAC_TXD0, MDIO, EMAC_TX_EN and MDC). And probably there is a crosstalk between the signals. It is a 4 layer board where one layer is dedicated for GND, and for 3.3V. However because of the component density there are small amount of some signals on the ground layers as well. Especially these ETH signals could not have a solid ground plane. See the image:

![image](https://user-images.githubusercontent.com/40227041/211346047-f333c5d8-588a-4d71-80dd-5cf9e502282b.png)
 
 The MCPWM is connected to the pink colored trace.

Any idea which signal could be affected?

**Comment by Jason2866** [comment]
Had issues with boards when GPIO 0 MAC_CLK_IN is disturbed "somehow"

**Comment by kostaond** [comment]
Try to check [these guidelines](https://resources.pcb.cadence.com/blog/2019-mii-and-rmii-routing-guidelines-for-ethernet) of how to route RMII traces.

**Comment by rob-bits** [comment]
> Try to check [these guidelines](https://resources.pcb.cadence.com/blog/2019-mii-and-rmii-routing-guidelines-for-ethernet) of how to route RMII traces.

Thanks, I will consider this next time.

However, what if I lower the speed of the interface? So basically 100mbit is not necessary, I could live with 10mbit as well. Can I do that? Does the Arduino framework support this?

And can I generate any kind of error to see really this is the issue?

So without MCPWM, pinging Google with period of 10 seconds is working well over hours of operation. And with MCPWM I have a connected state but do not get event for IP. And get no error or warning.

Can I get more status info from the phy or the connection? To determine what hangs?

**Comment by sauttefk** [comment]
Your signal quality seems to be very marginal when a PWM signal on an adjacent trace disturbes the EMAC signals this much.  
Try adding 22Ω to 33Ω series resistors on each of the EMAC RMII signals on the respective transmitter side. This will reduce signal reflections on the far end.
Also ground bounce could be an issue, it is very important to have a low impedance ground plane or strongly meshed copper fills.
Try to keep all traces of the EMAC signals almost the same length. Especially the each of the 3 signals for transmitting and receiving. 

Maybe you want to watch some of the [YouTube videos/tutorials of Robert Feranec](https://www.youtube.com/channel/UCJQkHVpk3A8bgDmPlJlOJOA) regarding PCB design and signal integrity.

**Comment by rob-bits** [comment]
> Your signal quality seems to be very marginal when a PWM signal on an adjacent trace disturbes the EMAC signals this much. Try adding 22Ω to 33Ω series resistors on each of the EMAC RMII signals on the respective transmitter side. This will reduce signal reflections on the far end. Also ground bounce could be an issue, it is very important to have a low impedance ground plane or strongly meshed copper fills. Try to keep all traces of the EMAC signals almost the same length. Especially the each of the 3 signals for transmitting and receiving.
> 
> Maybe you want to watch some of the [YouTube videos/tutorials of Robert Feranec](https://www.youtube.com/channel/UCJQkHVpk3A8bgDmPlJlOJOA) regarding PCB design and signal integrity.

Thanks I will try this out. I have issues high speed SPI + ethernet. Can that be the same issue?

Btw, I have a low impedance ground layer. However there are some signals which breaks the ground under the lines of RMMI:

![image](https://user-images.githubusercontent.com/40227041/211500075-d6b8d54b-c5e3-47a1-8db5-8503b3c27672.png)

**Comment by radzimir** [comment]
Probably slithly off-topic but I had similar problem with ESP32-CAM project using Camera Module and LEDC PWM.
The cause was, that camera module is using internaly as default LEDC_TIMER_0 and LEDC_CHANEL_0 (can be configured). 
After switching my code to LEDC_TIMER_1 and LEDC_CHANEL_1 all worked fine.
I found what aut by re-anabling my LEDC code line by line.

Hope this helps someone.
