### ISSUE TITLE
[Example] This WiFiClient example needs to be updated

### ISSUE THREAD

**Issue by pedrominatel** [espressif/arduino-esp32#7682]
This example needs to be updated since the "data.sparkfun.com" is no longer available.

https://github.com/espressif/arduino-esp32/blob/57b27cd800321e03c33f80bc5f2bf16aafb39b18/libraries/WiFi/examples/WiFiClient/WiFiClient.ino#L14

Change to any other working host.

**Comment by pedrominatel** [comment]
PTAL @PilnyTomas

**Comment by mrengineer7777** [comment]
I have found https://pipedream.com to be very helpful.

**Comment by PilnyTomas** [comment]
PR fixing this is merged
