### ISSUE TITLE
ESP32 Board Not downloaded in Arduino 1.8.19 IDE

### ISSUE THREAD

**Issue by mmfloom** [espressif/arduino-esp32#7715]
### Version

v2.0.6

### IDE Name

Arduino 1.8.19

### Operating System

windows 10

### Description

1. Hi, i am trying to install ESP32 by using the Stable Link: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

2. I have also tried after detecting all files in my C:\Users\user\AppData\Local\Arduino15 

3. but no use and I have received the below error message 

 "Error downloading https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"

4. I tying find solutions online, but I can't find 

please check below imgs 

![2023-01-15_11-34-29](https://user-images.githubusercontent.com/104716903/212525630-66a65a1d-3c23-4b20-9b93-1f67fb788be3.png)
![2023-01-15_11-35-17](https://user-images.githubusercontent.com/104716903/212525632-01f4c7ef-aea9-4aff-84c5-9c7b15e81a9d.png)

5. but the Old link is working " https://dl.espressif.com/dl/package_esp32_index.json" and the version is 1.0.6

![2023-01-15_11-56-36](https://user-images.githubusercontent.com/104716903/212526332-fdcf85d1-adc4-4dfd-bb8f-57b8a944e2d6.png)

6. I need the latest version 2.0.6 only 

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
Are you able to get to https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json in a web browser?

**Comment by mmfloom** [comment]
No, I am not able to get in a web browser, but some other links working,
please check this video.

https://user-images.githubusercontent.com/104716903/212587973-c2158265-7df2-4acf-bcfb-7c7b00c12119.mp4

**Comment by VojtechBartoska** [comment]
@mmfloom can you try another browser? It's a weird issue. Just an idea, maybe it's blocked by some "security related app" you have installed?

**Comment by mmfloom** [comment]
> VojtechBartoska

yes, I tried on mobile also, ESP32 link is not working, but the RP2040 link is working, I have attached that screen shorts for your reference 


https://user-images.githubusercontent.com/104716903/212813654-ef55ebb6-2449-4d4c-9b37-aca781fefefa.mp4


https://user-images.githubusercontent.com/104716903/212813676-b8a8fbbe-989d-4d52-8e52-d0d806791e4b.mp4

![photo_2023-01-17_10-17-47](https://user-images.githubusercontent.com/104716903/212813816-89d66624-845b-481d-aa70-de40704cab0e.jpg)

![photo_2023-01-17_10-17-33](https://user-images.githubusercontent.com/104716903/212813818-f8661652-2e2c-4aab-bdd4-8ba631d25075.jpg)

**Comment by mmfloom** [comment]
HI... the issue is solved by **enabling the VPN** !!!
please check the video,
thanks a lot for your support.


https://user-images.githubusercontent.com/104716903/213059289-ebeeacbc-68e6-4f24-a172-35b93136ea0a.mp4

**Comment by rohanpatil-rc** [comment]
I used vpn to put preference link  first and then downloaded(without vpn) from the board manger. thanks for your support

**Comment by the-confused-genius** [comment]
I have got the same issue. anyway, to resolve this without a vpn ?, and what's actually causing the issue?

**Comment by mmfloom** [comment]
I don't know exactly, but there is a chance that your country security system ( for example in India The National Cyber Coordination Centre (NCCC)) may mistakenly block this address or may mistakenly banned this address. So you need to use the VPN, otherwise you may do lot of research, if you find any alternative please update here.

**Comment by camp-easy** [comment]
hello, i receive the same issue..is the vp the only solution for this problem??? thank you in adveance.
