### ISSUE TITLE
TWAI/CAN and chip version - wroom-32 vs wroom-32E aka V3

### ISSUE THREAD

**Issue by handmade0octopus** [espressif/arduino-esp32#7723]
### Board

Not board specific

### Device Description

Noticed issue between two types of wroom-32U and wroom-32UE - the UE one apparently being version V3 https://www.espressif.com/en/news/ESP32_FIA_Analysis

### Hardware Configuration

Tested on 3x different boards, tried swapping transreceivers (SN65HVD231 and SN65HVD230), seems to be common culprit among all of them.

### Version

platformio one

### IDE Name

PlatformIO 5.2.0

### Operating System

Windows 10

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

921600

### Description

Ok so basically I am using [this CAN library](https://github.com/ThomasBarth/ESP32-CAN-Driver/tree/master/components/can)

Everything worked fine untill I got new boards with 32UE (extra E) which seems to be version V3. I read it requires new build setting in idf for it to work, there were some changes to IDF TWAI but not sure what.

Anyway tested with oscilloscope, on CAN, with 120 terminal resistor. Culprit is the same - 32U version works with same flash, none of my 32UE boards work with that.

I though its trans receiver but after swapping it - it's the same, only 32U version works. 

Is there any quick-dirty workaround for this issue?

Thanks.

### Sketch

```cpp
Not sketch specific but library uses which I hope didn't change in new version?

#define MODULE_CAN   ((volatile CAN_Module_t    *)0x3ff6b000)
```

### Debug Message

```plain
None
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by igrr** [comment]
There is an open feature request for the library you are using to support ESP32 revision 3: https://github.com/ThomasBarth/ESP32-CAN-Driver/issues/28.

You can try to implement that feature yourself, referring to this commit of the IDF CAN driver: https://github.com/espressif/esp-idf/commit/820fd6447d87490844d7e4fd6a1f8c7e0e97ba89

Alternatively, you can use IDF APIs described here: https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32/api-reference/peripherals/twai.html — they already work on ESP32 revision 3.

**Comment by handmade0octopus** [comment]
Thank you!
