### ISSUE TITLE
BLE library conflict with BLEPeripheral

### ISSUE THREAD

**Issue by vshymanskyy** [espressif/arduino-esp32#777]
Currently, the BLE library:
https://github.com/nkolban/ESP32_BLE_Arduino

Is conflicting with BLEPeripheral library:
https://github.com/sandeepmistry/arduino-BLEPeripheral

In example, the cannot be installed into Arduino IDE together.
It basically brakes the build of ESP32 BLE examples

**Comment by gtalusan** [comment]
I have a proposed fix here: https://github.com/sandeepmistry/arduino-BLEPeripheral/pull/200

**Comment by ayavilevich** [comment]
For now, edit library.properties file of the "arduino-BLEPeripheral" library and set
```architectures=nrf5``` manually.
