### ISSUE TITLE
get.py does not work on Linux system when Unicode character is used in directory's name

### ISSUE THREAD

**Issue by Patas007** [espressif/arduino-esp32#778]
get.py script from "tools" does not work on Linux systems which use localisation where standard names like "Downloads" are translated and contains unicode characters.

I created patch file which modifies get.py script.

[esp32_patch.txt](https://github.com/espressif/arduino-esp32/files/1417048/esp32_patch.txt)

**Comment by copercini** [comment]
Awesome!

Could you open a pull request with this modification?
Here is a simple and good tutorial of how to do this: https://www.youtube.com/watch?v=YTbRzhQju4c

**Comment by Patas007** [comment]
PR created. Sorry for "Issue" I opened.
