### ISSUE TITLE
API compatibility of WiFi.softAP() with ESP8266

### ISSUE THREAD

**Issue by artofit** [espressif/arduino-esp32#7780]
### Related area

API compatibility of WiFi.softAP() with ESP8266

### Hardware specification

ESP32 vs ESP8266

### Is your feature request related to a problem?

I was porting some code from ESP8266 to ESP32.
Encounter the following at compile:

With ESP8266 chip, the following

String myString="name of my AP net";
WiFi.softAP(myString, "my password);

is valid

Under ESP32
it does not compile, as API expect const char * and not String as valid type.

Therefore if you could add this behaviour, for the sake of simplicity and not breaking API behaviour.
WiFi.softAP(myString, "my password);

Thanks.

### Describe the solution you'd like

Add API:
WiFi.softAP(String acceptThis, String andAlsoThis)

### Describe alternatives you've considered

Modify source code.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
@artofit - PR #7801 shall add the requested API overloading.
