### ISSUE TITLE
undefined reference to uartGetEventQueue on linking

### ISSUE THREAD

**Issue by nikoyanakiev** [espressif/arduino-esp32#7785]
### Board

ESP32-S CAM

### Device Description

ESP32-CAM module is used

### Hardware Configuration

UART communication lines, 5V, GND and IO0 to GND for programming.

### Version

v2.0.6

### IDE Name

Arduino IDE v 2.0.3

### Operating System

Windows 10

### Flash frequency

80

### PSRAM enabled

yes

### Upload speed

115200

### Description

1. Installed Arduino IDE v 2.0.3
2. added https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json for the boards manager
3. tried directly to compile the CameraWebServer example, but failed due to multiple uart* missing interfaces (e.g. uartGetEventQueue and others from esp32-hal-uart.h).

A workaround which fixed the issue was to add
#include "esp32-hal.h" 
in HardwareSerial.cpp right after all other #include-s.

Note: after making the code compilable, flashed it once to the device, tested it OK, then commeting out the #include "esp32-hal.h" didn't reproduce the problem.

### Sketch

```cpp
the example CameraWebServer (#define CAMERA_MODEL_AI_THINKER is uncommented)
```

### Debug Message

```plain
undefined reference to uartGetEventQueue on linking
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@nikoyanakiev - I have done it and I got no error message. 
The difference to what is here described is that I had Arduino IDE 2.0.3 already installed along with the 2.0.6 Core version.

I think that sometimes the new 2.0x IDE fails after updated from previous version.
