### ISSUE TITLE
WifiSecureServer

### ISSUE THREAD

**Issue by meakashrao** [espressif/arduino-esp32#7789]
### Related area

Wifi

### Hardware specification

ESP32 DevKit C

### Is your feature request related to a problem?

https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFiClientSecure

As I can read here, this is a library for WiFiClientSecure, but I can't find any implementation for WifiServer similarly.

I want to make a ESP32 Web Sockets Server, and want to use SSL but I am not able to set CA certificates 

I might be completely off track, please correct me if so. I am a beginner and would appreciate if I have a starting point, if my current knowledge is completely off track

Regards,
Akash Rao

### Describe the solution you'd like

I'd like to have an understanding as to why WiFiSecureServer wasn't implemented or how can I make a ESP32 Websocket Server over ssl.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by mrengineer7777** [comment]
SSL adds a lot of processing overhead (RAM and time).  An SSL cert has to be generated for the server and updated regularly.  This doesn't make a lot of sense for a low power embedded device.  That said, you can build an HTTPS server in the lower level IDF: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/esp_https_server.html
