### ISSUE TITLE
Programming over the air

### ISSUE THREAD

**Issue by SirRibeiro** [espressif/arduino-esp32#78]
Hello,
Is it possible to program the Esp32 wireless?

Or is there any idea when it will be possible?

Thanks

**Comment by me-no-dev** [comment]
It will be possible yes, but it's not yet. Will be available when all requirements are fulfilled.

**Comment by git-tiger** [comment]
for commercial product, will the firmware be secure? Encrypt bin file.

**Comment by me-no-dev** [comment]
@git-tiger that would depend only on your implementation. ArduinoOTA would never make sense to be oversecured ;) it's meant for development, but there will be other options available (SSL server, so on) that would let you transfer updates securely post-production

**Comment by arcao** [comment]
@git-tiger Both [flash encryption](http://esp-idf.readthedocs.io/en/latest/security/flash-encryption.html) and [secure boot](http://esp-idf.readthedocs.io/en/latest/security/secure-boot.html) are supported in [Espressif IDF for ESP32](https://github.com/espressif/esp-idf/). Arduino-ESP32 framework is built upon it,  so it will be somehow supported in future _(I guess)_, but it's too early to speak about it. There is lot of other work to do first.

**Comment by me-no-dev** [comment]
implemented ;)

**Comment by inforaudio** [comment]
Have you got ready ESP32 OTA in arduino ide??

**Comment by mimansamaheshwari** [comment]
Is it possible to upload code multiple times via OTA on esp32 in Arduino Ide? If yes then how?
