### ISSUE TITLE
ESP32 S3  Always restart at startup

### ISSUE THREAD

**Issue by DreamPWJ** [espressif/arduino-esp32#7802]
### Board

v:esp32-s3-devkitc-1

### Device Description

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x403cd97a
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2920
entry 0x403c98d8
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x403cd97a

### Hardware Configuration

no 

### Version

v2.0.6

### IDE Name

PlatformIO 、   Clion

### Operating System

Windows11

### Flash frequency

40

### PSRAM enabled

no

### Upload speed

921600

### Description

![image](https://user-images.githubusercontent.com/16730031/216869490-72f0552e-3e0a-43f3-84de-a9ce833ddf9d.png)

### Sketch

```cpp
#include <Arduino.h>

void setup() {
// write your initialization code here
    // 设置UART串口波特率
    Serial.begin(115200);
    Serial.println("你好, ESP32 S3单片机");
}

void loop() {
// write your code here
    Serial.println("测试新主控芯片");
}
```

### Debug Message

```plain
SP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0xa (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2920
entry 0x403c98d8
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x403cd97a
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2920
entry 0x403c98d8
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by DreamPWJ** [comment]
platform = espressif32@4.4.0   work

**Comment by DreamPWJ** [comment]
esp32 s3   nvs  not work

**Comment by SuGlider** [comment]
I tested it with the Arduino IDE 1.8.18 and Arduino Core 2.0.6.
Using the same ESP32-S3 - Working Fine. 

Maybe something wrong with PIO configuration and tools?
@Jason2866 - Can you help, please?

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2920
entry 0x403c98d8
```

**Comment by SuGlider** [comment]
```
rst:0x3 (RTC_SW_SYS_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x403cd97a
```

It seems like a problem with the boot loader.
Maybe you can try the Arduino IDE with different options Flash/PSRAM OPI, QIO, DIO, etc.

**Comment by Jason2866** [comment]
What flash size and type does the board have? Guessing here ends in bootloops.
After setting correctly it will probably work. We can help in Platformio Setup, if you answer the question about flash.

**Comment by DreamPWJ** [comment]
use ESP32-S3-WROOM-1-N4， flash 4m， no psram @Jason2866

**Comment by Jason2866** [comment]
@DreamPWJ Put this settings in your [env]
```
board_build.flash_mode  = qio
board_build.flash_size  = 4MB
board_upload.maximum_size = 4194304
```
You had an error there. Wrong override name. Board is capable to run in mode `QIO` no need to reduce slower flash mode `DIO`

**Comment by DreamPWJ** [comment]
not work
E (231) esp_core_dump_flash: No core dump partition found!

**Comment by DreamPWJ** [comment]
use  espressif32@5.3.0      Serial1.read()   not work,  data is incorrect     `        while (Serial1.available()) {
            char c = Serial1.read();
            response += c;
        }`

**Comment by DreamPWJ** [comment]
board_build.flash_mode = qio  It doesn't work either, it's still dio  `ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2920
entry 0x403c98d8
E (231) esp_core_dump_flash: No core dump partition found!`

**Comment by Jason2866** [comment]
@DreamPWJ  I believe your code is not compatible to the actual version.
Have you tried a simple "Hello World"? If this does work the setup is correct.

**Comment by DreamPWJ** [comment]
but espressif32@5.0.0 all work @Jason2866

**Comment by DreamPWJ** [comment]
esp_core_dump_flash: No core dump partition found! This error message should not be a code problem at the beginning of the startup

**Comment by DreamPWJ** [comment]
I tested a my hello world, 5.3.0 doesn't work, 5.0.0 can

**Comment by Jason2866** [comment]
Can you upload the complete failing Hello World example setup to github?
Maybe we can reproduce the issue by this.

**Comment by DreamPWJ** [comment]
https://github.com/DreamPWJ/embedded-monorepo/tree/master/projects-demo/esp32-s3-demo ， set espressif32@5.3.0 , 4.3.0 work

**Comment by Jason2866** [comment]
Tested your example with 4.3.0 and 5.3.0. Both work. The Output of the 5.3.0 build
```
.Äx¯.¯xÄxÄ¯x¯.x.Äx.xÄx.x¯ÄÄÄÄÄ.Ä¯‰Ω†Â•Ω, ESP32 S3ÂçïÁâáÊú∫
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
ÊµãËØïÊñ∞‰∏ªÊéßËäØÁâáÂæ™ÁéØÊâßË°å
```

**Comment by DreamPWJ** [comment]
platformio has Espressif ESP32-S3-DevKitC-1-N8， no  Espressif ESP32-S3-DevKitC-1-N4?  I'm sure it's a difference caused by the size of the flash

**Comment by Jason2866** [comment]
@DreamPWJ  The settings are flash size. You can check the real size of your device flash via `esptool.py flash_id`  [See](https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/basic-commands.html) for more infos

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/219253902-7bccca04-4593-42ce-a856-f7103a36b2f3.png)

**Comment by mrengineer7777** [comment]
Stale
