### ISSUE TITLE
Is there an example about blufi

### ISSUE THREAD

**Issue by gary7530** [espressif/arduino-esp32#7806]
### Related area

blufi

### Hardware specification

ESP32-WROOM-32E

### Is your feature request related to a problem?

blufi example 

### Describe the solution you'd like

blufi example 

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
@gary7530 
Not with Arduino, but there is one for IDF.
https://github.com/wolfeidau/esp32-blufi-demo

If necessary, it is possible to create an IDF project with Arduino as Component.
By this way your Arduino "CPP Sketch" will be able to access the `esp_blufi` API.
