### ISSUE TITLE
GPIO 34 & 35 always reads as LOW with Pull-up

### ISSUE THREAD

**Issue by hasmqtt** [espressif/arduino-esp32#782]
### Hardware:
Board:							?ESP32 WROOM32?
Core Installation/update date:			?11/jul/2017?
IDE name:							?Platform.io?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
GPIO read on pin 34 and 35 returns LOW even I have used internal pull-up. One of post on ESP32 I have read as silicon bug and handled using RTC GPIOs 34 - 39 are impacted with this silicon bug. 

Appreciate help or pointers on how to resolve it.

### Sketch:
```cpp
#include <Arduino.h>

const int switchGPIOs[] = {34, 35, 32, 33, 25, 26}; //Connected to Switches
const int totalSwitches = sizeof(switchGPIOs)/sizeof(switchGPIOs[0]);
const int ssrGPIOs[] = {27, 14, 12, 13, 15, 2}; //Connected to LEDs

void initGPIOs() {
  for (int i = 0; i < totalSwitches; i++) {
    pinMode(switchGPIOs[i], INPUT_PULLUP);
    pinMode(ssrGPIOs[i], OUTPUT);
    digitalWrite(ssrGPIOs[i], HIGH);
  }
}

void readSwitches() {
  for (int i = 0; i < totalSwitches; i++) {
    int value = digitalRead(switchGPIOs[i]);
    Serial.printf("Value read is %d ==> %d\n", i, value);
    digitalWrite(ssrGPIOs[i], value);
  }
}

void setup() {
 Serial.begin(115000);
 initGPIOs();
}

void loop() {
readSwitches();
delay(30);
}
```

### Debug Messages:
None

**Comment by MarkyAD** [comment]
Those pins (gpio34-39) dont have software pullup/down functions. Use an external pullup resistor, 10K works here.

**Comment by hasmqtt** [comment]
Thanks for reply, then I will have to redesign my hardware :(

**Comment by NickChungVietNam** [comment]
MarkyAD  Thank you.

**Comment by TroyFletcher** [comment]
> Those pins (gpio34-39) dont have software pullup/down functions. Use an external pullup resistor, 10K works here.

THANK YOU! This was driving me crazy.

**Comment by csobrinho** [comment]
Also drove me crazy for the last 2 days. Added a 10K and magic...
😖😖😖

**Comment by malachib** [comment]
This saved me a lot of time, thank you!  For those extra picky people (like me) who want to see it in the official docs, [here it is](https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32/api-reference/peripherals/gpio.html#_CPPv418gpio_set_pull_mode10gpio_num_t16gpio_pull_mode_t)

**Comment by amandedhia** [comment]
Thanks for this! It is 3am and I was about to pull my hair out! Now I'm only pulling 10k
