### ISSUE TITLE
(( analogRead() ))    Strange fluctuations of values when using multiple analogRead()

### ISSUE THREAD

**Issue by ic1414** [espressif/arduino-esp32#7820]
### Board

ESP32 Dev Module

### Device Description

ESP32 Dev Module and four potential meters.

### Hardware Configuration

Potential meters connect to GPIO 36, 39, 34, 35

### Version

v1.0.6

### IDE Name

Arduino IDE

### Operating System

Windows10

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Example 1
The value of j2x follows the variation of j1y, but the value of j2x is expected to be a constant. The red one is j1y, and the green one is j2x.
![serialPlotter](https://user-images.githubusercontent.com/93729382/217888555-bc964efa-1ce3-4ff3-9b2f-34224c9a12d1.jpeg)

```c++

#define j1x 36
#define j1y 39
#define j2x 34
#define j2y 35

void setup() {
  Serial.begin(250000);
  pinMode(j1x, INPUT);
  pinMode(j1y, INPUT);
  pinMode(j2x, INPUT);
  pinMode(j2y, INPUT);
}


void loop() {
  int vals[4];
  vals[0] = analogRead(j1x);
  vals[1] = analogRead(j1y);
  vals[2] = analogRead(j2x);
  vals[3] = analogRead(j2y);

  for (int i = 0; i < 4; i++) {
    Serial.print(vals[i]);
    Serial.print("   ");
  }
  Serial.println();

  delay(2);
}
```

### Example 2
When swapping the sequence of analogRead(), the problem becomes j2x following the variation of j2y. The yellow one is j2y, and the green one is j2x.and the 
![图片](https://user-images.githubusercontent.com/93729382/217893378-5b092788-c34f-4207-bd42-704abecf5a38.png)
```c++
  vals[2] = analogRead(j2x);
  vals[0] = analogRead(j1x);
  vals[1] = analogRead(j1y);
  vals[3] = analogRead(j2y);
```

### Sketch

```cpp
#define j1x 36
#define j1y 39
#define j2x 34
#define j2y 35

void setup() {
  Serial.begin(250000);
  pinMode(j1x, INPUT);
  pinMode(j1y, INPUT);
  pinMode(j2x, INPUT);
  pinMode(j2y, INPUT);
}

void loop() {
  int vals[4];
  vals[0] = analogRead(j1x);
  vals[1] = analogRead(j1y);
  vals[2] = analogRead(j2x);
  vals[3] = analogRead(j2y);

  for (int i = 0; i < 4; i++) {
    Serial.print(vals[i]);
    Serial.print("   ");
  }
  Serial.println();

  delay(2);
}
```

### Debug Message

```plain
.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@ic1414 -
Please decribe (or send a diagram) about how the Potential Meters are connected to the input pins.

**Comment by ic1414** [comment]
@SuGlider Sorry for the late reply.
![IMG_2948](https://user-images.githubusercontent.com/93729382/218104428-a5182e15-39c0-40b9-9c7f-1c88eab04b08.jpg)

**Comment by SuGlider** [comment]
Thanks @ic1414 !
@PilnyTomas, could you try to replicate the issue and investigate it, please?

**Comment by kapyaar** [comment]
@ic1414 If you have the option, can you connect the 3V3 line of the pots to something separate from what is powering the esp board, (make sure the grounds of both power supplies are connected), and see if the same issue persists?

**Comment by PilnyTomas** [comment]
@ic1414 could you please tell us what are the approximate values of your potentiometers? I will try to reproduces with static resistors.
I have the same suspicion as @kapyaar.

**Comment by ic1414** [comment]
@PilnyTomas, they are all 5kΩ potentiometers, and their initial position is in the middle. In other words, the initial output of poetenriometers is 3V3/2. The line circled in red in the image below is the initial output.
![图片](https://user-images.githubusercontent.com/93729382/219057427-a78db1f5-3737-47ab-a8b6-7da0159ebc59.png)

**Comment by ic1414** [comment]
> @ic1414 If you have the option, can you connect the 3V3 line of the pots to something separate from what is powering the esp board, (make sure the grounds of both power supplies are connected), and see if the same issue persists?

@kapyaar @PilnyTomas , I will try this, but it might take a bit of time.

**Comment by TD-er** [comment]
Pin 36 and 39 are connected to the internal Hall sensor.
Maybe you can try other pins on ADC1?

**Comment by ic1414** [comment]
> @ic1414 If you have the option, can you connect the 3V3 line of the pots to something separate from what is powering the esp board, (make sure the grounds of both power supplies are connected), and see if the same issue persists? With no fixed resistors in between, you could be overloading the power supply/ affecting the adc reference. just a hunch.

@kapyaar @PilnyTomas @TD-er I tried with a new development board, and everything is OK (with no separation of the power supply). Probably the problem was caused by the high soldering temperature. Sorry to interrupt.
