### ISSUE TITLE
Enable adding multiple mDNS hostname

### ISSUE THREAD

**Issue by Zhu-jiatong** [espressif/arduino-esp32#7833]
### Related area

WiFi

### Hardware specification

Not relevant

### Is your feature request related to a problem?

I am working on a webserver project where I need to have 2 URLs distinguished by their subdomain names:
`domain.local` and `subdomain.domain.local`

Each should point route to a different server instance on different ports:
`AsyncWebServer main_server(80)` and `AsyncWebServer sub_server(81)`

I am not sure if there is already an existing method to achieve this. If not, this would be a nice addition.

### Describe the solution you'd like

Multiple MDNS instances or `MDNS.add_host(const char* hostname)`...

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
This is not how mDNS works. You can have only one hostname for given network interface. You can do what you want with DNS

**Comment by Zhu-jiatong** [comment]
Is there any way by which I can achieve this on both AP and STA interfaces?

Best regards,

**Comment by Jason2866** [comment]
Closing since not possible.

**Comment by kscheff** [comment]
According to this old post it is possible: http://esp32.io/viewtopic.php?t=8018
