### ISSUE TITLE
ESP32 Problem after properly uploading the code 

### ISSUE THREAD

**Issue by arballes** [espressif/arduino-esp32#7874]
### Board

ESP32 Wrover module

### Device Description

![image](https://user-images.githubusercontent.com/125959937/220302843-b7ef4c05-c10d-4e24-bba5-9bf5abc2fba9.png)

### Hardware Configuration

.

### Version

latest master (checkout manually)

### IDE Name

Adriuno IDE

### Operating System

Windows10

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

after copying this for my project 
https://www.youtube.com/watch?v=HfQ7lhhgDOk
the uploading part was finish but when i checked in the serial monitor if it will work this is what it shows
![image](https://user-images.githubusercontent.com/125959937/220303018-e5a7d925-431b-4980-928d-13c96fbebae6.png)

then i remove this pins on 10O and GND in ESP32 this is what it will show
![image](https://user-images.githubusercontent.com/125959937/220303713-1e7e467f-e70d-40db-80ef-17d364de441e.png)

### Sketch

```cpp
.
```

### Debug Message

```plain
.
```

### Other Steps to Reproduce

.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
IO0 must not be connected to GND in order for the ESP32 to boot. That is the pin that controls if the board boots into Download Mode or Flash to run your firmware
