### ISSUE TITLE
It cannot stop advertisement after that advert.start(4, 0);.

### ISSUE THREAD

**Issue by talashganvir** [espressif/arduino-esp32#7886]
### Related area

bluetooth start adv

### Hardware specification

ESP32C3 DEV MODULE

### Is your feature request related to a problem?

It cannot stop advertisement after that advert.start(4, 0);.

### Describe the solution you'd like

I used stop function but it reset the whole code

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
@talashganvir 

There is  `start()` and `stop()`in Advertising API:

https://github.com/espressif/arduino-esp32/blob/7856de7a57420e494176c16c5138174fe2c1dad0/libraries/BLE/src/BLEAdvertising.h#L47-L53

**Comment by SuGlider** [comment]
The same for `BLEMultiAdvertising` ... There is `stop(...)`

https://github.com/espressif/arduino-esp32/blob/7856de7a57420e494176c16c5138174fe2c1dad0/libraries/BLE/src/BLEAdvertising.h#L99-L102

**Comment by en129** [comment]
I'm also facing the same issue.
I understand there is a stop function. However, I don't know how to use the second argument ext_adv_inst.

**Comment by talashganvir** [comment]
No

**Comment by DavideLentini** [comment]
@en129 
@talashganvir 
@SuGlider 
Hi all ! Some problem here . 
How do I use this function for stop the advertising? 
Which kind of data is ext_adv_inst? 
Thanks all
