### ISSUE TITLE
Problem about WIFI scan

### ISSUE THREAD

**Issue by Heltec-Aaron-Lee** [espressif/arduino-esp32#791]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							ESP-32S Module
Core Installation/update date:			30/Oct/2017
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
When we test the WIFI scan examples, no network can be found. we tested with many boards or modules.

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by beegee-tokyo** [comment]
Check [#758](https://github.com/espressif/arduino-esp32/issues/758) for a solution.
