### ISSUE TITLE
UVC camera stream over USB | connect a camera like OV7670 to ESP32-S3 and then stream to computer using USB uvc class.

### ISSUE THREAD

**Issue by dev-techshlok** [espressif/arduino-esp32#7910]
### Related area

UVC camera boards

### Hardware specification

ESP32-S3

### Is your feature request related to a problem?

Unbale to make a usb webcam with usb-host feature.

### Describe the solution you'd like

When we connect any parallel camera to esp32, provide a USB-host driver that can simulate a uvc camera class and stream over usb to cimputer like a webcam.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
You are actually looking to create UVC Device and not Host. Generally it's not an issue, but in reality the Host (computer) requires faster USB standard than what is available on S2/S3, so even when proper USB device is created, the Host is not recognizing it as a working camera.
