### ISSUE TITLE
Mac OSX intallation 

### ISSUE THREAD

**Issue by totovr** [espressif/arduino-esp32#792]
I'm trying to set it up in Arduino 1.8.1 version but I got the next error in the installation step

Traceback (most recent call last):
  File "get.py", line 27, in <module>
    current_dir = os.path.dirname(os.path.realpath(unicode(__file__)))
NameError: name 'unicode' is not defined

----------------------------- Remove above -----------------------------

### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			30/oct/2017
IDE name:							Arduino IDE 1.8.1

### Description:
I'm trying to set it up in Arduino 1.8.1 version but I got the next error in the installation step

**Comment by me-no-dev** [comment]
interesting... what version OSX?

**Comment by totovr** [comment]
Sorry I forgot it, I'm using Sierra

**Comment by totovr** [comment]
![screen shot 2017-10-30 at 19 55 15](https://user-images.githubusercontent.com/15333235/32167474-496bbb46-bdac-11e7-94e7-399e3a46b955.png)

**Comment by me-no-dev** [comment]
can you run ```python --version``` please? Same OSX here. BTW no need to run the whole command again, just cd into esp32/tools and run ```python get.py``` from there

**Comment by totovr** [comment]
Im currently using version 3.6.2.

![screen shot 2017-10-30 at 20 04 31](https://user-images.githubusercontent.com/15333235/32167832-962e1a54-bdad-11e7-97a5-79592dddc3fe.png)

**Comment by me-no-dev** [comment]
ahh :) try python2 ;) I will look into p3 later

**Comment by totovr** [comment]
Done, I return to version 2.7 and is working normally.
Thank you very much!

<img width="492" alt="screen shot 2017-10-30 at 20 10 56" src="https://user-images.githubusercontent.com/15333235/32168099-9568ffc0-bdae-11e7-98df-82c1ecf08e8c.png">

I think that Python 3.x doesn't recognize the route of the path.

**Comment by alustig3** [comment]
replacing "unicode" with "str", fixes the problem.

line 27 of get.py before:
`current_dir = os.path.dirname(os.path.realpath(unicode(__file__)))
`
after 
`current_dir = os.path.dirname(os.path.realpath(str(__file__)))`
