### ISSUE TITLE
Old json installation link conflict - New core does not appear

### ISSUE THREAD

**Issue by rtek1000** [espressif/arduino-esp32#7929]
### Board

ESP32

### Device Description

Not applied

### Hardware Configuration

Not applied

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE 1.8.19

### Operating System

Linux Xubuntu 22.04

### Flash frequency

Not applied

### PSRAM enabled

yes

### Upload speed

Not applied

### Description

https://dl.espressif.com/dl/package_esp32_index.json

![Screenshot_2023-03-04_17-37-21](https://user-images.githubusercontent.com/8660811/222928119-d6fc0db1-77b4-480f-9525-5e0e49c60fa3.png)

### Sketch

```cpp
Not applied
```

### Debug Message

```plain
Not applied
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Hi :) What is the actual issue? Just switch to the new link.

**Comment by rtek1000** [comment]
The problem occurs when you have this core version 1 and version 2 link, but only the core version 1 appears to install. If one has many core links, it can get a little confusing.

It's more of a tip than a problem to solve.

I noticed that due to the v2 core it generates duplicate library warnings as well. But they are ESP8266 core libraries.

**Comment by rtek1000** [comment]
I noticed that it is not enough to remove the link, you have to uninstall the core version 1 for the core version 2 to appear in the manager.

**Comment by VojtechBartoska** [comment]
There is nothing we can do about this, closing as won't fix.
