### ISSUE TITLE
eps32cam  esp_camera.h Unable to introduce

### ISSUE THREAD

**Issue by zkbutt** [espressif/arduino-esp32#7931]
### Related area

eps32cam 

### Hardware specification

eps32cam

### Is your feature request related to a problem?

Cannot be referenced under E:\kaifa\esp-idf\yufa\components\arduino\libraries directory
hint

fatal error: esp_camera.h: No such file or directory
 #include "esp_camera.h"
![图片](https://user-images.githubusercontent.com/18031838/222940022-fc5f7ac9-30ab-489e-b834-a61d61f7f05d.png)

### Describe the solution you'd like

How to refer to esp_camera.h, which is in... components\arduino\tools\sdk\esp32\include\esp32-camera\driver\include\esp_camera

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
Since you are using Arduino as ESP-IDF component, you need to import the esp32-camera component in your project manually. In your case, nothing in `tools/sdk` is used in compilation
