### ISSUE TITLE
esp32s3 doesn't support EXT_RAM_ATTR

### ISSUE THREAD

**Issue by flybeyond** [espressif/arduino-esp32#7969]
### Board

ESP32S3 Dev Module

### Device Description

esp32s3

### Hardware Configuration

esp32s3

### Version

v2.0.7

### IDE Name

Arduino

### Operating System

FreeRTOS

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

Hi there,
eps32s3 memory.ld doesn't contain external ram and sections.ld put related sections to dram0, but esp32s2 has the defination. Any plans to add or reasons for not adding?

eps32s2:

   /* external memory bss, from any global variable with EXT_RAM_ATTR attribute*/
  .ext_ram.bss (NOLOAD) :
  {
    _ext_ram_bss_start = ABSOLUTE(.);

    . = ALIGN(4);
    _ext_ram_bss_end = ABSOLUTE(.);
  } > extern_ram_seg

  extern_ram_seg(RWX) : org = 0x3F500000,
                                     len = 0xA80000

esp32s3:

.dram0.bss (NOLOAD) :
  {
    . = ALIGN (8);
    _bss_start = ABSOLUTE(.);
    *(.ext_ram.bss*)

    *(.bss .bss.*)
    *(.ext_ram.bss .ext_ram.bss.*)
...
}

### Sketch

```cpp
eps32s2:

   /* external memory bss, from any global variable with EXT_RAM_ATTR attribute*/
  .ext_ram.bss (NOLOAD) :
  {
    _ext_ram_bss_start = ABSOLUTE(.);


    . = ALIGN(4);
    _ext_ram_bss_end = ABSOLUTE(.);
  } > extern_ram_seg

  extern_ram_seg(RWX) : org = 0x3F500000,
                                     len = 0xA80000

esp32s3:

.dram0.bss (NOLOAD) :
  {
    . = ALIGN (8);
    _bss_start = ABSOLUTE(.);
    *(.ext_ram.bss*)

    *(.bss .bss.*)
    *(.ext_ram.bss .ext_ram.bss.*)
...
}
```

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
I suggest you ask for explanation over at ESP-IDF's repo, since this is where all of that is coming from. We use it as-is
