### ISSUE TITLE
ESP32-S3 intermittant reboot

### ISSUE THREAD

**Issue by xinkiknix** [espressif/arduino-esp32#7973]
### Board

ESP32-S3 Dev Module

### Device Description

Nothing

### Hardware Configuration

BMP680

### Version

latest master (checkout manually)

### IDE Name

Arduino

### Operating System

Windows 11

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

I have a sketch running and once in a while it just reboots for no apparent reason.

It is a temperature monitoring system acting as a thermostat with a WIFI interface for setting data and wifi connection to the actual 
heating switch.

I log every reboot:
<html><body>

reboot 02 /09 20:44:33
reboot 02 /11 08:36:42
reboot 02 /18 09:33:33
reboot 02 /21 01:56:37
reboot 02 /22 12:42:25
reboot 02 /22 21:51:25
reboot 02 /23 23:55:48
reboot 02 /24 18:17:14
reboot 02 /24 18:27:00
reboot 03 /01 20:47:43
reboot 03 /02 07:53:38
reboot 03 /07 13:37:32
reboot 03 /16 17:04:01

</body>
</html>

I can't find any frequency nor action being performed that could cause this to happen. The system runs 24/7 and has no specific timeing event running 

### Sketch

```cpp
I have not found any reason/code point that could initialte the failure as it happens just so rarely
```

### Debug Message

```plain
none available
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment]
It sounds like a memory leak or other crash.  That reboot message doesn't exist in this repository, so it must be from your code.  Without code or a project demonstrating the issue there's nothing we can troubleshoot here.  

Things to try:
Capture serial data to a log with a program like Teraterm.  Try to capture an exception message.
On startup print the reboot reason
Monitor your heap usage

```
void PrintRebootReason(void) {
	RESET_REASON r = rtc_get_reset_reason(0);
        Serial.printf("Reset reason %i\r\n", r);
}
```

```
uint32_t prevheap = 0;
void monitor_heap(void) {
    uint32_t curheap = ESP.getFreeHeap();
    bool IsChanged = false;
    if (prevheap != curheap) {
        static uint32_t heap_highwater_mark = 0;
        static uint32_t heap_lowwater_mark = UINT32_MAX;

        if (curheap < heap_lowwater_mark) {IsChanged = true; heap_lowwater_mark = curheap;} 
        if (curheap > heap_highwater_mark) {IsChanged = true; heap_highwater_mark = curheap;}

        if(IsChanged) {
            uint32_t maxblock = ESP.getMaxAllocHeap();
            log_i("Heap   Free %u   Min %u   Max %u   Contig %u [%i]",
                curheap, heap_lowwater_mark, heap_highwater_mark, maxblock, xPortGetCoreID());
        }
        prevheap = curheap;
    }
}
```

**Comment by xinkiknix** [comment]
I will integrate this ASAP, but as you saw from the log sometimes there is over a week between  reboots or 10 minutes, ..

**Comment by mrengineer7777** [comment]
@xinkiknix Any updates?

**Comment by mrengineer7777** [comment]
Update?

**Comment by xinkiknix** [comment]
Since adding the heap checking I did not get any new reboots. Issue solved? or does the heap checking have any hidden functionality?

**Comment by mrengineer7777** [comment]
As far as I know, the heap checking doesn't do anything special to prevent crashes.

**Comment by VojtechBartoska** [comment]
Closing this ticket as answered, if needed, you can reopen.

**Comment by xinkiknix** [comment]
After running for a long period (since march 2023) I have had a few instances where the reboot reason was not power off/on. these seem to come in short sequences. the first:

```
reboot 08/07 14:04:25 reason:12
--
reboot 08/07 19:32:01 reason:12
reboot 08/07 19:51:25 reason:12
reboot 08/07 20:43:25 reason:12
```
and last week

reboot 10/19 11:10:05 reason:12
--
reboot 10/19 11:16:42 reason:12

Any suggestions ? is this a HW issue?
