### ISSUE TITLE
WiFi startup interferes with digital output on pins 25/26

### ISSUE THREAD

**Issue by ajuniper** [espressif/arduino-esp32#7980]
### Board

ESP32-WROOM-DA

### Device Description

devkit module with LED/relay driver on pins 25/26

### Hardware Configuration

Pins 25/26 connected to LED or opto isolator.

### Version

v2.0.7

### IDE Name

Arduino 2.0.4

### Operating System

Windows 10

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

Am using digital output on ports 25/26.
Have set pin mode to output and also called `dacDisable()` on those pins.
All is fine until WiFi gets started at which point the output voltage goes awry and the relays gain a mind of their own due to an indeterminite voltage appearing.
Once WiFi is started, this continues until I call `dacDisable()` on those pins again.
After calling `dacDisable()` the WiFi continues to work as expected.
My project is not using ADC or DAC.

Is there a way to prevent starting WiFi from interfering with the pin mode?  i don't want the pins outputing anything during bootup.

### Sketch

```cpp
#define PINA 25
#define PINB 26

// relay outputs are inverted
#define RELAY_ON LOW
#define RELAY_OFF HIGH

#include <WiFi.h>
const char* ssid     = "aaa";
const char* password = "bbb";

void setup() {
  Serial.begin(115200);
  Serial.setTimeout(60000);

  Serial.println(__LINE__);
  Serial.readStringUntil('x');

  dacDisable(PINA);
  dacDisable(PINB);
  digitalWrite(PINA,RELAY_OFF);
  pinMode(PINA,OUTPUT);
  digitalWrite(PINB,RELAY_OFF);
  pinMode(PINB,OUTPUT);

  Serial.println(__LINE__);
  Serial.readStringUntil('x');

  // Connect to Wi-Fi
  WiFi.begin(ssid, password);

  // 50ms delay is not enough
  delay(50);
  dacDisable(PINA);
  dacDisable(PINB);

  // wait for wifi to be ready
  while (WiFi.status() != WL_CONNECTED) {
      Serial.println("Connecting to WiFi..");
      delay(1000);
  }

  Serial.println(WiFi.localIP());

  Serial.println(__LINE__);
  Serial.readStringUntil('x');

  dacDisable(PINA);
  digitalWrite(PINA,RELAY_OFF);
  pinMode(PINA,OUTPUT);
  dacDisable(PINB);
  digitalWrite(PINB,RELAY_OFF);
  pinMode(PINB,OUTPUT);
  // pins behave correctly again

  Serial.println(__LINE__);
  Serial.readStringUntil('x');
}

static int a=0;
void loop() {
  // put your main code here, to run repeatedly:
  if ((++a)%2) {  
      digitalWrite(PINB,RELAY_OFF);
      digitalWrite(PINA,RELAY_ON);
  } else {
      digitalWrite(PINB,RELAY_ON);
      digitalWrite(PINA,RELAY_OFF);
  }
  delay(2000);
}
```

### Debug Message

```plain
n/a
```

### Other Steps to Reproduce

tried some other register settings found on internet which made no difference

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by PrintableProps** [comment]
I kinda have the same problem. If I use Wifi I am no longer able to send commands via serial1 or 2 (which I configured with gpio 25 and 26 as rx and tx) Other pins don't work either.

**Comment by ajuniper** [comment]
OK seems like it was my bad.
I am using a ESP32_DevkitC_V4 with a WROOM-32D module.
Rookie mistake was to pick the board which most closely matched the processor - turns out that "ESP32-WROOM-DA" is the wrong board type to pick, and the correct one is actually just "ESP32 Dev Module".  Having picked that, the pins work as expected.
This is my first usage of ESP32 and the internet had not given me sufficient clues on the correct module to pick, and everything else was working fine even with the wrong module selected.

**Comment by kenkit** [comment]
This also happened to me, was about to leave a bad review to the seller since only pin25 was not working, everything I tried didn't work on that pin. I used esp board view. Then I came accross your comment which solved it

**Comment by Rainer-vde** [comment]
Thanks for this - It saved my life after several hours of searching the problem i gladly stumbled over this. The "ESP32 Dev Module" was the right tip!!!
