### ISSUE TITLE
ESP32 Flash Write Freeze

### ISSUE THREAD

**Issue by savejeff** [espressif/arduino-esp32#7998]
### Board

ESP32 DevModule

### Device Description

Nothing Attached. Plane ESP32 Board

### Hardware Configuration

-

### Version

v2.0.7

### IDE Name

PlatformIO

### Operating System

Windows 10

### Flash frequency

-

### PSRAM enabled

no

### Upload speed

921600

### Description

Okay this is a weird one 

Short Explanation: 
 Im getting complete processor freezes when writing to the flash via the EEPROM lib or via SPIFFS. 
 this happens only on ESP32 - the same code runs fine on ESP32-S3
 The weird thing: I tried reducing the code to a minimal version but at some point removing more UNUSED code (no matter what code) solves the problem

- There is no hardware attached to the esp32
- i initialize 3 Serial, 1 SPI and 2 software I2C but I do nothing with them. removing the initialization removed the problem but removing other code unrelated to hardware ports also solves it (so i conclude its not about the hardware ports itself)
- i tested this with multiple ESP32 boards from different vendors as well as blank ESP32-Wroom modules purchased from mouser
- i can not offer a single sketch file that demonstrates the problem, as removing too much code solves the problem
- i tested this with all major firmware versions above 2.0.0
- there are no interrupts or other tasks running that might access/write to flash

Other Things i found out:
 - the code freezes in the nvs set blob code
for example in EEPROM::commit here `esp_err_t err = nvs_set_blob(_handle, _name, _data, _size);` 

 - there is no stack traceback when the watchdog is triggered - usually I get an exception msg at info what task triggered it
 - the complete processor freezes as parallel tasks also stop 
 - the problem goes away even if i start moving code from one .cpp to another (which should not happen as it does not change the code)

my best guess: some amount of user code above a certain threshold causes more flash to be used which then freezes the flash write operation. it might also be something about the amount of variable symbols or something like that. I also thought it might be related to a redefine or something like that, but then removing random unused code should not solve the problem

I'm working on this problem for a while now, and I just can't find where this is coming from. the software is compatible with ESP32 and ESP32-S3. on the S3 the code runs with no problem on many of my products, but on the ESP32 it just freezes

I'm pretty much out of ideas and as I don't even get a exception i have no idea how to further approach this problem.
I can offer my code in private to help to demonstrate the problem. a blank ESP32 board is enough to test it.

Any 

### Sketch

```cpp
#include "Defines.h"
#include "global.h"


#include "EEPROM.h"
#include "SD_MMC.h"
#include "SPIFFS.h"
#include <esp_task_wdt.h>

void setup() 
{

	// Init Serial, I2C and SPI
	SERCOM_Module_Init();

	esp_task_wdt_init(120, true); // above 60s needed for SPIFFS format
		
	SPIFFS.begin(true);

	Serial.println("SPIFFS init done");


	EEPROM.begin(512);
	
	uint8_t c = 0;
	while (true)
	{	

		c++;
		Serial.printf(">>>> WRITE %d\n", c);
		Serial.flush();

		EEPROM.writeByte(0x8C, c);
		EEPROM.commit();	

		delay(1000);

	}
}

void loop() {

}
```

### Debug Message

```plain
…
>>> WRITE


rst:0x7 (TG0WDT_SYS_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by savejeff** [comment]
Hi!,

thanks for the quick response. 
i dont think its only about the EEPROM code. if i erase the flash, it gets stuck when initializing the SPIFFS. that leads me to think its generally about the Flash writing.

since i posted i was able to reduce the code even more and it still freezes. i think im able to reduce it even more sind building no takes only 60s not 10min. ill reach out to you when i get to the smallest code base

**Comment by mrengineer7777** [comment]
Hmmm do you use a custom partition definition?  If so, compare to https://github.com/espressif/arduino-esp32/tree/master/tools/partitions.

**Comment by mrengineer7777** [comment]
That's an important data point.  I don't specify a partition at all, so it uses whatever the default is.  Try the default.  If that works then there might be an issue with the min_spiffs definition.

**Comment by savejeff** [comment]
i removed any specification to partitions. no it freezes while initializing the spiffs partition. 
I'm close to having a code base I'm comfortable to share (around 90% of code thrown out but still around 100 files left)

**Comment by savejeff** [comment]
im closing this as i created a new issue with updated information
