### ISSUE TITLE
ESP32 read input voltage from direct power supply

### ISSUE THREAD

**Issue by patelabhi23** [espressif/arduino-esp32#8004]
### Related area

Code update

### Hardware specification

ESP32 module

### Is your feature request related to a problem?

I want to monitor the voltage of the power source directly supplied to my ESP32 board to prevent any damage that may occur due to overvoltage, as it had happened before. 

### Describe the solution you'd like

Function like ADC converter to monitor voltage from power source

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
Hello, I'm closing this issue as expired due to no answer to keep the size of issue tracker maintainable, thanks for understanding. If needed, you can reopen.
