### ISSUE TITLE
 esp32-s3 cannot find F_CPU for FastLed

### ISSUE THREAD

**Issue by coskunyildirimcosel** [espressif/arduino-esp32#8005]
### Board

ESP32-S3

### Device Description

 esp32-s3 cannot find F_CPU for FastLed

### Hardware Configuration

NO

### Version

v2.0.7

### IDE Name

ESP-IDF

### Operating System

Windows10

### Flash frequency

40Mhz

### PSRAM enabled

yes

### Upload speed

921600

### Description

 esp32-s3 cannot find F_CPU for FastLed

### Sketch

```cpp
#ifndef HAL_ESP32_HAL_H_
#define HAL_ESP32_HAL_H_

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <inttypes.h>
#include <string.h>
#include <math.h>
#include "sdkconfig.h"
#include "esp_system.h"
#include "esp_sleep.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include "freertos/event_groups.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef F_CPU
#if CONFIG_IDF_TARGET_ESP32 // ESP32/PICO-D4
#define F_CPU (CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ * 1000000U)
#elif CONFIG_IDF_TARGET_ESP32S2
#define F_CPU (CONFIG_ESP32S2_DEFAULT_CPU_FREQ_MHZ * 1000000U)

//not esp32-s3
```

### Debug Message

```plain
esp32-s3 cannot find F_CPU for FastLed
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment]
What is FastLed?  In this repository `F_CPU` should be defined in boards.txt.  However your code looks like IDF code.  Did you mean to post here: https://github.com/espressif/esp-idf/issues ?

**Comment by Jason2866** [comment]
There is a open PR to fix this https://github.com/espressif/arduino-esp32/pull/7913

**Comment by SuGlider** [comment]
Just modified the PR #7913 to work with and the ESP Arduino suported SoCs.

**Comment by mrengineer7777** [comment]
@coskunyildirimcosel Fix was merged and will be available in next release.  Is it ok to close this issue?

**Comment by coskunyildirimcosel** [comment]
Ok thank you
