### ISSUE TITLE
sum with negative int

### ISSUE THREAD

**Issue by PM04290** [espressif/arduino-esp32#8016]
### Board

ESP32 Deckit

### Device Description

classic ESP32 Devkit 30pin

### Hardware Configuration

no hardware needed

### Version

v2.0.7

### IDE Name

Arduino IDE 1.8.19

### Operating System

Window 10

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

with int values :
A = 0;
B = -1
A += B return -1 (ok)
A = A + B return 0 (ko)

### Sketch

```cpp
start initialize
`int stationIndex = 0;
`

call function
`soundStart(-1);
`

function detail with 2 option : runnin well vs running with error

void soundStart(int skip = 0)
{
  if (skip != 0)
  {
    Serial.printf("index before %d\n", stationIndex);
    /* uncomment the line to test the version */
    /* good version 1 : return -1 */
    // stationIndex += skip;
    /* bad version 2 : 0    (lol) */
    // stationIndex = stationIndex + skip;
    Serial.printf("index after %d\n", stationIndex);
  }
}
```
```


### Debug Message

```plain
nop
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
I tested it and all works fine. In both cases I get `-1`
