### ISSUE TITLE
Missing/mismatched versions of gdb/openocd for x86_64 (xtensa)

### ISSUE THREAD

**Issue by tobozo** [espressif/arduino-esp32#8021]
### Board

esp32

### Device Description

observed on xtensa based esp32 flashed from a Linux x86_64 machine but may apply to other OS/devices

### Hardware Configuration

defaults

### Version

v2.0.7

### IDE Name

Arduino IDE (1.8.19)

### Operating System

Arch Linux x86_64

### Flash frequency

any

### PSRAM enabled

yes

### Upload speed

any

### Description

Getting `xtensa-esp32-elf-gdb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory` error when attempting to decode an exception.

According to [this comment](https://github.com/espressif/esp-idf/issues/6334#issuecomment-1427229813), esp32-arduino 2.0.7 should be bundled with a newer version of gdb tools. 

I managed to decode the exception after using the xtensa gdb binaries from [esp-gdb-v11.2_20220823](https://github.com/espressif/binutils-gdb/releases/tag/esp-gdb-v11.2_20220823).

### Sketch

```cpp
none
```

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
fixed in both `release/v2.x` and `esp-idf-v5.1-libs` branches. Will be in 2.0.8. ExceptionDecoder was also updated to support that new GDB
