### ISSUE TITLE
SD.cpp line 82 issues, totalBytes() return wrong size when using 16G Card, add '(uint64_t)' please.

### ISSUE THREAD

**Issue by tianye2003** [espressif/arduino-esp32#803]
uint64_t size = (fsinfo->csize)*(fsinfo->n_fatent - 2)

#if _MAX_SS != 512

        *(fsinfo->ssize);

#else

        *512;

#endif

**Comment by tianye2003** [comment]
uint64_t SDFS::totalBytes()
{
	FATFS* fsinfo;
	DWORD fre_clust;
	if (f_getfree("0:", &fre_clust, &fsinfo) != 0) return 0;
	uint64_t size = (uint64_t)(fsinfo->csize) * (uint64_t)(fsinfo->n_fatent - 2)
#if _MAX_SS != 512
		* (uint64_t)(fsinfo->ssize);
#else
		* 512;
#endif
	return size;
}

uint64_t SDFS::usedBytes()
{
	FATFS* fsinfo;
	DWORD fre_clust;
	if (f_getfree("0:", &fre_clust, &fsinfo) != 0) return 0;
	uint64_t size = (uint64_t)(fsinfo->csize) * ((uint64_t)(fsinfo->n_fatent - 2) - (uint64_t)(fsinfo->free_clst))
#if _MAX_SS != 512
		* (uint64_t)(fsinfo->ssize);
#else
		* 512;
#endif
	return size;
}

**Comment by me-no-dev** [comment]
please pull the latest master and retest

**Comment by jarda195** [comment]
I have 16GB SD Card..  this modification not working..  :(
