### ISSUE TITLE
Disable CCA(Carrise sense) using ESP-NOW ???

### ISSUE THREAD

**Issue by uecken** [espressif/arduino-esp32#8063]
### Board

ESP32-C3

### Device Description

Nothing.

### Hardware Configuration

Nothing

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Windows10

### Flash frequency

default

### PSRAM enabled

yes

### Upload speed

115200

### Description

Does anyone know disable the CCA(Carrise sense) using ESP-NOW?
I think below function means the carrier sense threshold.
esp_ieee802154_set_cca_threshold(int8_t cca_threshold);

Therefore,  esp_ieee802154_set_cca_threshold(-200) disable CCA?

https://github.com/espressif/arduino-esp32/blob/00214d5c2a1c2b1904f2caf6f0d5ddfe952331ff/tools/sdk/esp32c3/include/ieee802154/include/esp_ieee802154.h

### Sketch

```cpp
Nothing
```

### Debug Message

```plain
Nothing
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment]
No idea.  Try posting here: https://github.com/espressif/esp-now/issues
