### ISSUE TITLE
add documentation: what happens when an update gets aborted

### ISSUE THREAD

**Issue by ilka-schulz** [espressif/arduino-esp32#8101]
### Related area

Update.h

### Hardware specification

any ESP32 board

### Is your feature request related to a problem?

It is unclear from the documentation what happens when an OTA update is aborted. `Update.h` includes some documentation of the `end` method but nothing about the `abort` method and no mention of power failure during update, etc.

Will the ESP32 be able to continue running seamlessly? Or will the flash content be corrupted? How to recover if a new firmware has been written to flash only in half and the ESP32 does not work anymore?

### Describe the solution you'd like

documentation of the answers mentioned in the problem description

### Describe alternatives you've considered

I interrupted power supply during flashing and my ESP32 continued to work seemlessly with the old image. However, this test is probably not very useful because both firmwares were similar...

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment]
@mrengineer7777 will you do this or @lucasssvaz can take over this task?
