### ISSUE TITLE
2.0.8 release: ESP_ARDUINO_VERSION is still 2.0.6

### ISSUE THREAD

**Issue by tueddy** [espressif/arduino-esp32#8102]
### Board

ESP32 DEV module

### Device Description

--

### Hardware Configuration

no sopecific HW

### Version

v2.0.8

### IDE Name

PIO

### Operating System

Win11

### Flash frequency

40MHZ

### PSRAM enabled

yes

### Upload speed

115200

### Description

Hi Arduino team,

i want to use 

`ESP_ARDUINO_VERSION >= ESP_ARDUINO_VERSION_VAL(2, 0, 8)`

but this fails because `ESP_ARDUINO_VERSION_PATCH` is 6 not 8:

https://github.com/espressif/arduino-esp32/blob/237a3fe96c451e5da88e8cfe9d850961f9bbe036/cores/esp32/esp_arduino_version.h#L26

Any other idea to identify the release 2.0.8?

Thanks!

### Sketch

```cpp
-
```

### Debug Message

```plain
-
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
You are looking at the `master` branch, while 2.0.8 is in `release/v2.x` branch

https://github.com/espressif/arduino-esp32/blob/release/v2.x/cores/esp32/esp_arduino_version.h#L26
