### ISSUE TITLE
GDB executable not found - Arduino 2.10 fails to compile

### ISSUE THREAD

**Issue by frspp** [espressif/arduino-esp32#8121]
### Board

Nodemcu esp32

### Device Description

Oled display 
Dallas DS18B20 temperature sensor
TI CC1101 433mhz radio

### Hardware Configuration

-

### Version

2.0.8

### IDE Name

Arduino IDE 2.1

### Operating System

Windows 11

### Flash frequency

80

### PSRAM enabled

yes

### Upload speed

912600

### Description

GDB executable "C:\Users\CUT\AppData\Local\Arduino15\packages\esp32\tools\xtensa-esp-elf-gdb\11.2_20220823\bin\arm-none-eabi-gdb.exe" was not found. Please configure "cortex-debug.armToolchainPath" or "cortex-debug.gdbPath" correctly.

Did not get this error week or two ago with older Arduino IDE (2.0.5?) and older ESP board information.

### Sketch

```cpp
-
```

### Debug Message

```plain
GDB executable "C:\Users\vy14ju\AppData\Local\Arduino15\packages\esp32\tools\xtensa-esp-elf-gdb\11.2_20220823\bin\arm-none-eabi-gdb.exe" was not found. Please configure "cortex-debug.armToolchainPath" or "cortex-debug.gdbPath" correctly.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by frspp** [comment]
dunno it went away. Did I press "debug" button instead "compile"?

**Comment by me-no-dev** [comment]
> dunno it went away. Did I press "debug" button instead "compile"?

yes you did :)
