### ISSUE TITLE
Not returning value in function causes panic message

### ISSUE THREAD

**Issue by datphys** [espressif/arduino-esp32#8123]
### Board

Esp32 dev module

### Device Description

Cusom board

### Hardware Configuration

pin 27 control power key of modules sim

### Version

v2.0.8

### IDE Name

Arduino IDE 2.0

### Operating System

Windown 10

### Flash frequency

240 MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

Module reset frequenly

### Sketch

```cpp
//in sketch file
#include <LYNQ_L506.h>
const int pwrkey = 27;
l506_init(&Serial1, pwrkey);
l506_power_on_off();     // ----> reset here
// Replace with
digitalWrite(pwrkey, HIGH);
delay(2500);
digitalWrite(pwrkey, LOW); // ----> Working

# header file
#include <Arduino.h>
void l506_init(HardwareSerial *serial, int pin);
int8_t l506_power_on_off();

# cpp file
void l506_init(HardwareSerial *serial, int pin)
HardwareSerial *l506;
int PWRKEY;

{
    l506 = serial;
    PWRKEY = pin;
    pinMode(PWRKEY, OUTPUT);
    digitalWrite(PWRKEY, LOW);
}

int8_t l506_power_on_off()
{
    digitalWrite(PWRKEY, HIGH);
    delay(2500);
    digitalWrite(PWRKEY, LOW);
}
```

### Debug Message

```plain
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@datphys - 

This has nothig to do with `digitalWrite()`.
The issue is about declaring a function that shall return a value, but nothing is returned.

You can fix it by:
- making the function `l506_power_on_off()` void like: `void l506_power_on_off()`
- returning a value, for instance zero, at the end of the function `l506_power_on_off()`

**Comment by SuGlider** [comment]
You should see a warning message in the compilation output:

```
LYNQ_L506.cpp: In function 'int8_t l506_power_on_off()':
LYNQ_L506.cpp:18:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
```

**Comment by SuGlider** [comment]
You can enforce such warning as an error by setting `Compiler warnings:` option to `More` or `All`

![image](https://user-images.githubusercontent.com/65977697/234611034-e2013896-4fb9-4af3-9276-5a84d46cec0d.png)

**Comment by mrengineer7777** [comment]
Solution noted above
