### ISSUE TITLE
ESP32 Non Blocking Logging

### ISSUE THREAD

**Issue by meakashrao** [espressif/arduino-esp32#8124]
### Related area

ESP-Logging

### Hardware specification

ESP32 DevKit C

### Is your feature request related to a problem?

Mostly, I end up using Serial.print to log statements 
This ends up introducing delay's in the system

I want to run away from there

### Describe the solution you'd like

Some non Blocking Delay Function

### Describe alternatives you've considered

ESP_Log

but that also ends up using do while(0)

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by bertmelis** [comment]
`do {} while(0)` doesn't block.

your problem also isn't compatible with my problem: logging from multiple tasks: https://github.com/espressif/arduino-esp32/discussions/8064

**Comment by meakashrao** [comment]
Thank you
