### ISSUE TITLE
Enable RTOS trace to use SEGGER SystemView

### ISSUE THREAD

**Issue by alkonosst** [espressif/arduino-esp32#8155]
### Related area

FreeRTOS/Trace.

### Hardware specification

ESP32 in general.

### Is your feature request related to a problem?

We have a closed source product with an `ESP32-WROVER-IE 16MB` running with RTOS tasks, with WiFi, Ethernet, 4G, XBee, sensors, among others, and currently it´s running very stable for 2+ months. The ESP32 already has 7 tasks running, with priority and stack size determined by just iterating.

The issue is we need to keep adding stuff to it, like OTA, remote logs, webserver to configure, etc. At this moment, we just have logs with `log_x` to understand the behavior of the system.

### Describe the solution you'd like

We would like to better understand what happens at the RTOS level, and how all the tasks are running.

Seeing the behavior of the tasks with SEGGER SystemView would help a lot. It seems that ESP-IDF has it implemented: https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32/api-guides/app_trace.html#app-trace-system-behaviour-analysis-with-segger-systemview

Seems there is some people that also need to have a better understanding of RTOS tasks: #7179

### Describe alternatives you've considered

Using Arduino as a component, modifying sdkconfig, but no success at all.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
When using as component, there is nothing stopping you to enable app trace and follow the guide. Actually you need to follow this guide for Arduino with IDF v4.4.4: https://docs.espressif.com/projects/esp-idf/en/v4.4.4/esp32/api-guides/app_trace.html
