### ISSUE TITLE
[CI] merge_packages.py overwriting platform.txt::version value from build

### ISSUE THREAD

**Issue by tobozo** [espressif/arduino-esp32#8158]
### Description

According to the last commit on 2.0.9, the platform.txt should come with the following value:

![image](https://user-images.githubusercontent.com/1893754/236152560-ed5ad139-4a55-4df5-b8c0-a0f15756de16.png)

However it doesnt, the `version` value is empty.

Also according to Arduino standards, the `name` field should also contain the version number, here's an example with the pico boards:

```
name=Raspberry Pi RP2040 Boards(3.1.1)
version=3.1.1
```

### Other Steps to Reproduce

install the core from Arduino IDE Board Manager

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
@me-no-dev I think we can close this and it is not relevant anymore, right?

**Comment by me-no-dev** [comment]
right. long fixed
