### ISSUE TITLE
Bug in WebUpdater example.

### ISSUE THREAD

**Issue by ScriptNewbie** [espressif/arduino-esp32#8186]
### Board

N/A

### Device Description

N/A

### Hardware Configuration

N/A

### Version

latest master (checkout manually)

### IDE Name

N/A

### Operating System

N/A

### Flash frequency

N/A

### PSRAM enabled

yes

### Upload speed

N/A

### Description

There is bug in https://github.com/espressif/arduino-esp32/blob/master/libraries/HTTPUpdateServer/examples/WebUpdater/WebUpdater.ino

MDNS is initialised twice - first properly with "host" variable, but right after again.

MDNS.begin(host);
  if (MDNS.begin("esp32")) {
    Serial.println("mDNS responder started");
  }

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello @ScriptNewbie, thanks for the issue.

@PilnyTomas Can you please test and verify mentioned example? Thanks!
