### ISSUE TITLE
[lolin_s2_mini] Windows can't build project "ESPmDNS.cpp:42:10: fatal error: WiFi.h: No such file or directory"

### ISSUE THREAD

**Issue by Turbine1991** [espressif/arduino-esp32#8200]
### Board

lolin_s2_mini

### Device Description

N/A  The board is just attached to a custom shield, which controls two mosfet relays.

### Hardware Configuration

N/A Hardware is not the issue.

### Version

latest development Release Candidate (RC-X)

### IDE Name

PlatformIO

### Operating System

Windows 11

### Flash frequency

200Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

I'm trying to re-build a project which I last worked on perhaps 6-10 months ago on Windows. I've just tried to build my project again in Linux, and it works fine. Something is wrong for the Windows platform.

However, while I can reference WiFi.h in main no problem - The esp32 ESPmDNS.cpp file for whatever reason is unable to find the file.

I've tried going back to V2, but it doesn't solve my issue.

### Sketch

```cpp
As it's a project issue, I'll prove my entire project. The hardware isn't required to build the code.

Link:
https://tmpfiles.org/1413943/esp32-s2scooter.zip
```

### Debug Message

```plain
C:/Users/Administrator/.platformio/packages/framework-arduinoespressif32@src-e36c2260a49b9bf6768237494cebb35d/libraries/ESPmDNS/src/ESPmDNS.cpp:42:10: fatal error: WiFi.h: No such file or directory

**************************************************************
* Looking for WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFi.h"
* Web  > https://registry.platformio.org/search?q=header:WiFi.h
*
**************************************************************

 #include <WiFi.h>
          ^~~~~~~~
compilation terminated.
*** [.pio\build\lolin_s2_mini\libc09\ESPmDNS\ESPmDNS.cpp.o] Error 1
======================= [FAILED] Took 13.20 seconds =======================

Environment    Status    Duration
-------------  --------  ------------
lolin_s2_mini  FAILED    00:00:13.203
================== 1 failed, 0 succeeded in 00:00:13.203 ================== 

 *  The terminal process "C:\Users\Administrator\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'lolin_s2_mini'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```
```


### Other Steps to Reproduce

1) Open PlatformIO Tab
2) Select Project Task: lolin_s2_mini
3) Build

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mapaf2** [comment]
I just had a similar problem with WiFi.h (Multiple libraries were found for "WiFi.h") for a project that was working last week. I installed the library Arduino_ESP32_OTA found in the library manager of Arduino IDE and it solved the problem.

**Comment by SuGlider** [comment]
I just used Arduino IDE with Core 2.0.8 and 2.0.9 (latest) + mDNS examples from the Menu-->File-->Examples-->ESPmDNS folder.

The two available examples compiled and worked fine.

May it be related to a local Windows PlatformIO issue?

**Comment by mrengineer7777** [comment]
I recently fought with a platformIO project that was throwing errors not being able to find one of my normal library files. It seems the LDF breaks easily. It definitely gives up if headers refer to each other. Not sure what else causes it to fail. I ended up moving some of the failing code to a different library that could see the needed header and everything compiled again.
