### ISSUE TITLE
neopixelWrite incompatible with FastLED

### ISSUE THREAD

**Issue by Adrianotiger** [espressif/arduino-esp32#8212]
### Board

ESP32 S3 devkit

### Device Description

just the in built led

### Hardware Configuration

GPIO 14 on led strip, GPIO48 on internal led

### Version

latest master (checkout manually)

### IDE Name

IDE 2.1.0

### Operating System

Windows

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

When using the `neopixelWrite` function, `FastLED` doesn't work anymore.

### Sketch

```cpp
#include <FastLED.h>

const uint16_t STRIP_LEDS = 10;
CRGB _leds[STRIP_LEDS];

void setup() 
{
  Serial.begin(115200);
  neopixelWrite(RGB_BUILTIN, 10,0,0);

  FastLED.addLeds<WS2812B, 14, GRB>(_leds, STRIP_LEDS);

  Serial.println("HANGS?");
  FastLED.clear(true);

  Serial.println("READY!");

}

void loop() 
{
  // put your main code here, to run repeatedly:
}
```

### Debug Message

```plain
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
HANGS?
```
READY! is never wrote in the console.
```


### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@Adrianotiger - It seems that using I2S to drive the FastLED library works. I don't  have an LED Strip to test it, but you may want to give it a try. This is the modified sketch version I have used:

``` cpp
#define FASTLED_ESP32_I2S
#include <FastLED.h>

const uint16_t STRIP_LEDS = 10;
CRGB _leds[STRIP_LEDS];
#define RGB_BUILTIN 2

void setup() 
{
  Serial.begin(115200);
  neopixelWrite(RGB_BUILTIN, 10,0,0);

  FastLED.addLeds<WS2812B, 14, GRB>(_leds, STRIP_LEDS);

  Serial.println("HANGS?");
  FastLED.clear(true);

  Serial.println("READY!");

}

void loop() 
{
  Serial.println("Loop...");
  delay(1000);
  // put your main code here, to run repeatedly:
}
```

### Output:
```
HANGS?
READY!
Loop...
Loop...
Loop...
Loop...
```

**Comment by Adrianotiger** [comment]
@SuGlider Thank you for the help, time and the code!
`#define FASTLED_ESP32_I2S` is a solution.

`neopixelWrite` is a nice function and doesn't need any external library - it doesn't need any library at all :D So it is perfect to show a status on the ESP32.

I am testing 5 ledstrips with 3000 leds. It was nice to have another led just to show a status on startup without handle it over the "normal" code.

I don't know how the RMT driver works. Since `neopixelWrite` is just here to set a single led, it could also be set with a synchron function? Or is there a way to detect if another library is using the rmt?
Now (after your response), I know that there could be only 1 library using this rmt, but in future, if someone want to use the IR-library or FastLED-library or any other library with the rmt he will have the same problem.

**Comment by SuGlider** [comment]
Anyway, I'll think a way to make `neopixelWrite()` work in the standard Arduino way, meaning that it would use just GPIO bitbang to drive it. We may change/add it in order to make it more Arduino compatible with any other Arduino Library.

**Comment by SuGlider** [comment]
Update: Adafruit NeoPixel also uses RMT to drive LEDs with ESP32... It uses IDF.
In that case, maybe the best solution would be to use FastLED to control the status RGB LED and the 5 ledstrips.

**Comment by SuGlider** [comment]
@Adrianotiger - closing it. Feel free to reopen it, whenever necessary.
