### ISSUE TITLE
HWCDC::end() does not set tx_lock to NULL, causing crashes

### ISSUE THREAD

**Issue by TD-er** [espressif/arduino-esp32#8224]
### Board

ESP32-C3 / ESP32-S3

### Device Description

Any ESP32-C3 or -S3 using HWCDC

### Hardware Configuration

Any ESP32-C3 or -S3 board using HWCDC

### Version

v2.0.9

### IDE Name

PlatformIO

### Operating System

Windows 11

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

HWCDC::end() does not reset the semaphore.
So after a call to `end()` and a new call to `begin()` the `tx_lock` semaphore is invalid.
Thus trying to write something to that port again will cause a crash.

https://github.com/espressif/arduino-esp32/blob/3ec5f4efa1de4342aaab742008dc630091e5e035/cores/esp32/HWCDC.cpp#L190-L205

### Sketch

```cpp
-
```

### Debug Message

```plain
-
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
Thanks @TD-er - I'll check it and fix it.

**Comment by SuGlider** [comment]
Thanks again @TD-er - PR #8247 will fix it.
