### ISSUE TITLE
Cannot Capture image using ov7725 in esp32 

### ISSUE THREAD

**Issue by James-sjec** [espressif/arduino-esp32#823]
I am using WROOM-32 , below is the picture of the development board
![32568688-da8a6b72-c473-11e7-87cd-b0ae1e96edaf](https://user-images.githubusercontent.com/32930819/32648420-824da86a-c5aa-11e7-96fd-28a9dac008c3.jpg)

I enabled test pattern ,after which I got the following error
![32568756-0990810e-c474-11e7-9e38-fc1b0acc7e5e](https://user-images.githubusercontent.com/32930819/32648451-942ef8ae-c5aa-11e7-8f4a-3435be298f8c.jpg)

I am using following pin map
![32568763-11be0d60-c474-11e7-88ba-e97a968a1b3b](https://user-images.githubusercontent.com/32930819/32648453-95f11258-c5aa-11e7-8231-fbd7d675e25f.jpg)

**Comment by me-no-dev** [comment]
Why not post this into it's repository? :)

What I see above is that the queue that is used to acquire the image is emptied too slow and you are probably running out of memory. What are you capturing? Which camera?

**Comment by igrr** [comment]
Closing as the same was posted in esp32-cam-demo.
