### ISSUE TITLE
Can't switch between BLE4 and BLE5 scanning ESP32-C3

### ISSUE THREAD

**Issue by israelxss** [espressif/arduino-esp32#8242]
### Board

ESP32-C3

### Device Description

ESP32-C3 with an antenna

### Hardware Configuration

no

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Win10

### Flash frequency

80

### PSRAM enabled

yes

### Upload speed

115200

### Description

Trying to switch between scanning extended and regular scanning:

calling `ble_5()` after calling `ble_4()` :
raises: `BT_APPL: bta_dm_ble_set_scan_fil_params(), fail to set scan params.`

and in the other direction:
`(6603) BT_BTM: BTM_BleScan scan not active`

### Sketch

```cpp
void ble_4(){
  Serial.println("ble 4");
  bleScan = BLEDevice::getScan();
  bleScan->setAdvertisedDeviceCallbacks(new MyAdvertisedDeviceCallbacks());
  bleScan->setActiveScan(true);
  bleScan->start(scanTime);
  Serial.println("ble #");
  
}

void ble_5(){
  Serial.println("ble 5");
  bleScan = BLEDevice::getScan();
  bleScan->setExtendedScanCallback(new MyBLEExtAdvertisingCallbacks());
  bleScan->setExtScanParams();
  bleScan->startExtScan(scanTime, 3); 
}

void setup() {
  ble_5();
  ble_4();
  
  // or
  ble_4();
  ble_5();  
}
```
```


### Debug Message

```plain
calling `ble_5()` after calling `ble_4()` :
raises: `BT_APPL: bta_dm_ble_set_scan_fil_params(), fail to set scan params.`

and in the other direction:
`(6603) BT_BTM: BTM_BleScan scan not active`
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@israelxss - You need to `deinit()` the BLE device and then reinit for the next BLE scan with a different mode.

``` cpp
void setup() {
  ble_5();
  BLEDevice::deinit();
  BLEDevice::init("");
  ble_4();
  
  // or
  ble_4();
  BLEDevice::deinit();
  BLEDevice::init("");
  ble_5();  
}
```

**Comment by VojtechBartoska** [comment]
Closing as expired.

**Comment by mwaldoch** [comment]
But why is the deinit needed? I can't seem to find anything related in the documentation
