### ISSUE TITLE
ESP32 Devkit i2c slave begin error : sda gpio number error (IDFGH-10270)

### ISSUE THREAD

**Issue by PM04290** [espressif/arduino-esp32#8266]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Compile with ESP32 Dev Module on Arduino IDE

i'm using wireSlave.ino exemple and changing SDA/SCL pin by 2 and 4 in begin
`Wire.begin((uint8_t)I2C_DEV_ADDR, 2, 4);`

on running, there is this error : 
`E (10) i2c: i2c_set_pin(870): sda gpio number error`

i have the same error with all pins i have tryed.

**Comment by Alvin1Zhang** [comment]
Seems the issue is Arduino specific, moved to Arduino issue tracker.
