### ISSUE TITLE
Example for SD_MMC 1-bit mode?

### ISSUE THREAD

**Issue by Zhu-jiatong** [espressif/arduino-esp32#8269]
### Related area

SD Card (SDIO/SD_MMC)

### Hardware specification

Irrelevant

### Is your feature request related to a problem?

There is currently only example code for 4-bit SD_MMC library. It would be very helpful if a 1-bit mode example could be provided, since many ESP32 boards have pin conflicts when using 4-bit mode. 

### Describe the solution you'd like

A basic example sketch with example functions similar to that of the 4-bit mode example. Include specifications on pin connections as well.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by Zhu-jiatong** [comment]
Thanks. But what about the pin connections between the SD card module and the ESP32 board?
________________________________

**Comment by me-no-dev** [comment]
```cpp
#define SDMMC_SLOT1_IOMUX_PIN_NUM_CLK  14
#define SDMMC_SLOT1_IOMUX_PIN_NUM_CMD  15
#define SDMMC_SLOT1_IOMUX_PIN_NUM_D0   2
// Below only used in 4 bit mode
#define SDMMC_SLOT1_IOMUX_PIN_NUM_D1   4
#define SDMMC_SLOT1_IOMUX_PIN_NUM_D2   12
#define SDMMC_SLOT1_IOMUX_PIN_NUM_D3   13
```

**Comment by Zhu-jiatong** [comment]
What about the physical connections? Are any resistors required?
________________________________

**Comment by VojtechBartoska** [comment]
Ptal @PilnyTomas

**Comment by VojtechBartoska** [comment]
Closing this as expired, if needed you can reopen.

**Comment by zhaoker** [comment]
> ### Related area
> SD Card (SDIO/SD_MMC)
> 
> ### Hardware specification
> Irrelevant
> 
> ### Is your feature request related to a problem?
> There is currently only example code for 4-bit SD_MMC library. It would be very helpful if a 1-bit mode example could be provided, since many ESP32 boards have pin conflicts when using 4-bit mode.
> 
> ### Describe the solution you'd like
> A basic example sketch with example functions similar to that of the 4-bit mode example. Include specifications on pin connections as well.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### I have checked existing list of Feature requests and the Contribution Guide
> * [x]  I confirm I have checked existing list of Feature requests and Contribution Guide.

------I found a good way to do this :

#include <SD_MMC.h> // Include the SD_MMC library

// Pin configuration for SDMMC  Data pin (1-bit mode)

// #define SD_CL  39
// #define SD_CMD  38
// #define SD_D0   40


void listDir(fs::FS &fs, const char * dirname, uint8_t levels) {
  Serial.printf("Listing directory: %s\n", dirname);

  File root = fs.open(dirname);
  if (!root) {
    Serial.println("Failed to open directory");
    return;
  }
  if (!root.isDirectory()) {
    Serial.println("Not a directory");
    return;
  }

  File file = root.openNextFile();
  while (file) {
    if (file.isDirectory()) {
      Serial.print("  DIR : ");
      Serial.println(file.name());
      if (levels) {
        listDir(fs, file.name(), levels - 1);
      }
    } else {
      Serial.print("  FILE: ");
      Serial.print(file.name());
      Serial.print("  SIZE: ");
      Serial.println(file.size());
    }
    file = root.openNextFile();
  }
}

void setup() {
  Serial.begin(115200);
  if(!SD_MMC.setPins(SD_CL, SD_CMD, SD_D0))///SD_CL ,SD_CMD , SD_D0
    {
      Serial.println("Set pin failed!");
    }
  // Initialize SD card with SDMMC
  if (!SD_MMC.begin("/sdcard", true)) {
    Serial.println("SD Card Mount Failed");
    return;
  }

  uint8_t cardType = SD_MMC.cardType();
  if (cardType == CARD_NONE) {
    Serial.println("No SD card attached");
    return;
  }

  Serial.println("SD Card initialized.");

  // List files in the root directory
  listDir(SD_MMC, "/", 0);
}

void loop() {
  // Do nothing, listing happens in setup
}
this is ESP32S3-eye board.....  the important thing is code : "SD_MMC.setPins"
