### ISSUE TITLE
Does GPIO2 on the ESP32-WROOM-DA work differently from the ESP32-WROOM-32?

### ISSUE THREAD

**Issue by rtek1000** [espressif/arduino-esp32#8280]
### Board

ESP32-WROOM-DA

### Device Description

ESP32-WROOM-DA/ESP32-WROOM-32

### Hardware Configuration

GPIO2 -> LED

### Version

v2.0.8

### IDE Name

Arduino IDE 1.8.19

### Operating System

Lunux - Ubuntu 22.04.2 LTS

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

When testing the[ Advanced.ino](https://github.com/tzapu/WiFiManager/blob/master/examples/Advanced/Advanced.ino) code from the WiFiManager library, selecting the ESP32-WROOM-DA board in the IDE, and uploading the ESP32-WROOM-32 module, the GPIO2 pin flashes without being declared in the code.

Is this normal, or is it a bug?

If it's a bug, is the bug in the core, or in the library?

> Espressif new ESP32-WROOM-DA is pin-to-pin compatible with [ESP32-WROOM-32E](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf). Due to this pin compatibility, users of old ESP32-WROOM-32 modules will find it quick and easy to change to a new module. Apart from Espressif claims, ESP32-WROOM-32E has exact pin compatibility as widely used ESP32-WROOM- 32D. Therefore the new module should be pin-compatible with all those boards based on ESP32-WROOM-32D also.

Ref.: https://www.techtonions.com/esp32-wroom-da/

> you are using the wrong board defs for this board, thats the problem

Ref.: https://github.com/tzapu/WiFiManager/issues/1618

### Sketch

```cpp
[ Advanced.ino](https://github.com/tzapu/WiFiManager/blob/master/examples/Advanced/Advanced.ino)
```

### Debug Message

```plain
No error messages (only GPIO2 pin toggling)
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by atanisoft** [comment]
The ESP32-WROOM-DA module uses GPIO 2 and GPIO 25 to select which antenna is active. These are referenced from the datasheet for the module in table 3 (just after the pin assignment list). Make sure you are selecting "ESP32-WROOM-DA Module" in the boards menu which has additional defines added to enable dual antenna mode support.
