### ISSUE TITLE
macos compilation error ""python": executable file not found in $PATH"

### ISSUE THREAD

**Issue by frspp** [espressif/arduino-esp32#8287]
### Board

Nodemcu32

### Device Description

Nodemcu32

### Hardware Configuration

Yes, but not related.

### Version

Latest master, 1.0.6

### IDE Name

Arduino IDE 2.1

### Operating System

macos 13.3.1

### Flash frequency

80

### PSRAM enabled

yes

### Upload speed

115200

### Description

See https://forum.arduino.cc/t/mac-os-update-killed-esp32-sketch/969580/8

### Sketch

```cpp
Any sketch.
```

### Debug Message

```plain
/Users/USERNAME/Library/Arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/esp32-hal-spi.c: In function 'spiTransferBytesNL':
/Users/USERNAME/Library/Arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
                                       ^
/Users/USERNAME/Library/Arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/esp32-hal-spi.c:923:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_data8 = &last_data;
                                        ^

exec: "python": executable file not found in $PATH
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
You are not running the latest master. You are running 1.0.6 :) uninstall from Board Manager, switch the git branch to `release/v2.x`, run `get.py` again and should be OK.
