### ISSUE TITLE
Can't read analog data properly on ESP32 Wroom 32 u using circuitpython

### ISSUE THREAD

**Issue by sanroeeee** [espressif/arduino-esp32#8288]
### Board

ESP32-Wroom-32u

### Device Description

Hi! I am using ULPSM sensors from Digikey to measure SO2 concentration with the ESP32 on circuitpython. With the formula on the datasheet, I made the following code:

import time
import board
from analogio import AnalogIn

GasIn = AnalogIn(board.D34)
TempIn = AnalogIn(board.D35)

Vref=1.65
while True:
    time.sleep(2)
    Vgas=(GasIn.value/4096)*3.3
    Vtemp=(TempIn.value/4096)*3.3
    M=32.27
    T=29.0*Vtemp-18.0
    if T<20:
        Mc=M*((1.3*T)+74)
    else:
        Mc=M*((0.4*T)+92)
    Cx=(1/Mc)*(Vgas-Vref)
    print(Cx*1000, "ppb")

### Hardware Configuration

GPIOD34 to Vgas
GPIO35 to Vtemp
3.3V connected to V+
GND TO GND
VOLTAGE DIVIDER to Vref

### Version

latest master (checkout manually)

### IDE Name

ThonnyIDE

### Operating System

windows 11

### Flash frequency

9600?

### PSRAM enabled

yes

### Upload speed

9600?

### Description

The problem here is that the output is kinda constant (16-20ppm which is big) no matter what I do with the sensor. Vgas and Vtemp also exceeds the reference voltage of 3.3V which I set on my circuit. I was told that to initialize the analog connection The "D" on D34 should be replaced with "A" however, upon running dir(board), it outputs this:

<img width="1270" alt="image" src="https://github.com/espressif/arduino-esp32/assets/109780301/af8ddfac-5625-4ff4-94fd-2fde24281afc">

as you can see there are only digital pins (D) and no "A" pins so im quite confused as according to internet, all esp32 have analog pins.

I hope some would be able to help me. Thanks in advance. 

### Sketch

```cpp
none
```

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment]
This repo is only Arduino.
