### ISSUE TITLE
Example code for Wi-Fi and BLE Coexistence in ESP-S3 Module

### ISSUE THREAD

**Issue by Saheb199614** [espressif/arduino-esp32#8293]
### Related area

Wi-Fi and BLE Co-existence

### Hardware specification

ESp32-S3

### Is your feature request related to a problem?

I am facing trouble finding example code for Wi-Fi and BLE Co-existence code for ESP32-S3

### Describe the solution you'd like

We want the ESP-S3 module to connect to Bluetooth initially. After connecting we will get the MAC Address through BLE. After that we want to configure Wi-Fi to connect to Firebase.

### Describe alternatives you've considered

Wi-Fi and BLE work simultaneously on ESP-S3 Module

### Additional context

We are developing an app to interface with ESP32-S3 to transmit data wirelessly. Our Requirements are as follows.

- On the app there will be button "SCAN" through that it can scan the Bluetooth and connect to respective ESP32-S3 Module
- After the module is connected through Bluetooth, it will show a button that Configure Wi-Fi.
- Once clicked to it, it will open a web page to configure Wi-Fi through SSID and Password.
- Once set with the Wi-Fi, it will connect to the firebase and start send & receive data between ESP32 S3 module and APP.

Here, we are trying to configure ESP32-S3 in a way that it will initially use the antenna as Bluetooth and later while configuring Wi-Fi, it will disable Bluetooth and Enable Wi-Fi. As I got from multiple sources that it is also possible to use two of them together also but with data packaging. But I couldn't able to get any source code for that. Can you help us to configure this in a way that we can use the Bluetooth to get the MAC and to use the Wi-Fi to connect to Firebase.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by lbernstone** [comment]
This site is for issues with the code in the repo.  Use https://esp32.com to ask for someone to write code for your project.

**Comment by VojtechBartoska** [comment]
Closing
