### ISSUE TITLE
TCP  keepalive 

### ISSUE THREAD

**Issue by davidbcf** [espressif/arduino-esp32#8296]
### Board

ESP32-C3-S2

### Device Description

ESP32-C3-S2

### Hardware Configuration

no

### Version

v2.0.6

### IDE Name

Arduino IDE

### Operating System

win 10

### Flash frequency

80

### PSRAM enabled

yes

### Upload speed

961200

### Description

when i had set tcp keepalive parameters.After connection,client send nothing to server ,and i manually shut down the server's wifi connection. it seems i cant get any useful info to adjust that TCP connection is broken. 
for example :  client.connected()  still true,;
                       client.available();     return 0; not -1 as error code  for example.

so  how can i adjust  the tcp connection is brkoen ?with  which API?

### Sketch

```cpp
if (client.connect(m_ip.c_str(), (const uint16_t)atoi((const char *)m_port.c_str()))) //尝试访问目标地址
              {
                  Serial.println("Connected server success");     
                  int keepAlive=1;
                  int  keepIdle =5;
                  int  keepInterval =5;
                  int  keepCount=1;
                  if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPALIVE,(void*)&keepAlive,sizeof(keepAlive)))
                      Serial.println("TCP_KEEPALIVE failed");
                  if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPIDLE,(void*)&keepIdle,sizeof(keepIdle)))
                      Serial.println("TCP_KEEPIDLE failed");
                  if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPINTVL,(void*)&keepInterval,sizeof(keepInterval)))
                      Serial.println("TCP_KEEPINTVL failed");
                  if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPCNT,(void*)&keepCount,sizeof(keepCount)))
                      Serial.println("TCP_KEEPCNT failed");
              }
```

### Debug Message

```plain
Connected server success
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
Please try this:

``` cpp
if (client.connect(m_ip.c_str(), (const uint16_t)atoi((const char *)m_port.c_str()))) //尝试访问目标地址
              {
                  Serial.println("Connected server success");     
                  int keepAlive=1000;  // Milliseconds
                  int  keepIdle =5;
                  int  keepInterval =5;
                  int  keepCount=1;
                  if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPALIVE,(void*)&keepAlive,sizeof(keepAlive)))
                      Serial.println("TCP_KEEPALIVE failed");
                  if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPIDLE,(void*)&keepIdle,sizeof(keepIdle)))
                      Serial.println("TCP_KEEPIDLE failed");
                  if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPINTVL,(void*)&keepInterval,sizeof(keepInterval)))
                      Serial.println("TCP_KEEPINTVL failed");
                  if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPCNT,(void*)&keepCount,sizeof(keepCount)))
                      Serial.println("TCP_KEEPCNT failed");
              }
```

**Comment by SuGlider** [comment]
@davidbcf  - A way to know when the client gets disconnected is by using events and callbacks:

 ``` cpp
 void WiFiStationDisconnected(WiFiEvent_t event, WiFiEventInfo_t info){
  Serial.println("Disconnected from WiFi access point");
  Serial.print("WiFi lost connection. Reason: ");
  Serial.println(info.wifi_sta_disconnected.reason);
  Serial.println("Trying to Reconnect");
  WiFi.begin(ssid, password);
}
void setup(){
  Serial.begin(115200);

  // delete old config
  WiFi.disconnect(true);

  delay(1000);

  WiFi.onEvent(WiFiStationDisconnected, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);
  WiFi.begin(ssid, password);
}
 ```
 
```cpp

// single code line for setup(), using lambda function
 WiFi.onEvent([](WiFiEvent_t event, WiFiEventInfo_t info){
        Serial.print("WiFi lost connection. Reason: ");
        Serial.println(info.wifi_sta_disconnected.reason);
    }, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);

```

**Comment by davidbcf** [comment]
> 

it still didnt work....

> Please try this:
> 
> ```c++
> if (client.connect(m_ip.c_str(), (const uint16_t)atoi((const char *)m_port.c_str()))) //尝试访问目标地址
>               {
>                   Serial.println("Connected server success");     
>                   int keepAlive=1000;  // Milliseconds
>                   int  keepIdle =5;
>                   int  keepInterval =5;
>                   int  keepCount=1;
>                   if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPALIVE,(void*)&keepAlive,sizeof(keepAlive)))
>                       Serial.println("TCP_KEEPALIVE failed");
>                   if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPIDLE,(void*)&keepIdle,sizeof(keepIdle)))
>                       Serial.println("TCP_KEEPIDLE failed");
>                   if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPINTVL,(void*)&keepInterval,sizeof(keepInterval)))
>                       Serial.println("TCP_KEEPINTVL failed");
>                   if(client.setSocketOption(IPPROTO_TCP,TCP_KEEPCNT,(void*)&keepCount,sizeof(keepCount)))
>                       Serial.println("TCP_KEEPCNT failed");
>               }
> ```

**Comment by davidbcf** [comment]
> 



> @davidbcf -
> 
> ~The ESP32 is set as STA or AP?~ ~If you remove the `setSocketOption()`, does it work?~
> 
> I see that your question is how to know that the connection is broken or not, right?

yes, but it is tcp client disconnect with tcp server  ,not  wifi sta disconnect with wifi AP

**Comment by davidbcf** [comment]
> client

it seems talk about the wifi connection, however what i need is how to adjust the TCP connection .
i sot wifi sta mode, and connected tcp server success, when i turn off the server's network , the module cant hnow the connection to tcp server is broken.so i want use tcp keepalive mechanism to hnow that tcp server is disconnected. During the whole process, the client and server do not actively send messages to each other to makesure keeepalive mechanism  work.

**Comment by davidbcf** [comment]
> @davidbcf - A way to know when the client gets disconnected is by using events and callbacks:
> 
> ```c++
> void WiFiStationDisconnected(WiFiEvent_t event, WiFiEventInfo_t info){
>  Serial.println("Disconnected from WiFi access point");
>  Serial.print("WiFi lost connection. Reason: ");
>  Serial.println(info.wifi_sta_disconnected.reason);
>  Serial.println("Trying to Reconnect");
>  WiFi.begin(ssid, password);
> }
> void setup(){
>  Serial.begin(115200);
> 
>  // delete old config
>  WiFi.disconnect(true);
> 
>  delay(1000);
> 
>  WiFi.onEvent(WiFiStationDisconnected, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);
>  WiFi.begin(ssid, password);
> }
> ```
> 
> ```c++
> // single code line for setup(), using lambda function
>  WiFi.onEvent([](WiFiEvent_t event, WiFiEventInfo_t info){
>         Serial.print("WiFi lost connection. Reason: ");
>         Serial.println(info.wifi_sta_disconnected.reason);
>     }, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);
> ```

it seems talk about the wifi connection, however what i need is how to adjust the TCP connection .
i sot wifi sta mode, and connected tcp server success, when i turn off the server's network , the module cant hnow the connection to tcp server is broken.so i want use tcp keepalive mechanism to hnow that tcp server is disconnected. During the whole process, the client and server do not actively send messages to each other to makesure keeepalive mechanism work.

**Comment by davidbcf** [comment]
it seems talk about the wifi connection, however what i need is how to adjust the TCP connection .
i set wifi sta mode, it connected wifi AP and  tcp server success, when i turn off the server's network , i cant know the connection to tcp server is broken.so i want use tcp keepalive mechanism to know that tcp server is disconnected. During the whole process, the client and server do not actively send messages to each other to makesure keeepalive mechanism work.


> @davidbcf - A way to know when the client gets disconnected is by using events and callbacks:
> 
> ```c++
> void WiFiStationDisconnected(WiFiEvent_t event, WiFiEventInfo_t info){
>  Serial.println("Disconnected from WiFi access point");
>  Serial.print("WiFi lost connection. Reason: ");
>  Serial.println(info.wifi_sta_disconnected.reason);
>  Serial.println("Trying to Reconnect");
>  WiFi.begin(ssid, password);
> }
> void setup(){
>  Serial.begin(115200);
> 
>  // delete old config
>  WiFi.disconnect(true);
> 
>  delay(1000);
> 
>  WiFi.onEvent(WiFiStationDisconnected, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);
>  WiFi.begin(ssid, password);
> }
> ```
> 
> ```c++
> // single code line for setup(), using lambda function
>  WiFi.onEvent([](WiFiEvent_t event, WiFiEventInfo_t info){
>         Serial.print("WiFi lost connection. Reason: ");
>         Serial.println(info.wifi_sta_disconnected.reason);
>     }, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);
> ```

**Comment by davidbcf** [comment]
I solved this problem ,should add code below 

if(client.setSocketOption(SOL_SOCKET,SO_KEEPALIVE,(void*)&keepCount,sizeof(keepCount)))
                      Serial.println("TCP_KEEPALIVE failed");
