### ISSUE TITLE
ESP32-WROOM-32E Freezes 

### ISSUE THREAD

**Issue by mounishseetha** [espressif/arduino-esp32#8315]
### Board

ESP-32-WROOM-32E

### Device Description

ESP32-WROOM32E is attached to a Battery Management System IC (Analog Front END ) via I2c

### Hardware Configuration

18&19 are connected to i2c

Bluetooth Classic is Continuously Turned on

Soft restart is implemented for every 24 Hours

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE 1.8.13

### Operating System

Windows 11

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

ESP32 is connected to AFE IC vis i2c, but after some days/ some time/ hours/Days, esp32 completely freezes.
I have implemented Watchdog i.e, if the loop doesn't run it should restart within 10 seconds and
24-hour soft restart irrespective of anything nothing works but if we hard reset is done it is working well again

### Sketch

```cpp

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
```

### Debug Message

```plain
some times junk is being printed in serial monitor but below is message when hard reset

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13104
load:0x40080400,len:3036
entry 0x400805e4
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
There is not enough information in order to help this issue.

**Comment by VojtechBartoska** [comment]
Closing as expired, if needed you can reopen.

**Comment by HamzaYslmn** [comment]
Same issue here
