### ISSUE TITLE
memory: No such file or directory

### ISSUE THREAD

**Issue by SSHUSSAIN-86** [espressif/arduino-esp32#8323]
### Board

esp32-c3-devkitc-02

### Device Description

I am using PlatformIO to build my project and I am using "SPIFFS.h" that has dependency on "memory". Please help resolve!
/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/FS.h:24:10: fatal error: memory: No such file or directory

### Hardware Configuration

No just build errors and dependency errors!

### Version

latest development Release Candidate (RC-X)

### IDE Name

PlatformIO

### Operating System

Windows 10

### Flash frequency

60 MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

Build errors

### Sketch

```cpp
#include <freertos/task.h>
#include <sdkconfig.h>
#include <ArduinoJson.h>
#include <esp_system.h>
#include <Arduino.h>
#include <SPIFFS.h>
#include <FS.h>
```

### Debug Message

```plain
cannot open source file "memory" (dependency of "SPIFFS.h"). Please run the 'Select IntelliSense Configuration...' command to locate your system headers.C/C++(1696)
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
You do not need to put SPIFFS.h in your platformio.ini.  It is part of the core.

**Comment by SSHUSSAIN-86** [comment]
I have removed SPIFFS.h from the platform.ini. Please see the attached file. If SPIFFS is part of the core then why it is not being recognized?
![error](https://github.com/espressif/arduino-esp32/assets/74684205/b0903513-129d-476c-bee5-9d656a92f074)

**Comment by lbernstone** [comment]
Arduino runs in c++.  Name your root file main.cpp

**Comment by SSHUSSAIN-86** [comment]
I like to run in espidf framework with "FS.h" and  "SPIFFS.h". I have changed to main.cpp with app_main() as my entry point

framework = espidf

![error2](https://github.com/espressif/arduino-esp32/assets/74684205/e90efdc8-1d67-43d0-a653-a29a03605a1b)

**Comment by Jason2866** [comment]
espidf is a different framework than Arduino. So this will not work.

**Comment by SSHUSSAIN-86** [comment]
I know we can use esp-idf framework and use arduino as a component. This works. I am now interested in setting up PlatformIO to do that. Please see the following official link to the documentation.

https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/esp-idf_component.html

**Comment by Jason2866** [comment]
@SSHUSSAIN-86 Here is an [example (LittleFS)](https://github.com/Jason2866/Arduino_IDF_LittleFS) when Arduino is used as component with IDF.

**Comment by SSHUSSAIN-86** [comment]
@Jason2866 Thanks. This really helps 🥇

**Comment by lbernstone** [comment]
As shown in all these [examples](https://github.com/platformio/platform-espressif32/blob/develop/examples/espidf-arduino-blink/platformio.ini#L12), the framework should be `framework = arduino. espidf`

**Comment by VojtechBartoska** [comment]
I'm closing this as covered, if you need more help, don't hesitate to reopen this.
