### ISSUE TITLE
DNS Server ?

### ISSUE THREAD

**Issue by timpur** [espressif/arduino-esp32#833]
Any plans to port the DNS Server?

**Comment by beegee-tokyo** [comment]
I am using [DNSServer---esp32](https://github.com/zhouhan0126/DNSServer---esp32) until DNSServer is ported officially from ESP8266.

**Comment by me-no-dev** [comment]
it's on my computer but I am on the road. NBNS and DNS are coming this/next week.

**Comment by timpur** [comment]
Awesome :)

**Comment by timpur** [comment]
@me-no-dev any updates?

**Comment by timpur** [comment]
@me-no-dev

**Comment by Testato** [comment]
Now it is integrated, this issue can be closed ?
