### ISSUE TITLE
ESP Logging

### ISSUE THREAD

**Issue by meakash** [espressif/arduino-esp32#8331]
### Related area

ESP Logging 

### Hardware specification

ESP32 Wroom DevKit

### Is your feature request related to a problem?

How does ESP Logging work? Is it non-blocking, if not, is there any non Blocking Logging?

### Describe the solution you'd like

I'd like to have a non blocking delay

### Describe alternatives you've considered

I tried ESP Logging but I feel based on my results they end up introducing delay's in the system

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by mrengineer7777** [comment]
I believe logging to Serial happens on a separate thread, so it consumes CPU cycles but doesn't completely delay your program.  Printing debug statements will always slow down program execution.  Printing simultaneous messages from different threads can cause delays and also mix together the messages, making them difficult to read.  Lesson: log sparingly.

**Comment by lbernstone** [comment]
Answered on esp32.com, since this has nothing to do with the content here.

**Comment by meakashrao** [comment]
Thank you
