### ISSUE TITLE
ESP32-D0WD-V3 not starting, old ESP32-D0WDQ6 works.

### ISSUE THREAD

**Issue by auto-scripting** [espressif/arduino-esp32#8349]
### Board

NodeMCU-ESP32 DEVKITV1

### Device Description

DEVKITV1

### Hardware Configuration

Nothing connected only Endoscope to check if the blinkpin is changing.

### Version

latest master (checkout manually)

### IDE Name

VSCode with Arduino Framework

### Operating System

Windows

### Flash frequency

Crystal is 40MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

The old devkit with ESP32-D0WDQ6 (revision v1.0) can be flashed and software (blink application) works fine. The new bought devkit (tryed out 5 pieces) with ESP32-D0WD-V3 (revision v3.0) can be successfully flashed, but the software do not start (no serial output, the test output pin do not change state LOW->HIGH->LOW->...) in loop. The same software was flashed to both devices.  

### Sketch

```cpp
#include <Arduino.h>
int BLINKPIN = 15;
int READPIN = 12;

void setup() {
  Serial.begin(9600);
  Serial.println("Test");
  pinMode (BLINKPIN, OUTPUT);
  pinMode (READPIN, INPUT_PULLDOWN);
}

long printlast = 0;
long last = 0;
long waittime = 5000;
long printwaittime = 25;
int pinstate = LOW;

void loop() {
  long now = millis();
  long diff = now - last;
  long printdiff = now - printlast;

  if (diff > waittime) {
    last = now;
    pinstate = pinstate == LOW ? HIGH : LOW;
    digitalWrite(BLINKPIN, pinstate);
  }

  if (printdiff > printwaittime) {
    printlast = now;
    int pinvalue = digitalRead(READPIN);
    printf("pinvalue:%d\n", pinvalue);
  }
}
```

### Debug Message

```plain
Unfortunatelly even debug messages are not showed on not working device.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
`Serial.begin(9600);` - shouldn't it be 115200?
