### ISSUE TITLE
Some options in tools available in one IDE and is not available in other

### ISSUE THREAD

**Issue by meakashrao** [espressif/arduino-esp32#8364]
### Board

ESP32 Dev Module

### Device Description

ESP32 Dev Module

### Hardware Configuration

The one IDE which works for me (for OTA using esptool.py), when I go into the Boards Manager, it shows that I need to install the 1.0.6 of Arduino ESP or others from the Boards Manager

In preferences the OLD IDE has https://dl.espressif.com/dl/package_esp32_index.json and works without board manager and the new IDE installed today requires Boards Manager

### Version

other

### IDE Name

Arduino IDE

### Operating System

Windows 11

### Flash frequency

40Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

I downloaded Arduino IDE from the Windows store on 29th June 2023 (Arduino 1.8.19 -> Windows Store 1.8.57.0), which doesn't have the some options in the Tools menu options from the same version downloaded via the Windows Store some time ago

Image 1: Arduino IDE downloaded today:
![image](https://github.com/espressif/arduino-esp32/assets/120377875/bfae2004-8d60-4197-9f0b-2a977ac527a8)

Image 2: Arduino IDE downloaded sometime ago
![image](https://github.com/espressif/arduino-esp32/assets/120377875/fa9fedbf-0dff-43a8-abaf-b7bf876004b6)

Also, previously downloaded Arduino IDE as mentioned above just required the preferences (https://dl.espressif.com/dl/package_esp32_index.json) and didn't require Boards manager Package to be downloaded while the newly downloaded IDE requires the Boards Manager and doesn't gives these two options

### Sketch

```cpp
Not Required
```

### Debug Message

```plain
Not Required
```

### Other Steps to Reproduce

Not Required

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
This is the wrong JSON link :) this old one has up to 1.0.6

try: https://espressif.github.io/arduino-esp32/package_esp32_index.json
