### ISSUE TITLE
ipv6 crash

### ISSUE THREAD

**Issue by espuser** [espressif/arduino-esp32#84]
esp idf and arduino-esp32 crashes with ipv6 enabled routers. This was fixed in esp-idf issue #148 by rojer (uninitialized structure in lwip) could you please fix this in tcpip_adapter/tcpip_adapter_lwip.c

if (esp_netif[tcpip_if] == NULL) {
 -        esp_netif[tcpip_if] = malloc(sizeof(struct netif));
 +        esp_netif[tcpip_if] = calloc(1, sizeof(*esp_netif[tcpip_if]));
          if (esp_netif[tcpip_if] == NULL) {
              return ESP_ERR_NO_MEM;
          }

BR

**Comment by me-no-dev** [comment]
I'm always building against updated esp-idf, so in just a few minutes, that update will be up

**Comment by me-no-dev** [comment]
done :)
