### ISSUE TITLE
can't use espnow and ble together

### ISSUE THREAD

**Issue by xBLACKICEx** [espressif/arduino-esp32#8405]
### Board

esp32 dev module

### Device Description

went use espnow and BLE together

### Hardware Configuration

 no

### Version

latest master (checkout manually)

### IDE Name

arduino ide

### Operating System

win10

### Flash frequency

80Mnz

### PSRAM enabled

yes

### Upload speed

921600

### Description

can't use espnow and ble together

### Sketch

using ble_notify exemble in arduino_IDE then i add esp_now_init()``

### Debug Message

```plain
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40164bd8  PS      : 0x00060330  A0      : 0x800d13d7  A1      : 0x3ffc7b00  
A2      : 0x00000000  A3      : 0x3ffbfddc  A4      : 0x3ffc4cec  A5      : 0x00000003  
A6      : 0x00000003  A7      : 0x00000000  A8      : 0x800d3eb1  A9      : 0x3ffc7ad0  
A10     : 0x00000000  A11     : 0x3ffbed7c  A12     : 0x18152907  A13     : 0x00000003  
A14     : 0x00000001  A15     : 0x00000000  SAR     : 0x00000018  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x0000003c  LBEG    : 0x40091c00  LEND    : 0x40091c1c  LCOUNT  : 0xffffffff  

ELF file SHA256: 0000000000000000

Backtrace: 0x40164bd8:0x3ffc7b00 0x400d13d4:0x3ffc7b20 0x400d7bca:0x3ffc7b70 0x4009418a:0x3ffc7b90
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@xBLACKICEx - The RF Coexistance documentation may help to check if your application is feasible.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/coexist.html

`LoadProhibited` error is usually related to trying to read data from a NULL pointer.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/fatal-errors.html

There are very few pieces of information about how the code has produced such issue.

**Comment by VojtechBartoska** [comment]
Closing as answered.
