### ISSUE TITLE
camera PIXFORMAT_JPEG

### ISSUE THREAD

**Issue by hzhh110** [espressif/arduino-esp32#8439]
### Related area

ESP32-S3-EYE

### Hardware specification

camera PIXFORMAT_JPEG

### Is your feature request related to a problem?

ESP32-S3-EYE for PIXFORMAT_JPEG
pCodec = avcodec_find_decoder(AV_CODEC_ID_MJPEG);

### Describe the solution you'd like

ESP32-S3-EYE for PIXFORMAT_JPEG
pCodec = avcodec_find_decoder(AV_CODEC_ID_MJPEG);

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
JPEG Encode: https://github.com/bitbank2/JPEGENC
JPEG Decoder: https://github.com/bitbank2/JPEGDEC

**Comment by me-no-dev** [comment]
encoder and decoder are already bundled. Just check the CameraWebServer example. It does it al.

**Comment by hzhh110** [comment]
PIXFORMAT_RGB565    than frame2jpg  Then use ffmpeg to parse out the standard YUV420, and directly use PIXFORMAT_JPEG and ffmpeg to parse out not the standard YUV420 may be YUV422 format

**Comment by me-no-dev** [comment]
Sorry but I do not understand what you mean.

**Comment by SuGlider** [comment]
> PIXFORMAT_RGB565    than frame2jpg  Then use ffmpeg to parse out the standard YUV420, and directly use PIXFORMAT_JPEG and ffmpeg to parse out not the standard YUV420 may be YUV422 format

This seems to be a (Linux) ffmpeg usage case.
You want ESP32 source code example that executes such sequence?

**Comment by hzhh110** [comment]
![image](https://github.com/espressif/arduino-esp32/assets/19906209/f590d575-a2d1-49be-8b33-4a62bd74abc6)
![WechatIMG1](https://github.com/espressif/arduino-esp32/assets/19906209/6e82c651-6a24-4e7d-8a94-d86acc93b976)
![WechatIMG2](https://github.com/espressif/arduino-esp32/assets/19906209/8d5190db-f6f9-445f-a565-d403f2fedc43)
static void YUV420PPackages(uint8_t *yuv420, uint8_t *y_ptr, uint8_t *u_ptr,
                uint8_t *v_ptr, int width, int height)
{
    //Y分量的长度
    int yLen = width * height;
    //U和V分量的长度
    int uvLen = width / 2 * height / 2;
    memcpy((unsigned char *)yuv420, y_ptr, yLen);
    memcpy((unsigned char *)yuv420 + yLen, u_ptr, uvLen);
    memcpy((unsigned char *)yuv420+yLen+uvLen, v_ptr, uvLen);
}

static void YUYV422Packages(uint8_t *yuv422, uint8_t *y_ptr, uint8_t *u_ptr, uint8_t *v_ptr, int width, int height)
{
    //计算出空间大小
    int numBytes = width * height + width / 2 * height * 2;
    unsigned int yIndex = 0;
    unsigned int uIndex = 0;
    unsigned int vIndex = 0;
    //封包
    for (unsigned int i = 0; i < numBytes; i+=4) {
        //y
        memcpy((unsigned char *)yuv422+i,y_ptr+yIndex,1);
        yIndex++;
        //u
        memcpy((unsigned char *)yuv422+i+1, u_ptr+uIndex, 1);
        uIndex++;
        //y
        memcpy((unsigned char *)yuv422+i+2, y_ptr+yIndex, 1);
        yIndex++;
        //v
        memcpy((unsigned char *)yuv422+i+3, v_ptr+vIndex, 1);
        vIndex++;
    }
}
