### ISSUE TITLE
Arduino Support for WPA3 Authentication in AP mode

### ISSUE THREAD

**Issue by brindhakumar** [espressif/arduino-esp32#8451]
### Related area

WiFi

### Hardware specification

ESP32S2 Dev Module

### Is your feature request related to a problem?

I am facing a issue with configuring WPA3 in Access point Mode.
After the configuration I found that SAE Support is not there in the access point mode. It works with Station mode.
But configuring WPA3_AUTH_MODE in Access point will not work. 

### Describe the solution you'd like

When using the function  WiFi.softAP() with Authentication configuration I need to enable WPA3 Authentication with SAE Support

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by Rotzbua** [comment]
Current IDF4.4 does not support WPA3 AP.
Earliest support is IDF5.1. https://github.com/espressif/esp-idf/issues/10939
So take a ☕ until it is time.

**Comment by VojtechBartoska** [comment]
Possibly related to https://github.com/espressif/arduino-esp32/pull/8760
