### ISSUE TITLE
Arduino SDK Support for ESP-IDF 5.1

### ISSUE THREAD

**Issue by brindhakumar** [espressif/arduino-esp32#8452]
### Related area

Arduino as component

### Hardware specification

ESP32S2 Dev Module

### Is your feature request related to a problem?

I am trying to use Arduino as component in ESP-IDF V5.1 But The Arduino SDK Support available only for ESP - IDF version 4.4.1 to 4.4.99. 
I referred this link for converting arduino as component in ESP - IDF version 4.4.5
https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/esp-idf_component.html

### Describe the solution you'd like

Need Arduino SDK Support for Espressif IDF Version 5.0 and above.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
5.1 support is in the `esp-idf-v5.1-libs` branch currently. Use that :)
