### ISSUE TITLE
Exposing spiffs_object_truncate() in FS API

### ISSUE THREAD

**Issue by everslick** [espressif/arduino-esp32#847]
SPIFFS offers an function to truncate a file to a specific size. This is very useful, for rotating logfiles without going through a temp file as this needs additional space on the filesystem. Therefor I propose to expose

s32_t spiffs_object_truncate(
spiffs_fd *fd,
u32_t new_len,
u8_t remove_object);

which is defined in spiffs_nucleus.h through the FS API.

**Comment by freedaun** [comment]
I find I need this feature to truncate partially completed file-transfers. Each 32kB of the file is verified, validated and file is truncated after the last validated 32kB. Any progress on this? I'm following instructions now on https://github.com/pellepl/spiffs/issues/107 but this is obviously less than ideal.
