### ISSUE TITLE
MD5Builder has a potential memory leak

### ISSUE THREAD

**Issue by arkhipenko** [espressif/arduino-esp32#8472]
### Board

any

### Device Description

n/a

### Hardware Configuration

n/a

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Windows 10

### Flash frequency

40

### PSRAM enabled

no

### Upload speed

115200

### Description

in the `addStream` method

```
bool MD5Builder::addStream(Stream & stream, const size_t maxLen)
```

code may return without deallocating memory, thus losing 512 bytes. 

```
        // read data and check if we got something
        int numBytesRead = stream.readBytes(buf, readBytes);
        if(numBytesRead< 1) {
            return false;
        }
```

should be

```
        // read data and check if we got something
        int numBytesRead = stream.readBytes(buf, readBytes);
        if(numBytesRead< 1) {
            free (buf);
            return false;
        }
```

### Sketch

```cpp
n/a
```

### Debug Message

```plain
n/a
```

### Other Steps to Reproduce

n/a

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
If you edit [here](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/MD5Builder.cpp#L81), it will just take a couple clicks to submit a PR.
