### ISSUE TITLE
Problem with PSRAM

### ISSUE THREAD

**Issue by samuelatceon** [espressif/arduino-esp32#8495]
### Board

ESP32-WROVER-IE-N16R8

### Device Description

this is a development board that is planned to be used in conjunction with the SIM7600CE LTE chip, and CAN and RS 485 chips for other communication purposes.  

### Hardware Configuration

n/a

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

when uploading a simple hello world program to the esp32-wrover-ie-n16r8, it accepts the new software, however upon restating, on the aerial monitor i get this message E (88) psram: PSRAM ID read error: 0x7ca9ae06, this adress has been seen to change at times. 

ive given a screen shot of the current settings that i have been using. 

![ide](https://github.com/espressif/arduino-esp32/assets/141648517/e0c9b1b8-94c2-4e11-88da-6febc4861a3a)

### Sketch

```cpp
I am just using a simple "hello World!" program.,
```

### Debug Message

```plain
https://user-images.githubusercontent.com/141648517/258825997-43e0a0d5-100b-48ba-8589-9b4affef6d13.png
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
this suggests an issue with the PSRAM itself (or the module). Does it work if you set the frequency to 40MHz? Have you tried another board/module?

**Comment by podaen** [comment]
Or you try to map more than 4MB.

**Comment by samuelatceon** [comment]
> this suggests an issue with the PSRAM itself (or the module). Does it work if you set the frequency to 40MHz? Have you tried another board/module?

Thank you for your suggestion, i have another board, but with the same issue.

**Comment by samuelatceon** [comment]
> Or you try to map more than 4MB.

do you have any information on how to do that, cause ive tried looking for the boards.txt file through the file manager without any luck?

**Comment by samuelatceon** [comment]
![image](https://github.com/espressif/arduino-esp32/assets/141648517/4de4d9c7-ea59-4c27-9143-40764e89700b)
this seems to be the main issue, i thought my making sure PSRAM in the tools page is enabled would have ensure this.

**Comment by podaen** [comment]
> ![image](https://user-images.githubusercontent.com/141648517/259064340-4de4d9c7-ea59-4c27-9143-40764e89700b.png) this seems to be the main issue, i thought my making sure PSRAM in the tools page is enabled would have ensure this.

He dit that. Look at this description.



> > Or you try to map more than 4MB.
> 
> do you have any information on how to do that, cause ive tried looking for the boards.txt file through the file manager without any luck?

Are you trying to do it your self? PSRAM is a separate chip on your Esp board. It has range of datablocks you can write in. If you try to access without that range you will get random values after.

**Comment by samuelatceon** [comment]
> @samuelatceon - What Arduino Core version is being used?
im not entirely sure what you mean by core version 
![image](https://github.com/espressif/arduino-esp32/assets/141648517/b5c9cc47-d228-4384-af42-7c0a790b8ff1)

**Comment by samuelatceon** [comment]
> I see now. You have selected the wrong board. Please take "ESP Dev Module". I know it is weired because there are profiles like "ESP Wrover module" that doesn't have PSRAM and there is "ESP32 Wrover kit (all versions)" that didn't work for me too.

unfortunately, changing the board hasnt made any changes to outcome 
![image](https://github.com/espressif/arduino-esp32/assets/141648517/29604fcb-be5d-4142-bc41-18d018566509)

**Comment by samuelatceon** [comment]
please refer to this thread #8505
