### ISSUE TITLE
Retrieving HTTP header parameters should be case-insensitive using HTTPClient

### ISSUE THREAD

**Issue by TeepMZ** [espressif/arduino-esp32#8524]
### Related area

it is related to Http request using HTTPClient

### Hardware specification

ESP32-WROOM-DA-MODULE

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Using the HTTPClient library to read a response received from the server via the HTTP protocol, we can use the collectHeaders and header functions to obtain specific header parameter values. Currently, the String HTTPClient::header(const char* name) function is case-sensitive. However, certain server containers might employ lowercase for all header parameters. Consequently, it would be advantageous for the HTTPClient::header function to be case-insensitive when searching for a specific parameter.

PS: A similar behavior is observed in the HTTPClient::handleHeaderResponse function, where the "equalsIgnoreCase" function is employed to verify the existence of a header key
Lib link : libraries/HTTPClient

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by lucasssvaz** [comment]
You are correct, the comparison in `HTTPClient::header(const char* name)` should be case-insensitive to conform to the [RFC](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2). I'll open a PR to fix this.
