### ISSUE TITLE
ISSUES related to Arduino Core 2.0.10+ with IDF 4.4.5

### ISSUE THREAD

**Issue by SuGlider** [espressif/arduino-esp32#8528]
### Board

Any

### Device Description

Any

### Hardware Configuration

N/A

### Version

v2.0.11

### IDE Name

Arduino IDE

### Operating System

Win11

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

This is just a collection of issues related to Arduino 2.0.10/2.0.11 + IDF 4.4.5

1) USB CDC with C3 and maybe with S3
https://github.com/espressif/arduino-esp32/issues/8522

2) Smaller HEAP with ESP32
https://github.com/espressif/arduino-esp32/issues/8482#issuecomment-1664767990

3) DAC I2S IDF function parameters changed
https://github.com/espressif/arduino-esp32/issues/8467

### Sketch

```cpp
In each issue above.
```

### Debug Message

```plain
In each issue above.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
All issues in this summary ticket have been solved.
