### ISSUE TITLE
What Dial Switch do in ESP8266-DEVKITC

### ISSUE THREAD

**Issue by ktauchathuranga** [espressif/arduino-esp32#8532]
### Board

ESP8266-DEVKITC

### Device Description

![df4919912db5bfc6f37924735736651d150b9082](https://github.com/espressif/arduino-esp32/assets/79928743/d97a7c26-8861-4bc4-8573-a120fe567382)

### Hardware Configuration

null

### Version

other

### IDE Name

null

### Operating System

null

### Flash frequency

null

### PSRAM enabled

yes

### Upload speed

null

### Description

guys,
I have ESP8266-DEVKITC dev board, and it has a dial switch. When I reached in documents, it said its for " Auto Download and Flow Control"
I don't know what that means, can someone please explain that to me?

### Sketch

```cpp
null
```

### Debug Message

```plain
null
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by P-R-O-C-H-Y** [comment]
Hi @ktauchathuranga, this repository is for ESP32 chip family. You can try to ask on [ESP8266 Arduino repository ](https://github.com/esp8266/Arduino) but I found your question was quite well answered on [esp32 forum](https://esp32.com/viewtopic.php?f=2&p=118528).

I am closing it as this question is not related to this project.
