### ISSUE TITLE
ESP32-S3 ESP32-S3 doesn't work and is not suitable for a decent production level projects

### ISSUE THREAD

**Issue by virtyaluk** [espressif/arduino-esp32#8539]
### Board

ESP32-S3-DevKitC-1 N32R8V

### Device Description

DevKitC from [here](https://www.aliexpress.com/item/1005003979778978.html?spm=a2g0o.order_list.order_list_main.71.15ca1802MmySrI)

### Hardware Configuration

USB connected to my laptop's USB through USB-to-USB-C adapter

### Version

v2.0.11

### IDE Name

Arduino IDE

### Operating System

macOS 13.5

### Flash frequency

QIO 80Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

It is simple - the board doesn't work. It doesn't matter how hard I try it doesn't want to run my sketch. I've tried different Arduino IDE configs based on what I heard from other people on the Internet experiencing the same problems with this board, but nothing helps. The uploading process works fine, but the actual code won't execute. I have a dozen other boards like TTGO, Lolin D32, and regular ESP32 which work just fine. I simply that this board doesn't work and couldn't be used for a production-grade project.

### Sketch

```cpp
#include <Arduino.h>
#include <Wire.h>

void setup() {
  Wire.begin();
  Serial.begin(9600);

  while (!Serial)
  {
  }

  delay(500);
}

void i2c_scanner() {
  byte error, address;
  int nDevices;
 
  Serial.println("Scanning...");
 
  nDevices = 0;
  for(address = 1; address < 127; address++ )
  {
    // The i2c_scanner uses the return value of
    // the Write.endTransmisstion to see if
    // a device did acknowledge to the address.
    Wire.beginTransmission(address);
    error = Wire.endTransmission();
 
    if (error == 0)
    {
      Serial.print("I2C device found at address 0x");
      if (address<16)
        Serial.print("0");
      Serial.print(address,HEX);
      Serial.println("  !");
 
      nDevices++;
    }
    else if (error==4)
    {
      Serial.print("Unknown error at address 0x");
      if (address<16)
        Serial.print("0");
      Serial.println(address,HEX);
    }    
  }
  if (nDevices == 0)
    Serial.println("No I2C devices found\n");
  else
    Serial.println("done\n");
 
  delay(5000);           // wait 5 seconds for next scan
}

void loop() {
  i2c_scanner();
}
```

### Debug Message

```plain
02:11:33.980 -> 
02:11:33.980 -> ELF file SHA256: 6278e44c170468c9
02:11:33.980 -> 
02:11:33.980 -> E (183) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
02:11:33.980 -> Rebooting...
02:11:34.012 -> ESP-ROM:esp32s3-20210327
02:11:34.012 -> Build:Mar 27 2021
02:11:34.012 -> rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
02:11:34.012 -> Saved PC:0x40377014
02:11:34.012 -> SPIWP:0xee
02:11:34.012 -> Octal Flash Mode Enabled
02:11:34.012 -> For OPI Flash, Use Default Flash Boot Mode
02:11:34.012 -> mode:SLOW_RD, clock div:1
02:11:34.012 -> load:0x3fce3808,len:0x44c
02:11:34.012 -> load:0x403c9700,len:0xbe4
02:11:34.012 -> load:0x403cc700,len:0x2a68
02:11:34.012 -> entry 0x403c98d4
02:11:34.109 -> 
02:11:34.174 -> assert failed: do_core_init startup.c:328 (flash_ret == ESP_OK)
02:11:34.174 -> 
02:11:34.174 -> 
02:11:34.174 -> Backtrace: 0x40377406:0x3fceb180 0x4037a70d:0x3fceb1a0 0x403801cd:0x3fceb1c0 0x42008ad6:0x3fceb2f0 0x40376d77:0x3fceb320 0x403cd823:0x3fceb350 0x403cdae2:0x3fceb380 0x403c9929:0x3fceb4b0 0x40045c01:0x3fceb570 |<-CORRUPTED
02:11:34.174 ->
```

### Other Steps to Reproduce

My Arduino IDE setup:
<img width="531" alt="image" src="https://github.com/espressif/arduino-esp32/assets/795984/5cc94c88-d673-4630-9fb1-d6008cccf648">

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@virtyaluk - I think that the `ESP32-S3-DevKitC-1 N32R8V` is Octal Flash and Octal PSRAM.
Your configuration says `QIO 80MHz`, please change it to `OPI 80MHz` and in case you need to enable PSRAM, please select `OPI PSRAM`.

Please let me know if this new setting makes you board work.

**Comment by SuGlider** [comment]
@virtyaluk - 

Confirmed. Looking into the table of parts, it says OT (Octal Flash and PSRAM). Please change it in your Arduino IDE configuration.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html#ordering-information

<html>
<body>


ESP32-S3-DevKitC-1-N32R8V | ESP32-S3-WROOM-2-N32R8V | 32 MB OT | 8 MB OT | 1.8 V
-- | -- | -- | -- | --



</body>
</html>

**Comment by SuGlider** [comment]
@virtyaluk - Please let me know if this issue has been solver and could be closed.

**Comment by twinsvision** [comment]
> @virtyaluk - I think that the `ESP32-S3-DevKitC-1 N32R8V` is Octal Flash and Octal PSRAM. Your configuration says `QIO 80MHz`, please change it to `OPI 80MHz` and, in case you need to enable PSRAM, please select `OPI PSRAM`.
> 
> Please let me know if this new setting makes you board work.

GREAT!!! Works like a charm now! Been looking for this solution for days, thanks alot @SuGlider !

**Comment by lbernstone** [comment]
> @virtyaluk - Please let me know if this issue has been solved and could be closed.

Do you now think the ESP32-S3 does work and is suitable for a decent production level project? :)

**Comment by everslick** [comment]
@virtyaluk Please close the issue.

**Comment by VojtechBartoska** [comment]
Closing.
