### ISSUE TITLE
Ble-server example give me 3 services?

### ISSUE THREAD

**Issue by pickmonster100** [espressif/arduino-esp32#8543]
### Related area

BT

### Hardware specification

ESP32 DevKit

### Is your feature request related to a problem?

I tried esp32 ble-server to bluetouch connect,but I found a question,When I perform a bluetooth connection, 3 services are created, but only one is available,anyone can help me? Example link:https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/examples/BLE_server/BLE_server.ino
![image](https://github.com/espressif/arduino-esp32/assets/133647165/ad7d27ab-8235-407e-9849-49dab883c40c)

### Describe the solution you'd like

I think there should be only one service, but created three.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
@pickmonster100 - BLE has 2 mandatory default services (0x1801 and 0x1800).

The `BLE_server.ino` example creates:
UUID 0x1800 (Generic Access Service)
UUID 0x1801 (Generic Attribute Service)
UUID 4fafc201-1fb5-459e-8fcc-c5c9c331914b (The Sketch `SERVICE_UUID` Service)
