### ISSUE TITLE
Bluethoot Mac

### ISSUE THREAD

**Issue by totovr** [espressif/arduino-esp32#856]
### Hardware: MacOsx

Board: dev32 Board						
Core Installation/update date:			november/2017
IDE name:							Arduino IDE
Flash Frequency:					        40Mhz
Upload Speed:						115200

### Description:

esp32 support bluethoot with MacOsx?

**Comment by me-no-dev** [comment]
Yes, why wouldn't it?

**Comment by totovr** [comment]
Can you provide me an example to prove it? please.

**Comment by me-no-dev** [comment]
? I do not get your request? What have you tried so far and how are you trying to connect to the device?

**Comment by totovr** [comment]
I'm currently using [this board](http://espressif.com/en/products/hardware/esp32-devkitc/overview) with the Arduino IDE.

I tried this [example](https://github.com/nkolban/ESP32_BLE_Arduino/blob/cb1ab4ea76af17d347cdadcc003d1fe53af12aa7/examples/BLE_client/BLE_client.ino), but OS doesn't recognize the "bluetooth" device.

**Comment by me-no-dev** [comment]
this is a BLE client and not server. How are you trying to connect to a device on you Mac? You need some sort of BLE app on your Mac if you want to see BLE devices (and another sketch that is not a Client)
