### ISSUE TITLE
Installation issue:  get.exe UnicodeDecodeError

### ISSUE THREAD

**Issue by Cpt-Hook** [espressif/arduino-esp32#860]
After cloning the repository I exected get.exe and this is the error message.
I have no idea what to do now.
Tried administrator and compatibility mode, but the error seems to be caused by a codec exception, which is wierd

System: Windows, Info: Windows-10-10.0.16299
Platform: i686-mingw32
Traceback (most recent call last):
  File "get.py", line 138, in <module>
    get_tool(tool)
  File "get.py", line 76, in get_tool
    local_path = dist_dir + archive_name
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 12: ordinal not in range(128)
Failed to execute script get

**Comment by copercini** [comment]
Your folder or file name has any ⊘ somewhere?
![screenshot_1](https://user-images.githubusercontent.com/21266776/33146247-8fe6a01c-cfaa-11e7-96ac-6ea4290ef123.png)

**Comment by Cpt-Hook** [comment]
Oh this is possible, I am from the Czech republic, so in my username there is a "ř" symbol. Since I cannot simply change my username in win10 (I think at least), is there a way to at least change install folder of esp32 files? ESP8266 installed its files somewhere else if I remember correctly.

**Comment by me-no-dev** [comment]
done ;)

**Comment by Cpt-Hook** [comment]
Thank you for a quick fix, amazing.

**Comment by me-no-dev** [comment]
:) you welcome
