### ISSUE TITLE
Bluetooth connection with cellphone without any app 

### ISSUE THREAD

**Issue by Talha-Babar** [espressif/arduino-esp32#8603]
### Board

ESP32 Dev Module

### Device Description

ESP32 Dev Module and cell phone

### Hardware Configuration

Want to connect esp32 with cellphone

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 

### Flash frequency

40Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

I want to connect esp32 with cellphone using BLE and i dont want to use any app in cell phone for connection. I don't want to send any data just want to make a connection. Is this possible?

If yes, how can i do that?

### Sketch

```cpp
.
```

### Debug Message

```plain
.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hi, please consider using Gitter channel instead of issue tracker with asking for help.
