### ISSUE TITLE
Newest build broken "_VOLUMES was not declared in scope"

### ISSUE THREAD

**Issue by tgaraio** [espressif/arduino-esp32#862]
I updated my toolchain to the lastet esp-idf/xtensa-esp32-elf builds, now the arduino-esp32 breaks at line
.../arduino-esp32/libraries/SD/src//sd_diskio.cpp:60:31: error: '_VOLUMES' was not declared in this scope
 static ardu_sdcard_t* s_cards[_VOLUMES] = { NULL };

**Comment by me-no-dev** [comment]
probably change in IDF and not toolchain fault

**Comment by copercini** [comment]
Same as https://github.com/espressif/arduino-esp32/issues/858

Will close to concentrate this issue on https://github.com/espressif/arduino-esp32/issues/858  =)
