### ISSUE TITLE
Analog Attenuation API?

### ISSUE THREAD

**Issue by torntrousers** [espressif/arduino-esp32#87]
Thanks for the recently committed analog functions. 
Is there a problem with analog attenuation or some reason why its not exposed as an API to Arduino sketches? Or is it coming soon perhaps?

**Comment by me-no-dev** [comment]
Tried it and it did not work :)

**Comment by torntrousers** [comment]
Heh,  yes me too fiddling about in esp32-hal-adc and it didn't work for me either. Could I raise this as a bug with Espressif somewhere - (I don't properly understand how all the components fit together ) - is it  hardware thing or the sdk or idf ...?

**Comment by me-no-dev** [comment]
it's either hardware or we are missing some setting in the software that I do not know about. You can raise an issue in esp-idf as lower level guys visit that repo :)

**Comment by torntrousers** [comment]
Over [here](http://www.esp32.com/viewtopic.php?f=13&t=693&p=2940) it was suggested to use adc1_config_channel_atten, thats seems to work ok. 

Its in #include <driver/adc.h> and can do:
adc1_config_channel_atten(ADC1_CHANNEL_0, ADC_ATTEN_11db);
adc1_config_channel_atten(ADC1_CHANNEL_0, ADC_ATTEN_6db);
adc1_config_channel_atten(ADC1_CHANNEL_0, ADC_ATTEN_2_5db);
adc1_config_channel_atten(ADC1_CHANNEL_0, ADC_ATTEN_0db);

That seems to give a max input voltage of:
0db   = 1.1v
2.5db = 1.4v
6db   = 1.9v
11db  = 3.2v

**Comment by me-no-dev** [comment]
no wonder... I was writing to the wrong register

**Comment by me-no-dev** [comment]
please try the latest commit
```cpp
    analogSetAttenuation(ADC_0db);
    analogSetPinAttenuation(A18, ADC_0db);
    analogSetPinAttenuation(A19, ADC_2_5db);
    analogSetPinAttenuation(A6, ADC_6db);
    analogSetPinAttenuation(A7, ADC_11db);
```
