### ISSUE TITLE
Travis exploding 

### ISSUE THREAD

**Issue by stickbreaker** [espressif/arduino-esp32#879]
The automated build test on pull requests is failing in reference to "WiFiClientSecure.h" missing. My repo has not involved WiFi at all.

Chuck.

**Comment by me-no-dev** [comment]
It's the PIO build that is failing ;) @ivankravets

**Comment by ivankravets** [comment]
Yes, I see. I'm working on it. It's caused by a big update to PIO LIbrary Dependency Finder which will be introduced in PIO Core 3.5.0 next week.

@me-no-dev I'll ping you here just to restart a Job.

**Comment by me-no-dev** [comment]
Thanks :)

**Comment by ivankravets** [comment]
@me-no-dev please merge https://github.com/espressif/arduino-esp32/pull/881 , it should fix this issue.

**Comment by stickbreaker** [comment]
All Better
