### ISSUE TITLE
About ESP32 Arduino Lib Builder

### ISSUE THREAD

**Issue by Mushan-bin** [espressif/arduino-esp32#8830]
### Related area

ESP32,Arduino

### Hardware specification

ESP32 DevKitC

### Is your feature request related to a problem?

About ESP32 Arduino Lib Builder Build on Ubuntu, execute sudo pip install --upgrade pip, the following problem appears.

### Describe the solution you'd like

I would like to know where to compile the Arduino Lib Builder for creating ESP32 on umbuntu to create a custom Bluetooth connection library and use it on arduino.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by Mushan-bin** [comment]
![微信图片_20231103172923](https://github.com/espressif/arduino-esp32/assets/110099337/ae554e8f-95f2-4f11-bf57-0799dc6b589a)
![3](https://github.com/espressif/arduino-esp32/assets/110099337/11953780-b774-4edc-9740-78c9a9463739)

**Comment by me-no-dev** [comment]
so you could not upgrade PIP for the lib-builder. Please search google on how to overcome the PIP issue and then if you fix it and could not continue for another reason, post an issue in the lib-builder repo and not here.
