### ISSUE TITLE
A time less than 2017 year makes `ESP32Time.getTime()` slow.

### ISSUE THREAD

**Issue by luckyabsoluter** [espressif/arduino-esp32#8837]
### Board

Board hardware or firmware ESP32Time RTC

### Device Description

ESP32

### Hardware Configuration

sorry. many pin attached.

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

40Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

A time less than 2017 year makes `ESP32Time.getTime()` slow. (about 5 seconds)
Is it a firmware issue?

### Sketch

```cpp
#include <ESP32Time.h>

ESP32Time rtc;

void setup() {
    Serial.begin(115200);
}

void loop() {
    rtc.setTime(1, 1, 1, 1, 1, 2016);
    Serial.println("2016");
    timing(); // 5010
    rtc.setTime(1, 1, 1, 1, 1, 2017);
    Serial.println("2017");
    timing(); //0
}

void timing() {
    unsigned long st = millis();
    rtc.getTime();
    unsigned long et = millis() - st;
    Serial.println(et);
}
```
```


### Debug Message

```plain
.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Just out of curiosity and because we are already 2023, what is the use case to set the time to 7+ years ago?

**Comment by luckyabsoluter** [comment]
@me-no-dev
My RTC module was reset and I struggled with a weird bug. The same project, same code but suddenly stopped working, and the problem became a mystery.

**Comment by lbernstone** [comment]
Seems a lot more likely it is making the rtc grumpy, so it is slow to respond.  Look in their library.  ESP32 runs with a time back in the 1970s in many, many environments :)

**Comment by luckyabsoluter** [comment]
My bad. I had doubts about the absence of a loop in the ESP32Time library, but after upgrading the version from 1.0.2 to 2.0.4, the problem was resolved without any issues.

**Comment by 6v6gt-duino** [comment]
I also found this at https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-time.c

I haven't traced back your function call but the implication from this is that the ESP32  may want to reject a time with a year part of  2016 or earlier after waiting a timeout period. This matches your problem description. 

```
bool getLocalTime(struct tm * info, uint32_t ms)
{
    uint32_t start = millis();
    time_t now;
    while((millis()-start) <= ms) {
        time(&now);
        localtime_r(&now, info);
        if(info->tm_year > (2016 - 1900)){
            return true;
        }
        delay(10);
    }
    return false;
}
```

**Comment by szilvasyz** [comment]
While playing with an own DCF77 synced clock using ESP32 right just now I run into the trouble getLocalTime(&timeinfo) can be very slow. System time has been initialized to 2000-01-01 in the setup and I experienced weird slow update of the displayed time (should be updated once a second but saw once per 5 seconds) until the time is synced from DCF. 
Arduino IDE 2.3.6
ESP32 by Espressif v3.3.1

It seems that getLocalTime() uses a default timeout of 5 seconds and ESP32 implementation assumes years before 2017 are invalid as 6v6gt-duino pointed it. A workaround can be explicitly passing the maximum timeout to the getLocalTime() call, I am now using in in getLocalTime(&timeinfo, 20) form with no more troubles.
