### ISSUE TITLE
No support for the different versions of ESP32S3

### ISSUE THREAD

**Issue by packetkiller** [espressif/arduino-esp32#8910]
### Board

ESP32S3-WROOM2

### Device Description

ESP32S3-WROOM2 DevKitC v1
The builtin LED is on GPPIO38 (this is not the same GPIO layout as other ESP32S3 boards)
Some comments about hardware error causing GPIO38 to not work are incorrect and it can be proved via standard C code or using ESP-IDF to configure the builtin addressable LED.

### Hardware Configuration

Nothing else connected to the board; using GPIO38 connected to the integrated addressable LED.

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE (library errors cause incorrect GPIO configuration), ESP-IDF (works without issue), Visual Studio Code (same issue as Arduino IDE since it uses same libraries)

### Operating System

Windows 11, tried on MAC OS with same results.

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

default

### Description

Using Arduino IDE libraries, cannot configure blinky examples for some ESP32S3 boards to work with built-in addressable LED at GPIO38. Works fine using ESP-IDF at GPIO38.

### Sketch

```cpp
Using Arduino IDE 2.2.1:
 BlinkRGB example
ESP-IDF:
 BlinkRGB example
```

### Debug Message

```plain
None
```

### Other Steps to Reproduce

Using ESP-IDF built-in addressable LED works as expected.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Board manufacturers are free to add definitions to their boards. We are an open project and accept many such additions (just check the length of the boards list in Arduino). At the same time, we have no way of knowing or testing all boards that are out there.

Sorry but closing this issue as "can not do"
