### ISSUE TITLE
Arduino IDE 2.2.1 & ESP32 cam: fatal error: bits/cpu_defines.h: No such file or directory 

### ISSUE THREAD

**Issue by Akiradanica** [espressif/arduino-esp32#8951]
### Board

ESP32 Cam Module

### Device Description

ESP 32 Cam Motherboard or Arduino Uno

### Hardware Configuration

nothing i guess

### Version

v2.0.14

### IDE Name

Arduino IDE

### Operating System

Windows 11

### Flash frequency

40 MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

When i tried verifying code (blank code or the Camera Web server code )and with the attach "Ai Thinker ESP32-CAM" board.

it states that 
"fatal error: bits/cpu_defines.h: No such file or directory
 #include <bits/cpu_defines.h>"

In addition when i install the esp32 board for the first time, my internet is poor. 

i tried reinstalling everything, and unistalling the arduino ide itself, delete its files, but same issue appear.

### Sketch

```cpp
more on how to completely clean unistall the arduino ide
```

### Debug Message

```plain
fatal error: bits/cpu_defines.h: No such file or directory
 #include <bits/cpu_defines.h>
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by P-R-O-C-H-Y** [comment]
@Akiradanica Hi, can you please locate where the `#include <bits/cpu_defines.h>` comes from?
You can take a look on this issue #3745. Were you using manual installation or through the Arduino IDE boards manager?

**Comment by Akiradanica** [comment]
its nowhere to be found in the location of arduino in app data, and the other location of it

**Comment by VojtechBartoska** [comment]
Hello, closing this as expired, if needed, you can reopen.
