### ISSUE TITLE
[ESP32-C2] setCpuFrequencyMhz(): Bad frequency: 120 MHz! Options are: 240, 160, 80, 26 and 13 MHz

### ISSUE THREAD

**Issue by TD-er** [espressif/arduino-esp32#8955]
### Board

ESP32-C2

### Device Description

Just any ESP32-C2

### Hardware Configuration

Nothing attached to the board

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Windows 11

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

Cannot set the default CPU frequency, even though it is initially running at this frequency.
Debug error:
```
[   401][E][esp32-hal-cpu.c:195] setCpuFrequencyMhz(): Bad frequency: 120 MHz! Options are: 240, 160, 80, 26 and 13 MHz
```

Reported frequencies of this board:

- ESP Chip ID:  1005908 (0x0F5954)
- ESP Chip Frequency: 120 MHz
- ESP Crystal Frequency: 26 MHz
- ESP APB Frequency: 40 MHz
- ESP Chip Model: ESP32-C2
- ESP Chip Revision: 1.0

### Sketch

```cpp
setCpuFrequencyMhz(120);
```

### Debug Message

```plain
[   401][E][esp32-hal-cpu.c:195] setCpuFrequencyMhz(): Bad frequency: 120 MHz! Options are: 240, 160, 80, 26 and 13 MHz
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by P-R-O-C-H-Y** [comment]
@TD-er Thank you for reporting. I will take a look fix the issue.
