### ISSUE TITLE
Support Secure Boot and Flash Encryption

### ISSUE THREAD

**Issue by DanielLester83** [espressif/arduino-esp32#8974]
### Related area

Security

### Hardware specification

ESP32

### Is your feature request related to a problem?

The Current Process is difficult, requires redundant installs and potentially confusing.

### Describe the solution you'd like

I realize this would be an advanced feature, but it would be nice to have an automated process of setting up encryption and secure boot of esp32 devices, burning the efuses and storing the keyfile(s) in the project file and then pre encrypting all future uploads if keyfile(s) are found.

### Describe alternatives you've considered

Do it the Hard Way.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by Jason2866** [comment]
Not supported with Arduino. You have to use IDF.

**Comment by SuGlider** [comment]
@VojtechBartoska - MCU BOOT + Arduino.

**Comment by me-no-dev** [comment]
> @VojtechBartoska - MCU BOOT + Arduino.

Nope. I looked into it and is not any better than what we already have. MCU Boot is made for micros, like STM32, which do not already have partitions and so on support. If we are do add MCU Boot to our Arduino, a lot of flash space will be wasted and people will not like it. Arduino as component is the way to go here, if someone wants that feature.

**Comment by SuGlider** [comment]
https://github.com/mcu-tools/mcuboot/blob/main/docs/readme-espressif.md
https://docs.mcuboot.com/readme-espressif.html

There is already a MCU Boot for ESP32 SoCs.

**Comment by me-no-dev** [comment]
It's main purpose is to manage the main firmware, which is expected to always be at certain address in flash (let's take 0x1000 as example). When you want to OTA or something else, it would swap the running firmware with an updated on, by writing it to the same start address that the chip expects. This takes a lot of read/writes to the flash and makes no sense when we (ESP32 platform) can have firmwares at different addresses and switch them at will. Given that our options are much cleaner and easy on the flash, MCU Boot makes no sense.

**Comment by Jason2866** [comment]
My two cents, there is no easy way to implement secure boot and flash encryption in Arduino.
Arduino is reduced to basic features to make it simple to use. For enhanced and/or special cases there is IDF. As always you can't have anything.

**Comment by VojtechBartoska** [comment]
Up to the comments there are no actions step to be done. Closing as wontfix.
