### ISSUE TITLE
Installation only ESP32: pb to recompile any Wifi example

### ISSUE THREAD

**Issue by JPB1JPB1** [espressif/arduino-esp32#9]
hello,

nice to have this Arduino portage for ESP32.

Installing only this repertory arduino-esp32 and the python part,( i've NOTHING of ESP8266 library) , i failed to recompile few examples....
Please, this repertory is not enough to add to arduino1.6.9; i guess except if i ...
Please, can you regenerate a arduino-esp32 and with all the librairie files needed..

I keep looking forward for this.
Keep going and good..
Jp

**Comment by me-no-dev** [comment]
There is still lots that needs to be written and added. Expects many updates soon ;) This is just the start :)
