### ISSUE TITLE
log expansion

### ISSUE THREAD

**Issue by Lagunaxx** [espressif/arduino-esp32#9008]
### Related area

logging

### Hardware specification

any

### Is your feature request related to a problem?

low logging info

### Describe the solution you'd like

line _167_ and line _177_ of [https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-gpio.c]arduino-esp32/blob/master/cores/esp32/esp32-hal-gpio.c(url)
`log_e("Pin is not set as GPIO.");`
change to 
`log_e("Pin %i is not set as GPIO.", pin);`

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
Thanks @Lagunaxx! PR #9011 shall solve it.
