### ISSUE TITLE
idf.py v4.4 on v4.4 returns components/arduino/cores/esp32/Esp.cpp:289:14: error: 'EFUSE_RD_CHIP_VER_PKG_ESP32D0WDR2V3' was not declared in this scope case EFUSE_RD_CHIP_VER_PKG_ESP32D0WDR2V3

### ISSUE THREAD

**Issue by SylvianHemus** [espressif/arduino-esp32#9015]
### Board

ESP-32S

### Device Description

NodeMcu

### Hardware Configuration

no

### Version

other

### IDE Name

Emacs with ESP-IDF

### Operating System

Gentoo GNU+Linux

### Flash frequency

can't remember

### PSRAM enabled

yes

### Upload speed

can't remember

### Description

expect to compile

### Sketch

```cpp
hello world.c
```

### Debug Message

```plain
see title
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
Use the latest release of 4.4 (4.4.6 ATM).  The product was not released until after 4.4.0.

**Comment by VojtechBartoska** [comment]
any updates @SylvianHemus?

**Comment by VojtechBartoska** [comment]
Closing as expired due to no answer.
