### ISSUE TITLE
Can I use my Esp32-C6 in PlatformIO with the 3.0.0-alpha? if yes, how?

### ISSUE THREAD

**Issue by leorossi2005** [espressif/arduino-esp32#9048]
### Related area

Board Support

### Hardware specification

Esp32-C6 on PlatformIO

### Is your feature request related to a problem?

yes

### Describe the solution you'd like

How can I do this

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by SuGlider** [comment]
I think that it is possible by using Tasmota PlatformIO packages.
@Jason2866 - Any hint about it?

**Comment by Jason2866** [comment]
Correct not possible with official Platformio. I forked and did a version for project Tasmota.
The fork is not 100% compatible. Some changed sdkconfig settings and some library removed (SPIFFS). You can try and use with
```
platform = https://github.com/tasmota/platform-espressif32/releases/download/2023.12.10/platform-espressif32.zip
```

**Comment by Jason2866** [comment]
Using this open PR, makes it possible to use original espressif sources and libs
https://github.com/platformio/platform-espressif32/pull/1281

**Comment by leorossi2005** [comment]
> Using this open PR, makes it possible to use original espressif sources and libs [platformio/platform-espressif32#1281](https://github.com/platformio/platform-espressif32/pull/1281)

Thanks now I can use the 3.0.0 version, but for some reason it says that the ESP32-C6 is not supported anyway

**Comment by Jason2866** [comment]
There is no valid C6 boards.json for Arduino. you have to add a custom boards.json yourself

**Comment by leorossi2005** [comment]
How can I do this?

**Comment by mcuw** [comment]
Hi @leorossi2005,
have a look at this platformio project template: https://github.com/mcuw/ESP32-ghbuild-template
It includes some boards configurations, see https://github.com/mcuw/ESP32-ghbuild-template/blob/main/boards/
The latest arduino framework version is defined in the platform.ini, see https://github.com/mcuw/ESP32-ghbuild-template/blob/d3b2f578cdd3e89b41589b63f97c2a51268fdef3/platformio.ini#L57

**Comment by mcuw** [comment]
idf v3.0.0 is released. You can use the latest version so I think you can close this issue.
