### ISSUE TITLE
ADC2 issue

### ISSUE THREAD

**Issue by chegewara** [espressif/arduino-esp32#905]
Im trying to use `adc2_config_channel_atten` and i have pproper header included since `adc1_config_channel_atten` works but im getting this error message:
` 'adc2_config_channel_atten' was not declared in this scope`.

**Comment by me-no-dev** [comment]
Have you tried Arduino's adc functions to do that? https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-adc.h#L92

**Comment by chegewara** [comment]
No i didnt. Im so much tied to low level esp-idf api and i forgot about to check it.
