### ISSUE TITLE
WiFiServer receive GET parameters

### ISSUE THREAD

**Issue by krmax44** [espressif/arduino-esp32#909]
I'm currently doing some testing with the SimpleWiFiServer example sketch. For my project, I need to pass dynamic variables between the client and the server (ESP32).

Let's say, I make the following request: `http://myesp32/test?message=hello`
Now I'd like to get the `GET` parameter `message`. On the ESP8266, you can use `server.arg("message")`, and it would spit out `hello`, but this is not working on the ESP32. How can I get this working?

**Comment by me-no-dev** [comment]
that requires parsing the full http stuff :) in the pull requests there is a PR with the 8266 web server. Also you can run ESPAsyncWebServer which works on ESP32

**Comment by krmax44** [comment]
ok, i rather get an ESP8266.
