### ISSUE TITLE
 Error: HTTP_POST, HTTP_GET, HTTP_PUT, and HTTP_DELETE  were not declared in this scope

### ISSUE THREAD

**Issue by Nezaemmy** [espressif/arduino-esp32#9093]
### Board

ESP32 DEV MODULE

### Device Description

ESP32 DEV MODULE

### Hardware Configuration

NO hardware attached

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 11

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

921600

### Description

After migrating from version 2.14 to Alpha 3, Arduino-HomeKit-ESP32 has a conflict with the WIFI Manager library or other libraries similar to WIFI Manager. 
Arduino-HomeKit-ESP32 and WIFI Manager don't have any compiler errors, the errors come when you add #include <WiFiManager.h> in the Arduino-HomeKit-ESP32 example.

### Sketch

```cpp
Arduino-HomeKit-ESP32 Library with example is here: https://github.com/Nezaemmy/Arduino-HomeKit-ESP32.git

The 3 components of the Arduino-HomeKit-ESP32 example(ESP32_homekit, ESPButton, and buildin_led_accessory)must be in the same folder.

This is the WIFI Manager library: https://github.com/tzapu/WiFiManager
```

### Debug Message

```plain
c:\Users\Emugwaneza\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp: In member function 'void WiFiManager::setupHTTPServer()':
c:\Users\Emugwaneza\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp:658:34: error: 'HTTP_POST' was not declared in this scope; did you mean 'HTTP_BOTH'?
  658 |   server->on(WM_G(R_updatedone), HTTP_POST, std::bind(&WiFiManager::handleUpdateDone, this), std::bind(&WiFiManager::handleUpdating, this));
      |                                  ^~~~~~~~~
      |                                  HTTP_BOTH
c:\Users\Emugwaneza\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp: In member function 'void WiFiManager::handleWifiSave()':
c:\Users\Emugwaneza\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp:1808:55: error: 'HTTP_GET' was not declared in this scope; did you mean 'HTTP_ITEM'?
 1808 |   DEBUG_WM(DEBUG_DEV,F("Method:"),server->method() == HTTP_GET  ? (String)FPSTR(S_GET) : (String)FPSTR(S_POST));
      |                                                       ^~~~~~~~
      |                                                       HTTP_ITEM
c:\Users\Emugwaneza\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp: In member function 'void WiFiManager::handleParamSave()':
c:\Users\Emugwaneza\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp:1899:55: error: 'HTTP_GET' was not declared in this scope; did you mean 'HTTP_ITEM'?
 1899 |   DEBUG_WM(DEBUG_DEV,F("Method:"),server->method() == HTTP_GET  ? (String)FPSTR(S_GET) : (String)FPSTR(S_POST));
      |                                                       ^~~~~~~~
      |                                                       HTTP_ITEM
c:\Users\Emugwaneza\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp: In member function 'void WiFiManager::handleNotFound()':
c:\Users\Emugwaneza\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp:2392:36: error: 'HTTP_GET' was not declared in this scope; did you mean 'HTTP_ITEM'?
 2392 |   message += ( server->method() == HTTP_GET ) ? FPSTR(S_GET) : FPSTR(S_POST);
      |                                    ^~~~~~~~
      |                                    HTTP_ITEM

exit status 1

Compilation error: exit status 1
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lucasssvaz** [comment]
@Nezaemmy The 3.0.0 version has many breaking changes in the API. Libraries that interface directly with it will need to be changed to accommodate this. Note that 3.0.0 is not released yet in library developers might take some time to change them still.

You can check the 2.x to 3.x migration guide [here](https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html)

**Comment by Nezaemmy** [comment]
> @Nezaemmy The 3.0.0 version has many breaking changes in the API. Libraries that interface directly with it will need to be changed to accommodate this. Note that 3.0.0 is not released yet so library developers might take some time to change them.
> 
> You can check the 2.x to 3.x migration guide [here](https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html)

Thx @lucasssvaz

**Comment by VojtechBartoska** [comment]
closing this as answered.
