### ISSUE TITLE
LittleFS upload "Success" but file read fails.

### ISSUE THREAD

**Issue by meakashrao** [espressif/arduino-esp32#9126]
### Board

ESP32-WROOM-32E-N4 

### Device Description

The hardware is custom, but I was able to update to and fro multiple Firmware Versions with the LITTLEFS Partitions.

### Hardware Configuration

NA

### Version

latest master (checkout manually)

### IDE Name

Platform IO

### Operating System

Windows 11

### Flash frequency

40Mhz

### PSRAM enabled

yes

### Upload speed

460800

### Description

1) Platform IO Serial Update
a) When I use Platform IO Core 6.1.13 and Home 3.4.4 with Espressif 32 v6.4.0, and upload firmware.bin file using the upload button and littlefs.bin using the upload FileSystem Image, my ESP is able to read the LITTLEFS file. 
b) When I upload using the OTA method by making the ESP go into Access Point Mode and use the files espota.py and esptool.py although both files are updated successfully my LittleFS read fails(mount doesn't but file read fails)
I tried to format the LITTLEFS partion using the function "LittleFS.format()" and it returns successful and uploaded the LITTLEFS.bin again and it still resulted in File not present and File read failed. 
c) Then if I take the ESP, erase the flash contents, and repeat step 'a' things work again. 

I am attaching a zip file with my files. 
[ESP_OTA_LITTLEFS_Details.zip](https://github.com/espressif/arduino-esp32/files/13964313/ESP_OTA_LITTLEFS_Details.zip)

I have multiple sections where I send the Error Message using BLE a
The Error Messages are 
a)  it says _"LITLFS-FileReadFail"_ in the function 
void readFile(fs::FS &fs, const char * path), which basically just reads and serial prints contents of the 2 files in the data folder in Platform IO
b) Files not found
c) Reading fails again. 

OTA upload Screenshots 
Firmware File 
<img width="773" alt="image" src="https://github.com/espressif/arduino-esp32/assets/120377875/26022d97-975a-4afb-91c9-7776ad94589b">

SPIFFS Image:
<img width="771" alt="image" src="https://github.com/espressif/arduino-esp32/assets/120377875/bdb8c72a-6855-43d7-8a90-4b333f449eb2">

Starting of the espota.py file
<img width="960" alt="image" src="https://github.com/espressif/arduino-esp32/assets/120377875/5fe67d2c-b5b7-4c49-8e34-72410d1ec80a">

The whole espota.py and esptool.py are there in the zip

### Sketch

```cpp
I am attaching the LITTLEFS_Config.cpp here (it's included in the ZIP above as well)

#include "Arduino.h"
#include "main.h"
#include "LittleFS.h"  
#include "LITTLEFS_Config.h"
#include "Rotary_Encoder.h"
#include "Weight_Handler.h"
#include "FS.h"

// Function declarations
void checkLITTLEFSContent();              // Initializes LittleFS and reads the contents of the file
void readRGBPins(String line, String key);
void readHX711(String line, String key);
void readRGBArray(String line, String key);
void readQTempTrigger(String line, String key);
void parseIntArray(String valueStr, int* array, int arraySize);
void printArray(const int* array, int arraySize);
void listDir(fs::FS &fs, const char * dirname, uint8_t levels);
void readFile(fs::FS &fs, const char * path);
void readConfigFile(fs::FS &fs, const char * path);

void checkLITTLEFSContent()
{
    Serial.println("Mounting LittleFS...");
    if (!LittleFS.begin(true))
    {
        Serial.println("An Error has occurred while mounting LittleFS");
        //TODO: Error Handling
        errorType = 2;
        addErrorMessage("MountingLITLFSError");
        return;
    }

    listDir(LittleFS, "/", 0);

    String configFile = (machineVersion == "BB1") ? "/BB1_config.txt" : "/BB2_config.txt";

    readFile(LittleFS, configFile.c_str()); // Use c_str() to convert String to const char*
    readConfigFile(LittleFS, configFile.c_str());
}

void readFile(fs::FS &fs, const char * path)
{
  Serial.printf("Reading file: %s\r\n", path);

  File file = fs.open(path);
  if(!file || file.isDirectory())
  {
    Serial.println("- failed to open file for reading");
    addErrorMessage("LITLFS-FileReadFail");
    return;
  }

  Serial.println("File Content:");
  while(file.available())
  {
    Serial.write(file.read());
  }
  file.close();
}

// Function to list the contents of a directory
void listDir(fs::FS &fs, const char * dirname, uint8_t levels) 
{
    Serial.printf("Listing directory: %s\n", dirname);

    File root = fs.open(dirname);
    if (!root) 
    {
        Serial.println("- failed to open directory");
        //TODO: Error Handling
        errorType = 4;  
        addErrorMessage("Directory-openfaile");
        return;
    }
    if (!root.isDirectory()) 
    {
        Serial.println(" - not a directory");
        //TODO: Error Handling
        errorType = 5;  
        addErrorMessage("Not-a-directory----");
        return;
    }

    const char* fileNames[] = {"BB1_config.txt", "BB2_config.txt"};         // Define the file names to check in the directory
    bool foundFiles[] = {false, false};                                     // Corresponds to the files in fileNames
    int numberOfFiles = sizeof(fileNames) / sizeof(char*);

    File file = root.openNextFile();
    while (file) 
    {
        Serial.print(file.isDirectory() ? "  DIR : " : "  FILE: ");
        Serial.println(file.name());
        Serial.print(file.size());                              // Print the size of the file
        Serial.println(" bytes");

        for (int i = 0; i < numberOfFiles; i++) 
        {
            if (String(file.name()).endsWith(fileNames[i]))     // Check if the file name ends with the desired file name
            { 
                Serial.printf("Found: %s\n", file.name());
                foundFiles[i] = true; // Mark as found
            }
        }
        if (file.isDirectory() && levels) 
        {
            listDir(fs, file.name(), levels - 1);               // Recursively list subdirectories
        }
        file = root.openNextFile();
    }
    // Check which files were not found and print the messages after listing
    if (foundFiles[0] == false) 
    {
        Serial.printf("Not found: %s\n", fileNames[0]);
        //TODO: Error Handling
        errorType = 6;      
        addErrorMessage("BB1-config-notfound");                            
    }
    if (foundFiles[1] == false) 
    {
        Serial.printf("Not found: %s\n", fileNames[1]);
        //TODO: Error Handling
        errorType = 7;   
        addErrorMessage("BB2-config-notfound");                               
    }
}

void readRGBPins(String line, String key) 
{
    if (key.equalsIgnoreCase("RedLed") || key.equalsIgnoreCase("GreenLed")) {
        int pin = line.toInt();
        // Assign the pin to the respective LED
        if(key.equalsIgnoreCase("RedLed")) redPin = pin;
        if(key.equalsIgnoreCase("GreenLed")) greenPin = pin;
    }
}

void readHX711(String line, String key) 
{
    if (key.equalsIgnoreCase("HX711_DOUT")) 
	{
        actual_dout_pin = line.toInt(); 
    }
}

void readQTempTrigger(String line, String key) 
{
    if (key.equalsIgnoreCase("qTempTrigger")) 
	{
        qTempTrigger = line.toFloat();
    }
}

void readRGBArray(String line, String key) 
{
    if (key.equalsIgnoreCase("GreenRGB")) 
    {
        parseIntArray(line, greenRGB, 3);
    } 
    else if (key.equalsIgnoreCase("OrangeRGB")) 
    {
        parseIntArray(line, orangeRGB, 3);
    } 
    else if (key.equalsIgnoreCase("RedRGB")) 
    {
        parseIntArray(line, redRGB, 3);
    }
    else
    {

    }
}

void readConfigFile(fs::FS &fs, const char * path) 
{
    Serial.printf("Reading file: %s\n", path);

    File file = fs.open(path);
    if (!file || file.isDirectory()) 
    {
        Serial.println("- failed to open file for reading");
        //TODO: Error Handling
        errorType = 3;
        addErrorMessage("LITLFS2FileReadFail");
        return;
    }
    while (file.available()) 
    {
        String line = file.readStringUntil('\n');   // Read a line of text up to the newline character.
        line.trim();                                // Remove any leading or trailing whitespace from the line.
        int equalSignIndex = line.indexOf('=');     // Find the position of the equal sign, which separates the key from the value.
        if (equalSignIndex != -1)                   // If there is an equal sign, then it's a line with a setting to process.
        {                 
            String key = line.substring(0, equalSignIndex);     // Extract the key (the part of the line before the equal sign).
            key.trim();                                         // Remove any whitespace around the key.
            String valueStr = line.substring(equalSignIndex + 1);   // Extract the value (the part of the line after the equal sign).
            valueStr.trim();                                    // Remove any whitespace around the value.
            // Call the appropriate function to handle the setting based on the key.
            // These functions will parse the value string and set the corresponding configuration variables.
            readRGBPins(valueStr, key);
            readHX711(valueStr, key);
            //readQTempTrigger(valueStr, key);
            readRGBArray(valueStr, key);
        }
    }
    file.close();  // After reading all the settings, close the file.
}

/*
General function to parse a comma-separated list of "integers" from a String and store them into an array.
valueStr: The string containing the comma-separated values.
array: The integer array to store the parsed values.
arraySize: The size of the array to know how many elements to expect.

The current parseIntArray assumes that there are commas separating values. 
If there's any deviation in the file format (like spaces or other characters), it won't parse correctly.
*/
void parseIntArray(String valueStr, int* array, int arraySize) 
{
  int startIndex = 0;                    // Keeps track of the starting index of each number in the comma-separated list
  int commaIndex = 0;                    // Used to store the index of the found comma
  for (int i = 0; i < arraySize; i++)    // Loop through the expected number of elements in the array
  {
    commaIndex = valueStr.indexOf(',', startIndex);     // Find the next comma in the string starting from startIndex
    if (commaIndex == -1)                               // If no comma is found, this must be the last value, so set commaIndex to the end of the string
    {
      commaIndex = valueStr.length();
    }
    String numberStr = valueStr.substring(startIndex, commaIndex);      // Extract the substring representing the current number
    array[i] = numberStr.toInt();                                       // Convert the substring to an integer and store it in the array
    startIndex = commaIndex + 1;                                        // Set the starting index for the next number to be right after the current comma
  }
}

void printArray(const int* array, int arraySize) 
{
  Serial.print("[");
  for (int i = 0; i < arraySize; i++) 
  {
    Serial.print(array[i]);
    if (i < arraySize - 1) 
    {
      Serial.print(", ");
    }
  }
  Serial.println("]");
}

bool formatLittleFS()
{
    bool ret = LittleFS.format();
    return ret;
}
```

### Debug Message

```plain
NA.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by meakashrao** [comment]
Please help to decode the issue. Why does it works when I upload serially and why not with OTA 

My flatformio.ini file 
<img width="396" alt="image" src="https://github.com/espressif/arduino-esp32/assets/120377875/54a09a2f-6472-4f70-a128-c01945b51e48">

**Comment by Jason2866** [comment]
Since there are changes in LittleFS version it is mandatory to know which core version you use. You don't use latest master, that is sure. Since no version is pinned in Platformio setup we don't know at all. So please change in your Platformio.ini  `platform = espressif32` to `platform = espressif32 @ 6.5.0` to use released core 2.0.14.

Do you still have the same behaviour with this setup?

**Comment by meakashrao** [comment]
> Since there are changes in LittleFS version it is mandatory to know which core version you use. You don't use latest master, that is sure. Since no version is pinned in Platformio setup we don't know at all. So please change in your Platformio.ini `platform = espressif32` to `platform = espressif32 @ 6.5.0` to use released core 2.0.14.
> 
> Do you still have the same behaviour with this setup?

I am using 6.4.0, I tried using 6.5.0 but that has some issue with the WiFi and Serial Port, so I am forced to stick to 6.4.0
This is what I get while compiling the properly working code on 6.5.0
<img width="544" alt="image" src="https://github.com/espressif/arduino-esp32/assets/120377875/5667a63f-6d87-4f6b-ab1d-f268a521fd59">

**Comment by meakashrao** [comment]
> Are you using in both cases the fs.img generated from Platformio? If yes, either the upload fails "somehow" -> the fs.img is loaded at a wrong address and/or the content got corrupted. To know what happened download the complete flash content with esptool.py First the working serial version. Upload via OTA. Dump this version. Compare both versions with a hex viewer to see where the differences are.

Thank you for this suggestion.
I found the below article to read the flash contents. 
<img width="544" alt="image" src="https://github.com/espressif/arduino-esp32/assets/120377875/106d7d7a-cce7-426c-b39d-f55f904021a8">

Do you have any suggestions for what hex viewer to use? Also, this gives me .bin file, am I on the right track with this?

**Comment by meakashrao** [comment]
> Are you using in both cases the fs.img generated from Platformio? If yes, either the upload fails "somehow" -> the fs.img is loaded at a wrong address and/or the content got corrupted. To know what happened download the complete flash content with esptool.py First the working serial version. Upload via OTA. Dump this version. Compare both versions with a hex viewer to see where the differences are.

Yes, I am using the same littlefs.bin file for Serial and OTA update.

I found this command to read the contents of the flash in a .bin extension
https://docs.espressif.com/projects/esptool/en/latest/esp32s3/esptool/basic-commands.html#read-flash-contents-read-flash

Am i right here? and do you have any recommendations for hex viewer?

Thanks for replying to my queries

**Comment by meakashrao** [comment]
Also, is there any way to correct set the offset according to my min_spiffs.csv partition table during OTA using the command 
python .\espota.py -d -i 192.168.1.1 -p 3232 --auth=admin -f .\littlefs.bin -s

**Comment by Jason2866** [comment]
Yes, correct for reading flash. Before changed to Mac used this one with Windows http://www.winhex.com/winhex/index-d.html

**Comment by meakashrao** [comment]
Hello @Jason2866 

Should I be using "extra_scripts = ./littlefsbuilder.py" and the appropriate file as in this image 
<img width="411" alt="image" src="https://github.com/espressif/arduino-esp32/assets/120377875/296d7df5-d22a-491a-9449-464733085755">

or the line board_build.filesystem = littlefs in my .ini file does the job?

**Comment by meakashrao** [comment]
> Are you using in both cases the fs.img generated from Platformio? If yes, either the upload fails "somehow" -> the fs.img is loaded at a wrong address and/or the content got corrupted. To know what happened download the complete flash content with esptool.py First the working serial version. Upload via OTA. Dump this version. Compare both versions with a hex viewer to see where the differences are.

So, I checked the bin files
First I took a machine on Which SPIFFS was never used then did OTA and read the flash.bin files 
Then uploaded it with serial and read the flash.bin files
Both have been written to the same location

With OTA there were multiple troubles
a) after updating the firmware.bin
![image](https://github.com/espressif/arduino-esp32/assets/120377875/d7b65a97-eded-4dc8-b263-b1508addba47)
This got solved after a Power ON OFF()spiffs mounted successfully)

b) after updating littefs.bin
![image](https://github.com/espressif/arduino-esp32/assets/120377875/77486f2b-b965-4acf-beda-83b1b2c601fe)

but the same machine after serial update works properly.

**Comment by meakashrao** [comment]
As suggested I have check the flash contents 

I have attached a zip folder which contains 
1) ota_flash-machine2_dump.bin -> Bin file read from flash after OTA update of both firmware and littlefs files
2) serial_flash-machine2_dump.bin -> Bin file read from flash after serial flashing of both firmware and littlefs files
3) Serial and OTA update.docx -> this contains all screenshots of Serial terminal and the screenshots of above bin files
4) firmware.bin -> This is the actual firmware.bin being used for OTA and serial update
5) littlefs.bin -> This is the actual firmware.bin being used for OTA and serial update
6) LITTLEFS_Config.cpp -> This is my LittleFS config file
7) platformio_ini -> PlatformIO configuration File
8) espota.py -> file that I am using
9) esptool.py -> file that I am using 

Please if someone can find time to help me with what the issue is with my code.  

[LittleFs_Debug.zip](https://github.com/espressif/arduino-esp32/files/13974216/LittleFs_Debug.zip)

**Comment by Jason2866** [comment]
The entry "extra_scripts = ./littlefsbuilder.py" is not needed anymore with actual espressif32 Platformio Platform. This part selects "mklittlefs" to use as App to build the fs img.
https://github.com/platformio/platform-espressif32/blob/develop/builder/main.py#L264-L281
This part is working correctly since flashing via VSC results in working firmware and accessible files from Filesystem.
So "something" bad happens via the OTA update of the FS. When doing this the flash content of the used flash differs from the one via wired flash. Can't help here any further since not using `espota.py`

**Comment by meakashrao** [comment]
> The entry "extra_scripts = ./littlefsbuilder.py" is not needed anymore with actual espressif32 Platformio Platform. This part selects "mklittlefs" to use as App to build the fs img. https://github.com/platformio/platform-espressif32/blob/develop/builder/main.py#L264-L281 This part is working correctly since flashing via VSC results in working firmware and accessible files from Filesystem. So "something" bad happens via the OTA update of the FS. When doing this the flash content of the used flash differs from the one via wired flash. Can't help here any further since not using `espota.py`

Thank you so much for the insights. I hope someone else picks up and helps me

**Comment by Jason2866** [comment]
I think it is not an Platformio issue. The used `espota.py` is the one provided from the framework in folder "tools". 
@me-no-dev Has it been tested lately if uploading a LittleFS image via `espota.py` is working? Flashing the same LittleFS image via esptool.py (wired) does work.

**Comment by meakashrao** [comment]
Hello Team, any update on this?

**Comment by Jason2866** [comment]
@meakashrao Great you find the reason. "Nice" trap.
