### ISSUE TITLE
ledcAttach is undefined 

### ISSUE THREAD

**Issue by patrickwasp** [espressif/arduino-esp32#9169]
### Board

ESP32S3

### Device Description

[Seeed Studio XIAO ESP32S3](https://www.seeedstudio.com/XIAO-ESP32S3-p-5627.html), attached to nothing

PLATFORM: Espressif 32 (2023.11.1) > Seeed Studio XIAO ESP32S3

### Hardware Configuration

nothing connected 

### Version

other

### IDE Name

PlatformIO

### Operating System

Ubuntu

### Flash frequency

40

### PSRAM enabled

yes

### Upload speed

115200

### Description

'ledcAttachChannel' was not declared in this scope

https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/ledc.html

### Sketch

```cpp
void setup() {
  ledcAttach(LED_BUILTIN, 2000, 12);
}

void loop(){}
```

### Debug Message

```plain
/tmp/arduino_modified_sketch_36424/ledcFrequency.ino: In function 'void setup()':
ledcFrequency:2:3: error: 'ledcAttach' was not declared in this scope
   ledcAttach(LED_BUILTIN, 2000, 12);
   ^~~~~~~~~~
/tmp/arduino_modified_sketch_36424/ledcFrequency.ino:2:3: note: suggested alternative: 'ledcAttachPin'
   ledcAttach(LED_BUILTIN, 2000, 12);
   ^~~~~~~~~~
   ledcAttachPin
exit status 1
'ledcAttach' was not declared in this scope
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
The API has changed.  ledcAttachPin was v2.x.  ledcAttach is v3.0
The compiler is telling you the exactly correct answer.

**Comment by P-R-O-C-H-Y** [comment]
For more details please take a look on [MIGRATION GUIDE FROM 2.X TO 3.X](https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html).

**Comment by nsmith1024** [comment]
Hello, was this fixed? it is still not defined.

**Comment by me-no-dev** [comment]
@nsmith1024 API has changed, this will never be "fixed" you need to use the new API
