### ISSUE TITLE
TWAI V2 update is Arduino IDE

### ISSUE THREAD

**Issue by MatheusCaltran** [espressif/arduino-esp32#9193]
### Related area

Update to TWAI

### Hardware specification

ESP32

### Is your feature request related to a problem?

I can't get Multiple TWAI Instances to work on Arduino IDE. 

### Describe the solution you'd like

You need espressif's 5.2 toolchain or newer since that has the twai v2 update

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
Arduino based on IDF 5.3 is coming later this year. Next in line is 5.1 to be relased

**Comment by MatheusCaltran** [comment]
Do you have any predictions on the arrival of 5.1 and 5.2?

**Comment by me-no-dev** [comment]
5.1 is in alpha and soon to be in RC. 5.3 have not yet started on.
