### ISSUE TITLE
Port i2s light sleep peripheral bus disconnect to **legacy** i2s driver

### ISSUE THREAD

**Issue by zackees** [espressif/arduino-esp32#9199]
### Board

Port i2s light sleep fix to legacy i2s driver

This references `https://github.com/espressif/arduino-esp32/issues/8207`, which was the fix for the new i2s driver.

### Device Description

Xaio ESP32C3 

### Hardware Configuration

See pin configuration in: https://github.com/espressif/arduino-esp32/issues/8207

### Version

latest master (checkout manually)

### IDE Name

CLI

### Operating System

Windows 10

### Flash frequency

40mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

https://github.com/espressif/arduino-esp32/issues/8207

### Sketch

```cpp
See:

https://github.com/espressif/arduino-esp32/issues/8207
```

### Debug Message

```plain
See:

https://github.com/espressif/arduino-esp32/issues/8207
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
if you reference another issue, then this one is not needed.
