### ISSUE TITLE
ledcFade can lead to dead-lock on ESP32-classic

### ISSUE THREAD

**Issue by TD-er** [espressif/arduino-esp32#9212]
### Board

ESP32 (classic)

### Device Description

ESP32-classic

### Hardware Configuration

Nothing attached to the board

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Windows 11

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

Several calls to `ledcAttach` followed by `ledcFade` on the same pin without calling `ledcDetach` for that pin will lead to a completely frozen system on ESP32.

N.B. the same code on ESP32-C2 does not show this behavior. Not tested on other ESP32-variants.

Since there doesn't seem to be a simple check to see if a pin is already attached, I added a simple `ledcWrite` check first to set the start duty cycle for the upcoming fade.
If this returns false, I run `ledcAttach` on that pin.

So either of these 2 variants do work:

```c++
    if (!ledcWrite(gpio, start_duty)) {
      // Pin not yet attached
      if (!ledcAttach(gpio, frequency, resolution)) {
        return false;
      }
    }

    if (!ledcFade(gpio, start_duty, target_duty, fadeDuration_ms)) {
      return false;
    }
```

```c++
    ledcDetach(gpio);
    if (!ledcAttach(gpio, frequency, resolution)) {
      return false;
    }

    if (!ledcFade(gpio, start_duty, target_duty, fadeDuration_ms)) {
      return false;
    }
```

### Sketch

```cpp
// Not working code
while (true) {
    if (ledcAttach(gpio, frequency, resolution)) {
      ledcFade(gpio, start_duty, target_duty, fadeDuration_ms);
    }
    delay(2*fadeDuration_ms);
}
```

### Debug Message

```plain
Node just freezes after a few calls
Probably due to the semaphore code in ledcFadeConfig
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@TD-er - based on the fact that you are using the C2 to test it, I guess that this is about Arduino Core 3.0.0-Alpha2.
Is it correct?

@P-R-O-C-H-Y  - Please take a look. It may be related to this change: https://github.com/espressif/arduino-esp32/pull/9031/files

**Comment by TD-er** [comment]
Yep, the latest code from Arduino and ESP-IDF.
So it might be that this is even a soon-to-be-bug in Arduino if it doesn't fail yet on your tests :)

**Comment by P-R-O-C-H-Y** [comment]
Hi @TD-er, I am now taking a look at this. Just quick question, why would you call every time the `ledcAttach()`, is that because of the pin is using for other purposes also?

**Comment by P-R-O-C-H-Y** [comment]
I have used you non-working code in testing sketch, but no issues on my side.
```
// use 12 bit precission for LEDC timer
#define LEDC_TIMER_12_BIT  12

// use 5000 Hz as a LEDC base frequency
#define LEDC_BASE_FREQ     5000

// fade LED PIN (replace with LED_BUILTIN constant for built-in LED)
#define LED_PIN            4

// define starting duty, target duty and maximum fade time
#define LEDC_START_DUTY   (0)
#define LEDC_TARGET_DUTY  (4095)
#define LEDC_FADE_TIME    (3000)

void setup() {
}

void loop() {
    if (ledcAttach(LED_PIN, LEDC_BASE_FREQ, LEDC_TIMER_12_BIT)) {
      ledcFade(LED_PIN, LEDC_START_DUTY, LEDC_TARGET_DUTY, LEDC_FADE_TIME);
    }
    delay(2*LEDC_FADE_TIME);
}
```

**Comment by TD-er** [comment]
> Hi @TD-er, I am now taking a look at this. Just quick question, why would you call every time the `ledcAttach()`, is that because of the pin is using for other purposes also?

The actual use case is about letting a LED fade from one state to another state and then back again.
And since it is done via commands from rules in my application, the command just doesn't make any assumptions of the pin state and starts the fade process. (not sure if that's the best approach, but that was how it was done)
