### ISSUE TITLE
Flash Encryption on Arduino IDE

### ISSUE THREAD

**Issue by sboicu** [espressif/arduino-esp32#9233]
### Related area

esp32 dev

### Hardware specification

esp32 dev

### Is your feature request related to a problem?

no

### Describe the solution you'd like

I guess there are a lot of person out there who just wait for the Arduino IDE Flash Encryption feature, not going thru work around.
When is it going to be possible? 

### Describe alternatives you've considered

i read all forums and used previously ok encryption with encrypted bootloader, but does not work very well and some parts are just bricked after some time used.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
we will probably never provide firmware encryptions through Arduino IDE. You are welcome to use Arduino as component in IDF and use such features through there.
