### ISSUE TITLE
esp32 wroom arduino ide/ beacon

### ISSUE THREAD

**Issue by meymi19666** [espressif/arduino-esp32#9297]
### Related area

I programmed the esp32 wroom in the Arduino IDE, but it does not appear on the mobile phone except for the advertising data and the biandroid application.

### Hardware specification

esp32wroom

### Is your feature request related to a problem?

I programmed the esp32 wroom in the Arduino IDE, but it does not appear on the mobile phone except for the advertising data and the biandroid application.

### Describe the solution you'd like

Does esp32 wroom card not support beacon? If it is supported, what should I do?

### Describe alternatives you've considered

Is firmware enough?

### Additional context

![Screenshot_20240227-225926_nRF Connect](https://github.com/espressif/arduino-esp32/assets/105879370/bc7ef2ee-2efd-4401-ba5e-546844306def)
![Screenshot_20240227-225941_nRF Connect](https://github.com/espressif/arduino-esp32/assets/105879370/70b19213-d485-44ff-97e6-bfbc9bddc0dc)
android ekran görüntüsü.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by P-R-O-C-H-Y** [comment]
Hi @meymi19666, can you please post the sketch + debug output?

**Comment by meymi19666** [comment]
First of all, thank you for your reply, I was a little annoyed by the late
reply.
In the Arduino IDE, there is no error report, I cannot see the problem
devices of nRF Connect, but I cannot see the advertising broadcast.
I want to do it, I want to open the menu of the cafe, ESP32's advertising
to all mobiles in a cafe, whatever your contribution to me was, it was
enough for you to answer, parting with your work, success.
I am a bit old and have eyes on the ground, I am sorry if there is anything
missing regarding the correspondence rules in the forums.
Mehmet
attachment: beacon installed on esp32 without any problems

Jan Procházka ***@***.***>, 27 Şub 2024 Sal, 23:49 tarihinde
şunu yazdı:

**Comment by P-R-O-C-H-Y** [comment]
Hello, as it seems that there is no bug in the code on our side, probably you have some issue in your sketch. I can't tell much more without having more informations about your code and logs. So I am closing this issue.
Feel free to ask on our [Gitter channel](https://gitter.im/espressif/arduino-esp32), where you can get help from the community and maybe someone was facing the same problem as you in the past and can share some tips.

**Comment by meymi19666** [comment]
I looked at the translation of the message I wrote to you, the words were
written wrong, I'm sorry. I am grateful for your answers and contributions.
Thank you very much. Good luck to all my friends. Best regards.
Mehmet

Jan Procházka ***@***.***>, 29 Şub 2024 Per, 16:00 tarihinde
şunu yazdı:
