### ISSUE TITLE
Add option to compiler.cpp.flags

### ISSUE THREAD

**Issue by sorscode** [espressif/arduino-esp32#93]
Add the following option tag in the compiler.cpp.flags, located in platform.txt file.

-fno-threadsafe-statics

This will allow the ArduinoJson library to compile.

**Comment by copercini** [comment]
Same issue here

**Comment by me-no-dev** [comment]
Maybe the author of the library should come along and look at the issue. We are running in a multithreaded multicore environment and there is a reason for some errors to show. Would not like to just dismiss them like that ;)
We are rewriting all Arduino libs to be thread-safe, so maybe others should do the same ;)

**Comment by igrr** [comment]
Ah, this is because static initialization guards are not implemented. I'll should get this done.

**Comment by me-no-dev** [comment]
seems to be fine now :) closing this
