### ISSUE TITLE
Instant crash with BLE-MIDI examples with 3.0.0.alpha3

### ISSUE THREAD

**Issue by metaview** [espressif/arduino-esp32#9308]
### Board

ESP32-S3 Dev Board

### Device Description

This board: https://www.amazon.de/dp/B0CQNB74R9?psc=1&ref=ppx_yo2ov_dt_b_product_details

### Hardware Configuration

Nothing connected, just the computer on USB

### Version

latest development Release Candidate (RC-X)

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

All BLE examples I've tried lead into a reset loop. They work fine with 2.0.11 but not with 3.0.0.alpha3 anymore.

### Sketch

```cpp
None of the Midi BLE examples worked, regardless of library I used. For instance try this with 3.0.0.alpha3 and 2.0.11 and see the difference:
MidiBle_Client from https://github.com/lathoub/Arduino-BLE-MIDI
```

### Debug Message

```plain
ELF file SHA256: c75e3ce9cd42ea34

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40377429
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x508
load:0x403c9700,len:0x4
load:0x403c9704,len:0xad0
load:0x403cc700,len:0x29d8
entry 0x403c9880
[   145][D][esp32-hal-tinyusb.c:711] tinyusb_enable_interface2(): Interface CDC enabled
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
  Model             : ESP32-S3
  Package           : 0
  Revision          : 2
  Cores             : 2
  Frequency         : 240 MHz
  Embedded Flash    : No
  Embedded PSRAM    : No
  2.4GHz WiFi       : Yes
  Classic BT        : No
  BT Low Energy     : Yes
  IEEE 802.15.4     : No
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
please show a log with the reboot loop and [decode any backtrace](https://github.com/me-no-dev/EspExceptionDecoder)

**Comment by metaview** [comment]
Now, for making things easier, I used the BLE Client example from Espressif:
Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha3\libraries\BLE\examples\Client
I set "Core debug level" to debug and put it on my ESP32S3 device and got the output below. The Exception Decoder just says:


>PC: 0x40057067
>EXCVADDR: 0x00000000
>
>Decoding stack results

Log output:

ELF file SHA256: 6ce855741ef63b4d

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x9 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40376949
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x508
load:0x403c9700,len:0x4
load:0x403c9704,len:0xad0
load:0x403cc700,len:0x29d8
entry 0x403c9880
[   200][D][esp32-hal-tinyusb.c:711] tinyusb_enable_interface2(): Interface CDC enabled
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
  Model             : ESP32-S3
  Package           : 0
  Revision          : 2
  Cores             : 2
  Frequency         : 240 MHz
  Embedded Flash    : No
  Embedded PSRAM    : No
  2.4GHz WiFi       : Yes
  Classic BT        : No
  BT Low Energy     : Yes
  IEEE 802.15.4     : No
------------------------------------------
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   361468 B ( 353.0 KB)
  Free Bytes        :   326496 B ( 318.8 KB)
  Allocated Bytes   :    29876 B (  29.2 KB)
  Minimum Free Bytes:   321448 B ( 313.9 KB)
  Largest Free Block:   294900 B ( 288.0 KB)
------------------------------------------
Flash Info:
------------------------------------------
  Chip Size         : 16777216 B (16 MB)
  Block Size        :    65536 B (  64.0 KB)
  Sector Size       :     4096 B (   4.0 KB)
  Page Size         :      256 B (   0.2 KB)
  Bus Speed         : 80 MHz
  Bus Mode          : QIO
------------------------------------------
Partitions Info:
------------------------------------------
                nvs : addr: 0x00009000, size:    20.0 KB, type: DATA, subtype: NVS
            otadata : addr: 0x0000E000, size:     8.0 KB, type: DATA, subtype: OTA
               app0 : addr: 0x00010000, size:  1280.0 KB, type:  APP, subtype: OTA_0
               app1 : addr: 0x00150000, size:  1280.0 KB, type:  APP, subtype: OTA_1
             spiffs : addr: 0x00290000, size:  1408.0 KB, type: DATA, subtype: SPIFFS
           coredump : addr: 0x003F0000, size:    64.0 KB, type: DATA, subtype: COREDUMP
------------------------------------------
Software Info:
------------------------------------------
  Compile Date/Time : Mar  1 2024 12:30:31
  Compile Host OS   : windows
  ESP-IDF Version   : v5.1.2-185-g3662303f31-dirty
  Arduino Version   : 3.0.0
------------------------------------------
Board Info:
------------------------------------------
  Arduino Board     : ESP32S3_DEV
  Arduino Variant   : esp32s3
  Arduino FQBN      : esp32:esp32:esp32s3:JTAGAdapter=default,PSRAM=disabled,FlashMode=qio,FlashSize=4M,LoopCore=1,EventsCore=1,USBMode=default,CDCOnBoot=default,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,PartitionScheme=default,CPUFreq=240,UploadSpeed=921600,DebugLevel=debug,EraseFlash=none,ZigbeeMode=default
============ Before Setup End ============
Starting Arduino BLE Client application...
[   800][D][BLEAdvertisedDevice.cpp:474] setRSSI(): - setRSSI(): rssi: -86
[   807][D][BLEAdvertisedDevice.cpp:293] parseAdvertisement(): Type: 0xff (ESP_BLE_AD_MANUFACTURER_SPECIFIC_TYPE), length: 29, data: 060001092002e8ed883c2665aca7d6be4d8b3a855b622cb12e3a47bcd8
[   824][D][BLEAdvertisedDevice.cpp:451] setManufacturerData(): - manufacturer data: 060001092002e8ed883c2665aca7d6be4d8b3a855b622cb12e3a47bcd8
BLE Advertised Device found: Name: , Address: 0f:d9:44:f3:c2:6f, manufacturer data: 060001092002e8ed883c2665aca7d6be4d8b3a855b622cb12e3a47bcd8, rssi: -86
[   847][D][BLEAdvertisedDevice.cpp:474] setRSSI(): - setRSSI(): rssi: -80
[   856][D][BLEAdvertisedDevice.cpp:293] parseAdvertisement(): Type: 0xff (ESP_BLE_AD_MANUFACTURER_SPECIFIC_TYPE), length: 29, data: 060001092002c55f10c1b984315d3092289e2bdb713f3762a9fe6fde4a
[   873][D][BLEAdvertisedDevice.cpp:451] setManufacturerData(): - manufacturer data: 060001092002c55f10c1b984315d3092289e2bdb713f3762a9fe6fde4a
BLE Advertised Device found: Name: , Address: 42:17:29:24:98:3a, manufacturer data: 060001092002c55f10c1b984315d3092289e2bdb713f3762a9fe6fde4a, rssi: -80
[   900][D][BLEAdvertisedDevice.cpp:474] setRSSI(): - setRSSI(): rssi: -43
[   907][D][BLEAdvertisedDevice.cpp:293] parseAdvertisement(): Type: 0x01 (ESP_BLE_AD_TYPE_FLAG), length: 1, data: 06
[   917][D][BLEAdvertisedDevice.cpp:293] parseAdvertisement(): Type: 0x07 (ESP_BLE_AD_TYPE_128SRV_CMPL), length: 16, data: 00c7c44ee36c51a7334be8ed5a0eb803
[   931][D][BLEAdvertisedDevice.cpp:502] setServiceUUID(): - addServiceUUID(): serviceUUID: 03b80e5a-ede8-4b33-a751-6ce34ec4c700
[   943][D][BLEAdvertisedDevice.cpp:293] parseAdvertisement(): Type: 0xff (ESP_BLE_AD_MANUFACTURER_SPECIFIC_TYPE), length: 5, data: 73696e636f
[   955][D][BLEAdvertisedDevice.cpp:451] setManufacturerData(): - manufacturer data: 73696e636f
BLE Advertised Device found: Name: , Address: 80:34:19:c0:09:bb, manufacturer data: 73696e636f, serviceUUID: 03b80e5a-ede8-4b33-a751-6ce34ec4c700, rssi: -43
=========== After Setup Start ============
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   361468 B ( 353.0 KB)
  Free Bytes        :   253996 B ( 248.0 KB)
  Allocated Bytes   :    97480 B (  95.2 KB)
  Minimum Free Bytes:   252156 B ( 246.2 KB)
  Largest Free Block:   241652 B ( 236.0 KB)
------------------------------------------
GPIO Info:
------------------------------------------
  GPIO : BUS_TYPE[bus/unit][chan]
  --------------------------------------  
    43 : UART_TX[0]
    44 : UART_RX[0]
============ After Setup End =============
Forming a connection to 80:34:19:c0:09:bb
 - Created client
[  1051][I][BLEDevice.cpp:625] addPeerDevice(): add conn_id: 0, GATT role: client
[  1064][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_REG_EVT
[  1074][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_REG_EVT
[  1114][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_CONNECT_EVT
[  1125][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_CONNECT_EVT
[  1136][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_OPEN_EVT
[  1146][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_OPEN_EVT
 - Connected to server
[  1316][I][BLEDevice.cpp:256] gapEventHandler(): ESP_GAP_BLE_AUTH_CMPL_EVT
[  1323][D][BLEClient.cpp:496] handleGAPEvent(): BLEClient ... handling GAP event!
[  1595][D][BLEClient.cpp:496] handleGAPEvent(): BLEClient ... handling GAP event!
[  2149][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... Unknown
[  2159][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... Unknown
[  2171][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2183][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2194][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2205][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2216][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2227][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2239][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2250][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2261][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2272][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2283][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2295][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2306][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2317][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_RES_EVT
[  2328][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_CMPL_EVT
[  2339][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_SEARCH_CMPL_EVT
[  2351][D][BLEDevice.cpp:150] gattClientEventHan - Found oudr serviceler(): gattClientEventHandle
r [esp_gatt_if: 3] ... ESP_GATTC_C[G M3U1E[T][BLERemoteService.cpp:196] retrieveCharacteristics(): Found a characteristic: Handle: 114, UUID: 7772e5db-3868-4112-a1a9-f2669d106bf3
[  2375][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_CFG_MTU_EVT
[  2375][D][BLERemoteCharacteristic.cpp:298] retrieveDescriptors(): Found a descriptor: Handle: 115, UUID: 00002902-0000-1000-8000-00805f9b34fb
 - Found our characteristic
[  2419][D][BLEDevice.cpp:150] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_READ_CHAR_EVT
[  2430][D][BLEClient.cpp:180] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_READ_CHAR_EVT
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x40057067  PS      : 0x00060f30  A0      : 0x8200d6f7  A1      : 0x3fca6650  
A2      : 0x3fcb0008  A3      : 0x00000000  A4      : 0x00000001  A5      : 0x3fcaab20  
A6      : 0x00000005  A7      : 0x00000020  A8      : 0x00000000  A9      : 0x00000000  
A10     : 0x00000001  A11     : 0x3fcb0478  A12     : 0x00000000  A13     : 0x3fca8780  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000014  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400556d5  LEND    : 0x400556e5  LCOUNT  : 0xfffffff9  


Backtrace: 0x40057064:0x3fca6650 |<-CORRUPTED

**Comment by me-no-dev** [comment]
@metaview please decode the exception anyways. the PC address should give a hint. We will also need a minimal example sketch to reproduce the issue.

**Comment by metaview** [comment]
The decoder doen't show any more infos. But I got the example (Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha3\libraries\BLE\examples\Client) working after removing these lines:

>    // Read the value of the characteristic.
>    if(pRemoteCharacteristic->canRead()) {
>      String value = pRemoteCharacteristic->readValue();
>      Serial.print("The characteristic value was: ");
>      Serial.println(value.c_str());
>    }

Now I can receive Midi data from my keyboard. I will work on it a bit now.
Next week I'll try the BLE Midi libraries again. If I get any more exceptions I will report again.

**Comment by lucasssvaz** [comment]
If you find anything else, please reopen this issue
