### ISSUE TITLE
Need it to support esp32-C2 core

### ISSUE THREAD

**Issue by boschLining** [espressif/arduino-esp32#9312]
### Related area

Board support

### Hardware specification

ESP32-8684

### Is your feature request related to a problem?

Now this version can not support ESP32-C2 board, do you have any solutions.

### Describe the solution you'd like

Please provide a solution to support esp32-C2 on Arduino, thanks.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by Jason2866** [comment]
See https://github.com/espressif/arduino-esp32/issues/6701

Arduino Core branch master does support esp32-c2, you have to compile the needed libs yourself or use the GH actions fragments for the c2 from the CI of the espressif Arduino lib builder https://github.com/espressif/esp32-arduino-lib-builder/actions/workflows/push.yml

**Comment by VojtechBartoska** [comment]
as mentioned above, C2 is supported version 3.0.0 but you need to build libs on your own.

There is more explanation in mentioned issue.

I am closing this ticket as duplicate.

**Comment by boschLining** [comment]
Thank you.
