### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by kov-serg** [espressif/arduino-esp32#9320]
### Board

any

### Device Description

any

### Hardware Configuration

any

### Version

v2.0.14

### IDE Name

any

### Operating System

ubuntu 22

### Flash frequency

any

### PSRAM enabled

yes

### Upload speed

115200

### Description

Code lines are overlapping page boundaries:

![](https://i.imgur.com/J6wffbF.png)

### Sketch

```cpp
// any
```

### Debug Message

```plain
// none
```

### Other Steps to Reproduce

git clone --depth=1 https://github.com/espressif/arduino-esp32.git
cd arduino-esp32/docs/
build-docs -l en -bs latex

[arduino-esp32doc-2.0.14.pdf](https://github.com/espressif/arduino-esp32/files/14469449/arduino-esp32doc-2.0.14.pdf)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
It looks weird in the [web format](https://docs.espressif.com/projects/arduino-esp32/en/latest/api/ble.html), but does not mess up the page boundaries. Seems like a latex issue.

**Comment by kov-serg** [comment]
No this problem in documentation formatting. It should be more smart or simply fix source codes to prevent formatting issues. 
![html version](https://github.com/espressif/arduino-esp32/assets/5946122/3ae77a8a-6890-48e0-9fe9-45c2590f2863)

**Comment by lucasssvaz** [comment]
There are mixed spaces and tabs in the indentation. I'll open a PR to fix it.
