### ISSUE TITLE
ESP32-S2 DAC2 Requires Load Resistor?

### ISSUE THREAD

**Issue by biomurph** [espressif/arduino-esp32#9324]
### Board

Adafruit ESP32-S2 Feather

### Device Description

na

### Hardware Configuration

Oscilloscope

### Version

v2.0.14

### IDE Name

Arduino IDE 2.3.2

### Operating System

Mac

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

DAC2 output is not 0 to 3.3V (Vdd). The lower half of the byte value (0 to 128 or so) is not registering the correct output voltage. I have the DAC1 connected to the Yellow Channel and DAC2 connected to the Pink Channel in the photo here. You can see the DAC1 trace makes a nice sawtooth /| faithfully presenting the correct voltage on the pin. DAC2 on the other hand is trying to make a sawtooth |\ but has distorted values that range from 0 to about mid range (128). I confirm that when I make DAC2 draw a sawtooth /| style it has the same Voltage value correlated to the byte value.

Why is this happening? Is this expected? Is there a preferred circuit to connect to the DAC outputs? 
I tried to search the forum, but the search is broken, at least for me.

I plan to buffer the DAC output signals with an OpAmp.

![DACs_noLoad](https://github.com/espressif/arduino-esp32/assets/6284057/b24a1fcf-8691-4a8d-9ebf-9f2bee248b4b)

### Sketch

```cpp
void setup() {
  pinMode(DAC1,OUTPUT); dacWrite(DAC1,127);
  pinMode(DAC2,OUTPUT); dacWrite(DAC2,127);

  Serial.begin(230400);
  while(!Serial){}
  delay(1000);
  Serial.println("DAC tester");
}

void loop() {

  for(uint8_t b=0; b<255; b++){
    dacWrite(DAC2,256-b);
    dacWrite(DAC1,b);
    delay(5);
  }

}
```

### Debug Message

```plain
na
```

### Other Steps to Reproduce

In order to get a better, more complete DAC2 output, I added a load resistor to GND. Here are examples of various R Load values.

`R Load = 100R`
![DACs_100R](https://github.com/espressif/arduino-esp32/assets/6284057/a804c305-6dac-40b1-b1d9-10ce7d09e9cd)

`R Load = 220R`
![DACs_220R](https://github.com/espressif/arduino-esp32/assets/6284057/7fb8c9fb-a6bc-4e25-8256-6d6698912519)

`R Load = 330R`
![DACs_330R](https://github.com/espressif/arduino-esp32/assets/6284057/4e9fd61e-0b84-4e9a-9a58-b6c406f5a5f8)

`R Load = 470R`
![DACs_470R](https://github.com/espressif/arduino-esp32/assets/6284057/5587e2d4-3715-4171-a4a9-f20f0216bd89)

You can see that the range expands with increase of R value until there is some weird foldover of the values at 470R.
In the next image, a 390R value is used and the distortion appears equally at either end of the range.

`R Load = 390R`
![DACs_390R](https://github.com/espressif/arduino-esp32/assets/6284057/9ef28237-5481-4e16-af4b-71bd3e78be21)

I first saw this distortion when I was trying to produce two sine waves at different 
frequencies using a lookup table of pre-calculated values. Here's the initial scope view with no load resistor on DAC2 (Pink Channel).
![DACs_sine_noLoad](https://github.com/espressif/arduino-esp32/assets/6284057/234a6b73-4b92-463f-9946-8af21126b180)

With a 390R load resistor connected from DAC2 to GND, The output of the sine values is better, but there is some strange clipping at the range limits.
![DACs_sine_2clip](https://github.com/espressif/arduino-esp32/assets/6284057/aaa6b893-81fe-415d-9807-bc8625cf0b4c)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
This has been dacWrite has been rewritten in 3.0.0 using the IDF hal.  Can you please test with the [development version](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html#installing-using-arduino-ide)?

**Comment by biomurph** [comment]
I installed the development version 3.0.0 alpha3 using the Arduino board manager.
I get the exact same distortion of DAC2 with no load resistor as shown in oscilloscope trace in previous post.
Now, however, the optimal R Load is 470R, and while it appears to be able to produce 0V, it still won't go all the way up to 3.3V. Here is a pic of the same code running with a 470R Load Resistor.

`470R Load with v3.0.0 alpha3 board files`
![DACs_470R_v3alpha3](https://github.com/espressif/arduino-esp32/assets/6284057/7627cca1-a113-4a8e-b639-207e0a610707)

**Comment by biomurph** [comment]
Can anyone replicate this, please?

**Comment by P-R-O-C-H-Y** [comment]
Let me test :)

**Comment by biomurph** [comment]
Thanks @P-R-O-C-H-Y 
I will take it up with the kids at Adafruit.

**Comment by biomurph** [comment]
@P-R-O-C-H-Y 
I am comenting here, because this issue thread has all of the content in regard to the problem that I found.

I acquired an ESP32-S2 Soala board, and found the same issue with DAC2. The exact same distortion of the lower half of the signal range values were distorted in the same way as my scope pictures above. The signal trace reacted the same way to the application of a load resistor.

I found the schematics of the Soala board here:
https://dl.espressif.com/dl/schematics/ESP32-S2-SAOLA-1_V1.1_schematics.pdf

It clearly shows that on the Soala GPIO-18 is used to drive the neopixel on the board. There is a 0 ohm jumper, R40, from GPIO-18 to the neopixel. GPIO-18 also has a 10K pull-up resistor, R42. I removed R40 and R42 from the Soala, and now I get the proper wave shape on DAC2. That is good, but how were you able to get a clean signal on DAC2 of your Soala board with the 10Kpullup and neopixel hanging off of it?

Further, the Adafruit Feather ESP32-S2 board uses the Espressif ESP32-S2 Mini 1 radio module.
There is nothing on the Adafruit designed circuit that is connected to DAC1 or DAC2. Here is a link to their schematic:
https://learn.adafruit.com/assets/110822
NOTE that the schematic says "ESP32-S3" but Adafruit says that the board layout between the S2 and S3 feather boards are exactly similar. Adafruit does not have any circuitry connected to the DAC1 or DAC2, however, I can measure a 10K resistance between DAC2 and 3V3. DAC1 resistance to 3V3 is in the tens of magaohms. 

It does look like the radio module ESP32-S2 Mini 1 has a 10K pullup resistor under the can. Can that be verified? Is there a schematic of the radio module?

**Comment by viric** [comment]
I was fighting with this wit the [Wemos S2Mini board](https://www.wemos.cc/en/latest/s2/s2_mini.html). It also has a 10K pullup on GPIO18 (DAC2) and I don't know why.
From old ESP8266 boards like the [D1Mini](https://www.wemos.cc/en/latest/d1/d1_mini.html), probably the original board that defined the shape and pinout for later shields, had the ESP8266 GPIO0 where today there is the ESP32S2 GPIO18.
In ESP8266 GPIO0 was used to boot the ROM for code upload if there was a 0, so the board manufacturers set there a ~10K pull up.
For board compatibility with the shields probably they added the same 10K pull-up also to the ESP32S2 boards although that pin is not the pin that decides the boot mode in ESP32S2.

**Comment by viric** [comment]
As a curiosity, I checked the Saola board schematics and there is a 10K pull up on GPIO18.
I also checked the schematics of the ESP32-S2-MINI-1 board and it also has the 10K pull-up on GPIO18. [ESP32-S2-MINI-1 Reference Design](https://www.espressif.com/sites/default/files/documentation/ESP32-S2-MINI-1_V1.1_Reference%20Design.zip)

**Comment by ColonelThirtyTwo** [comment]
I just ran into this too, again on an Adafruit ESP32-S2 feather that does not have anything except a header pin connected to the DAC2 pin GPIO18. Setting the pin to input with no pull reads 3.26v, and with the internal pulldown reads 2.48V. The DAC can get it down to ~1.5v without a load.

The ESP32-S2 Mini 1 module that it uses does show a pullup in the schematic:

<img width="706" height="525" alt="Image" src="https://github.com/user-attachments/assets/9ef56b9a-f1c3-43b6-93fe-540fcac9d731" />

And while it's labeled as NC, it being populated would explain what I'm seeing.

I guess this is more of a hardware issue though.

**Comment by viric** [comment]
I think it's a mistake in the ESP32 *reference design* so every board manufacturer follows it.
