### ISSUE TITLE
use char instead of String in SerialBT.begin()

### ISSUE THREAD

**Issue by BlackWolfDEsign** [espressif/arduino-esp32#9357]
### Related area

SerialBT.begin()

### Hardware specification

ESP32 DevKit c3

### Is your feature request related to a problem?

no

### Describe the solution you'd like

i want to use a char array instead of String because i read String is more insecure then char[]

### Additional context

I want to reduce conversion from string to char or char to string

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
how about `SerialBT.begin(String(char_array));`? And what do you mean by "insecure"?

**Comment by BlackWolfDEsign** [comment]
currently i use String().  I read String can cause memory (overflow) problems

**Comment by me-no-dev** [comment]
Sorry, never heard of the issue. Do you have any links to such info/discussion? String is the default class for handling char arrays in Arduino. It takes a bit more memory then a char array, but not much and it offers many features for that price.

**Comment by BlackWolfDEsign** [comment]
[lnk](https://forum.arduino.cc/t/difference-between-char-array-and-string/603608/10)

> It took me a while to unlearn using the String class, but thanks to some very patient experts here, I finally grok.I had no choice because I was running out of RAM in a project and it was full of Strings (note the upper-case "S"). Strings (String class) are a memory hog, but using c-strings (lower-case "s"), saved my project.

[lnk2](https://forum.arduino.cc/t/understanding-the-evil-string/427528/11)

**Comment by SuGlider** [comment]
> [lnk](https://forum.arduino.cc/t/difference-between-char-array-and-string/603608/10)
> 
> > It took me a while to unlearn using the String class, but thanks to some very patient experts here, I finally grok.I had no choice because I was running out of RAM in a project and it was full of Strings (note the upper-case "S"). Strings (String class) are a memory hog, but using c-strings (lower-case "s"), saved my project.
> 
> [lnk2](https://forum.arduino.cc/t/understanding-the-evil-string/427528/11)

I understand that using many `String` objects that change along time (or C++ sdt:: many things that "mallocs") in a MCU that has just 16KB or 32KB of SRAM may be an issue (AVR) because of memory fragmentation, in very specific use cases.

But ESP32-C3 has 400KB SRAM. The smallest memory case may be the C2 that has 272KB SRAM.
For most Arduino sketches it won't make any difference.
