### ISSUE TITLE
HWCDC & periman broken

### ISSUE THREAD

**Issue by lbernstone** [espressif/arduino-esp32#9360]
### Board

esp32-c6

### Device Description

devkitc

### Hardware Configuration

usb connected (to usb-otg)

### Version

latest master (checkout manually)

### IDE Name

Arduino

### Operating System

linux

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

usb

### Description

https://github.com/espressif/arduino-esp32/pull/9331 has issues.  Please test on a esp32-c3 or c6.  Pins do not get set properly. The pin assignments on line 249&258 are wrong, and even if pins are set properly I don't get USB-CDC starting.

### Sketch

```cpp
Any with serial output
```

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lucasssvaz** [comment]
@SuGlider PTAL

**Comment by SuGlider** [comment]
@lbernstone - Correct. I'll fix it.

**Comment by SuGlider** [comment]
> Not sure if related, but HWCDC on the ESP32-S3 is also working really bad. Not as broken as on the C3 (doesn't even show up as serial port anymore in Windows) but it does skip quite a lot of bytes sent to any connected terminal (I use it as console in ESPEasy) I used to send it per byte from a buffer to the serial port, but I noticed it is now doing quite a lot of locking, so I adapted the code to flush in chunks. Now it just flushes my chunk of data and then doesn't output anything for quite a while. Just like the `availableForWrite` is reporting 0. (have to check to be sure this is causing it)

@TD-er - please open a new issue reporting this problem with a sketch that I can use to reproduce it.
