### ISSUE TITLE
Sloeber Eclispe v4.43 with 3.0.0-alpha3

### ISSUE THREAD

**Issue by jzhvymetal** [espressif/arduino-esp32#9366]
### Board

ESP32-s3

### Device Description

DEV board

### Hardware Configuration

none

### Version

latest master (checkout manually)

### IDE Name

Sloeber

### Operating System

Windows10

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

I'm trying to get Sloeber Eclispe working with ESP32-S3 because Ardunio IDE stop showing autocomplete.    When I compile I get some unresolves errors.  Any ideas or is there howto?   This is using 3.0.0-alpha3

![image](https://github.com/espressif/arduino-esp32/assets/8966946/9ad02319-98ee-4d2e-9552-0c633657dbb3)

### Sketch

```cpp
none
```

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello, this issue is related to https://github.com/espressif/arduino-esp32/issues/9150. I am closing this ticket in favour of mentioned issue. Please follow that ticket.
