### ISSUE TITLE
Why is "IPAddress" part of the core?

### ISSUE THREAD

**Issue by timpur** [espressif/arduino-esp32#94]
I never understood why some things were pat of the core and why some were not. 

Like the IPAddress library? Shouldn't this be with the WIFI library ?

Also maybe some other libraries shouldn't be part of the core?

**Comment by me-no-dev** [comment]
WiFi, Ethernet and other network libraries use those classes so you get the same functionality regardless of which lib you use. They are there to stay :)

**Comment by timpur** [comment]
Makes sense :)
