### ISSUE TITLE
`SD.begin()` calls functions that don't acquire SPI and thus is not thread-safe

### ISSUE THREAD

**Issue by and3rson** [espressif/arduino-esp32#9438]
### Board

ESP32-S3

### Device Description

ESP32-S3-WROOM-1-N16R8

### Hardware Configuration

TFT & SD card sharing SPI bus (SPI modes 3 and 0)

### Version

v2.0.14

### IDE Name

PlatformIO

### Operating System

n/a

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

When calling `SD.begin()` from one task while drawing to TFT display from another task, visual glitches occur on display due to [sdcard_init](https://github.com/espressif/arduino-esp32/blob/7b29bac625ee63f5140a5468cbbd7368879dec16/libraries/SD/src/sd_diskio.cpp#L733) not instancing [AcquireSPI](https://github.com/espressif/arduino-esp32/blob/7b29bac625ee63f5140a5468cbbd7368879dec16/libraries/SD/src/sd_diskio.cpp#L468).

`sdcard_mount`, on the other hand, **does** acquire SPI.

Temporary workaround to still use SD card, albeit without high-level interface:

```cpp
SPI.beginTransaction(SPISettings(4000000, MSBFIRST, SPI_MODE0));
uint8_t pdrv = sdcard_init(SDCARD_CS, &SPI, 4000000);
SPI.endTransaction();
sdcard_mount(pdrv, "/sd", 5, false);
```

Same behavior is observed with `sdcard_uninit`. Suggested fix is to add `AcquireSPI lock(card`) into `sdcard_mount` and `sdcard_uninit`.

### Sketch

```cpp
n/a
```

### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by P-R-O-C-H-Y** [comment]
Hi @and3rson, I have been testing that and the only place where AcquireSPI lock is missing is in the sdcard_uninit.
I have opened a PR so you can take a look. Can you also try with that change if that solves your issue? Thanks
