### ISSUE TITLE
oneWire DS18b20 fix

### ISSUE THREAD

**Issue by stickbreaker** [espressif/arduino-esp32#951]
Is anyone using Dallas OneWire devices.  I modified the standard Arduino OneWire library maintained by @PaulStoffregen.  So far It has returned accurate values from a couple of DS18b20's sharing the same pin(17).  If anyone is interested in test it with other devices/configurations feel free.  Constructive comments/ debug reports are welcome.

[stickbreaker/OneWire](https://github.com/stickbreaker/OneWire)

Chuck.

**Comment by bbasil2012** [comment]
I just tried it.
Seems it run fine :) on my high load http server !!! 
WBR Basil.

**Comment by stickbreaker** [comment]
@bbasil2012 Great!

**Comment by CelliesProjects** [comment]
@stickbreaker Just swapped in your lib and enabled Dallas error logging in my project.
No more crc errors where before I had a crc error every 6-20 seconds.
Project uses 3 sensors max. also no problems there.

Great work!

**Comment by palomarcoder** [comment]
I tried it, and it works for me.  Thanks!

**Comment by stickbreaker** [comment]
No problems reported, I'm closing this.
