### ISSUE TITLE
Failed to allocate RSA interrupt 261

### ISSUE THREAD

**Issue by lekshith** [espressif/arduino-esp32#9512]
### Board

ESP32 -S3

### Device Description

Devkit C -1

### Hardware Configuration

IO pins are connected to motors and sensors. Connection is established using ethernet. 

### Version

other

### IDE Name

Visual studio code

### Operating System

windows 11

### Flash frequency

40 MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

I'm trying to establish MQTT broker connection from my ESP32 to publish some data. The client initialization was working perfectly fine with the esp_crt_bundle certificates until I included the data packets to be sent over the connection. It is now failing with the following error "![now](https://github.com/espressif/arduino-esp32/assets/162119147/35fafdca-e509-4fa4-b36d-7a6cc9a7fd11)1" which looks like a certificate validation error. There is enough memory available, I've made use external SPIRAM as well. Nothing else was changed in the code expect for adding some json data packets to be sent over. Please suggest any workaround for this issue.

### Sketch

```cpp
const esp_mqtt_client_config_t mqtt_cfg = {
         .broker = {
             .address.uri = "mqtts://hive.prod.epcloud.ebmpapstneo.io:8883",
             .address.port = 8883,
              .verification.crt_bundle_attach = esp_crt_bundle_attach,
            //.address.transport = MQTT_TRANSPORT_OVER_SSL,
        },
         .credentials = {
             .username = server_response->username,
            //.client_id = gateway_id,
            .authentication = {
                 // .certificate = (const char *)client_cert_pem_start,
                 // .key = (const char *)client_key_pem_start,
                 .password = server_response->password,
             },
         },
         .session.disable_clean_session = false,
     };
```

### Debug Message

```plain
E (32515) bignum: Failed to allocate RSA interrupt 26
```

### Other Steps to Reproduce

the connection was working perfect fine, authentication was being successful, but after modifying the data packet, its resulting with this error. Any idea what this error could mean? cause I can't fine any resource for this online.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Ki @lekshith . I suggest you ask this in the esp32.com forum. This issue tracker is for bugs in the Arduino core and you are using actually IDF build and APIs
