### ISSUE TITLE
ESP32 S3 serial and USB HID stall when DTR is activated a second time

### ISSUE THREAD

**Issue by ChrGri** [espressif/arduino-esp32#9582]
### Board

ESP32 S3 dev

ESP32 S3 DevKitC 1 N16R8 ESP32 S3 WROOM1 N16R8 Entwicklungsboard WiFi Bluetooth 5.0 Mesh Entwicklungsboard https://amzn.eu/d/iAX62Sv

### Device Description

esp32-s3-devkitc-1

The platformIO file can be found in the code section.

### Hardware Configuration

USBOTG connection to PC

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Win 11

### Flash frequency

-

### PSRAM enabled

no

### Upload speed

-

### Description

ESP32 S3 runs simple program that should provided USB HID gamepad and serial messages via USB OTG port. Im using the Windows inbuilt USB gamecontroller program to monitor the gamepad data and [this serial monitor app](https://sites.google.com/site/terminalbpp/) to monitor the serial messages. The serial monitor app allows to set the DTR/RTS states manually, by pressing the red marked software buttons<br>
![image](https://github.com/espressif/arduino-esp32/assets/21274895/9f16b128-b23c-4422-bba2-58f625305fca)

The first activation of DTR enables the serial output as expected. When DTR is disabled, USB HID output continiues, which is also expected. But, when DTR is activated a second time, USB HID and serial output stall, which is not as expected.

https://github.com/espressif/arduino-esp32/assets/21274895/4a82961b-29db-452e-b95e-f4d1f56a183a

Apart from that, when serial and USB HID output are activated, both will stall after a while, [see](https://github.com/espressif/arduino-esp32/issues/7554#issuecomment-2088049999).

### Sketch

```cpp
Can be found here:
https://github.com/ChrGri/DIY-Sim-Racing-FFB-Pedal/tree/develop/Validation/Joystick_Serial_test
```

### Debug Message

```plain
-
```

### Other Steps to Reproduce

1. Flash firmware
2. Open serial monitor app
3. Connect to COM port
4. Enable DTR
5. Check USB HID and serial output
6. Deactivate DTR
7. USB HID output still updating
8. Activate DTR
9. USB HID and serial output stall 

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
Is this about USB Serial Device (CDC-ACM) signals?

**Comment by SuGlider** [comment]
@ChrGri - please keep in mind that DTR and RTS signals of the USB CDC port actually control "reset" and "boot mode" signals of the ESP32-S3.

**Comment by SuGlider** [comment]
It may be putting the S3 into download mode... "freezing/halting" the S3 firmware execution...

**Comment by SuGlider** [comment]
@ChrGri - Please read this: https://github.com/espressif/arduino-esp32/issues/6762#issuecomment-1182821492

![image](https://github.com/espressif/arduino-esp32/assets/65977697/dbe8f6e4-9d70-4648-a018-b25783082f2f)

**Comment by ChrGri** [comment]
@SuGlider Thank you very much. I understood, that to enter the download mode on a regular ESP, one has to execute a specific DTR/RTS [sequence](https://electronics.stackexchange.com/questions/473443/esp32-dev-board-dtr-rts), as shown below
![image](https://github.com/espressif/arduino-esp32/assets/21274895/3d639cfd-2e20-4d2c-954a-182d35293658).

From the documentation you referenced, I understood that only the download mode flag is toggled, but the chip is never asked to reset:
![image](https://github.com/espressif/arduino-esp32/assets/21274895/b5f2dbc5-106c-46ee-a0ee-685488280495)

I think setting [enableReboot](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/usb_cdc.html) has improved the behaviour and the USB HID output is continuous independent of the DTR state. However, simultaneous USB HID and serial output are still buggy and both stall after some time.

**Comment by SuGlider** [comment]
>However, simultaneous USB HID and serial output while RTS/DTR sates beeing const. are still buggy and both stall after some time. Single output of serial data or single output of USB HID data works fine though.

I see that you are using PlatformIO. What is the Arduino Core version used with it?
If possible, could you test it with Arduino IDE using Arduino Core 3.0.0-RC1?

**Comment by ChrGri** [comment]
> > However, simultaneous USB HID and serial output while RTS/DTR sates beeing const. are still buggy and both stall after some time. Single output of serial data or single output of USB HID data works fine though.
> 
> I see that you are using PlatformIO. What is the Arduino Core version used with it? If possible, could you test it with Arduino IDE using Arduino Core 3.0.0-RC1?

I've changed the platformIO as shown below. No difference. 
![image](https://github.com/espressif/arduino-esp32/assets/21274895/1b13dc6e-a1a5-46b5-8ad9-7e9ee4dbe3a7)

You can find the sample code [here](https://github.com/ChrGri/DIY-Sim-Racing-FFB-Pedal/tree/develop/Validation/Joystick_Serial_test). I've played around with `Serial.setTxTimeoutMs(0);` and `Serial.flush();` without success. The observation is always, as soon as USB HID and serial output are activated together, the output will stall at some point.

BR
Chris

**Comment by ChrGri** [comment]
One thing which helped a lot, was adding a delay between the serial write and USB HID output command, as such
![image](https://github.com/espressif/arduino-esp32/assets/21274895/59396ecb-5b64-412a-b63e-bd026f24e1f2).

**Comment by SuGlider** [comment]
I understand that your project uses USB OTG and TinyUSB for both, HID and CDC.
The delay seems to give TinyUSB some room to run different tasks from those 2 endpoints and/or their tasks...

It may be necessary to run a deep investigation of this issue.

**Comment by ChrGri** [comment]
> I understand that your project uses USB OTG and TinyUSB for both, HID and CDC. The delay seems to give TinyUSB some room to run different tasks from those 2 endpoints and/or their tasks...
> 
> It may be necessary to run a deep investigation of this issue.

Yes, CDC and HID. Do you have an idea, why `Serial.flush()` apparently doesn't give that room too?

Is there something I can to help to find a proper fix?

BR
Chris

**Comment by SuGlider** [comment]
I'd need to analyse it better and try to understand why it could fail. 

Regarding `Serial. Flush()`, it actually just waits until all the data is sent to the USB Host.
By other hand, `delay(time_ms)`  releases the FreeRTOS Scheduler to run another task while waiting for that time to pass.

Arduino has a 1 ms time slice defined for FreeRTOS. 
`delay(5);` means waiting for 5 time slices while other tasks could be executed - maybe something related to HID... 
This is the "room" that I've mentioned about.

It is necessary to see the whole picture and try to understand the sequence of actions and possible reasons for the issue.

**Comment by ChrGri** [comment]
Just want to report that 2.0.17 behaves identical.

**Comment by ChrGri** [comment]
@SuGlider I dont want to bother you, but is there something I can do to accelerate the investigation?

**Comment by SuGlider** [comment]
There is a way to check if the S3 enters in Boot Mode by connecting another terminal application to the UART0 output and check the messages ROM will output when DTR is activated.

**Comment by ChrGri** [comment]
Thank you @SuGlider You already explained the RTS/DTR logic above. The remaining issue is, that the serial output stalls after a while, see https://github.com/espressif/arduino-esp32/issues/9582#issuecomment-2095318759

I initially thought that serial transmission only stalls, when CDC and HID output is activated, but it seams to stall when only CDC is activcated too.

**Comment by SuGlider** [comment]
Would it be possible for you to post a basic sketch with detailed explanation in order to help me to reproduce the CDC stalling?

Thanks.

**Comment by ChrGri** [comment]
> Would it be possible for you to post a basic sketch with detailed explanation in order to help me to reproduce the CDC stalling?
> 
> Thanks.

For sure. A sample script was posted here:
https://github.com/espressif/arduino-esp32/issues/9582#issuecomment-2096672910

**Comment by SuGlider** [comment]
The issue is also only with CDC, right?
I understand that it is not necessary to use HID together with CDC.

How should I reproduce the CDC issue?

**Comment by ChrGri** [comment]
> The issue is also only with CDC, right? I understand that it is not necessary to use HID together with CDC.
> 
> How should I reproduce the CDC issue?

I'll try to generate a simple code to reproduce the issue with CDC only. This will take some time though. In the meantime, I suggest looking into the sample code from above (HID + CDC) which will create the serial stall, when the delay call is removed:
![image](https://github.com/espressif/arduino-esp32/assets/21274895/6388e443-973c-44ce-8f2e-0926bf975715)

Thank you

**Comment by ChrGri** [comment]
@SuGlider Did you had a chance to look into the HID+CDC example already?

**Comment by SuGlider** [comment]
Hi @ChrGri - I just returned from vacation. This is in my list of work. Please give me a week and I'll test it.

**Comment by ChrGri** [comment]
@SuGlider any updates?

**Comment by ChrGri** [comment]
@SuGlider Anything I can do to help?

**Comment by ChrGri** [comment]
@SuGlider it's been over a month since you replied. Can you confirm the issue from [here](https://github.com/espressif/arduino-esp32/issues/9582#issuecomment-2258902207) now?

**Comment by ChrGri** [comment]
The main issue was described. The cdc+hid issue will be tracked [here](https://github.com/espressif/arduino-esp32/issues/10307).

**Comment by ChrGri** [comment]
The main issue was described. The cdc+hid issue will be tracked [here](https://github.com/espressif/arduino-esp32/issues/10307).
