### ISSUE TITLE
Update IDF to v3.0 or v3.0-rc

### ISSUE THREAD

**Issue by chegewara** [espressif/arduino-esp32#964]
@me-no-dev Hi. 
Is there any chance we can have at least new branch v3.0-rc with c++ exceptions working?

**Comment by copercini** [comment]
@me-no-dev please enable `CONFIG_MBEDTLS_HARDWARE_SHA ` again since it has fixed on IDF and requested here: https://github.com/espressif/arduino-esp32/issues/976

**Comment by lbernstone** [comment]
Please close this issue.
