### ISSUE TITLE
UNABLE TO PROGRAM MY ESP CHIP USING AN EXTERNAL PROGRAMMER

### ISSUE THREAD

**Issue by Lakshmidivija** [espressif/arduino-esp32#9647]
### Board

ESP-32 ALL KITS

### Device Description

i am using esp-32-wroom-32e ic on my pcb board. in order to code my ic i recently bought a esp-prog v1.1 . i connected all the pins exactly how they are on programmer . but when i am trying to upload the code my boot button on my programmer is not responding despite giving connections properly. 

### Hardware Configuration

i am writing uart code where rx is on gpio 28 and tx is on gpio 6

### Version

latest development Release Candidate (RC-X)

### IDE Name

arduino

### Operating System

windows 11 pro

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

921600

### Description

boot button is not working even after giving connections. i connected 3v3,gnd,tx to rx pin on ic , rx to tx pin, enable pin and io0.
i tried programming while connecting all these and also i connected only vcc , gnd,rx and tx and check same issue. also checked continuity for the boot button with multimeter . its working fine. supply is also working fine. both power led and tx pin led on esp prog are in on condition while uploading. i would like to know the solution hhow to upload code when boot button is not working 

### Sketch

```cpp
#define RXD0 28
#define TXD0 6

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
   Serial1.begin(115200, SERIAL_8N1, RXD0, TXD0);
}

void loop() {
  // put your main code here, to run repeatedly:
  if (Serial.available() > 0) {
    char incomingChar = Serial.read();
    Serial.println("Received: ");
    Serial.println(incomingChar);
  }  

}
```

### Debug Message

```plain
no
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Lakshmidivija** [comment]
i tried on different development kits also. facing same trouble . please help me

**Comment by me-no-dev** [comment]
Please show diagram on all connections between your ESP32 and the Prog

**Comment by me-no-dev** [comment]
ESP-Prog might show as two serial ports. In that case, you will need to upload to the second one (first one is JTAG).
The only connections you need is RX, TX, IO0, EN, GND and 3v3. RX and TX are the original GPIOs 1 and 3, not your custom selected ones.

**Comment by Lakshmidivija** [comment]
![Uploading 20240517_150330.jpg…]()
![Uploading 20240517_150330.jpg…]()
![Uploading 20240517_150343.jpg…]()
![Uploading 20240517_150359.jpg…]()
For now i connected to esp 32 s3 devkit and programmer is esp prog v1.1 capuf embedded where I can only program not debug 
And 
![17159387648565796527073067684672](https://github.com/espressif/arduino-esp32/assets/69615400/abc3a199-27bb-4a51-9b19-d8bd165e58ed)
Here my tx and rx pins 37 and 36 
I need to write code for uart
In my ic that is on PCB rx and tx pins are 28 and 6

**Comment by me-no-dev** [comment]
first you said ESP32-Wroom, now ESP32-S3-Wroom. Which is it? And which numbers are you saying you are using? the ones inside the module (1-40) or the ones outside (Actual GPIO names).
```
ESP-Prog | ESP32-S3
-------------------
IO0      |      IO0
EN       |       EN
RXD      |     TXD0
TXD      |     RXD0
GND      |      GND
3V3      |      3V3
