### ISSUE TITLE
SmoothBlink_ULP_Code.ino fails to compile for XIAO_ESP32C6

### ISSUE THREAD

**Issue by andrewc1** [espressif/arduino-esp32#9650]
### Board

Seeed Studio XIAO ESP32C6

### Device Description

Plain module

### Hardware Configuration

nothing but USB

### Version

latest development Release Candidate (RC-X)

### IDE Name

Arduino IDE

### Operating System

Linux 6.5.0-28-generic

### Flash frequency

can't flash

### PSRAM enabled

yes

### Upload speed

115200

### Description

1. In the Arduino IDE, select File->Examples->ESP32->DeepSleep->SmoothBlink_ULP_Code.ino.
2. Verify the sketch.
3. Receive the error:

Compilation error: esp32/ulp.h: No such file or directory

### Sketch

```cpp
#include <Arduino.h>
#include "esp32/ulp.h"

void setup() {
}

void loop() {
}
```

### Debug Message

```plain
/tmp/.arduinoIDE-unsaved2024418-69056-1dkslf.hhzho/SmoothBlink_ULP_Code/SmoothBlink_ULP_Code.ino:9:10: fatal error: esp32/ulp.h: No such file or directory
    9 | #include "esp32/ulp.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: esp32/ulp.h: No such file or directory
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment]
The Risc-v ULP from the C6 is not supoort from Arduino.
