### ISSUE TITLE
Kendi kartımın pin.h dosyasını nasıl eklerim buraya

### ISSUE THREAD

**Issue by hsyngndz85** [espressif/arduino-esp32#9652]
### Related area

Kendi kartımı. Pin h dosyasını ekletmek istiyorum

### Hardware specification

Kartımın dosyalarını nasıl eklerim buraya

### Is your feature request related to a problem?

Kartımın dosyalarını nasıl eklerim

### Describe the solution you'd like

Yeni kart dosyaları nasıl ekelerim

### Describe alternatives you've considered

Yeni kart ekleme

### Additional context

Yenı kart ekleme

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by hsyngndz85** [comment]
Ayrıca kütüphane ve pin.h dosyasında değişiklik yapınca nasıl ekleyebilirim buraya

**Comment by me-no-dev** [comment]
we support communication only in English. Please re-submit in a language that we can understand
