### ISSUE TITLE
Stopping serial monitor

### ISSUE THREAD

**Issue by eroniki** [espressif/arduino-esp32#97]
When I use the `make flash monitor` to observe the serial communication, I cannot stop the process in regular (ctrl+c) fashion. Is there a way to stop the process without unplugging the USB cable from the PC? 

I am using Ubuntu 14.04 with x64 installation.

Thanks in advance.

**Comment by me-no-dev** [comment]
mine says:
```
--- Miniterm on /dev/tty.SLAB_USBtoUART  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
```
so answer is Ctrl+]

**Comment by exocode** [comment]
Erm.. why is that not `ctrl+c` like any other program out there?

I have a European keyboard and have to press three keys (`ctrl+alt+5`) to exit which is a bit annoying.
It would be very user-friendly when new users don't have to search on the internet and can use the "traditional" 99% working `ctrl+c` approach.

**Comment by AP-Frank** [comment]
What works for me (German keyboard):

Use ``ctrl++``. Explanation: ``+`` on a keyboard with German layout is where ``]`` would be on a keyboard using the standard English/American layout.

So for all other layouts it might be worth to try ``ctrl+<key where ] would be on english keyboard>``

**Comment by bonmotwang** [comment]
ctrl+] worked on me. I am using CMAKE. Just tested it.

**Comment by arnolde** [comment]
On my German keyboard CTRL+AltGr+9 works as expected. I'd still prefer ctrl-c to work, at least optionally.

**Comment by zhivko** [comment]
CTRL+C would be super standard solultion - What is the reason not using CTRL+C? I could not know... It would be great if authors could let us know why they did not use CTRL+C? thx

**Comment by mchobby** [comment]
On **belgian Keyboard** the "]" is produced with ALTGR+]
So to exit the monitor, press CTRL+ALT+ALTGR+] to compose the needed key combination
Cheers

**Comment by lbernstone** [comment]
The reason CTRL+C is not used is because it is used to send a CTRL+C to the remote system rather than the local.

**Comment by sennert** [comment]
Macbook Pro with german keyboard: control + option + 6
