### ISSUE TITLE
Face Detection on the original ESP32 no longer works (using ESP_IDF_VERSION=5.1) but still works with (using ESP_IDF_VERSION=4.4)

### ISSUE THREAD

**Issue by Rob58329** [espressif/arduino-esp32#9711]
### Board

"ESP-WROVER-DEV” camera board, and also the “M5 ESP32CAM-PSRAM” board

### Device Description

Original boards (detailed above).

### Hardware Configuration

OV2640 camera connected.

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE v1.8.19

### Operating System

Windows 10

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

FaceDetection (TWO_STAGE=true) on ESP32-S3 works fine using github.com/espressif/arduino-esp32" v23May24 (ESP_IDF_VERSION =5.1).

HOWEVER, if using the original ESP32 it does NOT work.  Specifically you get face-detected boxes which are far too big, one box coving about 95% of the screen, when the face is only a few percent of the screen.

Note that if you use exactly the same sketch in “github.com/espressif/arduino-esp32" v16Jan23 (ESP_IDF_VERSION=4.4), FaceDetection on the original ESP32 still works fine (accurate small face-detected boxes).

### Sketch

```cpp
The standard "Examples/ESP32/Camera/CameraWebServer" wifi example.
```

### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
yes. the underlying library that does the detection has changed. Now it works very fast on ESP32-S3, but very very slow on ESP32, so we have disabled it
