### ISSUE TITLE
Broken SSL certificate - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verif y failed (_ssl.c:590)

### ISSUE THREAD

**Issue by cunninr2** [espressif/arduino-esp32#974]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							?ESP32 Dev Module?
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
get.exe script failss due to SSL certificate error

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
C:\Users\robert\Documents\Arduino\hardware\espressif\esp32\tools>get.exe
System: Windows, Info: Windows-10-10.0.15063
Platform: i686-mingw32
Downloading xtensa-esp32-elf-win32-1.22.0-75-gbaf03c2-5.2.0.zip
Traceback (most recent call last):
  File "get.py", line 139, in <module>
    get_tool(tool)
  File "get.py", line 89, in get_tool
    r = requests.get(url)
  File "site-packages\requests\api.py", line 70, in get
  File "site-packages\requests\api.py", line 56, in request
  File "site-packages\requests\sessions.py", line 488, in request
  File "site-packages\requests\sessions.py", line 609, in send
  File "site-packages\requests\adapters.py", line 497, in send
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verif
y failed (_ssl.c:590)
Failed to execute script get
```

**Comment by copercini** [comment]
Duplicated of https://github.com/espressif/arduino-esp32/issues/973 will close to concentrate this issue on https://github.com/espressif/arduino-esp32/issues/973 and keep the things organized =)
