### ISSUE TITLE
Warning: Board esp32:esp32:esp32_family doesn't define a 'build.board' preference. Auto-set to: ESP32_ESP32_FAMILY

### ISSUE THREAD

**Issue by Rob58329** [espressif/arduino-esp32#9749]
### Board

ESP32S3 Dev Module

### Device Description

Board only.

### Hardware Configuration

None.

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE v1.8.19

### Operating System

Windows10

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

On the most resent "github.com/espressif/arduino-esp32" software (eg. v2Jun24) I get the compilation warning:
`Warning: Board esp32:esp32:esp32_family doesn't define a 'build.board' preference. Auto-set to: ESP32_ESP32_FAMILY`

I do not understand this warning as the boards.txt file DOES have:
`esp32s3.build.board=ESP32S3_DEV`

Note that this Arduino IDE warning occurs as:
```
Using board 'esp32s3' from platform in folder: C:\arduino-1.8.19\hardware\esp32\esp32
Using core 'esp32' from platform in folder: C:9\arduino-1.8.19\hardware\esp32\esp32
Warning: Board esp32:esp32:esp32_family doesn't define a 'build.board' preference. Auto-set to: ESP32_ESP32_FAMILY
cmd /c if exist "C:\\Users\\xx\\Documents\\Arduino\\_ESP32_Camera_sw\\FaceDetection_v3\\partitions.csv" COPY /y "C:\\Users\\xx\\Documents\\Arduino\\_ESP32_Camera_sw\\FaceDetection_v3\\partitions.csv" "C:\\Users\\xx\\AppData\\Local\\Temp\\arduino_build_434145\\partitions.csv"
```

PS. Also note that this warning ALSO occurs when compiling on an ESP8266 board and somehow messes up the ESP8266 compiled-code, necessitating the removal of the ESP32 directory from the Arduino IDE and then the re-compilation of the ESP8266 sketch.  ( See. https://github.com/esp8266/Arduino/issues/9148 )

### Sketch

```cpp
Any sketch.
```

### Debug Message

```plain
Warning: Board esp32:esp32:esp32_family doesn't define a 'build.board' preference. Auto-set to: ESP32_ESP32_FAMILY
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
this is a warning for another board. We will fix it for release. Your board is OK
