### ISSUE TITLE
Mise à niveau 3.0.0 sur arduino ide

### ISSUE THREAD

**Issue by Pepemoko** [espressif/arduino-esp32#9751]
### Board

Arduino IDE

### Device Description

Tout ESP32

### Hardware Configuration

déclaration de GIO voir description

### Version

v3.0.0

### IDE Name

IDE Arduino

### Operating System

WINDOWS 11

### Flash frequency

240MHZ

### PSRAM enabled

no

### Upload speed

921600

### Description

gpio_set_drive_capability((gpio_num_t) 4, GPIO_DRIVE_CAP_0);// Ne fonctionne plus
esp_task_wdt_init ( WDT_TIMEOUT , true);// Ne fonctionne plus
 esp_task_wdt_add ( NULL ) ;//Ne fonctionne plus
esp_task_wdt_reset () ;//Ne fonctionne plus
LittleFS.format();// déclenche des dépassements WDT (watch doc) 
Tous fontionnaient dans la dernière version.

### Sketch

```cpp
void setup(void) {
 
  delay(1000);
  esp_task_wdt_init ( WDT_TIMEOUT , true);// active une réinit si temps dépassé / active la panique pour que l'ESP32 redémarre
  esp_task_wdt_add ( NULL ) ; //ajouter le fil de discussion actuel à la surveillance WDT
  Serial.begin(115200);
  while(!Serial);
  Serial.print(" Time OUT =)");Serial.println(CONFIG_ESP_INT_WDT);
 
   WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0);// arrête la surveilance de baisse de tension
  gpio_set_drive_capability((gpio_num_t) 4, GPIO_DRIVE_CAP_0);
  gpio_set_drive_capability((gpio_num_t) 5, GPIO_DRIVE_CAP_0);
  gpio_set_drive_capability((gpio_num_t) 13, GPIO_DRIVE_CAP_0);
  gpio_set_drive_capability((gpio_num_t) 14, GPIO_DRIVE_CAP_0);
  gpio_set_drive_capability((gpio_num_t) 15, GPIO_DRIVE_CAP_0);
  gpio_set_drive_capability((gpio_num_t) 16, GPIO_DRIVE_CAP_0);
  gpio_set_drive_capability((gpio_num_t) 17, GPIO_DRIVE_CAP_0);
  gpio_set_drive_capability((gpio_num_t) 21, GPIO_DRIVE_CAP_0);
  gpio_set_drive_capability((gpio_num_t) 22, GPIO_DRIVE_CAP_0);
 
 
  LittleFS.begin();
  Serial.println("begin");
  esp_task_wdt_reset () ;// redémarre à zéro
  LittleFS.format();
```

### Debug Message

```plain
message du watchdog
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Please use English when submitting issue reports.
