### ISSUE TITLE
Return Values of `WiFi.macAddress()` Differ in Core v3

### ISSUE THREAD

**Issue by Xylopyrographer** [espressif/arduino-esp32#9766]
### Board

ESP32 Dev Module / any

### Device Description

None

### Hardware Configuration

Nothing attached.
Configuration:
Board: "ESP32 Dev Module"
Port: "/dev/cu.usbserial-0001"
Get Board Info
CPU Frequency: "240MHz (WiFi/BT)"
Core Debug Level: "None"
Erase All Flash Before Sketch Upload: "Disabled"
Events Run On: "Core 1"
Flash Frequency: "80MHz"
Flash Mode: "QIO"
Flash Size: "4MB (32Mb)"
JTAG Adapter: "Disabled"
Arduino Runs On: "Core 1"
Partition Scheme: "Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS)"
PSRAM: "Disabled"
Upload Speed: "921600"
Programmer: "Esptool"

### Version

v3.0.0

### IDE Name

Arduino IDE 2.3.3

### Operating System

macOS 14.4.1 / Debian GNU/Linux 12

### Flash frequency

80 MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

With arduino-esp32 core v2.0.17 and earlier, `WiFi.macAddress()` always returns the proper WiFi MAC address of the chip regardless of the WiFI connect status.

With core v3.0.0, `WiFi.macAddress()` returns a valid MAC address only after a WiFi connection is made.

The core v3 version of `WiFi.macAddress()` should be reverted to behave as it does in core v2.

Running the sketch below:

Using arduino-esp32 core v2.0.17

	With no WiFi connection:
		Using String method of WiFi.macAddress(), MAC = 40:91:51:B1:30:00
		Using buffer method of WiFi.macAddress() (same as Arduino), MAC = 40:91:51:B1:30:00

	With WiFi connection:
		Using String method of WiFi.macAddress(), MAC = 40:91:51:B1:30:00
		Using buffer method of WiFi.macAddress() (same as Arduino), MAC = 40:91:51:B1:30:00
		
Using arduino-esp32 core v3.0.0

	With no WiFi connection:
		Using String method of WiFi.macAddress(), MAC = 00:00:00:00:00:00
		Using buffer method of WiFi.macAddress() (same as Arduino), MAC = 00:00:00:00:00:00
	
	With WiFi connection:
		Using String method of WiFi.macAddress(), MAC = 40:91:51:B1:30:00
		Using buffer method of WiFi.macAddress() (same as Arduino), MAC = 40:91:51:B1:30:00

### Sketch

```cpp
#include <WiFi.h>

const char* SSID = "SSID";
const char* pwd = "password";

String getWiFiMacBuf() {
	uint8_t mac[ 6 ];
    char macStr[ 18 ] = { 0 };
    WiFi.macAddress( mac );
    sprintf( macStr, "%02X:%02X:%02X:%02X:%02X:%02X", mac[ 0 ], mac[ 1 ], mac[ 2 ], mac[ 3 ], mac[ 4 ], mac[ 5 ] );
    return String( macStr );
}

void connectToWifi( const char* SSID, const char* password ) {
	WiFi.disconnect( true );
	WiFi.setSleep( false );
	WiFi.mode( WIFI_STA );
	WiFi.persistent( false );
	
	Serial.print( "Connecting to WiFi." );
	WiFi.begin( SSID, password );
	while ( WiFi.status() != WL_CONNECTED ) {
		Serial.print( "." );
		delay( 200 );
	}
	Serial.println( "\r\n  - WiFi connected." );
}

void setup() {

	Serial.begin( 115200 );
	delay( 200 );
    Serial.println();

    Serial.println( "With no WiFi connection:" );
    Serial.print( "    Using String method of WiFi.macAddress(), MAC = " ); Serial.println( WiFi.macAddress() );
	Serial.print( "    Using buffer method of WiFi.macAddress() (same as Arduino), MAC = " ); Serial.println( getWiFiMacBuf() );
    Serial.println();

	connectToWifi( SSID, pwd );

    Serial.println();
    Serial.println( "With WiFi connection:" );
    Serial.print( "    Using String method of WiFi.macAddress(), MAC = " ); Serial.println( WiFi.macAddress() );
	Serial.print( "    Using buffer method of WiFi.macAddress() (same as Arduino), MAC = " ); Serial.println( getWiFiMacBuf() );
}

void loop() {

}
```
```


### Debug Message

```plain
No debug message produced.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
`Network.macAddress()` when you have not started an interface. This will be explained in the upcoming network documentation
