### ISSUE TITLE
3.0.0: 'esp_wifi_set_mac' was not declared in this scope

### ISSUE THREAD

**Issue by AndyKoder** [espressif/arduino-esp32#9777]
### Board

ESP32-Wroom32 (ESP32 Dev Module)

### Device Description

DevKit

### Hardware Configuration

no

### Version

v3.0.0

### IDE Name

Arduino IDE

### Operating System

ubuntu linux

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

Trying to set a custom MAC (worked in 1.x 2.x)
```
/code/WiFiClientConnect_test/WiFiClientConnect_test.ino:40:5: error: 'esp_wifi_set_mac' was not declared in this scope
   40 |     esp_wifi_set_mac(WIFI_IF_STA, &CustomMac[0]);
      |     ^~~~~~~~~~~~~~~~
```

### Sketch

```cpp
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiClientConnect/WiFiClientConnect.ino

plus:


WiFi.setHostname(hostname);

uint8_t CustomMac[] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06};
esp_wifi_set_mac(WIFI_IF_STA, &CustomMac[0]);	

WiFi.begin(ssid, password);
```
```


### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
```cpp
#include "esp_wifi.h"

Network.setHostname(hostname);
WiFi.STA.begin();
uint8_t CustomMac[] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06};
esp_wifi_set_mac(WIFI_IF_STA, &CustomMac[0]);
WiFi.begin(ssid, password);
```
