### ISSUE TITLE
API to read the internal temperature sensor?

### ISSUE THREAD

**Issue by torntrousers** [espressif/arduino-esp32#98]
Is there any way to read the ESP32's internal temperature sensor from an Arduino sketch?

There's [this IDF issue](https://github.com/espressif/esp-idf/issues/146) that mentions temprature_sens_read(), and from grep'ing I see that is in the Arduino code in esp32/tools/sdk/lib/librtc.a  and /esp32/tools/sdk/lib/libesp32.a. 

How can I call that?

**Comment by me-no-dev** [comment]
if there is no header defining the method, you are on your own :)
it's probably untested, unfinished or something else
