### ISSUE TITLE
Query regarding esp-modbus. 

### ISSUE THREAD

**Issue by kabirwbt** [espressif/arduino-esp32#9854]
### Board

ESP32 Dev Module

### Device Description

Plain module

### Hardware Configuration

Nothing as of yet

### Version

v3.0.1

### IDE Name

Arduino IDE

### Operating System

 Pop!_OS 22.04 LTS

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

I wanted to ask how to use esp-modbus(https://github.com/espressif/esp-modbus) with esp32 core 3.0.1. It was earlier available under .arduino15/packages/esp32/hardware/esp32/2.0.14/tools/sdk/esp32/include/freemodbus/. There is no modbus library in the core now. 

### Sketch

```cpp
-
```

### Debug Message

```plain
-
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Since IDF 5, modbus is external module. We would need to add it again

**Comment by kabirwbt** [comment]
Thank you for your quick response.
