### ISSUE TITLE
[ArduinoOTA]: Dependency on wifi

### ISSUE THREAD

**Issue by nenadalm** [espressif/arduino-esp32#987]
Hi. It looks like OTA updates are supported only via wifi: https://github.com/espressif/arduino-esp32/blob/70d0d4648766cea047613062ed50a9ecfc9de31f/libraries/ArduinoOTA/src/ArduinoOTA.h#L83. Wouldn't it be possible to make it more generic? So that one could implement an interface which would work with a GSM module?

**Comment by lbernstone** [comment]
Updater has no dependency on wifi, and has an example using SD.  Can this issue be closed?
