### ISSUE TITLE
Preferences documentation error - getBool call definition displays getUChar.

### ISSUE THREAD

**Issue by paulgiordano** [espressif/arduino-esp32#9887]
### Board

Any

### Device Description

Any

### Hardware Configuration

n/a

### Version

latest master (checkout manually)

### IDE Name

VSCode/PlatformIO

### Operating System

Ubuntu 22.04

### Flash frequency

n/a

### PSRAM enabled

yes

### Upload speed

115200

### Description

The entry in docs/en/api/preferences.rst, getUChar should read getBool:

getBool

    Retrieve a value stored against a given key in the currently open namespace.

    uint8_t getUChar(const char* key, uint8_t defaultValue = 0);

    Except for the data type returned, behaves exactly like getChar.

### Sketch

```cpp
n/a
```

### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
https://docs.espressif.com/projects/arduino-esp32/en/latest/api/preferences.html#getbool
