### ISSUE TITLE
ppp-modem: reset pulse is too short on A7672G

### ISSUE THREAD

**Issue by tl-sl** [espressif/arduino-esp32#9907]
### Board

Custom Esp32

### Device Description

Simcom A7672G

### Hardware Configuration

not relevant

### Version

v3.0.1

### IDE Name

PlatformIO

### Operating System

Linux

### Flash frequency

40Mhz

### PSRAM enabled

no

### Upload speed

115200

### Description

Testing ppp-modem on Simcom A7672 using the SIM7600 driver. Reset pulse of 200ms does not trigger reset of the modem.

A7672 datasheet says reset pulse should be 2.5secs, and in my testing anything under 2secs fails to reset.

Looking at other datasheets the pulse time for reset varies significantly across different simcom models, perhaps this value could be made configurable? If so can make a PR for this issue.

### Sketch

```cpp
from ppp library

    perimanSetPinBusExtraType(_pin_rst, "PPP_MODEM_RST");
    digitalWrite(_pin_rst, !_pin_rst_act_low);
    delay(200);
    digitalWrite(_pin_rst, _pin_rst_act_low);
    delay(100);
```
```


### Debug Message

```plain
[103772][E][PPP.cpp:311] begin(): Failed to wait for communication
```

### Other Steps to Reproduce

any reset pulse under 2000ms will fail to reset device ending with the above debug message.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
> If so can make a PR for this issue.

Please do 😄
