### ISSUE TITLE
docs: ESP32-S is listed as no having no BLE. Only true for S2

### ISSUE THREAD

**Issue by nxxxse** [espressif/arduino-esp32#9923]
### Description

```diff
diff --git a/docs/en/boards/boards.rst b/docs/en/boards/boards.rst
index cd0b310a66a..a103123cc24 100644
--- a/docs/en/boards/boards.rst
+++ b/docs/en/boards/boards.rst
@@ -18,8 +18,10 @@ The ESP32 is divided by family:
 
 * ESP32
     * Wi-Fi and BLE
-* ESP32-S
+* ESP32-S2
     * Wi-Fi only
+* ESP32-S3
+    * Wi-Fi and BLE 5
 * ESP32-C
     * Wi-Fi and BLE 5
 * ESP32-H
```

I am sorry that I cannot open a PR. I am not comfortable with signing the CLA. Refs:

* https://media.ccc.de/v/gpn22-270-why-the-cloud-is-evil
* https://youtu.be/hNcBk6cwim8

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@nxxxse, Thanks for the report!
#9925 shall solve it.
