### ISSUE TITLE
Add support for LILYGO T3S3 Board- ESP32S3 with SX12xx lora RF module

### ISSUE THREAD

**Issue by joyel24** [espressif/arduino-esp32#9927]
### Related area

Board Support

### Hardware specification

 LILYGO T3S3

### Is your feature request related to a problem?
NO

### Additional context

The T3S3 board schematic is here :
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/schematic/T3_S3_V1.2.pdf

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by joyel24** [comment]
@Xinyuan-LilyGO @LilyGO

**Comment by joyel24** [comment]
> Hello, this is something which needs to be done by Community or board vendor.

Of course, this is why I mentioned them in the comment above 👍

**Comment by joyel24** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/issues/179#issuecomment-2196027777
It's probably coming thanks to @lewisxhe

**Comment by lyusupov** [comment]
@joyel24  

https://github.com/espressif/arduino-esp32/pull/9956

<img width="279" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/236c0f78-faff-4d77-9ba4-8f1b1de94710">

**Comment by joyel24** [comment]
@lyusupov 
Yes, I have seen it seems to be fixed but did't test it yet. I wanted to wait for the next release and test it with arduino ide to see if it works well before closing the issue..;

**Comment by lyusupov** [comment]
@joyel24 
> ... I wanted to wait for the next release ...  before closing the issue...

<img width="856" alt="image" src="https://github.com/user-attachments/assets/5cd31c41-e041-4395-abf9-7afdaec15a33">
